### ISSUE TITLE
Tooling restore flow for optional packages like IBCMerge

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#100]
Some tools like IBCMerge and TestILC are in a VSTS feed, not public. BuildTools offers the "[optional tooling restore](https://github.com/dotnet/buildtools/blob/921f7c57e9941eba0879bd83ff89df0ec684d365/src/Microsoft.DotNet.Build.Tasks/PackageFiles/OptionalTooling.targets)" flow to restore tools from these feeds, and Arcade needs an equivalent to replace it. Ideally it would work on non-Windows, too. (That side's stubbed out in BuildTools because we haven't needed it yet.) CoreFX usage: [external/test-runtime/optional.json](https://github.com/dotnet/corefx/blob/00547db7233076da50db7b4d6e1a8e7ff1710ed0/external/test-runtime/optional.json).

**Comment by markwilkie** [comment]
We should at least look into using https://securityguidance.cloudapp.net/

**Comment by dagood** [comment]
What does that give us? These are not open source tools.

**Comment by markwilkie** [comment]
Sorted as part of the bootstrapping work with standardized blob "feed" locations

**Comment by tmat** [comment]
This is how we solve it in Roslyn: The CI build has extra step in YAML definition that restores internal tools like IBCMerge: https://github.com/dotnet/roslyn/blob/master/.vsts-ci.yml#L29-L32.

**Comment by markwilkie** [comment]
Doesn't https://github.com/dotnet/arcade/blob/master/Documentation/Projects/NativeDependencies/Design.md cover this?  If not, I'd like to understand the gap better so it can be closed.

**Comment by weshaggard** [comment]
We could possibly use the native bootstrapping design to handle this but most of these tools are nuget packages that need to be plugged into specific parts of our builds. Looks like Roslyn is using a particular project to restore these set of packages and BuildTools currently does something similar where we restore a project during initialization if we pass in the credentials for the protected feed. I think we will need some basic infrastructure in arcade to handle this scenario.

**Comment by ericstj** [comment]
@dagood  let me know how to map from that GUID back to a feed in VSO.

Follow this link https://devdiv.visualstudio.com/DevDiv/_packaging?_a=feed&feed=8f470c7e-ac49-4afe-a6ee-cf784e438b93

Then click "connect to feed" and you can get a link for nuget.exe and the credential provider.

**Comment by ViktorHofer** [comment]
The proposed solution does not work for corefx as we not just require optional tools for official builds but also locally and in CI. I just submitted https://github.com/dotnet/corefx/pull/34946 to make that work without the buildtools dependency.

**Comment by dagood** [comment]
> in CI

Public CI, or only internal CI? I don't expect optional tooling to be possible in public CI because a secret is required. (The PAT to the optional feed hosted by AzDO.)

As far as I can tell, the approach above works fine for internal CI, where secret access is fine, and locally, where you can do some extra dev machine setup based on the steps @ericstj mentioned.

**Comment by ericstj** [comment]
Yeah, I was thinking we'd eliminate the need to have generated project files / targets to do the restore.  I was assuming we'd just do a restore locally using the developer's local nuget configuration and document that developers should add a feed for VSO with appropriate creds.   For the official build I chatted with @safern about adding an explicit restore step in the yml with the appropriate GUID for the feed that had the optional tooling.

**Comment by adiaaida** [comment]
Closing because the parent Epic was closed. If you believe this issue should still be worked on, please re-open.
