### ISSUE TITLE
MicroBuild signing tasks need to be ported to .Net Core 

### ISSUE THREAD

**Issue by tmat** [dotnet/arcade#1000]
Even when we can build our repos using .NET Core, we still have a dependency on Visual Studio for signing.

**Comment by JohnTortugo** [comment]
Just wondering: isn't this something that the MicroBuild team would be willing to work on?

cc: @markwilkie

**Comment by jcagme** [comment]
@tmat would you consider this to be a hard requirement for shipping preview (12/14)

**Comment by tmat** [comment]
Nope. What we have today works ok.

**Comment by Chrisboh** [comment]
This is not something that we own and we believe no longer needs VS as well.
