### ISSUE TITLE
Create team and area path for dotnet-templating in dnceng/internal

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/arcade#10008]
We want to manage internal AzDO better than we do now, for this we need some configuration to be done:

1) Team: dotnet-templating-maintainers (@JanKrivanek, @donJoseLuis + me)
2) Area path: internal/templating
3) Assign dotnet-templating-maintainers as default approver for any PR in dotnet-templating repo (if possible as optional, so eng people can override) or give us right to do it.
4) Create a board showing the open issues/active PR in our area path (or give us the rights to do it).

We will use the team an area path for CG alerts as well.

**Comment by chcosta** [comment]
Worked with Vlada off line to ensure all of her needs were met.
