### ISSUE TITLE
Fix Race Condition between Queue Insights & AzDo Build Checks

### ISSUE THREAD

**Issue by melotic** [dotnet/arcade#10001]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

QueueInsights needs to obtains the list of pipelines  from a given PR. Currently, this is done by using `GetBuildCheckRunsAsync` from `IGitHubChecksService` which parses the checks from Github for a given PR. However, we manage to beat AzDo in fetching these checks before they posted them.

There are two solutions for this that I can see:

1. Add a new Controller in HelixAPI that listens to events from AzDo, and then post the queue insights check
2. Wait a certain amount of time or loop untill we get all the build checks.

What are your thoughts? @ulisesh @ChadNedzlek @AlitzelMendez @riarenas

**Comment by ChadNedzlek** [comment]
It doesn't seem necessary to have a whole other hook, just multi-purpose the one build analysis is already using.  Build Analysis is able to get this information and keep it up to date... we should be able to generalize the mechanism for that so both services can have the information they need without having to have separate communication paths for both of them.  Waiting is also really finicky. This information in GitHub can be _hours_ behind sometimes.

**Comment by riarenas** [comment]
option 2 sounds like a workaround which I would be fine as a temporary measure, but not as a final solution for the situation. 
Option 1 seems like a real fix, but it seems like it's basically the exact same functionality that build analysis already uses so I'm not sure we need a whole other webhook controller and would be good if we could just add to the existing one?

**Comment by riarenas** [comment]
I wrote my message before seeing Chad's reply. I agree with him that it would be better to generalize the existing one rather than to write a new one.

**Comment by ChadNedzlek** [comment]
It seems like just putting this functionality _in_ build analysis is probably the route to go... we want to provide some insights into every check that's running, about all the builds that are related to that PR... that's exactly what build analysis is doing.  Adding an extra "and also go generate the queue insights check too" method call in the AnalysisProcessor (which already has all the information needed and all the timing/retry stuff in place) seems reasonable to me?  It doesn't feel like this "isn't build analysis" enough that it needs to be exiled to a different project, it just a slightly broader definition of analysis. :-)

**Comment by melotic** [comment]
Thanks for the feedback. Integrating this into build analysis is the way too go.
