### ISSUE TITLE
Investigate Async Triage "UnknownError" failure

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#10017]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When attempting to create new channel messages, the AsyncTriage tool, via the Graph api fails with:

```
Unhandled exception. Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: BadRequest
Message: UnknownError
```

No other details. This has happened before, but self resolved. This has been failing for at least a month. We need to reach out to the graph api team (@missymessa or @markwilkie may know how to reach out to) and work with them to figure out why their api has stopped working.

**Comment by AlitzelMendez** [comment]
Opened issue: https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1991409/

**Comment by AlitzelMendez** [comment]
IcM: https://portal.microsofticm.com/imp/v3/incidents/details/323004742/home

**Comment by ilyas1974** [comment]
Triage tool is functioning again as expected.

**Comment by adiaaida** [comment]
Has the graph team acknowledged anything and suggested they fixed anything?

**Comment by ilyas1974** [comment]
They made some comments in the ICM and I believe Jon is continuing to follow up them on this.
