### ISSUE TITLE
Exclude some symbols to publish during dry run

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#10016]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Teams thread -> https://teams.microsoft.com/l/message/19:1dad2081c8634f34915d88dce6220265@thread.skype/1657747300972?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1657747300972&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=Arcade&createdTime=1657747300972

Upgrade assistance wants to exclude some symbols to publish during dry run. It is currently failing their build. 

CC: @brandonh-msft

**Comment by epananth** [comment]
Checking if we can skip symbol publishing dry run for upgrade assistance. Going to run some test

**Comment by epananth** [comment]
Arcade test -> https://dev.azure.com/dnceng/internal/_build/results?buildId=1881353&view=results

**Comment by epananth** [comment]
So for short term fix we are planning to skip the dry run symbol publishing for upgrade assistance only. For long term fix we will add the ability to exclude symbols from publishing during dry run.

**Comment by epananth** [comment]
@hoyosjs has a better short term fix for this, I will work on the long term fix to exclude these files from the dry run..

**Comment by michellemcdaniel** [comment]
Removed blocking since there is a workaround that unblocked the original scenario

**Comment by MattGal** [comment]
Given there's a reasonable workaround and no pressure to change this for 7 months, I'm closing this.  We can revisit the issue if the workaround becomes less reasonable or others hit it.
