### ISSUE TITLE
[darc/maestro++] Add operation should be able to pull the latest version from the BAR

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1001]
Getting repo/sha and version of an item is annoying when adding a dependency.  `add` should be able to find the latest of a specific dependency.

**Comment by jcagme** [comment]
So, instead of just adding the placeholder with whatever info the user provided and let Maestro update on the next update we should pull down the latest?

**Comment by riarenas** [comment]
We get the same effect by adding dependency + updating.
