### ISSUE TITLE
Bump VS2022Regular version

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#10029]
VS2022 17.2.5 has been in scouting for two weeks, we should bump the regular queues to it.
Also doing this because we are no longer generating a VS2022 17.2.3 image, so we didn't get the windows patches on it (the last image was Helix-Server-Datacenter-2022-VS2022Enterprise_17_2_3-2022-06-20). With this change, all of our queues will have the latest windows patches

**Comment by dkurepa** [comment]
pr: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/24172?_a=files

**Comment by MattGal** [comment]
Rolled out 7/20/2022
