### ISSUE TITLE
Package Sdk/3.1.422-servicing-016036 for MAC OS is missed

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/arcade#10026]
Hi @dotnet/dnceng,

During automatic Arcade update,[[main] Update dependencies from dotnet/arcade by dotnet-maestro · Pull Request #292 · dotnet/install-scripts (github.com)](https://github.com/dotnet/install-scripts/pull/292/checks?check_run_id=7322488980) I have noticed tests failure for MAC OS machine
[Pipelines - Run 20220713.1 logs (azure.com)](https://dev.azure.com/dnceng/public/_build/results?buildId=1877768&view=logs&j=91498d90-aae7-5483-fd7e-b805526da7e1).

I have checked scripts installation for Ubuntu and Mac OS 
`./dotnet-install.sh  -Channel "release/3.1.4xx" -Verbose`

and it fails for the second env only: 
`Download failed: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.422-servicing-016036/dotnet-dev-osx-x64.3.1.422-servicing-016036.tar.gz`

This version is resolved from https://dotnetcli.azureedge.net/dotnet/Sdk/release/3.1.4xx/latest.version file

Could you check if the package exists?

**Comment by andriipatsula** [comment]
Hello @YuliiaKovalova 
For some reason latest point to `3.1.422-servicing-016036` version, but there is no such feed. I'll ask team how to search if actual file exist. And what to do if no.

**Comment by adiaaida** [comment]
@rbhanda I think this is because the config.txt used for the 3.1.422 release used a dash instead of a dot to separate servicing and the ######.##, as I pointed out in one of the teams chats. Can someone on the release team take a look and try to fix up this file?

**Comment by adiaaida** [comment]
This actually looks like it happens in the publishing code. This build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1868892

**Comment by adiaaida** [comment]
@marcpopMSFT is this file `dotnet-dev-osx-x64.3.1.422-servicing-016036.tar.gz` expected to exist in the sdk for 3.1?

**Comment by adiaaida** [comment]
In fact, it looks like ALL of the osx files are missing from this build (they look like they got built, but not published to blob artifacts, meaning they didn't get published to azure storage).

**Comment by riarenas** [comment]
It looks like this build's osx asset manifest didn't get uploaded to the AssetManifests container, which caused the publishing infra to not know it needed to publish these files.

I'll see if a rerun of the same commit helps with this at all.

**Comment by marcpopMSFT** [comment]
3.1.422 is an unreleased SDK version (August release). Not sure why the install scripts are finding a build of that as we really shouldn't be picking up daily servicing builds (we removed them from the installer homepage). That's the latest public build of 3.1.4xx fwiw. https://dev.azure.com/dnceng/internal/_build/results?buildId=1868892&view=results

The latest internal build is here: https://dev.azure.com/dnceng/internal/_build/results?buildId=1881924&view=results

**Comment by marcpopMSFT** [comment]
I'm not sure what the correct logic for the script is or the published files is but my assumption is that the install scripts should not be trying to install internal-only builds by default.

**Comment by YuliiaKovalova** [comment]
@marcpopMSFT ,

this logic is by design. Test failure was identified not in the scope of any changes, but with the automatic initiated Arkade bot.
I suspect, that something is missed in aka.ms links after one of the recent changes

**Comment by mmitche** [comment]
> @marcpopMSFT ,
> 
> this logic is by design. Test failure was identified not in the scope of any changes, but with the automatic initiated Arkade bot. I suspect, that something is missed in aka.ms links after one of the recent changes

As far as I know, the 3.1 infra hasn't changed in a very long time.

**Comment by mmitche** [comment]
It could be a change in the install scripts recently. @bekir-ozturk.

However, what do you expect that your invocation should return?

But there a few things to note:
- 3.1 doesn't use aka.ms links, so we shouldn't focus on those.
- The format "release/3.1.4xx" for the channel is a branch name format, which isn't really supported any longer. It's trying to parse the latest.version file under that path in dotnetcli, which is a daily build.
- If it's pointing to an internal build, it's only by coincidence that the version numbers match. 3.1 uses commit height versioning and this can happen if the internal branch and the public branch match in commit height.

**Comment by riarenas** [comment]
It might have been lost in the other discussion so mentioning it again in case this is related. @adiaaida and I looked into this build (the latest successful public release/3.1.4xx): https://dev.azure.com/dnceng/internal/_build/results?buildId=1868892&view=results and we found that for some reason, a Darwin asset manifest wasn't uploaded, and thus the publishing infra didn't publish any OSX related files. My initial investigations seem to suggest a #vso logging command got dopped by the console and didn't trigger the manifest upload.

I tried running the same SHA: https://dev.azure.com/dnceng/internal/_build/results?buildId=1883680&view=results, but as these are stable builds, we would've attempted to publish duplicate packages to feeds, so it failed. Do we need to run a new build that does a version bump so we stop getting conflicts? or is it OK to wait until a new build of 3.1.4xx happens naturally?

**Comment by YuliiaKovalova** [comment]
@mmitche , I expect that install-scripts.sh can resolve a link for both MacOS and Ubuntu environments when channel "release/3.1.4xx" is specified.
For now, it receives the wrong version for Mac OS.
No changes were introduced in scripts, and tests failure were revealed by auto PR created by Arcade bot.

**Comment by mmitche** [comment]
> @mmitche , I expect that install-scripts.sh can resolve a link for both MacOS and Ubuntu environments when channel "release/3.1.4xx" is specified. For now, it receives the wrong version for Mac OS. No changes were introduced in scripts, and tests failure was revealed by auto PR created by Arcade bot.

What do you expect that the version will resolve to? GA? Daily? etc.

**Comment by riarenas** [comment]
There doesn't seem like there's anything to do from the First responders side on this issue right now so I'm removing the label. Let me know if there's anything additional we can help investigating.

**Comment by YuliiaKovalova** [comment]
@mmitche , the daily build is expected.

@riarenas could you tell me the schedule of the regular deployment?

**Comment by riarenas** [comment]
@YuliiaKovalova can you clarify which deployment you mean?

**Comment by YuliiaKovalova** [comment]
@riarenas, I referenced this response 
` Do we need to run a new build that does a version bump so we stop getting conflicts? or is it OK to wait until a new build of 3.1.4xx happens naturally?`

**Comment by riarenas** [comment]
This refers to a new build of the release branch of the installer repository.

No deployment involved and @marcpopMSFT can probably answer when a new build is expected.

**Comment by mmitche** [comment]
> @riarenas, I referenced this response ` Do we need to run a new build that does a version bump so we stop getting conflicts? or is it OK to wait until a new build of 3.1.4xx happens naturally?`

I would wait until a new build happens naturally. Note that public daily builds of servicing releases aren't all that interesting, since public builds don't contain the next month's runtime (there is no public dependency flow)

**Comment by YuliiaKovalova** [comment]
Hi everyone,

Do you have any updates regarding this item?

**Comment by mmitche** [comment]
Hey @YuliiaKovalova It looks like the last few builds of the release/3.1.4xx branch have failed because the public and internal branches have the same commit height and the internal one (which is the more important branch) is completing first.

After further consideration, I don't think this is a valid use of the script nowadays. There really are no public daily builds of 3.1.4xx any longer, only by coincidence did this happen to work about once a month. The latest merge from public failed in another unrelated way, so we did not get an update.

If the intention is to get the latest **released** version of the SDK, then I think the invocation is different.

I am rerunning https://dev.azure.com/dnceng/internal/_build/results?buildId=1932739&view=results, which is the latest failed. It may fail again, or it may succeed and resolve the issue. But, I don't think this invocation should be relied upon.

**Comment by YuliiaKovalova** [comment]
Hi @mmitche,

Thank you for your explanation. I think we can close this ticket.
