### ISSUE TITLE
eng/common directory not deleting files

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#1003]
While looking at something in corefx I noticed there are a number of files under eng/common in corefx that aren't in arcade/eng/common. Shouldn't the script update delete these?

See https://github.com/dotnet/corefx/blob/master/eng/common/PushBuildAssets.cmd as an example.

**Comment by jcagme** [comment]
Related to https://github.com/dotnet/arcade/issues/258?

**Comment by markwilkie** [comment]
Closing in favor of @#258
