### ISSUE TITLE
[Test Reporting] Query is expired (Kusto)

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10049]
Our monitoring caught a bunch of these errors between 3:29 and 4:04am today. Would be worth looking into in the event we see this again. 

  | level | error
  | outerMessage | Query execution has resulted in error (0x80DA0006): Query is expired. [0]Kusto.Data.Exceptions.KustoDataStreamException: Query execution has resulted in error (0x80DA0006): Query is expired. Timestamp=2022-07-18T11:04:04.3898317Z ClientRequestId=KD2RunQuery;fdcd3df4-9532-40d2-89c6-5dfe911da93e ActivityId=95fe514d-93b2-422e-b332-b59873b4e1f4 ActivityType=GW.Http.CallContext ServiceAlias=ENGSRVPROD MachineName=KEngine000000 ProcessName=Kusto.WinSvc.Svc ProcessId=4608 ThreadId=15628 AppDomainName=Kusto.WinSvc.Svc.exe ActivityStack=(Activity stack: CRID=KD2RunQuery;fdcd3df4-9532-40d2-89c6-5dfe911da93e ARID=95fe514d-93b2-422e-b332-b59873b4e1f4 > GW.Http.CallContext/95fe514d-93b2-422e-b332-b59873b4e1f4) MonitoredActivityContext=(ActivityType=GW.Http.CallContext, Timestamp=2022-07-18T11:00:00.3582005Z, ParentActivityId=95fe514d-93b2-422e-b332-b59873b4e1f4, TimeSinceStarted=244031.6312 [ms])ErrorCode= ErrorReason= ErrorMessage= DataSource= DatabaseName= ClientRequestId= ActivityId=00000000-0000-0000-0000-000000000000 UnderlyingErrorCode=80DA0006 UnderlyingErrorMessage=Query is expired
  | timestamp | 1658142244556

**Comment by markwilkie** [comment]
closing assuming this is ok now, please re-open if not true.
