### ISSUE TITLE
Script tests in dotnet-helix-machine broken

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#10040]
The helix-client script integration tests in the [ScriptTests](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/test/ScriptTests) and [ServiceMockTests](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/test/ServiceMockTests&version=GBmain&_a=contents) projects of dotnet-helix-machines have not been running in CI. Running them ScriptTests to be broken (perhaps from simply being out of date as the client has evolved?).

[Build 20220714.04](https://dev.azure.com/dnceng/internal/_build/results?buildId=1880892&view=results) is a typical passing main-branch CI build. Notice that the test report does not include any test from ScriptTests or ServiceMockTests.

[Build 20220715.14](https://dev.azure.com/dnceng/internal/_build/results?buildId=1884134&view=results) is a build with two projects renamed to match Arcade's `.Tests` naming convention, causing these tests to get noticed and run. The test fails in Script.Tests are clear, and match what I see locally. The tests in ServiceMock.Tests pass and are listed in the test summary as expected.

These... should be fixed. Or, deleted if they're actually not providing value.

**Comment by MattGal** [comment]
These tests do provide value and I'm interested in taking this on, I'll do at least an initial investigation this week and see if I can unblock them.

**Comment by premun** [comment]
I see flakey behaviour with the ScriptTests:
https://dev.azure.com/dnceng/internal/_build/results?buildId=1895069&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=baf0d620-26ff-5880-4e4c-71df819d0940&s=6884a131-87da-5381-61f3-d7acc3b91d76

It failed in PRs and in main as well. Is this the right issue to re-open?

**Comment by MattGal** [comment]
Sure, I'll take a stab at fixing them, as I turned them back on.

**Comment by MattGal** [comment]
https://dev.azure.com/dnceng/internal/_git/569090e3-cc96-4250-a2d3-cd9b0039aa14/pullrequest/24322 merged , I'll put this in validate until it's been passing a while.

**Comment by MattGal** [comment]
I haven't seen this fail since last week, so closing.
