### ISSUE TITLE
New Helix Queues

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#10052]
As part of a customer request, we need 2 additional scouting queues created to support our Mac environment

osx.amd64.iphone.scouting.open
osx.amd64.appletv.scouting.open

Both will have similar configurations to the osx.amd64.scouting.open queue - except they will have a physical device attached to them.

**Comment by ilyas1974** [comment]
iphone_SE

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/24321
