### ISSUE TITLE
Copy AzDO Service Hooks for DevWF to new public AzDO project

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10058]
With the migration to the new `dotnet-public/public` AzDO project, we're going to need to copy our Service Hooks over. 

Ensure the following service hooks are copied: 
- [x] Completed build > buildresultanalysis queue - prod environment
- [x] Completed build > buildresultanalysis queue - staging environment
- [x] Completed build > testreporting queue - prod environment
- [x] Run state changed > buildresultanalysis queue - prod environment
- [x] Run state changed > buildresultanalysis queue  - staging environment
- [x] Run stage state changed > buildresultanalysis queue - prod environment
- [x] Run stage state changed  > buildresultanalysis queue - staging environment
- [x] Build `arcade-ci` > testreporting queue - staging environment
- [x] Build `build-result-analysis-test` > testreporting queue - staging environment

After the copy: 
- [x] Ensure that the new hooks work with Build Analysis, Test Reporting. 
- [x] Update MetricsObserver and Grafana appropriately.

We also may need to create a new PAT for these, since the current PAT is only enabled for a single org. 
- [x] Create PAT for `dnceng-public/public`

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Update Build Analysis Grafana dashboard to support monitoring/alerts on service hooks in multiple AzDO instances.

**Comment by garath** [comment]
Reminder that moving these hooks will also require changes to MetricsObserver and Grafana dashboards.

**Comment by missymessa** [comment]
Added two pipelines for the DevWF test project to the dnceng-public/public instance: 
![image](https://user-images.githubusercontent.com/47990216/180075480-ee50f3a9-df8a-45f5-8b31-a4a5f1f5c0bc.png)

**Comment by missymessa** [comment]
PAT for both dnceng and dnceng-public was created by Alex and added to secret manager configs by Ali. Should be good to go there.

**Comment by missymessa** [comment]
Checked a recent Arcade PR and it looks like the links are pointing back to `dnceng-public/public`.

**Comment by missymessa** [comment]
Seeing test results in prod Kusto cluster with `dnceng-public` listed as the organization.

**Comment by missymessa** [comment]
PR for the MetricsObserver changes: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/25713

**Comment by missymessa** [comment]
PR merged. Will need to update Grafana after the changes roll out.

**Comment by missymessa** [comment]
PR for updating the Build Analysis dashboard: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/27229

**Comment by missymessa** [comment]
Looks like this rolled out. Closing!
