### ISSUE TITLE
Address OS mismatch in Android Queue

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#10077]
Based on the data within the Matrix of Truth, we have multiple version of the Android operating system running within the same queue. As this is something that goes against our best practices, we need to determine which systems are running on the older version of Android so we can make sure and get them updated.

**Comment by ilyas1974** [comment]
@premun is going to work on getting the list of systems still running Android 29 so I can work with DDFUN to get the systems updated.

**Comment by premun** [comment]
I was able to gather API versions from the machines:

```sql
WorkItems
| where JobName == "e0ec7a39-c1bd-4e63-915e-c504cc411191" and MachineName != ""
| distinct MachineName, API=ExitCode
| order by API asc, MachineName asc
```

Which gives me these machines that need upgrading:
- `DNCENGWIN-001`
- `DNCENGWIN-002`
- `DNCENGWIN-003`
- `DNCENGWIN-004`
- `DNCENGWIN-005`
- `DNCENGWIN-006`
- `DNCENGWIN-007`
- `DNCENGWIN-008`
- `DNCENGWIN-009`
- `DNCENGWIN-010`
- `DNCENGWIN-011`
- `DNCENGWIN-012`
- `DNCENGWIN-013`
- `DNCENGWIN-014`
- `DNCENGWIN-015`
- `DNCENGWIN-016`
- `DNCENGWIN-017`
- `DNCENGWIN-018`
- `DNCENGWIN-019`
- `DNCENGWIN-020`
- `DNCENGWIN-021`
- `DNCENGWIN-023`
- `DNCENGWIN-024`
- `DNCENGWIN-025`
- `DNCENGWIN-026`
- `DNCENGWIN-027`
- `DNCENGWIN-028`
- `DNCENGWIN-029`
- `DNCENGWIN-030`
- `DNCENGWIN-031`
- `DNCENGWIN-032`
- `DNCENGWIN-033`
- `DNCENGWIN-034`
- `DNCENGWIN-035`
- `DNCENGWIN-037`
- `DNCENGWIN-038`
- `DNCENGWIN-039`
- `DNCENGWIN-040`
- `DNCENGWIN-041`
- `DNCENGWIN-042`
- `DNCENGWIN-043`
- `DNCENGWIN-044`
- `DNCENGWIN-045`

**Comment by premun** [comment]
@ilyas1974 I have re-run the check with the two missing machines now being online and they were on 30 already

**Comment by ilyas1974** [comment]
moving this to FR so we can address it with DDFUN

**Comment by premun** [comment]
I think this might be completed already?

**Comment by Chrisboh** [comment]
@premun can you run the tool you ran to check to see if there are any more machines with a mismatched API versions?

**Comment by premun** [comment]
Sure, will do.

For completness, this is the script:
```ps1
Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://aka.ms/get-xharness-ps1'))

$Env:DOTNET_ROOT='./.dotnet'

./xharness android state

# Start the process.
$ps = [System.Diagnostics.Process]::Start(
  [System.Diagnostics.ProcessStartInfo] @{
    FileName = './xharness'
    Arguments = 'android state'
    UseShellExecute = $false
    RedirectStandardOutput = $true
    RedirectStandardError = $true
  }
)

# Read the output streams asynchronously, to avoid a deadlock.
$tasks = $ps.StandardOutput.ReadToEndAsync(), $ps.StandardError.ReadToEndAsync()

if ($PSVersionTable.PSVersion.Major -ge 7) {
  # PowerShell (Core) 7+: Wait for task completion in background threads.
  $tasks | ForEach-Object -Parallel { $_.Wait() }
} else {  
  # Windows PowerShell: Poll periodically to see when both tasks have completed.
  while ($tasks.IsComplete -contains $false) {
    Start-Sleep -MilliSeconds 100
  }
}

# Wait for the process to exit.
$ps.WaitForExit()

$stdout = $tasks[0].Result.Trim()
$stderr = $tasks[1].Result.Trim()

if ($stdout -match "API version: ([0-9]+)") {
  exit $Matches.1
}

exit -1
```

And this is the Helix job that used it:
```
osob_cli exec -Pc premun -q windows.10.amd64.android.open --work-item-count 200 --timeout 00:07:00 --payload "C:\Users\prvysoky\Desktop\android-state.ps1" --% "powershell.exe -ExecutionPolicy ByPass -NoProfile -File android-state.ps1"
```

**Comment by premun** [comment]
This is the result:
```sql
WorkItems
| where JobName == "4f3bd9d2-314b-4778-b531-80aa1e7a0b17"
| order by Finished desc 
| project FriendlyName, MachineName, Attempt, ExitCode, Finished, Duration=Finished-Started, ConsoleUri
| where ExitCode == 29
| distinct MachineName
```

which means that these still need upgrading:

- `DNCENGWIN-001`
- `DNCENGWIN-002`
- `DNCENGWIN-003`
- `DNCENGWIN-004`
- `DNCENGWIN-005`
- `DNCENGWIN-006`
- `DNCENGWIN-007`
- `DNCENGWIN-008`
- `DNCENGWIN-009`
- `DNCENGWIN-010`
- `DNCENGWIN-011`
- `DNCENGWIN-012`
- `DNCENGWIN-013`
- `DNCENGWIN-014`
- `DNCENGWIN-015`
- `DNCENGWIN-016`
- `DNCENGWIN-017`
- `DNCENGWIN-018`
- `DNCENGWIN-019`
- `DNCENGWIN-021`
- `DNCENGWIN-023`
- `DNCENGWIN-024`
- `DNCENGWIN-025`
- `DNCENGWIN-026`
- `DNCENGWIN-027`
- `DNCENGWIN-028`
- `DNCENGWIN-029`
- `DNCENGWIN-030`
- `DNCENGWIN-031`
- `DNCENGWIN-032`
- `DNCENGWIN-033`
- `DNCENGWIN-034`
- `DNCENGWIN-035`
- `DNCENGWIN-037`
- `DNCENGWIN-038`
- `DNCENGWIN-039`
- `DNCENGWIN-040`
- `DNCENGWIN-041`
- `DNCENGWIN-042`
- `DNCENGWIN-043`
- `DNCENGWIN-044`
- `DNCENGWIN-045`

**Comment by jonfortescue** [comment]
IcM filed here: https://portal.microsofticm.com/imp/v3/incidents/details/334698866/home

**Comment by jonfortescue** [comment]
IcM has been resolved; closing.
