### ISSUE TITLE
Consider removing 1ES Hosted build resources from our subscriptions

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#10076]
We may have already discussed this, but this came up when discussing the Service 360 issue [here](https://dnceng.visualstudio.com/internal/_workitems/edit/3008). 

The work would be small (remove SubscriptionId, TenantId, Vnet etc from Provider Properties when deploying) and it would move all monitoring for S360 for these machines to the 1ES team.

I've put the "needs triage" tag here and will represent this issue this week @ triage.

**Comment by garath** [comment]
It is typical to have 1ES own the subscription?

**Comment by garath** [comment]
Just saw your other comment that it is indeed recommended for 1ES to own the subscription.

**Comment by MattGal** [comment]
> It is typical to have 1ES own the subscription?

Supposedly, yes.  Every time I have a problem with Service 360 stuff this is the immediate recommendation.

**Comment by garath** [comment]
Sounds like there are concerns for quota and billing. We'll discuss in triage.

**Comment by adiaaida** [comment]
@Chrisboh to weigh in

**Comment by adiaaida** [comment]
Putting this in Operations to investigate billing/cores questions

**Comment by missymessa** [comment]
@riarenas do you know if this is still needed?
