### ISSUE TITLE
Update Azure service bus libraries in helix-machines

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#10081]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

part of the root cause for https://github.com/dotnet/arcade/issues/9925 was that when moving the repo to use central package management, we started hitting `ObjectDisposedException`s  when trying to get service bus queue information.

We're due for an update of these libraries, which in this case means moving away from the deprecated Microsoft..Azure.Management.* APIs for the newer Azure management sdks

**Comment by MattGal** [comment]
@riarenas by virtue of having to get it working on the newer 6.0 .NET Core, I think this work would "naturally" happen when we do https://github.com/dotnet/arcade/issues/10018.  Do you think this is worth doing as an intermediate step to get CG stuff happy, or should it wait?

**Comment by riarenas** [comment]
I wasn't aware this was getting flagged by CG. If we're approaching a deadline for resolving alerts I think it makes sense to do individually. 

If it's going to be taken care of by the other work I think we can close this.

**Comment by riarenas** [comment]
Ah, I think I see. Do you mean because the original change that broke things was done as part of CG compliance?

I think this was introduced when attempting to onboard to central package management, but I believe @garath dealt with the underlying alerts in the repo already.

**Comment by MattGal** [comment]
I forgot we were CG clean, but either way the conversion can happen as part of the other issue because if it doesn't, it'll have the same problem by virtue of having the latest version of SSLStream

**Comment by MattGal** [comment]
Closing in favor of https://github.com/dotnet/arcade/issues/10018
