### ISSUE TITLE
Unified Build

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#10097]
Unified build is a massive amount of work across a large variety of product and infrastructure areas. This epic serves as holding epic for items that we identify we need to do before they get organized in to concrete, isolated sections of work.

**Comment by tkapin** [comment]
@mmitche The Unified Build work is mostly structured now, do you see value in transforming this epic into a top-level container for other UB epics or prefer to close it? I have slight preference for the former so we could have one entry point into all UB work, but wouldn't mind to close it to reduce the number of epics.

**Comment by mmitche** [comment]
I think we should close it. A lot of folks don't love the super-epic format, and I think we're gaining a good handle on the overall work required anyway.
