### ISSUE TITLE
Generate SVG badge with version information

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#1009]
(from @natemcmaster )

Generate an SVG badge on build that contains the package version. This can be uploaded to an Azure blob store and referenced from README.

TODO:
- [ ] Figure out how to get the value of PackageVersion. It's currently always empty when I run build.cmd
- [ ] Upload badge.svg and latest.txt (must be uploaded with `--content-cache-control="no-cache, no-store, must-revalidate")

**Comment by markwilkie** [comment]
There is currently an open question about whether to put this in as part of the build, or publish.  For now, I'm adding this issue to the 'publish' epic....

**Comment by JohnTortugo** [comment]
I'm wondering if it would be possible to add an entry in Maestro API (that don't require auth) to return the latest version of an asset as a string (SVG?) that way we wouldn't need to create/upload SVG anywhere.

What do you think @riarenas @alexperovich @mmitche

**Comment by riarenas** [comment]
Adding an API adjacent to the assets API seems like a good idea. 

@markwilkie is this still a priority?

**Comment by markwilkie** [comment]
Not currently a priority
