### ISSUE TITLE
Add OS version info to the first line of Helix log

### ISSUE THREAD

**Issue by danmoseley** [dotnet/arcade#10099]
eg., extend something like
`Console log: 'System.Threading.Tasks.Tests' from job 54dfd2ef-2143-45ff-af70-9997432b1728 workitem 044e1461-d0cb-4e8f-af56-afacd835664a (osx.1200.amd64.open) executed on machine dci-mac-build-371.local`
to 
`Console log: 'System.Threading.Tasks.Tests' from job 54dfd2ef-2143-45ff-af70-9997432b1728 workitem 044e1461-d0cb-4e8f-af56-afacd835664a (osx.1200.amd64.open) executed on machine dci-mac-build-371.local running macOS 12.3.1`

Or any form that shows us the OS version, patch version, etc.

As suggested here  https://github.com/dotnet/runtime/issues/68290#issuecomment-1156706495 -- a test where it appeared that the test may be fixed by a patch update, but we couldn't tell which machine was in which state.

**Comment by danmoseley** [comment]
In general any info like this on the first line is pretty handy, because not only is it easy to find it's also easy to copy into an issue.

**Comment by melotic** [comment]
I'll take a look at this.

**Comment by danmoseley** [comment]
TBH the output of `uname -a`  or just eg `uname -srvmp` (either on this line or the next one) might be nice on Linux, not sure of equivalent on mac. For example, I recently wanted to check on the kernel version of certain configurations. that would tell me right there.

**Comment by melotic** [comment]
> TBH the output of `uname -a` or just eg `uname -srvmp` (either on this line or the next one) might be nice on Linux, not sure of equivalent on mac. For example, I recently wanted to check on the kernel version of certain configurations. that would tell me right there.

We would probably just use pythons native [`platform.platform()`](https://docs.python.org/3/library/platform.html#platform.platform) so this would appear on all helix machines and be a cross-platform solution.

On Mac, this would output: `macOS-10.15.7-x86_64-i386-64bit`

On Ubuntu: `Linux-4.9.140-tegra-aarch64-with-Ubuntu-18.04-bionic`

However, on Windows 11 it will output `Windows-10-10.0.22000-SP0`, as the Windows API returns its Windows 10, with the only distinction being the magical build number `10.0.22000` signifying Windows 11.

Does this fit your needs?

**Comment by danmoseley** [comment]
Seems reasonable, yes!

**Comment by melotic** [comment]
Great!

PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/24421

This will be rolled out next week.

**Comment by MattGal** [comment]
Rolled out last week, looks good, closing.
