### ISSUE TITLE
Missing VS workload "ATL" in `build.windows.amd64.vs2022.pre.open`

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#10106]
As per a [client request](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1658382615017?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1658382615017&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1658382615017), we are missing these ARM workloads in `build.windows.amd64.vs2022.pre.open`:
![image](https://user-images.githubusercontent.com/7013027/180166166-7152fc4b-b6dd-4903-98f4-5303269e9e9d.png)

[[Build link]](https://github.com/dotnet/wpf/pull/6838/checks?check_run_id=7439284028)

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/24325

**Comment by riarenas** [comment]
This is not a request for new workloads, and it's indeed a regression. https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/commit/6848c54aa05da21ce361b6d1130e8b60fb475915?refName=refs%2Fheads%2Fmain changed the list of workloads we install in the preview images, but we didn't add all the workloads we installed in the non-preview images.

Notably in the diff between the two workload lists, we stopped installing 

`Microsoft.VisualStudio.Component.VC.ATL.ARM64`
