### ISSUE TITLE
SBOM for VS insertions manifest tool error 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#10104]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

| Repo name | Do we need to do anything here? | Infra error / Repo Error / Sbom manifest tool error  | Test run |
 |-|-|-|-|
 | vs-code-debugger | Done |   | |
 | dotnet-winforms-designer |  Done  |  | (https://dev.azure.com/dnceng/internal/_build/results?buildId=1961917&view=results)|
 | MS.VS.Debugger.BrokeredServices  | Figuring out arcade update    | Repo error | |
 | dotnet-msbuild |  Done  | | https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6597691&view=logs&j=bb592630-4b9d-53ad-3960-d954a70a95cf&t=afa1a0df-45a6-583b-c394-85c871daa736 |
 | razor-tooling | Done |    | https://dev.azure.com/dnceng/internal/_build/results?buildId=1961930&view=results|
 | Fsharp |   Done| SBOM tool error  | |
 | VS-code-coverage | Done | | https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6596820&view=results |

**Comment by epananth** [comment]
We have 3 issues open for microsoft/dropvalidator repo 

1) https://github.com/microsoft/dropvalidator/issues/455 - This is blocking the following repos Razor tooling, winforms-designer, f sharp to generate sbom for VS insertion

2) https://github.com/microsoft/dropvalidator/issues/466 - This is blocking Razor tooling alpine leg sbom generation for dontet

3) https://github.com/microsoft/dropvalidator/issues/454 - This is blocking msbuild to generate sbom for VS insertion.

**Comment by epananth** [comment]
We need the manifest tool folks to fix the issues. After the issue is fixed we need to update the GenerateSbom flag to true in the above mentioned repos (in the pipeline yaml)

**Comment by ilyas1974** [comment]
Continuing to work with the microsoft/dropvalidator team to address our open issues.

**Comment by epananth** [comment]
Alpine leg error fix is merged and I did see some positive runs in runtime : https://dev.azure.com/dnceng/internal/_build/results?buildId=1960979&view=results
But we see some warning : https://dev.azure.com/dnceng/internal/_build/results?buildId=1960979&view=logs&j=79152c53-978f-5956-309f-f18ecaacb149&t=d038bec2-71ea-5576-6a31-c1121da57f0d

**Comment by epananth** [comment]
SBOM team has not completed the test for the alpine leg, so they rolled back

**Comment by epananth** [comment]
Updated test runs on the issue. MAGICALLY the builds for the issue microsoft/dropvalidator#455 starting to work. 

PS : I have NOT made any changes to this piece of code. IDK if the sbom team pushed any change that fixed this issue

**Comment by epananth** [comment]
All the repos except fsharp worked, trying to see why that one is spl.

**Comment by epananth** [comment]
I tried to get a repro in fsharp, I got an error in signing ( after 4 hours of waiting) I have requeued the build. @MattGal said he will help me look at the error but I'm not getting a proper repro. I will try to get it EOD or next week.

**Comment by Chrisboh** [comment]
@epananth I have two questions for this:

- What is the current status of this?
- Should this be tracked in FR?

**Comment by epananth** [comment]
Apologize for the delay, I was oof for some time, I couldn't get to this earlier. I will update this by EOD

**Comment by epananth** [comment]
vs-code-debugger repo is working,  I am looking at F sharp and machine-learning repo now

**Comment by epananth** [comment]
I did some tests in machine learning repo, looks like they have some upstream package error they are fixing.

**Comment by epananth** [comment]
I was not able to run the test for f sharp, I have some permission issue.. I pinged some folks from the team to get more info

**Comment by epananth** [comment]
unblocked dotnet-machinelearning repo

**Comment by epananth** [comment]
Fsharp is the last repo working on that

**Comment by epananth** [comment]
VSDebug-Core I had the successful build already, helping the owner with the PR today.

**Comment by epananth** [comment]
all the repos are onboarded except Fsharp. Fsharp has customized build a lot. The way they generate vsix files are totally different from all the repos we have dealt with so far. I have asked Kevin Ransome to take a look at the vsix file generation and move some things out of the folder we actually care for sbom generation.  Once that is done, I will retry sbom generation.

**Comment by epananth** [comment]
Fsharp was fixed this week. This is complete!

Thank you for your patience :)
