### ISSUE TITLE
GenFacades doesn't support desktop msbuild

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#1010]
I'm seeing failures when running with desktop msbuild.
```
error MSB4062: The "GenFacadesTask" task could not be loaded from the assembly F:\dotnet-maestro-bot\corefx\packages\microsoft.dotnet.genfacades\1.0.0-beta.18478.5\build\../tools/netcoreapp2.1/Microsoft.DotNet.GenFacades.
dll.
```

This is due to the targets not selecting the desktop build of the task when running on desktop:
https://github.com/dotnet/arcade/blob/0f209fc718e920446ac1c85ab8b8d9fab68258d6/src/Microsoft.DotNet.GenFacades/build/Microsoft.DotNet.GenFacades.targets#L34

These should be switching on the runtime type similar to 
https://github.com/dotnet/arcade/blob/5b8a27d82fc3ed08196ff40d42401931e345d406/src/Microsoft.DotNet.ApiCompat/build/Microsoft.DotNet.ApiCompat.targets#L7-L8

As an aside: why are all these targeting net472 for desktop?  I doubt all consumers of these arcade tasks have net472.

**Comment by markwilkie** [comment]
@ericstj - for context on the 472 decision, see #393

**Comment by wtgodbe** [comment]
https://github.com/dotnet/arcade/pull/1015 should resolve the issue
