### ISSUE TITLE
Machine PerfTiger100 removed from Windows.10.Amd64.19H1.Tiger.Perf

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#10112]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

On request from @LoopedBard3, the machine was taken out of the `Windows.10.Amd64.19H1.Tiger.Perf` queue for testing. This issue tracks adding it back once testing has been completed

**Comment by MattGal** [comment]
From @LoopedBard3 : "I cleared off my stuff from testing on PerfTiger100, it can be added back into the queue. Thanks!"
