### ISSUE TITLE
Add Android and iOS support information to MoT

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#10110]
Per our sync, we need to add information to the matrix of truth for Android and iOS/tvOS support. This was introduced in .NET 6. @dkurepa is going to work on getting this added to the JSON. As for coverage, we are going to assume that runs within the appleTV/iphone queues are for tvOS/iOS support and runs within the Android simulator queues and/or the android on premise queue are for Android support.

**Comment by dkurepa** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/24346

**Comment by ilyas1974** [comment]
Information for Android and iOS support has been added to the Matrix
