### ISSUE TITLE
Add usable OpenSSL package to ARM64 Mac queues

### ISSUE THREAD

**Issue by wfurt** [dotnet/arcade#10139]
We have test gap for runtime as the arm Macs do not seems to have usable OpenSSL and tests are failing to run.
related to https://github.com/dotnet/runtime/issues/49083

https://helix.dot.net/api/2019-06-17/jobs/88104698-a529-45da-b32d-a2f3344596db/workitems/System.Security.Cryptography.OpenSsl.Tests/console

```
Console log: 'System.Security.Cryptography.OpenSsl.Tests' from job 88104698-a529-45da-b32d-a2f3344596db workitem 74733977-78aa-4504-87c7-323eca23865a (osx.1200.arm64.open) executed on machine dci-macm1-build-124.local
+ ./RunTests.sh --runtime-path /tmp/helix/working/9D0908EC/p
----- start Fri Jul 15 18:08:50 PDT 2022 =============== To repro directly: =====================================================
pushd .
/tmp/helix/working/9D0908EC/p/dotnet exec --runtimeconfig System.Security.Cryptography.OpenSsl.Tests.runtimeconfig.json --depsfile System.Security.Cryptography.OpenSsl.Tests.deps.json xunit.console.dll System.Security.Cryptography.OpenSsl.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/private/tmp/helix/working/9D0908EC/w/97F90895/e /private/tmp/helix/working/9D0908EC/w/97F90895/e
  Discovering: System.Security.Cryptography.OpenSsl.Tests (method display = ClassAndMethod, method display options = None)
No usable version of libssl was found
./RunTests.sh: line 168: 39042 Abort trap: 6           "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Security.Cryptography.OpenSsl.Tests.runtimeconfig.json --depsfile System.Security.Cryptography.OpenSsl.Tests.deps.json xunit.console.dll System.Security.Cryptography.OpenSsl.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/private/tmp/helix/working/9D0908EC/w/97F90895/e
----- end Fri Jul 15 18:08:51 PDT 2022 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
```

I verified on my M1 macBook that if appropriate package is installed tests can run as expected.
There can be several issues with the package so if we feel the package is already there I would need access to helix instance to investigate.

**Comment by MattGal** [comment]
This all boils down to a typo in a OneNote used by the DDFUN team to set up mac machines.   Specifically for Mac M1s (ARM machines) it says to link the OpenSSL 1.1 dylibs into /opt/homebrew/Cellar instead of hte usual '/usr/local/lib'.    I've fixed this location in the docs as well as chatting with a DDFUN vendor IC.

I have fixed this up on all 67 Mac M1 devices in `osx.1200.arm64.open` and `osx.1200.arm64` and will do the same for the OSX 11 ARM64 machines shortly.

**Comment by MattGal** [comment]
`osx.1100.arm64` and `osx.1100.arm64.open` are done now.  @wfurt please reenable the tests as the problem should be fixed for all Helix M1 Macs.  

I will leave this in "validate" til end of week in case this does not fully solve the problem.

**Comment by wfurt** [comment]
thanks @MattGal I kicked tires on https://github.com/dotnet/runtime/pull/72294 and I'll post update when the test run is finished. (I will eventually revert back the force run on OSX_arm64)

**Comment by andriipatsula** [comment]
Hello. I linked one more issue https://github.com/dotnet/runtime/issues/73210 from runtime. libssl is missing for mac ARM 
machines.

**Comment by MattGal** [comment]
After doing the same script-based check on every machine in these queues:

```
osx.1200.amd64.open
osx.1100.amd64.open
osx.1200.amd64
osx.1100.amd64
```
... only `dci-mac-build-103` was in the failed state.  

Putting this back to "validate";  I'll keep monitoring it but it looks like a single machine (out of 200+ was messed up in this case).

Self reminder to check later:
``` 
WorkItems
| where Queued > datetime(2022-08-01 23:00:00.0000000)
| where FriendlyName == "System.Security.Cryptography.OpenSsl.Tests"
| where QueueName startswith "osx."
| where ExitCode != 0
```

**Comment by MattGal** [comment]
Tests pass in the [reenabling PR](https://github.com/dotnet/runtime/pull/72294#pullrequestreview-1060531477) and all machines are updated, closing this issue.
