### ISSUE TITLE
Move GitHub->DevDiv mirroring into Arcade

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#10159]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The current github->devdiv mirroring script lives in the `DotNet-BuildPipeline` repo. https://dev.azure.com/devdiv/DevDiv/_build/index?definitionId=7168&_a=completed and https://dev.azure.com/devdiv/DevDiv/_build?definitionId=8289.

This repo has quite a few CG errors (mainly due to oddness in the 2.1 SDK), and since 2.1 is EOL, we should try to get rid of uses of it. What we could do is move the mirroring logic into the arcade repo and repoint those definitions to the arcade repo. It should also be possible to move these to YAML at the same time. The primary difference between the devdiv and dnceng mirrors is just the calculation of the target branch names for MSRC mirroring, and the calculation of the target repo (DevDiv does Repo-Trusted).

Recommendation is to:
1. Copy (or modify) arcade's current YAML files for mirroring to support devdiv mirroring
2. Point the devdiv mirrors to the new YAML
3. Have fun.

**Comment by MattGal** [comment]
https://github.com/dotnet/arcade/pull/10196

**Comment by MattGal** [comment]
Steps 1 and 2 completed and the old devdiv.vs pipelines are now disabled.  I'll keep this in "validate" until next week so I can see the [dnceng-internal one](https://dnceng.visualstudio.com/internal/_build?definitionId=240) take a few real changes too, then close this.

**Comment by MattGal** [comment]
I'm deleting the old pipelines in devdiv.vs, after that I will close this issue.
