### ISSUE TITLE
Update KustoQuery and KustoHelpers to be able to pass options

### ISSUE THREAD

**Issue by AmandaMisjuwar** [dotnet/arcade#10191]

**Comment by AmandaMisjuwar** [comment]
The options that I need to pass are
- `ClientRequestProperties.OptionProgressiveProgressReportPeriod` (`"query_results_progressive_update_period"`)
- `ClientRequestProperties.OptionMaxOutputColumns` (`"maxoutputcolumns"`)

**Comment by epananth** [comment]
putting this back in the backlog

**Comment by ilyas1974** [comment]
Hi @AmandaMisjuwar, I wanted to follow up with you and see if this is still an outstanding issue for you?

**Comment by ilyas1974** [comment]
Did not realize this was related to our intern project from the summer. Closing this issue.

**Comment by missymessa** [comment]
It looks like @ulisesh made a PR for this work back in February, the issue just needed to be closed.
