### ISSUE TITLE
Fix VM cleaner Azure function

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#10226]
I think something broke the VM cleaner that runs as an Azure function, it shows some nuget error.

We need to fix the error and then we might need to create the service principal used the app because they were deleted as part of https://github.com/dotnet/arcade/issues/10220

**Comment by MattGal** [comment]
Created https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/24570 to update to durable functions 2.x

**Comment by MattGal** [comment]
Slated to roll out 8/10/2022

**Comment by MattGal** [comment]
Rolled out this morning, closing.
