### ISSUE TITLE
[Arcade-validation][release/6.0] Validate publishing job failing to load Azure.Core after version bump

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#10233]
- [X] This issue is blocking 
This is blocking promotion of release/6.0 builds of arcade
- [ ] This issue is causing unreasonable pain

The arcade-validation official pipeline is failing during the "validate publishing" job. 

https://dev.azure.com/dnceng/internal/_build/results?buildId=1910407&view=results spawned https://dev.azure.com/dnceng/internal/_build/results?buildId=1910580&view=results

which failed during publishing with the following error:
```
##[error].packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.22378.11\tools\SdkTasks\PublishArtifactsInManifest.proj(118,5): error : Could not load file or assembly 'Azure.Core, Version=1.0.2.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'. The system cannot find the file specified.
```

This was caused by https://github.com/dotnet/arcade/commit/73f43b50da82b706494ddaa1af739a7c5269a5b1, which bumped azure.core to a version we can't load in the context of the 6.0 branch. 

FYI @AlitzelMendez @ilyas1974 

I'm putting this in FR because it's related to the CG work for newtonsoft in the 6.0 release branch.

**Comment by AlitzelMendez** [comment]
PR: https://github.com/dotnet/arcade/pull/10249

**Comment by garath** [comment]
Looks like things are good now: [build 1919160](https://dev.azure.com/dnceng/public/_build/results?buildId=1919160&view=results)

**Comment by riarenas** [comment]
Agreed that things are looking good now, but I think it's https://dev.azure.com/dnceng/internal/_build/results?buildId=1921212&view=results that we care about
