### ISSUE TITLE
NetHelix service connection could not be found

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#10277]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

dotnet-helix-service's weekly pipeline is now failing with authorization issues due to not being able to find the NetHelix service connection. Example: https://dev.azure.com/dnceng/internal/_build/results?buildId=1921589&view=results

**Comment by MattGal** [comment]
On it...

**Comment by MattGal** [comment]
Created IcM https://portal.microsofticm.com/imp/v3/incidents/details/325197387/home.  Will keep poking around.

**Comment by MattGal** [comment]
Problem seems to have subsided.  Support engineer from AzDO suggested clicking "verify AND save" when checking out "broken" service connections, otherwise no idea what changed.

**Comment by MattGal** [comment]
helix-machines is failing for other reasons but this hasn't reproduced, so I'm closing this... @jonfortescue please reactivate if you see it again.
