### ISSUE TITLE
Add WiX localization to the OneLocBuild template/script

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#10298]
WiX localization is needed for multiple repos for the .NET 7.0 timeline. Should be done ASAP.

**Comment by dougbu** [comment]
See [Pull request 542784: Add WiX_CloneLanguages for WiX localization - Repos (visualstudio.com)](https://ceapex.visualstudio.com/CEINTL/_git/SoftwareLocalization/pullrequest/542784?_a=files) and [Pull request 542784: Add WiX_CloneLanguages for WiX localization - Repos (visualstudio.com)](https://ceapex.visualstudio.com/CEINTL/_git/SoftwareLocalization/pullrequest/542784) for more detail on the new OneLocBuild@2 option enabling strings.wxl (aka WiX localization) onboarding.

**Comment by dougbu** [comment]
Sorry for my dupe in the comment above. Meant to link to <https://dev.azure.com/ceapex/CEINTL/_workitems/edit/659992>.
