### ISSUE TITLE
SBOM generation timing

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#10312]
We've had reports of SBOM generation timing out a few times in a row in the same place: during [`Scan Manifest file: /tmp/ScanManifest_20220804213642.json`](https://dev.azure.com/dnceng/internal/_build/results?buildId=1924121&view=logs&j=d21bfc57-2f78-5de1-fdb5-cfedcec99163&t=8bbcbf11-ca63-553b-b565-aa12d75b3dda&s=6884a131-87da-5381-61f3-d7acc3b91d76).

**Comment by epananth** [comment]
Spoke to one of the engineers from SBOM team, he mentioned that they had to deployment that was rolled back. So this error should go away..

**Comment by epananth** [comment]
we can monitor the builds in the weekend, then on Monday we can close this issue

**Comment by MichaelSimons** [comment]
I re-queued the build that prompted this issue and I am still seeing a hang - https://dev.azure.com/dnceng/internal/_build/results?buildId=1924121&view=logs&s=a6e6a9d4-98dc-5d9d-8b49-09e0ab9a55da&j=6515dcf6-cc56-5539-8332-cd3ae9e11746

**Comment by MichaelSimons** [comment]
I stand corrected, the previous build was triggered by rerunning failed jobs.  I queued a new build and it passed this time.

**Comment by MattGal** [comment]
As this is passing ([example](https://dnceng.visualstudio.com/internal/_build/results?buildId=1926557&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76)) and was rolled back externally, I am closing the issue.
