### ISSUE TITLE
`dci-mac-build-103` does not seem to have OpenSSL installed

### ISSUE THREAD

**Issue by karelz** [dotnet/arcade#10314]
The machine failed `System.Security.Cryptography.OpenSsl.Tests Work Item` in several runs with `No usable version of libssl was found`.
It is hard to query for them all (as there is different problem interfering), so here a few examples only:

Day | Build | Details
-- | -- | --
8/1 | PR [1915309](https://runfo.azurewebsites.net/view/build/?number=1915309) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72934-merge-0ee8b5b1c0e2431fab/System.Security.Cryptography.OpenSsl.Tests/1/console.b280c88d.log?%3Fhelixlogtype%3Dresult)
7/31 | Rolling run - [1914601](https://runfo.azurewebsites.net/view/build/?number=1914601) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d48929e09acb474baa/System.Security.Cryptography.OpenSsl.Tests/1/console.a5cb0446.log?%3Fhelixlogtype%3Dresult)
7/30 | PR [1913265](https://runfo.azurewebsites.net/view/build/?number=1913265) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73105-merge-dea2f38219db4b0c83/System.Security.Cryptography.OpenSsl.Tests/1/console.c304960b.log?%3Fhelixlogtype%3Dresult)
7/29 | PR [1913058](https://runfo.azurewebsites.net/view/build/?number=1913058) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73037-merge-91da29e7eafc47b4ba/System.Security.Cryptography.OpenSsl.Tests/1/console.ce2fe4a9.log?%3Fhelixlogtype%3Dresult)
7/29 | Rolling run - [1912276](https://runfo.azurewebsites.net/view/build/?number=1912276) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ece4b02e992848eebd/System.Security.Cryptography.OpenSsl.Tests/1/console.524d5644.log?%3Fhelixlogtype%3Dresult)

**Comment by andriipatsula** [comment]
I've disabled this machine:
```
Machine `dci-mac-build-103` in `osx.1200.amd64.open` has been disabled
```
There was similar issue: https://github.com/dotnet/arcade/issues/10139 related to Arm64 machines. @MattGal, I believe this is related.

**Comment by MattGal** [comment]
From the discussion on https://github.com/dotnet/arcade/issues/10139, see this comment https://github.com/dotnet/arcade/issues/10139#issuecomment-1203018889

"... only dci-mac-build-103 was in the failed state."

Note your last instance of this problem was 8/1, which was 4 days ago.

**Comment by MattGal** [comment]
@karelz I confirmed this machine has never had the problem since I fixed it.  You can check this out via Kusto:

```
WorkItems
| where Queued > datetime(2022-08-01 23:00:00.0000000)
| where FriendlyName == "System.Security.Cryptography.OpenSsl.Tests"
| where MachineName == "dci-mac-build-103"
| order by Finished desc 
```

I'm going to re-online this machine and close this issue, feel free to reopen if this happens again.
