### ISSUE TITLE
HTTP 500s from AzDO Test Results API

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#10358]
Tracking IcM: https://portal.microsofticm.com/imp/v3/incidents/details/326663396/home

This seems to be impacting approximately 1 in 3 builds:

[Query](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA12QTUvEMBCG7/0VQ08p7KGyeKwHbxUEZYU9iCxpM2yz3cyUmQRd8ccba4sfuU3eJ3kfZs8ythGDFh/wOqAg7KKViA5uwB7ZbGtX5ejEnmD05BpPhGIKyOceVe0RdR7W58vlE75FGKxCGZkhWLrAdV0DirCAoE5MiloWFTDBfpFoXa7SFIIV/47QXX4lG7jjbgb+uYDJgc7/rETuRnJwm/zZtQ4amKwoHk7KZB6EJ5ToUavnciHKlz+9jwkTuibaEQ9Z3HzP1ZfP2vAD95womjnsPC3sBq7mtUnWyIY9n1OgfsiL/QR2y8DgcAEAAA==)

![image](https://user-images.githubusercontent.com/11790765/185514119-2eb56580-44ae-4d19-8d50-739045521622.png)

**Comment by missymessa** [comment]
Should we turn this into a Known Issue?

**Comment by MattGal** [comment]
> Should we turn this into a Known Issue?

I'd say only if we can make those grep through the Helix (non-console) logs, otherwise it's indistinguishable from a crash or other non-test-failure failure.

**Comment by markwilkie** [comment]
> only if we can make those grep through the Helix (non-console) logs,

Which should be rolling out this week!

**Comment by MattGal** [comment]
No updates on the IcM, problem continues to (sporadically) occur for scenarios outside of the Arcade artificial TRX scenario.

**Comment by ChadNedzlek** [comment]
This problem started Aug 9, and has happened 3,000 times a day.  Hopefully we can get some traction there.  Given how "big" PR's are, even a small incidence of this bubbles up into a lot of failed PRs.

**Comment by ChadNedzlek** [comment]
Here's a chart showing how many jobs are impacted [Jobs impacted](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA12QTUvEMBCG7/0VQ08p7KGyeKwHbxUEZYU9iCxpM2yz3cyUmQRd8ccba4sfuU3eJ3kfZs8ythGDFh/wOqAg7KKViA5uwB7ZbGtX5ejEnmD05BpPhGIKyOceVe0RdR7W58vlE75FGKxCGZkhWLrAdV0DirCAoE5MiloWFTDBfpFoXa7SFIIV/47QXX4lG7jjbgb+uYDJgc7/rETuRnJwm/zZtQ4amKwoHk7KZB6EJ5ToUavnciHKlz+9jwkTuibaEQ9Z3HzP1ZfP2vAD95womjnsPC3sBq7mtUnWyIY9n1OgfsiL/QR2y8DgcAEAAA==)

It's nearly 300 builds a day, this is unacceptable and needs to be elevated.

**Comment by ChadNedzlek** [comment]
Quick chart (red is builds that crashed into this problem at least one):

![image](https://user-images.githubusercontent.com/11790765/185514119-2eb56580-44ae-4d19-8d50-739045521622.png)

**Comment by ChadNedzlek** [comment]
Update the description to reflect the current severity.

**Comment by markwilkie** [comment]
Shouldn't this be a sev2?  cc/ @Chrisboh 

Is it possible to have a known issue tracking the builds affected?  cc/ @ulisesh 

thanks a ton @ChadNedzlek for figuring the impact here

**Comment by Chrisboh** [comment]
Yeah Chad got us the data last night to confirm this is sev 2 and Stu is raising that now and getting on the bridge.

**Comment by ulisesh** [comment]
> Shouldn't this be a sev2? cc/ @Chrisboh
> 
> Is it possible to have a known issue tracking the builds affected? cc/ @ulisesh
> 
> thanks a ton @ChadNedzlek for figuring the impact here

Unfortunately, the error happens in the Helix client and test known issues is design to identify problems in the tests

**Comment by garath** [comment]
The team has evidence that the root cause is related to an incomplete fix for the problems described in dotnet/arcade#9865. They are rolling-back the fix, which should resolve this issue but, unfortunately, bring back the original. They will continue to treat as Sev 2.

**Comment by garath** [comment]
The rollback was successful, no hits on this over the weekend.

**Comment by MattGal** [comment]
This came back on 9/1/2022 and we didn't notice.  Reopening (@Chrisboh for visibility)

**Comment by MattGal** [comment]
It's back in dnceng-public so they asked me to file a new IcM as they claim the root cause is different (we can't tell; we get 500s).  Filed https://portal.microsofticm.com/imp/v3/incidents/details/335170304/home to track this

**Comment by MattGal** [comment]
I think I see the actual issue; created https://github.com/dotnet/arcade/issues/10916 to track this.

**Comment by MattGal** [comment]
Chad is pursuing https://github.com/dotnet/arcade/issues/10916 , closing this one in favor of that as it's a new variation.
