### ISSUE TITLE
Operationalize weekly image update tasks

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#10353]
# Goal

## Motivation and Business Impact

Today, there is a fair amount of work that has to happen to keep the images used in dotnet-helix-machines both up-to-date and maintain the promises made such as keeping images updated and the regular tick-tock of Visual Studio version updates for the "current" version.  

We would like to document this process and have it be handled by the new dncengopsvendors team. We have existing processes for the helix machines "end of life" policy and Artifact updating / end-of-life, this would represent an extension of these responsibilities. 

## Business Objectives

| Objective | ETA | Status |
| -----------|------|-------|
| P0: Visual Studio version update tick-tock and any new automation required is documented and run regularly by the vendor team | 10/01/2022 | Complete |
| P0: Azure Gallery base image update version work (and any new automation required) is documented and run regularly by the vendor team | 10/15/2022 | Complete |
| P1: Vendor team can generate rollout release notes for dotnet-helix-machines repo | 11/04/2022 | Complete |
| P1: Vendor team can generate rollout pull requests for dotnet-helix-machines repo | 11/04/2022 | Complete |

**Comment by garath** [comment]
I just went through image update today and wrote [this record](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/959/Regular-update-of-Helix-machine-images) of the steps I took. Hopefully it's a helpful starting point.

**Comment by tkapin** [comment]
There are few other docs relevant to this:
* [ImageFactoryCli README.md](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=%2Fsrc%2FImageFactoryCli%2FREADME.md&version=GBmain&_a=contents)
* [VS2022 Upgrade Schedule](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/899/VS2022-Upgrade-Schedule)
* [OSOB Rollout](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/561/-Needs-Updating-OSOB-rollout)

**Comment by jonfortescue** [comment]
Leaving this open until the vendor team successfully executes on rollout PR/release notes generation, but the work here is complete.
