### ISSUE TITLE
Unclear error on mobile platforms

### ISSUE THREAD

**Issue by karelz** [dotnet/arcade#10350]
Starting on 8/8, I have seen couple of failures in each Rolling run:

Run | Tests | OS | Details
-- | -- | -- | --
8/9 AM - [1931188](https://runfo.azurewebsites.net/view/build/?number=1931188) | System.Runtime.ReflectionInvokeEmit.Tests Work Item | net7.0-tvOSSimulator-Release-x64-Mono_Release-OSX.1200.Amd64.Open | Error: ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)
--"-- | System.Resources.Writer.Tests Work Item | net7.0-iOSSimulator-Release-x64-Mono_Release-OSX.1200.Amd64.Open | Error: ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)
8/8 PM - [1930413](https://runfo.azurewebsites.net/view/build/?number=1930413) | System.Threading.Overlapped.Tests Work Item | net7.0-iOSSimulator-Release-x64-Mono_Release-OSX.1200.Amd64.Open | Error: ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)
--"-- | System.Xml.RW.XmlWriterApi.Tests Work Item | net7.0-tvOSSimulator-Release-x64-Mono_Release-OSX.1200.Amd64.Open | Error: ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)
8/8 AM - [1929126](https://runfo.azurewebsites.net/view/build/?number=1929126) | System.Xml.Linq.Properties.Tests Work Item | net7.0-tvOSSimulator-Release-x64-Mono_Release-OSX.1200.Amd64.Open | Error: ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)
--"-- | System.Net.NameResolution.Pal.Tests Work Item | net7.0-Android-Release-arm-Mono_Release-Windows.10.Amd64.Android.Open
--"-- | System.Text.Json.Tests Work Item | net7.0-tvOS-Release-arm64-Mono_Release-OSX.1100.Amd64.AppleTV.Open

**Comment by premun** [comment]
Closing in favor of https://github.com/dotnet/arcade/issues/10351
