### ISSUE TITLE
Android devices lost internet connectivity

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#10367]
We should take high hitters from this query:
```sql
Metrics
| where EventType == "_MobileDeviceOperation" and MetricName == "NoInternet" and Timestamp > now()-7d
| join kind=inner WorkItems on WorkItemId
| extend Dimensions = parse_json(Dimensions)
| summarize NoInternet=count() by MachineName
```

These machines have devices that are offline:
- `DNCENGWIN-095`
- `DNCENGWIN-119`

**Comment by premun** [comment]
I offlined the machines

**Comment by oleksandr-didyk** [comment]
The corresponding DDFun incident -> https://portal.microsofticm.com/imp/v3/incidents/details/326729909/home

**Comment by premun** [comment]
Seems like DDFUN only checked for phone connection, not the WiFi connection which still doesn't work.

![image](https://user-images.githubusercontent.com/7013027/185072383-f2a540ea-df2c-44c9-a16a-e851a6ad3ca0.png)

I asked them to re-open the IcM

**Comment by premun** [comment]
AP was down. It was fixed as part of a different IcM - https://portal.microsofticm.com/imp/v3/incidents/details/327915531/home

Machines are back online
