### ISSUE TITLE
Make mobile device Helix timeouts more obvious in logs

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#10369]
### Context

When user workloads using XHarness SDK in Helix time out, it is not obvious from the logs that this happened and users then categorize the failure wrong.

The logs show this:
```
...
./xharness-runner.apple.sh: line 173: 99491 Terminated: 15          source command.sh
```

Which is the result of these lines:
https://github.com/dotnet/arcade/blob/fb7b35cf6d107a2d483b554b74c8b103820d5fb0/src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/xharness-runner.apple.sh#L173

https://github.com/dotnet/arcade/blob/fb7b35cf6d107a2d483b554b74c8b103820d5fb0/src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/xharness-helix-job.android.sh#L81

While we already have a human readable error for Android / Windows runs:

https://github.com/dotnet/arcade/blob/fb7b35cf6d107a2d483b554b74c8b103820d5fb0/src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/xharness-helix-job.android.ps1#L46

### Goal

Add a human readable error so that it's obvious that the run was terminated after it timed out.

**Comment by premun** [comment]
Hey **Triage**,
Can you please discuss how requests like these will be handled/triaged?

**Comment by riarenas** [comment]
@premun I might be missing something. What makes this request different that it needs to go to triage immediately without going through the asyc triage channel first?

**Comment by premun** [comment]
This is the first XHarness/Mobile device request basically, there's no epic, we hadn't really have to do this before

**Comment by riarenas** [comment]
That should be fine. I'm going to remove the label and have this go through the normal process first.
