### ISSUE TITLE
XHarness workloads should only rename `testResult.xml` instead of removing it

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#10371]
### Context
When client/SDK requests a work item retry because an infrastructural issue occurred, we remove the `testResults.xml` file so that it doesn't get uploaded to AzDO as we expect the future attempt will have a better one.

This happens here:
https://github.com/dotnet/arcade/blob/927f89f4f71d629c9ed08cb5bf0adfbb6bb51d66/src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/xharness-event-processor.py#L366-L372

### Problem
When devs are investigating the runs, it might happen that all 3 attempts fail and there's no `testResults.xml` so it might be beneficial to have the XML among the uploads for them to inspect.

### Goal
Either keep the file if we're on the 3rd attempt (not sure we can find this out from some env var), or just not delete the file and rename it so that it gets uploaded but not processed by the AzDO test reporter. When removing, be careful that the reporter looks for various forms of the `testResult` word so maybe verify how it matches it that you change it enough.

**Comment by karelz** [comment]
@akoeplinger when should we see this in runtime main?

I've had another hit in 9/8 AM Rolling build - [8501](https://runfo.azurewebsites.net/view/build/?number=8501) - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-24aa6b76899548ea86/System.Net.Sockets.Tests.Attempt.3/1/console.5d98ff68.log?%3Fhelixlogtype%3Dresult) - **System.Net.Sockets**.Tests Work Item

**Comment by akoeplinger** [comment]
@karelz this already hit dotnet/runtime main a while ago and looking at the build it worked, we now got the testResults.xml.retry files in the Helix artifacts.

The xml file(s) and the console log confirms that we hit an Android device that has no internet connection, we saw three retries but since they run on the same machine (DNCENGWIN-089) they all hit the same issue. It already got picked up by monitoring in https://github.com/dotnet/arcade/issues/10779. Someone from dnceng should disable the machine.

**Comment by karelz** [comment]
OK, Runfo unfortunately does not find the testResults.xml file and does not show the error :(

Here's another one: 9/5 AM Rolling run [4698](https://runfo.azurewebsites.net/view/build/?number=4698) - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-62aeb0f7b6f44ef2a1/System.Net.Sockets.Tests.Attempt.3/1/console.36341f79.log?%3Fhelixlogtype%3Dresult) - **System.Net.Sockets**.Tests Work Item - net7.0-Android-Release-arm-Mono_Release-Windows.10.Amd64.Android.Open - same machine DNCENGWIN-089

Can you please file issue to disable that machine?

**Comment by akoeplinger** [comment]
I've pinged Premek on the arcade issue.
