### ISSUE TITLE
[HOTFIX] Build analysis crashes using cached analyses

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#10384]

**Comment by missymessa** [comment]
See this thread here for context: https://teams.microsoft.com/l/message/19:72e283b51f9e4567ba24a35328562df4@thread.skype/1660167254502?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1659968580850&teamName=.NET%20Eng%20Services&channelName=Rollout&createdTime=1660167254502

**Comment by ulisesh** [comment]
Hotfix deployed 

PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/24767
