### ISSUE TITLE
Evaluate Cost of increasing Azure VM speed/availability

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#10397]
Our customers are experiencing a lot of pain (at least according to their feedback within our internal satisfaction survey) around the type of resources available to them within our engineering systems. This issue to track the work to evaluate the cost and benefits to our customers if we utilize some of the other types of technologies currently available within Azure. 

Some ideas: 
 - Spot VMs for additional capacity
 - Stateless agents to wait for helix jobs to complete
 - Moving repos with more workloads to different queues to unblock other workloads

At this point we are just looking to cost possible solutions and present them to leadership. 

cc: @Chrisboh

**Comment by garath** [comment]
@ilyas1974, this possibly has overlap with dotnet/arcade#8841. What do you think?

**Comment by ilyas1974** [comment]
I think this can be closed in favor of the other issue.
