### ISSUE TITLE
Pending Queue Insights Check Appears in Repos that don't have queue insights enabled

### ISSUE THREAD

**Issue by melotic** [dotnet/arcade#10416]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Currently, we post a pending check to Roslyn that Queue Insights is determining the CI pipelines, because we do not have a check to determine if they're an allowed repository. However, since the main Queue Insights Check has this allowed check, the real results never get posted and they are left with just the pending check.

We can:

1. Enable it in Roslyn
2. Check for allowed repos when posting the pending check

**Comment by riarenas** [comment]
This is happening places other than roslyn, such as dotnet/xharness, and that is causing undesired interactions with the maestro dependency update PRs: https://github.com/dotnet/xharness/pull/938/checks?check_run_id=7790720085

**Comment by riarenas** [comment]
This means we should probably do 2 anyways.

**Comment by ChadNedzlek** [comment]
Definitely agree, we shouldn't post the pending check if we aren't intending to actually do anything.

**Comment by riarenas** [comment]
Yep this should be fixed with this week's rollout.

**Comment by riarenas** [comment]
We now check for repos being in the allow list before deciding to post the pending check. https://github.com/dotnet/xharness/pull/940/checks?check_run_id=7899635493 didn't trigger a queue insights check for instance.
