### ISSUE TITLE
FR Tracking Issue: StorageErrorException when uploading

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10449]
https://portal.microsofticm.com/imp/v3/incidents/details/328063516/home

Thread: https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1660601291095?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1660601291095&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1660601291095&allowXTenantAccess=false

```
{
    "errorMessage" : "azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status"
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by missymessa** [comment]
We are attempting to raise the IcM to a sev 2.

**Comment by missymessa** [comment]
XStore team removed the service instance that our accounts were on out of rotation because it looked unhealthy, and it looks like that fixed the issue. We'll keep this issue open until EoD to monitor the issue and see if the fix sticks :)

**Comment by markwilkie** [comment]
Is it possible with these failures to add the known issue meta-data so we can tell how many builds this impacted?

**Comment by missymessa** [comment]
I'm attempting to set this up as a Known Issue as well as an critical infra issue. 

- I followed the instructions here to convert this into a Known Issue: https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/567/Dev-Design-Infra-Known-Issues
- The error messages are occurring in tests, which I think rolled out last week. Not sure if the steps to make this a Known Issue are different for tests.

**Comment by ulisesh** [comment]
You added the right labels to make the issue a Critical issue 😄 

I don't think we can use test known issues for this, the error is happens in the Helix client and for test known issues we only scan console logs for test known issues. Analyzing Helix client logs would increase the scope of the search significantly

**Comment by missymessa** [comment]
Looks like the API is behaving again and build aren't failing due to this error. Told the Storage devs we were good to mitigate the IcM and I'm going to close this tracking issue.
