### ISSUE TITLE
source.dot.net not indexing all projects

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#10468]
Issue originally reported in FR Channel conversation on [August 16](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1660675802920?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1660675802920&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1660675802920&allowXTenantAccess=false) and in issue dotnet/source-indexer#103. 

Specific example: The site's search function fails to find "System.String".

The previous nightly build [1946368](https://dev.azure.com/dnceng/internal/_build/results?buildId=1946368&view=results) shows no overt errors but poking through the binlogs finds exceptions indicating MSBuild... struggled.

This correlates to an increase of failed requests over Aug 16: [Link to App Insights](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4fc5514-21a9-4296-bfaf-5c7ee7fa35d1%2FresourceGroups%2Fsource.dot.net%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnetsourceindex/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA22NOw7DIBAF%252B5xiO0CyLZsi8nUAPwkKSLIsshLl8MEpXLl8H80wXg1V6u1LewSDJOWeXX6Sh%252BxA0ZsTHK1WdrZ2nNdxuStD00QXy6qM6azacnacPqDwaEW0If8mn4o%252B8QMt0Qz9GALqoWeUDfz3h%252BhYfiLvrlOaAAAA)

@alexperovich reconfigured the site to use an older (but complete) index that is still in storage, and also disabled the [indexing pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=612&_a=summary). So the site is working but static for now.

**Comment by missymessa** [comment]
@garath and/or @alexperovich do we know what work is needed to permanently source.dot.net so that it's current, or is investigation still needed?

**Comment by garath** [comment]
> do we know what work is needed to permanently source.dot.net so that it's current, or is investigation still needed?

Unfortunately, investigation is needed. There is some speculation in the Teams thread, but nothing concrete.

**Comment by MattGal** [comment]
chatted with @alexperovich and he's actively working on this, so I've assigned it to him.

**Comment by garath** [comment]
Looks like this is resolved!
