### ISSUE TITLE
aka.ms link creation ocassionally failing during Publish Assets stage

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#10469]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://dev.azure.com/dnceng/internal/_build/results?buildId=1888286&view=logs&j=4e900526-dc14-51b4-e135-b2939fefc210&t=49a49036-118d-5e1f-57be-0d55c06bab63

This appears to happen only occasionally. It could be an issue communicating with the aka.ms API, or perhaps something else.

**Comment by adiaaida** [comment]
I wonder if it is a throttling issue. Also, that's a weird one. It's in create client?

**Comment by adiaaida** [comment]
Tagging as FR as it could affect official builds

**Comment by alexperovich** [comment]
This error is a null ref inside the MSAL client libraries. There isn't anything we can do without updating the library to the newer stuff they have released. Without a binlog of the run that failed I can't investigate deeper. I will see if I can add uploading of the binlog do the job.

**Comment by alexperovich** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/25743

**Comment by alexperovich** [comment]
Extra logging has been merged. If this happens again we can investigate further.
