### ISSUE TITLE
Helix-service staging getting test failures in post-deployment tests

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#10479]
We are seeing 500 errors in the post-deployment tests unrelated the changes that have been checked in: https://dev.azure.com/dnceng/internal/_build/results?buildId=1947607&view=results

Looking into app insights, @MattGal found that we are seeing

```
DNS failure in System.Net.Sockets.SocketException at HelixAPI.Shared.AzureResourceHelper+<CreateStorageAccount>d__4.MoveNext
```

errors. AppInsights query: https://ms.portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fcab65fc3-d077-467d-931f-3932eabf36d3%2FresourceGroups%2Fdotnet-eng-int-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng-int/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA02Puw6CQBBFe77ihgoqscBCxYTYSGOMP0AWdpRNdlncR0Tjx4uQIM0kkzP3MZIcdFdwiwyBoYcn62zwwbMhQ6il9ry8aklnpghZhvDGKiPq7epEUvTTzC9FOEucUIMFUx32YHcdrdMmBmv5AhwmsGniWWXIeumOmo8haZIMxHqlmBFvAqrXUJIMc0K3ZcF3AfU1db%252Ft33V5AIgW0fhX%252FAVsDsjk4gAAAA%253D%253D

We likely need to just restart the int cluster to mitigate, but this may require further investigation

**Comment by MattGal** [comment]
I'll try the reboot real quick... the specific exception text was `No such host is known. (management.azure.com:443)`

**Comment by adiaaida** [comment]
@AlitzelMendez, post reboot, now we are getting an OctoKit failure in the build analysis tests. Can you help?

**Comment by missymessa** [comment]
Looks like Post Deployment tests are passing on Helix Services CI build again. Closing!

/cc @AlitzelMendez

**Comment by adiaaida** [comment]
Thanks Missy and Ali!
