### ISSUE TITLE
aspnet/Extensions official builds from VSTS (dev.azure.com/dnceng/internal)

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#1047]
Official builds on VSTS - https://github.com/dotnet/arcade/blob/master/Documentation/VSTS/MovingFromDevDivToDncEng.md
- [ ] Official builds are building in VSTS (dnceng)
  - [ ] Using YAML
  - [ ] Referencing [base.yml](https://github.com/dotnet/arcade-minimalci-sample#base-your-builds-on-arcade-for-ease-of-use)

**Comment by natemcmaster** [comment]
Official builds come out of dnceng now. Using https://github.com/dotnet/arcade/issues/1046 to track using the arcade yml templates instead of our own.
