### ISSUE TITLE
Need method for sharing js packages 

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#105]
Sharing nuget packages is straightforward, but we should also provide some story for how to share .js packages.  npm?

**Comment by maririos** [comment]
@jcagme this will be covered by Maestro++, right?

**Comment by alexperovich** [comment]
This is more like creating package feeds, but npm rather than nuget. The task here is creating "blob" feeds for npm packages and a way to publish package to them.

**Comment by jcagme** [comment]
Yeah I think Alex is correct. Maestro would update the dependency of a npm package only (like the version for example) then something like 'sync.cmd' would know that a npm package has to be restored from 'foo' feed.

**Comment by maririos** [comment]
thanks for the clarification guys!

**Comment by maririos** [comment]
> we should also provide some story for how to share .js packages. npm?
@markwilkie who will use it or benefit if we implement this?

**Comment by markwilkie** [comment]
If anyone, it'd be ASP who would use it the most. 

@natemcmaster - worth doing?

**Comment by natemcmaster** [comment]
This would make @anurse happy but I don't think its high priority. We currently use myget.org for daily builds of our npm packages, but we only use that share bits with customers. It's not necessary for us to transport bits between teams or legs of the build.

**Comment by markwilkie** [comment]
closing due to low priority
