### ISSUE TITLE
When on macOS please append sw_vers to the first line of Helix logs

### ISSUE THREAD

**Issue by danmoseley** [dotnet/arcade#10500]
The first line of the Helix log is a super useful place to find info about the job/workitem and configuration. It's easy to paste into issues. 

Recently we added the output of Python's `platform.platform()` to the first line of the Helix logs, so we could see the "real OS configuration". It turns out this uses mac_ver() which lies:

```
Console log: 'System.Net.Security.Tests' from job afed2094-0e40-4bd4-a0ee-55fa1b2cc3d1 workitem b1b033f0-1b26-438c-bff4-e307225d6774 (osx.1200.amd64.open) executed on machine dci-mac-build-316.local running macOS-10.16-x86_64-i386-64bit
```
Here the OS is macOS 12, but it's saying 10.16.

The source of truth is  `/usr/bin/sw_vers -productVersion ` -- on this machine it will give 12.4 (note, this is better info than the queue name, as well as being a check on the queue configuration)

Please append the output of  `/usr/bin/sw_vers -productVersion ` when on macOS. We should keep `platform.platform()` for non Mac (I don't care if it's still there on Mac and we ignore it)

cc @MattGal

**Comment by danmoseley** [comment]
Actually why not include all of `sw_vers` .. it's not much in size and might be useful (eg it includes build number and that might help track an unpatched box)

**Comment by danmoseley** [comment]
Past issue: https://github.com/dotnet/arcade/issues/10099

**Comment by MattGal** [comment]
Tossed onto FR backlog.

**Comment by adiaaida** [comment]
PR for this is here: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/25344

**Comment by adiaaida** [comment]
This has rolled out
