### ISSUE TITLE
Report merge on red reasons

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#10504]
I am splitting this issue: https://github.com/dotnet/arcade/issues/9954
so we can work on the report first and then we can have the discussion about the label, implications, etc.

**Comment by AlitzelMendez** [comment]
@markwilkie @missymessa 

This is a first draft for this:
![image](https://user-images.githubusercontent.com/6895254/185514656-0e66f287-895e-4c03-97b9-9504327488d7.png)

please let me know what information you want to see or in which way :)

there are just a couple of records because we started collected the data Yesterday

**Comment by markwilkie** [comment]
Thanks Ali!  This is super cool.

Is my assumption correct that we're only really able to compare a count of known issues with a count of build/test failures?  In other words, probably not possible to directly correlate each build/test failure with a known issue?

The end goal is to track how many merge-on-red PRs were merged without known issues tracking each failure.  If the best we can do is a numerical compare, then so be it.  

The end report could be something like the existing merge-on-red bar chart, but with the dark blue being just the merge on reds, and the light blue being those which did not have known issues tracking.

Happy to chat in person if that's helpful.

**Comment by missymessa** [comment]
Agree with what Mark is saying. Probably do a stacked bar chart for all PRs that have merged on red in that given timeframe, and then differentiate between those that merged on red without known issues and then those with known issues. 

Additionally, if possible, clicking on one of the parts of the bar would give us a list of the PRs that fell under that criteria in the event folks want to deeper dive into PRs that merged on red without known issues to see what was going on with them. (But I'm not sure how possible that is to do in PowerBI).

**Comment by AlitzelMendez** [comment]
@markwilkie yes, on this graph I am only showing counts, the counts are actual number of build errors and test errors that didn't have a match on a known issue.

But we have the builds ids so if we need to, we can correlate the known issues count with actual known issues failures but for the build failures without known issues we don't have the data of which was the failure, as you said we can have a call!! 

al for the rest, I will do the changes that you suggested.

@missymessa I am positive we can do that on power bi :)

**Comment by markwilkie** [comment]
This is interesting for sure.  The primary goal however is to track merge-on-red where all the failures don't have a matching known issue.  That's the graph I'll take to tactics and the M2's.

**Comment by AlitzelMendez** [comment]
so I just should remove the other categories?

because what the graph is showing, which probably I need to rephrase, is the status of the pull request when it was merged so it has the follow categories:

-  **Unique test/build errors** : At least one of the failures on the pull request is unique to this pull request 
-  **Known issues**: All the errors were known issues (GitHub known issues or shared with target branch issues)
- **Unknown**: We cannot determine if all the issues were known issues or unique issues

I can totally delete the other categories and just show the pull request with unique failures and remove all the others.

**Comment by AlitzelMendez** [comment]
talked with Mark and added a line with the percentage of pull request that have been merged with only known issues since we started capturing the necessary data (a little bit over a week) and it's 0% but we have the number now :)




![Image](https://user-images.githubusercontent.com/6895254/186793503-fab416ba-1276-4986-ba7c-af53f958c197.png)

**Comment by markwilkie** [comment]
woo hoo!    :)

**Comment by AlitzelMendez** [comment]
published :)
