### ISSUE TITLE
Code preventing work items from being retried during a timeout not working

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10515]
@ChadNedzlek has been investigating this issue: 

> Ah. That code doesn't work for the "_send_metadata" call, which always happens now, so we effectively neutered the previous code, and are back to the turning every timeout into a timebomb.

Teams thread: https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1660935003543?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1660935003543&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1660935003543&allowXTenantAccess=false

This causes a cascade failure problem, because as soon as a _single_ build timeout, the work in the queue immediately triples (since future builds end up stuck behind the triplicated work, also triplicating themselves). So it's fairly high severity when it happens.  It _only_ happens when a queue gets backed up, but it basically ensures the queue STAYS backed up until there are several hours of downtime.

**Comment by missymessa** [comment]
Putting this in FR as it was reported in FR.

**Comment by ChadNedzlek** [comment]
It looks like we have code that handles errors for sending the test results or the attachments with the "_send" helper, but we aren't using that in the "_send_metadata" path, so it's not turning into a "TERMINAL_ERROR", so we retry.  That's bad.

The code is in the "azure_devops_result_publisher.py".  I think we just need to change all the direct calls to the clients into using the "_send" method in the class to catch and wrap the exceptions nicely, so that they get handled at the outer layer correctly.

**Comment by garath** [comment]
Any measure of the impact this has to customers?

**Comment by missymessa** [comment]
> Any measure of the impact this has to customers?

@davidwrighton has reported that the ubuntu.1804.armarch.open queue is completely overwhelmed, which lead to Chad discovering the cause of it.

**Comment by ChadNedzlek** [comment]
We've retried nearly 15,000 workitems in the last 24 hours on this queue.  A quick spot check shows them all to be because of this, I think.  So it's causing PR's to timeout on this queue, because we are just endlessly redonig dead work (causing future work to ALSO die... exacerbating the problem)

**Comment by garath** [comment]
> A quick spot check shows them all to be because of this, I think.

Any queries worth sharing?

**Comment by ChadNedzlek** [comment]
Mostly just digging into logs of anything that has "Attempt > 1" in the Workitems table.

**Comment by garath** [comment]
[Oof](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/queues/queue-monitor?orgId=1&refresh=30s&var-QueueName=ubuntu.1804.armarch.open&var-UntrackedQueues=%22osx%22%2C+%22perf%22%2C+%22arm%22%2C+%22arcade%22%2C+%22xaml%22%2C+%22appcompat%22&from=1660895859483&to=1660939059484&viewPanel=12)

![image](https://user-images.githubusercontent.com/2303549/185697693-5d25bbfa-56e1-4abd-9e8f-5f79d289eaf2.png)

**Comment by missymessa** [comment]
What happened at 9am?!?! :D

**Comment by ChadNedzlek** [comment]
This problem causes a cascade failure.  Job 1 times out... and therefore runs three times, causing basically every job behind it to do the same thing. As soon as a _single_ build times out, the load on the queue instantly triples, drowning it.

**Comment by garath** [comment]
PR to make that path retry more smarter: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/25208

**Comment by garath** [comment]
Rolled-out today!
