### ISSUE TITLE
Handle TaskCancelledException in Arcade SDK "DownloadFile" Task

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#10534]
As seen here: https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/src/DownloadFile.cs#L123 
We retry for OperationCancelled but not TaskCancelled.  We should handle both scenarios for when network connections are flaky and hit Http Client timeouts (this can be surfaced as a TaskCancelledException)

**Comment by MattGal** [comment]
Per @mmitche : I wonder whether the built in task [DownloadFile Task - MSBuild | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/downloadfile-task?view=vs-2022) would be a good replacement for our task.

**Comment by MattGal** [comment]
Created https://github.com/dotnet/arcade/pull/10542

**Comment by MattGal** [comment]
PR merged, will leave in Validate for a day or two to remind myself to check in on the change flowing.

**Comment by riarenas** [comment]
Is this trying to fix builds such as these? https://dev.azure.com/dnceng/internal/_build/results?buildId=1960569&view=results (it looks like it)

If so, I think we'll need to flow this change manually to the 'latest' engineering channel, as automated promotions of arcade are currently blocked on the installer repo being broken. (see https://github.com/dotnet/arcade/issues/10546 and family)

**Comment by MattGal** [comment]
> Is this trying to fix builds such as these? https://dev.azure.com/dnceng/internal/_build/results?buildId=1960569&view=results (it looks like it)
> 
> If so, I think we'll need to flow this change manually to the 'latest' engineering channel, as automated promotions of arcade are currently blocked on the installer repo being broken. (see #10546 and family)

It is, but I'd wager this is an intermittent behavior caused by Http Client timeouts, so it should succeed eventually no?

**Comment by MattGal** [comment]
Closing as this is just a robustness change and the linked issue is closed.
