### ISSUE TITLE
Enable VMR sync from non-GitHub remotes

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#10549]
## Context

Currently, the code supports synchronization from GitHub public repos. It should be easy to add support for AzDO / private GitHub repositories as the code from DarcLib that it's using is prepared for that.

## Goals
- Figure out how to wire the appropriate tokens to the `IRemoteFactory` and make it decide based on the URI what remote it should create.
- Enable overriding the remote in source-mapping (?)

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Not notes-worthy

**Comment by MilenaHristova** [comment]
### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Enabled VMR sync from non-GitHub remotes

**Comment by premun** [comment]
@MilenaHristova you need to put this in the description

**Comment by premun** [comment]
I will re-open this and increase the scope of this.

We should also make sure that things like commit message make sense (we are putting there links to GitHub commits and those will have a different format in AzDO for instance).

Re-opening this until we actually try that AzDO sync works and we tested everything.

**Comment by MilenaHristova** [comment]
I tried initializing `sdk` from AzDO, it works and the correct URL is written in `source-manifest`. For now the commit link is taken from `DefaultRemote` so it's not correct but we can change that in https://github.com/dotnet/arcade/issues/11912
