### ISSUE TITLE
[Tracking] Consider renaming "up-for-grabs" label to "help wanted"

### ISSUE THREAD

**Issue by mairaw** [dotnet/arcade#10543]
Using the default label name is especially recognized by GitHub and we're trying to get a consistent experience for newcomers. See context at https://github.com/dotnet/runtime/issues/71496

I also couldn't find the label called **good first issue**.

You should also consider adding the project to https://up-for-grabs.net/
See an example PR at https://github.com/up-for-grabs/up-for-grabs.net/pull/3329

/cc @danmoseley

**Comment by markwilkie** [comment]
oh cool - this is a good idea

**Comment by adiaaida** [comment]
I'm fine with this change. We'd need to update the label and the update the async triage tool to ignore `help wanted` labeled issues instead of (or in addition to during transition) `up-for-grabs`

**Comment by Chrisboh** [comment]
Fixed

**Comment by adiaaida** [comment]
Did you update the project board and the async triage tool too?

**Comment by adiaaida** [comment]
I updated the board and made the code change in https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/26977
