### ISSUE TITLE
Dump collection broken on windows.10.arm64v8.open machines

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#10540]
As reported by @mangod9 in Teams, all but 15 of these machines are not currently taking core dumps when processes crash.  I am checking out a few examples and will attempt to fix them shortly.

**Comment by MattGal** [comment]
I updated 122 of 126 machines to have working core dump settings for ARM64 processes, and have this ticket open to fix up the rest:

https://portal.microsofticm.com/imp/v3/incidents/details/329766967/home  (Some of the machines were stuck rebooting)

**Comment by MattGal** [comment]
All machines should be capable of making dumps now (2 will likely need reimaging) and I verified that dumps are being uploaded by a majority of machines, closing.

**Comment by mangod9** [comment]
Thanks @MattGal for your help on this. @dotnet/crossgen-contrib -- hoping this will help with capturing some win arm64 crashes.
