### ISSUE TITLE
Cost/Benefit analysis for technical debt for arcade-services

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#10554]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Cost/benefit analysis for https://github.com/dotnet/arcade/issues/8836

**Comment by premun** [comment]
I am personally curious/invested in this as I started adding new functionality to `DarcLib` (with new commands in `darc.exe`) - I am adding new commands for managing the VMR (I also use DarcLib in installer in an MSBuild task). I expect to have more and frequent changes in the coming months.

What is unclear to me in the original issue - how should we deal with the dependencies between the various things if we split them. For example, I am not sure I agree with putting `darc.exe` to arcade. Seems like both `Maestro` and `darc.exe` are heavily reliant on `DarcLib` which they basically wrap so it seems it's a bit counter-productive to split them to different repositories.

Can we, instead, consider not splitting the code but maybe splitting the pipelines connected to the repo (e.g. Azure services get their own deployment pipeline)? Maybe we can express the different life-cycle of the various things by doing that?

Additionally, I am fighting some debt (e.g. https://github.com/dotnet/arcade-services/pull/1965) within the `DarcLib` itself where we strongly couple BAR with Azure/GH git clients in a very cumbersome way.
There is a lot of good code in `DarcLib` for working with remote/local repositories but the way the code is organized makes it very hard to re-use it. I will probably deal with some of this debt later regardless of whether we will decide to do this epic or not.

I am happy to chat about this some more.

**Comment by riarenas** [comment]
@premun and I did a write-up for this and stuck it in the epic: https://github.com/dotnet/arcade/issues/8836#issuecomment-1242351132
