### ISSUE TITLE
Need to reduce Kusto usage in engsrvprod

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#10558]
As part of investigating https://github.com/dotnet/arcade/issues/10553, I found lots of Kusto connection problems, bursting in the time of the slow API responses.  I followed up with the Kusto team and they were fairly shocked by our usage patterns. 

We need to discuss this so I am marking with the "Needs Triage" label to discuss this week.  Also tagging @ChadNedzlek in case he wants to pile on any useful data.

Relevant IcM ticket: https://portal.microsofticm.com/imp/v3/incidents/details/329798643/home

Below shows how much time our top 11 usages use (in _Days.Hours:Minutes:Seconds.Fractional_ format).  I am taking steps presently to significantly reduce what AutoScaleActorService does (should be able to get it under 2 days usage per 10 days) but we are now regularly hitting API timeouts and being either throttled or straight up rejected by Kusto for new connections.

```
.show queries 
| where StartedOn > ago(10d)
| summarize sum(Duration) by Application
| order by sum_Duration desc 
```

| Application | sum(Duration) |
| - | - |
| HelixAPI | 74.03:56:30.1595755                    |
| AzureDevOpsTestAggregation | 40.21:06:08.2427345  |
| AutoScaleActorService | 11.01:12:21.4480691       |
| Grafana-ADX | 2.07:25:49.2973983                  |
| BuildResultAnalysisProcessor | 1.17:16:38.2120386 |
| MetricsObserver | 17:04:20.0776551                |
| DependencyUpdater | 05:53:59.1044860              |
TestDataAggregationService | 02:40:14.3751389
KnownIssuesMonitor | 02:36:19.1245124
Maestro.Web | 02:08:57.9728915
SQLCleaner | 01:40:15.5044311

Checking out a 30-day period:
```
.show queries 
| where StartedOn > ago(30d)
| summarize sum(Duration) by Application, bin(StartedOn, 1d)
| render  timechart 
```
... we see that the Helix API and Azure Devops Test aggregation are both moving up in the past couple weeks.  

![image](https://user-images.githubusercontent.com/7862010/186275948-7e8e4a8e-7524-44e4-a0d1-761757306bfe.png)

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/25239 should 1/9th the usage by the AutoscaleActorService (number 3 on the list)

**Comment by ChadNedzlek** [comment]
The API usage is shockingly high... Who's calling it so much? The "is this job done" call shouldn't be that expensive...

**Comment by missymessa** [comment]
I had to...

![image](https://user-images.githubusercontent.com/47990216/186279263-e81c54c1-3d42-4e5e-81fc-9ff7446d3d90.png)

(sorry, not sorry)

**Comment by ChadNedzlek** [comment]
The AutoScale thing REALLY needs to not query every queue individually, it should be faily easy to drop it's usage by like 99% by making the queries in bulk up front.

**Comment by riarenas** [comment]
The top two are so overwhelmingly above the rest that it seems like even if we reduce everything else, it's still too much? 111 days of usage per 10 days is a lot.

**Comment by garath** [comment]
Can certainly reduce Grafana's use by auditing the alert queries. Certainly there are many that don't need to query as often as they are. I'm also curious if the heavy Grafana queries are interesting at all.

**Comment by AlitzelMendez** [comment]
I think that for AzureDevOpsTestAggregation we can improve one of the queries (the most expensive one) I will open an issue and work on that

**Comment by riarenas** [comment]
I'm not surprised, but it looks like QueueInsights queries make up a lot of the most costly queries from the BuildResultAnalysisProcessor and we'll have to revisit them, or consider serving cached information instead of querying it live for every PR.

**Comment by ChadNedzlek** [comment]
We should use "Cpu" usage and not necessarily duration. A lot of the HelixAPI have long durations... but only because the cluster was overloaded by other queries. (If you run some queries that took 3 minutes earlier, they only take 0.3 seconds now).

**Comment by MattGal** [comment]
> We should use "Cpu" usage and not necessarily duration. A lot of the HelixAPI have long durations... but only because the cluster was overloaded by other queries. (If you run some queries that took 3 minutes earlier, they only take 0.3 seconds now).

Good point but I think we care about both equally because connections get limited and are considered in throttling / failure to connect scenarios.   One thing we can also consider is scaling out, though not until budget considerations are more settled.

**Comment by markwilkie** [comment]
This is a great discussion

**Comment by ChadNedzlek** [comment]
I wonder if it's not JUST kusto usage, but actual SF node usage too.  If some node is burning the network down trying to fetch all these files, any other network request that node makes (like, say, if the Helix API is running on that node and trying to talk to SQL/Kusto at the time), is going to get slowed WAY down.

I think our service might be growing complex enough that just having one node type that runs whatever it feels like might not be working anymore.   @alexperovich, thoughts?

**Comment by ChadNedzlek** [comment]
Note: That might also solve our capacity problem, because the other node types could be of a machine that has more/better capacity, so we can move some of the overly expensive node workloads there to free up the frontend processing power.

**Comment by alexperovich** [comment]
The node capacity and metrics thing we have should be placing the hungry services separate from each other. A second node type is quite a bit more complex to do, but gives a way to force isolation. We need to make sure that every service that may kill the network has the proper metrics set.

**Comment by ChadNedzlek** [comment]
The problem is our node are over 100% network metric, so it's basically unable to actually isolate them. And no service we have is zero network, so they might always end up on a node that's heavy network usage. Like the API doesn't use a LOT of network.  But if it ends up on a node doing 100% network, it's going to end up being sluggish.  The only way would be if the network heavy services didn't get ANY other services on them... but that's not really an option with our current set up.

**Comment by ChadNedzlek** [comment]
It feels like we sort of need backend services, where throughput is key (for things like the analysis processor), but then frontend services where responsiveness is key.  That's tricky to do I think with only a single node type.

**Comment by alexperovich** [comment]
Yea, that would make sense as a split of node types

**Comment by garath** [comment]
Significant improvement happened in dotnet/arcade#10600.

**Comment by ChadNedzlek** [comment]
Between that and @MattGal and @AlitzelMendez changes, I think we are probably in a good spot to resolve this after the rollout. Ali's change should make the spikes every 5 minutes less spiky, and my change reduced the size of the data all up, and Matt reduced the frequency of spikes caused by the scaler.

**Comment by MattGal** [comment]
This usage all fell off a cliff starting in September, so I am closing the issue.  Great work, everyone who contributed an improvement!

![image](https://user-images.githubusercontent.com/7862010/189716055-369e6bfa-136c-4bc1-8a8c-f9928055317f.png)

**Comment by garath** [comment]
FYI AutoScale brought the prod cluster down to its minimum of two instances on September 1 (it was 5 instances at peak).

```json
"properties": {
  "Description": "Optimized Autoscale attempting to scale resource from 3 instances count to 2 instances count.",
  "ScaleReason": "CacheUtilization, CPU, IngestionCapacity, StreamingIngestion and SealsLoadFactor are low",
},
```

Good job everyone on getting those Seals under control!
