### ISSUE TITLE
wix.targets Builds failing with exit code 103

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#10562]
A customer reported having a build failing with exit code 103. https://github.com/dotnet/windowsdesktop/pull/3114#issuecomment-1225012209. I'm not familiar with this so I'm not sure where to even start. Failing build: https://dev.azure.com/dnceng/public/_build/results?buildId=1962423&view=logs&j=fdea2036-e6b2-512d-a259-98f88c972586&t=af096630-56f5-5928-33b7-4066f690cbe3

**Comment by adiaaida** [comment]
@mmitche has this been fixed with your work to help them on the linked PR?

**Comment by mmitche** [comment]
@adiaaida Possibly? I don't think I helped specifically with that error, but it passed.

**Comment by adiaaida** [comment]
As the build is now passing, I am going to close this issue. If it returns, we can investigate then
