### ISSUE TITLE
Help teams move servicing builds to -Svc NetCore1ES pool providers

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#10578]
As a push to relieve some pain from release builds (and, indirectly, main builds) I've opened the following PRs to release branches which are not using "-Svc-" pool providers.  

```
let builds=
BuildTimelineRecord
| where OrganizationName == "dnceng"
| where Type == "Job"
| where ProjectId == "9ee6d478-d288-47f7-aacc-f6e6d082ae6d"
| where WorkerName startswith "NetCore1ESPool-Public"
| distinct BuildId;
Build 
| where OrganizationName == "dnceng"
| where FinishTime > ago(7d)
| where BuildId  in (builds)
| where SourceBranch contains "release"
| summarize arg_max(BuildId,*) by RepositoryId
```

### Interactive:
- [ ] release/jupyter: https://github.com/dotnet/interactive/pull/2305

### Arcade: 
- [x] 6.0: https://github.com/dotnet/arcade/pull/10572 (pending)
- [x] 3.x: Not needed

### AspNetCore:
- [x] release/7.0-rc1 : https://github.com/dotnet/aspnetcore/pull/43528 (Closed in favor of https://github.com/dotnet/aspnetcore/pull/43529)
- [x] release/7.0     : https://github.com/dotnet/aspnetcore/pull/43529 (merged)

### EFCore:
- [x] release/7.0     : https://github.com/dotnet/efcore/pull/28873
- [x] release/7.0-rc1 : https://github.com/dotnet/efcore/pull/28874

### dotnet/fsharp : 
- [x] release/dev17.4 : https://github.com/dotnet/fsharp/pull/13779

### Installer:
- [x] release/7.0.1xx-rc1 : not needed
- [x] release/7.0.1xx     : https://github.com/dotnet/installer/pull/14392
- [x] release/6.0.4xx     : not needed
- [x] release/6.0.1xx     : not needed

### dotnet/llvm-project
- [x] dotnet/release/7.0  : https://github.com/dotnet/llvm-project/pull/255

### dotnet/roslyn :
- [ ] release/dev17.4          : https://github.com/dotnet/roslyn/pull/63584
- [ ] release/dev17.3          : https://github.com/dotnet/roslyn/pull/63585
- [x] release/dev17.0-vs-deps  : Already done

### dotnet/runtime:
- [x] 7.0-rc1: https://github.com/dotnet/runtime/pull/74521

### dotnet/sdk
- [x] release/7.0.1xx-rc1 : https://github.com/dotnet/sdk/pull/27425
- [x] release/7.0.1xx     : https://github.com/dotnet/sdk/pull/27426
- [x] release/6.0.4xx     : not needed
- [x] release/6.0.3xx     : not needed
- [x] release/6.0.1xx     : not needed

### dotnet/templating
- [x] release/7.0.1xx-rc1 : https://github.com/dotnet/templating/pull/5154
- [x] release/7.0.1xx     : https://github.com/dotnet/templating/pull/5155
- [x] release/6.0.4xx     : already done
- [x] release/6.0.3xx     : already done

### dotnet/windowsdesktop
- [x] release/7.0-preview7 : https://github.com/dotnet/windowsdesktop/pull/3123

### dotnet/winforms
- [x] release/7.0      : https://github.com/dotnet/winforms/pull/7659
- [x] release/7.0-rc1  : https://github.com/dotnet/winforms/pull/7660

### dotnet/wpf:
- [x] release/7.0     : https://github.com/dotnet/wpf/pull/6947
- [x] release/7.0-rc1 : https://github.com/dotnet/wpf/pull/6948

### Release Note Description
Internal alerting changes - Does not need release notes

**Comment by dagood** [comment]
> As a push to relieve some pain from release builds

I currently happen to be working on a change that will make microsoft/go builds consistently (automatically) use the Svc pool in release branches, but I'm curious what this means. Is it internal pain, or will something be different on the repo side?

(Maybe https://github.com/dotnet/arcade/blob/main/Documentation/AzureDevOps/AzureDevOpsOnboarding.md#agent-queues could be updated to include the "why"?)

**Comment by MattGal** [comment]
@dagood All I meant by pain there is that the builds trying to go through the "normal" public pool are bottlenecking while the -Svc pool, while having fewer maximum machines, is significantly less busy.  Lots of folks trying to get out 7.0 RC1 builds were hitting this.

**Comment by dagood** [comment]
I see, thanks. 😄 Wasn't aware `Svc` vs. non`Svc` pools actually had different sets of machines--makes sense.

**Comment by akoeplinger** [comment]
I agree we should use the `Svc` pool automatically for all `release/*` branches, maybe we can add some common variable .yml to eng/common so repos can just use that rather than copying the logic around.

**Comment by MattGal** [comment]
Checked in today, https://github.com/dotnet/fsharp/pull/13807 was the only new change to make.  All the others I saw were either branches that were being deleted being run scheduled, or repos' Source Build tasks (need arcade updates to change).

**Comment by MattGal** [comment]
Found some more.  New PRs for moving to SVC made today:

  https://github.com/dotnet/emsdk/pull/210
  https://github.com/dotnet/llvm-project/pull/274
  https://github.com/dotnet/msquic/pull/112
  https://dnceng.visualstudio.com/internal/_git/dotnet-wpf-int/pullrequest/25664

I've also made sure that the changes are in arcade release/7.0 and all active subscriptions have been triggered.

**Comment by MattGal** [comment]
Getting slowly better all the time. What remains today:

![image](https://user-images.githubusercontent.com/7862010/189700342-619cda18-8bdf-46fd-85dc-7efacc80d056.png)


- AspNetCore has not taken rel/7.0 arcade update due to changed compiler warnings (https://github.com/dotnet/aspnetcore/pull/43880)
- FSharp needs to update arcade in the release/dev17.4 branch
- Various small repos still need arcade rel/7.0 updates

**Comment by MattGal** [comment]
- [x] dotnet/source-build-reference-packages - release/7.0 - https://github.com/dotnet/source-build-reference-packages/pull/456 
- [ ]  dotnet-source-build-externals	refs/heads/release/7.0	https://github.com/dotnet/source-build-externals/pull/53 
- [ ] dotnet-dotnet-monitor	release/7.x https://github.com/dotnet/dotnet-monitor/pull/2619

**Comment by MattGal** [comment]
Update:

dnceng-public	public	dotnet/fsharp	release/dev17.4
dnceng-public	public	dotnet/fsharp	release/dev17.5
dnceng-public	public	dotnet/roslyn	release/dev17.4

These branches use arcade main - for free -Svc pool provider usage, recommended to move to release/7.0 - I will start work on making arcade switch automatically on SourceBranch, and reach out to these teams letting them know it'd be nice to move to a release branch of arcade.

dnceng-public	public	dotnet/templating	release/7.0.2xx
https://github.com/dotnet/templating/pull/5476

dnceng-public	public	dotnet/sdk		release/6.0.1xx
https://github.com/dotnet/sdk/pull/28638

dnceng-public	public	dotnet/sdk		release/6.0.3xx
https://github.com/dotnet/sdk/pull/28641

**Comment by MattGal** [comment]
Today's updates:


### dotnet-sdk	

  Branch: release/6.0.1xx
  PR: https://github.com/dotnet/sdk/pull/28744

  Branch: release/6.0.3xx
  PR: https://github.com/dotnet/sdk/pull/28745

### dotnet-dotnet-docker	

  Branch: internal/release/nightly
  PR: https://dnceng.visualstudio.com/internal/_git/dotnet-dotnet-docker/pullrequest/27027

### dotnet-roslyn	
  Branch: release/dev17.2
  PR: https://github.com/dotnet/roslyn/pull/64950 (rest will be hit by arcade update)

### dotnet-fsharp
  Branch: release/dev17.5
  PR: https://github.com/dotnet/fsharp/pull/14168 (sent to main)

**Comment by MattGal** [comment]
Some more today:
- [ ] dotnet-interactive	refs/heads/release/rename	2031916 https://github.com/dotnet/interactive/pull/2409 
- [ ] dotnet-windowsdesktop	refs/heads/release/7.0	2031787 - https://github.com/dotnet/windowsdesktop/pull/3285 
- [ ] dnceng-public	dotnet/Scaffolding	refs/heads/release/7.0 - https://github.com/dotnet/Scaffolding/pull/2068 (merged)
- [ ]  dnceng-public	dotnet/Scaffolding	refs/heads/release/6.0 - https://github.com/dotnet/Scaffolding/pull/2067 (merged)

**Comment by MattGal** [comment]
Yet more:
- [ ] dotnet-machinelearning	refs/heads/release/2.0	https://github.com/dotnet/machinelearning/pull/6434
- [ ] dotnet-Scaffolding	refs/heads/release/7.0 https://github.com/dotnet/Scaffolding/pull/2068 (already merged)
- [ ] dotnet-sdk	refs/heads/internal/release/6.0.1xx https://github.com/dotnet/sdk/pull/28744
- [ ] dotnet-templating	refs/heads/internal/release/3.1 https://github.com/dotnet/templating/pull/5563
- [ ] dotnet-toolset	refs/heads/internal/release/3.1.4xx	 https://github.com/dotnet/toolset/pull/5195
- [ ] microsoft-reverse-proxy	refs/heads/release/latest https://github.com/microsoft/reverse-proxy/pull/1922/files

**Comment by MattGal** [comment]
I am reducing the number of repos we monitor via https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/27501?_a=files which should still catch the vast majority of (non-Roslyn) builds that get sent to the wrong place.  After reducing the query, we should be green now and covered by the alerts.
