### ISSUE TITLE
Don't require storing "locked" files in eng/common/ 

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1059]
Every repo using Arcade is supposed to have a `eng/common/` folder, and is not supposed to touch the files in this repo. There are currently 38 files in this folder, and is expected to grow. This was done for some good reasons that I'd like to acknowledge before pointing out the problems:

* Bootstrapping. You need _something_ in the repo.
* Uniformity. Everyone using Arcade has the same templates and scripts.

The problem with having so many duplicate files scattered around is:

* The need to synchronize changes to these files. This means Darc needs to handle all the possibilities: deleted files, renamed, modified, created, etc.
* Cannot restrict editing these files. Nothing we can do will stop people from changing them. We can educate our contributors, but its inevitable the files will get customized, intentionally or not.
* Customization to these files are at risk of being lost. If someone needs to tweak one of the files, the next Maestro++ update will open a PR to blow away the change.
* Cannot force people to accept updates to the files. If someone has to customizes the files, ideally they contribute fixes back to arcade. But that's not reasonable or always possible. Likewise, if we make changes that break someone's repo, we cannot force them to accept a PR to put the files back to a clean state and therefore break there build.

For context: we (the aspnet team) used to have this problem. The scenarios I've just mentioned are not hypothetical --- it's what happened to us several times.

## Proposal

Remove all "locked" files from eng/common/. There will be some amount of boilerplate code in each repo, but this can be reduced by making Arcade's scripts and YML config an API instead of requiring they be duplicated into all repos.

#### 1. Make Arcade's scripts and tools an "API" that get's called by a single bootstrapper script.

Arcade is a producer of APIs, and the repos are consumes of these APIs. This pattern can be implemented like this:

The producer (arcade):
* Creates a zip of the scripts: "Arcade.Scripts.$(version).zip"
* Uploads it to https://dotnetfeed.blob.core.windows.net/dotnet-core/arcade/$version/Arcade.Scripts.$(version).zip

The consumers:
* Write a bootstrapper script which
  * Reads global.json to determine the Arcade version
  * Downloads https://dotnetfeed.blob.core.windows.net/dotnet-core/arcade/$version/Arcade.Scripts.$(version).zip
  * Extracts arcade scripts to a local machine cache. (Location doesn't matter much. For example, we could use `$DOTNET_HOME/arcade/$version/`)
* Consumers are then free to write any/all scripts to suit their needs. These re-use Arcade's goodness by:
  * Importing functions from `$DOTNET_HOME/arcade/$version/arcade_v1.{sh, psm1}`
  * Invoking functions to perform tasks, such as installing native tools, invoking MSBuild, downloading .NET Core, etc.

Benefits:
* It constrains Arcade's scripts to an API. Like C# APIs, this can be versioned, tested, obsoleted, etc.
* Consumers only need to know (1) where to get Arcade's scripts and (2) which APIs they want to call. The rest is implementation detail hidden from consumers.
* Consumers can't customize Arcade's inner workings

#### 2. Reduce the amount of boilerplate VSTS yaml required.

11 of the files in eng/common/ are for VSTS yaml templates. The number of files used could be reduced with a few techniques:
* Replace yml steps with [custom VSTS tasks](https://docs.microsoft.com/en-us/azure/devops/extend/develop/build-task-schema). A good example of this would be [the telemetry](https://github.com/dotnet/arcade-minimalci-sample/blob/45c09192b9be983b4beb4defe1d85224e7e13f67/eng/common/templates/steps/telemetry-start.yml), currently a few hundred lines of yml. In theory, this could be replaced with a custom VSTS task, and repos only need this in their source:
```yml
- task: StartMyCustomBuildTelemetryTask@0
# repo specific build steps here
- task: EndMyCustomBuildTelemetryTask@0
  condition: always()
```

* Use [templates from other repositories](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories). ASP.NET has 50 something repos all pulling templates from https://github.com/aspnet/BuildTools. This allows us to update common settings, like machine pool names, without having to touch all 50 repos. It also means each repo that uses KoreBuild only needs a small YML file like this:
```yml
trigger:
- master
- release/*

# See https://github.com/aspnet/BuildTools
resources:
  repositories:
  - repository: buildtools
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: aspnet/BuildTools
    ref: refs/heads/master

phases:
- template: .vsts-pipelines/templates/project-ci.yml@buildtools
```

cc @markwilkie @Eilon

**Comment by tmat** [comment]
I'm definitely for reducing the amount of files in `eng\common`. 

The design has always been to include just enough scripts to bootstrap msbuild (dotnet cli or VS msbuild) and do the rest in msbuild targets in Arcade SDK.

This logic is implemented in the following files:
```
build.ps1
build.sh
cibuild.cmd
cibuild.sh
tools.ps1
tools.sh
```

I think that's reasonable amount.

Definitely agree that we should think about reducing the amount of YAML files and other infrastructure.

@natemcmaster Is there anything blocking you or is this proposal for improvement. I like the idea but I'd rather keep it as is for now until we are done with moving our repos to Arcade. Then we can work on improvements. I'm little worried to spend time on redesigning bootstrapping while we don't have all repos ready for Arcade yet.

**Comment by natemcmaster** [comment]
This is primarily a proposal for improvement. I'll file a separate issue for anything I find that blocks aspnet from switching toolsets.

**Comment by markwilkie** [comment]
Meeting notes:
-  @tmat has recently added the notion of "APIs" to our scripts, which should allow repos owners to extend Arcade to suite their needs.  Next step here is to dig in a bit to see if all the requirements are met.
-  There was wide agreement that some sort of verification step is required no matter what.  @mmitche says he'll add the eng/common file verification to 'darc verify'
-  Regarding packaging the majority of the contents, there was "tacit" agreement that this approach might make sense.  (another way of saying this is to not have files which can't be touched and checked in)  Next step here might be to learn more as we can do this largely behind the scenes in a non destructive fashion.

**Comment by markwilkie** [comment]
Filed two issues for the concrete deliverables.  Let me know @natemcmaster if you want an issue tracking your "gap" analysis.

**Comment by natemcmaster** [comment]
Thanks @markwilkie. I'll hopefully have time to look closer in the next week and attempt to onboard a repo to eng/common/. I'll open issues if I find big gaps that need addressing.
