### ISSUE TITLE
Enable Sbom generation vs-code-coverage

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#10595]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

**Comment by epananth** [comment]
Going to keep this open till @jakubch1 approves the pr

**Comment by epananth** [comment]
@ilyas1974  I will follow up with @jakubch1 when he is back from vacation.

**Comment by Chrisboh** [comment]
Any updates for this issue @epananth?

**Comment by epananth** [comment]
I created this PR https://devdiv.visualstudio.com/DevDiv/_git/DotNet-msbuild-Trusted/pullrequest/419812 couple of weeks ago, needs Jakubs approval. I pinged him. ( he was oof when I created the Pr)

**Comment by MattGal** [comment]
Any update here?

**Comment by epananth** [comment]
done closign this
