### ISSUE TITLE
Merge repotoolset into arcade

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#106]
As discussed, we need to move repotoolset into arcade.  This move will be somewhat disruptive, so messaging should be clear to the current repotoolset consumer repos.

This also implies a bit more detail around guidelines for getting PRs into Arcade will be helpful.  I'll work on that.

cc/ @jaredpar, @tmat, @weshaggard, @natemcmaster, @chcosta

**Comment by tmat** [comment]
I'll do this once we are done with 2.1 and source build

**Comment by markwilkie** [comment]
@tmat - any further thoughts on timing?

**Comment by tmat** [comment]
I think we should first stabilize all repos that are already on the toolset on its latest version. There is too many moving parts at this point.

**Comment by jcagme** [comment]
@alexperovich can you confirm this was done, and if so, close this issue?

**Comment by alexperovich** [comment]
Yes, I have moved all of RepoToolset into arcade under the Microsoft.DotNet.Arcade.Sdk name.

**Comment by jcagme** [comment]
This work has been completed.
