### ISSUE TITLE
Super slow mac machine

### ISSUE THREAD

**Issue by jkotas** [dotnet/arcade#10615]
### Build

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1968936

### Build leg reported

Mono  Product Build OSX x64 release

### Pull Request

https://github.com/dotnet/runtime/pull/74630

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "ran longer than the maximum time of 120 minutes",
    "BuildRetry": false
 }
 ```

### Additional information about the issue reported

Mono Product Build OSX x64 release typically finishes in less than 20 minutes. This one timeout after 2 hours. Looking at the log, everything is running like 10x slower on this machine. Is there something wrong with this particular macOS machine - does it need to be recycled?

### Report
|Build|Definition|Step Name|Console log|
|---|---|---|---|
|[1977395](https://dev.azure.com/dnceng/public/_build/results?buildId=1977395)|dotnet/runtime|Libraries Build OSX x64 Release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1977395/logs/1068)
|[1977345](https://dev.azure.com/dnceng/public/_build/results?buildId=1977345)|dotnet/runtime|Build Linux armv6 Release AllSubsets_Mono|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1977345/logs/150)
|[1976315](https://dev.azure.com/dnceng/public/_build/results?buildId=1976315)|dotnet/runtime|Build Linux armv6 Release AllSubsets_Mono|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1976315/logs/140)
|[1976240](https://dev.azure.com/dnceng/public/_build/results?buildId=1976240)|dotnet/runtime|Build Linux armv6 Release AllSubsets_Mono|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1976240/logs/145)
|[1974398](https://dev.azure.com/dnceng/public/_build/results?buildId=1974398)|dotnet/runtime|CoreCLR  Product Build OSX arm64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1974398/logs/1291)
|[1970895](https://dev.azure.com/dnceng/public/_build/results?buildId=1970895)|dotnet/runtime|Build Linux armv6 Release AllSubsets_Mono|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1970895/logs/223)
|[1976727](https://dev.azure.com/dnceng/public/_build/results?buildId=1976727)|dotnet/runtime|Build Linux armv6 Release AllSubsets_Mono|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1976727/logs/54)
|[1976631](https://dev.azure.com/dnceng/public/_build/results?buildId=1976631)|dotnet/runtime|Installer Build and Test coreclr  OSX_x64 Release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1976631/logs/1334)
|[1976735](https://dev.azure.com/dnceng/public/_build/results?buildId=1976735)|dotnet/runtime|Build Linux armv6 Release AllSubsets_Mono|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1976735/logs/139)
|[1978774](https://dev.azure.com/dnceng/public/_build/results?buildId=1978774)|dotnet/runtime|CoreCLR  Product Build OSX x64 release|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1978774/logs/49)
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|8|10|10|

**Comment by andriipatsula** [comment]
I am working on this.

**Comment by andriipatsula** [comment]
Hello @jkotas , this machine is not own by us. This `macos-11` image is own by AzDo and this could be a degradation issue. I re-run failing PR jobs. Let's see what happen.

**Comment by ilyas1974** [comment]
Closing this issue as these are not systems that are managed by DNCENG and the AzDO team is currently working on implementing a new set of mac systems.
