### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/arcade#1064]
All the links in https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Signing.md#usage-examples are dead :)

**Comment by markwilkie** [comment]
@JohnTortugo - can you make a pass and make sure our signing docs are up to date please?

cc/ @chcosta

**Comment by chcosta** [comment]
Looks like the relative paths are wrong and need to be updated

**Comment by JohnTortugo** [comment]
> @JohnTortugo - can you make a pass and make sure our signing docs are up to date please?
> 
> cc/ @chcosta

Definitely. I'm looking into it now.

**Comment by JohnTortugo** [comment]
@AdamYoblick I fixed the links. Thanks for reporting. Let me know if you have any issue with signing.

**Comment by AdamYoblick** [comment]
Hi John, I actually do have a signing issue, but maybe I'm doing something wrong. I will open up a separate issue for it since it's not related to docs.
