### ISSUE TITLE
Update VS2022 updates for 2022-09-07

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade#10653]
https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/899/VS2022-Upgrade-Schedule

**Comment by andriipatsula** [comment]
https://github.com/dotnet/arcade/issues/10653

**Comment by premun** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/25506

**Comment by premun** [comment]
Rolled out
