### ISSUE TITLE
Helix-service weekly build failing

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#10657]
- [X] This issue is blocking 
This is blocking deployments of helix-service
- [ ] This issue is causing unreasonable pain

We need to resolve some secret-manager issues: https://dev.azure.com/dnceng/internal/_build/results?buildId=1973927&view=results

**Comment by MattGal** [comment]
I secret-manager updated both and restarted, it's green now.

**Comment by ilyas1974** [comment]
@riarenas can you confirm that this has been resolved?

**Comment by riarenas** [comment]
It's resolved. Thanks!
