### ISSUE TITLE
dev.azure.com/dnceng-public migration starting at 4pm PST

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#10665]
All builds in dev.azure.com/dnceng/public will be offline starting at 4pm as we commence migration to dev.azure.com/dnceng-public/public

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by adiaaida** [comment]
@alexperovich how should we triage this? Can we just put it in FR or should it be closed?

**Comment by alexperovich** [comment]
I can just close this. I made it so build analysis had a notice on it.
