### ISSUE TITLE
Install XCode 14 on OSX.Amd.AppleTV.Scouting.Open

### ISSUE THREAD

**Issue by steveisok** [dotnet/arcade#10664]
We build tests on helix, so we need the beta version of xcode installed there.

/cc @ilyas1974

**Comment by ilyas1974** [comment]
https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/870/Install-new-version-of-Xcode-on-Helix-machines

**Comment by premun** [comment]
I asked Rolf whether mlaunch supports Xcode 14 already (mlaunch hasn't been updated since mid of June)

**Comment by premun** [comment]
This should do https://github.com/dotnet/xharness/pull/944

(installation of Xcode itself described in the link from Ilya is still left)

**Comment by adiaaida** [comment]
I assume beta 6 is what is needed?

**Comment by steveisok** [comment]
Yes, the latest beta would be best.

**Comment by premun** [comment]
We decided to put on the RC1 that came out yesterday

**Comment by adiaaida** [comment]
I think I have gotten the RC1 installed on this queue. I have this PR up for the code changes, but those are for future updates to the queue, not for the actual installing: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/25660

**Comment by steveisok** [comment]
> I think I have gotten the RC1 installed on this queue. I have this PR up for the code changes, but those are for future updates to the queue, not for the actual installing: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/25660

Thanks! I'll give it a try.

**Comment by steveisok** [comment]
We got something, but I think the devices need some manual intervention

```
[19:24:07.1025030] error MT1020: Failed to launch the application 'net.dot.System.Text.Json.Tests' on the device 'DNCENGTVOS-091': Application failed to launch: EThe operation couldn’t be completed. [PBD] Denying open-application request for reason: Disabled (Cannot launch app 'net.dot.System.Text.Json.Tests' while Setup Assistant is running)
```

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74809-merge-6236d568383b436f96/System.Text.Json.Tests.Attempt.3/1/net.dot.System.Text.Json.Tests.log?helixlogtype=result

**Comment by premun** [comment]
It seems like the device not properly set up and is hanging in the setup screen. @oleksandr-didyk can you please open an IcM for this?

I disabled the machine in the meantime.

**Comment by Chrisboh** [comment]
@oleksandr-didyk I have assigned this to you to track the ICM to get that one machine reimaged.

**Comment by oleksandr-didyk** [comment]
IcM ticket (mirroring from https://github.com/dotnet/arcade/issues/10797) -> https://portal.microsofticm.com/imp/v3/incidents/details/334627306/home

**Comment by oleksandr-didyk** [comment]
The machine was restarted and reported as working by the IcM, waiting for it to get some work to verify the state

**Comment by ilyas1974** [comment]
System is configured and functioning. While there are issue with runs on this system, they are not related to the hardware setup. Closing issue

**Comment by steveisok** [comment]
@ilyas1974 I spoke too soon.  It appears the tvOS devices that are tethered to the queue are asleep. Can someone please make sure they are awake?

**Comment by ulisesh** [comment]
IcM created for DDFun to take a look https://portal.microsofticm.com/imp/v3/incidents/details/337936644/home

**Comment by ulisesh** [comment]
DDFun created a ticket for MLS to fix the problem with the sleeping AppleTV

**Comment by ulisesh** [comment]
The device has been fixed, @steveisok could you please give it a try?

**Comment by ulisesh** [comment]
Friendly ping @steveisok

**Comment by steveisok** [comment]
@ulisesh All good. Thanks!
