### ISSUE TITLE
Unable to use Hosted Mac Preview agent pool

### ISSUE THREAD

**Issue by sbomer** [dotnet/arcade#1067]
I’m having trouble using the “Hosted Mac Preview” agent pool recommended here: https://github.com/dotnet/arcade/blob/master/Documentation/VSTS/VSTSOnboarding.md#github-to-dnceng-internal-mirror.
I get an auth error that points me at https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=vsts#troubleshooting-authorization-for-a-yaml-pipeline, which recommends resetting the pipeline branch. That worked when I got an auth error for the dotnet-external-temp pool, but didn’t fix it for the mac pool.
I instead switched to the “Hosted macOS” pool mentioned at https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml.

Could you either help me with the authentication, or update the arcade docs (if the Hosted macOS pool is replacing Hosted Mac Preview)?

**Comment by markwilkie** [comment]
@chcosta

**Comment by chcosta** [comment]
Hey @sbomer, sorry for the delayed response.  

I'm surprised you're having issues with the "Hosted Mac Preview" pool, unlike the non-hosted pools, Hosted are supposed to auto-authorize (soon they all will).

If you look in our [Onboarding documentation](https://github.com/dotnet/arcade/blob/master/Documentation/VSTS/VSTSOnboarding.md#troubleshooting), there's a similar note about this. That documentation is about resources in general but doesn't help you with the current agent pool authorization problem.  I'll update the documentation

It's a bit of a pain to get this to authorize, but here's the instructions.

1. Push your changes to a branch of the dnceng repository (not your fork)
2. Edit the build definition
3. Take note of the "Default branch for manual and scheduled builds"
4. Change "Default branch for manual and scheduled builds" to the branch you just pushed

**5. Change the "Default agent pool" to the pool that is unauthorized.**

6. Save the build definition. This will force reauthorization of the "default" branch resoures.
7. Edit the build definition
8. Change the "default branch for manual and scheduled builds" back to the value you noted in step 3 **and the default agent pool back to its previous value (probably Hosted VS2017)**.
9. Save the build definition
10. Now the resources should be authorized and you can submit your changes via a PR or direct push

**Comment by chcosta** [comment]
https://github.com/dotnet/arcade/pull/1094

**Comment by markwilkie** [comment]
@sbomer - I'm closing this as I'm assuming based on the PR that things are ok now.  However, please reopen is you need to.
