### ISSUE TITLE
[Known issues] Is a known issue blocking a PR?

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#10674]
We have been discussing the possibility of give build analysis the ability to change the status of PR checks. To get closer to this goal, build analysis would need to know if a known issue should block a PR or if it is ok to merge with a known build break.

Test issues would likely be **not blocking** known issues vs service outages which reduce the confidence of your build.

We need to add this setting to the known issue json blob

**Comment by missymessa** [comment]
Move to epic for final DevWFy stuff

**Comment by missymessa** [comment]
Moved to https://github.com/dotnet/arcade/issues/12183

**Comment by missymessa** [comment]
Handled with the last DevWF epic. Closing
