### ISSUE TITLE
[Known issues] Include report of test known issues

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10682]
Reported by @jkotas 

This is happening for all Known Build Error issues in dotnet/runtime. 

Is the summary report that the automation creates in the Known Issues on github expected to work?

It always shows all zeros, even in issues that are probably getting it. For example https://github.com/dotnet/runtime/issues/74328

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/25452

**Comment by AlitzelMendez** [comment]
this is the same as: https://github.com/dotnet/arcade/issues/10658
closing the other one on favor of this but updating the name of this to reflect what happened!

**Comment by AlitzelMendez** [comment]
This is stil failing
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/25583
