### ISSUE TITLE
HelixPublish does not produce a binlog

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#1070]
HelixPublish should produce a binlog so that any failures can be investigated.  There's currently no logging that I can see.

https://github.com/dotnet/arcade/blob/master/eng/common/templates/steps/helix-publish.yml#L21

A binlog would help me investigate failures like https://dev.azure.com/dnceng/public/_build/results?buildId=32591&view=logs.  @jonfortescue , can you help me understand what is causing the failure?  I'm following the documentation at https://github.com/dotnet/arcade/blob/master/Documentation/VSTS/SendingJobsToHelix.md (which I've made a few modifications to so that the documents makes some Arcadey specific assumptions

FYI @markwilkie

**Comment by jonfortescue** [comment]
@alexperovich
