### ISSUE TITLE
Update Build Analysis exception alerting to reduce noise

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10704]
See conversation here: https://teams.microsoft.com/l/message/19:23c287844dbd4f2c818607ab799024a9@thread.skype/1661980972708?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1661980972708&teamName=.NET%20Eng%20Services&channelName=V-Team%20-%20Dev%20WF%20(Kitchen)&createdTime=1661980972708&allowXTenantAccess=false

### Release Note Description
Updated Build Analysis alerts to increase timeframe before changing status

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/27683
