### ISSUE TITLE
Failed to download package 'runtime.any.System.Text.Encoding.4.3.0' 

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/arcade#10731]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=3005

### Build leg reported

CoreCLR  Product Build OSX x64 checked / Build managed product components and packages

### Pull Request

https://github.com/dotnet/runtime/pull/75001

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "The HTTP request to 'GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/45bacae2-5efb-47c8-91e5-8ec20c22b4f8/nuget/v3/flat2/runtime.any.system.text.encoding/4.3.0/runtime.any.system.text.encoding.4.3.0.nupkg' has timed out after 100000ms.",
    "BuildRetry": false
 }
 ```

### Additional information about the issue reported

Probably nothing to do but retry here or wait longer.

Opening this because we're now going to try logging every failure we see this way.

### Report
|Build|Definition|Step Name|Console log|
|---|---|---|---|
|[3005](https://dev.azure.com/dnceng/public/_build/results?buildId=3005)|dotnet/runtime|Build managed product components and packages|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/3005/logs/691)
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by garath** [comment]
Just a note, the restore also had some SSL failures.

**Comment by AlitzelMendez** [comment]
@AndyAyersMS do you want to track every system.text.encoding timeout? or every timeout happening on while downloading a package?
my question is to identify the best "Error message" for the scenario that you want to track :) thanks!

**Comment by AndyAyersMS** [comment]
Seems like this particular error is going to be sporadic and hit on different things over time, so I would guess any package?

**Comment by Chrisboh** [comment]
Looks like this only hit once and appears to just be a blip.  If we start seeing this again, please reopen.
