### ISSUE TITLE
Fix post-deployment scenario test in Helix Services

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10743]
Since the AzDO org migration, we're seeing our post-deployment scenario test in Helix Services (for Build Analysis functionality) fail. It likely has something to do with the fact that the repo we're using for testing is not in the dotnet GitHub org. 

/cc @alexperovich @AlitzelMendez 

TODO: 
- [x] Reactivate scenario tests  

### Release Note Description
Internal, Not for release notes. Activating again our scenario test

**Comment by AlitzelMendez** [comment]
Temporarily mitigating with https://github.com/dotnet/arcade/issues/10789 but when this gets resolved we need to rever those changes.

**Comment by missymessa** [comment]
According to Alex, this should be mitigated, so we can re-enable these tests again.

**Comment by AlitzelMendez** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/27325
