### ISSUE TITLE
Migrate off of pkgsrc.joyent.com

### ISSUE THREAD

**Issue by mthalman** [dotnet/arcade#10742]
A build issue popped up in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/683 which was getting a failure when attempting to run the build-rootfs.sh script. It was failing due to an [expired cert for pkgsrc.joyent.com](https://github.com/TritonDataCenter/pkgsrc/issues/342). The build-rootfs.sh script currently references the pkgsrc.joyent.com domain:

https://github.com/dotnet/arcade/blob/5fb434d9e8b99ff4d64381ef2f0c577b314a56e2/eng/common/cross/build-rootfs.sh#L394

However, according to this [SmartOS announcement](https://smartos.topicbox.com/groups/smartos-discuss/Tc0914fe1414685b5-M516296004a2f8ea793b60932), the recommendation is to migrate off of this domain. The script should be updated accordingly.

**Comment by adiaaida** [comment]
looks like there is a PR here: https://github.com/dotnet/arcade/pull/10751
