### ISSUE TITLE
Update base image for Windows.10.Amd64.CoreAppCompat* queues to simpler VS-2017-having image

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#10759]
The images used on Windows.10.Amd64.CoreAppCompat / Windows.10.Amd64.CoreAppCompat.Pr are routinely getting flagged for bulit-in Windows images.  Switching to a server-based image from our VS 2017 build image collection should reduce or eliminate the problem.

**Comment by MattGal** [comment]
From Junjun:

- Either VS2017 or VS2019 installed is working fine for us. 

We can try with a clean base image first to see what happen.  Please help 1) install CodeUI feature in VS and 2) add Edge Driver downloaded location(C:\edge-driver) to PATH system environment variable.   (make sure artifacts are the same)

- Please keep our current queues working as they are used for .NET testing now.   We can try our test with a new queue.  If everything goes smoothly , we can move to the new queue then. (use .Pr version of the queue first)

**Comment by Chrisboh** [comment]
Just a note here, we should use a client SKU of windows and not a server SKU as apps generally don't install on server

**Comment by jonfortescue** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/25781

**Comment by Junjun-zhao** [comment]
@jonfortescue  @MattGal 

Thanks for helping update Appcompat Queue.

From the error message of your above PR, it seems you are going to update all of AppCompat queues. 
Please **only update "windows.10.amd64.coreappcompat.pr"** for this time, because we need to test and make sure everything works well with the updated base image firstly and then we can update another queue as well. Thanks.

![image](https://user-images.githubusercontent.com/83067197/190570795-61785175-e960-41e4-ade8-8e6fb6e75249.png)

**Comment by jonfortescue** [comment]
New base image introduced in PR here: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/25974

**Comment by jonfortescue** [comment]
Done. Adding said base image here: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/26052

**Comment by Junjun-zhao** [comment]
@MattGal @jonfortescue Any update for this ticket? Can you please let us know when the new image will be available for PR queue?  It looks the base image update has been rolled out this Wednesday from latest rollouts heads up sent from Alitzel Mendez.  

We will take a long holiday next week and OOF from 10/1 to 10/7. We will try it from holidays if it is available then.

CC: @PriyaPurkayastha

**Comment by jonfortescue** [comment]
@Junjun-zhao As you said, the base image has been rolled out. Now that that's the case, we should be able to roll out the new queue next week assuming everything goes smoothly. Will keep you updated if there are issues.

Please enjoy your holiday!

**Comment by Junjun-zhao** [comment]
@jonfortescue Thank you for your update!

**Comment by jonfortescue** [comment]
@Junjun-zhao PR merged, should roll out on Friday for your use!

**Comment by Junjun-zhao** [comment]
@jonfortescue  Thanks very much for your help.  We have checked the new PR queue, please help remove the 3 components from VS 2019 which will affect our runtime compat test with the latest SDK version. 

- .NET 5.0 Runtime
- .NET Core 2.1 Runtime
- .NET Core 3.1 Runtime

There seems some difference from VS 2017 and VS 2019 with same workloads artifacts for VS. In VS2017, they don't have to install these runtimes, but in VS 2019 they are needed to install if install same workloads.   Please help **only** remove the depended workloads if you want to update workloads, keep the ones not related to runtimes (For example,  codeUI, Desktop development with C++, VS extension development)

**Comment by Junjun-zhao** [comment]
@MattGal  @jonfortescue  Any suggestion or update  for https://github.com/dotnet/arcade/issues/10759#issuecomment-1273068538

> @jonfortescue Thanks very much for your help. We have checked the new PR queue, please help remove the 3 components from VS 2019 which will affect our runtime compat test with the latest SDK version.
> 
> * .NET 5.0 Runtime
> * .NET Core 2.1 Runtime
> * .NET Core 3.1 Runtime
> 
> There seems some difference from VS 2017 and VS 2019 with same workloads artifacts for VS. In VS2017, they don't have to install these runtimes, but in VS 2019 they are needed to install if install same workloads. Please help **only** remove the depended workloads if you want to update workloads, keep the ones not related to runtimes (For example, codeUI, Desktop development with C++, VS extension development)

@MattGal @jonfortescue   Do you have any update or suggestion for this request?

**Comment by MattGal** [comment]
@Junjun-zhao I'm a little lost here, can you clarify why these runtimes cause problems for your test execution in Helix?   There's no reason you'd be forced to use runtimes that come built into the images, although 2.1 and 5.0 are technically end of life at this point and 3.1 is coming soon.  

We don't have existing scaffolding in place to remove default components of VS and even if we did I don't see how this matters to the underlying goal here, which was to move onto an image that had fewer security flagged issues.

**Comment by Junjun-zhao** [comment]
@MattGal Because this is pre-requisite for AppCompat team test and current runtime installed is blocking the automation test in PR queue.
AppCompat Team are doing third-party real-world apps runtime combability validation with Latest SDK. We have different .NET version Apps in our Lab such as
.NET Core 3.1, and need to test them with the latest specific runtime such as .NET 7 to find the compatibility issue. So the machine should not have any .NET version that they were built, otherwise, App we are testing will pick up the .NET version they were built with to run instead of the one we are testing.

Our Scenario for .NET 7 is:
1.Install Only latest .NET SDK.
2.Set DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2 to make app use the latest specific runtime installed on the machine instead of using the .NET version that the app was built with.  
3.Run the 3rd party Apps.
4.Check the app can be launched and its common function could work well.

**Comment by MattGal** [comment]
> So the machine should not have any .NET version that they were built, otherwise, App we are testing will pick up the .NET version they were built with to run instead of the one we are testing.

Isn't the ability to have as many distinct versions side-by-side a key feature of .NET Core, as well as the ability to install to a specific folder and run from that folder?  You've asked for machines with Visual Studio 2019 Enterprise installed on them, and that is where those .NET cores are coming from.  Unless I'm missing something, these runtimes can be excluded from the path simply setting environment variables, or if you want you can explicitly delete them at test run time. 

We can also try removing visual studio from the images relatively easily.  Writing an artifact just to chop up the runtimes that come with VS is a non-trivial amount of work so I want to understand how this is absolutely unavoidable before going down that path.  Feel free to set up a meeting any time open on  my calendar 8-4 PDT if you'd like to discuss further.

**Comment by Junjun-zhao** [comment]
@MattGal Understand. We are trying with a workaround and will update our result later. No Meeting needed with you temporarily. Thank you.

**Comment by Junjun-zhao** [comment]
@MattGal We have found a solution and it works well now, no need help from your side. Till now, we have completed about 50% of App Automation Test. Is there any S360 alerts you see for this new image? If no, we will continue to finish the remaining test. From current estimation, it will spend at least 1 week as there are only 5 machines in this queue.

**Comment by ilyas1974** [comment]
@Junjun-zhao please let us know when your tests are complete.

**Comment by MattGal** [comment]
> @MattGal We have found a solution and it works well now, no need help from your side. Till now, we have completed about 50% of App Automation Test. Is there any S360 alerts you see for this new image? If no, we will continue to finish the remaining test. From current estimation, it will spend at least 1 week as there are only 5 machines in this queue.

I will let you know if I see S360 alerts but I think thus far it's looking good for the test run.    Let me know when you're ready to make the other queue use this image and I'll get on that immediately.

**Comment by MattGal** [comment]
@Junjun-zhao  any updates?

**Comment by Junjun-zhao** [comment]
@MattGal  Thanks you.  We have some testing in the queue Windows.10.Amd64.CoreAppCompat this week. It should be OK to change it to use the new image next week.

**Comment by Junjun-zhao** [comment]
@MattGal @ilyas1974 We have completed our testing on the queues. I think we are ready to update the other queue to use the new image. Could you help update it in next week?

**Comment by ilyas1974** [comment]
Moving this back to our backlog to address the changes (as requested).

**Comment by MattGal** [comment]
Rolled out yesterday
