### ISSUE TITLE
New public AzDO fails all jobs with `macOS-12` hosted agents

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#10756]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The pipelines in the new dnceng-public AzDO instance can't use Azure Pipelines macOS-12 agents.

![image](https://user-images.githubusercontent.com/7013027/188860307-225e3688-8df4-4ef5-9b53-bb33ac521759.png)

You can try in this PR - https://github.com/mono/mono.posix/pull/27
Pipeline is here: https://dev.azure.com/dnceng-public/public/_build/results?buildId=7061&view=logs&j=006859bf-aef6-54c5-e4f3-b51877b6a20c

We have tried with 11 and it worked fine. 12 fails. We tried case-sensitive variations too.

The agents briefly appear after starting the pipeline:
![image](https://user-images.githubusercontent.com/7013027/188860416-5b9ffd21-6c15-4fde-8b05-4ecd0a99bb05.png)

but then they go into a canceled state.

**Comment by MattGal** [comment]
I shared this with some folks from the mac cloud team as well

**Comment by alexperovich** [comment]
This has been fixed by Azure Dev Ops

**Comment by akoeplinger** [comment]
Thanks, I confirmed it works now.
