### ISSUE TITLE
The `MonoARM64` agent pool wasn't migrated to `dnceng-public`

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#10757]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Original pool https://dev.azure.com/dnceng/public/_settings/agentqueues?queueId=160&view=jobs

Failing pipelines: https://dev.azure.com/dnceng-public/public/_build/results?buildId=7071&view=results

**Comment by alexperovich** [comment]
What pool even is this? Who manages it? It looks like a pool of static machines.

**Comment by riarenas** [comment]
@directhex is listed as the pool owner

**Comment by directhex** [comment]
Hm?

Yeah, that's a small pile of Lenovo Ampere machines. I can probably dig up the asset tags. They're on mlskvmui

**Comment by alexperovich** [comment]
I may be able to switch them to the new org, but its probably better for whoever did that originally to do it

**Comment by directhex** [comment]
I can do it. Do I have permission to create a new pool, or register a new agent, though?

**Comment by alexperovich** [comment]
I can add you

**Comment by directhex** [comment]
Or can we throw them in a trash compactor and use Azure Dpsv5 yet?

**Comment by alexperovich** [comment]
does this pool get used in internal also?

**Comment by directhex** [comment]
No, we don't use the same pool for internal and external jobs, that's a good way to wake up with a horse's head in your bed

There were, historically, sister pools for public ARM32, and private ARM64/ARM32, hosted on identical but separate machines, but those seem retired right now & I couldn't tell you how long ago they were retired

**Comment by Chrisboh** [comment]
@directhex  were you able to get your machines added to the pool?

**Comment by Chrisboh** [comment]
I am going to assume that this was all handled.  If there is more you need help with please feel free to reopen.

**Comment by directhex** [comment]
Hi, this wasn't handled. I don't have the permissions I need to resolve it, i.e. I can't create a pool on dnceng-public to migrate the machines into,

`Access denied. Jo Shields needs Create permissions to perform the action. For more information, contact the Azure DevOps Server administrator.`

**Comment by ulisesh** [comment]
I'll try to create the pool in dnceng-public so we can move the machines

**Comment by ulisesh** [comment]
Created the pool MonoARM64 and made @directhex the owner. The pool is here https://dev.azure.com/dnceng-public/_settings/agentpools?poolId=28&view=agents

**Comment by directhex** [comment]
I think I'm still missing a permission? I can't see poolId 28 at all on the list of pools at https://dev.azure.com/dnceng-public/_settings/agentpools , and clicking your link loads a mostly-blank page without working links (e.g. the pool name isn't listed at the top, clicking `Agents` doesn't do anything)

**Comment by ulisesh** [comment]
Can you please try again @directhex?

**Comment by directhex** [comment]
Yeah, that looks better! I'll need to add agents to see if that works, of course.

Is there any easy way to move a machine from one queue to another e.g. with a config file change? Or do I need to do a full uninstall/reinstall of the VSTS agent on all relevant machines?

**Comment by ulisesh** [comment]
It looks like you need to remove the agent and then reconfigure it again 

https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#remove-and-re-configure-an-agent

**Comment by directhex** [comment]
Hm. I'm getting a 401 when trying to configure agents, via a PAT I just created w/ Agent Pool Read/Create permission

![rpviewer](https://user-images.githubusercontent.com/308992/193125297-71bc1510-e42c-453e-9a7b-ed7584f7faf2.png)

**Comment by ulisesh** [comment]
Could you please try again? I moved the pool to the project level, it was at the org level. Hopefully it helps

https://dev.azure.com/dnceng-public/public/_settings/agentqueues?queueId=28&view=jobs

**Comment by directhex** [comment]
I think I've made progress on the auth issue (PAT issue on my end), but it looks like I'm still missing a permission somewhere on the AzDO end:

![image](https://user-images.githubusercontent.com/308992/193272400-c8391efc-d250-4864-a7f8-f3bbc39872b0.png)

**Comment by ulisesh** [comment]
@directhex can you please try again?
