### ISSUE TITLE
Supported AzDO projects in Build Analysis should be configurable, not hardcoded

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10765]
Related to https://github.com/dotnet/arcade/issues/10761

This bit of code here: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service?path=/src/ServiceFabric/Helix/Helix.Internal.BuildFailureAnalysis/Providers/RelatedBuildProvider.cs&version=GBmain&line=23&lineEnd=24&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents has hardcoded values for supported AzDO projects. This was missed during the refactor to support multiple AzDO instances in Build Analysis, and we feel that this should be something configurable for easier expansion in the future. 

### Release Note Description
Internal, doesn't apply for release notes.

**Comment by AlitzelMendez** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/26413
