### ISSUE TITLE
Helix authenticated calls have lower rate limit than anonymous ones

### ISSUE THREAD

**Issue by jaredpar** [dotnet/arcade#10764]
The current rate limit for Helix API calls is 

| Client Type | Calls per Minute | Calls per Hour |
| --- | --- | --- |
| Anonymous | 400 | 24,000 | 
| Authenticated | Unknown | 5,000 | 

Given this it's a distinct disadvantage for Helix users to use an authenticated client. Most of our developer tooling is around artifacts from public builds hence is accessible form an anonymous client. That means using authentication serves only to make your code more likely to encounter rate limiting issues. 

This is essentially backwards from all other API clients. Rate limiting is used as an incentive to authenticate so they can more accurately track the usage of a person / tool. In Helix though we are encouraging the opposite. 

I encountered this when I moved runfo to use authenticated Helix clients. After finding this out though I'm moving to go back to anonyomous access as the new rate limit is impacting my ability to perform tasks.

**Comment by garath** [comment]
Maybe pedantic, but the rate limit split is not truly based on authenticated/unauthenticated. 

All calls are limited at 400/1m _and_ at 5000/1h. Both apply at the same time for everyone. The limit is measured by the username if authenticated and by IP address if not authenticated. 

An anonymous user can get limited at 5000/h, and an authenticated user can get limited at 400/m. No individual "user" can actually get to 24k calls (this would require an anonymous user and changing IPs). This can be seen in real data on this [helix-api-throttle dashboard](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/1KY-xTG4k/helix-api-throttle).

This was all originally meant as Yet Another Tool to keep misbehaving build machines from causing too much trouble. It works for that, but is not as clean as it could be.

**Comment by garath** [comment]
One idea: Azure publishes IP ranges for services. Those could be used to apply a rate limit to build machines. Then there could be a separate (very low?) limit for unauthenticated, non-Azure requests, and a separate (high?) limit for known, authenticated users.

**Comment by garath** [comment]
More generally, is rate limiting actually helping us manage the services? Or is it just acting as a late-game circuit breaker?

**Comment by alexperovich** [comment]
it makes sure our poor API server doesn't explode, or more likely cause sql to redline and die.

**Comment by garath** [comment]
> or more likely cause sql to redline and die.

I would agree, but the SQL database is already working very hard. I'm not convinced this rate limit what keeps it from falling over.

**Comment by ChadNedzlek** [comment]
I think right now both numbers are "as low as we can make them without breaking legitimate flows".  Azure/AzDO/MSFT tend to end up having a single IP from a public perspective, so those have to be a bit higher, otherwise we end up disabling basically "everything from Azure", or "all builds".

If a user only wants to access public builds, they shouldn't be using a token anyway, since that's just a security vulnerability (having to manage the token) for no real gain.

The limits have been there for a long time and seem to be doing what they are intended. They stop runaway clients, and mostly don't impact anyone that isn't doing anything that might cause damage to our services.

I don't think the risk associated with messing with stuff are worth it.

**Comment by ChadNedzlek** [comment]
I'm going to close this, since I'm not sure what a "better" behavior than we have is right now, and I think the risk is pretty high that we might either cause 429's to occur a lot more frequently, or end up overwhelming our service when a bad build or something starts hammering the service.
