### ISSUE TITLE
TimelineRecords kusto table is missing dnceng-public records

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#10768]
We don't have any rows from dnceng-public in TimelineRecords, whatever services adds the rows needs to monitor our new AzDo instance

**Comment by garath** [comment]
FYI to avoid accidental double-work, @epananth was asking me about this the other day.

**Comment by riarenas** [comment]
I think it's this? https://github.com/dotnet/arcade-services/blob/main/src/Telemetry/AzureDevOpsTimeline/.config/settings.json#L5-L8

**Comment by garath** [comment]
More generally [this](https://github.com/dotnet/arcade-services/tree/main/src/Telemetry/AzureDevOpsTimeline) is the project. It will need to be taught how to look at more than one Organization.

**Comment by missymessa** [comment]
@epananth and I talked about how we implemented the multi AzDO org support in Helix Services, because she said she needed to do the same in Arcade-Services. I'm assuming this work is related to that discussion.

**Comment by ulisesh** [comment]
Good, thanks everyone!

cc @Chrisboh as some reports are missing data

**Comment by garath** [comment]
I'm probably the last person to touch this code (having it get all timelines instead of just the latest). Let me know if I can help at all.

**Comment by ulisesh** [comment]
I think this should be part of the epic in charge of moving to the new instance

**Comment by epananth** [comment]
I was talking to @Chrisboh about this a few mins ago. We need to update this support both orgs, so that CI council dashboards work.

**Comment by epananth** [comment]
Yes, I was tracking this as a part of dashboard work, but I can use this instead

**Comment by ulisesh** [comment]
Feel free to take this issue to track the work or close it as a dupe if there is another one already 😄

**Comment by riarenas** [comment]
As I think about this issue more, I'm starting to think this is the root cause for the Queue Insights alert as well: https://github.com/dotnet/arcade/issues/10710. 

@dkurepa can probably confirm it best, but if we're not ingesting builds from dnceng-public, the matrix of truth doesn't have information from those builds, and then queue insights won't record some of the needed entries for queue insights to work correctly.

**Comment by epananth** [comment]
I have the code changes, I am currently testing it. Once that is successful I will have my PR for this

**Comment by epananth** [comment]
@garath gave me some suggestions to test this, trying that now

**Comment by alexperovich** [comment]
This is now fixed.
