### ISSUE TITLE
Fix how we correlate build errors and test known issues 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#10772]
After the dnceng-public migration we are having problems to identify the unique build failures as test failures as the reported pipeline reference are slightly different, so we are not able to correlate them correctly

**Comment by AlitzelMendez** [comment]
took a further look and is not a problem with the correlation but how the information is passed, I already have done other fixes in here :/ I am worried on how many scenarios are like this :/ I will try to cover more scenarios this me

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/25629

I think all the scenarios are already in here, if you think any other scenario is missing, please let me know @missymessa @ulisesh

**Comment by missymessa** [comment]
/cc @AaronRobinsonMSFT @dougbu @hoyosjs @radical @elinor-fung @MichalStrehovsky @tlakollo @ViktorHofer 

Hey folks, this issue should correct where Build Analysis reports a "Helix work item failure" as a build failure when it's actually a test failure and the related test failure (so overlapping failures). If you happen to see any more instances of this happening, please let us know so we can make sure to include that scenario in our exceptions. Thanks!
