### ISSUE TITLE
dotnet/llvm-project objwriter/release/7.0 branch is not mirrored to Azure DevOps

### ISSUE THREAD

**Issue by sbomer** [dotnet/arcade#10773]
We need https://github.com/dotnet/llvm-project/tree/objwriter/release/7.0 to be mirrored to the internal repo. There's a [subscription](https://github.com/dotnet/versions/blob/ceb85d0cb272823e3366e6498fdc4178c9e4322c/Maestro/subscriptions.json#L471) set up for `https://github.com/dotnet/llvm-project/blob/objwriter/**/*` but this doesn't appear to be working.

cc @MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
The branch mirrored over once we merged a pull request into it.
