### ISSUE TITLE
AzDO pipeline fails to download artifacts from a specific build

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#10783]
- [x] This issue is blocking

There is a [test pipeline](https://dev.azure.com/dnceng-public/public/_build?definitionId=81&_a=summary) whose artifacts are used in [another pipeline](https://dev.azure.com/dnceng-public/public/_build?definitionId=22&_a=summary).
The download task is specified here: https://github.com/dotnet/wpf/blob/a812f55e28dff046745caa01a931199f6b68c346/eng/pipeline.yml#L211-L220
and points to this build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=6988&view=results

The download fails in two different ways:
```
Starting: Fetch Test Binaries
##[error]notFound:CannotBeNullOrEmpty
```
and
```
##[error]The container 28527970 could not be found.
```

**Comment by premun** [comment]
@MattGal do you think this qualifies as an "outage" and a ticket through the chat bot should be opened?

**Comment by premun** [comment]
I let them know that they might try a workaround and pull the artifact from a different build, not sure it will help but maybe it's just that one build that we can't pull the artifacts from.

**Comment by MattGal** [comment]
> @MattGal do you think this qualifies as an "outage" and a ticket through the chat bot should be opened?

Yes, for one-off investigations like this where it seems like a clear bug on the AzDO side I'd recommend opening a Sev3 incident to ask them to investigate it.  I would set expectations for response time fairly low, however.

**Comment by oleksandr-didyk** [comment]
IcM ticket -> https://portal.microsofticm.com/imp/v3/incidents/details/334338455/home

**Comment by oleksandr-didyk** [comment]
Closing as the discussion was moved to the linked IcM ticket
