### ISSUE TITLE
Fix unique test failures count 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#10788]
When doing other changes, I noticed that the unique test failures count wasn't accurate when we had shared test failures 

![image](https://user-images.githubusercontent.com/6895254/189382480-569ba8a9-145a-43a2-abab-84cd4b7f4441.png)

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/25657

**Comment by missymessa** [comment]
@AaronRobinsonMSFT this issue fixes the test error count confusion we discovered during the user study.
