### ISSUE TITLE
Add E2E tests for VMR git operations

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#10798]
### Context

The VMR code doesn't have many tests yet as it's being developed, however the time is coming when we will need to add some. Apart from unit tests, we should have E2E tests so that we also test the integration with git (new git versions can have different behaviour).

### Goal
We should end up with E2E tests on the PR build of arcade-services and cover following cases:
- Files are being changed
- Files are being in/excluded between commits
- XML files tracking the dependencies are created
- All files are always commited well ("git status is clean")
- Submodules are being inlined properly in the VMR properly
    - Changes in submodules are being synchronized well
    - Submodules are added/removed
- VMR patches
    - Patches are applied well
    - Patches are removed/added
- VMR's non-`src/` content is synchronized

### Notes
There are already some tests in my personal repo - https://github.com/premun/git-patch-test - these can be an inspiration though I would reconsider using docker. Maybe a clean folder for each test will be good enough?

These tests synchronize two repositories and compare the file tree/contents:
```
Individual repo before:
/work/individual-repo
|-- ignored
|   `-- B.txt
`-- included
    `-- A.txt

2 directories, 2 files

Individual repo after:
/work/individual-repo
|-- ignored
|   `-- B.txt
`-- included
    `-- C.txt

2 directories, 2 files

VMR before:
/work/vmr
`-- src
    `-- individual-repo
        `-- included
            `-- A.txt

3 directories, 1 file

Creating patch..

Patch created:
diff --git a/included/A.txt b/included/C.txt
similarity index 100%
rename from included/A.txt
rename to included/C.txt

Applying patch..

VMR after:
/work/vmr
`-- src
    `-- individual-repo
        `-- included
            `-- C.txt

3 directories, 1 file
        renamed:    src/individual-repo/included/A.txt -> src/individual-repo/included/C.txt
```

Most notable, the test suite number 7 is the most interesting.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Added some E2E tests for the cases of adding or changing files, adding and removing submodules

**Comment by premun** [comment]
The other interesting test case is:

- There was a repo `nuget-client`
- The repo has a submodule at `src/submodules/FileSystem`
- There was a bad file in the submodule's root `NuGet.config` so in the VMR `src/nuget-client/src/submodules/FileSystem/NuGet.config`
- We added a patch that was removing this file
- We removed the patch afterwards but the file didn't come back

This is not fixed yet, but feel free to write a failing test, we can mark it as Ignored and I can open a PR with my fix.

You can also try out merging my branch later and seeing if the test passes. But it's possible my branch broke other things too..

My branch: https://github.com/premun/arcade-services/tree/prvysoky/patch-application

**Comment by MilenaHristova** [comment]
Until now we have tests for:

- [x] Files are being changed
- [x] Files are being in/excluded between commits
- [x] XML files tracking the dependencies are created
- [x] All files are always commited well ("git status is clean")
- Submodules are being inlined properly in the VMR properly
    - [x] Changes in submodules are being synchronized well
    - [x] Submodules are added/removed
- VMR patches
    - [x] Patches are applied well
    - [x] Patches are removed/added
    - [x] Files are deleted/restored when removing a VMR patch
- [x] VMR's non-`src/` content is synchronized
- [ ] All repos in the dependency tree are updated to the correct version
