### ISSUE TITLE
Abandon build analysis messages because problems renewing lock

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#10807]
We have been facing problems renewing a lock in azure storages.

[For example](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA3WQQUvDQBCF7%252F6KIZfqIak1UZNADoqKXkRqPZfJ7qRZ2OyGnQm24I93VVqK6PXxzfceIwEV8ckHvPcUCJT1k14vvaVnHAiaBmYdtsGoev5I1mznt5Oxekk8WblxaHds%252BCX4qGAfZlFDWyGnAWCIEW7oSa%252BhAfEswbjNqZpY%252FHBnBnJsvOPsgJ3BYcTRKSjvBI1jSK67Mi8uuzZVV3meFuWiSquyxbSoSsQFnl8UeZX8dhzdv7kenbak40ZFo8R6eN2x0JCt4h4%252Fyf0%252Br2HVE%252FiRAn5jPTJIZDREKkvAhz%252F8D2i%252B5OJh%252FHnInqn%252FrUk%252BAYl6eFd%252BAQAA/timespan/2022-09-08T15%3A43%3A23.000Z%2F2022-09-12T15%3A43%3A23.000Z)

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Fixed scenario in which the build analysis wasn't processed correctly, and it didn't return results

**Comment by AlitzelMendez** [comment]
I created a [new query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA7WQsQrCQAxA935F6FIFobvSoU66iPQHSnoXa%252BR6KZcrWvDjvUVpP8Ax5PHyiKMIMlLAyOL1bBUqiAENafaG550CgXEy2bYRRxccCKoKiht2gc2%252BPJHjV3mc2NmGdHKx9uhmZb0GSQqVUPw0Q5qxTzrxEdkr5HWH3opn33%252BXeaLHIA8yi6r2bA%252FZf5qWN4A9bFav2CYu4RG6eUXuIHIKjjiMgGo%252B32N3c0MBAAA%253D/timespan/P2D) to observe multiple scenarios is which we are abandoning message when trying to:

1.  The operation has timed out. at  Azure.BlobContextualStorage.AcquireAsync
followed by
1. Renew task exception: Azure.RequestFailedException: The specified message does not exist.

seems that one is waiting for the other.

Not sure about how to test/repro around this to looks for ways to fix it. @ulisesh  and @garath  this started happening after moving WindowsAzure.Storage to modern Azure SDK. Could you please explain to me how to test this locally? if there is any way.

**Comment by AlitzelMendez** [comment]
ok I took a look at this again and the problem is that when an AzDO message is renewed a new popReceipt gets generated: https://learn.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient.updatemessage?view=azure-dotnet

in our code, after the message is renew, we keep following the original message (without observing the new popReceipt and new expire visibility time), when we try to renew the message again, we use the old popReceipt so a message of: message not found appears, as we can't renew the message (due to the incorrect popReceipt) the message appears again on the queue and because some rules on AzDO queues another thread can take the same message causing all this problem. 

in order to fix all this the renew process for the AzDO queues needs to be fixed

**Comment by missymessa** [comment]
>the message appears again on the queue and because some rules on AzDO queues another thread can take the same message causing all this problem.

Are the rules our rules or AzDO rules that we can't change?

**Comment by AlitzelMendez** [comment]
those are AzDO rules. I don't think we need to change the rules, I only pointed that out because this is the reason this started happening when we started using this library, but we just need to take this into consideration while renewing message, I created a PR for this: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/28194

**Comment by missymessa** [comment]
Ah okay, thanks for the clarification!

**Comment by AlitzelMendez** [comment]
I finally got to validate this. It is working as expected 🥳 
closing!
