### ISSUE TITLE
Build monitor not opening issues

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#10805]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

There have been a few failures in the arcade-validation and arcade-services official pipelines that should've opened issues in arcade but haven't.

**Comment by riarenas** [comment]
I touched the configuration for issue opening last, will check to see if I can find something related, and then move to FR for investigation if it seems unrelated.

**Comment by riarenas** [comment]
the service hook is still enabled, but I see some failures.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade/issues/10806 exists, so the service is working correctly and I didn't break it (most important part)

**Comment by garath** [comment]
Yeah, #10795 is probably the reason these builds were missed.
