### ISSUE TITLE
TIMED_OUT failures on DNCENGWIN-020

### ISSUE THREAD

**Issue by karelz** [dotnet/arcade#10819]
Occurrences:
- [last 30 days - System.Net.Security.Tests](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.net.security.tests+work+item%22) as of 9/13

Day | Run | Log | OS | Machine
-- | -- | -- | -- | --
9/12 | PR [12963](https://runfo.azurewebsites.net/view/build/?number=12963) (main) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-75436-merge-febd6236c7d84892b8/System.Net.Security.Tests/1/console.af886775.log?%3Fhelixlogtype%3Dresult) | net7.0-Android-Release-**arm64**-Mono_Release-Windows.10.Amd64.Android.Open | DNCENGWIN-020
9/10 | Rolling run [11508](https://runfo.azurewebsites.net/view/build/?number=11508) (main) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-328bbadd3f404349be/System.Net.Security.Tests/1/console.30df3c84.log?%3Fhelixlogtype%3Dresult) | net7.0-Android-Release-**arm64**-Mono_Release-Windows.10.Amd64.Android.Open | DNCENGWIN-020
9/1 | PR [1724](https://runfo.azurewebsites.net/view/build/?number=1724) (main) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74936-merge-7ae0d66f54b643bba2/System.Net.Security.Tests/1/console.9a032399.log?%3Fhelixlogtype%3Dresult) | net7.0-Android-Release-**arm**-Mono_Release-Windows.10.Amd64.Android.Open | DNCENGWIN-020
8/29 | Rolling run [1973372](https://runfo.azurewebsites.net/view/build/?number=1973372) (main) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-9e200d2ec1944b4e86/System.Net.Security.Tests/1/console.764f6773.log?%3Fhelixlogtype%3Dresult) | net7.0-Android-Release-**arm64**-Mono_Release-Windows.10.Amd64.Android.Open | DNCENGWIN-020
8/27 | PR [1971858](https://runfo.azurewebsites.net/view/build/?number=1971858) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74709-merge-5a2c6bdacef94808bf/System.Net.Security.Tests/1/console.3c5c5d5f.log?%3Fhelixlogtype%3Dresult) | net7.0-Android-Release-**arm**-Mono_Release-Windows.10.Amd64.Android.Open | DNCENGWIN-020
8/26 | Rolling run [1969937](https://runfo.azurewebsites.net/view/build/?number=1969937) (7.0-rc1) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-rc1-1342087fe7c64e458e/System.Net.Security.Tests/1/console.0c7bf55d.log?%3Fhelixlogtype%3Dresult) | net7.0-Android-Release-**arm64**-Mono_Release-Windows.10.Amd64.Android.Open | DNCENGWIN-020
?-8/23 | Logs are not available |  |  |

Error:
```
[13:59:39] dbug: Executing command: 'C:\h\w\B62009AE\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.22456.1\runtimes\any\native\adb\windows\adb.exe -s 9CBAY1NP1W shell am instrument -w net.dot.System.Net.Security.Tests/net.dot.MonoRunner'
[14:29:39] fail: Waiting for command timed out: execution may be compromised
[14:29:39] warn: Running instrumentation class net.dot.MonoRunner timed out after waiting 1800.0090662 seconds
[14:29:39] dbug: Exit code: -2
                 Std out:
                 
                 
                 
[14:29:42] dbug: Executing command: 'C:\h\w\B62009AE\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.22456.1\runtimes\any\native\adb\windows\adb.exe -s 9CBAY1NP1W logcat -d '
[14:29:45] info: Wrote current ADB log to C:\h\w\B62009AE\w\ADCB099F\uploads\adb-logcat-net.dot.System.Net.Security.Tests-net.dot.MonoRunner.log
[14:29:45] info: Attempting to remove apk 'net.dot.System.Net.Security.Tests'..
[14:29:45] dbug: Executing command: 'C:\h\w\B62009AE\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.22456.1\runtimes\any\native\adb\windows\adb.exe -s 9CBAY1NP1W uninstall net.dot.System.Net.Security.Tests'
[14:29:51] info: Successfully uninstalled net.dot.System.Net.Security.Tests
[14:29:51] dbug: Saving diagnostics data to 'C:\h\w\B62009AE\w\ADCB099F\e/diagnostics.json'
XHarness exit code: 70 (TIMED_OUT)
User command ended with 70
```

**Comment by karelz** [comment]
@premun I updated hits more into history -- it happened 6x in last 17 days - all on the same machine. Any explanation why it would be always the same machine?

**Comment by karelz** [comment]
I let @steveisok @akoeplinger decide if they want to move it into Runtime repo as a problem with test / app.

**Comment by steveisok** [comment]
> I let @steveisok @akoeplinger decide if they want to move it into Runtime repo as a problem with test / app.

We'll test it out locally and see if it times out.

**Comment by premun** [comment]
If this keeps happening on the same phone, let's take it out of the rotation and get checked.

@oleksandr-didyk can you please disable this machine and open an IcM?

**Comment by oleksandr-didyk** [comment]
Machine is disabled, IcM created -> https://portal.microsofticm.com/imp/v3/incidents/details/334626564/home

**Comment by oleksandr-didyk** [comment]
IcM rebooted the machine, enabled it back to the queue to test if its working properly

**Comment by oleksandr-didyk** [comment]
After 24 hours, it seems that the work items are handled properly, no other failures are seen. Closing the ticket as done
