### ISSUE TITLE
Remove all hard-coded c:\ paths from Helix machines artifacts

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#10810]
DDFUN needs to be able to run Helix agents off the D:\ drive;  this is often broken by hard-coded c:\ paths inside the scripts, which puts some files onto the UIP imaging drive often which can be small.

@JpratherMS FYI

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/26042

**Comment by MattGal** [comment]
This is rolled out, closing.   @JpratherMS FYI; let me know if you see any issues with machine setup after 9/28.

**Comment by MattGal** [comment]
@parose1 showed me a problem with this today, reactivating so I can fix two more locations with the problem.

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_build/results?buildId=2025314&view=results should fix the issue and removes the last two c:\’s in the entire repository.  Once merged and in staging, I'll work with @parose1 to see if this sorts the problem.

**Comment by MattGal** [comment]
@parose1 found one more place we had this, addressed in https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/27051.  I also had to change artifacts around to be able to put the helix disk on D:\ for this queue.

**Comment by MattGal** [comment]
@parose1 is OOF until tomorrow so I'll check back with him then about whether this finally solves the problem.

**Comment by parose1** [comment]
@MattGal I have tested the new changes in staging, and everything is working correctly now. The machines get added to the queue and start heart beating automatically. Thank you!

**Comment by MattGal** [comment]
This is rolled out, closing.
