### ISSUE TITLE
[Signing OSX Files] Patch SignTool to call the MicroBuild target for signing OSX Files

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#1081]
Original discussion was here: https://github.com/dotnet/arcade/issues/898

**Comment by JohnTortugo** [comment]
Please take a look at my plan below (+some questions) to implement this. It doesn't seem like a big change.

**Question:** Which are the OSX extensions that we need to support? .dylib, .pkg?

- I plan to add a new static variable, [like this one](https://github.com/dotnet/arcade/blob/ba1453c0ef97843aab2d2e1cc63dd876896458e9/src/Microsoft.DotNet.SignTool/src/SignToolConstants.cs#L18), that will old all signable OSX file extensions.
- Patch this method to split `filesToSign` in OSX files and "non-OSX files".
- Create a new method (e.g., `GenerateOSXBuildFileContent`) to prepare all OSX files to be signed - All files need to be in the same folder (subfolders are allowed) - and generate a .proj for calling MicroBuild.

@markwilkie @tmat @natemcmaster @weshaggard

**Comment by markwilkie** [comment]
@leecow - can you confirm which osc extension we need?  .dylib, .pkg?

**Comment by leecow** [comment]
pkg is all that we currently sign.
