### ISSUE TITLE
Create production branch for dotnet-buildtool-prereqs-docker

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#10831]
To start creating the `latest` tags, we need to create the production branch and begin doing weekly rollouts.

**Comment by adiaaida** [comment]
@mthalman I'd like to do this tomorrow as part of dnceng's weekly rollout. Does that work for you?

**Comment by mthalman** [comment]
Yes, that'll be fine. You should have permissions to push a new branch. One thing that will need to change is for the new branch to be declared as an "official branch" in the YAML. That's a built-in safeguard meant to prevent publishing images from a branch not declared as official.

You can see this in for our nightly pipeline at https://github.com/dotnet/dotnet-docker/blob/38d02249b6bc86982d563196c72cbc6348044946/eng/pipelines/dotnet-core-nightly.yml#L22-L24.

It's probably easiest just to declare this in the common variables.yml, which is referenced by all the pipelines, at https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/eng/pipelines/variables/common.yml:

```yaml
- name: officialBranches
  # comma-delimited list of branch names
  value: main,production
```

**Comment by adiaaida** [comment]
Thanks! I'll put up a pr for that

**Comment by adiaaida** [comment]
I have created the production branch!
