### ISSUE TITLE
Bad machine DNCENGWIN-070

### ISSUE THREAD

**Issue by karelz** [dotnet/arcade#10842]
9/13 Rolling run [14506](https://runfo.azurewebsites.net/view/build/?number=14506) had 4 hiccups on the machine:
- Microsoft.Extensions.Logging.Generators.Roslyn3.11.Tests Work Item - no response: connection reset - [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-166ee0e875d5403c9c/Microsoft.Extensions.Logging.Generators.Roslyn3.11.Tests/1/console.991bc90f.log?%3Fhelixlogtype%3Dresult)
- System.Xml.RW.XmlReader.ReadContentAs.Tests Work Item - no response: connection reset - [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-166ee0e875d5403c9c/System.Xml.RW.XmlReader.ReadContentAs.Tests/1/console.bccdcf42.log?%3Fhelixlogtype%3Dresult)
- System.Net.Security.Enterprise.Tests Work Item - PowerShell error - [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1d4de921e44f425aa8/System.Net.Security.Enterprise.Tests/1/console.31d7a4ae.log?%3Fhelixlogtype%3Dresult)
- Microsoft.Extensions.Configuration.Tests Work Item - PowerShell error - [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1d4de921e44f425aa8/Microsoft.Extensions.Configuration.Tests/1/console.15cdc189.log?%3Fhelixlogtype%3Dresult)

**Comment by karelz** [comment]
BTW: The PowerShell error looks like mangled output - can we do something about the encoding there to make it look like text?

**Comment by alexperovich** [comment]
I've offlined this machine, and I will make a ticket for ddfun to give the machine a checkup.

That powershell error looks like UTF-16 output in a utf-8 shell. I don't think there is anything we can do about that other than using pwsh instead of powershell.

**Comment by alexperovich** [comment]
The first 2 errors can be "resolved" by doing what matt suggested here (https://github.com/dotnet/arcade/issues/10617#issuecomment-1247154909). The powershell error looks like its a memory/disk space issue, and I've opened https://portal.microsofticm.com/imp/v3/incidents/details/335263948/home to investigate.

**Comment by ilyas1974** [comment]
The DDFUN ICM has been resolved. Putting this system back online and closing the issue.
