### ISSUE TITLE
Define rollout process for dotnet-buildtools-prereqs-docker

### ISSUE THREAD

**Issue by michellemcdaniel** [dotnet/arcade#10844]
We need to get the repo/builds up-to-date with the rollout policies so that we can rollout dotnet-buildtools-prereqs-docker to production on a regular cadence.

**Comment by adiaaida** [comment]
This is back in the backlog until we make a decision about what our plans with the docker containers used by our build and test infrastructure will be.

**Comment by michellemcdaniel** [comment]
closing this as we will be moving the dockerfiles
