### ISSUE TITLE
Create AzDO tasks for parts of our YAML templates

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#1085]
Based on our discussion around #1059, we agreed that there are portions of our YAML templates that would be better served put into a task.  The first step is to identify which parts should be converted, and then go from there.

**Comment by chcosta** [comment]
This is in progress.

One-pager - https://github.com/dotnet/core-eng/issues/4473

**Comment by markwilkie** [comment]
Closing because there's now an epic #1477
