### ISSUE TITLE
Make sure dnceng-public is onboarded to cloudmine

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#10863]
@ulisesh reports that cloudmine doesn't yet include info from dnceng-public. 

Onboarding instructions are here: [CloudMine onboarding](https://eng.ms/docs/products/1es-cloudmine/onboarding). Should be straightfoward!

**Comment by jonfortescue** [comment]
Filed IcM to onboard [here](https://portal.microsofticm.com/imp/v3/incidents/details/336590133/home).

**Comment by jonfortescue** [comment]
This has been completed.

**Comment by ulisesh** [comment]
Thanks for completing this @jonfortescue.

I checked 1ES AzDo DB and it now contains information about dnceng-public builds 😄 unfortunately it didn't bring the information retroactively, so the earliest data we have is from 9/23. We lost around 3 weeks of data, cc @Chrisboh

**Comment by garath** [comment]
I think everything in that database is capturable after-the-fact. You might try asking them if they can fill-in the gap. Or we could do it and submit the data to them for ingestion. 

It's worth a try, at least!

**Comment by ulisesh** [comment]
I'm on FR so I'll give it a try
