### ISSUE TITLE
User study feedback: Better discoverability for Known Issues project board

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10881]
User asked how to discover what Known Issues were in their repo. I sent them a link to the project board. We should make this more discoverable.

**Comment by ChadNedzlek** [comment]
Isn't it just... things with a specific label?  It's pretty basic GitHub stuff... I'm not sure what the confusion is.

**Comment by jkotas** [comment]
One source of the confusion is that the label is called "Known Build Error", but we use it for both build errors and failing tests. Builds and tests are two different things, at least in the repos that I work on.

I would recommend to rename the label to "Known CI Issue" or something like that.
