### ISSUE TITLE
Create/initialize the VMR

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#10890]
- [x] We have to create the repository itself, initialize it and make sure we can synchronize it.
    - [x] We should give permissions for writing to the UB and A&D teams only.
- [x] We need to take care of licenses and similar files that are needed in the root of the repo.
- [x] #11159

**Comment by premun** [comment]
@terrajobst we are creating a new repository that will contain all of the .NET product repos + whatever submodules they have copied inside (instead of keeping them as submodules). This repository will be used to ship the source-build version of .NET for RedHat and Canonical.

We are unsure about the licensing for the repository and also other files required in the root.
Can we put the regular MIT license even though there are other sources synced inside that have a different license?
Do we also need to put the other docs such as what is in the new repo template: https://github.com/dotnet/new-repo?

**Comment by premun** [comment]
Ok, so from the discussions, it seems like we should have these files in the VMR:

1. `CODE_OF_CONDUCT.md`
2. Special `CONTRIBUTING.md` that points that PRs should be made to the individual repos (unless it's us and we're doing something special)
3. `SECURITY.md` (❓❓❓ - no one mentioned this one but I see it in repositories and looks like it won't hurt anything?)
3. `LICENSE.md` (❓❓❓ - license for other files than the ones mirrored from elsewhere - should it be MIT or Apache?)
4.  Special `THIRD-PARTY-NOTICES.TXT` that would be an aggregation of all licenses and external repositories found in the repo
    - Example in runtime: https://github.com/dotnet/runtime/commits/main/src/installer/pkg/THIRD-PARTY-NOTICES.TXT
    - It is generated on demand by https://github.com/dotnet/runtime/blob/main/eng/regenerate-third-party-notices.proj
    - We will need to accommodate the inlined submodules as well when porting this tooling
    - I opened an issue for that: https://github.com/dotnet/arcade/issues/11397

cc @mmitche @richlander @terrajobst @jkotas @tkapin

**Comment by jkotas** [comment]
> SECURITY.md (no one mentioned this one but I see it in repositories and looks like it won't hurt anything?)

The compliance checking bot look for this file. You want to have this file in the repo to make the bot happy.

> license for other files than the ones mirrored from elsewhere - should it be MIT or Apache?)

MIT

**Comment by premun** [comment]
Here is a PR with the files that will be used for the VMR:
https://github.com/dotnet/installer/pull/14848

**Comment by premun** [comment]
We're up!
