### ISSUE TITLE
Kusto client secrets are expired on staging

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#10911]
Today I saw the following error in staging: 

```
Kusto.Data.Exceptions.KustoClientApplicationAuthenticationException: Kusto client failed to perform AAD application authentication. This is not a Kusto service error. Please review your application credentials.
Full details: 'AADSTS7000222: The provided client secret keys for app are expired.
```

>  Response status code does not indicate success: 401 (Unauthorized)

**Comment by ChadNedzlek** [comment]
Where is staging? Which secret? Which application? I need a few more details. :-)

**Comment by AlitzelMendez** [comment]
oh sorry! 
I saw it in couple of helix-services applications: [Query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fcab65fc3-d077-467d-931f-3932eabf36d3%2FresourceGroups%2Fdotnet-eng-int-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng-int/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAw3MMQrDMBBE0T6nGHwTQzpDilwgLNLYXpC0QrsmjQ9vtZ%252FHjyGJ%252FrrxPzmISnc5iGQtRJtj2S4PQyrKFthFCzNm6By7jYp1fUN6X%252BYhq4e2FBPblX9fK%252FxI5QMRKS%252FGYgAAAA%253D%253D/timespan/P1D) :

fabric:/Helix/BuildResultAnalysisProcessor
fabric:/Helix/TestDataAggregationService
fabric:/Helix/DataMigration
fabric:/Helix/SQLCleaner

**Comment by ChadNedzlek** [comment]
K. I'll see if I can find out why.

**Comment by ChadNedzlek** [comment]
The weekly build ran, the expirations must be wrong.

**Comment by garath** [comment]
This _should_ be fixed as of now.

**Comment by ChadNedzlek** [comment]
Fixed.
