### ISSUE TITLE
User study feedback: Header names are confusing

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10914]
A lot of feedback regarding confusion around the header wording we chose. Folks did not understand the different between "Unique Build Failures" and "Merging this PR may introduce X test failures". The word "unique" was also confusing, and some asked, "why not unique test failures?". "Shared" in Shared Test Failures was also confusing. 

Perhaps we should be clearer with a simple: "Build Failures" and "Test Failures". We could include the count of failures in both cases in parentheses in the title).

**Comment by ChadNedzlek** [comment]
Yeah, I think we might be trying to be... to helpful with some of the headers.

**Comment by missymessa** [comment]
Let's go with "Build Failures" and "Test Failures (X tests failed)"

**Comment by missymessa** [comment]
PR: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/26286

**Comment by missymessa** [comment]
Rolled out. Closing
