### ISSUE TITLE
Adopt native Windows ARM64 Python 3 when possible

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#10925]
Originating from https://github.com/dotnet/arcade/issues/10168.  Tracking issue to periodically check on the latest native ARM64 windows Python 3 builds, and see if it can successfully run all the Helix client's dependencies.

**Comment by 333fred** [comment]
Sometimes I hate being first in the list.

**Comment by MattGal** [comment]
Given the AMD64 performance on the Windows.11.Arm64/Windows.11.Arm64.Open machines, there's little real need for this.  Closing.
