### ISSUE TITLE
User study feedback: More collapsible sections

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10931]
There is a LOT going on in Build Analysis, that some folks would appreciate it if they can collapse more sections. Specifically the Error Messages and Stack Traces, as well as whole headers of sections. 

@AlitzelMendez, did we experiment with how much we would be able to collapse, and did GitHub's formatting make it look bad? 

----

Additional information based on our team sync: 

- Be able to determine which sections are important and default not collapse those sections (e.g. over a certain number of tests is more important than a build failure)
- Sections that we should collapse: 
  - [x] List of configurations a test is failing on
  - [ ] ~~Stack Trace / Error Message~~
  - [ ] ~~Data Driven Tests~~
  - [x] Whole sections (e.g. Build Failures, Test Failures, Known Issues)

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

- Adding the ability to collapse top level headers in Build Analysis
- Adding the ability to collapse individual tests in Build Analysis

**Comment by ChadNedzlek** [comment]
I wonder if can maybe always have them be collapsable, but be smart about if they are collapsed by default.  Using the "open" attribute, we can decide if something is collapsed or not.  So maybe when there is only 1 o two things, we could have them expanded by default, but if there are a ton, we can collapse them by default (so that they don't overwhelm the user).

**Comment by markwilkie** [comment]
Yep - we heard from a lot of folks that the build analysis screen as too busy and hard to decipher.  So.....let's try being smart (the best) we can with collapsible sections.

**Comment by missymessa** [comment]
PR that addresses collapsing top level and tests: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/28687

**Comment by missymessa** [comment]
Took a peek at a couple of failing PRs in product repos and it looks like the collapsible sections are showing up correctly when avaiable. Closing :)
