### ISSUE TITLE
Update VS 2022 to latest preview

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#10949]
Per request from our customers, we need to generate an image with VS 17.4 - Preview 2.1. We are currently working with tactics to verify we can bypass scouting and put this new release directly into "production"

**Comment by riarenas** [comment]
Do we have any context on why this ask wasn't done before the breaking changes were merged, since it looks like the product teams were fully aware this would cause breaks downstream?

**Comment by ChadNedzlek** [comment]
Indeed. it's... frustrating to have things light on fire when they could pretty easily have not been fires had people just communicated their needs and expectations to us more clearly.

**Comment by dkurepa** [comment]
PR for the base images: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/26055
I will also updated the GA Scouting queue, since 17.3.4 was recently released

**Comment by dkurepa** [comment]
PR for the queues: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/26057

**Comment by premun** [comment]
Rolled out
