### ISSUE TITLE
Create epic for tracking known issues

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#10944]
@markwilkie: Namely, setup and epic for this and add a PR to the dev handbook

**Comment by missymessa** [comment]
Is the epic going to track Known Issue like the GitHub project currently does, or is this an epic for future work?

**Comment by missymessa** [comment]
Let's use a label instead, so action item is just to create the label (and this is only for infra Known Issues). 

And add documentation for this :D

**Comment by missymessa** [comment]
Can reopen this work if we need it in the future.
