### ISSUE TITLE
Add native tools on machine parameter to build.ps1

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#10951]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In order to use native tools on machine locally, the `NativeToolsOnMachine` environment variable needs to be specified. This is easy to do in YAML, but when using `eng/common/build.ps1` it's not quite as easy. We should add a parameter to that build script to make specifying native tools on machine easier.

**Comment by RussKie** [comment]
Would we need this for release/3.1 and release/5.0 branches as well?

**Comment by jonfortescue** [comment]
@RussKie Yup, I'm backporting to the other branches as we go. :)
