### ISSUE TITLE
User study feedback: Guidance for how to navigate Build Analysis

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10971]
We should consider including a link (in our documentation) for how to navigate Build Analysis so folks have a better understanding the first couple of times they look at it. 

Other things we could do are provide a legend for symbols on the page (although we think they're self-explanatory, it might not be to others, especially the first couple of times they're engaging with the feature). Or maybe a table of contents (if character limitations allow)?

This work could also be lumped together with: https://github.com/dotnet/arcade/issues/10964

**Comment by AlitzelMendez** [comment]
we already added links to landing page to navigate build analysis better. closing
