### ISSUE TITLE
Lots of images need update UpdateRequiredDate (10/12/2022) 

### ISSUE THREAD

**Issue by v-zheyan** [dotnet/arcade#10989]
Lots of images reaching UpdateRequiredDate on 10/12/2022 and we will update them from the Helix test matrix. This needs to be included in messages about rollouts.

Affected queues:
build.server.amd64.vs2017
build.server.amd64.vs2017.open
build.server.amd64.vs2019
build.server.amd64.vs2019.open

build.windows.10.amd64.vs2017
build.windows.10.amd64.vs2019
build.windows.10.amd64.vs2017.open
build.windows.10.amd64.vs2019.open
build.windows.10.amd64.vs2019.pre
build.windows.10.amd64.vs2019.pre.open
build.windows.10.amd64.es.vs2017.open

build.windows.amd64.vs2022.pre
build.windows.amd64.vs2022.pre.open
build.windows.amd64.vs2022.pre.scout.open
build.windows.amd64.vs2022.scout.open

mariner.2.amd64
mariner.2.amd64.open
mariner.2.amd64.open.rt
mariner.2.amd64.open.svc
mariner.2.amd64.rt
mariner.2.amd64.svc

windows.10.amd64.appcompat
windows.10.amd64.appcompatpr
windows.10.amd64.client20h2.open.reunion
windows.10.amd64.client20h2.reunion
windows.10.amd64.client20h2.xaml
windows.10.amd64.clientpre.vs2019.pre
windows.10.amd64.clientpre.vs2019.pre.svc
windows.10.amd64.clientrs5
windows.10.amd64.clientrs5.open
windows.10.amd64.clientrs5.open.reunion
windows.10.amd64.clientrs5.open.rt
windows.10.amd64.clientrs5.open.svc
windows.10.amd64.clientrs5.open.xaml
windows.10.amd64.clientrs5.reunion
windows.10.amd64.clientrs5.svc
windows.10.amd64.clientrs5.xaml
windows.10.amd64.coreappcompat
windows.10.amd64.coreappcompat.pr
windows.10.amd64.server2022.es
windows.10.amd64.server2022.es.open
windows.10.amd64.server2022.es.open.rt
windows.10.amd64.server2022.es.open.svc
windows.10.amd64.server2022.es.rt
windows.10.amd64.server2022.es.svc
windows.10.amd64.serverrs5
windows.10.amd64.serverrs5.open
windows.10.amd64.serverrs5.open.rt
windows.10.amd64.serverrs5.open.svc
windows.10.amd64.serverrs5.rt
windows.10.amd64.serverrs5.svc
windows.10.amd64.tof

windows.81.amd64
windows.81.amd64.open
windows.81.amd64.open.rt
windows.81.amd64.open.svc
windows.81.amd64.rt
windows.81.amd64.svc

windows.amd64.vs2022.pre
windows.amd64.vs2022.pre.open
windows.amd64.vs2022.pre.open.svc
windows.amd64.vs2022.pre.svc

windows.server.amd64.vs2017
windows.server.amd64.vs2017.open
windows.server.amd64.vs2019
windows.server.amd64.vs2019.open
windows.server.amd64.vs2019.open.svc
windows.server.amd64.vs2019.svc

windows.vs2017.amd64
windows.vs2017.amd64.es.open
windows.vs2017.amd64.open
windows.vs2019.amd64
windows.vs2019.amd64.open
windows.vs2022.scout.amd64.open
windows.vs2022preview.amd64
windows.vs2022preview.amd64.open
windows.vs2022preview.scout.amd64.open

**Comment by MattGal** [comment]
Image updates are merged and these updates roll out next week.  We might just say "Updated all required base images" instead of this giant list, though.

**Comment by MattGal** [comment]
Rolled out Weds.
