### ISSUE TITLE
[Feed package] Enable dependency uptake in Arcade

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#11]
Feed package currently has a dependency on VersionTools which is published out of BuildTools.  Until that dependency is removed, we should look into a maestro type solution for taking updates.  Also, in general we'll need some solution for this going forward.

**Comment by maririos** [comment]
After talking to @mmitche , the Feed package version that we have in Arcade, is going to remove any dependency with VersionTools and instead, push the publish information to Darc/Maestro

**Comment by maririos** [comment]
FYI @jcagme

**Comment by maririos** [comment]
This is covered by the work of Darc and Maestro++. Current work is happening to enabling Arcade to use those systems.
Example PR https://github.com/dotnet/arcade/pull/489
