### ISSUE TITLE
Docker image caching in dnceng AzDo instances

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#11018]
The App Center team was able to reduce network traffic and build time by caching their docker images in their AzDo instance, a similar approach would great to have for dnceng repos 

cc @dougbu

**Comment by garath** [comment]
What does "cache" mean exactly? Is it having a local-to-the-build-machine copy of docker images? 

This would improve the "docker pull" step in a build, right? How much time is spent there now?

**Comment by ulisesh** [comment]
> What does "cache" mean exactly? Is it having a local-to-the-build-machine copy of docker images?

Yes, I think that's it means

> This would improve the "docker pull" step in a build, right? How much time is spent there now?
Right, I don't have all the data. This was Doug's idea best on the success story from App Center team shared DevDiv Quality Starts

**Comment by ulisesh** [comment]
Investigating a different issue, I came across [AzDo's documentation](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md) for their images. It mentions that their image already has some docker images cached. We could do the same and cache our supported docker images in MCR, that way all our build and test machines don't have to spend time downloading the images.

**Comment by adiaaida** [comment]
I got curious into our actual numbers, and I don't think we're being affected by this in the way that really makes sense to spend a large amount of time improving. Here are our numbers over the last 90 days:

Avg: 1:52.77
Median: 1:14.75
Min: 0:02.82
Max: 48:17.75

Out of 182319 “Initialize containers” steps  in the last 90, 4 took longer than 30 minutes, and 183 were longer than 10 minutes. So 0.1% of our runs take longer than 10 minutes, and the median takes just over a minute. 97719 of those runs were < 1m. It's clear that some caching is already happening (the min cases, though there aren't *that* many of them), and I just don't know if fixing the 1m cases is really going to make a noticeable difference to our customers.

For just runs with "Azure Pipelines" in the WorkerName, our numbers are even better:

Avg: 0:43.7488398
Median: 0:45.94
Worst: 39:36.51
Best: 00:06.92

Over 19701 cases (so significantly less than those run on our NetCore pools).

**Comment by adiaaida** [comment]
Especially when the example was "we moved pools and our docker pulls started taken 10-15 minutes" which we are not experiencing, in general.

**Comment by adiaaida** [comment]
Based on the data we collected, we don't believe there is the ROI here, so we are going to close this for now.
