### ISSUE TITLE
Make async triage tool check for open issues with closed epics

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#11029]
Sometimes we close an epic and forget to unassign issues from it to kick them back to triage. The async triage tool find these.

**Comment by ChadNedzlek** [comment]
I feel like @garath was going to run some super awesome query to see what sort of numbers we are talking about here (is it like 2 or 3 low priority issues, or it it dozens/hundreds).

**Comment by garath** [comment]
I was, and sorry for not getting back. It turns out that this particular data (info from the Projects API) is not included in CloudMine, so I can't do this by query.

**Comment by ChadNedzlek** [comment]
Yeah, I was afraid of that. :-( We'll have to write some code to make a bunch of GraphQL queries, I think.

**Comment by adiaaida** [comment]
I don't think we'll have to do much more than we already do. We already grab the epics list, we already grab all the issues, and we already grab info about if the issues are open or closed, so we should just be able to search our epic list and see if the listed epic exists, is open, or is closed.

**Comment by ChadNedzlek** [comment]
Yeah, I was just hoping to try to stop the tool from expanding, since it's a relatively awkward thing to run.  It feels like it should only do the teamsy part of stuff (since that's what requires it being run manually and not made a service).
