### ISSUE TITLE
Invalid doc url in the comment

### ISSUE THREAD

**Issue by ryuuc** [dotnet/arcade#11038]
below doc url  is invalid
https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/SignCheck/Microsoft.SignCheck/Interop/PortableExecutable/ImageDataDirectory.cs#L10

although it can redirect to a new address ->  https://learn.microsoft.com/en-us/windows/desktop/api/winnt/ns-winnt-_image_data_directory, it's still 404.

the right one could be https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-image_data_directory , looks like the directory has been renamed  `windows/desktop/api ` -> ` windows/win32/api `  ?

**Comment by AlitzelMendez** [comment]
PR: https://github.com/dotnet/arcade/pull/11443

**Comment by AlitzelMendez** [comment]
Thanks @ryuuc for bringing this to our attention!!
