### ISSUE TITLE
Reimage or move workspace of low-disk-space android test agents

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#11049]
I've made it so as of today (9/28/2022) reimaged machines should have their workspace on %SYSTEMDRIVE%, however either these need to be reimaged _or_ they need to have the HELIX_WORK_ROOT env var moved to the bigger disk

DNCENGWIN-062
DNCENGWIN-064
DNCENGWIN-066
DNCENGWIN-068
DNCENGWIN-069
DNCENGWIN-070
DNCENGWIN-071
DNCENGWIN-072
DNCENGWIN-074
DNCENGWIN-075
DNCENGWIN-077
DNCENGWIN-078
DNCENGWIN-079
DNCENGWIN-080
DNCENGWIN-082
DNCENGWIN-083
DNCENGWIN-084
DNCENGWIN-085
DNCENGWIN-086
DNCENGWIN-087
DNCENGWIN-088
DNCENGWIN-089
DNCENGWIN-090
DNCENGWIN-091
DNCENGWIN-092
DNCENGWIN-093

Causes symptoms seen in https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-75609-merge-ccf9df10c434471bbc/HelloAndroid/1/console.7b3b51a9.log?helixlogtype=result 
`Windows Power Shell terminated with the following error:
Couldnotloadfileorassembly'System.Management.Automation,Version=3.0.0.0,Culture=neutral,PublicKeyToken=31bf3856ad364e35'oroneofitsdependencies.Thepagingfileistoosmallforthisoperationtocomplete.(ExceptionfromHRESULT:0x800705AF)`

See me for any questions.

**Comment by ulisesh** [comment]
Asked to reimage the devices in https://portal.microsofticm.com/imp/v3/incidents/details/338419626/home

**Comment by ulisesh** [comment]
Paul is working on this

**Comment by ulisesh** [comment]
Waiting for DDFun to make progress on this

**Comment by ulisesh** [comment]
Paul is validating the SystemDrive changes in DNCENGWIN-062, 64, and 66

**Comment by ulisesh** [comment]
Paul is still having problems reimaging the devices, assigning the issue to @MattGal

**Comment by ulisesh** [comment]
Paul is still working on this

**Comment by ulisesh** [comment]
DDFun is still working on this, the update was: I have finished setting up the OS on the last batch of machines and they are now ready to have MLS re-do the Android phone trust

**Comment by ulisesh** [comment]
All devices have been reimaged and are back online. Closing issue
