### ISSUE TITLE
Merge on Red report timescale improvement

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#11051]
Per @JulieLeeMSFT: 

> In the power BI dashboard for merge on red, please match timescale on the x axis for 2 upper charts. If you see below screenshot, 72 failed issues are spread in 2 bars in the upper right chart. 

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/47990216/192900715-aafeb557-96e1-4e4f-8570-3b76bfafdbfd.png)

https://msit.powerbi.com/groups/de8c4cb8-b06d-4af8-8609-3182bb4bdc7c/reports/8bdd4339-ea39-4e67-963a-fc44a450605b/ReportSection

**Comment by AlitzelMendez** [comment]
this has been fixed
