### ISSUE TITLE
Matrix of truth daily pipeline broken 

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#11057]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The pipeline is broken: https://dev.azure.com/dnceng/internal/_build/results?buildId=2007037&view=results

The pipeline doesn't give enough information to make a guess at what could be wrong.

```
Starting: Run Matrix Of Truth CLI
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_work\_temp\648b8a47-e1aa-4686-a337-9639992db87a.cmd""
The system cannot find the path specified.
##[error]Cmd.exe exited with code '1'.
Finishing: Run Matrix Of Truth CLI
```

**Comment by garath** [comment]
There's a good chance I broke this when I moved everything to net6. I'll take it for investigation.

**Comment by garath** [comment]
From what I understand, this isn't critical, but if anyone has concerns I can submit a work-around to execute the MoT CLI directly. Just let me know.

**Comment by dkurepa** [comment]
Yup, I also think the pipeline is failing because it's not finding any 6.0 binaries. 
I don't know if we need to unblock this urgently, the PowerBI reports should have the data from the last successful run. @ilyas1974 , what do you think?

**Comment by riarenas** [comment]
The pipeline is no longer blocked. Closing.
