### ISSUE TITLE
Build Analysis Feedback took fails with "Gateway Time-Out" error

### ISSUE THREAD

**Issue by jkotas** [dotnet/arcade#11071]
### Build

Try to submit feedback by clicking thumbs up / thumbs down button in https://github.com/dotnet/runtime/runs/8617852673. The feedback forms open, but attempt to submit the form fails with:

<img width="415" alt="image" src="https://user-images.githubusercontent.com/6668460/193159388-e1c3fb00-4461-47b2-ac15-e5158802d200.png">

The tracking issue apparently gets created, but the browser does not get the response back. I ended up opening duplicate issues as I have retried it multiple times (https://github.com/dotnet/arcade/issues/11068, https://github.com/dotnet/arcade/issues/11069, https://github.com/dotnet/arcade/issues/11070)

### Pull Request

https://github.com/dotnet/runtime/pull/76357

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false
 }
 ```

**Comment by missymessa** [comment]
@ChadNedzlek fyi

**Comment by ChadNedzlek** [comment]
That's... odd...

**Comment by ChadNedzlek** [comment]
This is pretty low bar for FR (since we don't get a ton of feedback and the feedback _is_ created, so we just have to close the duplicate issues).  Thoughts @ilyas1974?

**Comment by ChadNedzlek** [comment]
This is one of the very few posts in our service... I wonder if that's causing a problem...

**Comment by ChadNedzlek** [comment]
We go throttled by AzDO, and the gave us a "retry-after" header of 4 minutes. We dutifully waited that long, but that was too long for the browser, and it called it dead.  We might need to get a boost to our AzDO quota... gosh this change to the new server has been painful.

/fyi @alexperovich @Chrisboh @ilyas1974 @MattGal: I'm probably going to need to ask the AzDO folks for an increase to our quotas for stuff.

**Comment by ChadNedzlek** [comment]
If you look at this chart it shows the times we got throttled:
```
traces
| where timestamp > ago(30d)
| where message startswith "Retry-After detected"
| summarize count() by bin(timestamp, 1h)
| render columnchart 
```
It's only be a few times since we got the increased capacity.  I think I'm going to call this one a sad fluke and close it, but we might want to keep an eye out for it.

**Comment by ChadNedzlek** [comment]
You can see one of the logs for the failed request here:
```
traces
| where operation_Id == '78acecd5dea44657775a3d8660b76ca5'
| order by timestamp desc
```

**Comment by alexperovich** [comment]
Why do we not just return 204 to the browser and continue processing? Then we can take however long we need to finish the processing.

**Comment by ChadNedzlek** [comment]
What if it doesn't work? We shouldn't tell the user everything is fine if it doesn't work. :-) Also it's a pain to both return and keep running in ASP.NET. Also also also, it's never been a problem before that, and making all our AzDO asynchronous queue based is a lot of work (and this feature is relatively low usage)
