### ISSUE TITLE
Install XCode 13.4 on runtime iOS and tvOS helix queues

### ISSUE THREAD

**Issue by steveisok** [dotnet/arcade#11082]
There are some reliability issues we are having with the usbmux connection between machine and device.  Upgrading xcode to 13.4 (we're on 13.0) is one inexpensive step to see if that solves the issue.  Please upgrade the machines on the following queues:

- [ ] ~~OSX.1015.Amd64.Iphone.Open~~
- [x] OSX.1200.Amd64.Iphone.Open
- [ ] ~~OSX.1015.Amd64.AppleTV.Open~~
- [ ] ~~OSX.1100.Amd64.AppleTV.Open~~

https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/870/Install-new-version-of-Xcode-on-Helix-machines

**Comment by premun** [comment]
Yeah, this sounds like a reasonable step

**Comment by premun** [comment]
Though we really didn't have these issues until July (and we were on 11.6, 12.4 and 13.0 for some time)

**Comment by premun** [comment]
@steveisok so Xcode needs MacOS 12+ so with 10.15 queues and Xcode 12.4 we're at the latest possible unfortunately.

@ilyas1974 how does it look with MacOS 10.15 and deprecation of OSX? I can see that this month MacOS 13 is supposed to be released. I understand we will migrate to 13/12/11 and ditch 10.15?

**Comment by steveisok** [comment]
> @steveisok so Xcode needs MacOS 12+ so with 10.15 queues and Xcode 12.4 we're at the latest possible unfortunately.

I'm ok bumping the machines to MacOS 12.

**Comment by premun** [comment]
@steveisok iPhone 12.00 queue is already on 13.4

**Comment by premun** [comment]
The iPhone 12.00 queue with Xcode 13.4.1 still has this issue:
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-xharness-refs-pull-957-merge-fc8056521e334592a8/ios-device-System.Buffers.Tests.app/1/console.0ed2dfbb.log?helixlogtype=result

I'd look somewhere else. Meanwhile we can have a conversation on how to update the 10.15 queues.

**Comment by steveisok** [comment]
I agree.  It does not seem that upgrading would solve the problem.

**Comment by ulisesh** [comment]
FYI, as part of #11088, I upgraded osx.1100.amd64.appletv.open to Xcode 13.2.1 and planning to upgrade osx.1200.amd64.iphone.open to Xcode 14.0.1 tomorrow. Please let me know if you think we shouldn't upgrade to 14.0.1

**Comment by premun** [comment]
Please don't do Xcode 14. The support in mlaunch has not been yet properly merged into main (we're using non-main mlaunch at the moment).

The only queues with Xcode 14 should be scouting

**Comment by premun** [comment]
Closing this as it should be handled by https://github.com/dotnet/arcade/issues/11082
