### ISSUE TITLE
Upgrade Xcode

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#11088]
Requested by @jkoritzinsky on Teams

**Comment by ulisesh** [comment]
Waiting for some direction from @ilyas1974

**Comment by ulisesh** [comment]
I'll do the work to upgrade Xcode in our OSX queues with the following versions

OSX 10.15 -> Xcode 12.4
OSX 11.00 -> Xcode 13.2.1
OSX 12.00 -> Xcode 14.0.1

**Comment by ulisesh** [comment]
Both osx.1100.amd64 and osx.1100.amd64.appletv.open now have Xcode 13.2.1

**Comment by ulisesh** [comment]
There are 23 machines where the upgrade didn't work in osx.1100.amd64.open. I'll work on them tomorrow

**Comment by ulisesh** [comment]
These 23 machines have the OS in a small disk, I'll put them offline and ask DDFun to reimage them so that the Helix work directory in a bigger disk

Premek mentioned that we shouln't upgrade OS 12.00 queues

**Comment by ulisesh** [comment]
I won't create the IcM ticket until we rollout next week and we publish on-prem scripts with the new xcode version https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/26569

**Comment by ulisesh** [comment]
The PR was merged and the changes will be rolled out tomorrow, once this is done I'll create the IcM

**Comment by ulisesh** [comment]
IcM created: https://portal.microsofticm.com/imp/v3/incidents/details/342701780/home

**Comment by ulisesh** [comment]
MSL is working on this

**Comment by ulisesh** [comment]
DDFun and MLS are still making progress, there are still 15 devices offline

**Comment by ulisesh** [comment]
MLS is working on last batch of Macs

**Comment by garath** [comment]
isn't a group of macs called a "network"?

**Comment by ulisesh** [comment]
All machines have been reimaged and are using their big disk, closing
