### ISSUE TITLE
Document `source-mappings.json` behaviour

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#11099]
The file now expects some things which are not clear and we should document it somewhere.

Options:
- Allow JSON comments directly in this file (.NET supports that) and put the comments inside
- Add some README somewhere
- Add JSON schema - https://json-schema.org/learn/getting-started-step-by-step

Living list of things that we should document:
- Default cloaking filters + overriding
- Cloaking submodules
- Git attributes for overriding cloaking filters

**Comment by premun** [comment]
@tkapin @mmitche do you have an opinion on this?

This is something I'd start doing rather sooner.

**Comment by mmitche** [comment]
I think a combo:

- Allow JSON comments directly in this file (.NET supports that) and put the comments inside
- Add some README somewhere

The readme should probably be overall VMR mechanics and design.

**Comment by premun** [comment]
Alright, this has been resolved. We have documentation in the JSON (https://github.com/dotnet/installer/pull/14848) pointing to the design documents (https://github.com/dotnet/arcade/pull/11439/files)
