### ISSUE TITLE
Helix job links no longer show up in builds

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/arcade#11129]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain

It used to be that I could get a link to the Helix job from AzDo, like so:

```
  Sent Helix Job; see work items at https://helix.dot.net/api/jobs/e6df725b-7a21-4eab-a4c1-3c1e82c8b4be/workitems?api-version=2019-06-17
```

But what I see now is:

```
  Sent Helix Job; see work items at [System.String]::Copy('').TrimEnd('/')/api/jobs/5c729cc2-8299-4430-86f7-001e35434c43/workitems?api-version=2019-06-17
```

See e.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=39472&view=logs&jobId=b2c675c1-1c32-50e9-7c40-e762459300db&j=b2c675c1-1c32-50e9-7c40-e762459300db&t=4f51db95-f7de-5a4e-cd10-f078782dd75b

**Comment by riarenas** [comment]
looks like for runtime's case, https://github.com/dotnet/runtime/pull/76605 includes the fix. In the meantime, you can use the helix artifacts tab in the test section of the build, which is the preferred way to access helix job information. There's a good chance we're going to remove the links altogether from the console output. https://github.com/dotnet/arcade/issues/8948

**Comment by riarenas** [comment]
The necessary arcade sdk to get this bug reverted has already flowed down to repos, and as they take the updates they should see this resolved. Closing but feel free to reopen if you keep seeing this even after having the most up to date arcade updates.
