### ISSUE TITLE
Matrix of Truth Docker Parser fix

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#11134]
The new tagging schema is causing issues with the Matrix of Truth docker parser, it currently can't parse tags with two "parts" (centos-7 for example) it should be an easy fix tho.

**Comment by dkurepa** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/26532

**Comment by michellemcdaniel** [comment]
Closing this as it looks like the fix was checked in
