### ISSUE TITLE
[Darc] Versions.props should use "PackageVersion" as property suffix

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1114]
To minimize churn in repos, we should use PackageVersion as the suffix for the Version.props properties.

Update the spec in the process.

**Comment by tmat** [comment]
We are not overriding package versions as we did with ProdCon, right? So why does it matter whether we use `-Version` or `-PackageVersion`?

**Comment by weshaggard** [comment]
I agree it shouldn't matter what we use although it is good to be consistent. If we use different values then DARC needs to allow for configuration of what properties to use if they don't follow convention, which I also think we should provide.

**Comment by tmat** [comment]
I see. Makes sense then.

**Comment by mmitche** [comment]
#1186
