### ISSUE TITLE
Fix query for Build monitor service hook deliveries alert

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#11152]
[Build monitor service hook deliveries alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/historical/backend-status?tab=query&viewPanel=78&orgId=1&editPanel=78) got broken after the PR https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/25713

We have to fix the query to include the new names

cc @missymessa

**Comment by riarenas** [comment]
As a bandaid, I updated Grafana to look for both `BuildMonitorWebhook-dnceng` and `BuildMonitorWebhook`, but we might want to add the rest of the orgs? Currently we only have build monitor alert on builds from dnceng though, and I'm not sure the build monitor itself supports multiple orgs.

**Comment by riarenas** [comment]
Just taking this for a quick fix in FR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/26684

**Comment by riarenas** [comment]
This was rolled out
