### ISSUE TITLE
Onboard dnceng repos to C3K

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#11151]
Swap current CodeQL workflow to use the C3K extension.

Priority 1:
- [x] arcade/main: #11155
    Test run: https://dnceng.visualstudio.com/internal/_build/results?buildId=2016359&view=results
- [x] arcade/release-6.0:  https://github.com/dotnet/arcade/pull/11218
    Test run: https://dnceng.visualstudio.com/internal/_build/results?buildId=2017641&view=results
- [x] arcade/release-7.0: https://github.com/dotnet/arcade/pull/11216
    Test run: https://dnceng.visualstudio.com/internal/_build/results?buildId=2017640&view=results
- [x] arcade-services: https://github.com/dotnet/arcade-services/pull/2053
    Test run: https://dnceng.visualstudio.com/internal/_build/results?buildId=2017647&view=logs&j=179e7e63-bd3a-519a-2d5e-221496da915a

- [x] dotnet-helix-service: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/26638
    Test run: https://dnceng.visualstudio.com/internal/_build/results?buildId=2017701&view=logs&j=17b0a9f0-33a0-5d1c-11b5-282e644826af

- [x] dotnet-helix-machines: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/26632
    Test run: https://dnceng.visualstudio.com/internal/_build/results?buildId=2017686&view=results
    (Waiting on PR to merge, test run looks good)

Priority 2: 
- [x] xharness: https://github.com/dotnet/xharness/pull/965  
    Test run: https://dnceng.visualstudio.com/internal/_build/results?buildId=2017951&view=results
- [x] xliff-tasks: https://github.com/dotnet/xliff-tasks/pull/669
    Test run: https://dnceng.visualstudio.com/internal/_build/results?buildId=2017847&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9
- [x] arcade-extensions:  https://github.com/dotnet/arcade-extensions/pull/57
    Test run: https://dnceng.visualstudio.com/internal/_build/results?buildId=2017849&view=results
- [x] source-indexer:  https://github.com/dotnet/source-indexer/pull/108/files
    Test run: https://dnceng.visualstudio.com/internal/_build/results?buildId=2017886&view=results
- [x] dotnet-migrate-package: https://dnceng.visualstudio.com/internal/_git/dotnet-migrate-package/pullrequest/26640?_a=files
    Test run: https://dnceng.visualstudio.com/internal/_build/results?buildId=2017852&view=results

**Comment by MattGal** [comment]
I don't think these pipelines honor the "TSAEnabled" parameter as plumbed through.  I am trying a variation on this via https://github.com/dotnet/arcade/pull/11193 and will move it to the other yamls if/when it solves the problem.

**Comment by garath** [comment]
Oh that's unfortunate. 

I think you can then just create a new pipeline variable in the UI with that name.

**Comment by MattGal** [comment]
Created https://github.com/dotnet/arcade/pull/11263 to update the guidance

**Comment by garath** [comment]
All of our repos are updated, regular scheduled builds are happening and reporting is working as expected. Yay!
