### ISSUE TITLE
[tvOS] System.Security.Cryptography crashes exit code 80

### ISSUE THREAD

**Issue by mdh1418** [dotnet/arcade#11167]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=38726
https://dev.azure.com/dnceng-public/public/_build/results?buildId=38726&view=logs&j=3f1a5045-515d-58b5-c978-1369a4d554be&t=2f13cef9-de38-5712-3330-0d9e881c0fb9&s=b15d9194-8f26-5328-b47f-5968c76b37e7
https://dev.azure.com/dnceng-public/public/_build/results?buildId=38726&view=logs&j=f04e4db6-4dff-5e05-5bcf-b9e1f1b162f3&t=1fc9e925-43ca-5174-4bce-b2f00bdffe8b&s=d654deb9-056d-50a2-1717-90c08683d50a

### Build leg reported

System.Security.Cryptography.Tests.WorkItemExecution

### Pull Request

https://github.com/dotnet/runtime/pull/76465

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false
 }
 ```

### Additional information about the issue reported

This suite has crashed on 3 of the 5 builds for this PR. 
These other suites crashed for the other 2 builds in which System.Security.Cryptography didn't crash.
System.ComponentModel.Composition.Tests
System.Net.Mail.Functional.Tests
System.Composition.TypedParts.Tests

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by MattGal** [comment]
Your test is actually failing and the logs are available to read.  I suggest getting access to a TvOS device and running locally?

console log has:
```
[16:59:55] dbug: Process mlaunch exited with 0
[16:59:55] fail: Application test run crashed
                 No test log file was produced
                 
                 Check logs for more information

```

... so I checked https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76465-merge-e226d406a7b649f68e/System.Security.Cryptography.Tests/1/net.dot.System.Security.Cryptography.Tests.log?helixlogtype=result 


... inside this log:

```
[16:59:18.3792670] 2022-10-04 16:59:18.365 System.Security.Cryptography.Tests[44065:921965] 	[PASS] System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests.InvalidCFBFeedbackSizes
[16:59:18.3844680] 2022-10-04 16:59:18.369 System.Security.Cryptography.Tests[44065:921965] 	[PASS] System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests.InvalidIVSizes
[16:59:18.3845650] 2022-10-04 16:59:18.371 System.Security.Cryptography.Tests[44065:921965] 	[PASS] System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests.InvalidIVSizes
[16:59:19.3350050] Xamarin.Hosting: Process '44065' exited with exit code  or crashing signal 9.
[16:59:19.3357420] Application 'net.dot.System.Security.Cryptography.Tests' terminated (with exit code '' and/or crashing signal '9).
```

**Comment by ulisesh** [comment]
Agree with Matt, this doesn't feel look an infrastructure issue

**Comment by steveisok** [comment]
I agree, this particular failure is a legit crash.
