### ISSUE TITLE
timeouts during publishing steps in maestro build promotion pipeline

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#11165]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Some official  builds are failing during the publish-using darc stage due to timeouts. The timeouts seem to be both in the publish-using-darc stage, as well as the underlying promotion build.

example: https://dev.azure.com/dnceng/internal/_build/results?buildId=2013027&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=c7a8693b-2f9c-5ea8-c909-cde9405ac2e1

**Comment by riarenas** [comment]
It looks like there's something actually going on with the publishing task where we are waiting for a long time without logging until we hit the 120 minute timeout. I'm removing my assignment for now while I have more cycles to investigate. At least two of the runtime builds failed due to having a shorter timeout for their darc call than what we have for the promotion build itself, so that should definitely be done, but we shouldn't increase the timeouts on the arcade side until we understand why we're seeing some pauses in the publishing task.

My guess is that this relates to the azure artifacts problems we are experiencing, so maybe the metadata migration will help with this.

**Comment by riarenas** [comment]
We haven't seen any timeouts in the maestro build promotion pipeline since Friday, so I think this is just related to overall feed instability. I'm going to keep track until the end of the week and then close.

**Comment by riarenas** [comment]
We are still seeing a mix of failures in the build promotion pipeline. There were 6 failed builds yesterday, with a mix of:

* 1 timeout
* several 429s when trying to push packages
* failures to download a package from the build's artifacts
* Some failed attempts to publish duplicates. 

Still nothing to see that isn't explained by the artifacts stability issues

**Comment by riarenas** [comment]
We have stopped seeing timeouts or throttling, and the only recent failures look like repo bugs. I think we can close this for now

**Comment by riarenas** [comment]
We're seeing these timeouts again. For example https://dev.azure.com/dnceng/internal/_build/results?buildId=2034088&view=results

FYI @AlitzelMendez

**Comment by epananth** [comment]
@MattGal did some investigation around this already,

"...on the artifacts side looks like there was a config db upgrade, and an upgrade to the partition dbs at around 9:20 pdt
So basically we were running our deployments around that time, might have introduced some slowness trying to write to the dbs while the upgrade tasks were completing. Seeing a slight increase in slow commands around that time. It's totally normal. Have there been any issues after say like 9:30-10?"

Link to the teams chat :  https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1667334327755?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1667334327755&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1667334327755&allowXTenantAccess=false

So, we have nothing to do here. I am going to close this one.
