### ISSUE TITLE
Known issues processing for internal builds

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#11174]
Build analysis processes only builds from public, this prevents us from measuring the impact of a known issue in internal builds.

To make this happen, we would need to:
- Set up a webhook in internal
- Find a way to process known issues without posting a github check

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Process internal build to get known issues information and impact on internal issues

**Comment by AlitzelMendez** [comment]
rolled out
