### ISSUE TITLE
Make artifact information Dictionary case insensitive

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#11184]

**Comment by dkurepa** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/26578

**Comment by dkurepa** [comment]
We ended up not doing this, but adding a bit more information in the exception message, so things are easier to debugg.

**Comment by premun** [comment]
@dkurepa can you assing this to an epic?

**Comment by michellemcdaniel** [comment]
@dkurepa should this issue be closed?

**Comment by dkurepa** [comment]
Closing the issue as we decided it wasn't a good idea
