### ISSUE TITLE
New on-premises queues to support macOS 13

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#11186]
As part of prep for the macOS 13 release, we need to have a few more queues created. 

osx.13.amd64
osx.13.arm64
osx.12.amd64.appletv.open
osx.13.amd64.appletv.open

We will not be moving any systems to these new queues until after the release of macOS 13 - this is just prep for future needs.

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/26581

**Comment by MattGal** [comment]
These are rolled out, closing.
