### ISSUE TITLE
Build analysis generates duplicate reports

### ISSUE THREAD

**Issue by jkotas** [dotnet/arcade#11211]
The tables with hit statistics included in issues are duplicated. It is regression introduced in last few days.

Example from https://github.com/dotnet/runtime/issues/76826:

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[45431](https://dev.azure.com/dnceng-public/public/_build/results?buildId=45431)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/45431/logs/2903)|dotnet/runtime#76764|
|[45701](https://dev.azure.com/dnceng-public/public/_build/results?buildId=45701)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/45701/logs/2613)|dotnet/runtime#76799|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[45431](https://dev.azure.com/dnceng-public/public/_build/results?buildId=45431)|dotnet/runtime|[LibraryImportGenerator.UnitTests.IncrementalGenerationTests.GeneratorRun_WithNewCompilation_DoesNotKeepOldCompilationAlive](https://dev.azure.com/dnceng-public/public/_build/results?buildId=45431&view=ms.vss-test-web.build-test-results-tab&runId=923446&resultId=178030)|dotnet/runtime#76764|
|[45701](https://dev.azure.com/dnceng-public/public/_build/results?buildId=45701)|dotnet/runtime|[LibraryImportGenerator.UnitTests.IncrementalGenerationTests.GeneratorRun_WithNewCompilation_DoesNotKeepOldCompilationAlive](https://dev.azure.com/dnceng-public/public/_build/results?buildId=45701&view=ms.vss-test-web.build-test-results-tab&runId=923292&resultId=109244)|dotnet/runtime#76799|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|4|4|

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Remove duplicated Known Issues matches from issue report

**Comment by jkotas** [comment]
cc @markwilkie @missymessa

**Comment by missymessa** [comment]
cc @ulisesh

**Comment by ulisesh** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/29270

**Comment by ulisesh** [comment]
Validated with https://github.com/dotnet/runtime/issues/35066 it should only test known issues but the error message is in the build logs too
