### ISSUE TITLE
Enable `DNCENGMAC144.local` in the `osx.1200.amd64.iphone.open` queue

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/arcade#11224]
A request came in from @akoeplinger to disable `DNCENGMAC144.local` from the Helix queue as they want to use the machine for debugging an issue with tvOS.

We should enable it back once the machine is no longer needed.

**Comment by ilyas1974** [comment]
Machine was taken offline to investigate issue #10820. Closing this issue.
