### ISSUE TITLE
Generate a call of a base class constructor if the default constructor does not exist.

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade#11254]
# Context
```C#
class A
{
    public A(int a, bool b) { }
}

class B : A
{
    public B() : base(default, default) { }
}
```

Base class **A** does not have default constructor, that's why derived classes must have explicit constructor and call base class constructor.

The question: is it possible having a `INamedTypeSymbol` object (corresponds to A in an example) to determine if it has default constructor or not and if not how to determine the list of parameters for explicit constructor (From example: `A(int a, bool b)`).

Having a constructor (object of `IMethodSymbol`), we'd like to generate compliable code `public B() : base(default, default) { }`

**Comment by andriipatsula** [comment]
@RikkiGibson , could you please assist? It the issue is unclear - we could have a call to discuss. Thanks in advance.

**Comment by RikkiGibson** [comment]
I would check `methodSymbol.ContainingType.BaseType.InstanceConstructors`.
