### ISSUE TITLE
Send to Helix message not formatted correctly

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#11252]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When sending work to helix, the message is mangled when informing the user that a job was sent:

```
Sent Helix Job; see work items at [System.String]::Copy('').TrimEnd('/')/api/jobs/ccb15a88-0a6d-4096-bff5-487e9993e326/workitems?api-version=2019-06-17
```

This makes it hard for users to see the api.

Example pr: https://dev.azure.com/dnceng-public/public/_build/results?buildId=46509&view=logs&j=fa59fe4e-195c-56fa-189b-58fd241f10dd&t=71146b80-38e1-5fea-9b74-ba1045aac3e1&l=356

**Comment by riarenas** [comment]
You might be some versions of the sdk behind. This change was already reverted. See https://github.com/dotnet/arcade/issues/11129 for details.

**Comment by adiaaida** [comment]
Ahhhhh. Ok. This was from runs from a few days ago (and was happening in some of my docker PRs that I was looking at).

**Comment by riarenas** [comment]
as usual, repos always pick up the arcade changes with the bugs quickly but then the fix lingers for a bit 😋 The pr that sdk needs to merge is https://github.com/dotnet/sdk/pull/28504 which in the diff includes the revert of the logging bug: https://github.com/dotnet/arcade/compare/d2d3927...7cdba99
