### ISSUE TITLE
Harden rollout scorer against non-matching started/stopped events

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#11253]
Rollout Scorer has not been generating scorecard PRs for some time, and requires manual intervention to create them, and even then, only one rollout has been scored (see https://github.com/dotnet/arcade/pull/11240) when other rollouts have occurred since then. 

Talked to @jonfortescue about this issue and it looks like there is consistently missing data (specifically an "end time" for the rollout), which signals to the rollout scorer process that the rollout is not ready to be scored. 

The impact of rollout scorer being out of commission means that I don't have an easy way to look up data (e.g. metrics from rollouts that are calculated on the scorecards; lists of hotfix issues related to rollouts) for our rollouts for our retrospective discussions, so that we can learn from what happened and make improvements to our process in the future. 

### Release Note Description
Do not include in release notes.

**Comment by michellemcdaniel** [comment]
Going to put this in Operations. Ops v-team, let me know if you disagree.

**Comment by garath** [comment]
@jonfortescue You said "got it working but don't ask too many questions" (IIRC), right? What does the proper fix look like?

**Comment by jonfortescue** [comment]
We need to teach the rollout scorer that if there isn't an "end time" for a deployment for a couple of days, it's probably done. It should assume completion and move on.

**Comment by missymessa** [comment]
I'm prepping for the retro tomorrow and noticed that the scorecards after the manual fix have been rolling every subsequent build into the score for that scorecard. For example: https://github.com/dotnet/arcade/blob/main/Documentation/TeamProcess/Rollout-Scorecards/Scorecard_2022-09-14.md

9/14 rollout score card contains all builds until 10/12

**Comment by missymessa** [comment]
Also, hotfix links in Helix Machines aren't being pick up in the scorecard creation: https://github.com/dotnet/arcade/blob/main/Documentation/TeamProcess/Rollout-Scorecards/Scorecard_2022-10-26.md#dotnet-helix-machines
