### ISSUE TITLE
Scan VMR in installer's PR gate for binaries

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#11267]
- [ ] We need to add a PR build step that would scan new VMR sources for binaries/any files that are not allowed to be part of the repository.
- [ ] We need to update the VMR Design doc in case we change anything around the cloaking

> Note: We should look into RedHat's/Canonical's tooling and ideally whether we can run the same check as them.
> Related: https://docs.fedoraproject.org/en-US/package-maintainers/Package_Review_Process/

>Note: We can reach out to 1ES too

### Release Note Description
Have a way of detecting binaries when they try to enter the VMR

**Comment by premun** [comment]
This is interesting: https://stackoverflow.com/questions/59869859/how-to-use-libgit2sharp-to-determine-if-a-file-is-binary

**Comment by dkurepa** [comment]
Maybe it'd make sense to add this functionality to the vmr scan operation? The files would already be in the VMR, but we would find out about them. In my mind these scenarios are similar, they're both about files that shouldn't be in the VMR

**Comment by dkurepa** [comment]
We have merged the following PR: https://github.com/dotnet/arcade-services/pull/2177
The implementation works in a similar way to the cloaked file scanner.
We are using the `git diff <zero commit> --numstat` command to get a list of all files and see which of them are binary. The git --numstat command displays the number of lines that are different within a file, and has a unique marking for binary files, which we are using. The PR also made all scanner operations parallel, so they're performed faster

**Comment by premun** [comment]
@dkurepa it seems this approach is somewhat faulty.

For instance, these files are being flagged as binaries:
- https://github.com/microsoft/vstest/blob/main/test/TestAssets/RecursiveResourceLookupCrash/RecursiveResourceLookupCrash.csproj
- https://github.com/NuGet/NuGet.Client/blob/dev/test/EndToEnd/Packages/FileTransformWorksOnDependentFile/test.1.0.0.nuspec

**Comment by premun** [comment]
I think we can close this, the follow-ups have their own issues but the scans are in place already
