### ISSUE TITLE
DevWF data for product team M2s

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#11273]
- Percentage of merge-on-red PRs that don't have known issues for each failure, broken out by lead (or by github handle, if by lead is too much work)
- Dev percentage who looked at the Build Analysis page for a failed PR, by lead (or by github handle, if by lead is too much work). Also, the assumption is the page view of the Build Analysis is by the dev that created the PR, even if that might not be accurate.

**Comment by ulisesh** [comment]
We put the data together in a PowerBI report. @markwilkie is working with M2s 😄
