### ISSUE TITLE
Find home for Shared services. 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#11276]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We need to find a place to move all the shared services. 

Teams discussion -> https://teams.microsoft.com/l/message/19:83953de1ddd34bcaa9ebaba54cb8eba4@thread.skype/1665620287970?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1665620287970&teamName=.NET%20Eng%20Services&channelName=General&createdTime=1665620287970&allowXTenantAccess=false

**Comment by michellemcdaniel** [comment]
Is like sort of an epic in and of itself?

**Comment by ChadNedzlek** [comment]
@Chrisboh is there an existing epic for this work?  If not, should we turn this into it, or do we want to manage it more verbosely?

**Comment by Chrisboh** [comment]
Its been a part of the planning but I don't think we have created the Epic yet.  I am fine if we turn this into an epic or create a new one and put this in there.

**Comment by missymessa** [comment]
dnceng-shared is a thing now.
