### ISSUE TITLE
helix urls are broken

### ISSUE THREAD

**Issue by kasperk81** [dotnet/arcade#11296]
seeing broken urls in all runtime jobs sending to helix

```
  Sent Helix Job; see work items at [System.String]::Copy('').TrimEnd('/')/api/jobs/84d97cc3-49cc-4090-82ec-bd5ccc43d602/workitems?api-version=2019-06-17
```

**Comment by markwilkie** [comment]
@dotnet/dnceng  -  Making sure this has visibility.

**Comment by MattGal** [comment]
Yup I saw this, will address it via FR issue.

**Comment by MattGal** [comment]
@premun already addressed this via https://github.com/dotnet/arcade/pull/11093

**Comment by missymessa** [comment]
Ricardo recommended in subsequent issues regarding this error to update your Helix SDK to ensure you have the fix.
