### ISSUE TITLE
Link to Build IDs in MessageAbandoned Builds is incorrect

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#11306]
The Build links in MessageAbandoned Builds still points to the dnceng AzDO instance instead of the dnceng-public AzDO instance. 

Link: https://dotnet-eng-grafana-staging.westus2.cloudapp.azure.com/d/buildAnalysis/build-analysis?from=now-7d&to=now&viewPanel=40

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
- Fixed links to builds on Build Analaysis dashboard to facilitate investigation

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/27628

I also updated the query of abandoned message because it wasn't pointed to the correct buidls
