### ISSUE TITLE
Helix Work Items list said to be located at [System.String]::Copy('').TrimEnd('/')/api/jobs/...

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/arcade#11312]
Example run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=55488&view=logs&jobId=4f4b926f-8abe-5536-d4a9-2361289b3c74&j=4f4b926f-8abe-5536-d4a9-2361289b3c74&t=deaa050d-9b6a-5244-2786-43f5db38e264

The message shown is: `Sent Helix Job; see work items at [System.String]::Copy('').TrimEnd('/')/api/jobs/58d63621-9077-4af6-b6a1-006263bf09c2/workitems?api-version=2019-06-17`.

Perhaps something changed so that some template/interpolated string turned into a literal.

**Comment by MattGal** [comment]
This has already been fixed via https://github.com/dotnet/arcade/pull/11093.  If you need this fixed before natural dependency flow, you will need to trigger an arcade update in your repository.

**Comment by RikkiGibson** [comment]
Thanks!
