### ISSUE TITLE
Helix API's AzDevExtension "Download all files" link not working

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#11330]
See https://helix.dot.net/AzDevExtension/WorkItemResultData?jobName=8a5255fa-b150-4a65-9a91-767eb64909cc&workItemId=ComInterfaceGenerator.Unit.Tests# ,
https://helix.dot.net/AzDevExtension/WorkItemResultData?jobName=d8d0e61f-f588-4484-9004-6aa0f67cba95&workItemId=Microsoft.AspNetCore.Mvc.IntegrationTests--net7.0# ,
https://helix.dot.net/AzDevExtension/WorkItemResultData?jobName=88ca34df-c7d2-4d9c-a99a-484c94c62fc0&workItemId=JIT.Stress#
... etc; seems to be systemic. (I tried 5 random work items)

The most recent change I can find related to the AzDevExtension in the Helix API[ is this one](https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/commit/1dd49ca86dee736fb1a897a1df35b2c58568e651?refName=refs%2Fheads%2Fmain), which seems innocuous (@ChadNedzlek  any suggestions here?)

**Comment by AlitzelMendez** [comment]
The Dowland process of all the files is triggered as a pop-up, @MattGal do you have Blocked the pop-ups for helix.dot.net?

because in that case is not able to download all the files:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/6895254/197639472-c912c1aa-d59f-4759-aac1-70fc054b33f5.png">

**Comment by MattGal** [comment]
> The Dowland process of all the files is triggered as a pop-up, @MattGal do you have Blocked the pop-ups for helix.dot.net?
> 
> because in that case is not able to download all the files: <img alt="image" width="242" src="https://user-images.githubusercontent.com/6895254/197639472-c912c1aa-d59f-4759-aac1-70fc054b33f5.png">

ah, that may be it?  It downloaded 2/4 files when I enabled popups for helix.dot.net.  Feel free to resolve this then if you're seeing all the files download in that case, though I think it may be worth having a comment next to the button like ("Requires popups to be allowed for helix.dot.net") then

**Comment by missymessa** [comment]
>though I think it may be worth having a comment next to the button like ("Requires popups to be allowed for helix.dot.net") then

I agree with this.

**Comment by AlitzelMendez** [comment]
PR with comment: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/27032
