### ISSUE TITLE
Error in `eng/common/tools.ps1`: The variable '$vsMajorVersion' cannot be retrieved because it has not been set

### ISSUE THREAD

**Issue by davidwengier** [dotnet/arcade#11383]
A community member reported an error trying to build Razor in a docker container:

```
Using xcopy-msbuild version of 17.2.1 since VS version 16.3 provided in global.json is not compatible
The variable '$vsMajorVersion' cannot be retrieved because it has not been set.
```

More context in the issue: https://github.com/dotnet/razor-tooling/issues/7005

The issue seems to be in `eng/common/tools.ps1` where there is a code path that indeed doesn't set `$vsMajorVersion`:
https://github.com/dotnet/arcade/blob/main/eng/common/tools.ps1#L414-L415

Should that path throw? Or set the variable to something? Or is there something we can do on the Razor side to prevent this happening?

**Comment by michellemcdaniel** [comment]
@mmitche it's weird that this code path would suddenly be causing a failure when it's been there for, as far as I can tell, 2 years. Should we be setting vsMajorVersion and vsMinorVersion in that code path? Seems like we should?

**Comment by mmitche** [comment]
I think it should be setting the variable. I'm unsure why this is failing now though.

**Comment by mmitche** [comment]
Most repos appear to also have an xcopy-msbuild node? https://github.com/dotnet/aspnetcore/blob/main/global.json#L26

**Comment by michellemcdaniel** [comment]
Some just use the vs node, which is what razor is using. Looks like their global.json was updated 28 days ago from vs versions 16.3 (too low) to 17.2 (not too low). But it does look like the "too low" case is missing some code. It probably didn't get hit because most people upgrade their vs versions to "good enough" as we release, or they use the xcopy-msbuild node.

**Comment by davidwengier** [comment]
Should we be updating the global.json on some regular schedule?

**Comment by mmitche** [comment]
Usually it's only updated when VS requirements change. For instance, if you started targeting 7.0, it would make sense to require 17.4, since 7.0 cannot be targeted with 17.3 and earlier.

**Comment by michellemcdaniel** [comment]
We do also update the minimum version in arcade, which could cause this code to eventually pop up again, if you're not updating at least every so often. The minimum right now is 16.8, I believe

**Comment by davidwengier** [comment]
Thanks. I guess I read the "not too low" comment above to mean "not too low, but could be better" :)

**Comment by michellemcdaniel** [comment]
Checked in the fix for this. Closing.
