### ISSUE TITLE
Implement yaml templates 

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#114]
VSTS yaml templates are in mseng now for vsts.  https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-templates.md

Time to implement in Arcade...

**Comment by markwilkie** [comment]
Need to sort which instance of VSTS we're using, then start this work in there.  Given that .NET is open source, plus that fact we are probably in an earlier ring, it's likely that we'll be using a dotnet.visualstudio.com instance.  But, nothing's been set yet....

**Comment by JohnTortugo** [comment]
I think this is now implemented on Arcade. @chcosta  ?

**Comment by chcosta** [comment]
Yes, this is implemented for arcade
