### ISSUE TITLE
Update macOS 13 systems to Release build

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#11401]
With the release of macOS 13 (Ventura), we need to update OSOB to reflect this. 

For the macOS 13 queues (with non-tethered devices), we need to make sure our tooling reflects macOS 13 (release) and XCode 14(release) within the osx.13.amd64.open, osx.13.amd64, osx.13.arm64.open and osx.13.arm64 queues. 

For the macOS 13 queues with tethered devices, we also need to make sure that we reflect that the devices will be running iOS 16 (don't know if we track this in OSOB). 

### Release Note Description
Updating macOS13 queues

**Comment by AlitzelMendez** [comment]
Created a draf pr, could you please take a look @ilyas1974  and let me know if this is the expectation: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/27049

also I am working in upload the new version of Xcode into azure container

**Comment by AlitzelMendez** [comment]
Uploaded Xcode_14.1_Release_Candidate_2 as is the one supporting macOS 13 according to https://xcodereleases.com/

**Comment by AlitzelMendez** [comment]
waiting for DDFUN to test my changes: [IcM](https://portal.microsofticm.com/imp/v3/incidents/details/[344938682](https://portal.microsofticm.com/imp/v3/incidents/details/344938682/home)/home)

**Comment by AlitzelMendez** [comment]
I talked with @epananth about the progress of this issue and she is going to take over this one

**Comment by epananth** [comment]
@premun - @AlitzelMendez did a few things. ( will add link to what she ran when I get that info from her) 

Logged into dci-mac-build-293 and ran a bunch of commands 

![Image](https://user-images.githubusercontent.com/47157394/200464556-d1c16fe6-eabd-4160-8760-308698669f67.png)

Not really sure what to do next.

**Comment by premun** [comment]
This looks suspicious?

![image](https://user-images.githubusercontent.com/7013027/200516799-0c790701-b1c4-4a32-88c4-8d14cbdc49b9.png)

Based on https://xcodereleases.com/ you need Xcode 14.1 for macOS 13+

https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/870/Install-new-version-of-Xcode-on-Helix-machines

**Comment by epananth** [comment]
Cool thanks, I will update this :)

**Comment by epananth** [comment]
created an ICM to reimage these 2 systems https://portal.microsofticm.com/imp/v3/incidents/details/348183591/home

**Comment by epananth** [comment]
So after reimaging I got to rerun the PR https://dev.azure.com/dnceng/internal/_build/results?buildId=2043243&view=results and looks like it worked :) 

the machine is heart beating 


![Image](https://user-images.githubusercontent.com/47157394/201447346-22695ba0-df91-42ab-bc39-b9ffca1ad044.png)

**Comment by premun** [comment]
@epananth I am not sure I follow - how does the PR affect the on-prem machine? I thought there's no relation really?

**Comment by epananth** [comment]
@premun We were testing the PR on those machines. We updated some versions and wanted to test that on some on prem machines before we roll it out to production.
