### ISSUE TITLE
[darc/maestro++] GitHub mirroring should be a first class-citizen for Maestro

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1141]
For complex branch management, Maestro will need to manage the mirroring of code between branches.  Today this is done via old maestro, (launching build definitions that do mirroring), and the subscriptions.json file.  This has two drawbacks:
- Errors in mirroring are difficult to surface
- More difficult to automate addition/removal of mirrored branches. (i'm wary of parsing, altering the json without review).

In Maestro++ we should have mirroring as a first class citizen.  We could actually keep the infra (build defs), but we need to do the following:
- Surface errors easily
- Manage which branches are mirrored and how (merge vs. overwrite) 
- Disable/enable mirroring easily.

We probably should just have a table in the Maestro DB to control what/how mirroring is done, install webhooks in the source repos using the Maestro app, and then launch the builds defs.  The results would be surfaced in some history function.

**Comment by markwilkie** [comment]
Agreed - @mmitche, would you consider this a requirement for 12/14?

**Comment by mmitche** [comment]
> @mmitche, would you consider this a requirement for 12/14?
Nope

**Comment by mmitche** [comment]
After consideration, this should be a separate service to promote reuse outside .net core.

**Comment by mmitche** [comment]
Covered by #3650
