### ISSUE TITLE
Invalid architecture param is passed to install-scripts for Mac OS (M1) when sdk >= 6.0 is requested

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/arcade#11418]
Hi Team,

Recently, an issue landed in the install-scripts repo after fixing the issue for MAC OS (arm64).
[macOS ARM64 source-build of v6.0.1xx fails](https://github.com/dotnet/install-scripts/issues/318)
The customer uses dotnet-installer and it looks like you have a fallback mechanism that doesn't work as expected after applying a new rule:
When Mac OS runs on arm64:
- if a customer requests sdk < 6.0 , try to install the package for x64 (if Rosetta is detected);
- if a customer requests sdk >= 6.0 then the package for arm64 has to be installed.

In the customer's ticket, I can see that in "Successful logs" (before the rule implementation), the installer was applying some logic for changing the architecture:
`Unknown CPU arm64 detected, treating it as x64`.

I hope you can find all the required information in the linked ticket.
Thank you.

**Comment by marcpopMSFT** [comment]
The text listed above appears to come from /eng/common/dotnet-install.sh so moving to arcade.

**Comment by YuliiaKovalova** [comment]
@marcpopMSFT , thank you for transferring this issue to the right repository.

**Comment by michellemcdaniel** [comment]
It looks like the eng/common/dotnet-install.sh script in installer's v6.0.109 tag is horribly out of date. Compare [arcade main](https://github.com/dotnet/arcade/blob/main/eng/common/dotnet-install.sh#L55) to [v6.0.109](https://github.com/dotnet/installer/blob/v6.0.109/eng/common/dotnet-install.sh#L55).

**Comment by YuliiaKovalova** [comment]
Hi @michellemcdaniel,

Are any actions required from my side for resolving this issue?

**Comment by epananth** [comment]
@YuliiaKovalova this dotnet-install script needs an update. But again, the script you are referring is an old tag v6.0.109. You cannot actually update that. So, you should be able to update the install script for the next release.

**Comment by YuliiaKovalova** [comment]
@epananth ,
I am not s part of Arcade team and I can see that this file is completely different from what we have in the install-scripts repo.
Are you sure that install-scripts team is responsible for managing this thing?
@michellemcdaniel

**Comment by epananth** [comment]
created pr for this -> https://github.com/dotnet/arcade/pull/11552

**Comment by epananth** [comment]
@YuliiaKovalova , after the PR https://github.com/dotnet/arcade/pull/11570 gets merged into arcade, I will trigger the subscription for you to get these changes. Once you merge the arcade update, this error should go away.

Keeping this one open till we see a successful build

**Comment by epananth** [comment]
I see this change got promoted https://dev.azure.com/dnceng/internal/_build/results?buildId=2041120&view=results

**Comment by YuliiaKovalova** [comment]
@epananth ,
Thank you for the updates! I have asked the customer to check if the issue is resolved for him.

**Comment by epananth** [comment]
one thing is, does installer have updates from arcade turned on/ off for release6.0?

**Comment by epananth** [comment]
this is the update https://github.com/dotnet/installer/pull/14972 that has to be merged. Again, this file has to be updated in installer ( it will be after merging this PR). But it's not going to affect the tag your customer is using. You will need to send a latest tag for them to test this.

**Comment by YuliiaKovalova** [comment]
> this is the update [dotnet/installer#14972](https://github.com/dotnet/installer/pull/14972) that has to be merged. Again, this file has to be updated in installer ( it will be after merging this PR). But it's not going to affect the tag your customer is using. You will need to send a latest tag for them to test this.

Thank you for working on it!
could you clarify what "the latest tag" is?

**Comment by michellemcdaniel** [comment]
So the customer who reported the issue was cloning the repo at a specific release tag, aka one of these: https://github.com/dotnet/installer/tags. We can't actually update the code associated with a given tag because they are tied to specific commit shas. The fix Epsi made will inly apply to the repo going forward, so the customer will be unable to source build at the 6.0.109 tag that they were using. They will have to either build from the tip of a different release branch once it gets these changes, or intentionally replace the dotnet-install.sh script provided by arcade in their local clone.
