### ISSUE TITLE
Image generation problems on latest 2022-Datacenter images

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#11421]
We've hit several image generation issues with the new 20348.1131.221014 Server datacenter image.    This issue tracks unblocking that, namely first by seeing if `20348.1129.221007` works, then trying newer images (i.e. reverting to "latest" next month when a new one comes out.

### Release Note Description
Switch back to 'latest' version for base Server 2022 images

**Comment by garath** [comment]
In other words let us revisit this one week from now (around November 2) when a version _after_ 20348.1131.221014 is released and see if it builds. The assumption is that this "latest" is bad in some way and will be corrected.

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/27511

**Comment by MattGal** [comment]
I think we're good, moving to waiting for rollout.

**Comment by MattGal** [comment]
This has been good for some time using latest images, closing.
