### ISSUE TITLE
Move Windows.10.Amd64.*.Rt queues to D_v4 SKU vms

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#11420]
Currently these are Da_v4 (AMD EPYC) which doesn't yet support AVX512 instructions.  Moving these to D_v4 will allow the runtime team to have a test queue for this instruction set.

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/27068

**Comment by MattGal** [comment]
@BruceForstall this has been rolled out and I personally verified all the Windows.10.Amd64.*.Rt queues now have Standard_D4_v4 size VMs.  Ping me on Teams for any concerns.

**Comment by BruceForstall** [comment]
Thank you!
