### ISSUE TITLE
Add linked issue check to dotnet-helix-service and arcade-services and update the one in helix-machines

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#11433]
Additionally, we should update helix-machines to check for release notes in the issue after https://github.com/dotnet/arcade/issues/11432 is complete.

### Release Note Description
Do not include in release notes.

**Comment by ChadNedzlek** [comment]
I don't think I'm a fan of this... it's a process that costs a non-trivial amount of time... and I'm not sure what it's really adding?  Like we don't need release notes/an issue for https://github.com/dotnet/arcade-services/pull/2088, that would just be a waste of everyone's time.
