### ISSUE TITLE
Data already exists failure

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/arcade#11447]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=65930

The data already exists, but there was a failure. I believe the tests have all passed but the infrastructure has failed for some readon.

### Build leg reported

Build / SuperPMI replay windows x64 checked / Publish SuperPMI logs

### Pull Request

https://github.com/dotnet/runtime/pull/77556

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false
 }
 ```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by oleksandr-didyk** [comment]
From what I can tell you have re-ran the build due to failure to send the work item to Helix, which might have caused the duplicate log artifact error. 

I triggered the affected pipeline again, hopefully it will fix the issue

**Comment by oleksandr-didyk** [comment]
After the pipeline was triggered again, it finished with no issues.

Please feel free to re-open the issue if you run into something similar or need further help

**Comment by riarenas** [comment]
@AaronRobinsonMSFT Given how this is a side effect of rerunning failed jobs, you could consider changing the log upload job to either:

1. Not cause the build to fail if it fails
2. Append the attempt number to the log artifact you are attempting to upload.

**Comment by michellemcdaniel** [comment]
For Ricardo's first suggestion,

```
continueOnError: true
```

should be added to the Publish Artifacts tasks [here](https://github.com/dotnet/runtime/blob/30d85939446fba71112967b2a217827e6304fe43/eng/pipelines/coreclr/templates/run-superpmi-replay-job.yml#L102-L114).

For the second, the artifactName in those two steps is what would need the attempt number (which is `System.JobAttempt`).
