### ISSUE TITLE
Maestro is generating invalid commit links

### ISSUE THREAD

**Issue by Scottj1s** [dotnet/arcade#11499]
### Build

Displaying results for a [given build](https://reunion-maestro-prod.westus2.cloudapp.azure.com/54/https:%2F%2Fgithub.com%2Fmicrosoft%2FWindowsAppSDK/latest/graph), clicking the commit links from each node details page presents a 404.  The issue appears to be an incorrectly generated link, containing “\commits\” instead of “\commit\”.

Manually editing any of the links to remove the trailing 's' from 'commits' results in a valid page which loads:
https://dev.azure.com/microsoft/DWriteCore/_git/DWriteCore/commits/ac9a64e79f584a1692512d83b2caf2bddcdec67c
https://dev.azure.com/microsoft/LiftedIXP/_git/DCPP/commits/cd0911a72c1c9981849737cadbb30f0027a2dd7e
https://dev.azure.com/microsoft/ProjectReunion/_git/ProjectReunionClosed/commits/f01ee1d0765a007e8a858c3608261d795cdd1d87
https://dev.azure.com/microsoft/WinUI/_git/microsoft-ui-xaml-lift/commits/52be26989f4fc323ac95318cab3319c77b145db3
https://github.com/microsoft/WindowsAppSDK/commits/b6875ceccc2fc9ff273b20a782833b02d204bcc0

/cc: @MattGal 

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false
 }
 ```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by MattGal** [comment]
Updated labels so we'll discuss in triage today.

**Comment by riarenas** [comment]
Keep in mind this is happening in the project reunion maestro instance. This is highly unlikely to be something that our team can help with

**Comment by kythant** [comment]
I assume if it's happening in the reunion's instance, it would also be happening in dotnet's instance?
