### ISSUE TITLE
Async Triage tool should ignore FROps label

### ISSUE THREAD

**Issue by michellemcdaniel** [dotnet/arcade#11498]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Since we added the FROps label, we need to ignore it in the async triage tool, since that label means the issue has been triaged to FROps.

/cc @MattGal @garath 

### Release Note Description
Release notes not needed ; async triage is an internal-only tool

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/27227

Also added the "TechnicalDebt" label as we will be looking to deal with that in the near future and it represents similarly already-triaged stuff.

**Comment by michellemcdaniel** [comment]
Thanks Matt!

**Comment by MattGal** [comment]
Change is finally merged (hit some weird issues), should roll out next week

**Comment by MattGal** [comment]
rolled out, closing.
