### ISSUE TITLE
Migrate ARM Dev Systems to new hardware

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#11492]
We need to migrate our customers from the EOL Centriq (Qualcomm) hardware to the VMs on the Mt Jade hardware. 

Dev Systems are tracked in https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/881/Tracking-of-Hardware-not-in-Helix?anchor=distributed-resources

**Comment by ilyas1974** [comment]
I have already talked with the runtime team and gotten contact information on who to work with to get their workloads migrated. I have also gotten 6 Ubuntu 22.04 VMs and 6 Windows 11 VMs for that purpose.

**Comment by Chrisboh** [comment]
@ilyas1974 What is the latest status on this?

**Comment by ilyas1974** [comment]
Cores have been added to this DTL for us to use. Closing this issue
