### ISSUE TITLE
Private github onboarding gotchas

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/arcade#1150]
Hello,

So I ran into a few gotchas with our private github repo that I thought I’d share so you’re aware in case other teams run into the same issues:

1. The VSTS CI build (for the github source) is meant to be public eventually, but it’s internal right now. This causes some issues:
a.     All the steps that are intended to be run on internal projects will incorrectly be running (since the yaml expressions only check if the project is public)
b.	BUT the build still needs to run on the internal pool (since external pool is not accessible from dnceng/internal projects)
c.	See the following commits for what I did to temporarily fix this while the github repo was private and the pipeline was internal:
i.	https://github.com/dotnet/winforms/commit/4f5d958468471c142a9833a6763fbfc2deea0599
ii.	https://github.com/dotnet/winforms/commit/501caa9ca22934e7e8f29f67e99958bba62d1cb1  
iii.     https://github.com/dotnet/winforms/commit/82613a5099e23d969f11534ea04f5fde0f7ca94d 
d.	Basically you don’t want to publish anything to the dotnet feed, you don’t want to ‘real’ sign, and you don’t want to publish build assets. Those should all only be done from your official internal build. **You should revert these changes once you go public and your vsts project moves from dnceng/internal to dnceng/public**

2.	When setting up maestro to do the github -> dnceng mirroring, the maestro bot can’t see your github repo if it’s private.
a.	Add dotnet-maestro-bot as a collaborator (Read) to your repo

**Comment by AdamYoblick** [comment]
As mentioned in the e-mail, these fixes are hacky and depend on the build definition name. A better permanent fix is probably to check where the repo lives and don't do "internal" things (except the agent pool) if it's github. 

There is a variable called Build.Repository.Provider that you can use to check if the repo lives in github. It will equal 'GitHub' if that's the case.

**Comment by AdamYoblick** [comment]
Reopening this issue because this fix is needed in arcade and the Build.Repository.Provider variable is not available when the yaml is parsed.

**Comment by markwilkie** [comment]
@chcosta - Does guidance exist here?

**Comment by chcosta** [comment]
We don't have specific guidance for this scenario, but I'll file an issue.  I think we want both guidance, and to make sure there's a supported path so that teams don't have to fork code or do other craziness to make this work.  There will certainly be some effort on the part of repo owners going down this path but it shouldn't put them in a position where they can't get support (new changes).

**Comment by AdamYoblick** [comment]
@markwilkie The arcade team added a parameter to all the arcade templates called RunAsPublic which allows you to force this behavior, which eliminates the need for the Build.Repository.Provider check.

Although is the user doesn't know to pass this in, they will still get steps running that shouldn't be when using a private github repo. Unfortunately, there's no good way to enforce this without some sort of hacky solution in the yaml. Maybe a comment in the arcade yaml explaining that you HAVE to set this to true when using a private github repo or something along those lines would be helpful :)

It's an edge case for sure, but WPF is onboarding from scratch and are going to run into the exact same issue. I pointed them to the doc I wrote with gotchas so they should have minimal surprises.

**Comment by markwilkie** [comment]
We've linked Adam's document, so I'm considering this issue closed.
