### ISSUE TITLE
Clashing test properties

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#1151]
Today corefx uses its own set of testing targets but there isn't any way to opt-out of the Tests.props that comes in with the sdk by default. For the most part it hasn't caused a lot of pain but we have had to work around some things because we also have an IsTestProject property which is defined differently then what https://github.com/dotnet/arcade/blob/518da700456e1766c69bbfeb24ae104b8fe2cd62/src/Microsoft.DotNet.Arcade.Sdk/tools/Tests.props#L25 defines it to be. We define it as https://github.com/dotnet/buildtools/blob/0fa455c550abb4f49f4830a7f2fa78609f373fd0/src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props#L60.

For now in my PR https://github.com/dotnet/corefx/pull/32921 I'm working around this by resetting IsTestProject around the import of the sdk but we should have some opt-out for the testing setup in the arcade sdk. We might even want to remove it from the sdk and make it an optional package for a repo.

@ViktorHofer is working on the corefx testing package factoring and will dig in deeper here.

**Comment by tmat** [comment]
I disagree. Why not rename the test projects in CoreFX repo to comply with the Arcade [project naming conventions](https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#project-name-conventions)?

**Comment by ViktorHofer** [comment]
> I disagree. Why not rename the test projects in CoreFX repo to comply with the Arcade project naming conventions?

Right, we could do that as most of the stuff defined in the Tests.props does work for corefx. The fact that we don't resolve our packages in corefx per project but during the bootstrapping of the repository, things like `PackageReference` won't work for us, i.e. https://github.com/dotnet/arcade/blob/518da700456e1766c69bbfeb24ae104b8fe2cd62/src/Microsoft.DotNet.Arcade.Sdk/tools/Tests.props#L36.

Also the current architecture of your Tests.targets and XUnit.targets isn't as scaleable as we need it to be for corefx to also run on tfms like uap, uapaot and netcoreappaot. We should definitely try to use as many of the features that arcade offers as possible but at this point we need to use our own testing infrastructure in corefx. We should then slowly bring our additions over to the common arcade testing framework.

**Comment by weshaggard** [comment]
>I disagree. Why not rename the test projects in CoreFX repo to comply with the Arcade project naming conventions?

As for naming convention we will try and align with the conventions defined here but for the actual infrastructure we currently cannot align because we have a lot more requirements that what is supported in arcade today.

**Comment by tmat** [comment]
> things like PackageReference won't work for us

Do you mean it breaks something or it just doesn't do anything useful?
Is it possible to run CoreFX tests from VS Test Explorer?

> we can't use the testing framework in arcade and should have an option to disable it

The test runner framework is not forced upon you. It's already optional. Just don't use `Test` target. 
Roslyn also has a custom test runner for perf reasons. The developer still have the option to run `msbuild /t:Test foo.csproj` on individual projects if they want to, but it's not something that has to be used.
