### ISSUE TITLE
Make sure edge cases are covered when doing `darc add`

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#1154]
One user reported the following scenarios did not work as expected when running `darc add`:

*  Not specifying correct arguments
*  Had `global.json` with msbuild-sdk, but didn’t have a `Version.Details.xml`
*  `Version.Details.xml` didn’t have the right sections in it (`ProductDependencies` and/or `ToolDependencies`)
*  `global.json` already had Arcade SDK in the `msbuild-sdks` section

We should make sure that these work as expected or at least fail gracefully with a descriptive error log

**Comment by mmitche** [comment]
My recent change to introduce testing here fixed:
- Version.Details.xml didn’t have the right sections in it (ProductDependencies and/or ToolDependencies)

It don't think I fixed:
- Had global.json with msbuild-sdk, but didn’t have a Version.Details.xml and
- global.json already had Arcade SDK in the msbuild-sdks section

This may be one of the skipped tests right now.  The way this was going to have to be implemented was kinda hacky and I kind of wanted to fix it in an overall refactor.  But, it could be fixed now is some hacky way and be fine.

**Comment by jcagme** [comment]
> Had `global.json` with msbuild-sdk, but didn’t have a `Version.Details.xml`

So if `Version.Details.xml` is not there should we add it for the user or gracefully fail pointing to an example? We are currently throwing a `FileNoteFound` exception. @mmitche thoughts? 

> `global.json` already had Arcade SDK in the `msbuild-sdks` section`

We already throw `Failed to add dependency 'Microsoft.DotNet.Arcade.Sdk' to repository.
Microsoft.DotNet.DarcLib.DependencyException: Dependency Microsoft.DotNet.Arcade.Sdk already exists in this repository`

**Comment by mmitche** [comment]
@jcagme I think we should fail gracefully and point to the arcade onboarding docs
