### ISSUE TITLE
Component Governance Detection showing some warning 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#11541]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Arcade-services: https://dev.azure.com/dnceng/internal/_build/results?buildId=2038875&view=results

Need to check if packages are out of date and need to updated it

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by MattGal** [comment]
Oops I may have just done this work.
