### ISSUE TITLE
Perftiger163 offline for a customer

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade#11566]
disconnected perftiger163 machine for a customer to do testing 

FR conversation:
https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1667968304764?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1667968304764&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1667968304764&allowXTenantAccess=false

**Comment by ilyas1974** [comment]
Per IM from customer, they have completed work on this system. I have put it back online.
