### ISSUE TITLE
Race condition between publishing of darc and deployment of maestro service

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#11575]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

The arcade-services build is structured such that we deploy a new version of the darc tooling before we deploy the maestro application to the service fabric cluster. However, there's no direct dependency between these two jobs, so we run the risk of the maestro deployment finishes, signaling repos that a new version of darc is available, however the publishing pipeline may have not finished publishing the tool to the feed yet.

This exact situation happened on this rollout build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2041249&view=results

We should change the pipeline so that we only deploy the service once the publishing stage has completed.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [X] Internal Infrastructure Improvements
### Release Note Description
Removed race condition between the publishing of darc and the deployment of Maestro.

**Comment by michellemcdaniel** [comment]
Put in FR, but might actually be FROps @ilyas1974

**Comment by premun** [comment]
Is this only about adding the "darc publish" stage to the `dependOn` of Pre-Deployment?

![Image](https://user-images.githubusercontent.com/7013027/201627787-433fba4b-8907-4b7a-8f71-76e7fa9280e1.png)


I am also curious - how did this manifest exactly? What failed?

**Comment by michellemcdaniel** [comment]
Correct, that is the change we are proposing. Ricardo summarized the impact of the current pipeline structure:

> we run the risk of the maestro deployment finishes, signaling repos that a new version of darc is available, however the publishing pipeline may have not finished publishing the tool to the feed yet.

What happened is the publish to darc step hadn't finished publishing the new version of darc itself, but the rest of maestro deploy had finished, which signaled to the publishing pipeline for the rest of the product that there was a new version of darc available and to start using it. But that new version hadn't finished publishing yet, so the publishing pipeline would fail because it couldn't get that version of darc. Hence race condition.

**Comment by premun** [comment]
> signaled to the publishing pipeline for the rest of the product that there was a new version of darc available and to start using it

Can you elaborate a bit please on how this happens? We put the actual version somewhere?

**Comment by riarenas** [comment]
>Can you elaborate a bit please on how this happens? We put the actual version somewhere?

https://github.com/dotnet/arcade-services/blob/3a8b32b60e6030e921756dd7ae8865d72fbc8898/src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/AssetsController.cs#L89

and then https://github.com/dotnet/arcade/blob/5b786331c7b5f8d389e55d504bf00f4464758e46/eng/common/darc-init.ps1#L24 queries that endpoint for the version to install.

**Comment by michellemcdaniel** [comment]
This has rolled out
