### ISSUE TITLE
Several linux images need update UpdateRequiredDate (12/01/2022)

### ISSUE THREAD

**Issue by v-yuyangshi** [dotnet/arcade#11582]
Several linux images reaching UpdateRequiredDate on 12/01/2022 and we will update them from the Helix test matrix. This needs to be included in messages about rollouts.

Affected queues:
ubuntu.1604.amd64
sles.15.amd64
sles.12.amd64

### Release Note Description
Update linux base images

**Comment by MattGal** [comment]
Updated via https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/27384?_a=files
