### ISSUE TITLE
Investigate / improve / fix Dead Service restarter Service in dotnet-helix-service

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#11586]
As seen in [the regular Grafana alerts,](https://github.com/dotnet/arcade/issues/11521) the dead service restarter doesn't seem to work with the AutoscaleActorService, which has taken three naps this week after many weeks of reliable operation.

It would be nice to know why the service gets into this state, but given we HAVE a dead service restarter it'd also be great for this to self-recover since it can be down for hours before a human is online to notice.

### Release Note Description
Improve logging of internal DncEng services for investigations

**Comment by MattGal** [comment]
@alexperovich is on FR this week and has some cycles, so has volunteered to check this out.

**Comment by Chrisboh** [comment]
@alexperovich what is the latest status on this?

**Comment by alexperovich** [comment]
I have merged changes into arcade-services that give us more logging when this happens. I need to update helix-service with the new packages from arcade-services.

**Comment by Chrisboh** [comment]
When do you think this will be done?

**Comment by alexperovich** [comment]
The version update is here https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/29032. Once that is in this is finished.

**Comment by MattGal** [comment]
@alexperovich that PR is merged and rolled out, should this be closed?

**Comment by alexperovich** [comment]
Yea, we can close this out. I haven't seen any issues with the service in quite a while.
