### ISSUE TITLE
Please consider using `ExitWithExitCode 0` for failed builds only on Azure Pipelines

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/arcade#11589]
As part of the https://github.com/dotnet/arcade/pull/6635 PR, the build scripts used by Arcade were updated to return a `0` exit code for build errors when the `-ci` flag is specified. While the remark was made that it could break certain scenarios like CI builds made on GitHub Actions, it was assumed that `-ci` meant `Azure Pipelines` and no check was added to avoid using `ExitWithExitCode 0` without considering the actual CI environment.

In the aspnet-contrib and OpenIddict projects, we use Arcade on GitHub Actions for our CI builds, and this change sadly broke us: https://github.com/openiddict/openiddict-core/issues/1546 (no need to say it wasn't trivial to find why failed builds were reported as successful... 😄).

Is there a chance the suggested check could be added, so that the `ExitWithExitCode 0` trick is only used on Azure Pipelines?

/cc @alexperovich @ChadNedzlek

**Comment by markwilkie** [comment]
Hi @kevinchalet !  - thanks for the issue.  Unfortunately, we aren't yet ready to support GH actions with Arcade.  Further, the ramifications of a change like this would likely be very destabilizing - as our CI/CD has many dependencies on things like this. (and this particular change has been around for a couple of years it looks like)

However....curious how you ended up using Arcade?   Your perspective would be super interesting to us as we don't hear from folks outside of the immediate team that much.

Cheers

**Comment by kevinchalet** [comment]
Hey @markwilkie,

Thanks for your reply! 😄

> However....curious how you ended up using Arcade? Your perspective would be super interesting to us as we don't hear from folks outside of the immediate team that much.

We adopted Arcade in August 2019 as a replacement for KoreBuild (that was deprecated in June 2019). Since it's super opinionated/Microsoft-oriented (to say the least 😄), [I'd be lying if I told you it was easy to set up](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/321) but it really met all the complex requirements I had for the OpenIddict project. For instance:
  - It takes care of the bootstrapping process by downloading the .NET SDK for you, independently of what's installed on the dev machine/CI server.
  - It's perfect for projects that use multi-targeting as you just have to list the runtimes you need in `global.json` and Arcade takes care of downloading them transparently.
  - Arcade figures out itself what TFMs unit test projects should run on based on the OS, which is great when you have test projects that target .NET Framework.

So, Arcade was really the obvious choice at the time, and it's been working flawlessly until now 😄

> Unfortunately, we aren't yet ready to support GH actions with Arcade.

We [moved to GitHub Actions in July 2020](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/423) and  Arcade has been working just fine on GA. While a closer integration would be welcome (e.g to have nicer warnings/errors in the log output), there's really no reason not to use Arcade with GitHub Actions when it works as intended 😄

> Further, the ramifications of a change like this would likely be very destabilizing - as our CI/CD has many dependencies on things like this. (and this particular change has been around for a couple of years it looks like)

To be clear, I'm by no means suggesting you should remove the `ExitWithExitCode 0` logic, but a simple "is it running on Azure Pipelines ?" check could be easily implemented. Alternatively, a command line argument like the ones already present in `Tools.ps1/sh` could be used to opt out this logic.

In any case, https://github.com/dotnet/arcade/pull/6635 reveals that this change was made in 2020 simply to avoid double-logging on build failures, so the risk of regressing things is inexistent.

**Comment by markwilkie** [comment]
Love it!  Yea, the reasons you're using arcade are indeed some of the reasons we created it.  :)

Yea, if you want to add a PR to check if it's running in Azure Pipelines, that might be fine - especially if it's outside of the existing paths and something you use in the action.

**Comment by kevinchalet** [comment]
> Yea, if you want to add a PR to check if it's running in Azure Pipelines, that might be fine - especially if it's outside of the existing paths and something you use in the action.

Awesome, thanks!

Do you have a preferred way of detecting whether it's running in Azure Pipelines?

`AzureDevOpsTask` uses the `BUILD_BUILDNUMBER` environment variable, but maybe you'd prefer something less generic/more specific like `TF_BUILD` (https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)?

https://github.com/dotnet/arcade/blob/974dccd7055b08deb3b9650b8235323b66f04976/src/Microsoft.DotNet.Helix/Sdk/AzureDevOpsTask.cs#L20

**Comment by kevinchalet** [comment]
I went ahead and created a PR in the OpenIddict samples repository with the necessary changes: https://github.com/openiddict/openiddict-samples/pull/216/files

If you think it's fine, I'll open a PR here 😃

**Comment by markwilkie** [comment]
thoughts @ChadNedzlek ?

**Comment by kevinchalet** [comment]
I opened https://github.com/dotnet/arcade/pull/11869, which includes the same changes as in https://github.com/openiddict/openiddict-samples/pull/216.

**Comment by kevinchalet** [comment]
Can someone from the Arcade team PTAL? This is really degrading the UX of our contributors. See https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/739#issuecomment-1353099136 for another very recent case.
