### ISSUE TITLE
Response status code does not indicate success: 503 (Service Unavailable)

### ISSUE THREAD

**Issue by jkotas** [dotnet/arcade#11597]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=80098

### Build leg reported

Build / Installer Build and Test coreclr  windows_x86 Debug / Build

### Pull Request

https://github.com/dotnet/runtime/pull/78208

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "error NU1301: Response status code does not indicate success: 503 (Service Unavailable)",
    "BuildRetry": true
 }
 ```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Additional information about the issue reported

Why is this not getting linked to a known infrastructure issue?

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[80282](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80282)|dotnet/sdk|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/80282/logs/85)|dotnet/sdk#29022|
|[80098](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80098)|dotnet/runtime|Copy native test components to test output folder|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/80098/logs/1143)|dotnet/runtime#78208|
|[80074](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80074)|dotnet/runtime|Libraries Test Run checked coreclr windows arm64 Release|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/80074/logs/327)||
|[80064](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80064)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/80064/logs/1056)|dotnet/runtime#77884|
|[80052](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80052)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/80052/logs/1547)|dotnet/runtime#77874|
|[80019](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80019)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/80019/logs/9)|dotnet/roslyn#64160|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[80108](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80108)|dotnet/sdk|[dotnet.Tests.dll.8.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80108&view=ms.vss-test-web.build-test-results-tab&runId=1673872&resultId=102980)|dotnet/sdk#29018|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|7|

**Comment by oleksandr-didyk** [comment]
Hey, taking a look at this, will let you know once we have any updates

**Comment by jkotas** [comment]
This is not a one-off issue. I have seen number of jobs failing in last few days with the nuget service unavailable errors. Here is a random example from a different job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=79388&view=logs&j=af986455-df3a-5ed6-b067-9144b6c8d0c6&t=2f3069f0-e001-503f-08a5-20cd64bd1e2e&l=165

Do you have a telemetry for how many CI jobs are failing with these 50* errors?

**Comment by oleksandr-didyk** [comment]
Sure thing, will take a look

**Comment by MilenaHristova** [comment]
We've had this problem with the Nuget feeds because of volume, we're working with the Nuget team to resolve it. You can see more in this issue: https://github.com/dotnet/arcade/issues/10885
