### ISSUE TITLE
[BYOC] Automated rollout for pool provider

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1162]
Create int and prod automated rollout for the BYOC pool provider service and ensure it conforms to dnceng's service policies.

**Comment by chcosta** [comment]
@mmitche , what's the state / status of this?  Is this in the right epic?  Is this a blocker for P2?  This seems important to me but I don't have any visibility via this issue.

**Comment by mmitche** [comment]
Not a blocker for p2. There has been no work on automating the rollout.  The PP should also move to its own repo or into arcade-services.

**Comment by jcagme** [comment]
I think this is done? Can you please confirm @mmitche

**Comment by mmitche** [comment]
It's not.

**Comment by mmitche** [comment]
Automated for int/prod is in place, with automatic triggers on prod
