### ISSUE TITLE
Fix issues seen with Helix Secondary Queue feature

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#11636]
Helix "secondary" queueing has been around for some time but was presumed to be no longer in use.  .NET Native team still seems to need this for their testing purposes (despite it being broken on their end for some time now).

This issue tracks investigating why the feature is not working (currently hitting 401s using the SAS token provided, but will take lots of doing to repro) and attempting to fix it if feasible. 

### Release Note Description
Fix problem with URI generation in SAS token for Helix Secondary queues

**Comment by MattGal** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/27490?_a=files

**Comment by MattGal** [comment]
I believe I've found the issue, specifically we're generating the SAS tokens with the wrong URL leading to an HTTP 401.  I've prepped a PR and can validate E2E with Vitek against the staging environment once it merges.

**Comment by MattGal** [comment]
The PR I merged above unblocks the re-queuing scenario as expected, but there's a bigger problem.

Namely, Helix's service bus REST client needs to plumb through the modified Friendly name of the new work item and a new GUID to make it "unique", otherwise you get Null Ref exceptions as seen https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fcab65fc3-d077-467d-931f-3932eabf36d3%2FresourceGroups%2Fdotnet-eng-int-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng-int/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAw3LwQmAMAwAwL9TBCdQitU8OoBTSJpE9FFb0oIIDq%252F3v2bEWrsX7kNNIRc1ame%252BtlUgBOg5Mk7jrLioZ9kjOu8XNw4iMyIN0v81m6hBfKCdSWujVIAqf4yG9HlaAAAA/timespan/P1D.


@vitek-karas is investigating if he can do all this work on a single ARM64 machine (now that Windows 11 supports AMD64 binaries).    I am kicking this out of FROps for now to discuss in triage this thursday (11/17).

**Comment by michellemcdaniel** [comment]
Closing as not planned
