### ISSUE TITLE
GenFacades doesn't work when running on desktop msbuild

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#1167]
```
"D:\git\corefx\src\System.Runtime.InteropServices\src\System.Runtime.InteropServices.csproj" (rebuild target) (1) ->
"D:\git\corefx\src\System.Runtime.Extensions\src\System.Runtime.Extensions.csproj" (default target) (2:3) ->
"D:\git\corefx\src\System.Runtime\src\System.Runtime.csproj" (default target) (7:3) ->
  C:\Users\wesh\.nuget\packages\microsoft.dotnet.genfacades\1.0.0-beta.18522.6\build\Microsoft.DotNet.GenFacades.target
s(98,5): error : Unable to load DLL 'Microsoft.DiaSymReader.Native.x86.dll': The specified module could not be found. (
Exception from HRESULT: 0x8007007E) [D:\git\corefx\src\System.Runtime\src\System.Runtime.csproj]
```

@wtgodbe looks like we are missing some dependencies with the desktop output in our package.

**Comment by wtgodbe** [comment]
The `ResolvePackageAssets` task is placing the `Microsoft.DiasymReader.Native` .dll's in the `ResolvedRuntimeTargets` ItemGroup, while the others seem to be placed in `RuntimeCopyLocalItems` and `ResourceCopyLocalItems`. Still looking

**Comment by weshaggard** [comment]
@ericstj do we need to explicitly flatten the runtime assets when publishing for .NET Framework?

**Comment by ericstj** [comment]
I think @tmat owns that package.  I believe the way its supposed to work when restored for desktop is that it copies the DLLs and renames them :
```
  <ItemGroup Condition="Exists('packages.config') OR Exists('$(MSBuildProjectName).packages.config') OR Exists('packages.$(MSBuildProjectName).config')">
    <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win\native\Microsoft.DiaSymReader.Native.x86.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
      <Link>Microsoft.DiaSymReader.Native.x86.dll</Link>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)\..\runtimes\win\native\Microsoft.DiaSymReader.Native.amd64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
      <Link>Microsoft.DiaSymReader.Native.amd64.dll</Link>
    </Content>
  </ItemGroup>
```

I bet that the package never was designed to work for an AnyCpu desktop project using packagereference.

That's a bug in `microsoft.diasymreader.native`.  We can workaround it by doing what its targets would have done for packages.config.

**Comment by tmat** [comment]
We consume the package like so:

https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj#L26-L35

I have not added this to the DSRN package targets since we don't know what architectures the AnyCPU app wants to actually use.

**Comment by ericstj** [comment]
I see, I found it odd the package does this for packages.config without any conditions for architecture but doesn't do it for package-reference-based desktop.  That means folks will see a break when moving from pc to PR.

**Comment by tmat** [comment]
@ericstj Yes, that was just for backwards compat, since it was initially done that way. 

> That means folks will see a break when moving from pc to PR.

That's ok, the fix is easy and there is not many people who will care about this anyways.
