### ISSUE TITLE
Mark the whole run as failing if a component job fails

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/arcade#11681]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

When some components are warning and some are failure, the whole run is marked as Warning. It is misleading and hides failures.
Please change it to mark the whole run as failing.

Example: [Test Run](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D2044300%26view%3Dresults&data=05%7C01%7CJulie.Lee%40microsoft.com%7C6ea2e7eea3d24b6ec67f08dac9b85831%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638044090875981189%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WzMDCZdddsmVWphuNBLQvX7g%2Bu6DozANJCzBD89hvZ4%3D&reserved=0)

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by markwilkie** [comment]
cc/ @ulisesh, @AlitzelMendez , and @missymessa so this issue can be updated based on the meeting last week.

**Comment by AlitzelMendez** [comment]
Hi @JulieLeeMSFT,

I took a quick look to this and seems to be related on how these steps are define on the yaml so this needs to be changed on the yaml of the repo, in this case I think is coming from [this line](https://dev.azure.com/dnceng/internal/_git/dotnet-runtime?path=/eng/pipelines/coreclr/templates/run-superpmi-collect-job.yml&version=GBmain&line=148&lineEnd=149&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)

**Comment by missymessa** [comment]
Following up on this issue, @JulieLeeMSFT, was Ali's suggestion able to solve your problem?

**Comment by missymessa** [comment]
@dotnet/jit-contrib hi folks, looks like this change is within your purview. Thanks!
