### ISSUE TITLE
[darc/maestro++] Add "what's old and why" command

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1168]
One of the most common tasks done with dependency flow is the "what's out of date here and why" task.  Typically this goes as follows:
1. I can't remember seeing a PR for an update of X recently.
2. Go check and see whether there is a PR.
3. If there is a PR, then why wasn't it merged
4. If there isn't, should there be an update? (was there a new build of X recently)
5. Go find out what happened with build X.
6. If it exists, why didn't I get a PR?
7. ....

It would be good to have a command that does this flow.  In a basic frameework, it would do the following:

- Given current repo state or remote repo info, determine how far out of date you are on each dependency vs. the latest builds of those given subscription channels.
- Walk back through the chain of steps (PR, etc.) to determine what is going on.

You should also also be able to ask this question another way, which is "where is change X"

/cc @weshaggard @natemcmaster @livarcocc

**Comment by jcagme** [comment]
@mmitche  related to you current/latest work?

**Comment by mmitche** [comment]
This is pretty far out of scope overall
