### ISSUE TITLE
Darc publishing is often timing out

### ISSUE THREAD

**Issue by agocke** [dotnet/arcade#11694]
### Build

https://dev.azure.com/dnceng/internal/_build/results?buildId=2050151&view=results

### Build leg reported

publish

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by michellemcdaniel** [comment]
@agocke can you provide a link to a build, rather than a definition. I wouldn't expect darc publishing to be happening on a dotnet-public pipeline.

**Comment by michellemcdaniel** [comment]
Found a build where this happens: https://dev.azure.com/dnceng/internal/_build/results?buildId=2050151&view=results. Interestingly, the publish with darc job has a timeout of 1hr, where the actual publish job has a timeout of 2. IMO, the job waiting should have a longer timeout than the job doing the publish. Additionally, the publishing build itself (https://dev.azure.com/dnceng/internal/_build/results?buildId=2050294&view=results) also timed out, just an hour later. Normally, the publishing job for runtime takes around 30-40 minutes. For some reason, this publish job took over 2. It was definitely doing something, but I suspect some sort of rate limiting happening perhaps? @alexperovich this job is publishing to azdo feeds and to azure storage accounts. Is there any known rate limiting happening in those? I'm not seeing any notifications from azure/azdo suggesting there was any sort of degraded performance on their end.

I'm going to look through the various times this failed because of a timeout and see if I can figure out any similarities on the runtime side, but we may want to increase the timeout for publishing.

**Comment by mmitche** [comment]
I think this was a hang. Relevant timestamps:
```
2022-11-21T17:03:10.2702817Z ##[section]Starting: Publish packages, blobs and symbols
...
2022-11-21T17:20:51.4985889Z     aka.ms/dotnet/8.0/daily/Workloads.VSDrop.8.0.100.zip -> https://dotnetbuilds.azureedge.net/public/Runtime/8.0.0-alpha.1.22571.1/workloads/Workloads.VSDrop.8.0.100.8.0.0-alpha.1.22571.1.zip
2022-11-21T17:20:51.4986695Z   Updating 100 aka.ms links.
2022-11-21T17:20:51.4987152Z   Updating 100 aka.ms links.
2022-11-21T17:20:51.4987633Z   Updating 91 aka.ms links.
2022-11-21T19:01:16.4092597Z Attempting to cancel the build...
2022-11-21T19:01:16.7123174Z ##[error]The operation was canceled.
2022-11-21T19:01:16.7132082Z ##[section]Finishing: Publish packages, blobs and symbols
```

**Comment by michellemcdaniel** [comment]
Also @alexperovich, I wonder if this is one of those types of jobs that we could use agentless to do the waiting.

**Comment by michellemcdaniel** [comment]
Ah @mmitche, I always forget to look at timestamps.

This happened 3 times recently: twice seems to have been the same issue, a hang in the publishing job. The other, the publishing job passed, but it looks like it started nearly 15 hours later? I assume it was one of those jobs where it got stuck trying to get permissions for variable groups, though that would be a little odd (https://dev.azure.com/dnceng/internal/_build/results?buildId=2048123&view=logs&j=5c24930e-0ae1-546c-7353-8c3b261a7651&t=ede56238-58c2-5c27-0cb6-65bc8e848af0)

**Comment by mmitche** [comment]
That one shows:

```
"queueTime":"2022-11-18T09:32:15.750526Z",
"startTime":"2022-11-18T10:06:39.6750222Z",
"finishTime":"2022-11-18T10:31:00.7883769Z"
```

So that one just took a while to start, and your fix will resolve that to some degree.

**Comment by michellemcdaniel** [comment]
Did some kusto querying, and it looks like this has happened 13 times in the last week:

| BuildId | BuildNumber | TotalTime |
| ------ | -------------- | ---------- |
| 2049997 | Promoting dotnet-sdk build 20221120.6 (157436) to channel(s) '.NET 7.0.2xx SDK' # | 02:00:22 |
| 2050294 | Promoting dotnet-runtime build 20221121.1 (157533) to channel(s) '.NET 8' # | 02:00:33 |
| 2049023 | Promoting dotnet-runtime build 20221118.9 (157373) to channel(s) '.NET 8' # | 02:00:29 |
| 2048444 | Promoting dotnet-installer build 20221118.5 (157273) to channel(s) '.NET 6.0.3xx SDK Internal' # | 02:00:21 |
| 2047895 | Promoting dotnet-installer build 20221117.21 (157160) to channel(s) '.NET 8.0.1xx SDK' # | 02:00:21 |
| 2047468 | Promoting dotnet-icu build 20221117.1 (157057) to channel(s) '.NET 6' # | 02:00:33 |
| 2046948 | Promoting dotnet-installer build 20221116.11 (156976) to channel(s) '.NET 6.0.3xx SDK Internal' # | 02:00:24 |
| 2047098 | Promoting dotnet-runtime build 20221116.2 (157021) to channel(s) '.NET 6 Internal' # | 02:00:19 |
| 2046826 | Promoting dotnet-roslyn build 20221115.1 (156885) to channel(s) '.NET Core Tooling Dev' # | 02:00:22 |
| 2046363 | Promoting dotnet-runtime build 20221115.4 (156834) to channel(s) '.NET 7' # | 02:00:38 |
| 2046834 | Promoting dotnet-roslyn build 20221115.2 (156884) to channel(s) '.NET Core Tooling Dev' # | 02:00:32 |
| 2045487 | Promoting dotnet-installer build 20221114.31 (156672) to channel(s) '.NET 7.0.1xx SDK' # | 02:00:23 |

**Comment by michellemcdaniel** [comment]
Since this is for official builds, not PR/public CI, I am going to remove the known issues section.

**Comment by alexperovich** [comment]
Agentless waiting for things like this might work. It would be separate from the agentless helix stuff though. This looks like it just hung waiting for aka.ms link creation. I haven't heard anything about outages for that service.

**Comment by Chrisboh** [comment]
@michellemcdaniel are we good to close this?

**Comment by michellemcdaniel** [comment]
Actually, no. It is still happening: https://dev.azure.com/dnceng/internal/_build/results?buildId=2054045&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=c7a8693b-2f9c-5ea8-c909-cde9405ac2e1

**Comment by michellemcdaniel** [comment]
Since it successfully sent the request, I think @mmitche we were wrong about where this is hanging. There is more here to track.

**Comment by mmitche** [comment]
Yep. I'm glad you ended up keeping the logging in there. Either way, the async fix was correct, just not the real bug. Looking at the log there, there were 14 sends and 14 processings. Probably need to go peruse the code and see what else we may have missed.

**Comment by michellemcdaniel** [comment]
I think it'd be good to add some logging at the bottom of the function to say that the links were successfully created to see if we can eliminate all other paths in this function.

**Comment by michellemcdaniel** [comment]
Because the only other path I can see being an issue is the symbols publishing. I wonder if it's hanging trying to do some of the streaming?

**Comment by mmitche** [comment]
Let me take a look again. I saw this a few more times yesterday.

**Comment by mmitche** [comment]
More logging: https://github.com/dotnet/arcade/pull/11748

**Comment by mmitche** [comment]
There no obvious codepath that I can see that would be hanging. Maybe in the disposal of the http request message? Or perhaps it's not in aka.ms at all. Added logging for all those cases.

**Comment by mmitche** [comment]
Logging updated in latest publishing runs, but no timeouts in the last few hours.

**Comment by michellemcdaniel** [comment]
we have another https://dev.azure.com/dnceng/internal/_build/results?buildId=2057427&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=c7a8693b-2f9c-5ea8-c909-cde9405ac2e1

**Comment by michellemcdaniel** [comment]
We don't get the logging for "Completed publishing of blobs", and we get neither the enter or exit statement for persisting artifacts in BAR. So I think it's something in publishing blobs

**Comment by mmitche** [comment]
I think we may need more logging. I think if we turn on verbose logging for the publishing task we'll get enough of the low pri messages to start further pinpointing.

**Comment by mmitche** [comment]
Nothing obvious is popping out at the moment.

**Comment by mmitche** [comment]
Nothing new overnight

**Comment by michellemcdaniel** [comment]
We've got one from over the weekend: https://dev.azure.com/dnceng/internal/_build/results?buildId=2060537&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=c7a8693b-2f9c-5ea8-c909-cde9405ac2e1

**Comment by mmitche** [comment]
Nothing new since Thursday (I think fix went in early Friday)

**Comment by Chrisboh** [comment]
Are we good to close this then @mmitche ?

**Comment by mmitche** [comment]
I want to see another couple days of green builds, but I think we finally got it.

**Comment by MattGal** [comment]
Still looking good, closing.
