### ISSUE TITLE
Arcade SDK fails on macOS

### ISSUE THREAD

**Issue by sbomer** [dotnet/arcade#1169]
> /Users/sven/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.18524.4/tools/RepoLayout.props(33,5): error MSB4185: The function "GetFolderPath" on type "System.Environment" is not available for execution as an MSBuild property function. [/Users/sven/tmp/resolvetest/resolvetest.csproj]

Same issue as https://github.com/dotnet/roslyn-tools/issues/172.

**Comment by jcagme** [comment]
FYI @tmat

**Comment by markwilkie** [comment]
@sbomer - is this blocking you?

**Comment by sbomer** [comment]
@markwilkie not blocking, I've got a workaround (setting the nuget package path to prevent execution of https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/RepoLayout.props#L33).

**Comment by sbomer** [comment]
The call to GetFolderPath was removed in https://github.com/dotnet/arcade/pull/1423/files, fixing this.
