### ISSUE TITLE
Add support for using CentralPackageVersions MSBuild sdk for package versioning

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#117]
This syntax in project files using properties for package versions:
```xml
<ItemGroup>
  <PackageReference Include="Pizza" Version="$(PizzaPackageVersion)"/>
</ItemGroup>
```
With a `PackageVersion.props` file somewhere defining `PizzaPackageVersion=1.2.0` adds additional unneeded complexity to the project file. Additionally, it causes extra work for developers adding projects into arcade who don't know and/or forgot about this requirement and add explicit versions in the project file, only to be told to change it during PR if one of the reviewers notices the problem.

CentralPackageVersions removes the need to say anything at all about version in the Project file, and produces a build error if the developer does the wrong thing.

CentralPackageVersions will also play more nicely with maestro by removing the need to perform the PackageId -> Property Name transformation assuming that developers will do the "correct" thing.

**Comment by tmat** [comment]
https://github.com/Microsoft/MSBuildSdks/tree/master/src/CentralPackageVersions

**Comment by jaredpar** [comment]
Yes it's not great with the UI. But we can't use the UI for our packages anyways in our current proposal where we have to update a side file as well. I'm interested in the error prone claim.

**Comment by alexperovich** [comment]
If you typo the property name, you get no error just an odd warning from NuGet. To someone new to a project they might not know what that means and have trouble figuring out how to fix it. They might also not even know they need to add packages that way. With something like CentralPackageVersions (I had no idea that existed, it's really cool) a new developer who uses the VS UI to add a package will find success because the error message says exactly what they need to do. With the property scheme the developer gets no indication they did something wrong until code review. Adding support to the VS UI for this scenario would just be icing on the cake and more goodness for VS because we can't be the only project that needs centralized versions.

**Comment by jaredpar** [comment]
> If you typo the property name, you get no error just an odd warning from NuGet

That sounds like a bug in NuGet, not an inherent flaw in the design.

**Comment by markwilkie** [comment]
@alexperovich - can you check in with https://github.com/anangaur  on this please?  Apparently nuget has some plans around package versions and it would be good to understand better what those are and align to them.

**Comment by alexperovich** [comment]
@tmat @jaredpar I have updated the title and description. I think this should be added to the sdk as an opt-in/out allowing repos to choose. My biggest argument for this is it simplifies the project files, and doesn't require PR reviewers to catch mistakes.

**Comment by tmat** [comment]
@alexperovich Yes, I agree that it would be good to have eventually. I would not add it at this point to the toolset though. The msbuild repo, which is also on RepoToolset, is currently switching to central package versions, so let's wait to see how well it works there. We can then adopt it in other repos and make it the standard.

**Comment by markwilkie** [comment]
Closing until there's more demand
