### ISSUE TITLE
Hardware issues with PERFTIGER198

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#11701]
@LoopedBard3 notes this machine may be experiencing hardware failure.  It may be time to work with DDFUN to decommission it?

**Comment by LoopedBard3** [comment]
@MattGal Is there a process for starting this with DDFUN? I have not done this before so looking for any guidance. Thanks!

**Comment by MattGal** [comment]
Created https://portal.microsofticm.com/imp/v3/incidents/details/352553274/home to track running tests on the machine and/or decommissioning it.

**Comment by MattGal** [comment]
Update: Waiting on MLS folks to test the machine

**Comment by parose1** [comment]
Hi @MattGal MLS has completed the HW check and did find a failed memory module in PERFTIGER198. They replaced the memory module with an exact replacement from previously retired PERFTIGER*** machines. They re-ran the HW check and the system came back healthy. PERFTIGER198 is back up and heart beating. Please let me know if there is anything else needed. Thank you.
