### ISSUE TITLE
Renewal process of the aspnetmaven PGP key

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#11711]
https://dev.azure.com/dnceng/internal/_workitems/edit/3928

### Release Note Description
Have a process for renewing PGP keys

**Comment by dkurepa** [comment]
The key has been extended and added to one of our key vaults.
This was done on a Windows Sandbox VM, where we had to:
- import the old, expired key
- using the gpg --edit-key command, enter the editing mode for the key
- in the editing mode, using the expire command we extended the key by 2 years
- saved all progress with the save command
- exported the new public/private keys and uploaded them to our KeyVault. Both the old and the new key are available there now

**Comment by tkapin** [comment]
Can you please check for an exact dates when they are going to create the key and when they are going to roll it out?

**Comment by dkurepa** [comment]
A followup for this issue has been created in the staging pipeline epic https://github.com/dotnet/arcade/issues/13151
