### ISSUE TITLE
Documentation around additional SDL tools to run is lacking

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#11714]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The SDL templates and [documentation](https://github.com/dotnet/arcade/blob/758b26a79090d7c3bc7891af87b5d2c7b45e97aa/Documentation/HowToAddSDLRunToPipeline.md) include parameters to customize the tools that should run during the guardian scan. However, there is a lack of documentation for:
* Which additional tools are supported (even if just a link to the guardian docs)
* How to configure the additional tools.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
SDL is now being injected via 1ES PT, so this is probably not needed anymore.
