### ISSUE TITLE
Environment variables like DOTNET_INSTALL_DIR are not set correctly on Linux and macOS in CI build

### ISSUE THREAD

**Issue by GangWang01** [dotnet/arcade#11727]
### Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=94583&view=results

### Build leg reported

OSX debug_configuration/Build, OSX release_configuration/Build, Linux debug_configuration/Build, Linux release_configuration/Build

### Pull Request

https://github.com/dotnet/templating/pull/5667

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "[error]XUnit(0,0)",
    "BuildRetry": false
 }
 ```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Additional information about the issue reported

Tests on macOS & Linux were not executed due to required `Framework: 'Microsoft.NETCore.App', version '8.0.0-alpha.1.22570.4' (x64)` was missing according to test logs similar to below.
```
You must install or update .NET to run this application.

App: /home/vsts/work/1/s/.packages/xunit.runner.console/2.4.2/tools/netcoreapp2.0/xunit.console.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0-alpha.1.22570.4' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  3.1.4 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  3.1.6 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  3.1.20 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  3.1.31 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  5.0.4 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  5.0.9 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  5.0.17 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  6.0.11 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  7.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
In CI build, dotnet root should be `/home/vsts/work/1/s/.dotnet` rather than `/usr/share/dotnet`. 
Build.binlog told that environment variables like `DOTNET_INSTALL_DIR` were wrongly set.
![EV](https://user-images.githubusercontent.com/2950449/204269226-0e60c076-ccdb-4130-b05c-994c53a7333b.png)

On Windows in CI run it doesn't have this problem.

**Comment by andriipatsula** [comment]
Updated an ErrorMessage field

**Comment by alexperovich** [comment]
This version of the hosted mac machines has .net 7.0.100 installed in it. And the arcade update has tools.dotnet == '7.0.100'

This is triggering the 'Can we use the preinstalled .net" in the scripts so we are using that. The checks for "do you have runtimes in global.json" are somehow not working.

**Comment by alexperovich** [comment]
I have a fix for this here https://github.com/dotnet/arcade/pull/11736 

I manually applied it to https://github.com/dotnet/templating/pull/5667/files but it will also come with the next arcade update after I get this merged.

**Comment by alexperovich** [comment]
This has been fixed in arcade.
