### ISSUE TITLE
Signing validation is not working with .net 7.0

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade#11724]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Link to a failing build:
https://dev.azure.com/dnceng/internal/_build/results?buildId=2047797&view=logs&j=b11b921d-8982-5bb3-754b-b114d42fd804&t=cdcedd1f-8008-523f-9da1-cc35fbfef9a3

Work around: Disable signing validation https://github.com/dotnet/arcade/blob/main/azure-pipelines.yml#L329

Link on FR discussion: [teams](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1668725598780?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1668725598780&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1668725598780&allowXTenantAccess=false)

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by riarenas** [comment]
This should be fixed with https://github.com/dotnet/arcade/issues/11702

**Comment by akoeplinger** [comment]
It is fixed with #11702 but you need to make sure there's no `xcopy-msbuild` entry in global.json that overrides the version.

**Comment by ulisesh** [comment]
@sebastienros it looks like the problem was fixed in arcade, could you please give it a try in dotnet/crank?

**Comment by sebastienros** [comment]
@ulisesh it worked, thanks

https://dev.azure.com/dnceng/internal/_build/results?buildId=2058566&view=logs&s=3df7d716-4c9c-5c26-9f45-11f62216640d

**Comment by ulisesh** [comment]
Great, closing issue
