### ISSUE TITLE
Streamline Guardian scanning

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#11761]
# Overview
When we first adopted Guardian, we were very early adopters and Guardian was not fully integrated for the way we wanted to use it. We thus wrote some scripts to allow us to use Guardian as part of Arcade. Furthermore, the fact that we had our public and internal projects on the same AzDO instance meant we couldn't limit where the Guardian tasks (once they were created) were run.

With the advent of the Guardian tasks and the dnceng-public instance, we are now able to obviate the need for our custom scripts and switch to auto-injected Guardian tasks.

# Business Objectives
- [ ] Stop being a "unicorn" with regard to Guardian by using its official Azure Pipelines tasks
- [ ] Remove the maintenance overhead of maintaining our custom Guardian scripts

**Comment by missymessa** [comment]
SDL tasks moved to 1ES PT. Closing this.
