### ISSUE TITLE
Move some more .Rt Helix queues to Intel cores for AVX512 validation

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#11809]
@BruceForstall requests moving some Runtime Helix queues over from AMD EPYC to Intel-based SKUs for AVX-512 test scenarios. 

Queues to move: 
- windows.10.amd64.x86.rt 
- Ubuntu.1804.Amd64.rt
- Ubuntu.1804.Amd64.Open.rt

### Release Note Description
Move some .Rt Helix queues over to Intel AVX-512-supporting Azure SKUS

**Comment by MattGal** [comment]
Created https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/28081

**Comment by ulisesh** [comment]
I left a comment on the PR

Once we decide the VM SKU we will use, I'll do the math of how much this change would impact us

**Comment by MattGal** [comment]
D_v4 is already in use for AVX-512 support, this is just moving some more queues to it and adding comments explaining why.

**Comment by MattGal** [comment]
This has rolled out; the queues above are now all Standard D_v4 SKU, which supports AVX-512.

**Comment by BruceForstall** [comment]
> This has rolled out; the queues above are now all Standard D_v4 SKU, which supports AVX-512.

Thank you!
