### ISSUE TITLE
Pack fails with DotNetBuildFromSource=true

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#1183]
These projects have `ExcludeFromSourceBuild` set, so they aren't `Restore`d, but then they try to run some targets during `Pack` which fail:

```
/work/.dotnet/sdk/2.1.400-preview-009088/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(280,5): error NETSDK1004: Assets file '/work/artifacts/obj/Microsoft.DotNet.GenAPI/project.assets.json' not found. Run a NuGet package restore to generate this file. [/work/src/Microsoft.DotNet.GenAPI/Microsoft.DotNet.GenAPI.csproj]
/work/.dotnet/sdk/2.1.400-preview-009088/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(280,5): error NETSDK1004: Assets file '/work/artifacts/obj/Microsoft.DotNet.GenFacades/project.assets.json' not found. Run a NuGet package restore to generate this file. [/work/src/Microsoft.DotNet.GenFacades/Microsoft.DotNet.GenFacades.csproj]
/work/.dotnet/sdk/2.1.400-preview-009088/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(280,5): error NETSDK1004: Assets file '/work/artifacts/obj/Microsoft.DotNet.ApiCompat/project.assets.json' not found. Run a NuGet package restore to generate this file. [/work/src/Microsoft.DotNet.ApiCompat/Microsoft.DotNet.ApiCompat.csproj]
```

I'm guessing there are some new targets that need to be added to:

https://github.com/dotnet/arcade/blob/bcf675d551d7d9fc25277fdb8dc19a19989f462b/src/Microsoft.DotNet.Arcade.Sdk/tools/Empty.targets#L9-L20

Repro:

```
docker run -it --rm microsoft/dotnet-buildtools-prereqs:centos-7-b46d863-20180719033416 bash
# Inside interactive shell:
git clone https://github.com/dotnet/arcade
arcade/build.sh --pack \
  /p:DotNetBuildFromSource=true \
  /p:PackageProjectUrl=https://github.com/dotnet/source-build
```

(`PackageProjectUrl` is provided because SourceLink is disabled during a build from source--this is fine.)

Binlog: [pack-dotnetbuildfromsource.zip](https://github.com/dotnet/arcade/files/2520538/pack-dotnetbuildfromsource.zip)

---

@tmat are you still the right person to help with this?

**Comment by dagood** [comment]
Workaround is to delete the projects from the sln file. (This is fine for my purposes for now.)

**Comment by tmat** [comment]
Cool. I haven't had time yet to look into this. I'm close to getting Roslyn on Arcade SDK and will test our source build there.
