### ISSUE TITLE
Disable UseVerifiableInstrumentation in helix service code coverage settings

### ISSUE THREAD

**Issue by michellemcdaniel** [dotnet/arcade#11842]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
not for rollout notes

**Comment by premun** [comment]
Interesting - we've just hit the same in `arcade-services`: https://github.com/dotnet/arcade-services/commit/eb189ce3155c5f0989969f8f6b03b57103262543

@MarcoRossignoli can you explain to us what this does? Amaury claimed this should affect only .NET FW but we seem to have issues with this all over the place suddenly.

**Comment by MarcoRossignoli** [comment]
It's used for CAS with partially trusted code(CAS is no more a thing in .NET Core so it should not affect that testing scenario), can you point me to the "issues"?

**Comment by premun** [comment]
This is the one we've hit: https://dev.azure.com/dnceng-public/public/_build/results?buildId=96118&view=logs&j=074323ca-ed16-5d66-87ac-2d9d4a30c602&t=f23de43e-5140-53e2-77ae-1bfa956f8a5d&l=576

**Comment by premun** [comment]
@MarcoRossignoli additionally, we only had this when trying to `new Process()` from a unit test. It only manifested then.

We were launching another `dotnet` process.

**Comment by MarcoRossignoli** [comment]
We'll take a look we had in past some issue with children processes and the Shim, but for .NET Core tests you don't need it so it's fine set UseVerifiableInstrumentation  to false, the Shim for .NET Core is "a nop" and we're planning to completely remove.

**Comment by jakubch1** [comment]
We have logic to automatically disable verifiable probes for .NET Core processes. So you use old version of our package or you are starting .NET Framework process. What version of Test.SDK or Microsoft.CodeCoverage you are referencing in test project?

**Comment by michellemcdaniel** [comment]
`<PackageVersion Include="Microsoft.CodeCoverage" Version="16.5.0" />` in helix-service. `<PackageVersion Include="Microsoft.CodeCoverage" Version="16.6.1" />` in arcade-services

**Comment by jakubch1** [comment]
Please upgrade to latest stable: 17.4.0. This issue was fixed around 16.11.

**Comment by michellemcdaniel** [comment]
Thanks! I'll create an issue for us.
