### ISSUE TITLE
Differentiate artifact types in documentation

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#1187]
We need to define terminology in a way that makes sense and leads to less confusion due to overloaded terms.

Sample:

> “Artifacts” can be a bit overloaded.  In the case of Azure DevOps, the “artifacts” tends to imply surfacing information to help with investigations and that generally ends up meaning “save the build logs”, as Arcade does here, https://github.com/dotnet/arcade/blob/master/eng/build.yml#L78.  

> Publishing of artifacts is now supported in both public and internal builds.

> If by “artifacts”, you mean build assets (nupkgs) and such, then that depends on your build but usually involves publishing assets to blob feed.

> Alternatively, you may be asking about transferring “artifacts” (ie build assets) between phases.  DevOps doesn’t currently have support for this built in.  The general model is to have a build pipeline which publishes artifacts and then a dependent release artifact which downloads the artifacts.  

> Depending on your scenario, there are some “tricks” we could employ like using “Trigger Build Task” along with the “Download Build Artifacts” task to make things work.  It feels a little icky and I think we should work with Azure DevOps to figure out their recommend before we go down that path and I’d think we’d kind of carry-over what CoreClr is doing today if necessary (ie blob storage) until DevOps provides a better solution (pipelines).

Side note:  I think "Publish build artifacts" / "Download build artifacts" is not "icky" for the above scenario and is actually the guidance we should be providing, particularly for public projects where blob storage is less of a simple option.  Azure DevOps is looking into supporting publish / download artifacts with first class syntax support (no current known timeline for that).

**Comment by JohnTortugo** [comment]
I think we've been kicking this issue down the road for sometime now :-| . I'll make sure to make this clear when working on creating the documentation for the new publishing infra: https://github.com/dotnet/arcade/issues/3599
