### ISSUE TITLE
Regenerate signing certificates for osx.1100.amd64.appletv.open

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#11898]
Follow instructions from https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/862/Apple-(iOS-tvOS)-signing-certificates to unblock test machines in this queue; check others for similar symptoms

Once this works on osx.1100.amd64.appletv.open, we also need to update:

```
osx.1015.amd64.appletv.open
osx.1100.arm64.appletv.open
osx.amd64.appletv.scouting.open
```

**Comment by MattGal** [comment]
@premun , I followed the instructions provided as best as I could, but ended up with this error:
```
[12:15:23] dbug: error MT1006: Could not install the application '/tmp/helix/working/B089095A/w/B95009FF/e/Microsoft.Extensions.Logging.Testing.Tests.app' on the device '6a408d29795884d85dbde190f230b4bf582aea28': AMDeviceSecureInstallApplicationBundle returned: 0xe8008015.
[12:15:23] dbug: 
[12:15:23] dbug: AMDeviceSecureInstallApplicationBundle returned: 0xe8008015
[12:15:23] dbug: Process mlaunch exited with 1
[12:15:23] fail: Failed to install the application
                 No valid provisioning profile found
```
[Sample log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/results-056677acb0aa46bd8d/Microsoft.Extensions.Logging.Testing.Tests/1/console.18fbc3cd.log?helixlogtype=result)
... Interestingly, I can't find any evidence in Xharness or the artifact involved that the "NET_Apple_Development_tvOS.mobileprovision" file is even used by XHarness or the Helix machines artifact.

Let's synch up on Teams when you're available and work through this together; it's possible I just misunderstood your instructions but either way at this point I'm stumped.

@steveisok FYI.

**Comment by MattGal** [comment]
All machines are update except DNCENGMAC020 & DNCENGMAC037, I will update these manually.

**Comment by MattGal** [comment]
I manually ran the setup artifact on the above two machines, so all tvOS certificates have been updated.  Closing issue... @steveisok please let me know if the symptom comes back / reopen the issue. 

From checking out https://dnceng-public.visualstudio.com/public/_build/results?buildId=107808&view=logs&j=acac6bf3-3edd-5022-4e45-3362a02520b1&t=1de8bf71-8fe5-5d5c-4360-8c2eb159d012, the helix run ran on every machine in osx.1100.amd64.appletv.open and passed work items on each, with one timeout in System.Text.Json that seems to be not new.

**Comment by premun** [comment]
@MattGal did you also do the iphone queues?

**Comment by MattGal** [comment]
> @MattGal did you also do the iphone queues?

Yes.  The full list of queues updated was 
```
osx.1015.amd64.appletv.open
osx.1015.amd64.iphone.open
osx.1015.amd64.iphone.perf
osx.1100.amd64.appletv.open
osx.1100.arm64.appletv.open
osx.1200.amd64.iphone.open
osx.amd64.appletv.scouting.open
```
