### ISSUE TITLE
Add .devcontainer support to the VMR

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/arcade#11902]
It would be nice to define a .devcontainer for the VMR that contains the prereqs to build the repo.  We had this capability with the source-build tarball infra in dotnet/installer - https://github.com/dotnet/installer/tree/main/.devcontainer

**Comment by MichaelSimons** [comment]
cc @premun - I consider this a lower priority nice to have item

**Comment by premun** [comment]
> Note: This should replace functionality removed in https://github.com/dotnet/installer/pull/15114/files
