### ISSUE TITLE
Permission to modify build pipeline

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade#11932]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

I gave permission to DotNet-Templating-Maintainers security group to edit this pipeline : https://dev.azure.com/dnceng/internal/_build?definitionId=303&_a=summary

After they are done we will remove the permission

**Comment by ilyas1974** [comment]
Customer has completed their work. I have removed the permissions.
