### ISSUE TITLE
Migrate DotNet.Status.Web to Azure.Security.KeyVault

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#11951]
Part of Part of https://github.com/dotnet/arcade/issues/11852

**Comment by dkurepa** [comment]
pr: https://github.com/dotnet/arcade-services/pull/2152

**Comment by dkurepa** [comment]
The PR has been merged and the Staging App has been deployed successfully. We had to give it the Contributor access to the storage account for it to work. We will do the same thing when it comes time for the production deployment

**Comment by garath** [comment]
Does it need contributor to the entire storage account, or does it work with a narrower scope like the blob container, blob, or table?

**Comment by dkurepa** [comment]
I haven't tried narrowing the scope yet. I will try reducing the the access on the staging build this week to see if it will still work.
There were no roles that had a narrower scope (just target the containers), but a role with less access might work.
For now I gave the prod app service the Contributor role, same as we deed for staging

**Comment by dkurepa** [comment]
This has been rolled out
