### ISSUE TITLE
Helix "Work Item Details" API 404s for any job that failed in data migration

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#11977]
As part of investigating https://github.com/dotnet/arcade/issues/8850, I noted I found many work items which seemingly incorrectly 404'ed as a result of not finding the work items in `GetWorkItemDetails()` in `src\ServiceFabric\Helix\HelixAPI\Shared\HelixDataService.cs` (this is called by, for instance, `/api/jobs/{job}/workitems/{id}/files`)

Poking around, it's because of this query:
```
Jobs
| where Name == {the job name}
| project JobName = Name
| join kind = inner(WorkItems) on JobName
| where FriendlyName == {the friendly name}
| project JobId, WorkItemId, Name, Status, Queued, Started, Finished, ExitCode, ConsoleUri, MachineName, Attempt
```
The problem is that in any case where the data migration processor fails to migrate a job from SQL -> Kusto,  the work items will exist but not the Job, making the above query return nothing as soon as SQL is cleaned out (about 24 hours). This failure to migrate can happen for all sorts of reasons including transient outages (azure devops or otherwise), bad test case naming, lack of permissions to the Azure DevOps org where test results are stored, etcetera.

We haven't had specific reports of this impacting customers, so I wanted to raise it to discuss in triage.   Adjusting this query to just get all the fields it gets directly from the WorkItems table would be trivially easy, but we'd then need to de-dupe for the same information if it also came from SQL.

This query, for example, gives the same results as the above but works when there is no Job in the Kusto DB:

```
WorkItems
| where JobName == {the job name}
| where FriendlyName == {the friendly name}
| project JobId, WorkItemId, Name, Status, Queued, Started, Finished, ExitCode, ConsoleUri, MachineName, Attempt
```

**Comment by MattGal** [comment]
On further inspection the join is necessary.  Kicking back to triage to discuss one more time and probably close (as this is an exceptional scenario and no actual users are asking for it)

**Comment by michellemcdaniel** [comment]
Sounds like this doesn't need fixing, closing.
