### ISSUE TITLE
Notification process for when cloaked files are found in the VMR

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#11985]
### Problem

When we change cloaking filters, files already checked in the VMR will stay checked in. We should learn about this somehow.

### Goal

- Figure out how to get the files (possibly create a diff using all of the cloakings)
- Add a validation stage into the official VMR CI pipeline

### Release Note Description
Have a way of detecting cloaked files in the VMR automatically

**Comment by dkurepa** [comment]
pr for the VMR scan command: https://github.com/dotnet/arcade-services/pull/2162

**Comment by dkurepa** [comment]
the PR has been merged. We'll have to update darc in the installer repo and update the CI to scan the VMR after synchronizing it

**Comment by tkapin** [comment]
@dkurepa could you please describe what's the solution in this case? thanks

**Comment by dkurepa** [comment]
The solution works by creating a git diff with the "zero commit" for each VMR repo (arcade, runtime, ...) and searching for all of the files that are *excluded* in the source-mappings.json that do not have the *vmr-preserve*. So in the end, the command looks something like `git diff --name-only <zero commit sha>  :(attr:!vmr-preserve)src/arcade/\*/\*.dll ...`

**Comment by premun** [comment]
This is in place already
