### ISSUE TITLE
Incorporate (merge) doc from Adam 

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#1199]
@AdamYoblick wrote a nice doc based on his experiences starting from scratch.  This needs to be incorporated into the main docs.

https://teams.microsoft.com/_#/docx/viewer/teams/https%3A~2F~2Fmicrosoft.sharepoint.com~2Fteams~2FNETCoreEngServicesPartners~2FShared%20Documents~2FArcade~2FArcade%20-%20Starting%20From%20Scratch.docx?threadId=19%3A1dad2081c8634f34915d88dce6220265%40thread.skype&messageId=1540829709668&baseUrl=https%3A~2F~2Fmicrosoft.sharepoint.com~2Fteams~2FNETCoreEngServicesPartners&fileId=b0d2e383-9b89-43fe-83e4-8d4e1ff2d750&ctx=chiclet&viewerAction=view

**Comment by garath** [comment]
See also: [Arcade - Starting from Scratch](https://microsoft.sharepoint.com/:w:/t/MerriesWinFormsandSetup/EdJpqtiLVdtFuS6p10E0o_IBVu2WsETAd4zBf6YdVKsLcQ?rtime=hYbVs0Vh1kg) and [Build Automation](https://microsoft.sharepoint.com/:w:/t/MerriesWinFormsandSetup/EXeMyTffPftOhto3dVDbGWIBTZ68F-DGvsVZ8tc3F0Obbg?rtime=8qiw-0Rh1kg).
