### ISSUE TITLE
New Queues for Performance Team

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#12006]
Per recent conversation with the performance team, we need the following queues created 

### Release Note Description
Added support for the following on-premises perf queues 

- windows.11.amd64.tiger.perf
- windows.11.amd64.tiger.perf.open
- windows.11.amd64.tiger.perf.scouting
- windows.11.amd64.owl.perf
- windows.11.arm64.perf.surf
- ubuntu.2204.amd64.tiger.perf
- ubuntu.2204.amd64.tiger.perf.open
- ubuntu.2204.amd64.tiger.perf.scouting

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/28466

**Comment by MattGal** [comment]
Rolled out today.
