### ISSUE TITLE
Clean-up PowerBI workspace

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#12015]
- [ ] This issue is blocking
- [ ] This issue is causing unreasonable pain

@ilyas1974 notes that the team's PowerBI workspace is cluttered with reports no longer in use and asked that it be cleaned up.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

(Exclude from release notes.)

**Comment by garath** [comment]
Criteria for deletion:

- Dataset unused by any report
- No refresh in 2022
- No views in last 30 days (as reported by dataset report usage)

Here is a list of the names of all reports and datasets that were deleted.

Datasets not used in any reports:

- build_reliability_timelinebuilds_public
- Failure Breakdown
- ToF Cost
- build_reliability
- build_reliability_internal
- build_reliability_public
- DNCEng Metrics (Draft)

Reports without any datasets:
- Product KPIs

Reports that are unused:
- OSOB Inventory Report
- Azure Cost
- BuildData
- Custom Autoscale Cost Estimate
- GitHub Throttling
- Key Metrics - On-Prem
- Helix Managed Storage Usage
- Hardware
- Key Metrics (Month over Month)
- On Premise Allocation
- OSOB Inventory Report

Also removed:
- Monitoring: Known to not be useful as data is now in Grafana.

**Comment by garath** [comment]
I saved a copy of all of these. If anyone wants any restored, just let me know.

**Comment by ilyas1974** [comment]
I think the following reports should be restored

- OSOB Inventory Report (this was on the list twice - don't know if it was a duplicate?)
- Hardware
- On Premise Allocation

While these reports are not used often, I do know that they are used whenever questions come up in these areas. The data does not change often so while it has not been updated recently - that does not mean is isn't still accurate.

**Comment by garath** [comment]
> I think the following reports should be restored
> 
> * OSOB Inventory Report (this was on the list twice - don't know if it was a duplicate?)
> * Hardware
> * On Premise Allocation
> 

These are now restored.
