### ISSUE TITLE
Offline / Decommission OSX 10.15 machines too slow to reliably run Apple Simulators

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#12038]
The following machines are now offline:

"dci-mac-build-013",
"dci-mac-build-014",
"dci-mac-build-015",
"dci-mac-build-019",
"dci-mac-build-021",
"dci-mac-build-023",
"dci-mac-build-024",
"dci-mac-build-028",
"dci-mac-build-030",
"dci-mac-build-031",
"dci-mac-build-032",
"dci-mac-build-035",
"dci-mac-build-036",
"DCI-MAC-BUILD-037",
"DCI-MAC-BUILD-042",
"dci-mac-build-043",
"dci-mac-build-144",
"dci-mac-build-145",
"dci-mac-build-146",
"dci-mac-build-148",
"dci-mac-build-179",
"dci-mac-build-188"

This comes from them reliably timing out while trying to run Apple Simulator tests, which this queue is coincidentally used for.

Query used:
```
let jobIds = 
Jobs 
| where QueueName == "osx.1015.amd64.open"
| extend props = parse_json(Properties)
| where tostring(props["System.StageName"]) == "Test_XHarness" and tostring(props["System.PhaseName"]) == "Apple_Simulators"
| summarize by JobId;
let machinesThatTimedOutAppleSimulators = 
WorkItems
| where JobId in (jobIds)
| where Name != JobName
| where Finished > ago(30d)
| where ExitCode == -3
| summarize by replace_string(MachineName, ".local", "");
HeartbeatExport
| where Machine in (machinesThatTimedOutAppleSimulators)
| summarize by Machine, Queue
```
 Removing these 21 machines will greatly increase Xharness and Arcade repo test perf and reliability.

**Comment by MattGal** [comment]
Assigned to Ilya per his request; he will follow up w/ runtime team about machine allocations.

**Comment by MattGal** [comment]
Offlined dci-mac-build-146 as it has the same problem and is an EOL mac mini

**Comment by ilyas1974** [comment]
Closing this issue as duplicate. Please see https://github.com/dotnet/arcade/issues/13531 for current status of this work.
