### ISSUE TITLE
Lots of base images need updated

### ISSUE THREAD

**Issue by v-zheyan** [dotnet/arcade#12040]
Updated all required base images

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Updated all required base images

**Comment by MattGal** [comment]
Something is wrong with the latest mariner 2 image (using 2.20221203.01) that this change brought to main. Image generation logs actually show no errors, but deprovisioning doesn't finish or something, and it logs "Image has not been updated for at least 15 minutes; failing."


I kicked off a fresh generation of the mariner image in https://dnceng.visualstudio.com/internal/_build/results?buildId=2076116&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3 that will pick up 2.20221215.01.  Tracking ID is d160f3b2-4260-ab7b-32c1-cc0509f9c377.  After this finishes, I will PR up the Helix-Mariner-2-* image it makes to see if this fixes things.

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/28514 is that attempt.

**Comment by MattGal** [comment]
Same problem there, so I created https://github.com/dotnet/arcade/issues/12042 to track working with DDFun to figure out what's going on in ImageFactory.

**Comment by MattGal** [comment]
All images are updated and main is green again, moving to "waiting for rollout"

**Comment by MattGal** [comment]
Rolled out.
