### ISSUE TITLE
[darc/maestro++] Maestro schedule based update cron strings should be configurable

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1205]
We can't force everything to go at 5am or so.  It should be configurable on a per-subscription basis, and should take generic cron strings, ideally with `@daily` shortcuts for typical cases.

**Comment by jcagme** [comment]
I think this is still needed but probably low in priority

**Comment by safern** [comment]
We would like to use this in corefx and coreclr... we need a faster dependency flow in between this repositories, because coreclr consumption is slow now, if there is a regression we have to wait till next day or update it manually ourselves. However we can't do per build, since we have rolling builds which will probably beat CI system in coreclr. So we would like to have a frequency of every 5 hours or so.

cc: @tannergooding

**Comment by safern** [comment]
@markwilkie can we give this guy a higher priority? I think it is important for productivity... right now to close an issue where code lives in coreclr, sometimes it takes us around 72 hours to get it in.

**Comment by mmitche** [comment]
@safern I don't think so, we have a ton of work to do by P7 and I don't see this as higher priority than say internal servicing workflows and publishing.

**Comment by safern** [comment]
cc: @danmosemsft

**Comment by tannergooding** [comment]
Right, currently in the normal case:
* Check in a PR against CoreCLR
* Wait till the next morning for changes to flow into CoreFX
* Check in ref assembly fixes against CoreFX
* Wait till the next morning for changes to flow into CoreCLR
* Check in remaining changes
* Wait till the next morning for changes to flow into core-setup
* Wait till the next morning for changes to flow into core-sdk (for a nightly msi you can install)

This is also assuming that everything lines up and we don't push a build that is missing some change required.

**Comment by tannergooding** [comment]
CoreCLR/CoreFX are in a torn state in the interim for these types of changes as one or the other could be exposing APIs that haven't been properly supported by the JIT or that have been removed from S.P.Corelib.

This will also heavily impact cases like the experimental work on the ARM HWIntrinsics (which we have some external partners that will be assisting on this).

**Comment by mmitche** [comment]
FYI you don't actually need to wait.  Using `darc trigger-subscriptions` you can fire off the subscription without doing a local manual update.

**Comment by tannergooding** [comment]
> Using darc trigger-subscriptions you can fire off the subscription without doing a local manual update.

I believe this also requires the authentication tokens/etc to be setup, correct?

Would it be much work to setup a job someone can explicitly trigger in AzDO to do the same?

**Comment by jcagme** [comment]
No, it shouldn't be a lot of work. An example for that would be https://github.com/dotnet/arcade/blob/master/eng/common/generate-graph-files.ps1. Which installs darc (on a pinned version) and executes a command using the tokens passed in. For trigger-subscriptions I think you only need barToken. To pass in the toke you need to do https://github.com/dotnet/arcade/blob/master/eng/common/templates/job/generate-graph-files.yml#L21

**Comment by riarenas** [comment]
We already provide more frequent updates such as `TwiceDaily` and `EveryBuild`

Closing, feel free to reopen if more granular control is needed.
