### ISSUE TITLE
Cleanup/Refactor VMR CI Artifacts 

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/arcade#12099]
The artifacts in the VMR CI builds are confusing/poorly named which can lead to folks grabbing the wrong artifacts - [build artifacts](https://dev.azure.com/dnceng/internal/_build/results?buildId=2079974&view=artifacts&pathAsName=false&type=publishedArtifacts) (Microsoft internal link).

<img width="499" alt="image" src="https://user-images.githubusercontent.com/8290530/210860792-3e76489a-d954-41fb-9fa1-cf033c7e5a97.png">

The issue is related to the following folders:

* AssetManifests
* BlobArtifacts
* PdbArtifacts
* Linux_linux_Build_Arm64_Release_<nnn>
* Linux_linux_Build_LinuxPortable_Release_x64_<nnn>

I believe these folders all contain artifacts from the Microsoft SDK leg which produces the Microsoft SDK used in the sdk comparison tests.  The issue I see is there is no indication these are artifacts are associated with that leg.  Someone could easily interpret BlobArtifacts/dotnet-sdk-...tar.gz to be the portable source-built one.

**Comment by MichaelSimons** [comment]
cc @premun

**Comment by premun** [comment]
This issue will be superseded by https://github.com/dotnet/arcade/issues/12338
