### ISSUE TITLE
Update the default version of MSTest

### ISSUE THREAD

**Issue by Evangelink** [dotnet/arcade#12095]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Currently, arcade is shipping with by default version `2.0.0` (see https://github.com/dotnet/arcade/blob/3fd7922054e920d6289194eec58435badc7c4385/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L94). This version of MSTest is more than 3 years old (2019.03.09 according to [NuGet](https://www.nuget.org/packages/MSTest.TestFramework/2.0.0)). I was wondering if we could update to newest (maybe latest) available (e.g. [3.0.2](https://www.nuget.org/packages/MSTest.TestFramework/3.0.2)).

I don't know what would be the notification process for users as there might be multiple breaking changes related to this bump (not only the ones described in 3.0.0 but all version from 2.2.X are including breaking changes in patch version).

cc @MarcoRossignoli @pavelhorak 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by michellemcdaniel** [comment]
What is the business reason for making this potentially breaking change? Could you just use the MsTestVersion property to use the version you want for your repo?

**Comment by Evangelink** [comment]
> What is the business reason for making this potentially breaking change?

I am the owner of MSTest repository and I'd like to encourage people to use "latest" of our tool by default. Doing a small search on MS repositories, I have seen that most people don't bump the version of the test framework version so I'd like to encourage migration to latest supported version. In this effort, I have recently onboarded MSTest to arcade and started to publish dogfood versions to some channel.

As part of the v3 release, we did a big effort to fix long standing bugs, most upvoted bugs and reducing the feature gap between TFMs. This version contains multiple breaking changes that fall under the following categories:
- Remove out of support TFMs
- Fix long standing bugs. Because these issues exist for a long time people started to rely on the incorrect behaviour.

As a side note, I'd also would like to point out that all versions of MSTest after 2.2.3 (so 4 to 10) are lying from a semantic versioning point of view as they contain new features and even breaking changes inside a patch version so you already did a couple of breaking changes without noticing it. 

I can understand if this is not enough for you but I'd like to get a little more information on what would be the story to move on teams out of this old version.

> Could you just use the MsTestVersion property to use the version you want for your repo?

I definitely can bump the version of MSTest on repositories I own/work with.

**Comment by michellemcdaniel** [comment]
@markwilkie @Chrisboh do we know how many repositories are using mstest?

**Comment by Chrisboh** [comment]
I am not sure but I didn't think many were.

**Comment by michellemcdaniel** [comment]
After doing some searching in the dotnet org for "MSTest.TestFramework", which should be a pretty clear indication that a repo is using MSTest vs XUnit, it looks like dotnet/sdk is the only repo really using MSTest, and using the MSTestVersion variable to set the version they use. Other repos that use MSTest are hard coding the version they want to use, irrespective of MSTestVersion (most teams use XUnit or NUnit).

@Evangelink I would reach out to the dotnet/sdk team to see if you can convince them to roll forward, and work with them on setting MSTestVersion in their repo. If we can guarantee that all teams using MSTestVersion in their repos are setting the version themselves, then we might be willing to take the update in arcade, but if we roll something out that will break repos, it 1) won't be taken by the repos and 2) will probably just be reverted as that is the safest way to unblock all the other changes that we make and need to roll out to repos that are onboarded to arcade.

**Comment by michellemcdaniel** [comment]
I don't believe they use arcade. arcade is a part of dotnet's infrastructure.

**Comment by Evangelink** [comment]
How do you want to handle this. Shall we close this ticket and I reopen if every arcade onboarded project is now already using MSTest v3+? Or shall we keep this open with a "blocked" state until all repos have moved?

**Comment by Evangelink** [comment]
Reviving the issue as we have now moved `dotnet/sdk` to newer version and we have now 2 years of feedback on MSTest v3.

**Comment by Evangelink** [comment]
@michellemcdaniel do you need some other confirmation? Can I create a PR?

cc @mmitche

**Comment by missymessa** [comment]
@Evangelink, feel free to create a PR. @michellemcdaniel is no longer on the dnceng team.
