### ISSUE TITLE
JobSender regression -- HelixWait task no longer breaks the build on work item/test failure

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#1209]
Need to add logic to break the build when that occurs.

cc / @alexperovich

**Comment by MattGal** [comment]
Can either of you help me understand how  this is a regression?  I can't seem to find any code in the Helix Arcade SDK that looks at XUnit results of even work item exit codes

**Comment by markwilkie** [comment]
The current (longer term) thinking is to let AzDO fail (or not) the build based on the fact that there are failing tests or not.

@AdamYoblick - we're working on getting the Helix test results loaded directly into AzDO under the test tab.  (pretty cool)  However, this won't be ready until a few weeks from now.  Given that any short term fix would be both expensive, and throw away - can you live with this for now?

**Comment by AdamYoblick** [comment]
That IS pretty cool :)

But I think those are two separate tasks, no? A failed helix job failing the build seems unrelated to getting helix job results in the test tab imo. But in either case, yes, we can live with it, we'll just run our tests on the build machine in the meantime

**Comment by AdamYoblick** [comment]
Ah, then that sounds perfect. Will this work for arbitrary helix jobs as well (functional tests, etc...)?

**Comment by jonfortescue** [comment]
Yes. All Helix jobs will work this way.

**Comment by markwilkie** [comment]
We can close once AzDO is working for us.

**Comment by safern** [comment]
Is this planning to be fixed: I see the regression was caused here -- https://github.com/dotnet/arcade/commit/ad4e7d02c4d2a20fbb5d3e79e33d24381412aa94#diff-d4e35e4b8161372d4f3f7dfeac3eafb4

I'm hitting this in CoreFX and this is the only piece missing to enable CI in CoreFX.

**Comment by AdamYoblick** [comment]
Santiago, the helix team is working on getting the helix job results into the Test Results tab in Azure Dev Ops, which will give us the same functionality with the added benefit of seeing the logs (as long as your helix jobs spits out xUnit xml). 

So unless I'm mistaken, they are opting to not fix this the existing helix code and instead fix it with this new feature.

**Comment by safern** [comment]
> Santiago, the helix team is working on getting the helix job results into the Test Results tab in Azure Dev Ops, which will give us the same functionality with the added benefit of seeing the logs (as long as your helix jobs spits out xUnit xml).

Thanks! Yes I do know of that work happening, but how long is that going to take? Cause if we want to move out of Jenkins in CoreFX either one or the other is required 😄 

So I just want to know if they are planning on fixing this, since I saw it open, just want to know what to expect and if I should just block on this.

**Comment by alexperovich** [comment]
This change https://github.com/dotnet/arcade/pull/1356 adds support for pure test results showing up in AzDev. The Console logs will take a bit longer.

**Comment by jonfortescue** [comment]
I'm going to close this since #1356 will soon be merged.
