### ISSUE TITLE
Start "darc" library with script support

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#121]
Start the darc library which knows how to record (locally) the fact that a script has been updated.  https://github.com/dotnet/arcade/pull/120

The next step will be to have "maestro++" use this library to understand the changes, and then update the stack by also asking each repo darc library to do the right thing.  

Completion means:

- [x] Write a Darc spec
- [x] Implement initial Darc functions so Maestro++ can consume it for prototyping purposes (merely remote operations)
- [ ] Add local repo operations
- [ ] Test both Maestro++/dev scenarios

**Comment by markwilkie** [comment]
#60 is also relevant.  (might be able to close it as dup)

**Comment by maririos** [comment]
Issues have been created under the Epic #74 which tracks the work needed for Darc and Maestro++ in order to flow dependencies.
