### ISSUE TITLE
Manage the dn-bot gh account secrets

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#12100]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We need to manage the dn-bot GitHub secrets so we can manage GH pats.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Do not include in release notes.

**Comment by MattGal** [comment]
Any update here?

**Comment by ilyas1974** [comment]
Closing this issue as we will be doing this work as part of https://github.com/dotnet/dnceng/issues/535
