### ISSUE TITLE
Remove manual prompts from Helix setup script

### ISSUE THREAD

**Issue by JpratherMS** [dotnet/arcade#12118]
When installing helix via our automation there are manual prompts asking you to enter "YES" (see screenshot) for platform version check overrides. I believe this is the last step we need removed before automation is complete

![image](https://user-images.githubusercontent.com/26681415/211104188-ecce79a1-669c-44b0-bfa7-3010adabc93a.png)

**Comment by MattGal** [comment]
Tossing into FROps backlog.  Due to some limitations of how we image on-prem Helix machines this will need to be Windows-only ; @JpratherMS and I discussed on Teams and this seems OK.  I am thinking adding a "-noprompt" flag that will block unnecessary prompts.

**Comment by MattGal** [comment]
Chatted with @parose1 today and I think this is already done, just not in use when doing UIP-based imaging.

From reading the sources to the helix machines driver python file:
``` py
    platform_check = True
    if '-p' in opt_dict:
        platform_check = False
```
This in turn is set by the run.py being called with `--skip-platform-check`, so we just need to add `--skip-platform-check` to anywhere we intend to do full unattended install and this entire check gets removed from behavior.

If I am mistaken and this doesn't work, please feel free to reactivate it and we'll explore it further.
