### ISSUE TITLE
Replace BlockStable with !IsShipping in Version.props

### ISSUE THREAD

**Issue by tmat** [dotnet/arcade#1213]
Update CoreFX to use `IsShipping`.

**Comment by weshaggard** [comment]
cc @ericstj 

What other implications does IsShipping have? From a quick look it would appear that things still get signed so that is good.

**Comment by tmat** [comment]
It does not disable publishing PDBs in general. Only Windows PDBs. Portable PDBs are still published.

`IsShipping` means it does ship via an official channel, e.g. nuget but not only nuget:
> projects that produce NuGet packages that are not shipping on NuGet.org or via other official channel 

@weshaggard Commented on `BlockStable`:
> Some projects want to remain producing prerelease packages even if we are doing a final stable build because *they don't ship or aren't ready to ship stable*

Which to me sounds like the same thing that `!IsShipping`. 

If `BlockStable` is not what the comment means then please define it precisely.

**Comment by jcagme** [comment]
Looks like `BlockStable` is still used in corefx. Have we decided if we are going to change that to `!IsShipping` or not?

**Comment by ericstj** [comment]
I believe they have different meanings described above.

**Comment by tmat** [comment]
@ericstj We have allowed for finder grained control using `IsShippin` properties. See https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#isshipping-isshippingassembly-isshippingpackage-isshippingvsix-bool

Wouldn't setting `IsShippingPackage` to `false` work?

**Comment by tmat** [comment]
Actually, I still think the projects should just set `IsShipping` to `false` -- based on this statement: "they don't ship or aren't ready to ship stable".

**Comment by ericstj** [comment]
They do ship in the sense that we build and publish the package along with the rest of the packages.  The only difference is that they don't move to stable versioning if the rest of the product does.  That is the sole purpose of this flag.  When the product is ready to remove the pre-release specifier these packages keep their prerelease suffix.

**Comment by tmat** [comment]
I see. Makes sense. Since this property effectively suppresses `DotNetFinalVersionKind` can we rename it to `SuppressFinalVersionSuffix`?

**Comment by ericstj** [comment]
I find that an odd name since it uses the terms *suppress* and *suffix* however the behavior is to actually *include* a *suffix*.  Maybe just `SuppressFinalVersion` or `SuppressStableVersion`?

**Comment by tmat** [comment]
`SuppressFinalVersion` sounds good.

**Comment by tmat** [comment]
Or maybe `SuppressFinalPackageVersion` to be a bit more specific. Either way.

**Comment by ericstj** [comment]
Seems reasonable.

**Comment by mmitche** [comment]
@ericstj @tmat It looks like we closed on the behavior that if a package has IsShipping=false, it should not have stabilized versioning if DotNetFinalVersionKind=release, and that BlockStable=true will override the stable versioning even for shipping packages.

This appears to be broken in arcade today. We produce stable versioning for non-shipping packages. I can go and fix the behavior, just wanted to make sure that the current behavior was not intentional.

**Comment by ericstj** [comment]
If a package sets BlockStable it should never be built without a prerelease suffix.  /cc @anipik

**Comment by mmitche** [comment]
Right, and I think that's right and works properly today.  But if a package is non-shipping (project sets IsShipping=false) then we should produce non-stable versions.  There should be no reason to additionally have to set BlockStable=true.  Setting BlockStable=true for packages that are shipping, but which are not yet ready to produce final versions is a slightly different scenario.

**Comment by safern** [comment]
PR is out in corefx: https://github.com/dotnet/corefx/pull/41513

**Comment by safern** [comment]
PR is out in corefx: https://github.com/dotnet/corefx/pull/41513
