### ISSUE TITLE
NetCore-Public-XL agents internet connectivity is degraded

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#12148]
Today, roughly 4 hours ago, the machines in the NetCore-Public-XL started having issues cloning repositories from GitHub:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=131923&view=logs&j=61a52f3a-cec1-5bff-8c02-d8ba2c8bed99&t=a25c6909-5dd7-54ad-ee4f-b38644d21392
 
Receiving objects:  44% (81137/183707), 114.94 MiB | 56.00 KiB/sReceiving objects:  44% (81141/183707), 115.01 MiB | 58.00 KiB/sReceiving objects:  44% (81148/183707), 115.06 MiB | 63.00 KiB/sReceiving objects:  44% (81151/183707), 115.08 MiB | 62.00 KiB/sReceiving objects:  44% (81161/183707), 115.11 MiB | 58.00 KiB/sReceiving objects:  44% (81173/183707), 115.19 MiB | 47.00 KiB/sReceiving objects:  44% (81183/183707), 115.22 MiB | 44.00 KiB/sReceiving objects:  44% (81184/183707), 115.23 MiB | 38.00 KiB/sReceiving objects:  44% (81185/183707), 115.24 MiB | 32.00 KiB/s
 
It started happening on (I think) all new builds after some time. Not just one agent.
 
This clone usually takes 1 minute (https://dev.azure.com/dnceng-public/public/_build/results?buildId=131726&view=logs&j=61a52f3a-cec1-5bff-8c02-d8ba2c8bed99&t=a25c6909-5dd7-54ad-ee4f-b38644d21392)
 
Does someone know who owns these and what can be done here?

**Comment by riarenas** [comment]
I'm suspecting some sort of general problem with GitHub. There are a couple of code mirroring builds which run in different agents that are also timing out or taking more than 45 minutes to clone repos: https://dev.azure.com/dnceng/internal/_build/results?buildId=2084349&view=results
https://dev.azure.com/dnceng/internal/_build/results?buildId=2084361&view=results

**Comment by riarenas** [comment]
Also, in yet another completely different pool, it took 20 minutes to clone the dotnet/versions repo (which is tiny) in https://dev.azure.com/dnceng-public/public/_build/results?buildId=131915&view=logs&j=efb274cb-82e8-595f-8d22-6f4b39df6a80&t=69029e18-f3eb-53a4-03ed-b4cb9e9c645f

**Comment by michellemcdaniel** [comment]
Yeah, they are reporting a degradation: https://www.githubstatus.com/incidents/00km0kwpz23b

**Comment by AlitzelMendez** [comment]
closing as this incident has been resolved.
