### ISSUE TITLE
msbuild.ps1/sh scripts shouldn't pass /m if the caller already passed it

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/arcade#12155]
- [ ] This issue is blocking
- [ ] This issue is causing unreasonable pain

Azure Pipelines use the eng\common\msbuild.{ps1,sh} scripts to invoke MSBuild. These scripts (via tools.{ps1,sh}) unconditionally add the `/m` argument to msbuild. They should not do so if the caller has already passed `/m` (or `-m` or `/maxCpuCount` or `/maxcpucount` or `-maxcpucount:50`, etc.).

It looks as though the invoker's arguments (including `-maxcpucount:50`) get appended to the unconditionally added `/m`, and it appears that msbuild takes the last argument passed and ignores the earlier ones, so the only operational problem here is confusion.

This issue was found when writing https://github.com/dotnet/runtime/pull/80409

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by chcosta** [comment]
@BruceForstall just so I understand this issue correctly; there's nothing blocking you, but it's ugly (confusing) to have a command line with multiple parameters that override each other.  Is that correct?

**Comment by BruceForstall** [comment]
Correct.

For example, looking at SendToHelix.binlog for coreclr__TestRunLogs_windows_x64_checked_jitstresss-isas-x86 for this run:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=137894&view=artifacts&pathAsName=false&type=publishedArtifacts

I see and invocation of msbuild of:
```
Command line arguments = "D:\a\_work\1\s\.dotnet\sdk\8.0.100-alpha.1.23061.8\MSBuild.dll -maxcpucount -verbosity:m /m /nologo /clp:Summary /v:minimal /nr:False /p:ContinuousIntegrationBuild=True /p:TreatWarningsAsErrors=false D:\a\_work\1\s/src/tests/Common/helixpublishwitharcade.proj /maxcpucount:55 /bl:D:\a\_work\1\s/artifacts/log/SendToHelix.binlog /p:TargetArchitecture=x64 /p:TargetOS=windows /p:TargetOSSubgroup= /p:Configuration=Checked /logger:D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23059.1\tools\net8.0\Microsoft.DotNet.ArcadeLogging.dll"
```

Which includes:
```
-maxcpucount /m /maxcpucount:55 
```

I added the last one, and the core msbuild scripts appear to have added the first two. Luckily, mine, at the end, overrides the first two (without error or warning, even).

**Comment by chcosta** [comment]
Thanks Bruce.  I completely agree that it's ugly and confusing and could be better.   I'm pretty sure it was the original design to do it that way just for simplicity's sake.  Given that this isn't blocking anything, I'm going to move this out of FR and allow triage to determine how best to address this.

**Comment by michellemcdaniel** [comment]
Triage: it sounds like this causes a little confusion, but works as designed: we use the last /maxcpucount on the command line, which would be the one that the user supplies. Closing this issue
