### ISSUE TITLE
Apple OSs: Publishing build artifacts failed with an error: Not found PathtoPublish: /Users/runner/work/1/s/artifacts/log/

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/arcade#12176]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=132037

### Build leg reported

CoreCLR  Product Build OSX arm64 release / Install native dependencies

### Pull Request

https://github.com/dotnet/runtime/pull/80434

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false
 }
 ```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Additional information about the issue reported

Lots of Apple OSs failing in the Publish leg with the same error:

```
Publishing build artifacts failed with an error: Not found PathtoPublish: /Users/runner/work/1/s/artifacts/log/

```

Example PRs that had this issue:

https://github.com/dotnet/runtime/runs/10571511570
https://github.com/dotnet/runtime/pull/80392/checks?check_run_id=10585813017

**Comment by riarenas** [comment]
Isn't this https://github.com/dotnet/runtime/issues/80428?

**Comment by MattGal** [comment]
Also related: https://github.com/dotnet/arcade/issues/11740 .  Note this is hosted macos machines running dotnet/runtime's `eng/install-native-dependencies.sh` script so there's not much we can do either.

**Comment by riarenas** [comment]
It is indeed a failure to install openssl: https://dev.azure.com/dnceng-public/public/_build/results?buildId=132037&view=logs&j=0fd811be-702d-513b-8268-d884b4628722&t=a2027c81-cb68-5e61-f611-daf47663e39a&l=565. Closing this as duplicate.
