### ISSUE TITLE
Determine ownership of dotnet/arcade-services components

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#12182]
This work is dependent on output of https://github.com/dotnet/arcade/issues/12180 and must be completed after it.

We need to identify where all components are used and whether their ownership remains with the DncEng team or is moved to the ProdCon team. Achieve some form of written/recorded consensus on this division before starting moves, although since our teams remain close this can remain somewhat fluid.

- For each component, make an initial guess at which team will own the component (dnceng or prodcon).
  The general rubric is:
    - Dependency Flow, BAR, and Darc functionality will be owned by the ProdCon team
    - Components used by or related to dotnet-helix-machines, dotnet-helix-service, or dotnet/arcade will be owned by DncEng team
- When completed the list of ownership should be added to this issue and any relevant work items for moving sources / Azure objects should be appended in the "Required for Epic" section of the https://github.com/dotnet/arcade/issues/12178 epic.

**Comment by tkapin** [comment]
The table in the parent epic says this is complete. Are there any captured results?

**Comment by tkapin** [comment]
@MattGal - to wrap up on this, was there any outcome of this captured or it has not been started yet? Cheers!

**Comment by MattGal** [comment]
> @MattGal - to wrap up on this, was there any outcome of this captured or it has not been started yet? Cheers!

I believe there has been no outcome, but this is more of a question for @garath.  Given the time frame of when I created it and subsequent events, I'm fine with just closing the issue and letting you do whatever you like.

**Comment by missymessa** [comment]
@tkapin @dkurepa Do you think there's still work that needs to be done here? I think this was covered via the Ownership Alignment epic.

**Comment by missymessa** [comment]
I'm going to close this issue. Think this has been covered by the Ownership Alignment epic.
