### ISSUE TITLE
The VMR readme and TPN template files should not be in the eng/bootstrap folder

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/arcade#12187]
The VMR readme and TPN template files should not be in [eng/bootstrap](https://github.com/dotnet/dotnet/tree/main/eng/bootstrap).  This bootstrap folder contains artifacts used to bootstrap the source-build.  It is not intended for artifacts used to bootstrap the VMR.  Having these files located here confuses the intent of the folder.  It doesn't seem like these template files are needed in the VMR itself.  It feels like these better belong in a new https://github.com/dotnet/installer/tree/main/src/SourceBuild folder outside of the content.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
No release notes

**Comment by MichaelSimons** [comment]
cc @premun

**Comment by premun** [comment]
@MichaelSimons what about other VMR-ey things in the `content` folder?

Thinking about it more, I am a bit unclear on whether we shouldn't make a bigger split. We could have a pure SB-only content in `SourceBuild/content` - basically what would go in the tarball. We can have VMR things such as `eng/pipelines`, the `.devcontainer`, the READMEs, .. in `VirtualMonoRepo/content` and map it onto the root of the VMR too.

**Comment by MichaelSimons** [comment]
I consider the templates this issue is about to be different than the other content you mention.  The templates themselves should not be mirrored, rather the resulting output is what gets included.  Because of this, they do not belong in the content folder IMO because mirroring them as is will bloat the VMR.  Splitting the content that gets mirror as is across folders, e.g. `VirtualMonoRepo/content` and `SourceBuild/content` will be a source of confusion IMO because I speculate the justification on why certain content is in one versus the other will not be understandable by those not deeply engrained in the infra.

**Comment by MilenaHristova** [comment]
We decided to pass the paths to the templates as `--readme-template` and `--tpn-template` arguments to `vmr initialize` and `vmr update` and only regenerate those files if templates are provided. Then move them into the `src/VirtualMonoRepo` folder
