### ISSUE TITLE
Add coverage for the `eng/pack-sources.sh` script

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#12193]
### Context

As part of https://github.com/dotnet/source-build/issues/3112 we have added a script that exports the sources from the VMR in the form of an archive. The Linux distro partners depend on this as that's how they consume the VMR. We need to make sure this keeps working.

### Goal
We need to add coverage for this by using it in the CI - exporting the archive and building it. Specifics on how often and where to put this are to be determined.

**Comment by MichaelSimons** [comment]
One suggestion would be to alter some of the existing CI legs to run with the tarball.  For example the Fedora and CentOS offline legs should build with the tarball since that is how they build while Ubuntu would use the repo.
