### ISSUE TITLE
[WindowsAppSDK Maestro Instance] Geneva Monitoring system deteching PAT leak when using git commands 

### ISSUE THREAD

**Issue by kythant** [dotnet/arcade#12212]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

I got an ICM incident for a cred leak in WindowsAppSDK's instance of Maestro. It is being detected by the Geneva Monitoring system which is only active on WindowsAppSDK's instance. The core of the issue is when we run git commands to clone, the git PAT is being passed via command line args which Geneva thinks is a cred leak. 

This issue is similar to https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1973318
To fix this, we could use environment variables to pass in the PAT. Example: https://github.com/microsoft/azure-pipelines-agent/pull/3949/files

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by riarenas** [comment]
I think the right way to think about this change would be:

*  Apply your PR to your instance of maestro
*  Let this run for a while, to make sure that both the service is still healthy, and other monitoring tools are fine with these variables being present in the environment
* Contribute the change back to the .NET maestro.

**Comment by michellemcdaniel** [comment]
Taking conversation offline
