### ISSUE TITLE
Add baseline files to the VMR

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#12238]
With the new vmr scan-binary-files and vmr scan-cloaked-files operations, we have the ability to see all binary and cloaked files that are currently in the VMR, so we're notified, in case we want to remove them.
In case we don't, we want to have a way of saying it's ok for these files to be in there.
We want to introduce a file to the VMR that will have a list of these allowed files.
The files in the list can either be a full path to the file, or have some wildcards (*) in them to reference multiple files

### Release Note Description
Introduce a list of baseline files to the VMR

**Comment by dkurepa** [comment]
The PR has been merged. The vmr-*-scan commands now expect a path to the baseline file, which is a simple txt file that has a simple list of allowed binary files in the vmr

**Comment by premun** [comment]
This is now complete, will follow with https://github.com/dotnet/arcade/issues/12372
