### ISSUE TITLE
Remove image windows.10.arm64 for Helix-machine

### ISSUE THREAD

**Issue by v-zheyan** [dotnet/arcade#12255]
Windows.10.arm64 will meet EOL at 2023-02-01, we will remove it after 1/25.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Remove image windows.10.arm64 for Helix-machine

**Comment by MattGal** [comment]
This is done, rolled out yesterday.
