### ISSUE TITLE
RCA: Cannot login to Maestro.Web after Jan 18 deployment

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#12268]
Please fill out the root cause analysis [Azure Boards work item](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_workitems/edit/4266), and then close this issue and the Azure Boards work item.

Filling it out promptly after resolving an issue ensures things are fresh in your mind.

For help filling out this form, see the [Root Cause Analysis](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/133/Root-Cause-Analysis).

**Comment by chcosta** [comment]
@dkurepa, can you make a first pass at filling out the RCA and then we'll get @alexperovich and @ChadNedzlek to chime in  with additional thoughts?  Does that sound reasonable?

**Comment by dkurepa** [comment]
I added everything I new and did leading up to the deployment

**Comment by chcosta** [comment]
@alexperovich , can you add your thoughts on best practice or how we can / should prevent this from occurring again?

**Comment by alexperovich** [comment]
I don't have anything more to add to the discussion in the work item. A simple status endpoint that is monitored by app insights and checked during scenario testing would have caught this in staging.

**Comment by garath** [comment]
> A simple status endpoint that is monitored by app insights and checked during scenario testing would have caught this in staging.

Only if a scenario test exercised login, right?

**Comment by alexperovich** [comment]
nope, the status endpoint can just round trip a guid through data protection to ensure it works.

**Comment by ChadNedzlek** [comment]
Yup, it could just do something like 
```csharp
var pizza = "ABCDEFG";
var pizzaBites = Encoding.Utf8.GetBytes(pizza);
var roundPizza = _protector.Unprotect(_protector.Protect(pizzaBytes));
if (pizza != Encoding.Utf8.GetString(roundPizza)) {
  throw InvalidOperationException();
}
```

We'd probably want to make it a bit more robust (and have the status endpoint return something like a json blob that looks something like:
```json
{
   "keys": "Key configuration invalid",
   "azureDevOpsConnection": ""
}
```
and return 200 if everything is fine, and a 500 if it's not (so that simple probe work, but we can get more details for debugging/status pages/notifications)

**Comment by garath** [comment]
Ah, gotcha. Then the emphasis is on the "this scenario test does not yet exist".
