### ISSUE TITLE
Add internal "windows.vs2022preview.scout.amd64" build image

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#12262]
The image `windows.vs2022preview.scout.amd64.open` exists, but no internal equivalent.  Mirror this image so teams needing "bleeding edge" VS can build against internal. 

### Release Note Description
Add internal windows.vs2022preview.scout.amd64 build image

**Comment by MattGal** [comment]
Image generated and verified to be deployed via https://helix.int-dot.net/#1ESHostedPoolImagesWestUS-Int-rg-Internal-Windows.  Should be available for use by afternoon of 1/25/2023

**Comment by Tanya-Solyanik** [comment]
@MattGal  - my experimental build had passed - https://github.com/microsoft/winforms-designer/pull/4864. Thank you!

**Comment by MattGal** [comment]
Thanks for confirming!
