### ISSUE TITLE
Create monitoring solution for darc publishing

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#12284]
As a follow up for https://github.com/dotnet/arcade/issues/11694, we should have some type of monitoring to verify that darc publishing is functioning properly. Basically, dnceng should know that there is a problem before our customers. 

I talked to Premek about this, and he is going to think about a solution as part of his FR rotation next week. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description

Added monitoring for Darc publishing so that the dnceng team is alerted when package publishing fails

**Comment by premun** [comment]
I have looked at this and I think the easiest, least-maintenance heavy and quick solution would be adding an email notification from AzDO when the **[Maestro Build Promotion](https://dev.azure.com/dnceng/internal/_build?definitionId=750&_a=summary)** fails.

We can make it mail to the "FR Bot Notification" channel and we should get there a thread for each time this fails. It will across all branches without code changes and we can then have a good idea which internal promotions have failed and need a re-run.

The only issue is that I am not able to "Get email address for channel" in Teams. I will ask someone with admin rights over the team to try.

**Comment by premun** [comment]
We could use the **Build Failure Notifications** channel too

**Comment by riarenas** [comment]
@premun Any thoughts about using the build monitor in arcade-services that opens issues? We've found that issues are much easier to investigate than emails.

**Comment by riarenas** [comment]
Issues like this one: https://github.com/dotnet/arcade/issues/12295. We can even use dotnet/dnceng as the assignee for the issues so they trigger all the machinery already configured to notify us of a mention to that group.

**Comment by premun** [comment]
@riarenas I was thinking about this too and I'd rather open this to a vote. Needing code, infra, extra build agent/time and backporting it everywhere seemed a lot for what we want. The ask is basically "make us learn about broken publishing asap".

But to be fair, we already have the infra in place and have to maintain it anyway, aand backporting would happen through Arcade automatically, so if you say you have better experience with issues, we could do that.

**Comment by riarenas** [comment]
@premun. Afaik we only need to add the configuration to arcade-services to know about these pipelines. I don't think we would need to backport code? 

We need to add the pipelines we care about to these sections https://github.com/dotnet/arcade-services/blob/b12e6b305a7db52892a5123fac94fae8fcb4bf1d/src/DotNet.Status.Web/.config/settings.json#L33. 

This shouldn't require onboarding the repo to anything. Maybe if we see a lot of devdiv-exclusive promotion failures we'd need to add a new service hook to monitor builds in devdiv as well, but we can start out with dnceng only imo and it would get us really far.

**Comment by premun** [comment]
Ah, it's configured this way. Yeah, then maybe adding the [Maestro Build Promotion](https://dev.azure.com/dnceng/internal/_build?definitionId=750&_a=summary) pipeline is a good solution for this.

**Comment by premun** [comment]
@ilyas1974 so in case darc publishing fails, there will be an FR issue opened in Arcade for the team to investigate.

**Comment by premun** [comment]
@riarenas Ilya was curious if we can/should test this. I imagine we're quite confident this will work?

Would it for instance report a cancelled stage if I did that manually?

**Comment by premun** [comment]
Okay, this seems to work well now
