### ISSUE TITLE
Helix Autoscale Json files being generated with bogus objects listed as "scalesets"

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#12296]
With the switch to the "Azure.ResourceManager.Compute" version of libraries, we're seeing two extra, definitely-not-scalesets objects showing up in every configuration file:

Example JSON entry:
``` json
  "ScaleSetIds": [
    "/subscriptions/<GUID>/resourceGroups/windows.amd64.vs2022.pre.open.svc-westus-v2-rg/providers/Microsoft.Compute/virtualMachineScaleSets/windows.amd64.vs2022.pre.open.svc-a-scaleset",
    "/subscriptions/<GUID>/resourceGroups/windows.amd64.vs2022.pre.open.svc-westus-v2-rg/providers/Microsoft.Insights/autoscalesettings/windows.amd64.vs2022.pre.open.svc-a-autoscale",
    "/subscriptions/<GUID>/resourceGroups/windows.amd64.vs2022.pre.open.svc-westus-v2-rg/providers/Microsoft.Network/virtualNetworks/network"
  ],
```

I noticed this during an investigation into failure to scale out in the Helix staging environment, though I don't actually know if it's relevant.  It definitely fills up the logs in app insights with bogus errors and makes the scaler more compute intensive.  

@garath FYI.

### Release Note Description
Not needed - fixing a bug with our autoscale implementation

**Comment by garath** [comment]
Gotcha. I'll take a look.

**Comment by MattGal** [comment]
I couldn't find the resourcetype in an existing enum but I think this sorts it.  Seems to be a transient issue as the exact same code doesn't do this for already deployed scale sets but every config file I checked in storage has extra junk

https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/29075

**Comment by MattGal** [comment]
Just made a more blunt version of this as a hotfix, and filed https://portal.microsofticm.com/imp/v3/incidents/details/363118376/home to ask for investigation.

**Comment by garath** [comment]
I [found a spot](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/src/DeployQueues/QueueManager.cs&version=GCafe68121a7eface93367def8f2367d3df974c2b2&line=617&lineEnd=617&lineStartColumn=105&lineEndColumn=167&lineStyle=plain&_a=contents) in the pre-net6 conversion where it filtered the deployed resources by type that I overlooked during the migration. 

The autoscale config files are written on two code paths. Matt's fixes have been on one, this is on the other, explaining the behavior we've seen. 

Fix in PR [29222](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/29222)

**Comment by MattGal** [comment]
This change rolled out last friday and addresses the issue, closing
