### ISSUE TITLE
Add SubscriptionId property to queue info json to enable placing storage accounts in correct subscriptions

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#12314]
The helix storage api supports sticking the storage accounts in subscriptions related to the queue being sent to, but this requires a SubscriptionId property to exist in the queue info.

Steps include:
- [x] Investigate how we provision new storage accounts today; if this uses the same princpals as the autoscaler it should "just work".
  
  - We'll need to add notes to add the "HelixProdService" managed identity through to all subscriptions used, 
  -  Add this identity as a reader on the sub, and an Storage Account Contributor on a new resource group "HelixManagedStorageAccounts"

- [x] Add SubscriptionId property to the info.json files (PR below)
- [ ] Monitor and deal with any fallout when this goes to production. 

### Release Note Description
Add extra data about Helix scaleset location to queue information

**Comment by alexperovich** [comment]
@MattGal fyi

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/29351 does the 2nd part.  I am checking on the 1st part now.

**Comment by MattGal** [comment]
Changes are in and look good from reading https://helixosautostaging.blob.core.windows.net/info/info.json.   Moving to rollout.  We'll need to monitor this as it rolls out but I have pre-loaded the existence of the

**Comment by MattGal** [comment]
This is rolled out and has created at least one new account in a different sub. I am going to submit jobs to all possible subscriptions to poke the system then close this.

**Comment by MattGal** [comment]
Seems to work.  However, the way we implemented transparent redirection seems like as it is can't work with drops, only results.

To address this, we'd need to duplicate the weird controller logic we have in the Storage API, add support for passing in repo and branch name to the storage API, then roll that out, then regenerate the swagger client, then plumb that through in storage upload API usage in Arcade.  I'm having some conversations with various folks to find out if this is needed.

**Comment by MattGal** [comment]
This cheap fix helped and is rolled out, but did not entirely separate storage concerns.  This has to do with how redirection for things like ".rt" and ".svc" queues works, and will require significantly more work than plumbing through a GUID to do, so is outside the scope of this FROps issue.

@missymessa  / @ulisesh the follow up work may be worth exploring as part of the spend epic?

**Comment by alexperovich** [comment]
> Seems to work. However, the way we implemented transparent redirection seems like as it is can't work with drops, only results.

The drop storage creation stuff in the sdk should be passing to the storage api the queue its sending too so we can create the storage in the right place.

**Comment by ulisesh** [comment]
Thanks Matt!! I'll monitor the new storage accounts and measure the impact.

**Comment by alexperovich** [comment]
Yup, right here the Helix SDK Passes the "targetQueue" into the storage api call https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/JobSender/StorageHelpers/ApiBlobHelper.cs#L25

**Comment by MattGal** [comment]
> Yup, right here the Helix SDK Passes the "targetQueue" into the storage api call https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/JobSender/StorageHelpers/ApiBlobHelper.cs#L25

That's the problem.  Runtime passes windows.10.amd64.open, for instance, and is redirected to windows.10.amd64.open.rt.  So, the drops will always be in the location of windows.10.amd64.open

**Comment by alexperovich** [comment]
ahh.... fiddlesticks.
