### ISSUE TITLE
Refactor the MSFT SDK content comparison tests into a separate pipeline

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#12338]
### Context 

During the official CI of the VMR, we also build the non-source-built MSFT SDK so that we can compare its contents with the SDK build by Source Build.

There are some problems with this such as:
- Adding extra build time onto the VMR build
- https://github.com/dotnet/arcade/issues/12099
- The VMR official pipeline then contains these non-source-build files

### Goal

We should extract the comparison tests into a separate pipeline which would run daily. The pipeline would grab the two latest runs - the VMR and the installer official build - and compare the SDKs from those.

This will probably require factoring the tests out of the smoke tests.

**Comment by premun** [comment]
Based on our discussion last week, we have looked into this more and we ended up with this proposed solution:

1. We will add a new pipeline, something like `source-build-content-validation`
2. This pipeline will either trigger when official VMR CI finishes or be scheduled to run daily/weekly - this is a subject to how YAML will let us connect the pipelines and also how long it will take to run
3. The pipeline will take the tag from the VMR CI which contains the installer SHA
4. It will look up the associated installer build, fail if we don't have one for that SHA (or possible get the other latest one?)
5. It will download artifacts from both the VMR and the installer builds - it can do all the different distros
6. It will git diff the contents and compare to the baseline

Notes:
- We think that triggering based on VMR's CI is better as the VMR build takes longer to finish and thus an installer build will be already done by then.
- Technically, it should be also possible to run this content validation as a last stage of the VMR CI build.
- Furthermore, we think it might be better to just make this pipeline a mix of YAML and bash. It seems like it would be an extra overhead to have a C# unit test for this that just calls `find` + `git diff` anyway but needs to be built and run.

@MichaelSimons will this cover the intended behaviour?

**Comment by MichaelSimons** [comment]
> @MichaelSimons will this cover the intended behaviour?

It all looks good except the last point.  I am not in favor of rewriting the tests in bash.  The use of a test framework and shared test infrastructure should be utilized IMO.  I would also prefer to see the tests remain as a configurable smoke test.

**Comment by premun** [comment]
Understood. We'll have a look at how to selectively run the smoke tests only then
