### ISSUE TITLE
Investigate workaround for python "requests" package issues

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#12335]
See https://github.com/dotnet/arcade/issues/12332 for how we're working around this.

I created this issue at @ilyas1974 's request.  A quick internet search indicates this isn't just us:

###  Original issue, closed already without fix:
https://github.com/psf/requests/issues/6331

### Others hitting the issue:
https://github.com/Toufool/Auto-Split/pull/193/files#diff-7a3ce58e9448657fa8ab45e91f4cd0ad00ddb48e18e9fdca941aa56ac1b15c2dR25 
https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/534

We should explore how we can harden against this and move forwards if needed, since the requests team does not seem to be likely to address it any time soon (there is some talk in the issue about simply removing this dependency.)

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description
Upgrade `requests` library (used by the Helix client) to latest version, 2.28.2.

**Comment by garath** [comment]
A merge request appears! [!29330](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/29330) 🐶

**Comment by garath** [comment]
Reverting. It broke in Mariner. [!29471](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/29471).
