### ISSUE TITLE
Work Item Processor failing to open arcade issues

### ISSUE THREAD

**Issue by michellemcdaniel** [dotnet/arcade#12331]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

It looks like the PAT might have expired for the WorkItemProcessor. See: https://dev.azure.com/dnceng/internal/_settings/serviceHooks > WorkItem Created service hook. We are getting

> Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

@AlitzelMendez's instructions in her PR [here](https://dev.azure.com/dnceng/internal/_git/dotnet-eng-wiki/pullrequest/28478?_a=files&path=/Documentation/BuildAnalysis/FirstResponderBuildAnalysis.md&anchor=**service-hook-delivery-alert**) has instructions for updating the service hooks (the instructions for the build analysis hook is identical to the instructions for the workitem processor hook, it's just a different service hook. They use the same azure queue.)

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by chcosta** [comment]
Chatted with Ali.  She confirmed, the secret was already rotated, but not updated in the service connection, it has now been updated.

**Comment by AlitzelMendez** [comment]
## Build Summary
:x: <a href="https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=147680">runtime-coreclr crossgen2</a>
<ul>
<b>Build failures:</b>
<table>
<td></td>
<td></td>
</table>


    <ul>Unique to this build: 5</ul>
    <ul>Repository know failure: 0</ul>
    <ul>Infrastructure known failures: 0</ul>
</ul>
<ul>
<b>Test failures:</b>
     <ul>Unique test issues: 32</ul>
     <ul>Test known issues: 0</ul>
</ul>
:x: <a href="https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=147683">runtime-coreclr crossgen2-composite</a>
<ul>
<b>Build failures:</b>
    <ul>Unique to this build: 5</ul>
    <ul>Repository know failure: 2</ul>
    <ul>Infrastructure known failures: 0</ul>
</ul>
<ul>
<b>Test failures:</b>
     <ul>Unique test issues: 1586</ul>
     <ul>Test known issues: 0</ul>
</ul>
:x: <a href="https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=147684">coreclr-release-outerloop-nightly</a>
<ul>
<b>Build failures:</b>
    <ul>Unique to this build: 0</ul>
    <ul>Repository know failure: 0</ul>
    <ul>Infrastructure known failures: 0</ul>
</ul>
<ul>
<b>Test failures:</b>
     <ul>Unique test issues: 0</ul>
     <ul>Test known issues: 0</ul>
</ul>
