### ISSUE TITLE
Failures during deploy metrics job in helix-service

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#12375]
- [X] This issue is blocking 
- This is blocking the build, and blocking the rollout for the repository
- [ ] This issue is causing unreasonable pain

As seen in [this build](https://dnceng.visualstudio.com/internal/_build/results?buildId=2100649&view=logs&j=1f6d8ccc-0f92-53cf-80a5-df07c5c41423&t=c50ca2c7-1e65-511b-9531-ada9b4a215d2&l=72)
```
  1:7>Project "D:\a\_work\1\s\src\Monitoring.HelixService\Monitoring.HelixService.proj" on node 1 (PublishGrafana target(s)).
     1>C:\Users\cloudtest\.nuget\packages\microsoft.dotnet.monitoring.sdk\1.1.0-beta.23074.2\Sdk\Sdk.targets(48,5): error MSB4062: The "MonitoringPublish" task could not be loaded from the assembly C:\Users\cloudtest\.nuget\packages\microsoft.dotnet.monitoring.sdk\1.1.0-beta.23074.2\Sdk\/../../../../artifacts/bin/Microsoft.DotNet.Monitoring.Sdk//net6.0/publish/Microsoft.DotNet.Monitoring.Sdk.dll. Could not load file or assembly 'C:\Users\cloudtest\.nuget\artifacts\bin\Microsoft.DotNet.Monitoring.Sdk\net6.0\publish\Microsoft.DotNet.Monitoring.Sdk.dll'. The system cannot find the path specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\a\_work\1\s\src\Monitoring.HelixService\Monitoring.HelixService.proj]
```

It seems this started with this change https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/commit/db2fb159ab908ff8f71758ef5e0a8c8e4ffe50a5 which brought a new version of the monitoring SDK.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [X] Internal Infrastructure Improvements
### Release Note Description
Fix path reference in Monitoring SDK

**Comment by garath** [comment]
Publish from arcade-services happened as expected. Here's the PR for helix-service to take it: [29313](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/29313)

**Comment by garath** [comment]
helix-service builds are green!
