### ISSUE TITLE
Document High Api Response Time Wiki 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#12378]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

How to investigate Helix API response time is high alert. 

Currently we don't really know what to take a look at when this grafana alert pops up. This doc will be a start to investigate these errors. 

The causes for this alert are numerous, I feel this should be an updateable doc, so everytime a new error pops up one can go and update the error in the doc and steps on how to resolve it. ( if that can be documented) 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by epananth** [comment]
Doc https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/999/-Alerts-Helix-API-Average-Response-Time

**Comment by epananth** [comment]
@garath has great ideas to improve this..

**Comment by ilyas1974** [comment]
Doc has been posted.
