### ISSUE TITLE
Incorrect conditions in eng/common/templates/job/job.yml

### ISSUE THREAD

**Issue by RussKie** [dotnet/arcade#12393]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

I believe the following conditions are incorrect:
* https://github.com/dotnet/arcade/blob/b40fa37a9086f204fea57539ee19a47b45062295/eng/common/templates/job/job.yml#L174
* https://github.com/dotnet/arcade/blob/b40fa37a9086f204fea57539ee19a47b45062295/eng/common/templates/job/job.yml#L195
* https://github.com/dotnet/arcade/blob/b40fa37a9086f204fea57539ee19a47b45062295/eng/common/templates/job/job.yml#L137 

Essentially, they imply the following: "**_Run the task if (argument == 'true' OR argument != '')_**" which is always true unless the argument is not specified at all. And this is super weird and unexpected. E.g., the following [configuration](https://github.com/dotnet/r9/commit/74092f23b82e6fae9f70101b183e20033d5364a2#diff-a39ace32dc21ed729a195e236341b9f75820f63d013def2b23d4a7f68b66d133) _still_ runs the tasks:
```yml
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      artifacts:
        publish:
          artifacts: false
          logs: true
          manifests: false
```
![image](https://user-images.githubusercontent.com/4403806/216203850-cee141c0-d026-4687-9570-56580c368679.png)

Only after I have completely removed the entries, it worked as expected:
```diff
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      artifacts:
        publish:
-         artifacts: false
          logs: true
-         manifests: false
```
![image](https://user-images.githubusercontent.com/4403806/216203797-fb810057-d557-4fe4-9a56-3147fcecbfee.png)

I am pretty sure the conditions are meant to be the following: "**_Run the task if (argument == 'true' OR argument == '')_**" - i.e., run the task only if 
- the argument isn't supplied - assume it's true, or
- the argument is true.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by MattGal** [comment]
Tossing into FR.

**Comment by ulisesh** [comment]
@RussKie thanks for reporting the problem. We believe the default should be false in the parameters aren't set, I implemented this changes in #12471

**Comment by MattGal** [comment]
@ulisesh  heads up this broke the official build by making it no longer download pipeline artifacts in arcade main.

**Comment by ulisesh** [comment]
The official build is now fixed
