### ISSUE TITLE
Create story for updating the Helix api generated client code

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#124]
The Helix Api Client code is currently generated by https://github.com/Azure/autorest
We need to figure out what the correct story is for either
  * Updating the checked in code when new changes are deployed to the helix api, or
  * Generating the code on-the-fly as part of the build of arcade

I am partial to leaving the code checked in and making something that will run the generator when new APIs are available to avoid adding node/npm to the build of arcade.

**Comment by markwilkie** [comment]
@alexperovich - fair, grin.  I guess I meant a documentation specific issue.  But to your point, this one works fine for that.

**Comment by markwilkie** [comment]
Follow up with Alex as this was being poked on already

**Comment by jcagme** [comment]
Is this something you own @alexperovich ?

**Comment by alexperovich** [comment]
I have things in the pipe for this, its just not super high priority. If we need the current code to get updated I can manually update it.

**Comment by jcagme** [comment]
Asking more to know who to assign this issue. Can this be assigned to you?

**Comment by alexperovich** [comment]
yes

**Comment by alexperovich** [comment]
This will be solved as part of dotnet/core-eng#3728. For that work we need generated clients for both repro-tool and BAR/Maestro, we will get Helix for free when that is done.
