### ISSUE TITLE
Upgrade NUnit to support VS2022

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#12416]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

According to [NUnit3TestAdapter release notes](https://docs.nunit.org/articles/vs-test-adapter/AdapterV4-Release-Notes) v4 is the version that support VS2022

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Upgrade NUnit to support VS2022

**Comment by garath** [comment]
PRs are dotnet/arcade-services#2213 and [!29318](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/29318)
