### ISSUE TITLE
Add parameter to yaml templates that allow running "public" builds in the internal project

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#1241]
Adding an "isPublic" parameter to the templates would let a dev specify that they want their build to be treated as a public build, even if they run in the internal project.

Related to one of the issues that @AdamYoblick faced when onboarding to Arcade from a private github repo detailed in #1150

**Comment by AdamYoblick** [comment]
Please add this to the eng\build.yml template as well. Even though this isn't part of the common folder, many customers will copy this straight from Arcade, so it would be nice to be able to pass it down.

I'm not sure how you're going to add it to vsts-ci.yml though. I tried specifying variables in the past and they do not resolve properly with delayed variable expansion. This is why you have to have the same IF expression over and over, you can't just use a single variable. It only seems to work as inputs to a template, not declared in the same yml. I think an env var is necessary, at least until you are inside of a template, but I could have been doing it wrong, you're welcome to try :)

**Comment by riarenas** [comment]
The way I see this going is that we need to add parameters to the templates under eng/common. Any yaml definition would be able to pass the parameter. Since it's not really a variable, there won't be the same issues that appear with variable evaluation.

There could be some issues if you're trying to decide the value of the "isPublic" parameter through a variable, but that would be strange, as it's a pretty special scenario, and you should know if your builds need it from the start.

**Comment by AdamYoblick** [comment]
Yes, but eng/build.yml isn't under eng/common, and many teams might still use that. So I was just suggesting that you put it on that template as well. :)

There needs to be some sort of solution for the vsts-ci.yml as well, since that expression occurs five times in that file as well.
