### ISSUE TITLE
Helix-machines fails to regen images when artifact changes

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#12410]
MattGal noticed that his PR [29281](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/29281), which definitely changes artifacts in images, did not cause new images to be generated in the build. 

Investigate!

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by MattGal** [comment]
Any update here?

**Comment by garath** [comment]
I didn't find anything suspicious and builds seem okay now. I'm closing this but of course let's reopen if there is more evidence.
