### ISSUE TITLE
Remove the last of Microsoft.Azure.KeyVault

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#12465]
There are still some traces of Microsoft.Azure.KeyVault that should be removed, coming in as dependencies of the packages we're using.

Part of: https://github.com/dotnet/arcade/issues/11852

**Comment by dkurepa** [comment]
PR: https://github.com/dotnet/arcade-services/pull/2218

**Comment by dkurepa** [comment]
The PR was merged, we should keep an eye on our staging environment Kusto table after staging deployment to see if everything is working

**Comment by dkurepa** [comment]
We had to roll back the original PR, since the staging Kusto was not getting any updates after the merge.

**Comment by dkurepa** [comment]
Second PR that should have the fix: https://github.com/dotnet/arcade-services/pull/2228 has been merged

**Comment by dkurepa** [comment]
Looks like the second PR worked. We deployed these changes to staging yesterday and the TimelineBuilds table has been getting updates regularly since then

**Comment by dkurepa** [comment]
Perhaps it'd be worth it if we created a Grafana alert that tells us if our Kusto infra is broken? Something simple like checking if there have been any updates in the last few hours should be enough. @garath what do you think?

**Comment by garath** [comment]
> Something simple like checking if there have been any updates in the last few hours should be enough.

Checking a negative is tricky (It might be normal that no builds run for a few hours). Especially if this is a problem that only happens "occasionally, when we change things". But it's certainly a better than nothing.

Is there some error message from the Telemetry service that positively indicates a problem?
