### ISSUE TITLE
Regular update for Helix-machines images sles-12/15-amd64 & 0001-com-ubuntu-pro-microsoft

### ISSUE THREAD

**Issue by v-zheyan** [dotnet/arcade#12486]
Regular base images update for sles-12/15-amd64 & 0001-com-ubuntu-pro-microsoft
https://dnceng.visualstudio.com/internal/_workitems/edit/4465

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Update regular Helix-machines base images

**Comment by MattGal** [comment]
@v-zheyan while I do see some Ubuntu ones, I don't see any SLES updates, can you clarify why this issue got created?  Also, are you going to handle the PR to update this?

**Comment by v-zheyan** [comment]
> @v-zheyan while I do see some Ubuntu ones, I don't see any SLES updates, can you clarify why this issue got created? Also, are you going to handle the PR to update this?

https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/29450?_a=files&path=/definitions/shared This is the commit, It completed now, I forgot to close the issue.

**Comment by MattGal** [comment]
> > @v-zheyan while I do see some Ubuntu ones, I don't see any SLES updates, can you clarify why this issue got created? Also, are you going to handle the PR to update this?
> 
> https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/29450?_a=files&path=/definitions/shared This is the commit, It completed now, I forgot to close the issue.

No problem.  this was just a base image update so it's fine to close, but in the future please put these into "Waiting for rollout" until they roll out to production.
