### ISSUE TITLE
Packaging build scripts/tools rather than copying them into repos

### ISSUE THREAD

**Issue by anurse** [dotnet/arcade#1248]
Was looking at on-boarding some ASP.NET "labs" repos as a first dip into Arcadifying ASP.NET and saw that we need to [copy a large quantity of files](https://github.com/dotnet/arcade-minimalci-sample/tree/master/eng/common) to build the `eng/common` directory. We've gone through this a number of times with our KoreBuild tools and found it *very* difficult to manage aligning these files cross-repo, which is why we dropped our KoreBuild template down to 5 scripts (https://github.com/aspnet/BuildTools/tree/master/scripts/bootstrapper), most of which just delegate down to a core PowerShell/Bash base script to fetch the tools and bootstrap the repo.

Given our history here, I worry that having to manage these files across our numerous repos (even after merging repos, we're going to have a number to manage) is going to bring back the pain we've experienced in the past. We had plenty of tools to "synchronize" toolsets across our repos in the past but found them quite brittle as the number of files became larger and larger, which is why we ended up trimming back to a minimal set of low-churn "bootstrap" scripts that fetch everything else. It's also very difficult to on-board new repos because the "templates" get out of date very easily and most people end up copying scripts from an existing repo (that may itself be out of date).

Has there been any discussion on how to improve this?

**Comment by markwilkie** [comment]
Indeed @anurse - there's been plenty of discussion.   <grin>

Check out https://github.com/dotnet/arcade/issues/1059 for the (documented) history here thus far, and the two issues that specify next steps.

**Comment by anurse** [comment]
Yes, @natemcmaster pointed me at that, but I didn't see anything in the linked new issues about actually reducing the content of the `eng/common` directory. Is that off the table? That would be unfortunate given that there's a lot in that directory (native CMake stuff, for example) that doesn't apply to our repos and having to have multiple copies of it seems brittle (since it would require changes in our repo when those files change, even though we never use them)

**Comment by jcagme** [comment]
A, somehow, easy approach for this could also be keeping an inclusion file where repos define which files they want synced into their repos. Issues with this:

1. `eng/common` won't be common anymore
2. Manual updates required when repos need file(s) in `eng/common`
3. We'd need a way to communicate repos that there are new things in `eng/common` so they decide if they need them or not

**Comment by tmat** [comment]
@jcagme I like the approach, but we should not allow to customize (include/exclude) every single file. 
Instead, let's define feature sets and let repos opt into each feature set. 

Something like: 
- `unix` - include all `.sh` scripts
- `native` - include support for native tools
- `yaml-templates` - include YAML templates
- `prodcon` - include support for meastro, helix, darc

All feature sets should be included by default. Repo can exclude those they don't need.

**Comment by jcagme** [comment]
Yeah, I like it. And for number 3, do we send an email to Arcade working group when there is a new thing feature?

FYI @markwilkie @mmitche

**Comment by tmat** [comment]
I would not expect these feature sets to change often, if ever. 
If we need to add a feature set we would announce it (we should have a DL for announcements, breaking changes, etc.). If repos do not do anything they just get potentially a few more files, since by default each feature would be on.

**Comment by natemcmaster** [comment]
What problem would we be solving by splitting into multiple "packages"? Based on my understanding of this proposal, it seems like the additional complexity isn't worth the benefits.

**Comment by tmat** [comment]
We don't mean to create packages nor to split anything. The only thing is that darc would not push all the eng\common files to all repos. Some repos do not need all of them. There is now 67 files... We should try to reduce the amount of stuff in eng\common in general, but it's not always possible.

The problem this is trying to solve is to remove clutter from repos that don't need these files. 
This shouldn't be a high priority, it's rather nice to have.

The complexity would be localized to darc configuration.

**Comment by natemcmaster** [comment]
I think I understand. What you're proposing is not what this issue is about then. You're not proposing to "Packaging build scripts/tools rather than copying them into repos". You're proposing to copy fewer files via some sort of filtering mechanism.

**Comment by tmat** [comment]
Correct. The conversation evolved in that direction.
