### ISSUE TITLE
Allow customise test log output location

### ISSUE THREAD

**Issue by RussKie** [dotnet/arcade#12485]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The solution I'm currently working consists of hundreds of projects (many of which a test projects). As a result the ./artifacts/logs folder gets filled with many *.log files ([example](https://dev.azure.com/dnceng/internal/_build/results?buildId=2107609&view=artifacts&pathAsName=false&type=publishedArtifacts)). It makes it difficult to see other logs produced during the build. 
The paths are configured here:
https://github.com/dotnet/arcade/blob/0978c75667efa5248017f7babab1ff966ab7e622/src/Microsoft.DotNet.Arcade.Sdk/tools/Tests.targets#L40-L68

I'm specifically interested in `ResultsStdOutPath`, and it doesn't look like the destination path can be easily customised (short of changing `ArtifactsLogDir` variable).

May we entertain the following tweak?

```diff
    <PropertyGroup>
      <_TestArchitecture>%(_TestArchitectureItems.Identity)</_TestArchitecture>
      <_ResultFileNameNoExt>$(MSBuildProjectName)_$(TargetFramework)_$(_TestArchitecture)</_ResultFileNameNoExt>

+     <TestResultsLogDir Condition=" '$(TestResultsLogDir)' == '' ">$(ArtifactsLogDir)</TestResultsLogDir>
    </PropertyGroup>

    <ItemGroup>
      <TestToRun Include="$(TargetPath)">
        <TargetFramework>$(TargetFramework)</TargetFramework>
        <TargetFrameworkIdentifier>$(TargetFrameworkIdentifier)</TargetFrameworkIdentifier>
        <TargetFrameworkVersion>$(TargetFrameworkVersion)</TargetFrameworkVersion>
        <TestRuntime>$(TestRuntime)</TestRuntime>
        <TestTimeout>$(TestTimeout)</TestTimeout>
        <Architecture>$(_TestArchitecture)</Architecture>
        <EnvironmentDisplay>$(TargetFramework)|$(_TestArchitecture)</EnvironmentDisplay>
        <ResultsFilePathWithoutExtension>$(_ResultFileNameNoExt)</ResultsFilePathWithoutExtension>
        <ResultsXmlPath>$(ArtifactsTestResultsDir)$(_ResultFileNameNoExt).xml</ResultsXmlPath>
        <ResultsTrxPath>$(ArtifactsTestResultsDir)$(_ResultFileNameNoExt).trx</ResultsTrxPath>
        <ResultsHtmlPath>$(ArtifactsTestResultsDir)$(_ResultFileNameNoExt).html</ResultsHtmlPath>
-       <ResultsStdOutPath>$(ArtifactsLogDir)$(_ResultFileNameNoExt).log</ResultsStdOutPath>
+       <ResultsStdOutPath>$(TestResultsLogDir)$(_ResultFileNameNoExt).log</ResultsStdOutPath>
        <TestRunnerAdditionalArguments>$(TestRunnerAdditionalArguments)</TestRunnerAdditionalArguments>
      </TestToRun>
    </ItemGroup>
  </Target>
```

This way I can alter my solution's config as this:
```xml
  <PropertyGroup>
    <TestResultsLogDir>$([MSBuild]::NormalizeDirectory('$(ArtifactsLogDir)', 'TestLogs'))</TestResultsLogDir>
  </PropertyGroup>
```
...and have tests in a subfolder:
![image](https://user-images.githubusercontent.com/4403806/217428562-57503a49-b60f-4484-870b-d587fddc2441.png)

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by michellemcdaniel** [comment]
Feel free to submit a PR to arcade and we'll review it!

**Comment by RussKie** [comment]
Is there some mechanism to have an experimental package published somewhere so I could test the change?

**Comment by riarenas** [comment]
> Is there some mechanism to have an experimental package published somewhere so I could test the change?

* Push a branch to the internal arcade mirror
* Trigger the official build pipeline for the branch https://dnceng.visualstudio.com/internal/_build?definitionId=6
* Add the build to the "general testing" channel and feed:
    ```powershell
    darc add-build-to-channel --id <your build's BAR id> --channel "general testing"
    ```
* That will push the package to the general-testing feed for consumption https://dnceng.visualstudio.com/public/_artifacts/feed/general-testing

**Comment by RussKie** [comment]
Thank you @riarenas, but it doesn't look like I have permissions:
```
PS > darc add-build-to-channel --channel "general testing" --id 167735
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      A '401 - Unauthorized' status was returned for a HTTP request. We'll set the retries amount to 0.
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Non-continuable HTTP 401 error encountered while making request against URI '_apis/build/builds/2119148/artifacts'System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 100
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to assign build '167735' to channel 'general testing'.
Microsoft.DotNet.DarcLib.DarcAuthenticationFailureException: Failure to authenticate: Response status code does not indicate success: 401 (Unauthorized).
   at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 119
   at Microsoft.DotNet.DarcLib.AzureDevOpsClient.ExecuteAzureDevOpsAPIRequestAsync(HttpMethod method, String accountName, String projectName, String requestPath, ILogger logger, String body, String versionOverride, Boolean logFailure, String baseAddressSubpath, Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 875
   at Microsoft.DotNet.DarcLib.AzureDevOpsClient.GetBuildArtifactsAsync(String accountName, String projectName, Int32 azureDevOpsBuildId, Int32 maxRetries) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 1287
   at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.ValidateAzDOBuildAsync(AzureDevOpsClient azdoClient, String azureDevOpsAccount, String azureDevOpsProject, Int32 azureDevOpsBuildId) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs:line 332
   at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.PromoteBuildAsync(Build build, List`1 targetChannels, IRemote remote) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs:line 232
   at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs:line 153
```

https://dnceng.visualstudio.com/internal/_build/results?buildId=2119148&view=results

**Comment by garath** [comment]
@RussKie Is Darc working for you in other cases? I didn't think that channel publish required special authentication, but I'll look into it.

**Comment by epananth** [comment]
May be your local Azdo PAT expired. Try to regenerate it and put it back in darc-authenticate -(https://github.com/dotnet/arcade/blob/main/Documentation/Darc.md#authenticate)

**Comment by epananth** [comment]
ah neva mind, it was your build. Looks like it is working now

**Comment by RussKie** [comment]
I can run other darc command, e.g.:
![image](https://user-images.githubusercontent.com/4403806/220460192-b95350ef-d4b9-4f3d-a399-c7dc4083c949.png)

...but I still can't run `add-build-to-channel`:
![image](https://user-images.githubusercontent.com/4403806/220460276-58e89145-8193-4ad4-8597-fb90158f2f0a.png)

**Comment by RussKie** [comment]
> May be your local Azdo PAT expired. Try to regenerate it and put it back in darc-authenticate -([`main`/Documentation/Darc.md#authenticate](https://github.com/dotnet/arcade/blob/main/Documentation/Darc.md?rgh-link-date=2023-02-21T21%3A10%3A22Z#authenticate))

I updated AzDO PAT, and still the same result....

**Comment by garath** [comment]
> I updated AzDO PAT, and still the same result....

Please try also updating the BAR / Maestro token.

**Comment by RussKie** [comment]
Alright, after regenerating both tokens it seemed to work. Thank you for the suggestions.
