### ISSUE TITLE
Recent MacOS updates seem to have removed mono-libgdiplus from installed brew packages

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#12495]
As seen here: https://github.com/dotnet/runtime/issues/32449#issuecomment-1422972660
(this comment is about runs on the `osx.1200.amd64.open` queue; we should check all the macoses)

From getting on a machine and checking, in this case `DCI-MAC-BUILD-311`, there's neither llvm/lldb (recent ask) nor mono-libgdiplus installed on the machine.

We should use helix scripts to check out the state of the machines we have and address this via DDFUN IcM ticket. 

@carlossanlop FYI.

**Comment by ulisesh** [comment]
This is what I found

osx.1200.amd64 all missing llvm
osx.1200.amd64.open all missing llvm
osx.13.amd64.open all good
osx.13.amd64 no machines
osx.1100.amd64.open 75 out of 114 machines missing llvm
osx.1100.amd64 all missing llvm

I'll create an IcM for DDFun to install llvm where it is missing

**Comment by MattGal** [comment]
> This is what I found
> 
> osx.1200.amd64 all missing llvm osx.1200.amd64.open all missing llvm osx.13.amd64.open all good osx.13.amd64 no machines osx.1100.amd64.open 75 out of 114 machines missing llvm osx.1100.amd64 all missing llvm
> 
> I'll create an IcM for DDFun to install llvm where it is missing

How about open SSL and mono-libgdiplus?  This issue was about libgdiplus.

**Comment by ulisesh** [comment]
I rerun the analysis and found only two machines where mono-libgdiplus missing and many without openssl@3. I don't think openssl@3 is required so I won't include it in the IcM for DDFun

Queue | Machine count | LLMV | mono-libgdiplus | openssl@1.1 | openssl@3
------- | -----------------| ------- | ------------------ | -------------- | ------------|
osx.1100.amd64 | 10 | 0 | 10 | 10 | 0
osx.1100.amd64.open | 18 | 0 | 18 | 18 | 1
osx.1200.amd64 | 10 | 0 | 10 | 10 | 10
osx.1200.amd64.open | 97 | 0 | 95 | 97 | 78

**Comment by ulisesh** [comment]
IcM: https://portal.microsofticm.com/imp/v3/incidents/details/367714177/home

**Comment by ulisesh** [comment]
DDFun installed mono-libgdiplus in both machines. Closing
