### ISSUE TITLE
DOTNET_INSTALL_DIR is corrupted if there are multiple dotnet CLI installs on the path

### ISSUE THREAD

**Issue by anurse** [dotnet/arcade#1251]
If the user has multiple dotnet CLIs on their path, the DOTNET_INSTALL_DIR value gets corrupted because this code doesn't properly select the *first* result:

https://github.com/dotnet/arcade-minimalci-sample/blob/a249ce8e79a9b71d5367d7bc59132121a7490d5b/eng/common/tools.ps1#L36-L38

On my machine, where the PATH search yields multiple results, DOTNET_INSTALL_DIR ends up being set to multiple directories:

![Incorrect DOTNET_INSTALL_DIR value](https://user-images.githubusercontent.com/7574/47938508-8529a500-dea1-11e8-96a7-520ec69a2571.png)

This causes the search for the correct SDK version to fail, and Arcade changes to use a repo-local `.dotnet` directory, which is definitely not what I wanted :).

A simple patch to add `| select -first 1` on the end fixes this for PowerShell. Haven't checked if this occurs in Bash as well.

**Comment by alexperovich** [comment]
That code is a bit odd. Why is it not just `(Get-Command dotnet.exe).Path` on windows and `command -v dotnet` on linux?

**Comment by markwilkie** [comment]
@anurse - thoughts on @alexperovich comment?

**Comment by anurse** [comment]
Sounds fine to me. I just want the script to find dotnet even when I have multiple on the PATH :)

**Comment by markwilkie** [comment]
The solution to #1253 likely makes this better.

**Comment by anurse** [comment]
Ping @chcosta @natemcmaster

**Comment by tmat** [comment]
I'll have a fix soon.
