### ISSUE TITLE
Arcade build broken

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#12512]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Looks like https://github.com/dotnet/arcade/commit/0978c75667efa5248017f7babab1ff966ab7e622 may have broken the arcade official build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2107675&view=results

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by ulisesh** [comment]
https://github.com/dotnet/arcade/pull/12504 should fix this

**Comment by michellemcdaniel** [comment]
@ulisesh did this fix the issue. Can we close this?

**Comment by ulisesh** [comment]
Yes, #12504 fixed this. Closing
