### ISSUE TITLE
Figure out data for S360 budget report

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#12514]
To be able to split the budget https://github.com/dotnet/arcade/issues/12493, we need to figure out a couple things: 

- [ ] Move dnceng services to another subscription (leave scalesets that are used by customers in the current sub). Work with @garath and @jonfortescue for this work, since PME may already be doing something in this space. 
- [ ] Work with Greg and Avi about accessing and working with the data.

**Comment by missymessa** [comment]
@Chrisboh do we still want to update the report right now, or will the Kusto query work for now until we get the subs reorganized to make the report easier to work with?

**Comment by Chrisboh** [comment]
I think a kusto query right now would be enough.  In the end I think having a powerbi dashboard will be good but lets build that dashboard when we think we are closer to having everything sorted.

**Comment by missymessa** [comment]
Going to put this in the backlog until we have all the subs sorted making this work a bit easier to do.

**Comment by missymessa** [comment]
Closing epic.
