### ISSUE TITLE
New Helix Queues to support customers

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#12536]
A few more queues are needed in Helix to fully support macOS 13

osx.13.arm64.appletv.open
osx.13.amd64.iphone.perf

A few additional queues to support perf
windows.11.amd64.pixel.perf
windows.11.amd64.galaxy.perf

### Release Note Description
New Helix queues

- osx.13.arm64.appletv.open
- osx.13.amd64.iphone.perf
- windows.11.amd64.pixel.perf
- windows.11.amd64.galaxy.perf

**Comment by ulisesh** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/29494

**Comment by ulisesh** [comment]
Waiting for tomorrow's rollout

**Comment by MattGal** [comment]
rollout completed.
