### ISSUE TITLE
Explore simplifying vsts-ci.yml by adding an intermediate template

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#1254]
from https://github.com/dotnet/arcade/pull/1243#issuecomment-435483740

> It would be nice if there was an easy way to do this in .vsts-ci.yml as well, that file is nasty with all the expressions. From talking to the yaml team, it sounds like this isn't high on their list.

> One workaround would be to just make vsts-ci.yml a simple wrapper and move all real logic into a ci.yml template, then everything could be controlled by simple variable inputs instead of duplicating the expressions over and over (similar to what is already done with build.yml and base.yml)

**Comment by markwilkie** [comment]
For now, the Arcade working group is thinking that we should leave things "inline" for now.  There are features coming (not soon), plus, it's hard when you keep adding more levels of indirection.

In addition, let's not forget that we're moving functionality into AzDO tasks.

@chcosta - could you link to the AzDO proposal for tasks?

**Comment by chcosta** [comment]
https://github.com/dotnet/arcade/blob/master/Documentation/Projects/DevOps/Tasks/OnePager.md
