### ISSUE TITLE
OneLocBuild parsing HTML files incorrectly resulting in over-localization of files

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#12559]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Per [this thread](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/778677?src=WorkItemMention&src-action=artifact_link), we need to add an LCI file to the generated LocProject.json so that those HTML files get parsed correctly. For whoever takes this, reach out to me for help if you have any questions.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Do not include in release notes.

**Comment by alexperovich** [comment]
https://github.com/dotnet/arcade/pull/12620

**Comment by alexperovich** [comment]
This has been merged, and once arcade flows to affected repos they will get lci files included.
