### ISSUE TITLE
Multi-solution build issues

### ISSUE THREAD

**Issue by anurse** [dotnet/arcade#1256]
FYI: This issue will likely block ASP.NET onboarding (cc @natemcmaster)

Most ASP.NET repositories are multi-solution repositories, or will be by the time Arcade is fully adopted. For example, I'm looking at on-boarding [aspnet/AspLabs](https://github.com/aspnet/AspLabs), which has the following layout (the `eng/common` directory is only present in my [WIP branch `anurse/arcade`](https://github.com/aspnet/AspLabs/tree/anurse/arcade)):

```
src/
	DotNetDiagnostics
		src/
			[projects]
		dotnet-monitor.sln
	Proxy
		src/
			[projects]
		Proxy.sln
	WebHooks
		src/
			[projects]
		WebHooks.sln
eng/
	common/
		...
	...
```

Arcade, by default, scans the root for solutions, which means I have to run the following command to build (PowerShell `Convert-Path` is to work around https://github.com/dotnet/arcade/issues/1255)

```
./eng/common/build.ps1 -build -projects "$(Convert-Path "./src")\*\*.sln"
```

This is awkward and has led to me just creating a top-level custom `build.ps1`, which I don't think is sustainable given the goal of aligning the build systems better :).

Perhaps having a well-defined pattern for multi-solution repos would be a good idea here. Some suggestions:

* Automatically scan for `src/*/*.sln` (or some other folder convention)
* Support a list of solutions in a top level MSBuild file

**Comment by weshaggard** [comment]
Today you can already specify the projects you want via Build.props, see https://github.com/dotnet/corefx/blob/master/eng/Build.props#L4. That should allow you to wildcard all your solutions if you want. Corefx just calls a root build.proj which we have as a traversal project as we don't actually use our solution files for building at the command line. We generally need to phase our builds (i.e. build ref, build src, build tests) where as our solutions have all the projects for a given library so there isn't a great way to cross the different options so we don't build the solutions from the command line.

**Comment by anurse** [comment]
> Today you can already specify the projects you want via Build.props, see [dotnet/corefx:eng/Build.props@`master`#L4](https://github.com/dotnet/corefx/blob/master/eng/Build.props#L4). That should allow you to wildcard all your solutions if you want.

Excellent, I'll take a look at this.

> Thanks @anurse. Any idea when you might be getting to this?

@natemcmaster would have more context on when we'll be onboarding more repos. I'm onboarding a small side-car (non-shipping) repo of prototype stuff we're considering for 3.0 (and beyond, or never ;)) right now.

**Comment by markwilkie** [comment]
@anurse - do you have what you need here so far?

**Comment by anurse** [comment]
Yeah, I think @weshaggard 's suggestion is working for us, I can close this.
