### ISSUE TITLE
Regular baseimages update for helix-machines

### ISSUE THREAD

**Issue by v-zheyan** [dotnet/arcade#12591]
Regular baseimages update for helix-machines which will be rolled out in 2023-02-22

PR link: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/29644?_a=files

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Regular baseimages update for helix-machines

**Comment by MattGal** [comment]
@v-zheyan since this is for tomorrow's rollout I'm putting it into the "Waiting for rollout" column.  Please include the PR that goes along with the change in the issue.
