### ISSUE TITLE
Create a cross-platform way to packing .nuspec files without relying /t:Pack

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#126]
We should either create -- or work with the NuGet team to create -- an cross-platform way to package a .nuspec file directly, without needing to go through the `/t:Pack` targets in Microsoft.NET.Sdk. So far, aspnet, roslyn, and corefx have all implemented a task to do this on their own, and we expect new repos building .nuspec files will need this task too.

Initially, I wrote and proposed an MSBuild task to pack .nuspec files. https://github.com/dotnet/arcade/pull/57. This was closed for now as we ran out of time to complete design and implementation that satisfies all potential consumers of this task.

Requirements:

 - Given a .nuspec file only, I should be able to pack it
 - Support variable replacement using the `$varName$` in the .nuspec
 - Support packing .nuspec files without NuGet.exe (cross platform support)
 - Support invoking the pack command from MSBuild without needing to create a dummy .csproj file to invoke /t:Pack

**Comment by adiaaida** [comment]
Closing because the parent Epic was closed. If you believe this issue should still be worked on, please re-open.
