### ISSUE TITLE
BAR SQL database not accessasble from Prague

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#12681]
Currently, the Prague team can't access the BAR database due to firewall settings.
Are things meant to be this way?

**Comment by garath** [comment]
I think I know what you are running into, and yes it is expected.

**Comment by tkapin** [comment]
Can we have an update on this? The BAR DB has to be reachable from Prague and I'd like to understand what needs to be done to do so. If this information is not suitable for public disclosure, let's have a follow-up in an AzDO issue. Thanks

**Comment by dkurepa** [comment]
I created a wiki page for the process: https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki?wikiVersion=GBwikiMaster&pagePath=/Product%20Construction/Accessing%20the%20BAR%20(BuildAssetRegistry)%20database&pageId=1009&_a=edit

**Comment by missymessa** [comment]
Epic issue closed. Kicking this back to be retriaged.

**Comment by missymessa** [comment]
@dkurepa was the workaround in the wiki sufficient?

**Comment by dkurepa** [comment]
yup, adding a firewall rule for your IP address does the trick. will close this, sorry
