### ISSUE TITLE
Monitor throttling errors after known issues reprocessing 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#12699]
We observed so  throttling errors after known issues reprocessed some builds (around 1500), this created a very high load, if this continue happening (get throttled)  we should:
- [ ] Add  wait-and-retry logic to AnalysisProcessor
- [ ] Control the insert of message of the AnalysisProcessor queue. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Avoid reprocessing same known issue

**Comment by AlitzelMendez** [comment]
We are still facing this problem significantly.
When we insert a message into build analysis queue, even if we skip most of the process, we do 1 call to azdo and 1 call to github, we should avoid inserted unnecessary messages

Example:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/6895254/231572149-a504022d-9229-4b74-81e6-1c4c613d080c.png">

This three are too close to have a meaningful change! and even though we are not going to reprocess them three times, we are doing call to github for each on them

**Comment by markwilkie** [comment]
Any thoughts on how to mitigate yet @AlitzelMendez ?

**Comment by AlitzelMendez** [comment]
The problem mostly comes from GitHub. We can:

1. Move one of our validations to skip some builds before a critical GitHub call, which should mitigate some of the problem.
2. Implement a retry-after so we retry the failing builds after the throttling period.
3. Control the speed at which we insert messages into the queue after a reprocess.

We are having problems with the 65k limit character which is causing us to retry the same build 10 times. This issue will be fixed next week and should help with this too, additionally I will go work on the first suggestion, targeting to have this on the next rollout.

Let’s see if things get better with these two changes; if we still face the problem, we can try more aggressive approaches like 2 and 3.

**Comment by AlitzelMendez** [comment]
The GitHub error has been fixed after this from build analysis side: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/30654

Doing one additional PR to avoid known issues been reprocessed when the error message didn't change: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/31219

After that we should be able to close this issue :)

**Comment by AlitzelMendez** [comment]
This look under control , not happening anymore, closing.
I will reopen it if necessary
