### ISSUE TITLE
The type initializer for 'Microsoft.TeamFoundation.DistributedTask.Pipelines.Yaml.PipelineParser' threw an exception

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/arcade#12700]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=183819

### Build leg reported

Build / CoreCLR  Product Build linux arm checked

### Pull Request

https://github.com/dotnet/runtime/pull/82623

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section)

 ```json
 {
    "ErrorMessage" : "The type initializer for 'Microsoft.TeamFoundation.DistributedTask.Pipelines.Yaml.PipelineParser' threw an exception",
    "BuildRetry": true,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Additional information about the issue reported

Affecting other builds too, and other PRs.

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[184182](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184182)|dotnet/runtime|Mono crossaot Product Build osx arm64 release|||
|[183797](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183797)|dotnet/runtime|windows-x64 release Runtime_Release ||dotnet/runtime#82560|
|[184162](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184162)|dotnet/runtime|Evaluate Paths||dotnet/runtime#82556|
|[183851](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183851)|dotnet/aspnetcore|Test: Blazor E2E tests on Linux|||
|[184183](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184183)|dotnet/aspnetcore|Source-Build (Managed)||dotnet/aspnetcore#46715|
|[183923](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183923)|dotnet/runtime|coreclr  Pri1 Runtime Tests Run R2R_CG2 linux arm64 checked|||
|[184197](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184197)|dotnet/sdk|Darwin_AoT_Tests Build_Release|||
|[184135](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184135)|dotnet/aspnetcore|Test: macOS||dotnet/aspnetcore#46819|
|[183953](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183953)|dotnet/runtime|Installer Build and Test coreclr  osx_x64 Release||dotnet/runtime#82635|
|[184160](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184160)|dotnet/runtime|windows-x86 release Runtime_Debug ||dotnet/runtime#82556|
|[184018](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184018)|dotnet/runtime|Libraries Test Run release mono linux x64 Debug||dotnet/runtime#81871|
|[183976](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183976)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  windows arm64 checked||dotnet/runtime#81924|
|[183796](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183796)|dotnet/runtime|windows-x86 release Runtime_Debug ||dotnet/runtime#82560|
|[183850](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183850)|dotnet/aspnetcore|Tests: Ubuntu x64|||
|[183985](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183985)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  osx x64 checked||dotnet/runtime#82630|
|[183867](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183867)|dotnet/roslyn|Correctness_Bootstrap_Build|||
|[184020](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184020)|dotnet/runtime|browser-wasm linux release Runtime_Release ||dotnet/runtime#81871|
|[184036](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184036)|dotnet/roslyn|VS_Integration_CoreHost_Debug||dotnet/roslyn#66899|
|[184041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184041)|dotnet/roslyn|VS_Integration_CoreHost_Debug||dotnet/roslyn#67043|
|[184186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184186)|dotnet/installer|Linux Build_Debian_Stretch_Debug_x64||dotnet/installer#15631|
|[184145](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184145)|dotnet/sdk|Ubuntu_20_04 Build_Release|||
|[184171](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184171)|dotnet/installer|Linux_Build_Arm64_Debug||dotnet/installer#15632|
|[183910](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183910)|dotnet/runtime|Libraries Test Run release coreclr windows x64 Debug||dotnet/runtime#82629|
|[184149](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184149)|dotnet/roslyn|Build_Unix_Debug||dotnet/roslyn#67045|
|[184173](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184173)|dotnet/installer|Linux_Build_Arm64_Debug|||
|[183734](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183734)|dotnet/runtime|Evaluate Paths||dotnet/runtime#82615|
|[183690](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183690)|dotnet/runtime|Libraries Test Run checked coreclr linux x64 Release||dotnet/runtime#82610|
|[183665](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183665)|dotnet/runtime|Libraries Test Run release coreclr windows x86 Release||dotnet/runtime#82609|
|[183841](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183841)|dotnet/sdk|Windows_NT_FullFramework Build_Debug|||
|[183680](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183680)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  windows x86 checked||dotnet/runtime#81484|
|[183807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183807)|dotnet/roslyn|Correctness_Rebuild||dotnet/roslyn#66768|
|[183755](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183755)|dotnet/runtime|Installer Build and Test coreclr  freebsd_x64 Release||dotnet/runtime#82612|
|[183781](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183781)|dotnet/runtime|Mono crossaot Product Build windows x64 release||dotnet/runtime#79169|
|[184012](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184012)|dotnet/runtime|Mono crossaot Product Build linux x64 release||dotnet/runtime#82615|
|[183819](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183819)|dotnet/runtime|Libraries Build linux arm64 Debug||dotnet/runtime#82623|
|[184023](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184023)|dotnet/runtime|linux-armv6 Release AllSubsets_Mono |||
|[184158](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184158)|dotnet/runtime|Evaluate Paths||dotnet/runtime#82556|
|[184137](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184137)|dotnet/aspnetcore|Tests: Ubuntu x64||dotnet/aspnetcore#46819|
|[184003](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184003)|dotnet/roslyn|Test_Windows_CoreClr_UsedAssemblies_Debug||dotnet/roslyn#67020|
|[183751](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183751)|dotnet/runtime|Installer Build and Test coreclr  FreeBSD_x64 Release||dotnet/runtime#82617|
|[184042](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184042)|dotnet/aspnetcore|Source-Build (Managed)||dotnet/aspnetcore#46328|
|[184019](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184019)|dotnet/runtime|linux-x64 debug Libraries_AllConfigurations ||dotnet/runtime#81871|
|[184034](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184034)|dotnet/roslyn|Source-Build (Managed)||dotnet/roslyn#66899|
|[183995](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183995)|dotnet/aspnetcore|Build: Linux Musl x64||dotnet/aspnetcore#46791|
|[184048](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184048)|dotnet/roslyn|Determine_Changes|||
|[183774](https://dev.azure.com/dnceng-public/public/_build/results?buildId=183774)|dotnet/runtime|Evaluate Paths||dotnet/runtime#82619|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|46|46|

**Comment by lewing** [comment]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=184131&view=results in runtime-assets had the same failure and there are community reports

**Comment by AndyAyersMS** [comment]
Also (in my same pr that hit the above): https://dev.azure.com/dnceng-public/public/_build/results?buildId=183820&view=results

**Comment by ericstj** [comment]
Here it is in installer as well: https://dev.azure.com/dnceng-public/public/_build/results?buildId=184201&view=results

**Comment by AlitzelMendez** [comment]
in case you can see the impacted builds without waiting for the hourly update: https://helix.dot.net/BuildAnalysis/SearchReport?issueId=12700&repository=dotnet%2Farcade

**Comment by AlitzelMendez** [comment]
IcM: https://portal.microsofticm.com/imp/v3/incidents/details/370113588/home

**Comment by AlitzelMendez** [comment]
closing as this is not happening anymore.
