### ISSUE TITLE
Add check to sign.proj that ensures you have some item to sign

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#1271]
CoreFx added a target to validate that there were items being passed to the signtool see https://github.com/dotnet/corefx/blob/master/eng/Signing.props#L2. This should probably generalized and added to arcade as an extra validation step. The last thing we want to happen is someone mess-up the output and nothing gets signed or published.

**Comment by JohnTortugo** [comment]
The SignTool has a [check for that condition](https://github.com/dotnet/arcade/blob/7e178f9f6c01d445f5561366e0b6e969dd5b85fe/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs#L121); but I agree that it would be nice to have a separate step to validate things.

**Comment by weshaggard** [comment]
That is just a warning and easily missed in a large build log. I added that extra error case to make sure that we fail the build when we didn't sign files.
