### ISSUE TITLE
Bump XBox GDK to October 2022 Update 2

### ISSUE THREAD

**Issue by steveisok** [dotnet/arcade#12717]
I'd like to have the GDK installed on the build agents upgraded to the October 2022 Update 2 version. This would apply to the `windows.vs2022.amd64` image.

**Comment by MattGal** [comment]
I accidentally made a dupe, changes from https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/29816 should roll out tomorrow.

**Comment by MattGal** [comment]
This rolled out today.

**Comment by steveisok** [comment]
Thanks @MattGal !
