### ISSUE TITLE
Cannot figure out which package causes signtool error

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1272]
As the binaries in our packages shift, we occasionally hit this error:

>  error : Couldn't determine certificate name for signable file: D:\src\obj\ContainerSigning\A4D4A10DA67E52C590D8A0A921AD01F790E2D1C79EB95A7DECE30640057AEAB1\Banana.dll

From the error message, I can't figure out which vsix, zip, or nupkg contained "Banana.dll". It would be nice if the error message could also contain the name of container so I can figure out what is pulling this file.

**Comment by tmat** [comment]
Agreed. More precisely, the error should list _all_ packages that contain the file since there might be multiple.
