### ISSUE TITLE
code mirroring for dotnet/source-indexer not working

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#12734]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The past two commits in the https://github.com/dotnet/source-indexer repository have not been automatically mirrored. We should investigate why.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by riarenas** [comment]
I wonder if it's the maestro webhook that somehow got disabled in the repo? @mmitche or @alexperovich would you mind adding dnceng-admin to the admins list for ongoing maintenance of stuffs?

**Comment by mmitche** [comment]
The webhook didn't exist. I've added it back.

**Comment by riarenas** [comment]
thanks @mmitche! I'll close this for now.
