### ISSUE TITLE
Non-SDK projects that import arcade targets fail to determine an SDK version

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1276]
A project that does not use the NET SDK (e.g. some corefx projects), but use some of the arcade targets tend to eventually import Versions.targets and fail because of https://github.com/dotnet/arcade/pull/1234

@tmat I'm assigning this to you.  We probably can't require the Net sdk be used in each and every project that uses any of arcade.  Maybe this check should be a conditional based on whether the NetCoreSDKVersion property is empty or not?

**Comment by tmat** [comment]
Sorry about that. Forgot we have projects that do not import .NET Core SDK and only tested it on repos that use the SDK.

> Maybe this check should be a conditional based on whether the NetCoreSDKVersion property is empty or not

yup, that'd be the right fix.

**Comment by jcagme** [comment]
To check I understand this issue. Currently nothing is broken since @mmitche reverted the change and the purpose of this issue is to have in mind that when we check for the required .Net version there are projects that don't use it?

**Comment by tmat** [comment]
We need to put the (corrected) check back. Let me do that.
