### ISSUE TITLE
Blob publishing error in dotnet-templating

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#12765]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Dotnet-templating blob publishing is failing

|Build   |  Blob error |   Which channel is it publishing to? | 
|-------------|---------|-------| 
| https://dev.azure.com/dnceng/internal/_build/results?buildId=2124598&view=results  |  Yes      | .NET 8.0.1xx SDK', '.NET 8.0.1xx SDK Preview 2 | 
|  https://dev.azure.com/dnceng/internal/_build/results?buildId=2124697&view=results  | Yes | .NET 8.0.1xx SDK', '.NET 8.0.1xx SDK Preview 2'|   
| https://dev.azure.com/dnceng/internal/_build/results?buildId=2125517&view=results | Yes | .NET 8.0.1xx SDK', '.NET 8.0.1xx SDK Preview 2 |
| https://dev.azure.com/dnceng/internal/_build/results?buildId=2102931&view=results  | Yes | .NET 8.0.1xx SDK', '.NET 8.0.1xx SDK Preview 2 | 
| https://dev.azure.com/dnceng/internal/_build/results?buildId=2104054&view=results |  Yes | .NET 8.0.1xx SDK Preview 1', '.NET 8.0.1xx SDK| 
| https://dev.azure.com/dnceng/internal/_build/results?buildId=2105218&view=results | Yes | NET 8.0.1xx SDK Preview 1', '.NET 8.0.1xx SDK | 
| https://dev.azure.com/dnceng/internal/_build/results?buildId=2127179&view=results | Yes |  .NET 8.0.1xx SDK', '.NET 8.0.1xx SDK Preview 2 | 

NOTE: all the builds are green on retry

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by epananth** [comment]
All these builds publish to more than one channel. 

NET 8.0.1xx SDK, .NET 8.0.1xx SDK Preview 1, .NET 8.0.1xx SDK Preview 2 all them publish to dotnet8 feed - https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json

**Comment by epananth** [comment]
So publishing to blob fails for the first time and then passes. I think it cos we are publishing to the same feed twice, so the first time it fails and the second time it passes but the build reports a failure

**Comment by epananth** [comment]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/47157394/222584130-4cc2adc9-3267-4805-8434-4afc6146c437.png">

**Comment by epananth** [comment]
If we publishing to the same feed more than once, then we probably publish only once? 

cc: @mmitche

**Comment by mmitche** [comment]
It's because the same build is going to multiple channels. @vlada-shubina It looks like the default channel set up for templating is odd:

(4678) https://github.com/dotnet/templating @ release/8.0.1xx-preview2 -> .NET 8.0.1xx SDK
(4428) https://github.com/dotnet/templating @ main -> .NET 8.0.1xx SDK
(4651) https://github.com/dotnet/templating @ release/8.0.1xx-preview1 -> .NET 8.0.1xx SDK Preview 1
(4692) https://github.com/dotnet/templating @ release/8.0.1xx-preview2 -> .NET 8.0.1xx SDK Preview 2

Any idea why the preview2 branch is publishing to two different channels?

**Comment by vlada-shubina** [comment]
> It's because the same build is going to multiple channels. @vlada-shubina It looks like the default channel set up for templating is odd:
> 
> 
> 
> (4678) https://github.com/dotnet/templating @ release/8.0.1xx-preview2 -> .NET 8.0.1xx SDK
> 
> (4428) https://github.com/dotnet/templating @ main -> .NET 8.0.1xx SDK
> 
> (4651) https://github.com/dotnet/templating @ release/8.0.1xx-preview1 -> .NET 8.0.1xx SDK Preview 1
> 
> (4692) https://github.com/dotnet/templating @ release/8.0.1xx-preview2 -> .NET 8.0.1xx SDK Preview 2
> 
> 
> 
> Any idea why the preview2 branch is publishing to two different channels?

Publishing should be done from main only. 
Can we check when and by whom preview2 subscription was created? 

@YuliiaKovalova could you please disable preview2 subscription? Thank you

**Comment by mmitche** [comment]
@vlada-shubina Thanks. I deleted it.

**Comment by epananth** [comment]
the channel is deleted. So I am going to close this one.
