### ISSUE TITLE
 Unusual wait times on osx.1200.amd64.open queue

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#12763]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

Since 02/28 EOD we started experience problems processing jobs on osx.1200.amd64.open. The queue is getting constantly backed up.

We are actively investigating what could be causing this problem, so far we observed a huge increase on failing workitems which is causing a lot more retries of this workitems and also longer runs per workitem, we are still looking if this is a regression test that is running in our queues or is a problem with xharness. 

[osx.1200.amd64.open  grafana](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/queues/queue-monitor?orgId=1&refresh=30s&var-QueueName=osx.1200.amd64.open&var-UntrackedQueues=%22osx%22,%20%22perf%22,%20%22arm%22,%20%22arcade%22,%20%22xaml%22,%20%22appcompat%22&from=now-2d&to=now)

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by steveisok** [comment]
https://github.com/dotnet/runtime/pull/82915 went in as I noticed MacCatalyst and iOSSimulator work items were being retried an excessive amount.  Unclear if this is the only issue, but it'll at least help.

**Comment by EgorBo** [comment]
I feel like it could be me in https://github.com/dotnet/runtime/pull/81635 - I had an issue in codegen that led to timeouts in some platforms in a lot of tests - I've just fixed it so sorry if that was the case 😞

**Comment by AlitzelMendez** [comment]
@premun update: _"talking to the runtime team as this is probably a regression in the maccatalyst runtime (not iOS/tvOS simulators but another „mobile“ platform)"_

**Comment by premun** [comment]
@AlitzelMendez I think we can close this issue. Steve paused the test legs causing this so the queue of itself is now okay.
