### ISSUE TITLE
Enable Build Analysis/Known Issues for other dotnet repos

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#12813]
We should enable Build Analysis/Known Issues for all repos in dotnet that [qualify](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/Introduction.md#how-do-i-get-it) to use it so that more folks can benefit from using Build Analysis and Known Issues. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by epananth** [comment]
Closing this for now, we are going to take care of it case by case basis.
