### ISSUE TITLE
Auditing Grafana Alerts 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#12829]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Auditing Grafana Alerts to guarantee that
- Are useful: Get trigger when expected
- Has proper instructions/documentation

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by AlitzelMendez** [comment]
The main focus of this work and the reason I am driving this is that we have a significant number of alerts for which we don't know what action to take. In the past, there was always someone on the team who would know what to do with a specific alert, but now we need to ensure that anyone can handle it or at least take the first steps when an alert gets triggered.



### **Alerts that needs doumentation to be updated/created/fixed**
The following alerts doesn't have an actionable documentation or the documentation is not clear for someone that doesn't have the full context of the service

| Alert | Name | Production: Hits 2 months|  Production: Hits Ever |
| --- | --- | --- |---|
|[54aa0d7e647e46ff9e880bf6ae532b99<sup>1<sup>](https://github.com/search?q=repo%3Adotnet%2Farcade+54aa0d7e647e46ff9e880bf6ae532b99&type=issues)|[Autoscale: Minutes to scale-up from zero machine alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/queues/queue-monitor?tab=alert&viewPanel=62&orgId=1&editPanel=62) | 13 |168|
|[44aff3c937c042caa09f821ae923c26c](https://github.com/search?q=repo%3Adotnet%2Farcade+44aff3c937c042caa09f821ae923c26c&type=issues)|[Azure quota usage for west us 2](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/quota/azure-quota-limits?editPanel=13&tab=alert&orgId=1)|8|15|
|[d2356d84cf3e43ea952d81de941eaa76](https://github.com/search?q=repo%3Adotnet%2Farcade+d2356d84cf3e43ea952d81de941eaa76&type=issues)|[On-Prem Machines Heartbeating By Queue alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/queueOverview/on-premises-helix-queue-status?editPanel=9&tab=alert&orgId=1)|7|137|
|[24cae10d9eca44079e7cf3d47f148497](https://github.com/search?q=repo%3Adotnet%2Farcade+24cae10d9eca44079e7cf3d47f148497&type=issues)|[Helix API Average Response Time](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/arcadeAvailability/service-availability?editPanel=19&tab=alert&orgId=1)|4|23|
|[6fe0b7b34a004f0bad0064a42f9b9135<sup>1<sup>](https://github.com/search?q=repo%3Adotnet%2Farcade+6fe0b7b34a004f0bad0064a42f9b9135&type=issues)|[Build Analysis: Exceptions and Errors Alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/buildAnalysis/build-analysis?editPanel=46&tab=alert&orgId=1)|2|13|
|[a5641c4a6d8e4e499f1710aa8386d81b<sup>1<sup>](https://github.com/search?q=repo%3Adotnet%2Farcade+a5641c4a6d8e4e499f1710aa8386d81b&type=issues)|[Servicing Builds Running in R&D Pools Alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/historical/backend-status?editPanel=67&tab=alert&orgId=1)|2|7|
|[6213d3c5ce9a46278343bf075798e46f<sup>2</sup>](https://github.com/search?q=repo%3Adotnet%2Farcade+6213d3c5ce9a46278343bf075798e46f&type=issues)|[Helix AutoScaler Service Stopped Running](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/arcadeAvailability/service-availability?editPanel=29&tab=alert&orgId=1)|1|30|
|[d70761f3c7e84a6380e44943a2e583e6<sup>1<sup>](https://github.com/search?q=repo%3Adotnet%2Farcade+d70761f3c7e84a6380e44943a2e583e6&type=issues)|[Apple device failure rate alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/mobileDevices/mobile-devices?editPanel=16&tab=alert&orgId=1)|1|6|
|[116ed29b46934330b0aa31e843807b32](https://github.com/search?q=repo%3Adotnet%2Farcade+116ed29b46934330b0aa31e843807b32&type=issues)|[On-Prem Machines Heartbeating alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/queueOverview/on-premises-helix-queue-status?editPanel=6&tab=alert&orgId=1)|1|5|
|[6179576701874a7abc440a574cf636d0](https://github.com/search?q=repo%3Adotnet%2Farcade+6179576701874a7abc440a574cf636d0&type=issues)|[Helix API availability](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/arcadeAvailability/service-availability?editPanel=18&tab=alert&orgId=1)|1|5|
|[2ca5b0285c1e4179b621f916b8b5e75f](https://github.com/search?q=repo%3Adotnet%2Farcade+2ca5b0285c1e4179b621f916b8b5e75f&type=issues)|[High Number of Machines With Low Disk Space in Some Queue(s)](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/queues/queue-monitor?editPanel=84&tab=alert&orgId=1)|0|14|
|[7f6435eff89c4306ad11684c461533c5](https://github.com/search?q=repo%3Adotnet%2Farcade+7f6435eff89c4306ad11684c461533c5&type=issues)|[Data Migration: Migration Queue Depth alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/historical/backend-status?editPanel=40&tab=alert&orgId=1)|0|13|
|[f391698eca5c411aa51ad5e3ba37c72e<sup>1<sup>](https://github.com/search?q=repo%3Adotnet%2Farcade+f391698eca5c411aa51ad5e3ba37c72e&type=issues)|[Helix Service Fabric exception count alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/historical/backend-status?editPanel=10&tab=alert&orgId=1)|0|5|
|[e2be2ec3e22e46d28730bab54ff8fa77](https://github.com/search?q=repo%3Adotnet%2Farcade+e2be2ec3e22e46d28730bab54ff8fa77&type=issues)|[Azure quota usage for west us](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/quota/azure-quota-limits?editPanel=12&tab=alert&orgId=1)|0|3|
|[fd20a5c2ffca4e89940bc33e00e7aada](https://github.com/search?q=repo%3Adotnet%2Farcade+fd20a5c2ffca4e89940bc33e00e7aada&type=issues)|[Maestro / BarViz alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/arcadeAvailability/service-availability?editPanel=39&tab=alert&orgId=1)|0|3|
|[b87805b575d141e4b2b6d258f5e3a79e](https://github.com/search?q=repo%3Adotnet%2Farcade+b87805b575d141e4b2b6d258f5e3a79e&type=issues)|[Maestro Failed Requests/Hour alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/arcadeAvailability/service-availability?editPanel=41&tab=alert&orgId=1)|0|2|
|[9a64e127211c4352b38b4ce1e1ddf5ce](https://github.com/search?q=repo%3Adotnet%2Farcade+9a64e127211c4352b38b4ce1e1ddf5ce&type=issues)|[SQL database size too high](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/historical/backend-status?editPanel=74&tab=alert&orgId=1)|0|1|
|[b50b57fa7d1840438da5232711af4485](https://github.com/search?q=repo%3Adotnet%2Farcade+b50b57fa7d1840438da5232711af4485&type=issues)|[Azure quota usage for east us](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/quota/azure-quota-limits?editPanel=24&tab=alert&orgId=1&from=now-7d&to=now)|0|1|
|[4782665d50764ecb9dbd5d929e017115](https://github.com/search?q=repo%3Adotnet%2Farcade+4782665d50764ecb9dbd5d929e017115&type=issues)|[SQL Cleaner alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/historical/backend-status?editPanel=20&tab=alert&orgId=1)|0|0|
|[fb8faaf7600740f98a1c2db076cd1712](https://github.com/search?q=repo%3Adotnet%2Farcade+fb8faaf7600740f98a1c2db076cd1712&type=issues)|[source.dot.net Availability](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/arcadeAvailability/service-availability?editPanel=16&tab=alert&orgId=1)|0|0|

<sup>1</sup> Incomplete documentation: The documentation is in there but it's incomplete </br>
<sup>2</sup> Query is not totally related with the alert

### **Alert that needs documentation to be migrated to our wiki**
These alerts have a good coumentation, clear and actionable but is on the Alert issue instead of our wikis, this documentation needs to be move to our wiki

| Alert | Name | Hits ever |
| --- | --- | --- |
|[d2dd705a6c724ed68fcf6955561c06dd](https://github.com/search?q=repo%3Adotnet%2Farcade+d2dd705a6c724ed68fcf6955561c06dd&type=issues)|[DotNetEng Status Failed Requests/Hour alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/arcadeAvailability/service-availability?editPanel=44&tab=alert&orgId=1)| 7 |
|[5aa74f27ef6445ce9d3d8d3d382e7e35](https://github.com/search?q=repo%3Adotnet%2Farcade+5aa74f27ef6445ce9d3d8d3d382e7e35&type=issues)|[Servicing jobs in R&D queues alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/historical/backend-status?editPanel=65&tab=alert&orgId=1)| 7 |



### **Alerts that "probably" are not alerting when they should**
Alert that should be triggered under certains scenarios and is not happening, the query needs to be reviewed

| Alert | Name | 
| --- | --- |
|[763d449c7cd747a786373befe76ad19b](https://github.com/search?q=repo%3Adotnet%2Farcade+763d449c7cd747a786373befe76ad19b&type=issues)|[Queue Insights Failures alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/queueInsights/queue-insights?editPanel=4&tab=alert&orgId=1&from=now-90d&to=now)|
|[65dba2e7b92b4c4794316a09e22f918d](https://github.com/search?q=repo%3Adotnet%2Farcade+65dba2e7b92b4c4794316a09e22f918d&type=issues)|[Helix Service Fabric MSI Exceptions (For Alerts only) alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/historical/backend-status?editPanel=64&tab=alert&orgId=1)|

### **Alerts that are not alerting to GitHub**
The following alert gets triggered in Grafana and the status can be seen on the dashboard but we are not alerted in github
| Name |
| --- | 
|[SLA - Wait Time Threshold Alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/iXElCVcnz/waitingtimemetricstest?editPanel=6&tab=alert&orgId=1)|
|[Test Queues: SLA WorkItem Wait Time Alert alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/iXElCVcnz/waitingtimemetricstest?editPanel=4&tab=alert&orgId=1)|
|[Work Items Waiting Time Is Too High (Build Pools) alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/introduction/introduction?editPanel=4&tab=alert&orgId=1)|
|[Work Items Waiting Time Is Too High (Test Queues)](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/introduction/introduction?editPanel=10&tab=alert&orgId=1)|

**Comment by markwilkie** [comment]
I love this!

cc/ @shawnro

**Comment by missymessa** [comment]
Nice! Does the list also include the ones that Ilya said were disabled because they weren't useful in their current state? (I think it was the on-prem alerts)

**Comment by AlitzelMendez** [comment]
> Nice! Does the list also include the ones that Ilya said were disabled because they weren't useful in their current state? (I think it was the on-prem alerts)

yes, I think all of them are on: Alerts that are not alerting to GitHub 😄

**Comment by AlitzelMendez** [comment]
thanks for taking a look to the list. I am going to start working on this!

As there are a lot of alerts, I will be working on them on different issues, and I will be updating this issue with links to the new issues! :)
