### ISSUE TITLE
Publishing in staging broken

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#12849]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

When sleet was removed, the support for using a storage account key was also removed. A SAS uri should now be used. This broke dotnet-release, which relied on such behavior. Fix should be relatively simple. Change their feed override tokens to SAS URis, and it should work as expected.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
@epananth can you follow up please?

**Comment by mmitche** [comment]
This has been completed.
