### ISSUE TITLE
Get S360 Process Sorted

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#12858]
Get S360 Process Sorted

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by dougbu** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-eng-wiki/pullrequest/30080

**Comment by dougbu** [comment]
Completed w/ https://dev.azure.com/dnceng/internal/_git/dotnet-eng-wiki/commit/b8c2343f1c4c07901fb12defa6a72629de353d54

Will add a follow up issue to refine the process after we've used it for a while&hellip;
