### ISSUE TITLE
Get Rollouts Sorted

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#12866]
Follow up with Ricardo and Ali about rollouts, see if we can start getting other team members involved (possibly dogfood some documentations on how to do rollouts) so more folks know how to do it. Additionally, determine if we can have this process handled by the FR person to reduce randomization on Ricardo/Ali during rollouts. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by riarenas** [comment]
Here is what we have written about this: https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/831/Rollout

And here is the operations process for this:
https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/984/Generating-Rollout-PR-and-Release-Notes

**Comment by missymessa** [comment]
Rollouts have been occurring on their regular cadence. We can refine the process as necessary.
