### ISSUE TITLE
Make updating NuGet packages "self-service"

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#12876]
As part of our re-evaluation of work .NET Eng Services will be handing, we have decided to create a pipeline that our customers can use to add NuGet packages to the dnceng-public project. 

This issue is to track the work to set up this pipeline and the "how to" documentation needed for customers to use it.

**Comment by garath** [comment]
Is Auditing a concern? If so some thought will be needed to make sure that is covered. Azure Pipelines do record, for example, who triggered the build, but that is incidental and "auditability" should really be more deliberate.

**Comment by missymessa** [comment]
This work was completed: https://github.com/dotnet/arcade/blob/main/Documentation/MirroringPackages.md
