### ISSUE TITLE
New Secret Owners

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#12894]
- [ ] Update our secrets in our KVs to reflect owners who are currently on the team. 
- [ ] Come up with a process for updating secrets in the event we have personnel changes so that it's known how to handle this work in the future. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by garath** [comment]
Secrets should be inventoried by .vault-config YAML and secret manager. I think _most_ of dnceng secrets are there. Probably some aren't and are instead still in the original "owned-by" tag system. Those should instead be moved to secret-manager YAML. I don't think there are any situations for individual-owned secrets.

**Comment by missymessa** [comment]
Epic issue closed. Let's retriage.

**Comment by missymessa** [comment]
Secret Manager should've made this obsolete. Closing.
