### ISSUE TITLE
Gather helix information for cloud test meeting

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#12931]
1. List of queues that we have
2. Average number of machines per queue
3. Workitems processed daily, overall and by queue

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by AlitzelMendez** [comment]
For the cloud test meeting we want to be prepared for any questions that might arise about our volume/usage and needs. That’s why I did a short investigation based on three key aspects of our work: load, machines, and work items.

## Overall data
1. How much work do we do every day: On average, we run the work of 700-800 days per day on weekdays
*Load in a month*
![DaysOfWork](https://user-images.githubusercontent.com/6895254/227059115-b8879678-2cfc-4182-90c1-ef866a1542c8.png)

1. Machines (How Many Machines Do We Need To Run Our Work): On average, we run between 1800 and 2200 machines during the day on weekdays, with peaks of up to 3000 machines at some points.
*Machines distribution during a day*
![Daily](https://user-images.githubusercontent.com/6895254/227059198-eca30658-4f9e-464e-bbc4-9afdc129af70.png)
*Machines distribution during a month*
![Montly](https://user-images.githubusercontent.com/6895254/227059230-7bb948cb-1ffd-4b05-99e9-160f036bb955.png)

1. Work Items (How Many work items do we process every day): On average, we process around 500,000 - 900,000 work items per day on weekdays.
*Workitems in a month*
![workitems](https://user-images.githubusercontent.com/6895254/227059338-f7388fa5-be0a-49e1-8de7-ea096b601c6f.png)

## Queue data

 We have approximately 419 queues (in the last month I found work items in around 140 queues). Some queues are "duplicated" as we have them in more than one subscription. 

Here are some interesting facts about our queues:

- The queue with the highest load in work items is ubuntu.1804.amd64.open.rt (23.5%).
- The queue with the highest load in machine time is ubuntu.1804.amd64.open.rt (760 days).
- The queue with the highest number of machines is ubuntu.1804.armarch.open (600).
- Most of the queue usually have less that 100 machines 


### Top 5 queues with high load in machine time during 7 days
| Queue name | Days |
| -- | -- |
ubuntu.1804.amd64.open.rt | 760 days
windows.amd64.server2022.open.rt | 580 days
windows.10.amd64.open.rt | 383 days
ubuntu.1804.armarch.open | 362 days
windows.10.amd64.open | 246 days
osx.1200.amd64.open  | 243 days

## Top 5 queues with more machines
| Queue name | Machines |
| -- | -- |
ubuntu.1804.armarch.open  | 600
windows.11.arm64.open | 580
ubuntu.1804.amd64.open.rt  | 460
windows.10.amd64.open | 360
windows.amd64.vs2022.pre.open  | 350
windows.amd64.server2022.open.rt | 343

### Top 5 queues with more work items
| Queue name | Percentage of work items coming from this queue |
| -- | -- |
ubuntu.1804.amd64.open.rt  | 23.5%
ubuntu.1804.armarch.open | 15%
osx.1200.amd64.open | 8.5%)
windows.10.amd64.open.rt | 7%)
windows.amd64.server2022.open.rt | 4.2%
ubuntu.1804.amd64.open.svc | 3%

**Comment by chcosta** [comment]
@AlitzelMendez , all of the above data is related to the "open" queues, is that correct? or is there some mingling of open vs internal workloads here?
