### ISSUE TITLE
Add MSYS2 and some of its packages to Windows image

### ISSUE THREAD

**Issue by directhex** [dotnet/arcade#12938]
I need MSYS2 added to the windows.vs2022.amd64 image, plus ideally a handful of packages - this is part of the regular AzDO Hosted pool, but seems not to be present on our pool's images.
Right now, I'm using:

```
(New-Object System.Net.WebClient).DownloadFile('https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe', 'msys2.exe')
.\msys2.exe -y -oC:\  # Extract to C:\msys64
Remove-Item msys2.exe  # Delete the archive again
C:\msys64\usr\bin\bash -lc ' '
C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -S msys/make msys/ninja msys/cmake msys/diffutils'
```

on a per-build basis. We should probably bake it in, to avoid the repeated downloads & extra point of failure.

(These instructions are pretty much direct from the MSYS2 website page on CI integration, https://www.msys2.org/docs/ci/#other-systems )

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Added MSYS2 to windows.vs2022.amd64 images

**Comment by riarenas** [comment]
@directhex since you mention that this is available in the microsoft hosted images, could you give the `1es-windows-2022` image a try in your build? Those images are mostly the same as the hosted public images. 

They do have some older versions of packages and tools stripped for compliance purposes by 1ES so there's a chance you might hit other blockers, in which case it would make sense to add it to our pool providers.

**Comment by directhex** [comment]
OK, looks like MSYS2 is present on that image, with no packages. So I can remove the "install MSYS2" call & keep only the "install make, ninja, cmake, diffutils" call. Is that the better choice, or is using windows.vs2022.amd64 with MSYS2 and those packages added?

**Comment by riarenas** [comment]
I think we'd normally want everything you need to be in the base image, but given our recent reshuffle I'm not sure when we'd be able to address it.

I'd say for now use whatever image needs less additional downloads during the build until we can triage this.

**Comment by directhex** [comment]
:+1: my build is green with `1es-windows-2022` and:

```
        - powershell: |
            C:\msys64\usr\bin\bash -lc ' '
            C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
            C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -S msys/make msys/ninja msys/cmake msys/diffutils'
          displayName: Install MSYS2 packages (GNU Make and related)
```

**Comment by ilyas1974** [comment]
@directhex, is there any additional action for .NET Eng Services on this issue?

**Comment by directhex** [comment]
If y'all are happy with me downloading packages on every single build, then I'm happy.

**Comment by mmitche** [comment]
Yeah I think this is an improvement. Certainly an improvement over downloading a nightly build of msys2

**Comment by AlitzelMendez** [comment]
this rolled out Yesterday, closing the issue but feel free to reopen if is not working as expected
