### ISSUE TITLE
Darc `get-build` command duplicate output bug

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#12933]
The darc `get-build` command has a bug when you run it with the `--repo` and `--commit` parameters:
The command will output the same build twice for some reason
This only happens when using these parameters, using the `--id` parameter works fine

### Release Note Description
Fix Darc `get-build` command duplicate output bug when using `--repo` and `--commit` parameters

**Comment by ali-turan7** [comment]
this is the PR https://github.com/dotnet/arcade-services/pull/2256.

**Comment by ali-turan7** [comment]
The issue is resolved by deduplicating the result list.
