### ISSUE TITLE
Autoscale: Minutes to scale-up from zero machine alert in reunion queues

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#12930]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

This alert: [Autoscale: Minutes to scale-up from zero machine alert](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/queues/queue-monitor?tab=alert&viewPanel=62&orgId=1&refresh=30s) has been getting triggered by reunion queues by two reasons:

```
"Operation could not be completed as it results in exceeding approved standardDAv4Family Cores quota. Additional details - Deployment Model: Resource Manager, Location: westus2, Current Limit: 200, Current Usage: 180, Additional Required: 44, (Minimum) New Limit Required: 224...
```
and 
```
Allocation failed. Please note that allocation for this subscription is constrained to a set of clusters, which may be out of capacity. Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance. To remove the cluster constraint, please contact the subscription administrator or Microsoft Support.
InternalDetail: [Details of predominant failure]
Microsoft.Windows.Azure.GCM.Allocator.AllFabricsFailedToAllocateException: No compute stamps available for allocation of 55a8b063-78ab-4c4d-9a1b-c666333ccb21.
Constraints applied: SubscriptionPinning, VMSize.
```

In order to fix this we should provide more Da_v4 quota to the subscriptions or change the SKU used to something they already have more capacity with.

There are some discussion trying to decide what is going to be done with this queues, so this is a tracking issue.  

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Not needed

**Comment by AlitzelMendez** [comment]
I am creating this PR to stop monitoring `.reunion` queues until this get sorted: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/30233

@markwilkie do you have any thoughts about stop monitoring the scaling of these queues until this gets sorted? the reason is that we can't take any action on the alert and this is becoming very noisy.

**Comment by ilyas1974** [comment]
@markwilkie have you had a chance to look at this issue?

**Comment by ilyas1974** [comment]
Per conversation with customer, we are going to remove these queues from Helix. I have created https://github.com/dotnet/dnceng/issues/470 to track that work.
