### ISSUE TITLE
Migrate TestAppFactory to Microsoft.DotNet.Internal.Testing 

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#12952]
Currently, `TestAppFactory` is a part of the `Microsoft.DotNet.Web.Authentication.Tests`. Since this is a Test project, it doesn't get published, but we need to consume `TestAppFactory` from a package that is published. Migrating it to `Microsoft.DotNet.Internal.Testing ` feels like a natural fit

### Release Note Description
Not interesting for our customers

**Comment by garath** [comment]
Just curious. What project wants to consume this?

**Comment by dkurepa** [comment]
The pr has been merged
