### ISSUE TITLE
Microsoft.Internal.DncEng.CommandLine.Secret does not execute (missing appsetting.json)

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#12969]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Our prescribed way for [setting](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/553/How-to-create-a-new-bot) up bots is to install this tool as a global tool.  When you do so, however, it gives you this error

> Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The expected physical path was 'C:\Users\chcosta\.dotnet\tools\.store\microsoft.internal.dnceng.commandline.secret\4.1.137\microsoft.internal.dnceng.commandline.secret\4.1.137\tools\net7.0\any\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.DncEng.CommandLineLib.DependencyInjectedConsoleApp.RegisterConfiguration(IServiceCollection services)
   at Microsoft.DncEng.CommandLineLib.DependencyInjectedConsoleApp.RunAsync(IEnumerable`1 args)
   at Microsoft.Internal.DncEng.CommandLine.Secret.Program.<Main>(String[] args)

It *appears* that this was broken when the tool was migrated from a zip that was passed around, to a dotnet tool, see [this](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/22908) PR.

This is blocking any user that needs to setup a bot.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Unblock dotnet tool version of "secret" commandline by enabling appinsights logging via appsettings.json

**Comment by chcosta** [comment]
After changing the settings file to be optional, the CommandLineLib library complained that it was missing an "instrumentationkey" so I went the route of creating an appinsights resource and including the appsettings file.  @ChadNedzlek , any concerns with that path?

**Comment by garath** [comment]
An empty instrumentation key will also work, as the libraries interpret it as "don't try to log telemetry." 

IMO I suggest leaving the instrumentation key blank and not setting up any new resources. We didn't use it before, and there is nothing motivating actual adoption (yet?). So this would be the smallest change to get things working again.

**Comment by chcosta** [comment]
what's the downside to including the key?  i feel like these things are always useless... until they aren't useless.  if you think there's a ton of overhead or cost associated with collecting the appinsights data, then i'm happy to omit it.  If the cost is minimal, then inclusion seems reasonable to me.  The secret tool itself doesn't log any telemetry, but it's built upon a base library that does.

**Comment by garath** [comment]
The cost is only the data that gets ingested, and data storage is very cheap, so the cost is negligible. I have no problem turning it on.

**Comment by chcosta** [comment]
resolved with https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/30334
