### ISSUE TITLE
Disable commit description auto-linking to dnceng internal issues

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#1298]
(Moving from https://dnceng.visualstudio.com/internal/_workitems/edit/103 because this isn't AzDO feedback anymore--it's actionable by us.)

> I "follow" some issues, and it's spammy when some unrelated commit that happens to contain "`#123`" in its title (referring to some GitHub issue) gets attached to issue 123 here, for example.
> 
> Maybe disabling the auto linkage altogether isn't necessary to fix this, but it's the solution that seems straightforward.

Matt Cooper told us this is a per-repo setting, so we have to disable them. (I did what I could and disabled it for the source-build repo.)

> I assume this is because you're mirroring GitHub code into Azure Repos. There's a setting on each repo to disable work item linking. For example https://dnceng.visualstudio.com/internal/_settings/repositories?_a=options, see the first setting under "Work Item Management".

@chcosta @markwilkie

**Comment by Chrisboh** [comment]
Closing from Core-eng as we moved this to arcade

**Comment by dagood** [comment]
This is Arcade, I'm guessing some UI wasn't clear?

**Comment by markwilkie** [comment]
Closing in favor of https://github.com/dotnet/arcade/issues/1298  (sorry for the confusion)

**Comment by markwilkie** [comment]
Oh that's weird....  we used the new gh "transfer" feature and it looks like a file hard link...

**Comment by dagood** [comment]
Clicking a link to the old issue like https://github.com/dotnet/core-eng/issues/4540 redirects me to this issue. My guess is you're looking at it through ZenHub, and their iframe is being redirected without being very clear about it. I guess it'll take them a bit to polish in response to the new feature. 🙂

**Comment by dagood** [comment]
@chcosta @natemcmaster Do you mind taking a look at this? Always disappointing to get a notification thinking one of my issues have been responded to, then see it's just a commit. (I think it's always been from an aspnet repo so far.)

**Comment by chcosta** [comment]
I don't think it's difficult to write some rest api script to disable this option for all of the internal repos.  The problem is, that seems like a very temporary fix as there's nothing enforcing the setting or applying it to new repos.

**Comment by dagood** [comment]
I'd probably end up doing that if I had the permissions. If I'm the only person who cares, I'd be fine rerunning it if I get annoyed again. (As long as someone doesn't end up actually using this feature... they'd have to let me know.)

**Comment by chcosta** [comment]
I have no problem with that.  Unless anybody else does, I'll look at getting you permissions

**Comment by dagood** [comment]
Awesome, thanks. 🙂

**Comment by chcosta** [comment]
I gave @dagood permissions to modify repo options (more specifically I gave Contributors permissions).  @dagood is intending to manage this setting for the repos.  If that proves not to be sustainable we can work with DevOps to find a better solution.

**Comment by dagood** [comment]
@mmitche can we add this to the playbook of creating a new repo? Just got a flood of commit links, and me fixing up my tooling and redoing the set is next to worthless after the initial push.

**Comment by dagood** [comment]
Actually, looks like I don't even have permission on the new repos.

**Comment by mmitche** [comment]
I also managed to deny myself permissions on the new repos.  ANyways, these are recreations for the purposes of archival, and they are locked down and can't be changed from here on out.

**Comment by dagood** [comment]
Is there anywhere you can document this so that auto-linking is turned off for future new repos?

**Comment by mmitche** [comment]
Not that I know of.  I didn't even know repo commit mention linking was a thing there :).  How many mails did you get?

**Comment by dagood** [comment]
At least 133. And AzDO sent them over the course of ~30 minutes, presumably because you ran the pushes over time.

**Comment by dagood** [comment]
Maybe we can just delete all the issues in the dnceng instance, AFAIK they aren't used anymore. Or I can find a way to mass unsubscribe myself from these issues, but who knows if there's an API available for that. (There isn't one for turning auto-linking off, and now I'm getting 500 errors from how I hijacked the UI element to do that, so my tool doesn't work anymore.)

**Comment by dagood** [comment]
> a way to mass unsubscribe myself from these issues, but who knows if there's an API available for that.

There is, easy to use:

```C#
VssConnection connection = new VssConnection(
    new Uri(collectionUri),
    new VssCredentials(new VssBasicCredential("", pat)));

// <PackageReference Include="Microsoft.VisualStudio.Services.Notifications.WebApi" Version="16.162.1-preview" />
var client = connection.GetClient<NotificationHttpClient>();

Task.WhenAll(
    client
        .ListSubscriptionsAsync(connection.AuthorizedIdentity.Id)
        .Result
        .Where(s => s.Description.StartsWith("Following 'WorkItem' artifact"))
        .Select(s => client.DeleteSubscriptionAsync(s.Id))).Wait();
```

Closing, I shouldn't be affected by this problem anymore.
