### ISSUE TITLE
Rethink .NET Releases: prepare a diagram(s) for the release pipeline.

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade#12986]
We have:
* Release-DotNet-5.x(-Test) - the release pipeline for the .Net versions >=5.x
* Release-DotNet-2.x(-Test) - the release pipeline for the .Net versions <=2.x

And each diagram has a set of options available (like "Publish to DotNetCli", etc.). It would be nice to have a diagram(s) that would show how each option affects the pipeline execution. Plus, it would be nice to have a diagram that illustrates the differences between the -Test and Prod modes (similar to https://github.com/dotnet/arcade-services/issues/2636).

**Comment by MilenaHristova** [comment]
I'm writing this page https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1017/Test-Version-of-Release-DotNet-5x then I'll also do a picture

**Comment by andriipatsula** [comment]
@MilenaHristova , May I assume this one is done?

**Comment by MilenaHristova** [comment]
> @MilenaHristova , May I assume this one is done?

I haven't looked at the Release-DotNet-2.x(-Test) pipelines but we are not focusing on them now. So I'd say we close it

**Comment by andriipatsula** [comment]
> I'm writing this page https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1017/Test-Version-of-Release-DotNet-5x then I'll also do a picture

You mentioned "I'll also do a picture". Is it still a plan?

**Comment by MilenaHristova** [comment]
I added some more information about the other parameters. Not sure if a picture makes sense here because the test pipeline just skips almost all stages, the other parameters skip a job or a step each

**Comment by andriipatsula** [comment]
closing as done
