### ISSUE TITLE
SignCheck fails with IOException attempting to write to the error log

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1300]
I'm attempting to setup SignCheck on https://github.com/aspnet/Extensions, but Microsoft.DotNet.SignCheck.exe always fails while attempting to write an error log file.

**Repro**
Arguments:
```
.\Microsoft.DotNet.SignCheck.exe --verbosity Detailed --error-log-file C:\src\aspnet\Extensions\artifacts\logs\signcheck-errors.log --generate-exclusions-file C:\src\aspnet\Extensions\artifacts\logs\signcheck.exclusions.g.txt --input-files C:\src\aspnet\Extensions\artifacts\ --recursive --verify-jar --verify-strongname 
```

**Result**
Verification partially completes, but then fails with a fatal error:

![image](https://user-images.githubusercontent.com/2696087/48231646-b69fe600-e363-11e8-8550-dd1f9f9ea330.png)

Ironically, I believe it is SignCheck.exe that has created the file, because this file is created and contains this:
```
System.IO.IOException: The process cannot access the file 'C:\src\aspnet\Extensions\artifacts\logs\signcheck-errors.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.SignCheck.Verification.SignatureVerificationManager.GetFileVerifierByHeader(String path)
   at Microsoft.SignCheck.Verification.SignatureVerificationManager.GetFileVerifier(String path)
   at Microsoft.SignCheck.Verification.SignatureVerificationManager.VerifyFiles(IEnumerable`1 files)
   at SignCheck.SignCheck.Run()
```

**Details**
I'm using SignCheck 1.0.0-beta.18558.2

cc @joeloff

**Comment by joeloff** [comment]
Is it running multiple instances of the SignCheck?

**Comment by natemcmaster** [comment]
No. It looks like the same process attempts to open the same file multiple times.

![image](https://user-images.githubusercontent.com/2696087/48232033-2662a080-e365-11e8-8257-c635cb66f348.png)

**Comment by joeloff** [comment]
What happens if you switch to using the shortform parameters, e.g. -e instead of error-log-file? Also, for the input files, if you're giving it a folder, try something like c:\foo\*.* and pass -t to scan sub-folders.


I need to check, but I can't recall if it will just scan the files in the folder automatically. That might be a bug.

**Comment by joeloff** [comment]
Ignore my last comment. I tried the internal version I wrote for WebTools and it's happy with just root folders for the input files. I'll take a look at what's going on here

**Comment by natemcmaster** [comment]
> What happens if you switch to using the shortform parameters, e.g. -e instead of error-log-file? 

Same error.

**Comment by natemcmaster** [comment]
I think I understand why. If the log is in the directory being recursively searched, the tool attempts to open the log file to check for signing.
