### ISSUE TITLE
Setup Arcade SDK to use SignTool to strong name sign files

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#1301]
The SignTool task now accepts a new parameter to specify sn.exe path and also supports strong name signing files locally. We need to setup Arcade SDK to use the latest version of the tool and inform the new parameters to the task.

**Comment by JohnTortugo** [comment]
I crafted the function below to lookup the path to 'sn.exe' on common directories. Right now what I'm thinking is to change SignTool again to use this function if no path is specified as a parameter. What do you think?

```
private string FindSNBinaryPath()
{
    var BasePath = Environment.GetEnvironmentVariable("ProgramFiles(x86)");
    var SDKBasePath = $@"{BasePath}\\Microsoft SDKs\Windows\";

    string[] v10Files = Directory.GetFiles($@"{SDKBasePath}\v10.0A\", "sn.exe", SearchOption.AllDirectories);
    string[] v8Files = Directory.GetFiles($@"{SDKBasePath}\v8.1A\", "sn.exe", SearchOption.AllDirectories);
    string[] anyFile = Directory.GetFiles(SDKBasePath, "sn.exe", SearchOption.AllDirectories);

    if (v10Files.Any())
    {
        return v10Files.OrderByDescending(q => q).First();
    }
    else if (v8Files.Any())
    {
        return v8Files.OrderByDescending(q => q).First();
    }
    else if (anyFile.Any())
    {
        return anyFile.OrderByDescending(q => q).First();
    }
    else
    {
        return null;
    }
}
```

**Comment by tmat** [comment]
I'd rather avoid dependency on the machine state. Can't we package `sn.exe` into a standalone NuGet package and add a `PackageReference` to Tools.proj in Arcade SDK? Then pass the path to `sn.exe` as a parameter to the SignTool task.

**Comment by weshaggard** [comment]
Yeah I think we can do that similar to what we did for vswhere.

**Comment by JohnTortugo** [comment]
Sounds good. I'm working on it.

**Comment by JohnTortugo** [comment]
I'm not sure how to proceed on this. I've a few questions:

- Is this the right feed to use?  https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
- Can I just create the package locally and upload it? I think it would be better to have the "package content" maintained somewhere (not necessarily a repo) for transparency and in case we need to inspect it in the future.

@jcagme @markwilkie

**Comment by jcagme** [comment]
> Is this the right feed to use? https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json

Yes.

> Can I just create the package locally and upload it? I think it would be better to have the "package content" maintained somewhere (not necessarily a repo) for transparency and in case we need to inspect it in the future.

Where did we get the code originally?

I can help uploading the package

**Comment by JohnTortugo** [comment]
Thanks @jcagme . AFAIU we are going to upload the executable and it's dependencies (a few libs).
