### ISSUE TITLE
Determine what to do with the xharness test legs in Arcade

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#13044]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The xharness apple_simulator testing in arcade is notoriously flaky, and was disabled as part of https://github.com/dotnet/arcade/pull/13043. In general, the xharness testing is a bit flaky and may be better suited as part of an xharness update in arcade itself.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by epananth** [comment]
@premun we area planning to do arcade validation here, what you do you think about this?

**Comment by premun** [comment]
There was an increase in issues with Apple Simulators when we merged some old HW into the 10.15 queue. This should go away with the move to the MacOS 12/13. Maybe we should just stop using 10.15 and move to 13 and the reliability issues would go away?

**Comment by premun** [comment]
We only made the tests run when we make changes to XHarness
