### ISSUE TITLE
Enable generation of account SAS uris

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#13041]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We need to be able to generate account SAS uris for the purpose of the staging pipelines's publishing process + recent arcade changes to publishing whcih removed support for account key publishing.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

Add ability to generate account SAS uris.

**Comment by missymessa** [comment]
@mmitche is this completed? Can we close it? Thanks :)

**Comment by mmitche** [comment]
Yep. done!
