### ISSUE TITLE
Apple TV upgrade to tvOS 16 

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#13063]
@akoeplinger reports that the Apple TVs connected to these devices have been upgraded (unintentionally) to tvOS 16, which is incompatible with XCode. The devices should be reverted back.

- osx.1015.amd64.appletv.open -> DNCENGMAC025
- osx.1100.amd64.appletv.open -> DNCENGMAC114
- osx.1100.amd64.appletv.open -> DNCENGMAC115

**Comment by garath** [comment]
I've taken these machines offline

**Comment by akoeplinger** [comment]
Downgrading an iOS/tvOS device is usually hard if not impossible, so it's probably easier to just reassign these machines to the `osx.13.amd64.appletv.open` queue.

**Comment by garath** [comment]
Filed [ICM 380302357](https://portal.microsofticm.com/imp/v3/incidents/details/380302357/home) enlist help from DDFUN.

**Comment by garath** [comment]
Closed and all is well!
