### ISSUE TITLE
crit: System.Exception: Failed to list devices. preventing text from executing on TvOS in 7.0

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#13060]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=229239

### Build leg reported

System.Runtime.Tests.WorkItemExecution

### Pull Request

https://github.com/dotnet/runtime/pull/84355

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section)

 ```json
 {
    "ErrorMessage" : "crit: System.Exception: Failed to list devices.",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[274350](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274350)|dotnet/runtime|[System.Memory.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274350&view=ms.vss-test-web.build-test-results-tab&runId=5427848&resultId=100094)||
|[274345](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274345)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274345&view=ms.vss-test-web.build-test-results-tab&runId=5427182&resultId=100001)||
|[271126](https://dev.azure.com/dnceng-public/public/_build/results?buildId=271126)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=271126&view=ms.vss-test-web.build-test-results-tab&runId=5350764&resultId=100001)|dotnet/runtime#86127|
|[266742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266742)|dotnet/runtime|[System.Runtime.Handles.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=266742&view=ms.vss-test-web.build-test-results-tab&runId=5252048&resultId=150090)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|4|

**Comment by ilyas1974** [comment]
We deployed XCode 14.3 to all the tvOS systems earlier today. Will continue to monitor this issue, but this update should resolve the issues we are seeing.

**Comment by ilyas1974** [comment]
@premun could you take a look at this issue when you get a chance? XCode has been updated and the new version is in the logs, but the workloads still are not able to communicate with the AppleTVs
/cc: @steveisok

**Comment by premun** [comment]
This is a problem with mlaunch being too old. We have an update coming into the branch here: https://github.com/dotnet/runtime/pull/85726

I believe this should help.

**Comment by steveisok** [comment]
I haven't seen it lately either.  I think it can be closed.
