### ISSUE TITLE
NuGet restore fails with The repository primary signature validity period has expired

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#13070]
### Build

https://dev.azure.com/dnceng/internal/_build/results?buildId=2153225

### Build leg reported

Build

### Pull Request

https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/30063

 ```json
 {
    "ErrorMessage" : "The repository primary signature validity period has expired",
    "BuildRetry": true,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[283331](https://dev.azure.com/dnceng-public/public/_build/results?buildId=283331)|dotnet/runtime|Build HttpStress|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/283331/logs/14)||
|[2181170](https://dev.azure.com/dnceng/internal/_build/results?buildId=2181170)|dotnet-diagnostictests|Build - Windows x86 $(NetCoreVersion) on Windows|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2181170/logs/158)||
|[260336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260336)|dotnet/roslyn|Build - Validate determinism|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/260336/logs/74)|dotnet/roslyn#67807|
|[253865](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253865)|dotnet/roslyn|Build - Validate determinism|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/253865/logs/48)||
|[253696](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253696)|dotnet/roslyn|Build - Validate determinism|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/253696/logs/214)||
|[253258](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253258)|dotnet/runtime|Build HttpStress|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/253258/logs/18)||

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[270758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270758)|dotnet/performance|[Partition2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=270758&view=ms.vss-test-web.build-test-results-tab&runId=5338912&resultId=100003)|dotnet/performance#3019|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|7|

**Comment by garath** [comment]
ICM on this issue from another team: [ICM 380022563](https://portal.microsofticm.com/imp/v3/incidents/details/380022563/home).

**Comment by dtivel** [comment]
@garath, does https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#retry-untrusted-root-failures help?

**Comment by dougbu** [comment]
I'm going to try something out in dotnet-helix-machines&hellip;

**Comment by garath** [comment]
> I'm going to try something out in dotnet-helix-machines…

What is that? Damon's suggestion?

**Comment by dougbu** [comment]
> What is that? Damon's suggestion?

After a conversation w/ @ilyas1974 and @riarenas, our initial thought was to upgrade the .NET SDK (and therefore the `dotnet nuget` command) used in dotnet-helix-machines. However, a number of the reports above involve very recent SDK versions. An update may solve some issues but likely not this one.

@dtivel's suggestion is about NU3028 but the error is actually <https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3037>. That said, I'll try it out.

If that doesn't work, the `DOTNET_NUGET_SIGNATURE_VERIFICATION=false` environment variable setting mentioned in dotnet/sdk#31868 sounds scary but may be necessary.

**Comment by dtivel** [comment]
> @dtivel's suggestion is about NU3028 but the error is actually https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3037. That said, I'll try it out.

The timestamp's trust fails, so the timestamped signature remains expired.  A trusted timestamp basically allows a timestamped signature to not expire.

`DOTNET_NUGET_SIGNATURE_VERIFICATION` has no effect whatsoever on Windows.

**Comment by dougbu** [comment]
> @garath, does https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#retry-untrusted-root-failures help?

Yes it seems to make a significant difference, at least w/ the 6.0.404 .NET SDK.

@garath thoughts on putting this workaround into job.yml or tools.ps1 and tools.sh❔ Third option would be to pass this success along to the dotnet/performance, roslyn, runtime, and sdk teams.

**Comment by dougbu** [comment]
> > @garath, does https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#retry-untrusted-root-failures help?
> 
> Yes it seems to make a significant difference, at least w/ the 6.0.404 .NET SDK.
> 
> @garath thoughts on putting this workaround into job.yml or tools.ps1 and tools.sh❔ Third option would be to pass this success along to the dotnet/performance, roslyn, runtime, and sdk teams.

/ping @garath. Our customers are still hitting this though helix machines is unblocked w/ the following workaround in place
``` text
  # Retry signature validation up to three times, waiting 2 seconds between attempts.
  # See https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#retry-untrusted-root-failures
  - name: NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY
    value: 3,2000
```
Should we put this into our eng/common/job.yml or reach out to affected customers❔

/cc @dotnet/dnceng for broader visibility since I'll be OOF tomorrow and so will @garath&hellip;

**Comment by premun** [comment]
Should we put this into our `eng/common/job.yml` or reach out to affected customers❔

I think we'd need to do both. I suspect our job templates might not be utilized in repositories such as runtime.

**Comment by dougbu** [comment]
> I'm not sure what the best thing to do here is.

I have a vague feeling that changing job.yml won't hurt anything and might mostly avoid flare-ups like we experienced a month or so ago. the workaround is minimal and has more words in the comments than the actual addition 😀

**Comment by garath** [comment]
Sounds good to me. PRs welcome!

**Comment by dougbu** [comment]
> Sounds good to me. PRs welcome!

sorry, just one PR: #13659

**Comment by dougbu** [comment]
/fyi [ICM 380022563](https://portal.microsofticm.com/imp/v3/incidents/details/380022563/home) was just reopened because another team hit the same issue. turns out NuGet feels they're only able to work around a problem in Windows itself. I believe Windows has no fix (yet❔).

**Comment by dougbu** [comment]
could someone here please approve #13659❔ would be nice to put this longstanding "FR" issue behind us

**Comment by dougbu** [comment]
fix is now in (thx @AlitzelMendez). is any validation needed before closing this issue❔

**Comment by dougbu** [comment]
Completed w/ ab7df8826d29
