### ISSUE TITLE
Update screenshot in Build Analysis documentation

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#13114]
Name of the app was changed. Need to update our screenshots to reflect the current state of Build Analysis. 

https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/Introduction.md

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by AlitzelMendez** [comment]
PR: https://github.com/dotnet/arcade/pull/13748

**Comment by AlitzelMendez** [comment]
one more: https://dnceng.visualstudio.com/internal/_wiki/wikis/DNCEng%20Services%20Wiki/945/Enabling-Build-Analysis-GitHub-App-for-.NET-OSS-Admins
