### ISSUE TITLE
Invalid Arcade version used in installer CodeSpaces after sync

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/arcade#13124]
After syncing Arcade changes in the VMR, an invalid version is used to unpack the built Arcade:

```
/workspaces/dotnet/repo-projects/Directory.Build.targets(486,5): error : An exception has occurred while trying to decompress '/workspaces/dotnet/artifacts/obj/x64/Release/blob-feed/packages/Microsoft.DotNet.Arcade.Sdk.8.0.100.nupkg' into '/workspaces/dotnet/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/'. [/workspaces/dotnet/repo-projects/arcade.proj]
/workspaces/dotnet/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/ : error : FileNotFoundException: Could not find file '/workspaces/dotnet/artifacts/obj/x64/Release/blob-feed/packages/Microsoft.DotNet.Arcade.Sdk.8.0.100.nupkg'. [/workspaces/dotnet/repo-projects/arcade.proj]
```

The version utilized in the path to the built Arcade is coming from the `arcadeOutputPackageVersion` variable found in `AllRepoVersions.props` file.

Manually altering the variable to the correct version fixes the failure.

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
No release note required

**Comment by premun** [comment]
This is now fixed, Arcade version won't be bumped with one-off updates in the VMR
