### ISSUE TITLE
Improving sdk install performance

### ISSUE THREAD

**Issue by sebastienros** [dotnet/arcade#13128]
I noticed that every time I would run `build.cmd` it is taking an unreasonable amount of time to detect that I already have the required runtimes locally in `.\.dotnet`. I managed to improve this time by using this check in `tools.ps1`:

```powershell
function InstallDotNet([string] $dotnetRoot,
  [string] $version,
  [string] $architecture = '',
  [string] $runtime = '',
  [bool] $skipNonVersionedFiles = $false,
  [string] $runtimeSourceFeed = '',
  [string] $runtimeSourceFeedKey = '',
  [switch] $noPath) {

  # BEGIN
  $runtimePath = $dotnetRoot

  $runtimePath = $runtimePath + "\shared"
  if ($runtime -eq "dotnet") { $runtimePath = $runtimePath + "\Microsoft.NETCore.App" }
  if ($runtime -eq "aspnetcore") { $runtimePath = $runtimePath + "\Microsoft.AspNetCore.App" }
  $runtimePath = $runtimePath + "\" + $version

  if (Test-Path $runtimePath) {
    $installSuccess = $true
    Exit
  }
  # END

  $installScript = GetDotNetInstallScript $dotnetRoot
  $installParameters = @{
    Version = $version
```

I believe that just loading `dotnet-install.ps1` is already costly, and on repositories that target multiple  runtimes it is accumulating quickly. On my previous machine with aspnetcore it would spend 10s for nothing on each build.

But I think this could be improved even more if the calls to `dotnet-install.cmd` were skipped altogether and that would performance even better since it would prevent from starting a `cmd` which itself calls `powershell` then loads the scripts, for each runtime in `global.json`. My solution is barely skipping the `dotnet-install.ps1` invocation.

**Comment by markwilkie** [comment]
I'd be open to a PR on this @sebastienros.

**Comment by sebastienros** [comment]
I am glad you are suggesting it as I didn't want to start anything if you had reasons not do accept changes around that. Thanks

**Comment by RussKie** [comment]
This has been bothering me too. It's both too time consuming and too noisy. I have already made [changes to dotnet-install scripts](https://github.com/dotnet/install-scripts/pull/356) to reduce the chattiness. 

I see there are possibly few ways of achieving the improvement. Probably the easiest option is to add a new switch - e.g., `--skip-restore-toolset | -srt` - that would bypass this command:
https://github.com/dotnet/arcade/blob/fb14cae30eacbe844468ac297b3d4c61e0bb9dc0/eng/common/dotnet-install.ps1#L20

This way for the first time a dev will need to run `.\restore.cmd` to install the required toolsets, and then run `.\restore.cmd -srt` to only install the SDK, if required.

A more hands-off kind of solution could be building the runtime-pack paths and then conditionally run the above command.
