### ISSUE TITLE
Helix deployment script error on Ubuntu 22.04 "libmsquic" was not found

### ISSUE THREAD

**Issue by parose1** [dotnet/arcade#13130]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

This issue blocks adding Ubuntu 22.04 based systems into Helix

While attempting to add the first Ubuntu 22.04 system into Helix.  Ran into a stopping error on PERFTIGER168 that ended the Helix deployment script pre-maturely.

Closest error I could find to the termination was that it was failing to install package "libmsquic" as it was no longer found in the Ubuntu repository.

System we can use for investigation:

PERFTIGER168
IP Address: 10.231.247.198
Username: perflocal
Password: [Microsoft Azure](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/asset/Microsoft_Azure_KeyVault/Secret/https://dotnetcore-perf.vault.azure.net/secrets/PerfTiger-Linux-Password/2cf17d21db854cb2a5c5ba20c0e307ad)

![image](https://user-images.githubusercontent.com/48035740/231562406-4170da23-764c-4e5b-b882-3d8619834ae1.png)

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Fix the `libmsquic` package installation in Ubuntu 22.04

**Comment by parose1** [comment]
Creating this issue on behalf of Shawn Lemhous v-shlemh@microsoft.com. Please conact them for updates to this issue. Thank you.

**Comment by dougbu** [comment]
Sharing this w/ you @premun because I already started looking at the similar-sounding #13160

**Comment by dougbu** [comment]
If this is the same as #13160, problem likely happens earlier (w/ an inability to install `libmsquic` at all):

From dotnet-helix-machines-ci [build #20230411.01](https://dev.azure.com/dnceng/internal/_build/results?buildId=2155330&view=logs&j=5ea6af1c-23d4-5a64-84c5-c8f1f8bb95c3&t=8a413273-bfac-5c42-b6db-06f02d67d179&l=416):
<details>
<summary>Image Factory logs</summary>

``` text
2023-04-12 02:50:14Z -> ------------------------------------------Starting artifact linux-add-package------------------------------------------
2023-04-12 02:50:14Z -> /mnt/ImageFactoryWorker/artifacts/linux-add-package/linux-add-package.sh --update True --packages libmsquic
2023-04-12 02:50:14Z ->  --groups 
2023-04-12 02:50:14Z -> packages: libmsquic
2023-04-12 02:50:14Z -> update: True
2023-04-12 02:50:14Z -> groups: 
2023-04-12 02:50:14Z -> /usr/bin/apt
2023-04-12 02:50:14Z -> Using apt as the package manager.
2023-04-12 02:50:14Z -> Adding WaLinux exemption
2023-04-12 02:50:14Z -> Running update command
2023-04-12 02:50:14Z -> Hit:1 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
2023-04-12 02:50:14Z -> Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease
2023-04-12 02:50:14Z -> Hit:3 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
2023-04-12 02:50:14Z -> Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease
2023-04-12 02:50:14Z -> Hit:5 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
2023-04-12 02:50:16Z -> Reading package lists...
2023-04-12 02:50:16Z -> Building dependency tree...
2023-04-12 02:50:16Z -> Reading state information...
2023-04-12 02:50:16Z -> 35 packages can be upgraded. Run 'apt list --upgradable' to see them.
2023-04-12 02:50:16Z -> Installing packages
2023-04-12 02:50:17Z -> Some packages could not be installed. This may mean that you have
2023-04-12 02:50:17Z -> requested an impossible situation or if you are using the unstable
2023-04-12 02:50:17Z -> distribution that some required packages have not yet been created
2023-04-12 02:50:17Z -> or been moved out of Incoming.
2023-04-12 02:50:17Z -> The following information may help to resolve the situation:
2023-04-12 02:50:17Z -> The following packages have unmet dependencies:
2023-04-12 02:50:17Z ->  libmsquic : Depends: libssl1.1 but it is not installable
2023-04-12 02:50:17Z -> ------------------------------------------ERROR DATA FOR ARTIFACT: linux-add-package------------------------------------------
...
+ apt update

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

W: https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
+ [[ -n libmsquic
 ]]
+ echo 'Installing packages'
+ pm_install libmsquic
++ install_command apt
++ case "$1" in
++ echo '-qq -y install'
+ apt -qq -y install libmsquic

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Unable to correct problems, you have held broken packages.
2023-04-12 02:50:17Z -> ------------------------------------------ERROR DATA FOR ARTIFACT: linux-add-package------------------------------------------
2023-04-12 02:50:17Z -> ------------------------------------------Ending artifact linux-add-package------------------------------------------
```
</details>

**Comment by dougbu** [comment]
Closing #13160 because it looks more and more like a duplicate. Go there for a bit more console logging.

Problem does indeed seem specific to the Ubuntu 22.04 images.

Have started the process of finding the team that owns `libmsquic` and will poke around on the repro machine once I get a bit done on #13161&hellip;

**Comment by premun** [comment]
Thanks @dougbu! I think they actually sit here in Prague so I will reach out to them.
(https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Quic/readme.md)

**Comment by premun** [comment]
So apparently there's a new dependency on openssl 1.1 which is only in the 20.04 package repository. It can be worked around by adding the 20.04 repository. It will take a couple of weeks for them to push a new version which will already depend on 3.0 (msquic 2.0) and then this workaround won't be needed anymore.

I will open a PR with the fix

**Comment by premun** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/30672

**Comment by premun** [comment]
Logged https://github.com/dotnet/arcade/issues/13167 as a follow up

**Comment by premun** [comment]
The current solution actually doesn't need a follow-up at all

**Comment by dougbu** [comment]
Should this issue be closed now that https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/commit/d7cdd3b88b0109e04c77e08f153b7ee2e480ba6f is in❔

> The current solution actually doesn't need a follow-up at all

And should we close #13167 because the extra openssl1.1 installation won't hurt anything❔ I actually lean the other way because I'm betting @karelz's team will have fixed other things in msquic 2.0 and ASP.NET and the rest of the runtime team will start depending on 2.0. (Which may mean we need both versions on the images.)

**Comment by premun** [comment]
Yes, closing this.

@dougbu I opened #13167 when my initial workaround was much more invasive. Only later I noticed we already install `libssl1.1` but later in the process and a bit older version. So I think the current workaround is actually not in a way of anything and we can just close it too.

**Comment by parose1** [comment]
Hi all,

We were told the fix for this was rolled out into Helix Staging. We tried to run the helix deployment script on two new machines into the Helix Staging environment but are still getting the error for libmsquic not being found. 

Just wanted to verify if the fix was rolled out to staging and is still an ongoing issue or has not been rolled out yet?

![image](https://user-images.githubusercontent.com/48035740/232897865-b10c6a5a-2469-4aba-9db8-30786142dcd3.png)

**Comment by dougbu** [comment]
@parose1 the fixes were specific to Ubuntu 22.04. They _should_ have made it too staging but there hasn't been a successful build of main lately for other (mostly Windows at first) reasons. What Ubuntu image were you building in that log❔

**Comment by parose1** [comment]
Hi @dougbu The machines we tested on were Ubuntu 22.04. We tried on two machines PERFTIGER168 and PERFTIGER169. They are available in https://mlskvmui if you want to take a look. v-shlemh should have more info as well on the errors, he is just unable to update/create GitHub issues at this time so I am helping to update.

**Comment by dougbu** [comment]
We should probably wait until @riarenas and I unblock Linux builds before looking at this recurrence. My suspicion is the staging images aren't updated until a build of main completes successfully.
Right now, we're focused on doing a single build at a time in the dotnet-helix-machines-ci pipeline to avoid overloading Image Factory and our subscription limits. That means we're focusing on Windows builds and https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/30772 in particular.

This will hopefully complete soon, allowing us to see what breaks in 'main' builds and starting to look at one or two of the Linux problems. Please bear with us.

**Comment by parose1** [comment]
ok good to know. Thanks again. I'll talk with Ilya on next steps for DDFUN then.

**Comment by premun** [comment]
Fix will be here then - https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/30792?_a=files

**Comment by dougbu** [comment]
> was checked in so we are not even able to roll out?

Correct.

We're also trying to avoid building anything except changes that those that get us closer to green. Depending on how [build #20230419.04](https://dev.azure.com/dnceng/internal/_build/results?buildId=2162461&view=results) goes, that'll either mean merging https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/30792 or reverting all Linux changes since the last build of main.

**Comment by premun** [comment]
There were only two VS images being broken so I went ahead and merged. This change only affects on-prem queues anyway and those don't apply in the Build Images phase so I went ahead and merged

**Comment by premun** [comment]
Rolled out, closing
