### ISSUE TITLE
[Needs Breakdown] Write tests for Helix JobSender SDK

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#1313]
Should include unit tests for each individual component and probably some sort of end-to-end test which will send a job to Helix and wait for a response.

**Comment by missymessa** [comment]
Helix JobSender and SDK don't look like they have very many tests. We need to break down this issue into test plans for what we want to test. At the minimum, I think we at least need to ensure that the version of Arcade built works with the version of Helix API it's referencing.

**Comment by jonfortescue** [comment]
Breaking this down into the following issues:

* Helix JobSender tests
  - Unit tests for payloads -- #5186 
  - Payload tests with mocked storage API  -- #5187
  - Validate WorkItem construction and Job sending -- #5188
  - Scenario test parity for the DirectApiTests's job/work item send tests -- #5189
  - Unit tests for helper methods -- #5190

As for the SDK -- it is a wrapper for the JobSender, so these underlying tests function well for unit tests for it. It currently is heavily scenario tested because arcade itself runs its test using that SDK, so it should be validated properly.
