### ISSUE TITLE
Request to bump XCode on tvOS helix queue

### ISSUE THREAD

**Issue by steveisok** [dotnet/arcade#13155]
I'm requesting to have XCode bumped to 14.3 on the machines in the `OSX.13.Amd64.AppleTV.Open` helix queue.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Updating XCode within osx.13.amd64.appletv.open

**Comment by ilyas1974** [comment]
XCode has been updated on all systems and the previous version has been removed.
