### ISSUE TITLE
Make eng/Publishing.props optional (default to version 3)

### ISSUE THREAD

**Issue by tmat** [dotnet/arcade#13157]
By now all repos are likely on V3 publishing. Can we make `eng/Publishing.props` optional?

**Comment by missymessa** [comment]
@epananth can you put this somewhere, thanks :)

**Comment by epananth** [comment]
Still don't know where to put this. 

We need to decide who will own publishing to put this is arcade-services or let it remain with Engineering Services.

**Comment by epananth** [comment]
V3 is the only publishing we support. Closing this
