### ISSUE TITLE
Expired tokens handling

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#13150]
We had some Release pipeline failures during the release today due to some expired tokens:

winget-publishing failed [Pipelines - Run 20230404.2-7.0.203,7.0.105 logs (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=2150311&view=logs&j=228b415c-fbd3-556f-2acf-3e133446cdaf&t=464ede47-6eb1-509a-c6d7-3eab2f4908c5&s=106c6af6-e499-5c8c-b964-934f1069d626) because the BotAccount-dotnet-winget-bot-PAT secret has expired. The secret isn't in the SecretManager config, we should probably add it there. I don't know if there's going to be some extra work because it's in the DotnetDocker2 subscription. I asked Matt Thalman to rotate the secrets so we can unblock the release
	
repo propagation failed [Pipelines - Run 20230407.1-8.0.100-preview.3.23178.7 logs (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=2153008&view=logs&j=76f541c7-37b2-56fa-4bf9-5b5565b84973&t=0212a458-0f58-5a3d-bf84-ebedeadab93e) to copy dotnetchecksumstage to dotnetclichecksums. This is most likely due to an expired token again, dotnetclichecksums-account-blob-write-token-base64. The token is in the secret manager config, so we should be able to forcefully rotate it. We manually copied files to unblock the release
	
There might be other tokens that are not in the Secret Manager config, we should probably try to identify them all

**Comment by MilenaHristova** [comment]
BotAccount-dotnet-winget-bot-PAT is added to the config https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/31628
Closing this, we have a follow-up to gradually add all secrets
