### ISSUE TITLE
Update `libmsquic` to a version that depends on OpenSSL 3.0

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#13167]
### Context

The libmsquic package cannot be out-of-the-box installed in Ubuntu 22.04  as it depends on libssl1.1 which is not present in the 22.04 package repository. We need to install it from the 20.04 one. We have put a temporary solution in place as future versions of libmsquic will depend on openssl 3.0 and this won't be needed anymore.

The workaround was added as part of https://github.com/dotnet/arcade/issues/13130

### Goal

Once the new version is available, remove the `linux-ubuntu-2204-add-libmsquic` artifact and just plain install the `libmsquic` package using `linux-ubuntu-add-package` artifact. Contact Nick Banks for more information about libmsquic.

**Comment by premun** [comment]
I am pinging @dotnet/dnceng here as we will get a ping in the future from the msquic team about the availability of the new package

**Comment by premun** [comment]
The workaround turned out to be just a small bump of the openssl library we're already installing so I don't think we need to track this or remove anything.

**Comment by CarnaViire** [comment]
@premun FYI: The recently published libmsquic 2.2.1 for Ubuntu 22.04 finally supports OpenSSL 3+, and helix images seem to have consumed the update already:

```
lia@knatalia-ubuntu22-v2:~$ sudo dpkg-query -l | grep msquic
ii  libmsquic                           2.2.1                                   amd64        Microsoft implementation of the IETF QUIC protocol
lia@knatalia-ubuntu22-v2:~$ ldd  /lib/x86_64-linux-gnu/libmsquic.so.2
        linux-vdso.so.1 (0x00007ffde917d000)
        libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f6339120000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6338ef8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f63396ce000)
```
(the above was on a VM created in azure helix-repro-vms)

I leave up to you whether you wish to remove OpenSSL 1.1 from the image or not, but it's not needed by libmsquic anymore.

**Comment by premun** [comment]
Thanks @CarnaViire!

**Comment by premun** [comment]
@CarnaViire I am quite curious - which exact image have you used? I don't think it's possible we have this on the images already. Maybe in the docker images?

**Comment by CarnaViire** [comment]
![image](https://user-images.githubusercontent.com/3184057/236445339-4de0e71a-c4c4-4b6f-b01a-881094c3fb24.png)

No, we're updating docker images separately https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/866

**Comment by CarnaViire** [comment]
@premun If you have any other ways to check the version on the image (I only know to create a VM in azure like I did above) -- can you please check and share?

**Comment by premun** [comment]
I can check the [images we use in Helix](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/84a65c9a-787d-45da-b10a-3a1cefce8060/resourceGroups/HELIXIMAGES/providers/Microsoft.Compute/galleries/HelixImages/images/build.ubuntu.2204.amd64/overview) but I am not sure you have access there. I am not sure how `helix-repro-vms` is populated actually.

We did build one yesterday, however, we used to install `libmsquic` from a `.deb` package we upload manually to a storage with installation packages and we don't have the newest one there so it would somehow have to with Ubuntu automatically and I don't think that's the case as you need to MSFT repository first. So that's why I was wondering how come you found the package on the VMs.

**Comment by CarnaViire** [comment]
I thought the package was installed directly from packages.microsoft.com? At least I got this impression from https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=/definitions/shared/linux.yaml&version=GBmain&line=99&lineEnd=107&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents but I might have interpreted the code wrongly 😅

**Comment by premun** [comment]
Ah, you're right. I was looking at an old version. So I guess that would get the latest, yeah..

**Comment by dougbu** [comment]
@premun since we are using the latest `libmsquic`, why are we still installing OpenSSL 1.1.1f on our Ubuntu 22.04 images❔ should that be treated as a separate follow-up to the confirmations above❔

**Comment by dougbu** [comment]
&hellip; see dotnet-helix-machines' linux.yaml. search for the following nice comment
``` yaml
# libmsquic depends on libssl1.1 which is not available in Ubuntu 22.04
```

**Comment by dougbu** [comment]
if we should remove the explicit OpenSSL installation as part of this issue, please reopen it

**Comment by premun** [comment]
@dougbu originally, this issue was intended to be the one we'd get a notification on from the networking team but the way we've dealt with this problem changed as compared to how this is described in this issue (we bumped the package and removed it from 16.04).

However, thinking about this, I am not sure we can just remove it everywhere as I don't understand the full impact. I am worried that there might be some servicing branches relying on older `libmsquic` which still requires this `libssl1.1`.

We have some extra code in the YAMLs to omit it from 16.04 but that queue might be going away anyway.

Maybe we only make a note that when creating new Ubuntu queues, we omit this?
