### ISSUE TITLE
Maestro promotion failing for .NET 5 (internal) channels 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#13175]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Following pipelines are failing 

| Pipeline | Repo | Channel | 
|----------|-------|----------|
| https://dev.azure.com/dnceng/internal/_build/results?buildId=2154787&view=results | Runtime | .Net 5 Internal | 
| https://dev.azure.com/dnceng/internal/_build/results?buildId=2157132&view=results | Efcore | .Net 5 internal | 
| https://dev.azure.com/dnceng/internal/_build/results?buildId=2158411&view=results | aspnet-core | .Net 5 internal | 
| https://dev.azure.com/dnceng/internal/_build/results?buildId=2158608&view=results | sdk | .NET 5 SDK 5.0.5xx Internal | 
| https://dev.azure.com/dnceng/internal/_build/results?buildId=2158612&view=results | templating |  .NET 5 SDK 5.0.5xx Internal | 
| https://dev.azure.com/dnceng/internal/_build/results?buildId=2137249&view=results| installer |.NET 5 SDK 5.0.5xx Internal | 

This can be cos of sleet code removal 

cc: @mmitche 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by mmitche** [comment]
I believe we are not going to need to fix this.
