### ISSUE TITLE
Migrate Shared arcade-services libraries to dotnet-dnceng-shared

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#13182]
We will be migrating all shared libraries from arcade-services to the newly created dotnet-dnceng-shared. The repo currently only exists on AzDo, we will be creating a public GitHub repo once the migration is complete.

The libraries will be published to the `.NET Eng Services - Int` channel, in a similar way to how we're doing things now.

List of shared libraries:

- [x] Microsoft.DotNet.Services.Utility
- [x] Microsoft.DotNet.Internal.Logging
- [x] Microsoft.DotNet.Internal.DependencyInjection
- [x] Microsoft.DncEng.Configuration.Extensions
- [x] Microsoft.DotNet.ServiceFabric.ServiceHost
- [x] Microsoft.DncEng.CommandLineLib
- [x] Microsoft.DotNet.Authentication.Algorithms
- [x] Microsoft.DotNet.GitHub.Authentication
- [x] Microsoft.DotNet.Internal.DependencyInjection.Testing
- [x] Microsoft.DotNet.Internal.Health
- [x] Microsoft.DotNet.Internal.Testing.DependencyInjection.Abstractions
- [x] Microsoft.DotNet.Internal.Testing.DependencyInjectionCodeGen
- [x] Microsoft.DotNet.Internal.Testing.Utility
- [x] Microsoft.DotNet.Kusto
- [x] Microsoft.DotNet.Web.Authentication
- [x] ServiceFabricMocks
- [x] Microsoft.DotNet.Metrics
- [x] Microsoft.AspNetCore.ApiVersioning
- [x] Microsoft.AspNetCore.ApiVersioning.Swashbuckle
- [x] Microsoft.AspNetCore.ApiVersioning.Analyzers
- [x] Microsoft.AspNetCore.ApiPagination
- [ ] CoreHealthMonitor

**Comment by missymessa** [comment]
> `Microsoft.AspNetCore.ApiPagination` fits into the Shared libraries, but is currently used just buy Maestro. Should we migrate it too?

Might as well migrate it, if it's not too much additional work.

**Comment by dkurepa** [comment]
Yup, let's do that, I added it to the list

**Comment by dkurepa** [comment]
All packages in the list above have been migrated to https://dev.azure.com/dnceng/internal/_git/dotnet-dnceng-shared
