### ISSUE TITLE
Drops issue: VS30063: You are not authorized to access https://devdiv.artifacts.visualstudio.com 

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/arcade#13194]
### Build

https://dev.azure.com/dnceng/internal/_build/results?buildId=2161178

### Build leg reported

Full_Signed/Upload VSTS Drop

### Pull Request

https://github.com/dotnet/fsharp/pull/15076

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section)

 ```json
 {
    "ErrorMessage" : "Exception calling \"CreateDrop\" with",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by vzarytovskii** [comment]
All recent builds are failing with the same issue: https://dev.azure.com/dnceng/internal/_build?definitionId=499&_a=summary

**Comment by riarenas** [comment]
This was fallout from a PAT that lost its drop scopes as part of the work in https://github.com/dotnet/arcade/issues/13189. I have re-added the drops scope to the PAT and verified this is now unblocked. https://dev.azure.com/dnceng/internal/_build/results?buildId=2161393&view=logs&j=e3072f97-b3f6-597b-f816-087a04d4fd77&t=ac45dc56-44bd-507b-e50c-548ef96d0dae
