### ISSUE TITLE
Define RHEL8 helix machines

### ISSUE THREAD

**Issue by sbomer** [dotnet/arcade#13202]
With the plan in https://github.com/dotnet/runtime/issues/83428 (implemented in https://github.com/dotnet/runtime/pull/84148), .NET 8 minimum glibc version is glibc 2.23. This means RHEL7 is no longer supported.

Some teams are using RHEL7 helix images for testing (for example, see failing aspnetcore tests using Redhat.7.Amd64.Open in https://dev.azure.com/dnceng-public/public/_build/results?buildId=237929&view=results). We need new RHEL8 images to replace these.

cc @captainsafia

**Comment by ManickaP** [comment]
Should we consider upgrading RH 7 helix machines to either RH 8 or 9? RH 7 is fairly old release that is out full support (in maintenance): https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates
