### ISSUE TITLE
Set up Maestro subscriptions for new repos

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#13216]
- [x] `dnceng-shared` to flow into `dotnet/arcade-services`
- [x] `dnceng-shared` to flow into `dotnet-helix-services`
- [x] `dnceng-shared` to flow into `dnceng` (I think the Internal Tools make use of functionality in the shared libraries)
- [x] `arcade` to flow into `dnceng`
- [x] `arcade` to flow into `dnceng-shared`

**Comment by dkurepa** [comment]
We should also setup `arcade -> dnceng` and `arcade -> dnceng-shared`. We want to use arcade release/6.0 so we're on the same version as arcade-services currently

**Comment by dkurepa** [comment]
@missymessa I see that there's a dnceng-shared -> dotnet-helix-service subscription created, I will mark it as complete in the task

**Comment by dkurepa** [comment]
All subscriptions are created now. Closing the issue
