### ISSUE TITLE
GitHub team clean-up

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#13218]
I've been looking into some FR requests and found that there are some GH teams we might want to take ownership of:
- https://repos.opensource.microsoft.com/orgs/dotnet/teams/bots-high (owned by Chris & Chad)
- https://repos.opensource.microsoft.com/orgs/dotnet/teams/bots-low (owned by Chad)
- https://repos.opensource.microsoft.com/orgs/dotnet/teams/dncenghot/members (needs cleaning/updating + has no owners?)
- add @dougbu to @dnceng-admin

**Comment by premun** [comment]
I believe we should add @dougbu to @dnceng-admin

**Comment by dougbu** [comment]
> I believe we should add @dougbu to @dnceng-admin

please

**Comment by premun** [comment]
@markwilkie @tkapin can we get this addressed?

**Comment by tkapin** [comment]
> @tkapin but it can only be resolved by you or Mark?

Ah, I wasn't aware of that and assumed it needs to be coordinated with the previous owners. Let me look into this.

**Comment by premun** [comment]
Well.. I think @dougbu would appreciate the access?

Secondly, it's literally a minute - all the work of finding the problematic teams is done and described in the issue so I don't think it will take long.

**Comment by tkapin** [comment]
To clarify, as there was some confusion in the conversation above, I've added @dougbu to @dnceng-admin, which was the thing @premun asked for.

The remaining things to do is to document purposes of the GH teams above and find new maintainers for these teams /cc @missymessa.

**Comment by missymessa** [comment]
Action items: 
- [ ] Decomission dncenghot
- [ ] Get ownership of bot groups moved to Mark + seniors
- [ ] Document usage of bot groups (there might be documentation for this already)

**Comment by missymessa** [comment]
Doc about bots: https://dnceng.visualstudio.com/internal/_wiki/wikis/DNCEng%20Services%20Wiki/546/Bots
