### ISSUE TITLE
Set up GitHub repos for code migrating out of arcade-services

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#13211]
Need two new GitHub repos: 
- [x] `dotnet/dnceng-shared` - for shared libraries that are used by arcade-services, helix-services, et ceteara
- [ ] `dotnet/dnceng` - for Internal Tools owned by dnceng

**Comment by missymessa** [comment]
Both repos created through Open Source Management. They're currently private so we'll need to figure out what all we need to do to make them public.

**Comment by dkurepa** [comment]
The dotnet/dnceng-shared has been populated with code

**Comment by missymessa** [comment]
The repos have been created. We still need to populate and make `dotnet/dnceng` public, but the repo creation has been completed.
