### ISSUE TITLE
(old) Maestro does not refresh secrets until the service is restarted

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#13238]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

The [Maestro](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/68672ab8-de0c-40f1-8d1b-ffb20bd62c0f/resourceGroups/maestro/providers/Microsoft.Web/sites/maestro-prod/appServices) app service is set up in such a way that the secrets it uses to queue builds in Azure DevOps are only read from the key vaults on service startup.

This means that when secret-manager runs during the weekly synchronization builds, if any of the secrets in use by the app service are cycled, the service will not know about this change, and will instead work only until the old value of the secret expires for good.

The visibility for when we are in this state is poor, and we usually perform a lot of investigations without finding a clear root cause, only to remember we just had to restart the app service.

We should:
* Look into adding alerting to old maestro
* See if it's worth adding some code like what we did for the service fabric services where we refresh the secrets from the vault every 5 minutes

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by garath** [comment]
Related to dotnet/arcade#13240

**Comment by riarenas** [comment]
Are we doing investments in old maestro? Is this really an ops issue?

**Comment by missymessa** [comment]
Old Maestro replacement is currently being worked on. https://dnceng.visualstudio.com/internal/_workitems/edit/6145

Closing this issue.
