### ISSUE TITLE
Decrease the number of CG scans that helix-machines builds perform

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#13248]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://dnceng.visualstudio.com/internal/_build/results?buildId=2163409&view=results

Helix-machines builds run the Component detection scans in most stages. This is unnecessary, and results in 20+ warnings in the build whenever there is an alert that needs to be dealt with.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by dougbu** [comment]
CG checks may only be needed in the `Build` and `BuildImages` jobs. The first compiles and performs `nuget restore` operations while the second downloads some tools used in our images.

**Comment by garath** [comment]
I think I did this with PR [!31409](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/31409). @riarenas agree?

**Comment by riarenas** [comment]
We now only run it during the build and publish wheel jobs, so it's drastically reduced. I'm not sure if we still need to run it during the build images stage as @dougbu suggests.

**Comment by dougbu** [comment]
> I'm not sure if we still need to run it during the build images stage as @dougbu suggests.

it's probably not necessary there. I'm having a separate email thread w/ the CG team about determining what we _actually_ install while preparing machines. if that ever goes anywhere, we may need to gather info into another cgmanifest and run it in the Build Images job. we're nowhere near there

**Comment by riarenas** [comment]
Thanks Doug. Sounds like we're good for now then. I'll close this.
