### ISSUE TITLE
Helix-service main build broken in "validate secrets" stage

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#13258]
- [X] This issue is blocking 
This blocks deployment of the repo

- [ ] This issue is causing unreasonable pain

The latest main build of helix-service: https://dev.azure.com/dnceng/internal/_build/results?buildId=2162914&view=results failed during the secret validation process when secret-manager failed with the errors:

```
Synchronizing secrets contained in D:\a\_work\1\s\.vault-config\helixprodservice.yaml
##[error]Unhandled Exception: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
##[error]Unhandled Exception: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
##[error]Script failed with exit code: 1

```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by garath** [comment]
I probably caused this. I manually set "next-rotation-on" values for some secrets that were missing it and themselves causing build blocks by secret manager. (Though I did run secret manager validation after the changes and had it agree with the changes.) 

I'll do an investigation.

**Comment by garath** [comment]
Well of course this doesn't repro locally...

**Comment by riarenas** [comment]
Maybe worth a retry just in case it was something flaky on the azure side of the calls?

**Comment by garath** [comment]
Already started: [ValidateSecrets Attempt 2](https://dev.azure.com/dnceng/internal/_build/results?buildId=2162914&view=results)

**Comment by garath** [comment]
Succeeded on retry. So the error must come from  catching an exception and just reporting a generic message?
