### ISSUE TITLE
Helix-service main build broken in "validate secrets

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#13257]
- [X] This issue is blocking 
This blocks deployment of the repo

- [ ] This issue is causing unreasonable pain

The latest main build of helix-service: https://dev.azure.com/dnceng/internal/_build/results?buildId=2162914&view=results

failed during the secret

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by garath** [comment]
@ricardo it seems like #13258 replaces this?

**Comment by riarenas** [comment]
I have no clue how this issue was opened, it looks like I was finishing up typing #13258 and this got posted in the meantime? weird stuff.

**Comment by riarenas** [comment]
also poor I bet @ ricardo hates me a little bit as he keeps getting tagged on things.

**Comment by garath** [comment]
> also poor I bet @ ricardo hates me a little bit as he keeps getting tagged on things.

😶 my apologies!
