### ISSUE TITLE
Consider some mechanism for feedback on whether Build Analysis is succeeding at matching

### ISSUE THREAD

**Issue by agocke** [dotnet/arcade#13255]
What I was thinking: if a Known Build/Test Issue could specify a sample PR that should definitely match, Build Analysis could provide some mechanism for signaling if it doesn't. That would tell the user that things aren't working correctly.

**Comment by agocke** [comment]
In particular there was the case of:

>For build errors we see at the log on the failing jobs and the errors at the top of the build
For test known issues we look at error message, stack trace and helix logs (with some limitation)
in the case that you shared the error is inside a helix log but is not a test, it is part of a build error, so we are not looking at the helix log, do you have other example?

It's pretty hard to tell when things deliberately aren't matching, so this might be a good instance where a feedback loop could help.

**Comment by AlitzelMendez** [comment]
@agocke thanks for this feedback, we are currently working on this on the issue: https://github.com/dotnet/arcade/issues/12798

**Comment by agocke** [comment]
Awesome, closing this as dup of https://github.com/dotnet/arcade/issues/12798
