### ISSUE TITLE
Release pipeline errors categorization

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#13298]
Consolidation of errors in Release pipeline 

| Error | Notes | Actions to take |  Ownership | Need automation? | 
|---|---|---|--|--| 
| Automate Release pipeline to update latest.version in blob storages | User  | https://github.com/dotnet/arcade/issues/12996 | Infra team | Automate | 
| Add testing capability in Release pipeline | We do not have a testing capability | https://github.com/dotnet/arcade/issues/13057 | Infra team | Does not apply | 
| Improve Nuget Validation | Not sure if we should fix this | Waiting on Rahul to answer| Waiting on Rahul | | 
| Automate any manual steps in release pipeline | | |
| publishing in Repo Propagation stage is failing | | https://github.com/dotnet/arcade/issues/13221| Infra team | Automate | 
| secrets missing in secret manager for release pipeline | | https://github.com/dotnet/arcade/issues/13222| Infra team | Manual |

**Comment by MilenaHristova** [comment]
another release pipeline error: https://github.com/dotnet/arcade/issues/13221 and https://github.com/dotnet/arcade/issues/13222

**Comment by andriipatsula** [comment]
@epananth , can we close this issue (as done)?
