### ISSUE TITLE
Build retention should not fail the build in Staging pipeline 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#13306]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Staging pipeline -> https://dev.azure.com/dnceng/internal/_build/results?buildId=2160139&view=logs&j=6606dbf2-e954-58ee-2b33-bc1713636658&t=55d2db69-7837-5679-149b-695c54eef813

Build retention should not fail the build

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Error in build Retention should not block the build

**Comment by andriipatsula** [comment]
@epananth , have you managed to prepare a PR for this?

**Comment by epananth** [comment]
I did last week and wasn't able to test it. I am going to run a test and get this PR in today

**Comment by epananth** [comment]
Test -> https://dev.azure.com/dnceng/internal/_build/results?buildId=2171801&view=logs&s=b576a58d-8d3b-5d68-c48d-6d3ec0e2b155&j=c62e860b-6817-58cb-b096-cb547a9441f4

**Comment by epananth** [comment]
PR -> https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/31032

**Comment by epananth** [comment]
this is merged. Closing this

**Comment by andriipatsula** [comment]
@epananth , do we know how often this problem occurred? Do we need to follow up of those errors? Update documentation, etc
