### ISSUE TITLE
Create a list of all dnceng-owned service connections

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#13327]
Service connections are very manual to maintain. Right now we don't have a single source of truth cataloging them. I would like to create this to evaluate the benefit of creating some automation to help manage them (specifically, avoiding unexpected build breaks because of authentication expiry).

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
No release notes

**Comment by chcosta** [comment]
You can derive the list of service connections via the Azure Rest API

```Powershell
$sourceUrl = 'https://dev.azure.com/dnceng/internal/_apis/serviceendpoint/endpoints?api-version=7.2-preview.4'

# ServiceConnectionReadPAT is a VSO PAT (for dnceng) with scope "Service Connections (Read)"
$password = $env:ServiceConnectionReadPAT
$pair = ":$($password)"
$encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($pair))
$basicAuthValue = "Basic $encodedCreds"
$Headers = @{
    Authorization = $basicAuthValue
}

$Response = Invoke-WebRequest -Uri $sourceUrl -Headers $Headers -Method Get
$json = $Response | ConvertFrom-Json

$table = ForEach ($part in $json.value)
{
    $hash = [ordered]@{
        'Name' = $part.name
        'CreatedBy' = $part.createdBy.uniqueName
        'Type' = $part.type
        'Id' = $part.url
    }
    [PSCustomObject]$hash
}

$table | Sort-Object CreatedBy | Format-Table
```

There are currently 69 service connections owned by dnceng (include Prague) team members and 15 service connections unowned by dnceng. members in the 'internal' project, this does not include 'public'.
