### ISSUE TITLE
Collection of container console logs from Helix jobs fails sometimes

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/arcade#13345]
### Context
When collecting logs from within the Docker container after Helix job is finished, it can sometimes fail, possibly due to encoding problems.

The collection happens here: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/resources/helix-scripts/helix/dockerhelper.py&version=GBmain&line=197&lineEnd=198&lineStartColumn=1&lineEndColumn=77&lineStyle=plain&_a=contents

### Example

The test log would be empty ([example](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85313-merge-3a135758ddc7455e96/WasmTestOnBrowser-System.Text.Json.Tests/1/console.7e3ce814.log?helixlogtype=result)) and `run.py` log would have this log line:
```
2023-04-27T21:33:17.208Z    ERROR      executor(733)    _execute_command_in_container    Exception: 'charmap' codec can't encode characters in position 70671-70672: character maps to <undefined>
```

### Release Note Description

Make log processing more forgiving to UTF8 encoding errors

**Comment by oleksandr-didyk** [comment]
Yeah, thanks for pointing it out

It is possibly happening here: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/resources/helix-scripts/helix/dockerhelper.py&version=GBmain&_a=contents

**Comment by pavelsavara** [comment]
cc @radical

**Comment by radical** [comment]
https://github.com/dotnet/runtime/issues/85676 also seems to have a similar issue where the `\u2193` (downward arrow) might be causing the issue.

**Comment by pavelsavara** [comment]
Another 
```
2023-06-08T09:07:53.373Z	ERROR  	executor(733)	_execute_command_in_container	Exception: 'charmap' codec can't encode character '\u221e' in position 33656: character maps to <undefined>
```

[log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-86759-merge-2e80acd1b97c4b08b1/WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Legacy.Tests/43ba0e63-456f-4d31-b743-10e9de3d6bfe.log?helixlogtype=result)

**Comment by pavelsavara** [comment]
I created PR on that internal repo https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/32863 somebody please review

**Comment by radical** [comment]
cc @akoeplinger

**Comment by pavelsavara** [comment]
@dougbu the build on that internal PR failed and I don't know what to do next about it. Please help.

**Comment by dougbu** [comment]
I commented in the PR. in the future, please tag @dotnet/dnceng rather than me individually

**Comment by dougbu** [comment]
using the default issue template here would have helped as well

**Comment by pavelsavara** [comment]
PR merged
