### ISSUE TITLE
Update NodeJS on Ubuntu queues to `11.5.3`

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#13399]
As per the discussion in https://github.com/dotnet/xharness/pull/1014

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Updated `nodejs` on Ubuntu off-prem queues to `11.5.3`

**Comment by premun** [comment]
@ilyas1974 is this one the vendors could take? Could they also have a look why this artifact is not being updated like the others?

**Comment by ilyas1974** [comment]
@premun - Let me know about the vendors doing this. I think with all the issues we recently had with Helix-Machines, our vendor team has been on hold with changes. 

Also, what version(s) of Linux does this apply to and are you sure this isn't a docker request (as most of the runs are done in containers and not on the base os? And what architectures?

**Comment by premun** [comment]
> Let me know about the vendors doing this. I think with all the issues we recently had with Helix-Machines, our vendor team has been on hold with changes.

It seems this hasn't been updated in a very long time?

> Also, what version(s) of Linux does this apply to and are you sure this isn't a docker request (as most of the runs are done in containers and not on the base os? And what architectures?

Seems like we have one version of NodeJS we install in all Ubuntu queues. I guess that's by design?

I will ask the team whether they couldn't run this in a docker, maybe it's better than to touch our queues, yeah.

**Comment by ilyas1974** [comment]
As a general rule, our customers do not run on our Ubuntu machines "natively" - usually the queues are used to host the docker containers that are actually used.

**Comment by ilyas1974** [comment]
Also - https://dev.azure.com/dnceng/internal/_workitems/edit/4961

**Comment by ilyas1974** [comment]
@premun do you know if this is still an issue?

**Comment by premun** [comment]
I believe this should be instead resolved on client's end by them using a Docker image with the dependency as per https://github.com/dotnet/xharness/pull/1014
