### ISSUE TITLE
Update VS Preview 

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#13403]
Per request from customer, we need to move VS 17.6 P3 (currently in scouting) to the preview queue as they need to the features in this newer version before they can merge some pending changes. 

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
- Promote Visual Studio 17.6 Preview 3 to the "Preview" queues
- Promote Visual Studio 17.6 Preview 6 to the "Scouting" queues

**Comment by garath** [comment]
PR in [!31118](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/31118)
