### ISSUE TITLE
New Queue to support Android devices

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#13432]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Please create a new queue - windows.11.amd64.android.open to support the new devices we recently received. 
Devices are Pixel 6a and are running Android 32

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

Adding Windows.11.amd64.android.open queue to support new devices

**Comment by AlitzelMendez** [comment]
rolled out!
