### ISSUE TITLE
Python scripts should support Python 3

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/arcade#13433]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

There are python scripts in https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.Build.Tasks.Installers/build/deb-package-tool/scripts that aren't compatible with Python 3.  Python 2 is out of support by now, and Debian 12 will remove support for it entirely, so we probably need to update these scripts to be able to run on Python 3.

If it's not possible to author them to run in both versions of Python, this may be complicated because it would have to be coordinated with switching all of the CI images (that use deb-package-tool at least) to install Python 3 instead of Python 2).

For reference, this came up when we migrated to Debian 11, and the `python` command is no longer available by default:

- https://wiki.debian.org/Python/FAQ#Python_2_support
- https://github.com/dotnet/installer/pull/16283

FYI @marcpopMSFT @mmitche 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

**Comment by dougbu** [comment]
> /cc @dougbu and @garath because they've been working on this situation.

Not sure we're really "working on this situation." There have been Python issues that affected multiple Core-Eng repos but I believe ancient code that runs only on Python 2 hasn't come up recently &mdash; before this issue.

We're looking closest at #13186. That issue is problematic because SLES 12 supports only Python 3.4 and we need at least one newer package that is incompatible w/ that Python version.

**Comment by missymessa** [comment]
@ericstj I think this is something that Runtime needs to handle?

**Comment by ericstj** [comment]
I think the installer infrastructure is owned by @NikolaMilosavljevic, however it looks like @jkoritzinsky might have already helped out with this in https://github.com/dotnet/arcade/commit/dd4ebc53c8d02294838b825fd0bdcde3e616b9a1.

**Comment by jkoritzinsky** [comment]
Yes, I handled this to get the DEB packaging legs to run on Ubuntu 22.04

**Comment by missymessa** [comment]
> Yes, I handled this to get the DEB packaging legs to run on Ubuntu 22.04

Great! Are we able to close out this issue, or is there more work that needs to be done?

**Comment by jkoritzinsky** [comment]
Yes, I think we can close this. Any other work is tracked by https://github.com/dotnet/arcade/issues/13186.
