### ISSUE TITLE
Investigate Component Governance Detection task for dnceng build definitions

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#1346]
@riarenas commented on [Thu Nov 08 2018](https://github.com/dotnet/core-eng/issues/4595)

Every time I look at a build for OS onboarding I get the following message in a banner at the top of the screen:

`
This build does not have the required Component Governance Detection task installed. Help us protect and secure Microsoft by adding this build task. Simply follow the instructions at https://aka.ms/oss_addcg_smartbanner and email ossgetclean@microsoft.com for any questions.
`

---

@riarenas commented on [Fri Nov 09 2018](https://github.com/dotnet/core-eng/issues/4595#issuecomment-437457933)

This seems to appear on every build in dnceng. Not only OS onboarding builds.

**Comment by jcagme** [comment]
@riarenas what's the follow up on this issue?

**Comment by riarenas** [comment]
No clue. I just pointed out something I saw when running builds in dnceng. I see that step with a task is now inserted on every build, but I still have no idea what this is.

**Comment by jcagme** [comment]
I remember seeing that but it's been I while since the last time I saw it. Does it make sense to close this and file a new one if the banner appears again?

**Comment by riarenas** [comment]
Sure. I mostly wanted to see if anyone understood what this component governance thing was and if it would require any work from our part, but it looks like it's gone, and the automatic build step doesn't seem to be affecting any of our builds, so I'm fine with just closing until and if it becomes a thing.

**Comment by markwilkie** [comment]
Adding @sunandabalu for visibility
