### ISSUE TITLE
Implementing an emergency mode for Stage-DotNet pipeline

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade#13497]
## Motivation

Creating a optimized mode of the Stage-DotNet pipeline to be run in emergency situation as described in https://github.com/dotnet/arcade/issues/12261 

## Implementation

Introducing a emergency switch parameter to the pipeline as described in the [one-pager](https://github.com/dotnet/arcade/blob/main/Documentation/TeamProcess/One-Pagers/bcm-emergency-staging-pipeline-optimizations-12261.md) 
Rearranging the stages of the pipeline according to the value of the parameter - if true, stages are run in parallel where possible

**Comment by andriipatsula** [comment]
PR -> https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/31189

**Comment by andriipatsula** [comment]
The https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/31189 PR is merged. Closing this one.
