### ISSUE TITLE
Intermittent Build Issues Due to Concurrent File Access in Arcade: Need for Unique Output Paths Across Runtime Versions

### ISSUE THREAD

**Issue by ocallesp** [dotnet/arcade#13507]
### Build

I'm encountering a recurring issue with Arcade, particularly regarding [several pipelines](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?definitionScope=%5CVSUnitTesting) in our internal repository. They intermittently face build issues with `pdb2pdb.exe`, a problem that occurs with considerable frequency. Although this issue doesn't completely halt our operations, it imposes a significant delay as it necessitates a rebuild every time a pipeline fails.

The core of the problem lies in the fact that the file '<PROJECT>.pdb' cannot be accessed by the process because it's being used by another process concurrently.

This arises because `_DeployPortableSymbolsToSymStore` runs `pdb2pdb.exe`, designating the same output (`/out`) path across various runtime versions.

Our project incorporates various runtimes including linux-arm64, win-arm64, win-x86, among others. To illustrate:

_PdbConverterCommandLineArgs for linux-arm64 is as follows
`_PdbConverterCommandLineArgs = "<PATH>\linux-arm64\<DLL>" /out "<PATH SymStore>\Release\<PROJECT>\<FRAMEWORK>\<PROJECT>.pdb"`

Similarly, for win-arm64 it is:
`_PdbConverterCommandLineArgs = "<PATH>\win-arm64\<DLL>" /out "<PATH SymStore>\Release\<PROJECT>\<FRAMEWORK>\<PROJECT>.pdb"`

And for win-x86:
`_PdbConverterCommandLineArgs = "<PATH>\win-x86\<DLL>" /out "<PATH SymStore>\Release\<PROJECT>\<FRAMEWORK>\<PROJECT>.pdb"`

However, it appears there's an omission. For linux-arm64, I think the correct _PdbConverterCommandLineArgs should ideally be: `"<PATH>\linux-arm64\<DLL>" /out "<PATH SymStore>\Release\<PROJECT>\**<RUNTIME_IDENTIFIER>**\<FRAMEWORK>\<PROJECT>.pdb"`.

Support for multiple RuntimeIdentifier's is missing.

### Build leg reported

Build

### Pull Request

https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=7752226&view=logs&j=4032467e-dc57-5727-0bde-0b3f32a19231&t=d467e7d5-e028-5fd4-b25f-2746de72cefc&l=602

### Known issue core information

If this is an issue that could be causing build breaks across multiple respositories:
1. Edit this issue and add an error string in the JSON. Use the [Known Issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section)

 ```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by dougbu** [comment]
@ocallesp this is not actually a Core-Eng issue. it definitely doesn't affect enough services to be considered a `Known Build Error`.

Instead, you're dealing w/ a normal `msbuild` parallelism issue or perhaps a problem w/ `pdb2pdb` not cleaning up file locks consistently.
* If it's the first, @rainersigwald has some tools that help avoid the "multiple write" problem. you can also see a summary of potential issues of this type near the bottom of a binary log for your build (in Structured Log Viewer).
  * I seem to remember some issues like this relating to `pdb2pdb` in dotnet/aspnetcore. @wtgodbe do you remember how we fixed them❔
* If it's the second, suggest reaching out to the team that owns that tool. I think that's @agocke's team these days (he'll know where to point you if not)

Please move this issue to the appropriate repo (perhaps `VSUnitTesting`) once you've decided where it should go.

**Comment by ocallesp** [comment]
@dougbu
I am in the `VSUnitTesting `team.

Let me clarify if I understand correctly. You're stating that the repeated writing of pdb2pdb to the same output pdb file isn't the problem, but rather the issue lies in the lock file not being released. Am I interpreting your statement accurately? If that is indeed the case, should we consider transferring this ticket to the pdb2pdb owners for further investigation?

**Comment by dougbu** [comment]
@ocallesp I'm stating the problem is _either_ the repeated / parallel use of `pdb2pdb` or that the tool isn't releasing locks. IIRC we focused on the first possibility when resolving this in dotnet/aspnetcore.

either way, it's not anything to do with Arcade and it's not a broad outage. perhaps you should move the issue to your repo while determining if the issue likes there❔

**Comment by rainersigwald** [comment]
> However, it appears there's an omission. For linux-arm64, I think the correct _PdbConverterCommandLineArgs should ideally be: `"<PATH>\linux-arm64\<DLL>" /out "<PATH SymStore>\Release\<PROJECT>\**<RUNTIME_IDENTIFIER>**\<FRAMEWORK>\<PROJECT>.pdb"`.

This sounds reasonable to me. The definition of this is in Arcade, so I don't think I understand your pushback @doubgu.

https://github.com/dotnet/arcade/blob/2d8d59065b5e090584a8e90c4371fc06ed60bdc5/src/Microsoft.DotNet.Arcade.Sdk/tools/SymStore.targets#L28-L32

**Comment by dougbu** [comment]
my apologies @ocallesp and @rainersigwald, I didn't realize `_PdbConverterCommandLineArgs` was part of the Arcade SDK. Guess I never had reason to use that feature&hellip;

the problem is in Arcade but it seems @ViktorHofer and @tmat have been the primary maintainers of src\Microsoft.DotNet.Arcade.Sdk\tools\SymStore.targets. I am missing information on how `linux-amd64` is "special" and why the `DeployToSymStore` target runs multiple times w/in a single build step. the target isn't referenced in dotnet/arcade at all.

**Comment by ocallesp** [comment]
@dougbu I would like to clarify that `linux-amd64` is not special. It was merely used as an example.

In the description of this issue I mentioned that a project has many runtimes but all of them are writing to the same output pdb.

**Comment by dougbu** [comment]
@ViktorHofer, @tmat is multiple `$(RuntimeIdentifier)`s in a single project a supported feature where `DeployToSymStore` is used❔ should it be❔

if yes, it's probably a one line addition e.g.,
``` msbuild
<_SymStoreOutputDir Condition="'$(RuntimeIdentifier)' != ''">$(_SymStoreOutputDir)$(RuntimeIdentifier)\</_SymStoreOutputDir>
```

I'd put that after the following as builds targeting multiple runtimes per `$(PlatformName)` is likely more common than the reverse
``` msbuild
<_SymStoreOutputDir Condition="'$(PlatformName)' != 'AnyCPU'">$(_SymStoreOutputDir)$(PlatformName)\</_SymStoreOutputDir>
```

But first, should this be supported❔

**Comment by ocallesp** [comment]
In case you decide this is not supported, is there a workaround?

One option we've come across, although not recommended, is disabling pdb2pdb by setting the property `PublishWindowsPdb = false`. This approach may have some drawbacks. It can potentially lead to the symbol check task failing during insertions and may also affect developers when debugging crashes.

**Comment by ocallesp** [comment]
PR https://github.com/dotnet/arcade/pull/13598

**Comment by ocallesp** [comment]
Resolution: _"PDB conversion had only been necessary until Watson and WinDBG added support for Portable PDB. These tools have been updated so there is no need to public converted Windows PDBs.

The only remaining minor issue is that VS insertion use symchk tool that still hasn't been updated to support Portable PDBs. But that can be worked around by updating the list in VS for now until this tool is also updated. Arcade publishing itself ensures that PDBs have been published for any shipping binary, so the validation in VS is superfluous anyways."_
