### ISSUE TITLE
Arcade breaking change in signing behavior

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#1350]
@dotnet-mc-bot commented on [Fri Nov 16 2018](https://github.com/dotnet/core-eng/issues/4673)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2215120
  - **Agent:** DDVSOWINAGE084
  - **Error log:** E:\A\_work\0\s\corefx\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18565.8\tools\Sign.proj(0,0): error : List of files to sign is empty. Make sure that ItemsToSign is configured correctly....

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2215121
  - **Agent:** DDVSOWINAGE085
  - **Error log:** E:\A\_work\0\s\corefx\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18565.8\tools\Sign.proj(0,0): error : List of files to sign is empty. Make sure that ItemsToSign is configured correctly....

@jcagme, @markwilkie

---

@MattGal commented on [Fri Nov 16 2018](https://github.com/dotnet/core-eng/issues/4673#issuecomment-439461704)

I'm pretty sure this was a regression introduced by https://github.com/dotnet/corefx/commit/4b9db6c88f31d7f0f5f69e693a65a748e82823d1 , an Arcade-auto update.  I'm chatting with @jcagme and will ask @JohnTortugo  as well.

---

@MattGal commented on [Fri Nov 16 2018](https://github.com/dotnet/core-eng/issues/4673#issuecomment-439463537)

I'm torn whether to call this ToolsError or SourceCode here, but going with source for now (since a target that signs things seems to be getting invoked and erroring when nothing's there).  Will move this to Arcade to investigate.

**Comment by MattGal** [comment]
@JohnTortugo  FYI.  May totally be by-design and intentional, but it's worth noting since [an arcade update](https://github.com/dotnet/corefx/commit/4b9db6c88f31d7f0f5f69e693a65a748e82823d1) which made it past CI ended up breaking the official build

**Comment by MattGal** [comment]
From Joe's investigation looks like it just needs to honor preexisting values for AllowEmptySignList

https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.proj#L43

**Comment by joperezr** [comment]
right, the problem is that this property is not conditioned:

https://github.com/dotnet/arcade/blob/995d5bc5507f25475368368ecd6fef4252e8232d/src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.proj#L41-L44

What we should have is something like: `<AllowEmptySignList Condition="'$(AllowEmptySignList )' == ''">false</AllowEmptySignList>` instead

**Comment by JohnTortugo** [comment]
Thanks for looking into that guys. @joperezr the idea is that repos override that property in their `Signing.props` which is included after "declaring" that property: https://github.com/dotnet/arcade/blob/995d5bc5507f25475368368ecd6fef4252e8232d/src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.proj#L47

**Comment by joperezr** [comment]
I see that makes sense, I didn't see that we imported the Signing props right after that. I would probably still add a comment on the import or the property mentioning that the order of those two matter a lot, that way if there is some refactoring that happens on these files in the future it won't break repos that define the property staticly.

**Comment by JohnTortugo** [comment]
Thanks @joperezr . I'll add that comment. 

FYI: I'm also looking to check how we can catch such errors next time before we merge the maestro PRs in the master branch.

**Comment by joperezr** [comment]
> FYI: I'm also looking to check how we can catch such errors next time before we merge the maestro PRs in the master branch.

FWIW, coreclr has a on-demand CI build that will test the ingestion of this coreclr into corefx, and see if that would break corefx. You could potentially have something similar here.

**Comment by JohnTortugo** [comment]
From a quick look that I did with @jcagme it seems that at least for corefx builds we don't do test sign on CI builds, which means that signing issues related to repo configuration won't be tested before the merge happens! I'll look more into that. 

@chcosta

**Comment by chcosta** [comment]
Hmm... I think this falls into the scenario testing bucket which we're starting to explore such that we can provide an Arcade LKG.  I wouldn't expect any signing to be happening (even test signing) in a CI build.

**Comment by MattGal** [comment]
Signing wouldn't need to occur to catch this issue.  You could override the Microbuild Sign* targets with nerfed ones that just use the Message task to print out the parameters they received, then "sign" things as usual.  If that were happening, the error (You didn't ask to sign anything) would still have happened
