### ISSUE TITLE
dotnet-helix-machines-ci failure in queue validation 

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade#13515]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

`Validate on-prem queues` stage in `dotnet-helix-machines-ci` is failing at sending test jobs to helix queues with `"Errors":["The Creator property is required.","The Creator property is required."]}`
Log: https://dev.azure.com/dnceng/internal/_build/results?buildId=2179423&view=logs&j=64055507-1fa1-5236-6b45-2026e01f604b&t=59c8a4ec-73f6-5458-7c14-97d6bec4e3b2
https://dev.azure.com/dnceng/internal/_build/results?buildId=2179053&view=logs&s=33460554-8d19-50d0-9581-26581ffff7b4&j=64055507-1fa1-5236-6b45-2026e01f604b

It can be a expired token or a issue that comes from `helix-service`

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Not release note worthy

**Comment by dkurepa** [comment]
I think this PR should fix the issue https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/31258. I'm not sure why we started seeing it recently. I don't see that anything relevant has changed recently

**Comment by garath** [comment]
This was caused by an expiring secret. Or, more precisely, it was caused by me incorrectly generating a new secret to replace an expiring secret. The new secret never actually had permissions to anything, so validation failed. 

Your instinct of "It could be an expired token" was correct :smile:

**Comment by garath** [comment]
@dougbu is working on stepping everything back over in [!31267](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/31267) and confirming that the build returns to green.

**Comment by ilyas1974** [comment]
Issue is resolved.
