### ISSUE TITLE
Rerunning the "Publish CTI Validated Assets" stage cause the "Publish Assets to Staging Location/Publish Log" step to fail.

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade#13517]
Pipeline run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2160139&view=logs&j=08d96039-50ac-56c2-563d-65d9179dcbf0

## Motivation:
Currently each run of the Staging pipeline produces some number of warning and errors. One of our goals is to make the Release Infrastructure more reliable.

## Work Items:
> ##[error]Artifact PublishAssetsLogs already exists for build 2160139.

`Publish Assets to Staging Location/Publish Logs` should check if the folder (from previous attempt) already exists and if yes - rename it. You can use a datetime suffix or determine use an attempt number.

**Comment by MilenaHristova** [comment]
@andriipatsula I think here there's no need to check if it exists, I propose we just name the folder with the attempt number so that there's no conflicts

**Comment by MilenaHristova** [comment]
this is done with https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/31602
