### ISSUE TITLE
Ensure it's possible to mirror multiple packages at once

### ISSUE THREAD

**Issue by tkapin** [dotnet/arcade#13527]
Based on feedback from @jaredpar, mirroring multiple packages one-by-one is inconvenient.

The [migrate-package](https://dev.azure.com/dnceng/internal/_git/dotnet-migrate-package) utility allows for specifying multiple packages at once, it's necessary to check if it's possible to specify this also in the [dotnet-migrate-package](https://dev.azure.com/dnceng/internal/_build?definitionId=931). 

It should be possible to specify either migrating the latest versions of multiple packages, or a set of (package, version) pairs.

**Resources**
* Documentation in Arcade at [MirroringPackages.md](https://github.com/dotnet/arcade/blob/main/Documentation/MirroringPackages.md)
* Pipeline used to run the mirroring - [dotnet-migrate-package](https://dev.azure.com/dnceng/internal/_build?definitionId=931&_a=summary)
* AzDo Repo - [dotnet-migrate-package](https://dev.azure.com/dnceng/internal/_git/dotnet-migrate-package)

**Comment by chcosta** [comment]
ack, i'll take a look this week :)

**Comment by chcosta** [comment]
This was resolved with a fix
