### ISSUE TITLE
User Scenarios to explore CloudTest

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#13556]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We need to provide all the various use cases we use Helix, so that we can run it by CloudTest team so that they can vet it out. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by chcosta** [comment]
Shared doc with CloudTest (dm @chcosta for link).  chcosta to follow-up.

**Comment by chcosta** [comment]
follow-up meeting occurred on 6/21
