### ISSUE TITLE
Feature differences between Helix vs CloudTest 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#13550]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We need to understand the feature difference between Helix and CloudTest.

Main concerns or questions to address 
1) What does CloudTest offer that Helix doesn't currently provide. 
2) What are the customized things that we will miss out from Helix 
3) Also explore CloudTest 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
Epic issue closed. Let's retriage.

**Comment by epananth** [comment]
closing this
