### ISSUE TITLE
Async Triage Tool Updates

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#13586]
- [ ] Async Triage Tool will need to be updated to understand our new way of handling the concept of an epic. 
    - [ ] Should look at issues in dotnet/arcade
    - [ ] Should look at issues in dotnet/dnceng
- [ ] Inform the vendors of the update (in case they need to fetch the code changes)

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
We'll probably be deprecating Async Triage tool. Will close this issue if that happens.

**Comment by garath** [comment]
Closing as the Async Triage tool can be deprecated. See dotnet/dnceng#558.
