### ISSUE TITLE
Change Helix API response for an unauthenticated request

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade#13605]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Reported on FR: https://github.com/dotnet/arcade/issues/13520

When querying work item results without providing a token the Helix API response is misleading - doesn't show the correct information and doesn't mention that the the user should provide a token
For example 
in https://helix.dot.net/api/jobs/3368452d-cca0-4844-bb49-59aa8aec4c11/workitems/Partition1?api-version=2019-06-17 work item is "Unscheduled"
meanwhile https://helix.dot.net/api/jobs/3368452d-cca0-4844-bb49-59aa8aec4c11/workitems/Partition1?api-version=2019-06-17&access_token=[ACCESS TOKEN] returns the actual information that's also in Kusto
Maybe the response can be changed to mention the need for a token

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
Adding this information in the error message is a security concern. Sorry :(
