### ISSUE TITLE
Pin NugetVersion in Staging pipeline

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#13601]
In the `Download RM Package` job we're installing NuGet with the `NuGetToolInstaller@1` task. We technically have a variable for the nuget version we want to install, `nugetVersion` but we're not initializing it so the task just downloads the most recent version.
Recently, the version got bumped from 6.5.0 to 6.6.0 (https://dist.nuget.org/tools.json) and this is causing errors in the Staging pipeline https://dev.azure.com/dnceng/internal/_build/results?buildId=2182812&view=logs&j=16f90517-043a-56a2-38d5-ecc42e209b1a&t=09a2ec16-21db-5d02-1df2-d76b52acc168. I will pin the version to 6.5.0 to unblock the pipeline.

**Comment by andriipatsula** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/31322

**Comment by dkurepa** [comment]
This has been completed
