### ISSUE TITLE
Investigate the cause of the `Download RM Package` job failure using Nuget version 6.6.0

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade#13604]
Work around: https://github.com/dotnet/arcade/issues/13601

The NuGetToolInstaller@1 task installs the latest Nuget if the `nugetVersion` variable is not specified.
Following the recent update of NuGet version from 6.5.0 to 6.6.0 (https://dist.nuget.org/tools.json), the `NuGet Install VSEng Nuget Package job` has started to fail.
> ##[warning]Can't find loc string for key: Info_NuGetSupportedAfter3_5
##[error]Info_NuGetSupportedAfter3_5 6.6.0-preview.3+0fa557836fa35aee7d60776ef0c88176dbcd22ac.0fa557836fa35aee7d60776ef0c88176dbcd22ac

pipeline link: https://dev.azure.com/dnceng/internal/_build/results?buildId=2182758&view=logs&j=f6a410f0-0e92-5473-3b66-3f206fe668e5&t=33fefec8-09d7-51f2-9ca1-4897122e44d7

**Comment by dkurepa** [comment]
The internet doesn't have a lot to say about those error messages :/

**Comment by MilenaHristova** [comment]
@dkurepa does this explain the error https://status.dev.azure.com/_event/390743653

**Comment by dkurepa** [comment]
I think it does, I will try reverting the PR

**Comment by andriipatsula** [comment]
the issue is resolved.
