### ISSUE TITLE
Team specific shared properties

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#1361]
From: Jacques Eloff <joeloff@microsoft.com> 
Sent: Monday, November 19, 2018 10:30 AM
To: Mark Wilkie <mawilkie@microsoft.com>; Alex Perovich <Alex.Perovich@microsoft.com>; Arcade Working Group <arcadewg@microsoft.com>
Subject: RE: shared properties for multiple packages

Rummaging through the binlog I found ProjectDefaults.props. This would seem like a good place to have something like <Import Project=”$(ImportAfterDefaultProps)” Condition=’$(ImportAfterDefaultProps)’ != ‘’ />

ProjectDefaults.props seems to define a lot of items specific to .csproj files and other properties like Company, LicenceUrl, etc. that are common to packages, unless this file is more intended for the assemblies than the packages.

I can just place the common props file locally in the src folder for now and have my projects just import it. If we come up with official guidance it should be simple to change

From: Mark Wilkie <mawilkie@microsoft.com> 
Sent: Monday, November 19, 2018 10:26 AM
To: Alex Perovich <Alex.Perovich@microsoft.com>; Jacques Eloff <joeloff@microsoft.com>; Arcade Working Group <arcadewg@microsoft.com>
Subject: RE: shared properties for multiple packages

The challenge here is the “cluttering up” of the eng folder w/ team specific packages.  I think what Jacques is asking for is a way to manage “families” of product/team specific projects with shared properties.

From: Alex Perovich <Alex.Perovich@microsoft.com> 
Sent: Monday, November 19, 2018 10:21 AM
To: Mark Wilkie <mawilkie@microsoft.com>; Jacques Eloff <joeloff@microsoft.com>; Arcade Working Group <arcadewg@microsoft.com>
Subject: RE: shared properties for multiple packages

In the arcade repo we have put shared targets files directly in the eng folder and just import them from projects that need them. I don’t know if we have any specific guidance though.

From: Mark Wilkie <mawilkie@microsoft.com> 
Sent: Monday, November 19, 2018 10:19 AM
To: Jacques Eloff <joeloff@microsoft.com>; Arcade Working Group <arcadewg@microsoft.com>
Subject: RE: shared properties for multiple packages

BCCing dnceng and adding Arcade working group

Don’t think we’ve encountered this yet – but having guidance would be good.  Thoughts from the Arcade working group?

From: Jacques Eloff <joeloff@microsoft.com> 
Sent: Monday, November 19, 2018 10:10 AM
To: Mark Wilkie <mawilkie@microsoft.com>; .NET Core Engineering <dnceng@microsoft.com>
Subject: RE: shared properties for multiple packages

Hi Mark

The WebSDK repo that I’m converting produces three packages:

Microsoft.NET.Sdk.Publish.3.0.100-dev.nupkg
Microsoft.NET.Sdk.Web.3.0.100-dev.nupkg
Microsoft.NET.Sdk.Web.ProjectSystem.3.0.100-dev.nupkg

The package description, tag, copyright, etc. are all the same, so duplicating that in the individual .csproj files means having to change it in 3 places in the future. I can easily add something like commonpackage.props and just import that into the project files, but I figured that Arcade might have an extension point for this sort of thing. I was hoping for something like eng\Packages.props

eng\Versions.props seems like another props file that’s shared, though I don’t want to clutter up the version properties with other items

Jacques

From: Mark Wilkie <mawilkie@microsoft.com> 
Sent: Monday, November 19, 2018 10:04 AM
To: Jacques Eloff <joeloff@microsoft.com>; .NET Core Engineering <dnceng@microsoft.com>
Subject: RE: shared properties for multiple packages

This is a good question Jacques – could you expand a bit with your specific example?

From: Jacques Eloff <joeloff@microsoft.com> 
Sent: Friday, November 16, 2018 3:10 PM
To: .NET Core Engineering <dnceng@microsoft.com>
Subject: shared properties for multiple packages

Hi

Is eng\build.props a good place to define common package properties, e.g. if you’re building multiple packages using separate project files, but you want the same package description. Or should one rather define a separate file that all the package project files can import that’s outside of the eng folder?

Thanks,
Jacques

**Comment by markwilkie** [comment]
@chcosta - this is the issue I was trying to remember the other day as an FYI

**Comment by chcosta** [comment]
Now I need to try to remember why you were trying to remember this issue..

**Comment by markwilkie** [comment]
grin - this had to do w/ extensibility or guidance for what to do with scripts that are specific to teams, but should (perhaps) be a part of eng/  (e.g. picked up by darc)

**Comment by markwilkie** [comment]
Closing....bigger fish to fry and folks haven't been running into this.
