### ISSUE TITLE
sles-15-sp3-basic is no longer available in the Azure Marketplace

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#13615]
sles-15-sp3-basic is no longer available in the Azure Marketplace. I do not know why.

Either the queues must be deprecated, or they must be moved to a supported version of SLES (as in, one available in the Marketplace).

Note that the easiest way to see this conflict is to use the OsobCli tool. From the root of the helix-machines repository, run:

```bash
dotnet run --project .\tools\OsobCli\OsobCli.csproj -- list-image-versions --definitions-directory .\definitions\
```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by dougbu** [comment]
@garath I think this was fixed in [!31787](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/31787). Please close if I'm correct

**Comment by garath** [comment]
Yes, looks like @dougbu found only that sp3 was not found, but sp4 is available.
