### ISSUE TITLE
Create Ubuntu 22.04 based Helix queues for Android instead of 18.04

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/arcade#13619]
We want to move off of the soon-deprecated 18.04 Ubuntu images in https://github.com/dotnet/runtime/pull/86194, but right now we only have these for the Android queues:
`Ubuntu.1804.Amd64.Android.29.Open`

We'll need to create queues based off of Ubuntu 22.04.

/cc @ilyas1974 

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Adding Ubuntu 22.04 to support Android Simulators

**Comment by akoeplinger** [comment]
@ilyas1974 what is the current status of this?

**Comment by ilyas1974** [comment]
Sorry for not updating this issue - it has been rolled out.
