### ISSUE TITLE
SignCheck --verify-strongname fails on native .dll/.exe files

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1362]
The `--verify-strongname` flag on SignCheck creates a false-positive error on native .dll/.exe files. These don't have a strong name because they are not .NET binaries.

**Repro:**
Download https://www.nuget.org/api/v2/package/dotnet-ef/2.1.4
Run sign check on it:
```
microsoft.dotnet.signcheck.exe -i .\dotnet-ef.2.1.4.nupkg --recursive --verify-strongname
```

**Expected**
Sign check only produces strong-name errors for managed, .NET assemblies that are missing a strong name.

**Actual**
Sign check flags the `dotnet-ef.exe` files, which are non-.NET native executables.
```
[File] dotnet-ef.2.1.4.nupkg, Signed: True
  [File] 54f9627c062431c5c1718eeb471f84ca.exe, Signed: False, Full Name: tools/netcoreapp2.1/any/shims/win-x64/dotnet-ef.exe
  [File] 696221522c7f479ed2955bd6c11079f7.exe, Signed: False, Full Name: tools/netcoreapp2.1/any/shims/win-x86/dotnet-ef.exe
```

cc @bricelam @Eilon  @joeloff

**Comment by joeloff** [comment]
Yeah, that's wrong. It's supposed to check if it's native code or not. I'll take a look
