### ISSUE TITLE
Timeouts during "Deploy1ESHostedPools" stage in Helix-machines

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#13620]
- [X] This issue is blocking 
This blocks the production rollout of the repo
- [ ] This issue is causing unreasonable pain

Build https://dnceng.visualstudio.com/internal/_build/results?buildId=2183353 has been consistently timing out during the 1ES Hosted pol deployment stage. 

The logging always stops when attempting to check the existence of the 1ES managed identity and then times out with error:

```
##[error]D:\a\_work\1\s\Deploy1ESHostedPools.dll(,): error : Cloud error during operation : Long running operation failed with status 'Canceled'. Additional Info:'The request has been completed with result Canceled. Please check details with more information.'
```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
(To do)

**Comment by dougbu** [comment]
attempt **6** and counting ☹️

**Comment by garath** [comment]
I put in a ticket with the Hosted Pool team for help.

In the meantime, here's a potential work-around: [Pull request 31435: Avoid redeploying Hosted Pools - Repos (azure.com)](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/31435)

**Comment by garath** [comment]
Opened [ICM 391637079](https://portal.microsofticm.com/imp/v3/incidents/details/391637079/home)

**Comment by garath** [comment]
With remarkably short turn-around, the owning team responded to the ICM with concrete suggestions! I'll start going through them.

**Comment by garath** [comment]
Merged [!31435](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/31435) as a work-around. The subsequent main-branch [build 2186050](https://dev.azure.com/dnceng/internal/_build/results?buildId=2186050) was successful. Yay!

**Comment by garath** [comment]
I'm taking this issue to track the ICM and movement to a proper fix.

**Comment by garath** [comment]
The ICM is marked as mitigated and all seems to be well.
