### ISSUE TITLE
Generate Xcopy msbuild 17.6.0

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade#13621]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Based on a [failure](https://dev.azure.com/dnceng/internal/_build/results?buildId=2183208&view=logs&j=b11b921d-8982-5bb3-754b-b114d42fd804&t=fb192a8b-e433-5fc8-e2b0-276ab015e7d5) reported on FR with
```
Version 8.0.100-preview.4.23260.5 of the .NET SDK requires at least version 17.6.0 of MSBuild. The current available version of MSBuild is 17.4.0.51802. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.
```
We should generate version 17.6.0 of `RoslynTools.MSBuild` and publish it to `dotnet-eng` then update the version in arcade scrips like in https://github.com/dotnet/arcade/pull/11266

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by dkurepa** [comment]
This work was completed. We also wrote instructions on how to do this, if it's needed again https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1074/RoslynTools.MSBuild-(xcopy-msbuild)-generation
