### ISSUE TITLE
`Publish workloads to VSDROP` can't find `Microsoft.SourceLink.AzureRepos.Git` package

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade#13630]
The `Restore workloads.csproj` step of `Publish workloads to VSDROP` in the staging pipeline is failing because it can't find `Microsoft.SourceLink.AzureRepos.Git` package
https://dev.azure.com/dnceng/internal/_build/results?buildId=2183718&view=logs&j=173b5010-12b9-52a5-cd40-2f635e6c8571&t=42c38e86-cdf5-5f58-3249-aa2d8c607b6f

```
D:\a\_work\1\s\.dotnet\dotnet.exe restore --configfile D:\a\_work\1\s\src\workloads\NuGet.config --packages D:\a\_work\1\s\.packages D:\a\_work\1\s\src\workloads\workloads.csproj
  Determining projects to restore...
D:\a\_work\1\s\src\workloads\workloads.csproj : error NU1102: Unable to find package Microsoft.SourceLink.GitHub with version (>= 8.0.0-beta.23252.2)
D:\a\_work\1\s\src\workloads\workloads.csproj : error NU1102:   - Found 701 version(s) in dotnet-core-internal-tooling [ Nearest version: 8.0.0-beta.23221.1 ]
D:\a\_work\1\s\src\workloads\workloads.csproj : error NU1102: Unable to find package Microsoft.SourceLink.AzureRepos.Git with version (>= 8.0.0-beta.23252.2)
D:\a\_work\1\s\src\workloads\workloads.csproj : error NU1102:   - Found 690 version(s) in dotnet-core-internal-tooling [ Nearest version: 8.0.0-beta.23221.1 ]
  Failed to restore D:\a\_work\1\s\src\workloads\workloads.csproj (in 8.7 sec).
```

The cause is that `Microsoft.SourceLink` s latest version is now in `dotnet8` feed instead of `dotnet-tools` 
`src\workloads\NuGet.config` contains https://pkgs.dev.azure.com/devdiv/_packaging/dotnet-core-internal-tooling/nuget/v3/index.json feed
We probably need to add `dotnet8` feed as upstream to the `dotnet-core-internal-tooling` feed

**Comment by andriipatsula** [comment]
Specified dotnet8 as an Upstream Sources for the `dotnet-core-internal-tooling` feed. Restored locally and 
https://dev.azure.com/devdiv/DevDiv/_artifacts/feed/dotnet-core-internal-tooling/NuGet/Microsoft.SourceLink.GitHub/overview/8.0.0-beta.23252.2
