### ISSUE TITLE
Arcade update builds failing for testfx and vstest

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#13648]
A customer reported some failing builds for their [arcade-update](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1684745638789?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1684745638789&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1684745638789). The update only contains these changes, and has been passing in other repos without any issues. Also, the repos had a successful arcade update on the same day

**Comment by Evangelink** [comment]
It's also failing here https://github.com/dotnet/roslyn-analyzers/pull/6645

**Comment by ViktorHofer** [comment]
Taking a look now

**Comment by ViktorHofer** [comment]
Repositories that use Desktop MSBuild (i.e. for signing) will need Visual Studio 17.6. I reached out to @garath offline and asked if we can update the VS version as 17.5 is already out-of-support since May 16th.
