### ISSUE TITLE
Arcade tools bootstraping fails on Linux if dotnet sdk is installed globally

### ISSUE THREAD

**Issue by jkotas** [dotnet/arcade#1364]
Repro:

```
docker -it microsoft/dotnet:2.1-sdk
apt-get install clang-3.9 cmake make libc6-dev libssl-dev libkrb5-dev libcurl4-openssl-dev zlib1g-dev
cd $HOME
git clone https://github.com/dotnet/corefx
cd corefx
./build.sh
```

Result:

Build fails with

```
/root/corefx/eng/Tools.props(56,5): error MSB3073: The command "/root/.nuget/packages/microsoft.dotnet.buildtools/3.0.0-preview1-03415-01/lib/init-tools.sh /root/corefx/ /root/corefx/.dotnet/dotnet /root/corefx/Tools /root/.nuget/packages/ > /root/corefx/init-tools.log" exited with code 1. [/root/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.18565.8/tools/Tools.proj]
```

**Comment by jkotas** [comment]
`init-tools.log` contains the following error:
`
ERROR: Cannot find dotnet.exe at path '/root/corefx/.dotnet/dotnet'. Please pass in the path to dotnet.exe as the 2nd parameter.
`

The problem seems to be on the path where the scripts detect the globally installed dotnet and try to use it instead of downloading local copy. The globally installed dotnet is not wired in correctly.

**Comment by markwilkie** [comment]
I think this is a known issue.  @chcosta or @jcagme - do you remember the details?

**Comment by chcosta** [comment]
AFAIK, this is not a known (or reported) issue.

**Comment by jcagme** [comment]
Yeah I don't think this is known. Epic updated and will prioritize accordingly.

**Comment by marek-safar** [comment]
@jcagme what is the update on the priority? We are hitting this working on CoreFX for Mono on Mac as well.

**Comment by jcagme** [comment]
Not sure on my end but I think @tmat was maybe looking at it?

**Comment by tmat** [comment]
I think [these lines](https://github.com/dotnet/corefx/blob/master/eng/Tools.props#L15-L17) should be removed and the usage of `DotNetCmd` replaced with `DotNetTool` defined [here](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/RepoLayout.props#L30-L41).

**Comment by jcagme** [comment]
I've tried this on ubuntu-16.04-c103199-20180628134544 where I installed dotnet SDK 2.1.4 before running `build.sh` and I was not able to repro.

In case it continues to be an issue please file a new issue.
