### ISSUE TITLE
Arcade depends on the deprecated WindowsAzure.Storage package

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#13683]
The WindowsAzure.Storage package is deprecated and should be replaced with `Azure.Storage.Common`: https://www.nuget.org/packages/WindowsAzure.Storage

https://github.com/dotnet/arcade/blob/0b89b3c809549f07eb52dfdd62c1173ad6b4c460/eng/Versions.props#L108-L110C6

The library is currently used in couple of places in the repo and is undesirable for another reason: It brings in the entire netstandard1.x dependency graph (which includes vulnerable packages). By replacing it, we don't need to manually bump vulnerable package versions anymore.

cc @MilenaHristova @tkapin

**Comment by MilenaHristova** [comment]
the Engineering Services team owns arcade so we'll leave it to them to triage this. 
I had a look and I see only one use of the package that could even be removed, I may be missing something though

**Comment by ViktorHofer** [comment]
Does the Engineering Services Team have a GH group that we can ping here?

**Comment by tkapin** [comment]
To update a bit, arcade is the shared tooling where the overall ownership lies with dnceng, but it's a shared tooling where everyone is encouraged to make changes. This needs to get triaged to find the scope of the work. /cc @dotnet/dnceng

**Comment by riarenas** [comment]
The only project I see using it is https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.GitSync.CommitManager/Microsoft.DotNet.GitSync.CommitManager.csproj#L19

I don't believe this tool is maintained by dnceng as it was brought in from buildtools by corefx folks. The tool is not published anywhere. The fact that the only changes we have seen in this area are playing whac-a-mole with component governance, and that it was related to the old maestro in the old corefx world makes me think this code should be deleted along with the other project mentioned in https://github.com/dotnet/arcade/blob/main/Documentation/GitSyncTools.md

**Comment by ViktorHofer** [comment]
We (dotnet/runtime, dotnet/corefx, dotnet/coreclr and dotnet/core-setup) don't use these tools anymore. I don't know the history behind them but I would be surprised if they are still used. Based on https://github.com/dotnet/arcade/pull/289 it sounds like those were used for the mirrored folders between the repos. We don't do that anymore.

cc @ericstj
