### ISSUE TITLE
Deadletter osx.1015.amd64.iphone.open queue

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#13705]
The product teams have recently moved their workloads out of the osx.1015.amd.iphone.open queue. To allow us to migrate the physical machines within this queues to the osx.13.amd64.iphone.open queue, we want to deadletter the existing queue to make sure work items don't get stuck in a queue without resources. 

Please update the Helix-Machines YAML to set the osx.1015.amd64.iphone.open queue to forward work items to deadletter. 
Additionally, starting Friday, May 26, please manually enable the osx.10.15.amd64.iphone.open queue to forward work items to deadletter. 

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Deadletter osx.1015.amd64.iphone.open queue

**Comment by steveisok** [comment]
/cc @dotnet/runtime-infrastructure 

We have moved runtime traffic off of this queue, so there should be no impact.  Letting you all know just in case.

**Comment by AlitzelMendez** [comment]
@ilyas1974 are we only doing the Deadletter for osx.1015.amd64.iphone.open?
or also OSX.1015.Amd64.Iphone and OSX.1015.Amd64.Iphone.Perf?

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/31557

Doing the deadletter tomorrow morning :)

**Comment by AlitzelMendez** [comment]
I did the Deadletter on service bus for osx.1015.amd64.iphone.open
