### ISSUE TITLE
Check if SignTool is working properly when we have managed binaries that aren't strong-name signed

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#1370]
@ericstj mention that it may happen that some repo have managed binaries that don't need to be strong-name signed. The current implementation of signtool assumes that all managed binaries will need to be strong-name signed, we might need to check that assumption in the future.

Worth noting that the current implementation also allow:
- Disabling the validation on strong-name
- Exclude specific files from the validation while still doing validation in the general case

**Comment by Chrisboh** [comment]
Closing as this hasn't been an issue.
