### ISSUE TITLE
AzDO hides failed tests in case of another job timeing out

### ISSUE THREAD

**Issue by ManickaP** [dotnet/arcade#13704]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

In https://github.com/dotnet/runtime/pull/86342, I was making changes that were expected to cause failed tests, but [AzDO didn't show the jobs as failed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=285739&view=ms.vss-test-web.build-test-results-tab&runId=5691572&resultId=178729&paneView=debug), but with a "play" icon. When expanded, the failed test is there as expected, but one have to know, that this ambiguous blue icon can also mean failure:
![obrazek](https://github.com/dotnet/arcade/assets/11718369/ae06f1d1-30d0-4127-b334-9726ed450df0)

In the end, it turned out that that [particular leg](https://dev.azure.com/dnceng-public/public/_build/results?buildId=285739&view=logs&j=1f44e919-17d8-5098-631c-31ef11f9e57b&t=d617d884-da52-5b82-bd49-f7613b408af4) had another job that timed out:
![obrazek](https://github.com/dotnet/arcade/assets/11718369/26f2cb30-2450-4149-b3e0-57be0266b8fd)

I think that failed test should always show as a failure no matter what.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
@ManickaP unfortunately, this is how AzDO has chosen to display their tests.
