### ISSUE TITLE
Downgrade DependencyModel to latest preview release

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/arcade#13718]
Follow-up work to https://github.com/dotnet/arcade/issues/13471 based on https://github.com/dotnet/arcade/pull/13473#issuecomment-1563573726

Arcade's dependency on latest version of a `runtime` package is far from ideal and based on comments from Viktor and Matt (linked above) should be replaced by the latest preview release version.

We should downgrade the current version to the target one + make sure this version gets bumped on new preview release.

**Comment by ViktorHofer** [comment]
> We should downgrade the current version to the target one + make sure this version gets bumped on new preview release.

Dependabot could help with that. We want to avoid using it for SBRPs but I don't see an issue when consuming N-1.

**Comment by mmitche** [comment]
That could work.

**Comment by oleksandr-didyk** [comment]
> Dependabot could help with that.

Can't Maestro deal with this?

**Comment by missymessa** [comment]
@oleksandr-didyk did your PR resolve this issue?

**Comment by oleksandr-didyk** [comment]
> @oleksandr-didyk did your PR resolve this issue?

Technically yes, just haven't gotten to configuring dependency-bot to auto-update the version to latest preview. Will separate it into its own issue and close this one
