### ISSUE TITLE
Error when creating a package using .net core sdk 3.0.100-preview-009764 and arcade sdk 1.0.0-beta.18569.4

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/arcade#1373]
Hello,
 
I moved winforms up to 3.0.100-preview-009764 of dotnet, and I’m getting an error when running .\build -pack locally:
 
Successfully created package 'E:\src\repos\github\winforms\artifacts\packages\Debug\Shipping\Microsoft.Private.Winforms.1.0.0-dev.nupkg'.
E:\src\repos\github\winforms\.dotnet\sdk\3.0.100-preview-009764\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(199,5): error NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead. [E:\src\repos\github\winforms\pkg\Microsoft.Private.Winforms.csproj]
 
Per email, it sounds like Arcade needs to use the new nuget properties.

To repro, set your global.json to this:

{
  "tools": {
    "dotnet": "3.0.100-alpha1-009703"
  },
  "msbuild-sdks": {
    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.18569.4"
  }
}

Then run .\build -pack

**Comment by markwilkie** [comment]
@AdamYoblick - is this still and issue?

**Comment by AdamYoblick** [comment]
I believe so. I had to add `<NoWarn>$(NoWarn);NU5125</NoWarn>` to my package project for pack to work. If arcade has fixed this, it's news to me :)

**Comment by markwilkie** [comment]
@chcosta / @jcagme - do either of you guys know the current status of this?

**Comment by chcosta** [comment]
There's a discussion with the Arcade working group.  I believe @tmat is working to get this updated (currently making sure an update here won't break source build).

**Comment by markwilkie** [comment]
Any update on this @tmat?

**Comment by tmat** [comment]
Not yet.

**Comment by jcagme** [comment]
Any updates here?

**Comment by tmat** [comment]
Do you see any?

**Comment by jcagme** [comment]
So, going forward to avoid annoying @tmat when asking for updates, please make sure to to update this issue. I'll also check all the commits in the attempt to find a related one.

**Comment by tmat** [comment]
I'm sorry, but I don't like this constant polling on open issues. I will make sure I update the issue when I have made some progress.

**Comment by AdamYoblick** [comment]
I’m not on the arcade team, but since I created this issue, I feel I have to comment.

That kind of response is not ok. Please be respectful.

________________________________

**Comment by tmat** [comment]
Yes, I'm sorry. I shouldn't reacted that way.

**Comment by jcagme** [comment]
All is good! Please keep this thread up to date whenever there are changes so we know what work is pending.
