### ISSUE TITLE
GenFacades depends on BuildTools target unnecessarily

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#1374]
See https://github.com/dotnet/arcade/blob/b6b9dfa1778de0f3094c3ae42abd83a23f4cd81a/src/Microsoft.DotNet.GenFacades/build/Microsoft.DotNet.GenFacades.targets#L3-L7

This should be removed.  /cc @wtgodbe

**Comment by wtgodbe** [comment]
Good call, this can be removed now. https://github.com/dotnet/arcade/pull/1377
