### ISSUE TITLE
Support channel specification in global.json

### ISSUE THREAD

**Issue by dougbu** [dotnet/arcade#13759]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Nothing is horribly wrong but we could ease our monthly workload slightly, especially the number of servicing PRs needed in [dotnet/arcade](https://github.com/dotnet/arcade). That is, we can make @mmitche's life easier.

Customers may also prefer to stay current within a specific SDK feature band automatically.

We currently need to update global.json in all open [dotnet/arcade](https://github.com/dotnet/arcade) `release/*` branches to reflect the just-released SDK after Patch Tuesday. This is extra work that the `-Channel` command-line parameter to the downloaded `dotnet-install.*` scripts can handle for us. For example, `.dotnet/dotnet-install.sh --channel 6.0.3xx --version latest --quality ga --install-dir $PWD/.dotnet/` adds the latest 6.0.3xx SDK to the local .NET installation folder.

Since some repositories also specify runtimes to install and (if they're diligent) update them monthly in their servicing branches, we should support this option for runtimes as well as the SDK.

## Syntax

We could support this option in global.json w/ syntax such as
``` json
"tools": {
  "dotnet": {
    "version": "latest",
    "channel": "6.0.4xx"
  }
}
```
and
``` json
"tools": {
  "runtimes": {
    "dotnet/x64": [
      {
        "channel": "2.1",
        "version": "latest"
      }
    ]
  }
}
```

**Note** two-part versions e.g., `"6.0"` may be problematic when specifying an SDK. SDK feature bands are not necessarily backward-compatible. (@marcpopMSFT please confirm)

## Related requirements

In addition to expanding the global.json parsing in eng/common/tools.ps1 and eng/common/tools.sh, we must update the Maestro++ SDK updates to leave the `version` alone if it's `latest` (even if the `version` just defaults to `latest`) and `channel` is specified.

## Potential stages

1. Add the feature in `eng/common/tools.*`
2. Update Maestro++ to leave global.json mostly alone if the file uses the new syntax for the SDK
3. After a conversation w/ our partners about potential downsides such as not having repeatable builds when using an old servicing commit (because they'll use a newer SDK from a channel). use the option in Arcade servicing branches
4. Stop performing monthly SDK updates in the [dotnet/arcade](https://github.com/dotnet/arcade) repo

We could consider stopping after (2) if our customers prefer using this feature for runtime updates only.

### Another potential downside

Broken aka.ms links could break builds of any repository using this feature. This could also be a **Good Thing:tm:** if we catch the link problem before it affects our customers. However, existing automation greatly reduces the chances of this issue happening.

### Release Note Category

- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description

We have added support for installing the latest SDK or runtime from a specific `channel` in global.json. See #13759 for syntax and other details.

**Comment by missymessa** [comment]
@mmitche should this go into the VMR epic?

**Comment by missymessa** [comment]
Followed up with mmitche. It's not VMR related.

**Comment by missymessa** [comment]
@ViktorHofer what do you think about this issue?

**Comment by ViktorHofer** [comment]
I don't have a strong opinion here but I prefer the exact version as it allows to build deterministically. We don't use floating versions for NuGet packages for the same reason.
