### ISSUE TITLE
Helix agents not provisioning

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#13774]
Customer reported that it's taking a long time for build agents to provision. Investigation shows that it started suddenly. 

![image](https://github.com/dotnet/dnceng/assets/47990216/bfb2b9c8-209d-41bb-b537-5e415475dbfe)

IcM has been filed: 

https://portal.microsofticm.com/imp/v3/incidents/details/395129564/home

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
(transferring to dotnet/arcade so that Known Issues can pick this up).

**Comment by missymessa** [comment]
Current status: 

- Issue was caused due to a bug in Secret Manager. 
- Have redeployed Helix Machine to fix the issue with the secrets. Will need to do some manual mitigation so that VMs don't keep spinning up in a broken state. 
- Asked the AzDO team to close the IcM as we have identified the problem on our side and have managed to make progress forward.

**Comment by riarenas** [comment]
All Helix VMs are now provisioning normally. The on-prem machines we lost will need to be configured again by with the updated configuration files. I'll add RCA details tomorrow.
