### ISSUE TITLE
[Testing - Helix] Arcade version of "CloudTest" libraries

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#138]
Name is unimportant, but I wanted to add this to an issue and couldn't find an existing one.  At some point in the near future we want to move the CloudTest libraries (i.e. everything you need to upload payloads and send jobs to helix in product-agnostic MSBuild tasks).

I want to make sure that when this happens, all result and drop API usage uses the new helix storage API;  ideally Arcade will never provide a version of the CloudTest libraries where users provide any of their own storage account keys or connection strings.

**Comment by maririos** [comment]
@MattGal are you talking about this https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.Helix ? 
If so, because you have the knowledge on what we should have and what there is, could you help me identify if there are still action items with that package?

**Comment by MattGal** [comment]
Right those are the Helix Client libraries and Alex's Job Sender stuff but this issue is about having msbuild tasks that do (similar to) what we have today a la https://github.com/dotnet/buildtools/tree/master/src/Microsoft.DotNet.Build.CloudTestTasks .  That work has not been started as far as I know.

It needs to be:

- Repo-agnostic
- Use Azure Client libraries as much as possible
- Use latest Helix API features wherever possible (such as the storage API)

**Comment by maririos** [comment]
Thanks for the clarification @MattGal

**Comment by markwilkie** [comment]
Currently being tracked in its own epic #947
