### ISSUE TITLE
Nightly validation scheduler failing

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#13817]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://dev.azure.com/dnceng/internal/_build/results?buildId=2187043&view=logs&j=559e8c61-8d51-558d-7b08-43d2f6c6578c&t=67a4272e-b412-5521-fd1f-95beadaad539

The scheduler is failing with a BadRequest exception since about May 22nd.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
@mmitche since the build the link goes to is expired, can you link the pipeline if the error is still occurring?

**Comment by mmitche** [comment]
Looks good now.
