### ISSUE TITLE
400 Bad Request when trying to fetch test run results

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/arcade#13848]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=317248

### Build leg reported

Build / osx-arm64 Release NativeAOT_Libraries / Send to Helix and runtime / Build / Libraries Test Run checked coreclr osx x64 Debug / Send to Helix

### Pull Request

https://github.com/dotnet/runtime/pull/87503

### Known issue core information

```json
 {
    "ErrorMessage" : "Request to https://dev.azure.com/dnceng-public/public/_apis/test/runs?api-version=5.0 returned failed status 400 Bad Request",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by premun** [comment]
The exact error there seems to be this:
```
Build 317248 cannot be found.
```

`317248` is the ID of the build where this happened so this rather seems like an issue with AzDO?

**Comment by missymessa** [comment]
@jkoritzinsky doesn't look like there's been any hits on this error, are you still seeing this error occurring?

**Comment by jkoritzinsky** [comment]
I haven't seen it again. I'll close this out.
