### ISSUE TITLE
Helix agents are unable to upload results to Azdo 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#13841]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

This was previously reported as a known issue: https://github.com/dotnet/arcade/issues/13778, but this information can't be found by known issue functionality as is part of the python log.

I don't know the impact of this issue but has been reported more than once and it's a failure happening while uploading results to AzDO: https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1686846358994?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1686846358994&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1686846358994

This was observed on the build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2200348&view=logs&j=853c7f6c-be79-54da-abe5-39f10d9d1aff&t=028f943f-f877-58b5-f634-318f999b2fd7

You can check this log to see the error
```
Logs
| where JobName contains "147188f7-e362-4969-ac22-779aaaa8a08f"
| where WorkItemName  == "e5c1aa6b-49f5-42b3-88c0-989328736788"
```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by radical** [comment]
cc @lewing this is related to perf results in our dashboard

**Comment by AlitzelMendez** [comment]
this was handle on the First Responder channel:
[Ankit Jain: dotnet-runtime-perf results for wasm not getting reported correctly](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1686846358994?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1686846358994&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1686846358994)

The conclusion is that there are not enough machines on the queue which is causing that the queue is backed up, this is happening because some machines were taken off for testing by the team. 

If this continue happening after the machines are returned to the queue, please feel free to reopen the issue
