### ISSUE TITLE
Use D_v4 SKU for runtime Ubuntu 22.04 VMs

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/arcade#13868]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The runtime team needs AVX512 for some tests, same as for the old 18.04 queue. When the new Ubuntu.2204.Amd64.Open.Rt queue was added this was missed.

PR: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/32298

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

Use D_v4 SKU for the Ubuntu.2204.Amd64.Open.Rt queue to support AVX512

**Comment by dougbu** [comment]
/cc @ilyas1974
Note Ilya is out this week @akoeplinger
