### ISSUE TITLE
VS2022 Regular and baseimages update for 2023-07-05

### ISSUE THREAD

**Issue by v-zheyan** [dotnet/arcade#13865]
Update regular VS2022 version for rollout 2023-07-05.

### Release Note Category
- [X] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Update regular release version from 17.6.0 to 17.6.3 
Update scouting release version from 17.6.3 to 17.6.4
Update regular baseimages

**Comment by v-yuyangshi** [comment]
PR: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/32299
