### ISSUE TITLE
Baseimages update for 2023-07-12

### ISSUE THREAD

**Issue by v-yuyangshi** [dotnet/arcade#13875]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Update regular baseimages

**Comment by ilyas1974** [comment]
Closing this issue as we have a newer issue to track base image updates.
