### ISSUE TITLE
SignTool: TEST sign Python files

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#1389]
The MicroBuild team is working to get tools in place to be able to test sign Python files. Until that work is completed the Arcade SignTool is bypassing (i.e., not signing) any Python files.

@markwilkie @tmat @natemcmaster @ericstj

**Comment by JohnTortugo** [comment]
I just had a quick talk with Trevor Short (from Microbuild team) and this are his words: "To be clear, there is no guarantee that I’ll be able to get “test” signing working for python files. "

Cc'ed people, I'm not quite sure if that will be a blocker for you (i.e., for building preview). Is it?

**Comment by tmat** [comment]
No, we don't need test signing for anything as far as I know.
