### ISSUE TITLE
Official build broken due to CG alerts

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#13905]
- [X] This issue is blocking 
This blocks official builds of Arcade from completing and thus blocks Arcade dependency flow.
- [ ] This issue is causing unreasonable pain

Arcade's official build is failing due to CG alerts in the source-build (managed) leg: https://dnceng.visualstudio.com/internal/_build/results?buildId=2224367&view=logs&j=2f0d093c-1064-5c86-fc5b-b7b1eca8e66a&t=18d66b88-5bf0-507c-5e81-5343305a5e7e

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by garath** [comment]
> Consider not breaking on CG alerts in this leg

Hmmmmm, I don't know enough about source-build to say if this is a good or bad spot for component governance scans. @lbussell what do you think? Can you help me understand source-build's compliance story?

**Comment by lbussell** [comment]
@dotnet/source-build-internal

**Comment by MichaelSimons** [comment]
This issue has been resolved in main.  Looks like the current builds are passing.  The offending packages were removed from https://github.com/dotnet/source-build-reference-packages

**Comment by mthalman** [comment]
I mentioned this to @mmitche as this showed up in the installer-official-ci builds as well. For whatever reason, this is newly scanning these branches when they weren't before. You can see a build for 6.0 from yesterday that skipped scanning: https://dnceng.visualstudio.com/internal/_build/results?buildId=2239437&view=logs&j=2f0d093c-1064-5c86-fc5b-b7b1eca8e66a&t=18d66b88-5bf0-507c-5e81-5343305a5e7e. Something recently changed that caused this to be scanned.

**Comment by ilyas1974** [comment]
Closing this issue has we have been getting recent Arcade builds.
