### ISSUE TITLE
SBOM Check is failing for F# insertion

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/arcade#13917]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Currently, SBOM check is failing for F# insertion builds for 17.8 (it was the case just about a year ago too, and Epsitha helped us to fix it): https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/485786

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by garath** [comment]
@vzarytovskii Is this issue for your own tracking while you work on a fix? Or, is there an Ask for dnceng?

**Comment by vzarytovskii** [comment]
> @vzarytovskii Is this issue for your own tracking while you work on a fix? Or, is there an Ask for dnceng?

No, Epsitha asked me to create it here.

**Comment by garath** [comment]
> No, Epsitha asked me to create it here.

Ah, okay. Thanks for clarifying.

**Comment by epananth** [comment]
requested for a fsharp build so that I can investigate further

**Comment by epananth** [comment]
Looks like the F sharp build is generating SBOM.

**Comment by epananth** [comment]
Going to close this one.
