### ISSUE TITLE
Arcade should include scripts for determining OS name, architecture, and distro RID

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/arcade#13946]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

dotnet/runtime currently has scripts for determining the OS name, architecture, and distro RID,:
https://github.com/dotnet/runtime/blob/main/eng/native/init-distro-rid.sh
https://github.com/dotnet/runtime/blob/main/eng/native/init-os-and-arch.sh

This would be useful functionality to have in Arcade itself in `eng/common`. There are already copies in other repos (for example, diagnostics, dotnet-monitor) which are manually synced to the runtime version when there's an issue.

https://github.com/dotnet/source-build/issues/3578 would also need this functionality.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
@elinor-fung, feel free to submit a PR with these additions to the repo :)
