### ISSUE TITLE
Port codeOptimization.targets to arcade

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#1396]
For corefx, we need to port the codeOptimization target to arcade. It could also use some clean up. From @ViktorHofer:

> It probably also needs to be cleaned up. It stores versions and names inside the target and directly accesses files from the PackagesDir (which we tried to avoid and instead restore everything upfront as part of depproj files). The RestoreOptimizationDataPackage could probably be removed entirely and replaced with a depproj or a simple nuget restore.

**Comment by tmat** [comment]
What does PreProcessIBCData do? Is it something specific to CoreFX or generally useful? We do not do any preprocessing, other than merging raw IBC to the DLLs when producing package with optimization data. If that's what the target does then we could probably reuse that also in Roslyn and other repos.

**Comment by adiaaida** [comment]
We can't apply IBC data to assemblies other than the one they were generated with unless the data is already embedded into the assembly it was generated with. For most of the IBC data we collect (everything other than System.Collections.Immutable and System.Reflection.Metadata), we collect on machines that are possibly publicly accessible, so we don't pull ibcmerge down on them, and therefore can't do the step where we merge the data into the assembly we collected on so that we can use it later. Instead, we package up the assembly and the ibc data, to be processed with PreProcessIBCData when we get to the repo where we are using the data (ie, the official builds). Right now, we do this for CoreCLR and CoreFx, though CoreCLR doesn't currently use the buildtools targets.

For the Roslyn dependencies, they collect differently and presumably do this preprocess step at the collection stage, rather than the official build stage, but for the other assemblies that we collect for, we need that target.

**Comment by tmat** [comment]
I see. We currently do the first merging before publishing the package. Perhaps we should update that logic, so that we have the same flow. 

BTW, you can now update CoreFX to train Roslyn dependencies (SRM and SCI) like you do other assemblies. We no longer use the training data that are embedded to them and instead replace them with our own training data (we are now shipping different binaries in VS than CoreFX).

**Comment by adiaaida** [comment]
Thanks for that update! I will work on getting our training scenario updated to collect for those two assemblies.

**Comment by tmat** [comment]
If it was useful we could also combine our IBC data for these assemblies with yours. We publish them to a nuget package on myget that you could potentially get them from.
