### ISSUE TITLE
[Feed package] Use default dependency versions in Feed package

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#14]
tmat reviewed an hour ago 
```
src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj 

+    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.4.0-beta-24813-03" /> 
+  </ItemGroup>   
+ 
+  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.5'"> 
 ``` 
 
tmat an hour ago • edited  
Why do we conditionally reference different versions of packages (like SRM 1.4.1 vs 1.3.0)? NuGet should automatically pick the right binary from each package based on TargetFramework version.

**Comment by maririos** [comment]
@JohnTortugo was this also solved by #380 ?

**Comment by JohnTortugo** [comment]
At least for Tasks.Feed yes; but maybe worth to keep this issue to check all packages. Also, I should add a note for checking this on the "how to create package" doc. #374

**Comment by maririos** [comment]
I don't think keeping this issue open is going to help us guarantee that packages in Arcade use the default versions. I see it more like we need to create something that will validate that, and/or look for things like that in the code review process of Arcade PRs.

**Comment by markwilkie** [comment]
Next steps here?
