### ISSUE TITLE
Add install telemetry for native toolsets

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#140]
Let's track things like:
- Which versions are being used  (actively installed)
- Exceptions 
- Reliability #'s

**Comment by markwilkie** [comment]
@Chrisboh - What do you think about telemetry stuff?

**Comment by markwilkie** [comment]
@chcosta - I'm closing this for now as we think we can probably back into this from our feed endpoints.  However, if there are other requirements, please don't hesitate to reopen.
