### ISSUE TITLE
[TestReporting] Add ability to populate AzDev test results "custom test fields"

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#1400]
@Chrisboh @echesakovMSFT fyi

**Comment by alexperovich** [comment]
I am on first responder for the next 2 weeks then I will be OOF for vacation over Christmas. I will not be able to work on this until next January.

**Comment by echesakovMSFT** [comment]
FYI, It seems that "custom test fields" are not fully implemented in AzDO now.

/cc @RussKeldorph

**Comment by mjanecke** [comment]
AzDO Test team will provide information about how to use "tagging" for test results that will add the ability to add custom tags to a test result so that test results can be grouped by the tagging.
