### ISSUE TITLE
16c5f6a1509ed6ab05d3ff4ab81d753585e5af63

### ISSUE THREAD

**Issue by Ericsandanu** [dotnet/arcade#14012]
16c5f6a1509ed6ab05d3ff4ab81d753585e5af63

_Originally posted by @Ericsandanu in https://github.com/microsoft/ContributorLicenseAgreement/pull/1#pullrequestreview-1608582379_

**Comment by riarenas** [comment]
This doesn't look like an issue, feel free to reopen with additional information.
