### ISSUE TITLE
Update xcopy-msbuild to 17.7

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#14031]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

SSA request here: https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1694708677309?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1694708677309&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1694708677309

How to: https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1074/RoslynTools.MSBuild-(xcopy-msbuild)-generation

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Updated xcopy-msbuild to 17.7.2

**Comment by epananth** [comment]
Fix was merged https://github.com/dotnet/arcade/pull/14078

Closing this
