### ISSUE TITLE
17.7.2 xcopy-msbuild issues

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#14055]
- [x] This issue is blocking 
Repo SDK updates and arcade promotions are blocked on this.

- [ ] This issue is causing unreasonable pain

See threads: 

- https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1695655754018?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1695655754018&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1695655754018
- https://teams.microsoft.com/l/message/19:276707cdcf5d431caaa8792b29bd832d@thread.skype/1695656843903?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1695656843903&teamName=.NET%20Eng%20Services&channelName=FR%20Internal&createdTime=1695656843903

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
Related PR: https://github.com/dotnet/arcade/pull/14037

**Comment by riarenas** [comment]
As far as I'm aware, this is blocking updating repos to the RC1 sdk that needs the new msbuild. Arcade-validation is already in this state, so this is blocking arcade promotions.

**Comment by ilyas1974** [comment]
Package has been updated and arcade promotions have been unblocked.
