### ISSUE TITLE
Arcade could use Central Package Management

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#14060]
https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management

We already do use it in other repositories https://github.com/dotnet/arcade-services/blob/main/Directory.Packages.props but it's unclear whether this is possible in Arcade.

Discussed here https://github.com/dotnet/arcade/pull/13998#pullrequestreview-1646553727

**Comment by premun** [comment]
@ViktorHofer I think this is a rabbit hole. CPM needs package source mappings and those won't be supported by the tools that are adding nuget sources dynamically (e.g. internal feeds added on the fly).

I am not sure how this works for other product repos. Do you know of some that are using this already?

**Comment by ViktorHofer** [comment]
sent you a link on Teams

**Comment by ViktorHofer** [comment]
Fixed with https://github.com/dotnet/arcade/pull/14074
