### ISSUE TITLE
Branch for .NET 9

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#14068]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Create a new release/8.0 branch in Arcade. Instructions at https://github.com/dotnet/arcade/blob/main/Documentation/Policy/ArcadeServicing.md#mechanics-of-branching-arcade-and-services

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by AlitzelMendez** [comment]
@riarenas you are the best, thanks for sharing the instructions 😄

**Comment by riarenas** [comment]
FYI @mmitche

**Comment by AlitzelMendez** [comment]
this is done now 😄 closing the issue!!!
