### ISSUE TITLE
xcopy msbuild 17.7.4 is actually 17.7.2

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#14076]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The xcopy msbuild package with version 17.7.4 published in the dotnet-eng feed, although it was generated with a 17.7.4 installation of the VS build tools, still only has MSBuild 17.7.2 in it.

The package works as expected, but we should:

* Republish the package as 17.7.2-<next version we haven't messed up>
* delete the 17.7.4 package
* Update the instructions for package generation so that we check the msbuild assembly version using nuget package explorer
![image](https://github.com/dotnet/arcade/assets/23242101/f9bfa267-39cd-4523-b86e-68a693f506de) and we name the package according to that version

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by epananth** [comment]
fix is merged. Closing this
