### ISSUE TITLE
`Publish.proj` does not respect SymbolPublishingExclusionsFile

### ISSUE THREAD

**Issue by dibarbet** [dotnet/arcade#14089]
The documentation lists this method for configuring excluded files in symbol packages - https://github.com/dotnet/arcade/blob/main/Documentation/CorePackages/Publishing.md#can-we-exclude-symbols-from-publishing-to-symbols-server which allows a file to be added to specify paths to exclude from the symbol publishing package.  This does appear to be respected in [PublishToSymbolServer.proj](https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/PublishToSymbolServers.proj#L66C1-L67C1), 

### Bug
However this file is not respected in [Publish.proj](https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/Publish.proj#L248) - no files are excluded from the packages.

This means I am unable to exclude files from symbol packages whenever `Publish.proj` gets invoked.  This was found in https://github.com/dotnet/roslyn/pull/70162 and build https://dev.azure.com/dnceng-public/public/_build/results?buildId=429092&view=logs&j=0f289b55-e51e-537b-a78d-659668d39b05&t=65ecf3f3-6240-545e-af3c-b1c21351fb50

**Comment by missymessa** [comment]
@epananth are you still working on this?

**Comment by garath** [comment]
@epananth What's the status with this? It looks like it's stalled. Are you still working on it?

**Comment by Cosifne** [comment]
Hi, this becomes a blocker for https://github.com/dotnet/roslyn-tools/pull/1396
Is there any update?

**Comment by epananth** [comment]
This documentation pertains to publishing with V3, specifically utilizing the publishToSymbolServer.proj. It has never been functional with publish.proj.

That being said, I am trying to re-evaluate if there is a work around you could use.

**Comment by epananth** [comment]
try passing /p:DotnetPublishUsingPipelines=true in your build command.

**Comment by epananth** [comment]
https://teams.microsoft.com/l/message/19:1dad2081c8634f34915d88dce6220265@thread.skype/1711649646692?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1711649646692&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=Arcade&createdTime=1711649646692

we were able to find a work around for this one. Closing this issue
