### ISSUE TITLE
[Release/8.0] Branch is missing CI / PR triggers

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#14080]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We missed updating the triggers for PR and CI validation in this branch.

https://github.com/dotnet/arcade/blob/release/8.0/azure-pipelines.yml#L5-L33 we need to add release/8.0  to the list of branches that should run validation

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by epananth** [comment]
fix is merged. Closing this
