### ISSUE TITLE
XUnit tests on net462 are skipped due to Strong name signature verification.

### ISSUE THREAD

**Issue by JRahnama** [dotnet/arcade#14091]
- [ x] This issue is blocking 
- At SqlClient team, we have started to use Microsoft.DotNet.XUnitExtensions from Arcade source provider and trying to remove our internal build of the package to benefit from latest improvements. While working on the task I noticed all net462 tests are skipped with a note:
```error
 [xUnit.net 00:00:01.41] Skipping: ManualTests (could not load dependent assembly 'Microsoft.DotNet.XUnitExtensions, Version=9.0.0'): Could not load file or assembly 'Microsoft.DotNet.XUnitExtensions, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
```
NetCore is working fine.
I have tested with:
```props
Microsoft.DotNet.XUnitExtensions 9.0.0-beta.23506.2
Microsoft.DotNet.XUnitExtensions 8.0.0-beta.23505.1
XUnit 2.5.1
```

Could be checked at PR [#2033](https://github.com/dotnet/SqlClient/pull/2033) on SqlClient repo.
- [ ] This issue is causing unreasonable pain

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by ViktorHofer** [comment]
Is that happening inside VS only or also with `dotnet test` / `dotnet build /t:Test`?

**Comment by JRahnama** [comment]
@ViktorHofer this is happening on 1ES images. windows-2022 image and this is the link to what is included in that image:
https://github.com/actions/runner-images/blob/win22/20230924.1/images/win/Windows2022-Readme.md

**Comment by ViktorHofer** [comment]
I don't understand the problem fully yet but it has to with full strong name signature verification on .NET Framework when using appdomains.

Here's what we do in our repositories to make this work:

Add a `xunit.runner.json` file to your project and make sure that it gets copied to the output directory:

```json
{
  "shadowCopy": false
}
```

In the test project:

```
  <ItemGroup>
    <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
```

**Comment by JRahnama** [comment]
@missymessa I just tested and can confirm the issue is fixed. Thank you.
