### ISSUE TITLE
Clarify YAML

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#1410]
AzureDevOpsOnboarding is a good entry point to AzDO and Arcade. Some improvements:

 - Refactor to speak to a user, not an Arcade developer. 
 - Make clear which pieces are provided by AzDO and what pieces are provided by Arcade.
 - Document intent and use of Arcade pieces.
 - Consider merging AzureDevOpsGuidance into here, or at least the bits that are useful to users.

**Comment by markwilkie** [comment]
This has been happening over time - and I don't think this specific issue is actionable.  Closing.
