### ISSUE TITLE
Package mirroring pipeline can't handle spaces in comma delimited package list

### ISSUE THREAD

**Issue by mconnew** [dotnet/arcade#14121]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

I started a dotnet-migrate-package per [the instructions here](https://github.com/dotnet/arcade/blob/main/Documentation/MirroringPackages.md) and had an issue with package mirroring failing. My first run can be [found here](https://dev.azure.com/dnceng/internal/_build/results?buildId=2288803&view=results). These are the parameters I used:  
```
MigrationType : "New or non-Microsoft"
PackageNames : "CoreWCF.Primitives, CoreWCF.Http, CoreWCF.NetTcp, CoreWCF.ConfigurationManager, CoreWCF.WebHttp, CoreWCF.NetFramingBase, CoreWCF.NetNamedPipe, CoreWCF.Queue, CoreWCF.MSMQ, CoreWCF.UnixDomainSocket"
PackageVersion : "latest"
```

The CoreWCF.Primitives package downloaded the 1.5.0-preview1 version which was expected. The next and subsequent packages didn't get downloaded. [Here's the pipeline step for CoreWCF.Http](https://dev.azure.com/dnceng/internal/_build/results?buildId=2288803&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997). This is the output log:
```
dotnet run --project migrate-package -- --name " CoreWCF.Http" --version "latest" --prerelease --include-dependencies --pat ***
========================== Starting Command Output ===========================
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_work\_temp\05195012-f098-44c4-b74a-b4f559ee300a.cmd""
Package ' CoreWCF.Http' not found on nuget.org
```

When parsing a list of packages to mirror, leading and trailing spaces should be trimmed as it's common to use spaces when providing a comma delimited list.   

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by lewing** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-migrate-package/pullrequest/34570
