### ISSUE TITLE
(Some) branch protection rules are missing for the release/* branches

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#14126]
I just noticed that I can merge this PR in at any given time: https://github.com/dotnet/arcade/pull/14110. I think the release/8.0 or all release branches are missing some of the main branch protection rules.

cc @mmitche

**Comment by akoeplinger** [comment]
Seems to be specific to the release/8.0 branch according to the shield icons on the branch page:
<img width="282" alt="image" src="https://github.com/dotnet/arcade/assets/1376924/131d1aa6-8014-4b97-a13e-f26f429e41e0">

The same applies to the https://github.com/dotnet/arcade-validation repo

**Comment by ViktorHofer** [comment]
Note that you can use glob expressions in the branch pattern: `release/*`

**Comment by missymessa** [comment]
I created issues from getting pinged about these, so I think they're being taken care of.
