### ISSUE TITLE
What is all this?

### ISSUE THREAD

**Issue by dferretti-fig** [dotnet/arcade#1413]
I just stumbled onto this repo, and after spending time reading through some of the documentation, it seems to address a lot of the issues I face at my work. We have a decent and growing number of repositories, many of which with similar build/release processes, so we use a custom terraform provider to create these (holding on to hope that someday this might get picked up https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/34057141-terraform-provider). But now we are coming to realize the annoying problem of updating a base package and having to propagate it through all the other packages in the right order. Right now it is manual, but had on the todo list a way of mapping out the dependency hierarchy and having a bot of sorts auto create PRs - but looks like that is exactly what this project aims to solve (among other neat repo-standardizing tasks). Also looks like it could reduce duplication of build processes - our build processes are very much duplicated, we built the terraform provider to create them before yaml builds were around (at least I think).

I plan on using this repo to learn from (like the diagram on Maestro's speculative package flow was very useful), but will I eventually be able to use these tools? It looks like some of it is specific to your internals, I'm guessing the target audience is mostly people on the dotnet/aspnet teams. 

A couple other quick questions too:
- Where does the name Arcade come from?
- Where does the name Darc come from?
- Will mc.dot.net be public facing?

Thanks!

**Comment by danmosemsft** [comment]
@markwilkie

**Comment by markwilkie** [comment]
Hi!  (sorry for the delayed response)

Yes, our primary target is .NET Core 3.  However, I could imagine that between BAR, Darc, and Maestro, one would be able to wire up most any "composed" build product.

> Where does the name Arcade come from?
The idea comes from a "collection" - in this case, a collection of tools and packages that is shared across the full product

> Where does the name Darc come from?
.NET Arcade.  (kinda boring I know...grin)

> Will mc.dot.net be public facing?
Maybe....  Test results will be going into the 'test' tab in Azure Dev Ops, but the visual representation fo the graph from BAR will still be in mc.dot.net (or something like that).  We still haven't figure out the details around whether or not that'll be public or not as there are some seemingly simply, but "sticky" challenges to work through.

Feel free to engage further and we'll certainly help as we can.  Also, note that we're standing up https://github.com/dotnet/arcade-services/ which will have the Azure based services bits as we're moving that out of Arcade.

Cheers!

**Comment by dferretti-fig** [comment]
Awesome - thanks for your answers!
