### ISSUE TITLE
Xcopy-MSBuild improvements

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#14146]
Xcopy-MsBuild serves a purpose, but it's not ideal for a variety of reasons which have been discussed internally.  While our current state is "fine" (meaning not really fine but it's reality), there are some ways that this could be improved in the immediate or near-term future

- An active inventory of places where we are taking a dependency on xcopy-msbuild rather than defaulting to the installed VS MSBuild (ie, the Signing Validation repo task is a primary culprit, MicroBuild is another).  Maintaining a list would allow us to drive down those dependencies

- Long-term, we would hope that the Setup team would provide a solution.  In the interim, 1ES has a similar internal solution which does not rely on a VS installation.  Converging on that solution would be a marked improvement over maintaining a separate solution.

**Comment by missymessa** [comment]
1ES is going to make us a package. This solution might negate the need for this work, but we'll hold off on it just in case.

**Comment by chcosta** [comment]
We're now using the 1ES provided package and I haven't heard any complaints within the last two weeks (since we switched over).  Closing this - https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1074/Updating-Microsoft.DotNet.Arcade.MSBuild.Xcopy-WAS-RoslynTools.MSBuild-(xcopy-msbuild)-generation
