### ISSUE TITLE
Some transient failures when test signing on Microbuild side

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#1415]
I've observed (and got some reports) that some Arcade Debug (which uses test signing) builds are failing or timing out on the signing step. 

I'm working with the Microbuild team to see if we can get more info about that.

Two builds related to that are:
- https://dnceng.visualstudio.com/internal/_build/results?buildId=49424
- https://dnceng.visualstudio.com/internal/_build/results?buildId=49922

Cc @jcagme @chcosta @RickKra

**Comment by JohnTortugo** [comment]
In one of the builds I get this failure on the logs:

`
9> 29.13.53.46 Warning: System.ApplicationException: 
Authenticode test signing failed for 'F:\vsagent\-containerSas\54\s\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.ApiCompat.1.0.0-beta.18579.1.nupkg'
Authenticode test signing failed for 'F:\vsagent\-containerSas\54\s\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.DarcLib.1.0.0-beta.18579.1.nupkg'
Authenticode test signing failed for 'F:\vsagent\-containerSas\54\s\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.Helix.JobSender.1.0.0-beta.18579.1.nupkg'
Authenticode test signing failed for 'F:\vsagent\-containerSas\54\s\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.Helix.Sdk.1.0.0-beta.18579.1.nupkg'
Authenticode test signing failed for 'F:\vsagent\-containerSas\54\s\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.Maestro.Client.1.0.0-beta.18579.1.nupkg'
Authenticode test signing failed for 'F:\vsagent\-containerSas\54\s\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.Maestro.Tasks.1.0.0-beta.18579.1.nupkg'
Authenticode test signing failed for 'F:\vsagent\-containerSas\54\s\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.SignCheck.1.0.0-beta.18579.1.nupkg'
Authenticode test signing failed for 'F:\vsagent\-containerSas\54\s\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.SignTool.1.0.0-beta.18579.1.nupkg'
Authenticode test signing failed for 'F:\vsagent\-containerSas\54\s\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.SwaggerGenerator.CmdLine.1.0.0-beta.18579.1.nupkg'
Authenticode test signing failed for 'F:\vsagent\-containerSas\54\s\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.SwaggerGenerator.MSBuild.1.0.0-beta.18579.1.nupkg'
Authenticode test signing failed for 'F:\vsagent\-containerSas\54\s\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.XUnitExtensions.2.4.0-beta.18579.1.nupkg'
Test signing failed for 11 file(s)
   at Microsoft.VisualStudio.Tools.Build.TestSigner.RunSubmit(List`1 records, Timeout globalTimeout)
   at Microsoft.VisualStudio.Tools.Build.SignerBase.InternalSubmit(IList`1 records, Timeout globalTimeout)
   at Microsoft.VisualStudio.Tools.Build.SignerBase.DoSign(Object o)
`

**Comment by JohnTortugo** [comment]
Another build that failed in test sign: https://dnceng.visualstudio.com/internal/_build/results?buildId=50380

**Comment by chcosta** [comment]
Tracking in core-eng with https://github.com/dotnet/core-eng/issues/4734
