### ISSUE TITLE
Signing validation stops working after .NET SDK is updated to 8 RTM

### ISSUE THREAD

**Issue by jjonescz** [dotnet/arcade#14154]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When darc updates dependencies from arcade and with it .NET SDK 8 RTM, signing validation job starts failing with:

```
error NETSDK1213: Targeting .NET 8.0 or higher in Visual Studio 2022 17.7 is not supported.
```

For example: https://dev.azure.com/dnceng/internal/_build/results?buildId=2299706&view=logs&j=b11b921d-8982-5bb3-754b-b114d42fd804&t=fb192a8b-e433-5fc8-e2b0-276ab015e7d5

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by ViktorHofer** [comment]
cc @markwilkie @mmitche

**Comment by riarenas** [comment]
The repo is asking for 17.7 xcopy msbuild and vs in their global config. an RTM sdk needs 17.8 at a minimum. Please update your global.json. If you don't need to specify those values, you can let Arcade use the ones it will use by default.

**Comment by ViktorHofer** [comment]
Thank you. Yes that worked. Build succeeded: https://dnceng.visualstudio.com/internal/_build/results?buildId=2300015&view=results
