### ISSUE TITLE
[xliff] Incorrectly producing note from XML comment in XAML file

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/arcade#14168]
The XML comment in this property:

https://github.com/dotnet/project-system/blob/04bae84071dd08f6e5f5c3e9c9f39a2d349f7654/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.VisualBasic.xaml#L380-L401

Is producing a weird comment in the XLF files, for example:

https://github.com/dotnet/project-system/blob/04bae84071dd08f6e5f5c3e9c9f39a2d349f7654/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/BuildPropertyPage.VisualBasic.xaml.ko.xlf#L190-L194

The code that's producing the XLF files is incorrectly converting that comment into a note.

**Comment by missymessa** [comment]
@adamint @drewnoakes @ViktorHofer was this work completed?

**Comment by adamint** [comment]
@missymessa yes, it was
