### ISSUE TITLE
remove usage of dotnet-blob-feed variable group in official build

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#14188]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

This variable group is slated for deletion in https://github.com/dotnet/arcade/issues/13963, but still used by the official arcade build.

**Comment by riarenas** [comment]
Quick search that shows usage of the variable group: https://github.com/search?q=repo%3Adotnet%2Farcade+dotnet-blob-feed+path%3A%2F%5Eeng%5C%2F%2F&type=code

**Comment by missymessa** [comment]
Still need some fix ups in 6.0/7.0 branches before we can do this work. Moved to tracking/blocked for now.

**Comment by missymessa** [comment]
NM, we can do this one!
