### ISSUE TITLE
Support private repos with GitHubMergeBranches.ps1

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#14228]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The script currently doesn't support private repos, at least in the cloning step. It assumes the source repo is public.

**Comment by ilyas1974** [comment]
@mmitche is this needed for .NET 9?

**Comment by mmitche** [comment]
This is supported now that we moved this into a GH action.
