### ISSUE TITLE
runtime 8.0 builds hitting C++/CLI build failures due to old VS install

### ISSUE THREAD

**Issue by agocke** [dotnet/arcade#14231]
Looks like we need VS 17.8 on our build machines in those queues, but we have 17.7.

**Comment by missymessa** [comment]
Related discussion thread on Teams: https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1700178936962?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1700178936962&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1700178936962

**Comment by riarenas** [comment]
To summarize the discussion there. 17.8 release will first reach the regular scouting image during the next deployment (which is scheduled for 11/29. It will then move to the regular image afterwards some time in December)

If the branch needs 17.8 before then, the vs preview images can be used.

I'm going to close this issue as the scheduled updates will take care of getting this version to the images.
