### ISSUE TITLE
Arcade should opt into `BuildWithNetFrameworkHostedCompiler` by default

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/arcade#14311]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://github.com/dotnet/sdk/pull/32734 introduced a new property, `BuildWithNetFrameworkHostedCompiler` which when `true` will add a `PackageReference` to a Roslyn package that exactly matches the version of the compiler included in the .NET SDK, for use within Visual Studio/`MSBuild.exe` scenarios which may have an older or newer compiler referenced.

This is generally a more stable arrangement and has proven useful for some package update scenarios like https://github.com/microsoft/testfx/pull/1944.

I think Arcade should consider opting into this by default for all repos.

cc @jaredpar, @Forgind, @marcpopMSFT

**Comment by ViktorHofer** [comment]
citing @jaredpar: anything that is in Arcade should ideally get productized so that our customers would benefit from it as well or removed as it hasn't proven valuable. Following that logic, why wouldn't we want this to be the default for our customers and only apply to our own "arcadified" repositories?

**Comment by ViktorHofer** [comment]
Got it. That sounds like a great reason to enable it in Arcade and file a tracking issue to productize and remove it from Arcade. You want dogfood data that you can get from ourselves without adding a great risk for our customers by enabling it globally.

That's exactly the process that we should follow with any new features that gets added to Arcade.

**Comment by marcpopMSFT** [comment]
We have tentative plans to enable it by default sometime in the future. However, @jaredpar and I haven't discussed what that rollout plan or timeline looks like. Having it enabled in arcade would provide data that it's stable enough to work.

**Comment by marcpopMSFT** [comment]
@markwilkie We're getting more and more noise from customers that version tearing is causing issues. This flag is our solution to that but we still don't have great data on if it solves all the issues. Getting it enabled by default in arcade would help us dogfood this ourselves and give us confidence to turn it on for customers. See Jared's linked issue.

**Comment by jaredpar** [comment]
Our goal is that with 9.0.0-preview3 and going forward we want to start pushing this aggressively to customers as a solution. As a step towards that we want to make it the default in Arcade. This is a pretty straight forward property change, happy to do the work myself. Think ti's best though if it's tied in with the maestro update that pushes the 9.0.0-preview3 SDK around. If I can get a pointer to that happy to help with cchanges.

**Comment by mmitche** [comment]
Yeah this looks good to me. @jaredpar I'll tag you on the p3 update PR

**Comment by mmitche** [comment]
It was not on my radar to implement, but I can if need be.

**Comment by Evangelink** [comment]
On MSTest repo, we are moving to arcade 9 (see PR https://github.com/microsoft/testfx/pull/3531) and building locally is now resulting in many `NU1010: The PackageReference items Microsoft.Net.Compilers.Toolset.Framework do not have corresponding PackageVersion.`

Looking up at the other repos, it seems the common workaround is:

```xml
<!--
      Needed to avoid error NU1010: The PackageReference items Microsoft.Net.Compilers.Toolset.Framework do not have corresponding PackageVersion.
      Related to https://github.com/dotnet/sdk/issues/41791.
    -->
<BuildWithNetFrameworkHostedCompiler>false</BuildWithNetFrameworkHostedCompiler>
```

It seems that turning it to `false` is fixing the issue for MSTest but that's hard to understand why we need to constantly swtich between `true` and `false` on this setting.

**Comment by rainersigwald** [comment]
There have been a few bugs on the road to getting this automatically enabled in the SDK. @Evangelink after you take the final preview 7 SDK, you should be able to remove that line.

**Comment by rainersigwald** [comment]
However I think this issue is stale now since the SDK should just do it, right @jaredpar @jjonescz?

**Comment by jjonescz** [comment]
Agreed, the SDK will use the framework toolset compiler automatically when SDK is in torn state. Setting BuildWithNetFrameworkHostedCompiler explicitly to true should be unnecessary.

**Comment by Evangelink** [comment]
> There have been a few bugs on the road to getting this automatically enabled in the SDK. @Evangelink after you take the final preview 7 SDK, you should be able to remove that line.

I got updated to preview 5, is there something to do to be on preview 7?

**Comment by jaredpar** [comment]
> I got updated to preview 5, is there something to do to be on preview 7?

Preview 7 is where this will start taking effect. 

> . Setting BuildWithNetFrameworkHostedCompiler explicitly to true in arcade should be unnecessary.

Agree. going to close this out.

**Comment by rainersigwald** [comment]
> I got updated to preview 5, is there something to do to be on preview 7?

No, an Arcade bump should bring it to you in a couple of weeks.

**Comment by Evangelink** [comment]
I have forced some preview 7 and confirm it solves the problem locally, I am waiting to see if that fixes the issue for me on internal CI too.
