### ISSUE TITLE
Dependency flow in and out of DotNet-Trusted

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#1431]
It is unlikely that both wpf and winforms will be fully out of DotNet-Trusted by the time we lock down for preview II.  Given that we have the goal of shipping PII on the new infrastructure, we should get this sorted.

cc/ @mmitche, @jcagme, @vatsan-madhavan, @AdamYoblick

**Comment by AdamYoblick** [comment]
Winforms should be. Shyam is just finishing up adding the other winforms binaries to the other repo. All that's left is for us to get those binaries into the transport package and the corresponding steps from DotNet-Trusted.

**Comment by markwilkie** [comment]
Thanks @AdamYoblick.  To clarify I'm speaking specifically of darc + maestro to flow dependencies.  I know that @mmitche was working on AzDO git support last week....

**Comment by mmitche** [comment]
I still am, it's just getting constantly interrupted by 3.0 stuff

**Comment by markwilkie** [comment]
#936

**Comment by mmitche** [comment]
This is complete

**Comment by AdamYoblick** [comment]
Can confirm this is working for our AzDO repo. Matt filed a separate bug for Maestro not being able to auto-merge in AzDO like it can in github, but that's not a blocker since we can just click on "Complete" :)

Thanks Matt!
