### ISSUE TITLE
Redesign the way packages are published - Breakdown

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#1433]
Introduce an Azure DevOps release pipeline concept into Maestro/Bar. Release pipelines are associated with a channel. Upon assignment of a build to a channel, if that channel has an associated release pipeline, the release pipeline should be triggered for the build. Execution of additional post-build actions (e.g. subscription updates) will block on the completion of the release pipeline.

**Comment by JohnTortugo** [comment]
I'm getting myself familiarized with Maestro/BAR sources and the release pipeline concept. 
I'll post a plan for implementation here when I've one. 
I'm also looking if this issue needs to be split into smaller issues.

Any advice will be appreciated! @mmitche @jcagme @alexperovich

**Comment by JohnTortugo** [comment]
I've reviewed a few things and come up with the following questions / points. Can you please take a look and let me know what you think before I start coding?

- The release definitions (RLs) themselves will be created by the user and he will use some Maestro interface (Darc, swagger, etc) to assign RL(s) to channel(s).
- I believe I'll need to [use this API](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases/create?view=azure-devops-rest-5.0) to create the releases for a release pipeline. 
- I am thinking to create a new class in Maestro.Data/BAR to represent a release-pipeline, like so:
  - DefinitionId
  - ArtifactsName
  - Organization / Project # Only needed if we don't want to hard code the API URL
- Naturally part of this work will be to patch Darc/Maestro to handle management RLs for channels.

**Comment by alexperovich** [comment]
What exactly are the requirements for this? We need to trigger a release from a build in the BAR somehow when it gets put into a channel? How would the release know where to get its artifacts and what version of those artifacts? What would these releases be used for?

For the database stuff the "Release Pipeline" should be associated with a channel. Probably a one-to-many (one channel to many release pipelines)

**Comment by JohnTortugo** [comment]
> What exactly are the requirements for this? We need to trigger a release from a build in the BAR somehow when it gets put into a channel? 

I think that is the primary requirement. Whenever a build happens and Maestro see that the build happened, it will look for a channel, if the channel have any release pipeline associated the pipeline will be triggered.

> How would the release know where to get its artifacts and what version of those artifacts? What would these releases be used for?

The API to trigger the pipeline accepts a build id and an artifact alias. AFAIU the goal of the release pipeline will be to decide the final destination of the build artifacts. In the future the artifacts will be initially placed on an intermediate place.

> For the database stuff the "Release Pipeline" should be associated with a channel. Probably a one-to-many (one channel to many release pipelines)

I think M-N also makes sense, right? The same release pipeline can be used by different channels?! Although, I don't know if there is a need for that. @mmitche

**Comment by mmitche** [comment]
@JohnTortugo From the doc, we will change from using an intermediate blob feed for package outputs and instead use azure devops artifacts:

https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/AsyncPublishing.md#options-for-intermediate-feeds (second paragraph)

https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/AsyncPublishing.md#phase-1---remove-lock-contention-and-introduce-public-dev-release-pipelines-for-feeds-only (step 4)

That means Maestro just needs to pass in the artifacts from the build to the release pipeline.

The association of channel to release pipelines should be 1->M, though the same release pipeline could be used for multiple channels like you say.

**Comment by JohnTortugo** [comment]
Closing this issue as I got sorted my questions already and created a few other specific issues to get the work moving forward.
