### ISSUE TITLE
ProjectDefaults.props overrides Directory.Build.props

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1435]
We're trying to get ASP.NET Core projects building with the Arcade SDK. It appears settings from ProjectDefaults.props are always overriding settings we put into the Directory.Builds.props files.

For example, when attempting to configure which strong name key we use, our values are getting overridden.

> Property reassignment: $(StrongNameKeyId)="MicrosoftShared" (previous value: "MicrosoftAspNet") at C:\Users\rybrande\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18579.9\tools\ProjectDefaults.props (11,5)

![image](https://user-images.githubusercontent.com/2696087/49409492-c10c9000-f715-11e8-8c61-c04a10698ff7.png)

@tmat - suggestions?

cc @ryanbrandenburg @rynowak @bricelam

**Comment by natemcmaster** [comment]
I think we can workaround this by ensuring `<Import Project="Sdk.props" Sdk="Microsoft.DotNet.Arcade.Sdk" />` is the verify first thing imported. But to be safe, it might be good to update Arcade to be gentler with its defaults, like this:
```
<StrongNameKeyId Condition=" '$(StrongNameKeyId)' == '' " >MicrosoftShared</StrongNameKeyId>
```
Compare to https://github.com/dotnet/arcade/blob/fa247a5766d89abf19e466a5c36bc4cd1576f65b/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.props#L10-L22

**Comment by tmat** [comment]
This is by design, `<Import Project="Sdk.props" Sdk="Microsoft.DotNet.Arcade.Sdk" />` is expected to be imported before any customizations. Let me update the [docs](https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#srcdirectorybuildprops) to explicitly say so.

**Comment by natemcmaster** [comment]
What do you think about gentler defaults? We noticed this issue right away because our SNK wasn't working. I'm concerned about projects that do this wrong but may not notice. There are lots of MSBuild settings in ProjectDefaults.props, and this will continue to change. I wouldn't be surprise if someone fails to notice they've been overriden by Arcade.

**Comment by tmat** [comment]
By gentler you mean conditional? 
We want to overwrite some of .NET Core SDK and msbuild common props defaults, so those can't be conditional. We could make others conditional, but then we would have some conditional and some unconditional and that would be even more confusing. I think it's simpler if we say import SDK first and then you can customize.

**Comment by natemcmaster** [comment]
I’ll keep a watchful eye to make sure Arcade is imported first.

**Comment by msbasanth** [comment]
@natemcmaster 

What is the tool that you used for viewing the hierarchy of properties imported with both Directory.Build.props and also explicitly imported props files.

Regards
Basanth

**Comment by natemcmaster** [comment]
http://msbuildlog.com/

**Comment by msbasanth** [comment]
> http://msbuildlog.com/

Thanks for sharing
