### ISSUE TITLE
SymbolUploader builds with old dependencies

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#14380]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

As SymbolUploader, SymStore and others are internal tools I won't comment further on them and which dependencies are stale. These tools need some updates.

It would also be good to make sure that they don't bring .NET Standard 1.x dependencies in anymore. This can automatically be validated by the Arcade SDK by setting this switch in the repos: https://github.com/dotnet/arcade/blob/d5ee27a55ec6383c29790f3ec666e7c87f7da022/Documentation/ArcadeSdk.md?plain=1#L1047

Related: https://github.com/dotnet/arcade/pull/14379 (which had to add a workaround for Microsoft.DotNet.Build.Tasks.Feed which brings SymbolUploader in).

cc @mmitche, @tommcdon, @hoyosjs, @mikem8361

**Comment by missymessa** [comment]
@mikem8361 It seems like this is going away, should we close this issue?

**Comment by epananth** [comment]
Symbol uploader cannot be updated anymore and it is going to be replaced by Symbols.exe, going to close this issue.
