### ISSUE TITLE
How to mirror packages to dotnet-public from other package feeds than nuget.org?

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#14393]
XUnit is one example which uses a separate feed to make not yet stable released packages available for testing/consumption: https://xunit.net/docs/using-ci-builds

Usually we just wait for a stable released package to appear on nuget.org but in time sensitive situations, i.e. right now before we branch-off for .NET 9 Preview 1, we need to consume prerelease packages to unblock dependency flow.

How is that supposed to work? I don't see any mention of being able to control the package feed sources [here](https://github.com/dotnet/arcade/blob/main/Documentation/MirroringPackages.md).

**Comment by ViktorHofer** [comment]
If we don't want a self-service solution for this, that's OK to me. It then just needs someone on the dnceng side to do this manually.

**Comment by garath** [comment]
By security policy, dotnet-public is strictly for packages from nuget.org. 

Perhaps the general-testing feed for this case?

**Comment by riarenas** [comment]
@mmitche for his recommendation on how to do this securely. Using private unreleased packages in a preview makes me a little nervous in the first place.

I agree if we are pushing these packages to a feed, it should be dotnet-public 
I'm also hesitant to say use general-testing because I'd rather not add anything that isn't managed by the BAR into the BAR managed feeds, but I have less of a strong preference there.

We could create an exclusive feed. Which repos would need to restore these packages?

**Comment by riarenas** [comment]
BTW [we've already pushed these packages to dotnet-public](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1705654009869?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1705654009869&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1705654009869)

**Comment by mmitche** [comment]
This should have gone to something like dotnet-tools. As @garath mentions, dotnet-public is only for packages on nuget.org.

**Comment by dougbu** [comment]
suggest closing this issue w/ no action other than the move of a few packages to dotnet-tools. the more general answer is DncEng is available to get packages into any feed we control &mdash; dotnet-eng and dotnet-tools being frequent choices

**Comment by ViktorHofer** [comment]
That works for me. dotnet-tools isn't an option as not all repos which use xunit and consume Arcade use that feed. dotnet-eng works though as otherwise you cannot use the Arcade SDK itself.
