### ISSUE TITLE
Update pipeline templates to use `NetCore1ESPool-Publishing-Internal` pool

### ISSUE THREAD

**Issue by dougbu** [dotnet/arcade#14445]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Once we roll out the production `NetCore1ESPool-Publishing-Internal` pool (hopefully tomorrow) and thereby wrap up dotnet/dnceng#1145, we need to use the queue where appropriate. That includes the following small changes:
- update the dnceng pool used in the `Publish Assets` / `Publish to Build Asset Registry` job of eng/common/templates/job/publish-build-assets.yml to the new one
- update the dnceng pool used in `Publish using Darc` job of eng/common/templates/post-build/post-build.yml to use the new one
- update the dnceng pool used in eng/publishing/v3/publish.yml to new one
- eliminate all mention of the `useServicingBuildPool[s]` parameters (except perhaps a historical comment) from eng/promote-build.yml and eng/publishing/v3/publish.yml

this requires changes in all active Arcade branches:
- [x] main
- [x] release/8.0
- [ ] release/7.0 (if @mmitche thinks it's worthwhile for builds between now and EOL)
- [x] release/6.0

----

I'll file a separate dotnet/arcade-services issue about eliminating sending the top-level `useServicingBuildPool` to the build promotion pipeline.

----

Note the fix here causes a breaking change in the Maestro++ infrastructure. Please see dotnet/arcade-services#3258 for our reaction to that break (in `darc`).

**Comment by dougbu** [comment]
+ @missymessa in hopes you can do the backports of #14446 and tick off the non-main checkboxes above

**Comment by mmitche** [comment]
You can skip 7.0. It will be a decent comparison point (though it will still get the promotion job benefits)

**Comment by dougbu** [comment]
rollout in this case is just the arcade-validation pipeline. I'll validate the status tonight.

**Comment by dougbu** [comment]
done
