### ISSUE TITLE
`send-to-helix.yml` should support specifying the project path as a template parameter

### ISSUE THREAD

**Issue by radical** [dotnet/arcade#14470]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

IIUC, the files in `eng/common` are meant to be used as-is instead of making modifications to them. For the non-trivial helix case the `eng/common/helixpublish.proj` is not enough, and a custom project file has to be created (https://github.com/dotnet/arcade/blob/main/Documentation/AzureDevOps/SendingJobsToHelix.md#the-more-complex-case) . But the `eng/common/templates/steps/send-to-helix.yml` has the project file path and arguments fixed in the template, which would mean making a copy of the template and modifying that.

What is the recommended way of doing this? If the template can accept parameters for project path, and extra arguments to be passed to the build, then the template can be used as-is with a custom project file.

This was hit in https://github.com/dotnet/aspire/pull/1917 .

cc @joperezr @eerhardt

**Comment by akoeplinger** [comment]
adding the parameters sounds good to me, mind opening a PR?
