### ISSUE TITLE
Publishing test results to Azure DevOps doesn't support retry

### ISSUE THREAD

**Issue by safern** [dotnet/arcade#1450]
If there is a helix workitem that has ExitCode != 0, helix will retry this workitem. However if it fails once, the test cases that failed are published to AzureDev Ops as failed, then they are not updated, so the build will fail and tests that "passed on retry" would be shown as failed in the test results.

We should figure out a way to update the test case result.

cc: @alexperovich @markwilkie @ViktorHofer

**Comment by markwilkie** [comment]
@alexperovich - please take a look and see if there's a way to do this given the AzDO path.  It's kinda a big deal w/ corefx.

**Comment by danmosemsft** [comment]
+1 Without this, almost every leg/build has some kind of networking failure, which obscures "real failures".

(Yes, tests shouldn't be flaky, but progress has been made and it's not an easy problem. It is far more interesting if a test consistently fails.)

**Comment by mjanecke** [comment]
Not doing this. Closing. (AzDO is implementing their own thing).

**Comment by safern** [comment]
> Not doing this. Closing. (AzDO is implementing their own thing).

But the SDK will need to support publishing the results correctly so that they show in AzDO own thing, right? So there is actually work needed here?

**Comment by alexperovich** [comment]
The SDK already supports publishing the results correctly.
