### ISSUE TITLE
AzDO issue #5877

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#14502]
[Azure Boards WorkItem](https://dev.azure.com/dnceng/internal/_workitems/edit/5877)

**Comment by missymessa** [comment]
Triage: This should be deleted. Need to verify and close if so.

**Comment by missymessa** [comment]
So, it's still referenced, however: 
- The Official 1ES PTs cannot access them
- Cannot be accessed on the public builds because they lack the ability to access the secrets
