### ISSUE TITLE
Update release version in Generate-sbom.yml 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#14511]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The release version in Generate-sbom.yml needs to be updated whenever we have a new release.

**Comment by epananth** [comment]
Oh damn, I saw this now. I already created the PRs :(

**Comment by epananth** [comment]
thanks @riarenas

**Comment by riarenas** [comment]
No harm in updating if you already started looking into it! also makes sense that we'd do it in the servicing branches. We still don't know what's going to happen to those.

**Comment by epananth** [comment]
I will skip updating main, cos we are going to make that change in 1ES pipeline template.
