### ISSUE TITLE
Arcade release/7.0 PR failures

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade#14522]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

A few recent PRs to Arcades `release/7.0` branch are failing tests on Windows

- https://github.com/dotnet/arcade/pull/14507
- https://github.com/dotnet/arcade/pull/14504
- https://github.com/dotnet/arcade/pull/14509

Failure log from the first listed PR: https://helix.dot.net/api/2019-06-17/jobs/5f332db1-20da-4408-aacd-6d0268b23310/workitems/AspNetCoreTest/console

```
C:\h\w\AD090924\w\A2130988\e>powershell C:\h\w\AD090924\w\A2130988\u\aspnet-versioncheck.ps1 -aspNetCoreVersion 7.0.0 
.NET SDK '8.0.200' -- major version: '8.0'; preview: ''
ASP.NET SDK '7.0.0' -- major version: '7.0'; preview: ''
ASP.NET Core Runtime version and .NET Core Runtime version do not match -- update DotNetCli.props!

C:\h\w\AD090924\w\A2130988\e>set _commandExitCode=1 
```

I'm not sure this is the main cause. In the individual test [logs](https://helix.dot.net/api/2019-06-17/jobs/5292acb7-49d6-4a2c-896c-572eea1466f2/workitems/Microsoft.DotNet.Build.Tasks.Feed.Tests.dll/console) there is
```
+ dotnet exec --roll-forward Major --runtimeconfig Microsoft.DotNet.Build.Tasks.Feed.Tests.runtimeconfig.json --depsfile Microsoft.DotNet.Build.Tasks.Feed.Tests.deps.json /mnt/work/AB1F0951/p/xunit-runner/tools/netcoreapp2.0/xunit.console.dll Microsoft.DotNet.Build.Tasks.Feed.Tests.dll -nocolor -xml testResults.xml
dotnet: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by dotnet)
dotnet: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by dotnet)
+ export _commandExitCode=1
```

**Comment by missymessa** [comment]
Looks like all these PRs got merged, so closing this issue.
