### ISSUE TITLE
Avoid failing when GuardianConfiguration artifact already exists

### ISSUE THREAD

**Issue by jjonescz** [dotnet/arcade#14527]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

When I rerun roslyn official build after for example "Execute SDL" step fails, the re-run can never succeed since the "Publish GuardianConfiguration" will always report "##[error]Artifact GuardianConfiguration already exists for build 2390566."

[Recent example](https://dev.azure.com/dnceng/internal/_build/results?buildId=2390566&view=logs&j=f247cf43-855e-5fe0-b3bd-22e82628e238&t=62aacf81-511f-5948-03ee-b1116a25367b)

So I have to start a completely new official build which takes 2 hours.

Can we instead make the "Publish GuardianConfiguration" step optional so the pipeline continues even if the artifact exists? (Or delete/overwrite the previous artifact?) I don't know what the Guardian here is, but it doesn't seem crucial for the build to continue.

**Comment by dougbu** [comment]
@jjonescz does this issue remain in branches that have migrated to use the 1ES pipeline templates❔ I am wondering whether SDL support in dotnet/arcade should be removed soon after the migrations wrap.

**Comment by jjonescz** [comment]
You're right. The SDL step is currently disabled/skipped in 1ES templates, so the issue doesn't occur there, or at least not in SDL step, but it might occur in other steps where artifacts are uploaded similarly (during migration I have tried rerunning the pipeline at various stages and it often failed with similar error although I haven't investigated more deeply). Also I think the SDL step should be re-enabled, see [internal thread](https://teams.microsoft.com/l/message/19:32be8fb7e8164f8b95a112ab87d588c3@thread.skype/1710327476856).

**Comment by missymessa** [comment]
SDL scans should be used in conjunction with the Official 1ES PT. We will be removing SDL from Arcade as not to duplicate efforts between Arcade and 1ES PT. 

Please reach out to 1ES PT support channel if you need help with it. https://teams.microsoft.com/l/channel/19%3A6d24d44587aa4d868bd4e96fe0eead31%40thread.tacv2/Support%20-%20General?groupId=886b1d22-e648-4492-af5f-6fbe81e73d4a&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47

**Comment by missymessa** [comment]
1ES PT conversions should be completed. SDL is not injected into pipelines via Arcade. Closing this issue.
