### ISSUE TITLE
1ESPT conversion cleanup

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#14531]
- As part of cleanup from 1ES PT conversion, we should examine whether the CodeQL template we provide is still necessary or we can just direct to the 1ES path.

  https://github.com/dotnet/arcade/pull/14525#discussion_r1507976118

- Consider removing SDLValidationParameters - https://github.com/dotnet/arcade/pull/14525/files#r1508020331
- Validate whether setup-maestro-vars.yml is any use. I think its usefulness died with the addition of --default-channels in add-build-to-channel

**Comment by riarenas** [comment]
Adding a few more items

* Clean up any conditional that mentions running a PR, running as public, or running in the public project
* Understand whether we still need to generate SBOMs with our [own templates](https://github.com/dotnet/arcade/blob/main/eng/common/templates/steps/generate-sbom.yml#L4) or can solely rely on the template injected sbom generation

**Comment by dougbu** [comment]
re the CodeQL point: `parameters.PackageVersion` is a lousy name anyhow. we should at least fix that if the hook is still needed

**Comment by riarenas** [comment]
As a more general cleanup point:

* the public templates should only do public things
* the official templates should only do official things

**Comment by riarenas** [comment]
> > Understand whether we still need to generate SBOMs with our [own templates](https://github.com/dotnet/arcade/blob/main/eng/common/templates/steps/generate-sbom.yml?rgh-link-date=2024-02-29T19%3A02%3A27Z#L4) or can solely rely on the template injected sbom generation. This might not be possible, as the [Microbuild guidance](https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/38953/MicroBuild-Template-Migration-(YAML)?anchor=**use-1es-tooling-to-migrate-yaml-pipeline-to-the-microbuild-template**) is to keep using the manifest generator task...
> 
> if we keep our own SBOM task then we need to bump the package version since it wasn't bumped in main: #14511

Especially because a certain @riarenas said we should update it in main yet😛

**Comment by missymessa** [comment]
@chcosta do you know what the status of the clean up is? Is there more that we need to clean up from the migration?

**Comment by chcosta** [comment]
This is done for main.  Equivalent changes were never made to release branches because of wave 1 prioritization.  I'm not certain that this is a high enough priority for release branches at this time or in the near future.
