### ISSUE TITLE
What's the guidance when you have projects that only build on Windows?

### ISSUE THREAD

**Issue by rynowak** [dotnet/arcade#1454]
(see title)

Is there a recipe for this? The projects in question have WPF inside them and don't build on Mac/Linux (though they try).

I'm solving it right now using the following in `Build.props`
```
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ProjectToBuild Condition="'$(OS)'=='WINDOWS_NT'" Include="$(MSBuildThisFileDirectory)..\src\Razor\Razor.sln" />

    <ProjectToBuild Condition="'$(OS)'!='WINDOWS_NT'" Include="$(MSBuildThisFileDirectory)..\src\Razor\Razor.Slim.sln" />
  </ItemGroup>
</Project>
```

**Comment by tmat** [comment]
We use 2 solutions in Roslyn as well. I believe this is the best we can do right now without convoluted hacks, since we want to be able to work with the solution in an IDE on both OSes.

**Comment by markwilkie** [comment]
Not closing this as we'd like to do better, but moving out beyond at least P2.

**Comment by natemcmaster** [comment]
I started working on this earlier today because I believe this is a blocker for aspnet.

**Comment by markwilkie** [comment]
Ah - good to know @natemcmaster.  Could you explain a bit more what makes it a blocker so I understand better?

Moving to the preview epic until sorted.

**Comment by natemcmaster** [comment]
AspNet has multiple solutions which have overlapping projects. When specifying multiple solutions or when specifying the .csproj files directly, NuGet restore fails due to race conditions in calling RestoreTask multiple times for the same project.

I believe #1567 should address this.

**Comment by natemcmaster** [comment]
I've merged https://github.com/dotnet/arcade/pull/1567 and updated docs for Arcade SDK.

@rynowak let me know if you think this docs update makes it clear enough what to do: https://github.com/dotnet/arcade/blob/f657be5cb7cd4920334dd9162173b131211a1e17/Documentation/ArcadeSdk.md#example-conditionally-specifying-which-projects-to-build

**Comment by rynowak** [comment]
Doc updates look great. I'm closing this since I think it's super done 👍
