### ISSUE TITLE
eng/common/templates-official is missing changes from the last two months

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#14556]
This affects any file that got updated in the last two months in eng/common/templates. Here's an example for source-build.yml:

https://github.com/dotnet/arcade/blob/ae62c8d33c26fead308f9ad0f3bbc2018ecd1c14/eng/common/templates-official/steps/source-build.yml#L96 this file is missing the following changes:

1. https://github.com/dotnet/arcade/commit/121602686e08541612970b0714110a73ef2b00dc
2. https://github.com/dotnet/arcade/commit/269a0e658ebd52b02a34072dc99277be43fe58f7

This was causing vstest's official repo source-build leg to fail: https://github.com/microsoft/vstest/commit/9b8ef3e19c71f35412b38bc2e822f7412617d97e

cc @mmitche @MichaelSimons

**Comment by ViktorHofer** [comment]
cc @riarenas

**Comment by MichaelSimons** [comment]
The duplicated yml is going to be problematic and a potential bug farm.  @riarenas - Is it not possible to share the common logic more than what is currently done?  There is only one intentional line difference in this source-build template.

**Comment by riarenas** [comment]
Eventually the plan is to share, where we can, yes.

**Comment by MichaelSimons** [comment]
> Eventually the plan is to share, where we can, yes.

Can you link a tracking issue?

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade/issues/14524

**Comment by markwilkie** [comment]
In the meantime @MichaelSimons, regardless the fact that the entry points are split, it's possible to share code under the covers.  Do you have examples where sharing would be good to templatize overall as part of eng/common?

**Comment by MichaelSimons** [comment]
> In the meantime @MichaelSimons, regardless the fact that the entry points are split, it's possible to share code under the covers. Do you have examples where sharing would be good to templatize overall as part of eng/common?

Yes - These two files are identical outside of one line - the name of the task to execute for publishing.

https://github.com/dotnet/arcade/blob/main/eng/common/templates/steps/source-build.yml
https://github.com/dotnet/arcade/blob/main/eng/common/templates-official/steps/source-build.yml
