### ISSUE TITLE
Add Workload release channels

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/arcade#14573]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

For workloads from Aspire and Maui, we want to have separate channels for major version and separate channels for daily versus release. This is because there are some cohorts who want to test and flow individual builds and a broader set of users and dogfooders who we only want to end up testing specific builds.

We also want this for codeflow to the branches of the workload set repo: https://github.com/dotnet/workload-versions

Proposal:

|Major Version|BuildType|Channel|
|----|-----|-----|
|8.0|Daily|.NET 8|
|8.0|Release|.NET 8 Workload Release|
|9.0|Daily|.NET 9|
|9.0|Release|.NET 9 Workload Release|

The new versioned release channels would allow workload authors to push specific builds they plan on releasing (or they want specific 1P dogfooding from)

**Comment by marcpopMSFT** [comment]
CC @jonathanpeppers @joperezr

**Comment by jonathanpeppers** [comment]
The channels for the Release builds look good to me. 👍 

My only concern about the daily build, is MAUI currently has builds like:

* `.NET SDK 8.0.1xx SDK` - built with daily SDK from this same channel
* `.NET SDK 8.0.2xx SDK` - built with daily SDK from this same channel

There is a period of time we have builds from branches like `release/8.0.1xx`, `release/8.0.2xx`, etc. In the past we have also changed version bands for the workload on each of these branches, but we have been fine to stay on 8.0.100 the whole time now.

**Comment by joeloff** [comment]
Do we need internal channels too?

**Comment by marcpopMSFT** [comment]
If we have a security update for aspire/main, we could potentially use the .NET N Internal channel. I didn't want to use that today because those feeds are more locked down and so harder to work with for testing right before release but they could be a good alternative in that situation.

**Comment by mmitche** [comment]
Daily channels should go to dotnet8/dotnet9 feeds. release should go to dotnet8-workloads and dotnet9-workloads.
