### ISSUE TITLE
No way to flow MaxRetryCount to Helix clients from JobDefinition.SendAsync()

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#1457]
As seen here, there's no way to provide a value so it will always be 0 (no retries).

https://github.com/dotnet/arcade/blob/bd3e6b007d9a4b5d8926343e79e538dc2a52d7e5/src/Microsoft.DotNet.Helix/JobSender/JobDefinition.cs#L149

From discussions with @safern this is needed as well still have some flaky OSes like Nano where retry can be necessary to resolve strange problems with workitem timing.

**Comment by safern** [comment]
cc: @alexperovich @jonfortescue
