### ISSUE TITLE
Delete promote-build.yml in release branches 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#14598]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In our Arcade setup, we exclusively utilize main branch for promoting builds. Therefore, the promote-build.yml file should not be present in any of the release branches.

**Comment by riarenas** [comment]
@epananth, The changes to the release branches broke arcade-validation official in the publishing validation

**Comment by riarenas** [comment]
Maybe we just delete publishing validation in all non-main branches?

**Comment by epananth** [comment]
Merged. Closing this one
