### ISSUE TITLE
Update MicroBuildSigningPlugin to version 4

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#14643]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Needs to be done for: 
- [x] main: https://github.com/dotnet/arcade/pull/14644
- [x] release/6.0: https://github.com/dotnet/arcade/pull/14645
- [x] release/7.0: https://github.com/dotnet/arcade/pull/14646
- [x] release/8.0: https://github.com/dotnet/arcade/pull/14647

See this thread here: https://teams.microsoft.com/l/message/19:32be8fb7e8164f8b95a112ab87d588c3@thread.skype/1711144604895?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1711144604895&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=1ES%20PT%20Porting%20Effort&createdTime=1711144604895

**Comment by riarenas** [comment]
It looks like additionally, we want to set up the `MicroBuildOutputFolderOverride` to a folder that isn't scanned by default, such as the agent's temp directory.

**Comment by riarenas** [comment]
The plugin has been updated and the environment variable is now set on all branches
