### ISSUE TITLE
Remove `-pt` image use

### ISSUE THREAD

**Issue by dougbu** [dotnet/arcade#14652]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The `-pt` images in our pools are redundant and add nothing except extra verbiage for our customers. Unfortunately they're referenced in some dotnet/arcade branches. Need to check all of the branches below and remove that usage if found.

- [x] release/6.0
- [x] release/7.0 &mdash; if branch lasts long enough
- [x] release/8.0
- [x] main

**Comment by riarenas** [comment]
PRs to all branches have been merged.

**Comment by dougbu** [comment]
Not quite done. @chcosta opened #14717 because #14694 reverted 'main' to its previous `-pt` image use. Reopening and co-assigning to @chcosta (for final closure after PR is merged and arcade-validation is done)&hellip;
