### ISSUE TITLE
Fix up devdiv pool usage in official arcade templates

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#14651]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

There is at least one instance of the official Arcade templates where we are using the incorrect pool and image combination: https://github.com/dotnet/arcade/blob/release/6.0/eng/common/templates-official/post-build/post-build.yml#L139-L141

We should go through the templates to make sure we're consistent in our choice of pool + image in devdiv.

**Comment by dougbu** [comment]
@riarenas, could you please remove use of the `-pt` images while updating any other dotnet/arcade branch w/ this issue❔

**Comment by riarenas** [comment]
I think that will make the changes larger than I want to target them. I'll scope this issue just to fixing real blocking issues with using non-compatible images.

**Comment by riarenas** [comment]
6.0: https://github.com/dotnet/arcade/pull/14654

**Comment by riarenas** [comment]
I think it was good to create the other issue, I could only find the instances in #14654. I'll work on https://github.com/dotnet/arcade/issues/14652 next.

**Comment by riarenas** [comment]
I could only find two instances of broken pools. So I think this issue is done.
