### ISSUE TITLE
Tools.csproj makes it hard to use central package management

### ISSUE THREAD

**Issue by jaredpar** [dotnet/arcade#14693]
The `eng/common/internal/Tools.csproj` makes it difficult to migrate to Central Package Management. The lookup rules for MSBuild will find the `Directory.Packages.props` file in the root of a repository because `Tools.csproj` takes no steps to prevent this. That means in many cases that centralized package management rules come into play, `Tools.csproj` is not build for CPM and builds error out. 

To better facilitate repos migrating to CPM we need to take steps to insulate Tools.csproj from that. Think we should consider setting the following to do this: 

```xml
<ImportDirectoryPackagesProps>false</ImportDirectoryPackagesProps>
```

**Comment by mmitche** [comment]
Is a better solution to add a D.P.p in eng/common/internal/?

**Comment by jaredpar** [comment]
> Is a better solution to add a D.P.p in eng/common/internal/?

That definitely also works.

**Comment by jaredpar** [comment]
WRT to this idea 

```xml
<ImportDirectoryPackagesProps>false</ImportDirectoryPackagesProps>
```

This does not actually work inside a project file. The consideration for whether or not to import Directory.Packages.props occurs before the project file contents are processed (part of Sdk.props). In order for this property to be effective it has to be included in Directory.Build.props .
