### ISSUE TITLE
Tests marked with `OuterLoop` attribute ignore `-notrait category=failing`

### ISSUE THREAD

**Issue by mkhamoyan** [dotnet/arcade#14779]
While running [runtime-libraries-mono outerloop](https://dev.azure.com/dnceng-public/public/_build?definitionId=242&_a=summary) tests we noticed that test cases marked with the `OuterLoop` attribute, which also have attributes like `ActiveIssue` or `SkipOnPlatform`, are still being executed and causing failures in the pipeline.

For example, the following test will still run on the browser platform:
```
[OuterLoop]
[SkipOnPlatform(TestPlatforms.Browser, "Not supported on browser")]
```
The command passed to Xharness contains:

`-trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing `

This command should work correctly by excluding tests that shouldn't run on specific platforms.

_Side Note_: If we include the TestPlatforms parameter with the OuterLoop attribute, it respects the platform exclusion, and the tests are skipped as expected. For example:
```
[OuterLoop("Resource-intensive due to parallel processing", ~TestPlatforms.Browser)]
[SkipOnPlatform(TestPlatforms.Browser, "Not supported on browser")]
```

**Comment by akoeplinger** [comment]
This is an xharness-only issue, tracked at https://github.com/dotnet/xharness/issues/908

**Comment by mkhamoyan** [comment]
Thanks, I'll close this one.
