### ISSUE TITLE
Build logs are no longer gathered and published on error

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/arcade#14787]
When a build that is set to publish logs (for example, via setting artifacts.publish.logs) errors out, no logs are published. Successful builds do publish their logs.

@chcosta I think this is from https://github.com/dotnet/arcade/pull/14736

Example build failure without logs published: https://dev.azure.com/dnceng-public/public/_build/results?buildId=685790&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=d2b92d58-337d-5541-2ecb-d35f35f29352
'Gather logs for publish to artifacts' is skipped and then `Publish logs' can't actually publish anything, since logs weren't copied to the expected location..

The task for gathering logs to publish that isn't run:
https://github.com/dotnet/arcade/blob/de915412b21207ef5c99a9ebaddc6960712ccd91/eng/common/core-templates/job/job.yml#L242-L256
I think they just need `continueOnError: true`. But perhaps other places should also have that (maybe gathering binaries/packages?).

Before the template refactor:
https://github.com/dotnet/arcade/blob/857f51ec8dec7d2fe5403ada109559e5bc67afd0/eng/common/templates/job/job.yml#L208-L213

**Comment by chcosta** [comment]
Ack, I'll take a look tomorrow

**Comment by chcosta** [comment]
I'm validating a fix for this
