### ISSUE TITLE
Orchestrated final publish tasks are overwriting storage 

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1479]
The final publish tasks for blob storage in orchestrated builds are overwriting output storage even when they should not be.  Investigate and fix.

**Comment by mmitche** [comment]
This is because of this revert made a while back: https://github.com/dotnet/buildtools/pull/1914/files

**Comment by markwilkie** [comment]
@mmitche - has this been resolved?

**Comment by JohnTortugo** [comment]
This has been fixed now by refactoring Tasks.Feed to use Azure Storage SDK
