### ISSUE TITLE
Start Convention Doc

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#148]
While looking around I noticed that we are inconsistent with our naming convention for scripts, for example:

```
Build.cmd
build.sh
```

While it is minor and doesn't matter on windows I tend to lean towards using lowercase for our script names.  While we are starting to bring online more scripts and engineering based files (i.e. json/config/targets/props)  I thought it might be worth writing down a naming guideline, here is a first draft:

1. Filenames should be all lowercase `build.cmd` or `nuget.config`. Only exceptions are for files that needs to be cased a particular way for an existing set of tools to read them (Example: `Directory.Build.props` which msbuild expects exactly that case on linux).
2. Filenames with multiple words should use `kebab-casing` like `init-tools.sh`. 
3. Msbuild based targets and props files for a particular library should match the exact casing of the library package they belong to, like `Microsoft.DotNet.Build.Tasks.Feed.targets`. 

What do others think @tmat @natemcmaster @chcosta @markwilkie?

**Comment by weshaggard** [comment]
I agree that is an interesting idea but it is inconsistent and also doesn't help on windows. Personally I like consistency over a little convenience on one platform, but I'm open to other opinions and I can be convinced otherwise.

**Comment by natemcmaster** [comment]
+1 for consistent casing. `build.cmd`, `build.sh` is okay with me. I'm not worried optimizing for tab completion.

**Comment by jaredpar** [comment]
+1 for consistency. 

No real opinion on which casing.

**Comment by weshaggard** [comment]
OK so it sounds like most folks want consistency so we should stick to the rule of making everything lowercase by default.

**Comment by markwilkie** [comment]
I'll start a convention doc and add this to it.
