### ISSUE TITLE
Add more arcade specific telemetry

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#1481]
It's unclear what telemetry we're currently capturing via Arcade.  However, we should be capturing items like the following at minimum:
- build success/failure over time by team/repo/branch (hopefully this is an AzDO query)
- activity by channel  (likely just a darc query)
- Which AzDO custom tasks are being used
- which packages are being published where + volume (darc query??)
- Helix telemetry (in theory this already exist)

With this data, we should be able to better keep tabs on the our services and be able to make meaningful decisions moving forward

**Comment by jcagme** [comment]
I don't feel this issue is truly a validation issue since validation work blocks the progress forward of an Arcade build during the build. Telemetry data requires some sort of analysis to make a decision/take action but at the end is not validating the state of Arcade's assets.  Thoughts?
