### ISSUE TITLE
Provide localization guidance

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#1482]
This guidance mostly is "use  https://github.com/dotnet/xliff-tasks "

**Comment by jcagme** [comment]
Given that the link above has most xliff details, should we add a section in our docs pointing to it?

**Comment by markwilkie** [comment]
Yes @jcagme, I think that sounds right. In fact, I'm pretty sure there are already docs.  @nguerrera - I presume there are docs for the xliff stuff?

**Comment by nguerrera** [comment]
Cc @tmeschter 

The README there is the current extent of the docs. 

It would be nice to have contact info for getting the repo onboarded to getting handed off and handed back. But I think that would be the loc PM for any given team. Maybe there's an alias we can reference (not sure if we can list one publicly) or a reference to an internal page about that?

**Comment by tmeschter** [comment]
I see two aspects to this:

1. _Technical_ guidance on how to set up a repo to support localization. Partly that's addressed by the https://github.com/dotnet/xliff-tasks README.md, but I'm sure there are many holes. I'm happy to address those as they arise.
2. _Process_ guidance on how to get onboarded with the internal loc team and hand .xlf files back and forth. That's something we'll need to discuss offline, with the loc team involved. From my limited vantage point, that seems very ad hoc right now.
