### ISSUE TITLE
NuGet validation post-build step broken

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/arcade#14840]
This got broken with https://github.com/dotnet/arcade/pull/14809. /cc @premun

We probably are not importing the utils that contain `Write-PipelineTelemetryError` anymore.

https://dev.azure.com/dnceng/internal/_build/results?buildId=2472257&view=logs&j=a13e9384-d6d3-5a14-7a96-79282fc11262&t=62b78796-390e-5a19-0957-0b46593907e3&l=26

```
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_work\_temp\3d7689fe-b7a8-4ae6-a4de-f5c36b4e8928.ps1'"
at <ScriptBlock>, D:\a\_work\1\s\eng\common\post-build\nuget-validation.ps1: line 9
at <ScriptBlock>, D:\a\_work\_temp\3d7689fe-b7a8-4ae6-a4de-f5c36b4e8928.ps1: line 4
at <ScriptBlock>, <No file>: line 1
D:\a\_work\1\s\eng\common\post-build\nuget-validation.ps1 : The term 'Write-PipelineTelemetryError' is not recognized 
as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At D:\a\_work\_temp\3d7689fe-b7a8-4ae6-a4de-f5c36b4e8928.ps1:4 char:1
+ . 'D:\a\_work\1\s\eng\common\post-build\nuget-validation.ps1' -Packag ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Write-PipelineTelemetryError:String) [nuget-validation.ps1], CommandNot 
   FoundException
    + FullyQualifiedErrorId : CommandNotFoundException,nuget-validation.ps1
 ```

**Comment by premun** [comment]
Oh yeah, thanks. One import is missing there.

**Comment by akoeplinger** [comment]
The fix didn't work, I'm still seeing this in https://dev.azure.com/dnceng/internal/_build/results?buildId=2473882&view=logs&j=a13e9384-d6d3-5a14-7a96-79282fc11262&t=62b78796-390e-5a19-0957-0b46593907e3&l=16

```
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_work\_temp\b41a9dc4-57c4-4493-a99c-2d77ac970fb6.ps1'"
at <ScriptBlock>, D:\a\_work\1\s\eng\common\post-build\nuget-validation.ps1: line 16
at <ScriptBlock>, D:\a\_work\_temp\b41a9dc4-57c4-4493-a99c-2d77ac970fb6.ps1: line 4
at <ScriptBlock>, <No file>: line 1
```

/cc @andriipatsula

**Comment by andriipatsula** [comment]
Looking. I'll try to resolve the issue today.

**Comment by andriipatsula** [comment]
Somehow, the [nuget-verification.ps1](https://github.com/dotnet/arcade/blob/main/eng/common/post-build/nuget-verification.ps1) script didn't propagate to your repo. <-- that's the reason. We are looking to mitigate the problem.

**Comment by andriipatsula** [comment]
Maestro++ should have overridden the entire /eng/common folder, but it didn't

**Comment by akoeplinger** [comment]
ohh interesting

**Comment by andriipatsula** [comment]
Hm, that could be because Maestro++ clones a repo, copies files, and creates a commit on a machine. I suggest removing this .gitignore rule or making it more explicit. You can manually copy the file into /eng/common or wait for the next dependency update from Arcade.

**Comment by akoeplinger** [comment]
I fixed the .gitignore and a new arcade update contained the file, thanks :)

I think you can pass `-f` to `git add` so it ignored .gitignore rules, might be something we should do for the eng/common files.
