### ISSUE TITLE
Azdo outage. Broken dnceng builds

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade#14854]
### Build

https://dev.azure.com/dnceng/internal/_build/results?buildId=2475470&view=logs&j=bc38e8b8-e027-53cb-48e7-2adbd1070eca&t=d93c51ac-9522-4730-bf6b-2627d2523284&l=60

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "Error Malformed DboConnectionInfo",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by premun** [comment]
@andriipatsula the wiki link was wrong, please use this template instead: https://github.com/dotnet/arcade/issues/new?assignees=&labels=First+Responder%2CKnown+Build+Error&projects=&template=z-build-break-infrastructure-issue-template.yml

**Comment by andriipatsula** [comment]
thanks. closing this one
