### ISSUE TITLE
[dnceng-bot] Branch `release/8.0` can't be merged to Azure DevOps internal branch

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/arcade#14884]
Branch [release/8.0](https://github.com/pavelsavara/runtime/commits/release/8.0/) can't be mirrored from GitHub to Azure [internal/release/8.0](https://dev.azure.com/dnceng/internal/_git/pavelsavara-runtime?version=GBinternal%2Frelease%2F8.0&_a=history) via internal merge. 

There are conflicting commits in the target branch.
The branch is configured to be mirrored via automated merge. 
The situation is rare but normal. The target branch is expected to receive manual commits in the Azure DevOps clone, which could cause conflict.

Conflicts need to be **resolved to unblock the code flow**.
- you can resolve the issue by resolving the conflict in the **target branch only**. 
    - **Please make sure that the changes sensitive from security perspective are not published ahead of time to GitHub!**
- reverting the extra commits in the Azdo target branch.
- you can disable the mirroring of the branch in the [configuration file](https://dev.azure.com/dnceng/internal/_git/dotnet-mirroring?path=/C:\Dev\dotnet-mirroring\testing-dnceng-subscriptions.jsonc).
- you can ask @dotnet/dnceng for help or read the [documentation](https://dev.azure.com/dnceng/internal/_git/dotnet-mirroring?path=/README.md).

**Comment by pavelsavara** [comment]
this was just testing

**Comment by mmitche** [comment]
@pavelsavara The repo name should be included in the issue if it's being file to arcade.

**Comment by riarenas** [comment]
Pavel is way ahead of you! https://github.com/dotnet/arcade/issues/14885
