### ISSUE TITLE
GenerateReferenceSource does not always add the 'new' modifier

### ISSUE THREAD

**Issue by tannergooding** [dotnet/arcade#1488]
For the hardware intrinsics, we currently have some nested types that mask and inherit from a nested type in the base class. GenerateReferenceSource does not currently add the required `new` modifier in this scenario.

For example, there should be a `new` modifier on `Sse2.X64` in the below code.
```csharp
public abstract partial class Sse
{
    public abstract partial class X64 { }
}

public abstract partial class Sse2 : System.Runtime.Intrinsics.X86.Sse
{
    public abstract partial class X64 : System.Runtime.Intrinsics.X86.Sse.X64 { }
}
```

**Comment by tannergooding** [comment]
CC. @ahsonkhan. 

This came about from https://github.com/dotnet/corefx/pull/33892

**Comment by ahsonkhan** [comment]
cc @ericstj, @weshaggard 

Thanks @tannergooding for running the tool and discovering these edge cases that need fixing.

**Comment by ericstj** [comment]
Bug is in https://github.com/dotnet/arcade/blob/fe25f076bdd44568aa6334d4266e6553719cf91d/src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Types.cs#L147

I don't think `new` here is persisted in metadata, so a fix here would need to examine the members of the base type.

You should be able to workaround this by adding `new` in partial definition via a manual file with the following:
```c#
public partial class Sse2
{
    public new partial class X64 { }
}
```

/cc @wtgodbe
