### ISSUE TITLE
Be able to build, sign publish an specific package

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#1494]
I'm not sure if this is possible today but: wouldn't it be useful to be able to build + [sign] + publish individual Arcade packages? A scenario I've in mind where this would be useful IMO is for fixing problems on specific packages. E.g.,

- I make a change to a single package, let's say Tasks.Feed (need to wait a bunch of minutes because all packages in the repo are built, signed + published)
- Plug the new version of the package in the repo (e.g., Version.props)
- Wait a couple of minutes to reach the publishing step to find out that something was wrong with the change I made in step 1.

This is **particularly** useful for packages that depend on the environment they are executing like Signing (i.e., be able to test the real sign path) and Tasks.Feed (for testing artifact publishing).

@mmitche @jcagme @markwilkie

**Comment by tmat** [comment]
Adding tests of your should help you to discover issues early. 
The packages need to be written in such way that allows testing without accessing the real service.

**Comment by markwilkie** [comment]
There is a need from time to time for repos to publish one-off packages.  Generally the reasons for this is not very good, but this issue probably deserves revisiting to see what the right business priority is.  I've assigned it to the next signtool epic for post preview 2 evaluation.

**Comment by JohnTortugo** [comment]
> Adding tests of your change should help you to discover issues early.
> The packages need to be written in such way that allows testing without accessing the real service.

There are other situations as well. For instance, when fixing bug in specific packages. Why would we need to recompile the whole repo?

**Comment by tmat** [comment]
And why not recompile the whole repo? You need to get the package signed anyways before publishing it. So you need an official build to run.

**Comment by Chrisboh** [comment]
Since this opened we haven't really had this be an issue.  If this does because problematic in the future we can revisit.
