### ISSUE TITLE
The sign type is set to 'real' even if the `_SignType` variable is defined

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade#14980]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In the [dotnet/test-templates/azure-pipelines.yml](https://github.com/dotnet/test-templates/blob/main/azure-pipelines.yml#L20-L21) pipeline, customers are defined the `_SignType` with the `test` value. But in the [build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=755023&view=logs&j=7c8326b9-0a5f-532a-e6de-db8515c72d9a&t=cab6e3f0-aa10-5bbb-514b-fc6a638553f8), the SignToolTask produces an output `Signing mode: Real`.

That means that the value of `DotNetSignType` is set to `real`
https://github.com/dotnet/arcade/blob/c45d41114722ff910cde462f4be003b1d7fde58f/src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.proj#L49-L50 because we have a validation and raise an error if the parameter is an empty string or not equal to `real` or `test`
https://github.com/dotnet/arcade/blob/c45d41114722ff910cde462f4be003b1d7fde58f/src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.proj#L42-L43

and we set the value of `DotNetSignType` in https://github.com/dotnet/arcade/blob/c45d41114722ff910cde462f4be003b1d7fde58f/eng/common-variables.yml#L26-L27

**Comment by andriipatsula** [comment]
@Evangelink, please close this issue if you find that the problem is on your side rather than with Arcade.

**Comment by Evangelink** [comment]
It's not clear if that's the expected behavior of arcade of not. Are we supposed to pass the sign info on the public PR pipelines?

**Comment by Evangelink** [comment]
@ViktorHofer confirmed we do need to pass the property so I'll be closing that issue.

**Comment by ViktorHofer** [comment]
Just to summarize our local discussion, SignType=real in public is absolutely fine as there's a second property: DryRun (in Sign.proj and Publish.proj) which determines if actually work gets sent to the signing backend. So, no need to pass SignType in on public.
