### ISSUE TITLE
Handle CLI as a bootstrapped native tool

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#151]
It would be nice to use the same native toolset bootstrapping system to acquire / use the cli.  Currently, we use a different system and CLI uses a [different env var](https://github.com/dotnet/arcade/pull/142#pullrequestreview-119574268) to reference it's install directory (DOTNET_INSTALL_DIR vs NETCOREENG_INSTALL_DIRECTORY).

We should examine if we can use native toolset bootstrapping to acquire the CLI.

**Comment by weshaggard** [comment]
To help reconcile this perhaps we can set DOTNET_INSTALL_DIR to NETCOREENG_INSTALL_DIRECTORY if it is set in side our wrapper dotnet-install script.

**Comment by markwilkie** [comment]
@weshaggard, @tmat, @livarcocc, and @natemcmaster - thoughts on what's left for CLI bootstrapping?

**Comment by natemcmaster** [comment]
I haven't looked at what's currently being done.

**Comment by livarcocc** [comment]
Is there an ask for the CLI team here? Setting the install script variable to the value of the NETENG variable seems reasonable to me.

**Comment by markwilkie** [comment]
Ok, moving this to the guidance epic such that we're telling teams the right way to think about this.
