### ISSUE TITLE
CodeSignTask hitting long path error when signing SiteExtension packages with runtime store

### ISSUE THREAD

**Issue by pakrym** [dotnet/arcade#1513]
I'm trying to sign a SiteExtension nuget package that contains dotnet runtime store 

Signing fails with the following error:

```
 SignToolTask starting.
  DryRun: True
  Signing mode: Real
  MicroBuild signing logs will be in (Signing*.binlog): D:\github\aspnet\AspNetCore\artifacts\logs\
  MicroBuild signing configuration will be in (Round*.proj): D:\github\aspnet\AspNetCore\obj\
C:\Users\pakrymet\.dotnet\buildtools\korebuild\3.0.0-build-20181207.1\modules\KoreBuild.Tasks\CodeSign.targets(51,5): error : The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\Users\p akrymet\.dotnet\buildtools\korebuild\3.0.0-build-20181207.1\KoreBuild.proj]
  SignToolTask execution finished.
```

After attaching to MSBuild and catching the first change exception I was able to figure out that the path that is being create is 
`D:\github\aspnet\AspNetCore\obj\ContainerSigning\16D285869A01B4C54E3C5CDA81CE0A9B075BD2A43F824EAFB00AFB3B3FC4497F\content/store/x64/netcoreapp3.0/microsoft.aspnetcore.azureappservices.hostingstartup/3.0.0-preview-1999-0010/lib/netcoreapp3.0/Microsoft.AspNetCore.AzureAppServices.HostingStartup.dll`

So even if I remove my base directory  `obj\ContainerSigning\16D285869A01B4C54E3C5CDA81CE0A9B075BD2A43F824EAFB00AFB3B3FC4497F\content/store/x64/netcoreapp3.0/microsoft.aspnetcore.azureappservices.hostingstartup/3.0.0-preview-1999-0010/lib/netcoreapp3.0/Microsoft.AspNetCore.AzureAppServices.HostingStartup.dll` is still 270 characters long.

Not sure how to fix or workaround this.

**Comment by JohnTortugo** [comment]
I think I might do something to try to reduce the size of the temp container signing folder. That is, reducing from `16D285869A01B4C54E3C5CDA81CE0A9B075BD2A43F824EAFB00AFB3B3FC4497F` to something like `16D28586`. I'll look into it. @tmat any idea here?

**Comment by tmat** [comment]
Yes, why don't we enable long paths?

**Comment by JohnTortugo** [comment]
I didn't know that was possible :-/ . Still, the public builds (i.e., [the failing one](https://dnceng.visualstudio.com/public/_build/results?buildId=54875)) are run on hosted agents, can we control that option on those agents? @chcosta @riarenas

**Comment by pakrym** [comment]
We would have to enable long path for MSBuild inside VS. It seems that it's not that trivial (https://github.com/Microsoft/msbuild/issues/2338#issuecomment-317021561)

**Comment by rainersigwald** [comment]
Not until recent 16.0 builds, where it's on silently (https://github.com/Microsoft/msbuild/pull/3507).

**Comment by tmat** [comment]
I see. Cool, good to know that we can get rid of any workaround that we implement once we move to 16.0. @JohnTortugo let's implement a workaround then and file an issue to remove it once we move to msbuild 16.0

**Comment by tmat** [comment]
@JohnTortugo actually, if you implement my suggested workaround we don't need to have the issue. It can be kept.
