### ISSUE TITLE
Darc authenticate opens an editor with no content and shows no console output

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1514]
I have Sublime Text set as my git editor. Darc commands open new editor windows with no content and no console instructions on what to do.

## Repro:

1. Set git editor: `git config -g core.editor 'subl -w'`
1. run `.\eng\common\darc-init.ps1`
2. run `darc authenticate`

## Result
No content in the editor
![image](https://user-images.githubusercontent.com/2696087/49751254-cb70e180-fc61-11e8-94b9-3385628c7463.png)
No console output

![image](https://user-images.githubusercontent.com/2696087/49751280-d88dd080-fc61-11e8-8cf0-9040642d8f07.png)

## Info
```
PS> darc --version
Microsoft.DotNet 1.0.0-beta.18570.17+93b39c3209a5929662190c7e85b43b4f2a32bab1
```

**Comment by natemcmaster** [comment]
Same thing happens with VS Code. (`git config core.editor 'code -w'`)

![image](https://user-images.githubusercontent.com/2696087/49751431-31f5ff80-fc62-11e8-8a9d-4472ca7b1411.png)

**Comment by jcagme** [comment]
Weird... Just for kicks, could you update to `1.0.0-beta.18607.6`. Change the SDK version in `global.json` and run `eng/common/darc-init` again

**Comment by natemcmaster** [comment]
Same issue with 1.0.0-beta.18607.6.

**Comment by jcagme** [comment]
Something changes if you change to something like notepad++?

**Comment by natemcmaster** [comment]
I haven't found a setting for core.editor that works.

**Comment by jcagme** [comment]
Ok, will need to take a look since things work for me with notepad++.

**Comment by mmitche** [comment]
@natemcmaster is this still happening?

**Comment by natemcmaster** [comment]
No, I think you fixed this one by changing the 'UseShellExecute' setting on ProcessStartInfo.
