### ISSUE TITLE
Revert Python Version Downgrade when Signing on Mac and Linux

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/arcade#15151]
Due to https://portal.microsofticm.com/imp/v3/outages/details/438336221/overview, we have to hardcode the Python version to 3.11.x down from 3.12 when signing on Mac and Linux machines.

We should remove [this version downgrade](https://github.com/dotnet/arcade/blob/eae5081afff305d2f5c3e418f0c03817b9469998/eng/common/core-templates/steps/install-microbuild.yml#L11-L15) this once the outage has been resolved.

**Comment by garath** [comment]
@ellahathaway is this something for you or something dnceng needs to take action on?

**Comment by ellahathaway** [comment]
Closed with https://github.com/dotnet/arcade/pull/15326
