### ISSUE TITLE
`darc authenticate` on macOS fails with an error

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1516]
I'm trying to follow directions in https://github.com/dotnet/arcade/blob/master/Documentation/DependencyFlowOnboarding.md, and getting stuck on setting credentials using `darc authenticate`

## Repro:

1. Run `./eng/common/darc-init.sh`
2. Run `darc authenticate`

## Result

If `git config core.editor` is set to `vim`, I get
```
$ darc authenticate
The file /Users/namc/src/aspnet/AspLabs/vim does not exist.
```

If `git config core.editor` is set to `subl -w`, I get
```
$ darc authenticate
open: invalid option -- w
Usage: open [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-s <partial SDK name>][-b <bundle identifier>] [-a <application>] [filenames] [--args arguments]
Help: Open opens files from a shell.
      By default, opens each file using the default application for that file.
      If the file is in the form of a URL, the file will be opened as a URL.
```

If I remove my git config settings, I run into #1514 

## Info

```
$ darc --version
Microsoft.DotNet 1.0.0-beta.18607.6+e8b77277ce388a80223941927a0e4388d02b7233%
```

**Comment by mmitche** [comment]
@natemcmaster is -w is a valid option to subl?  I don't see that in the list.

**Comment by natemcmaster** [comment]
`-w` is an option for the editor (`subl -w`), not for `open`.
