### ISSUE TITLE
Need PAT that can be used with the MicroBuild release tasks

### ISSUE THREAD

**Issue by rynowak** [dotnet/arcade#1518]
I need a PAT(s) that can be used with the following MicroBuild release tasks:
- Upload Azure DevOps Drop
- Create Insertion PR

This is for automating a VS insertion workflow, so they need permissions on devdiv.visualstudio.com

/cc @MattGal

**Comment by markwilkie** [comment]
@MattGal - thoughts on next steps?

**Comment by rynowak** [comment]
I know that we need something that's accessible from dnceng/internal but with permissions to access stuff on devdiv. 

Naming is for ya'll to decide. 

We'll need a PAT for drop management and also for creating PRs. I don't think it's important if they are the same token or not.

**Comment by MattGal** [comment]
OK I couldn't find Mark and it's not a big amount of work, will just crank this out for you.

**Comment by MattGal** [comment]
Created DotNet-DevDiv-Insertion-Workflow-Variables with variable 'dn-bot-devdiv-drop-rw-code-rw'

**Comment by rynowak** [comment]
Thanks I'll give this a try and get back to you.

**Comment by rynowak** [comment]
@MattGal - this is failing due to a permissions error https://dnceng.visualstudio.com/internal/_releaseProgress?releaseId=651&_a=release-pipeline-progress 

Can I have you double-check that I wired up the token correctly? I can stop by if necessary.

**Comment by MattGal** [comment]
Taking a peek.

**Comment by MattGal** [comment]
Looks like you didn't add the variable group, I added it here:
![image](https://user-images.githubusercontent.com/7862010/50016528-4eee4380-ff7e-11e8-9f8b-c52adf5afd63.png)

... this means you passed your PAT as $(dn-bot-devdiv-drop-rw-code-rw) which hopefully would never be a valid token :)

Can you try again now?

**Comment by rynowak** [comment]
Oh wierd. I thought I did that. Thanks!

**Comment by MattGal** [comment]
did it work?

**Comment by rynowak** [comment]
We still have some issues here related to permissions... from the email thread:

> Sorry about the confusion. You’re the 1st team trying to insert to devdiv from a different org, so we’re having a few bumps here. As long as you’ve selected all the Release perms (in addition to the others you already have), that should cover it.

**Comment by rynowak** [comment]
@markwilkie - if @MattGal is out can someone else help with this minor permissions issue? Getting the VS insertion workflow 100% complete would be a lovely christmas gift.

**Comment by MattGal** [comment]
Sorry I was not feeling well.  I'll try updating the PAT today, can I just spin the build to test it out?

**Comment by MattGal** [comment]
I believe I've done what Rick asked for here: dn-bot-all-drop-rw-code-rw-release-all

Note that the "Drop" permission interestingly only exists in the devdiv.visualstudio instance?

**Comment by rynowak** [comment]
Thanks Matt, I'll give this a try and get back to you.

**Comment by rynowak** [comment]
Yep. Tried again and still encountering an error: https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-environment-logs&releaseId=711&environmentId=2117

So we can create PRs, but we're still blocked on adding/assigning people to look at them.

**Comment by markwilkie** [comment]
@rynowak - is this still an issue?

**Comment by rynowak** [comment]
Yes, this is still an issue We're not blocked, but it's not 100% working. I think what would be really helpful here would be for @MattGal to get in touch with the MicroBuild people and make sure they agree on the set of permissions that are required. 

I'll ping the email thread we had going.

**Comment by markwilkie** [comment]
Any update on this?

**Comment by MattGal** [comment]
I will follow up, I think there was a miscommunication where Ryan was using a different PAT than the one I kept adding permissions to and he should be unblocked.

**Comment by markwilkie** [comment]
@MattGal  - did this get resolved?

**Comment by MattGal** [comment]
In as much as Ryan's stuff works yes.  We never iterated with an actually-scoped-down PAT, it currently still has full access AFAIK.

**Comment by markwilkie** [comment]
Ok....closing this issue as it sounds like there's not much more to do.  However, if there is (like scoping), please reopen.
