### ISSUE TITLE
VSTS build telemetry doesn't work completely when VSTS has issues/delays scheduling the builds.

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#152]
This may become a problem at some point. If/When it does we need a solution. Any solution for this would require deeper integration with VSTS than we have right now.

**Comment by markwilkie** [comment]
Given that we don't have a specific problem that needs fixing right now, nor is there really any actionable plan, I'm closing this issue.  We've got MUCH on our plate, and if (when...grin) this comes back, we'll have more clarity on the scenario to fix.
