### ISSUE TITLE
.tar.gz files not being correctly repacked with SignTool in .NET 8.0

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/arcade#15232]
It was revealed today that .tar.gz files are not being correctly repacked when signing with SignTool in .NET 8.0.

Here are examples of builds:
- [Build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2553033&view=results) with correct .tar.gz (no runpacking/repacking of .tar.gz with SignTool)
- [Build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2577473&view=results) with incorrect .tar.gz (unpacking/repacking of .tar.gz with SignTool)

Looking through the binlogs, it appears that the files get extracted correctly from the containers, but it is unclear why they do not get properly repacked.

We should investigate this, as this could negatively impact signing for repos who attempt to use the tooling for these files.

cc @tmat - Including you on this since I believe you wrote [the unpacking/repacking tar infra](https://github.com/dotnet/arcade/pull/13999) that SignTool uses for these files. For context, I enabled the unpacking of `.tar.gz` files using the tooling you wrote with [this 8.0 PR](https://github.com/dotnet/arcade/pull/15202)

**Comment by ericstj** [comment]
@ellahathaway can you describe how the files are not correct?  Are things missing, are paths wrong, attributes missing, corrupt files, etc?

**Comment by ellahathaway** [comment]
> [@ellahathaway](https://github.com/ellahathaway) can you describe how the files are not correct? Are things missing, are paths wrong, attributes missing, corrupt files, etc?

Yes - files were missing from the repacked container.

**Comment by ellahathaway** [comment]
@ViktorHofer - I see that your PR addressed this issue for main (thank you for fixing that btw). Assuming that we plan to backport your fix to 8.0, we keep this issue open until we finish the backport?

**Comment by ViktorHofer** [comment]
Do we need to backport this to 8.0? I thought we don't run this path in that branch anymore (@mmitche mentioned a revert offline).

**Comment by mmitche** [comment]
I reverted the functionality in 8.0 so good to go there.

**Comment by ellahathaway** [comment]
Sounds good. If the functionality isn't being invoked, then I don't see a reason to open this with the intent to backport Viktor's changes to 8.0. Thanks for the clarification.
