### ISSUE TITLE
Check file attributes in pkg tool testing

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/arcade#15267]
Based on https://github.com/dotnet/arcade/pull/15205#discussion_r1847416214.

In addition to [checking file hashes](https://github.com/dotnet/arcade/issues/15219) when testing the MacOSPkg tool, it would be beneficial to add tests that check for file attributes (and extended attributes). This will ensure that all relevant file metadata is preserved and verified during the unpacking and repacking process of pkg files.

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/arcade/pull/15270
