### ISSUE TITLE
Move Arcade to DotNet VSTS Public CI

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#153]

**Comment by jaredpar** [comment]
Do we have any documentation on what the equivalent of netci.groovy is for VSTS? I know it's not fully fleshed out yet but an understanding of the final state will help us as we begin porting individual jobs over.

**Comment by chcosta** [comment]
There's no real documentation covering the scenario that I've found (yet).  We should be using the same .vsts-ci.yml file but provide conditions / templates for PR scenarios.

https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?tabs=batch&view=vsts#buildreason

ie
```
- phase: B
  dependsOn: A
  condition: and(succeeded(), eq(variables['build.reason'], 'PullRequest'))
```
