### ISSUE TITLE
Can't Ctrl-C out of Installing dotnet cli in Windows command prompt hangs

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#1534]
@hughbe commented on [Thu Jun 15 2017](https://github.com/dotnet/corefx/issues/21078)

Normally I can press Ctrl-C and quit the currently exectuting task in the WIndows command prompt.

However, things seem to jam up and hang if I press control C when installing the dotnet cli.

This is a pain because my slow internet takes upwards of 1 hour to download the CLI, and I also often get errors like these and can't quit the build...

```
C:\Users\hugh\Documents\GitHub\corefx>build
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\GenFacades.Core.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\Microsoft.Cci.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\Microsoft.Cci.Extensions.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\Microsoft.DotNet.Build.Tasks.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\Newtonsoft.Json.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\NuGet.Common.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\NuGet.Packaging.Core.Types.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\NuGet.Packaging.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\NuGet.ProjectModel.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\NuGet.Versioning.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\roslyn\tools\Microsoft.Build.Tasks.CodeAnalysis.dll - Access is denied.
C:\Users\hugh\Documents\GitHub\corefx\Tools\net46\System.Diagnostics.TraceSource.dll - Access is denied.
Installing dotnet cli...
```

---

@karelz commented on [Thu Jun 15 2017](https://github.com/dotnet/corefx/issues/21078#issuecomment-308623061)

@weshaggard @mellinoe any idea how to route it? This is significantly impacting contributor workflow :(

---

@danmosemsft commented on [Thu Jun 15 2017](https://github.com/dotnet/corefx/issues/21078#issuecomment-308779282)

Does Ctrl-Break work? Usually that's not ignorable, wheras Ctrl-C relies on the app handling it.

---

@weshaggard commented on [Thu Jun 15 2017](https://github.com/dotnet/corefx/issues/21078#issuecomment-308873050)

Also the access denied part is generally caused because msbuild or VS is holding locking those libraries so they cannot be updated. You generally need to shutdown those processes to unlock those files. 

---

@danmosemsft commented on [Fri Jun 16 2017](https://github.com/dotnet/corefx/issues/21078#issuecomment-308879026)

And VBCSCompiler.exe. Taskkill that, devenv and msbuild...

---

@hughbe commented on [Wed Jun 21 2017](https://github.com/dotnet/corefx/issues/21078#issuecomment-309946328)

Sorry for the delay answering. I don't actually have a break key on my laptop - indeed I've never actually heard of one before!
https://en.wikipedia.org/wiki/Break_key shows some substitute key combinations for dell laptops, but they don't seem to work either

What I meant about the access denied errors is that if they occur I don't really want the build to continue, However, I can't exit the build at this point which is a pain

---

@ViktorHofer commented on [Sun Aug 12 2018](https://github.com/dotnet/corefx/issues/21078#issuecomment-412340274)

I think we should address this as the "ordinary" dev expects Ctrl + C to just work. I also hit this when I started to work in corefx.

---

@ViktorHofer commented on [Tue Dec 11 2018](https://github.com/dotnet/corefx/issues/21078#issuecomment-446245878)

Moving to arcade as they are now the owners of the bootstrap script.

**Comment by markwilkie** [comment]
@ViktorHofer - as far as I can tell, this is a CLI issue.  Am I misunderstanding?

cc/ @livarcocc

**Comment by ViktorHofer** [comment]
This is about not being able to stop the download of the SDK zip archive which is the first step when calling .\build. That should be part of arcade, right?

**Comment by markwilkie** [comment]
Arcade isn't doing much:

```
function GetDotNetInstallScript([string] $dotnetRoot) {
  $installScript = "$dotnetRoot\dotnet-install.ps1"
  if (!(Test-Path $installScript)) {
    Create-Directory $dotnetRoot
    Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile $installScript
  }
```

**Comment by tmat** [comment]
Also then executing the script that it downloads
```
$installScript = GetDotNetInstallScript $dotnetRoot
& $installScript -Version $version -InstallDir $dotnetRoot
```

https://github.com/dotnet/arcade/blob/master/eng/common/tools.ps1#L154

**Comment by tmat** [comment]
Actually, we should switch to our utility function instead of using `&` operator: https://github.com/dotnet/arcade/blob/master/eng/common/tools.ps1#L60
This might help.

**Comment by danmosemsft** [comment]
Indeed I see this in that function:
```
    while (-not $process.WaitForExit(100)) { 
      # Non-blocking loop done to allow ctr-c interrupts
    }
```
Perhaps there are other cases of this pattern that should move to the utility function?

**Comment by tmat** [comment]
I don't think so, but I'll look for other usages of `&` operator in init.ps1 and update it.

**Comment by markwilkie** [comment]
@ViktorHofer - did this get resolved?  (I seem to recall it did)

**Comment by ViktorHofer** [comment]
No it still doesn't stop the download. The "terminate the batch job" questions only appears when the download is finished. Also I noticed that regardless of my answer it stops the job:

```
C:\git\corefx2>.\build.cmd
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.401/dotnet-sdk-2.1.401-win-x64.zip
Terminate batch job (Y/N)? N

C:\git\corefx2>
```

**Comment by ViktorHofer** [comment]
@markwilkie afaik this is still an issue.
