### ISSUE TITLE
Maestro bot update PRs change file permissions on .sh files

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1535]
The bot-generated PR to update Arcade in aspnet/AspLab last night changed permissions on all of the .sh scripts from 755 to 644 (no +x permissions). This seems like a mistake, and may cause build failures for anyone invoking these scripts directly with a `chmod +x` first.

https://github.com/aspnet/AspLabs/pull/82

![image](https://user-images.githubusercontent.com/2696087/49815598-f9692b00-fd20-11e8-8afa-4a56d6aa6484.png)

![image](https://user-images.githubusercontent.com/2696087/49815650-1d2c7100-fd21-11e8-9baa-099c28b15cd0.png)

**Comment by markwilkie** [comment]
@mmitche - is this a darc thing?

cc/ @jcagme

**Comment by mmitche** [comment]
Oh, this must be related to jc's change to move to use Lib2git2sharp.

**Comment by markwilkie** [comment]
This seems like a big deal to me.  @mmitche / @jcagme - who's on point to fix this?

**Comment by mmitche** [comment]
I am.  But it's lower priority than automated rollout now.

We should be able work around this.  @natemcmaster Were those new files?  What's missing is an update of the git index's executable bit.  I *think* this should only affect new files. In that case, after the update is done you should be able to workaround the issue by updating the index and commiting the changes.  At that point, I don't think maestro will make an additional new modifications.

**Comment by natemcmaster** [comment]
> Were those new files?

No, as I described above, the bot changed existing files.

**Comment by markwilkie** [comment]
This not blocking in that the .sh files are sourced.   However, this really should be looked into further as it's goofy.

**Comment by mmitche** [comment]
Not required for preview 2 (and shouldn't be changing existing files now anyway since it's using a traditional git flow vs. octokit)

**Comment by markwilkie** [comment]
@natemcmaster - are you still seeing this happen?

**Comment by natemcmaster** [comment]
Nope.
