### ISSUE TITLE
tools.sh fails with "unbound variable $1"

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1536]
Maestro updated aspnet/AspLabs last night, and now darc-init.sh is busted.

Repro:
1. Clone https://github.com/aspnet/AspLabs/tree/6a5221fa44c327529e96ac02d70c4c92988b5f8b
2. Run `./eng/common/darc-init.sh`

Result:
```
/Users/namc/src/aspnet/AspLabs/eng/common/tools.sh: line 86: $1: unbound variable
```

**Comment by markwilkie** [comment]
@tmat

**Comment by markwilkie** [comment]
Sorry - meant @mmitche

**Comment by markwilkie** [comment]
@natemcmaster - was this resolved?

**Comment by natemcmaster** [comment]
Yes. Not sure when, but more recent version are fixed.
