### ISSUE TITLE
Allow parallel test execution

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/arcade#1539]
AspNet largely prefers to run our test assemblies in parallel, but there doesn't seem to be a way to set that in Arcade. Parallel tests help local development move faster and can serve as a canary for thread safety issues.

CC @natemcmaster who I talked about this with.

**Comment by natemcmaster** [comment]
We've implemented this in KoreBuild using `dotnet vstest`, which supports running parallel test assemblies for .NET Core and .NET Framework.

It appears the Arcade SDK uses xunit.runner.console which does not support parallel test assemblies in .NET Core.

**Comment by markwilkie** [comment]
Can you guys confirm that this issue is covered by https://github.com/dotnet/arcade/issues/1443?

**Comment by natemcmaster** [comment]
It's not covered by Helix. We still want to support contributors who run tests from the command line on their local machines.

**Comment by markwilkie** [comment]
Ah - let's chat more on this as I want to understand more about the scenario.  The current guidance is to always test using Helix, but I understand there's likely other scenarios and I'd like to understand what they are.

**Comment by natemcmaster** [comment]
The scenario is cloning source code and running `build.cmd -test`. We found that running test assemblies in parallel can shave dozens of minutes off test execution time. There are a handful of reasons why a contributor may not be able to run tests on Helix; most obvious one is because they don't work for Microsoft.

**Comment by tmat** [comment]
`build -test` runs tests for different projects in parallel (each project by its own xunit runner process). Is that not sufficient?

**Comment by tmat** [comment]
Not saying it's ideal, there are smarter ways to parallelize. Roslyn has a custom test runner that does better job scheduling runners. So the question is if you need more sophisticated parallelization.

**Comment by markwilkie** [comment]
What's the latest on this?

**Comment by natemcmaster** [comment]
Ryan is OOF. We should look at this more when he gets back.

**Comment by jcagme** [comment]
I think @ryanbrandenburg is back now

**Comment by singhsarab** [comment]
@markwilkie @tmat Since we are already considering using vstest, I think this one would also be taken care of.
