### ISSUE TITLE
Microsoft.DotNet.Build.Tasks.Feed.targets does not set output path

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#1555]
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed/build/Microsoft.DotNet.Build.Tasks.Feed.targets doesn't set AssetManifestPath, so the task attempts to write to the null path.

This target needs to set that (choosing a reasonable, but overridable default), and the task needs to validate it's inputs before taking action and produce useful error messages.

**Comment by markwilkie** [comment]
@JohnTortugo - please be sure this is sorted w/ the new publish stuff

cc/ @mmitche

**Comment by safern** [comment]
It is also missing to set: ManifestRepoUri

**Comment by JohnTortugo** [comment]
Hi @safern , are you blocked by this? I can try to give this a shot tomorrow in any case.

**Comment by safern** [comment]
Not really, I worked around by calling the Task directly on my targets, but was just wondering if this was on your soon to do list.
