### ISSUE TITLE
msbuild.ps1/.sh throws when used in -ci if nodeReuse is not set to false

### ISSUE THREAD

**Issue by safern** [dotnet/arcade#1559]
In build scripts we set nodeReuse to false when -ci flag is passed, for msbuild scripts we don't seem to do so. Now that we throw when ci is true and nodeReuse is true, people that use msbuild scripts using the -ci flag are forced to disable nodeReuse as an argument, which seems odd, and bath to force people to do, rather than doing it in the msbuild script before calling the msbuild function. 

This is the commit that introduced this behavior: https://github.com/dotnet/arcade/commit/ca315f22be3dccacb83ed8ec7c2446e5380a9adb

cc: @tmat

**Comment by safern** [comment]
Also, nodereuse parameter is not consistent in between ps1 and sh script. 

For ps1 it is `nodeReuse` with pascal casing.
For sh it is `nodereuse` all lowercase.

**Comment by tmat** [comment]
Re casing: The casing of `nodereuse` in bash scripts was fixed to `node_reuse`.

> In build scripts we set nodeReuse to false when -ci flag is passed, for msbuild scripts we don't seem to do so.

You mean `eng\msbuild.ps1` and `eng\msbuild.sh`? An oversight. These should disable node reuse as well on ci.

**Comment by tmat** [comment]
Would you mind sending PR to update `eng/msbuild.*`?

**Comment by safern** [comment]
> Would you mind sending PR to update eng/msbuild.*?

Sure. I'll do so. Assigned.
