### ISSUE TITLE
Determine viability of speculative package flow proposal

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#157]
@mmitche commented on [Tue Jan 02 2018](https://github.com/dotnet/core-eng/issues/2320)

Speculative package flow is a possible way to fix the  issues that are seen with the current orchestrated model.  However, there are questions as to how much gain might be attained by running the build in this scheme.

We can simulate this to a large degree though, given the full set of changes across the repos involved.  Develop a simulation that will determine the rate of builds produced.

---

@mmitche commented on [Mon Jan 08 2018](https://github.com/dotnet/core-eng/issues/2320#issuecomment-356021807)

Simulator now has almost the complete set of rules.  It's been run over the corclr->cli set of changes, and some tweaks need to be made.  Initial indications are that speculative flow might be reasonably good.

---

@mmitche commented on [Thu Jan 11 2018](https://github.com/dotnet/core-eng/issues/2320#issuecomment-357003944)

The set of rules currently implemented leads to a lot of wasted build time using the 'real' data.  I think they are probably too restrictive.   I think they mostly need to be re-implemented in terms of 'carried repo state', which basically means that we identify what changes are carried with a build of a repo, and the general rule is that a build should not continue if a commit would move the current repo state 'backwards'.

**Comment by dagood** [comment]
What's the result of this issue?

**Comment by markwilkie** [comment]
Moved to https://github.com/dotnet/arcade/issues/433
