### ISSUE TITLE
Eliminate conditions inside tasks - rely on VSTS build conditions instead.

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#158]
@karajas commented on [Thu Nov 09 2017](https://github.com/dotnet/core-eng/issues/2057)

Eg. Publish is run only when a powershell condition checks if ConfigurationGroup is Release, we should eliminate these.

---

@markwilkie commented on [Thu Mar 22 2018](https://github.com/dotnet/core-eng/issues/2057#issuecomment-375359794)

moving to prodcan as this should really happen.

**Comment by JohnTortugo** [comment]
Closing as this is quite outdated now.
