### ISSUE TITLE
Custom attributes file is not cleaned

### ISSUE THREAD

**Issue by sharwell** [dotnet/arcade#1588]
https://github.com/dotnet/arcade/blob/51db89556e676085aa06dbe1ae930ed4a3dd5f6a/src/Microsoft.DotNet.Arcade.Sdk/tools/Workarounds.targets#L43-L48

This property group should include the following property to ensure this file is cleaned at the appropriate times.

```
<TargetFrameworkMonikerAssemblyAttributesFileClean>true</TargetFrameworkMonikerAssemblyAttributesFileClean>
```

**Comment by tmat** [comment]
+1 for adding the property, but is it related to the race condition https://github.com/Microsoft/msbuild/issues/1479?
