### ISSUE TITLE
As an MC user, I can interact with auto-upgrade and mirroring builds

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#159]
@dagood commented on [Wed Jun 21 2017](https://github.com/dotnet/core-eng/issues/987)

This would let first responders file issues against failures using MC, and we would start getting telemetry.

---

@Chrisboh commented on [Wed Mar 28 2018](https://github.com/dotnet/core-eng/issues/987#issuecomment-376996792)

There should be no work on MC side of the house for this to work.  As long as the mentioned builds are instrumented everything else is free.  Kicking to triage to see if this would still be worth doing in that context.

**Comment by mmitche** [comment]
Closing in favor of #3650
