### ISSUE TITLE
Add override for IsShipping condition in Localization.targets

### ISSUE THREAD

**Issue by rladuca** [dotnet/arcade#1591]
Right now, [localization.targets](https://github.com/dotnet/arcade/blob/6d347be0654dcb05a1070162a33c3a4166ef6dcf/src/Microsoft.DotNet.Arcade.Sdk/tools/Localization.targets) requires IsShipping to be set in order to import the XLIFF tasks.

I don't think these should be coupled.  Specifically, the WPF repository isn't marked as shipping as it creates transport packages that are not directly published.

We'd like to be able to override the IsShipping condition on the inclusion of XliffTasks.

**Comment by tmat** [comment]
> WPF repository isn't marked as shipping as it creates transport packages that are not directly published

WPF should set `IsShipping` to true for libraries that eventually make it to customers. It does not matter if they are published directly to NuGet, thru an installer, or indirectly shipped by other component.

**Comment by nguerrera** [comment]
This sentence in the documentation is misleading :

> https://github.com/dotnet/arcade/blame/fa19e5a7dd74bca0dbea83b8a306457483534eec/Documentation/RepoToolset/MigrationToArcade.md#L16

**Comment by tmat** [comment]
It's clarified in the next sentence:
> - projects that produce NuGet packages that are not shipping on NuGet.org or **other official channel (like part of an official installer)**, 

I'll try to reword here to make it better:
https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#isshipping-bool
