### ISSUE TITLE
[Maestro++] Add ability to queue Maestro builds

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#160]
@karajas commented on [Tue Jun 06 2017](https://github.com/dotnet/core-eng/issues/876)

When Maestro fails to execute on a versions repo change due to for eg. api rate limiting, we need a mechanism for it to either retry after a set amount of time or allow a user to manually trigger a maestro update.

/cc @dagood 

---

@dagood commented on [Tue Jun 06 2017](https://github.com/dotnet/core-eng/issues/876#issuecomment-306626188)

I don't think Maestro should auto-retry (rather, the VSTS build that Maestro runs should do the right thing (https://github.com/dotnet/buildtools/issues/1043)) but being able to easily manually trigger an arbitrary Maestro subscription is tracked by https://github.com/dotnet/versions/issues/99. (I think we should leave this issue open to track status and raise visibility at least for now.)

---

@Chrisboh commented on [Tue Jun 13 2017](https://github.com/dotnet/core-eng/issues/876#issuecomment-308279019)

@karajas @dagood how often do we see this?

---

@karajas commented on [Tue Jun 13 2017](https://github.com/dotnet/core-eng/issues/876#issuecomment-308281483)

The bot has now been updated to use dotnet-maestro-bot so retry is no longer required, but we still need the ability to manually trigger a subscription run.

---

@Chrisboh commented on [Tue Jun 13 2017](https://github.com/dotnet/core-eng/issues/876#issuecomment-308282940)

@karajas is something else tracking that work? Can I close this issue?

---

@karajas commented on [Tue Jun 13 2017](https://github.com/dotnet/core-eng/issues/876#issuecomment-308283162)

There's the versions issue that Davis mentioned https://github.com/dotnet/versions/issues/99 

---

@dagood commented on [Wed Jun 21 2017](https://github.com/dotnet/core-eng/issues/876#issuecomment-310088647)

I think the title is restricting the implementation and feature--removing "from VSTS". This should be for any subscription, not just one that has a VSTS action. (I think it could be reasonable to trigger a "Maestro subscription triggerer" VSTS build, but not a GeneralExecutor build def.)

---

@MichaelSimons commented on [Fri Jun 30 2017](https://github.com/dotnet/core-eng/issues/876#issuecomment-312300977)

Design proposal was added to https://github.com/dotnet/versions/issues/99

---

@markwilkie commented on [Thu Jul 06 2017](https://github.com/dotnet/core-eng/issues/876#issuecomment-313489447)

Now that there's a proposal, moving this issue back into the backlog and making it part of the build reliability epic.

---

@markwilkie commented on [Thu Mar 22 2018](https://github.com/dotnet/core-eng/issues/876#issuecomment-375352294)

Moving to prodcon to make sure it's handled.

---

@dagood commented on [Thu Mar 22 2018](https://github.com/dotnet/core-eng/issues/876#issuecomment-375355165)

That's a very good fit: post-build steps are run using Maestro, and being able to run them easily manually will make it a lot easier to rerun in the case of failure and develop new post-build steps.

---

@maririos commented on [Tue May 08 2018](https://github.com/dotnet/core-eng/issues/876#issuecomment-387481253)

@MichaelSimons are you planning on working on this? or now that it is in ProdCon should we remove you from it.

---

@MichaelSimons commented on [Tue May 08 2018](https://github.com/dotnet/core-eng/issues/876#issuecomment-387483585)

@maririos - I have no plans for work on this.

**Comment by jcagme** [comment]
I assume this is "Add ability to queue Arcade builds"? This is already in place and dependencies are flowing

**Comment by dagood** [comment]
It's actually the ability to retry auto-update attempts when something in the infra fails. I saw in the demo today that this is also already complete, unless I'm misremembering the retry URL @alexperovich showed off. 😄
