### ISSUE TITLE
Enable archiving logs in all build definitions

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#163]
@karajas commented on [Thu Nov 09 2017](https://github.com/dotnet/core-eng/issues/2059)

This helps us understand output not printed to console. 

Another workaround is to condition verbosity in official build to be more verbose.

---

@karajas commented on [Thu Nov 09 2017](https://github.com/dotnet/core-eng/issues/2059#issuecomment-343301761)

This is tricky in the case of docker runs.

---

@markwilkie commented on [Thu Mar 22 2018](https://github.com/dotnet/core-eng/issues/2059#issuecomment-375360454)

this is more about diagnosabilty than reliability.  Kicking back out for triage.

---

@Chrisboh commented on [Thu Mar 22 2018](https://github.com/dotnet/core-eng/issues/2059#issuecomment-375443928)

See if this should be an automated part of the build

**Comment by adiaaida** [comment]
Closing because the parent Epic was closed. If you believe this issue should still be worked on, please re-open.
