### ISSUE TITLE
If unspecified, the Arcade Helix Job sender should not use the Storage API for results

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#1639]
We should change the Arcade Helix sender to not provide any Results* properties for jobs unless specifically overridden.  The Job start API is smart enough to automatically store logs in an appropriately selected storage account.

Instead, stuff sent via Arcade today is putting results in https://helixexternaldrops.blob.core.windows.net/ which is clearly meant to be for drops.  Fixing this will make drops and results nicely separated.

**Comment by jonfortescue** [comment]
PR blocked by rollout of https://github.com/dotnet/core-eng/issues/5202.

**Comment by jonfortescue** [comment]
As an update, https://github.com/dotnet/core-eng/issues/5202 is now in rollout, so this should be mergeable after the next rollout.
