### ISSUE TITLE
`darc add` generates dead code

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1643]
## Repro

1. `darc add -n Something -t product -v 1`

## Result

The `eng/Versions.props` file now has this section, which appears to have no use.

```
  <!--Package names-->
  <PropertyGroup>
    <SomethingPackage>Something</SomethingPackage>
  </PropertyGroup>
```

Can we stop adding this to the version.props file?

Darc version: Microsoft.DotNet 1.0.0-beta.18612.12+ffc7a871add67b229c7fd41ad1cdff41da926312

**Comment by jcagme** [comment]
@mmitche, this was added by https://github.com/dotnet/arcade/pull/1186. I kinda remember there was a reason to add the package name group but I don't exactly remember the details. Also, I don't think this is currently in use

**Comment by mmitche** [comment]
@natemcmaster I think there were repos with this form (they had package name elements as well as verison elements) that motivated this change.  I'll remove it.

**Comment by jcagme** [comment]
This is still happening, I can address this when I work on some other `add` improvements.
