### ISSUE TITLE
Can Maestro++ update the .NET Core SDK?

### ISSUE THREAD

**Issue by bricelam** [dotnet/arcade#1647]
Is there a way to flow in the latest version like other depencencies? In other words, get dotnet-maestro to send PRs for these lines in `global.json`:

```json
{
  "tools": {
    "dotnet": "3.0.100-preview-009750"
  },
  "sdk": {
    "version": "3.0.100-preview-009750"
  }
}
```

**Comment by ryanbrandenburg** [comment]
Related to/the same as https://github.com/dotnet/arcade/issues/811?
