### ISSUE TITLE
As a developer, it's easy for me to get all the artifacts that were shipped as part of a .NET Core release.

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#165]
@ellismg commented on [Thu Nov 03 2016](https://github.com/dotnet/core-eng/issues/52)

(Opening this on behalf of @DrewScoggins, who asked me a reasonable question).

Drew wanted to get all of the packages that were part of .NET Core 1.0.1 release to do some testing. It turns out this is harder than expected.  The best way we could come up with was to use the information in dotnet/versions to figure out all the package versions from 1.0.1 (by just poking around the different commits) and then script downloading them from nuget.

It would be ideal if there was some better way of doing this.  Ideally all the nuget packages that made up a release would be published to some well known azure container that anyone could download.  This would mimic the "good old days" when we had something like `\\cpvsbuilds` that just had all the raw binaries.

I think we already have all the packages somewhere on azure today, but it's not discoverable.  Each repo uses a different container and the containers are named after build numbers (which differ across repositories!).

Ideally, in addition to the raw nupks, all the zips and installers would also be available.

---

@markwilkie commented on [Wed Nov 09 2016](https://github.com/dotnet/core-eng/issues/52#issuecomment-259467426)

[User Story 694413: As a product owner, I can use automation to find the artifacts I need to deploy](url)

---

@markwilkie commented on [Mon Mar 20 2017](https://github.com/dotnet/core-eng/issues/52#issuecomment-287812541)

Related to #429

---

@markwilkie commented on [Thu Mar 22 2018](https://github.com/dotnet/core-eng/issues/52#issuecomment-375342634)

Moved to prodcon v2 epic

**Comment by markwilkie** [comment]
This is now handled as part of #73
