### ISSUE TITLE
Add support for pinned dependencies

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#1656]
@natemcmaster mentioned it is common for aspnet to pin versions. In the current design this could be achieved by keep dependency versions in `Versions.props` with no entry in `Version.Details.xml`. While this would work we still need the dependencies declared in `Version.Details.xml` so we can build the dependency graph, this is also needed by source build.

We could introduce a new "pinned" attribute in `Version.Details.xml` so we know that the dependency is not to be updated but still the repo declares that it depends on it.

```xml
<Dependency Name="Microsoft.DotNet.Arcade.Sdk" Version="1.0.0-beta.18620.6" Pinned="false">
  <Uri>https://github.com/dotnet/arcade</Uri>
  <Sha>f3336ecb1009ee5c6f68142c0d05a68bc5609a60</Sha>
</Dependency>
```

/cc: @mmitche

**Comment by mmitche** [comment]
Yeah let's do that.

**Comment by jcagme** [comment]
https://github.com/dotnet/arcade-services/pull/108

**Comment by jcagme** [comment]
@natemcmaster FYI that this is complete and we now support pinning. https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#engversiondetailsxml for the new attribute

**Comment by natemcmaster** [comment]
Thanks!
