### ISSUE TITLE
As a dev, I know official/orchestrated dev builds won't try to index symbols, avoiding the extra load on storage space

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#166]
@dagood commented on [Tue Nov 08 2016](https://github.com/dotnet/core-eng/issues/90)

There is no need for dev builds to index its symbols to a symbol server: symbol packages are available, and dev builds are not intended for wide use. Indexing uses up storage space and makes the build take longer, so actively cutting it out of the build for dev builds would help.

This is related to the work to automatically archive symbols: https://github.com/dotnet/core-eng/issues/79. Both involve adding configurable symbol-server-related steps.

/cc @AlfredoMS 

---

Old PipeBuild plan:

> The plan is to implement this by adding a conditional step to the pipeline, so whoever queues the build can indicate it shouldn't index symbols. (This is the same place the build is configured to not push packages to MyGet.) Because VSTS doesn't have conditional steps, this is a little tricky--traditionally symbols are indexed during each build leg, so we need to split out the publishing part into its own build to make it more granular. This also should reduce some build step duplication.

---

@shawnro commented on [Fri Feb 24 2017](https://github.com/dotnet/core-eng/issues/90#issuecomment-282381308)

@dagood Is this work still relevant with the new plan to replace PipeBuild?

---

@dagood commented on [Fri Feb 24 2017](https://github.com/dotnet/core-eng/issues/90#issuecomment-282393448)

The plan isn't relevant anymore, but the goal is. Renamed the story to make it independent of PipeBuild.

---

@markwilkie commented on [Thu Mar 22 2018](https://github.com/dotnet/core-eng/issues/90#issuecomment-375342878)

Probably already being handled by prodcon.  Moving to that epic.

---

@dagood commented on [Thu Mar 22 2018](https://github.com/dotnet/core-eng/issues/90#issuecomment-375346675)

Maybe: it's a cleanup item that will improve build speed and reliability. Maybe it should be split onto repos that own their own builds.

**Comment by markwilkie** [comment]
We should index every build - CI included.  (but not PR)
