### ISSUE TITLE
Automated Maestro/BAR/Darc testing

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1661]
Create a suite of end-to-end automated tests for the Darc/Maestro installation.  These should be more scenario and end-to-end focused (e.g. using the command line tool and REST APIs directly)

**Comment by jcagme** [comment]
Looks like these tests should be enough validation-wise or you think we should have a validation leg in arcade-validation for these? 

Originally we thought of adding a leg where the darc CLI would be installed and the whole set of commands (with option permutations) would run and we'd just check for errors, if nothing erred then we would call it success without actually checking the outcome. Given that this is similar to what current UTs do we decided to focus on other validation areas.

/cc: @riarenas

**Comment by mmitche** [comment]
This is for the deployed maestro, which would happen on every check-in to INT, so we can just keep these tests in arcade-services.  And yes, they use a combo of the darc CLI and Maestro itself.

**Comment by mmitche** [comment]
I have a few tests now in place, starting with basic azure devops and github dependency flow.  This gives me enough confidence so far that I could start a rollout.
