### ISSUE TITLE
Diamond dependencies and darc

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1677]
Some of our repos have diamond dependencies. Dependency updates via darc attempt to solve this problem by always updating repos to use the latest versions of dependencies on a channel. This is not always the correct solution for how diamond dependencies should be resolved. How can repos describe additional constraints on dependency updates to ensure darc updates are correct?

**Scenario**: AspNetCore, core-setup, and corefx

The aspnet/AspNetCore repo has a dependency on System.Reflection.Metadata (from dotnet/corefx) and Microsoft.NETCore.App (dotnet/core-setup), and dotnet/core-setup has a dependency on System.Reflection.Metadata (corefx). 
```
     ---------> core-setup ---------
     |                             |
     |                             v
 corefx ----------------------> aspnetcore
```

The version of System.Reflection.Metadata used by AspNetCore must be less than or equal to the version that was used in Microsoft.NETCore.App.

**Problem**: let's say the latest packages on the dev channel are corefx 3.0.0.1 and core-setup 3.0.0.1. Corefx produces a new build, 3.0.0.2. If maestro creates an update PR **before** core-setup has re-built using corefx 3.0.0.2, the update to AspNetCore would be invalid:

    Wrong:
    aspnetcore -> Microsoft.NetCore.App 3.0.0.1 -> System.Reflection.Metadata 3.0.0.1
    aspnetcore -> System.Reflection.Metadata  3.0.0.2

    Correct, but not available yet:
    aspnetcore -> Microsoft.NetCore.App (TBD) -> System.Reflection.Metadata 3.0.0.2
    aspnetcore -> System.Reflection.Metadata  3.0.0.2

The update should wait until core-setup has been re-built using corefx 3.0.0.2. 

Fortunately, AspNetCore has PR checks which would fail, so it wouldn't be merged, but how do we prevent this from happening in the first place?

cc @mmitche

**Comment by mmitche** [comment]
I've been thinking about this and don't have a good solution yet.  There are some other interesting details though:
- There's not necessarily a direct dependency chain.  For example, core-setup depends directly on corefx's
  - Microsoft.Private.CoreFx.NETCoreApp
  - Microsoft.NETCore.Platforms

  But nothing else. However, aspnet depends on Microsoft.NetCore.App as well as a host of other corefx binaries.  So in fact, we're really saying that you can't upgrade a particular corefx binary unless the *build* it came from was also pulled into core-setup, specifically that build's Microsoft.Private.CoreFx.NETCoreApp and Microsoft.NETCore.Platforms bits. This means that there are implicit relationships between Microsoft.Private.CoreFx.NETCoreApp and other corefx outputs that aren't actually encoded in the inputs to the core-setup build.
  This feels a bit like a product issue that we're going to have to paper over with the dependency system.
- You could have other cases where binaries produced in a build are in fact truly independent, so you can't just blanket make a rule where all binaries in a build must move as a unit.

Maybe the what needs to be done is that we make core-setup's inputs reflective of the actual dependency structure, then add a way to specify in the version.details.xml that a group of binaries must have familial relationships.

I'll need to think on it some more.

**Comment by pakrym** [comment]
This is causing a lot of pain in AspNetCore repo. We were not able to take an automatic update in 2 weeks and I don't see this changing any time soon without us taking some action on this issue.

Is there any short term fix that we can do here?

**Comment by jcagme** [comment]
Are you hitting the scenario that @natemcmaster describes? One work around I can think of is pinning those dependencies that are not correctly updated and manually updating them. Problem with this, well, is manual and you'll need to know the version you want to take in and create a new PR with the changes.

I don't know the current state of this work to know what is left and then give you a better ETA.

**Comment by natemcmaster** [comment]
Yes, is the same problem. We've almost never had an automatic update into aspnet/AspNetCore work the first time. I've had to manually run darc commands to update versions to workaround this problem.

**Comment by jcagme** [comment]
So, you'll get a PR created that then you update by running darc commands?

**Comment by natemcmaster** [comment]
No, I use darc commands to make changes locally and then create a PR manually.

**Comment by jcagme** [comment]
Interesting. And you have all subscriptions in place so PR are created automatically?

**Comment by natemcmaster** [comment]
Yes. The bot is generating pull requests, but the contents of the PR are incorrect and always fail PR checks.

**Comment by markwilkie** [comment]
@mmitche has been doing a lot of thinking about this, but I'm not sure where he landed (if anywhere)

**Comment by jcagme** [comment]
I **think** he solved this for darc's gather-drop command. If this is actually the case a similar approach can be applied here.

**Comment by mmitche** [comment]
Sorry was oof today.  I'm about halfway through, mostly with the prep work, but got sidetracked by a blog post the last couple days.  I hope to have this starting to roll out early next week.

**Comment by mmitche** [comment]
Update on this.  Local darc support is in PR.  Testing to come.

**Comment by mmitche** [comment]
ParentCoherentDependency is rolled out and working.  i'm going to close this in favor of a common child dependency work item, if and when it is necessary.
