### ISSUE TITLE
Maestro ought to set a tag in the 'source' repo when it commits a PR in a 'target' repo

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#168]
@danmosemsft commented on [Fri Feb 23 2018](https://github.com/dotnet/core-eng/issues/2748)

It would be handy if Maestro set tags for the version of a branch that most recently got ingested.

For example when Maestro commits an update of CoreFX to CoreCLR, it could move forward a tag in CoreFX named like "coreclr".

That would let devs
* Pick it from the dropdown on the homepage of each repo, or

* Locally `git checkout tags/coreclr` in corefx to get the exact state of code that CoreCLR has ingested

Both would be handy.

**Comment by weshaggard** [comment]
I don't think this is really an issue with prodconv2 as we are going to be having the sha of all the dependencies checked into the repos so folks can track down the correct sources if they need to.

**Comment by markwilkie** [comment]
As @weshaggard pointed out, V2 makes this no longer relevant.
