### ISSUE TITLE
MC: Hovering over repository nodes in prodcon builds makes UI jump around

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#169]
@mmitche commented on [Tue Mar 20 2018](https://github.com/dotnet/core-eng/issues/2942)

In Chrome

1. Go to prodcon UI
2. Scroll to bottom of page
3. Hover over box in Orchestrator/CoreCLR, etc.
4. UI jumps up, then back down, then up, then back down...etc.

---

@dagood commented on [Thu Mar 22 2018](https://github.com/dotnet/core-eng/issues/2942#issuecomment-375029805)

(Edit: After discussing in triage I see that what I'm describing is actually a different issue: general DPI problem, not the scoll issue.)

The hovers in the prodcon pages seem to respond poorly to scaling in general. @dleeapho had this same behavior earlier, and on my main monitor, the popup just comes up somewhere else on the page. Works fine on my 1:1 DPI scaling monitor at 100% browser zoom, but anything else has displacement (which sometimes makes it flicker).

---

@alexperovich commented on [Wed Mar 21 2018](https://github.com/dotnet/core-eng/issues/2942#issuecomment-375043370)

Are you in chrome? From my testing it looks like Chrome has issues with high DPI monitors and our display structure. If you put chrome on a regular monitor it will work. Alternatively you can modify the compatibility settings of the chrome shortcut. Enable the "Override high DPI scaling behavior" option and select "System" to perform the scaling.

---

@dagood commented on [Wed Mar 21 2018](https://github.com/dotnet/core-eng/issues/2942#issuecomment-375047746)

Yep, Chrome-based browser. I saw the same ("Works fine on my 1:1 DPI scaling monitor at 100% browser zoom"). Edge works fine.

**Comment by JohnTortugo** [comment]
Closing as we don't rely on MC anymore.
