### ISSUE TITLE
.NET Core Product Construction 2.0 Plan

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#170]
@mmitche commented on [Fri Mar 23 2018](https://github.com/dotnet/core-eng/issues/3001)

---

@mmitche commented on [Fri Mar 23 2018](https://github.com/dotnet/core-eng/issues/3001#issuecomment-375746603)

There is a design for product construction 2.0

---

@mmitche commented on [Wed Apr 04 2018](https://github.com/dotnet/core-eng/issues/3001#issuecomment-378652688)

Sections completed in draft:
- Dependency Flow Tooling
- Dependency Description Format
- Repository API

---

@mmitche commented on [Mon Apr 16 2018](https://github.com/dotnet/core-eng/issues/3001#issuecomment-381649996)

Versioning: https://github.com/dotnet/arcade/pull/108
Dependency Description: https://github.com/dotnet/arcade/pull/120

**Comment by mmitche** [comment]
Last item is channels/subscriptions/branch management spec

**Comment by shawnro** [comment]
If we have a breakdown of all the individual items that make this up, that we're working on, can this be closed and we just use those?  Been a long time in the Dev pipeline.

**Comment by mmitche** [comment]
Final item is in PR here.
