### ISSUE TITLE
Arcade-validation builds are sometimes failing due to incorrect version of Arcade sdk being restored.

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#1705]
Shows up as: 
`F:\vsagent\-containerSas\154\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-dev.18424.13\tools\Build.proj(63,5): error : Property 'Projects' must be specified`

**Comment by markwilkie** [comment]
@riarenas - am I remembering correctly that this has been resolved?

**Comment by riarenas** [comment]
Nope, this is still ongoing. I have a fix I want to try since the Nuget folks haven't been able to see what's going on.

**Comment by riarenas** [comment]
I'm having trouble reproing this since the latest machine rotation. It might have been some bad state in those machines. I'll close it for now and revisit if I start seeing it again.
