### ISSUE TITLE
[Darc] Add support for a full Prodcon build with a CHK runtime

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#171]
@Chrisboh commented on [Wed Mar 28 2018](https://github.com/dotnet/core-eng/issues/3062)

CoreCLR would like to be able to produce a full prodcon build that has just the runtime built as chk.  This way as the full stack does their testing they will get better test coverage.

---

@Chrisboh commented on [Thu Apr 12 2018](https://github.com/dotnet/core-eng/issues/3062#issuecomment-380938647)

@chrisboh

---

@maririos commented on [Tue May 15 2018](https://github.com/dotnet/core-eng/issues/3062#issuecomment-389317953)

@Chrisboh What was it that we needed from you for this issue? why it ended up in ProdCon?

**Comment by maririos** [comment]
This might be covered by the Speculative Product Build

**Comment by markwilkie** [comment]
Implement using channels
