### ISSUE TITLE
Arcade Helix Telemetry should pick up Attempt # from environment if available

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#1712]
It seems when helix telemetry is sent from the Arcade SDK , "Attempt 1" is hard coded in.  This means retries become duplicate builds, which are difficult to reason about in the database.  The telemetry supports the number having different values.

It may also be of use to add the property to the "Properties" of the Job events to distinct-ify the different builds.

**Comment by Chrisboh** [comment]
@MattGal how does this problem manifest itself?  I am not sure how this impacts our customer.

**Comment by MattGal** [comment]
it means distinct builds that we're storing information about stomp each other in our queries and data is lost about the build in the process.  This breaks any visualization we might have about the builds as well as impacting our automated triage and analysis of builds.  

Different builds should be distinct; we are doing multiple attempts, that information is available in the environment, and we're reporting every attempt as the first one.
