### ISSUE TITLE
As a developer doing integration testing I can easily access the latest product and test binaries and symbols for dotnet repos

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#172]
@schaabs commented on [Tue Dec 13 2016](https://github.com/dotnet/core-eng/issues/264)

Currently to perform integrated stress testing of corefx and coreclr we rely on a powershell script which pulls down product binaries, test binaries and symbols for both corefx and coreclr created from repo specific builds using drop.exe.  However, currently this scripting is very fragile as it depends on many internal implementation details and limitations such as:
  - specifics of how each repo versions their 'drops'
  - package and branch naming conventions 
  - timing issues between when the dotnet/versions repo is updated and when drops are available
  - inability to identify incomplete builds (for instance builds where the test build failed)

This scenario would be much simpler if we had a unified tool which could identify the latest successful build for a given repo and branch, and download all the artifacts from that build.  To be used for our scenario the tool would need to be able to get the following artifacts:

  - both chk and ret packages for the given build
  - symbols for chk and ret packages (as packages or just as a drop)
  - test zips for the given build

---

@markwilkie commented on [Tue Dec 13 2016](https://github.com/dotnet/core-eng/issues/264#issuecomment-266894849)

Thanks @schaabs.  Can you confirm (or not) that #162 addresses this?  Lorenzo and I just talked and agree this is a priority and want to get on it sooner than later.

---

@schaabs commented on [Tue Dec 13 2016](https://github.com/dotnet/core-eng/issues/264#issuecomment-266895680)

@markwilkie #162 seems like it could eliminate the need for also download the symbols, however we would still need the ability to download the chk and ret product packages and the test packages.

---

@markwilkie commented on [Tue Dec 13 2016](https://github.com/dotnet/core-eng/issues/264#issuecomment-266897909)

@schaabs good point.  So the "resolver" client mentioned in #162 should download the product as well.  Do you view this as an optional feature where you would specific ret or chk if wanted?

---

@schaabs commented on [Tue Dec 13 2016](https://github.com/dotnet/core-eng/issues/264#issuecomment-266900922)

@markwilkie it's possible we could reuse this tooling for acquiring the product bits.  However, I see a couple of possible issues with this approach: 

1. We still need a way to determine the version of the latest full build.  The workflow is different from the debugging scenario where you are starting from a dump which already references a specific product version. In our case we're trying to build tests against the latest product version which currently we have to determine through a bunch of hokey version string magic.
2. We also need a way to get the test drops for this build. I'm not sure you'd want to complicate the symbol resolver with this. 

---

@markwilkie commented on [Tue Dec 13 2016](https://github.com/dotnet/core-eng/issues/264#issuecomment-266901134)

@schaabs - makes sense.  Do you have any recommends or approaches you'd like to see?

---

@dagood commented on [Tue Dec 13 2016](https://github.com/dotnet/core-eng/issues/264#issuecomment-266941809)

> We still need a way to determine the version of the latest full build.

We could do this by adding a pipeline that depends on every other pipeline, then have that new pipeline update a "all done for version X" file in the versions repository. ("Pipeline" here as in `Publish Packages to Feeds - Release`, `Publish Packages to Drop - Debug`, and `Publish-Tests-Windows-Release`.)

I think continuing to use Drops for this and improving and strengthening the Drop conventions is the best way forward. We already expect product owners to fetch Drops to get at their release packages, so I think it makes a lot of sense to standardize conventions to clean up that story. I also already have been using them to transfer packages to the symbol archive infra, and standardization will only improve that.

---

@schaabs commented on [Wed Dec 14 2016](https://github.com/dotnet/core-eng/issues/264#issuecomment-267105564)

@dagood I agree that we should use drops for this.  I was just hoping we could abstract the multiple calls to drops that are needed to determine which builds are available and download the full set of packages (chk, ret, tests, symbols) into one tool or script shared in build tools.  That way other repo's like the dotnet-reliability repo don't have to take dependencies on internal details such as version format, or path specifics.

---

@dagood commented on [Wed Dec 14 2016](https://github.com/dotnet/core-eng/issues/264#issuecomment-267157681)

Good point--even if there is a convention, it shouldn't be baked into random places. I like the idea of sharing that through a buildtools package. I don't know if there's an alternative to using the (I believe internal) Drop application, so implementation will need more investigation.

---

@shawnro commented on [Wed Jan 11 2017](https://github.com/dotnet/core-eng/issues/264#issuecomment-271973519)

Let's figure out a way to get this done within the next couple sprints and set expectations with @schaabs as to when we'll be able to complete this work. @dleeapho please talk with @dagood to come up with a plan

---

@markwilkie commented on [Wed Feb 01 2017](https://github.com/dotnet/core-eng/issues/264#issuecomment-276746131)

@dagood is full for S114 on build from source.  @shawnro and @dleeapho to discuss the right way to get this priority completed.

---

@dleeapho commented on [Thu Feb 23 2017](https://github.com/dotnet/core-eng/issues/264#issuecomment-282137517)

@schaabs At sprint planning someone mentioned that this work may not be needed or is it now lower pri because of a change in stress testing strategy. Is this so?

---

@shawnro commented on [Thu Apr 27 2017](https://github.com/dotnet/core-eng/issues/264#issuecomment-297864763)

@dleeapho do we even know what we're doing with this one anymore?

---

@markwilkie commented on [Fri Apr 28 2017](https://github.com/dotnet/core-eng/issues/264#issuecomment-298023924)

My opinion is that we still need a "normalized" and sustainable mechanism for publishing build artifacts.  While I think we're close (in that these artifacts exists already in various locations), I also suspect there are still holes - meaning, I can't go to a known location and find "everything" related to a build with confidence.

I also know that Davis has done some recent good work with drops and this area in general.  My suspicion is that we're even closer than ever.  Maybe this is just a matter if finishing things off.

Finally - I'd like to lobby for thinking about these types of things as "services" wherever possible.  Instead of direct injection into the pipeline (which tend to be more tightly coupled), I feel it'd be great to have a "service" that take care of publishing.  

---

@markwilkie commented on [Thu Mar 22 2018](https://github.com/dotnet/core-eng/issues/264#issuecomment-375344332)

Pretty sure that prodcon is doing this.  Moving to that epic for verification.

**Comment by jcagme** [comment]
@markwilkie, since the information about produced assets, including location, is stored in the BAR, can we close this or the requirement for this issue is different?

**Comment by markwilkie** [comment]
Between the stabilized builds, publishing package, and BAR+Darc, I think this is covered.
