### ISSUE TITLE
Helix Payloads should be able to be unzipped into a specific folder rather than into the same folder with all the other payloads

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#1720]
Currently all helix payloads are unzipped into the same directory, this can cause collisions. We should allow payloads to specify that they want to be unzipped into a sub directory/path of the base directory to avoid collisions.

**Comment by jonfortescue** [comment]
The PR for the server side changes was merged [here](https://dev.azure.com/mseng/Tools/_git/CoreFX%20Engineering%20Infrastructure/pullrequest/427483?_a=overview).

Sticking this in tracking until that gets rolled out, which is when we can validate and merge the attached PR for the client changes.

**Comment by jonfortescue** [comment]
Test job showing this working: https://mc.int-dot.net/#/user/jonfortescue/pr~2Fjonfortescue/test/2822019.85/workItem/test/wilogs
