### ISSUE TITLE
ApiCompat appears to have a number of issues with partial facades

### ISSUE THREAD

**Issue by tannergooding** [dotnet/arcade#1730]
This is a copy of the relevant details from: https://github.com/dotnet/corefx/issues/34444

I got @ericstj to stop by and take a look and it appears that there were (still are) multiple issues with GenAPI, including:
* The reference assembly was listed as one of the implementations in ApiCompat
* ApiCompat wasn't able to resolve the location of S.P.Corelib
* ApiCompat, when it could resolve S.P.Corelib didn't fail due to the APIs that were removed

@ericstj responded:
> > The reference assembly was listed as one of the implementations in ApiCompat
>
> Reference path was being passed as an implementation candidate.  Even though this is last it seems dangerous since it could mean API compat is potentially diffing the same files.  Looking at https://github.com/dotnet/arcade/blob/3220be53ac764d9ee160b0bc64baa492af219aa7/src/Microsoft.DotNet.ApiCompat/build/Microsoft.DotNet.ApiCompat.targets#L46 this appears to be expected, but a better alternative might be do pass specific files rather than directories.  Probably a feature rather than the actual problem we're hitting here.
>
> Ultimately there is something *fishy* here that's resulting in API compat missing these changes.  We should debug to find out what's going on.  /cc @ViktorHofer @wtgodbe

**Comment by ericstj** [comment]
I'm investigating this right now and will determine what's going on.

**Comment by ericstj** [comment]
I see what's going on.  This is the result of the attribute diffing.  We're seeing an attribute diff (addition) in the implementation.  That difference is being treated as a `DifferenceType` for the entire type (addition), so further differences in the type are skipped.  This was a problem with the return value of the differ.  When a difference rule returns a `DifferenceType` for a particular Diff method, that `DifferenceType` is applied to the entire mapping.  In the case of the attribute differ we are diffing TypeDefinitions so we should never claim the type definition has been added or removed, only changed.
