### ISSUE TITLE
Arcade Validatesdk self build is not restoring the correct versions during the build process

### ISSUE THREAD

**Issue by robertborr** [dotnet/arcade#1737]
@dotnet-mc-bot commented on [Wed Jan 09 2019](https://github.com/dotnet/core-eng/issues/4945)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=69051
  - **Agent:** a0000J0
  - **Error log:** ##[error]PowerShell exited with code '1'....

@jcagme, @markwilkie

---

@robertborr commented on [Wed Jan 09 2019](https://github.com/dotnet/core-eng/issues/4945#issuecomment-452814343)

@alexperovich , @riarenas  - are working on this as I was researching it.

**Comment by riarenas** [comment]
Problem results from caching the toolset during the first build of the process using a global variable. This prevents us from restoring the actual toolset we want to use, and instead rely on the cached version. Clearing up the global variable after the first initial build solves the problem.

**Comment by riarenas** [comment]
Still has issues.

**Comment by riarenas** [comment]
Moving to validate while we have a green official build. Waiting on signing issues to be resolved.

**Comment by riarenas** [comment]
This was resolved via dotnet/arcade#1747
