### ISSUE TITLE
Add mechanism to validate microbuild signing plugin version and deliver a specific version to repos

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#1741]
Seems like something that we should consider enabling via dependency flow (somehow) or some similar mechanism whereby Arcade validates pulls the newest version and validates it before rolling others forward.  Just rolling forward is likely to cause as many problems as locking to a version is going to cause.

@mmitche @markwilkie

_Originally posted by @chcosta in https://github.com/dotnet/arcade/pull/1740#issuecomment-452892153_

**Comment by markwilkie** [comment]
@riarenas - do you think this is now covered elsewhere?

**Comment by riarenas** [comment]
I don't think it is.

The Arcade templates still install the latest version of the MicroBuild plugin, so even if Arcade-validation signing tests succeed, any repo could break at any given time if a bad version of the plugin gets released.

**Comment by markwilkie** [comment]
@riarenas - wouldn't arcade-validation fail as well given that it would be using the same version of the microbuild plug-in?

**Comment by riarenas** [comment]
Arcade-validation will eventually fail, but that will just mean that all signed builds that use the arcade templates will be broken already. 

Since the templates use the latest version, as soon as a bad version of the task gets pushed, it will break the first repo to try a signed build, nothing specific to the validation flow will prevent it from spreading.

**Comment by markwilkie** [comment]
I see - this is about validating the tasks from Microbuild...

**Comment by markwilkie** [comment]
Ok, in thinking about this a bit more, I'm closing this issue w/ the following rationale:
- We're not currently funded/tasked with validating all of our dependencies (e.g. Azure, AzDO, microbuild, etc) 
- There's currently no significant problem to solve
- If this becomes a problem in the future - namely one of our dependencies is unreliable - then that is a business problem of another sort and should be dealt with as such.

I'd like to underscore again that we own our services - which means we also own making sure our dependencies are dependable.
