### ISSUE TITLE
Implement the correct dependency chaining for the Versioning Task

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#176]
This issue originated from conversation here: https://github.com/dotnet/arcade/pull/137#discussion_r188746398

This issue relates to finding an appropriate way for "Arcade-using" repos, and Arcade itself, use the format string generation target [Microsoft.DotNet.Build.Tasks.Versioning](https://github.com/dotnet/arcade/pull/137)

Mentioned options include:

> Projects would use this target as a depend-on of their own Build target.

> Generally I'd recommend that a NuGet package or SDK that does something like this hook up to the build process using BeforeTargets.

> It could also be in the default targets that arcade provides and executes.

> If this package remains independent of the root arcade sdk package then I do believe we need to find an appropriate set of targets to chain this off of so folks only need to add the package reference and nothing else special is needed. 

Also, we need might we need to have Nuget automatically reference the .props and .target files for projects that reference the Versioning package.

**Comment by weshaggard** [comment]
I don't think this one will be solved by darc/maestro. This is talking about how to hook in the versioning targets into the build pipeline.

**Comment by JohnTortugo** [comment]
I think this issue now is solved since we are using the Versioning already presented in the SDK and plugged into `GetAssemblyVersion `?
