### ISSUE TITLE
Partial publish is problamatic

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#1761]
If publish to a feed using sleet fails partially through, it's difficult to publish again.

cc/ @rynowak as he is interested as well.

**Comment by JohnTortugo** [comment]
@markwilkie / @rynowak  do you have more details about this? Is the difficulty due to corruption of the feed index?

**Comment by riarenas** [comment]
Is this still relevant now that we're moving to azure artifacts feeds?

**Comment by JohnTortugo** [comment]
I think this can be closed as it's only relevant when using Sleet. But I don't have full context on the issue.

**Comment by mmitche** [comment]
I think this is okay now. All of the publishing will do comparisons against currently pushed versions and skip if identical.
