### ISSUE TITLE
SymbolUploader - Rename PublishSymbols.targets to the name of build task

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#1764]
@mikem8361 commented on [Mon Dec 17 2018](https://github.com/dotnet/core-eng/issues/4813)

[3:14 PM] Santiago Fernandez Madero

Yeah, so basically when you do restore, it generates a .nuget.g.targets and a .nuget.g.props file that is autoimported, under those files it imports the package props and package targets which should be named after tha package. 

In corefx in order for us to not have to import the props/targets file manually since we do the restore one time and not per project, we import those generated files manually: https://github.com/dotnet/corefx/blob/master/Directory.Build.targets#L149
So that way we wouldn't have to be importing the symbols targets manually wherever we want to use them, since they would be imported by Directory.Build.targets manually
​
[3:15 PM] Santiago Fernandez Madero
It is not critical, I just wanted to bring it up as it may be beneficial as all the arcade packages have been following those conventions

**Comment by garath** [comment]
This issue was moved to Arcade from core-eng to ease organization.

**Comment by tmat** [comment]
I don't understand what the ask is.

**Comment by mikem8361** [comment]
I think the ask is to rename PublishSymbols.targets to name of the build task: Microsoft.SymbolUploader.Build.Task.targets to match some build task convention. 

We may still want to include PublishSymbols.target for backwards compat. It can import the new file.

**Comment by tmat** [comment]
I see, the file in the package? Makes sense.

**Comment by mikem8361** [comment]
Added Microsoft.SymbolUploader.Build.Task.targets to version 1.0.0-beta-64019-04
