### ISSUE TITLE
[darc/maestro++] Document subscription batching

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#1774]
Document procedure to use subscription batching and why such a thing is useful. 

> You can use the swagger REST api to patch the subscriptions to be batchable:
> https://maestro-prod.westus2.cloudapp.azure.com/swagger/ui/index.html#/Subscriptions/Subscriptions_Create
> And then ensure there is a repository merge policy set for the repo/branch combo (since when you batch subscriptions they end up sharing merge policies).
> https://maestro-prod.westus2.cloudapp.azure.com/swagger/ui/index.html#/Repository/Repository_SetMergePolicies
> There will eventually be support for this in darc. but it's lower priority at the moment.

**Comment by riarenas** [comment]
Darc has support for this and it's documented. Closing.
