### ISSUE TITLE
AllowEmptySignList doesn't work with warnings treated as errors

### ISSUE THREAD

**Issue by nguerrera** [dotnet/arcade#1776]
See https://github.com/dotnet/arcade/blob/9104c21492e1c6ed98105dd87388bca8f1f1abaa/src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.proj#L76-L77

Vs. 

https://github.com/dotnet/arcade/blob/1dfb8626e832a99989dd9551bb0382ce93264750/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs#L157-L160

If I set AllowEmptySignList in Signing.props, I still get a warning, and then that gets elevated to an error, eliminating the effect of AllowEmptySignList. Furthermore, the warning does not have a code, so I cannot disable it using `MSBuildWarningsAsMessages`.

**Comment by JohnTortugo** [comment]
I'll fix that. Is that blocking?

**Comment by nguerrera** [comment]
I found a workaround, so no: https://github.com/dotnet/core-sdk/commit/dcc9df88405cda54e4da442185757b3d0773d5c0
