### ISSUE TITLE
BAR API not returning location data

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1790]
The BAR API is not returning location data correctly.  It's valid in the DB but being missed.

**Comment by alexperovich** [comment]
Asset locations are only returned if you ask for a specific asset, or you query assets and specify "loadLocations": true. This is intentional so we don't return tons of data when it isn't required.

**Comment by mmitche** [comment]
Actually, it looks like the actual locations were missed. PR in a second.
