### ISSUE TITLE
Error in AfterSigning.proj doesn't fail the build

### ISSUE THREAD

**Issue by rynowak** [dotnet/arcade#1800]
See the Windows release log at: https://dnceng.visualstudio.com/internal/_build/results?buildId=72573

```
2019-01-15T00:11:41.3289443Z   SignToolTask execution finished.
2019-01-15T00:11:41.4035887Z   Generating manifest for VS component 'Microsoft.VisualStudio.RazorExtension'
2019-01-15T00:11:41.4072305Z F:\vsagent\12\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19057.6\tools\VisualStudio.InsertionManifests.targets(27,5): error : Property VisualStudioDropName must be specified in official build that produces Visual Studio insertion components. [F:\vsagent\12\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19057.6\tools\AfterSigning.proj]
2019-01-15T00:11:41.5202679Z   Performing feed push...
```

We recently ingested the new VSIX insertion changes (yay) and I was really suprised to see that it **didn't break the build**. We don't yet have `VisualStudioDropName` defined.

/cc @tmat

**Comment by markwilkie** [comment]
cc/ @JohnTortugo

**Comment by JohnTortugo** [comment]
@markwilkie - not exactly caused by signing issues. 

I wonder why this might be failing on this specific situation..? I look to implement a workaround if needed/possible.

**Comment by rainersigwald** [comment]
I think this is another instance of https://github.com/Microsoft/msbuild/issues/3345. Why do you think differently, @tmat?

I find the build logic here baffling, though. @JohnTortugo I can help with a workaround but we probably need to pair on it or I'll have to ask ten thousand getting-up-to-speed questions.

**Comment by tmat** [comment]
Yes, it is likely https://github.com/Microsoft/msbuild/issues/3345.

Why is it baffling?

It's pretty straightforward: 
`Build.proj` runs `MSBuild` task on `AfterSigning.proj`, which defines basic targets (Build, Test, Pack, etc.) and imports targets files that chain their targets to those general targets.

**Comment by rainersigwald** [comment]
Several basic questions: Why are multiple targets run on `AfterSigning.proj`? Why are those targets empty? Why is this target hooked _after_ Pack, instead of somewhere else?

**Comment by tmat** [comment]
The empty targets correspond to [build switches](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj#L25-L35) that can be turned on/off. 

`AfterSigning.proj` and `AfterSolutionBuild.proj` define these targets as extension points that the imported targets can hook to.

For example, if the repo wants to execute a custom test runner after solution is built it would define a target in `eng\AfterSolutionBuild.targets` that chains to `Test` target. `AfterSigning.proj` provides similar extension points.

> instead of somewhere else

Where else? What's wrong with chaining the targets after the empty targets (other then msbuild not reporting the errors properly)?

**Comment by markwilkie** [comment]
@rainersigwald - did this get sorted for you?

**Comment by markwilkie** [comment]
@rainersigwald - feel free to reopen is this is still a problem.
