### ISSUE TITLE
PR builds and official "intermingled" on AzDO

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#1810]
It's hard to reason about official builds because the PR build results on AzDO are intermingled.  There needs to be a way to categorize them differently in AzDO

cc/ @chcosta

**Comment by riarenas** [comment]
More of a workaround than anything else, but AzDO allows for branch filters when looking at the build results. Ideally, only official builds should be going to the non-PR branches?

**Comment by mmitche** [comment]
@markwilkie Why would they be intermingled? They happen in two different projects.

**Comment by markwilkie** [comment]
Closing until I hear more complaining....
