### ISSUE TITLE
Set tag or build number in mirror/utility builds to clarify target repo

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#1817]
Looking at the builds that happen in one of the mirroring build defs like https://dnceng.visualstudio.com/internal/_build?definitionId=240&_a=summary isn't very useful, since it always uses Arcade `master`. Even when looking at a particular build failure, you have to inspect the build logs or queue-time variables to see which repo it was for.

I suggest putting repo and branch in the build number (visible on build list) and/or tag (unfortunately only visible in the one-build view, AFAIK) using these [log commands](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md):

```
##vso[build.updatebuildnumber]build number
##vso[build.addbuildtag]build tag
```

**Comment by markwilkie** [comment]
We're thinking that perhaps we should set things up so that each repo has their own mirroring build.  Moving to the Arcade SDK epic...

**Comment by dagood** [comment]
Why is that?

Also, why is it considered part of the Arcade SDK (judging by the epic name)? AFAIK this is (and must be) separate from the SDK, because these utils serve servicing branches.

**Comment by markwilkie** [comment]
Yea, I meant to add it to https://github.com/dotnet/arcade/issues/2107

**Comment by mmitche** [comment]
Would be superceded by #3650

**Comment by dagood** [comment]
I implemented this with https://github.com/dotnet/arcade/pull/4664.

![image](https://user-images.githubusercontent.com/12819531/72927285-87348980-3d1b-11ea-8ab0-67a5450a6b87.png)

**Comment by dagood** [comment]
Looks like it doesn't pick up the commit hash being mirrored correctly. That's not very important to me, leaving it be.
