### ISSUE TITLE
Define and use more granular IsShipping properties

### ISSUE THREAD

**Issue by tmat** [dotnet/arcade#1820]
Specialize IsShipping for various artifact kinds:
-	Property IsShipping can be set by the project meaning all assets produced by the project are shipping unless specified otherwise.
-	Property IsShippingAssembly is inferred from IsShipping unless it’s already set by the project.
-	Property IsShippingPackage is inferred from IsShipping unless it’s already set by the project.
-	Property IsShippingVsix is inferred from IsShipping unless it’s already set by the project.

Targets do not directly use IsShipping, they use IsShippingAssembly, IsShippingPackage and IsShippingVsix depending on the asset they are dealing with.

**Comment by tmat** [comment]
On second thought `IsShippingContainer` is not good enough. One project can produce both NuGet and VSIX packages, so having just one property would mean these need to either both be shipping or be both non-shipping.

Discussed this more with @natemcmaster offline. We agreed that both `IsShipping` and `IsProduct` may be confusing in some way (e.g. is OOB package a product?) and that the best name would probably be `IsShippable`. That said, even that name might not be clear to everyone. I think there isn't a short name that is completely unambiguous and although naming things well is desirable it is even more important that there be a specification that clarifies details. 

In any case, I don't think renaming `IsShipping` to `IsProduct` or `IsShippable` is worth the effort at this point. We are not at a point anymore where these renames are cheap.

**Comment by natemcmaster** [comment]
Agreed. No great solutions for naming ambiguity, and making a breaking change is a less-good solution so let's keep as is and add these more granular toggles.

**Comment by tmat** [comment]
Implemented by #1900

**Comment by markwilkie** [comment]
@tmat - did this end up getting documented yet?  Given the confusion in the runnup to p2, seems like a good thing to make sure is done.

**Comment by tmat** [comment]
Updated doc: https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#isshipping-isshippingassembly-isshippingpackage-isshippingvsix-bool
