### ISSUE TITLE
Branch not deleted after the PR is merged

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/arcade#1825]
The automated darc updates creates branches on the repo but when the PR gets merged the branch is still left. Those need to be automatically deleted when they are no longer needed.

![image](https://user-images.githubusercontent.com/1579269/51341212-a41de900-1a45-11e9-8696-edca6b106099.png)

**Comment by alexperovich** [comment]
These branches should be deleted when Maestro++ merges the PRs. If they are not that is a bug. Did these PRs get merged manually or automatically?

**Comment by ajaybhargavb** [comment]
They were merged automatically. I see a lot of these branches in both https://github.com/aspnet/AspNetCore and https://github.com/aspnet/AspNetCore-Tooling but I don't a corresponding open PR

**Comment by markwilkie** [comment]
@alexperovich - should this issue be closed in favor of #1826?

**Comment by jcagme** [comment]
These two were fixed by https://github.com/dotnet/arcade-services/pull/101
