### ISSUE TITLE
SignTool fails to update .nupkg because .nupkg is used by another process 

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1839]
After updating aspnetcore signtool from 1.0.0-beta.18614.1 to 1.0.0-beta.19057.6, we started getting consistent build failures with this error:

```
CodeSign.targets(51,5): error : Updating 'C:\b\w\e37dd45d8cd1eaf4\artifacts\\packages\Release\Shipping\Microsoft.AspNetCore.App.3.0.0-preview-19068-0407.nupkg' with signed content failed: 'The process cannot access the file 'C:\b\w\e37dd45d8cd1eaf4\artifacts\\packages\Release\Shipping\Microsoft.AspNetCore.App.3.0.0-preview-19068-0407.nupkg' because it is being used by another process.'
```

I've reverted back to signtool 1.0.0-beta.18614.1 to workaround this, but this is currently blocking us from update to the latest version.

**Comment by JohnTortugo** [comment]
I'll take a look on it.

**Comment by natemcmaster** [comment]
Here are two:

* http://aspnetci/viewLog.html?buildId=615447&tab=buildResultsDiv&buildTypeId=UniverseCoherence
* http://aspnetci/viewLog.html?buildId=615440&tab=buildResultsDiv&buildTypeId=UniverseCoherence

**Comment by natemcmaster** [comment]
Ok, this must be a coincidence, not causation. I tried reverting to 1.0.0-beta.18614.1  and got the same build error. http://aspnetci/viewLog.html?buildId=615485&tab=buildResultsDiv&buildTypeId=UniverseCoherence

Here is the commit when this started happening. This changed the names of folders we put .nupkg files into and renamed some MSBuild variables, but nothing that I think would lead to locked .nupkg files. https://github.com/aspnet/AspNetCore/commit/922512a9fb5ca16c73b75c16c946d6ec92dd81f9. SignTool doesn't care about the folder naming containing the .nupkg file, does it?

**Comment by JohnTortugo** [comment]
SignTool doesn't depend on paths, but I've seen MicroBuild plugin crash like this under certain scenarios. I'm trying to find out exactly which scenario/configuration might be causing this.

**Comment by natemcmaster** [comment]
It must be something our build which is causing strange race conditions. Still investigating on my end. I'll re-open if I determine conclusively that we need a change to signtool.

**Comment by JohnTortugo** [comment]
Thanks @natemcmaster . Let me know if there is anything I can help. I'll ping you if I've more info about what might have happened.

**Comment by natemcmaster** [comment]
Not sure why, it appears to that having double backslashes in the file path causes this problem. As a part of https://github.com/aspnet/AspNetCore/commit/922512a9fb5ca16c73b75c16c946d6ec92dd81f9, I made a mistake and had this in my code.

```
<ArtifactsShippingPackagesDir>$(ArtifactsDir)\packages\$(Configuration)\Shipping\</ArtifactsShippingPackagesDir>
```
ArtifactsDir always has a trailing backslash, so the path value SignTool gets has `artifacts\\packages\` in it.
It appears normalizing the file path to a single slash solved the problem.

https://github.com/aspnet/AspNetCore/commit/dea1950bdc00c435f7992fda03437e5614eb09d1#diff-91eef0a9c69d2f293d8e0ec326d0cded
