### ISSUE TITLE
Port GenFacades.exe from buildtools to Arcade

### ISSUE THREAD

**Issue by joperezr** [dotnet/arcade#185]
We need to port GenFacades.exe over from buildtools in order to onboard Arcade on corefx. [GenFacades](https://github.com/dotnet/buildtools/tree/master/src/GenFacades) is heavily used today in corefx in order to generate typeforward assemblies. It is worth noting that GenFacades use CCI and specifically [CCI Extensions](https://github.com/dotnet/buildtools/tree/master/src/Microsoft.Cci.Extensions) which also lives in buildtools so that will have to get ported as well.

There are three targets files related to GenFacades, we will most likely only need to port the task one instead of the exe one, but here are the three:
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.targets
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.task.targets
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.exe.targets

**Comment by tmat** [comment]
Is anyone working on rewriting GenFacades to generate C# code that gets passed to CSC, instead of using CCI?

**Comment by joperezr** [comment]
I don't think that is absolutely required as part of this, but that would be great if it is not to hard to do, that way we could stop requiring CCI Extensions and our PDB story for portable would be easier.

**Comment by weshaggard** [comment]
>Is anyone working on rewriting GenFacades to generate C# code that gets passed to CSC, instead of using CCI?

That is definitely something I'd like to do because I want to remove this rewriter but it isn't clear when we will tackle it yet.

**Comment by wtgodbe** [comment]
The general plan is as follows:

1. Port the following files:

- https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/GenFacadesTask.cs
- https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.targets
- https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.task.targets
- https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.exe.targets
- Contents of https://github.com/dotnet/buildtools/tree/master/src/GenFacades

2. Port https://github.com/dotnet/buildtools/tree/master/src/Microsoft.Cci.Extensions

3. Convert all .csproj files to SDK-style projects

4. Fold all project.json files into the existing .csproj files

5. Create pkgproj for GenFacades.Core, which depends on the .exe, the task, and Microsoft.Cci.Extensions (note - should this be done with ProjectReferences, as in https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/Microsoft.DotNet.Helix.Sdk.csproj#L25?)

Note that we should move to netcoreapp2.0 (https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/GenFacades.runtimeconfig.json)

@weshaggard does this sound like a reasonable plan?

**Comment by weshaggard** [comment]
I think that is a fair summary except for step (5) we shouldn't need to use a pkgproj. It should just be using the normal dotnet SDK "pack" command, and we should use the GenFacades.Task project for it instead of GenFacades.Core. 

Also I figured out that we can add ExcludeFromSourceBuild=true property to the projects to have them opt-out of source-build. 

>Note that we should move to netcoreapp2.0 

Yes I think targeting netcoreapp2.0 and net461 for these projects is fine. We may want to target netstandard2.0 for the libraries.

**Comment by wtgodbe** [comment]
Makes sense, thanks @weshaggard. One more clarification - are ProjectReferences (https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/Microsoft.DotNet.Helix.Sdk.csproj#L25) the correct way to express the dependencies on Microsoft.Cci.Extensions, etc?
