### ISSUE TITLE
Port xunit.console.netcore.exe to Arcade

### ISSUE THREAD

**Issue by joperezr** [dotnet/arcade#187]
Another piece that needs to be ported to Arcade in order to be able to onboard it with corefx is xunit.console.netcore.exe. That is the tool we use to run all of our .NET Core tests and UAPAOT tests on corefx repo. Here are the targets that need to be ported along with it: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets

**Comment by alexperovich** [comment]
Do we even need a custom build of xunit.console now? If we still do we should look into getting whatever changes we need merged into xunit so we don't need to maintain a custom copy.

**Comment by joperezr** [comment]
I think that we can definitely remove some chunks of our runner, but we would still want to keep a wrapper above it that has some additional parameters and functions specific to our repos. That analysis should be done as part of fixing this issue.

**Comment by joperezr** [comment]
It is worth noting that as part of this, [xunit.netcore.extensions](https://github.com/dotnet/buildtools/tree/master/src/xunit.netcore.extensions) will have to be ported as well.

**Comment by jaredpar** [comment]
@joperezr have you all looked at moving to the coreclr xunit runner? Roslyn used to depend on this package as well but it was pretty easy to migrate over to the new runner. Only mention because it's one place where it may be easier to migrate vs. putting the deprecated piece on arcade.

**Comment by joperezr** [comment]
I believe that is what @alexperovich was suggesting. Part of the work covered by this issue will be to see if we can use our xunit extensions over the xunit that comes with the CLI so that we could deprecate the runner and just mantain the custom extensions.

**Comment by ViktorHofer** [comment]
Closing as we now use the official runner.
