### ISSUE TITLE
Strong Name signing C++/CLI assemblies

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/arcade#1870]
I'm trying to puzzle out how to enable strong-name signing in C++/CLI projects. 

The tentative approach I'm using looks like this (assume that `ManagedCxx` is defined appropriately):

```
<ItemDefinitionGroup>
  <Link>
        <AdditionalOptions Condition="'$(ManagedCxx)'=='true'">%(AdditionalOptions) /keyfile:$(AssemblyOriginatorKeyFile) /delaysign</AdditionalOptions>
  <Link>
</ItemDefinitionGroup>
```

- Is this a reasonable approach? 
- Can I depend on `AssemblyOriginatorKeyFile` property to exist and remain supported in the future as the way to discover the path to the key file? 

This all assumes, of course, that signtool will eventually re-sign these same binaries again after it has been packaged. 

cc @stevenbrix, @miguep, @rladuca, @danzil

**Comment by markwilkie** [comment]
@JohnTortugo

**Comment by markwilkie** [comment]
@JohnTortugo - has this been sorted already?

**Comment by JohnTortugo** [comment]
Sorry, this issue slipped through. 

I'm not aware of any plan to discontinue `AssemblyOriginatorKeyFile`, so I think your approach in general seems reasonable. 

Which strong name key are you going to use? Is it available in ESRP? What form of packaging are you going to use?

@tmat might have more info about this as well.

**Comment by vatsan-madhavan** [comment]
We are going to set StrongNameKeyId=ECMA per this [recommendation](https://github.com/dotnet/wpf/issues/208#issuecomment-459795224), and assume that `AssemblyOriginatorKeyFile`  will resolve to the right file. 

As to packaging, the C++/CLI files get gathered up and packaged by a separate `.csproj` using a custom-generated `.nuspec`. This package generation step is largely left compatible with Arcade SDK's semantics, so the eventual signing of the nuget packages should, I think, re-sign these assemblies very much like they would do for typical C# assemblies.

**Comment by tmat** [comment]
Msbuild common targets translate `AssemblyOriginatorKeyFile` to `KeyOriginatorFile` property here:
https://github.com/Microsoft/msbuild/blob/3a844ce00a873d8ca6ba0a8abc0c6b64f772d937/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3219

The C# build task then consumes `KeyOriginatorFile`.

**Comment by markwilkie** [comment]
@vatsan-madhavan - is this resolved for you?

**Comment by vatsan-madhavan** [comment]
Thanks for the hints - the info is helpful. This can be resolved now.

**Comment by JohnTortugo** [comment]
Thanks @vatsan-madhavan
