### ISSUE TITLE
SignTool fails to read public key token from crossgen-ed assemblies

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1876]
I'm trying to convert aspnet to use the Arcade SDK, and running into a problem with SignTool **1.0.0-beta.19073.4**. It appears SignTool task fails to read the public key token from a crossgen-ed .dll, so I can't use the 'StrongNameInfo' item.

**Inputs**
   * StrongNameInfo: (PublicKeyToken <-> Cert mapping)
   * ItemsToSign: a list of crossgened .dlls

**Result:**

Microsoft.AspNetCore.Antiforgery.dll should match this StrongNameInfo item (pkt = adb9793829ddae60), but it doesn't.

![image](https://user-images.githubusercontent.com/2696087/51700054-10a76380-1fc3-11e9-9574-4ef0b5778526.png)

![image](https://user-images.githubusercontent.com/2696087/51700095-274dba80-1fc3-11e9-9189-60cb28e8ceeb.png)

```
Could not determine certificate name for signable file(s): [C:\Users\namc\.dotnet\buildtools\korebuild\3.0.0-build-20190123.3\KoreBuild.proj]
File: C:\src\aspnet\AspNetCore\obj\ContainerSigning\14\content/shared/Microsoft.AspNetCore.App/3.0.0-preview-t000/Microsoft.AspNetCore.Antiforgery.dll 
error MSB4018: The "Microsoft.DotNet.SignTool.SignToolTask" task failed unexpectedly.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

Server stack trace: 
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.DotNet.SignTool.Configuration.GenerateListOfFiles()
   at Microsoft.DotNet.SignTool.SignToolTask.ExecuteImpl()
   at Microsoft.DotNet.SignTool.SignToolTask.Execute())
```

**To reproduce**
Try running this file (a crossgened .dll): [Microsoft.AspNetCore.Antiforgery.dll.zip](https://github.com/dotnet/arcade/files/2793088/Microsoft.AspNetCore.Antiforgery.dll.zip)

Set StrongNameInfo to:
```xml
<StrongNameInfo Include="AspNetCore" PublicKeyToken="adb9793829ddae60" CertificateName="Microsoft400" />
```

cc @JohnTortugo

**Comment by riarenas** [comment]
@natemcmaster Are you blocked by this for P2?

**Comment by natemcmaster** [comment]
No, not blocked. I have a workaround.

**Comment by riarenas** [comment]
Perfect. Thanks.

**Comment by vijayrkn** [comment]
@natemcmaster - what was the workaround (https://github.com/dotnet/arcade/issues/1876#issuecomment-457386148)?

I am running into the same issue in Scaffolding 

> E:\git\scaffolding\.dotnet\buildtools\korebuild\3.0.0-build-20190226.1\modules\KoreBuild.Tasks\CodeSign.targets(29,5): error : Could not determine certificate name for signable file(s): [E:\git\scaffolding\.dotnet\buildtools\korebuild\3.0.0-build-20190226.1\KoreBuild.proj]
> E:\git\scaffolding\.dotnet\buildtools\korebuild\3.0.0-build-20190226.1\modules\KoreBuild.Tasks\CodeSign.targets(29,5): error :     File: E:\git\scaffolding\obj\ContainerSigning\8\tools/netcoreapp3.0/any/dotnet-aspnet-codegenerator.dll [E:\git\scaffolding\.dotnet\buildtools\korebuild\3.0.0-build-20190226.1\KoreBuild.proj]
> E:\git\scaffolding\.dotnet\buildtools\korebuild\3.0.0-build-20190226.1\modules\KoreBuild.Tasks\CodeSign.targets(29,5): error MSB4018: The "Microsoft.DotNet.SignTool.SignToolTask" task failed unexpectedly. [E:\git\scaffolding\.dotnet\buildtools\korebuild\3.0.0-build-20190226.1\KoreBuild.proj]
> E:\git\scaffolding\.dotnet\buildtools\korebuild\3.0.0-build-20190226.1\modules\KoreBuild.Tasks\CodeSign.targets(29,5): error MSB4018: System.Collections.Generic.KeyNotFoundException: The given key 'Microsoft.DotNet.SignTool.SignedFileContentKey' was not present in the dictionary. [E:\git\scaffolding\.dotnet\buildtools\korebuild\3.0.0-build-20190226.1\KoreBuild.proj]

**Comment by JohnTortugo** [comment]
@vijayrkn can you post a link to the failing build?
