### ISSUE TITLE
Port UAP test runner and launcher from buildtools

### ISSUE THREAD

**Issue by joperezr** [dotnet/arcade#188]
In order to move corefx into Arcade, we will need to port the UAP [runner](https://github.com/dotnet/buildtools/tree/master/src/xunit.runner.uap) and [launcher](https://github.com/dotnet/buildtools/tree/master/src/WindowsStoreAppLauncher) from buildtools. These two things are required when building and testing the UAP vertical.

**Comment by ViktorHofer** [comment]
Done with https://github.com/dotnet/arcade/pull/355.
