### ISSUE TITLE
SourceLink does not work for strongly typed resources file (SR.cs)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/arcade#1885]
SourceLink obviously can't link to generated files - and indeed it doesn't.
```
c:\pdb>dotnet install sourcelink
...
c:\pdb>sourcelink test System.Private.CoreLib.pdb
2 Documents with errors:
4f669fa1207b58d3b39ddff04669a5b70d4e3d347d8050812be67735e76b76b0 sha256 csharp /__w/8/s/bin/obj/Linux.x64.Release/System.Private.CoreLib/SR.cs
https://raw.githubusercontent.com/dotnet/coreclr/b9e88989458e24fa9764e045917b141e3338eae7/bin/obj/Linux.x64.Release/System.Private.CoreLib/SR.cs
error: url failed NotFound: Not Found
da711da20befe335e16ebe6ddff69f2ccd87b2627d4f7ef271a234d9dad1faac sha256 csharp /__w/8/s/bin/obj/Linux.x64.Release/eventing/DotNETRuntimeEventSource.cs
https://raw.githubusercontent.com/dotnet/coreclr/b9e88989458e24fa9764e045917b141e3338eae7/bin/obj/Linux.x64.Release/eventing/DotNETRuntimeEventSource.cs
error: url failed NotFound: Not Found
sourcelink test failed

c:\pdb>sourcelink test System.Collections.Specialized.pdb
1 Documents with errors:
48b0076adc624decfc86b8871b5ba2c79c39228f09da4ad293b1a4eb7d7409e3 sha256 csharp /Users/vsts/agent/2.144.2/work/1/s/artifacts/obj/System.Collections.Specialized/netcoreapp-AnyOS-Release/System.SR.cs
https://raw.githubusercontent.com/dotnet/corefx/351ca391579740ae8af8a5405cffa16d152ad6b2/artifacts/obj/System.Collections.Specialized/netcoreapp-AnyOS-Release/System.SR.cs
error: url failed NotFound: Not Found
sourcelink test failed
```
This is fine and inevitable but is forever going to be noise when we validate sourcelink in our PDB's.

Not a big deal but @tmat is there (eg) some flag we should pass to embed into the PDB somehow the knowledge that sourcelink will not work for SR.cs, that would suppress such errors?

**Comment by tmat** [comment]
We should be embedding the generated files into the PDB. I'd start with using `EmbedUntrackedSources` option for this: https://github.com/dotnet/sourcelink/tree/master/docs#embeduntrackedsources. We need to see if it significantly slows down build. Hopefully not, but I haven't measured it in large repos yet. If it does cause a slow down, I'll investigate if it can be sped up. If not we can manually list the files to embed, but I'd rather avoid that.

**Comment by danmosemsft** [comment]
@Anipik this is only a nice to have. The other sourcelink issue in this repo is more important.

**Comment by Anipik** [comment]
sure :)

**Comment by Anipik** [comment]
@tmat Setting this property  ```EmbedUntrackedSources``` to true solves our problem and doesnot slow down significantly.
I was wondering if there is a way to embed untracked files in specific directory ? eg untracked files in only the artifacts folder.
I am just worried that people may be able to use it to add non-generated files as well and we wont be able to detect the sourcelink failure 
 
cc @ericstj

**Comment by danmosemsft** [comment]
@anipik do the PDBs get significantly bigger? I guess we don't care too much about their size (we care a lot about implementation size)

**Comment by tmat** [comment]
`EmbedUntrackedSources` instructs SourceLink to add source files that are passed to the compiler as inputs and that match an entry in `.gitignore`. These files are added to `EmbeddedFiles` item group that is passed to the compiler.

> I am just worried that people may be able to use it to add non-generated files as well and we wont be able to detect the sourcelink failure

I don't understand what do you mean by "may be able to use it to add non-generated files". How do those files end up in the repository?

**Comment by Anipik** [comment]
eg the sourcelink is broken for a random.cs file which is in the repo. 
I use  ```<EmbedFiles Include="Random.cs" />``` to fix the sourcelink for this file. 
I am just wondering if there is a way to restrict me from doing that. Maybe a check on embeded items before passing them to the compiler

**Comment by Anipik** [comment]
talked with @ericstj  offline. Your comment addresses most of his concerns. Thanks I will put up the PR to address it
