### ISSUE TITLE
Cannot opt into C# 8 nullable references in csproj

### ISSUE THREAD

**Issue by roji** [dotnet/arcade#1899]
I'm a bit of a newcomer so I hope I'm posting in the right place with the right details.

While working on introducing C# 8 nullable reference annotations into the Entity Framework Core codebase, it would seem that the `<NullableReferenceTypes>` attribute isn't getting properly picked up from the project's csproj, but only when building with Visual Studio 2019 Preview2. When trying to build, I'm getting warnings of the following type for each null-annotated type:

```
error CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' context.
```

Building the same project from the cmdline succeeds. Building a regular, non-Arcade project from VS also succeeds. Placing `#nullable enable` in the source file also works, so the problem really seems to be with the csproj property.

VS version: 2019 Preview 2
dotnet SDK: 3.0.100-preview-010010

**Comment by benaadams** [comment]
The [reddits say](https://www.reddit.com/r/csharp/comments/al2nib/announcing_net_core_3_preview_2/efafi99/) its changed to `<NullableContextOptions>enable</NullableContextOptions>`

**Comment by roji** [comment]
Thanks @benaadams, that works :) I'm guessing that my EF Core build was on a newer SDK because of arcade, while the standalone project was on an older version with the previous property.
