### ISSUE TITLE
[Feed package] Decouple VersionTools manifest generation from Feed package

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#19]
@chcosta commented on [Tue Feb 20 2018](https://github.com/dotnet/core-eng/issues/2699)

The feed package has a dependency on VersionTools which it consumes to make build manifest generation "easy" / transparent.  The dependency is not strictly necessary and not every consumer of the feed package may care about the build manifest generation.  We should remove the feed task package dependency on VersionTools.

> I think that it'd make sense to have a "prodcon v1 push" task that encapsulates the PushToBlobFeed plus manifest generation, and brings in whatever packages are needed--which would be the Feed and VersionTools packages. -dagood

> I think that, for now, I'm just going to update versiontools package to include the desktop assets and have the feed package consume it as a packagereference during build.  we can pull it apart down the road -chcosta

This is the kind of thing that it's easy to let slide because it's somewhat difficult (may involve quite a few moving pieces and updating how consumption works across many repo's), but I think we should invest in this sooner than later.

/cc @dagood @markwilkie 

FYI @weshaggard @mmitche 

---

@chcosta commented on [Tue Feb 20 2018](https://github.com/dotnet/core-eng/issues/2699#issuecomment-367118329)

Additional info https://github.com/dotnet/buildtools/pull/1836

**Comment by maririos** [comment]
@chcosta  The build manifest is used to know which assets where produced by a build? Information like what was created and from where and with which SHAs?

**Comment by maririos** [comment]
FYI @jcagme

**Comment by maririos** [comment]
After verifying with @mmitche the work here is to delete the logic in the Feed package that creates/uploads/downloads the build manifest to version tools.
That includes changes in files like:
- https://github.com/dotnet/arcade/blob/7e04f1d5eac5dac5df3fa3840c9844a80eb3a6fa/src/Microsoft.DotNet.Build.Tasks.Feed/build/Microsoft.DotNet.Build.Tasks.Feed.targets
- https://github.com/dotnet/arcade/tree/2ff5743b14f2f32a0bda6750b312598686347105/src/Microsoft.DotNet.Build.Tasks.Feed/src/BuildManifest

and similar references

**Comment by jcagme** [comment]
@maririos  I have a PR out which already touches the `Microsoft.DotNet.Build.Tasks.Feed` project. I can also remove these files if you need me to

**Comment by jcagme** [comment]
Changes addressed in https://github.com/dotnet/arcade/pull/489. @maririos PTAL
