### ISSUE TITLE
Cross targeting for netcoreapp3.0 in arcade

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#1907]
I attempted to upgrade the CLI version in corefx to 3.0.0-preview 2 (3.0.100-preview-010184) but failed as we depend on tools compiled against netcoreapp2.1, i.e. ApiCompat, GenAPI, etc. What's the plan for supporting netcoreapp3.0 in arcade / arcade packages?

**Comment by ViktorHofer** [comment]
cc @ericstj

**Comment by ericstj** [comment]
We can make our rubtimeconfig’s permit rollforward on major version: https://github.com/dotnet/core-setup/blob/92072fd9ea03740ea317b631d3894ff3c5d0854d/Documentation/design-docs/roll-forward-on-no-candidate-fx.md

**Comment by ViktorHofer** [comment]
Thanks for the roll forward link, that will be valuable in corefx. As this issue is about adding the ability to compile for netcoreapp3.0 which involves using the 3.0 SDK in general, I will keep it open.

**Comment by markwilkie** [comment]
Moving to post dev16 GA

**Comment by ericstj** [comment]
@markwilkie I think you mentioned that folks are actively working on this plan for next week?

**Comment by ViktorHofer** [comment]
We aren't blocked on this anymore. We added the major version rollforward policy to our tools that we depend on in corefx.

**Comment by markwilkie** [comment]
@riarenas - can you update this when the sdk is flowing please?

**Comment by ViktorHofer** [comment]
Now possible with the 3.0 SDK. Closing.
