### ISSUE TITLE
SignTool: rename StrongNameSignInfo parameter and patch existing users

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#1919]
This originated from Tomas comment here: https://github.com/tmat

The issue is just to rename the StrongNameSignInfo parameter to something more aligned to what it does currently. The purpose of the parameter has changed quite a bit since its introduction in the tool, we need to rename it to reflect that new purpose.

**Comment by markwilkie** [comment]
@JohnTortugo - when you're back, any chance of explaining a bit more the thinking behind this?

**Comment by JohnTortugo** [comment]
@markwilkie I updated the issue's description.

**Comment by Chrisboh** [comment]
Given currently business priorities this isn't an issue we will get to anytime soon.  If anyone feels different please feel free to reopen.
