### ISSUE TITLE
[Darc] Create layout compatible with release-day activities

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#1933]
On release day, nuget package publish for the Runtime (CoreCLR, CoreFX, Core-Setup) and symbol publish for a potentially wider set of repos is handled by these steps:
* [NuGet gallery push](https://devdiv.visualstudio.com/Personal/_git/dagood?path=%2FReleaseTool%2FDocumentation%2Fpush-nuget.md&version=GBmaster)
* [Symbol publish](https://devdiv.visualstudio.com/Personal/_git/dagood?path=%2FReleaseTool%2FDocumentation%2Fpush-symbols.md&version=GBmaster)

I have a custom tool (and a build definition that runs it) that generates the file layout those steps use. It accepts a json file, which specifies ProdCon v1 manifests, file shares, and blob storage locations to pull from. For 1.0/1.1/2.1/2.2 releases so far, I've been writing up the json and feeding it into the tool to create release staging dirs that the above steps use.

For 3.0, Darc should be able to generate a json file that can be fed into the tool. (Darc could lay out the release drop directly itself, but generating the json is trivial, avoids duplicating the layout logic, and gets us where we need to be.)

This should be trivial, just tracking the work. /cc @mmitche

**Comment by dagood** [comment]
For example, preview4 could have been handled by this if gather-drop were working and everything were categorized correctly:

```json
[
  {
    "release": "3.0.0-preview4",
    "products": [
      {
        "name": "coreclr",
        "fileshare": "\\\\mmitche1\\netcore3.x\\preview4\\coreclr\\20190415.73\\shipping"
      },
      {
        "name": "corefx",
        "fileshare": "\\\\mmitche1\\netcore3.x\\preview4\\corefx\\20190412.13\\shipping"
      },
      {
        "name": "core-setup",
        "fileshare": "\\\\mmitche1\\netcore3.x\\preview4\\core-setup\\20190415.11\\shipping"
      },
      {
        "name": "dotnet-trusted",
        "fileshare": "\\\\mmitche1\\netcore3.x\\preview4\\DotNet-Trusted\\20190413.28\\shipping"
      },
      {
        "name": "aspnetcore",
        "fileshare": "\\\\mmitche1\\netcore3.x\\preview4\\AspNetCore\\20190416.3\\shipping"
      },
      {
        "name": "aspnetcore-tooling",
        "fileshare": "\\\\mmitche1\\netcore3.x\\preview4\\AspNetCore-Tooling\\20190416.2\\shipping"
      },
      {
        "name": "entityframeworkcore",
        "fileshare": "\\\\mmitche1\\netcore3.x\\preview4\\EntityFrameworkCore\\20190416.3\\shipping"
      },
      {
        "name": "extensions",
        "fileshare": "\\\\mmitche1\\netcore3.x\\preview4\\Extensions\\20190416.2\\shipping"
      }
    ]
  }
]
```

(For `preview4`, I did combine the aspnet repos into a single zip. This is *possible* to do in the json by passing multiple shipping dirs to one product with the `fileshares` property, but since you'd have to keep track of which repos are part of the aspnet "product" in Darc to do that, I don't think it's worth it. We have a similar problem with individual coreclr/corefx/core-setup symbol zips but we don't combine those either.)

**Comment by mmitche** [comment]
Fixed by: https://github.com/dotnet/arcade-services/pull/383
