### ISSUE TITLE
Manifest publish fails for svg files

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#1942]
Core-Setup official builds are (still) failing due to:

```
  Starting build metadata push to the Build Asset Registry...
F:\vsagent\4\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19080.6\tools\SdkTasks\PublishBuildAssets.proj(36,5):
  error : Version could not be extracted from 'core-setup/Runtime/3.0.0-preview-27331-3/sharedfx_centos.7-x64_Release_version_badge.svg'
```

https://dev.azure.com/dnceng/internal/_build/results?buildId=84895

https://github.com/dotnet/arcade/issues/1842 added a `ExcludeFromManifest` feature that I tried to use in Core-Setup via https://github.com/dotnet/core-setup/pull/5037. The binlog shows that the metadata is set, but the generated manifest still has the SVGs and publish still fails.

Also in https://github.com/dotnet/arcade/issues/1842:

> As a follow up, the error here was that when the split between arcade and arcade services happened we took an old version of `Micosoft.DotNet.Maestro.Tasks` which had no support for SVGs hence the error you were getting.
> 
> I've ported the correct version of the files so this does not happen again even though we have exclusion support

It doesn't look like this fix took hold. 😕 

@jcagme @chcosta @mmitche any ideas?

**Comment by dagood** [comment]
It looks like Core-Setup uses an old version of the feed push tasks, intentionally: https://github.com/dotnet/core-setup/pull/4934. That would explain `ExcludeFromManifest` not doing anything. I'm not sure what the issue was that's holding back that dependency but I think it's on my plate to figure that out at some point.

I would still expect the Maestro-side fix to work, though....

**Comment by dagood** [comment]
> The root cause of that was that when we took out Maestro pieces our from Arcade we took an old version of the task. This old version did not support SVGs by then. This was fixed by [dotnet/arcade-services#105](https://github.com/dotnet/arcade-services/pull/105).

Why isn't this fix making the Core-Setup official builds work?

**Comment by dagood** [comment]
To make sure I'm asking the right question: my basic assumption is that the root cause being in Maestro++ in dotnet/arcade-services means it's a server-side issue. Is that not true, does the root cause fix actually depend on the version of some client-side thing?

From what I gather, I can *work around* the issue by upgrading the feed publish tasks and using `ExcludeFromManifest`, but I shouldn't need to work around it because the root cause in the service is fixed. Is that not the right train of thought?

**Comment by dagood** [comment]
Ah, thanks for the clarifications.

It sounds like once that gets merged and Core-Setup gets an Arcade SDK update, this will start working.

**Comment by jcagme** [comment]
That's correct. This should be hands-off for you since it looks like dependencies are flowing fine into core-setup. Or if it is high pri you could manually update the Arcade SDK version in global.json

**Comment by dagood** [comment]
It works! Thanks.
