### ISSUE TITLE
Verbosity option not passed through to test runner

### ISSUE THREAD

**Issue by Tratcher** [dotnet/arcade#1948]
We're attempting to debug test hangs in the AspNetCore/Extensions repo. Adding an [xunit.runner.json](https://xunit.github.io/docs/configuring-with-json) file with `"diagnosticMessages": true` gets you test progress reports logged, but only if the verbosity is at least "normal" rather than the default "minimal". We can set this verbosity using `dotnet test -v normal`, but if we pass -v to the full build script it applies to the build only and is not passed through to the test runner. 

cc: @ryanbrandenburg

**Comment by tmat** [comment]
BTW, you can pass additional parameters to XUnit runner via `TestRunnerAdditionalArguments` property.

**Comment by ryanbrandenburg** [comment]
I tried to use that property but it seemed to be interpreting it as an xunit argument instead of an MSBuild argument.

**Comment by tmat** [comment]
Yes, it is XUnit argument - I though you are trying to customize xunit. There is no msbuild involved in running the tests, other than executing `xunit.console.runner.exe` process. Unless this issue is in Helix?

**Comment by tmat** [comment]
If XUnit outputs some detailed diagnostics to its STDOUT then you can find that in a log file in artifacts\log directory.

**Comment by Tratcher** [comment]
Is `dotnet test -v normal` calling `xunit.console.runner.exe`?

**Comment by markwilkie** [comment]
cc/ @alexperovich as he might have some insight as well

**Comment by markwilkie** [comment]
@alexperovich ?

**Comment by alexperovich** [comment]
I don't have any additional information for this. Arcade SDK doesn't use VSTest for running tests locally. If we don't use VSTest then VSTest options will not work. I don't know if xunit.console.exe has equivalent options for this case.

**Comment by tmat** [comment]
I don't think there is anything to do here. The xunit test runner already outputs detailed log.

**Comment by markwilkie** [comment]
Closing based on no comments.  Feel free to open again @Tratcher if need be.
