### ISSUE TITLE
[Darc] Darc should be able to update Arcade's src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/Versions.props

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#1956]
For now we'd need to keep versions defined in `src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/Versions.props` hard coded since Darc does not know how to deal with this file.

**Comment by tmat** [comment]
I don't think Darc should be updating this file. Darc should only be updating `global.json` in repo root or `eng\common`. 

This is more or less duplicate of https://github.com/dotnet/arcade/issues/1599.

**Comment by jcagme** [comment]
This was fixed by https://github.com/dotnet/arcade/pull/1990
