### ISSUE TITLE
SignTool: consider skipping already-signed .jar/.nupkg/.vsix files

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1957]
SignTool has an optimization right now which skips code-signing for already-signed files. It appears this check only works for PE files, though. As a perf optimization, would it be good to also skip code-signed .jar, .nupkg and .vsix files?

Example scenario: AspNetCore has two build steps
```yml
- script: build.cmd -arch x64 -sign
- script: build.cmd -arch x86 -sign
```
The second step is re-submitting the packages from the first step for signing because sign config picks up everything in the artifacts directory, regardless of the `arch` parameter.

Thoughts @tmat @JohnTortugo?

**Comment by natemcmaster** [comment]
FWIW, the workaround is pretty simple so this isn't urgent.

**Comment by JohnTortugo** [comment]
I had chatted with @natemcmaster on Teams. To me it looks like a good idea. @natemcmaster pointed out that we need to be sure that the content of packages are all signed or can be ignored before skipping signing of the container.

**Comment by Chrisboh** [comment]
Closing as this causing us any issues since this was opened.
