### ISSUE TITLE
Define an extension point for internal tools restore

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#1974]
The internal tools restore functionality that was added with https://github.com/dotnet/arcade/commit/daaabd049e724f89edd1892a3692d4832b1a1fe3 should support extending packagereferences and restore sources from the eng directory. In corefx we restore additional tools, i.e. ILC which would benefit from such a functionality.

https://github.com/dotnet/arcade/commit/daaabd049e724f89edd1892a3692d4832b1a1fe3#r32189632

cc @tmat @ericstj

**Comment by ViktorHofer** [comment]
cc @safern

**Comment by ViktorHofer** [comment]
@tmat we would like to get rid of our buildtools dependency eventually by EOW. As we rely on optional tooling for ILC (UWP Release) we are blocked on this right now. Do you have some to add the extensibility point this week or should I give it a shot?

**Comment by tmat** [comment]
@ViktorHofer Give it a shot. Should be simple - just add an import of `/eng/InternalTools.props` if it exists.
Something like:
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj#L55-L56

**Comment by safern** [comment]
Should we also make it the default restore sources and PackageReference to not be included by an optional property?

Like, `IncludeDefaultPackageReferences`? 

```xml
<ItemGroup Condition="'$(IncludeDefaultPackageReferences)' != 'false'">
    <PackageReference Include="Microsoft.DotNet.IBCMerge" Version="$(MicrosoftDotNetIBCMergeVersion)" Condition="'$(UsingToolIbcOptimization)' == 'true'" />
    <PackageReference Include="Drop.App" Version="$(DropAppVersion)" ExcludeAssets="all" Condition="'$(UsingToolVisualStudioIbcTraining)' == 'true'"/>
  </ItemGroup>
```

**Comment by tmat** [comment]
No need for extra property, they are already conditional on `UsingToolIbcOptimization` and `UsingToolVisualStudioIbcTraining`.
