### ISSUE TITLE
Test the new publishing via release pipelines

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#1988]
Helping Cesar out with his final testing of the new async publishing via release pipelines, which is also helping me ramp up for phases 2 and 3 of the same work.

- [x] Be able to publish for a build
- [x] Work on a build without a channel
- [x] Work on a build+channel without pipeline
- [x] Be able to publish for simultaneous builds of the same repository + branch: https://dnceng.visualstudio.com/internal/_build/results?buildId=121133 https://dnceng.visualstudio.com/internal/_build/results?buildId=121134 https://dnceng.visualstudio.com/internal/_build/results?buildId=121135 https://dnceng.visualstudio.com/internal/_build/results?buildId=121136
- [x] Be able to trigger multiple pipelines for same build and channel
- [x] Be able to trigger multiple pipelines for different channels, same build
- [x] Be able to publish for different repos
- [x] Be able to publish when an existing build is associated with a channel

**Comment by riarenas** [comment]
I'll start testing in maestro's int environment now that the PR was merged.

**Comment by markwilkie** [comment]
What's the latest?

**Comment by riarenas** [comment]
FR was busy the last couple of days, so not much progress. I have validated that the release pipelines get triggered and the database updated correctly in int, but still need to keep testing to verify that the publishing aspect of the pipeline we're using works correctly.

I've synced up a bit with @JohnTortugo and he's going to help me out with the validation while I'm still in FR.

**Comment by JohnTortugo** [comment]
I was able to get the first few fully automated publishing (build from arcade build-def, called maestro-int and publish to my azure feed) using the new infra. I added new test cases to the issue's description; once I finish those I'll consider this tested/validated. @riarenas if you have time please let me know if you can think of more test cases.
