### ISSUE TITLE
Product construction post-build failures should report on Mission Control

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#199]
@mmitche commented on [Thu Feb 01 2018](https://github.com/dotnet/core-eng/issues/2563)

Today we have a build mail that goes out when there is a post-build failure in product construction (signing/final publish). Ideally this would  be a mission control item.

This should be relatively straightforward but has some subtlety.  In order to report on Mission Control, we need the product build id.  The product build id is parsed from the final build manifests, so until the assets are downloaded we wouldn't know how to report on mission control.  This also implies that if download fails we wouldn't have any MC visibility at all.  If that's fine, then what we could do is bring back tasks/targets to CloudTestTasks that can do the MC eventhub reporting.  Then we can use these targets in the utility build definitions used for postbuild to report the correct status.

FYI We used to have tasks but removed them here: https://github.com/dotnet/buildtools/pull/959

---

@mmitche commented on [Thu Feb 01 2018](https://github.com/dotnet/core-eng/issues/2563#issuecomment-362435778)

fyi @MattGal 

Is CloudTestTasks the right place for this @MattGal? THese seem like they should go in a more generic package, since they aren't helix test specific.

---

@MattGal commented on [Thu Feb 01 2018](https://github.com/dotnet/core-eng/issues/2563#issuecomment-362452606)

I say put it in CloudTestTasks.  The assembly is small and contains useful cloud-related tasks.  Having an helper method that understands Event Hub JSON events that are very much only used for builds and helix tests makes the most sense to go there.   There's little downside.  JobStarted/JobFinished are events that both test runs and builds use.  Splitting it out later is low effort.  Making people depend on a whole extra package is silly.

**Comment by JohnTortugo** [comment]
I think this can be closed. Agree @markwilkie @mmitche @MattGal  ?

**Comment by MattGal** [comment]
I agree so strongly that I'm closing it.
