### ISSUE TITLE
Make Maestro++ `StartAssociatedReleasePipelinesAsync` method a new service and make it use BackgroundQueue

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#1994]
Currently `StartAssociatedReleasePipelinesAsync` is a method that is called whenever a new BuildChannel entity is inserted into BAR. That method is responsible for triggering release pipelines associated with a channel that the build is linked to.

This issue is to make `StartAssociatedReleasePipelinesAsync` into a new service fabric service that will be activated in a similar way that DependencyUpdate is.

**Comment by riarenas** [comment]
Making progress on this. Service is seems to be standing up correctly in my local service fabric cluster, but now trying to figure out why the service becomes unhealthy after the call to try and trigger the pipeline which was previously working when used while in the API.
