### ISSUE TITLE
Arcade's usage of MSBuildAllProjects contributes significantly to VS memory consumption

### ISSUE THREAD

**Issue by davkean** [dotnet/arcade#1995]
Starting in Dev16, all targets/props files should stop appending to `MSBuildAllProjects`, MSBuild will now automatically make sure that the first element of this property always contains the newest targets file, and hence consumption of it will continue to work.

Across a bunch of repros we've started removing setting of this property to reduce memory pressure, for example: https://github.com/dotnet/sdk/pull/2853.

This repro's targets files is contributing to significant memory usage when opening CoreFx. Using a custom tool we for analyzing dumps for duplicate strings, ~12% of the heap (nearly 400 MB) is made up of the strings caused by the appending of this, large portion of which is Arcade.

![image](https://user-images.githubusercontent.com/1103906/52389295-e8e9ec80-2ae6-11e9-8590-e6b198173aad.png)

**Comment by markwilkie** [comment]
@davkean - what do you think the risk of this being a breaking for some folks is? 

cc/ @jcagme, @tmat

**Comment by davkean** [comment]
If you look at how https://github.com/dotnet/sdk/pull/2853 was made with a specific path for Dev15, low. Even if you regressed this in Dev15 (by not following that PR), the worst that would happen is that these in-place changes to these files would be ignored. Given these ship as NuGet packages, the likelyhood of that happening is low because NuGet packages are immutable.

**Comment by drewnoakes** [comment]
https://github.com/dotnet/sdk/pull/2853/commits/19cfae4eb3717ad997d28c750b13b0525129f04e initially had the guard that prevented breaking 15, but it was decided unnecessary and the entire property element removed in subsequent commit https://github.com/dotnet/sdk/pull/2853/commits/49002c14cf91ecd08e79d6184dbd4716c005b509.

**Comment by drewnoakes** [comment]
This analysis was performed using [StringTheory](https://github.com/drewnoakes/string-theory) which was just open sourced.

**Comment by tmat** [comment]
Let's remove these.

**Comment by davkean** [comment]
That guard was removed because the SDK doesn't run on Dev15, but I'm assuming Arcade does.

**Comment by tmat** [comment]
@davkean So should this be conditional for packages that are expected to work on bot Dev15 and Dev16 or not? 

> the worst that would happen is that these in-place changes to these files would not cause us to consider the project to be out of date

If this is the only issue on Dev15 that I think we are fine without the guard.

**Comment by tmat** [comment]
@davkean Ping

**Comment by davkean** [comment]
The condition is there if you want to continue to support Dev15.

**Comment by tmat** [comment]
What does it mean _support_ though? 

> If this is the only issue on Dev15 that I think we are fine without the guard?

**Comment by davkean** [comment]
> Even if you regressed this in Dev15 (by not following that PR), the worst that would happen is that these in-place changes to these files would not cause us to consider the project to be out of date. Given these ship as NuGet packages, the likelihood of changes being made to them is low because NuGet packages are typically immutable.

**Comment by tmat** [comment]
OK, just wanted to confirm this is the only issue that would arise on Dev15 if we completely remove the property (instead of making it condition). Thanks!
