### ISSUE TITLE
Maestro merges even if the PR reviewers have requested changes

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1999]
_From @natemcmaster on January 24, 2019 19:10_

Is there a way to tell the bot to hold-off merging a PR? I figured the "request changes" gesture in GitHub reviews would have been honored, but apparently not: https://github.com/aspnet/EntityFrameworkCore/pull/14506

![image](https://user-images.githubusercontent.com/2696087/51702381-8530d100-1fc8-11e9-9d85-ae43b59339ef.png)

_Copied from original issue: dotnet/arcade-services#103_

**Comment by natemcmaster** [comment]
@markwilkie do we triage issues in this repo? Or should I move this to dotnet/arcade?

**Comment by natemcmaster** [comment]
_From @mmitche on February 7, 2019 17:20_

@natemcmaster I'd move it to arcade.

**Comment by natemcmaster** [comment]
@markwilkie @mmitche can we give this issue consideration? Now that aspnet is enabling automerge, we'd still like a way to tell the bot to hold off merging.

**Comment by natemcmaster** [comment]
cc @JunTaoLuo @dougbu

**Comment by mmitche** [comment]
Ya, will see whether this is a quick fix.

**Comment by mmitche** [comment]
@natemcmaster I think once the PR goes in (and a rollout happens) I'll go and bulk add this to all existing subscriptions.

**Comment by natemcmaster** [comment]
Awesome 👏
