### ISSUE TITLE
multiple repo official build invalid command "publishbuildassets.cmd" missing

### ISSUE THREAD

**Issue by robertborr** [dotnet/arcade#2006]
@robertborr commented on [Thu Feb 07 2019](https://github.com/dotnet/core-eng/issues/5194)

https://dev.azure.com/dnceng/internal/_build/results?buildId=89615

2019-02-07T15:46:29.9444865Z Script contents:
2019-02-07T15:46:29.9452514Z eng\common\publishbuildassets.cmd /p:ManifestsPath='D:\a\1\a/Download/AssetManifests' /p:BuildAssetRegistryToken=*** /p:MaestroApiEndpoint=https://maestro-prod.westus2.cloudapp.azure.com /p:Configuration=Debug
2019-02-07T15:46:30.0280744Z ##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\09eb40bb-548f-4bab-adb5-f8dfef0123a8.cmd""
2019-02-07T15:46:30.0396058Z 'eng\common\publishbuildassets.cmd' is not recognized as an internal or external command,
2019-02-07T15:46:30.0396620Z operable program or batch file.
2019-02-07T15:46:30.1468966Z ##[error]Cmd.exe exited with code '1'.

---

@robertborr commented on [Thu Feb 07 2019](https://github.com/dotnet/core-eng/issues/5194#issuecomment-461510303)

publishbuildassets.cmd was deleted, and job not updated

---

@robertborr commented on [Thu Feb 07 2019](https://github.com/dotnet/core-eng/issues/5194#issuecomment-461510807)

@nguerrera - could your change have done this?

---

@robertborr commented on [Thu Feb 07 2019](https://github.com/dotnet/core-eng/issues/5194#issuecomment-461516036)

this also affected build: https://dev.azure.com/dnceng/internal/_build/results?buildId=87682

---

@robertborr commented on [Thu Feb 07 2019](https://github.com/dotnet/core-eng/issues/5194#issuecomment-461521556)

this also affected build https://dev.azure.com/dnceng/internal/_build/results?buildId=87703

---

@robertborr commented on [Thu Feb 07 2019](https://github.com/dotnet/core-eng/issues/5194#issuecomment-461522077)

also affected https://dev.azure.com/dnceng/internal/_build/results?buildId=89577 through 
https://dev.azure.com/dnceng/internal/_build/results?buildId=87674

---

@robertborr commented on [Thu Feb 07 2019](https://github.com/dotnet/core-eng/issues/5194#issuecomment-461522650)

also affected: https://dev.azure.com/dnceng/internal/_build/results?buildId=87637   through  https://dev.azure.com/dnceng/internal/_build/results?buildId=89544

---

@riarenas commented on [Thu Feb 07 2019](https://github.com/dotnet/core-eng/issues/5194#issuecomment-461533087)

@chcosta do you have any context on this one so whoever picks it up from FR can take a look?

---

@chcosta commented on [Thu Feb 07 2019](https://github.com/dotnet/core-eng/issues/5194#issuecomment-461534064)

This was caused by a change that @tmat made - https://github.com/dotnet/arcade/pull/1939#issuecomment-461193801

@tmat, can you take a look?

---

@MattGal commented on [Thu Feb 07 2019](https://github.com/dotnet/core-eng/issues/5194#issuecomment-461665102)

@chcosta - Should we also track issues like this in dotnet/arcade instead?

---

@chcosta commented on [Thu Feb 07 2019](https://github.com/dotnet/core-eng/issues/5194#issuecomment-461674811)

Yes, this particular issue should probably be tracked in arcade rather than core-eng

**Comment by chcosta** [comment]
@tmat, PTAL

**Comment by nguerrera** [comment]
cc @livarcocc @wli3 

Wasn't this already fixed by #1992 ?

**Comment by chcosta** [comment]
I haven't done any investigation here, if it's already fixed, that's fantastic, thanks Nick!

**Comment by nguerrera** [comment]
I see all of our builds have turned green, except dotnet/cli but only because the arcade update got hit with CI flakiness. I believe this is indeed fixed with latest arcade that rolled out to our uptake this morning.

**Comment by nguerrera** [comment]
Fixed by #1992
