### ISSUE TITLE
darc-init.sh installs some really old version of darc, not the one it was trying to install

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#2007]
### Repro:
1. Clone https://github.com/aspnet/Extensions (currently at https://github.com/aspnet/Extensions/tree/61070026dca7117d439de0443cfbbb0fb7172c65)
2. Run ./eng/common/darc-init.sh

### Result
The script says it is trying to install  1.0.0-beta.19104.18, but 1.1.0-beta.18618.7 is actually installed.

> $ ./eng/common/darc-init.sh
> Installing Darc CLI version 1.0.0-beta.19104.18...
You may need to restart your command shell if this is the first dotnet tool you have installed.
Restoring packages for /var/folders/2m/hdplh2w93rbgy0yqd6hcmcq00000gp/T/hce0mhnr.gyt/restore.csproj... Installing Microsoft.DotNet.Darc 1.1.0-beta.18618.7. /var/folders/2m/hdplh2w93rbgy0yqd6hcmcq00000gp/T/hce0mhnr.gyt/restore.csproj : warning NU1603: restore depends on Microsoft.DotNet.Darc (>= 1.0.0-beta.19104.18) but Microsoft.DotNet.Darc 1.0.0-beta.19104.18 was not found. An approximate best match of Microsoft.DotNet.Darc 1.1.0-beta.18618.7 was resolved. Generating MSBuild file /Users/namc/.dotnet/tools/.store/.stage/akdgvs35.u40/restore.csproj.nuget.g.props. Restore completed in 1.17 sec f Tool 'microsoft.dotnet.darc' (version '1.1.0-beta.18618.7') was successfully installed. invoke the tool using the following command: darc

cc @mmitche

**Comment by natemcmaster** [comment]
This is what I've been doing to workaround this:

```
dotnet tool uninstall -g Microsoft.DotNet.Darc && dotnet tool install --version '1.1.0-*' -g Microsoft.DotNet.Darc  --add-source https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
```

**Comment by jcagme** [comment]
Looks like `datc-init,sh` doecfs not have the changes needed after the move of darc to arcade-services https://github.com/dotnet/arcade/commit/736f4afebac5ad58a4488daaef37fab28b0475c3#diff-f9871d76aa2f37c8b863a912f253cd1a

**Comment by mmitche** [comment]
This is now fixed as it will use the version currently in use by the server.
