### ISSUE TITLE
Arcade packages not signed?

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#2008]
I happened to create a new VM with VS2019 and my nuget config had
```
  <config>
    <add key="signatureValidationMode" value="require" />
  </config>
```

This was causing corefx build to fail with an error `Build Failed` - no log no other text.

When I manually ran `dotnet build` on our root project I saw the following:
```
D:\corefx\Directory.Build.props(259,3): error : Package 'Microsoft.DotNet.Arcade.Sdk 1.0.0-beta.19081.1' from source 'https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json': signatureValidationMode is set to require, so packages are allowed only if signed by trusted signers; however, this package is unsigned.
D:\corefx\Directory.Build.props(259,31): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
```

Seems like we should be signing arcade packages?

**Comment by tmat** [comment]
That's odd. I see `.signature.p7s` file in the package.

**Comment by tmat** [comment]
Also, from the build signing log that produced the package:

![image](https://user-images.githubusercontent.com/41759/52508591-02a03800-2baa-11e9-9a02-57623823e1fb.png)

**Comment by ericstj** [comment]
can you repro the error if you set signatureValidationMode? /cc @rrelyea 

I recall there were some issues with nuget around this previously.

**Comment by rrelyea** [comment]
fixed in 2.1.504 and 2.2.103 (?) that ship on patch Tuesday (next week)
Fixed with nuget 4.9.3 assemblies

**Comment by markwilkie** [comment]
@ericstj - is this resolved?

**Comment by ericstj** [comment]
Thanks @rrelyea
