### ISSUE TITLE
MSBUILD : error MSB1008: Only one project can be specified

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/arcade#2010]
After updating from 1.0.0-beta.19103.1 to 1.0.0-beta.19107.1, local build cmd no longer worked. Showed the following error: 

```
MSBUILD : error MSB1008: Only one project can be specified.
Switch: Build

For switch syntax, type "MSBuild -help"
Build failed.
See log: E:\winforms\artifacts\log\Debug\Build.binlog
```

But no binary log was produced. See hash f9fe161aa8a9b9b62eb9b675e0af3f5583cabd7a in https://github.com/dotnet/winforms/ for repro

**Comment by tmat** [comment]
The bug is in: https://github.com/dotnet/winforms/blob/master/build.cmd#L2 
Remove `LocalBuild`.

**Comment by zsd4yr** [comment]
Thank you
