### ISSUE TITLE
Arcade builds timing out running Helix tests

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#2020]
@dotnet/dnceng 

All of the Arcade builds (public and internal) are timing out trying to run Helix tests

Internal - https://dev.azure.com/dnceng/internal/_build/results?buildId=91664&view=logs&jobId=16ce49ee-8d0d-5a76-4958-88f78392b71f&taskId=585e46b5-e6cd-5412-e232-b228daaaa8d5&lineStart=53&lineEnd=56&colStart=1&colEnd=1

public - https://dev.azure.com/dnceng/public/_build/results?buildId=92235&view=logs&jobId=00e6d9d3-6ce7-5b67-7f41-a4c1f1007d9d&taskId=be188a2e-c4ff-5d23-f1c4-c094e1d961eb&lineStart=51&lineEnd=52&colStart=1&colEnd=66

**Comment by chcosta** [comment]
FYI @MattGal @alexperovich

**Comment by jcagme** [comment]
https://github.com/dotnet/core-eng/issues/5209 might be related

**Comment by riarenas** [comment]
Yes. That is absolutely dotnet/core-eng#5209. Would it be better to just switch to another linux queue that isn't affected at the moment, like debian.9.amd64(.open) while the issue in core-eng is resolved?

**Comment by markwilkie** [comment]
Closing as it looks like this is resolved.
