### ISSUE TITLE
Adding Functionality to merge conflicts in the mirror

### ISSUE THREAD

**Issue by Anipik** [dotnet/arcade#2027]
Currently all types of merge conflicts need to be handled by the one maintaining the mirror.
This policy can be make little bit easier in case of unidirectional mirrors.

Having a unidirectional mirror suggests that we don't want to edit the shared folder in the actual repo and will always be imported from the outside repo.
Here merge conflicts occur when people edit the files in the actual repo.

We can avoid these merge conflicts by always choosing the incoming version of the merge conflict files (overriding the local version)

eg https://github.com/mono/mono/commit/bb5feb2579733aac92156f2eb0df2ae872ed3e71#diff-dd75eeeaa041d1e149475af52fca075e edited the shared path

and then this change was also ported into the coreclr https://github.com/dotnet/coreclr/pull/22518

When this coreclr commit was mirrored into the mono repo, it caused merge conflicts. this could have been handled by just using the coreclr copy.

# suggested solution
add a conflict property to repository object. if set to true ,

do something like this
```
git checkout --theirs .
git add .
git am --continue
``` 

cc @marek-safar @danmosemsft @safern

**Comment by danmosemsft** [comment]
If the change was identical any idea why it caused a merge conflict? We should least handle that kind of merge 😸

**Comment by alexperovich** [comment]
Its the classic git rebase/cherry-pick problem. They are "identical" changes, but they aren't on top of the same stuff or the same commit, so git doesn't know how to deal with it. What a human can recognize as identical, a computer things is completely different.

________________________________

**Comment by danmosemsft** [comment]
Not on top of the same commit, but the content of the file affected was the same in both repos before the change. I guess we don't know that.

**Comment by markwilkie** [comment]
Closing given that the epic closed.
