### ISSUE TITLE
Utility Pipelines-compatible logging functions

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/arcade#2038]
It would be nice if Arcade had some utility functions in PowerShell and bash that help format error messages and warnings in the [explicit Pipelines way](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md). Then utility scripts in various repos could just call, for example

```powershell
Write-PipelineError "The system is down."
```

And get that translated into

```
##vso[task.logissue type=error]this is an error
```

if the script is running in a Pipelines environment, and just red text otherwise.

Probably with additional optional arguments for the `sourcepath`, `linenumber`, `columnnumber`, and `code` fields.

(Related to #2036 but would be helpful independently of the full flow back to GitHub, since these errors are displayed better on Pipelines build-result pages.)

**Comment by rainersigwald** [comment]
This should follow the Pipelines error-handling guidelines once they exist (https://github.com/MicrosoftDocs/vsts-docs/issues/3225).

**Comment by jaredpar** [comment]
To be more flexible I think the signature should be the following:

``` ps1
function Write-Pipeline([string]$text, [string]$type = "error") { 

}
```

That would allow for easily having non-error messages as well.

**Comment by markwilkie** [comment]
@chcosta - thoughts?

**Comment by chcosta** [comment]
Azure Pipelines supports errors, warnings, and debug messages.

debug messages only show up if you "Queue with diagnostic logs" (or explicitly set the "system.debug" environment variable to "true").  This could be displayed dependening on verbosity, or as a "task.debug" command when running in azure devops.

We probably also want to support error [codes](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md#task-logging-commands).

Seems really reasonable / useful to add this into eng/common/tools.ps1

**Comment by anurse** [comment]
AzP's own task "SDK" has PowerShell functions for this already: https://github.com/Microsoft/azure-pipelines-task-lib/tree/master/powershell/Docs/FullHelp. 

I don't know how feasible it is, but just giving Arcade scripts access to that library would probably be the best solution, since it would mean we could rely on the same code-base.

**Comment by chcosta** [comment]
We'll need a cross-plat solution (I don't think we're on Powershell Core anywhere in Arcade).

**Comment by markwilkie** [comment]
Thoughts @rainersigwald ?

**Comment by rainersigwald** [comment]
The meat of the logging isn't that much:

https://github.com/Microsoft/azure-pipelines-task-lib/blob/11c9439d4af17e6475d9fe058e6b2e03914d17e6/powershell/VstsTaskSdk/LoggingCommandFunctions.ps1#L529-L570

https://github.com/Microsoft/azure-pipelines-task-lib/blob/11c9439d4af17e6475d9fe058e6b2e03914d17e6/powershell/VstsTaskSdk/LoggingCommandFunctions.ps1#L464-L499

I think it could be ported to bash without too much trouble. I'd go with powershell on Windows and bash on *nix, like the rest of Arcade.

I'll take a stab at the bash port.

**Comment by markwilkie** [comment]
Thanks @rainersigwald !

**Comment by chcosta** [comment]
@jaredpar, do you have anything pending on this (w.r.t. the PowerShell emitting error API) or does this still need to be picked up?

**Comment by jaredpar** [comment]
@chcosta this still needs to be picked up. I don't have anything pending at the moment.
