### ISSUE TITLE
Helix SDK should provide a way to download secrets and set them as environment variables

### ISSUE THREAD

**Issue by safern** [dotnet/arcade#2043]
We have 2 common scenarios, to run performance tests and code coverage in helix. 

To run these kind of tests, we need a code coverage token or performance token in order to upload the reports into the services to be able to get to the report after the helix workitems are done.

I propose a python script that you tell it which azure keyvault, which azure secret and what environment variable to set. Then we can use this through either an itemgroup in msbuild or as HelixPreCommands. 

Currently we have to set it directly as HelixPreCommands which leaks the secrets either on binlogs or in test execution std output if you don't wrap the command around the right commands to turn off logging.

cc: @ViktorHofer @adamsitnik @adiaaida @jonfortescue @alexperovich @markwilkie

**Comment by markwilkie** [comment]
Also adding @MattGal as he might have insight.

**Comment by MattGal** [comment]
I don't think this makes sense.  This is exactly what Variable Groups do today, the problem is that we don't want to provide the public access to secret values.  Implementing this ourselves is very much against ShawnR's DncEng core principles.

**Comment by safern** [comment]
> I don't think this makes sense. This is exactly what Variable Groups do today,

But how do we flow them into helix machines? If we flow them into helix machines we would be exposing secrets and therefore can't enable these kind of builds on PRs.

**Comment by MattGal** [comment]
Ah I initially read this as build, but the same thing persists.  If you set something as an environment variable it can be exfiltrated by the user.  There's no way to do this that isn't illusory security.  I'd suggest using short-lived auth tokens such that if(when) the secret is taken it can't be used for long.  

I've had a lot of discussions about this recently, it might be more productive to meet up in person and chat.

**Comment by adamsitnik** [comment]
> I'd suggest using short-lived auth tokens such that if(when) the secret is taken it can't be used for long.

I know that it's far from perfect, but when creating SAS tokens for Azure services it's possible to create a token that is going to work only for machines from selected IP address range.

![obraz](https://user-images.githubusercontent.com/6011991/52849651-d177b880-3111-11e9-937f-79f9b85c8d06.png)

Do helix machines have static IP adresses?

**Comment by MattGal** [comment]
They don't have public IPs at all (any more) but it may be possible to deduce their NAT'ed IPs sources, definitely something interesting to explore.

**Comment by jonfortescue** [comment]
@safern I'd like to follow up with you on this tomorrow so I can better understand this scenario. Adding it to the Helix epic for now.

**Comment by jonfortescue** [comment]
@safern and I talked about this online. He's going to do some more work to see exactly how much work is necessary here and then we're going to have a sit-down meeting at some point to figure out exactly what we would want here. This isn't needed by next week, so I'm kicking this to GA.

**Comment by safern** [comment]
Closing as this is no longer needed now.
