### ISSUE TITLE
How do I set the variables in Tools.ps1?

### ISSUE THREAD

**Issue by rynowak** [dotnet/arcade#2049]
How do I set this? https://github.com/dotnet/arcade/blob/master/eng/common/tools.ps1#L34

Since we need to install multiple runtimes to run our tests (#1441), I need `dotnet` to always be repo local. What's the right way to do this?

**Comment by tmat** [comment]
Like so:
https://github.com/dotnet/sdk/blob/master/eng/configure-toolset.ps1
https://github.com/dotnet/sdk/blob/master/eng/configure-toolset.sh

**Comment by tmat** [comment]
Actually, one change: use `use_installed_dotnet_cli` casing, not `useInstalledDotNetCli`. Both work, but `useInstalledDotNetCli` is kept only for backwards compat.

**Comment by rynowak** [comment]
Thanks! Closing this since my question was answered.
