### ISSUE TITLE
Microsoft.DotNet.GenApi is not updated by dotnet-maestro bot

### ISSUE THREAD

**Issue by pakrym** [dotnet/arcade#2056]
https://github.com/aspnet/Extensions/pull/1134/files#diff-5c6a1c77fe216efcfbbdccb11b863063R71

The definition seems to be correct and in line with what other repos do https://github.com/dotnet/corefx/blob/f9faba33028907c870793e8249397069c6cf91c6/eng/Version.Details.xml#L54

**Comment by jcagme** [comment]
Looking

**Comment by pakrym** [comment]
> @natemcmaster 
> Let's also open a bug on dotnet/arcade to do case-insensitive comparisons. NuGet does not allow package ID's to vary by case, so I don't think `darc` should either.

**Comment by jcagme** [comment]
https://github.com/dotnet/arcade/issues/2058
