### ISSUE TITLE
Build log file name can be specified only with `/bl` parameter, '-bl' is not supported

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/arcade#2062]
When converting build script arguments to msbuild arguments, tools.sp1 file tests for a hardcoded slash character, thus build log name specified with `-bl` on the command line for the build script will not be passed to the msbuild process. However other build script parameters can accept `-` as an argument prefix. 
 
https://github.com/dotnet/arcade/blob/bac85242024ba867b6204b90c1522793093f5e31/eng/common/tools.ps1#L490

> function GetMSBuildBinaryLogCommandLineArgument($arguments) {  
>   foreach ($argument in $arguments) {
>     if ($argument -ne $null) {
>       $arg = $argument.Trim()
>       if ($arg.StartsWith(**"/bl:",** "OrdinalIgnoreCase")) {
>         return $arg.Substring("/bl:".Length)
>       } 
> 
>       if ($arg.StartsWith("/binaryLogger:", "OrdinalIgnoreCase")) {
>         return $arg.Substring("/binaryLogger:".Length)
>       }
>     }
>   }
>   return $null
> }

**Comment by tmat** [comment]
`GetMSBuildBinaryLogCommandLineArgument` function is only used to print out the log path if the build fails. It's not used to pass the binary log name to msbuild. `-bl`/`-binaryLog` [parameter](https://github.com/dotnet/arcade/blob/bac85242024ba867b6204b90c1522793093f5e31/eng/common/build.ps1#L20) of `build.ps1` is a switch parameter. It does not take the log path as a parameter.
