### ISSUE TITLE
GenerateNativeVersionFile target sometimes fails due to failed copy NativerVersion.rc

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/arcade#2064]
[`GenerateNativeVersionFile` ](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.targets#L58) calls [`Copy`](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.targets#L116 ). In turn, the `Copy` task does not check whether `NativeVersion.rc` already exists, and attempts to create it every time. 

This sometimes causes failures. Multiple native (i.e., C++) projects could be building in parallel, and in turn, calling into `GenerateNativeVersionFile` through `ResourceCompile` target. This can (and does) in turn lead to errors like this:

`E:\A\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19070.2\tools\Version.targets(120,5): error MSB3026: Could not copy "E:\A\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19070.2\tools\NativeVersion.rc" to "E:\A\_work\1\s\artifacts\obj\NativeVersion.rc". Beginning retry 1 in 1000ms. The process cannot access the file 'E:\A\_work\1\s\artifacts\obj\NativeVersion.rc' because it is being used by another process.`

I believe the `Copy` task could be changed a bit like this:

    <Copy SourceFiles="$(MSBuildThisFileDirectory)NativeVersion.rc"
          DestinationFolder="$([System.IO.Path]::GetDirectoryName($(NativeVersionFile)))"
          Condition="'$(OS)' == 'Windows_NT' And !Exists('$([System.IO.Path]::GetDirectoryName($(NativeVersionFile)))\NativeVersion.rc')" />

The downside is that a stale copy of `NativeVersion.rc` will not get updated - but this is primarily a problem for local/dev builds and a minor one IMO.

/cc @danzil, @rladuca 
/cc @tmat

**Comment by tmat** [comment]
Such change wouldn't eliminate the race condition. 

`NativeVersionFile` property needs to be set to a project-specific intermediate output path.

**Comment by vatsan-madhavan** [comment]
Then perhaps the [default definition of `NativeVersionFile`](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.targets#L72) could change like this: 

Before:
      `<NativeVersionFile Condition="'$(NativeVersionFile)' == ''">$(ArtifactsObjDir)_version.h</NativeVersionFile>`

After:
      `<NativeVersionFile Condition="'$(NativeVersionFile)' == ''">$(IntermediateOutputPath)_version.h</NativeVersionFile>`

**Comment by tmat** [comment]
Yes that should work.

**Comment by vatsan-madhavan** [comment]
#2067 fixes this.
