### ISSUE TITLE
msbuild.ps1/.sh doesn't pass down ContinuousIntegrationBuild=true to msbuild project when -ci switch is enabled

### ISSUE THREAD

**Issue by safern** [dotnet/arcade#2073]
Should pass down this property when -ci switch is enabled? I've seen some cases where we want to use msbuild.ps1/sh scripts in PR or Official builds and we pass down the `-ci` switch, but we also need to pass `ContinuousIntegrationBuild=true` as a property.

cc: @tmat

**Comment by tmat** [comment]
Sounds reasonable.
