### ISSUE TITLE
Inconsistent handling of command line options between Windows and Unix

### ISSUE THREAD

**Issue by jkotas** [dotnet/arcade#2075]
https://github.com/dotnet/arcade/blob/master/eng/common/build.ps1 expects the arguments to start with a single dash.

https://github.com/dotnet/arcade/blob/master/eng/common/build.sh expects the arguments to start with a double dash.

This inconsistency makes it hard to write good examples of command line options in the documentation; and generally maintain sanity when moving back and forth between Windows and Unix.

More discussion at https://github.com/dotnet/corefx/pull/34385#issuecomment-465811051

**Comment by jkotas** [comment]
Proposal 1: Recognize both `-` and `--`, on both Windows and Unix.

Proposal 2: Recognize `-` for shortcuts and `--` for long commands, on both Windows and Unix.

**Comment by tmat** [comment]
Does PowerShell support `--`? 

We can easily support `-` on Unix for all parameters.

**Comment by jkotas** [comment]
> We can easily support `-` on Unix for all parameters.

That would work for me.

**Comment by markwilkie** [comment]
Moving to post dev16 GA

**Comment by ViktorHofer** [comment]
> We can easily support `-` on Unix for all parameters.

I think that would be the wrong direction. We recently applied POSIX rules to tools like GenAPI and ApiCompat. Also dotnet itself follows POSIX. A single `-` stands for a shorthand command, double `--` present the actual command. I.e. `dotnet build -f netcoreapp3.0` and `dotnet build --framework netcoreapp3.0`. 

cc @natemcmaster

**Comment by natemcmaster** [comment]
PowerShell does not support `--`. Wish it did. Implementing our own parsing in PowerShell would be a pain. As much as I want POSIX to be the default, I don't think it's reasonable to implement that on Windows.

An alternative to consider: the build.sh script could support both the POSIX conventions and the powershell versions. For the sake of muscle memory, this is what we did in the aspnetcore build.sh script (see [this for example](https://github.com/aspnet/AspNetCore/blob/a2c8a34556ae29a2c415d1b66b0e68a807563f2c/build.sh#L218-L245))

**Comment by ViktorHofer** [comment]
> PowerShell does not support `--`.

https://github.com/PowerShell/PowerShell/issues/1584 :(

**Comment by ViktorHofer** [comment]
I submitted https://github.com/dotnet/arcade/pull/2127 which adds the single hyphen alternative.
