### ISSUE TITLE
Helix support for codecoverage reporting scenario.

### ISSUE THREAD

**Issue by safern** [dotnet/arcade#2076]
Currently in corefx we're enabling codecoverage test runs in Helix. Which is great, because now we get reports in a parallel and isolated environment. However, in order to get a Full Report generated, we need to get all the coverage.xml reports for every test execution into the build machine and generate the report there, then upload to codecov.

After talking offline with @Chrisboh and @alexperovich we concluded that it would be nice to support this scenario as part of arcade, with two main features:

### 1. Add a built-in feature into the helix SDK to download files from the results storage.

With this feature we would be able to download .xml reports into the build machine to a well known location. This feature will work the following way:

1. Every helix workitem can include metadata specifying which files to download. I.e:
```xml
<WorkItem Include="MyHelixWorkItem">
  <DownloadFilesFromResults>coverage.xml;testResults.xml</DownloadFilesFromResults>
</WorkItem>
```
2. Every helix job will set metadata through an itemgroup that will be written down to a file under the root folder where files are downloaded in order for the consumer to know this metadata. Metadata will include:
            

- HelixQueue
- HelixProperties (arch, configuration, os)

 The consumer, can add more metadata through this itemgroup, I can imagine corefx for example, adding framework. i.e:
```xml
<DownloadResultsMetadata Include="TargetFramework=netcoreapp" />
```
3. This files will be downloaded to a location defined by an overridable msbuild property: `$(ResultsDestinationPath)/helixresults/<JobId>/<WorkItemName>/` -- the metadata file would be `$(ResultsDestinationPath)/helixresults/<JobId>/metadata.txt`

### 2. Add an azure devops task that merges the codecoverage files and uploads them

This task, should be configurable so that repos can specify:

- ResultsDrop (the task should read the metadata.txt to determine, OS, architecture, configuration, etc.)
- codecov api endpoint.
- codecov token
- repository
- more info???

Please add stuff that I might have missed. I think we can start with the 1st piece as that would unblock many repos to start running code coverage in helix in the meantime as the task is fully designed and developed. 

cc: @alexperovich @Chrisboh @markwilkie @chcosta @ViktorHofer @jaredpar @danmosemsft 

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

**Comment by alexperovich** [comment]
Only one comment on 4. It should be a property like $(ResultsDestinationPath) or something that can be overwritten by the build, then it works locally and on the build agent.

I also think 1. is not necessary. We can enable this based on the Metadata on the items.

**Comment by markwilkie** [comment]
This sounds great @safern.  Thanks for getting things going.

**Comment by Chrisboh** [comment]
Thanks for writing this down.  From what we discussed I think this approach will work and also give us the flexibility to do things with other files from Helix in the future.

**Comment by markwilkie** [comment]
The demand for this has been essentially zero.  If it comes back up, we can re-evaluate.
