### ISSUE TITLE
Handle errors during publishing via release pipeline

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#2083]
In the async way of publishing, a build will add all its packages to an intermediate Azure Devops location, and the public dev release pipeline https://dev.azure.com/dnceng/internal/_release?definitionId=27 will publish the packages to the feed. 

All post build actions, like adding a build to a channel, and the dependency updates that would trigger, will only happen if the release definition succeeds.

This puts us in a situation where a build can succeed, but the packages generated by that build won't be available in the feed if the release definition fails.

We need a story for informing people of this type of failure, and for recovering from this state.

**Comment by riarenas** [comment]
THe main challenge with error reporting in this scenario is that both the official builds, and the release pipelines run as the dotnet-bot user, and not as the person who actually made the change.

We have reached out to Azure Devops to see if we can work with the notifications team to figure out a story for this.

**Comment by JohnTortugo** [comment]
Two options were discussed for solving this. 

Short term: make transparent that publishing failed by [creating an issue in Arcade](#2303 ) and Cc'ing the last committer from the repo that failed publishing.

Long term: Looks like using a new feature from AzDO, called Build stages, would make communication of the publishing failure evident. Still need to be investigated.

**Comment by JohnTortugo** [comment]
With the migration to YAML-based release pipelines the errors will be reported on the AzDO build page itself.
