### ISSUE TITLE
Blob feed publish failure, DirectoryNotFoundException for Sleet temp file

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#2086]
Failure in Core-Setup `release/3.0`: https://dev.azure.com/dnceng/internal/_build/results?buildId=101999

```
  Waiting to obtain an exclusive lock on the feed.
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\vsagent\AppData\Local\Temp\a431713f-c412-48fe-8de6-d6cad755e912\3bb3eaa0-b744-4a52-9138-232868f2ff76.tmp'.
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
     at Sleet.AzureFile.<CopyFromSource>d__2.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Sleet.FileBase.<EnsureFile>d__37.MoveNext()
  Failed to sync 'https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json'. Retrying.
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\vsagent\AppData\Local\Temp\a431713f-c412-48fe-8de6-d6cad755e912\3bb3eaa0-b744-4a52-9138-232868f2ff76.tmp'.
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
     at Sleet.AzureFile.<CopyFromSource>d__2.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Sleet.FileBase.<EnsureFile>d__37.MoveNext()
  Failed to sync 'https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json'. Retrying.
...
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
##[error]publish\publish.proj(288,5): Error : Could not find a part of the path 'C:\Users\vsagent\AppData\Local\Temp\a431713f-c412-48fe-8de6-d6cad755e912\3bb3eaa0-b744-4a52-9138-232868f2ff76.tmp'.
F:\vsagent\11\s\publish\publish.proj(288,5): error : Could not find a part of the path 'C:\Users\vsagent\AppData\Local\Temp\a431713f-c412-48fe-8de6-d6cad755e912\3bb3eaa0-b744-4a52-9138-232868f2ff76.tmp'.
```

It waited for the lock for 1h 37m. Is it possible Sleet set up a temp file that was deleted in this timeframe? Or is there something in Arcade that might be fixable?

I've only seen this once so far, so it might be just another way central feed publish can be flaky.

@markwilkie

**Comment by jcagme** [comment]
When the feed is locked the only thing that Sleet does it literally check again (and again...) until the feed is unlocked. I don't believe it changes anything outside that process but @emgarten might have a better idea.

**Comment by dagood** [comment]
I'm more thinking that some cleanup process on the build agent might have deleted the temp file, not Sleet or the build task. If so (and if this actually repros enough to make it worth it, which I doubt) maybe we can change where Sleet's temp files go to avoid it.

**Comment by markwilkie** [comment]
This is something we've seen a decent amount, and it should be fixed by the work that @riarenas is finishing up.  Also, if it becomes a bit problem in the interim, you can also publish to your own feed (which is what others have done to work around this) - it's just that anyone downstream would have to change as well.

Bottom line is that @riarenas is getting close to the real fix though....

**Comment by emgarten** [comment]
> I'm more thinking that some cleanup process on the build agent might have deleted the temp file, not Sleet or the build task.

This would be my guess also, sleet doesn't do anything while waiting for the lock since the feed will change before it is unlocked.

> maybe we can change where Sleet's temp files go to avoid it.

I've considered adding an option for this before, it could be done.

**Comment by dagood** [comment]
> This is something we've seen a decent amount

I think you're looking at the long lock time rather than the failure--I'm aware of efforts to fix locks, but this is about Sleet being unable to find a temp file/dir and failing the build. I wasn't able to find any reference in core-eng or arcade to the error.

In any case, closing this for now as flakiness probably not worth fixing. If it becomes a problem, I'll switch to a repo-specific blob feed to reduce temp file deletion window of opportunity. (It seems safe enough to assume that's what this is.)

**Comment by emgarten** [comment]
I took a look at the code, the `LocalCache` shouldn't be reused between the calls before the lock and after. I think this is contributing some of the problems. 

Also, you can pass the temp path to the `LocalCache` constructor. By default it just makes a new folder under temp if no path is passed. Just make sure that the folder you use is unique to the LocalCache object, nothing else should be working with that folder.

`LocalCache` is IDisposable, it expects to get disposed at the end, and at that point it will delete the folder.

https://github.com/dotnet/arcade/blob/7c9a7a085cd8315f049d76a52ca1b7780e6c17e5/src/Microsoft.DotNet.Build.Tasks.Feed/src/BlobFeedAction.cs#L350
