### ISSUE TITLE
Support Full NGEN with IBC

### ISSUE THREAD

**Issue by brianrob** [dotnet/arcade#2092]
Today, the target EnablePartialNGENOptimization unconditionally specifies -partialNGEN to ibcmerge.exe (https://github.com/dotnet/arcade/blob/660f6cd006b276edb3764f4d7d726cedf6c29d8e/src/Microsoft.DotNet.Arcade.Sdk/tools/OptimizationData.targets#L119) which means that any users of this target will get partial NGEN.

The bulk of IBC users should be fully pre-compiling their assemblies.  One way to address this would be to add a new target that uses most of the machinery of EnablePartialNGENOptimization but doesn't specify -partialNGEN to ibcmerge.exe.

@tmat, @billwert

**Comment by tmat** [comment]
> The bulk of IBC users should be fully pre-compiling their assemblies.

I wouldn't say that. Anything that is inserted into VS needs to be partial NGEN'd.

> One way to address this would be to add a new target that uses most of the machinery of EnablePartialNGENOptimization but doesn't specify -partialNGEN to ibcmerge.exe.

How does full NGEN differ from partial NGEN in terms of IBC? Is it just the absence of `-partialNGEN` parameter or is there something else?

**Comment by brianrob** [comment]
>How does full NGEN differ from partial NGEN in terms of IBC merge logic? Is it just the absence of `-partialNGEN` parameter or is there something else?

Yes.  The partialNGEN flag sets a bit in the binary that tells NGEN to perform a partial precompilation based on IBC data.  If you remove the partialNGEN flag then it does a full precompilation.

>I wouldn't say that. Anything that is inserted into VS needs to be partial NGEN'd.

Understood.  However, the bulk of binaries don't get inserted into VS.  Note that partial NGEN can be set at crossgen time in addition to setting the bit during IBC merge, so not setting the bit at merge time does not preclude the use of partial NGEN later on.

**Comment by tmat** [comment]
Sure, but we do not crossgen assemblies that target .NET Framework (those that are inserted to VS).

I think we can easily support full ngen by adding a property that removes the `-partialNGEN` flag. 

Currently we have bool `ApplyPartialNgenOptimization` and bool `EnablePartialNgenOptimization`.
We can rename to `NgenOptimization` with values { `full`, `partial`, `` } and `EnableNgenOptimization`, respectively to make the names more fitting.

**Comment by brianrob** [comment]
Seems completely reasonable.  Is this something that you can do?

**Comment by tmat** [comment]
Yup. When do you need it?

**Comment by brianrob** [comment]
1-2 weeks from now would be awesome.  Thanks.

**Comment by brianrob** [comment]
@tmat are you able to make this change?  Thanks.

**Comment by tmat** [comment]
Yes, I'm planning on doing it. Just waiting for Preview 3 to wrap up.

**Comment by brianrob** [comment]
Cool.  Do you have an ETA?

**Comment by tmat** [comment]
Would EOW work?

**Comment by brianrob** [comment]
Absolutely.  Thanks.

**Comment by tmat** [comment]
@brianrob Can we close this? You can now specify full/partial via `ApplyNgenOptimization` property.

**Comment by brianrob** [comment]
Yes, thanks again for doing this.
