### ISSUE TITLE
[DarcLib] Use RemoteFactory to determine the correct client

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2108]
Today, in some places, we rely on checking a URI host to determine whether the Git remote client interface we need to use is either AzDo ot GitHub. `RemoteFactory` already does this and we should make the change in https://github.com/dotnet/arcade-services/blob/master/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs#L332

**Comment by markwilkie** [comment]
done
