### ISSUE TITLE
[darc/maestro++] Missing commands

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2109]
This list represents some of the commands we are missing in darc. List is sorted by usage so the ones at the top should be created earlier:

- [x] get-latest-build
- [x] get-build
- [x] assign-build-to-channel
- [ ] assign-release-to-channel
- [ ] delete-release-from-channel
- [ ] get-pipelines
- [ ] add-pipeline
- [ ] delete-pipeline

**Comment by mmitche** [comment]
ALl functionality has been completed or is not necessary anymore
