### ISSUE TITLE
Create Build Asset Registry spec

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#211]

**Comment by maririos** [comment]
New proposed name "Product Dependencies Store" :)

**Comment by alexperovich** [comment]
current working copy: https://github.com/alexperovich/arcade/blob/alperovi/reportingStorespec/Documentation/BuildAssetRegistry.md

**Comment by alexperovich** [comment]
new link for working copy: https://github.com/alexperovich/arcade/blob/alperovi/reportingStorespec/Documentation/MaestroDataStore.md PTAL @maririos
