### ISSUE TITLE
Review build.proj extensibility changes

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#2116]
We should discuss if there's a better way to expose custom targets which are called from Build.proj than what we currently have: https://github.com/dotnet/arcade/blob/8853580f86696fa88ac77d6aca141eadc874a8ae/src/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj#L108-L109

cc @tmat

**Comment by markwilkie** [comment]
Any suggestions @ViktorHofer ?

**Comment by markwilkie** [comment]
@ViktorHofer - I'm going to close this for now given the non response.  However, please don't hesitate to reopen it.  I would ask that if you do reopen, please add the specific scenarios you're trying to address.

thanks

**Comment by tmat** [comment]
Reopening. This change was checked in without review. @ViktorHofer can you describe the scenario?

**Comment by markwilkie** [comment]
@ViktorHofer  - would you mind adding a quick description of the scenario you were solving for please?  After that, feel free to close this issue.

**Comment by ViktorHofer** [comment]
Of course, let me get back to this till end of week. I'll put it on my list.

**Comment by ViktorHofer** [comment]
I nearly forgot about this, let me quickly draft the requirements for corefx here.

In corefx we have a rich test suite which takes a considerable amount of time to build. Therefore we don't build tests by default when running ".\build.cmd/sh -build". Instead we have an action ".\build.cmd/sh -buildtests" which just build the test assemblies. My unapproved change added an extension point to plumb through this action into corefx.

IMO we could simply revert my change (the extension point) and instead add the buildtests action as a first class citizen and set `SkipNonexistentTargets="true"` to not cause a breaking change for consumers.

Opinions @tmat?

**Comment by markwilkie** [comment]
fyi @alexperovich

**Comment by tmat** [comment]
I don't think we should add another action for building. 

We already have an extensibility point that allows to customize what is built - the `Build.props` file. Couldn't you make inclusion of the test project conditional on some property, say `BuildTests` in `Build.props`?

**Comment by alexperovich** [comment]
If we already have an extensibility point for this, but a PR was created to add another one for the same use case, that is an indication that our documentation is insufficient. We need to properly document every "magic" file in `eng/` that arcade sdk imports conditionally. We should also add examples for each file demonstrating how to use them.

**Comment by tmat** [comment]
@alexperovich There is no issue with docs here. https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#engbuildprops

**Comment by ViktorHofer** [comment]
Let me try out if the public documented extension points are sufficient for what we need in corefx and get back to you (this time sooner).

**Comment by markwilkie** [comment]
Any luck using the docs @ViktorHofer ?

**Comment by markwilkie** [comment]
Thoughts @ViktorHofer ?

**Comment by ViktorHofer** [comment]
@markwilkie I have a few big items on my list that needs to be done this and next week. As soon as I have more resources I'll try this out.

**Comment by markwilkie** [comment]
Closing this for now as it looks like there might be a path forward - feel free to repoen @ViktorHofer as needed.
