### ISSUE TITLE
[Maestro] Normalize AzDO URLs

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2121]
Normalize AzDO urls on inputs to bar to the "dev.azure.com/:account/:project" form.  This avoids potential bugs

Optionally we might provide some kind of normalization on API inputs (e.g. get builds) for ease of use.

Forms:
- https://dnceng@dev.azure.com/...
- https://dev.azure.com/dnceng (preferred)...
- https://dnceng.visualstudio.com/...

Also fix up default channel and subscriptions when this happens.

**Comment by tmat** [comment]
When I clone repos locally using `dev.azure.com` urls the authentication does not work. I had to clone them using `https://dnceng.visualstudio.com` to make them work.

**Comment by jcagme** [comment]
Yeah I think this is a clone only thing, when it comes to API calls I **think** * https://dev.azure.com/dnceng works just fine

**Comment by mmitche** [comment]
Yes correct.  The reason it is that way is that credential manager on your local machine doesn't know how to lookup credentials without the user (dnceng@ format) or the subdomain (dnceng.visualstudio) form.  It works fine of course if you're explicitly cloning or talking to the API with credentials.

**Comment by jcagme** [comment]
I'd like to keep this open while I work on normalizing the URLs on the backend
