### ISSUE TITLE
Document the process to install the Maestro service into an organization

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#2134]
When a user attempts to add a subscription for a repository in an organization that hasn't yet installed the Maestro github application they receive the following error:
    

> The repository 'https://github.com/mono/linker' does not have an associated github installation. The Maestro github application must be installed by the repository's owner and given access to the repository.

We need to add documentation pointing to the place to do this (https://github.com/apps/dotnet-maestro) and link to the doc from the error message.

**Comment by riarenas** [comment]
Moving with all the other doc changes to NET5. This is still missing. The proper place is probably https://github.com/dotnet/arcade/blob/master/Documentation/DependencyFlowOnboarding.md
