### ISSUE TITLE
Limit parallelization of calls to Helix API in CheckHelixJobStatus

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#2144]
This piece of code:
https://github.com/dotnet/arcade/blob/910c6b8df1cfd57defeb4514d5102345ee6bd1dc/src/Microsoft.DotNet.Helix/Sdk/CheckHelixJobStatus.cs#L49
kicks of hundreds of requests to our API in parallel. The frontend can't handle that load, and causes a huge traffic spike.  It eats all our SQL connections and Kusto connections.

We should limit the parallelization to a smaller number to make better use of our pipes.  Making it 1 at a time is easy (just make it a for loop with an await inside) and likely won't show any marked decrease in performance.

If that's not parallel enough, maybe a Semaphore with like 5 limits of parallelization is ok.

These jobs need to act responsibly and can't "hog" our system, because when 2 or 3 jobs do this at the same time, the service falls over, and everyone suffers. So even if it's slightly slower to do it serially, it's still the right move to keep our service healthy.

Otherwise we'll just implement the throttling server side and make everyone suffer more if we can't depend on  clients (which we control) to behave themselves.

**Comment by markwilkie** [comment]
Is this something you have context on @alexperovich ?

**Comment by ChadNedzlek** [comment]
We discovered this yesterday when trying to figure out why Helix keeps falling over since February started.  The thing that looks to be he culprit are things with this pattern... where hundreds of requests for all the workitem for a single job arrive all at once.  They sometimes finish (we can answer the first ones in time to get to the others before they timeout), but because of the burst, the response time on these requests is nearly 2 minutes. Which is a long dangerous window where any other query is almost garanteed to fail as it get's queued up behind this one.

**Comment by ChadNedzlek** [comment]
Really I think we need a new API.  It shouldn't take hundreds of requests to gather this information.  All it's trying to know is if, in this job, and workitem failed.  We can do that with 1 pretty easy SQL query... and that will drop the load on the server by hundreds of times.  But that's a bit more involved... This we can fix in a minute or two. That's a bit more involved: https://github.com/dotnet/core-eng/issues/5389

**Comment by ChadNedzlek** [comment]
Or maybe it could call the aggregate API?  It is, after all, asking an aggregate question. This sort of thing is what that was designed for.

**Comment by markwilkie** [comment]
@ChadNedzlek - did this get assigned to FR already in core-eng?

**Comment by ChadNedzlek** [comment]
I think I already did this, but Matt has some rule that only things in core-eng can be in FR... which is going to get weird when arcade is involved. We might need to revisit.

**Comment by ChadNedzlek** [comment]
Fixed by #2216
