### ISSUE TITLE
[Maestro/BAR] Asset location data missing

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2150]
I think this PR: https://github.com/dotnet/arcade/pull/1908/files ended up dropping the location data from the build manifest, as it stopped getting propagated to BAR. This is causing the need for workarounds in the darc gather-drop command because of missing location info.

This needs to be added back, and in the process we should make the location data mandatory.

**Comment by jcagme** [comment]
I don’t remember if I ended up opening an issue or not but i think this is the same case for arcade-services. I checked corefx and manifests have the location set correctly.

**Comment by mmitche** [comment]
I'm guessing they are setting it explicitly.  Those using the built in arcade targets are not getting the data.

**Comment by chcosta** [comment]
Looking
