### ISSUE TITLE
[Maestro++] Implement Channel subscription mechanism to Arcade

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#216]
This involves:
- Evaluate if the current model (manage the subscriptions in a repository with a JSON file) is sufficient.
- Have the subscriptions in the Arcade repository.

**Comment by jcagme** [comment]
Channel creation will be through Darc. Darc will also provide a way to create subscriptions but might not be the only entry point

**Comment by jcagme** [comment]
This is already implemented in Maestro++ and the work to add it to Darc is already in progress
