### ISSUE TITLE
Support TRX test result format in test reporters

### ISSUE THREAD

**Issue by pakrym** [dotnet/arcade#2161]
`dotnet vstest`/`dotnet test` doesn't support producing xUnit XML.

It would be nice to be able to ingest TRX result files.

cc @alexperovich @anurse

**Comment by anurse** [comment]
Adding support for TRX files would significantly reduce our overhead when understanding test failures in Helix. Right now, engineers have to drill down through the `mc.dot.net` screens and it's very time consuming (and mostly impenetrable for external contributors). This is a high priority for our Helix adoption in ASP.NET (cc @Eilon).

**Comment by markwilkie** [comment]
@jonfortescue / @Chrisboh  - you guys aware of this?  Thoughts on next steps?

**Comment by Chrisboh** [comment]
We can add support for TRX files into Helix and get that work scheduled.  @pakrym I do wonder though is [this](https://github.com/spekt/xunit.testlogger) something that would meet your needs?  According to @alexperovich you can just drop this with your run and it will produce the xunit output we would need.

**Comment by markwilkie** [comment]
Added to the Helix go-live Epic.  Please move as appropriate as I can appreciate how this might be more urgent.

**Comment by jonfortescue** [comment]
Issue moved to [dotnet/core-eng #5655](https://github.com/dotnet/core-eng/issues/5655) via [**ZenHub**](https://www.zenhub.com/)
