### ISSUE TITLE
[darc/maestro++] graph-diff command

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2167]
Quite a few times there have been cases where we want to compare two different graphs to determine what real changes are in the graph.

This would do the following:
- Take two commits/versions/builds, or something like that.  Two initial versions.
- Build a graph for each one
- Diff commits from the same repos in each graph.
- Optionally remove
  - Dependency flow commits (default)
  - Toolset commits (default)

The diff will need to be pretty clever.  There are likely N versions of each repo in each graph, where N > 1

- This command should not double print diffs, 
- The command should not print diffs between nodes in the same graph.

**Comment by jcagme** [comment]
So the output would be the delta in a form of a graph or just the deltas per node?

**Comment by mmitche** [comment]
Deltas per repo.

**Comment by markwilkie** [comment]
@mmitche - is this part of your current PR?

**Comment by mmitche** [comment]
Nope

**Comment by mmitche** [comment]
This is related to #3001.  If this is completed in DarcLib it can be used for generating the PR description described in #3001.

**Comment by riarenas** [comment]
Decided to track everything related to this as part of #3001
