### ISSUE TITLE
Flow asset locations/feeds as part of dependency update.

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2174]
Since the assets contain the information of where they are stored, we are able to flow these locations as part of dependency updates PRs so that the feeds don't need to be added manually on every dependent repo.

This is also important to ensure that whenever we create a new immutable feed for internal builds, all downstream repos learn about the new feeds and are able to restore from them.

* [x] Update nuget.config during dependency flow PRs with the managed feeds where the dependency items are stored.

FYI: @riarenas @JohnTortugo @mmitche @markwilkie

**Comment by mmitche** [comment]
I like this for stabilized builds too, where we may need isolated feeds.  We also don't need to add repo->feed mapping in BAR.  We know the location of the assets we are updating in the repos (feed urls).  We can just use that.

**Comment by jcagme** [comment]
Even better! Where are the feed urls defined?

**Comment by mmitche** [comment]
Locations in the Asset type.

Another caveat here is that nuget.config may not be the correct place to put these for all repos.  In core-sdk, I think the nuget.config is generated off of msbuild data.

**Comment by riarenas** [comment]
Updated title and description with our current thinking for this work.

**Comment by riarenas** [comment]
POR changed a bit from original implementation plan.

We will only flow the asset location feeds into the Nuget.Config, and Maestro++ will only manage feeds with the following naming convention:

`https://pkgs.dev.azure.com/dnceng/_packaging/<repoName>-<CommitSha>/nuget/v3/index.json`

Updated description to reflect that.

**Comment by riarenas** [comment]
Naming convention for the restore sources in the nuget.config:

```
<add key="darc-<repoName>" value="https://pkgs.dev.azure.com/dnceng/_packaging/<repoName>-<CommitSha>/nuget/v3/index.json">
```

**Comment by mmitche** [comment]
@riarenas Might need to incldue some additional bits in the key, as multiple versions of the same repo could be inputs (e.g. two versions of corefx)

**Comment by mmitche** [comment]
@riarenas Yeah exactly.  This is pretty common for servicing, as corefx and aspnet/extensions only produce some packages on each build.

The other case here is where you run a stable build of the same sha twice.  This is just a corner case, not a core scenario.  In this case we can probably just append a suffix onto the end if the feed already exists.

Talked to @jcagme about this yesterday.

**Comment by jcagme** [comment]
Yeah the feed creation handles this and we should make sure we use it in the key. For example, these are created feeds:
*  https://dnceng.pkgs.visualstudio.com/_packaging/darc-int-arcade-123456
*  https://dnceng.pkgs.visualstudio.com/_packaging/darc-int-arcade-123456-1
*  https://dnceng.pkgs.visualstudio.com/public/_packaging/darc-pub-arcade-123456
*  https://dnceng.pkgs.visualstudio.com/public/_packaging/darc-pub-arcade-123456-1
*  https://dnceng.pkgs.visualstudio.com/public/_packaging/darc-pub-arcade-123456-2
