### ISSUE TITLE
Add option for ignoring exit code in RunTests target

### ISSUE THREAD

**Issue by anurse** [dotnet/arcade#2182]
We're looking at adding the ability to sequester tests by trait (specifically for Flaky tests right now). We want to be able to include test runs in Arcade builds that do not fail the build but still produce all the necessary output. It looks like this should be possible by making this Error task conditional on a flag stored with the TestRun item itself:

https://github.com/dotnet/arcade/blob/805802b7ae05b51813a540544bb9f510ca6329d4/src/Microsoft.DotNet.Arcade.Sdk/tools/XUnit/XUnit.targets#L112

I've [already got code in our build script](https://github.com/aspnet/Extensions/blob/1d6767f87fa0df0eceb8040a805de3da67c7f576/eng/FlakyTests.targets) that plugs in and synthesizes multiple TestRun items (and does things like changes the report filename and xunit '-trait' arguments) but I think I'd need an Arcade change to make this work (without just replacing the whole `RunTests` target).

(I have cycles to make the changes myself, but I wanted to create an issue first to discuss)

**Comment by tmat** [comment]
We have been doing this in Roslyn by having a separate CI leg that runs flaky tests. Then you can have the failure of that leg ignored. Would not work for you?

**Comment by tmat** [comment]
You wouldn't need to synthesize any TestRun items that way. Just set the trait in additional arguments based on what leg you are running on.

**Comment by anurse** [comment]
That does sound cleaner! I'll investigate further and re-open if something different is needed. Thanks!
