### ISSUE TITLE
On board other repositories to use Darc and Maestro++ for their official builds.

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#219]
It involves:
- Add the repositories to the Maestro++ subscriptions mechanism.
- Set Maestro++ policies for each repository.
- Builds send information to the Reporting Store using the API to report on the assests produced, the location, and other Build information.

**Comment by jcagme** [comment]
We've on boarded the arcade-minimumci-sample repo and with #804 we'll track on boarding of all tier 1 repos
