### ISSUE TITLE
Support different packages with same name to be published using release pipelines

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2190]
Issue created after this discussion: https://github.com/dotnet/arcade/pull/2186#discussion_r263497077

Due to conflicts with `arcade-validation.sh` script, Tasks.Feed -> PushToAzureDevOpsArtifacts 
needs to[ copy artifacts to a temporary location](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs#L87); The copying routine needs to be improved to support packages with same name but different locations not to override each other.

**Comment by jcagme** [comment]
Publishing to different locations, right?

**Comment by JohnTortugo** [comment]
I updated the issue's description.

**Comment by jcagme** [comment]
@JohnTortugo do you see this happening before P7?

**Comment by JohnTortugo** [comment]
This is an "easy fix" but it's not a priority nor a blocker.

**Comment by jcagme** [comment]
I'll keep around in case you have time after you're done with the main desiderables. Please only pick this up when all the YAML porting is done. :)

**Comment by riarenas** [comment]
@johntortugo Is this still needed now that we're moving away from release pipelines altogether?

**Comment by JohnTortugo** [comment]
We can close this. We can also remove the copy around in the `Publish.proj` and `PushToAzureDevOps` too. I remember a few days ago that @chcosta merged a PR that would solve the need to do that copying.

I'll assign this issue to me so I can investigate more about the PR I mentioned above and if we can indeed remove the copying.

**Comment by riarenas** [comment]
@johntortugo did you come to any conclusion here?

**Comment by riarenas** [comment]
@JohnTortugo Can you remind me of the status of the copying to a temp directory? It's either done or in PR correct? Closing this one.
