### ISSUE TITLE
Refactor eng\validate-sdk.ps1

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2197]
We should consider changing the approach used by `[validate-sdk.ps1](https://github.com/dotnet/arcade/blob/65820ecd54acd04013f95f2635c284459ba2c273/eng/validate-sdk.ps1#L86)` where it moves the whole `artifacts\` folder. This is causing a lot of interference with things that run after the script.

@chcosta @riarenas @alexperovich

**Comment by chcosta** [comment]
Agreed, there are already some issues tracking this type of change

-https://github.com/dotnet/arcade/blob/master/eng/validate-sdk.ps1#L83
- https://github.com/Microsoft/azure-pipelines-yaml/blob/master/design/container-steps.md

**Comment by JohnTortugo** [comment]
@riarenas just FYI, this is the reason we have those copy files around in PushToAzureDevOpsArtifacts: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs#L75

**Comment by chcosta** [comment]
This is removed in https://github.com/dotnet/arcade/pull/3530 where we just do the "validate-sdk" type work in a different stage and we no longer copy the artifacts folder around.

**Comment by JohnTortugo** [comment]
That's all I wanted to hear :-)
