### ISSUE TITLE
[Maestro] When PR description is longer than 4000 PR update/creation fails

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2219]
We saw this in an exception in App Insights. Decision was to update the description only with the contents of the last commit.

We should also check the length regardless of the change to make sure it still is not longer than 4000

**Comment by mmitche** [comment]
We should generally simplify the PR descriptions

**Comment by riarenas** [comment]
from #2639:
> Yeah, looks related. The description in #2219 doesn't call out the fact that you cannot actually build commits in Azure DevOps when the commit message is too long. We have to push a new commit in the repo to workaround this.

Going to start taking a look at this today.

**Comment by riarenas** [comment]
Removed epic label

**Comment by riarenas** [comment]
As per https://github.com/dotnet/arcade/issues/2884. it's not only the PR description that needs to be simpler, but also the commit description.

If a maestro PR is open for a while, it will include all the intermediate versions that got updated as part of the change description. This is not only unnecessarily verbose, but also misleading, as we're only really updating to the last version once it is merged.
