### ISSUE TITLE
Document the graph generation process

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2231]
With https://github.com/dotnet/arcade/commit/6a381e9538a9309261032b401bc475dedb6e6bc9 we provide the ability for every official build to generate graph information in the form of files and put them in the artifacts of the builds.

Since this is an opt-in feature we need to document how to enable it in case repo owners want to include this in their builds.

/cc: @garath

**Comment by markwilkie** [comment]
@jcagme - this is (in theory) quick to do?  If so, any chance you could submit a PR?

**Comment by jcagme** [comment]
Wait I thought @garath was the docs dude... Haha, sure, will have something ready by EOD

**Comment by garath** [comment]
You are probably the best to have the first go. I'm happy to help wiht edits or revisions.
