### ISSUE TITLE
Version Prefix number cannot go over 655

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#2233]
If VersionPrefix is _1.1.2000_ . It will fail with error “The specified version string does not conform to the recommended format - major.minor.build.revision”

Since https://github.com/dotnet/arcade/blob/c663d007ca7e1fcda2da21d807acb59799963f82/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.targets#L31

And file version patch has range of 0-65535

The minimal solution should allow setting custom FileRevision to avoid this calculation.

My end goal is to have an ever increasing “release”. The patch version is always increase so there is no need of “preview”. And we could ship the package to nuget without rebuild. And this bug prevent me to use date + build number as Version prefix

**Comment by tmat** [comment]
I do not understand the goal. The CLR stack versioning is documented here: https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md You should not be inventing your own versioning scheme.

**Comment by wli3** [comment]
How can i automatic increase release build version number without manual bump in this versioning scheme?

**Comment by tmat** [comment]
Why would you want automatic increase?

**Comment by wli3** [comment]
i don't want to bump manually

**Comment by tmat** [comment]
Why would you need to bump manually every build?

**Comment by nguerrera** [comment]
Separately, we have a hard requirement for revision > 655. We're shipping 2.1.700 soon. (2.1 isn't on arcade, but did repo toolset have the same problem,)

> The CLR stack versioning is documented here: https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md 

Not everything in the stack has the same versioning scheme. See https://docs.microsoft.com/en-us/dotnet/core/versions/

**Comment by wli3** [comment]
(different thread for version scheme issue https://github.com/dotnet/arcade/issues/2234)

**Comment by nguerrera** [comment]
cc @dotnet/dotnet-cli @markwilkie

**Comment by tmat** [comment]
> Not everything in the stack has the same versioning scheme.

What components don't? The Arcade versioning scheme does not apply to Major, Minor and Patch versions. Those are chosen by each component and not required to be the same across the stack.

@nguerrera Overflowing 655 for Path is an unforeseen issue :(. Currently we calculate 
the 3rd component of file version like so: `PATCH` * 100 + `yy`. I think the solution would be to change this to `PATCH` * 10 + `yy` - `$(VersionYearBase)`, where the default value of `VersionYearBase` would be 19. It would only need to be changed if we ship one Major.Minor version for more than 10 years, which seems unlikely.

If we make the change now the file versions of components that already shipped in Previews will be higher than the new ones. Is that ok (since it's just a preview) or will it upset the installer?

**Comment by nguerrera** [comment]
My brain hurts. How much money have we spent on this 16-but limitation.

Does that work for the patch version already being 100 in SDK 3.0.100?

**Comment by tmat** [comment]
> My brain hurts. How much money have we spent on this 16-bit limitation?
Yeah, it's terrible :(

Is it already 100?

**Comment by tmat** [comment]
If it's already 100 then we need to change +20 to +100

**Comment by nguerrera** [comment]
SDK versions are always x.y.100+. The reason is that if we went back to 3.0.0, then as soon as we needed a new VS release, everyone would go back and complain that the versions should all be the same. So we don't reset to 0, we reset to 100.

**Comment by tmat** [comment]
I see. Ok. We can do +100.

**Comment by tmat** [comment]
Actually, this won't work. Hmm :(

**Comment by tmat** [comment]
Better approach:

`FILEPATCH` = `yy` * 2000 + `PATCH`

Can we limit PATCH to < 2000?

**Comment by nguerrera** [comment]
I don't know why we said "This situation isn't expected to occur". We'll be at 800 soon. 1000 is definitely possible. 2000 is not far enough for me to say never.

**Comment by tmat** [comment]
Hmm, I don't know how to fit this then. Maybe we need to overflow the patch number to the minor version in the file version format.

**Comment by tmat** [comment]
`FILEMAJOR` = `MAJOR`
`FILEMINOR` = `MINOR` * 100 + PATCH / 100
`FILEPATCH` = (`PATCH` % 100) * 100 + `yy`

**Comment by tmat** [comment]
I think this would actually be best - it's compatible with the current format and easy to reason about.

**Comment by nguerrera** [comment]
That works. And we can still see the real version in informational version. File version just has to be increasing in predictable way at the end of the day.
