### ISSUE TITLE
Block repacking on global tools

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#2235]
When PackAsTool=true.

https://github.com/dotnet/arcade/issues/2234 make me realize the current way to support "ship any time" is to use repackage to have "with suffix" and "without suffix" nupkg. And since the embedded then signed shim version need to be the same as the package version, this will produce invalid global tools. We should discuss a long term solution, however, we should block this for now and surface the error early

**Comment by wli3** [comment]
cc @livarcocc @KathleenDollard

**Comment by wli3** [comment]
Ping. Do you mind if I send a PR to block it?

**Comment by markwilkie** [comment]
No of course not.  Thanks @wli3

**Comment by wli3** [comment]
closed via https://github.com/dotnet/roslyn-tools/pull/480
