### ISSUE TITLE
eng/common files not pushed to AzDO repos as part of dependency flow

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2243]
For AzDO repos version files are been updated with new versions correctly but files under `eng/common` are not been updated. This only happens on AzDO repos.

**Comment by jcagme** [comment]
@adiaaida this is now working https://dnceng.visualstudio.com/internal/_git/dotnet-optimization/pullrequest/658

FYI @markwilkie

**Comment by adiaaida** [comment]
@jcagme Thanks so much!

FYI @brianrob
