### ISSUE TITLE
[Helix] AzDev reporter failure doesn't fail the work item.

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#2246]
From this build: https://mc.dot.net/#/user/WinUI/pr~2Fwinui~2Frefs~2Fpull~2F420~2Fmerge~2F/test~2Fproduct~2F/5924.x64.release/workItem/ApiTests.ColorPickerTests/wilogs

The xunit reporter is failing, but the work item isn't reporting that failure.

The failure of xunit reporter needs to cause the work item to fail.

**Comment by markwilkie** [comment]
This issue seems stale and not necessarily relevant or of any significant priority.  However, if any of these assumptions are incorrect, please reopen.
