### ISSUE TITLE
[Helix] AzDev reporter fails sometimes with a missing module

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#2247]
From this build: https://mc.dot.net/#/user/WinUI/pr~2Fwinui~2Frefs~2Fpull~2F420~2Fmerge~2F/test~2Fproduct~2F/5924.x64.release/workItem/ApiTests.ColorPickerTests/wilogs

the xunit reporter is failing because the 'typing' module is missing.

**Comment by ChadNedzlek** [comment]
This build is long gone, and, as such, all ability to learn what was going on here is lost. I'm closing it.
