### ISSUE TITLE
[Maestro] FSharp builds not being automatically assigned to channels

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2251]
darc get-default-channels shows:

```
https://github.com/Microsoft/visualfsharp @ refs/heads/dev16.1 -> .NET Core 3 Dev
https://github.com/Microsoft/visualfsharp @ refs/heads/dev16.1 -> .NET Core 3 Release
```

But builds of this branch are not being automatically assigned:

https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=2493477

This may have something to do with fsharp building directly off of github.

**Comment by mmitche** [comment]
I'm 90% sure this is the exception thrown on this operation:

https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/AnalyticsBlade/initiator/AnalyticsShareLinkToQuery/isQueryEditorVisible/true/scope/%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod%22%7D%5D%7D/query/H4sIAAAAAAAAA0utSE4tKMnMzytWqFEoz0gtSlXIL0gtSgQJxXumKNjaKiilGRqaWRikJRmZWyYap5gkW5qZphkZpyYmp5kARZONlBS4APRrjw5HAAAA/isQueryBase64Compressed/true/timespanInIsoFormat/P1D

**Comment by mmitche** [comment]
```
Failed executing DbCommand (4ms) [Parameters=[@p0='?' (DbType = Int32), @p1='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [BuildChannels] ([BuildId], [ChannelId])
VALUES (@p0, @p1);
```

/cc @alexperovich

**Comment by jcagme** [comment]
This https://github.com/dotnet/arcade-services/pull/237 fixes this issue. When storing the build we are saving async but we are not awaiting so basically there is a race condition

**Comment by mmitche** [comment]
@jcagme Thanks. I'm also adding a scenario test case for this

**Comment by markwilkie** [comment]
@jcagme - can (or should) this issue be closed?

**Comment by jcagme** [comment]
Yup
