### ISSUE TITLE
Investigate what happened with these PRs

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2254]
These two PRs got into a weird state where they seem to have imported only part of the base branch:

https://github.com/dotnet/arcade-services/pull/236
https://github.com/dotnet/arcade-services/pull/237

we need to get a better understanding about what happened here.

/cc @jcagme @ChadNedzlek @alexperovich

**Comment by markwilkie** [comment]
@mmitche - is this still a thing?

**Comment by mmitche** [comment]
No idea.  I'm not even quite what "imported part of base branch" means.

**Comment by JohnTortugo** [comment]
I can take a look on this in the next days; if now, I guess it will be OK to close.

**Comment by markwilkie** [comment]
Closing per @JohnTortugo comment
