### ISSUE TITLE
Support something like "ReportedHelixTargetQueue" in Arcade Helix SDK

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#2261]
https://github.com/dotnet/arcade/blob/a1b24d2591cac827ce893c2a757771f42d24a5d8/src/Microsoft.DotNet.Helix/Sdk/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets#L37

Some places like .NET Mission Control use this operatingsystem property to report the Helix QUeue Id.  Previously users could set this property bag value to whatever they'd like. 

I'm thinking of something like:

- Have a new property called ReportedHelixTargetQueue
- If the property is not provided in the buildproperties, it defaults to HelixTargetQueue
- Always set operatingsystem to "ReportedHelixTargetQueue"

... but I don't care so long as jobs like this one show the reported queue (Debian.9-arm32): 
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F36054~2Fmerge/test~2Ffunctional~2Fcli~2F/20190314.30/workItem/CoreFx.Private.TestUtilities.Tests/wilogs

@wfurt , @jonfortescue  FYI

**Comment by safern** [comment]
What about if people are using multiple helix target queues? How do you specify this property as a build property? I think the Helix SDK rather than adding a property should parse the friendly name.

**Comment by MattGal** [comment]
It's easy to tell from the output that actually exists HelixTargetQueue is always a singular property, otherwise you'd see OperatingSystem be a value like "Queue1+Queue2+Queue3...".  on Mission Control for such.  My idea was optional and would probably require parsing at a higher layer anyways, the SDK just needs some way to support setting this property bag value.

**Comment by safern** [comment]
Yeah. Just wanted to call that out because at this layer of the SDK we already parsed multiple queues into individual queues in `MultiQueue.targets`, so we will need to do some parsing so that people can do `(FriendlyName1)HelixQueue+(FriendlyName2)HelixQueue2` -- this parsing will need to be done at `MonoQueue.targets` because when you pass down only one Queue using `HelixQueue` property, we don't use `MultiQueue.targets` at all.

**Comment by ChadNedzlek** [comment]
I believe this issue is in reference to MC, which is deprecated, so I'm closing this.

**Comment by MattGal** [comment]
Also QueueAlias is exactly what I was hoping for and the new Job API added this.
