### ISSUE TITLE
Microsoft.DotNet.Build.Tasks.Packaging throws missing method exception on .Net Core 3.0

### ISSUE THREAD

**Issue by jashook** [dotnet/arcade#2262]
```
/Users/jashoo/.nuget/packages/microsoft.dotnet.build.tasks.packaging/1.0.0-beta.19128.2/build/Packaging.targets(1214,5): error : System.MissingMethodException: Method not found: 'Void NuGet.Packaging.Manifest.Save(System.IO.Stream, Boolean)'. [/Users/jashoo/projects/scratch/scratch-coreclr/src/.nuget/Microsoft.NETCore.Native/Microsoft.NETCore.Native.pkgproj]
```

This will block dotnet/coreclr from updating to a 3.0 sdk. /cc @RussKeldorph @janvorli @sbomer

**Comment by jcagme** [comment]
This was fixed by @ericstj with https://github.com/dotnet/arcade/pull/2165. Can you confirm you Arcade version?

**Comment by jcagme** [comment]
`1.0.0-beta.19128.2` is kinda old. Latest we have available in Arcade is `1.0.0-beta.19162.7`. I see this hasn't been updated in a while and that there's a coreclr subscription to get updates pushed to the release/3.0 branch but it has no `updateFrequency` set so things won't flow. You could run `darc update-dependencies -c ".NET Tools - Latest"` and that would make your local repo up to date, and when you build, this particular error should be gone

**Comment by jashook** [comment]
Thanks will try this when I have the chance

**Comment by jashook** [comment]
Closing for now
