### ISSUE TITLE
Network build failures in 'official/dotnet/arcade/refs/heads/master' - '20190314.126'

### ISSUE THREAD

**Issue by robertborr** [dotnet/arcade#2264]
@dotnet-mc-bot commented on [Thu Mar 14 2019](https://github.com/dotnet/core-eng/issues/5498)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=124948
  - **Agent:** Hosted VS2017 2
  - **Error log:** error: remote unpack failed: error VS403654: The push was rejected because it might contain credentials or other secrets....

@robertborr

---

@robertborr commented on [Fri Mar 15 2019](https://github.com/dotnet/core-eng/issues/5498#issuecomment-473334504)

error: remote unpack failed: error VS403654: The push was rejected because it might contain credentials or other secrets.
To https://dev.azure.com/dnceng/internal/_git/dotnet-corefx
 ! [remote rejected]       master -> master (VS403654: The push was rejected because it might contain credentials or other secrets.

/src/System.Net.Requests/tests/HttpWebRequestTest.cs(1325,34-60) : error : CSCAN0220 : hash EHZG3hT5yNPz483bdwL8SrWW91p4oJH5ozVc4wlTsZE=

If these are valid credentials, even for non-production resources, you must remove them from Git’s branch history by resetting your branch or squashing all commits.
See https://aka.ms/1escredscan for instructions. Please report any false positives to 1ESSecTools@microsoft.com.

NOTE: It is not enough to remove the secrets and push another change. You must reset your branch according to the instructions.

If this is a false positive, you can bypass credential scanning (for this push alone) by running these commands, assuming that you have no staged changes:

    git commit -m "**DISABLE_SECRET_SCANNING**" --allow-empty
    git push

Alternatively, see https://aka.ms/1escredscan for instructions on how to use the hash values emitted above in a suppressions file to suppress false positives.)
error: failed to push some refs to 'https://dn-bot:***@dev.azure.com/dnceng/internal/_git/dotnet-corefx'
##[error]Cmd.exe exited with code '1'.

**Comment by alexperovich** [comment]
@robertborr this actually looks like a dotnet/corefx source code issue. The code in this commit https://github.com/dotnet/corefx/commit/2e006bb1a471d2b75d1bbae282241d15da388899 triggered AzDev to flag the commit as having credentials.

**Comment by robertborr** [comment]
interesting. thanks. I'll ask corefx and move it if they agree.

**Comment by robertborr** [comment]
per corefx team
There’s no problem here.  The only “credentials” in that commit are made up “rightusername” and “rightpassword”, that the test is just validating get passed along to itself.  Any flag on this is a false positive.

**Comment by dagood** [comment]
Is the CoreFX team expecting to fix the mirror build (work around the false positive) or is core-eng planning to help?

(Last CoreFX commit mirrored was 4 days ago.)

/cc @jcagme if you're looking at general mirroring stuff (or maybe the arcade-validation investigation was one-off)

**Comment by riarenas** [comment]
Should this be re-opened if we're duping these build failures to this one?

**Comment by robertborr** [comment]
sorry - I thought it was. my bad.

**Comment by robertborr** [comment]
the problem is really a corefx issue though, and they're trying to decide how to handle it.

**Comment by markwilkie** [comment]
@robertborr - has this been resolved?  (I thought I heard it might have been)

**Comment by robertborr** [comment]
I have not heard of any fixes on this. otoh - I haven't seen any of these failures today.

**Comment by markwilkie** [comment]
@MattGal - should we keep this open or close it?

**Comment by MattGal** [comment]
Yes, let's close this issue as this specific one has been worked around, but allow me to add you to an ongoing thread about this problem and perhaps we can use your skillset to drive to some kind of non-awful solution
