### ISSUE TITLE
Arcade should create environment variables for Artifacts and Logging directories

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/arcade#2276]
This should act like `Build.SourcesDirectory` where Arcade produces something like `Build.OutputDirectory` and `Build.LoggingDirectory`

**Comment by zsd4yr** [comment]
use case:

```yml
      - script: eng\cibuild.cmd
          -configuration $(_BuildConfig)
          $(_OfficialBuildIdArgs)
          -pack
          -sign $(_SignArgs)
          -publish $(_PublishArgs)
          /bl:$(BUILD.SOURCESDIRECTORY)\artifacts\log\$(_BuildConfig)\PackSignPublish.binlog
        displayName: Pack, Sign, and Publish
```

where ` /bl:$(BUILD.SOURCESDIRECTORY)\artifacts\log\$(_BuildConfig)\PackSignPublish.binlog` could be simplified and future-proofed to  /bl:$(BUILD.LOGGINGDIRECTORY)\$(_BuildConfig)\PackSignPublish.binlog

**Comment by zsd4yr** [comment]
This is already done in Tools.ps1; they should just be made environment variables instead of just creating powershell variables and directories

**Comment by zsd4yr** [comment]
Something like 
```powershell
$env:BUILD.LOGGINGDIRECTORY = $LogDir
```

here: https://github.com/dotnet/arcade/blob/ecda2c265c89b4ffc6fad9659681b3a172ad9c75/eng/common/tools.ps1#L519

**Comment by tmat** [comment]
I don't think we should use env variables. If anything VSO variables would be preferable.

**Comment by zsd4yr** [comment]
You use env vars for other purposes. I am not married to implementation; just making suggestions based on prior work in the repo

**Comment by tmat** [comment]
We try not to use env variables if possible. I'm not sure you can actually use env variables for this anyways, since they are scoped to the process that sets them and its children. But VSO variables would do.

**Comment by markwilkie** [comment]
Do AzDO vars work for you @zsd4yr ?

**Comment by zsd4yr** [comment]
> Do AzDO vars work for you @zsd4yr ?

@markwilkie are these ready-made? How can I refer to them? It could potentially work 😄

**Comment by markwilkie** [comment]
There's decen docs here:  https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch.  @chcosta is also a good source if you have questions.

**Comment by alexperovich** [comment]
AzDev variables should work for most cases. They show up as environment variables for every build step after the step they are created in.

**Comment by zsd4yr** [comment]
@markwilkie thanks for the doc link. I'll explore this option.

Closing the issue for now as by-design with alternative solution :) 

@alexperovich @chcosta do either of you know if there are already azure devops variables for the artifacts and logging directories?

**Comment by tmat** [comment]
Arcade build scripts do not set VSO variables for artifact dirs.

We set some variables to control dontet cli here: https://github.com/dotnet/arcade/blob/master/eng/common/tools.ps1#L147

We could set `Artifacts.Bin` and `Artifacts.Log` variables in the same way.

**Comment by zsd4yr** [comment]
> Arcade build scripts do not set VSO variables for artifact dirs.
> 
> We set some variables to control dontet cli here: https://github.com/dotnet/arcade/blob/master/eng/common/tools.ps1#L147
> 
> We could set `Artifacts.Bin` and `Artifacts.Log` variables in the same way here: https://github.com/dotnet/arcade/blob/master/eng/common/tools.ps1#L522

I would like to have either of these

**Comment by tmat** [comment]
@zsd4yr Feel free to send a PR that sets this variables at https://github.com/dotnet/arcade/blob/master/eng/common/tools.ps1#L522
