### ISSUE TITLE
EnableAzurePipelinesReporter should support non-XUnit results

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#2286]
The EnableAzurePipelinesReporter should support results from WorkItemCommands in addition to XUnit results.

**Comment by MattGal** [comment]
Kicking out of FR unless you have a reason that new feature work should go there.

**Comment by adiaaida** [comment]
@Chrisboh asked me to put it in FR.

**Comment by billwert** [comment]
hi @mjanecke any idea on an ETA for this fix?

**Comment by mjanecke** [comment]
@billwert I haven't started this yet.

**Comment by mjanecke** [comment]
Hi @billwert, I'm planning on starting this work today. Since this area of our codebase is new to me, I am hoping to have a better understanding of an ETA by tomorrow. Thanks!

**Comment by mjanecke** [comment]
PR merged.
