### ISSUE TITLE
[Maestro] Dotnet-Trusted not being assigned a default channel

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2292]
DotNet-Trusted builds are not getting assigned default channels.

**Comment by jcagme** [comment]
I've normalized the "old" values in the DB and running a validation build right now. We still need to figure out why we were not normalizing or not normalizing correctly the data read from DB and matching it to a normalized input.

**Comment by jcagme** [comment]
Build succeeded and it was correctly associated to the default channel.
