### ISSUE TITLE
Update version of Tasks.Feed / Sleetlib in Core-setup

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2295]
Looks like Core-setup is using an older version of Sleetlib. It'd be nice to update the repo to use the latest version so we can have profiling information about core-setup publishing.

/cc @jcagme @dagood

**Comment by jcagme** [comment]
And for that we should should update Arcade SDK’s DefaultVersions.props to include the latest Microsoft.DotNet.Task.Feed versión there since core-setup doesn’t define a dependency on it hence is not updated through dependency flow

**Comment by dagood** [comment]
Maybe I'm misunderstanding, but I don't think changing `DefaultVersions.props` would update the it either, since Core-Setup doesn't use Arcade SDK.

**Comment by jcagme** [comment]
Are you still using things from buildtools?

**Comment by JohnTortugo** [comment]
@dagood can you educate me and tell where you declare the version of Tasks.Feed used by core-setup? :-)

**Comment by dagood** [comment]
I don't know if this version in particular is from buildtools, but it's defined here: https://github.com/dotnet/core-setup/blob/eeb804262c54e7cb288912fb44a826fd31e7b0f2/dependencies.props#L45

More generally, yes. https://github.com/dotnet/core-setup/issues/4788
