### ISSUE TITLE
[Publishing] Open GitHub issues when something fails while running the publishing pipelines

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2303]
We don't have a good way to notify the user when the pipeline which is publishing the packages built  fails. We could open GH issues on the repo we are processing and that will send an email to those who want to be notified. At the same time we might not want to open the issues on the repo we are processing since most likely it's not a product issue. For this we'd need to keep a list of repo owners so we can tag them in said issue we'd open.

**Comment by JohnTortugo** [comment]
Can't we create the issue in Arcade (because publishing stuff come from there) and CC the last non-bot user that committed in the repo where publishing failed?
