### ISSUE TITLE
Create plan to move coreclr to VSTS

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#231]
CoreCLR has a very complete CI build definition in Jenkins.  A plan/approach needs to be created which describes what going to VSTS looks like.

**Comment by chcosta** [comment]
@jonfortescue is working to provide an example of one leg of the CoreClr official build building the product and tests, then sending tests to Helix.

**Comment by chcosta** [comment]
This exists - https://github.com/dotnet/arcade/blob/master/Documentation/MigrationPlan/CoreClrPlan.md
