### ISSUE TITLE
[Validation ring]  Publish packages to int.nugettest.org

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2310]
As recommended in https://docs.microsoft.com/en-us/nuget/faqs/nuget-faq#managing-packages-on-nugetorg uploading packages to the INT environment is a good way that things would work once packages are published to nuget.org.

I think we could make this an opt-in feature and teams decide whether they want to test this or not as it might add time to the overall release pipeline.

**Comment by JohnTortugo** [comment]
@jcagme I think @markwilkie said we had to come up with a plan describing a scheme for how frequently / for which builds this should happen. Do I recall that right?

**Comment by jcagme** [comment]
Yes. I sent the overall plan to @leecow to get it approved so I work on the sub-plans for each of the stages. I think Lee is still working on that but once I get a response I'll work on INT nuget and also the rest of the validation steps. I will also CC you in the thread so you know what's going on

**Comment by leecow** [comment]
To make sure I understand, we would use int.nugettest.org at some level of frequency for nupkg metadata validation?

**Comment by jcagme** [comment]
That is the plan. It is included in the "Final Validation" stage of the email I sent you last week.

**Comment by jcagme** [comment]
Now tracked by #2897
