### ISSUE TITLE
Release 'Publishing for build 20190325.7 of arcade-official-ci' failed

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2337]
Something failed while trying to publish assets in BAR build 1234 to feed 'feed.com'. Please click [here](https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=3867) to check the error logs. 
/fyi: @jcagme

**Comment by JohnTortugo** [comment]
Something failed while trying to publish artifacts for [Build 1234670.89](https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=3867). 

Please click [here](https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=3867) to check the error logs. 

/FYI: @jcagme @JohnTortugo @lastauthor-commit-author
