### ISSUE TITLE
NUGET_PACKAGES path does not match Visual Studio

### ISSUE THREAD

**Issue by sharwell** [dotnet/arcade#2351]
The following line does not end with a trailing `\`:

https://github.com/dotnet/arcade/blob/d37430d5f902154260b1d924d385b16c0929c290/eng/common/tools.ps1#L380

As a result, the `packageFolders` entry in **project.assets.json** changes depending on whether you run a restore operation inside Visual Studio, or via the arcade command line tools.

**Comment by tmat** [comment]
Sounds like a bug in NuGet. I'd expect NuGet normalize the path and trim the ending backslash.

**Comment by markwilkie** [comment]
@sharwell - Am I understanding this correctly that the restore works fine from the command line, but not from within VS?

**Comment by sharwell** [comment]
@markwilkie The restore works fine in both places for the build, but any difference between the two will force the restore process to rewrite the asset file on disk to apply the change.

**Comment by tmat** [comment]
@rrelyea @nkolev92

**Comment by nkolev92** [comment]
@tmat 
That's something that NuGet can fix. 

NuGet normalizes the path, but doesn't trim/append trailing slashes 
If fact the trailing slashes is explicitly added in https://github.com/NuGet/NuGet.Client/blob/27af96bdb7ba8d6d7ea9ad53fc76cd1d1aa80703/src/NuGet.Core/NuGet.Configuration/Utility/SettingsUtility.cs#L20

**Comment by markwilkie** [comment]
Suggestions on next steps @nkolev92 or @rrelyea ?

**Comment by nkolev92** [comment]
I'd suggest fixing your build infra so that you don't get the extra design time builds anymore. 
I have created an issue on our end to address it throughout. 
https://github.com/NuGet/Home/issues/7968

**Comment by markwilkie** [comment]
Looks like this is tracking, so am closing the issue.  Feel free to reopen of course if needed.
