### ISSUE TITLE
[darc/maestro++] Add a new step to validate generate-graph-files.ps1

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2357]
In the past week we've been breaking this process by updating the script with a `darc` version that errors for different repos. The same version might work fine for a repo like `arcade` but might fail for `core-sdk`. It could even for the same repo but different commits.

While it would be hard to test all permutations I think that using `core-sdk` is a safe bet since its graph includes all sort of edge cases. We'd need to run something like:

* `darc get-dependency-graph --repo https://github.com/dotnet/arcade --version master` and play with the following options: `--flat --coherency --graphviz --include-toolset`

One more thing that runs in the script is the PNG file generation based on the graphviz output. This has also failed before. For this we'd need to install `dot.exe` and feed it with the output of  `--graphviz`.

The ideal thing would be to just run `generate-graph-files.ps1` as is but we'd need to run it within a core-sdk repo. If we can clone the repo, update the `darc` version in `generate-graph-files.ps1` and execute it that would be enough.

**Comment by mmitche** [comment]
I think this was fixed by a unit test in arcade-services already which builds the graph of core-sdk
