### ISSUE TITLE
Plan for versioning templates

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#237]
@mmitche and I were discussing what's the best way to consume repository templates in a versioned or semi-versioned format.  This came up because of a PR that @natemcmaster recently submitted where the question was [asked](https://github.com/aspnet/Common/pull/374#issuecomment-395513762).

We should document the guidance around this.  A couple of the ideas are

- tag template respository builds
- use branches

For now, using master is fine, but this is likely to change, particularly w.r.t. servicing branches.

**Comment by markwilkie** [comment]
This hasn't come up recently, so am closing.  (reopen if required)
