### ISSUE TITLE
Make Maestro++ pass user defined parameters to the release pipeline

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2370]
In combination with https://github.com/dotnet/arcade/issues/2417 Maestro++ should pass down to the release pipeline, at the instant of release creation, the set of parameters+values configured for a Channel+ReleasePipeline association.

- Might be interesting to consider how to extend this to support passing custom parameters also based on the build's repository. For instance, to register a handler to send success / error messages.

/cc @mmitche @jcagme

**Comment by jcagme** [comment]
What's the difference between this one and https://github.com/dotnet/arcade/issues/2417?

**Comment by JohnTortugo** [comment]
This one was to make the ReleasePipelineRunner pass additional parameters to the pipeline. #2417 was to create a Maestro API & Modify BAR to store the parameters that ReleasePipelineRunner would pass to the pipeline.

I think both issues won't be necessary once we move to YAML pipelines.

**Comment by JohnTortugo** [comment]
There is no need for this now that we're moving to YAML-based publishing pipelines.
