### ISSUE TITLE
Consider reorganizing publishing pipelines project files under Arcade SDK

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2371]
Consider reorganizing publishing pipelines project files to meet these requirements / topics:

- Enable people not using Arcade SDK to use the pipelines
- Move files under Arcade SDK? Move to a different project?
- Add new configuration file to store package versions
- Add new configuration file(s) to support customization of release stages.
  - One configuration file for the whole pipeline?
  - Not rely on importing Signing.props

**Comment by JohnTortugo** [comment]
From @natemcmaster about [importing Signing.props in the pipeline](https://github.com/aspnet/AspNetCore-Tooling/pull/412#discussion_r274211933):

> That seems fragile. I don't that is sustainable. If someone were to add another <import> w/o a Condition, it would pass PR checks and local build, right? I think you're setting yourself up for a maintainers nightmare.

**Comment by jcagme** [comment]
@JohnTortugo what's the latest on this one?

**Comment by JohnTortugo** [comment]
This will be done as a side-effect of moving to YAML pipelines.

**Comment by JohnTortugo** [comment]
The files where moved to under `eng\common\post-build` and to SdkTasks in the Arcade.SDK.
