### ISSUE TITLE
Move Pipelines MSBuild Logger code to Arcade

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#2376]
https://github.com/dotnet/arcade/issues/2036#issuecomment-477736091

**Comment by markwilkie** [comment]
Once the code is moved over - it should be wired up as well in Arcade of course.

**Comment by markwilkie** [comment]
Thanks for working on this @jaredpar

**Comment by natemcmaster** [comment]
I think this is done done, right? https://github.com/dotnet/arcade/commit/b8f292cb3f839f2ea770ba231beed569dd60162c

**Comment by chcosta** [comment]
I don't think it's quite done.  I think [this[(https://github.com/dotnet/core-eng/issues/6292) is still needed to get things working.

**Comment by chcosta** [comment]
This is done
