### ISSUE TITLE
[darc/maestro++] Handle package version downgrades

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2389]
When a version is about to be downgraded by Maestro (determined by parsing the existing version numbers like NuGet does), we should provide a warning in the Maestro PR (and in local darc output).

We should probably also not auto-merge in this case.

**Comment by riarenas** [comment]
Considering moving some processes to asynchronous release pipelines is likely to cause an uptick of #2349. Bumping the priority of this one to P5 epic.

**Comment by mmitche** [comment]
Covered by #3216
