### ISSUE TITLE
Include version stabilization parameters in ProdCon manifest

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#239]
Enables https://github.com/dotnet/source-build/issues/550: updating version stabilization settings to match what ProdCon used during the build. This will allow source-build output versions to match ProdCon's without the human investigation currently required.

What comes to mind for implementation:

 1. Have pipebuild pass the versioning properties into `DotNet-Orchestration-Push-Manifest` (the ProdCon utility build def on VSTS), and have that build def pass the version stabilization parameters into the MSBuild call.
 2. Pass the MSBuild properties into the task that creates the final orchestrated build manifest:
https://github.com/dotnet/arcade/blob/a4867b9af404b4b7ac96164db5b8347630760da2/src/Microsoft.DotNet.Build.Tasks.Feed/build/Microsoft.DotNet.Build.Tasks.Feed.targets#L177
https://github.com/dotnet/arcade/blob/a4867b9af404b4b7ac96164db5b8347630760da2/src/Microsoft.DotNet.Build.Tasks.Feed/src/BuildManifest/PushOrchestratedBuildManifest.cs#L49
 3. Include the value in the manifest by:
    * Adding a "fake" `Build` element in the manifest that relays the versioning properties via custom metadata.
      * No `VersionTools` changes necessary. Probably preferred as the MVP.
    * Adding the new properties/elements to the strongly typed model in `VersionTools`, ensuring an auto-updater can use them.

/cc @mmitche

**Comment by dseefeld** [comment]
Removing from the 2.1.3 Servicing epic, since that epic is complete and will be closed.

**Comment by markwilkie** [comment]
@mmitche - can you confirm that prodcon v2 eliminates the need for this?

**Comment by markwilkie** [comment]
Issue moved to [dotnet/core-eng #4129](https://github.com/dotnet/core-eng/issues/4129) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mmitche** [comment]
@markwilkie I think it does.  @dagood May have an opinion on this.

**Comment by dagood** [comment]
I think ProdCon v2 *will* eliminate the need for this, however, it's valuable in ProdCon v1 because we don't know how long it will take to get `release/2.1` servicing running on ProdCon v2.

Not having this causes the source-build product to be different from the ProdCon one. This can be fixed up for each release with a manual servicing maintenance step, but automation is obviously preferred.
