### ISSUE TITLE
[Maestro/Darc] Automate running of Maestro Scenario tests

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#2390]
We have a set of powershell scripts under https://github.com/dotnet/arcade-services/tree/master/src/Maestro/tests/Scenarios that test some end to end flows for Maestro, and can be configured to run on the Int or Prod service provided the right authentication.

These should be configured to run on automatically as part of the validation process for Maestro deployments.

**Comment by riarenas** [comment]
Current plan is to run these tests as part of the release pipeline that deploys Maestro++ and Darc.

* Run against INT Maestro at the end of an INT deployment to validate it
* Run against INT as a gate to the PROD deployment to avoid promoting a bad state of master
* Run against PROD at the end of a PROD deployment to validate the build

Also checking feasibility of rolling back the deployments if the tests fail.

**Comment by jcagme** [comment]
Have you measured the added time? Interested in know how much it'd take to deploy a change all the way to PROD

**Comment by riarenas** [comment]
The whole set of tests take about 6 minutes to run on average (the release pipeline runner only checks for completed pipelines every 5 minutes, so it depends on where in the 5 minute cycle you started running the tests)

**Comment by riarenas** [comment]
Int is already running the tests automatically.
The Prod release definition also has them set up to run, but will keep this around until we do an actual prod deployment that runs them.

**Comment by riarenas** [comment]
Tests ran during the production deployment: https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-environment-logs&releaseId=7210&environmentId=19344
