### ISSUE TITLE
Jenkins is needed by VS

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#2395]
We need to understand better what the needs are from VS and ensure those workloads are taken care of.

@ManishJayaswal

**Comment by chcosta** [comment]
FYI @mmitche

**Comment by rainersigwald** [comment]
The MSBuild repo used Jenkins for dev14 and dev15 CI. We can lose it for dev14 with no real problem since for us our "real" build was out of VS at that time. For 15, our official build definition is in devdiv, but CI and cross-platform testing is definitely desired for servicing fixes.
