### ISSUE TITLE
[darc/maestro++] Support publish to Bar without dependencies

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#2396]
NuGet would like to publish a build manifest to BAR, but doesn't have an `eng/version.details.xml` file because they're not on Arcade and not fully on dependency flow.  Instead, they want to make a direct call to the https://github.com/dotnet/arcade-services/blob/master/src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs task to publish to BAR. 

Today, that task requires the repo contain the `eng/version.details.xml` file or it will fail...

https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=2547634&view=logs&jobId=3f8ea73b-fc11-5621-9f8e-6da2aa02cf1b&taskId=ebcc4e3a-dfab-5658-905b-85dd65c63ce4&lineStart=16&lineEnd=23&colStart=1&colEnd=84

```
  Reading 'eng/Version.Details.xml' in repo 'E:/A/_work/1344/s' and branch ''...
##[error]build\publish.proj(62,5): Error : DirectoryNotFoundException: Could not find a part of the path 'E:\A\_work\1344\s\eng\Version.Details.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Microsoft.DotNet.DarcLib.LocalGitClient.<GetFileContentsAsync>d__7.MoveNext()
```

We should support teams like NuGet.

@riarenas @jcagme @mmitche

**Comment by mmitche** [comment]
Agreed. @ChadNedzlek @alexperovich This was added recently for the viz work, right?  In that case, we should just treat a missing eng/Version.Details as no inputs.

**Comment by alexperovich** [comment]
Yea the dependencies are needed for the bar visualization to work. We shouldn't just blindly ignore errors from the call to get dependencies. When this was first deployed corefx was failing because they weren't in the repo for some reason, If we had ignored the failure they would be reporting incorrectly without anyone knowing.

I would prefer if we required repos to be very explicit about wanting to report no dependencies. We should not allow repos to incorrectly report no dependencies and not get a build failure. Adding an empty Version.Details.xml is the most explicit we can be here.

**Comment by dtivel** [comment]
At least allow publishers to override the default, hard-coded path for eng/Version.Details.xml.

**Comment by chcosta** [comment]
I'm not sure I follow.  Isn't `eng/Version.Details.xml` about the dependencies that a repo consumes and is used via Darc?  ie, if a repo is using dependency flow for consuming dependencies, then it requires `eng/version.details.xml`, otherwise it isn't going to work and I'd expect some sort of error to surface.  If a repo is only publishing assets and not representing any dependencies which it consumes via dependency flow, then I'd expect not having this file would be an expected behavior.

**Comment by mmitche** [comment]
@alexperovich We could just also allow a specific parameter to the task indicating the missing version details file.

**Comment by ViktorHofer** [comment]
We also need this for ProjectN in DevDiv to publish to BAR. Any update?

**Comment by markwilkie** [comment]
I moved this to P7.  @mmitche - feel free to move again as appropriate.

**Comment by mmitche** [comment]
This shoudl be fixed because nuget.client is publishing to BAR
