### ISSUE TITLE
[darc/maestro++] Add new artifact type(s) to VersionTools manifest model

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2398]
Would it make sense to add some new artifact types to the [manifest model](https://github.com/dotnet/arcade/blob/505e38906e1ee2d032c41bb297de0958307db946/src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/ArtifactSet.cs#L12)? Or perhaps change this to make the artifact type as an attribute of the artifact.

Reason of the change is to make more clear what kind of artifact is being described in the manifest so we wouldn't have to resort to name pattern checking. Also, _I might be very wrong here_ looks like we are overloading the term Blob here to represent a lot of things like symbol packages, pdb, etc.

In talk with @mmitche and @jcagme we decided to change the Manifest format to be like below:

```xml
<Build ... >
  <Artifact Id="Microsoft.Foo.Bar" Version="1.0.0-beta.19203.8" NonShipping="true" Category="package" />
  <Artifact Id="Microsoft.Foo.Sdk" Version="1.0.0-beta.19203.8" NonShipping="true" Category="package,installer" />
  <Artifact Id="Microsoft.Foo.Tar" Version="1.0.0-beta.19203.8" NonShipping="true" Category="package,symbol" />
 </Build>
```

i.e., add new element under `Build` that can be used to describe any build artifact. This new element will have a property called `Category` that will tell which categories this artifact fits in - example of categories are MSI, package, symbol, installer, etc. A list of categories should still be discussed.

**Comment by dagood** [comment]
`Blob` is intentionally vague, it just means it's a file rather than something that exists by accessing a NuGet v3 package feed.

`Blob`s (and `Package`s) support custom metadata, no need to invent `Artifact` for this. You can also stay within XML by using `IsPackage="true"`, `IsInstaller="true"` etc. rather than coding your own delimiter.

Conventions for 2.1/2.2 are documented here: https://github.com/dotnet/core-eng/blob/master/Documentation/Orchestrated-Build/Api/publish.md#default-final-publishing-steps

**Comment by dagood** [comment]
Reason I'm here, by the way, is I'm wondering if this could be used to declare whether a specific package should go to the main feed or an AzDO feed (https://github.com/dotnet/arcade/issues/1788) or both.

Specifically, a CoreXT package will need to go to a VS feed but other packages the build produces still go to the main feed.

**Comment by tmat** [comment]
We'll need to have a uniform output location for CoreXT packages in Arcade SDK. Currently each repo places them in different directories, which makes it hard for the publishing logic to distinguish between CoreXT packages and regular nuget packages.

We should make CoreXT a first class concept and put them to `artifacts/packages/{config}/CoreXT`.

**Comment by dagood** [comment]
FYI @dleeapho @nguerrera, sounds like there are already some thoughts about CoreXT stuff.

**Comment by markwilkie** [comment]
Moving to P7.

**Comment by tmat** [comment]
Adding support for CoreXT packages: https://github.com/dotnet/arcade/pull/2535

**Comment by JohnTortugo** [comment]
> `Blob`s (and `Package`s) support custom metadata, no need to invent `Artifact` for this. You can also stay within XML by using `IsPackage="true"`, `IsInstaller="true"` etc. rather than coding your own delimiter.

I like the idea of attributes. Only concern is that if/when we need to add other artifact types we'll need to add a new attribute to the model. This kind of change doesn't seem quite frequent, though..

> Reason I'm here, by the way, is I'm wondering if this could be used to declare whether a specific package should go to the main feed or an AzDO feed (#1788) or both.

That is one of the reasons for creating this issue. Let me know if you have thoughts about #1788 as well.

**Comment by dagood** [comment]
> Only concern is that if/when we need to add other artifact types we'll need to add a new attribute to the model. 

Why would we need to do that? The custom metadata stuff I mentioned means you don't even need to change the model for the initial implementation. Maybe I'm misunderstanding what "the model" is?

**Comment by JohnTortugo** [comment]
I didn't know this was implemented like this: https://github.com/dotnet/arcade/blob/3296e345e110defac6eb4db60d3fa90e88f8a720/src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/BlobArtifactModel.cs#L34 I thought we had some Model/Schema for which properties were acceptable for each element.

**Comment by dagood** [comment]
Ah, yep. It was basically designed for this: new custom attributes can be added by anyone without needing to deploy any centralized changes, but the class model can also be changed to advertise specific "common" attributes via properties. This was to allow any repo to add extra publish steps triggered via dotnet/versions (although nobody outside core-eng ended up taking advantage of this).

Changing this approach is fine, just want to provide a background. 🙂

**Comment by mmitche** [comment]
This was fixed by the ability to add categories per artifact
