### ISSUE TITLE
Create plan to on-board repos to the async release pipelines process

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2408]
As we make progress supporting basic actions (signing, symbol validation, publishing) in the release pipelines we should plan which repos should move first to this new approach. There are repos which have their own custom way of publishing and others than do more things that the common publishing (VS insertion) so we could leave these at the end once we figure out what's the best way to serve all.

We can use https://github.com/dotnet/arcade/blob/master/Documentation/NetCore3EngineeringRepoStatus.md to create the plan.

By //build time frame we should have those repos using the "common" publishing already publishing from releases.

**Comment by JohnTortugo** [comment]
I think this got close by https://github.com/dotnet/arcade/pull/2429
