### ISSUE TITLE
Move BYOC provider to new repo

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2412]
The BYOC provider needs a full int/prod automated rollout and it makes sense to move it to a separate repo.  Reasoning:
- Arcade isn't meant for services (which is why arcade-services exists)
- Arcade-services is exclusively focused on Maestro/Darc. By overloading it, we end up having to either have separate branches for each prod, or rolling out both prods at the same time, which may not be desirable (aligns the bake time).

**Comment by markwilkie** [comment]
@mmitche - how closely is the provider tied to Helix?

**Comment by mmitche** [comment]
It's not really, it only lightly uses the JobSubmitter package.

**Comment by markwilkie** [comment]
@mmitche - I seem to remember this got done?

**Comment by mmitche** [comment]
Yep, done.
