### ISSUE TITLE
[darc/maestro++] Refactor dependency graph build functionality for readability

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2413]
Today the algorithm has a lot of internal state, a lot of it for performance reasons.  Refactor the algorithm for ease of readability.  Some options:
- Move state into class and make build method non-static
- Refactor into an event based model.

Ensure perf (e.g. coherency update) does not get slower.

**Comment by markwilkie** [comment]
@mmitche - Which business priority (epic) would you like this to live under?
