### ISSUE TITLE
Have core-sdk publish a dummy package with a stable asset name for dependency uptake.

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#2426]
Splitting this up from #811

https://github.com/dotnet/core-sdk/pull/1072 had to be reverted due to a build break.

Working with core-sdk folks to figure out best way to unblock this flow.

**Comment by mmitche** [comment]
@riarenas Did this get done?

**Comment by riarenas** [comment]
No. I expect to have a definitive answer from CLI team on how they want this implemented this week.

**Comment by mmitche** [comment]
Thanks

**Comment by riarenas** [comment]
The package is getting published, but it's also getting renamed to include the sdk version in the asset name...

`Sdk/3.0.100-preview6-011788/Microsoft.Dotnet.Sdk.Internal.1.0.0-preview.19257.4.nupkg`

**Comment by mmitche** [comment]
That looks like it's being published as a blob, not a package.

**Comment by adiaaida** [comment]
Adding a comment so I get notifications on this work.

**Comment by billwert** [comment]
@riarenas hi! Can you give us status on this? This is very important to us to be able to improve our granularity of perf testing. Would really like to have this working ASAP. Are there ways we can help?

**Comment by riarenas** [comment]
@billwert I'm testing changes to the core-sdk publishing process to make sure that this package in particular gets published as a package as opposed to a blob, which is the final blocker for this.

I expect the package to be available before the end of the week.

**Comment by riarenas** [comment]
Core-sdk is completely skipping the Arcade publishing targets, which means the assets are only getting published by their custom publishing.props targets. I validated that if I stop importing the props file, things go as expected.

Investigating how to get the two publishes to work well together.

**Comment by riarenas** [comment]
I found a few properties that core-sdk was not passing, or was overwriting during their own custom publishing that was causing Arcade to not publish the asset the correct way.

I ran https://dev.azure.com/dnceng/internal/_build/results?buildId=238922&view=logs&j=102d5a1b-a8ad-521f-40d1-7396fb503645 after modifying the build and the asset was finally published as a package that can be consumed by dependency flow.

I will atempt to create a PR tomorrow that reconciles both publishing logics while core-sdk fully adopts the yaml-based publishing after P7.

**Comment by riarenas** [comment]
PR to fix this in https://github.com/dotnet/core-sdk/pull/2656. Core-sdk is branching on Friday, and then it will be safe to merge. Placing in tracking until then.

**Comment by riarenas** [comment]
The caveat here is that the dummy package will have a different version from the version of the sdk that produced it. This should be a point in time problem while core-sdk completely adopts Arcade publishing and we unify the versioning scheme by both arcade, and core-sdk.

**Comment by riarenas** [comment]
PR has been merged. Keeping an eye out for the package to be published.

**Comment by adiaaida** [comment]
HOORAY!!!!!!!

**Comment by riarenas** [comment]
Confirmed that Microsoft.Dotnet.Sdk.Internal package is now being published to BAR with a stable name.
