### ISSUE TITLE
[darc/maestro++] Display update to sdk versions as part of Dependency update PR description

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#2427]
We should inform the repo that we're updating their sdk versions in the global.json in the PR description for dependency updates.

**Comment by riarenas** [comment]
Hmm, SDK updates are probably still a good reason to open a PR, not sure this should be done silently once we finish implementing the silent dependency flow.

**Comment by JohnTortugo** [comment]
@riarenas - do you mean the .net sdk (i.e., Microsoft.NET.Sdk), right? If the PR is going to update that it will show up in the list of updates. Is the issue to make the update more evident to the reader?

**Comment by JohnTortugo** [comment]
PIng

**Comment by riarenas** [comment]
Nope, that's not it. It's when an Arcade update bumps the version of the sdk in the global.json.

See https://github.com/dotnet/arcade-validation/pull/1292. There's no indication that this was part of the PR.
