### ISSUE TITLE
[Arcade-Services] Tests for Arcade dependency updates

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#2428]
We do enough special logic with arcade dependency updates that we should have some testing in place to verify that Arcade updates:

* Flow the eng/common folder
* Flow the version of dotnet for the repo to buil if it's older than what Arcade is using
* Updates assets produced by Arcade (Can just be part of the general dependency flow testing)

**Comment by jcagme** [comment]
Ia the special logic around determining if we are working on Arcade updates?

**Comment by riarenas** [comment]
The special logic are the first two things on the list. We don't perform similar operations whenever any other repo is flowing dependencies, so we should have a case where we specifically test arcade dependency updates and verify that they do these extra steps that we want them to do.
