### ISSUE TITLE
Need to adjust OSX package signing build definition publishing path

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2432]
Here are the latest drops as an example:

Latest SDK - https://dotnetcli.blob.core.windows.net/dotnet/ **Sdk/3.0.100-preview4-011034/**
Latest macsign sdk - https://dotnetcli.blob.core.windows.net/dotnet-private/macsign/ **DotNet%20Core%20SDK%20(Official)/20190403.3/**

Latest Runtime - https://dotnetcli.blob.core.windows.net/dotnet/ **Runtime/3.0.0-preview4-27603-11/**
Latest macsign runtime - https://dotnetcli.blob.core.windows.net/dotnet-private/macsign/ **dotnet-core-setup/20190403.11/**

The highlighted sections should be identical so that any automation (or manual discovery) simply needs to be pointed to a different endpoint and will otherwise work the same.

**Comment by JohnTortugo** [comment]
@leecow I made the changes to the build definition. I'll keep the issue open for sometime so I can confirm things are working smoothly.

**Comment by leecow** [comment]
Thanks - I'll have a look at the build output tomorrow.

**Comment by JohnTortugo** [comment]
Ping @leecow

**Comment by leecow** [comment]
Drop structure looks good. Next steps are to enable on the 3.0 release branches. 2.1/2.2 have also been mentioned and should be enabled before too long. 

/cc @vivmishra

**Comment by JohnTortugo** [comment]
Tracking the other branches validation here: https://github.com/dotnet/arcade/issues/2612
