### ISSUE TITLE
Builds occasionally fail with licenseUrl complaint

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#2436]
There are builds failing with licenseUrl complaints intermittently. We should investigate and figure out why.

Example: https://dev.azure.com/dnceng/public/_build/results?buildId=159659

cc / @alexperovich

**Comment by tmat** [comment]
Where is it still set? It has been removed in https://github.com/dotnet/arcade/pull/2003.

**Comment by markwilkie** [comment]
@jonfortescue ?

**Comment by jonfortescue** [comment]
When I filed this, I was seeing consistent failures due to this in arcade-minimalci-sample. I am no longer seeing those, so it is likely this has been fixed.

**Comment by jonfortescue** [comment]
Reopening bc I found this happening again. It's intermittent and I'm not sure what the cause is so renaming accordingly.

**Comment by riarenas** [comment]
Where are you still seeing this?

**Comment by jonfortescue** [comment]
Edited the OP to include an example. Specifically I've been seeing it in arcade-minimalci-sample.

**Comment by riarenas** [comment]
The logs for that build are gone 😭

**Comment by jonfortescue** [comment]
:') that was fast. I'll screenshot next build I see with it.

**Comment by markwilkie** [comment]
@jonfortescue - let us know if you see this again.  Closing given that it's been 21 days...
