### ISSUE TITLE
Update recommended pools in AzureDevOpsOnboarding.md

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#2437]
https://github.com/dotnet/arcade/blob/dd7a71fd30b8514c74465a812721c39f497d0e57/Documentation/AzureDevOps/AzureDevOpsOnboarding.md#L55-L69

Would be nice to be able to point to a doc, I think I've only seen the BYOC info in email.

/cc @MattGal @mmitche

**Comment by MattGal** [comment]
Good point.  I'll take this one on.

**Comment by MattGal** [comment]
@dagood  - I did a dumb thing trying to edit via the web UI and ended up committing what I was trying to make a PR out of directly to master.  Can you review that and reactivate this issue if you have concerns?

**Comment by dagood** [comment]
Looks good to me, thanks for the update!
