### ISSUE TITLE
GenAPI should support the 'readonly members' feature

### ISSUE THREAD

**Issue by tannergooding** [dotnet/arcade#2453]
GenFacades should be updated to support the new `readonly members` feature and appropriately update the reference assemblies to include the `readonly` keyword rather than preserving the `[IsReadOnly]` attribute (which results in a compilation error).

**Comment by tannergooding** [comment]
CC. @ericstj

**Comment by tannergooding** [comment]
(this is similar to the `readonly struct` feature, but for individual members of a non-readonly struct).

**Comment by ericstj** [comment]
Can you elaborate? GenFacades doesn't do anything with members it just generates type forwards.  /cc @Anipik

**Comment by Anipik** [comment]
I think he may be refering to GenApi tool

**Comment by tannergooding** [comment]
> I think he may be refering to GenApi tool

Probably, I can never keep which tool does what straight in my head 😄 

I'm specifically referring to whichever of the tools can be used to generate and validate the various `ref assemblies` we have in CoreFX.

**Comment by ericstj** [comment]
Generate source is GenAPI.  Validate refs is API Compat.  Please feel free to submit a PR for this if you're blocked.
