### ISSUE TITLE
[Darc] VSTS REST APIs

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#246]
Currently Darc has the ability to create PRs in GitHub using the GitHub REST APIs.
Darc needs to do the same for VTSTS.

Documenation: https://docs.microsoft.com/en-us/rest/api/vsts/git/?view=vsts-rest-4.1

Considerations: Token manipulation for both endpoints. Whill the user/Maestro++ has to know the context of the repos in play so it provides the correct token?

@jcagme

**Comment by jcagme** [comment]
I'm done with some of the functions in VSTS. The things which are not ready are currently throwing `NotImplementedException` in the file `src\Microsoft.DotNet.Darc\src\DarcLib\Helpers\VstsClient.cs`

**Comment by dagood** [comment]
This should be implemented in VersionTools since it's not part of the prototype.

**Comment by maririos** [comment]
@dagood we started working on the VSTS side as part of the prototype, to see if it was possible to do the same thing we were doing in GitHub.

Once we clean the code and start working on V1, VersionTools sounds like the correct folder.
