### ISSUE TITLE
[darc/maestro++] Add flow issue detection tools

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2477]
Add tooling to detect the following:
- When a graph has a hard cycle, which is cycle that is not broken by a toolset dependency
- When multiple channels map to the same branch (this can potentially be valid, but should be warned on)
- Heuristically detect when graph is likely to cycle forever:
  - Graphs with non-hard cycles (broken by toolset dependency) where all subscriptions enabled and update regularly.
  - Detect cases where cross-channel flow can likely produce unwanted changes (e.g. .NET Tools - Latest flows into .NET Core 3 Release).

We should probably warn on:
- BARvis /cc @alexperovich 
- Darc get-dependency-graph

**Comment by riarenas** [comment]
@mmitche think this this is needed by P5?

**Comment by mmitche** [comment]
@riarenas Yeah I think so.  I think some of this can be pretty simple

**Comment by mmitche** [comment]
This is already done with the current get-health commands
