### ISSUE TITLE
Automate push 2.1/2.2 servicing builds into open

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2482]
When we do internal builds of 2.1/2.2 for servicing, we need to push their info into the open so that the Maestro automation runs. This should be automated.  Steps are:

1. Modify manifests in assets\orchestration-metadata to look like "open" manifests (e.g. branch names, feed urls)
2. Copy flatcontainer and assets directories from internal build to open build directory.
3. Run appropriate orchestrated build definition with correct product build id set, isstable=true, appropriate versions repo path, and Final-PushOrchestratedBuildManifest as the pipebuild root.

**Comment by jcagme** [comment]
Given that this is 2.1/2.2 and the work we are doing focuses mainly in 3.0, does it make sense to move this to the https://github.com/dotnet/arcade/issues/2935 epic?

**Comment by mmitche** [comment]
This is completed.  See new docs in the 2.1 and 2.2 servicing documents.
