### ISSUE TITLE
Add support for mimicking source-build locally and in CI.

### ISSUE THREAD

**Issue by brettfo** [dotnet/arcade#2491]
F# currently has source-build scenarios enabled for CI via the following tweaks:

- [yaml definition](https://github.com/Microsoft/visualfsharp/blob/08daf6d5a0abb62c01a475ea442c2996b0e79335/.vsts-pr.yaml#L159-L172)
- [properties workaround](https://github.com/Microsoft/visualfsharp/blob/08daf6d5a0abb62c01a475ea442c2996b0e79335/FSharpBuild.Directory.Build.props#L72-L85) by setting:
  - `$(DeterministicSourcePaths) = false`
  - `$(RepositoryType)`
  - `$(RepositoryUrl)`
  - `$(RepositoryCommit)`

**Comment by tmat** [comment]
FWIW - i'm working on making SourceLink buildable from source, which should help address some of these.

**Comment by markwilkie** [comment]
Being driven through the source-build repo/team
