### ISSUE TITLE
[BARviz] Sometimes view doesn't show all repos

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2503]
![image](https://user-images.githubusercontent.com/8725170/55966095-a51d7b80-5c2c-11e9-831b-b3a07a9d2c91.png)

Occasionally I don't see all repos (e.g. core-setup is missing here, from .NET Core 3 Release"

@dougbu I think this was what you were seeing.
@mjanecke @alexperovich Any ideas?

**Comment by mjanecke** [comment]
@alexperovich noticed that there were five channels that were deleted in the last 24 hours (we don't know which ones, however).

**Comment by mjanecke** [comment]
Determined that the "missing" repos are not available in the Default Channels list. Created #6002 to handle expanding the list of repos in BARViz to beyond just Default Channels.
