### ISSUE TITLE
[Release pipelines] When opening an issue related to a failed release tag known repo owners instead of last committers

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2508]
We've gotten several requests to use known "static" users on release failures per repo. This make sense since tagging the last committer might lead to confusion and to the start of long threads explaining the logic behind it.

We'd need to create a map of repo <=> owners so we get the owners keyed by repo. I'd persist this out from the runner code, either on DB or on a file part of the repo so we can do modifications to it without needing a full deploy for things to go into action.

It would also be good to have an on/off switch that we can toggle in case we don't want to file issues. i.e. there might be a bad outage causing releases to fail so we'b be opening a bunch of "false" issues.

/cc: @JohnTortugo @dougbu

**Comment by JohnTortugo** [comment]
My plan was to investigate supporting these customizations in the scope of these issues: https://github.com/dotnet/arcade/issues/2417 and #2370

**Comment by jcagme** [comment]
Yeah that is also an option. Still we'd need to persist the mapping somewhere as we currently do for artifact categories, but yeah this is a good option.

**Comment by dougbu** [comment]
As mentioned in a recent conversation, the sooner we can _disable_ notifying the last committer the better. The current state is in some ways worse than nobody getting notified.

/cc @JunTaoLuo @natemcmaster

**Comment by JohnTortugo** [comment]
I'll work on it today.

**Comment by JohnTortugo** [comment]
PR for disabling notifying the committer: https://github.com/dotnet/arcade-services/pull/337

**Comment by jcagme** [comment]
When we have moved to the new staged worlds, users will be able to see failures in the pipeline itself and would get notification of a failure so no need to tag owners, etc.
