### ISSUE TITLE
Permit defining multiple sdks

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#2509]
We are working to enable defining multiple .NET runtimes in Arcade which can be used for testing.  We should also consider if there is a way to extend the model to support defining multiple sdk's.

https://github.com/chcosta/arcade/commit/737e29378f2a8596f6ceec1f378beea2a7b0ba0b#r33153182

**Comment by markwilkie** [comment]
https://github.com/dotnet/arcade/issues/1441
