### ISSUE TITLE
Validate of Source Link of Portable PDBs

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2512]
For more context see the discussion here: https://github.com/dotnet/arcade/issues/1873

Builds of Arcade onboarded repos convert Portable PDBs to Windows PDBs during the build itself. We should validate that Source Link information of PDBs. It's easier to do that on Portable PDBs, since we can rely on [source link cli](https://github.com/ctaggart/SourceLink). This issue is to perform this validation.

**Comment by JohnTortugo** [comment]
> We should do the validation on Portable PDBs during publishing. We should also check during publishing that all managed binaries that are being published have Portable or Embedded PDBs.

@tmat - so you mean I should make the Portable PDBs and the windows PDBs available for the publishing step and then perform validation on Portable PDB but publish the Windows PDBs? I'm OK with that, I'm just confused if I should make the two sets of PDBs available for the release pipeline.

**Comment by tmat** [comment]
We should be always publishing both Portable PDBs and the converted Windows PDBs.
we can validate SourceLink in Portable PDBs now and in Windows PDBs later.

**Comment by JohnTortugo** [comment]
Thanks Tomas. Two more questions:

- From @danmosemsft message on the other issue I got the impression that the only validation necessary is for the links to be pointing to _a_ GitHub repo. Is that all I've to check? 
- What if a 3rd party DLL in the package have source link information pointing to some non-public servers (i.e., not GitHub)? How can I decide which DLL I should validate?

**Comment by danmosemsft** [comment]
> Is that all I've to check?

You should check the links resolve..
