### ISSUE TITLE
[darc/maestro++] Advanced flow control

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2518]
With the increased rate that dependencies can now flow through our systems via Maestro/Darc, we have some new challenges that have arisen:
- When coherency is desired, the coherency QB (CQB) must analyze sources of potential incoherency and carefully adjust default channels, subscriptions, etc. or risk inadvertent introduction of new changes into the graph late in release cycles.
- Potential sources of incoherency cannot be automatically determined
- It is riskier for the CQB to let repo owners produce outputs from any branch than to force everyone to branch. This violates one principle of Prodcon v2, which is that repository owners have control over the 'intent' of their builds.

A typical example is 'cross channel flow'.  In cross channel flow, a channel with a higher actual rate of change flows into a channel with a lower desired rate of change.  The higher rate channel effectively forces the lower rate channel to match its rate. Specifically, let's say symreader-portable decides that .NET Core 3 preview 6 is being produced out of the master branch.  Because master regularly takes updates from arcade, and .NET core preview 6's channel (.NET Core 3 Release) is set up for flow on every new build, every new update to arcade will make it into symreader and then into the .NET Core 3 release channel, risking incoherency.  The CQB could recognize this case, remove the default channel association for symreader, and manually flow only the changes that matter from symreader, but this requires a good deal of care to get right and introduces the possibility that a change that a dev checks in and believes is in the product will never got propagated.

What we need is a way to put a channel in "approval mode".  That is, only those changes that are "approved" will flow automatically, *and* those change that are approved will flow automatically to completion.  So, for instance, if PR 12000 is approved in symreader, and merged, then that commit will flow through all subscriptions, and all downstream subscriptions/branches that pick up that commit via dependency flow are also automatically approved.

I envision such an approval mode as simply a check on a PR (GH or AzDO). The check is failed or pending when not approved, then green when approved. This would be implemented as a GH app connected to some kind of backend datasystem

This could also be used in shiproom.  Today we use a tagging system to denote approved fixes. This tagging system is a little loose at best.  With an app, we could approve changes for a future release, with appropriate metadata (which release, etc.). Only these fixes would flow, and they would automatically flow to their eventuality with as little intervention as possible.  I also envision some features you could implement with this:
- Since "branch opening" dates tend to be fairly well defined, we could force "approved fixes" to remain unmergeable (failed check) until which time the branch opens, at which point all fixes approved for the next release would go green.
- We could easily track status of approved fixes across repos and orgs, ensuring that we don't miss fixes.
- We could add metadata not easily represented in the current tagging system, like "affected packages" which could then be fed into Maestro to ensure that the desired packages were actually produced (for those repos that have incremental servicing)

@natemcmaster @leecow @vivmishra @ericstj Thoughts?

**Comment by natemcmaster** [comment]
Sounds like a good problem to solve. If we can make GitHub PR approvals integrate well with dependency flow, awesome. On principle, I like the idea of having GitHub reflect our actual process for approving changes. I think that should be true for all pull requests, regardless of whether the PR author is a bot or human.

**Comment by mjanecke** [comment]
This feature depends on https://github.com/dotnet/core-eng/issues/7053
