### ISSUE TITLE
Need API to read SourceLink information from Windows PDBs

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2519]
Issue originated after discussion on this other issue: https://github.com/dotnet/arcade/issues/1873

It's what the title say. We need a tool that can read SourceLink information from Windows PDBs. See messages from @tmat below for better context.

From @JohnTortugo [here](https://github.com/dotnet/arcade/issues/1873#issuecomment-482622319): 
> AFAIU right now [sourcelink cli tool](https://github.com/ctaggart/SourceLink) can only handle Portable PDBs and the PDBs that we have during publish/release are Windows PDBs. I'm still investigating.

From @tmat [here](https://github.com/dotnet/arcade/issues/1873#issuecomment-482723953): 
> I don't think we have the necessary APIs in Microsoft.DiaSymReader/Native to read native source link data (they are stored in a different stream within the PDB than managed ones). No problem adding those APIs it's just work. 
> 
> So I suggest we separate validation of Source Link Portable PDBs and native (C++ generated) PDBs. Let's make sure our Portable PDBs are good first and later on we can add validation of native PDBs.

**Comment by jcagme** [comment]
Hey @JohnTortugo what's the latest here? Is this required for your work to be completed by end of June?

**Comment by JohnTortugo** [comment]
This is not a blocker for publishing itself. It's a blocker for how complete our validation process is: currently our source link validation is only performed in Portable PDBs. 

I don't think this is a blocker for P6/P7 .  @mmitche , @markwilkie for awareness

**Comment by jcagme** [comment]
Given that works only on portable PDBs could we safely say that things were validated? What's the risk of not validating Windows only PDBs?

**Comment by JohnTortugo** [comment]
I think the Windows PDB's are mostly from building C++ sources. @tmat can answer that question better.

**Comment by tmat** [comment]
The only concern imo is PDBs built by C++.

**Comment by riarenas** [comment]
Moving to the ringed releases epic.

**Comment by adiaaida** [comment]
Out of scope for #6418.

**Comment by jakubstilec** [comment]
[Async Triage]: @adiaaida where this should go when it was removed from #6418?

**Comment by markwilkie** [comment]
@mmitche - wondering if we should/could close this one too....

**Comment by MattGal** [comment]
[Async Triage]: I favor closing the issue; if someone cares the issue would need to be in https://github.com/dotnet/sourcelink anyways.

**Comment by jakubstilec** [comment]
[Async Triage]: no objection to close it
