### ISSUE TITLE
[Maestro] Maestro publishing APIs/manifest dropping asset location information

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2521]
The location information for assets appears missing as of late.

@JohnTortugo Any ideas on this?

/cc @riarenas This is something that we need to validate. I think it should be done in two places:
- In the new E2E testing scripts, ensure that location info is preserved on BAR publish
- In arcade-validation, we could use darc to run "gather-drop" on the input arcade build, then validate that the output drop contains all of the correct bits.

**Comment by JohnTortugo** [comment]
I'll look into it today

**Comment by mmitche** [comment]
@JohnTortugo Did you have a fix for this?  I don't to cause Preview 5 issues because of this.
