### ISSUE TITLE
Switch partners to prod pool providers

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2522]
The prod pool providers are now live.  Users can switch to them by changing:

- **NetCoreInternal-Int-Pool** to **NetCoreInternal-Pool**
- **NetCorePublic-Int-Pool** to **NetCorePublic-Pool**

arcade-validation should remain on Int.

**Comment by MattGal** [comment]
@mmitche seems reasonable, were you thinking as an FR activity?

**Comment by mmitche** [comment]
@MattGal Wasn't quite sure.  Maybe a combo of a partners mail and an FR mop up?

We should be able to tell using the new telemetry jobs that have not switched.

**Comment by markwilkie** [comment]
Moving to FR to be triaged.

**Comment by markwilkie** [comment]
Issue moved to [dotnet/core-eng #6291](https://github.com/dotnet/core-eng/issues/6291) via [**ZenHub**](https://www.zenhub.com/)
