### ISSUE TITLE
[Maestro] ReleasePipelineRunner ProcessFinishedReleasesAsync crashes if any of the channels that it is trying to insert builds into has been deleted

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#2529]
Found this one while automating the scenario tests:

It is possible for a channel to be deleted while a release is running. Then, once the release finishes, and the `ProcessFinishedReleasesAsync` scheduled task tries to insert a build into the now deleted channel, the whole task crashes, meaning that no builds will be added to any channel via a release pipeline, and dependency updates won't trigger. The Staging Release Pipeline runner is stuck in this state right now.

The fix should be to check if a channel still exists before attempting to add it to the list of entities that we'll try to persist here: https://github.com/dotnet/arcade-services/blob/master/src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs#L288

FYI @JohnTortugo @jcagme

**Comment by jcagme** [comment]
https://github.com/dotnet/arcade-services/pull/342

**Comment by riarenas** [comment]
Thanks! this unblocked my validation as soon as it made it to int :)
