### ISSUE TITLE
Restore mechanism for overriding package versions

### ISSUE THREAD

**Issue by crummel** [dotnet/arcade#2532]
In https://github.com/dotnet/arcade/pull/537 / https://github.com/dotnet/arcade/pull/537/commits/ac4c48cce4bbb1f626d6b160ef8978e126ab8d45, `DotNetPackageVersionPropsPath` was removed as a way to override package versions.  While this is correct in the long-term after we solve the coherency problems, in the short-term source-build still needs a mechanism to override these package versions (especially since release/2.1 and release/2.2 will probably not end up fully converted to be using the new coherent build process).  It seems like the easiest way to do this would be to add importing `DotNetPackageVersionPropsPath` in [DefaultVersions.props](https://github.com/dotnet/arcade/blob/6c05c3404b4535f66e2e6701f2ebc8a5ae29416a/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L101) below the Versions.props imports and all other package versions being set.  Does that sound like a reasonable approach?  Would we want it guarded by `DotNetBuildFromSource=true` so people can see it's not for general use?

**Comment by crummel** [comment]
cc @tmat

**Comment by tmat** [comment]
We already import `DotNetRestoreSourcePropsPath` here: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L103

Since this is supposed to be a temporary workaround, could source build overwrite the versions in that file (or import another .props file in that file)?

**Comment by tmat** [comment]
Accidentally closed.

**Comment by crummel** [comment]
That should probably work, I will give it a try.

**Comment by crummel** [comment]
This seems to be working fine for now.  Thanks!
