### ISSUE TITLE
GenerateReferenceSource should follow type forwards so we can update based on changes to S.P.Corelib

### ISSUE THREAD

**Issue by tannergooding** [dotnet/arcade#2540]
It appears as though running `/t:GenerateReferenceSource` does not currently pick up that the actual sources live in `S.P.Corelib` (or another assembly) but are exposed as part of a given projects `ref` assembly.

We should likely follow the `TypeForward` and use `System.Private.Corelib` to validate the exposed surface is up to date.

**Comment by tannergooding** [comment]
I imagine this might require some logic to dictate which types are meant to be exposed by a given reference assembly and it might require some logic to indicate when individual members are explicitly not exposed.

However, I think having this explicitness might help automate `GenerateReferenceSource` in the future.

**Comment by tannergooding** [comment]
CC. @ericstj, @ahsonkhan

**Comment by ericstj** [comment]
> to dictate which types are meant to be exposed by a given reference assembly 

That's already defined by the typeforwards in the src assembly that GenerateReferenceSource operates on.

> indicate when individual members are explicitly not exposed

GenAPI supports exclusions. https://github.com/dotnet/arcade/blob/5c40ffc8d160681c1ff39f69ec8fd893795bd520/src/Microsoft.DotNet.GenAPI/Program.cs#L42

**Comment by markwilkie** [comment]
Anything more to do here @tannergooding ?

**Comment by tannergooding** [comment]
No, I think this can be closed.
