### ISSUE TITLE
[darc/maestro++] Enable pinging of users on failed PR checks

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2541]
When a PR check fails on an update PR, we should have the ability to ping a set of users to take a look (and not ping otherwise).

/cc @natemcmaster

**Comment by riarenas** [comment]
I think this might fit with the new dependency flow where we'll only open PRs when attention is required.

Can probably make this a field that can be set during subscription setup?

**Comment by riarenas** [comment]
Given that in the near future PRs will only be opened when there is some manual intervention required, we don't believe there's value in making explicit pings to a list of people that could get out of date very quickly. Every Dependency update PR using the new flow should be given attention.
