### ISSUE TITLE
[darc/maestro++] Add tests for flowing internal/stable build feeds

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2545]
1. Come up with a proposal for how feed urls and blob storage urls are updated in repositories as we flow dependency versions. The requirements are:
  - Feed urls are 'trimmed' to remove urls no longer interesting
  - Blob storage urls (e.g. dotnetcli.blob.core.windows.net/dotnet) are flowed also
  - Flowed based on the location of assets.

2. Implement and roll out plan.

**Comment by mmitche** [comment]
We believe this work has been completed for stable/internal builds.

**Comment by riarenas** [comment]
Looks like this was meant to be closed? @mmitche feel free to reopen if there was some work missing here.
