### ISSUE TITLE
[Maestro/Darc] Maestro doesn't recognize the merge policy created by darc add-subscription --require-checks

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#2547]
See: https://dev.azure.com/dnceng/internal/_git/maestro-test2/pullrequest/980?_a=overview

The subscription was created with the `require-checks` option, but Maestro doesn't understand what that merge policy means.

**Comment by riarenas** [comment]
Since no repos are using this merge policy, and it's a more common scenario to want all checks to succeed with some exceptions, should we just look into removing this merge policy?

**Comment by markwilkie** [comment]
@mmitche - thoughts?

**Comment by mmitche** [comment]
We should remove it...I think @riarenas may have already fixed this up.

**Comment by markwilkie** [comment]
@riarenas  - any update?

**Comment by riarenas** [comment]
Sorry. Missed this mention. The require-checks policy was removed as it wasn't very useful and no one was using it. THis is no longer an issue.
