### ISSUE TITLE
[darc/maestro++] Update darc to support sdk.version

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#2548]
Darc updates the version of the sdk used in a repo based on the version specified by global.json in Arcade.  It is likely that we are going to move from specifying the sdk version as 

```json
"tools": {
  "dotnet": [version]
}
```

to the CLI supported format of 

```json
"sdk": {
  "version": [version]
}
```

if this is not fixed, then the update feature will be regressed

See discussion [here](https://github.com/dotnet/arcade/pull/2343#discussion_r275938922) and the CLI proposal linked there

**Comment by tmat** [comment]
I'd just want to emphasize that this change can only be made in our repos once the CLI proposal is implemented and all our repos update to a dotnet version that has it implemented.

**Comment by markwilkie** [comment]
@chcosta and @riarenas - once https://github.com/dotnet/arcade/issues/2426 is done and rolled out, are we ready for this?

**Comment by riarenas** [comment]
No, this actually shouldn't require #2426, but it will require a small change to Maestro++ so that we stop looking at the `tools.dotnet` property, and look at `sdk.version` instead when determining the sdk version to flow from Arcade.

This wasn't on my radar, but it shouldn't be a big change to support the current state of things, and be prepared for the change once we're ready to do it in Arcade.

**Comment by mmitche** [comment]
This should be done before arcade does any work on this.

**Comment by mmitche** [comment]
@chcosta Is this still a thing that should be done?

**Comment by chcosta** [comment]
This is a thing that **can't** be done at this time.  This should only be done if Arcade updates that CLI has established to be used in [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json#globaljson-schema).  I don't think there's any current WIP or driving factor which is moving Arcade to support that standard.  For now, this can probably be closed.

**Comment by mmitche** [comment]
Okay thanks
