### ISSUE TITLE
Have a main off switch for async release publishing

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2554]
Let's say there is major outage on AzDo release pipelines and we are one day ahead of shipping and we need packages to be published. Today, the backup plan would be to go to each repo and change `_PublishUsingPipelines` to false. This would take time between making the change and getting it merged, etc.

We should have a config-like file in `eng/common` so all repos get it where we define whether we should use the things defined in the YAML or we should override what the YAML defines and just go the "previous" way.

/cc: @JohnTortugo @mmitche

**Comment by JohnTortugo** [comment]
I think this can be implemented as part of this one: https://github.com/dotnet/arcade/issues/2371 where we would have a "PublishingConfig.props" or something, and that file would include a property that can override the decision of _PublishUsingPipelines. This config file would be delivered by Maestro.. which would still require a PR...

**Comment by JohnTortugo** [comment]
> We should have a config-like file in `eng/common` so all repos get it where we define whether we should use the things defined in the YAML or we should override what the YAML defines and just go the "previous" way

This will still require a PR.. though a potentially automatically mergeable one.. which I think is better than nothing..

Other option would be to just go to the build-definition and override PublishUsingPipelines ..?

**Comment by jcagme** [comment]
PRs would be always required. If we decided to use the switch we'd merge the chane in Arcade and trigger all Arcade subscriptions so this change gets to all repos.

**Comment by riarenas** [comment]
If a PR is always required, isn't it enough to change this line to be false?

https://github.com/dotnet/arcade/blob/626977542214f3ffac08c1cc61434ed5a56a97b1/eng/common/templates/job/publish-build-assets.yml#L58

**Comment by JohnTortugo** [comment]
This line actually: 

https://github.com/dotnet/arcade/blob/626977542214f3ffac08c1cc61434ed5a56a97b1/azure-pipelines.yml#L21

**Comment by JohnTortugo** [comment]
Also, I thought the feature would be opt in just for some time. After a while it would be the default and no fallback mechanism would exist. Did that change?

**Comment by riarenas** [comment]
Won't that just change how Arcade publishes?

I thought the idea was a kill switch for the feature for emergencies that we could change in Arcade, and then flow to all repos.

**Comment by jcagme** [comment]
I think what @riarenas proposes is a great quick fix. @JohnTortugo the one you propose wouldn't flow to other repos and it will still need to be changed in all repos manually.

> Also, I thought the feature would be opt in just for some time. After a while it would be the default and no fallback mechanism would exist. Did that change?

Nothing has changed from the design, remember this is a fallback "OMG we'll all die" sort of a emergecy thing

**Comment by JohnTortugo** [comment]
> Won't that just change how Arcade publishes?

Yeah, that was just an example. Changing just the template also won't resolve since Publish.proj uses a same named parameter that come from a different input. But we could use the same idea and just change the SDK to ignore the PublishUsingAsync parameter

**Comment by jcagme** [comment]
Also, I think @riarenas referred to do a change like: `/p:PublishUsingPipelines=false` where we don't set any variable but literally set `p:PublishUsingPipelines` to `false`.

**Comment by jcagme** [comment]
I'm closing this since eventually we'll move all repos to stages and everything (build + publishing) will happen in the same pipeline
