### ISSUE TITLE
GenAPI generates invalid C# 

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#2555]
This change to Microsoft.Cci.Extensions is breaking the GenAPI tool for aspnetcore: https://github.com/dotnet/arcade/pull/2526

For instance, regenerating our reference assemblies with the latest GenAPI tool produces output like this:

```C#
@@ -352,9 +352,9 @@ namespace Microsoft.AspNetCore.Components
     {
         private readonly object _dummy;
         private readonly int _dummyPrimitive;
-        public bool Cascading { [System.Runtime.CompilerServices.CompilerGeneratedAttribute]get { throw null; } }
-        public string Name { [System.Runtime.CompilerServices.CompilerGeneratedAttribute]get { throw null; } }
-        public object Value { [System.Runtime.CompilerServices.CompilerGeneratedAttribute]get { throw null; } }
+        public readonly bool Cascading { [System.Runtime.CompilerServices.CompilerGeneratedAttribute]get { throw null; } }
+        public readonly string Name { [System.Runtime.CompilerServices.CompilerGeneratedAttribute]get { throw null; } }
+        public readonly object Value { [System.Runtime.CompilerServices.CompilerGeneratedAttribute]get { throw null; } }
     }
```

This does not compile. ❗️ 

Context: https://github.com/aspnet/AspNetCore/blob/b9e600a45c5a56f869f12dda6242ef069bd2f9dc/src/Components/Components/ref/Microsoft.AspNetCore.Components.netstandard2.0.cs#L350-L358

cc @tannergooding @ericstj

**Comment by tannergooding** [comment]
This is valid code in C# 8; there is likely a disconnect in what your reference sources and implementation is being compiled with.

**Comment by tannergooding** [comment]
CC. @RikkiGibson, however. Is it expected that `IsReadOnlyAttribute` is being applied to members of a `readonly struct`? I had thought this was only for members of non-readonly structs....

**Comment by tannergooding** [comment]
Ok, I think I understand the problem after talking to @RikkiGibson offline.

The latest compiler is emitting the `[IsReadOnlyAttribute]` on get-only auto properties even if don't target 8.0. However, the update I made was not expecting to see the attribute unless the implementation was actually compiled targeting C# 8...

I don't think we have a way to detect what target framework version a reference assembly was compiled against, so I don't think there is an easy way to workaround this...

**Comment by ericstj** [comment]
You can pass in LangVersion to GenAPI and constrain this against that value.

**Comment by markwilkie** [comment]
Is ASP the only team so far that's hitting this?  I'm wondering if the change needs to be backed out of Arcade...

**Comment by natemcmaster** [comment]
@markwilkie I would be interested to know which version of the .NET Core SDK is used by other teams. We ran into this one in the process of updating from .NET Core SDK from 3.0 Preview 3 to Preview 4.

**Comment by markwilkie** [comment]
ah - yes.  I'm pretty sure that's all over the map right now.  There's https://github.com/dotnet/arcade/issues/811 which should get turned on soon which *should* allow for better consistency across the stack.

**Comment by tannergooding** [comment]
I've got a PR up here: https://github.com/dotnet/arcade/pull/2560
