### ISSUE TITLE
[Darc] Support for enabling;/disabling of default channels

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2558]
Darc support for enabling/disabling of default channels.  Depends on #1925

**Comment by jcagme** [comment]
Adding this here after in person conversation. It would be nice to add fields/tables where we keep when things changed. For example, when we delete a DefaultChannel and things stop flowing, if someone doesn't know that this was done it could take a while to find that the channel was removed, but if we had some sort of bookkeeping then changes like these would be easily tracked.

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade/issues/2559
