### ISSUE TITLE
Joining DARC repo

### ISSUE THREAD

**Issue by fuocor** [dotnet/arcade#2563]
The documentation indicates that we need to go to here to join the team needed to use darc.
Unfortunately it goes nowhere.

**Comment by fuocor** [comment]
The documentation indicates that we need to go to [here](https://github.com/orgs/dotnet/teams/arcade-contrib/members) to join the team needed to use darc.
Unfortunately it goes nowhere.

**Comment by jcagme** [comment]
Hey @fuocor thanks for reaching out. Could I ask two questions:
* What document brought you here?
* What scenarios are your trying to cover by using darc?

**Comment by fuocor** [comment]
I have a large distributed application that I am trying to sync with netcoreapp3.0.

the Darc.md and DependencyFlowOnboarding.md both refer to it as step 1.

**Comment by markwilkie** [comment]
Hi @fuocor - any chance I could understand better your scenario?  We'd love to help and want to make sure we're understanding what you need.

**Comment by fuocor** [comment]
I have an geo-distributed IoT application with a situational awareness dashboard as front-end. The IoT devices communicate through socket gateway to an Orleans backend hosted in Service Fabric. 

My CI build involves Orleans as a source dependency because their Service Fabric clustering is out of date and I made modifications.

I have a custom JWT validator to address web socket authentication from IoT devices as well as custom routing for the socket endpoints.

The latest updates to aspnetcore seem to have introduced a number of breaking changes in the routing and authentication, and I cannot afford to get too far behind them.

I have arcade managing the build but would like to automate the versioning with darc.

regards

**Comment by markwilkie** [comment]
I think I see - you would like to trigger your build everytime aspnetcore updates?

**Comment by fuocor** [comment]
excatly

**Comment by markwilkie** [comment]
First - it's cool that you are already successfully using Arcade, as this is our long term goal - namely to enable our community to use the same stuff we do.

Unfortunately.......we've not yet achieved this goal as the darc backing service is internal to msft only right now.  :(

Alternatively, perhaps you could watch the myget feed and trigger off a new package?

**Comment by fuocor** [comment]
thanks.

the problem is that not all of the dependencies are coherent and may result in too many failed builds because they are out of sync with each other. My goal was to pick up all the dependencies used for a specific build of aspnetcore and netcore.

**Comment by markwilkie** [comment]
Yea...kinda like what darc does...  :)

Let me think about this some more.  Orthogonality, I'd love to chat if you have a few minutes next week.

**Comment by fuocor** [comment]
sure. just let me know what the best time and means to connect is.

**Comment by markwilkie** [comment]
cool.  I just emailed you and we can work out the details.

**Comment by markwilkie** [comment]
@fuocor and I chatted about this a few days ago.  Basically, we don't (yet) support external access to our arcade related services.  We talked about a work-around, and the fact that we'd really like full community support in the future.
