### ISSUE TITLE
[Darc] Support delete for scripts in GitHub and VSTS

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#258]
Today we support propagating script changes including:

*  Adding a script which lives in arcade but not in the participating repo
*  Editing an existing script in a participating repo which is different from that in arcade 

We are not checking if there is a file which is not in arcade but exists in a participating repo so we remote it from the last

**Comment by weshaggard** [comment]
@tmat recent change to rename init-tools to tools is a prime example of why we need these auto-PRs to clean-up these old files. Now we have both an init-tools and tools set of scripts in corefx https://github.com/dotnet/corefx/pull/32887/files.

**Comment by jcagme** [comment]
I'll start working on this after finishing my current work later today
