### ISSUE TITLE
[darc/maestro++] Allow trigger subscriptions to be run against specific builds

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2582]
Add an API that will set a build that is already in a channel (release steps have already run) to be the latest build.

This avoids a problem where out-of-order publishing might get us into an unwanted state where we may have to go manually edit the DB.

**Comment by alexperovich** [comment]
What do you mean by "latest"? There isn't anything stored in the DB that means "latest". Unless you are talking about what channel the build is in?

**Comment by mmitche** [comment]
@alexperovich Yeah, latest in channel.

**Comment by mmitche** [comment]
This should probably be "trigger subscriptions against specific build", so that we can go back in time and roll back to previous state.

**Comment by riarenas** [comment]
Not as useful to have now that remove-build-from-channel also triggers the subscription to put it back to the state before that build existed.
