### ISSUE TITLE
[darc/maestro++] Make release pipeline runner assign build to channel in build finishing order

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2583]
If, for some reason, a release for a build (A) stalls and a release for a later build (B) finishes before release of build (A) the pipeline runner will assign builds to channel out of the order the builds finished. This might cause problems in the dependency updater.

We should patch release pipeline runner to assign builds to channel in the order the builds finished/arrived in the runner.

/cc @mmitche

**Comment by JohnTortugo** [comment]
@mmitche do you think there will still be work to be done on this once repos move to YAML release pipelines?

**Comment by mmitche** [comment]
i don't think so, but we will need to see.

**Comment by mmitche** [comment]
With stages and build batching, this is now guaranteed.
