### ISSUE TITLE
SDK version needs to be updated to 2.1.300 

### ISSUE THREAD

**Issue by Anipik** [dotnet/arcade#259]
Currently we are using ```2.1.100-preview-007366``` defined here https://github.com/dotnet/arcade/blob/master/global.json#L3 . It needs to be updated to ```2.1.300``` SDK version so that moving forward we can support net core 2.1 projects.

After updating the SDK, the ```TargetFramework``` Property in ```Microsoft.DotNet.GitSync.CommitManager.csproj``` should be changed to netcoreapp2.1

cc @eerhardt @weshaggard @danmosemsft

**Comment by eerhardt** [comment]
Fixed by #278
