### ISSUE TITLE
GenerateReferenceSource can't agree with itself on enum member ordering

### ISSUE THREAD

**Issue by rynowak** [dotnet/arcade#2607]
See: https://github.com/aspnet/AspNetCore/pull/9657#issuecomment-485589091

I didn't change anything in these enum types, but the GenerateReferenceSource target reordered them. This is causing the code check step to fail because the CI doesn't do that.

**Comment by markwilkie** [comment]
cc/ @ericstj

**Comment by natemcmaster** [comment]
I believe this change was intentional. @rynowak it sounds like you're running into problems because you have a stale version of ref assembly code and GenAPI on your local branch. Rebase on master and regenerate the reference assembly code to get the latest version of GenAPI.

Recommend closing because I don't think there is an action item here for Arcade.

**Comment by natemcmaster** [comment]
Nevermind, I'm wrong. The results of GenAPI.exe are machine-dependent. It seems like something else, like roll-forward onto .NET Core 3, might be changing the way this code behaves:

https://github.com/dotnet/arcade/blob/0d3112d5fd33028bbee4326e1446b0e488a859f9/src/Microsoft.Cci.Extensions/Traversers/SimpleTypeMemberTraverser.cs#L89-L96

cc @tannergooding

**Comment by tannergooding** [comment]
Could you give an example of what is differing and how I can repro?

**Comment by natemcmaster** [comment]
Found the reason. The results differ based on whether GenAPI ran on .NET Framework or .NET Core.

### Minimal repro:
1. Create a project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.GenAPI" Version="1.0.0-beta.19218.7" GeneratePackagePath="true" />
  </ItemGroup>

  <Target Name="Repro" DependsOnTargets="Build">
    <Message Importance="High" Text="==========.NET Core =========-" />
    <Exec Command="dotnet $(PkgMicrosoft_DotNet_GenAPI)\tools\netcoreapp2.1\Microsoft.DotNet.GenApi.dll $(TargetPath)" />
    
    <Message Importance="High" Text="%0A%0A%0A" />
    <Message Importance="High" Text="==========.NET Framework ==========" />
    <Exec Command="$(PkgMicrosoft_DotNet_GenAPI)\tools\net472\Microsoft.DotNet.GenApi.exe $(TargetPath)" />
  </Target>

</Project>
```
2. Add a file
```c#
using System;

namespace EnumTest
{
    public enum MyEnum
    {
        A = 26,
        Z = 0,
    }
}
```
3. Run `dotnet msbuild -restore -t:Repro`

## Result:
![image](https://user-images.githubusercontent.com/2696087/56611406-89b85600-65c6-11e9-8886-27124692c633.png)

**Comment by tannergooding** [comment]
@natemcmaster thanks!

Looks like `IOrderedEnumerable` was made to be covariant in .NET Core. It is not in .NET Framework.

**Comment by tannergooding** [comment]
Fix is here, sorry for the noise: https://github.com/dotnet/arcade/pull/2616

**Comment by rynowak** [comment]
Thanks for the quick turnaround on this!
