### ISSUE TITLE
On/off switch for auto generate release pipeline GitHub issues

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2609]
In relation to https://github.com/dotnet/arcade/issues/2554 we should have a way to disable opening issues when something fails during releases. We might be testing a new feature or debugging an issue which might lead to a bunch of issues been created. I think the best approach would be to have the on/off switch in a config file in the arcade repo (`eng`?) where we can just update a value and merge the change without the need of actually deploying it.

**Comment by JohnTortugo** [comment]
Not needed now that we are moving to YAML-based publishing pipelines.
