### ISSUE TITLE
Double check & fix the asset location types

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2622]
Need to double check the asset location types and fix according. For instance, blobs should have asset type Container and currently they are not: https://github.com/dotnet/arcade/blob/e2ac511fb24d2e222fded2a2008ac803c30cf424/src/Microsoft.DotNet.Build.Tasks.Feed/src/PushArtifactsInManifestToFeed.cs#L213

cc` @mmitche @jcagme

**Comment by jcagme** [comment]
Is this currently breaking something? Seems like using the correct asset location type is important

**Comment by JohnTortugo** [comment]
Last time @mmitche had to do some workarounds. I think we can manage to implement this before P6.

**Comment by jcagme** [comment]
P7? P6 is just next week and we won't be deploying in the week so let's assume is P7

**Comment by mmitche** [comment]
@jcagme We can use an INT version of darc for gathering.  Fixes are only client side.

**Comment by JohnTortugo** [comment]
Fixed in https://github.com/dotnet/arcade/pull/2986
