### ISSUE TITLE
Commit messages made by maestro can be so long they break the build

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#2639]
Example:
* https://dev.azure.com/dnceng/public/_build/results?buildId=172217
* https://github.com/aspnet/AspNetCore-Tooling/commit/1653a53ee23593c9ee1df683e7bb15fc25031802

The generated commit message listed the complete history of the PR. This was so long, it caused MSBuild.exe to crash.

```
##[warning]Environment variable 'BUILD_SOURCEVERSIONMESSAGE' exceeds the maximum supported length. Environment variable length: 33743 , Maximum supported length: 32766

Downloading vswhere
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe /nologo /bl:F:\workspace\_work\1\s\artifacts\log\Debug\ToolsetRestore.binlog /clp:Summary /clp:ErrorsOnly;NoSummary /m /nr:False /p:ContinuousIntegrationBuild=True /p:TreatWarningsAsErrors=true /p:__ToolsetLocationOutputFile=F:\workspace\_work\1\s\artifacts\toolset\1.0.0-beta.19225.5.txt /t:__WriteToolsetLocation /v:minimal /warnaserror F:\workspace\_work\1\s\artifacts\toolset\restore.proj
##[error]Unhandled Exception: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Environment variable name or value is too long.
=============
System.ArgumentException: Environment variable name or value is too long.
   at System.Environment.SetEnvironmentVariable(String variable, String value)
   at Microsoft.Build.BackEnd.InProcNode.HandleShutdown(Exception& exception)
```

**Comment by dougbu** [comment]
This issue overlaps #2462 though I hadn't seen the impact on the env variable when I last commented there.

**Comment by natemcmaster** [comment]
Another build failure caused by the bot. https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=179049

cc @markwilkie for triage - the bot is making commits which are unbuildable in Azure Pipelines because the commit message is too long.

**Comment by markwilkie** [comment]
@riarenas @mmitche 

@natemcmaster - this is because the commits pile up?

**Comment by markwilkie** [comment]
Likely related:  https://github.com/dotnet/arcade/issues/2219

**Comment by natemcmaster** [comment]
Yeah, looks related. The description in #2219 doesn't call out the fact that you cannot actually build commits in Azure DevOps when the commit message is too long. We have to push a new commit in the repo to workaround this.

**Comment by markwilkie** [comment]
Closing in favor of https://github.com/dotnet/arcade/issues/2219
