### ISSUE TITLE
nuget restore for a specific project fails

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/arcade#2641]
See attached binlog (in zip file) 
[Build.zip](https://github.com/dotnet/arcade/files/3129488/Build.zip)

When trying to restore a specific project file, we get an error about the incorrect NugetRestoreLocation. This seems to be due to a typo in Build.proj, notice the use of `$(_NuGetRestoreTargets)` and the `Condition="'$(NuGetRestoreTargets)'==''"`. It looks like this should be `Condition="'$(_NuGetRestoreTargets)'==''"`

```
    <PropertyGroup>
      <_RestoreUsingNuGetTargets Condition="'$(_RestoreUsingNuGetTargets)' == '' and '$(_BuildSolutions)' == 'false'">true</_RestoreUsingNuGetTargets>

      <!-- IsRunningFromVisualStudio may be true even when running msbuild.exe from command line. This generally means that MSBUild is Visual Studio installation and therefore we need to find NuGet.targets in a different location.  -->
      <_NuGetRestoreTargets Condition="'$(NuGetRestoreTargets)'=='' and '$([MSBuild]::IsRunningFromVisualStudio())'=='true'">$(MSBuildToolsPath32)\..\..\..\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets</_NuGetRestoreTargets>
      <_NuGetRestoreTargets Condition="'$(NuGetRestoreTargets)'==''">$(MSBuildToolsPath)\NuGet.targets</_NuGetRestoreTargets>
    </PropertyGroup>
```

**Comment by stevenbrix** [comment]
A plausible workaround for now is to manually set the `_NuGetRestoreTargets` property as desired and set the `NuGetRestoreTargets` to any non-empty value.

**Comment by tmat** [comment]
I think it broke it recently. Thanks for filing an issue. Fixing.

**Comment by stevenbrix** [comment]
Thanks @tmat! :)

For what it's worth, the workaround i provided works, but it needs to go in the `Build.props` file in the `eng` folder of the repo.
