### ISSUE TITLE
Create internal subscriptions

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2660]
We need one subscription per repo where the branch is “internal/release/x” where x is the release version i.e. 3.0.

This is going to be needed once a year but we could create a script to automate the process.

**Comment by jcagme** [comment]
@mmitche do we want to create internal subscriptions for all existing subscriptions or we should just create them when is needed? Process-wise we could create the subscriptions when the internal branches are created?

**Comment by JohnTortugo** [comment]
JC can we move this to post P7 epic?

**Comment by jcagme** [comment]
If we decide we need all the subscriptions created, yes we can move it, if not we can just close it.

**Comment by JohnTortugo** [comment]
Ping @mmitche

**Comment by mmitche** [comment]
I would say create when needed. We will not need internal subscriptions for all existing subscriptions.  We only need those for repositories downstream in the graph of any internal changes.

**Comment by jcagme** [comment]
Awesome. Thanks for clarifying.

@JohnTortugo, closing this since is not needed anymore
