### ISSUE TITLE
Understand “Azure Internal Feeds” and how do we interact with them

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2661]
Things we need to understand:

1. What’s their access scope?
2. How can a repo restoring packages can authenticate?
3. Do we create one per servicing batch? One per repo?
4. For stable builds we need to support overriding existing packages, is that supported by the feeds or we need to delete and post?
5. Delete the feed when the internal builds are merged with public?

**Comment by jcagme** [comment]
Currently blocked by the fact that restoring from an internal AzDo feed on Mac and build agents is not working. I've filed https://developercommunity.visualstudio.com/content/problem/591052/restoring-from-private-azure-devops-feed-doesnt-wo.html and that was linked to https://developercommunity.visualstudio.com/content/problem/581357/dotnetcorecli.html which I am updating with findings.

As a plan B, in case this doesn't get resolved we could use private blob feeds with an Azure Function proxy.

**Comment by jcagme** [comment]
Seems like there is an issue on Nuget/dotnet-cli which is tracked by https://github.com/NuGet/Home/issues/7855

**Comment by JohnTortugo** [comment]
@jcagme - one question that popped into my head: these feeds support publishing blobs to them, right? As in having a flatcontainer?

**Comment by jcagme** [comment]
Good thing you brought this up. Yes, in a form. There is a thing called Universal Packages which is like a ZIP of all blobs in the feed but one can GET a specific file from the ZIP itself. Drawback is that there is REST Api or HTTP way to get the files and we'd need to use the Azure CLI or Universal Package tooling to do this. I'll, first, understand the usage scenario of blobs on servicing and then try to come up with a nice solution.

**Comment by JohnTortugo** [comment]
Thanks @jcagme . Just a rant: perhaps Azure CLI or UP tooling would be an issue for source build?

**Comment by jcagme** [comment]
Let's ask @crummel  about that. @crummel basically, if we move on with using AzDo Feeds we'd need a third party client tool to download files from said feed. This tool would be a client tool like nuget.exe. Is this a red flag for source build?

**Comment by alexperovich** [comment]
The azure artifacts documentation says to use azure cli to download universal packages, but it 100% uses one of these rest apis https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/artifact%20%20details/get%20package%20version?view=azure-devops-rest-5.1

We could figure out what api it is using and just use that directly.

**Comment by jcagme** [comment]
@zarenner mentioned there's no HTTP support for getting a filepath filtered file from an universal package just yet. Probably the APIs today support getting the whole UP which might contain a lot of files that we don't need to download... That said, I think is good to analyze both paths and see what's the best

**Comment by alexperovich** [comment]
The "whole zip" is just whatever you uploaded as the package. Its not a lot of files. If you create a package "pizza" version "1.0.0", the zip for that package is just the files you put in it. Its not, "every package in the feed"

**Comment by jcagme** [comment]
I know. Let's say repo A publishes a bunch of packages (of all sorts) and 100 files contained in UP pizza.1.0.0. Repo B just needs one file from the 100 files in pizza.1.0.0. Probably (I haven't checked yet) the apis expose a way to download/restore pizza.1.0.0. completely (100 files) while the CLI/UP tool provide a way to download a particular file.

**Comment by alexperovich** [comment]
why would repo A publish hundreds of files into a universal package pizza.1.0.0? That would be like asp.net publishing all of its code into a single nuget package. Just publish more than one package for each set of files that makes sense.

**Comment by jcagme** [comment]
Logic right now is that things which are not NuGet, npm, Maven packages will go into a universal package. The files different the previously mentioned could be more than one. Are you suggesting creating different UPs? Maybe per file type? That's not a bad idea.

**Comment by alexperovich** [comment]
Yea, why just one universal package? Each thing that is a "blob" package right now should be its own universal package.
