### ISSUE TITLE
Native toolset installation scripts between Windows / Linux are not at parity

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#2674]
The Windows scripts were redesigned to use a common install script for native tools (`install-tool.ps1`); Linux scripts still require per tool script installers (ie `install-cmake.sh`).  We need to align these scripts.

**Comment by jonfortescue** [comment]
Since artifacts are required to be on machines and we're obviating native tools bootstrapping, tools like `cmake` should be installed via package manager on Linux.
