### ISSUE TITLE
Inconsistent .nuget.dgspec.json

### ISSUE THREAD

**Issue by fuocor** [dotnet/arcade#2694]
With SDK version 3.0.100-preview6-011752 installed the restore function is failing with the corresponding Microsoft.NETCore.Platforms not being found. 

The issue appears to be at line 111 in DefaultVersions.props.
```<RestoreSources Condition="'$(UsingToolXliff)' == 'true' and $(XliffTasksVersion.Contains('-'))">$(RestoreSources);https://dotnet.myget.org/F/dotnet-core/api/v3/index.json</RestoreSources>```

which results in myget being added to the ```.nuget.dgspec.json``` where it does not exist. it exists in ```https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json```

although ```https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json``` is in ```NuGet.config``` it is not in ```Versions.props``` and the [onboarding](https://github.com/dotnet/arcade/blob/master/Documentation/Onboarding.md) does not indicate that it is needed. By adding it to the ```Versions.props``` the package references were found.

This appears to be an issue only when myget and the dotnetfeed get out of sync.

**Comment by fuocor** [comment]
Follow-up. While the workaround gets it past the build, at runtime it results in 
```The specified framework 'Microsoft.NETCore.App', version '3.0.0-preview6-27705-02' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\ossiaco\dotnet\artifacts\bin\Chorus.Cosmos\Debug\netcoreapp3.0\shared\Microsoft.NETCore.App
  - Alternatively, install the framework version '3.0.0-preview6-27705-02'.
```

There is no shared directory.

**Comment by markwilkie** [comment]
Sharing w/ the wider arcade working group as we're about to move to 3.0 globally....

**Comment by mmitche** [comment]
We should remove the myget feed from the onboarding docs if possible.  That feed doesn't contain any new packages.

**Comment by fuocor** [comment]
It seems to have been a bad drop of the SDK. Version ```3.0.0-preview6-27702-72``` seems to work fine

**Comment by markwilkie** [comment]
@chcosta - what's the right feed we should reference in https://github.com/dotnet/arcade/blob/master/Documentation/Onboarding.md?

**Comment by fuocor** [comment]
mine has the following
```
  <PropertyGroup Label="RestoreSources">
    <RestoreSources>
      $(RestoreSources);
      https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json;
      https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/index.json;
      https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/index.json;
      https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/index.json;
      https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json;
      https://dotnetfeed.blob.core.windows.net/aspnet-extensions/index.json;
      https://www.myget.org/F/applicationinsights/api/v3/index.json;
      https://dotnet.myget.org/F/rx/api/v3/index.json;
      https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json;
      https://www.myget.org/F/aad-clients-nightly/api/v3/index.json;
      https://dotnet.myget.org/F/orleans-ci/api/v3/index.json;
      https://www.myget.org/F/azure-cosmos/api/v3/index.json;
    </RestoreSources>
  </PropertyGroup>
```

the ```dotnetfeed.blob.core.windows.net``` are as per the  preview 5/6 SDK recommendations

**Comment by chcosta** [comment]
It really depends on what packages you need.  As a (new) baseline, I set it to the same values as we have in Arcade.  The key one is generally "https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" and then you can add to that for one-off packages that your solution needs to pull in.

NuGet.config is used to restore your custom MSBuild SDK's, `eng/Versions.props` is used to restore packages for your solution.  It is intended (optimistically) that in the future a props file could be used for both, but MSBuild doesn't currently support that for SDK's.

**Comment by markwilkie** [comment]
@fuocor - do you think anything else?

**Comment by markwilkie** [comment]
Closing since it looks we're good given the staleness of the thread.
