### ISSUE TITLE
Investigate missing toolset zip

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2711]
This maestro PR is failing because of missing toolset zip file: https://github.com/dotnet/core-sdk/pull/1821

The build logs show the zip being uploaded but the zip isn't in the blob storage: https://dnceng.visualstudio.com/internal/_build/results?buildId=183150

/cc @riarenas @mmitche

**Comment by mmitche** [comment]
@JohnTortugo I think this regression came in with an arcade update.  If so, the arcade commit range was:

https://github.com/dotnet/arcade/compare/7bec23ce3da545d97f53f99abce457a2e252aa58...ac8d88df02d246d3147338fcfb03b1b93dc84b53

**Comment by livarcocc** [comment]
@JohnTortugo any updates on this? This is currently blocking insertions of the toolset into the core-sdk. Which means that core-sdk hasn't been updated with new tooling for a while, only runtimes.

**Comment by JohnTortugo** [comment]
Issue moved to [dotnet/core-eng #6281](https://github.com/dotnet/core-eng/issues/6281) via [**ZenHub**](https://www.zenhub.com/)

**Comment by JohnTortugo** [comment]
No update yet @livarcocc . I'm moving this to FR so this can get special attention.
