### ISSUE TITLE
[Signing] Aggregate of strong names in SignTool

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#272]
- [ ] Incorporate the aggregate of the strong names defined in:
  - [ ] https://github.com/dotnet/roslyn-tools/blob/0bce8ad78a0afe6d03e6ba95c3a9e9729cbc00c9/src/RepoToolset/tools/StrongName.targets
  - [ ] https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets

- [ ] Update SignTool documentation with the list of supported sn / certificates

**Comment by tmat** [comment]
Please, send a PR to RepoToolset that adds the missing keys to StrongName.targets.

**Comment by maririos** [comment]
From @weshaggard recommendation: 
However one key missing piece of data is figuring out what strong name and certificate to use for a given binary. The certificate is generally the same but the strong name varies. If we can figure out a way to get all the necessary information (perhaps we could crack open the files and read the public key token to figure out the strong name) then I'm all for eliminating the requires_signing marker files as well.

=> Let's try to read the strong name from the metadata.

**Comment by JohnTortugo** [comment]
This is already being covered by the new changes in the SignTool #410.

**Comment by weshaggard** [comment]
We still need to explicitly configure the list of strong name tokens supported. That is separate from the SignTool itself.

**Comment by JohnTortugo** [comment]
How do I find the pair of StrongName / Certificate for a given SNK file or PublicKeyToken?

**Comment by JohnTortugo** [comment]
Can't we just import what is defined in the SignToolData.json files from these (and maybe others) repos?

**Comment by weshaggard** [comment]
>How do I find the pair of StrongName / Certificate for a given SNK file or PublicKeyToken?

You need to figure out the list of publickeytokens for both and find the matching certificate name. For BuildTools you can see the key names https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets#L22 you may need to open the snk files to get the publickeytokens (you can run `sn -tp <snk file>` to get the public key token from the file). Then align them with the certificate name you can find here https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets#L28.

For the roslyn-tools you will need to match the public keys with the certs in the signtooldata.json file.

On top of this mapping we need to add the additional BuildTools strong name mappings to the arcade sdk at https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/StrongName.targets#L28.

**Comment by JohnTortugo** [comment]
Planing to close this as the idea now is that the repo owner will be able to use a `Signing.props` file to set specific details of the signing for his repository. Any objections ?

**Comment by weshaggard** [comment]
Extra corefx strong names added with https://github.com/dotnet/arcade/pull/1066.
