### ISSUE TITLE
Helix should support acquiring payloads directly from Azure DevOps artifacts

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#2720]
Rather than requiring teams to create (zip up) payloads and send them to Helix, we should support specifying an Azure DevOps artifact location which Helix can directly access.  

Is this already supported or are there authentication issues that need to be resolved to support this? @MattGal @alexperovich 

Request comes from @dougbu 

FYI @mmitche @markwilkie @Chrisboh

**Comment by MattGal** [comment]
If it's a publicly accessible .zip, .tar, .tar.gz, or .nupkg I think it'll just work.  If auth is required we will have to dig deeper.

**Comment by dougbu** [comment]
FYI @HaoK @natemcmaster @JunTaoLuo

**Comment by markwilkie** [comment]
@dougbu - could I understand the scenario a bit more please?  Perhaps this is needed by your end-to-end tests?

cc/ @natemcmaster and @alexperovich

**Comment by dougbu** [comment]
@markwilkie this is an idea that came up in a meeting @chcosta chaired not that long ago.

The fan-out of test payloads takes a great deal of time in Helix control jobs and caches the same bits in multiple places. To reduce the burden of using Helix and reduce the fan out time and redundancy, I suggest the Helix test jobs get their payloads directly from AzDO artifacts the Helix control jobs (or earlier build steps) upload.

This would also reduce the concept count for new Helix users.

**Comment by markwilkie** [comment]
Moved to the Helix business priority which will be post P7 at the earliest.

**Comment by ChadNedzlek** [comment]
I'll need more details here... but I don't think there is anything Helix needs to do here.  "Helix" is just msbuild code, which can't interact with Azure DevOps artifacts in any meaningful way.  We don't control the stages, so we can't even know that previous artifacts exist.

I think we already have a mechanism for passing whatever payload URI's a user wants to the Helix job, and we'll happily download and unpack them.  But I'm not sure what functionality we can provide beyond that... build authorship is generally outside the scope of the Engineering team.

**Comment by MattGal** [comment]
I agree with Chad here; any scenario where we'd do this would most certainly involve just generating SAS-ified URIs to the AzDO resources and then Helix clients would download them exactly the way they always have.  

That said, I'm confused why this would be a good thing.  Azure DevOps' artifacts are shared and throttled across the whole project instance, whereas the storage we use for Helix jobs is dedicated to them.  While it _can_ occasionally slow down, Azure storage accounts have, at least subjectively to me, been more reliable than AzDO artifacts in terms of both download performance and availability.

**Comment by dougbu** [comment]
I asked about this simply to avoid redundant uploads of the core product i.e. creating artifacts for later stages as well as pushing the same assemblies to Helix agents.

The redundancy might not be a big deal given the relatively short time spent pushing the Helix payloads. It also won't be an issue once testing moves after SDK creation. And, I wasn't aware of the different throttles.

**Comment by ChadNedzlek** [comment]
Alrighty. I'm going to close this.  If we notice a big uptick in upload times later, we can re-examine the situation, but it sounds like, for now, we are in an ok place.

**Comment by markwilkie** [comment]
Seems reasonable to wait until (or if) upload times become a limiting factor.

It does seem that it *might* be interesting to explore sending in pointers to the payload instead of the payload itself.
