### ISSUE TITLE
InstallDotNetCore.targets fails with "error: Unknown argument `dotnet`"

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#2730]
See https://dev.azure.com/dnceng/public/_build/results?buildId=184631 and https://github.com/dotnet/arcade-validation/pull/385

```
  Restore completed in 3.21 sec for /__w/4/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19259.2/tools/Tools.proj.
dotnet_install: Error: Unknown argument `dotnet`
Failed to install dotnet SDK (exit code '1').
/__w/4/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19259.2/tools/InstallDotNetCore.targets(15,5): error : dotnet-install failed [/__w/4/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19259.2/tools/Tools.proj]
```

Using the new runtimes feature of global.json doesn't work. It appears the arguments passed to the dotnet-install.sh script are incorrect.

This is blocking aspnet from consuming this new feature.

cc @chcosta

**Comment by markwilkie** [comment]
cc @chcosta

**Comment by chcosta** [comment]
Looking.  it worked in my validation job against Roslyn
