### ISSUE TITLE
Helix precommands that fail don't cause the workitem to fail

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#2731]
It appears that if a HelixPreCommand fails, the Helix work item ignores the failure and continues on. Are we doing something wrong or is this the intended behavior of helix precommands?

## Details

Here's what we're doing:

We're using "Microsoft.DotNet.Helix.Sdk": "2.0.0-beta.19253.2". One of the test projects has a command defined like this:
```xml
<ItemGroup>
   <HelixPreCommand Include="call RunPowershell.cmd UpdateIISExpressCertificate.ps1" />
</ItemGroup>
```

Here is the RunPowershell.cmd script: https://github.com/aspnet/AspNetCore/blob/4db8260c6cdec1a6ad3624b28c279f6f104a8f14/eng/scripts/RunPowershell.cmd

The powershell script it was launching -- `UpdateIISExpressCertificate.ps1` -- had a syntax error which caused it to fail on Windows 7 and 8.1. But despite this, it appears the helix execution script continued on and ignored this error. 

Example: job ID 69d8ccf8-de65-4447-90f7-c3c284ede521. Here are some log snippets.
```
# precommands run and fail
C:\dotnetbuild\work\69d8ccf8-de65-4447-90f7-c3c284ede521\Work\d808a2e2-e5e6-4d46-a7b1-c8b906a92794\Exec>call RunPowershell.cmd update_schema.ps1 
The term 'New-SelfSignedCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

# Next step runs
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview5-011568/dotnet-sdk-3.0.100-preview5-011568-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview5-011568/dotnet-sdk-3.0.100-preview5-011568-win-x64.zip
```

https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190508.34/workItem/IISExpress.FunctionalTests~2Fnetcoreapp3.0/wilogs

cc @alexperovich @jkotalik

**Comment by markwilkie** [comment]
cc @MattGal

**Comment by MattGal** [comment]
to set some context, all that Pre and Post commands are doing is sticking extra stuff in the beginning and end of the script.  So, if this is desirable behavior, you could 

On Lunix/OSX:
`set -e` as your first precommand

On Windows, since this is generating a .cmd, there isn't really a concept of set -e, so you could do something like:

```
<ItemGroup>
   <HelixPreCommand Include="call RunPowershell.cmd UpdateIISExpressCertificate.ps1 || exit /b 123" />
</ItemGroup>
```

such that if the left side ever returns non-0, the right side ends execution and forces an error code (ideally unique per place you might fail)

**Comment by alexperovich** [comment]
The PreCommand support in the helix sdk was intentional about not having an opinion on if it should fail the work item if a PreCommand fails. Adding an explicit exit call is the correct way to cause a failure if it is desired that a failing PreCommand will fail the work item.

**Comment by natemcmaster** [comment]
Are there situations in which a failing precommand is considered okay? If not, auto-failing precommands that exit non-zero seems like a sensible default.

**Comment by MattGal** [comment]
There definitely are executables that exist which return non-zero exit codes while still doing what the user wants (for instance, imagine you want to run XUnit and then do something afterwards)  As we have no idea what people may want to do in these situations and making things fail out is easy to add, we've always avoided second-guessing the user for this.

**Comment by natemcmaster** [comment]
Ok. The solution for us is pretty simple then – explicitly make our precommands fail.

That said, I think you should reconsider this default. I think it is reasonable to expect that scripts which fail should cause failures without the user needing to tell Helix “a non-zero exit code is a failure”. This is the default that many systems like MSBuild’s <Exec> task, Azure Pipelines tasks, TeamCity CI, and others have selected, and I think it’s what users expect. For the advanced cases, like people who want to do something with a non-zero code, you could provide a knob like “IgnoreExitCode”. I would not expect IgnoreExitCode to be used often, though, as non-zero exit code almost always means something bad happened.

**Comment by markwilkie** [comment]
And alas, this would also be a breaking change....

**Comment by natemcmaster** [comment]
It might be, but aren't we interested in knowing when precommands are failing? Seems like a good breaking change that might uncover failures that have gone unnoticed.

**Comment by markwilkie** [comment]
The main comment/feedback here is that people generally *expect* failures to result in failures

**Comment by markwilkie** [comment]
This issue seems stale, no longer necessarily relevant or of significant priority.  However, if any of these assumptions are incorrect, please reopen.

**Comment by MattGal** [comment]
One thing to note here is that it's certainly possible via scripting choices to make the precommands fail today;  if we let folks insert arbitrary extra commands lines before things there's no guaranteed way to check a given arbitrary line's return code (in fact it may be part of a multi-line entry).   I agree with closing this.
