### ISSUE TITLE
Helix SDK's XUnit reporter should cause script exit with failure code on failure

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#2739]
Currently XUnit reporter fails silently when it does... from discussing with @alexperovich the behavior wasn't intentional;  we end up sending the regular exit code of the work item, so if that's 0, the whole thing becomes 0.

It makes sense if this reporter is being used that it failing to do its thing should explode the work item.

**Comment by markwilkie** [comment]
Closing in preference for #2731
