### ISSUE TITLE
[Testing - Helix] Provide arcade/buildtools updates that allow using SAS instead of storage key / connection string for uploading payloads.

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#274]
@MattGal commented on [Wed Apr 25 2018](https://github.com/dotnet/core-eng/issues/3374)

Cut off of https://github.com/dotnet/core-eng/issues/2914:

---

@maririos commented on [Thu Jun 21 2018](https://github.com/dotnet/core-eng/issues/3374#issuecomment-399233677)

@maririos move this to arcade

**Comment by maririos** [comment]
@MattGal is this for Helix jobs? or publishing packages

**Comment by MattGal** [comment]
The Helix Storage API gives you SAS tokens and base URIs for handling uploads.  The old MSBuild tasks take storage account keys to do the same.  The idea here would be to be able to feed what the API gives you (or literally just call the API when doing it) and use the values it provides.  This way, we can automatically rotate the keys used by Helix and get automated security this way.

**Comment by markwilkie** [comment]
no longer relevant

**Comment by MattGal** [comment]
because we use the storage APIs and already did the work in the arcade Helix SDK, or ?
