### ISSUE TITLE
InstallDotNetCore mixes x64 and x86 versions of .NET Core in the same install root - causes dotnet.exe to crash

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#2744]
Attempting to update to use the new runtimes install feature. The InstallDotNetCore runtimes target is mixing x64 and x86 versions in the same installation root. This breaks .NET Core for obvious reasons - you can mix CPU architectures for native binaries.

![image](https://user-images.githubusercontent.com/2696087/57547543-8dacdd80-7313-11e9-9b9b-abbc9def7ae6.png)

Repro:
1. Clone https://github.com/natemcmaster/AspNetCore-Tooling/tree/dotnet
2. Run build.cmd

cc @chcosta

**Comment by chcosta** [comment]
What is your expectation?

**Comment by natemcmaster** [comment]
I would expect the installer to know which architecture it is installing, and not to mix bitness. You cannot mix x86 and x64 in the same installation. It causes .NET Core crash with errors like
```
##[error]dotnet.exe : Failed to load the dll from 
##[error][F:\workspace\_work\1\s\.dotnet\host\fxr\3.0.0-preview6-27708-04\hostfxr.dll], HRESULT: 0x800700C1
```

**Comment by chcosta** [comment]
Cool, that makes sense, I wasn't certain if you were proposing something else.

Obviously, the immediate workaround would be to specify "dotnet/x64".

It seems that the initial sdk install script runs in your current machine environment 

PROCESSOR_ARCHITECTURE         AMD64

but when you are installing the runtimes (using dotnet), you are running under the WoW

PROCESSOR_ARCHITEW6432         AMD64
PROCESSOR_ARCHITECTURE         x86

I completely agree that these should be consistent.

**Comment by chcosta** [comment]
Looking into this

**Comment by natemcmaster** [comment]
I think MSBuild.exe is the problem here. I'm only seeing this when building on Windows with MSBuild.exe, which runs as x86.

**Comment by chcosta** [comment]
FYI @tmat

**Comment by chcosta** [comment]
I'm not a huge fan of this thought, but I suppose, when the installed msbuild is your build engine, we could use an msbuild process to install the sdk as well.

**Comment by tmat** [comment]
I'm not sure I understand the issue. Is the install script selecting the bitness based on the bitness of the process it runs it? I think we should always default to 64-bit Core CLR if the bitness is not specified.

**Comment by chcosta** [comment]
Yes, if the architecture is not specified then we don't default one and "dotnet-install.ps1"  auto selects an architecture based on the architecture of the process. We could easily default to x64 instead.

**Comment by tmat** [comment]
Yes, let's do that. But only if we are not on ARM.

`System.Runtime.InteropServices.RuntimeInformation.OSArchitecture == X86 | X64`

Not sure how ARM works. Does Windows on ARM have WoW? If so then probably also want ARM64 to be the default if OSArchitecture == ARM | ARM64.

**Comment by laurenprinn** [comment]
I had the opposite issue happen. I was running MSBuild on a 32 .NET core and  the installation was trying to install 64 bit .NET runtime. 
This occurred when running the SDK repo (https://github.com/laurenprinn/sdk/tree/outputProperties_itemgroup) commit id bdd78a6ba34631f370b35a6263fed0158fe6b0a7 on a 32 bit command prompt.


![image](https://user-images.githubusercontent.com/44309659/84422287-cdb35380-abea-11ea-90af-9c9f6e7aa745.png)
