### ISSUE TITLE
Provide guidance for how to keep up to date with latest Helix Sdk

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#2745]
@riarenas commented on [Tue May 07 2019](https://github.com/dotnet/arcade-validation/issues/377)

We already have the infrastructure in place for repositories to subscribe to dependency updates to the Helix SDK.

We should provide guidance on why, when, and how repos should explicitly add the Helix SDK dependency.

**Comment by markwilkie** [comment]
@riarenas - can you expand please?  In my mind at least, our guidance is "take the latest".

**Comment by riarenas** [comment]
That's my mind as well. This question came up during a standup, to see if we wanted to further document or provide explicit guidance on when/how to pin a version.

**Comment by markwilkie** [comment]
Do you think https://github.com/dotnet/arcade/blob/master/Documentation/Policy/DefaultsGuidance.md is enough?

**Comment by markwilkie** [comment]
Closing for now given the guidance as written down.  Let's reopen if needed
