### ISSUE TITLE
Version VSTS YAML

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#275]
@chcosta commented on [Thu Jun 07 2018](https://github.com/dotnet/core-eng/issues/3643)

We have a dependency on the config as code (YAML) changes which VSTS provides via the build agent.  I believe, that the only way to lock the version is via not taking an update the build agent on a build machine.  

We should document how we intend to handle this for servicing, and also follow up with VSTS on what their suggested practice is so that we can service builds which may not roll forward with the latest VSTS feature changes.

Filed - https://dotnet.visualstudio.com/internal/_workitems/edit/24

/cc @mmitche @markwilkie 

---

@maririos commented on [Thu Jun 21 2018](https://github.com/dotnet/core-eng/issues/3643#issuecomment-399237616)

@maririos move to arcade

**Comment by JohnTortugo** [comment]
@mmitche @chcosta - Do we still need this? If so, we should start working on a plan, right?

**Comment by JohnTortugo** [comment]
This looks quite related to https://github.com/dotnet/arcade/issues/237

**Comment by mmitche** [comment]
This is done.  We don't really have control over the agent version in the long term.  The cloud provider will give us an agent version and we need to use it.  We also don't have control in any hosted pools.
