### ISSUE TITLE
Helix Arcade SDK Wait behavior does not log correctly on "Fireball" (bad-exit) work items

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#2757]
This seems to (mostly ) happen on runs that failed with catastrophic errors but I'm pretty sure I've seen it happen on good runs too. 

The build for this got manually deleted by @wtgodbe while I was filing the issue, but the job was:
```
WorkItems
| where JobName == "75e2d0a5-9e17-416e-83bc-b57dc1b177ea"
| where Status != "Pass"
```

And the wait task errors out like this:
```
 error : This task can only be used on completed jobs. There are 6 of 212 unfinished work items
```

It should instead log something to the effect of "job was completed, but 6 work items failed via bad exit codes"

@Chrisboh FYI.

**Comment by ulisesh** [comment]
#2878 should fix this

**Comment by ulisesh** [comment]
After #2878, this will only happen when workitems timeout

**Comment by markwilkie** [comment]
@MattGal - can you confirm that this is Helix?

**Comment by markwilkie** [comment]
Adding to the Helix epic.

**Comment by MattGal** [comment]
@markwilkie sorry for not responding here.  I haven't actually checked out what the arcade SDK does here so I don't know if it's a fix in the client side or the API side, but I lean towards the former.

**Comment by ChadNedzlek** [comment]
The current behavior should be much improved in this area. Closing.
