### ISSUE TITLE
Packages are missing from blob feed index

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#2774]
The dotnet/standard build produced two builds rather closely together.

Somehow it seems that the newer build deleted the package index entries for the earlier build.

Earlier build: NETStandard.Library.2.1.0-prerelease.19264.2
https://dev.azure.com/dnceng/internal/_releaseProgress?_a=release-environment-logs&releaseId=7481&environmentId=20350

Later build : NETStandard.Library.2.1.0-prerelease.19264.3
https://dev.azure.com/dnceng/internal/_releaseProgress?_a=release-environment-logs&releaseId=7485&environmentId=20364

Both successfully published to the blob feed, and for a time the 19264,2 build was restore-able
https://github.com/dotnet/corefx/runs/127694102
Then later it was not
https://dev.azure.com/dnceng/public/_build/results?buildId=189054

Manually inspecting https://dotnetfeed.blob.core.windows.net/dotnet-core/sleet.packageindex.json shows that the 2.1.0-prerelease.19264.2 is now **missing** from the feed.

/cc @emgarten @markwilkie @mmitche

**Comment by emgarten** [comment]
There was a previously an issue where the package index was read outside of the lock to check if the packages were already on the feed. Then the same local file cache was used for the push inside the lock, and the new changes would be added to an older version of the index.

It was fixed here: https://github.com/dotnet/arcade/pull/2094

Is it possible that an older version of arcade read the index before 2.1.0-prerelease.19264.2 completed, and then pushed packages (they could be any id) using the old index before NETStandard.Library.2.1.0-prerelease.19264.3 was pushed?

Sleet uses the package index as the source of truth, when NETStandard.Library.2.1.0-prerelease.19264.3 was pushed it will find all versions of NETStandard.Library and use that create https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/netstandard.library/index.json which is used by restore.

**Comment by ericstj** [comment]
/cc @wtgodbe @jcagme 

An arcade update did come in to build 2.1.0-prerelease.19264.1, but this was using the same version of sleet that its been using for months.  The two builds in question were merely source changes in the repo.  We appear to be using the same version of Sleet for the past months
https://github.com/dotnet/arcade/blob/33c39b1d3a7043bfaf2c9b388b98d709f89db3b2/eng/Versions.props#L42

**Comment by ericstj** [comment]
Actually ignore everything I said about versions.  It looks like the publishing portion in the release workflow is using 2.2.0-beta.19170.2 (apparently hardcoded in the release pipelines?).  This still has your fix though.  

> Is it possible that an older version of arcade read the index before 2.1.0-prerelease.19264.2 completed, and then pushed packages 

This seems likely.  This is the dotnet-core feed, which is the one we used to share with the entire stack.  It seems likely that there could be some old build somewhere (eg: release branch) using an old copy of this code but I don't really know how I would hunt that down: is there any auditing for this?

**Comment by emgarten** [comment]
@jcagme are older versions of arcade/sleet still being used on the dotnet-core feed? I think you mentioned recently that there were still legacy builds pushing to this which were holding the lock for a long time. I suspect that could be what caused this.

> is there any auditing for this?

The catalog/audit log isn't turned on for this feed.

**Comment by JohnTortugo** [comment]
@emgarten I think the case you're talking about was core-setup. We have recently updated the version used there, though.

**Comment by JohnTortugo** [comment]
Both packages are still on the blob storage, though:

```
https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/netstandard.library/2.1.0-prerelease.19264.2/netstandard.library.2.1.0-prerelease.19264.2.nupkg

https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/netstandard.library/2.1.0-prerelease.19264.3/netstandard.library.2.1.0-prerelease.19264.3.nupkg
```

**Comment by emgarten** [comment]
If everything is using the latest version of arcade with the fix then the locking should be correct. Possibly the lock was lost due to a network issue, possibly by the push of 19264.2 or another push going on at the same time.

Sleet fails silently and tries to get the lock again if something happens trying to renew the blob lease. I've opened https://github.com/emgarten/Sleet/issues/76 to track improving this on Sleet.

If this continues happening we could turn on the catalog to track all package operations happening. It would slow down performance since it does extra nupkg hashing, but it would give an audit log. Older clients would respect this also. The setting is in https://dotnetfeed.blob.core.windows.net/dotnet-core/sleet.settings.json

**Comment by mmitche** [comment]
We pushed a bunch of packages yesterday from the release branches.  Those are definitely using old versions of sleet at the moment. There was an attempt made to update it, but it ran into buildtools issues.

**Comment by jcagme** [comment]
> Both packages are still on the blob storage, though:
> 
> [netstandard.library.2.1.0-prerelease.19264.2.nupkg](https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/netstandard.library/2.1.0-prerelease.19264.2/netstandard.library.2.1.0-prerelease.19264.2.nupkg)
> 
> [netstandard.library.2.1.0-prerelease.19264.3.nupkg](https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/netstandard.library/2.1.0-prerelease.19264.3/netstandard.library.2.1.0-prerelease.19264.3.nupkg)

So the bits are in the feed but the index doesn't have both?



> We pushed a bunch of packages yesterday from the release branches. Those are definitely using old versions of sleet at the moment. There was an attempt made to update it, but it ran into buildtools issues.

Are these the prodcon builds?

@emgarten even though I think this is the first time we hit this, is there something we could do to avoid this? Is the fix to move ALL the repos to the latest?

**Comment by ericstj** [comment]
I wouldn't say this is the first time we hit this.  This is the first time we hit it and we took the time to root cause it.  In most cases this would just look like some publishing failure and folks would move on to a new build.  Here we actually had a large enough window where we were able to successfully restore before the index got corrupted so we merged a dependency on the package before it disappeared from the index.

I don't think we should accept a "lossy" publishing process.

**Comment by jcagme** [comment]
Just to be clear, I am not "accepting" and moving on, hence my question to @emgarten on what should be the correct action to take.

**Comment by JohnTortugo** [comment]
> So the bits are in the feed but the index doesn't have both?

Yes, that's correct.

**Comment by emgarten** [comment]
> @emgarten even though I think this is the first time we hit this, is there something we could do to avoid this? Is the fix to move ALL the repos to the latest?

Yes, everything working with the feed needs to have the https://github.com/dotnet/arcade/pull/2094 fix so that locking works properly. I don't think this issue can be prevented otherwise.

**Comment by markwilkie** [comment]
There are two paths that make up the path forward:
1) We're moving to AzDO feeds right after P7
2) Make sure #2094 is there, and the immediate problem should be mitigated

@ericstj - is this your understanding as well?

**Comment by markwilkie** [comment]
I would prefer to wait until we've got the new publishing stuff in using AzDO artifacts.  Given that we're not seeing high incidents of this, I'm closing for now.  However, there are options if this becomes more urgent or pressing.

**Comment by ericstj** [comment]
@anipik just noticed this happen in servicing https://github.com/dotnet/core-setup/pull/7517.  @emgarten is there any workaround that will bring the feed back to "good" state (EG: regenerate index or something)?

@markwilkie does the fact that this is happening in 2.1 servicing change your resolution here?

**Comment by emgarten** [comment]
> @emgarten is there any workaround that will bring the feed back to "good" state (EG: regenerate index or something)?

Re-pushing the packages would be the simplest way to fix the feed. The nupkgs should be there still, just missing from the indexes.

**Comment by markwilkie** [comment]
After we get through GA, I'd like to explore what it would take to move our servicing to AzDO feeds.

**Comment by mmitche** [comment]
@markwilkie I've already started trying it a bit, and filed an issue for the arcade repo to move.  Once that moves a lot else will go easily.

**Comment by Anipik** [comment]
cc @ViktorHofer

**Comment by ViktorHofer** [comment]
> our servicing to AzDO feeds.

everything or just 3.0?

**Comment by mmitche** [comment]
3.x+

**Comment by ViktorHofer** [comment]
The issue that @Anipik was hitting was on 2.x. Should we backport the changes that fixes the races with sleet?
