### ISSUE TITLE
[PKPIs] Missing/Disabled Product Input Subscriptions

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2780]
Name | Qualifier | Indicates | Drives Action
-- | -- | -- | --
Missing/Disabled Product Input Subscriptions | Per Repo, Per Default Channel (input branch) | Indicates that a branch that applies to a default channel is missing inputs subscriptions for product dependencies, and thus coherency may not be able to be achieved. A subscription is not missing when dependencies are pinned or when they are tied via CoherentParentDependency attributes to other dependencies. Subscriptions that do not update automatically should also be viewed as disabled | Repository owner determines whether those input dependencies need to be marked as Pinned or whether subscriptions should be created/changed to update automatically

**Comment by riarenas** [comment]
This has been rolled out.
 Feel free to reopen if there's more work needed on this.

**Comment by chcosta** [comment]
@riarenas, was this implemented for Darc, BarViz, or both?  Trying to understand if there's more work here.  Also, for my education, how is this used?  ie, where do I go to dterming if a subscription is missing or disabled?

**Comment by riarenas** [comment]
@chcosta I closed this based on the fact that the issue was in the rollout column and the associated changes were rolled out. @mmitche will know the state better.
