### ISSUE TITLE
[PKPIs] Open Dependency Update PRs vs. Possible Dependency Update PRs	

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2781]
Name | Qualifier | Indicates | Drives Action
-- | -- | -- | --
Open Dependency Update PRs vs. Possible Dependency Update PRs | Per Input Channel, Per Repo | A large number of open dependency update PRs indicates that dependencies are not flowing through the repository node. This may indicate that auto-merge is not available for the repository, that the repository owners are not keeping up with merging updates.The metric is qualified based on the input channel because the focus of the team shifts between channels at different stages of the product cycle. | Repository owner investigates open dependency update PRs and merges/fixes as needed

**Comment by adiaaida** [comment]
This is covered by other metrics, so closing.
