### ISSUE TITLE
[PKPIs] Transitive Product Staleness

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2785]
Name | Qualifier | Indicates | Drives Action
-- | -- | -- | --
Transitive Product Staleness | Per Output Channel, Per Repo | Measures the staleness of the direct product inputs of a repository, aggregated with the staleness of the dependencies of those inputs, onward down the repository dependency graph. Staleness calculations are broken at cycles.In contrast to direct dependency staleness, a repository may have a positive staleness score for its direct inputs. However, if those inputs have old dependencies, then the transitive product staleness will increase. A high degree of staleness indicates a higher possibility of breaks as inputs come up to date, that dependencies may not be smoothly flowing through a node, etc. | Repository owner walks dependency tree (in BARViz) to determine where the dependency update clogs are, then communicates with that repository owner to determine why dependencies aren't flowing.

**Comment by chcosta** [comment]
Cut from epic
