### ISSUE TITLE
[PKPIs] Release Pipeline Time	

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2789]
Name | Qualifier | Indicates | Drives Action
-- | -- | -- | --
Release Pipeline Time | Per associated release pipeline | Measures the median amount of time for a successful run of a release pipeline associated with a specific channel. A slow release pipeline time indicates a risk to the flow of dependencies through the product. | Engineering services team investigates why the release pipeline time has regressed and determines a plan of action

**Comment by mmitche** [comment]
Note: might want to alter this one to track the originating repo for release pipeline time.

**Comment by chcosta** [comment]
Cut from epic
