### ISSUE TITLE
[PKPIs] Release Pipeline Pass Rate

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2790]
Name | Qualifier | Indicates | Drives Action
-- | -- | -- | --
Release Pipeline Pass Rate | Per output channel | Measures the average pass rate of a release pipeline associated with a specific channel. The pass rate should be at or near 100% at all times. A low pass rate indicates a indicates a risk to the flow of dependencies through the product. | Engineering services team investigates why the release pipeline pass rate has regressed and determines a plan of action.

**Comment by chcosta** [comment]
Cut from epic
