### ISSUE TITLE
[PKPIs] Dependency Update PR Merge Time

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2791]
Name | Qualifier | Indicates | Drives Action
-- | -- | -- | --
Dependency Update PR Merge Time | Per Repo, Per default output channel | Measures the median amount of time from dependency PR creation to dependency PR merge for PRs to branches that will apply to a specified default output channel once merged. A high merge time may indicate any number of issues, like the rate of incoming change is faster than the PR build time or that the PR pass rate is low, but generally indicates that dependencies will have trouble flowing through the node. | Repository owner determines why dependency update PRs are not merging quickly, potentially looking at other indicators to do so (ci pass rate, ci time, etc.). Perhaps update PRs are not being auto-merged. Repository owner develops a plan to decrease the merge time.

**Comment by chcosta** [comment]
Cut from epic
