### ISSUE TITLE
[PKPIs] Dependency Update PR CI Time

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2792]
Name | Qualifier | Indicates | Drives Action
-- | -- | -- | --
Dependency Update PR CI Time | Per Repo, Per default output channel | Measures the median build time of successful PR builds targeting a branch that is applied by default to the specified channel. This should include time for retries. A large PR build time indicates that it is slow to move dependencies through the node or get new outputs from the node, and that failures in the official build that require retries will be expensive, potentially putting ship schedules at risk. This represents a subset of the PR merge time. | Repository owner investigates ci time, determines why it has regressed (or is high in the first place), and develops a plan to mitigate it.

**Comment by chcosta** [comment]
Cut from epic
