### ISSUE TITLE
[PKPIs] Time to Coherency

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2796]
Name | Qualifier | Indicates | Drives Action
-- | -- | -- | --
Time to Coherency | Per Repo, Per default output channel | Time to coherency is an aggregated metric indicating that, if non-dependnecy flow changes were halted for all branches that apply by default to the specified channel, how long would it take for coherency to be acheived. It is possible for this value to be infinite if there are cycles that flow automatically. This metric is not static and is instead based on the current dependency graph state at the current node. This metric needs to take into account all of the times at the specified steps in the dependency flow process: official build time, release pipeline execution time, dependency flow graph shape, dependency update pr elapsed time, etc. | This metric can drive two primary actions: 1) Determining why time to coherency is long (look at other metrics to narrow) and develop a plan for improvement. 2) Determine lead time required for shipping.

**Comment by chcosta** [comment]
Cut from epic
