### ISSUE TITLE
[PKPIs] Missing/Disabled Toolset Input Subscriptions

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2797]
Name | Qualifier | Indicates | Drives Action
-- | -- | -- | --
Missing/Disabled Toolset Input Subscriptions | Per Repo, Per Default Channel (input branch) | Indicates that a branch that applies to a default channel is missing inputs subscriptions for toolset dependencies. A subscription is not missing when dependencies are pinned or when they are tied via CoherentParentDependency attributes to other dependencies. | Repository owner determines whether those input dependencies need to be marked as Pinned or whether subscriptions should be created/changed to update automatically. In a release channel, this is not generally needed but should be evaluated on a case-by-case basis.
-- | -- | -- | --

**Comment by mmitche** [comment]
This will be covered by existing work, with just some additional switches to narrow between product and toolset dependencies.

**Comment by riarenas** [comment]
This has been rolled out. Reopen if there's more work needed for this.
