### ISSUE TITLE
[darc/maestro++] Allow repositories to select what common scripts to sync

### ISSUE THREAD

**Issue by tmat** [dotnet/arcade#2803]
Based on discussion https://github.com/dotnet/arcade/issues/1248#issuecomment-461909217

There are ~70 files in `eng\common` directory.
Not all repositories need all these files.

To reduce clutter in repositories that do not need them we should allow to exclude subsets of these files from synchronization.

The files can be categorized to 
- `native-tools` - scripts supporting native tools (`cross` and `native` subdirectories and 
   `init-tools-native.cmd|ps1|sh` files, which we should perhaps move to `native` directory)
- `yaml-templates` - YAML templates (`templates` subdirectory)

These files are currently directly in `eng/common`:
  - `helixpublish.proj`
  - `PublishBuildAssets.cmd`
  - `PublishToPackageFeed.proj`

Perhaps these files can actually be moved to the SDK.

**Comment by mmitche** [comment]
I do not think this is necessary and potentially introduces breaks if you do not have your filters set up appropriately.  Also with the reduced number of repos in 5, this should be less of an issue.
