### ISSUE TITLE
Run Credscan as part of the release process

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#2806]
This is dependent on the work that @sunandabalu is doing to enable SDL during the release.

Notes:
* This will allow us to stop running credscan on the mirroring to azure devops, which has been causing overhead whenever something that looks remotely like a password or secret is being mirrored from Github to AzDO
* Investigate if it's possible/makes sense to run it as part of CI to catch these things as early as possible.

**Comment by jcagme** [comment]
Post P7?

**Comment by JohnTortugo** [comment]
I think that would be a more reasonable timeline.

**Comment by JohnTortugo** [comment]
> * Investigate if it's possible/makes sense to run it as part of CI to catch these things as early as possible.

I think this sort of things would be better to catch as early as possible. 

@sunandabalu can you give me an idea of how much work is to implement this and usually how long does it take to execute it for a build?

**Comment by riarenas** [comment]
@markwilkie @sunandabalu does it still make sense to try and get this to work during CI?

**Comment by JohnTortugo** [comment]
Moving to the #2891 Epic.

**Comment by sunandabalu** [comment]
> @markwilkie @sunandabalu does it still make sense to try and get this to work during PR/CI?

The last stand was we can't run CredScan on public builds aka PRs, which is why we are currently running on CI / Official builds. I have an issue to figure out the whole CredScan story - https://github.com/dotnet/core-eng/issues/6849

**Comment by jcagme** [comment]
As defined in the holding Epic, we'll only do SDL's BinSkim during releases
