### ISSUE TITLE
Running tests with arcade causes multiple instances of the test assembly to be loaded in the AppDomain

### ISSUE THREAD

**Issue by pranavkm** [dotnet/arcade#2816]
Discovered as part of investigating https://github.com/aspnet/AspNetCore-Internal/issues/1733.
You should be able to reproduce this by unskipping the tests in this file https://github.com/aspnet/Extensions/blob/master/src/JSInterop/Microsoft.JSInterop/test/DotNetDispatcherTest.cs#L76-L86 and building from the root of the repository.

I do have a fairly limited way to reproduce this:

Consider a test project with a test like so:

```C#
public class UnitTest1
{
    [Fact]
    public void Test1() 
    {
        // Arrange
        var currentAssemblyName = typeof(UnitTest1).Assembly.GetName().Name;
        var expected = new[] { currentAssemblyName };

        Assert.Equal(expected, AppDomain.CurrentDomain.GetAssemblies().Select(a => a.GetName().Name).Where(a => a == currentAssemblyName));
    }
}
```

Running `dotnet test` on the project will cause the test to complete successfully. However running it the way Arcade's [Xunit targets](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/XUnit/XUnit.targets#L51) run will cause the test to report a failure:

```
dotnet.exe 
exec 
--depsfile XUnitTestProject1\bin\Debug\netcoreapp3.0\XUnitTestProject1.deps.json 
--runtimeconfig  XUnitTestProject1\bin\Debug\netcoreapp3.0\XUnitTestProject1.runtimeconfig.json 
.nuget\packages\xunit.runner.console/2.4.1/tools/netcoreapp2.0/xunit.console.dll
XUnitTestProject1\bin\Debug\netcoreapp3.0\XUnitTestProject1.dll
```

Snapshot from the Modules window when running it the Arcade way:

![image](https://user-images.githubusercontent.com/174281/57891095-f9e58080-77ee-11e9-9cd0-43f833d23b79.png)

Perhaps the way the test is executed needs to be tweaked?

**Comment by markwilkie** [comment]
@pranavkm - is this blocking you right now?

**Comment by pranavkm** [comment]
Nope, I was able to workaround it.

**Comment by markwilkie** [comment]
Cool!  What was the work-around @pranavkm ?

**Comment by pranavkm** [comment]
Our issue was that we were caching \ producing delegates using types from the first Assembly instance (of a given identity) and then passing in instances from the second instance. We changed our product code to use the first one consistently. 

We do not have actual product scenarios we need to support where different instances of the assembly exist in the AppDomain, so it was fairly innocuous. But it's fairly possible other products might have a harder time working around this.

**Comment by markwilkie** [comment]
Thanks @pranavkm - closing this given what you've described.
