### ISSUE TITLE
GenAPI is needed for platform not supported assemblies in source build

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#2817]
/cc @ViktorHofer @Anipik 

Turns out we can't completely remove GenAPI today as it will eliminate support for not-supported assemblies.  We need to determine how we're going to deal with this for source build.

**Comment by markwilkie** [comment]
cc/ @chcosta

**Comment by markwilkie** [comment]
@chcosta - is this still an issue for source build?

**Comment by chcosta** [comment]
I believe this is still an issue.

**Comment by ericstj** [comment]
I worked with @dseefeld to define a strategy for this: https://github.com/dotnet/corefx/issues/38035

We can close this one.
