### ISSUE TITLE
Make sure SymbolUploader has retry logic whenever communicating with AzDO

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2839]
In a few occasions the symbol uploader failed and reported some authentication (without any change on our side) / network related error.  We need to make sure we have retry logic everywhere we communicate with AzDO.

Example failure: https://github.com/dotnet/arcade/issues/2649

@mikem8361

**Comment by mikem8361** [comment]
There is already some retry logic around where that failure happened.  It is only 3 times though. 

For this problem and the other symbol validation failure, I need the full verbose logs of the symbol upload leg.

**Comment by JohnTortugo** [comment]
I'll increase the verbosity and let you know when we have other instance of this.

**Comment by JohnTortugo** [comment]
For the record. Another failure here: https://github.com/dotnet/arcade/issues/2917

**Comment by riarenas** [comment]
Have we seen any more failures? Should we keep this around?

**Comment by JohnTortugo** [comment]
Not seen this lately.
