### ISSUE TITLE
Should we move away from MicroBuild signing?

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2852]
This issue is to talk about _what value does MicroBuild signing add and whether we would be better off using ESRP directly for all platforms._

Also, recent update from ESRP folks says that they are now able to sign Linux files (rpm, deb, detached).

@markwilkie @tmat @joeloff

**Comment by ChadNedzlek** [comment]
MicroBuild is one of the things that's hardest for us to manage on our build machines, since the acrobatics required to get it set up properly are fragile, and unable to be tested outside of production.  It's a pile of 4 scripts that have to pull and install several special certificates with unusual encodings in special, non-standard ways.

Even in the best of cases, changing anything about a queue that does signing requires 2 rollouts... 1 to create the queue (which will fail, because it doesn't have permissions to the certificates), then it has to manually be given permission to access the secrets, then another full rollout has to happen to retry the failed deployments.

**Comment by markwilkie** [comment]
Yup - I want to circle back around and look at this again.

**Comment by JohnTortugo** [comment]
@tmat @leecow for signing .deb, .rpm packages will we need to handle that as .zip and .tar.gz files? I mean, extract the content, sign and then repack?

**Comment by joeloff** [comment]
Not 100% sure. The signing process was manual. If the package itself and the contents need to be signed you'd have to unpack the content, sign, repack, then sign the package just like anything else.

**Comment by leecow** [comment]
No, this is signing the deb and rpm. zips/tar.gzs are not signed and the individual linux executables are also not signed.

**Comment by tmat** [comment]
But shouldn't the .NET assemblies contained in the .deb and .rpm be signed?

**Comment by joeloff** [comment]
Authenticode is a Windows concept AFAIK. If the contents of the .deb .rpm have been tampered with then the packages' GPG signature should be invalid and not trusted. It's pointless to sign the DLLs if nothing is validating the signature.

**Comment by tmat** [comment]
Ok, then the sign tool does not need to repack .deb and .rpm. It can just sign them and not dig into them.

**Comment by JohnTortugo** [comment]
Thank you all folks for clarifying this.

**Comment by JohnTortugo** [comment]
This topic has been brought up again in an e-mail thread talk.

@ChadNedzlek explained how convoluted is the process of updating our ScaleSets due to gymnastics to install signing certificates on the VMs.

@premun @jcagme (and IIRC @weshaggard ) has experience on signing files directly with ESRP.

/cc @markwilkie for visibility

**Comment by ChadNedzlek** [comment]
Theoretically the os onboarding process could understand that permissions to vaults is a thing, and it could do the manual step itself (giving the scale set permissions to the vault containing the certificates).

We're always going to want some MSI based access to the certs, so that any ol' queue can't get the certs without some human with permissions agreeing that's ok.

**Comment by joeloff** [comment]
So I'm curious what the exact problem is. For WebTools, we don't use MicroBuild, but we use ESRPClient. All that's required is to have two certificates on the machine performing the signing so it can talk to the service

These certificates are used to authenticate the requests send to ESRP and validate that the requested signing certificate (aka keycode) is associated with the app id making the request. The second certificate is used to sign the request itself before its send to the service.

The appid is similar to the old EABA process where a lab account had privileges to sign using specific certificates. Permissions are now simply associated with the app id.

All that's required is to install these two certificates once (they are valid for 12 and 24 months). Once you have them, you can simply add/remove permissions through the ESRP portal to include new code sign permissions for the actual signing process.

@JohnTortugo Were you referring to directly leveraging the ESRP APIs? The ESRPClient has a lot of functionality that's already provided for free and maintained by PRSS. All that's required is to generate the appropriate input files. That's pretty simple to do. 

We store the certificates in keyvault, but we usually install them manually into our build agents, but it's a one-time cost and only needs to be done again if the certificates need to be renewed or a new agent is being brought online.

**Comment by markwilkie** [comment]
I don't think there's a problem per say @joeloff - this is more of a backlog item for us to circle back around and make sure it gets taken care of.  At its heart, we have to determine the value that microbuild is bringing to the table vs. just going with ESRP directly.  Today for example, we go directly to esrp for mac signing...

**Comment by joeloff** [comment]
Got it. Well, if you decide to use ESRPClient for everythin, I have a build task I wrote for web tools that can automatically generate the required json blobs and deal with submitting jobs and splitting everything out by keycodes into nested batches.

**Comment by Chrisboh** [comment]
@markwilkie do you feel like this is still worth looking into?

**Comment by markwilkie** [comment]
Perhaps....but I don't see the pressing need right now.  Closing until this comes up again.
