### ISSUE TITLE
Helix support for attemtps.

### ISSUE THREAD

**Issue by safern** [dotnet/arcade#2854]
We just noticed the when we retry a build using the `retry` feature in Azure Devops, the BuildNumber is the same, but it introduces an attempt number. However the helix test results are aggregated into the first attempt rather than overriding the previous run.

Also, regarding to azure devops test explorer, if there was a test failure on the first attempt and in the second attempt there were no failures, it will still show the test failure on the test explorer, and therefore the build badge on the PR it would show as red, because the test run is the same, but just with aggregated results.

cc: @alexperovich @ViktorHofer

**Comment by markwilkie** [comment]
@Chrisboh - how would you like to priority this Chris?

**Comment by Chrisboh** [comment]
The feedback from CI Council, and @ViktorHofer please chime in here if I am misspeaking, is for tests that are flaky  they should be moved out of the inner loop and into the outer loop and we should not be clicking retry on test legs.  We do need a better process for running and measuring tests that are always going to be flaky (i.e. UI tests) but the first step is to get them out of our inner loops.

**Comment by ViktorHofer** [comment]
Right wer explicitly don't want an inbuilt retry mechanism anymore. Instead we use our in-code retry helper + what Chris said
