### ISSUE TITLE
darc update-dependencies doesn't preserve file permissions

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/arcade#2862]
Performing a update-dependencies doesn't preserve the executable mode for shell files under common.

![image](https://user-images.githubusercontent.com/19413848/58213787-3f4ef580-7ca8-11e9-88e3-9d31a4b595b0.png)

version 1.1.0-beta.19265.2+5c528b7e6e9ae3892202d0e8ed9a9b2206fc950c

**Comment by alexperovich** [comment]
Were these files manually changed in your repository? `darc update-dependencies` should make the file modes exactly match the equivalent files in dotnet/arcade

**Comment by hoyosjs** [comment]
I just locally issued the update command, no changes were done on the coreclr tree.

**Comment by markwilkie** [comment]
Moving to the dependency flow epic.

**Comment by adiaaida** [comment]
I just wanted to ping this issue. I checked in https://github.com/dotnet/arcade/blob/master/eng/common/performance/performance-setup.sh yesterday, which was picked up automatically by https://github.com/dotnet/performance, however the file permissions didn't propagate to that repo.

**Comment by riarenas** [comment]
I think I understand the problem and we're going to need the correct file permissions to flow for new sh scripts that will restore from private azure artifacts feeds, so taking a look now.

**Comment by riarenas** [comment]
There are two parts to this issue:

1. Automated dependency updates are not keeping file mode. This one is a simple fix, we simply need to respect whatever file mode the file has in Arcade, and flow that. Just to be extra sure that things work correctly for everyone if we make this change, every bash script in Arcade should be set to be an executable file.

2. `darc update dependencies` respects the file mode if the file is already in the git index, but if there are any new files in eng/common, all the command does is write a new file to disk with the contents of the file from Arcade. It won't actually stage the files in the index, so there's no real way for the command to "preserve" the mode.

We could attempt to stage the files for the user, and make sure to preserve the mode by doing that.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade-services/pull/522 should fix the automated dependency update portion of this.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade/issues/2862 for the fix to local update-dependencies.
