### ISSUE TITLE
Investigate what's going on in Symbol Validation

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2871]
We got a few failures in symbol validation in the past few days. I'm disabling that step in our release process until I figure out what's happening and have a fix for it.

Some of the failed releases:

https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=7929
https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=7849
https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=7847

@jcagme @mmitche

**Comment by JohnTortugo** [comment]
The failures observed so far:

```
2019-05-23T02:06:54.2037133Z Validating Microsoft.DotNet.SwaggerGenerator.MSBuild.1.0.0-beta.19272.12.nupkg 
...
2019-05-23T02:07:03.1245831Z 	 Checking file D:\a\r1\a\PrimaryArtifact\Temp\ad341f27-dbed-42b1-bf7e-00151b55ea5e\tools\net472\SharpYaml.dll ... No symbols found on MSDL or SymWeb!
```

**Comment by alexperovich** [comment]
The first failure is not real, that dll is a 3rd party dependency. There is no way we could have produced symbols for it.

**Comment by JohnTortugo** [comment]
Yet, there is symbol for that file in the symbol server. I think the reason is because in the absence of a .symbols.nupkg we just copy the .nupkg for the package and assume the regular module contains embedded PDB info. This is explained here: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Publish.proj#L69

BTW, here is how I check for symbol availability (I also check MSDL):

```
.\SymbolTool\dotnet-symbol.exe --symbols --modules --windows-pdbs --microsoft-symbol-server "C:\temp\SymbolAvailability\Teste\SharpYaml.dll" -o ./TestSymbols
```

**Comment by JohnTortugo** [comment]
Some more info:

At 12:53 I executed the validation and got failure for these 4 packages:
```
Checking file C:\temp\SymbolAvailability\Extract\e845f1b6-4c5b-4e87-be61-da18e8199ba7\tools\net472\Microsoft.DotNet.SwaggerGenerator.CodeGenerator.dll ... No symbols found on MSDL or SymWeb!
Checking file C:\temp\SymbolAvailability\Extract\e845f1b6-4c5b-4e87-be61-da18e8199ba7\tools\net472\Microsoft.DotNet.SwaggerGenerator.MSBuild.dll ... No symbols found on MSDL or SymWeb!
Checking file C:\temp\SymbolAvailability\Extract\e845f1b6-4c5b-4e87-be61-da18e8199ba7\tools\netcoreapp2.1\Microsoft.DotNet.SwaggerGenerator.CodeGenerator.dll ... No symbols found on MSDL or SymWeb!
Checking file C:\temp\SymbolAvailability\Extract\e845f1b6-4c5b-4e87-be61-da18e8199ba7\tools\netcoreapp2.1\Microsoft.DotNet.SwaggerGenerator.MSBuild.dll ... No symbols found on MSDL or SymWeb!
```

Then I executed the symbol publishing: https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=8146

At 12:55 I retried the validation: Still failing
At 13:00 I retried the validation: Still failing
At 13:04 I retried the validation: PASSED

@mikem8361 are you aware of any reason for delays before the symbols be available in the feed?

**Comment by mikem8361** [comment]
I would guess the 10 minute or so delay it is part of the symbol uploading process. I don’t think there is anything on the client side (SymbolUploader) that could change it.  It is certainly way better than the old “CreateRequest.cmd” day or so delay.

**Comment by JohnTortugo** [comment]
These two files together has 100Kb. The whole package they are in has less than 1MB. The PublishSymbols task from Symbol-Uploader finished in about 10 seconds :-/ . 

IIRC these "servers" are backed by AzDO feeds, so I'm considering reach to the AzDO-Artifacts folks to see if they can give more light on this. Do you think that makes sense?

**Comment by jcagme** [comment]
Does this happen only for these two files?

**Comment by JohnTortugo** [comment]
> Does this happen only for these two files?

Yes, and I *think* the reason is because those files are what's really changing from build to build; i.e., the other files are kind of cached somehow... I still need to investigate that as well.

**Comment by JohnTortugo** [comment]
BTW, just got an answer from some folks in an e-mail thread:

> This delay is expected. Hits/misses of symbols to those endpoints are cached for 10 minutes. As such, if your pipeline queries for the symbols right after publishing them (and before the services have finished processing them), the cache will record a miss.

**Comment by dougbu** [comment]
@JohnTortugo where is the cache they mention? If it's similar to the multi-level NuGet cache and is on the client machine somewhere, perhaps we could clear it prior to doing symbol validation&hellip;

**Comment by JohnTortugo** [comment]
> @JohnTortugo where is the cache they mention? If it's similar to the multi-level NuGet cache and is on the client machine somewhere, perhaps we could clear it prior to doing symbol validation…

I understood that would be on the server itself. I included you in the thread.

**Comment by danmosemsft** [comment]
For the purposes of releasing 3.0, are we validating symbols some other way?

**Comment by JohnTortugo** [comment]
I don't think we have any other validation. Maybe we can implement the current known workaround (it will add about 10 min to the build) and live with it until we get something better. What do you think?

Cc'ing some folks that might be interested to comment @mmitche @dougbu @livarcocc

**Comment by ericstj** [comment]
@JohnTortugo can you please provide an update here?  We'd like to enable validation in 3.0 and realistically the cutoff for that is now, given preview9 lockdown and the increased bar there-after.

**Comment by JohnTortugo** [comment]
I didn't work on this any more. I think I've a workaround to mitigate the problem. I'll talk to @markwilkie to work out the priority on this.

**Comment by JohnTortugo** [comment]
Talked with @markwilkie and we are going to approach this validation in a different way. I'll send an e-mail about it shortly.

**Comment by JohnTortugo** [comment]
Just as a note about what was causing the problem: I got confirmation from some folks that there is indeed a caching mechanism in the symbol servers. That caching mechanism was causing the misleading results in the validation script since symbols are available for consumption only about 10 minutes after they are published.
