### ISSUE TITLE
[Signing] Change SignToolData.json file into a better format that merges well.

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#288]
Currently the SignToolData file is a json file which causes merge conflicts when 2 devs add lines due to no trailing commas allowed in json. We should think about changing the format to something like yaml that will merge cleanly when multiple people add lines.

**Comment by JohnTortugo** [comment]
Closing this since we aren't going to use that file anymore. List of containers+files to be signed will be passed as an ItemGroup to the task.
