### ISSUE TITLE
SignValidationExclusionList does not work

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#2888]
I had to disable the async pipelines publishing for aspnet/Blazor because I cannot get  SignValidationExclusionList to work.

I have specified, by file name, the files in Microsoft.AspNetCore.Blazor.Mono which are not supposed to be code-signed. (See https://github.com/aspnet/Blazor/blob/ff7b7c94be74f39d99043a3f5374960d78b76813/eng/Signing.props#L196-L197). Despite this, the signing validation step still fails the build . See https://dev.azure.com/dnceng/internal/_releaseProgress?_a=release-environment-logs&releaseId=8007&environmentId=22188

I suspect the problem is the generation of the signcheck exclusion file:
https://github.com/dotnet/arcade/blob/cb9317c52c891fba6c6c43901ec8621fe2b9bb3b/eng/common/SigningValidation.proj#L54-L59

I think this maybe producing a file that is not in the format signcheck expects.

@JohnTortugo @dougbu @JunTaoLuo

**Comment by natemcmaster** [comment]
Would it be possible to specify the exclusion list directly, instead of generating it? I'm working on converting aspnet/AspNetCore to use Arcade. We already have a sign exclusion file in the right format (see https://github.com/aspnet/AspNetCore/blob/master/eng/signcheck.exclusions.txt). It seems unnecessary to invent an MSBuild API to generate this file when we can just create the file manually.

Also, I couldn't find anyone else using the SignValidationExclusionList item group, so it might be safe to remove this altogether.

**Comment by JohnTortugo** [comment]
> I think this maybe producing a file that is not in the format signcheck expects.

Did you try adding the separators that SignCheck expect?

**Comment by markwilkie** [comment]
@natemcmaster ?

**Comment by natemcmaster** [comment]
Sorry, missed the reply. I didn't try adding the separators yet. I haven't figured out a good way to test signcheck exclusions without pushing to master and hoping for the best.

**Comment by dougbu** [comment]
I don't believe this problem remains. For example, I was able to exclude some sign checks in aspnet/AspNetCore#13899. But, I'm leaving this open in case I'm missing some aspect of the problem.

**Comment by Chrisboh** [comment]
Based on Doug's last comment I am assuming this is fixed.
