### ISSUE TITLE
Analyze the build dependency on releases

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2893]
Today each release depends on a build. Given that we will need to run the `gather drop` command of `darc` we might need to copy `darc-init.ps1` so we can install the darc and execute useful commands.

The best approach is to use arcade's version since it is the latest at all times, this means we'd need to execute a release using a build from arcade but allowing to input a core-sdk version and channel that then darc will use to generate the drop.

**Comment by riarenas** [comment]
This shouldn't matter as much anymore now that the darc install script uses the unauthenticated endpoint that returns the matching production version of prod.
