### ISSUE TITLE
[QCR][Validation ring] Create release validation release

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2894]
Create the release and add the required tasks defined in https://github.com/dotnet/arcade/blob/master/Documentation/ReleaseRingsPlan.md#release-validation-ring-release-validation-channel.

In case tasks not defined in the doc are required we'd need to update the docs.

**Comment by jcagme** [comment]
The validation ring is now part of the main release pipeline and we are still adding task to it but the main shell is in place

**Comment by markwilkie** [comment]
this is great.  which mainline repos (if any) is this turned on for?

**Comment by jcagme** [comment]
This will be repo agnostic since the input is a build candidate (file drop) that can be generated from any BAR ID or repo+commit-sha, so in theory it should work for any repo from which we can generate a file drop
