### ISSUE TITLE
Make DiaSymReader.Converter use SourceLink

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2898]
Current Arcade builds would fail with this:

```
Validating Microsoft.DotNet.GenFacades.1.0.0-beta.19271.7.symbols.nupkg ...
        File tools/net472/Microsoft.DiaSymReader.Converter.dll has broken links:
                Failed to retrieve https://raw.githubusercontent.com/dotnet/symreader-converter/420f4bfaaf7e423c537d88db2b5f65ab4f3c7b24/artifacts/obj/Microsoft.DiaSymReader.Converter/Release/net45/Microsoft.DiaSymReader.Tools.ConverterResources.cs (700)

        File tools/netcoreapp2.1/Microsoft.DiaSymReader.Converter.dll has broken links:
                Failed to retrieve https://raw.githubusercontent.com/dotnet/symreader-converter/420f4bfaaf7e423c537d88db2b5f65ab4f3c7b24/artifacts/obj/Microsoft.DiaSymReader.Converter/Release/netstandard1.3/Microsoft.DiaSymReader.Tools.ConverterResources.cs (700)
```

We need to make Microsoft.DiaSymReader.Converter use SourceLink so we can consume it in Arcade.GenFacades and have Arcade builds pass source link validation.

**Comment by tmat** [comment]
Why are we validating source link of dependencies?

**Comment by tmat** [comment]
What if we have a dependency on 3rd party lib that doesn't have source link?

**Comment by JohnTortugo** [comment]
That's a good point.

In this case this a SymReader-Converter DLL got copied into one of Arcade .symbols.nupkg

**Comment by tmat** [comment]
Perhaps we need exclusion list?

**Comment by JohnTortugo** [comment]
The validation don't require that a file has source link info. It only require that if there is such info, the links are accessible. I think for the current issue the best option is to fix the info is SymReader-Converter but probably the long term solution is to add the exclusion list feature. What do you think?

**Comment by tmat** [comment]
Then I don't understand why are you sending PR that adds source link if the source link is already there :-|?

**Comment by JohnTortugo** [comment]
I failed to look that `RepoToolset` was already including that for the repo! :-/

**Comment by JohnTortugo** [comment]
@tmat can you please tell me where is the build-definition for symreader-converter ?

**Comment by tmat** [comment]
@JohnTortugo I kicked off a new build.

**Comment by tmat** [comment]
https://dotnet.myget.org/feed/symreader-converter/package/nuget/Microsoft.DiaSymReader.Converter/1.1.0-beta1-64128-01
