### ISSUE TITLE
On board release branches to async releases pipelines

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2904]
Today the async release validation just runs on master and release runs don't have the additional validation checks before publishing to the feeds. We need to make the move so when Tactics chooses a build from release it has been already validated.

**Comment by riarenas** [comment]
Release and master branches are now using the YAML stages publishing that run the pre-publish validation.

Is there anything else this issue was capturing, or do you think it's good to close @jcagme?

**Comment by riarenas** [comment]
Keeping this alive until we have completely removed the async publishing release pipelines. Might go away once that is complete

**Comment by jcagme** [comment]
@riarenas do we still need this?

**Comment by riarenas** [comment]
Nope
