### ISSUE TITLE
Arcade SourceLink Failures

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2912]
Looks like something changed in Arcade.SDK recently and is causing source link validation to fail:

```
Validating Microsoft.DotNet.Arcade.Sdk.1.0.0-beta.19279.1.symbols.nupkg ...
        File tools/net472/Microsoft.DotNet.Arcade.Sdk.dll has broken links:
                Failed to retrieve https://raw.githubusercontent.com/dotnet/arcade/ea6addfdc65e5df1b2c036f11614a5f922e36267/.packages/microsoft.bcl.json.sources/4.6.0-preview4.19202.2/contentFiles/cs/netstandard2.0/Microsoft.Bcl.Json.Sources/SR.cs (700)
                Failed to retrieve https://raw.githubusercontent.com/dotnet/arcade/ea6addfdc65e5df1b2c036f11614a5f922e36267/.packages/microsoft.bcl.json.sources/4.6.0-preview4.19202.2/contentFiles/cs/netstandard2.0/Microsoft.Bcl.Json.Sources/System.SR.cs (700)
                Failed to retrieve https://raw.githubusercontent.com/dotnet/arcade/ea6addfdc65e5df1b2c036f11614a5f922e36267/.packages/microsoft.bcl.json.sources/4.6.0-preview4.19202.2/contentFiles/cs/netstandard2.0/Microsoft.Bcl.Json.Sources/BitStack.cs (700)
....
```

The XUnitConsoleRunner package is also failing the validation (this one seems to be a problem related to git submodules + sourcelink links):

```
Validating Microsoft.DotNet.XUnitConsoleRunner.2.5.1-beta.19279.1.symbols.nupkg ...
        File tools/netcoreapp2.1/xunit.core.dll has broken links:
                Failed to retrieve https://raw.githubusercontent.com/xunit/xunit/ad20ed120a3653d6af533b76cf8a04f096095349/src/xunit.assert/Asserts/Sdk/ArgumentFormatter.cs (700)
                Failed to retrieve https://raw.githubusercontent.com/xunit/xunit/ad20ed120a3653d6af533b76cf8a04f096095349/src/xunit.assert/Asserts/Sdk/AssertEqualityComparer.cs (700)
                Failed to retrieve https://raw.githubusercontent.com/xunit/xunit/ad20ed120a3653d6af533b76cf8a04f096095349/src/xunit.assert/Asserts/Sdk/AssertEqualityComparerAdapter.cs (700)
```
@tmat @ViktorHofer

**Comment by tmat** [comment]
I don't see how this could have worked before. Microsoft.Bcl.Json.Sources source package does not have Source Link targets in it. So that'd be a work item for CoreFX. 

XUnit is [using](https://github.com/xunit/xunit/blob/c54cc52ffb275c81afed022521870193bbca6c39/src/Directory.Build.props#L29) `SourceLink.Create.CommandLine` package, which does not support submodules. The files in [src/xunit.assert](https://github.com/xunit/xunit/tree/c54cc52ffb275c81afed022521870193bbca6c39/src/xunit.assert) are fetch from a submodule.

**Comment by ViktorHofer** [comment]
The xunit.core.dll thing is indeed a bug as it shouldn't be part of the package at all. I will exclude it.

**Comment by JohnTortugo** [comment]
Thanks folks. @tmat I'll look why the error was not showing up before and post here.

**Comment by danmosemsft** [comment]
> Microsoft.Bcl.Json.Sources source package does not have Source Link targets in it. So that'd be a work item for CoreFX.

We now publish a binary package instead. Maybe updating to that will fix it. @ahsonkhan

**Comment by tmat** [comment]
@danmosemsft But isn't Microsoft.Bcl.Json.Sources still gonna be used for apps that do not target Core 3.0?

**Comment by ahsonkhan** [comment]
> But isn't Microsoft.Bcl.Json.Sources still gonna be used for apps that do not target Core 3.0?

No, we have a binary netstandard2.0 compatible package which can work for apps that do not target Core 3.0. We will likely deprecate the source package (`Microsoft.Bcl.Json.Sources`).
https://www.nuget.org/packages/System.Text.Json

cc @terrajobst

**Comment by tmat** [comment]
OK.

**Comment by danmosemsft** [comment]
Is there a work item here to switch Arcade over and if so who is that for? 😺

**Comment by JohnTortugo** [comment]
> Is there a work item here to switch Arcade over and if so who is that for? 😺

I don't think there is. The introduction of this package in Arcade was done just a few days ago: https://github.com/dotnet/arcade/pull/2343/files . 

Does the two packages have the same API ? :-)

**Comment by ahsonkhan** [comment]
> Does the two packages have the same API ? :-)

Similar, but the source package is an older snapshot (since we stopped publishing that one). We have made some changes/additions to the APIs since then.

**Comment by markwilkie** [comment]
Suggested next steps @ahsonkhan ?  @JohnTortugo - is SourceLink still busted?

**Comment by JohnTortugo** [comment]
Yeah, as long as use that package it won't work. We need to either make Arcade.SDK use the newer library or implement some workaround in the source link checker (which I don't want to)

**Comment by danmosemsft** [comment]
I think @chcosta probably should revise his change to use the correct (binary) library.

**Comment by chcosta** [comment]
A "few days ago" is a month ago and was based on guidance from the CoreFx team (sorry, this has probably been broken for a month!).  @MattGal is this something that FR can update?

**Comment by chcosta** [comment]
@JohnTortugo , what's the priority of getting this fixed?

**Comment by JohnTortugo** [comment]
This is not a blocking issue. Also not high priority. But we need to fix it soon so I can enable the automated validation in place again and prevent other people from unknowingly add/use other source-link-wise broken libs.

**Comment by riarenas** [comment]
@JohnTortugo I see that #3353 was merged. What is left here?

**Comment by ViktorHofer** [comment]
The `XUnitConsoleRunner` issue is resolved.

**Comment by JohnTortugo** [comment]
> @JohnTortugo I see that #3353 was merged. What is left here?

I actually had to revert that PR. Right now SourceLink validation is disabled for Arcade and Arcade.SDK still use `microsoft.bcl.json.sources`. We need to keep this issue.

**Comment by riarenas** [comment]
Ack

**Comment by JohnTortugo** [comment]
I can try and use some cycles next week to look into this.

**Comment by riarenas** [comment]
(Not a priority. If it's not straightforward no rush)

**Comment by markwilkie** [comment]
I'm pretty sure that source link validation is being done as part of #2891.  

@JohnTortugo - can you confirm this is only a validation issue?
@jcagme - can you confirm that this is being handled?

If both assumptions are true, please close.

**Comment by jcagme** [comment]
Yes, https://github.com/dotnet/arcade/issues/3735

**Comment by danmosemsft** [comment]
@markwilkie having trouble keeping track of the short term work - I know that "rings" tracked by #2891 will give us long term validation, but for immediately coming previews, is it clear how symbols and sourcelink validation will happen ?

**Comment by JohnTortugo** [comment]
> I'm pretty sure that source link validation is being done as part of #2891.
> 
> @JohnTortugo - can you confirm this is only a validation issue?
> @jcagme - can you confirm that this is being handled?
> 
> If both assumptions are true, please close.

This issue is for fixing the SourceLink validation of Arcade builds; it's not an error in the validation script. The Arcade SDK is using a version of [Json library](https://github.com/dotnet/arcade/issues/2912#issuecomment-497199061) that [doesn't have sourcelink information available](https://github.com/dotnet/arcade/issues/2912#issuecomment-497089781).

**Comment by garath** [comment]
Triage: Can switch to System.Text.Json binary package.
