### ISSUE TITLE
Support signing assemblies in .tar.gz files

### ISSUE THREAD

**Issue by eerhardt** [dotnet/arcade#2915]
Related to #941.

We currently don't support signing the managed assemblies in a `.tar.gz` file. This scenario is used by .NET for Apache Spark (see conversation [here](https://github.com/dotnet/spark/pull/124#discussion_r288750148)).

Because of this, dotnet/spark currently needs to sign first, and then package the "Worker" application into `.zip` and `.tar.gz` files after signing. If arcade supported signing the assemblies inside of `.tar.gz` files, then we could simplify dotnet/spark's build even further and create the "Worker" packages at the same time we create the NuGet packages. And then signing would come later on the NuGet packages, .zip files and .tar.gz files.

**Comment by markwilkie** [comment]
cc/ @JohnTortugo

**Comment by JohnTortugo** [comment]
That looks interesting. 

I'm curious why you're the only one asking for this. If there are other repos that ship files in tar.gz this feature will be even more useful.

**Comment by eerhardt** [comment]
I know that the .NET Core SDK ships managed assemblies in a .tar.gz file.

In general, I would think anyone who is shipping an application on non-Windows would want to have managed assemblies in a .tar.gz file.

**Comment by markwilkie** [comment]
Microbuild is working on support for linux signing.  @JohnTortugo - is there more work to do to support tar.gz?

**Comment by eerhardt** [comment]
> is there more work to do to support tar.gz?

@jaredpar and @tmat can correct me if I'm wrong, but arcade's SignTool will automatically open `.zip` and `.nupkg` files, sign all the assemblies in them, and then repackage the `.zip` and `.nupkg` files with the signed assemblies in them. The work here would be to do the same thing for `.tar.gz` files.

See https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Signing.md#sign-tool.

Note also - for `dotnet/spark` the builds are happening on Windows machines. But they are publishing for both `win-x64` and `linux-x64` from the same Windows machine.

**Comment by JohnTortugo** [comment]
@markwilkie - it's what @eerhardt said, Arcade SignTool currently can't open .tar.gz files to process their content. That's the major (only one I guess) change that need to worked on.

**Comment by markwilkie** [comment]
Thanks - how expensive do you think @JohnTortugo ?  Seems we've got a hard deadline by the end of this month?

**Comment by JohnTortugo** [comment]
It doesn't seem like a lot of work Mark. I'll schedule some time to do a better investigation (prototype?) on this and update this issue back. I expected to come back with news before Tue.

**Comment by JohnTortugo** [comment]
@eerhardt I'm looking for some input files to test my changes. Are these good as any https://dnceng.visualstudio.com/internal/_build/results?buildId=226201&view=artifacts, right?

**Comment by eerhardt** [comment]
They should be good, except that the assemblies in them are probably already signed. So you may want to sign with a different certificate to ensure it is acting appropriately (if you are fully testing end-to-end).

**Comment by eerhardt** [comment]
You could build them locally if you want.

1. Clone dotnet/spark
2. `.\build.cmd -pack /p:PublishSparkWorker=true /p:SparkWorkerPublishDir=C:\temp\Spark`
3. `.\build.cmd -publish /p:SparkWorkerPublishDir=C:\temp\Spark /p:SparkWorkerPackageOutputDir=C:\temp\Spark-out`

Where `C:\temp\Spark` is the intermediate directory where the worker is published to.  And `C:\temp\Spark-out` is where the `.tar.gz` files should be written to.

**Comment by JohnTortugo** [comment]
Thanks, that'll be helpful.

**Comment by Chrisboh** [comment]
@markwilkie / @mmitche do you know if this is still an issue?

**Comment by mmitche** [comment]
Would be nice. Not a direct requirement at this point but probably will be at some point.

**Comment by eerhardt** [comment]
The good thing is that in .NET 7 we added [TarReader](https://learn.microsoft.com/en-us/dotnet/api/system.formats.tar.tarreader) and [TarWriter](https://learn.microsoft.com/en-us/dotnet/api/system.formats.tar.tarwriter) classes. So adding this support should be easier now since you can read and write tar files easily in .NET.
