### ISSUE TITLE
[darc] gather-drop doesn't work

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2922]
`darc gather-drop` appears broken at the moment:

```
darc gather-drop --commit 48cb2abb441bfa3affbcd9ae0988af05b2416e03 -o test/ --repo https://github.com/aspnet/Extensions

Determining what builds to download...
Looking up builds of https://github.com/aspnet/Extensions@48cb2abb441bfa3affbcd9ae0988af05b2416e03
Root build - Build number 20190529.7 of https://dev.azure.com/dnceng/internal/_git/aspnet-Extensions @ 48cb2abb441bfa3affbcd9ae0988af05b2416e03

Gathering drop for build 20190529.7 of https://github.com/aspnet/Extensions
  Downloading asset assets/symbols/Microsoft.JSInterop.3.0.0-preview6.19279.7.symbols.nupkg
    Failed to download asset, errors shown below:
      Blob uri 'https://dev.azure.com/dnceng/internal/_apis/build/builds/204820/artifacts for assets/symbols/Microsoft.JSInterop.3.0.0-preview6.19279.7.symbols.nupkg is of an unknown type
      Asset 'assets/symbols/Microsoft.JSInterop.3.0.0-preview6.19279.7.symbols.nupkg' has inconsistent location types (Container vs. None)
Aborting download.
Failed to download build with id 12661
```

**Comment by mmitche** [comment]
@JohnTortugo 

Can we get a check in the release pipelines that runs gather-drop?

**Comment by JohnTortugo** [comment]
Sure, I'll take a look

**Comment by JohnTortugo** [comment]
@jcagme do you think this might be related to this change: https://github.com/dotnet/arcade/commit/18d4250c1f5cdb7be1dcbe14830122ac6483a83d ?

**Comment by JohnTortugo** [comment]
Yeah, looking in BAR the first asset that has "location type == 0" is from this build: https://dnceng.visualstudio.com/internal/_build/results?buildId=198270

**Comment by JohnTortugo** [comment]
The problem here is in the communication with Maestro API. [This line here](https://github.com/dotnet/arcade-services/blob/2fd929502e9dab108af49a2e27c86a0b312f94e6/src/Maestro/Client/src/Generated/Assets.cs#L416) is adding the locationType to the query including the quotes, like so:
```
https://maestro-prod.westus2.cloudapp.azure.com/api/assets/1287284/locations?location=index.json&assetLocationType="nugetFeed"&api-version=2019-01-16
```

but if I try it on swagger (and there the location get added correctly to BAR), locationType is added to the query without the quotes, like so:

```
https://maestro-prod.westus2.cloudapp.azure.com/api/assets/1287284/locations?location=index.json&assetLocationType=nugetFeed&api-version=2019-01-16
```

**Comment by JohnTortugo** [comment]
@mmitche is there a fix for this already?

**Comment by mmitche** [comment]
Yes, in only in the INT client though.

**Comment by JohnTortugo** [comment]
PR with the fix in SwaggerGenerator got merged.

I'll now update Maestro.Client to use the newer swagger generator, etc.
