### ISSUE TITLE
Cannot have a hello world Arcade project with test project on macOS

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#2928]
I am setting up a brand new hello world project with Arcade. However, I hit a very strange blocker. 

In [this](https://github.com/dotnet/cli-lab/tree/12336fa0e9fbfa968d2c12b2bcf24a51d1068f43) test run on OSX, as long as I have a project with name “Test”, it will fail with “NuGet.targets(119,5): error : Invalid argument”.

branch https://github.com/dotnet/cli-lab/tree/testci

@chcosta

**Comment by chcosta** [comment]
This looks like https://github.com/NuGet/Home/issues/7908, which was fixed in newer versions of NuGet

**Comment by wli3** [comment]
@nkolev92 is this the same error? It looks different. Which version does not have the bug?

This is an argument exception for creating "dotnet-cli-lab\artifacts\obj\DotnetUninstallTests"

**Comment by nkolev92** [comment]
I don't know if it's the same issue. I've never seen that manifestation of it. 

2.2.300 should have the fix.

**Comment by wli3** [comment]
2.2.300 worked! Thanks @chcosta @nkolev92 for looking into this!
