### ISSUE TITLE
Support package harvesting from servicing releases

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#2929]
- [ ] Permit harvesting files from a specific servicing branch.  Instead of taking "latest version" take the latest version from that branch.
- [ ] Flow servicing version information from package index in Servicing branch to upstream servicing branches and master.
   - Central store. eg: dotnet-versions, nuget feed(s)
   - Flow index package across branches and merge indexes.  We would need to look at the merge semantics here as they are very fragile.  Perhaps we can add merge-policy to the 
- [ ] Download multiple versions of the same package.  Calls a target in all pkgproj's to report the packages they need to harvest and downloads those packages. Hypothetical solution: group packages by major.minor and reference those packages in a TFM with matching major.minor in a single project file.
- [ ] Catch cases where we are harvesting an asset that is older than the latest live built asset.  Download latest version for all PackageBands (Major.Minor).  Generate a package-report for all downloaded packages.  For every target in the latest package report, examine the target in the past package reports and ensure *none* of them had a higher file version.

Open: should we enable harvesting pre-release (when building pre-release?)

```
    <HarvestIncludePaths Include="lib/net46;runtimes/win/lib/net46" PackageBand="4.3" />
    <HarvestIncludePaths Include="runtimes/win/lib/netstandard1.3;lib/netstandard1.3" PackageBand="4.3" />
```

Implementation notes:
Target to read HarvestIncludePaths and compute actual package versions based on index.  Input: HarvestIncludePaths Output: HarvestIncludePaths with PackageVersion metadata.

Manual solution:
1. Make sure we manually flow stable versions / packageIndex data between servicing branches.
2. When we update a library in 1.x and 2.x and the 2.x package harvests assets that were built in 1.x we need to explicitly pick up the files from the 1.x servicing 
3. Rather than add support in packaging infra for this, we could use raw file elements in the PkgProjs and then use hand authored depproj's to do the restoring.

**Comment by jcagme** [comment]
Hey @ericstj. Is harvesting different from dependency flow? While this is not currently supported, we are working on making this possible. Things would look the same as the dependencies we flow day to day with private feeds involved, flowing the endpoints, among others.

**Comment by ericstj** [comment]
@jcagme This is for packaging, nothing to do with dependency flow nor any asks for dependency flow at the moment.  We may want to use dependency flow to implement part of this work but this issue is tracking early thinking on this.

**Comment by jcagme** [comment]
Sweet. Thanks for clarifying!

**Comment by ericstj** [comment]
Closing since we've eliminated the use of this feature and don't intend to develop it further.
