### ISSUE TITLE
Build failing because of Signtool Error

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/arcade#2936]
```
##[error].packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19303.8\tools\Tools.proj(0,0): error NU3027: Package 'Microsoft.DotNet.SignTool 1.0.0-beta.19303.8' from source 'https://dotnetfeed.blob.core.windows.net/arcade-validation/index.json': The signature should be timestamped to enable long-term signature validity after the certificate has expired.
```
https://dev.azure.com/dnceng/internal/_build/results?buildId=210368&_a=summary

 /cc @dotnet/wpf-developers 
/cc @mmitche

**Comment by mmitche** [comment]
@dotnet/dnceng Have you seen this error before?

**Comment by JohnTortugo** [comment]
I guess I've seen that in the past when a build was trying to use a binary only test signed.

**Comment by vatsan-madhavan** [comment]
This didn't even build anything. During restore, the SignTool package is identified as being problematic. 

Arcade does have a bug - in that it doesn't do test-signing correctly. I have reported this in the past (and it has been won't fixed). That said, it's not clear whether the problem is rooted in that particular problem (i.e., whether SignTool package is itself (inadvertently?) test-signed, and thus has an invalid signature-validity period) - perhaps someone can confirm this?

**Comment by jcagme** [comment]
@vatsan-madhavan as a side question, is there any reason you restore from `https://dotnetfeed.blob.core.windows.net/arcade-validation/index.json`? Is worth mentioning things published there have not yet been validated and could lead to the use of versions with bugs in them. The endpoint recommended to be used is https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json

**Comment by JohnTortugo** [comment]
> Arcade does have a bug - in that it doesn't do test-signing correctly. I have reported this in the past (and it has been won't fixed).

@vatsan-madhavan  - Can you please point me to the issue?

**Comment by vatsan-madhavan** [comment]
> @vatsan-madhavan as a side question, is there any reason you restore from `https://dotnetfeed.blob.core.windows.net/arcade-validation/index.json`? Is worth mentioning things published there have not yet been validated and could lead to the use of versions with bugs in them. The endpoint recommended to be used is https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json

https://github.com/dotnet/wpf/blob/73f83d93a9e002f857c304d5f0345347f38ee0c3/eng/common/PublishToPackageFeed.proj  has the only reference to `https://dotnetfeed.blob.core.windows.net/arcade-validation/index.json`. We are not using that feed intentionally.

**Comment by vatsan-madhavan** [comment]
> > Arcade does have a bug - in that it doesn't do test-signing correctly. I have reported this in the past (and it has been won't fixed).
> 
> @vatsan-madhavan - Can you please point me to the issue?

https://github.com/dotnet/arcade/issues/2304

**Comment by JohnTortugo** [comment]
> https://github.com/dotnet/wpf/blob/73f83d93a9e002f857c304d5f0345347f38ee0c3/eng/common/PublishToPackageFeed.proj has the only reference to `https://dotnetfeed.blob.core.windows.net/arcade-validation/index.json`. We are not using that feed intentionally.

I think this is a configuration that is coming from Arcade.SDK; https://github.com/dotnet/arcade/blob/7b1d2758170afb015b0577246f0928f38c83037c/src/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj#L26 . I'm inclined that we actually don't need that feed in that place.

Nevertheless, both feeds should only have 'real' signed packages.

**Comment by vatsan-madhavan** [comment]
> I'm inclined that we actually don't need that feed in that place.
Nevertheless, both feeds should only have 'real' signed packages

So we wait for Arcade to fix this?

**Comment by JohnTortugo** [comment]
We should understand why this package is failing. In the meantime can you give a try to another version of the SDK? For instance: Arcade.Sdk.1.0.0-beta.19303.9 ?

**Comment by vatsan-madhavan** [comment]
that worked - https://github.com/dotnet/wpf/pull/829

**Comment by rainersigwald** [comment]
I'm seeing this with `"Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.19306.12"`, using the normal feed:

```
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19306.12\tools\Tools.proj : error NU3027: Package 'Microsoft.DotNet.SignTool 1.0.0-beta.19306.12' from source 'https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json': The signature should be timestamped to enable long-term signature validity after the certificate has expired.
```

https://dev.azure.com/dnceng/public/_build/results?buildId=215988&view=logs&jobId=1522e9b9-b859-5e5f-ec86-a68fc9508baf&taskId=a8d37b2d-1a39-51d6-c11e-8665c8c9811e&lineStart=23&lineEnd=24&colStart=1&colEnd=1

**Comment by joeloff** [comment]
Are those signed with a test certificate? if they were signed with the official service there should be a timestamp check to verify the files before they're returned, unless validation is turned off in the request send to the sign service. I've only seen this sort of error when the signing machine doesn't have a timestamp service configured.

**Comment by vatsan-madhavan** [comment]
I have another instance of the bug here: https://dev.azure.com/dnceng/public/_build/results?buildId=215980

Can this issue be actively investigated to resolution, alongwith a fix for #2304 as well ?

**Comment by riarenas** [comment]
@dotnet/dnceng for visibility.

@JohnTortugo any ideas here? This doesn't seem to repro consistently, as other repos were able to restore this same version of the sdk without errors.

**Comment by JohnTortugo** [comment]
No clue right now. Needs more investigation.

**Comment by vatsan-madhavan** [comment]
I'm wondering if reactivating and solving #2304 would be a better approach here? If the signatures don't have a problem to start with, then restoring wouldn't have a problem either...

**Comment by JohnTortugo** [comment]
As per [your comment here](https://github.com/dotnet/arcade/issues/2304#issuecomment-475446932) I thought that was a solved issue. I don't think we should add timestamp to `test certificates`. We shouldn't ship or use test signed binaries.

**Comment by JohnTortugo** [comment]
From your links these are the packages affected so far: 

- Microsoft.DotNet.Arcade.Sdk 1.0.0-beta.19306.12
- Microsoft.DotNet.SignTool 1.0.0-beta.19303.8

**Comment by vatsan-madhavan** [comment]
My comment in #2304 indicated that I was inadvertently test-signing something when I should have been real-signing it. Arcade still has a bug - namely failure to correctly timestamp test-signed packages. 

We shouldn't ship test signed packages - true
We shouldn't use test signed packages - why? this claim makes no sense. Test signed packages exist for testing - we can and should be able to use these. 
We shouldn't timestamp test signed packages - this sounds like a bug.

**Comment by JohnTortugo** [comment]
@vatsan-madhavan thanks for your input. I'll create an e-mail thread later so we can discuss about your point of view. As a matter of fact, the certificate management is done by a different team.

**Comment by JohnTortugo** [comment]
From a quick manual/visual inspection of the files' certificate info it looks like the certificates are actually correct. They even look like real signed binaries. Furthermore, SignCheck was run on all these files and passed the validation.

I'm doing further investigations and talking with @joeloff how we can obtain more info about the files' signature status, etc.

**Comment by vatsan-madhavan** [comment]
![image](https://user-images.githubusercontent.com/20246435/59137266-d02a0000-893b-11e9-8b92-51bfe80d1db5.png)

**Comment by markwilkie** [comment]
Thanks @JohnTortugo - let us know what you find.

**Comment by vatsan-madhavan** [comment]
@JohnTortugo and I ended up debugging this last Friday and we have a better understanding of what happened. there were 3 different bugs that lead to this problem, I think (@JohnTortugo please correct me if I'm wrong. I'll defer to you for some of the details - I'll outline the main points here as I understand it). 

- **Two packages were produced with an identical version number and published to the same feed on the same channel** (!) 
  - Commit #1: https://github.com/dotnet/arcade/commit/fec3cd8a6c34fd2123c5e918fe67691b22b72ef1
  - Commit #2 (private branch): https://github.com/dotnet/arcade/commit/722086a06129c9d5784671f3fafd3961a6a2e95d
   - _There seems to be a potential for version number clash/overlap - which seems like the primary root-cause of the problem._ 
- One of these packages (commit #2) was inadvertently published to a public feed and onto a public channel. 
  - This was a private development bug (i.e.,, not a bug in the product per se, but perhaps a suboptimal convention). 
- The package for Commit #2 suffered from the bug outlined in #2304 
  - Because it was test-signed, it's signature had (has) a flaw.

**Comment by JohnTortugo** [comment]
Let me try adding some more details & explain how it happened:

- In my work on new publishing using YAML I use a build-definition to test the changes.
- That build definition only _test_ sign packages.
- I had modified that build-def to only produce two packages: SignTool & Arcade.SDK
- **The bug:** at one point I published (by mistake) the packages produced by that build definition to dotnetfeed/dotnet-core
  - Incidentally the packages published by this new build definition had a version number published by the official arcade build definition.
    - Once Maestro delivered an update to the affected repos their build tried to use the test signed packages produced incorrectly by my YAML build-definition.

**Comment by vatsan-madhavan** [comment]
> He thinks we should add a timestamp to the Test certificates.
> we'll kind of end up with two "real" signing modes.

That's more or less correct. The _mechanics_ of signing should not change whether we are using _test_ or _real_ certs. We treat _real_ certs as _precious artefacts_, and assets signed with those have a certain _(very high)_ trust-value; assets signed with _test certs_ lack such high-trust value, but allow us to exercise the engineering pipeline the exactly the same way as we'd do with real-signed assets. This is the _purpose_ of test-signing - to simulate engineering processes at will. To do so effectively, we need the signing process to be identical (to that of real-signing) as well. 

Besides, timestamping vs not-timestamping is not a process/policy-decision. It is a matter of _technical correctness_. In this instance, the absence of timestamp makes the package signing process suspect, and the tools that inspect this package (like `nuget`) say so with an error message. 

> I believe the current mechanism assumes no two build-definition would produce the same packages

We typically have at least two branches per repo (`master`, `release/3.0`) that concurrently produce packages that are named similarly - this is a common pattern across .NET Core repos. They have different _branding_ and are linked to different _channels_; nevertheless, repos tend to have multiple build definitions that produce similarly named packages. Two different build-instances that produce identical version numbers <= this seems like a surprising situation to me. 

/cc @tmat

**Comment by markwilkie** [comment]
@vatsan-madhavan - am I understanding this correctly that the situation that sparked this discussion is the fact that two identical arcade sdk packages were published by mistake?  (I want to make sure the main issue is addressed)

Regarding test vs real signing.  What scenario are you wanting test signing to work for @vatsan-madhavan ?  I want to make sure we're covering what's needed.

**Comment by vatsan-madhavan** [comment]
Yeah, two identical packages were published - this indeed turned out to be the main root-cause. 

As to test-signing, WPF has a [test repo](https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-test) (internal only for now) and we expect to produce test-signed packages out of it. We'd like test-signing to work correctly so that packages produced from this repo could be restored etc. without problems. I'll be happy to  wait and raise this issue again soon when it becomes an imminent problem for us, although it would be great it the problem can be fixed sooner. /cc @rladuca

**Comment by JohnTortugo** [comment]
@vatsan-madhavan - I created this other issue https://github.com/dotnet/arcade/issues/3024 to discuss about your requirements for test signing specifically. 

Do you think the current issue can be closed? Do you want me to create an issue for discussing your concerns about package versioning?

**Comment by vatsan-madhavan** [comment]
I'm ok with closing this issue. 

My sense is that the versioning scheme in place today can lead to a repetition of this kind of problem under different circumstances - even if only rarely - and each one of them will likely require painstaking sleuthing to root-cause. I will defer to you to decide whether you consider the scheme in place to be defective to decide whether it warrants an issue or not.

**Comment by JohnTortugo** [comment]
Closing. Created this issue to discuss about versioning: https://github.com/dotnet/arcade/issues/3044

**Comment by mmitche** [comment]
> > He thinks we should add a timestamp to the Test certificates.
> > we'll kind of end up with two "real" signing modes.
> 
> That's more or less correct. The _mechanics_ of signing should not change whether we are using _test_ or _real_ certs. We treat _real_ certs as _precious artefacts_, and assets signed with those have a certain _(very high)_ trust-value; assets signed with _test certs_ lack such high-trust value, but allow us to exercise the engineering pipeline the exactly the same way as we'd do with real-signed assets. This is the _purpose_ of test-signing - to simulate engineering processes at will. To do so effectively, we need the signing process to be identical (to that of real-signing) as well.
> 
> Besides, timestamping vs not-timestamping is not a process/policy-decision. It is a matter of _technical correctness_. In this instance, the absence of timestamp makes the package signing process suspect, and the tools that inspect this package (like `nuget`) say so with an error message.
> 
> > I believe the current mechanism assumes no two build-definition would produce the same packages
> 
> We typically have at least two branches per repo (`master`, `release/3.0`) that concurrently produce packages that are named similarly - this is a common pattern across .NET Core repos. They have different _branding_ and are linked to different _channels_; nevertheless, repos tend to have multiple build definitions that produce similarly named packages. Two different build-instances that produce identical version numbers <= this seems like a surprising situation to me.
> 
> /cc @tmat

@vatsan-madhavan Are you saying you're using the different build defininitions for different branches?

You should not have two build definitions producing the the same package for 3.0 and beyond.  The version suffix is tied to the build number, which will be unique for any given build definition, across across branches

**Comment by vatsan-madhavan** [comment]
> Are you saying you're using the different build defininitions for different branches?

> You should not have two build definitions producing the the same package for 3.0 and beyond. The version suffix is tied to the build number, which will be unique for any given build definition, across across branches

@mmitche Depends on what you mean by 'build definition' I think we use the same AzDo pipeline definition, but the corresponding `yml` can indeed differ sometimes.  At this time, our release/3.0 `yml` is a bit different that the master one because we made a change to the build-pools in master (but waited to make the same change to release/3.0 until preview 6 stabilized). 

There will be times when we try to prototype a big change that requires build `yml` changes. 

Chances are good that in .NET 5, master will see changes to build `yml` that will not be applicable to 3.0 branches.

**Comment by mmitche** [comment]
Right.  Yaml changes never require another build pipeline. You can just make changes in the appropriate branch, as the yaml build logic is always read from the branch being build. The build pipeline itself had unique build numbers regardless of branch (e.g. if master builds as 1, then release,/3.0 builds, it will be given number 2).

**Comment by rainersigwald** [comment]
^ assuming you use the default, bad, build numbers.

**Comment by vatsan-madhavan** [comment]
@JohnTortugo, in your case when two packages were produced, I'm assuming that they happened on different build-definitions? If so, I think that would explain the problem... 

Perhaps the learning here is that prototyping changes etc. are best done on a branch in the same repo, using the same build-pipeline/definition - this would avoid surprises.

**Comment by JohnTortugo** [comment]
> @JohnTortugo, in your case when two packages were produced, I'm assuming that they happened on different build-definitions? If so, I think that would explain the problem...

Yes, different build definitions.

**Comment by mmitche** [comment]
> ^ assuming you use the default, bad, build numbers, or ensure that your customized build number includes `$(Rev:.r)`

What are your thoughts on this? We evaluated this a while back and the revision is the preferred way to go for .NET which avoids major issues vs. a "stable" build number like one involving the git commit depth.

**Comment by rainersigwald** [comment]
I really dislike the default `YYYYMMDD.r` versions, because they lose valuable information about what's building. I think it would be valuable to get the Pipeline version to match the build output's version, like `Major.Minor.Patch-preview.YYYYMMDD.r`, especially in a forked development situation like near release where we're very likely to have multiple trains (16.1 development in master, 16.0 stabilization builds) running simultaneously.

It's easy to set a new version number with `##vso[build.updatebuildnumber]build number`, but I don't know how to ensure that's unique, since I think revision of the initial version gets reset if prior builds renumbered.

(One wrinkle here that bit us in the past: the VS systems that handle inserted components had very restrictive rules about version numbers; we had to adjust ours to accommodate. I'm not sure what I'm hoping for above would fly through all the systems.)

**Comment by mmitche** [comment]
Ahh, I gotcha.  Agreed the UI is rough in this case.

With `##vso[build.updatebuildnumber]` couldn't you update the build number after computing the full build number with the checked in info in the branch? Then it would still be unique (still has revision, YYMM, etc.).  Would the UI reflect that then?

**Comment by rainersigwald** [comment]
My understanding (fuzzy!) is that what happens is:

* The first build starts, gets assigned the default build number `20190613.1`
* The first build runs updatebuildnumber, changes to `16.3.0-preview.20190613.1`
* The second build starts, gets assigned a default build number--but because `20190613.1` is no longer taken, it gets `20190613.1` again
* Second build updates version number to the same as the first build :(

I think this could be gotten around with a [counter](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#counter), if we changed the initial assignment of "OfficialBuildId" that gets passed into the Arcade build:
https://github.com/dotnet/arcade/blob/ff0f47189f7d8a8b4ad353e37f3fc34aaa3090df/azure-pipelines.yml#L75

**Comment by tmat** [comment]
It's been suggested before (I believe @weshaggard did so) to use `YYYYMMDD.r` in pre-release package version instead of the more compressed form of the date we are using today.

Would that address the concern (at least partially)? Or is your main issue not having the other parts of the package version (major, minor, patch, pre-release label) displayed in the CI?

**Comment by rainersigwald** [comment]
Yeah, my main issue is that I want the other parts of the output version in the build name/number, because I don't know if 20190614.3 is 
* The first x.y servicing build in six months
* A normal rolling build of master
* A normal rolling build of the stabilization branch
* A stabilized release-mode build of the stabilization branch that we hope is final

All of that would be easy to know if we had `major.minor.patch-pre{disambiguator}`.

**Comment by mmitche** [comment]
> My understanding (fuzzy!) is that what happens is:
> 
> * The first build starts, gets assigned the default build number `20190613.1`
> * The first build runs updatebuildnumber, changes to `16.3.0-preview.20190613.1`
> * The second build starts, gets assigned a default build number--but because `20190613.1` is no longer taken, it gets `20190613.1` again
> * Second build updates version number to the same as the first build :(
> 
> I think this could be gotten around with a [counter](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#counter), if we changed the initial assignment of "OfficialBuildId" that gets passed into the Arcade build:
> https://github.com/dotnet/arcade/blob/ff0f47189f7d8a8b4ad353e37f3fc34aaa3090df/azure-pipelines.yml#L75

That sounds like more an AzDO issue than anything else. We should follow up with them I think.
