### ISSUE TITLE
[PKPIs] Product->Toolset CoherentParentDependency chains should affect product cycle health checks

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2939]
The product cycle health checks will break the graph at toolset edges.  However, parent coherent dependencies can 'hoist' a dependency out of toolset and into product.  For instance:

* core-setup depends on dotnet-wpf-int (product)
* dotnet-wpf-int depends on winforms (product), but ties the winforms version to core-setup's output via CoherentParentDependency attribute.

This means that even though the direct core-setup dependency is a toolset dependency, the product dependency cannot move without updating the toolset dependency, and hence there is a cycle.

This should be detected in health cycle checks.

**Comment by adiaaida** [comment]
Closing because the parent Epic was closed. If you believe this issue should still be worked on, please re-open.
