### ISSUE TITLE
Official build publishing failing with stale NuGet assembly version

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/arcade#2944]
MSBuild's official builds are failing with:

```
E:\A\_work\1366\s\.packages\microsoft.dotnet.build.tasks.feed\2.2.0-beta.19273.1\build\Microsoft.DotNet.Build.Tasks.Feed.targets(81,5): error : Could not load file or assembly 'NuGet.Common, Version=4.4.0.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. [E:\A\_work\1366\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19304.1\tools\Publish.proj]
```

See, for instance, https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=2734042

I looked into the `Microsoft.DotNet.Build.Tasks.Feed` package at version `2.2.0-beta.19273.1` and it appears to depend on `4.9.0.6`:
![image](https://user-images.githubusercontent.com/3347530/58908890-5db8e600-86d7-11e9-8c8d-fe6b76f473bf.png)

and also _deliver_ `4.9.0.6`:

![image](https://user-images.githubusercontent.com/3347530/58908931-6dd0c580-86d7-11e9-9764-01a16692a856.png)

Yet somehow it's looking for 4.4.0.3.

This appears to have started happening after [this merge](https://github.com/Microsoft/msbuild/commit/d71342a37061dc00bdae0265ace06986a72d4884#diff-5c6a1c77fe216efcfbbdccb11b863063L4), which included #2873. @jcagme, does the error above ring any bells?

**Comment by rainersigwald** [comment]
cc @livarcocc

**Comment by MattGal** [comment]
We're taking a look over here; current theory is something has already loaded a lower version into the executing appdomain when that happens.

**Comment by JohnTortugo** [comment]
I think I already have a fix for this. See this issue for more context: https://github.com/dotnet/core-eng/issues/6252

What's remaining to close that issue is to do more tests and merge it on @jcagme SleetLib fork.

**Comment by rainersigwald** [comment]
Isn't NuGet strong-named, and thus loadable side by side?

**Comment by JohnTortugo** [comment]
What I think is happening is that we have two different "packages" referencing a .dll with same name (although different versions) and the code linked below is overriding one of the files:

https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj#L27
https://github.com/dotnet/arcade/blob/master/eng/BuildTask.targets#L65

Does it make sense?

cc:  @tmat

**Comment by JohnTortugo** [comment]
@rainersigwald / @livarcocc can you please test with Tasks.Feed version: 2.2.0-beta.19306.14 ?

I don't have permission to create branches in dotnet/msbuild

**Comment by rainersigwald** [comment]
Trying https://github.com/Microsoft/msbuild/tree/exp/new-tasks-feed as https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=2745101&view=results

**Comment by rainersigwald** [comment]
That passed, @JohnTortugo. Should I merge that commit in, or wait for an Arcade SDK update to pull it in automagically (mostly just asking about timeline here).

**Comment by JohnTortugo** [comment]
Please wait for an update from Maestro. I'll try to get all changes in place today so you'll get a new+fixed Tasks.Feed overnight. The package you just tried wasn't an "official" release package.

**Comment by JohnTortugo** [comment]
Closing this one in favor of: https://github.com/dotnet/core-eng/issues/6252
