### ISSUE TITLE
Add NuGet.VerifyMicrosoftPackage check to the validation stage

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2945]
In the past, we hit some metadata compliance issues when we published packages to nuget.org. In order to avoid this we should add a validation check to check the built packages are compliant.

It was proposed to use the NuGet.VerifyMicrosoftPackage to catch all the compliance issues earlier.

The step could be as simple as the following:

`$url = "https://raw.githubusercontent.com/NuGet/NuGetGallery/jver-verify/src/VerifyMicrosoftPackage/verify.ps1"
Invoke-WebRequest $url -OutFile verify.ps1
.\verify.ps1 *.nupkg`

Notes:

*  [Source and readme](https://github.com/NuGet/NuGetGallery/tree/jver-verify/src/VerifyMicrosoftPackage)
*  This is not an official tool yet. It is very much in beta, not signed by the Microsoft cert, and not production ready. Please do not use it for any production or mission critical scenarios.

/fyi: @markwilkie @JohnTortugo

**Comment by JohnTortugo** [comment]
@jcagme do we need to perform this even if we are going at some point in the release push the packages to https://int.nugettest.org/ ? Is the benefit of running this tool (compared to publishing to nugettest) that we don't need to upload the packages?

**Comment by jcagme** [comment]
Good observation. This tools just checks for compliance package metadata and at the same time the tool does not check for package size limits, dlls should have authenticode, nuget.org-specific validations. So we need both checks to make sure packages are 100% ready for the final nuget.org push. 

Main idea of running this tool in every build is to fail fast so we can fix things earlier without consuming a lot of time while doing that.
