### ISSUE TITLE
[Signing] Provide a way to verify that the binaries that needed to be signed, were actually signed

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#295]
Cc: @jaredpar @tmat @weshaggard

**Comment by JohnTortugo** [comment]
What kind of validation is needed here? 

After the changes in progress on SignTool (#396) the list of files to be signed will be created dynamically. Would providing the list of discovered files + the list of signed files, as an output of the Signing task, be sufficient for this validation?

**Comment by maririos** [comment]
> Additionally, we can make the SignTool call an external tool (to be totally impartial) to check that the files were actually signed. I am thinking of "sn -v" or something like that.

I don't think we need an external tool for that. We can compare between what the list of discovered files has against the list of signed files. If something doesn't match, then the SingTool should fail and tell the user.

**Comment by tmat** [comment]
>  If something doesn't match, then the SingTool should fail and tell the user.

The only case when something wouldn't match would be if there was a binary with PKT that's not given to the sign task. This does not actually validate that the assets have been signed.

I don't think we should validate anything in the sign tool. Instead official build should have a step (in YAML definition) that validates that all assets are compliant -- not just signing, but also APIScan, etc.

**Comment by maririos** [comment]
Could it happen that Microbuild fails to sign some files? Just making sure that we know that all we send, got successfully signed.

**Comment by markwilkie** [comment]
The challenge here is probably less about did microbuild sign the files the tool asked for, and more about did the *right* files get signed which is harder to determine.  For example, we've seen in CoreFx numerous occasions where files were missed - meaning, signing was never attempted for them.

Along the lines of what @tmat is suggesting, there's probably something that should check that everything we're shipping is signed - as well as published, validated etc.

CoreFx has a start of this - at least for signing.

**Comment by tmat** [comment]
@maririos 

> Could it happen that Microbuild fails to sign some files? 

Yes, it could. But as I suggested above that should be detected by a VSTS build step that does overall validation of everything that's published.

**Comment by tmat** [comment]
> CoreFx numerous occasions where files were missed - meaning, signing was never attempted for them.

The design of the new sign tool should mostly mitigate that. The tool signs everything in a given set of shipping directories that's not signed yet. The publishing logic would use the same set of directories. So if some artifact is not there it won't get signed but it also won't get published.

**Comment by markwilkie** [comment]
@tmat - agreed that it would mostly be mitigated.  I'm still pretty sure we'll want some sort of "make sure what we're about to release is good" task....

**Comment by JohnTortugo** [comment]
I created a new issue to track implementation of the idea proposed by @tmat: https://github.com/dotnet/arcade/issues/462
