### ISSUE TITLE
[darc/maestro++] Clean up Maestro API / BAR once we finish moving repos to YAML pipelines

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#2956]
Once we move repos out of the current implementation of async publishing (i.e., the one based on external release pipelines) we'll probably be able to remove a several fields from Maestro API / BAR.

We'll probably be able to drop the whole ReleasePipelines table from BAR and it's link to channels, etc.

**Comment by riarenas** [comment]
This will most likely need to be done so we can stop using the release pipeline runner

**Comment by JohnTortugo** [comment]
Closing in favor of https://github.com/dotnet/arcade/issues/4577
