### ISSUE TITLE
helix machine setup is inconsistent

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/arcade#2959]
These two Helix runs are from the same commit. While we are doing some custom things to get the machine properly setup, I would expect the same behavior between both. I've been running into this issue off and on while trying to get Helix setup, thinking that I have something working and then only to find out that it doesn't. It took me a while to realize that something must be going on with the machine setup that is causing me so many headaches. I've probably lost weeks of time due to this issue.

Ignore the test results (there's a bug on our end there), you need to dig into the infrastructure logs for each to see the difference:

[Azure build #20190605.8](https://dev.azure.com/dnceng/public/_build/results?buildId=213272): Here are the associated [infrastructure logs](https://mc.dot.net/#/user/dotnet~2Fwpf/dotnet~2Fwpf~2Frefs~2Fheads~2Fdev~2Fstevenbrix~2Fhelix/tests~2Fdrt/20190605.8/workItem/DrtXaml/wilogs)

[Azure build #20190604.10](https://dev.azure.com/dnceng/public/_build/results?buildId=211842): Here are the associated [infrastructure logs](https://mc.dot.net/#/user/dotnet~2Fwpf/dotnet~2Fwpf~2Frefs~2Fpull~2F802~2Fmerge/tests~2Fdrt/20190604.10/workItem/DrtXaml/wilogs)

The payload directories and dotnet install needs to be properly cleaned up before the machine is reused for any other reason.

**Comment by riarenas** [comment]
@dotnet/dnceng

**Comment by MattGal** [comment]
Taking a look.

**Comment by MattGal** [comment]
@stephenbrix can you please give me some details about what you're seeing?  If you can stay within %HELIX_WORK_ROOT% things do get automatically cleaned up; depending on things you may or may not have installed outside of the helix work directory, it's possible for folks who depend on such things to get messed up.  If you can help me understand expected/actual I'll do my best to unblock you.

**Comment by stevenbrix** [comment]
Thanks @MattGal! This describes what we are currently doing:
https://github.com/dotnet/wpf/issues/816#issuecomment-498834686

What I'm seeing is that sometimes our test executable loads and runs fine, and other times it fails to find the `Microsoft.NETCore.App` runtime that we manually deploy onto the machine. However, I can only somewhat assume that this is what's happening since I'm not sure how to debug the machine. I have gone through the exercise locally and was able to debug the issue to figure out this is what was happening when I saw this error.

**Comment by stevenbrix** [comment]
Ahh, maybe this is the issue. It doesn't look like %HELIX_CORRELATION_PAYLOAD% is within %HELIX_WORKITEM_ROOT%, so maybe that's why I'm seeing this?

What's the difference between the %HELIX_CORRELATION_PAYLOAD%  and %HELIX_WORKITEM_PAYLOAD%, maybe i should be using that?

**Comment by mjanecke** [comment]
@stevenbrix 

Here's the documentation for Helix. The variable definitions are further down the page: 
https://github.com/dotnet/core-eng/blob/b86db0407b26e06befcfcba9f157e59f0703ffe8/Documentation/HelixDocumentation.md


HELIX_CORRELATION_PAYLOAD | The location on disk of the unzipped cached payload
-- | --
HELIX_WORKITEM_PAYLOAD | The location on disk of the unzipped workitem payload

**Comment by stevenbrix** [comment]
oh my gosh thank you for linking that. i was looking in the arcade repo and somewhat disappointed with the documentation that i found.

**Comment by MattGal** [comment]
+1 to what Missy is mentioning;  Anything that is xcopy-deploy-able is a perfect candidate to be a correlation payload (there's an important perf consideration here as these files are cached per job while work items are cleaned every work item).

**Comment by jonfortescue** [comment]
@stevenbrix -- it really isn't good that you didn't find the docs in arcade useful. My guess is that you were looking at The [Sending Jobs to Helix](https://github.com/dotnet/arcade/blob/master/Documentation/AzureDevOps/SendingJobsToHelix.md) doc, as that probably is the one that sticks out first. I wrote that doc assuming the reader would be familiar with Helix, but since our documentation is currently all over that place it's clear that won't always be the case, so I just added a link to the doc that Missy sent you to the top of it. Hopefully that helps unblock folks faster in the future!

I also just filed https://github.com/dotnet/core-eng/issues/6635 to have us move some of these helpful docs out of core-eng and into arcade which should make this more accessible in general.

**Comment by stevenbrix** [comment]
Thanks @jonfortescue! I think that will make life much easier for others :)

I feel like I am starting to see more consistent results, part of it might have been on our end for not properly cleaning things up. What we're doing is a bit unorthodox, but should work.

I don't want people to go chasing dragons, but I just noticed something very strange that also might explain why I've been so confused. I unfortunately don't have the repo anymore, since I retried the build and the console infrastructure logs from the original attempt were gone. I noticed on [one](https://dev.azure.com/dnceng/public/_build/results?buildId=213465) of my runs the x86 leg failed whereas the x64 leg passed. Before I was properly reporting xUnit logs, i was using the Mission Control website to look at the console output to determine if things were running smoothly. I was shocked/confused that when i looked at the logs for my x86 run, everything passed! This didn't make any sense, until i found logs through the UI in AzurePipelines that accurately showed the failure i was anticipating.

![image](https://user-images.githubusercontent.com/9649518/58993756-50692d80-87a3-11e9-8d02-114489e03c74.png)

Since we weren't returning a non-zero exit code, Azure Pipelines thought the tests succeeded and so this UI wasn't accessible. Anyways, i don't know if there have been reports of something similar to this, but this might help explain why it seemed like the machine is in a bad state. Rather than the issue being on the machine, it may have been how the console logs were being reported back.

**Comment by MattGal** [comment]
@stevenbrix for stuff like this I like to do investigations at a lower layer than VSTS for this to make sure stuff's not going awry in the Helix clients, and I can also give feedback about weird things going on.  Ping me on teams and provide Helix Job correlation ids (or links to your builds) and I'll try to both check for problems on our side and educate.

**Comment by MattGal** [comment]
I'm closing this out as I believe this turned out to be an accidental dependency on stuff other work items installed;  machines are recycled semi-regularly but we can't afford to reset them every work item because we handle millions a day.

Since this is WPF I think this isn't the case, but if you ever find that you're running work which can run in a docker container, something like 'pristine execution environment every time' is absolutely available.
