### ISSUE TITLE
Determining SourceRevisionId fails on Linux while building coreclr

### ISSUE THREAD

**Issue by lpereira** [dotnet/arcade#2963]
While building coreclr on Arch Linux, I get the following backtrace:

```
/home/leandro/git/coreclr/.packages/microsoft.build.tasks.git/1.0.0-beta2-19270-01/build/Microsoft.Build.Tasks.Git.targets(16,5): error : The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. [/home/leandro/git/coreclr/eng/empty.csproj]
/home/leandro/git/coreclr/.packages/microsoft.build.tasks.git/1.0.0-beta2-19270-01/build/Microsoft.Build.Tasks.Git.targets(16,5): error :    at LibGit2Sharp.Core.NativeMethods.git_buf_free(GitBuf buf) [/home/leandro/git/coreclr/eng/empty.csproj]
/home/leandro/git/coreclr/.packages/microsoft.build.tasks.git/1.0.0-beta2-19270-01/build/Microsoft.Build.Tasks.Git.targets(16,5): error :    at LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever) [/home/leandro/git/coreclr/eng/empty.csproj]
/home/leandro/git/coreclr/.packages/microsoft.build.tasks.git/1.0.0-beta2-19270-01/build/Microsoft.Build.Tasks.Git.targets(16,5): error :    at LibGit2Sharp.Repository.Discover(String startingPath) [/home/leandro/git/coreclr/eng/empty.csproj]
/home/leandro/git/coreclr/.packages/microsoft.build.tasks.git/1.0.0-beta2-19270-01/build/Microsoft.Build.Tasks.Git.targets(16,5): error :    at Microsoft.Build.Tasks.Git.GitOperations.LocateRepository(String directory) in /_/src/Microsoft.Build.Tasks.Git.Operations/GitOperations.cs:line 26 [/home/leandro/git/coreclr/eng/empty.csproj]
/home/leandro/git/coreclr/.packages/microsoft.build.tasks.git/1.0.0-beta2-19270-01/build/Microsoft.Build.Tasks.Git.targets(16,5): error :    at Microsoft.Build.Tasks.Git.RepositoryTasks.LocateRepository(LocateRepository task) in /_/src/Microsoft.Build.Tasks.Git.Operations/RepositoryTasks.cs:line 58 [/home/leandro/git/coreclr/eng/empty.csproj]
/home/leandro/git/coreclr/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19304.1/tools/Version.targets(53,5): error : SourceRevisionId is not set, which means the SourceLink targets are not included in the build. Those are needed to produce a correct sha for our build outputs. [/home/leandro/git/coreclr/eng/empty.csproj]
```

This seems related to other issues such as #1261.  I'm using coreclr at `d7e49efa`, `~/.dotnet` has been removed, repository directory has been cleaned, `init-tools.sh` did its thing successfully.

This is the current `global.json` from coreclr:

```
{
  "tools": {
    "dotnet": "3.0.100-preview6-011681"
  },
  "native-tools": {
    "cmake": "3.11.1",
    "python": "2.7.15"
  },
  "msbuild-sdks": {
    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.19304.1",
    "Microsoft.DotNet.Helix.Sdk": "2.0.0-beta.19304.1",
    "Microsoft.Build.NoTargets": "1.0.53",
    "Microsoft.Build.Traversal": "2.0.2"
  }
}
```

Running `.dotnet/dotnet` from the coreclr repo confirms that that version has been successfully restored.

As a workaround (so I'm not blocked on this), I can pass `-skipgenerateversion -skipnuget` to `build.sh`.  (The nuget target is also impacted by a similar issue.)

**Comment by hoyosjs** [comment]
@lpereira in coreclr our `-skipnuget` flag is nothing related to nuget per se, it's a bad naming choice for the equivalent flag `-skipbuildpackages` in `build.cmd`. The reason they both failed is exactly what you said: there's an issue trying to generate versioning information. Looking at the changes in libgit2 and libgit2sharp and the comments in https://github.com/dotnet/roslyn/issues/29289, I'm wondering if sourcelink needs a libgit2sharp update. @tmat

**Comment by tmat** [comment]
What distro is this on?

**Comment by tmat** [comment]
Never mind - I missed it: Arch Linux. Does Core CLR [support](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md) that distro?

**Comment by hoyosjs** [comment]
Ah, I don't know why I read Ubuntu 18.04. No, CoreCLR has no official Arch support.

**Comment by lpereira** [comment]
This seems to happen from time to time, and is "fixed" when it happens.  If the band-aids are distribution specific, it'll keep popping up every now and then.  I just joined the coreclr/core-setup team, and I'm trying to get this to work on my machine without skipping anything that I might possibly need.  I don't have any experience with .NET at this point, so a pointer in the direction I should look to get this fixed would be appreciated. :)

**Comment by tmat** [comment]
You can disable SourceLink by passing the following arguments to the build:
`/p:EnableSourceControlManagerQueries=false /p:EnableSourceLink=false`

**Comment by markwilkie** [comment]
@lpereira - you good here now?

**Comment by tmat** [comment]
https://github.com/dotnet/arcade/pull/3149 addressed the root cause, it shouldn't be necessary to disable Source Link anymore.
