### ISSUE TITLE
GenerateNativeVersionFile target doesn't handle incremental build

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/arcade#2968]
The `GenerateNativeVersionFile` target always recreates the source or header file even if no versions have changed, which does not play well with incremental build.

Could Arcade set `WriteOnlyWhenDifferent` on the `WriteLinesToFile` task in that target? Not sure when exactly that parameter was added to the task / what versions Arcade needs to support.

The SDK handles this for the generated assembly info by hashing the relevant properties and writing it to a file with `WriteOnlyWhenDifferent`: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L105

**Comment by elinor-fung** [comment]
cc @janvorli

**Comment by janvorli** [comment]
Fixed by #3441
