### ISSUE TITLE
Which packages should be included in Arcade?

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#298]
So far we have and are working on these packages:

- [x] SignTool - This is a batch signing and verification tool for Microbuild environments.
- [x] Helix (SDK, Client and JobSender)
- [x] GitSync  - Ports commits from one github repository to other.
- [x] Packaging - Task package which handle building projects with the extension pkgproj.
- [x] Feed - Task package which handles uploading files to an Azure blob storage account.
- [x] Versioning - Package for generating version strings.
- [x] Publishing
- [x] Telemetry

What else should be included?

**Comment by jcagme** [comment]
I'm expecting a close to final list of packages to be included in the SDK to be determined during the review of https://github.com/dotnet/arcade/pull/313 which then we can use to update the list in this here and unblock the documentation issue :)

**Comment by maririos** [comment]
As for the packages that should be part of the Arcade SDK, doc https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/PackagesRoadmap.md list them.

For packages in Arcade per se, there isn't a restriction.

**Comment by markwilkie** [comment]
@maririos - should this issue be closed?

**Comment by maririos** [comment]
@markwilkie it was closed 5 days ago.

**Comment by markwilkie** [comment]
@maririos - now I'm embarrassed....   :)
