### ISSUE TITLE
How to set project properties that depend on PackageVersion?

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#2984]
I'm trying to adopt Microsoft.DotNet.Arcade.Sdk. Before adopting this, we were computing VersionPrefix, VersionSuffix, and PackageVersion properties during the Directory.Build.props file.

In Microsoft.DotNet.Arcade.Sdk, the evaluation order is different. VersionSuffix is set in Version.BeforeCommonTargets.targets which is evaluated after the project file, so I can't set PackageVersion from Directory.Build.props. As a result, I haven't found a way to make something like this work:
```xml
<TargetName>aspnetcore-runtime-$(PackageVersion)-win-$(Platform)</TargetName>
```
Example: https://github.com/aspnet/AspNetCore/blob/67b665208c94908ef8503e39d54e078a2ea778dc/src/Installers/Windows/TargetingPack/TargetingPack.wixproj#L9

Candidates and why they don't work:
* Project file
  * Implicit top/bottom imports - evaluation is always too early. PackageVersion is empty
  * With explicit top/bottom imports, setting the property after the Sdk.targets import. - too late
* Directory.Build.targets - too late, Microsoft.Common.targets uses TargetName to compute a handful of other properties like TargetPath. I could attempt to find everywhere TargetName is used and re-compute all derived properties, but that's likely to be fragile
* Custom import set via CustomBeforeMicrosoftCommonTargets - target is still evaluated too early, before Version.BeforeCommon.targets

@tmat - any ideas how to solve this?

**Comment by tmat** [comment]
Related to https://github.com/dotnet/sdk/issues/3173.

A couple of options
1) I'm not familiar with wixtargets - maybe there is a way to override the output file name from a target instead of specifying it in `TargetName`?
2) If not, then perhaps we could build the file into intermediate directory without the version in the name and then rename it when it's copied to the bin?

**Comment by natemcmaster** [comment]
1. that was my first attempt, and what I tried to implement in https://github.com/aspnet/AspNetCore/pull/10674, but it doesn't work. Wix2010.targets uses `TargetName` in other derived properties, and if I override TargetName after the fact I get fun build errors due to the mismatch of the original value and the updated value. This happens inside wixtargets, so there is no way to insert my overrides in the right phase of the build.

2. Yeah, that was going to be my fallback if you think https://github.com/dotnet/arcade/pull/2985 is too problematic.

**Comment by natemcmaster** [comment]
That said, I would still prefer https://github.com/dotnet/arcade/pull/2985 because MSI is picky about file names. Renaming MSI files can cause some weird issues with bundling and online installers. Not the expert on this, but it's preferrable to keep the file name consistent when building bundles.

**Comment by tmat** [comment]
#2985 feels a bit hacky and contrary to the spirit of dotnet/sdk#3173. But perhaps we need to get WIX targets fixed first to enable a cleaner solution.

**Comment by natemcmaster** [comment]
Yeah, it's hacky. Let me spend more time digging through wix targets to see if I can find a better workaround.

**Comment by natemcmaster** [comment]
Found workarounds.
