### ISSUE TITLE
[Arcade Validation] SDL Job failures causing build timeouts / failures

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#2996]
The fxcop step has been causing arcade-validation builds to time out, and is blocking the flow of new versions of the arcade sdk.

https://dev.azure.com/dnceng/internal/_build/results?buildId=215785
The fxcop run is full of errors like:

```
    FxCop completed with exit code 9
    Error running FxCop job: 1 of 3828
    FxCop completed with an Error exit code: 9. An analysis error (possibly assembly load error) occurred.
```
and 

```
FxCop completed with exit code 1
    Error running FxCop job: 3 of 3828
    FxCop completed with an Error exit code: 1. A fatal error occurred. Some of the possible conditions that are considered fatal errors: 1) The analysis could not be performed because of insufficient input. 2) The analysis threw an exception that is not handled by FxCopCmd. 3) The specified project file could not be found or is corrupted. 4) The output option was not specified or the file could not be written.
```
Also not sure why the tool is trying to examine 3828 assemblies, since arcade-validation doesn't produce that many.

@sunandabalu 

I temporarily disabled this step in https://github.com/dotnet/arcade-validation/pull/497 but we should understand what is happening before enabling it again.

**Comment by tmat** [comment]
We shouldn't be using FxCop. What rules do we want to be validating?

/cc @jinujoseph @mavasani

**Comment by sunandabalu** [comment]
> We shouldn't be using FxCop. What rules do we want to be validating?
> 
> /cc @jinujoseph @mavasani

You are right, we should not be using FxCop. I was running different SDL tools through the automation scripts for testing purposes. We will be using Roslyn Analyzers instead. Closing this issue.
