### ISSUE TITLE
[darc/maestro++] Generate links to source diffs in auto-update PR description

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#3001]
When I get an auto-PR that fails in a way that looks like an upstream breaking change, I look at the upstream repo's diff to get a quick look at potential causes.

To do that, I open the upgrade PR's diff view to find the old/new commit hashes (the PR description isn't useful even this far!) and assemble a URL like this:

`https://github.com/dotnet/wpf/compare/d1280eb9093b0dd1424777278b93d90adddda5f5...1798ea52f6f12049cb2be6a55132741638bb68b4`

`https://github.com/dotnet/<repo>/compare/<old commit>...<new commit>`

This makes it very easy to spot many breaking changes.

Having links to these in the PR description would be a small QoL timesaver for me, but maybe it would help some people who didn't know how to quickly generate the URL for the diff. It shows up nicely thanks to GitHub, like https://github.com/dotnet/wpf/compare/d1280eb9093b0dd1424777278b93d90adddda5f5...1798ea52f6f12049cb2be6a55132741638bb68b4 for the above example.

---

Could Maestro++ put links like this in the auto-update PR description?

**Comment by markwilkie** [comment]
Seems like a good idea.  Adding to the dependency flow epic.

**Comment by mmitche** [comment]
This should be done right (should show updates of transitive repos).  Unlikely to get to in 3.1 but probalby in 5.

**Comment by markwilkie** [comment]
I'm wondering if we should leave this on the backlog or just close it.  @mmitche ?

**Comment by riarenas** [comment]
This was actually done. There's a bug regarding batched updates (https://github.com/dotnet/arcade/issues/7339) but the feature was added as part of @lwintjen's intern project so I think we can close this.
