### ISSUE TITLE
[Maestro++] Check if an AzDO build has finished before trying to trigger a release for it

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3002]
Currently, there's usually a 1-2 minute gap between the publishing to BAR, and the point where a build has finished, either from additional steps or even whole jobs that run after the build is added to BAR.

The runner for the release pipelines will trigger as soon as a BAR build is inserted in a channel, and will try to start a release for an unfinished build, which promptly results in Azure DevOps failing the request.

We will keep retrying and eventually we're able to trigger the release, but this generates unnecessary exceptions. We should be able to simply check if a build has finished before attempting the release at all.

**Comment by JohnTortugo** [comment]
Turns out this can be a block to my work on moving repos to YAML pipelines. Reason: the Publish to BAR step in the build stage will trigger the existent release pipeline while the other stages of the build are still executing.
