### ISSUE TITLE
Clean build of corefx hits an error in CoreFxTesting.Targets

### ISSUE THREAD

**Issue by pgovind** [dotnet/arcade#3005]
I just hit this at master(4b6562e0da17ba1d92d72bc2406af9eea3e9337a):
```
C:\Users\prgovi\.nuget\packages\microsoft.dotnet.corefxtesting\1.0.0-beta.19105.4\build\Microsoft.DotNet.CoreFxTesting.targets(66,61): error MSB4022: The result "" of evaluating the value "$(MSBuildTestAssemblyPath)" of the "AssemblyFile" attribute in element <UsingTask> is not valid. [C:\Users\prgovi\Desktop\Work\corefx\build.proj]
```

**Comment by ViktorHofer** [comment]
You are testing with an outdated build. Make sure that the artifacts folder is deleted. The property mentioned in the error message was removed a long time ago. Also your corefxtesting dependency version is outdated: `1.0.0-beta.19304.1`. You can't be on latest master.

**Comment by ericstj** [comment]
Interesting.  Thanks for checking!
