### ISSUE TITLE
Cannot specify dotnet/x86 runtime and still build on *nix

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#3006]
**Repro**
Put this in a global.json file and attempt to build on Linux or macOS
```json
{
  "tools": {
    "dotnet": "3.0.100-preview5-011568",
    "runtimes": {
      "dotnet/x64": [
        "2.2.0"
      ],
      "dotnet/x86": [
        "2.2.0"
      ]
    }
  }
}
```

**Result**
```
dotnet_install: Error: Architecture `x86` not supported. If you think this is a bug, report it at https://github.com/dotnet/cli/issues
Failed to install dotnet SDK (exit code '1').
/Users/namc/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19302.2/tools/InstallDotNetCore.targets(15,5): error : dotnet-install failed [/Users/namc/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19302.2/tools/Tools.proj]

Build FAILED.

/Users/namc/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19302.2/tools/InstallDotNetCore.targets(15,5): error : dotnet-install failed [/Users/namc/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19302.2/tools/Tools.proj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:07.82
Build failed (exit code '1').
```

**Comment by natemcmaster** [comment]
FYI this is going to block aspnetcore.

**Option 1**

Unless OS == Windows, always skip installing x86. It's not supported by .NET Core and there are currently no plans to support it.

**Option 2**

The way we solved this in KoreBuild was by allowing repos to specify additional runtimes as MSBuild items. See https://github.com/aspnet/AspNetCore/blob/936d4dcf0909855d00155e22a93a8fc017f3b111/build/runtimes.props. What if we repeated the same design here? For instance, we could support putting something like this into eng/Tools.props

```xml
  <ItemGroup>
    <DotNetCoreRuntime Include="$(MicrosoftNETCoreAppPackageVersion)" />
    <DotNetCoreRuntime Condition="'$(OS)' == 'Windows_NT'" Include="$(MicrosoftNETCoreAppPackageVersion)" Arch="x86" />
  </ItemGroup>
```

/cc @markwilkie @Pilchie @chcosta

**Comment by markwilkie** [comment]
@chcosta - I think you had thoughts about this?

**Comment by tmat** [comment]
I vote for Option 1. We can consider the requirements specified in the global.json conditional on availability on the current OS.
