### ISSUE TITLE
[darc/maestro++] get-subscriptions should have additional filters

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#3012]
Darc get-subscriptions should have some additional filters to aid the coherency QB and/or repo owners:

- Filter to only subscriptions that currently apply to toolset or product dependencies in the target branch
- Filter subscriptions to only those that apply to a channel or a branch that associates automatically to that channel

**Comment by mmitche** [comment]
I don't think the toolset or product one is particularly interesting, as it's:
1. Expensive (download and parse version details file for every subscription)
2. Basically covered by the subscription frequencies in the primary use cases.

**Comment by riarenas** [comment]
This was rolled out on 10/16
