### ISSUE TITLE
Remove source-build patches

### ISSUE THREAD

**Issue by crummel** [dotnet/arcade#3014]
Source-build has some patches that we are currently applying to your repo.  This issue tracks removing the patches.  These patches can be found at https://github.com/dotnet/source-build/tree/release/3.0/patches/arcade.

Patches that have the responsibility "Repo" and the Disposition "Incorporate" are patches that we believe are valid source-build fixes that should be moved into your repo.  Please let us know if these don't seem like good patches.  Any changes with the responsibility "source-build" is something that we plan to keep going forward or integrate in another way - please also let us know if you think there may be problems with those patches.

Patch name | Type | Disposition | Responsibility | Notes
-- | -- | -- | -- | --
arcade/0001-Fix-InternalsVisibleTo-generation.patch | One-off | Incorporate | source-build | Patch was needed only for cli-migrate signing issues.  Have PR out to Arcade.
arcade/0002-Exclude-test-projects-from-source-build.patch | ProjRemoval | Incorporate | Repo |  
arcade/0003-Remove-projects-that-increased-prebuilts.patch | ProjRemoval | Incorporate | Repo |  
arcade/0004-Use-alternate-workaround-for-bootstrapping-Arcade.patch | One-off | Soft-patch | source-build | Allows us to use the bootstrap version of arcade.  Will be fixed eventually by toolset   bootstrapping.

**Comment by tmat** [comment]
I don't understand why `0004-Remove-projects-that-increased-prebuilts.patch` is needed. Projects shouldnt' be removed from the solution. Does `ExcludeFromSourceBuild` not work for some reason?

**Comment by crummel** [comment]
Yeah, we should have been doing `ExcludeFromSourceBuild` here.  Aditya's PR took care of most of these and my PR to exclude test by default should take care of the rest.

**Comment by tmat** [comment]
@crummel Seems like with https://github.com/dotnet/arcade/pull/3051 fix there are no more patches needed, correct?

**Comment by crummel** [comment]
Yes, I think we can close this one out.  Thanks!
