### ISSUE TITLE
Investigate whether Test Signing meet WPF signing requirements

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3024]
See discussion on this issue: https://github.com/dotnet/arcade/issues/2936

Bottom line: A talk needs to happen to make sure that our current Test Signing approach meets the requirements (business needs) of WPF (@vatsan-madhavan ).

cc: @vatsan-madhavan @markwilkie

**Comment by vatsan-madhavan** [comment]
@JohnTortugo, Have you now understood the test-signing process well enough to say that the _lack of timestamps_ during test-signing is intentional, and not an (inadvertent) bug?

**Comment by vatsan-madhavan** [comment]
[Microsoft.DotNet.Arcade.Sdk.1.0.0-beta.19306.12.zip](https://github.com/dotnet/arcade/files/3278938/Microsoft.DotNet.Arcade.Sdk.1.0.0-beta.19306.12.zip)

Attaching a sample nupkg with missing timestamp. 
Also related: #2304

**Comment by rladuca** [comment]
Yes, if this is the correct forum for it, we'd like to understand the limits of signtool in terms of signing font files and other formats and if there is the possibility for expanding support in signtool.

We were trying to package up parts of our test data and signtool fails on fonts and, I believe, some other file types (we can generate a comprehensive list).  If we were to request an expansion on what types of files can be signed, would that be possible?

At least for fonts, I see there is [DSIG](https://docs.microsoft.com/en-us/typography/tools/signing-tool/) is there a way we can integrate that with Arcade or integrate that behavior into signtool?

**Comment by JohnTortugo** [comment]
> @JohnTortugo, Have you now understood the test-signing process well enough to say that the _lack of timestamps_ during test-signing is intentional, and not an (inadvertent) bug?

What exactly is the scenario that you want to use Test signed binaries for? The way I understand test-signed binaries shouldn't even be published (except for specific scenarios?! Internal use only..). I don't know if there would be an issue adding timestamp to Test certificates (I can find that out). I just want to understand better how you're relying on test-signed binaries.

@rladuca what kind of fonts do you want to sign? Right now I know that TTF fonts are supported by MicroBuild. I'm not sure if Arcade SignTool impose a limitation on signing font files. Did you try it?

**Comment by vatsan-madhavan** [comment]
> The way I understand test-signed binaries shouldn't even be published 

My understanding is that test signed product binaries shouldn't be published. Is there a reason (e.g. a policy) we shouldn't publish test-signed _test_ binaries? 

If there is a policy (need pointer) that requires us to use real-signing even for test binaries (i.e., a repo that only produces test assemblies, and no shipping binaries are produced), we can indeed switch to real-signing for the test repo and sidestep the _timestamping_ problem.

**Comment by JohnTortugo** [comment]
I don't have a problem with test-signing test binaries. In my understanding that's the goal for test signing. My understanding here is that you require test-signing + _timestamped_ certificates. I don't know how much work that will be or if it's possible. I'll start a thread (CC'ing you) to find out that.

**Comment by vatsan-madhavan** [comment]
> you require test-signing + timestamped certificates

This is not _our_ (i.e., WPF team's) requirement - we have inherited this requirement as much as you have. 

It looks like like timestamping is part of the contract for how signing is supposed to be done (_irrespective_ of the cert that is used - _real_ vs _test_ signing is just a choice of cert.) Besides nuget, there may be other tools/scenarios that are broken. Chasing each of them and find workarounds/fixes etc. may become very hard (vs. fixing the problem at the source). 

@rrelyea, can nuget work with packages that are signed, but are missing a timestamp ? AFAIK, restore fails today when such packages are encountered.

**Comment by rladuca** [comment]
@Miguep as he was doing the packaging when we noticed this.

I believe we were signing all TTF and signtool failed on them.  I think it was also attempting (and failing) to sign .doc and .xls files.

**Comment by markwilkie** [comment]
Can someone recap for me the scenario we're trying to solve for and next steps?

**Comment by markwilkie** [comment]
Closing given no follow up.
