### ISSUE TITLE
Unable to locate the .NET Core SDK

### ISSUE THREAD

**Issue by maneely** [dotnet/arcade#3035]
Using Arcade 1.0.0-beta.19272.13. Attempting to build I get:
%userprofile%\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19272.13\tools\Tools.proj : error : Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches th
e installed version.
%userprofile%\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19272.13\tools\Tools.proj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

However this is my global.json:
  "tools": {
    "dotnet": "3.0.100-preview5-011568",
    "runtimes": {
      "dotnet/x64": [
        "2.1.7"
      ]
    }

And these are the dotnet sdks I have installed:
dotnet --list-sdks
1.1.14 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.302 [C:\Program Files\dotnet\sdk]
2.1.507 [C:\Program Files\dotnet\sdk]
2.1.602 [C:\Program Files\dotnet\sdk]
2.1.700 [C:\Program Files\dotnet\sdk]
2.2.101 [C:\Program Files\dotnet\sdk]
2.2.202 [C:\Program Files\dotnet\sdk]
2.2.300 [C:\Program Files\dotnet\sdk]
3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk]

Adding this env var makes it work:
set DOTNET_MSBUILD_SDK_RESOLVER_SDKS_DIR=C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks

**Comment by alexperovich** [comment]
Is this a command line build with build.cmd? Or from VS?
What happens if you add `"sdk": { "version": "3.0.100-preview5-011568" }` into your global.json?

**Comment by maneely** [comment]
This is with build.cmd.

Adding the sdk doesn’t seem to help:

{
  "tools": {
    "dotnet": "3.0.100-preview5-011568",
    "runtimes": {
      "dotnet/x64": [
        "2.1.7"
      ]
    },
    "vs": {
      "version": "16.0"
    }
  },
  "msbuild-sdks": {
    "Microsoft.Build.CentralPackageVersions": "2.0.1",
    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.19272.13"
  },
  "sdk": { "version": "3.0.100-preview5-011568" }
}

Thanks!

-M

**Comment by alexperovich** [comment]
Oooo, I have seen this problem before with the vs msbuild installation that you are telling arcade to use. I think you need to have VS 16 preview installed for it to work with 3.0. If you have that already installed can you run build.cmd from a dev cmd prompt for that VS?

**Comment by maneely** [comment]
Building from a VS2019 command prompt results in the same errors:
error : Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the
installed version.
error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

And it is using the 2019 msbuild:
C:\>where MSBuild.exe
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe
%userprofile%\Downloads\MSBuild\MSBuild\15.0\Bin\MSBuild.exe

C:\> msbuild -version
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.1.76.45076

Thanks.

-M

**Comment by alexperovich** [comment]
I'm out of ideas. A binlog might have some useful information about the sdk resolver process. Can you gather a binlog? If that doesn't have anything useful in it then this is a problem somewhere in the guts of msbuild. @rainersigwald might be able to help.

**Comment by rainersigwald** [comment]
Are you running a released version of Visual Studio, or prereleases? There is a checkbox in the released versions that prevents resolving prerelease versions of the .NET Core SDK, under Tools -> Options:

![image](https://user-images.githubusercontent.com/3347530/59614580-a795c900-90e6-11e9-8981-0fdbd08d42bd.png)

Since the .NET Core 3.0 SDK is in a prerelease state, it's not officialy supported by release Visual Studio, and the SDK team recommends using preview Visual Studios for projects that use preview SDKs.

**Comment by maneely** [comment]
Is that relevant when building from the command-line?

(Also, Outlooks seems to have butchered your linked image below.)

Thx.

-M

**Comment by rainersigwald** [comment]
Yes, if the command-line build is driven through an RTM VS instance, it follows the same rules as the VS UI.

**Comment by maneely** [comment]
That appears to be the winner:

In VS menu, “Tools --> Options”:
Settings in section “Environment --> Preview Features”, set “Use previews of the .NET Core SDK” to checked.

Thanks, @Rainer Sigwald<mailto:raines@microsoft.com>!

-M

**Comment by markwilkie** [comment]
Looks like we're resolved here.

**Comment by JonnySchnittger** [comment]
I had this issue on the current 16.3 Visual Studio update (.net core 3.0 release version)... I fixed it by adding `C:\Program Files\dotnet` to my PATH variable, looks like it gets messed up somehow
