### ISSUE TITLE
Publish XliffTasks to dotnet-core feed

### ISSUE THREAD

**Issue by tmat** [dotnet/arcade#3038]
This is required before we can switch to NuGet.config.

**Comment by tmat** [comment]
@jcagme @markwilkie

**Comment by markwilkie** [comment]
Poking this again to make sure it's taken care of.  

cc/ @riarenas @jcagme  @JohnTortugo

**Comment by JohnTortugo** [comment]
@tmat is the work here to port dotnet/XliffTasks to build in dnceng with Arcade build templates and publish to `dotnet-core feed` ?

**Comment by tmat** [comment]
Yes

**Comment by mmitche** [comment]
I've been pushing these to dotnet-tools. Should be good to go. I think this issue can be closed.
