### ISSUE TITLE
Move NuGet.Repack tool from roslyn-tools to Arcade repo

### ISSUE THREAD

**Issue by tmat** [dotnet/arcade#3039]
<s>This is required before we can switch to NuGet.config.</s>

**Comment by markwilkie** [comment]
Poking this

cc/ @jcagme @riarenas  @JohnTortugo

**Comment by JohnTortugo** [comment]
@tmat is this still needed before we switch to NuGet.Config ?

**Comment by JoeRobich** [comment]
I need to fix up some unit tests that generate different results when running on .net core. Unfortunately I'm oof the rest of this week. I can look at them again on Monday.

**Comment by tmat** [comment]
> is this still needed before we switch to NuGet.Config

No.

**Comment by JoeRobich** [comment]
NuGet.Repack tool has been moved. https://github.com/dotnet/arcade/pull/3120
