### ISSUE TITLE
Publish Microsoft.DiaSymReader.Pdb2Pdb to dotnet-core feed

### ISSUE THREAD

**Issue by tmat** [dotnet/arcade#3040]
We need to convert dotnet/symreader-converter to Arcade and publishing pipeline.

To unblock NuGet.config migration, I'm going to publish the currently used package manually.

**Comment by markwilkie** [comment]
Poking

cc/ @jcagme @riarenas  @JohnTortugo

**Comment by jcagme** [comment]
By `publishing pipeline` do you mean async release management? Probably we can convert this to stages already, thoughts @JohnTortugo ?

**Comment by JohnTortugo** [comment]
I think he just meant to build in dnceng with Arcade build templates and publish to dotnet-core feed. We can definitely do it stages-based publishing. Is this still needed before the Nuget.Config move? @tmat

**Comment by jcagme** [comment]
I don't think is needed for NuGet.config move since the package was pushed manually but the ultimate goal is to have `dotnet/symreader-converter` publishing packages with every build

**Comment by JohnTortugo** [comment]
In this case can we move to post p7 epic?

**Comment by riarenas** [comment]
Symreader-converter is using the new yaml stages publishing.
