### ISSUE TITLE
[Azure feeds] Investigate whether we can publish packages across accounts

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#3057]
Since we need to create new releases that publish to AzDO artifact feeds we should investigate if we can publish the bits produced by a build in devdiv to a feed which lives in dnceng or viceversa.

Out of the box tasks don't allow this since they just allow selecting a feed in the same account but probably this is possible if we find a way of publishing packages through HTTP calls or something in the lines.

/fyi: @livarcocc @markwilkie

**Comment by riarenas** [comment]
We ran into issues with this one, but they were fixed via #3942
