### ISSUE TITLE
Clear NuGet cache

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#3058]
Since there might be times that a build will restore final/stable packages we need to clear the NuGet cache so we always get the package we need from the endpoint defined in NuGet.config.

**Comment by JohnTortugo** [comment]
Update:

- AzDO YAML documentation doesn't clarify whether `checkout.clean` will also clear NuGet caches. I asked a question about this here: https://github.com/MicrosoftDocs/vsts-docs/issues/4777#issuecomment-509840499

- I did some manual tests and what I observe is that `checkout.clean` **does not** clear NuGet caches. See results below:

  - Agent: hosted
checkout: self
clean: true
Result: everything seems clear
https://dnceng.visualstudio.com/internal/_build/results?buildId=258967&view=results


  - Agent: hosted
checkout: self
clean: -
Result: everything seems clear
https://dnceng.visualstudio.com/internal/_build/results?buildId=258968&view=results

  - Agent: NetCorePublic-Pool			-> 			BuildPool.Windows.10.Amd64.VS2017.Open
checkout: self
clean: -
Result: NOT CLEAN
https://dnceng.visualstudio.com/internal/_build/results?buildId=259007&view=results

  - Agent: NetCorePublic-Pool			-> 			BuildPool.Windows.10.Amd64.VS2017.Open
checkout: self
clean: true
Result: NOT CLEAN
https://dnceng.visualstudio.com/internal/_build/results?buildId=259026&view=results

What worked was executing an explicit NuGet cache clean command:

  - Agent: NetCorePublic-Pool			-> 			BuildPool.Windows.10.Amd64.VS2017.Open
Executing: **dotnet nuget locals --clear all**
Result: CLEAN
https://dnceng.visualstudio.com/internal/_build/results?buildId=259087&view=results

**Comment by riarenas** [comment]
Is there a disadvantage of clearing the cache any time it's an azdo build?

**Comment by JohnTortugo** [comment]
I'm not sure, only thing I can think of is the slowdown to download the packages again?!

**Comment by alexperovich** [comment]
There is a significant slowdown for downloading 100s of nuget packages again if the cache is cleared for every build. It should not be cleared for PR builds. Its probably correct to clear for official builds though.

**Comment by jcagme** [comment]
What @alexperovich said, we actually should only clear the cache in stable builds since having the exact same version of a package in the cache might cause that the new one is not restored

**Comment by tmat** [comment]
On CI we should be restoring packages to `.packages` directory in the repo, not to global nuget cache. So we shouldn't need to clear the global cache as it won't be used.

**Comment by jcagme** [comment]
@mmitche do you remember if and where you hit an issue when restoring packages with the same version? Was this pre-Arcade?

**Comment by mmitche** [comment]
Yeah, pre-arcade.  This was something we had to think about in the 2.1 and 2.2 days.

**Comment by jcagme** [comment]
Ok, so probably this is not even needed since as @tmat mentioned we restore to the `.packages` folder and it is created on a different folder on an agent and in theory should be deleted at the end of the run.

**Comment by JohnTortugo** [comment]
Yeah, I thought the same. Ok to close then?
