### ISSUE TITLE
Arcade repo not getting mirror to VSTS

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#306]
@maririos commented on [Mon Jul 09 2018](https://github.com/dotnet/core-eng/issues/3850)

Problem: there’s a point in time where the file existed as both NuGet.config and NuGet.Config.  Giuthub doesn't care but VSTS enforces that pushed files differ in more than case.

Recommendation from Kevin David:
As long as you’ve fixed the conflicts at all branch tips, the best approach we’ve found, generally, is to disable the setting on whatever repo has the problem in history (see docs [here](https://docs.microsoft.com/en-us/vsts/git/concepts/repository-settings?view=vsts)), push the repo, then re-enable the setting.

---

@maririos commented on [Mon Jul 09 2018](https://github.com/dotnet/core-eng/issues/3850#issuecomment-403555195)

Putting in FR for now as this is blocking work in Arcade

---

@dagood commented on [Mon Jul 09 2018](https://github.com/dotnet/core-eng/issues/3850#issuecomment-403556075)

I recommend:

> ...we can disable the push check, then **once we figure out how to verify this on GitHub**, we can enable it again. (Enabling it immediately isn’t very enticing because evidently nobody monitors the build def where this error showed up.)

---

@maririos commented on [Tue Jul 10 2018](https://github.com/dotnet/core-eng/issues/3850#issuecomment-403885640)

@MattGal do you know when we could get someone working on this?

---

@maririos commented on [Tue Jul 10 2018](https://github.com/dotnet/core-eng/issues/3850#issuecomment-403905080)

Moving to Arcade so that the Build Arcade with Arcade group can take a look

**Comment by chcosta** [comment]
> I worked with Matt Licholai to turn off case enforcement, push a recent version of GitHub:Arcade into VSTS, and re-enable case-enforcement.  It appears that the Arcade mirror (both for devdiv.visualstudio.com and dotnet.visualstudio.com) are now successfully mirroring changes from GitHub.

Thanks,
Chris
