### ISSUE TITLE
InternalsVisibleTo tag not working for exposing internals to Moq

### ISSUE THREAD

**Issue by mikaelm12** [dotnet/arcade#3068]
I was working to make some types internal and in the process decided to try out the `InternalVisibleTo `tag rather than using AssemblyInfo.cs. It worked well for most things but I found that it was not working as expected with the Moq testing framework.
```xml
  <ItemGroup>
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
```
Still produces
```
  Error Message:
   System.TypeLoadException : Type 'Castle.Proxies.ITransportFactoryProxy_1' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a621a9e7e5c32e69' is attempting to implement an inaccessible interface.
```

Where as using the AssemblyInfo.cs works fine.

**Comment by markwilkie** [comment]
@ericstj might have some insight.

**Comment by mikaelm12** [comment]
Turns out it just needed the Moq public key property. User error, closing
