### ISSUE TITLE
[Arcade-validation] Arcade-validation sourcelink information is broken

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3069]
SourceLink validation for this file `Validation.Tests.xxxxxxxx.symbols` is broken. The link broken is the one below:

```
https://raw.githubusercontent.com/dotnet/arcade-validation/a32985c8d77f98bf244f6bb78c42ce7c7134b825/artifacts/obj/Validation.Tests/Release/netcoreapp2.1/Validation.Tests.Program.cs
```

cc @riarenas

**Comment by jcagme** [comment]
@JohnTortugo I'm closing this since it was opened a long ago and I haven't heard anything related to it. Feel free to reopen if you think we still need this.

**Comment by JohnTortugo** [comment]
Currently that validation is disabled in arcade-validation: https://github.com/dotnet/arcade-validation/blob/master/azure-pipelines.yml#L188

I quicked this build with the validation enabled. If it passes then we are good to close this issue: https://dnceng.visualstudio.com/internal/_build/results?buildId=558717&view=results

**Comment by adiaaida** [comment]
I looked at the validation build, which failed, to figure out why. I think that test failed because it's looking for a commit in github that doesn't exist. @JohnTortugo is there a way to test on a commit that DOES exist, maybe by hard coding the GH commit id? I might take this on so that I can make progress on https://github.com/dotnet/arcade/issues/3735

**Comment by JohnTortugo** [comment]
@adiaaida - Yeah, that's probably the problem. To do the proper test you'll need to push the same branch+commit to the internal & github forks. I've just done that and triggered a new build: https://dnceng.visualstudio.com/internal/_build/results?buildId=579881&view=results

**Comment by adiaaida** [comment]
The failure now is that there is no github raw for artifacts/obj/Validation/Release/netcoreapp2.0/Validation.AssemblyInfo.cs, which makes sense, since those are... artifacts and not checked in code.

**Comment by JohnTortugo** [comment]
That's a legit error, though. You may want to talk with @Anipik or @safern as they solved a [similar problem](https://github.com/dotnet/runtime/issues/33097#issuecomment-597767153) for dotnet/runtime recently. Also, @tmat is the source link SME.

**Comment by tmat** [comment]
First, check if `EmbedUntrackedSources` is `true`. It is set by default Arcade SDK targets, so it should be.

There are also the following issues:
https://github.com/microsoft/msbuild/issues/1479
https://github.com/dotnet/sdk/issues/10614

Can we update msbuild/SDK to the builds that have the fixes or do we need temporary workarounds?

**Comment by markwilkie** [comment]
Thoughts @rainersigwald ?

**Comment by rainersigwald** [comment]
For 5.x both should flow in the normal course of things, as Arcade pushes updates to the SDK (which will pull MSBuild changes). I see no strong reason not to push forward, other than the usual ones.

**Comment by adiaaida** [comment]
This doesn't really fall under the release epic. Triage folks: maybe this is more of an FR issue, if we even care about arcade-validation's sourcelink info?

**Comment by jakubstilec** [comment]
[Async Triage]: @adiaaida when this is so old, can't it be closed instead putting under FR?

**Comment by adiaaida** [comment]
I guess that depends on if we care that source link information is broken for this repo. With it broken, it means that we can run it as part of arcade validation, which means nothing is validating changes before they flow to the repos. It never really belonged in the release episode, so it just kept getting deprioritized, and was never fixed. I think it at least deserved being looked at one more before we close it as will not fix.

**Comment by adiaaida** [comment]
I think all that needs to be done here is to add
```
<EmbedUntrackedSources>true</EmbedUntrackedSources>
```

To directory. Build. Props in arcade validation

**Comment by MattGal** [comment]
[Async Triage] Doesn't meet my sniff test for FR, but it's also tiny.  Seems like we should just try @adiaaida 's suggestion in a PR, but I don't know where the issue should live.

**Comment by MattGal** [comment]
https://github.com/dotnet/arcade-validation/pull/2256/files

**Comment by MattGal** [comment]
Verified and PR merged, source link validation is back.  Thanks @adiaaida for the pointers!
