### ISSUE TITLE
ConditionalTheoryDiscoverer should check if a test case contains a skip condition when constructing a 

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/arcade#3070]
We need logic like https://github.com/aspnet/Extensions/blob/f0458995c625dba132a74733e041b97c0e10e025/src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/ConditionalTheoryDiscoverer.cs#L47-L59.

This is required for us to support our TestMatrix API: https://github.com/aspnet/Extensions/blob/master/src/Hosting/IntegrationTesting/src/TestMatrix.cs

cc @Tratcher

**Comment by JunTaoLuo** [comment]
cc @markwilkie

**Comment by markwilkie** [comment]
@JunTaoLuo thoughts on next steps?

**Comment by JunTaoLuo** [comment]
We should port the logic from extensions that I linked into https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.XUnitExtensions/src/Discoverers/ConditionalTheoryDiscoverer.cs.

**Comment by adiaaida** [comment]
Closing because the parent Epic was closed. If you believe this issue should still be worked on, please re-open.
