### ISSUE TITLE
[Versioning] How we allow different systems to generate custom build number

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#308]
This issue was spun after this discussion https://github.com/dotnet/arcade/pull/305#pullrequestreview-135923587. Part of it is copied below:

Basically, we need to agree and implement a way to support different systems to generate custom build numbers.

@weshaggard
In order for this () to work for FileVersion we are going to have to do some slightly different number calculations, similar to what we were doing in the task we created and what is in the spec. While we could get away with this longer format just for packages we will need the other format for FileVersion.

@tmat
I don't see why we need to change anything. This calculation is currently used for FileVersion and it works.

@weshaggard
The file versions need to be ever increasing and not run out of space to fit into a short version slot. We had to take great care to control the version number so we don't ship a version that is lower then our last release and also take care to not blow the version space too quickly.

For example our build number version is 26709 today which is defined by the code in the spec https://github.com/dotnet/arcade/blob/master/Documentation/Versioning.md#version-field-generation. It is essentially 3 digits for the number of months since a given date and 2 digits for the day. The seed date allows folks to control the number to get it placed where they need it for their builds. I think we still need something like that.

@tmat
OK, let's discuss seeding separately from this PR. +@jasonmalinowski @tannergooding for opinion as they were previously involved in designing the current version calculation alg.

**Comment by jasonmalinowski** [comment]
Only thing I'll chime in for: for Roslyn version algorithm (and things that copied it), there's no reason we can't change it to something else, at least in our Dev16 branches. Going "backwards" is fine since we'll be revving the major versions.

**Comment by maririos** [comment]
Covered with issue https://github.com/dotnet/arcade/issues/336
