### ISSUE TITLE
Refactoring for the Arcade SDK

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#309]
- [x] Make sure that PB_ environment variables aren't being misused as properties
- [x] Replace usages of "OfficialBuild == true" by OfficialBuildId != ''
- [x] Rename CIBuild property to ContinuousIntegrationBuild
- [x] something else?

Cc' @weshaggard @tmat @alexperovich

**Comment by markwilkie** [comment]
@JohnTortugo - Is this complete now?

**Comment by tmat** [comment]
I think so.

**Comment by JohnTortugo** [comment]
I see that we [still have a few](https://github.com/dotnet/arcade/search?q=OfficialBuild+%3D%3D+true&unscoped_q=OfficialBuild+%3D%3D+true) `OfficialBuild == true` checks.

Also the `CIBuild` parameter is [still there](https://github.com/dotnet/arcade/search?q=CIBuild&unscoped_q=CIBuild).

Do we still want to do these refactorings ?

**Comment by tmat** [comment]
> I see that we [still have a few](https://github.com/dotnet/arcade/search?q=OfficialBuild+%3D%3D+true&unscoped_q=OfficialBuild+%3D%3D+true) `OfficialBuild == true` checks.

We decided to keep using `OfficialBuild` bool for readability.

> Also the `CIBuild` parameter is [still there](https://github.com/dotnet/arcade/search?q=CIBuild&unscoped_q=CIBuild).

`/p:CIBuild=$ci` can be removed now.

**Comment by weshaggard** [comment]
As part of this can we also add some documentation noting that ContinuousIntegrationBuild doesn't imply PR validation but is set for any builds that aren't done locally. This includes both PR validation builds as well as our official builds. OfficialBuildId/OfficialBuild will additionally be set for official builds that can help distinguish them from PR validation.

**Comment by jcagme** [comment]
> /p:CIBuild=$ci can be removed now.

Just to confirm, this has been removed right?

**Comment by jcagme** [comment]
@JohnTortugo can we close this?
