### ISSUE TITLE
Be able to test post-build YAML templates in PR builds

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3091]
Right now our PR builds don't test the post-build (publishing) templates. That means that these templates are delivered to other repos without proper _automated_ tests. We need to add some validations for those at PR time or at least in the arcade-validation builds.

**Comment by jcagme** [comment]
I'd use arcade-validation for this

**Comment by riarenas** [comment]
Closing this as https://github.com/dotnet/arcade/issues/4351 is the way forward for this. Moving that issue to .NET 5 epic as it's cheap and gives us validation for a lot of scenarios.
