### ISSUE TITLE
Microsoft.DotNet.Build.Tasks.VisualStudio build task is missing from arcade 1.0.0-beta.19319.1

### ISSUE THREAD

**Issue by agocke** [dotnet/arcade#3098]
I believe it's supposed to be in tools/net472 and is trying to be loaded, but it doesn't seem to be present any more.

**Comment by agocke** [comment]
See the Windows Determinism failure in https://github.com/dotnet/roslyn/pull/36581

**Comment by agocke** [comment]
@ViktorHofer Do you have any idea why this could have happened?

**Comment by ViktorHofer** [comment]
It is in the package:

![image](https://user-images.githubusercontent.com/7412651/59805569-f6fc1500-92f1-11e9-9009-082535cff856.png)

**Comment by ViktorHofer** [comment]
You are probably hitting the same issue as the sdk?

https://github.com/dotnet/sdk/commit/7aa2004792850f672c70181820c86e88b8963992

https://twitter.com/davkean/status/1141271510591496192

**Comment by agocke** [comment]
Hm, perhaps, let me investigate more

**Comment by agocke** [comment]
@ViktorHofer It looks like that package isn't get restored at all in our determinism build. Is there some helper I have to call from the common tools in order to pull that package in?

**Comment by agocke** [comment]
I've changed our code to do a proper toolset restore like it does for normal solution build, so it looks like this is resolved.
