### ISSUE TITLE
Can Arcade expose a dependency on Xliff?

### ISSUE THREAD

**Issue by crummel** [dotnet/arcade#3099]
Currently Arcade has a default version of Xliff included if the repos don't specify a different one:
https://github.com/dotnet/arcade/blob/372249cafc24384ae3488aab4e815e54c2ff3938/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L88

However, neither Arcade nor the consuming repos have a subscription and BAR dependency on Xliff, so Xliff never makes it into the BAR manifest.  It doesn't look like any repos are overriding the version currently - is Arcade the correct place to put this dependency?

**Comment by crummel** [comment]
cc @mmitche

**Comment by tmat** [comment]
I think we should flow Xliff to Arcade and use the same mechanism we use for Roslyn compilers to propagate the version to Arcade consuming repos. That is, to add version setting here:

https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/Microsoft.DotNet.Arcade.Sdk.csproj#L71

**Comment by markwilkie** [comment]
@crummel - is this still a thing?

cc/ @chcosta

**Comment by crummel** [comment]
Yes, source-build would still like to see this.  @tmat and I also talked on another issue about the Roslyn dependency he mentions - this isn't currently an actual subscription and that's something we should probably fix too.

**Comment by tmat** [comment]
Fixed by #4580
