### ISSUE TITLE
Add support for automatically creating merge PR's across branches to mirror changes

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#310]
Aspnet has a build definition and a script they use to automate keeping branches in-sync (see https://github.com/aspnet/BuildTools/pull/703) other repo's need this support as well so we should figure out how to integrate this support into arcade. 

cc @natemcmaster

**Comment by tmat** [comment]
Shouldn't this be done by darc?

**Comment by weshaggard** [comment]
Perhaps it could be done by darc but I don't think mirroring changes across branches is currently on it's feature list.
