### ISSUE TITLE
[Maestro++] Add e2e scenario tests for the feed flow feature.

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3106]
Add an e2e test to the suite of tests that run on every maestro deployment that exercise the code that flows nuget feeds for stable builds.

**Comment by jcagme** [comment]
@riarenas does this represent setting up the test branches and subscriptions so we could test the E2E flow? If so this could either be closed or moved to Dev right?

**Comment by riarenas** [comment]
No. This one is creating an automated e2e test along with all the others that run after a deployment. I was planning on working in this after all the docs are in place.

**Comment by jcagme** [comment]
Got it. Thanks for clarifying

**Comment by riarenas** [comment]
Haven't made much progress and have some higher pri issues. Moving back to backlog for now.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade-services/pull/535
