### ISSUE TITLE
[darc/maestro++] Populate asset locations as dependency updates are calculated

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3107]
There are a lot of places in the code where we create new asset objects, but fail to grab the locations for the assets when we do it.

We should make a general cleanup pass so the assets always have the locations available.

**Comment by JohnTortugo** [comment]
@riarenas does this need to be done in P7 timeframe or can we move it to post-P7 ?

**Comment by riarenas** [comment]
Post p7 is fine. This is more of a cleanup step.

**Comment by riarenas** [comment]
Rolled out on 10/16
