### ISSUE TITLE
[Azure Artifact Feeds] Play with Universal Packages

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#3109]
We'll push blobs in a build as Universal Packages to Azure DevOps Artifact feeds and we need to understand how it works and what things are needed to make it work with our pipelines

**Comment by JohnTortugo** [comment]
@mmitche / @livarcocc what are the requirements for blobs in terms of how do you want to access them? 

Universal Packages (i.e., AzDO feeds way to store blobs) don't support (yet) a direct link to a blob. The only way to download a UP is using the `az CLI`, i.e., something like:

```
az artifacts universal download \
  --organization "https://dnceng.visualstudio.com/" \
  --feed "darc-int-dotnet-arcade-9dd11e20dd9266c4d2e0690ccd887eff78a5ce9e" \
  --name "version.svg" \
  --version "1.0.0" \
  --path .
```

**Comment by mmitche** [comment]
@JohnTortugo I think we are okay with sticking with blob storage for this. When accessing blobs for internal builds, the build should be appending a SaS (from secrets) to the blob url to access the data.

On a side a note, when we do a stabilized build, do the blobs get pushed to a unique container or directory? If so, is it going to be possible to predict what this URL is via info in the repo, or are we going to to have to propagate that info somehow?

**Comment by JohnTortugo** [comment]
> @JohnTortugo I think we are okay with sticking with blob storage for this. When accessing blobs for internal builds, the build should be appending a SaS (from secrets) to the blob url to access the data.
> 

Ok, agree. Just to confirm: there is no problem overriding the blobs (for stable builds) in the storage?

> On a side a note, when we do a stabilized build, do the blobs get pushed to a unique container or directory? If so, is it going to be possible to predict what this URL is via info in the repo, or are we going to to have to propagate that info somehow?

When publishing to Azure Storage the blobs go to a specific nested folder inside the feed's flatcontainer folder. The nested folder name can be specified per blob (the RelativeBlobPath metadata). So, to answer your question, we can't predict it but we can extract the info from the build manifest.

**Comment by mmitche** [comment]
> When publishing to Azure Storage the blobs go to a specific nested folder inside the feed's flatcontainer folder. The nested folder name can be specified per blob (the RelativeBlobPath metadata). So, to answer your question, we can't predict it but we can extract the info from the build manifest.

Okay can you open an arcade issue to deal with this? We may need to do something here.  We could also allow blob publishing to publish to the non-unique location if absolutely necessary.

**Comment by JohnTortugo** [comment]
Talked offline. We are going to push the blobs to Azure Storage and let overrides happen for stable builds.
