### ISSUE TITLE
[Signing] Make Arcade use Arcade SDK SignTool to sign its packages

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#311]

**Comment by JohnTortugo** [comment]
This is already done.

**Comment by maririos** [comment]
Although it is already happening, once the PR you have open #410  gets merged, and we publish a new SignTool package, we need to update the Arcade SDK to consume it.
You could either re-open this issue and track that, or create a new one. Either way, I want to make sure we don't forget to do that.

**Comment by JohnTortugo** [comment]
Created this issue #464 to track that. Thank you. Sorry for the confusion.
