### ISSUE TITLE
Update global.json with latest packages

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#312]
Since Maestro/Dark isn't fully functional yet we need to manually update global.json to use the latest SDK version so we will be able to use the changes to SDK->SignTool & SDK->Versioning.

CC: @maririos @alexperovich

**Comment by jcagme** [comment]
FYI.

https://github.com/dotnet/arcade/issues/320 proposes moving SDK's version to https://github.com/dotnet/arcade/blob/master/Directory.Build.props#L7

**Comment by maririos** [comment]
@jcagme are you guys planning on making the change? and if so when?

**Comment by jcagme** [comment]
https://github.com/dotnet/arcade/issues/322

This is on the top 3 of the backlog but given my FR weeks coming I can't provide a hard ETA on when this will be done but most likely by the end of S138.

Changing this in Darc is not a huge change, have Maestro++ and Darc in place officially is what might be time consuming and completed by S140.

**Comment by jcagme** [comment]
Yeah. There is a lot of movement in the original thread. Let’s talk times once the new strategy has been signed off

**Comment by jcagme** [comment]
Yeah
