### ISSUE TITLE
[Arcade Services] Convert Arcade-services RM pipeline to YAML stage

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3121]
Arcade-services doesn’t have any default channel set in BAR. The builds are assigned to channels in their custom RM release pipeline: https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=9348 . Because of that part of the new YAML stuff doesn't execute.

I think maybe we should:
- Convert their RM “INT” pipeline to a build stage and plug it to the YAML publishing YAMLs
- Add a default channel for arcade-services so that all validations are executed as part of the build

For the record: talked with @mmitche and he agreed.

@riarenas @ChadNedzlek

**Comment by riarenas** [comment]
The validation epic is going to take care of converting the build + RM release pipelines into a single pipeline with stages.
@mmitche already added the default channel, and newer builds of arcade-validation are running the publishing stages.

**Comment by jcagme** [comment]
Could you please link the validation epic here or move this issue there? I didn't find one "validation" epic :)

**Comment by riarenas** [comment]
Already moved the issue, and the link is: https://github.com/dotnet/core-eng/issues/3671

**Comment by sunandabalu** [comment]
@ChadNedzlek FYI, this is the issue for moving Release Pipeline to yaml-based stages

**Comment by ChadNedzlek** [comment]
Guess I'm doing this now. :-)
