### ISSUE TITLE
Remove 'IsWpfTempProject' workaround after .NET Core Preview 8 is released

### ISSUE THREAD

**Issue by ryalanms** [dotnet/arcade#3129]
WPF for .NET Core is adding PackageReference restore to temporary project compilation in Preview 8.  When Preview 8 is released, the existing workaround needs to be removed from Arcade.  

https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Workarounds.props#L5
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Workarounds.targets#L26

**Comment by vatsan-madhavan** [comment]
We should have a tracking issue in wpf repo as well so it gets triaged and prioritized for P8.

**Comment by ryalanms** [comment]
@vatsan-madhavan: I've opened issue https://github.com/dotnet/wpf/issues/1055 in the WPF repo. Thanks.

**Comment by tmat** [comment]
We can't remove the workaround since we are not using Core WPF in most repos, but .NET Framework WPF. We can condition the workaround on TFM though.

**Comment by vatsan-madhavan** [comment]
Makes sense. In the next PR, use condition to detect WindowsDesktop Sdk (see https://github.com/dotnet/wpf/pull/1027 - there is a property you can sniff).

**Comment by markwilkie** [comment]
Seems this is resolved.  Pls reopen if not.
