### ISSUE TITLE
[darc/maestro++] Open Dependency flow PRs for assets with same version but different locations

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3131]
RIght now we only create a dependency update PR when the incoming dependency has a different version than the one already in the target branch. For stable builds, where every package has the same version and a feed will be created on every build, we need to still open the PR with the new locations for the asset.

**Comment by riarenas** [comment]
The logic to determine if we need to update a dependency is here:
https://github.com/dotnet/arcade-services/blob/58283fc186c2d68c7cd714674d37a319ed18bd0b/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs#L664

We need to also check if the asset locations in the incoming dependency are different from the existing asset. Might be a good oportunity to fix https://github.com/dotnet/arcade/issues/3107, but if #3107 is a lot of work, I'll just populate the locations in-place.

**Comment by riarenas** [comment]
This is an uncommon edge case. We will deal with it after P7.

**Comment by mmitche** [comment]
@riarenas Is this still the case? If you only depend on stable versions, you wouldn't get an update?

**Comment by riarenas** [comment]
Not the case anymore.
