### ISSUE TITLE
Coordinate the creation of an image which includes Azure CLI

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#3134]
For testing, we've been using the `BuildPool.Windows.10.Amd64.VS2017` queue to publish Universal Packages. This has a requirement to use the Azure CLI as explained [here](https://github.com/Azure/azure-devops-cli-extension#quick-start). 

Since the agents in this queue don't have the CLI installed we need to install it in a setup script which, while works fine, is not optimal.

We need to create a Windows 10 image, similar to `BuildPool.Windows.10.Amd64.VS2017` plus the Azure CLI.

/fyi: @MattGal

**Comment by markwilkie** [comment]
Moving this to FR

cc/ @MattGal

**Comment by MattGal** [comment]
Issue moved to [dotnet/core-eng #7044](https://github.com/dotnet/core-eng/issues/7044) via [**ZenHub**](https://www.zenhub.com/)
