### ISSUE TITLE
Should GenAPI be removing the ToolboxItem attribute?

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/arcade#3143]
Example usages: https://github.com/dotnet/corefx/blob/77cde697f9ee9941bdc76e02b9481d781790e86a/src/System.Diagnostics.EventLog/ref/System.Diagnostics.EventLog.cs#L101-L102
https://github.com/dotnet/corefx/blob/77cde697f9ee9941bdc76e02b9481d781790e86a/src/System.Management/ref/System.Management.cs#L136-L137

Excluded here: https://github.com/dotnet/corefx/blob/77cde697f9ee9941bdc76e02b9481d781790e86a/eng/DefaultGenApiDocIds.txt#L7

Should we be emitting these or retain them?

cc @vancem

**Comment by ericstj** [comment]
We do want this attribute present and it's currently present.  Related: https://github.com/dotnet/runtime/issues/31428
