### ISSUE TITLE
GitSync mirror should be smarter and support closing a mirror PR and updating an opened PR

### ISSUE THREAD

**Issue by safern** [dotnet/arcade#3148]
Currently if a mirror PR is failing and somethings need to be fixed in the source repo, we can't close the PR and expect the mirror to open a new one with the same commits + new ones added to the source repo.

The reason behind this behavior, is because the mirror, marks commits as "mirrored" when the PR is open, rather than when the PR is merged. I think the mirror should only consider a mirrored commit, when it makes it to the destination repo (merged PR).

Also, the mirror should be able to update a PR (e.g. if the mirror creates a PR, but there's an issue, so we go back and add another commit to the original repo and it updates the open PR with that new commit).

cc: @Anipik @stephentoub @jkotas

**Comment by markwilkie** [comment]
Moving to our GH mirror epic

**Comment by markwilkie** [comment]
Closing given that the epic closed.
