### ISSUE TITLE
[darc/maestro++] Investigate if `darc gather-drop` is working with AzDO feeds

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3152]
I remember in one of my recent tests that darc gather-drop didn't work with an asset published to AzDO feed. I'll try to look which build was that but in the meantime you can try to test with these assets:

```
Id	Location	Type	AssetId
3912	https://dnceng.pkgs.visualstudio.com/public/_packaging/darc-pub-arcade-94e2c6b4ea7d4b2e7571d93af54cc8339a8ecde4/nuget/v3/index.json	1	8819
3913	https://dnceng.pkgs.visualstudio.com/_packaging/darc-int-arcade-94e2c6b4ea7d4b2e7571d93af54cc8339a8ecde4/nuget/v3/index.json	1	8819
```

@riarenas

**Comment by riarenas** [comment]
There is no support in Gather-drop for azdo feeds. We explicitly only check if it's available in azure blob storage. I'll be working on this today.

**Comment by JohnTortugo** [comment]
Perhaps this might be of some help: https://dnceng.visualstudio.com/internal/_build/results?buildId=237612&view=logs&s=6b56b53e-c913-5b8c-161f-aef84124ab00&j=f9ae3985-dc73-54b2-790a-509de2074eb5

**Comment by riarenas** [comment]
We will not be publishing assets to public azure devops feeds for a while, so gather-drop support is not necessary until after P7. So **not** working on this today.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade/issues/3757 has more details, so closing in favor of that one.
