### ISSUE TITLE
Update VS on buildpool.windows.10.amd64.vs2019.pre.open to 16.3 Preview 1

### ISSUE THREAD

**Issue by tmat** [dotnet/arcade#3157]
Roslyn will need VS 16.3 Preview 1 build installed on the buildpool.windows.10.amd64.vs2019.pre.open machines in order to run integration tests.

We are working with the VS debugger team on a feature that is expected to be merged to VS master branch on this week (likely 6/25 or 6/26). We will need this change to be present on buildpool.windows.10.amd64.vs2019.pre.open machines in order to run Roslyn integration tests.

We will disable the integration tests while the new bits are not available, but would like to make that time span minimal to avoid potential regressions.

**Comment by markwilkie** [comment]
cc/ @MattGal

**Comment by MattGal** [comment]
This is a tricky one, my internal preview installer currently is only offering me up to 16.2 Preview 4.  We have an idea how we _might_ be able to put private internal preview builds on the public-facing (and therefore subject to their contents being exposed publicly) but I don't even think that build exists.  

Do you have any sort of ETA when that might be true?  We have an alternative option we might be able to pursue was well as a stopgap.

**Comment by tmat** [comment]
Good point. I think we need to keep the integration tests disabled for now until an official 16.3 P1 build is available. Perhaps we could run the specific integration tests that need the newer version internally. We currently don't have a infra for that, but seems like it shouldn't be hard to add a CI leg as long as we have a pool we can use.

**Comment by tmat** [comment]
@MattGal 
We decided to create an internal CI leg that would run the integration tests that require the latest build. We'd hook it up as soon as we have a pool we can use. 

I'll let you know once we have a VS build that has all the changes we need. Can you estimate how much work is it for you to roll out a new internal VS build?

**Comment by markwilkie** [comment]
Closing this, and assuming a new issue will be opened (or maybe already has) once the VS requirements are understood.

**Comment by MattGal** [comment]
yes I don't think this needs an issue, we have lots of people asking me every day for this and our SOP is for DDFUN to update all the VS images to their latest patched versions as they come out.
