### ISSUE TITLE
Windows.10.Amd64.EnterpriseRS3.ASPNET.Open doesn't have IIS installed on it anymore

### ISSUE THREAD

**Issue by jkotalik** [dotnet/arcade#3158]
We were using the agent pool Windows.10.Amd64.EnterpriseRS3.ASPNET.Open to verify ASP.NET Core bits with IIS. I'm not sure when this occurred, but right now, all tests that would normally run on IIS are skipped. We recently set up win7/win8 agents that had IIS installed: Windows.7.Amd64.Open and Windows.81.Amd64.Open. Is there a new queue we should be using to verify IIS on Win10?

**Comment by markwilkie** [comment]
cc/ @MattGal @dotnet/dnceng

**Comment by mjanecke** [comment]
Possibly related to this change: dotnet/core-eng#6608

**Comment by MattGal** [comment]
@jkotalik sorry to hear, the linked change was supposed to just reduce duplication not bring anything's counts to 0.   I'll move that back to the previous image for you, should take effect within 30 minutes, and we'll figure out what happened.

**Comment by MattGal** [comment]
It's rolled back to the previous (6/12) image and should behave as before now.  I'll move this to the core-eng repo to get properly tracked, and I'll have whoever takes on this work item get in touch with you to ensure that the right stuff ends up on the queue.

**Comment by MattGal** [comment]
Issue moved to [dotnet/core-eng #6803](https://github.com/dotnet/core-eng/issues/6803) via [**ZenHub**](https://www.zenhub.com/)
