### ISSUE TITLE
Walkthrough video link isn't accessible in Onboarding doc

### ISSUE THREAD

**Issue by dmonroym** [dotnet/arcade#3174]
This link: https://msit.microsoftstream.com/video/e22d2dad-ef72-4cca-9b62-7e33621f86a1 isn't accessible on here: 
https://github.com/dotnet/arcade/blame/master/Documentation/Onboarding.md#L5

**Comment by riarenas** [comment]
I can access it. Most likely some permission shenanigans for whoever investigates this.

**Comment by markwilkie** [comment]
Adding this to FR

cc/ @MattGal

**Comment by MattGal** [comment]
This doesn't repro for me either and we don't exactly have administrative control over anything in  https://msit.microsoftstream.com but I've assigned this to myself and will send mail to MSIT on Daniel's behalf once he's around.

**Comment by MattGal** [comment]
Walkthrough video now accessible to all MSFT FTEs, verified @dmonroym can access.  I also got owner access to it for giggles.
