### ISSUE TITLE
[darc/maestro++] Add subscriptionFrequency parameter to darc-trigger-subscriptions

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3180]
There have been a couple of times where I've wanted to trigger only subscriptions that should happen on EveryBuild, for a given repo, but there's no way for the command to filter by these. 

Having this as part of the command would also simplify the logic in https://github.com/dotnet/arcade/pull/3173

**Comment by mmitche** [comment]
Related to #3012

**Comment by riarenas** [comment]
Rolled out on 10/16
