### ISSUE TITLE
Update NuGet metadata validation script to use the stable version of the validation tool

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3187]
We use this tool to validate NuGet package metadata: https://github.com/NuGet/NuGetGallery/tree/jver-verify/src/VerifyMicrosoftPackage#script

However, this tool currently is in pre-release mode and [its usage will soon change](https://github.com/NuGet/NuGetGallery/tree/jver-verify/src/VerifyMicrosoftPackage#script):

> Note: this script currently downloads a pre-release package Jver.VerifyMicrosoftPackage. This will be switched to NuGet.VerifyMicrosoftPackage later. Also, the verify.ps1 URL will change to the master branch once this tool have been approved by some internal teams.

We'll need to adjust the `eng\common\post-build\nuget-validation.ps1` script once the tool become stable.

**Comment by riarenas** [comment]
@JohnTortugo @markwilkie Should we still run nuget validation on every build, or make this part of the ring promotion activities?

**Comment by JohnTortugo** [comment]
In a previous talk with @markwilkie he said to leave as is as this process is quite 'fast'. I think a good way for these validations to work would be:

- Leave OFF by default in the 'Validate' stage, as they take time and some are flaky. Still people can make them run for every build if they want to..
- Leave ON by default in the eventual ring-based release process - if the validation was already run in a previous stage just by skip it.

**Comment by riarenas** [comment]
Makes sense. Do we have an issue to turn this off by default in the post-build stages?

**Comment by JohnTortugo** [comment]
The slow ones are already disabled by default. Signing validation is potentially slow but it's a stable (not flaky) and quite important one so we left it enabled by default.

**Comment by JohnTortugo** [comment]
As of today the `verify.ps1` script still use pre-release tools.

**Comment by riarenas** [comment]
Worth revisiting in the .NET 5 timeframe to see if more development has been done to the tool

**Comment by riarenas** [comment]
We should also see if the tool is being distributed in a better way than just copying the latest from GitHub, as mentioned in #3799

**Comment by jcagme** [comment]
Fixed with https://github.com/dotnet/arcade/pull/4838
