### ISSUE TITLE
Create initial Build Asset registry implementation

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#319]
@alexperovich commented on [Mon Jul 02 2018](https://github.com/dotnet/core-eng/issues/3813)

@jcagme the initial framework is here: https://github.com/alexperovich/arcade/tree/alperovi/svcFabMaestro/src/Maestro

**Comment by jcagme** [comment]
Assigning this to Alex since he will continue to work on BAR. Pending things:

* Test request by adding a valid auth token
* Read the DB connection string from KeyVault
* Define deployment story
