### ISSUE TITLE
Update Newtonsoft.Json and Microsoft.Net.Test.Sdk dependencies

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#3194]
Newtonsoft.Json's version is currently pinned to 9.0.1 in arcade. This package is transitively referenced by the Microsoft.Net.Test.Sdk package. Referencing a higher version does not interfere with the the Test SDK as higher versions are allowed: https://github.com/microsoft/vstest/blob/fb3545cf67530577c7bc6d3340c7f92057e07f11/src/package/nuspec/TestPlatform.TestHost.nuspec#L19

Any concerns upgrading Newtonsoft.Json to 12.0.2 and Microsoft.Net.Test.Sdk to 16.2.0?

cc @ericstj @tmat

**Comment by ericstj** [comment]
@dseefeld @crummel since it may impact source build.

I’m OK updating.

**Comment by ViktorHofer** [comment]
@tmat do you whom I should additionally ping to make sure this change is ok and won't break a? consumer

**Comment by crummel** [comment]
Source-build should be ok with this, we've started building the 12.0.2 Newtonsoft.Json version.

**Comment by markwilkie** [comment]
This needs to wait until after P7 has shipped, but assuming no known breaking changes, I'm ok w/ the change in general.  (again, after P7 ships)

@ViktorHofer - can you confirm there are no known breaking changes?

**Comment by tmat** [comment]
@ViktorHofer I think we just need to merge and see if anything fails when the change gets to each repo.

**Comment by markwilkie** [comment]
But not merge before P7 ships please....  :)

**Comment by ViktorHofer** [comment]
Understood :)

**Comment by markwilkie** [comment]
What's the latest here @ViktorHofer ?

**Comment by ViktorHofer** [comment]
I was waiting for arcade to branch before finishing this. Are we there now?

**Comment by markwilkie** [comment]
Cool - so this is not needed for 3.0?  If so, then yes waiting is great.  Thanks!

**Comment by ViktorHofer** [comment]
Right this is just making sure that our dependencies are up-to-date. This can wait.

**Comment by markwilkie** [comment]
@ViktorHofer - feel free to check into master now that we've branched.

**Comment by saidurgas** [comment]
any updates on this ?

**Comment by ViktorHofer** [comment]
Closing as I don't plan to do this anymore.
