### ISSUE TITLE
[darc/maestro++] Branches for auto-update PRs aren't deleted if manually merged

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/arcade#3214]
We've recently enabled the Maestro/Darc auto-update PRs on the https://github.com/mono/mono repo.

Since we can't use the auto-merge capability yet (restrictions like #1758), we're manually merging the PRs. However we've noticed that the bot doesn't delete the `darc-master-*` branches after the PR is merged which clutters our repo branches.

See e.g. https://github.com/mono/mono/branches/all?utf8=%E2%9C%93&query=darc-master

Is this by design or a bug?

/cc @riarenas

**Comment by riarenas** [comment]
We currently completely back off when we detect that a PR has been manually merged or abandoned.

I don't think it would be a lot of work to implement a check where we delete the PR branch when we detect this has happened, and I think it's a reasonable ask.

@mmitche any thoughts?

**Comment by riarenas** [comment]
Need to check if this is still the case

**Comment by akoeplinger** [comment]
Yes it still happens.

**Comment by riarenas** [comment]
Noted. Thanks @akoeplinger.
