### ISSUE TITLE
[darc/maestro++] Maestro should not auto-merge downgrades

### ISSUE THREAD

**Issue by nguerrera** [dotnet/arcade#3216]
If an update causes a package to be downgraded, it should add a warning message to the PR and not merge.

See https://github.com/dotnet/core-sdk/issues/2701#issuecomment-507733147

It appears that something was incorrect in the code flow for roslyn there. It would have been very helpful if this caused an alert and didn't just auto merge a downgrade.

@mmitche @riarenas

**Comment by mmitche** [comment]
Agreed on not automerging the downgrades. The roslyn issue sounds somewhat familiar...I think somethign similar happened a while back and it was because the 'latest' build was an old version.
