### ISSUE TITLE
[Maestro] Tweak the regex for private feeds to the internal proxy + feeds.

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3220]
We need to be able to handle both the private proxy based feeds, as well as the yet to come private azure devops feeds in Maestro so that we flow them to the correct place.

@jcagme, do you think we need to also flow the proxy based feeds to versions.props?

**Comment by riarenas** [comment]
I believe the changes required for this are:

Need a second Regex next to this one for the proxy feeds here: 
https://github.com/dotnet/arcade-services/blob/6563955f7fb3c1c29a9c5e9c3e64cb35087016af/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs#L27

This needs to also return true if it's a proxy feed: https://github.com/dotnet/arcade-services/blob/6563955f7fb3c1c29a9c5e9c3e64cb35087016af/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs#L253


https://github.com/dotnet/arcade-services/blob/6563955f7fb3c1c29a9c5e9c3e64cb35087016af/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs#L944 needs to know if it's a proxy feed or an azure devops feed to construct the key.

**Comment by riarenas** [comment]
The blob feeds look a bit different than azdo feeds. Still needs a little work.

**Comment by riarenas** [comment]
Fix in https://github.com/dotnet/arcade-services/pull/516

**Comment by JohnTortugo** [comment]
@riarenas this can be closed, right?
