### ISSUE TITLE
Building with SourceLink fails when there is no Git remote named "origin"

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#3236]
Noticed in https://github.com/dotnet/iot/issues/553.

I also encountered this while porting Core-Setup to Arcade, but didn't look into it yet to find this cause. (I disabled SourceLink for now in that effort.)

Repro:

```
git clone https://github.com/dotnet/arcade
cd arcade
git remote rename origin dotnet
.\Build.cmd
```

```
C:\Users\dagood\.nuget\packages\microsoft.sourcelink.common\1.0.0-beta2-19351-01\build\Microsoft.SourceLink.Common.targets(50,5): error : Source control information is not available - the generated source link is empty. [D:\temp\remote\arcade\src\Microsoft.DotNet.SignTool\Microsoft.DotNet.SignTool.csproj]
...
```

**Comment by tmat** [comment]
This is not an Arcade issue, but rather SourceLink issue. 
Would https://github.com/dotnet/sourcelink/issues/306 address it?

**Comment by dagood** [comment]
Not sure, what happens if `origin` doesn't exist and the current branch has no tracking reference? (Or no branch is checked out?)

**Comment by tmat** [comment]
Why would that be the case? Sure, if you go out of your way to break it, it will break.

**Comment by dagood** [comment]
These seem pretty mainstream:

1. I haven't pushed the branch to any remote yet.
2. I'm trying to build commits to do a binary search on a bug's root cause.

If I have to disable sourcelink to do those (or temporarily add some `origin` remote), fine by me, but the error message should at least be actionable IMO.

**Comment by tmat** [comment]
Definitely agree that the error message could be better. https://github.com/dotnet/sourcelink/issues/324
BTW, currently we first check for `origin` then for any other remote (the first one). dotnet/sourcelink#306 suggests to check the remote tracking branch before falling back to `origin` or other remote.

**Comment by dagood** [comment]
> BTW, currently we first check for `origin` then for any other remote (the first one).

Interesting, this behavior sounds fine to me. Why is the repro in the issue description resulting in an error, then? It has a remote `dotnet` and fails with the `Source control information is not available` message.

**Comment by tmat** [comment]
What is the output of `git remote -v`?

**Comment by dagood** [comment]
```
#> git remote -v
dotnet  https://github.com/dotnet/arcade (fetch)
dotnet  https://github.com/dotnet/arcade (push)
```

**Comment by tmat** [comment]
Odd, that _should_ work. Will take a look.

**Comment by tmat** [comment]
Figured out what the issue is with `dotnet` remote. Fixing.
