### ISSUE TITLE
[Maestro++] Azdo auto merge E2E test is broken

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3242]
Test is failing since https://github.com/dotnet/arcade-services/pull/454 and is causing all deployments to report failure. 

I'll disable the test while https://github.com/dotnet/arcade-services/pull/505 fixes the issue.

**Comment by riarenas** [comment]
CC @jonfortescue

**Comment by riarenas** [comment]
Jon, assigned this to you, as it's the tracking issue for the PR you've been working on.

**Comment by jonfortescue** [comment]
PR merged; closing this.
