### ISSUE TITLE
Clean up once we switch to AzDO internal feeds

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3252]
Once we decide to switch to AzDO internal feeds we'll need to do some clean up in a few places that we had to implement workarounds to mimic AzDO internal feeds behavior:

- [x] Adjust SetupTargetFeed.proj to call the Tasks.Feed task that create AzDO feeds
- [x] Adjust SetupTargetFeed.proj logic in face of new scenario
- [x] Delete Tasks.Feed CreateInternalBlobFeed
- [x] Delete proxy wrapper for AzureStorage "Internal" feeds
- [x] Remove Parsing / processing logic of proxy-backed feeds in Darc / Maestro

/cc @riarenas @jcagme  in case I miss{ed, understood} something.

**Comment by riarenas** [comment]
@johntortugo Looks like most of these are done, could you do another check and close if that's the case?
