### ISSUE TITLE
Stop using RestoreSources from versions.props in Arcade SDK

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3259]
The work in https://github.com/dotnet/arcade/blob/master/Documentation/RestoreSourcesUpdateStatus.md
and https://github.com/dotnet/arcade/pull/3041 need to be completed before we can restore from private authenticated feeds, and from the proxy backed private blob feeds.

**Comment by riarenas** [comment]
This effort has been completed

**Comment by jcagme** [comment]
Based on https://github.com/dotnet/arcade/blob/master/Documentation/RestoreSourcesUpdateStatus.md this hasn't been completely done, we still need to remove RestoreSources from some repos.
