### ISSUE TITLE
Build fails on OSX with curl (23)

### ISSUE THREAD

**Issue by livarcocc** [dotnet/arcade#3282]
This seems to happen because the arcade scripts try to find a dotnet already installed on the machine to use. If it finds a dotnet in the path, it uses that to search for the specified sdk version in that location.

If it does not find the specific version, it tries to download the install script and install the required version to that location.

The issue happens because in osx (and linux), the global location in a write protected location, which then causes the build to fail.

This will happen to anyone building that has a global install of the .NET Core SDK but does not have the exact SDK version the repo wants installed globally.

**Comment by livarcocc** [comment]
Looked more into this. This happens when you do have the desired SDK installed in the global location. For some reason arcade still tries to download the install script and chooses to put in the global location, which we don't have permission to write to.

**Comment by markwilkie** [comment]
Making this FR  (@MattGal )

Also including @riarenas as he has bootstrapping experience which might be relevant.

**Comment by MattGal** [comment]
@livarcocc - can you please link a build or two that is hitting this problem to expedite investigation???

**Comment by MattGal** [comment]
Chatted with Livar:
>  I think the fix is for core-sdk to stop having its own code to acquire additional runtimes and instead use arcade for that
>   at the time we wrote this code, arcade did not have that capability

... so closing this one for now, we can restart the discussion if the arcade functionality has issues.
