### ISSUE TITLE
Run SDL Job is failing official builds with failure during tool installation

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3294]
See: https://dev.azure.com/dnceng/internal/_build/results?buildId=266492 for an example

CC @sunandabalu

**Comment by sunandabalu** [comment]
Looking

**Comment by sunandabalu** [comment]
Service Connection used to connect to secure guardian feed needed some fixing, SDL step succeeded in the arcade official build [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=267827&view=logs&s=3df7d716-4c9c-5c26-9f45-11f62216640d&j=7d9eef18-6720-5c1f-4d30-89d7b76728e9)

**Comment by JohnTortugo** [comment]
Looks like this is happening again: https://dnceng.visualstudio.com/internal/_build/results?buildId=274788&view=results

**Comment by sunandabalu** [comment]
This was due to the PAT used to connect to Guardian Secure feed disappeared, this is restored and the builds are working now. 
https://dev.azure.com/dnceng/internal/_build/results?buildId=274944&view=results
