### ISSUE TITLE
[Maestro++ /Darc] Harden SynchronizePullRequest

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3298]
If there is a failure during SynchronizePullRequestAsync when a dependency update is triggered, we create a new PR, and lose track of the old one. This is noisy as we don't try to close the old PR beforehand, and we'll end up with multiple PRs open at the same time for the same subscription, which causes confusion because only the newer one is still managed by Maestro.

We should harden this method a bit to try and mitigate this problem:

1. Harden the octokit api calls with retries in case of Github being flaky with their response codes (it's a thing...)

2. Attempt to close the existing PR before creating a new one and add a comment to the PR saying that there was an error, and to look for a new PR.

**Comment by mmitche** [comment]
Most of the issues I think come down to the default return value of ActionRunner when an exception is hit. For a `bool?`, this would be null. `null`, however, is used as a non-exceptional condition value (PR should no longer be tracked).

**Comment by mmitche** [comment]
I think this has been resolved with the removal of bool?

**Comment by riarenas** [comment]
Haven't seen any of the errors I used to see regarding this.
