### ISSUE TITLE
Make running PoliCheck on every PR easy

### ISSUE THREAD

**Issue by Eilon** [dotnet/arcade#331]
See original ASP.NET (private) issue here: https://github.com/aspnet/Coherence-Signed/issues/431

We would like to run PoliCheck via dotnet-ci on every PR.

* The results of the run must remain MS-internal (i.e. require AD auth)
* The success/failure status can be public via a GitHub "PR check status"
* The list of exclusions needs to remain MS-internal, and would likely be a single point shared between all repos (but perhaps versioned by branch)

**Comment by markwilkie** [comment]
Created a new epic (#335) to track SDL work and added this issue to it.  The epic is not yet prioritized, but needs to be before we get too far down the road.

**Comment by jonfortescue** [comment]
@mmitche has recommended making a GitHub app to accomplish this. I think that's the route I'm going to go.

**Comment by markwilkie** [comment]
@Eilon - how important is it to run policheck on every PR?  (Sadly, I missed the part that this is for every PR...yes, I know it's in the freaking title...grin)   Not only are there performance implications, but there are others issues too around disclosure.  So...I'm hoping to get a bit better sense of the business case for PR vs. official builds.

**Comment by Eilon** [comment]
It's not the most critical thing. But it's of course nice to have errors found as early as possible. But there's clearly a trade-off in this case in terms of cost vs. benefit.

**Comment by jonfortescue** [comment]
@Eilon Per policy we will not be able to implement this. Will ping you offline to explain.
