### ISSUE TITLE
[darc/maestro++] Normalize branch names

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3311]
We need to add branch names validation in a few places in the Maestro API to prevent users from inserting "invalid names". Valid branch names should match the format used by $(Build.SourceBranch) AzDO variable.

/cc @riarenas @mmitche

**Comment by mmitche** [comment]
@JohnTortugo Do you mean forgetting the `refs/heads` bit for default channels, or entering a truly invalid git branch name?

**Comment by JohnTortugo** [comment]
Yeah, just missing the "refs/heads" part

**Comment by mmitche** [comment]
I think we should just normalize the inputs, rather than rejecting requests without it.  The refs/heads bit isn't that interesting from a user's perspective.

**Comment by riarenas** [comment]
I was actually looking for an issue I thought I created about normalizing the branch names throughout the API, but I guess I never opened it. I agree we should just normalize.

**Comment by JohnTortugo** [comment]
Yeah, normalizing is fine. At the end my point was really to maintain a consistent format all around in BAR.

**Comment by JohnTortugo** [comment]
This was hit again twice by a user.
