### ISSUE TITLE
[darc/maestro++] LibGit2Sharp.NonFastForwardException

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#3318]
Was looking at exception logs for a mono related issue and found the following:

`outerMessage: Something went wrong when pushing the files to repo https://github.com/aspnet/AspNetCore in branch darc-master-476f351a-abe1-4756-a861-a8570dd8e5ee.` 

`innermostMessage: cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.`

@mmitche @riarenas

**Comment by mmitche** [comment]
Thanks.  I wonder if it's a timing issue...got a link to the appinsights message?

**Comment by jcagme** [comment]
I found it by just querying exceptions in the last 24 hours but [this](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/AnalyticsBlade/initiator/AnalyticsShareLinkToQuery/isQueryEditorVisible/true/scope/%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2Fresourcegroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod%22%7D%5D%7D/query/H4sIAAAAAAAAA0utSE4tKMnMzyvm5apRKM9ILUpVKCjKT8pJzfVMUUjOzytJzMwrVlDyyUxyzywxCs5ILCrQ88vPc0ssLnHLLypPLEpxhRmhpMAFAO7e0d1PAAAA/isQueryBase64Compressed/true/timespanInIsoFormat/P1D) should give you the exact hit.

**Comment by mmitche** [comment]
We should reenable mono subscriptions again and see what happens.

**Comment by riarenas** [comment]
Mono subscriptions have been re-enabled for a while and are working.
