### ISSUE TITLE
[darc/maestro++] Roslyn with multiple arcade PRs from master

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#3324]
I found the following PRs in Roslyn, I think instead of having three different PRs in theory there should only be one with 3 commits?

* https://github.com/dotnet/roslyn/pull/37245
* https://github.com/dotnet/roslyn/pull/37249
* https://github.com/dotnet/roslyn/pull/37277

Found this by looking at Timeout exceptions. I used [this](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/AnalyticsBlade/initiator/AnalyticsShareLinkToQuery/isQueryEditorVisible/true/scope/%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2Fresourcegroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod%22%7D%5D%7D/query/H4sIAAAAAAAAA7WPTQuCQBCG74H%2FYfBiHSzXz1UwCEKSoi7dY10nkvCDdcuKfnxaULeog7fhmXfm5ZGCcayVwR1ORVYWgBeOlWynJ2sOKBDKCgXr2C5OIQxB9RPPtyj3dNui1PFdm%2B5NYji2q0J3VYoUBSRXkFmOtWR5Bazm7UoZyHfd6%2FUnMQ1BlimT2KGhZhrE1w1PJ3RLzIBYgUHHpmVro58L%2FvCJJuuYkdm5WcZhzwqO24%2FC5ibq1SISc378rvAAP1FA2vEBAAA%3D/isQueryBase64Compressed/true) to do some debugging and it looks like https://github.com/dotnet/roslyn/pull/37277 was created correctly but then there was a strange timeout when Maestro checks for the status of the PR. This is better viewed by

```
traces
| union exceptions
| where operation_Id == "OzrsLHFrDck="
| order by timestamp asc
```
I thought we would spun a new process each time we check the status of a PR and kill it at the end and do this every 5 minutes but it looks like we create a new process and check for the status every 5 seconds. If the PR is still open after 5 minutes the process times out (and probably looses track of the PR hence opening new ones instead of adding commit to existing)

Also weird since in theory all operations should timeout after 10 minutes not 5 after https://github.com/dotnet/arcade-services/pull/253/files#diff-f241fdbf8c137f7576996080d603577bR17

@mmitche @riarenas @alexperovich

**Comment by mmitche** [comment]
Thanks for the analysis.

**Comment by mmitche** [comment]
This was fixed by the August rollout
