### ISSUE TITLE
[darc/maestro++]  Maestro++ better squashing

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#3328]
When Maestro++ update commits intermingle with dependency update commits, the squashed history is pretty bad: https://github.com/aspnet/AspNetCore/commit/771989b71dbfcdfed4093a5087948fbe87445bd6

We should either not auto-merge this if the commit description is going to be so long, or squash in a better way.

**Comment by mmitche** [comment]
This may not be necessary for .NET 5 because of reduced number of repos

**Comment by dougbu** [comment]
@mmitche if this is about dependency update PRs that intermingle users' reaction commits, I'm all for it!

I'm not sure the future reduced number of repos will make a fix unnecessary though it may make problems less frequent. For ASP.NET Core at least, the number of incoming dependencies is likely to remain high. We can handle _one_ EntityFrameworkCore dependency update description in the final commit now. We'll likely be able to handle at most _two_ core dependency update.

**Comment by mmitche** [comment]
@dougbu Maybe we do this in concert with simplifying the commit messages in the first place? There is some level of duplicated info (e.g. For a lot of cases, we're seeing the same coherent parent info and version info. We could collapse that. For example:

Instead of:
```
Microsoft.AspNetCore.Analyzer.Testing -> 5.0.0-alpha1.19467.2 (parent: Microsoft.EntityFrameworkCore)
Microsoft.AspNetCore.BenchmarkRunner.Sources -> 5.0.0-alpha1.19467.2 (parent: Microsoft.EntityFrameworkCore)
```

Do:

```
Microsoft.AspNetCore.Analyzer.Testing, Microsoft.AspNetCore.BenchmarkRunner.Sources -> 5.0.0-alpha1.19467.2 (parent: Microsoft.EntityFrameworkCore)
```

**Comment by epananth** [comment]
After discussing with  @riarenas  found another corner case for this issue : 

dotnet/arcade-validation@e788b97

If the dependency update is from the same repo and the builds differ then just get the latest build number and discard the older ones.
