### ISSUE TITLE
Cannot build locally "The system cannot find the file specified"

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#3357]
In current CLI master https://github.com/dotnet/cli Is this a known issue?

```
.\build.cmd
at Exec-Process, C:\work\cli\eng\common\tools.ps1: line 75
at MSBuild-Core, C:\work\cli\eng\common\tools.ps1: line 528
at InitializeToolset, C:\work\cli\eng\common\tools.ps1: line 455
at Build, C:\work\cli\eng\common\build.ps1: line 78
at <ScriptBlock>, C:\work\cli\eng\common\build.ps1: line 133
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, C:\work\cli\run-build.ps1: line 27
at <ScriptBlock>, <No file>: line 1
(NETCORE_ENGINEERING_TELEMETRY=InitializeToolset) Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
Failed to build
At C:\work\cli\run-build.ps1:28 char:27
+ if($LASTEXITCODE -ne 0) { throw "Failed to build" }
+                           ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to build:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to build
```

**Comment by jcagme** [comment]
Just did `build.cmd` from cli's root and got pass the build part (it failed creating the packages due to a random lock error). Do you have any local changes maybe?

**Comment by wli3** [comment]
I did `git clean -fxd`. I made sure no local change. Just pull master and run `build.cmd`. I can build the last build and after I pull the latest, I cannot. Could you repo it?

**Comment by jcagme** [comment]
I pulled latest master and build and other that those random errors I mentioned build was fine. Let’s sync tomorrow to see what’s wrong

**Comment by wli3** [comment]
I delete the whole folder, and pulled again, it worked. I think something wrong with my local git. Thanks!
