### ISSUE TITLE
[Versioning] Should FileVersion contain the number of builds done per-day

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#336]
Today the file version for core repos looks like `$(MajorVersion).$(MinorVersion).$(VersionSuffixDateStamp).$(VersionSuffixBuildOfTheDay)` (https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets#L24).

The versioning targets in arcade currently look like:

`$(MajorVersion).$(MinorVersion).$(Revision).$(VersionSuffixDateStamp)`. 

So the question is whether or not we need to include `$(VersionSuffixBuildOfTheDay)`? 

There are definitely times where we would want/need to build multiple times a day and in those times we need to ensure the FileVersion is unique, it is for those reasons I think we need the `$(VersionSuffixBuildOfTheDay)` to be included in the file version so that installers can correctly support install/upgrade from build to build. 

see further discussion at https://github.com/dotnet/arcade/pull/332/files#r202861690. 

cc @tmat @mmitche

**Comment by weshaggard** [comment]
I think something like `Revision = ServicingVersion * 100 + VersionSuffixDateStamp[0..2]` would likely work.

**Comment by tmat** [comment]
It wouldn't be different. In FileVersion it would just be split to two parts.

**Comment by weshaggard** [comment]
That's fair and seems reasonable. 

For better or worse we currently have different file and package versions for most of our stuff. For example System.Memory:
```
FileVersion = 4.6.26606.5
PackageVersion = 4.5.1 (or 4.5.1-servicing-26606-05)
```

This came from the fact we needed to ship some binaries at 4.6+ file version when we transitioned to open source and so that kind of ended up being the default for all our new libraries (https://github.com/dotnet/corefx/blob/master/Directory.Build.props#L12). I may try to re-baseline them when we move to this new versioning scheme and start sharing the file version and package version.

**Comment by tmat** [comment]
@markwilkie Yes, I'll update the versioning spec once we arrive to an agreement. 

@jaredpar @jasonmalinowski 

The current proposal is:

```
FileVersion = Major . Minor . Build . Revision

Build = ServicingUpdate * 100 + {2 digit year}
Revision = {day in the current year} * 100 + {build of the day}

DateStamp in PackageVersion = "{2 digit year} * 1000 + {day in current year}" "-" "{build of the day}"
```

Example
```
FileVersion = 1.2.118.15201
PackageVersion = 1.2.1-beta-18152-01-sha
```

**Comment by jasonmalinowski** [comment]
Ugh, "day in the current year" is quite indecipherable, but I'm not coming up with many better ideas, I'll admit.

**Comment by tmat** [comment]
@jasonmalinowski We could have `mmddb` if we don't expect more than 10 builds per day. I think that's pushing it though. Is the current number we use in Roslyn more decipherable? I don't think anyone is able to decipher it without looking in the build targets.

**Comment by tmat** [comment]
How about `(50 * m + d) * 100 + b`?

**Comment by weshaggard** [comment]
>Ugh, "day in the current year" is quite indecipherable, but I'm not coming up with many better ideas, I'll admit.

I had the same reaction initially an then I figured I generally only ever look at build numbers relative to each other and usually don't care the exact date and figured I could live with it. I also don't have a good alternative. The core used a "number of months since project start" and "day in the month" and skipped out on the year. With the currently split I don't think we can get away with that length unless we move things around. 

>How about (50 * m + d) * 100 + b?

I'm not sure that helps anything in my head.

**Comment by tmat** [comment]
It's easier to divide by 50 in head to see the month ;)

**Comment by tmat** [comment]
Updated the spec with previously implemented changes and the latest FileVersion proposal: https://github.com/dotnet/arcade/pull/353

**Comment by jasonmalinowski** [comment]
@tmat I guess the thing I kinda do sometimes is look at the dd part just to quickly judge the oldness of something. If I know some build/dump I'm looking at is a few days old, and today is the 23rd, it's helpful to know if the binary was build the 22nd or 21st or something. And that I can do fairly quickly without fancy math.

**Comment by markwilkie** [comment]
@weshaggard @jaredpar @jasonmalinowski

You guys satisfied?  Unless I get pushback, I'll close this issue.  Thanks @tmat for updating the spec.

**Comment by weshaggard** [comment]
I'm fine with attempting to use `(50 * m + d) * 100 + b`, if that turns out to be troublesome then we can consider changing it later.

**Comment by maririos** [comment]
This is covered as documentation here: #353 still need to implement it

**Comment by maririos** [comment]
Added with PR https://github.com/dotnet/arcade/pull/438/files
