### ISSUE TITLE
[Versioning] Need to add support for generating C++ header files with version info

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#338]
Our native binaries also need to have the version information so we need to include add some support for generating a header file using the same versioning information. See https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets#L78

cc @tmat @mmitche

**Comment by weshaggard** [comment]
Beyond just the header file we also need to generate the rc file for windows and on non-windows we generate a version.c file with a variable that contains the version which we need to handle as well.

**Comment by markwilkie** [comment]
@weshaggard will likely end up implementing

**Comment by jcagme** [comment]
Can this be closed now?
