### ISSUE TITLE
VersionPrefix is overwritten when PreReleaseVersionLabel is empty

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/arcade#3386]
As part of the release activities for MSBuild 16.2, we removed `PreReleaseVersionLabel` to start generating release packages: microsoft/msbuild#4478.

We didn't notice until it was too late that this produces bad versions. Instead of `16.2.0`, we produced `16.2.32702`, affecting both the version stamped into the binaries:

![image](https://user-images.githubusercontent.com/3347530/61894177-77a3c780-aed5-11e9-943f-d00afde8ae11.png)

and the NuGet package version.

The implementation comments this explicitly:

https://github.com/dotnet/arcade/blob/3dfa62fddcde597959c323d17426f215384e773a/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets#L59-L69

But it doesn't make sense to me. Shouldn't dropping the prerelease from `16.2.0-prerelease` result in `16.2.0`?

**Comment by tmat** [comment]
This is documented in https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md

Setting `PreReleaseVersionLabel` to empty means the project is opting into "release-only" versioning, meaning there is no pre-release package for this project. 

`DotNetFinalVersionKind` is supposed to be used to control labels on packages. Setting it to `release` will drop the pre-release label.

**Comment by rainersigwald** [comment]
I read that document three times before filing this and don't think it's clear on that at all. Also cc @chcosta

**Comment by tmat** [comment]
What is not clear?

**Comment by nguerrera** [comment]
What should PreReleaseVersionLabel be when DotNetFinalVersionKind is release? Seems weird if it has to be non empty.

**Comment by rainersigwald** [comment]
Indeed. Having orthogonal controls for "update X if from `preview1` to `previewN`" and "drop prerelease entirely" seems like a pit of failure.

What is your expected procedure for "going production"? Can you document that, at least?

**Comment by tmat** [comment]
`PreReleaseVersionLabel` specifies what label should be used when building package with pre-release label. It does not specify that the build is final release build. That's controlled by `DotNetFinalVersionKind`. It is possible to take any snapshot of a repo and build final release build without making a change to the repo (updating the value of `PreReleaseVersionLabel`).

Alternatively, some repos build release packages on every build (repackaging pre-release ones). `PreReleaseVersionLabel` stays unchanged in that case as well.

**Comment by tmat** [comment]
> What should PreReleaseVersionLabel be when DotNetFinalVersionKind is release?

IIRC the idea was that repos just use `preview1`, ..., `previewN`. When we decide to make final build we won't change the PreReleaseVersionLabel but instead set DotNetFinalVersionKind to "release".

**Comment by markwilkie** [comment]
Thoughts @rainersigwald ?

**Comment by rainersigwald** [comment]
Sounds like there's an outstanding request to document the "what should I do when my repo is ready for a final release?" question.

**Comment by markwilkie** [comment]
ack - moving to our tracking priority for that.

cc/ @mmitche
