### ISSUE TITLE
Improve post-build onboarding documentation

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3389]
- Make clear how to override feeds
- Make clear how to test before onboarding
- Make clear the issue about symbol validation

**Comment by riarenas** [comment]
As more repos are onboarding, we are getting a lot of questions regarding the points you mention in this issue. Are you actively working on this?

(Also, we're getting the same questions from a lot of folks as to why the steps that run as part of the different stages, and why they see a bunch of skipped jobs per stage. Would be great to add the known issues with AzDO stages right now, and why we had to implement those workarounds)

**Comment by jcagme** [comment]
What @riarenas said! Last email is a good example and I would use it as an exercise on what to include in that section

**Comment by JohnTortugo** [comment]
Yeah, fully agree with you. I'll work on this today.

**Comment by riarenas** [comment]
Load balancing and assigning to myself.
