### ISSUE TITLE
[Versioning] Use consistent Major/Minor properties for versioning

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#339]
Today our versioning targets assume that VersionPrefix will be set to the correct 3 part format before we take and use it in various places. Instead of making that assumption I suggest we break the version apart and setup our VersionPrefix in the targets itself so we can have consistent property names for the different parts. 

I propose we use: `$(MajorVersion)`, `$(MinorVersion)`, and perhaps `$(RevisionVersion)` pending the outcome of https://github.com/dotnet/arcade/issues/336. 

Then we set VersionPrefix to be `$(MajorVersion).$(MinorVersion).$(RevisionVersion)` in our targets.

cc @tmat @mmitche

**Comment by maririos** [comment]
If `versionprefix` is empty, set it to the 3 properties

**Comment by maririos** [comment]
Done with PR https://github.com/dotnet/arcade/pull/438/files
