### ISSUE TITLE
Improve post-build onboarding experience

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3390]
Specifically, can we provide an easy way for people to test the onboarding before they merge the onboarding PRs? That means:

- customer won't need to create default branch mappings for test branches
- get the packages published to a test feed
- ..?

/cc @jcagme @mmitche @riarenas

**Comment by riarenas** [comment]
Can we have a "Test" channel and stage that would trigger automatically if no default channel mapping is found?

**Comment by JohnTortugo** [comment]
I was thinking something on those lines as well

**Comment by riarenas** [comment]
I guess the only annoyance is that it would be yet another stage that does nothing most of the time, but yeah, would simplify the onboarding testing so as to not have to set up short lived default channels.

**Comment by mmitche** [comment]
Would the test feeds be public or private? What happens if I push an internal branch that doesn't have a normal default mapping (for example, a dev branch for an MSRC PR).  What would happen?

**Comment by JohnTortugo** [comment]
I was thinking this would run only in the "public" ADO project. Would that prevent the issue you pointed out @mmitche ?

@riarenas I think this way of _always_ showing _all_ default channels in the build UI isn't good. I think we'll need to change that.

**Comment by riarenas** [comment]
> @riarenas I think this way of always showing all default channels in the build UI isn't good. I think we'll need to change that.

Isn't that going away when we can trigger stages automatically? I thought the only reason we need to run and show every stage right now is that:
1. We can't hide stages yet
2. We need to read the default channel that the build would be assigned to in order to run the right stage.

**Comment by riarenas** [comment]
>I was thinking this would run only in the "public" ADO project. Would that prevent the issue you pointed out @mmitche ?

Remember that the public project has no access to any secrets, so no way of actually publishing to anywhere.

**Comment by JohnTortugo** [comment]
> Remember that the public project has no access to any secrets, so no way of actually publishing to anywhere.

We can do something in Tasks.Feed and implement a kind of DryRun mode. We'll also need to do something on those lines for the jobs/stages that access Maestro.

**Comment by JohnTortugo** [comment]
> Isn't that going away when we can trigger stages automatically? I thought the only reason we need to run and show every stage right now is that:

Yeah, those are the reasons. I was thinking to find some workaround (for hiding unactivated stages), though. The difficulty here is that we only know which stages should be activated after the YAML stages have been expanded..

**Comment by mmitche** [comment]
Okay, so if someone wanted to test the onboarding today, pushing to the internal repo and assigning the build to a test channel after the build is done will not work today?

**Comment by riarenas** [comment]
That could work. I guess the only concern would be that you won't actually see the packages being published as part of a stage, and would instead happen in a release pipeline, but as long as we have the pipeline do the same thing we do for the validation channel stage right now, and point people to where the pipeline is at, it may be good enough?

**Comment by mmitche** [comment]
You can still go and find the release pipeline, right? We could put some info in the docs for that.

**Comment by riarenas** [comment]
Yeah. I think it's a good compromise.

**Comment by riarenas** [comment]
All repos are onboarded, and we have some alternatives to help with testing.
