### ISSUE TITLE
[darc/maestro++] Use sparse and shallow checkout when pushing files

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#3394]
We found that big repos such as mono spend a big amount of time cloning the repo since we get all the files and not just the files we will update or add. To make this better we could shallow clone the target repo and sparce checkout `NuGet.config`, `global.json` and the `eng/` folder.

This should shave off several minutes from the cloning and pushing process making things faster in general and also avoiding annoying timeouts.

cc: @riarenas @mmitche

**Comment by riarenas** [comment]
Reopening and moving to rollout
