### ISSUE TITLE
Maestro PR builds failing after recent changes in SDK

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3399]
We got a few PR builds failing after recent changes in Arcade.SDK. Some of the builds are:

https://github.com/dotnet/cli/pull/11987
https://github.com/dotnet/sdk/pull/3453

I fixed build for [#3453](https://github.com/dotnet/sdk/pull/3453) by adding new feeds to NuGet.config but I'm afraid in time these problems might show up in other repos.

@tmat @jcagme @livarcocc

**Comment by vatsan-madhavan** [comment]
Is every repo being asked to add these to NuGet.config? WPF's builds are failing as well. 

```xml
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="nuget-nugetclient" value="https://dotnetfeed.blob.core.windows.net/nuget-nugetclient/index.json" />
    <add key="myget-dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
```

**Comment by jcagme** [comment]
**All** feed endpoints should be located in NuGet.config. We did the initial part of copying things in `Versions.props` to `NuGet.config` but there are repos which define `RestoreSources` in `.csproj`, `.targets`, `.props`, etc. we didn't work on those.

Also, before, Arcade use to add feeds automatically depending on conditions, https://github.com/dotnet/arcade/pull/3041/files#diff-f1b1f6d246bc1f9a81d8ea1c4498e3a5L108. Now, needed feeds will need to be added to `NuGet.config` as well.

**Comment by vatsan-madhavan** [comment]
In the PR's below, are you saying that RestoreSources should have moved from eng\Versions.props to NuGet.config, and NuGet.config should have been updated with additional feeds? 

- https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/2324?_a=files&path=%2Feng%2FVersions.props - 
- https://github.com/dotnet/wpf/pull/1399/files

**Comment by jcagme** [comment]
It is not an automated thing. We manually copied feeds from Versions.props into NuGet.config, like [this](https://github.com/dotnet/cli/commit/98df862f663c905862ec5535f1b0efcb7fcb9569). Based on what @JohnTortugo mentioned about wpf, no change was needed since NuGet.config had all the feeds already defined in Versions.props but these might not include feeds defined elsewhere or feeds which Arcade used to inject

**Comment by vatsan-madhavan** [comment]
So if we have all the right feeds in NuGet.config, then any guesses on why our builds are failing against these PR's?

**Comment by jcagme** [comment]
@tmat where would be a good place to add something like what we removed with https://github.com/dotnet/arcade/pull/3041/files#diff-f1b1f6d246bc1f9a81d8ea1c4498e3a5L108?

@vatsan-madhavan can you share the link to failed build so I can try to see what feeds are missing?

**Comment by vatsan-madhavan** [comment]
> * https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/2324?_a=files&path=%2Feng%2FVersions.props -
> * https://github.com/dotnet/wpf/pull/1399/files

These are the PR's that have failed. The corresponding PR build links - 

- https://dev.azure.com/dnceng/internal/_build%2Fresults?buildId=280834&_a=summary
- https://dev.azure.com/dnceng/public/_build/results?buildId=280746

**Comment by jcagme** [comment]
Oh, that is a different issue tracked by https://github.com/dotnet/arcade/issues/3401. I've uploaded missing packages and things should work now. I've retried both of your builds.

**Comment by vatsan-madhavan** [comment]
> Oh, that is a different issue tracked by #3401. I've uploaded missing packages and things should work now. I've retried both of your builds.

Thanks - that seems to have fixed it!

**Comment by JohnTortugo** [comment]
Closing the issue now that all linked PRs are merged. Thanks JC for addressing @vatsan-madhavan comments.
