### ISSUE TITLE
Genericize init-[tool].sh

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#3405]
Currently, Unix native bootstrapping requires a different script for every dependency to bootstrap (e.g. `install-cmake.sh`, `install-jdk.sh`, etc.). We should change this and have a single `install-tool.sh` script which will take an arbitrary tool and version as an argument and bootstrap it. This will bring parity with how the Windows bootstrapping works.

cc/ @riarenas

**Comment by riarenas** [comment]
Dupe of https://github.com/dotnet/arcade/issues/2674 ?

**Comment by jonfortescue** [comment]
@riarenas boof

closing because it's a dupe :')
