### ISSUE TITLE
Empty/sample projects for onboarding

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#341]
Can we create (or maybe there already exists) a sample/empty project that can be copied around, for the following purposes
- Creating new arcade packages
- Onboarding a fresh repo

Right now it seems like we just have to go and copy another project and then modify.

/fyi @tmat @markwilkie

**Comment by tmat** [comment]
What's needed beyond `dotnet new classlib`? We shouldn't need any boiler plate.

**Comment by mmitche** [comment]
@tmat Does that add the project sdk reference? Are there any other properties (signing, version numbers?) that need to be added into the csproj?

**Comment by tmat** [comment]
> Does that add the project sdk reference? 

Not sure what you mean by "project sdk reference". 

> Are there any other properties (signing, version numbers?) that need to be added into the csproj?

Not for a simple package. Right now you'll need to add the path to the binaries to SignToolData.json, but we can hopefully avoid that in future.

**Comment by mmitche** [comment]
e.g. https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.GitSync/Microsoft.DotNet.GitSync.csproj#L1

**Comment by tmat** [comment]
Actually, I guess there are a few properties that you need to set to create a proper package: `<IsPackable>`, `<Description>` and `<PackageTags>`. These are standard nuget properties that do not have defaults in Arcade SDK as they are specific to the project.

**Comment by tmat** [comment]
> Does that add the project sdk reference?

Yes, the SDK reference in project header is added by `dotnet new classlib` (or .NET Core library template in VS File New).

**Comment by markwilkie** [comment]
@tmat, do you see the value with a sample project?

Regardless, we should provide crystal clear guidance for folks onboarding.

**Comment by rainersigwald** [comment]
There should be a doc for _repo_ onboarding. I think the idea is that individual projects shouldn't have to do anything because there is a repo `Directory.Build.props` that gets picked up automatically and pulls in the Arcade references. So the complexity is more for a new or newly onboarding repo.

**Comment by tmat** [comment]
@rainersigwald Agreed. I think this is a good start:
https://github.com/dotnet/roslyn-tools/blob/master/docs/RepoToolset.md

**Comment by markwilkie** [comment]
We've created an arcade sample repo for a "simple" onboarding example for a repo.   https://github.com/dotnet/arcade-minimalci-sample

@maririos, could you create an issue please to track the work to create a sample/tutorial for how to create a package that is part of arcade please?    

Once that's done, I think we can close this issue.

**Comment by maririos** [comment]
Created issue #370
