### ISSUE TITLE
Gather Asset Manifests still runs with YAML stages unless global _PublishUsingPipelines variable is true

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/arcade#3412]
The docs for stages mentions that you just need to set `enablePublishUsingPipelines: true` if you use the jobs.yml template and only use `_PublishUsingPipelines` if you don't: https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/YamlStagesPublishing.md#how-to-onboard-onto-yaml-based-publishing

However the Gather Asset Manifests task only checks for the `_PublishUsingPipelines` variable so if you don't have the variable set it will still run: https://github.com/dotnet/arcade/blob/316481e57ee5e6acbbf2401eb6778a1d3d48d25b/eng/common/templates/job/job.yml#L190

/cc @riarenas @jcagme

**Comment by riarenas** [comment]
Yep, You're right, the variable is needed in both cases, since the Gather asset manifrsts task happens outside of jobs.yml and doesn't get any parameters that refer to the publishing using pipelines. I'll update the guidance doc.

**Comment by JohnTortugo** [comment]
I'm taking a look as well

**Comment by JohnTortugo** [comment]
I think this line:

https://github.com/dotnet/arcade/blob/316481e57ee5e6acbbf2401eb6778a1d3d48d25b/eng/common/templates/job/job.yml#L190

should reference a parameter and not the state of a global variable. I'm running a test build for that: https://dnceng.visualstudio.com/internal/_build/results?buildId=281939&view=results

**Comment by riarenas** [comment]
Adding the parameter to the job template is probably the better fix for this. My only worry would be that we would require people to be in the very latest arcade sdk for the fix to be available once that fix is in, and the sdk has been very slow to flow lately due to breaks.
