### ISSUE TITLE
Add coherent download links for .NET Core 3.0 to dotnet/core repo

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#345]
@mmitche commented on [Tue Jul 03 2018](https://github.com/dotnet/core-eng/issues/3828)

In order for customers to get access to our builds more easily, we need coherent download sdk links in the dotnet/core repo at https://github.com/dotnet/core/blob/master/daily-builds.md.

The key to these links is that they must be coherent.  So the runtime and aspnet links must match what the sdk contains.  Basically, before Darc and the BAR make this a lot easier, we need to:

For very new CLI build (or whatever the aggregator repo is for the SDK, maybe core-sdk), in the maestro postbuild steps
1. Determine the msbuild properties at the built sha that note what the runtime/aspnetcore versions were.
2. Generate a stable link to those binaries in the dotnetcli storage account.

Then we can update the dotnet/core readme page to point to the latest stable coherent build.

/cc @Petermarcu @dagood @DamianEdwards @leecow 

---

@dagood commented on [Thu Jul 05 2018](https://github.com/dotnet/core-eng/issues/3828#issuecomment-402746148)

Since the title says .NET Core 3.0, why would we have to do it "before Darc and the BAR make this a lot easier"? Should this be split out for .NET Core 2.1 (and 2.2), or will Darc/BAR really not necessarily be available for 3.0?

---

@mmitche commented on [Mon Jul 09 2018](https://github.com/dotnet/core-eng/issues/3828#issuecomment-403558695)

@dagood Peter made this a priority.

---

@Petermarcu commented on [Mon Jul 09 2018](https://github.com/dotnet/core-eng/issues/3828#issuecomment-403570087)

I don't know what darc and bar are but the crux of it is that we are very close to having features and fixes in 3.0 that we want to advertise and get the community using daily 3.0 build for. What is the time line if we wait for the things you mentioned? 

---

@mmitche commented on [Mon Jul 09 2018](https://github.com/dotnet/core-eng/issues/3828#issuecomment-403570758)

Much longer, those are part of prodcon v2, which is still in the early-ish stages.  We should do this first if coherent download links are that important for 3.0 (vs. just linking the SDK).  But, it is throwaway work.

---

@Petermarcu commented on [Mon Jul 09 2018](https://github.com/dotnet/core-eng/issues/3828#issuecomment-403572556)

People need to be able to get an sdk and a matching runtime. Well also need to have both runtime and sdk dockers images that are coherent and match. 

---

@maririos commented on [Thu Jul 12 2018](https://github.com/dotnet/core-eng/issues/3828#issuecomment-404644244)

FYI @Chrisboh 

---

@mmitche commented on [Wed Jul 18 2018](https://github.com/dotnet/core-eng/issues/3828#issuecomment-405927493)

Depends on https://github.com/dotnet/arcade/issues/340.

---

@mmitche commented on [Wed Jul 18 2018](https://github.com/dotnet/core-eng/issues/3828#issuecomment-405929725)

@Petermarcu Committed updates to the main dotnet/core page https://github.com/dotnet/core/blob/master/daily-builds.md

Updates to the dotnet/core-sdk page with new info here: https://github.com/dotnet/core-sdk/pull/33

Working on the aka.ms updater, which is required to provide links to the isolated feeds

**Comment by maririos** [comment]
@mmitche could you please put this issue in it's correct Epic?

**Comment by dseefeld** [comment]
Removing from the 2.1.3 Servicing epic, since that epic is complete and will be closed.

**Comment by markwilkie** [comment]
Moving back to core-eng for triage as this is a product ask, which may have requirements on the infra, but is not an infra requirement in and of itself.

There's likely work that needs to be done before prodcon v2 is stood up and adopted, and that needs to be addressed.  As @Petermarcu noted, our customers need to be able to get the latest *coherent* 3.0 bits.

**Comment by markwilkie** [comment]
Issue moved to [dotnet/core-eng #4130](https://github.com/dotnet/core-eng/issues/4130) via [**ZenHub**](https://www.zenhub.com/)
