### ISSUE TITLE
RestoreSources removal can break repos which didn't already have explicit nuget.org entries in their nuget.config

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#3475]
I believe this PR : https://github.com/dotnet/arcade/pull/3041 when merged made it so that the resulting Arcade SDK will not propagate if the team had an unintentional, implicit dependency on nuget.org but did not specify it.

I'm marking this FR so we can look into a quick fix for others who may be encountering the problem.

**Comment by jcagme** [comment]
Yes, this is exactly the case. Probably @tmat has suggestions on whether we can add something back into arcade or the instructions are more for the owner to add all the required feeds to NuGet.config

**Comment by tmat** [comment]
Repos will need to have nuget.org in their nuget.config.

**Comment by MattGal** [comment]
If this behavior can't be improved, we should at least make sure we have docs and stuff in place for it then so folks like @dougbu know what's up (perhaps a simple warning?)

**Comment by jcagme** [comment]
Agree. We have [this](https://github.com/dotnet/arcade/blob/master/Documentation/RestoreSourcesUpdateStatus.md) doc but it was until after we completed step 1 that we realized that there were some feeds that Arcade was inserting that might no already be in NuGet.config nor Versions.props. I'll update the doc and notify the working group.

**Comment by jcagme** [comment]
https://github.com/dotnet/arcade/pull/3477

**Comment by MattGal** [comment]
Docs look fine and per Doug's email they've already added to their nuget config, so closing this one out.
