### ISSUE TITLE
PushMetadataToBuildAssetRegistry task logic for calculating whether a build is stable is incorrect

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3476]
We use this function to determine if a build is stable:

https://github.com/dotnet/arcade-services/blob/3046e51818a10096baba80a1fba02bef5fb664d2/src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs#L114

The regex only allows single digits in each segment of the version, and we probably shouldn't be relying on the version of the assets anyways.

@jcagme, @JohnTortugo

**Comment by JohnTortugo** [comment]
In talk with @riarenas we believe that using `DotNetFinalVersionKind` is a better approach to detect stable/non-stable builds. Some documentation for that variable is available here: https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md#build-kind
