### ISSUE TITLE
[Release Features] Inform missing channels during publish build assets to BAR

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3503]
We rely on builds being assigned to a channel for:

* Dependency update
* Asynchronous Publishing via release pipelines
* The new YAML stages based publishing

If a build is not going to be assigned a default channel, none of these will end up happening, and we've had many questions lately asking about why a build finishing didn't have the expected effects.

We should inform the user when we detect that a build is not going to be assigned to any channel by default, so that there's no need to contact us to find out what happened, and to help diagnosability.

Some things we could do:

* Fail the build if the repo that produces the build has no default channels associated to it at all. 
* If there **are** default channels for other branches, but not for the one being built, make the 'Publish to Build Asset registry` step make the build only partially successful so that it's obvious that there might be subsequent steps that won't work as they should.

CC @chcosta, @JohnTortugo, @mmitche

**Comment by chcosta** [comment]
Thanks for filing this issue @riarenas

**Comment by riarenas** [comment]
@mmitche Not sure if it's always an error state that a repo has no default channels enabled at all, so maybe failing the build is a little extreme, but marking the step as yellow should be obvious that something is not quite right and needs attention.

**Comment by mmitche** [comment]
It's definitely not an error state. I'm not even sure it's a warning state.  There are plenty of cases today where builds are only assigned on-demand to specific channels (Nuget is one of these).  Default channels are only a shortcut that says "every build out of a branch is for this purpose".  Furthermore, there are plenty of cases where we are pushing additional branches to internal to run an official build, where those bits are never intended to flow anywhere else.

**Comment by riarenas** [comment]
Any thoughts on a good way to help with this scenario?

We could simply warn during the step that this build has no default channel, so it won't be running any publishing, but most people won't bother reading the logs of a successful build step.

With the YAML stages publishing, we 100% rely on having a default channel to understand when/where we should publish packages. A dev that merges a PR expects that publishing will happen if the official CI build is green, but that's not necessarily the case right now unless the BAR configuration is also correct, and they have no way of telling that there's going to be something blocking their publishing.

**Comment by mmitche** [comment]
I thought we had another way of assigning a build to a channel after-the-fact?

**Comment by JohnTortugo** [comment]
> I thought we had another way of assigning a build to a channel after-the-fact?

We don't have that feature yet.

**Comment by riarenas** [comment]
We do have a darc command to do it, and that triggers the release pipeline just fine if the channel has a release pipeline is associated to the channel. Also, when Azure DevOps finishes their stages implementation, we will be able to trigger stages on demand, but right now, this is a bit of a black hole for most devs.

The way we are handling this today is mostly: 
* A report comes in that some publishing step / subscription didn't trigger somewhere,
* It just ends up being that the build never got assigned to a channel.

We could just live with this experience for now, but just today we've had three customers asking why  something they expected to happen after their build finished didn't happen, and in all three cases it was due to the build not being in any channel.

**Comment by mmitche** [comment]
> We don't have that feature yet. The plan was to be able to "activate" one of the non-default channels in the build UI, but that's pending on ADO having that feature. The other option was to create a RM pipeline that receive ChannelID & BuildID and perform the publishing.

How far away are we from this? I don't think Nuget.Client can onboard otherwise (they produce multiple builds in sequence, only one of which is intended for .NET Core).  I also occasionally still do this.  For instance, today I noticed that Blazor had updated its default channels after the preview8 merge was done, so I needed to assign the last build to the release channel.

**Comment by riarenas** [comment]
Although the user experience is not ideal, there's no immediate reason to remove the ReleasePipelineRunner pipelines for situations such as these? All the builds will now have 'PublishUsingPipelines' set to true, so all it takes is a darc assign-build-to-channel to get the release to run after the fact.

We could help out Nuget.Client by providing something they can call at the end of the build that is intended for .NET core that would assign the build that was just published to BAR to a whatever channel.

**Comment by mmitche** [comment]
> We could help out Nuget.Client by providing something they can call at the end of the build that is intended for .NET core that would assign the build that was just published to BAR to a whatever channel.

I think they are using add-build-to-channel today

**Comment by riarenas** [comment]
The initial idea of this issue wasn't really feasible.

We now log which default channels were found and will be activated during the BAR publishing job, we provide documentation that explains how the default channel based publishing works, and we're working on adding a new pipeline that can be triggered manually if there's need for a build to be added to a channel after the fact. 

We can't fail or warn the build if no default channels were found, as this is a valid scenario. Closing.

**Comment by markwilkie** [comment]
This conversation is going again.  @tmat - I think you had another suggestion in teams - would you mind sharing here?

**Comment by tmat** [comment]
Yeah, when `DotNetPublishUsingPipelines` is `true` fail the build of a branch if it there is no any channel to publish to. A branch that's not intended to publish anywhere would be configured to publish to a special "nil" channel.

**Comment by tmat** [comment]
Also, the error message should ideally include `darc` command line that adds a default channel for the branch and the repo being built, so that it's easy to see what to do.

**Comment by mmitche** [comment]
> Yeah, when `DotNetPublishUsingPipelines` is `true` fail the build of a branch if it there is no channel to publish to. A branch that's not intended to publish anywhere would be configured to publish to a special "nil" channel.

This is not scalable. Branches pop into and out of existence all of the time that we run official builds against. Default channels do not need to be configured against a branch because builds can be assigned to (and do publishing) after the build is complete.

**Comment by JohnTortugo** [comment]
I talked with @mmitche and he agrees that we should emit a Warning message when the build doesn't have any default channel. 

Given the pros:
- We'll have a way to alert the user that the build won't publish
- We don't break repos that don't publish in every build

and cons:
- warning will show up when the user is running a build but doesn't intend to publish anything.

I think this is a good compromise. Does anyone disagree?
