### ISSUE TITLE
[Maestro++] Dependency updates to dotnet/source-build are not triggering

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3518]
We are not opening dependency updates to https://github.com/dotnet/source-build due to errors when building the dependency graph.

**Comment by crummel** [comment]
I changed XDT and Xliff to be pinned to get it to work locally, but that appears to have broken the uberclone.  I'm looking into the issue now.

**Comment by crummel** [comment]
Ah, looks like it's just that `PinnedDependency` is the old workaround way of pinning and the right way is `Pinned="true"`.

**Comment by riarenas** [comment]
Sorry, I went to lunch and then had a meeting at 1.

I did find the same conclusions you did after managing some exceptions a bit better in my local code. The Xliff and XDT dependencies are failing due to the DependentParentCoherency attribute. Are they configured correctly?

``` 
Unable to update Microsoft.Web.Xdt to have coherency with parent Microsoft.NET.Sdk.Web
Unable to update XliffTasks to have coherency with parent Microsoft.DotNet.Cli.Runtime
``` 
aspnet/xdt does not have a dependency on Microsoft.Net.Sdk.Web and dotnet/xliff-tasks does not have a dependency on Microsoft.DotNet.Cli.Runtime.

Maybe instead of pinning, the coherency attribute should be removed from those two?

**Comment by crummel** [comment]
The XDT -> websdk edge is correct according to what Nate/@JunTaoLuo have told me - this is probably a subscription we should add.  We have https://github.com/dotnet/arcade/issues/3099 open for feeding Xliff into Arcade, which is probably what that coherency parent should change to once that's in place.  But yeah, I had assumed these would be ignored if they didn't exist yet, I will remove at least the Xliff one for now and see what ASP.NET wants to do about the XDT -> websdk subscription.

**Comment by crummel** [comment]
Huh, actually it looks like the XDT -> websdk edge exists in both [Version.Details.xml](https://github.com/aspnet/websdk/blob/e8cb5ed1357d232251f26cf79413838ea62ba501/eng/Version.Details.xml#L20) and Maestro (subscriptions 46466a62-ed9a-427b-18ae-08d7114cdca3 and 6123bc98-eea8-412d-4dda-08d6bc676830).  Is there something else going on there?

**Comment by riarenas** [comment]
The XDT version in websdk is pinned. I wonder if that's what's causing the issue?

**Comment by crummel** [comment]
After removing the bogus Xliff edge and pinned XDT in source-build, a manual `trigger-subscriptions` worked.  I would still call the upstream pinning issue a bug though, so I think it makes sense to leave this open, unless you disagree?

**Comment by riarenas** [comment]
Agreed. I haven't had much bandwidth to look at this, but I expect to have some cycles this week to get to the underlying cause.

**Comment by riarenas** [comment]
The immediate issue was fixed and source-build is receiving updates. We made some changes to the area since the latest update and this has become too stale to actually get a root cause for this one instance of issues with pinning and CPD.

Closing this, feel free to reopen if you this reocurs with any other dependency.
