### ISSUE TITLE
Configuration system leaks Configuration property (and perhaps other global properties) when inspecting BuildConfigurations

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#3533]
Problem here: https://github.com/dotnet/arcade/blob/aa4285be7fab64e2b6e62e4d5688ea50931c407c/src/Microsoft.DotNet.Build.Tasks.Configuration/src/build/Microsoft.DotNet.Build.Tasks.Configuration.targets#L111

And likely in other places where we build cross-project in the configuration system.

We should avoid leaking any global properties of the parent project here.  Likely this means undefining Configuration but we should check others to determine what might need to be undefined.

This may be irrelevant if we can switch to TargetFrameworks, but some version of this will likely exist to implement filtering.

**Comment by ViktorHofer** [comment]
I believe this isn't happening anymore with the new configuration system? Closing.
