### ISSUE TITLE
[Versioning] Include `.final` to pre-release package versions, or not?

### ISSUE THREAD

**Issue by tmat** [dotnet/arcade#354]
The current spec says:

- **Final Prerelease** - Versions should include **MAJOR**, **MINOR**, **PATCH**, and **PRERELEASE** tag but no **SHORTDATE**, **REVISION**, or **SHORTSHA**.  **PRERELEASE** should be suffixed with `'.final'`.  This avoids a common issue in nuget package resolution where `2.1.0-rc1` < `2.1.0-rc1.12345`. The intention is that the final build is resolved over the date-versioned build.

The implementation does not include ".final" currently.

It doesn't seem like it's really necessary as we publish these packages to different feeds (MyGet/AzureBlob vs NuGet).

**Comment by maririos** [comment]
@mmitche

**Comment by maririos** [comment]
Done with PR https://github.com/dotnet/arcade/pull/438/files
