### ISSUE TITLE
Publishing target overwrites files from previous legs

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/arcade#3554]
The issue is in the `PublishToAzureDevOpsArtifacts` target. This target is called from multiple legs and each leg will have identically named artifacts. For example, each leg in the coreclr repo will have a `coreclr.pdb` and when a leg inserts this artifact into the same folder it will overwrite any previous artifact - see below.

https://github.com/dotnet/arcade/blob/26be9cf106bfc1d6d49e47fa7e002898d945baae/src/Microsoft.DotNet.Arcade.Sdk/tools/Publish.proj#L213-L224

Ideally the solution would be to put them in a sub-directory structure in the artifact. Perhaps the solution is to use a similar pattern as the `AssetManifestFileName` for the folder name?

**Comment by riarenas** [comment]
@JohnTortugo This feels like something we thought about and hardened against, or is this still needed? Moving to NET5 epic in the meantime.

**Comment by riarenas** [comment]
@JohnTortugo can we check if this is still needed? maybe we should just outright fail if we try to overwrite?

**Comment by JohnTortugo** [comment]
@AaronRobinsonMSFT - The latest version of Arcade SDK uploads the PDB folder recursively maintaining the directory hierarchy and thus it prevents this problem. I checked `dotnet/runtime` but looks like they aren't publishing any PDBs yet.

I'll close the issue for now. Let me know or re-open the issue if you find this problem again.
