### ISSUE TITLE
PushToAzureDevopsArtifacts task does not push anything to artifacts if publishFlatContainer property is set to true.

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3559]
Since the actual publishing of the artifacts and the publish operation during the build are decoupled, we need a way to tell the post-build scripts that the assets in a build manifest should be published to a flatcontainer. This issue is to modify Tasks.Feed tasks to storage that information in the build manifest.

**Comment by riarenas** [comment]
I think this is not really a problem. The only problem I'm aware of is that the PushToAzureDevopsArtifacts didn't do anything but write to the manifest when publishFlatContainer was set to true (and that's what the linked PR is solving)

**Comment by riarenas** [comment]
Changing title to reflect the actual problem.

**Comment by riarenas** [comment]
Fix has been merged. Need to validate and then update the default version of the package used by the SDK.

**Comment by riarenas** [comment]
Waiting for https://dev.azure.com/dnceng/internal/_build/results?buildId=299480 to go through publishing and finish validation before I can keep testing the fix.
