### ISSUE TITLE
Helix JobSender has implicit dependencies on running in Azure Devops build

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#3580]
Related to https://github.com/dotnet/arcade/issues/3579, filed separately as it's not FR and requires some thought about how to approach fixing it.

As of the current version of the Helix JobSender package, if the user does not specify "Source" properly, they end up getting a bunch of cryptic error messages about undefined environment variables.

Ideally these values should be either user-supply-able, or have defaults that work for "console app on person's machine".

**Comment by markwilkie** [comment]
Am making the assumption that given the successful resolution of the linked bug, this one is ok too.  If that's incorrect, and this still should be fixed, feel free to reopen.

**Comment by MattGal** [comment]
Ooops yes that PR was the fix, just never closed this issue.
