### ISSUE TITLE
dotnet/iot getting simultaneous arcade PRs per day

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#3584]
The dotnet/iot repo is getting multiple updates of arcade per day (parallel PRs)

https://github.com/dotnet/iot/pull/660
https://github.com/dotnet/iot/pull/659

**Comment by joperezr** [comment]
This has so far happened two days in a row. Yesterday's two PRs were:
https://github.com/dotnet/iot/pull/652
https://github.com/dotnet/iot/pull/653

**Comment by mmitche** [comment]
This is almost certainly because of #3595.  For repos getting multiple updates, we are retrying requests while the rate limit has been exceeded, which runs over the timeout on the update operation.  We lose track of the PR we were opening, then open another.

**Comment by joperezr** [comment]
Happend once more time: 
https://github.com/dotnet/iot/pull/665
https://github.com/dotnet/iot/pull/662

@riarenas 3 times in one week makes me feel that this is actually something we should probably look into. Would you be able to help us investigate?

**Comment by riarenas** [comment]
@mmitche just sent out a PR that should help with #3595, which we believe is the main cause of the duped PRs.

**Comment by mmitche** [comment]
Should be mostly unblocked by https://github.com/dotnet/arcade-services/pull/582

**Comment by joperezr** [comment]
Haven't seen this happen again. Feel free to close this is you want and I can reopen if I ever see it happening again.
