### ISSUE TITLE
[Release features] Cleanup Build properties deprecated by the move to stages-based publishing

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3597]
* /p:DotNetPublishToBlobFeedUrl
* /p:DotNetPublishToBlobFeed
* /p:DotNetPublishUsingPipelines
* /p:DotnetPublishBlobFeedKey
* UsingToolSymbolUploader - See discussion [starting here](https://github.com/dotnet/arcade/pull/4284#issuecomment-550134655).

Are all still required properties for the stages based publishing to work correctly. We should see if there are some parameters that we can pass by default or clean up usage of these variables now that everyone needs to onboard to this paradigm, or document the fact that they still needed.

@safern thanks for testing this out.
CC/ @JohnTortugo

**Comment by safern** [comment]
Also `DotnetPublishBlobFeedKey` is still required.

**Comment by riarenas** [comment]
As part of this work, we also need to document which properties used by the previous publishing implementations are now obsolete, and can be removed by repos.

**Comment by ViktorHofer** [comment]
@riarenas if I don't want to publish to the blob storage feed but just to the AzDO Artifacts feeds which is determined by the BAR channel, how would I do that today? Do I still need to set all these properties? Asking because my build is currently failing: https://dnceng.visualstudio.com/internal/_build/results?buildId=450406&view=logs

cc @mmitche

**Comment by mmitche** [comment]
> @riarenas if I don't want to publish to the blob storage feed but just to the AzDO Artifacts feeds which is determined by the BAR channel, how would I do that today? Do I still need to set all these properties? Asking because my build is currently failing when I don't pass all these in: https://dnceng.visualstudio.com/internal/_build/results?buildId=450406&view=logs
> 
> cc @mmitche

I don't think there is a way to do this today. There isn't a downside to publishing to the blob feed (aside from slightly increased build times). We are aiming to remove that publish for all repos en-masse by modifying arcade eventually.

**Comment by ViktorHofer** [comment]
Thanks, I'll add the boilerplate for now.

**Comment by JohnTortugo** [comment]
Some repos are still using the old publishing infrastructure and removing the properties mentioned in this issue will most certainly break them. The work on this issue will be postponed by four weeks to give the repo owners some time to catch up with the publishing changes.

For the record, these are the repos:

https://github.com/aspnet/xdt
https://github.com/mono/linker
https://github.com/dotnet/source-build-reference-packages
https://github.com/dotnet/command-line-api
https://github.com/microsoft/vstest

**Comment by riarenas** [comment]
Keeping this for .NET 5, this is helpful to make sure everyone is on the new publishing infra.

**Comment by JohnTortugo** [comment]
Hey @safern @ViktorHofer - From now on you can remove these properties. The Arcade SDK doesn't require them anymore if you are setting `PublishingUsingPipelines = true`.

Please see updated documentation here: https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Publishing.md#publishingusingpipelines--deprecated-properties

And PR that removed these properties from Arcade's YAML build-definition: https://github.com/dotnet/arcade/pull/4972
