### ISSUE TITLE
Publishing documentation

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/arcade#3599]
I believe the new task for publishing is `PushToAzureDevOpsArtifacts`? The documentation for [Publishing](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Publishing.md#the-pushtoblobfeed-task) appears to be out of date or missing some new context.

**Comment by markwilkie** [comment]
Thanks @AaronRobinsonMSFT  - @riarenas or @JohnTortugo , PTAL when you get a chance.

**Comment by riarenas** [comment]
Looking at that document it has gone quite stale as it doesn't even include the async release pipelines. I can start taking a look, but will most likely need input from @JohnTortugo after he comes back.

**Comment by markwilkie** [comment]
ACK

**Comment by garath** [comment]
FYI, Async publishing is described in [a separate document](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/AsyncPublishing_HowToUse.md). Does it just need to be more discoverable (as in, linked from the index)?

**Comment by riarenas** [comment]
Both that one, and the stages based publishing should be part of the document. The document also only describes a single task of the many that arcade supports and uses during its publishing.

At this point, that document is just pretty much completely stale.

**Comment by JohnTortugo** [comment]
@riarenas since I'm FR this week and the next... and then OOF for the next 4 weeks I think it's better if I move this issue to the backlog. Feel free to pick it up if you have cycles.
