### ISSUE TITLE
SourceLink validation failures for CoreFX

### ISSUE THREAD

**Issue by safern** [dotnet/arcade#3603]
While switching to use pipelines publishing in corefx, I encountered 2 failures in SourceLink before I decided to disable it in order to make progress.

```
Could not load file or assembly 'System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The paging file is too small for this operation to complete. (Exception from HRESULT: 0x800705AF)
System.Management.Automation.RemoteException: Could not load file or assembly 'System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The paging file is too small for this operation to complete. (Exception from HRESULT: 0x800705AF)
at <ScriptBlock>, D:\a\1\s\eng\common\tools.ps1: line 575
at <ScriptBlock>, <No file>: line 6
```
https://dev.azure.com/dnceng/internal/_build/results?buildId=297506&view=logs&jobId=0a6c679f-72be-5867-422e-acb741a068a3&taskId=d2ccdc12-7474-5a79-d9be-9757fb834354&lineStart=48&lineEnd=51&colStart=1&colEnd=36

The second one was:
```
Unable to load DLL 'iphlpapi.dll': Exception from HRESULT: 0x800705AF
System.Management.Automation.RemoteException: Unable to load DLL 'iphlpapi.dll': Exception from HRESULT: 0x800705AF
at <ScriptBlock>, <No file>: line 18
```
https://dev.azure.com/dnceng/internal/_build/results?buildId=298897&view=logs&jobId=0a6c679f-72be-5867-422e-acb741a068a3&taskId=d2ccdc12-7474-5a79-d9be-9757fb834354&lineStart=60&lineEnd=62&colStart=1&colEnd=37

I tried to repro locally by downloading the symbol packages from the build artifacts and ran the exact same version of the sourcelink validation ps1 script and didn't get a repro, it was successful the 3 times I tried to run it.

@riarenas started taking a look to see if he found anything earlier today.

cc: @tmat @JohnTortugo @mmitche

**Comment by ericstj** [comment]
It could be that this validation process is leaking memory and/or consuming too much disk space.  The fact that this is hitting multiple times on different machines indicates it's a likely a deterministic leak.  The machines are VMs which have limited memory and diskspace and we've hit these limits before.   I bet the validation process is creating a bunch of large objects and not freeing them while at the same time filling up the disk which prevents the OS from automatically growing the pagefile.

**Comment by markwilkie** [comment]
cc/ @tmat (he's OOF starting 8/9)

**Comment by safern** [comment]
This is definitely because we're eating the memory in the Hosted Agents which is limited: 

https://dev.azure.com/dnceng/internal/_build/results?buildId=308107&view=logs&jobId=306272fe-0d8c-58af-8d13-1dae09fcca5c&taskId=3ba16eee-15f0-509e-c67d-8f87feade086&lineStart=90&lineEnd=93&colStart=1&colEnd=37

That one failed with an `OutOfMemoryException`. @JohnTortugo whould you mind taking a look?

It seems like there are improvements that can be done in the validation script, like cleaning up every extract directory once the SourceLink validation is done, I see we don't do any cleanup.

**Comment by JohnTortugo** [comment]
I'll see what we can do to reduce the memory usage. The script span multiple parallel jobs and that's probably what's causing the OOM exception.

> It seems like there are improvements that can be done in the validation script, like cleaning up every extract directory once the SourceLink validation is done, I see we don't do any cleanup.

I'll include that suggestion. This usually not needed, though - because the build directory is cleaned up before/after every build.

**Comment by safern** [comment]
> I'll include that suggestion. This usually not needed, though - because the build directory is cleaned up before/after every build.

I mean cleaning up on each iteration/parallel job, so I see that you Extract the symbols.nupkg, then do the sourcelink validation and then in the `finally` statement, you only dispose the zip entry, I think you could also delete the extract directory, that will help the memory bloat during the validation execution, helping avoid this memory leaks that are causing the build agent to run out of memory.

**Comment by ericstj** [comment]
@JohnTortugo can you please provide an update here?  We'd like to enable validation in 3.0 and realistically the cutoff for that is now, given preview9 lockdown and the increased bar there-after.

**Comment by JohnTortugo** [comment]
I'll talk to @markwilkie to work out the priority on this. I think it's not much work. I'll keep the issue updated.

**Comment by ericstj** [comment]
Cleaning the disk is important, but also trying to get powershell to avoid the memory growth is also important.  Hacky fix for that would be a process boundary, perhaps there something with more finesse that would avoid hacks.  I'm not sure how powershell roots objects & interacts with GC otherwise I'd provide some better suggestions: like buffer pooling.

**Comment by JohnTortugo** [comment]
I did some quick profiling and confirmed that we're creating a bunch of Jobs -- 100's given for CoreFx number of assets. That caused the script to use about 2GB of memory:

<img width="989" alt="profile_before" src="https://user-images.githubusercontent.com/2249648/63307549-9e220c00-c2a3-11e9-9631-e057545eccc9.png">

I implemented something to limit the number of jobs that will be spawned to run in parallel and the memory footprint decreased to a factor of that:

<img width="631" alt="profile_after" src="https://user-images.githubusercontent.com/2249648/63307592-c7db3300-c2a3-11e9-8c5f-c51568347e18.png">
