### ISSUE TITLE
Enable publish to multiple locations for builds to .NET Core 5 Dev channel

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3605]
Publishing to this channel should automatically publish to:

Work for this issue:
* Extension point to enable publish to multiple feeds during the publishing stages.
* Set up the ' .NET core 5 dev' stage to publish to the right places:
  * dotnet-core feed
  * TBD

**Comment by riarenas** [comment]
@chcosta what was the idea to use an azure devops feed to help with this?

**Comment by chcosta** [comment]
[Upstream sources](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-DEVOPS) for major releases.  ie, a "dotnet5" feed, a "dotnet6" feed as upstream sources of a single "dotnet" feed which has all upstream sources and oob packages

**Comment by mmitche** [comment]
@riarenas is working on this.

**Comment by riarenas** [comment]
@mmitche the current version of Arcade already uses my changes from #3693 so it's now possible to specify multiple FeedConfigs per channel. Should be able to add more feeds to the netcore5 and netcore3 dev channels now.
