### ISSUE TITLE
[Darc/Maestro++] Default channels for the azure devops version of a repo don't get triggered if the same branch exists in github

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3628]
Been seeing this a few times for repos onboarding to the YAML publishing. If a branch is present in both GitHub and AzDO, only the channels that reference the GitHub repo will work.

If the branch is only present in Azure DevOps, the channel triggers successfully.

**Comment by mmitche** [comment]
@riarenas What is your default channel config when you see this behavior?

**Comment by riarenas** [comment]
I'll post a real config and situation where this happens when I see it again, but it's usually

https://github.com/dotnet/repo @ refs/heads/testBranch -> .Net Tools - Validation
https://dev.azure.com/dnceng/internal/_git/dotnet-repo @ refs/heads/testBranch -> .Net Tools -Validation

The default channel doesn't get assigned for builds out of the internal repo that have commits that are not yet present in the github version of the branch.

**Comment by mmitche** [comment]
The behavior should be the following:
1. If commit is present in public repo, then set the repo url to be the github repo,
2. Assign channels based on default config based on the final url.

**Comment by riarenas** [comment]
This MIGHT be fixed thanks to https://github.com/dotnet/arcade-services/pull/827 since we now look at  both the azdo and github repos separately.

**Comment by JohnTortugo** [comment]
Yeap. Got some logs showing that all default channels are getting fetched correctly now.

```
  Found the following default channels:
      https://github.com/dotnet/arcade@BuildOnINT => (130) Cesar Channels' 9
      https://dev.azure.com/dnceng/internal/_git/dotnet-arcade@BuildOnINT => (135) Validate Pipelines Publishing
  Determined build will be added to the following channels: [130][135]
```
