### ISSUE TITLE
Execution of sdk-task.ps1 doesn't include eng/Versions.props

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/arcade#3635]
Execution of the following doesn't appear to include `./eng/Versions.props`.

`.\eng\common\sdk-task.ps1 -task SigningValidation -restore -msbuildEngine dotnet /p:Configuration=Release /p:PackageBasePath='...\PackageArtifacts' /p:SignCheckExclusionsFile='...\eng\SignCheckExclusionsFile.txt'`

This was discovered when trying to override the default `MicrosoftDotNetSignCheckVersion` property value defined in `.../SdkTasks/Versions.props` with the repo's `./eng/Versions.props`.

https://github.com/dotnet/arcade/blob/e08510ec70a18245a72dd019c72f5cec6326daff/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/Versions.props#L12

**Comment by tmat** [comment]
That is expected. We don't want the sdk tasks to depend on the versions specified in the repo.

**Comment by tmat** [comment]
The sdk tasks use this versions file: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/Versions.props

**Comment by AaronRobinsonMSFT** [comment]
@tmat Thanks for replying. I get that `.../SdkTasks/Versions.props` is the customization mechanism, but I don't see how that is helpful from a consumer of Arcade's stand point. The issue is that there is no way for a consumer to provide the `MicrosoftDotNetSignCheckVersion` property via the AzDO yml files. See https://github.com/dotnet/arcade/pull/3634 for an example where being able to override the default from the repo can avoid an expensive update.

Would the suggestion here be to expose a property in the yml file that can be overridden?

https://github.com/dotnet/arcade/blob/f04f5d246059020bff83916bae03c859cc0150fe/eng/common/templates/post-build/post-build.yml#L52-L56

/cc @riarenas

**Comment by tmat** [comment]
You could pass `/p:MicrosoftDotNetSignCheckVersion=X.Y.Z` to the sdk-tasks.ps1 as a workaround until you can update to newer Arcade SDK. 

We want the sdk tasks to be runable on machines that do not clone the repo. They will only have the Arcade SDK package and nothing else.

**Comment by AaronRobinsonMSFT** [comment]
>You could pass /p:MicrosoftDotNetSignCheckVersion=X.Y.Z to the sdk-tasks.ps1 as a workaround until you can update to newer Arcade SDK.

We don't control the `post-build.yml` script, that too is owned by Arcade.

>We want the sdk tasks to be runable on machines that do not clone the repo. They will only have the Arcade SDK package and nothing else.

That is fine and I agree with that approach. I am not asking for a change that would require a repo's `./env/Versions.props`. What I am requesting is that if a repo's `./eng/Versions.props` exist it permits overriding version properties. The property in question already checks if it is previously set.

**Comment by tmat** [comment]
> What I am requesting is that if a repo's `./eng/Versions.props` exist it permits overriding version properties

But that wouldn't help you in the scenario above, because we intent to run `post-build.yml` on machines that do not have the repo checked out. I don't think we should add conditional behavior that makes it behave differently when repo is checked out and when it's not. Sdk tasks are intended to be completely independent of the repo. I'd like to keep it that way.

**Comment by AaronRobinsonMSFT** [comment]
> I'd like to keep it that way.

Okay. Thanks for the details.
