### ISSUE TITLE
[Post-Build] Publishing failing if no _DotnetArtifactsCategory variable is present

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3661]
This variable is supposed to be there to enable publishing to different default feeds than dotnet-core, but the YAML templates require the variable to exist or there will be failures.

see https://github.com/dotnet/arcade/blob/bce492f663707d2c476784d950735bcaa85b4025/eng/common/templates/post-build/channels/netcore-dev-5.yml for instance.

We should default the category to .NETCore, which is what most repos would specify anyways, and only require the variable if overwriting the default category.

CC @JohnTortugo @AaronRobinsonMSFT

**Comment by mmitche** [comment]
@JohnTortugo Should we remove this when we remove the release pipeline runner? I don't see a strong reason to allow repos to override this any longer., so we could just remove it.

**Comment by JohnTortugo** [comment]
This variable is also used to [let builds override the target feed](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/SetupTargetFeeds.proj#L111) when publishing to some public channels. 

I think once we remove the pipeline runner we can 1) deprecate this variable and 2) if we decide to keep enabling feeds overrides, come with a better variable name or mechanism for that.

**Comment by mmitche** [comment]
I don't think we need any of the feed overrides any longer.  I intend to remove the publish to dotnet-core for packages in the near-ish future anyway.

**Comment by riarenas** [comment]
Moving to the "only use azdo feeds" epic.
