### ISSUE TITLE
Fix stages-based symbol publishing treating non-issues as errors

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#3667]
https://dev.azure.com/dnceng/internal/_build/results?buildId=306392&view=logs&s=a21ada51-e004-53d2-3ec7-8286e425df0d&j=ba74bb7f-eac9-54e1-9a19-7176689830db

```
##[error].packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19411.1\tools\SdkTasks\PublishToSymbolServers.proj(57,5): error : File NOT found libsos.so CLR: libsos.so/elf-buildid-coreclr-8008117955784ef10817aee344881f2e21320967/libsos.so - libsos.so
```

This is a warning being treated as an error. In the spirit of keeping builds warning-free, the symbol publish tool could be updated.

A workaround is to mess with `eng/common` in the repo to turn off treating warnings as errors. This will be overwritten by Maestro++ auto-PRs, so can't be used for ongoing builds.

Edit: Once https://github.com/dotnet/arcade/issues/3666 is implemented, there will be a stable workaround.

**Comment by riarenas** [comment]
Would having https://github.com/dotnet/arcade/issues/3666 and being able to pass the property to not treat warning as errors sufficient for what core-setup needs?

**Comment by dagood** [comment]
Ah, yep, didn't catch that issue. Thanks.

**Comment by riarenas** [comment]
Great! just wondering if there was anything additional that would be needed

**Comment by JohnTortugo** [comment]
Closing in favor of #3666 and I'll talk with @mikem8361 to improve symbol publishing to accept new parameters to suppress warnings - or at least not fail the build.
