### ISSUE TITLE
OSX signing job should support other internal storage

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#3673]
The temporary osx signing job is publishing to public locations no matter what.  If the build was internal (manifest knows), the outputs should go to an internal location.

**Comment by mmitche** [comment]
@JohnTortugo @markwilkie Part of servicing readiness

**Comment by markwilkie** [comment]
@JohnTortugo - is this sorted with the latest changes with private feeds?

**Comment by mmitche** [comment]
@markwilkie I don't think so.

**Comment by JohnTortugo** [comment]
@markwilkie it's not. The OSX packages signing build definition and the Linux package signing build definition directly use tasks in the Tasks.Feed package.

@mmitche @leecow can we just change the build-defs to publish to a private feed?

**Comment by leecow** [comment]
I thought dotnet-private was private? If not, then making so is fine with me.

**Comment by JohnTortugo** [comment]
I thought the same..

**Comment by mmitche** [comment]
It's these lines:

https://dev.azure.com/dnceng/internal/_git/OSX-Files-Signing?path=%2Fsigning.yml&version=GBmaster&line=83&lineStyle=plain&lineEnd=100&lineStartColumn=1&lineEndColumn=1

**Comment by JohnTortugo** [comment]
Thanks for the pointer @mmitche . I changed the container permission to `No Public Access`:

<img width="389" alt="NoPub" src="https://user-images.githubusercontent.com/2249648/64371098-9917c900-cfd4-11e9-9a80-338a5097138d.png">

Is that sufficient or should I change the code to upload to the MSRC accounts?

**Comment by mmitche** [comment]
What accesses dotnet-private later? Will it still be able to access it?

**Comment by JohnTortugo** [comment]
AFAIU only @leecow access it manually.

**Comment by leecow** [comment]
Just me at the moment. I hope to be replaced by code in the near future ;-)
