### ISSUE TITLE
Add release pipeline for internal servicing channel

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3686]
We need to add a release pipeline that publishes to the internal private feeds when a build is assigned to the internal release channel after the fact.

* [ ] Create release pipeline
* [ ] Associate it with internal servicing channel

**Comment by markwilkie** [comment]
@JohnTortugo - I presume this is completed now?

**Comment by JohnTortugo** [comment]
@markwilkie this is not complete. The pipeline that @riarenas mentions is an RM pipeline (not the YAML thing that we're working). This new pipeline will be used when people want to promote a build to a channel sometime after the build has finished execution.

/cc @riarenas @mmitche will we need this for servicing? Like, immediately?

**Comment by mmitche** [comment]
I think we can get away with not having this for internal servicing.

**Comment by riarenas** [comment]
@mmitche should this be closed then or should we look into this.

**Comment by mmitche** [comment]
I don't think we need to do this.
