### ISSUE TITLE
Let users override the target pools for post-build jobs

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3700]
Let users override the target pools for post-build jobs but use the hosted ones by default. It might happen that for some reason (i.e., not sufficient disk space) a build might need to run on one of our build pools. This issue here is to address that requirement appropriately.

/cc @dagood

**Comment by JohnTortugo** [comment]
@MattGal - this is an issue that frequently hit us in official builds (e.g., #4216) and it's a simple change: add a new parameter to `post-build.yml` to let the user customize the target build pool for post-build jobs. May be a good one for FR?

**Comment by MattGal** [comment]
@JohnTortugo I agree with your assessment here in terms of scale, but please make sure the Arcade Triage agrees before sticking it in the FR epic.

**Comment by JohnTortugo** [comment]
I _think_ this hasn't been an issue anymore. Perhaps we can just close the issue.
