### ISSUE TITLE
Make SymbolUploader available in dotnet-core

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#3703]
The SymbolUploader is published to myget->buildtools feed. Not the dotnet-core feed.

For now, we've added the package manually to the dotnet-core feed. 

It might be a good idea to move the SymbolUploader project over to Arcade repo and get it publishing to dotnet-core feed.  But perhaps simply changing the publishing location is sufficient.

Thoughts @mikem8361 ?

**Comment by JohnTortugo** [comment]
@markwilkie this issue looks like a dup of this one (at least partially): https://github.com/dotnet/arcade/issues/3037

**Comment by mikem8361** [comment]
I already have some engineering issues to do for the symbol uploader that include that.

https://github.com/dotnet/arcade/issues/3037
