### ISSUE TITLE
OfficialBuildId on non-Azure Pipelines CI environments

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/arcade#3706]
Preamble: I'm totally aware that Arcade was designed to be primarily used in Microsoft projects, but we're interested in adopting it for the aspnet-contrib repositories as it perfectly suits our needs.

Unlike Microsoft projects, the aspnet-contrib repositories use AppVeyor and Travis. While Arcade works like a charm there, we're a bit blocked by the versioning mechanism of official builds, that requires a very specific format for `OfficialBuildId` that doesn't work well with the ever-increasing build identifiers (that are not reset at the end of the day). It wouldn't be a problem if the `r` part of `OfficialBuildId` was not limited to 2 digits, but sadly, that's not the case.

So, my question is: what's the recommendation in this case? 😄 

/cc @martincostello

(more context: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/335)

**Comment by PinpointTownes** [comment]
Note: I'm fine moving this discussion to the .NET MVP distribution list if you think it's a better place.

**Comment by markwilkie** [comment]
Hi Kévin!  You can certainly override the versioning behavior to suit your needs  However, I would first examine carefully why the current format wouldn't work.  Versioning seem to be one of those areas that always creates challenges, and this scheme is the result of quite a few years of experience.

Adding @alexperovich for details for how to override versioning if that's the route you chose to go down.

**Comment by PinpointTownes** [comment]
@markwilkie hey, thanks for the reply!

I don't mind using the default versioning policy, which is great.

We could easily provide Arcade with the `yyyymmdd.rr` build identifier it requires (by simply using the current date and the build ID given by AppVeyor), but the fact it limits the "revision" part to 2 digits is hard to work around, as you can't exceed 99: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/src/CalculateAssemblyAndFileVersions.cs#L97

**Comment by markwilkie** [comment]
Curious, how big does {build} get?

**Comment by PinpointTownes** [comment]
It grows up indefinitely, until you decide to reset it manually via the AppVeyor portal 😄 

For concrete numbers, I've used AppVeyor for my OpenIddict project since the first day and it has processed 1195 builds so far.

I can understand we need a limit somewhere, and a 3 or 4-digit revision would be way more handy than a 2-digit one, as we wouldn't have to reset it very often.

**Comment by markwilkie** [comment]
Hmmm, what if you took the last 5 bits of {build} and used that?  (or something along those lines)

**Comment by PinpointTownes** [comment]
Assuming you're referring to `OfficialBuildId`, the format is super strict (`yyyymmdd.rr`):
  - The part before the dot MUST be a valid date. If it's not, you'll get an error: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets#L28

  - The part after the dot can't have more than 2 digits (so you're limited to 99): https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/src/CalculateAssemblyAndFileVersions.cs#L97

Did I miss something?

**Comment by markwilkie** [comment]
Sorry, I meant doing something like taking appveyor's {build} variable and bit mangling it to be smaller (5 bits would be 31).  Just thinking out loud here....

**Comment by alexperovich** [comment]
Would it be possible to just use the {build} mod 100? That's simply the last 2 decimal digits and would be correctly increasing properly. Unless you have more than 100 builds in a single day.

**Comment by PinpointTownes** [comment]
It's certainly a workaround we can use.

@martincostello suggested an approach based on quarters here: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/335#issuecomment-522264608

But ultimately, 100 builds a day is quite limited for active repos (since AppVeyor will increase the build ID for every commit pushed to a PR branch). If you end up producing more builds than that, you'll either overwrite existing packages or get an error from the repository artifacts are pushed to if overwriting is not allowed.

Curious: was there any particular reason for this limit?

**Comment by markwilkie** [comment]
>Curious: was there any particular reason for this limit?

To be honest, I'm not remembering the details, but I seem to recall we have this limit because we construct (elsewhere) a different versioning scheme from the different pieces.  However - I'm waving my hands around a lot now and could be way off base.

@tmat will know, but he's on holiday.  Also, @alexperovich might remember.

**Comment by alexperovich** [comment]
The constraints on the version came from assembly file version issues. Something about needing file versions to match the file versioning scheme from netfx so updates work correctly. I don't know the whole story though, this versioning stuff came from when the SDK was named RepoToolset.

**Comment by PinpointTownes** [comment]
Thanks for the explanation. I will a bit before closing this ticket in case @tmat would likely to add details.

In the meantime, we'll likely opt for the `mod 100` option and pray we don't produce more than 100 builds a day 😄

**Comment by PinpointTownes** [comment]
There's another problem with the `mod 100` option, tho':

Let's say the current build ID is 1199. In this case, the revision will be set to 99. If we push another commit, the build ID provided by AppVeyor will be increased to 1200, so the revision will be set to 00, which means the package will have a lower version that the previous one. Which sucks.

**Comment by martincostello** [comment]
Didn't think of that - maybe that's why I thought to go with the timed-based idea so it would self-reset.

**Comment by PinpointTownes** [comment]
> @tmat will know, but he's on holiday

@tmat looks like you're back from holiday. Please let us know if you have a clever idea or want to add some details about the versioning policy 😄

**Comment by tmat** [comment]
There is no way we can fit more digits into the version. :(

See https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md#file-version

Can you configure your CI/CD to do build every 15 minutes (that's 96 build a day) instead of on each commit?

**Comment by martincostello** [comment]
@tmat I’ve not looked into whether AppVeyor supports batching like that, but I configured something similar here: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/335#issuecomment-522264608

**Comment by markwilkie** [comment]
@martincostello - Is there more to do here in your opinion or should we close the issue?

**Comment by PinpointTownes** [comment]
@markwilkie we have a workaround, but ideally, we'd love a way to opt out Arcade's versioning logic so we could use custom build numbers without being blocked by the very strict versioning scheme. Could that be an option for you?

**Comment by markwilkie** [comment]
@PinpointTownes - some sort of opt out would be something I'd entertain.  Funny enough, if you were an internal team - it'd be a hard "no".  <grin>

We generally don't like optional stuff as it complicates things, but you guys are external so if you put up a PR, and it seems reasonable, you'll have my blessing.

**Comment by PinpointTownes** [comment]
@markwilkie excellent, thanks! I'll try to work on a PR next week 😄

**Comment by tmat** [comment]
@PinpointTownes Have you exhausted all other options, e.g. configuring AppVeyor to not build after every commit?

**Comment by PinpointTownes** [comment]
> configuring AppVeyor to not build after every commit?

Scheduled builds are no longer supported on free plans, but frankly, it's typically the kind of feature that only makes sense for very large projects like CoreFX (there's just no point building things when there's no nothing new).

**Comment by tmat** [comment]
@PinpointTownes Migrate to Azure DevOps :)?

**Comment by tmat** [comment]
@PinpointTownes 
Do you publish package built after every commit to a package feed?

**Comment by PinpointTownes** [comment]
> @PinpointTownes Migrate to Azure DevOps :)?

Yeah, as a last resort (tho GitHub Actions 2 seems like a simpler option) 😄 

> Do you publish package built after every commit to a package feed?

Yep, we do (to MyGet). Packages are available immediately once the build is finished.

**Comment by markwilkie** [comment]
Looks like you went elsewhere @kevinchalet .  However, please reopen as you see fit.

**Comment by kevinchalet** [comment]
@markwilkie yeah, sorry for not getting back to you earlier, been busy with tons of other things 😭 

We're still using Arcade (**and are totally happy with it!**) with the workaround suggested by @martincostello. However, it's not perfect, as we sometimes end up with inconsistent versions within the same build, due to how the version number is computed: since it's evaluated per-csproj by MSBuild, the quarter may change if the build starts at 20h13 and ends at 20h17.

If I manage to save enough time to implement custom version numbers support, I'll let you know.

**Comment by markwilkie** [comment]
Thanks @kevinchalet !
