### ISSUE TITLE
darc-init.ps1 should take a verbosity option

### ISSUE THREAD

**Issue by nkolev92** [dotnet/arcade#3708]
darc-init.ps1 should have a verbosity option. 

NuGet.Client is not fully integrated with arcade, but we do use scripts such as darc-init.ps1 to do our insertions. 

We're seeing some failures caused by ambient machine state, and investigating those would be quicker if the script itself had a verbosity switch rather than a hardcoded one. 

Specifically I am referring to https://github.com/dotnet/arcade/blame/master/eng/common/darc-init.ps1#L6. 

If you are ok with this change, i can create a quick PR, but I'm unsure how all these changes flow to all the other repos. 

//cc @mmitche

**Comment by markwilkie** [comment]
I'm fine in principle, so yes, please submit a PR.

**Comment by nkolev92** [comment]
PR out: https://github.com/dotnet/arcade/pull/3743
