### ISSUE TITLE
 symbol publish causes red banner, "Artifact PDBArtifacts not found" if repo didn't publish any PDBArtifacts

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#3710]
> Developer Channel:Symbol Publishing: "Artifact PDBArtifacts not found for build 315618. Please ensure you have published artifacts in any previous phases of the current build."

![image](https://user-images.githubusercontent.com/12819531/63300613-39b07e00-c29e-11e9-8abd-4d35421ca98b.png)

https://dev.azure.com/dnceng/internal/_build/results?buildId=315618&view=results

I don't know if the banner has any effect, but it's sure alarming. 😄 (https://github.com/dotnet/core-eng/issues/7498)

/cc @JohnTortugo @riarenas

**Comment by riarenas** [comment]
@JohnTortugo is there really a reason to fail the job if there are no pdbartifacts? From conversations it seemed like it was something that could be totally normal.

**Comment by JohnTortugo** [comment]
The only job that failed was the "Download PDBArtifacts", the publishing of symbols happened AFAICT.

I guess the issue here would be to not display the warning if the build didn't upload PDBs?

**Comment by riarenas** [comment]
Yes. If it's a totally normal ocurrence not to have PDBArtifacts, then we shouldn't show an error at all.

**Comment by ViktorHofer** [comment]
@JohnTortugo can we fix that? This should probably just be an informational message in the step itself. This really doesn't look pretty:

![image](https://user-images.githubusercontent.com/7412651/65718052-03d39600-e0a3-11e9-80c4-7603086b6444.png)

**Comment by ViktorHofer** [comment]
![image](https://user-images.githubusercontent.com/7412651/65718077-11891b80-e0a3-11e9-8b09-bed7dab103bd.png)

**Comment by JohnTortugo** [comment]
Closing in favor of more general issue: https://github.com/dotnet/arcade/issues/3979

**Comment by JohnTortugo** [comment]
Re-Opening as this is still going on in some form. I've a fix for it. I'll create the PR soon.
