### ISSUE TITLE
Categorize "Unknown" Linux telemetry

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#3711]
![image](https://user-images.githubusercontent.com/10092143/63301698-0a931000-c290-11e9-9e61-c0f82dcd7644.png)

We had a recent outage (dot.net was unavailable) which caused CI failures.  Failures on Windows were properly categorized as "InitializeToolset" failures (https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/313219/logs/18).  Failures on Linux were not categorized.

Unknown failures:
- https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/313219/logs/30
- https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/313219/logs/32

The Linux scripts need to be updated to be on par with the Windows scripts and categorize the failures correctly so we are not seeing "Unknown" failures.

https://github.com/dotnet/arcade/blob/master/Documentation/Projects/DevOps/CI/Telemetry-Guidance.md

**Comment by epananth** [comment]
Test -> https://dev.azure.com/dnceng/public/_build/results?buildId=319757
