### ISSUE TITLE
[maestro++/darc] Assets from source-build-reference-packages not getting assigned a location

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3712]
See https://dev.azure.com/dnceng/internal/_build/results?buildId=315787

The asset manifests have a reported location that we should be updating in BAR when the manifest gets processed by the Maestro tasks, but none of the assets for BAR build **23703** have any locations.

This is stopping depenendent repos from getting dependency flow PRs from builds from the repo.

**Comment by riarenas** [comment]
Looks like it's just a case of using an Arcade SDK from before we added the location to the assets. I updated Arcade versions in a test branch, and was able to get this build to produce assets with a location:

https://dev.azure.com/dnceng/internal/_build/results?buildId=316075 published build 23724 to the BAR, which has assets with the correct location.

{
  "id": 2082711,
  "name": "Private.SourceBuild.ReferencePackages",
  "version": "1.0.0-beta.19419.3",
  "buildId": 23724,
  "nonShipping": false,
  "locations": [
    {
      "id": 1764906,
      "location": "https://dotnetcli.blob.core.windows.net/source-build-reference-packages/index.json",
      "type": "nugetFeed"
    }
  ]
}

**Comment by riarenas** [comment]
@dseefeld Is it possible to take an arcade update for the repo, as using the newer versions of the tasks solves the issues?

**Comment by dseefeld** [comment]
@riarenas I updated the arcade version for the repo and it solved the issue.  Thanks!

**Comment by riarenas** [comment]
Great news. Closing this as it has been resolved.
