### ISSUE TITLE
[BAR] Implement Update/Delete operations

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#373]

**Comment by jcagme** [comment]
Let's plan this first, also let's focus on having Arcade builds flowing dependencies with the Create and Read functionality on BAR first.

I totally see Updates happening for Subscriptions but not for other objects like Builds, Channels or Assets. We might want to Delete medata in BAR after sometime but probably until we stop supporting a version of the product?

/cc: @mmitche @markwilkie

**Comment by alexperovich** [comment]
Update and Delete for subscriptions and repo/branch -> channel mappings has been implemented. We can create another issue if/when we need support for other operations.
