### ISSUE TITLE
SDL tools in standard post-build should allow for continue on error

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#3730]
Right now, if using the standard post-build template, SDL tools can be enabled in your pipeline using the SDLValidationParameters, but you cannot pass continueOnError through.

**Comment by mmitche** [comment]
@sunandabalu

**Comment by sunandabalu** [comment]
Makes sense, it should be easy enough to plumb through. Putting it on FR backlog.

**Comment by MattGal** [comment]
Chatted w/ Ali: sorry, both of them are already closed, I though I has closed them
