### ISSUE TITLE
Errors in the validation stage kills the dependency flow

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#3739]
CoreFx had some issues with the SDL tools as a parameter was escaped incorrectly and therefore assets weren't published. Unfortunately the BAR publish happens as a pre-publish step BEFORE the validation step. This resulted in BAR record updates without packages being available in the feed.

I believe we need to re-sequence these stages and some of its steps (currently signing is in the same stage as the BAR publish).

Example failing build in coreclr which depends on Microsoft.NetCore.Platforms which has a newer BAR version but not a corresponding package in the feed: https://github.com/dotnet/coreclr/pull/26203

cc @mmitche

**Comment by riarenas** [comment]
@johntortugo I believe this is related to what you were investigating

**Comment by JohnTortugo** [comment]
@riarenas correct. CoreFX build-defs aren't setting `PublishUsingPipelines` to true when publishing to BAR. I think we need to check which other repos are trying to use YAML stages infra and not setting that property correctly as this is causing some problems.

**Comment by JohnTortugo** [comment]
Issue moved to [dotnet/core-eng #7558](https://github.com/dotnet/core-eng/issues/7558) via [**ZenHub**](https://www.zenhub.com/)
