### ISSUE TITLE
[darc/maestro++] Add support for "admin merging", bypassing branch policies

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/arcade#3741]
Right now, if we want maestro to auto-merge a dependency update PR, we have to turn off Required Reviewers. This is not ideal, especially for release branches.

It would be nice if Maestro could auto-merge (if the build check passes) without requiring reviewer approval. Teams that want this functionality would need to add the maestro bot as an admin of their repo (or something similar).

Thanks!

**Comment by vatsan-madhavan** [comment]
Even on **master**, this is not ideal. We'd like to have this process improved before 3.1 release process.

**Comment by riarenas** [comment]
This looks similar to the asks in https://github.com/dotnet/arcade/issues/1758, the work for which we scheduled for the 3.1 timeframe.

**Comment by AdamYoblick** [comment]
Ah yes, sorry. I tried to search for an existing issue, but I didn't see this one. Feel free to close this as duplicate if you like :)

**Comment by riarenas** [comment]
Sounds good! feel free to add to #1758 if necessary
