### ISSUE TITLE
Using SignCheck to verify that a file is not signed

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#3749]
Is there a way to verify that a file isn't signed using SignCheck?

Core-Setup produces a couple of template files, `apphost.exe`/`comhost.dll`, that must not be signed, and I'm concerned that slight changes to logic might cause signing to pick it up at some point. If that happens, I want it to break the Core-Setup official build. More info about the templates: https://github.com/dotnet/core-setup/pull/7549.

If that's not possible (and I suppose it's fairly niche), would it be possible to add this feature?

@joeloff

/cc @JohnTortugo @MichaelSimons @dleeapho @vitek-karas

**Comment by joeloff** [comment]
It's not supported right now, but I can definitely see the need for this feature.

Are there copies of these files that must be signed as well, e.g. can the installer carry two copies in different folders, one that must be signed and one that shouldn't be signed?

**Comment by vitek-karas** [comment]
These must never be signed.

**Comment by dagood** [comment]
> Are there copies of these files that must be signed as well, e.g. can the installer carry two copies in different folders, one that must be signed and one that shouldn't be signed?

Nope, from a configuration standpoint, adding `FailIfSigned="true"` or some different `CertificateName` value to this existing item in our `Signing.props` seems like it'd be a good way to set this up:

```
<FileSignInfo Include="apphost.exe;comhost.dll" CertificateName="None" FailIfSigned="true" />
```

**Comment by joeloff** [comment]
OK, from the tools perspective the simplest thing would be to have something similar to the exclusion file, and anything in that file, found to be signed would generate an error. This would give you the same flexibility to specify the parent files/container paths or use the hashed paths for the check.

I can probably look at it tomorrow

**Comment by markwilkie** [comment]
Any results @joeloff ?

**Comment by joeloff** [comment]
No, unfortunately not. I've been heads down with the new installer work. I can take a look at it sometime this week. I also owe doug a fix for another issue. Can the fixes go into arcade master or another branch?

**Comment by markwilkie** [comment]
Master works.  Thanks @joeloff !
