### ISSUE TITLE
[darc/maestro++] Make gather-drop work for AzDO feeds

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3757]
The format of AzDO NuGet feeds is like shown below and this is what's currently added to BAR as Asset's Locations:

```
https://<ORG>.pkgs.visualstudio.com/[PUBLIC/]_packaging/<FEED_NAME>/nuget/v3/index.json
```

We need to fix `darc gather-drop` to be able to download the artifacts from AzDO feeds.

/cc @mmitche @riarenas

**Comment by JohnTortugo** [comment]
@jcagme do you know if we can get a download link to a package/blob on an AzDO feed?

**Comment by mmitche** [comment]
https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/artifact%20%20details/get%20package?view=azure-devops-server-rest-5.0

**Comment by JohnTortugo** [comment]
Cool. I'll see to give that a try later today :-)

**Comment by markwilkie** [comment]
@JohnTortugo - are we good here?

**Comment by JohnTortugo** [comment]
We still need to do this. @mmitche said he had some work in progress on it. It's not a lot of work.

**Comment by riarenas** [comment]
This is rolled out.
