### ISSUE TITLE
configure-toolset not respected by msbuild.sh

### ISSUE THREAD

**Issue by sbomer** [dotnet/arcade#3763]
We set `use_installed_dotnet_cli=false` in `configure-toolset.sh`. This is respected by `dotnet.sh` but not `msbuild.sh`, which will fall back to the global install.

**Comment by markwilkie** [comment]
cc/ @chcosta

**Comment by chcosta** [comment]
Can you point to an example of the behavior you're describing?  What is `dotnet.sh`?  That's not a file provided by Arcade.  It's not really expected that people directly invoke `msbuild.sh` (but people do it).

**Comment by sbomer** [comment]
Sorry, you're completely right - `dotnet.sh` is a wrapper we use in coreclr, so probably not the best example. A better example is `eng/common/build.sh` - it sources `configure-toolset.sh` allowing it to be used to override defaults (and coreclr uses this to disable use of the global SDK).

I expected `msbuild.sh` to do the same - ideally we would be able to set `use_installed_dotnet_cli` (for example) in one place and have it be respected by all of our build logic (whether we call `msbuild.sh` directly, or through some arcade .yml).

**Comment by chcosta** [comment]
>  It's not really expected that people directly invoke msbuild.sh

How are you using msbuild.sh?

**Comment by sbomer** [comment]
We use it in a number of places as the msbuild driver in our build scripts, for example https://github.com/dotnet/coreclr/blob/28362930fdf47d758476a7810c481ca6867faf65/build.sh#L142. Maybe we shouldn't be doing this?

**Comment by tmat** [comment]
I don't think it makes sense to ever call msbuild.sh/ps1 from another script. If you look at the msbuild script all it does is import `tools.sh` and call `MSBuild` function. I'd recommend doing just that directly from your script.

**Comment by tmat** [comment]
Then you should also call `configure-toolset.sh` directly from your script if you need the initialization.

**Comment by sbomer** [comment]
Fixed in https://github.com/dotnet/arcade/pull/3975.
