### ISSUE TITLE
Rename files to follow Arcade Conventions

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#377]
We have a bunch of files that aren't following the file naming convention. For instance: Restore.cmd, Build.cmd, Arcade.sln(?), NuGet.Config, Directory.Build.*

**Comment by alexperovich** [comment]
We can't change the casing of Directory.Build.* IIRC. MSBuild searches for them with that specific case and it would fail on linux.

**Comment by tmat** [comment]
Keep `Arcade.sln` - what naming convention does it not follow?

**Comment by JohnTortugo** [comment]
> Keep Arcade.sln - what naming convention does it not follow?

IMO it's odd that it starts with a capital letter when the other files are all lowercase, exceptional cases noted :-)

**Comment by markwilkie** [comment]
@JohnTortugo - Is this complete?

**Comment by JohnTortugo** [comment]
It's not yet :-/ . I'll see to take a look on it when I've some "spare" time from higher priority issues.

**Comment by markwilkie** [comment]
We'll circle back around if this comes up again
