### ISSUE TITLE
Improved guideline for symbol packages creation

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3772]
[Until this PR was merged](https://github.com/dotnet/sdk/pull/3580) .Net core SDK had symbol package creation configured in their .csproj like so:

```
<PropertyGroup>
    ...
    <IncludeSymbols>true</IncludeSymbols>	
</PropertyGroup>
```

the symbol packages created this way were put in the same folder as the regular .nupkg packages which made the Arcade SDK signing logic to pick them up for signing. As a weird side effect this seemed to trigger a latent bug in Arcade SignToolTask and caused it to repack .nupkgs with unsigned .dlls.

Action items for this issue are:

- Improve Arcade guidelines for how symbol packages should be created.
- Make SignToolTask work properly in cases where .symbols.nupkg package should be signed in parallel with regular packages.
- Work with .Net SDK team to re-enable symbol package creation in the Arcady way.

/cc @livarcocc @mmitche @markwilkie @tmat

**Comment by markwilkie** [comment]
Looks like the PR was merged, so closing.
