### ISSUE TITLE
Provide guidance on best practices for WebAPI Services

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#378]
@maririos commented on [Thu Jul 26 2018](https://github.com/dotnet/core-eng/issues/3947)

Most of this information is in our Wiki, but it would be good to review, update and unify in a way that it is easy for users to use.

Include things like:
- Use Key Vault
- Use VSTS to deploy the services
- Use variable groups
- Don't reuse bots just cause. If there is a need to create one, use the guidance => https://github.com/dotnet/core-eng/wiki/Bots

**Comment by markwilkie** [comment]
This *should* be documented now.  Also, if (when) specific confusion points arise, it's important to open a new issue.
