### ISSUE TITLE
Update test reporter azure-devops python library when released

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#3780]
The [azure-devops](https://pypi.org/project/azure-devops/) Python library used to upload test results is marked "beta." This should be updated to the released version once available. 

Test reporter is [here](https://github.com/dotnet/arcade/blob/d8457f6ba527aef165ff6fb0aded44bf8123ce83/src/Microsoft.DotNet.Helix/Sdk/tools/azure-pipelines/reporter/azure_devops_result_publisher.py).

Will also need to update artifact definitions and Docker definitions where the libraries get included in the image.

**Comment by markwilkie** [comment]
Adding to FR so this work can be tracked.

**Comment by MattGal** [comment]
Freshest version as of 10/3/2019 is 5.1.0b4, moving to tracking.

**Comment by JohnTortugo** [comment]
It's still in beta. Shouldn't we move the issue to Tracking?

**Comment by MattGal** [comment]
@JohnTortugo I agree, maybe alongside checking with the team to see if there's an ETA.

**Comment by MattGal** [comment]
Throwing back to backlog to check ; should be a newer version by now.

**Comment by AlitzelMendez** [comment]
It's still in beta. There is newer versions but all of them are pre-released version, none of them has a released version.

**Comment by ilyas1974** [comment]
As of today, the package is still in beta. No release schedule for this package has been posted.

**Comment by MattGal** [comment]
It could be potentially disruptive, but do we ever want to update to newer betas?

**Comment by ilyas1974** [comment]
As of 4/21, this library is still in beta.

**Comment by ilyas1974** [comment]
Still no update for this library.

**Comment by ilyas1974** [comment]
Still no update for this library

**Comment by ilyas1974** [comment]
We still do not have an update for this software. @garath, do you think it is worth continuing to keep this issue open as I do not believe we will be seeing any additional updates to this software (the last update was back in January).

**Comment by MattGal** [comment]
yeah it's been 7 months since their last update; I favor closing this and updating it opportunistically when we're touching the code.  Given it hasn't released in that long it's unlikely to have breaking changes in the 6.x band

**Comment by garath** [comment]
> do you think it is worth continuing to keep this issue open

I'm fine with it being closed.
