### ISSUE TITLE
Arcade guidelines for producing SourceLink information

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3782]
We should create some documentation about how repos should approach the creation of SourceLink infos.

/cc @markwilkie

**Comment by markwilkie** [comment]
I bet @tmat knows where there are sourcelink docs.

**Comment by garath** [comment]
@tmat ping

**Comment by markwilkie** [comment]
Closing this as the issue is not getting any traction, which probably has to do w/ the fact that we do have some docs already.  @tmat, if you'd like to add to it, please reopen.
