### ISSUE TITLE
Do not send test results for jobs that no longer exist

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#3784]
Azure DevOps has telemetry that shows thousands of attempts to post test result data for test runs that do not exist. Likely the job timed-out or was cancelled. 

The endpoint complaining is [Add Test Results To Run](https://docs.microsoft.com/en-us/rest/api/azure/devops/test/results/add?view=azure-devops-rest-5.1). It is called in the [results uploader](https://github.com/dotnet/arcade/blob/10b2260/src/Microsoft.DotNet.Helix/Sdk/tools/azure-pipelines/reporter/azure_devops_result_publisher.py#L70). 

An easy solution may be to simply poll the API to check that the job still exists before sending the results.

@puagarwa can provide telemetry from AzDO to confirm good behavior.

**Comment by markwilkie** [comment]
What negative observable behavior is observed here?  it's clearly bad hygiene, but are there reasons beyond that?  (I suspect there are, and am curious what they are)

**Comment by puagarwa** [comment]
It tend to waste both server resource and agent machine and also bulk of these errors sometime coverup actual issues in system, but from functionality point of view there is no issue as such.

**Comment by garath** [comment]
I don't know of anything in Helix that is affected by this. The errors get logged and execution moves on.

It does point at an area of waste. Helix has a means to cancel a queued job, but it's not used anywhere. Puneet's data shows there is at least some amount of waste on CPUs and storage for work no one will look at. With the "timeline" data we should be able to get a better picture of how many jobs are cancelled before they run. Maybe it's worth some broader effort to improve efficiency.

**Comment by missymessa** [comment]
Let's do some investigation on this and cost out the fix.
