### ISSUE TITLE
Release stages should use category telemetry

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#3797]
It doesn't appear that the release stages are using telemetry categorization.

https://github.com/dotnet/arcade/blob/master/Documentation/Projects/DevOps/CI/Telemetry-Guidance.md

This means that we don't have insight into what parts of release are causing pain for partners.

https://dev.azure.com/dnceng/internal/_dashboards/dashboard/e1bb572d-a2b0-488f-a58a-54c73a547f0d

**Comment by markwilkie** [comment]
@JohnTortugo / @riarenas - thoughts on this?

**Comment by JohnTortugo** [comment]
This looks like good to have.

**Comment by markwilkie** [comment]
Adding to the release epic.

**Comment by chcosta** [comment]
https://github.com/dotnet/arcade/pull/4272
