### ISSUE TITLE
Is darc-gather-drop.ps1 needed?

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#3798]
It looks like [darc-gather-drop.ps1](https://github.com/dotnet/arcade/blob/master/eng/common/post-build/darc-gather-drop.ps1) is just a wrapper around a single command.  Is that script needed or can we just call the command directly in https://github.com/dotnet/arcade/blob/master/eng/common/templates/post-build/darc-gather-drop.yml

@johntortugo

**Comment by markwilkie** [comment]
Moving to the release epic to be triaged.

**Comment by riarenas** [comment]
@johntortugo I wonder if this makes sense as part of the current cleanup pass. Feel free to move to the improvements epic if not.

**Comment by JohnTortugo** [comment]
This file is currently not in use. If we decide to do a gather-drop as part of the ring promotion pipelines - [see discussion here](https://github.com/dotnet/arcade/issues/3877) - we shouldn't be using the file anyway.

I'll open a PR to delete the file.
