### ISSUE TITLE
nuget-validation.ps1 isn't versioned

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#3799]
[NuGet-Validation.ps1](https://github.com/dotnet/arcade/blob/master/eng/common/post-build/nuget-validation.ps1) just downloads a script file from GitHub; that script then downloads NuGet.exe and a verification tool.  None of this is versioned and you just kind of get what they give you.  This is likely to cause problems in servicing at some point.

**Comment by markwilkie** [comment]
Moving to the release epic to be triaged.

**Comment by riarenas** [comment]
Combining with #3187 and closing this one.
