### ISSUE TITLE
Building on Linux would produce different packages

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#38]
What level of support do we want to provide for building on Linux.  

Building for the desktop framework on a non-Windows platform is not currently supported.

https://github.com/dotnet/sdk/issues/335

There's a workaround to make this work, but it's not clear to me that this is even a scenario that we really care about for the Arcade repo.  I think we'll be doing all official publishing from a Windows box, so this won't apply there, but a dev building on Linux will produce a different package that won't run on Windows.

As a temporary work around, I'm going to add something like this to `/Directory.Build.props`

```
<PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <!-- Place 'NetFxTfm' in the 'TargetFramework' property of a csproj to include building framework version if building on Windows but to skip building against the framwork on non-Windows platforms.
         Building targeting the framework is not supported on Linux
         ie. <TargetFrameworks>netcoreapp2.0;$(NetFxTfm)</TargetFrameworks> -->
    <NetFxTfm>net45</NetFxTfm>
  </PropertyGroup>
```

Do we think it's important to build framework assets on Non-Windows platforms in the Arcade repo?

/cc @weshaggard @tmat @jaredpar @natemcmaster @markwilkie

**Comment by markwilkie** [comment]
@chcosta - the PR is merged, should this be closed?

**Comment by chcosta** [comment]
No, we still need to determine how we want to build packages on Linux. Whether we want to produce framework assets in Linux builds or live with Unix and windows producing different packages.

**Comment by markwilkie** [comment]
Kicking this issue out of the closed epic and moving back to triage

**Comment by tmat** [comment]
RepoToolset now supports building .NET Framework targeting projects on Linux, except for projects that require Windows specific targets like WPF, VSIX, etc.

**Comment by chcosta** [comment]
Oh yes, I recall this PR, https://github.com/dotnet/roslyn-tools/pull/190.  Great, then the remaining work is to validate that we produce those packages correctly on Linux (https://github.com/dotnet/arcade/blob/master/Directory.Build.props#L24)

**Comment by sunandabalu** [comment]
https://github.com/dotnet/arcade/pull/115
