### ISSUE TITLE
PublishBuildAssets job fails if there's a default channel set up for the internal and GitHub version of a repo + branch combination

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3826]
See https://dnceng.visualstudio.com/internal/_build/results?buildId=335739. 

```
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19429.16\tools\SdkTasks\PublishBuildAssets.proj(30,5): error : RestApiException`1: The response contained an invalid status code 500 Internal Server Error
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19429.16\tools\SdkTasks\PublishBuildAssets.proj(30,5): error : 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19429.16\tools\SdkTasks\PublishBuildAssets.proj(30,5): error : Body: {"message":"An error occured.","errors":null}
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19429.16\tools\SdkTasks\PublishBuildAssets.proj(30,5): error :    at Microsoft.DotNet.Maestro.Client.Builds.OnCreateFailed(HttpRequestMessage req, HttpResponseMessage res) in /_/src/Maestro/Client/src/Generated/Builds.cs:line 234
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19429.16\tools\SdkTasks\PublishBuildAssets.proj(30,5): error :    at Microsoft.DotNet.Maestro.Client.Builds.CreateInternalAsync(BuildData body, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/Builds.cs:line 293
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19429.16\tools\SdkTasks\PublishBuildAssets.proj(30,5): error :    at Microsoft.DotNet.Maestro.Client.Builds.CreateAsync(BuildData body, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/Builds.cs:line 214
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19429.16\tools\SdkTasks\PublishBuildAssets.proj(30,5): error :    at Microsoft.DotNet.Maestro.Tasks.PushMetadataToBuildAssetRegistry.PushMetadataAsync(CancellationToken cancellationToken) in /_/src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs:line 87
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19429.16\tools\SdkTasks\PublishBuildAssets.proj(30,5): error : 
##[error].packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19429.16\tools\SdkTasks\PublishBuildAssets.proj(30,5): error : RestApiException`1: The response contained an invalid status code 500 Internal Server Error
```
The default channel configuration at the time was:
```
(512)  https://dev.azure.com/dnceng/internal/_git/dotnet-arcade @ refs/heads/riarenas/minimal-repro -> riarenas-test
(513)  https://github.com/dotnet/arcade @ refs/heads/riarenas/minimal-repro -> riarenas-test
```

Once I removed default channel 513, the build stage succeeded:
https://dnceng.visualstudio.com/internal/_build/results?buildId=335746&view=results

**Comment by JohnTortugo** [comment]
I tried to repro this in Maestro INT but couldn't. No 500 error, things are looking normal. Here are the steps I did:

- Have the same Arcade branch+commit in Azdo and GitHub
- Configured a few default channels for that branch; using both AzDO and GH Urls
- Used the Maestro INT API to create new builds

The API added the multiple default channels and returned 200 response. 

However, it only added the default channels configured for GitHub, i.e., it ignored the default channels configured using the AzDO URLs. I'm looking at this behavior in the scope of [this other issue](https://github.com/dotnet/arcade/issues/3628).

@riarenas - what do you think of this?

**Comment by riarenas** [comment]
Just to clarify, the errors happen when a build runs the publishMetadatatoBuildAssetRegistry task when both default channels exist.

Could you try running an entire build with the same setup against INT? I was able to repro this very recently when deciding whether this was still an issue, but I only tested it against PROD. I can't recall any fixes in INT that would help with this issue, but that would be great news if all it takes is a rollout to fix this.

**Comment by JohnTortugo** [comment]
Tested it with this build: https://dnceng.visualstudio.com/internal/_build/results?buildId=473885&view=results . The build got persisted fine in BAR INT. However, only the default channels configured via GH URLs were added.

**Comment by riarenas** [comment]
Nice!, seems like we fixed this unintentionally along the way.

Are the errors during publishing from those builds due to your changes, or should we be worried about rolling out?

**Comment by JohnTortugo** [comment]
Talked offline. 

The error that we were seeing in publishing the assets were due to a typo:

    value: "hHttps://maestro-int.westus2.cloudapp.azure.com"
