### ISSUE TITLE
Simplify the artifact category mechanism in PublishArtifactsInManifest task

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3828]
The current approach of keeping a static mapping of extension -> category 

https://github.com/dotnet/arcade/blob/316c80d0c373be63f991cc4d586db85273c1c553/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifest.cs#L897-L909

means that whenever we need to add or change these categories, we need to:

* Generate a new version of the task package
* Change the version files of the Arcade SDK to use the new task package

The process is not great whenever a new extension needs to be added.

A possible solution is to simplify the categories into:

* Packages (NuGet packages)
* Blobs  (Everything else)
* Hybrid (Blobs that are also packages, such as symbol packages)

**Comment by mmitche** [comment]
Not needed for 3.1, moving to 5

**Comment by riarenas** [comment]
Fits the theme of improvements that we want to make for .NET 5. Keeping in the current epic.
