### ISSUE TITLE
Refactor the parameters passed to PublishArtifactsInManifest

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3842]
The list of parameters to PublishArtifactsInManifest is getting pretty big. See example here: https://github.com/dotnet/arcade/blob/master/eng/common/templates/post-build/channels/netcore-tools-latest.yml#L90

Some of these parameters come from env. vars and can be directly accessed by the .proj file instead of receiving them as properties. 

Also, we don't need to duplicate properties for internal/public values. We can use a single set of properties for that and the channel implementation will take care of passing the correct value (internal / public) to the task.

/cc @mmitche @riarenas

**Comment by markwilkie** [comment]
Moving to the release epic to be triaged.

**Comment by riarenas** [comment]
We've documented the current parameters. Closing.
