### ISSUE TITLE
DotNetFinalVersionKind=release doesn't work

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#3856]
When setting DotNetFinalVersionKind=release, an error is hit in the Packaging targets:

/root/coresetup/.packages/microsoft.dotnet.build.tasks.packaging/1.0.0-beta.19454.31/build/Packaging.targets(828,5): error : No VersionSuffix was set. Ensure it is set before targets in packaging are ran. [/root/coresetup/src/pkg/projects/netcoreapp/pkg/Microsoft.NETCore.App.Ref.pkgproj]

**Comment by JohnTortugo** [comment]
Hey @mmitche can you point to the build?

**Comment by mmitche** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=338867&view=results

**Comment by mmitche** [comment]
Fixed in various repos (conform to arcade conventions) as well as mnor tweaks in arcade.
