### ISSUE TITLE
Make it easy to browse source code for a package

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3863]
I think we should make it easier to browse the sources for a given package ID + version combination. Currently, when I want to check what are the actual sources for a given package I do this:

- Go to Maestro API and look up the build id that produced the given package ID + version combination.
- Using the Maestro API again I look up the commit SHA of the asset's build.

May be we can add some darc command that to help with that? Something like:

```
$> darc link-to-source --package Microsoft.DotNet.Arcade.Sdk --version 1.0.0-beta.19453.5
$> https://github.com/dotnet/arcade/tree/aa55374e2a4347799753abcd88969cd5aa72e31b
```

/cc @mmitche @riarenas @markwilkie

**Comment by riarenas** [comment]
Looks like darc get-asset does exactly what you want:

darc get-asset --name microsoft.dotnet.arcade.sdk --version 1.0.0-beta.19453.5

returns
```
Looking up assets with name 'microsoft.dotnet.arcade.sdk'and version '1.0.0-beta.19453.5' in the last 30 days
Microsoft.DotNet.Arcade.Sdk @ 1.0.0-beta.19453.5
Repository:    https://github.com/dotnet/arcade
Branch:        refs/heads/master
Commit:        6e94f0da0f12c7663ab39ce5bd6a67c4ab58b5ee
Build Number:  20190903.5
Date Produced: 9/3/2019 3:25 PM
Build Link:    https://dev.azure.com/dnceng/internal/_build/results?buildId=336054
BAR Build Id:  25986
Channels:
- .NET Tools - Latest
- .NET Tools - Validation
```

**Comment by JohnTortugo** [comment]
Kind of exactly. But that's good enough.

**Comment by markwilkie** [comment]
Also, azdo artifacts make this better.
