### ISSUE TITLE
Re-enable darc gather drop on channel implementations

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3877]
Once [this PR is merged](https://github.com/dotnet/arcade-services/pull/622) and the corresponding issue is closed we'll have a new version of darc that supports gathering packages from an AzDO feed. Once that happen we need to [revert this PR](https://github.com/dotnet/arcade/pull/3876) to add back a gather drop at the end of the publishing pipelines.

/cc @riarenas

**Comment by markwilkie** [comment]
@JohnTortugo - ready to revert?

**Comment by JohnTortugo** [comment]
Yeah, I think so.

**Comment by riarenas** [comment]
Closed by mistake. I was just moving it to the current epic

**Comment by riarenas** [comment]
@johntortugo @mmitche is there still motivation to do a gather drop at the end of every build or should we think of this for the release rings?

**Comment by mmitche** [comment]
Release rings.
