### ISSUE TITLE
Confusing error in build.sh when restore not passed

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/arcade#3878]
In WSL Ubuntu, I cloned dotnet/corefx then did `./build.sh` (this does `--restore --build`)

Then I did `./build.sh --buildtests` and I got
```
dan@danmose3:~/git/corefx$ ./build.sh --buildtests
/home/dan/git/corefx/.dotnet/sdk/3.0.100-preview7-012821/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(39,5): error NETSDK1042: Could not load PlatformManifest from '/home/dan/git/corefx/artifacts/bin/testhost/netcoreapp-Linux-Debug-x64/shared/Microsoft.NETCore.App/5.0.0/PlatformManifest.txt' because it did not exist. [/home/dan/git/corefx/src/Common/tests/CoreFx.Private.TestUtilities/CoreFx.Private.TestUtilities.csproj]
```

It would be helpful if (whether doing `--build` or `--buildtests`) it failed with a clear error if `--restore` is needed. Eg., `Please add --restore and try again`

@ViktorHofer

**Comment by danmosemsft** [comment]
Oh, no it's LANG again.

**Comment by talibsharif** [comment]
@danmosemsft - can you elaborate what you did to fix this. I am running into the same issue:

ConflictResolution.targets(39,5): error NETSDK1042: Could not load PlatformManifest from

Have a fresh checkout from corefx 3.1.1 branch.

The following all succeed.
.\build.sh --clean
.\build.sh --allconfigurations
.\build.sh --restore

Then the following fails
.\build.sh --buildtests 

@ViktorHofer

**Comment by danmosemsft** [comment]
@talibsharif this was because I was in WSL. In WSL, it is necessary to set the LANG environment variable to override their default. See discussion here https://github.com/dotnet/runtime/issues/29918

If you aren't using WSL then please open a separate issue with the full console output.

**Comment by talibsharif** [comment]
Thanks @danmosemsft - let me try the LANG trick, otherwise will open up a separate Issue
