### ISSUE TITLE
[Signing] Evaluate how to to unpack -> sign -> repack MSIs

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#388]

**Comment by natemcmaster** [comment]
I've done a little digging on this. My conclusion: don't. It's better to sign inputs to the MSI before creating it. Unpacking (e.g. using Wix's dark.exe tool) and repacking may not roundtrip all info you need.

**Comment by markwilkie** [comment]
I'm inclined to agree w/ Nate on this one.  As we dig further into the scenarios, I'm hopeful that we can can find a way to keep signing as a post build step, but have "2 stage" signing to accommodate MSI's (and potentially other complex packages)

**Comment by natemcmaster** [comment]
Just my 2 cents: I'm hoping to change the aspnet build to code-signing in build order instead of  unpack/repack. Repacking is easy for zips, but difficult to do with MSIs, macOS pkg installers, LZMA archives, and others. ASP.NET's build is currently a mix of inline and post-build signing, and it's really messy. It was done that way for historical reasons, but I don't think those reasons apply anymore with the new signing clients.

**Comment by tmat** [comment]
We will keep repacking for containers that support it and add some other mechanism for MSIs and others.

**Comment by joeloff** [comment]
The problem with MSIs is that the File table tracks file hashes which are critical for installs when it comes to upgrade rules, especially where unversioned files are concerned. If you use DTF, you can actually extract files, sign them and then update the CAB files. This should result in updating the file hashes too. 

The tricky parts are
1. You need to figure out the files to sign, especially if they're harvested. You'll need to look at the correct columns in the File table. 
2. If an MSI contains multiple CABs you need to make sure that the signed file is placed back in the original CAB. And if there are detached CABs you'll want to sign them as well.
3. If the MSI is part of a WiX bundle, then things become difficult. The WiX bundle will record information in its manifest. In this case you would need to decompile the bundle with Dark, sign the MSIs and their content. You will then need to rebuild the bundle and update the application manifest entries for the MSIs. Once you've done this, assuming the MSIs are statically linked to the bundle, you will need to detach the bundle engine, sign the engine, reattach and sign the whole bundle.
