### ISSUE TITLE
How to communicate about post-build templates's deprecated parameters

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3884]
Decide what's the best way to communicate about deprecated parameters to post-build templates.

For instance, we recently removed the symbol validation from the post-build stages, nevertheless we need to maintain the `enableSymbolValidation` parameter in post-build.yml until we patch every build definition to not use that parameter. We need to come up with a plan to warn about such removals instead of going to every build definition and removing the parameter.

**Comment by markwilkie** [comment]
@sunandabalu - could you work with @riarenas to make sure we're making this this a part of our release notes please?

**Comment by missymessa** [comment]
I don't think we've had problems with this in the last few years, so I'm going to close it out.
