### ISSUE TITLE
Move warnaserror from build scripts to common props

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#389]
In build.ps1/build.sh we currently hard-code the msbuild `/warnaserror` option to the msbuild invoke commands. In general I like to make warnings as error but there are cases where someone might need to opt-out of that for a given project so I think we should switch to using the property MSBuildTreatWarningsAsErrors in our common props instead of the command line switch. That way individual projects can opt-out of the setting where as they cannot do that with the command line switch (at least I didn't see a way to do that). 

https://github.com/Microsoft/msbuild/pull/1928 for reference about the warn as error feature for msbuild.

@tmat what are your thoughts?

**Comment by tmat** [comment]
I'd rather not do this a-priory. Let's wait until someone asks for it and have compelling reason.

**Comment by weshaggard** [comment]
The reason I filed this is because I'm running up against it in corefx right now. There are some warnings that are now errors that are not so easy to fix and I'm trying to avoid too many distractions so I wanted to turn this off for now. I think having the knob will help folks onboarding as well as folks that that run up against an issue.

**Comment by tmat** [comment]
OK, Sounds reasonable, although if there is no forcing function these warnings will never get fixed ;)

**Comment by weshaggard** [comment]
> although if there is no forcing function these warnings will never get fixed

I agree we need this forcing function and if I do disable it I will ensure there is an issue tracking it. 

Given the build scripts are checked in the repo I can also temporarily disable this flag via some option passed to the build script

**Comment by markwilkie** [comment]
@wes took a different approach and this issue can be closed.
