### ISSUE TITLE
Helix SDK should have option to error out for any disabled queues

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#3892]
Thoughts here:

If a Helix queue has the  "IsAvailable" property as false in the queue info API, we should:
- Not upload anything to storage (it won't ever get used)
- Cause an error if the job was going to be waited on (it was going to be a failure anyways) 
- Cause a warning if the job was NOT going to be waited on (since it needs to be logged somewhere and hey that build could still pass)

This will save users time and us money letting them know to update their source code for Helix queue lists.

**Comment by Tohron** [comment]
I'm able to test a queue with IsAvailable = false using local code, now working on determining the status of a queue and whether a job is being waited on in code.

**Comment by jonfortescue** [comment]
A stretch concept for this would be to cache the queue info API locally and check against it as a Roslyn analyzer, but that's A Lot™️

**Comment by Tohron** [comment]
This change was apparently reverted - looking for details on what replaced it to post here, before closing this.

**Comment by MattGal** [comment]
On further thought, we should discuss this at triage since there's clearly some disagreement whether we even want this work.  I'm removing the epic so we can discuss.

**Comment by markwilkie** [comment]
Leaving for triage discussion.

**Comment by garath** [comment]
Triage: Concern about hiding errors that shouldn't be hidden. Closing.
