### ISSUE TITLE
Feature request : Provide ability to upload specific file(s) from enqueued runs as artifacts

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#3893]
Once a helix run is done, we have APIs to let us get all the produced files from that run.  It'd be nice (with some wildcard-based masking) to be able to pick up, say, "*.xml", "*.log", *.trx, and maybe even *.dmp from the helix run and store it in artifacts as part of the build, which will live as long as that build does and provide a central place to access it.

**Comment by markwilkie** [comment]
Added to the Helix rework epic.

**Comment by markwilkie** [comment]
I see to recall that we've received quite a few request for this.  Is that accurate?

**Comment by MattGal** [comment]
Given the number of things we upload and my experiences with the AzDO Artifact service since last September, I think doing this work (ESPECIALLY the dumps) would overload AzDO and get artifact service usage throttled.  

The main reason folks want this is that for things like logs and dumps from .Open, their URLs live in Kusto long after their storage containers were cleaned up;  this is the "I care about that crash, but I was busy with other things for 10 days before investigating it" scenario.  It usually comes up in response to a subtle and hard-to-repro runtime bug and stops being as important  once such a bug is resolved.   

One possible workaround for this would be to have test runs in the helix internal queues, where storage lives much longer (I believe we give at least 30, maybe 90 days read access by default?) such that the URLs from the Helix API would be usable that much longer.

**Comment by markwilkie** [comment]
I haven't heard much demand from our customers lately, so am closing this.  Please reopen as necessary.

cc/ @Chrisboh
