### ISSUE TITLE
Capture telemetry for build data, not just timeline data

### ISSUE THREAD

**Issue by mthalman** [dotnet/arcade#3902]
In order to do proper analysis of our Docker pipeline builds, we need to know the values of the build parameters that were set when the build was queued.  This data is available in this REST API: https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get?view=azure-devops-rest-5.1#build.  This data is not being captured in the telemetry data in Kusto.  Without this data, we can't properly compare the results of two or more builds because they may have been queued with different parameters which has a significant effect in what the build does in our case.

**Comment by markwilkie** [comment]
Added to the CI council telemetry epic.  Move as needed...

**Comment by chcosta** [comment]
@mthalman , can you remind me what the POR was here?  Was the expectation that .NET Core Engineering start doing this work or that you were going to submit a PR for updating https://github.com/dotnet/arcade-services/tree/master/src/Telemetry?

I'm trying to figure out what to do with this issue.  I don't think this belongs in this epic (I'd like to close this epic out).  Unfortunately, I don't see another home for this issue either.

@Chrisboh, thoughts on what to do with this?

**Comment by Chrisboh** [comment]
I would like to better understand what the challenges are around not having the parameters?  What is the currently telemetry missing that is keeping you from creating buckets and finding the failing builds to fix them up?

**Comment by chcosta** [comment]
>  the values of the build parameters that were set when the build was queued.

This information is not available from the Timeline.

**Comment by mthalman** [comment]
> @mthalman Matt Thalman FTE , can you remind me what the POR was here? Was the expectation that .NET Core Engineering start doing this work or that you were going to submit a PR for updating https://github.com/dotnet/arcade-services/tree/master/src/Telemetry?

I'm not sure there was a plan.  I had no plans on adding this.  That's not to say I won't do it; it's just that the work hasn't been planned.

**Comment by mthalman** [comment]
> I would like to better understand what the challenges are around not having the parameters? What is the currently telemetry missing that is keeping you from creating buckets and finding the failing builds to fix them up?

We care about more things than just failures.  We're very concerned about the performance of the builds and need metrics on them.  Here's an overview of the questions we want answered about our builds:
* What is the historical view of build times for an official pipeline?
  * By overall build time
  * By pipeline stage
  * By job
* What are the long poles of a pipeline (i.e. where we should focus our efforts to improve perf)?
* Are there any build agent outliers (i.e. is there a particular agent that is performing worse or better than others that should be investigated)?
  * Is an agent repeatedly failing and requiring action by DDFUN?
* How much time is spent waiting for an agent to be available (including which pool and demands)?
* What is the monetary cost of a build?
  * What is the total CPU time spent on a build for a given agent configuration?
* What are the errors that occur during a build?
  * Are they infrastructure- or product-related?
  * How often do they occur?
  * How many retries must be made on a build due to errors?

From those questions, we're trying to determine what telemetry we need in order to answer those questions.

The build parameters are necessary because our process involves manually queuing official builds with custom build parameters.  The product that's being released impacts which build parameters are used when queuing the build.  It's not feasible to define separate pipelines that encapsulate the different sets of build parameters that we use; it would cause an explosion of the number of pipelines we'd need to manage.  For that reason, we're very much reliant on knowing what build parameters were used in order to interpret the telemetry data.  Without knowing the build parameters, comparing the telemetry results of two different builds could be comparing apples to oranges.

**Comment by markwilkie** [comment]
Does the AzDO timeline stuff work for your @mthalman ?  (I'd like to triage this issue correctly)

FYI, @chcosta has done a lot of work understanding and leveraging AzDO timelines and can I'm sure help provide guidance...

**Comment by mthalman** [comment]
@markwilkie - No, the timeline data on its own isn't sufficient because it doesn't provide the values of the build parameters.

**Comment by markwilkie** [comment]
We talked about this at triage, and we haven't seen other teams ask for this.  (builds can be compared)  If you think this is worth a PR, we'd be ok taking a look.  Keep in mind not to leak anything sensitive.

**Comment by mthalman** [comment]
This is no longer blocking due to the availability of all the necessary data from the 1ES Kusto.  This contains data on all internal builds.  IMO, this makes the Arcade build data obsolete.

**Comment by markwilkie** [comment]
Interesting, could you share link @mthalman?  I'm a little embarrassed to admit that I'm not sure I'm aware of this.

cc/ @Chrisboh @ChadNedzlek as they're might know about this.

**Comment by mthalman** [comment]
The Kusto cluster is https://1es.kusto.windows.net.  You need to add yourself to the "1ES Data" project in https://myaccess to get access to the necessary DBs.

**Comment by markwilkie** [comment]
Thanks @mthalman .  Would you mind sharing the queries you use as examples?

**Comment by MichaelSimons** [comment]
This is an example of a query used in the docker dashboard to monitor the amount of compute being consumed by CI validation and official builds.

```
let dotnetBuilds = datatable(DefinitionId:long, ProductFamily:string, BuildType:string)
[
  359, "core-nightly", "Official Build",
  373, "core", "Official Build",
  376, "core-samples", "Official Build",
  372, "fx", "Official Build",
  374, "fx-samples", "Official Build",
  453, "core-nightly", "PR Validation",
  387, "core", "PR Validation",
  739, "core-samples", "PR Validation",
  454, "fx", "PR Validation",
];
alias database["AzDO"] = cluster("https://1es.kusto.windows.net").database("AzureDevOps");
database("AzDO").BuildTimelineRecord
    | join kind=inner (
        database("AzDO").Build 
        | join kind=inner dotnetBuilds on DefinitionId
        | where OrganizationName == "dnceng"
        | distinct *
        | project OrganizationName, BuildId, ProductFamily, BuildType, BuildStartTime=format_datetime(StartTime, 'yyyy-MM')
    ) on OrganizationName and BuildId
    | where State == 'completed' and Type == "Task"
    | extend Duration = FinishTime - StartTime
    | extend Platform = iff(WorkerName hasprefix "DDVSOLINUXAGE" or WorkerName hasprefix "ubuntu" or WorkerName hasprefix "ddvsotx" or WorkerName hasprefix "Azure Pipelines", "linux",
        iff(WorkerName hasprefix "DDVSOWINAGE" or WorkerName hasprefix "dotnetdoc" or WorkerName contains "dock", "windows",
        "unknown"))
    | summarize TotalDuration = sum(Duration) by BuildId, ProductFamily, BuildType, BuildStartTime, Platform
    | sort by BuildId desc
```
