### ISSUE TITLE
[PKPIs] Superfluous Input Subscriptions (for BarViz)

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#3906]
| Name | UI | Qualifier | Indicates | Drives Action | Notes |
| ---- | -- | --------- | --------- | ------------- | ----- |
| **Superfluous Input Subscriptions** | Darc / BarViz | Per Repo, Per Default Channel (input branch) | Indicates that a branch that applies to a default channel has subscriptions that may do nothing. Each dependency should be evaluated based on the assets produced by the last build applied to the input subscriptions. This metric is inexact. It's possible that a subscription that looks superfluous now will produce a needed asset in the future. | Repository owner determines whether those subscriptions can be deleted. | - This is already done in [darc](https://github.com/dotnet/arcade/issues/2800), needs to be done in barviz |

**Comment by adiaaida** [comment]
Closing because the parent Epic was closed. If you believe this issue should still be worked on, please re-open.
