### ISSUE TITLE
[PKPIs] Number of dependency updates per given time frame

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#3907]
| Name | UI | Qualifier | Indicates | Drives Action | Notes |
| ---- | -- | --------- | --------- | ------------- | ----- |
| **Number of dependency updates per given time frame** | PowerBi | Per Output channel, Per Repo | Measures rate at which dependency updates are produced.  Lower numbers are better, large numbers indicate unneccessary complexity. As product moves towards shipping, number of dependency update PR's decreases.| Repository owner investigates open dependency updates and determines if increasing or current numbers are valid. | - This is a pulse metric, giving a sense of product health but may not be specifically actionable by repo owners. |

**Comment by meganaquinn** [comment]
We don't currently store this information, so it'll need to be retrieved using GitHub APIs through C# then stored. I chatted with people about how the dependency PRs are created and I know how to get the information, working on a prototype now.

The open questions I have right now are:
1 - Where/when should this run and where should the information be stored? (Unless there's a way to do on the fly api calls from Power BI that I'm not aware of?)
2 - Is this the count of the number of PRs triggered for dependencies or the number of dependencies changed in those PRs? (Each PR changes 2+ dependencies in most cases)
3 - What is the "given time frame"? Does it need to be variable? Is there a min/max or a granularity? Most likely we'll be building this query to github in C# & then storing the results to get it to Kusto/PowerBI, what granulatity/retention rate do we need?
4 - Is this only counting open dependency updates? Or is it all updates? (Drives action section implies that it's only open ones) If it's open only the overall technical requirements are the same, it still needs to be a parsed github query, it just has an extra filter
