### ISSUE TITLE
Fix '$(IsShipping)' == 'false' to conventional '$(IsShipping)' != 'true'

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#3908]
To match conventions and avoid confusion, this should be `'$(IsShipping)' != 'true'`:

https://github.com/dotnet/arcade/blob/694d59f090b743f894779d04a7ffe11cbaf352e7/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets#L101-L104

The explicit `== 'false'` suggests it's something like a nullable bool, where `false` and empty mean different things. (If this is the case, it should be described somewhere.)

/cc @mmitche

**Comment by mmitche** [comment]
Sure thing.
