### ISSUE TITLE
Add the dotnet SDK to the dependency flow system

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#3924]
We are currently manually updating the dotnet SDK on a per-repo basis. Adding the SDK to the dependency flow system would help identify bugs earlier, e.g. the combination of a specific compiler version with a specific shared framework (Microsoft.NetCore.App) version. We discussed that couple times in our corefx infra standups but I couldn't find a tracking issue for that.

cc @mmitche @markwilkie

**Comment by mmitche** [comment]
It is handled from here. Arcade defines a minimum version.  If the repo getting an arcade update has a version older than what arcade has, it will be updated.

**Comment by mmitche** [comment]
> What I mean is that we would like to be able to update the SDK version automatically every X days. I understand that arcade defines a minimum version but on a repo-basis we would like to dogfood newer builds periodically.

We are currently in discussions as to how this relates to overall toolset policy (using non-released versions) because it has implications outside of dogfooding.

**Comment by markwilkie** [comment]
@mmitche - next steps?

**Comment by mmitche** [comment]
I think this is tied up in core-sdk still, right @riarenas?

**Comment by mmitche** [comment]
We've decided the SDK should not update automatically every X days. Instead, it is a deliberate event:

https://github.com/dotnet/arcade/blob/master/Documentation/Policy/ToolsetPolicy.md#net-sdk--managed-toolset
