### ISSUE TITLE
Decide what TFMs we should use for our build tasks.

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#393]
Currently we have a bunch of build task packages that build with different TFMs. We need to settle on a single set of TFMs for all task packages.

**Comment by weshaggard** [comment]
My initial strawman would be "netcoreapp2.1;net461" that way we get exactly the set of dependencies for each of those platforms as that is all these tasks are expected to run on.

**Comment by rainersigwald** [comment]
I'd say `netcoreapp2.1;net46` since that's what MSBuild targets.

**Comment by weshaggard** [comment]
In https://github.com/dotnet/arcade/issues/59 we decided 461 for desktop because that is what VS requires.

**Comment by tmat** [comment]
Haven't we started discussion on using `net472`? let's update our Jenkins machines to have 4.7.2. MicroBuild machines have it.

@jaredpar

**Comment by markwilkie** [comment]
@jaredpar / @mmitche - should we skip 461 and go to 472?   This is likely related to OS onboarding.

**Comment by jaredpar** [comment]
In our side thread, think it was email only, we appeared to be settling on net472 as the TF for our tooling. All of the core infrastructure already uses this framework hence it should present no real problems on that aspect. 

My only fear is that it will be a barrier to contribution. We know for example some developers contribute to Roslyn on Windows 7 installations. At the same time though it's a reasonable ask that they move to a specific version of .NET in order to contribute. Especially now that net472 is an WU.

**Comment by markwilkie** [comment]
My personal preference is to use the most widely adopted platform (in this case 4.6.1)

Is there a reason we should move to 472, other than it's the latest?

**Comment by tmat** [comment]
Yes, it's the first version of .NET FX where netstandard 2.0 support is not buggy.

**Comment by jaredpar** [comment]
It also simplifies deployment considerably. There are essentially no facades + massive binding redirects to carry around with every single tool that we own.

**Comment by markwilkie** [comment]
@jaredpar - thoughts on #59 which is related?

**Comment by jaredpar** [comment]
@markwilkie forgot we had that issue. I'm not sure why we have both #59 and #393. We should be picking the same TF for both.

**Comment by weshaggard** [comment]
The only hesitation I'd have around picking net472 is older systems. For example all our build and test machines that run our tools will need to be updated to net472 which I think is a fine requirement. Another case we had in the past is the ability to run some of our tools in razzle which has a holder version of the .NET Framework included in it but again I don't think we need to worry about that at this point. We can always add additional build configurations for any special tools that need to work in an older environment.

So it sounds like we are leaning towards our tasks and tools targeting `netcoreapp21;net472`. For shared libraries I think we can target `netstandard2.0`.

**Comment by jaredpar** [comment]
> So it sounds like we are leaning towards our tasks and tools targeting netcoreapp21;net472. For shared libraries I think we can target netstandard2.0.

Agreed.

**Comment by markwilkie** [comment]
Looks like this is sorted.  Namely, tasks and tools targeting netcoreapp21;net472. For shared libraries I think we can target netstandard2.0.

**Comment by weshaggard** [comment]
@markwilkie the decision was made but I think it is worth documenting and doing a pass over the projects to make sure we are consistent.

**Comment by tmat** [comment]
We first need to make sure all Jenkins jobs are running on machine with 4.7.2.

**Comment by markwilkie** [comment]
@Wes, oops, forgot to add the doc link I filed.  https://github.com/dotnet/arcade/issues/976

@tmat, are you suggesting Jenkins target 4.7.2 before coming over?

**Comment by tmat** [comment]
Yes, we still need to be able to run all Arcade build tasks on Jenkins.

**Comment by weshaggard** [comment]
I'm going to reopen this again as we still need to do work beyond documenting to move this item forward. 

We need to setup move NetFxTfm to net472 and update the machines across the many systems to enable that move. We should also create a NetCoreAppTfm property and set it to netcorepapp2.1 so we can consistently use that as well. We should also think about having a way to pre-process our props/targets that currently hard code these tfms (ex: https://github.com/dotnet/arcade/blob/2b650e6d8b999afe2baa197a3812231d853246ce/src/Microsoft.DotNet.Arcade.Sdk/tools/BuildReleasePackages.targets#L9 and https://github.com/dotnet/arcade/blob/8839cc144d0dd99279285caa6eebf3859c06b062/src/Microsoft.DotNet.Build.Tasks.Feed/build/Microsoft.DotNet.Build.Tasks.Feed.targets#L43).

**Comment by jcagme** [comment]
Some projects like `Microsoft.DotNet.Arcade.Sdk` still use `net461`, other use the `$(NetFxTfm)` property which currently is [net461](https://github.com/dotnet/arcade/blob/master/Directory.Build.props#L20) and other made the change to net472
