### ISSUE TITLE
[Maestro++ / Darc] Dependency update PRs that flow feeds to nuget.config remove comments

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3938]
We currently only recreate the package sources inside the nuget.config when a dependency update flows new feeds. We should also respect comments in the file

**Comment by dagood** [comment]
When can we expect the fix live? I see some discussion about this not being a patch to prod in https://github.com/dotnet/arcade/issues/3944, but what does that mean?

This makes auto-update PRs require manually intervention in Core-Setup. (All branches.)

**Comment by riarenas** [comment]
We are actually planning a Production rollout for today, so we'll wait for that PR to go in, and we'll proceed to roll it out if everything looks good after it gets merged.

**Comment by riarenas** [comment]
And just to set expectations. This might have to wait until Monday if we're not able to roll out today.

**Comment by riarenas** [comment]
Reopening. This should be in rollout.

**Comment by riarenas** [comment]
This was rolled out.
