### ISSUE TITLE
Repos in devdiv failing to publish to azure devops feeds in dnceng

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3942]
For example:
* https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3046789
* https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3047333

```
WARNING: The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
...
Unauthorized https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/89836ee7-f4d9-4429-90a9-9e9005780b57/nuget/v2/ 8804ms
...
##[error].packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19461.7\tools\SdkTasks\PublishArtifactsInManifest.proj(65,5): error : Failed to determine whether an existing package on the feed has the same content as 'd:\a\1\a/PackageArtifacts/Microsoft.CodeAnalysis.CSharp.CodeStyle.3.4.0-beta2-19462-13.nupkg': Response status code does not indicate success: 404 (Not Found).
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19461.7\tools\SdkTasks\PublishArtifactsInManifest.proj(65,5): error : Failed to push 'Microsoft.CodeAnalysis.CSharp.CodeStyle@3.4.0-beta2-19462-13'. Result code '1'.

**Comment by riarenas** [comment]
Looped in the azure artifacts folks to figure out best practices, and I'll also talk to some people on our end who might have experience with this.

Looks like we have a couple of options:
* Create a NuGet service connection for every feed we're trying to push, and pass those service connections to the NuGet authenticate task. (we have 12 different feeds today, and it looks like service connections are on a per-feed basis, so this would mean 12 different service connections)

* Add the sources dynamically during the PushArtifactsInManifest task
`nuget sources add -name <name>  -source <feed url> -password <cross-org PAT>`

**Comment by riarenas** [comment]
Reply from the Azure artifacts folks when asked if there was an alternative to maintaining a separate service connection per feed:

The short answer is no, service endpoints are the supported solution for cross-organization authentication, and there must be one service endpoint per feed.

The long answer is: the credential provider uses environment variables to specify how to authenticate.

VSS_NUGET_ACCESSTOKEN can contain one PAT. The build task sets this to System.AccessToken.
VSS_NUGET_URI_PREFIXES can contain a list of uri prefixes that will use the accesstoken for authentication. The build task sets this to the pkgs endpoint variations for the current organization.

In theory, you could generate a PAT that has access to multiple organizations, provide that as a secret in the build, then update the two environment variables after NuGetAuthenticate has run to reflect your PAT/both sets of prefixes. I would not describe this as “best practice”, but I would recommend it over the nuget sources add approach.
The credential provider logic can be found here if you want to take a look: https://github.com/microsoft/artifacts-credprovider/tree/master/CredentialProvider.Microsoft/CredentialProviders

**Comment by riarenas** [comment]
@jcagme is looking into this while I take care of some GA related issues

**Comment by jcagme** [comment]
PR: https://github.com/dotnet/arcade/pull/3949

**Comment by riarenas** [comment]
The official build for that PR failed with the same error (now in dnceng). Reopening

**Comment by riarenas** [comment]
https://dnceng.visualstudio.com/internal/_build/results?buildId=354949&view=results

**Comment by jcagme** [comment]
This has been fixed by https://github.com/dotnet/arcade/pull/3971 and by temporary work arounds in Roslyn and msbuild repos
