### ISSUE TITLE
Third party Dlls are not dual signed when there is a sign from original publisher

### ISSUE THREAD

**Issue by bhsubra** [dotnet/arcade#3946]
Third party DLLs listed in eng\Signing.props are not dual signed when the dll has a signature from original publisher. If the third party dll doesn't contain original publisher's signature, arcade signs it with certificate listed in eng\Signing.props.

Sample signing.props:
```
<Project>
  <ItemGroup>
    <FileSignInfo Include="Newtonsoft.Json.dll" CertificateName="3PartySHA2" />
  </ItemGroup>
</Project>
```

We have a package reference to Newtonsoft.Json in csproj with version 12.0.2

**Comment by JohnTortugo** [comment]
I looked at the binlogs and indeed the Newtonsoft.Json.dll file isn't being sent to the signing server. For some reason SignTool isn't sending the file to be signed. 

SignTool does some check to see if the file is signed and if a dual signing is required, perhaps there is something wrong on that code.

**Comment by JohnTortugo** [comment]
@bhsubra perhaps you can post a link to a build?

**Comment by MattGal** [comment]
I'm looking at the logs and artifacts from https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3050291&_a=summary&view=logs now, will post back if I find anything useful.

**Comment by MattGal** [comment]
I got some awesome help from @JohnTortugo and I feel pretty confident in being able to debug this in the future! Looks like it's this: https://github.com/dotnet/arcade/pull/3980/files
... and I have no concept of how this DLL or any other ones is correctly doing this signing today given that.

**Comment by MattGal** [comment]
Fix is merged, hopefully this will unblock you or we'll debug once you can update the SignTool version.

**Comment by bhsubra** [comment]
@MattGal , thanks a lot for getting the fix in. Do I need to update the version of Microsoft.DotNet.Arcade.Sdk to get the changes? If yes, how do I find the version that includes this fix? Thanks!

**Comment by MattGal** [comment]
@bhsubra yes; the first Arcade SDK version with the change would be 5.0.0-beta.19468.5.  Chatting with some folks, it would seem until Arcade Validation is fixed though it wouldn't be available; @chcosta is working on that.

**Comment by bhsubra** [comment]
Thanks again @MattGal. I'll watch the other issue and update the version and test at our end. I'll keep you posted. Thanks!

**Comment by bhsubra** [comment]
@MattGal , @JohnTortugo , I verified the fix and it works great. Thanks again!

**Comment by MattGal** [comment]
Thanks for confirming, I'll close this out then.
