### ISSUE TITLE
Why not .net instead of .dotnet as the root folder?

### ISSUE THREAD

**Issue by kzu** [dotnet/arcade#3951]
From https://github.com/dotnet/arcade/blob/master/eng/common/tools.ps1#L135

`.net` would have been shorter and nicer (IMHO) than the current `.dotnet` which is a mouthful to pronounce ;)

**Comment by markwilkie** [comment]
You don't like dot dot dot dot dot dot dot dot dot dot net????  :) 

The cost is pretty high though, not to mention the fact that it's a breaking change.
