### ISSUE TITLE
[Darc/Maestro++] Dynamic feed management

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#3952]
Because custom feeds are created for all stable builds (for the stable packages), we quickly increase the number of feeds our projects.  This is going to get out of hand quickly and being hard to manage. We need to get rid of these feeds over time.  The feeds are prefixed with a "darc-" name.

This issue is complete when:
- [x] Empty (completely unused) darc feeds are deleted within a relatively short period of time The feeds are marked for deletion as soon as the feed is empty, then there is a 30 day period where the feed is recoverable.
- [x] Non-empty darc feeds are deleted when all packages are available on static feeds (e.g. dotnet3 or nuget,.org) 

It might be useful to do some sort of staged delete for the third case.  For instance, you could rename the feed (e.g. prefix with del-) at the point where there are no restores in the last N days, then wait another M days before making a final deletion. This ensures that if a mistake is made, we have a grace period to identify the feed is still needed.

**Comment by riarenas** [comment]
Un-epic-ing

**Comment by riarenas** [comment]
Last remaning piece is to check public locations to check whether a package is already available there, and to update BAR accordingly if we find them.

**Comment by riarenas** [comment]
I've been running some tests on the 3.1 int feeds in PROD to make sure this is doing the right thing. I'm not deleting any feeds yet.

* I'll run this today on all the `darc-int` feeds that we have since all packages should now be released, holding off on the `darc-pub` feeds

* Afterwards I'll make it so all empty feeds get deleted

* Finally I'll enable the functionality to delete released packages.

**Comment by riarenas** [comment]
Working on getting a list of what the tool believes are the packages that should be deleted from our feeds as already released. Once we validate that the list looks reasonable I'll actually enable the deletion of packages.
