### ISSUE TITLE
[Signing] Change how Singtool calls Microbuild

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#397]
Currently, Signtool is calling Microbuild using msbuild. see: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/RealSignTool.cs#L40

Instead, we would like to consume Microbuild targets directly and let the whole process invoke them.

FYI @weshaggard @tmat @mmitche

**Comment by jaredpar** [comment]
Why do we want to do this? 

Part of the reason it was done this way was to insulate ourselves from changes in Microbuild tasks / targets (which are effectively their API). They are free to change their tasks / targets as they wish so long as they can continue to process the `ItemGroup` as specified.

**Comment by tmat** [comment]
I think we also forgot about the fact that MicroBuild SignFiles task is Desktop msbuild task and does not run on Core, so we can't "inline" the invocation of the task. We need to build the projects that import MicroBuild targets in an msbuild.exe process.

**Comment by mmitche** [comment]
@jaredpar @maririos Are there two layers of targets here?  An outer one that is the public API interface -> inner tasks and targets?

**Comment by jaredpar** [comment]
@mmitche there is an outer set of props / targets that are the supported public API surface and this is what SignTool uses today. That is the limit of the supported API surface.

**Comment by markwilkie** [comment]
> Why do we want to do this?

Was this ever answered?

**Comment by maririos** [comment]
> I think we also forgot about the fact that MicroBuild SignFiles task is Desktop msbuild task and does not run on Core, so we can't "inline" the invocation of the task. We need to build the projects that import MicroBuild targets in an msbuild.exe process.

Closing this as per Tomas point

**Comment by weshaggard** [comment]
>I think we also forgot about the fact that MicroBuild SignFiles task is Desktop msbuild task and does not run on Core, so we can't "inline" the invocation of the task. We need to build the projects that import MicroBuild targets in an msbuild.exe process.

I think that is assuming that the outer call to our build task is happening on Core. There isn't anything that blocks that call to sign.proj from happening on full .NET msbuild as well. In general I find it odd that we are wrapping msbuild calls like this but I don't have a strong argument for why we don't want to do this at this point so I will live with it for now. As we start to onboard I will take a closer look at how this impacts the signing for the core repos.
