### ISSUE TITLE
Create pools for latest VS private but not signing builds

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/arcade#3970]
Arcade is bringing in an msbuild-sdk which is currently incompatible with 3.0 GA bits. This needs to be updated in order for people who depend on Arcade to build on 3.0 GA bits. /cc @mmitche 

in CI
```cmd
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19463.3\tools\Tools.proj : error : Version 3.0.100 of the .NET Core SDK requires at least version 16.3.0 of MSBuild. The current available version of MSBuild is 16.2.37902.0. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.
##[error].packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19463.3\tools\Tools.proj(0,0): error : Version 3.0.100 of the .NET Core SDK requires at least version 16.3.0 of MSBuild. The current available version of MSBuild is 16.2.37902.0. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19463.3\tools\Tools.proj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
##[error].packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19463.3\tools\Tools.proj(0,0): error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
```

Also worth noting is that this issue does not repro local to my machine; likely this is because my machine has latest Int-Preview of 16.4, which satisfies this need for "at least 16.3.0 of MSBuild". Perhaps we could ensure that the build machines have VS with at least this version on it? /cc @MattGal

**Comment by MattGal** [comment]
As discussed on Teams, they should be able to move from BuildPool.Windows.10.Amd64.VS2019 to BuildPool.Windows.10.Amd64.VS2019.Pre to get a version wtih 16.3 Preview 3.  We'll be updating to the latest RTM and preview bits for these queues some days after available.

**Comment by zsd4yr** [comment]
@mmitche update: we use "Hosted Windows 2019 with VS2019" pool for all "from github" psuedo-public builds. These don't have the version of msbuild we need implicit to VS and upgrading to this SDK means (still not super understanding this bit) we need it

**Comment by MattGal** [comment]
Can the title of this issue be improved?  We definitely have build agents with the required VS versions available, and the hosted agent pools will eventually catch up.   Not sure what the work for the arcade team is here, so perhaps updating that will make it clearer.

**Comment by markwilkie** [comment]
How's life @zsd4yr ?  :)

We're actually working on an updated policy to better manage VS images as it continues to be a challenge.  (not that you care anymore...grin)  Closing in favor of https://github.com/dotnet/core-eng/issues/9469
