### ISSUE TITLE
Update Helix JobSender Arcade SDK example code

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#3973]
As @jaredpar points out, with the latest Jobs API the code as-demonstrated doesn't work.  Fix it, and clean up as you go.

**Comment by jaredpar** [comment]
Specifically in this case the issue I ran into is the following line:

``` csharp
WithSource("pr/helloworld")
```

The Helix implementation will throw an exception saying that source cannot begin with pr, ci or official.

**Comment by MattGal** [comment]
(this happened when Arcade moved to the Helix 2019-06-17 Jobs API)
