### ISSUE TITLE
Post-build stages shouldn't fail if artifacts aren't present

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3979]
Currently, many (or all) of the post-build stages require that the build has produced at least:

- Build Manifest
- PackageArtifacts
- BlobArtifacts

However, some builds don't produce all this and some even don't produce any of it - [Winforms-designer is an example](https://dev.azure.com/dnceng/internal/_build/results?buildId=359015&view=results). The post-build stages/jobs should be hardened to not fail (or not even warn) if these information are missing.

A solution to this will probably requires first a solution to [this other issue](https://github.com/dotnet/arcade/issues/3700). So, very likely, both can be worked in parallel. @MattGal 

/cc @AdamYoblick @riarenas @sunandabalu

**Comment by JohnTortugo** [comment]
Related to: https://github.com/dotnet/arcade/issues/3710

**Comment by sunandabalu** [comment]
PR for SDL validation to not expect to have artifacts published - https://github.com/dotnet/arcade/pull/3985

**Comment by ViktorHofer** [comment]
is somebody actively working on this issue?

**Comment by JohnTortugo** [comment]
I'll write some instructions and ask FR to work on it. Bottom line: not right now, but very soon.

**Comment by mmitche** [comment]
PR up.https://github.com/dotnet/arcade/pull/4222
