### ISSUE TITLE
SwaggerGenerator compares ref objects to default

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#3995]
The swagger generator compares class objects to default:

```
if (body == default) {}
```

In 16.4 and beyond, this is no longer valid C#.

**Comment by alexperovich** [comment]
How is this not valid C#? The 'default literal' feature was added in 7.1.

**Comment by mmitche** [comment]
> How is this not valid C#? The 'default literal' feature was added in 7.1.

I talked to Jared about this.  It is not valid for ref types (valid for everything else). It worked because of an accident of how it was implemented, and that is now being removed.

**Comment by alexperovich** [comment]
That seems really strange. IMO anywhere the compiler can determine the type it should work.

**Comment by alexperovich** [comment]
The generator used it a lot to avoid having to figure out the appropriate T in the context because that was awkward to get.

**Comment by mmitche** [comment]
> That seems really strange. IMO anywhere the compiler can determine the type it should work.

According @jaredpar:

> default only has meaning in the places where we say it has meaning. It's called target typing. Essentially default by itself has no type. It only has a type when target typing comes into play. Essentially based on the way in which it's used we know what the type is

Target typing is applied expression by expression, but allowing == to participate in target typing was an accident.

**Comment by mmitche** [comment]
FYI we can use an explicit cast: inputVar == default(inputVarType).

**Comment by jaredpar** [comment]
Is this always against reference types? If so then use `x is null`. That's much preferred.

**Comment by mmitche** [comment]
> Is this always against reference types? If so then use `x is null`. That's much preferred.

Nope. Runs the gamut. Refs, enums, value types, etc.

**Comment by jaredpar** [comment]
What do you expect the behavior to be for a custom struct?

**Comment by mmitche** [comment]
> What do you expect the behavior to be for a custom struct?

Actually, I don't think there are any custom structs, but int, bool, string (handled specially) as well as ref types are in here.

**Comment by alexperovich** [comment]
I would expect a default constructed struct and operator ==. In this case we never compare structs though, just generated classes and keyword types.

**Comment by alexperovich** [comment]
and nullables

**Comment by alexperovich** [comment]
> FYI we can use an explicit cast: inputVar == default(inputVarType).

I used default because it worked to avoid having to do this. In some of the cases where we use default getting the type would involve code duplication that couldn't be avoided.

@jaredpar will `= default` as a method optional parameter continue to work in all cases?
