### ISSUE TITLE
Include SCEP Installer

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#40]
Today we use SCEP Installer in our CoreCLR build in the attempt to fix https://github.com/dotnet/core-eng/issues/2225 in the form of a package which 

This tool is used to install and uninstall Security Center Endpoint Protection which we think is causing the above issue. At the moment of filing this issue this is just an assumption and there is no hard data to confirm this will fix it.

If we've validated that this is the fix and we want to keep doing this we need to formalize the packaging process which today happens in someones computer and once the package is manually created we then manually upload it to the VSTS feed.

Documentation around how do we create the package and its contents can be found here: https://github.com/dotnet/core-eng/tree/master/Documentation/SCEP%20Installer

**Comment by chcosta** [comment]
Should this be moved to the core-eng repo?

**Comment by jcagme** [comment]
We won't use this approach anymore since we decided to go with the use of extension tasks so I'll close this.
