### ISSUE TITLE
Arcade validation builds are broken due to Arcade dependency updates removing a file

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#4007]
This file isn't mirrored correctly and causes the arcade validation builds to fail. We haven't got any arcade updates for some days already and depend on the SDK change. Please prioritize this issue accordingly.

https://github.com/dotnet/arcade/blob/master/eng/common/enable-cross-org-publishing.ps1

cc @chcosta @markwilkie @alexperovich @riarenas

**Comment by markwilkie** [comment]
@dnceng for FR

**Comment by MattGal** [comment]
We had https://github.com/dotnet/core-eng/issues/7898 6 days ago, but this is the first I was aware it was still broken since that issue is closed.

**Comment by MattGal** [comment]
@virk

> This file isn't mirrored correctly and causes the arcade validation builds to fail. We haven't got any arcade updates for some days already and depend on the SDK change. Please prioritize this issue accordingly.
> 
> cc @chcosta @markwilkie @alexperovich @riarenas

Which file?

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/arcade/blob/master/eng/common/enable-cross-org-publishing.ps1

**Comment by jcagme** [comment]
The file added by @ViktorHofer is been removed when the dependencies are flowed from Arcade to arcade-validation (https://github.com/dotnet/arcade-validation/pull/888/files). It might be a path length thing although I haven't checked and asked @JohnTortugo @mmitche to take a look.

**Comment by MattGal** [comment]
I'll take this; I'm working on understanding this now, but will utilize advice from @mmitche and @JohnTortugo as necessary.

**Comment by jcagme** [comment]
Happy to help if needed as well.

**Comment by ViktorHofer** [comment]
> The file added by @ViktorHofer is been removed

Note that I added the file with the assumption that it will be deleted in a subsequent commit and only did so to get a new Arcade build out.

**Comment by riarenas** [comment]
It's strange that this is only happening from Arcade to the master branch of arcade validation. Repos that get the arcade updates once we re-add the file in arcade-validation don't get the file removed, and this doesn't repro on any other repo or branch that takes an update from the .NET tools - channel.

I'll take a look at this since Matt is OOF today.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade-validation/pull/892/ just came through from arcade and is re-adding the file. I'll keep an eye out in case this was just a point in time problem (some cache in Maestro still thought the file was deleted, or we mucked about with the channels/subscriptions too much last week)

If the next dependency update PR does not delete the file, I'll close this.

**Comment by riarenas** [comment]
Another PR came through and left the file intact.

Considering this is the first time this has happened, I'm closing this issue. If it happens again it'll be worth finding what causes us to get into this temporary state.
