### ISSUE TITLE
[darc/Maestro++] Darc dependency update puts the <clear/> node in wrong place

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4009]
https://github.com/dotnet/core-setup/pull/8316/commits/3df3445a2ca206dc8d2070bb338158953d27bc9d

The clear node should be at the top.

**Comment by mmitche** [comment]
FYI I tried to repro this with the exact set of inputs and did not see the bad behavior.

**Comment by riarenas** [comment]
Fixed by https://github.com/dotnet/arcade-services/pull/659
