### ISSUE TITLE
[PKPIs] Add BarViz Visualization for Subscription Data

### ISSUE THREAD

**Issue by meganaquinn** [dotnet/arcade#4023]
Covers adding visualization to BarViz for:
Input Subscriptions

ETA: Re-scoped on 10/16/19 & again on 10/17 (all of the following require additional data sources)
The following items were split into other issues:
Conflicting Input Subscriptions (if needed)
Split subscriptions & dependencies into product/toolset
Superfluous Input Subscriptions
Missing/Disabled Input Subscriptions

**Comment by meganaquinn** [comment]
The logic for getting the enabled/disabled subscriptions can be added as a table on the existing page and will use the same "Include Toolsets" UI that's currently used for the Dependencies table. Each sub will be listed by Source Repository and there will be a separate tab for every branch on the selected (target) repo.

Getting the missing/extra/conflicting subscriptions is going to require pulling data from the Version.Details.xml for the latest build for each branch, then merging that information into the table. Because that requires a second data source that information will be loaded on demand, not on page load.
There's a chance that the repo information in the Version.Details is out of date, so I'll also be looking at whether it's possible to normalize in some way so that there's not a time when that data isn't current (which happens approximately once a month).

**Comment by riarenas** [comment]
> Getting the missing/extra/conflicting subscriptions is going to require pulling data from the Version.Details.xml

Maybe it's just a term overload, but when you say subscription do you mean something different than the data that is available in the subscriptions table? Version.Details.xml will tell you which dependencies a repo has, but those dependencies do not need to translate in a subscription.

**Comment by riarenas** [comment]
Although I guess if the goal is just to inform of such cases so that a decision can be made about whether a subscription should actually exist, it makes sense?

**Comment by meganaquinn** [comment]
Sorry, missed these comments - yes, the goal is to provide the information. Then the repo owners can make a decision.
