### ISSUE TITLE
Why does the Arcade SDK project enable GeneratePackageOnBuild?

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#4035]
https://github.com/dotnet/arcade/blob/c21a409f11386d22c6083198176868d3974de832/src/Microsoft.DotNet.Arcade.Sdk/Microsoft.DotNet.Arcade.Sdk.csproj#L10

From https://github.com/dotnet/arcade/pull/4030#discussion_r330180872.

If this is not necessary, it should also be removed from other SDK projects, probably. If it is necessary, it should be commented.

/cc @alexperovich

**Comment by tmat** [comment]
IIRC @natemcmaster added it so that unit test project can use the built package.
