### ISSUE TITLE
Arcades MSBuild files all say they are Apache licenses, when the project is MIT license

### ISSUE THREAD

**Issue by eerhardt** [dotnet/arcade#404]
All of our MSBuild files say

`Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.`

Example:
https://github.com/dotnet/arcade/blob/9517895d68d0ff37c75c35f9cd9545cb9122d382/src/Microsoft.DotNet.Arcade.Sdk/tools/BuildStep.props#L1

However, the root license is MIT.

We should straighten the licensing out.  It should all be MIT.

cc @tmat @markwilkie

**Comment by markwilkie** [comment]
@jcagme - note that Roslyn is Apache and Core is MIT, so please make sure we choose the correct license.  (I *think* it's MIT....but not 100% sure)

**Comment by jcagme** [comment]
Talked to @jaredpar and we are ok to move files to MIT. Will work on the PR

**Comment by jcagme** [comment]
PTAL https://github.com/dotnet/arcade/pull/415/files
