### ISSUE TITLE
[Maestro++/darc] Fix DefaultChannel lookup

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4049]
Something weird is happening in Maestro++ after latest rollout and causing it to not find default channel mappings correctly. The problem was caused after the merge [of this PR](https://github.com/dotnet/arcade-services/pull/648/files?file-filters%5B%5D=.cs) which is already [being reverted here](https://github.com/dotnet/arcade-services/pull/673) as a hot fix.

/cc @riarenas @mmitche

**Comment by riarenas** [comment]
I believe @mmitche was working on a fix, so make sure to sync up with him.

**Comment by mmitche** [comment]
@Fixed by #dotnet/arcade/674

**Comment by JohnTortugo** [comment]
Current fix is only partial. More investigation is needed. I'm un-assigning this from myself  to prioritize the servicing tests.

**Comment by mmitche** [comment]
Fixed in https://github.com/dotnet/arcade-services/pull/674

**Comment by riarenas** [comment]
Had a hiccup with this one due to some weird interactions between EF and the new computed properties that perform the normalization.

This is now working and rolled out as of 10/16
