### ISSUE TITLE
[Maestro++] Migrate Maestro subscriptions to Maestro++

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#405]
@alexperovich @jcagme Is this on the roadmap? Would be nice not to maintain both Maestro and Maestro++ forever.

**Comment by markwilkie** [comment]
Yes, this is the intended at least back to 2.x.  The plan is to let 1.x go to end of life though...

**Comment by dagood** [comment]
Why was this closed, if it's intended to happen? Is it tracked somewhere else?

**Comment by markwilkie** [comment]
Currently the scope of Maestro++ is the automation of Darc for dependency flow.  There are currently workloads in the old Maestro.  It is unclear at this time what the right migration path (if any) for those.

**Comment by markwilkie** [comment]
The assumed goal here is that we'll shut down Maestro at some point.  However, this does not necessarily imply moving to Maestro++.

**Comment by wtgodbe** [comment]
@markwilkie @mmitche @chcosta @riarenas @JohnTortugo is there any plan to do this soon? Manually disabling & re-enabling code merge jobs isn't very sustainable (see discussion in https://github.com/dotnet/versions/pull/525)
