### ISSUE TITLE
[darc/maestro++] Add scenario tests that would have caught the default channels bug

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4055]
When we rolled out on 10/2, we broke publishing.  The issue was that refs/heads was removed from the database for default channels and builds, but there is some disconnect where the arcade publishing was not correctly identifying the default channel that the branch being built should apply to.  Some of this may be related to lack of normalization in the query logic

This should have been caught by additional scenario tests which exercise the API with potential inputs. Arcade or other users may be querying for default channels with "refs/heads" prefixes on branches. The scenario tests did check for default channels with various input possibilities, but they use darc, which is not what arcade uses.

So I think we really just need additional tests against the API for valid sets of inputs.

Side note: Another possibility would be to run an actual arcade build against int and make sure that everything publishes properly.  The problem with this is that you can't use the stock arcade without jumping through a bunch of hoops.  It *could* probably be done, but it may be tough.  I think it would be better to simply beef up the API testing

**Comment by riarenas** [comment]
Rolled out on 10/16
