### ISSUE TITLE
[darc/maestro++] `darc add-dependency --name Thingy` produces broken dependency

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#4057]
Without repository or version, the dependency that gets registered doesn't work and can't be updated.

`--repository` should be required.

Also, add-dependency again (to attempt to correct the issue) creates a broken props file
```
<ThingPackageVersion>something-useful</ThingPackageVersion>
<ThingPackageVersion>
</ThingPackageVersion>
```
It replaces the good version with a... newline?

**Comment by mmitche** [comment]
@ChadNedzlek IIRC, the newline thing is an artifact of the way that the xml writer works on empty inner text, not maestro itself.

**Comment by ChadNedzlek** [comment]
That would be strange.  Usually when XmlWriter writes an empty element it writes `<a />`.  Because this element _isn't_ empty. It contains a text node that has the new line in it, which msbuild is going to see and react too appropriately.  Though honestly writing the empty element _at all_ is pretty confusing, and the fact that it doesn't replace it when adding a useful version, but preprends it before the new line element.

**Comment by riarenas** [comment]
The fix was rolled out on 10/16
