### ISSUE TITLE
BarViz spins indefinitely when trying to load a repo that does not publish to a channel

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#4059]
Repro:

* Go to https://maestro-prod.westus2.cloudapp.azure.com/2/https:%2F%2Fgithub.com%2Fdotnet%2Fcorefx/latest/graph (or to any product repo in .Net Tools - Latest).
* One of two things will happen: either a wheel will spin indefinitely, unable to load, or a message that says "unable to load" will appear.

I would expect that one of two things would happen. Either repos that do not publish to that channel should not be listed in the left panel, or we would load the page with some sort of message indicating that a repo does not publish to that channel.

**Comment by MattGal** [comment]
I believe this has been rolled out, closing.
