### ISSUE TITLE
[darc/maestro++] CPD algorithm can sometimes choose undesired versions

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4067]
For a dependency marked with a coherent parent, the version is updated to version first (shallowest) dependency found in the graph of parent target.

This sometimes leads to unexpected behavior. If dependency D has coherent parent B, and B comes from a commit where there are two separate dependencies on the repo where D comes from, and those dependencies have different commits (e.g. one is pinned), then depending on which dependency is traversed first, you could either get an old or a new version of D.

This doesn't happen in typical GA cycles because we are typically not pinning dependencies and all dependencies are revved on each build.

I think the ideal case is to choose the newest. Ideally, you'd also warn in the PR that another version could have been chosen, and indicate what that version is. The difficulty with that is that it may cause performance issues in the CPD algorithm.

**Comment by mmitche** [comment]
I've got the solution. What we really need to do is find the newest matching asset in the graph. The tough part is doing this efficiently.

Basically what needs to happen is that the algorithm, should basically work as it does today, where it notes when it finds an asset with the desired named in the graph.  But today it breaks out.  This should no longer happen. However, at that point, it should begin to prune graph traversal if the current dependency being visited was produced at a build that is **older** than the build that where the current "newest" asset was produced. Because it is impossible that you would find a newer version of the asset in any version that is older than the current version asset. This would then prune large portions of the graph.  Any time a newer version of the asset is found, the current metadata is updated and we continue onward.

**Comment by riarenas** [comment]
Was able to get a test case exhibiting this. Working on fixing now.

**Comment by riarenas** [comment]
Note: If there is a pinned CPD in the chain, we can't discard it because of being old. If a dependency is pinned, it means we explicitly want that version, even if it will eventually become the oldest version available in the graph.

**Comment by riarenas** [comment]
@riarenas still needs to finish this

**Comment by riarenas** [comment]
@mmitche fixed this in https://github.com/dotnet/arcade-services/pull/892

**Comment by riarenas** [comment]
This is rolled out now.
