### ISSUE TITLE
[darc/maestro++] Darc sometimes hangs when gathering drop

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4070]
When gathering a large drop, darc sometimes hangs. I think this happened after I added parallelism to the download process, and it may be related to thread pool starvation. I was not able to repro under a debugger when I saw this a while back.

The suggestion here is that we should add a cap on the parallelism (using a semaphore to cap the introduction of new download tasks) and an option for the maximum amount of parallelism allowed.

**Comment by riarenas** [comment]
This was rolled out on 10/16
