### ISSUE TITLE
Remove SetupNugetSources.sh/ps1 scripts

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4080]
Remove AzDO private feeds workarounds once the interaction with such feeds become stable. Need to check for the presence of these workarounds in repo/branches:

- `eng\common\SetupNuGetSources.ps1`
- Added timeouts for NuGet http handshake

**Comment by riarenas** [comment]
The code in Arcade that introduces the workarounds has a link to #3932 in its TODO for removal. Should we just keep using that issue to track any workarounds and further removal?

**Comment by riarenas** [comment]
Using #3932 to track this
