### ISSUE TITLE
GetLicenseFilePath.cs: cannot read file on linux with mono/msbuild

### ISSUE THREAD

**Issue by radical** [dotnet/arcade#4086]
Building mono/msbuild on linux (with case-sensitive filesystem) fails with: `/home/ankit/dev/msbuild/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19461.7/tools/RepositoryValidation.proj(29,5): error : No license file found in '/home/ankit/dev/msbuild/'` 

Analysis:
- msbuild on mono is built against `net472`.
- The repo (https://github.com/mono/msbuild/) has `LICENSE` file, which github requires in upper case (https://help.github.com/en/articles/adding-a-license-to-a-repository).
- [This](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/src/GetLicenseFilePath.cs#L39) is looking for `"license"` but [here it](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/src/GetLicenseFilePath.cs#L41-43) does not ignore case, which causes it to fail on Linux.

**Comment by tmat** [comment]
The fix is easy:

```
 System.IO.Directory.EnumerateFiles(Directory, "*" + extension, SearchOption.TopDirectoryOnly).Where(path => string.Equals(fileName, Path.GetFileNameWithoutExtension(path), StringComparison.OrdinalIgnoreCase));
```

**Comment by markwilkie** [comment]
@radical - feel free to open a PR so we can get it in.
