### ISSUE TITLE
[darc/maestro++] CreateAzureDevOpsFeed should sanitize the feed name before attempting to create it

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#4087]
See the failures in https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3127903

```
#[error].packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19474.3\tools\SdkTasks\SetupTargetFeeds.proj(135,5): error : Feed 'darc-pub-microsoft/msbuild-9af8dfc1' was not created. Request failed with status code BadRequest. Exception: {"$id":"1","innerException":null,"message":"The name 'darc-pub-microsoft/msbuild-9af8dfc1' isn't allowed. Name contains illegal characters.","typeName":"Microsoft.VisualStudio.Services.Feed.WebApi.InvalidFeedNameException, Microsoft.VisualStudio.Services.Feed.WebApi","typeKey":"InvalidFeedNameException","errorCode":0,"eventId":3000}
```

The error stems from here: 
https://github.com/dotnet/arcade/blob/3256926949fdd52b17017af9e9d9464cfb969705/src/Microsoft.DotNet.Build.Tasks.Feed/src/CreateAzureDevOpsFeed.cs#L85

where we use the repositoryName as is for part of the feed name. In this case, `microsoft/msbuild` breaks the rules for artifact feed naming.

We should sanitize these names so that we do not include any of the invalid characters:

`The feed name can't contain spaces, start with a '.' or '_', end with a '.', or contain any of these: @ ~ ; { } ' + = , < > | / \ ? : & $ * " # [ ] %`

Should probably be fine to simply replace any of these with a `'-'`

FYI @mmitche @JohnTortugo

**Comment by riarenas** [comment]
We have an (admittedly ugly) workaround for repos that hit this, but I think this is still urgent enough to warrant an FR label.

**Comment by mmitche** [comment]
Fix in master and then port to 3.x

**Comment by mmitche** [comment]
Working on this now
