### ISSUE TITLE
Implement retry when code-mirror fails

### ISSUE THREAD

**Issue by tkapin** [dotnet/arcade#4095]
Build [#20191010.31: Update dependencies from https://github.com/dotnet/arcade build 20191009.5 (#4091)](https://dev.azure.com/dnceng/internal/_build/results?buildId=384007) failed on step "Push changes to Azure DevOps repo".

According to @mmitche:

> I think this is a timing issue.  Between cloning the internal repo and attempting to mirror a new commit, another check-in went into the internal repo.
>
> I think the right thing to do here is probably to fetch, then retry.  The YAML for this pipeline is here: https://github.com/dotnet/arcade/blob/master/azure-pipelines-code-mirror.yml

**Comment by JohnTortugo** [comment]
@mmitche - I'm curious about why do we need to implement the retry on the YAML. Looks like the mirroring build-def is continually 're-triggered', therefore a form of retry is already in place.

Also, how are these mirroring builds started?

**Comment by mmitche** [comment]
> @mmitche - I'm curious about why do we need to implement the retry on the YAML. Looks like the mirroring build-def is continually 're-triggered', therefore a form of retry is already in place.
> 
> Also, how are these mirroring builds started? I mean, what starts the builds?

They are triggered on commit to the repo, which means if one is missed because of error, it will get picked up, but only on the next commit.

**Comment by MattGal** [comment]
@meganaquinn as you're OOF please add any updates from what you did and put in the backlog for next week.

**Comment by MattGal** [comment]
Un-assigning @meganaquinn and tossing to the backlog.

**Comment by garath** [comment]
The linked build has aged away, but going through the code-mirror history for the last two weeks I see two main types of failures from 17 failures: 

- HTTP 503 (2 times)
- Apparent dirty workspace (1 time)
- "missing commits" -- when the mirror has commits that the code-mirror doesn't  (14 times).

Of the "missing commits", the majority are from dotnet/fsharp, which has a rogue commit in the internal repo, so code-mirror should fail. The remaining are transient and just appear to be new repos onboarding. 

We can easily retry on any error. Git doesn't make it easy to differentiate network failures from invalid state failures from other failures. I'll do that first, which will hopefully cover the network errors and possibly get more info on other failures.

**Comment by MattGal** [comment]
Works for me;  I suggest adding some logging in the retry about the common reasons this fails too.

**Comment by garath** [comment]
I redid the interesting bit of the push in PowerShell and tested everything in a set of test repositories. When the logic detects that there are commits in the mirror that aren't in the public repo, it emits an error message that gets included in the build failure emails. Otherwise, a failure causes a few retries before aborting.

**Comment by MattGal** [comment]
PR is still open, please update w/ status.

**Comment by garath** [comment]
Changes were made in master. I'll resolve the conflict, double check the behavior, then merge.
