### ISSUE TITLE
[darc/maestro++] Don't automatically stage when running update-dependencies locally

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4100]
When running locally, we stage changes with `git add` just as we would in Maestro. This is not generally desirable as the user should pick and choose what should be staged before committing and pushing a branch.

**Comment by alexperovich** [comment]
Do we not have to stage them so the correct file modes are set for executable files?

**Comment by mmitche** [comment]
@alexperovich Only staging in that specific case.  Otherwise for just edits, I think it should not stage.
