### ISSUE TITLE
Building project in nuget cache breaks global.json search by msbuild sdk resolver

### ISSUE THREAD

**Issue by nguerrera** [dotnet/arcade#4102]
### Repro steps

1. `git clone git@github.com:aspnet/AspNetCore.git another`
2. `git checkout bcc962a182a273cdaa7de474528e97913373a212` (current master using 5.0 SDK)
2. `cd another`
3. `.\restore.cmd`
4. `git checkout 87a110aea8a2ba979de63a354b74e8bdeb8b280e` (current release/3.1 using 3.1 SDK)
5. `.\restore.cmd`

### Expected result
Both restores succeed

### Actual result
Second restore fails because it is trying to use 5.0 SDK that does not support targeting 3.1 (yet)

```
D:\Src\another\.dotnet\sdk\5.0.100-alpha1-014696\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(262,5): error NETSDK1073: The FrameworkReference 'Microsoft.NETCore.App' was not recognized [D:\Src\another\eng\tools\RepoTasks\RepoTasks.csproj]
```

This happens because arcade builds a project file in the nuget cache and not the repo, so the search for global.json starts in the wrong place, and the global.json specifying 3.1 SDK is not respected.

```
Tracing enabled @ Thu Oct 10 22:54:53 2019 GMT
--- Invoked hostfxr_resolve_sdk2 [commit hash: dfb28413477684834589b8b23492b48c43726e10]
Probing path [C:\Users\nicholg\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19462.4\tools\global.json] for global.json
Probing path [C:\Users\nicholg\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19462.4\global.json] for global.json
Probing path [C:\Users\nicholg\.nuget\packages\microsoft.dotnet.arcade.sdk\global.json] for global.json
Probing path [C:\Users\nicholg\.nuget\packages\global.json] for global.json
Probing path [C:\Users\nicholg\.nuget\global.json] for global.json
Probing path [C:\Users\nicholg\global.json] for global.json
Probing path [C:\Users\global.json] for global.json
Probing path [C:\global.json] for global.json
Terminating global.json search at [C:\]
Resolving SDKs with version = 'latest', rollForward = 'latestMajor', allowPrerelease = true
Searching for SDK versions in [D:\Src\another\.dotnet\sdk]
Version [3.1.100-preview1-014400] is a better match than [none]
Version [5.0.100-alpha1-014696] is a better match than [3.1.100-preview1-014400]
SDK path resolved to [D:\Src\another\.dotnet\sdk\5.0.100-alpha1-014696]
```

I think the ~~build.proj~~ tools.proj should be moved to eng\common or it should not import any SDKs.

cc @dougbu

**Comment by markwilkie** [comment]
Interesting.  Adding a few more folks who will care as well.

@mmitche , @alexperovich , @tmat

**Comment by tmat** [comment]
:(

Why is global.json searched at all for build.proj - this is not an SDK project (it doesn't import any SDKs). Shouldn't global.json only be searched for projects that import SDKs and be based on their location?

**Comment by nguerrera** [comment]
https://github.com/dotnet/arcade/blob/8cd48078f550fbcbd4f684b897b14db207397b52/src/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj#L2

**Comment by nguerrera** [comment]
Looks like it's tools.proj that imports Microsoft.NET.Sdk

The first project to import an SDK will look for global.json. We don't do it over and over again for every sdk lookup as that would be very expensive, there are at least two per project.

It is basically undefined behavior if you have global.json above some projects but not others in the same build invocation.

**Comment by nguerrera** [comment]
If we can remove the sdk import from the projects that are in nuget cache, it would work. But there is at least one project in nuget cache that imports the sdk, and that is the problem.

**Comment by dougbu** [comment]
Is there a workaround I can recommend to the ASP.NET Core team while this bug is investigated and resolved?

**Comment by nguerrera** [comment]
I think the only workaround is to delete the newer sdk from .dotnet\sdk\ if you switch to branch that uses older sdk.

**Comment by nguerrera** [comment]
I think a cheap (slightly hacky) fix would be to have a stub build.proj in eng\common that imports build.proj from nuget dir and build that instead of nuget dir proj directly.

**Comment by tmat** [comment]
We should revisit tools.proj. Not sure right now why it needs SDK.

**Comment by tmat** [comment]
> The first project to import an SDK will look for global.json. We don't do it over and over again for every sdk lookup or project as that would be very expensive.

If we can rely on this as a documented behavior then I think the fix is simple.

`Tools.proj` is used to restore packages needed for the outer build (like signing, symbol upload, etc). 

Currently we restore `Tools.proj` first and then restore the repo's solution. If we reorder this to restore solution first it would fix the issue, correct?

**Comment by nguerrera** [comment]
Will the fix for this roll out to 3.0/3.1 branches or only 5.0? People are reporting it against there 3.x branches

**Comment by tmat** [comment]
@nguerrera It's in 5.0 right now. https://github.com/dotnet/corefx/pull/41832 would need to be ported to 3.x if we were to port it.

@markwilkie

**Comment by nguerrera** [comment]
I believe it's high value and low risk and should be ported. It specifically impacts switching from 5.0 to 3.x branch so that experience won't be fixed until we port it.

**Comment by markwilkie** [comment]
This makes sense to me.  Is this a similar pattern that other repos should be following?  (wondering if it's worth normalizing across repos)

Regarding moving to 3.x, that's @danmosemsft 's call.  (it's infra, so it's tell to tactics)

**Comment by tmat** [comment]
@markwilkie Not sure what you mean by

>  Is this a similar pattern that other repos should be following? (wondering if it's worth normalizing across repos)

The issue is with building project files located in a package, which is pretty specific to Arcade SDK.

**Comment by markwilkie** [comment]
Are there other repos w/in .net core which restore tools first? (or some other proj which has the same effect) 

Likely this is fine....but want to reduce as many land-mines as we reasonably can.

**Comment by tmat** [comment]
I see what you mean. IDK.
