### ISSUE TITLE
Helix SDK failing to post test results to azure devops

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#4113]
Seeing various reports of failures when POSTing test runs to the URL: https://dev.azure.com/dnceng/public/_apis/test/runs?api-version=5.0-preview.2

which is manifesting in 503 errors:

```
F:\workspace\_work\1\s\.packages\microsoft.dotnet.helix.sdk\2.0.0-beta.19463.3\tools\azure-pipelines\AzurePipelines.MultiQueue.targets(16,5): error : Request to https://dev.azure.com/dnceng/public/_apis/test/runs?api-version=5.0-preview.2 returned failed status 503 Service Unavailable [F:\workspace\_work\1\s\tests\helixpublishwitharcade.proj]
F:\workspace\_work\1\s\.packages\microsoft.dotnet.helix.sdk\2.0.0-beta.19463.3\tools\azure-pipelines\AzurePipelines.MultiQueue.targets(16,5): error :  [F:\workspace\_work\1\s\tests\helixpublishwitharcade.proj]
F:\workspace\_work\1\s\.packages\microsoft.dotnet.helix.sdk\2.0.0-beta.19463.3\tools\azure-pipelines\AzurePipelines.MultiQueue.targets(16,5): error : {"$id":"1","innerException":null,"message":"TF10216: Azure DevOps services are currently unavailable. Try again later. Activity Id: 492fec1d-55ee-47f2-8853-0f26bdefb63d","typeName":"Microsoft.VisualStudio.Services.CircuitBreaker.CircuitBreakerShortCircuitException, Microsoft.VisualStudio.Services.Common","typeKey":"CircuitBreakerShortCircuitException","errorCode":0,"eventId":3000} [F:\workspace\_work\1\s\tests\helixpublishwitharcade.proj]
##[error].packages\microsoft.dotnet.helix.sdk\2.0.0-beta.19463.3\tools\azure-pipelines\AzurePipelines.MultiQueue.targets(16,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Request to https://dev.azure.com/dnceng/public/_apis/test/runs?api-version=5.0-preview.2 returned failed status 503 Service Unavailable
```

Code is here:https://github.com/dotnet/arcade/blob/64a027b8d8b3a8e8e214bb00da02148335e3bd92/src/Microsoft.DotNet.Helix/Sdk/StartAzurePipelinesTestRun.cs#L26

**Comment by riarenas** [comment]
I'm having trouble accessing that API too, even just to list any test runs in the public project.

According to https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops
> Once an API is released (1.0, for example), its preview version (1.0-preview) is deprecated and can be deactivated after 12 weeks.

So maybe we are just trying to post to a deactivated version?
We have started a conversation with Azure devOps about this.

**Comment by riarenas** [comment]
Whoever takes a look at this, a quick test would be to stop using the 5.0-preview.2 api version and use the 5.0 release version.

**Comment by Chrisboh** [comment]
There was an issue with the Azure DevOps API which they identified and mitigated around 7:30 this morning.  If you still are seeing any issues with this let me know and I will pass that along.

**Comment by riarenas** [comment]
We believe this is now resolved. Feel free to reopen if you still see the issue.

**Comment by ViktorHofer** [comment]
Thanks for the info. Should we nevertheless switch to the non preview api endpoint?

**Comment by ViktorHofer** [comment]
Thanks
