### ISSUE TITLE
[PKPIs] Update Official Build Time report to used BuildChannel insert time as end time

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#4116]
Once we record the insert time for BuildChannel, we need to update the power bi report to use that instead of timeline build end time as the finish time.

**Comment by chcosta** [comment]
@adiaaida , what's the timeline on this?  We need to pivot the results to this view before we can start sharing data with teams'

**Comment by adiaaida** [comment]
I've got the code worked up in Maestro right now (https://github.com/dotnet/arcade/issues/4115). I'm testing it now, and should have a PR up in an hour or two. Once we rollout, we'll be able to start using it.
