### ISSUE TITLE
Stop using the 5.0 preview AZDO APIs

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#4126]
In several places, both in Arcade, and in Arcade services, we are still using the AZDO 5.0 preview APIs.

According to https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops

> Once an API is released (1.0, for example), its preview version (1.0-preview) is deprecated and can be deactivated after 12 weeks.

None of the APIs have been deactivated thus far, but we should prepare for this possibility by moving to the 5.0 release version.

**Comment by riarenas** [comment]
[This naive query](https://github.com/search?l=&p=1&q=preview.+repo%3Adotnet%2Farcade+repo%3Adotnet%2Farcade-services+repo%3Adotnet%2Farcade-validation+extension%3Acs+extension%3Ash+extension%3Aps1&ref=advsearch&type=Code) is a good start to find our usage of the preview apis

**Comment by ChadNedzlek** [comment]
5.0 isn't released yet. :-)

**Comment by riarenas** [comment]
5.0 is released, but not all the APIs from the previews may have made it in the way we were using them, which is what I suspect happened in Arcade-Services

**Comment by ChadNedzlek** [comment]
The error message is pretty clear that 5.0 is still preview.  Maybe some of the API's are still stuck in preview?  Or maybe they've only partially released 5?

Unfortunately, we delegate everything through the same layer, so we can't really do partial versions.  We expect the same version on every API.

**Comment by riarenas** [comment]
To re-introduce the change in arcade-services, we will want to make sure to run the scenario tests locally:

1. Run the Maestro application locally
1. Get a BAR token for your local maestro application from wherever it's running (usually https://localhost:4430)
1. Get a GitHUB (repo scope) and AzDO (code r+w, build r+w+r scope) PAT
1. Request access to the https://github.com/maestro-auth-test org
1. Run the AZDO powershell scenario tests (they are the most comprehensive right now). All tests that start with azdo from here https://github.com/dotnet/arcade-services/tree/master/src/Maestro/tests/Scenarios:
```test-to-run.ps1  -maestroInstallation "https://localhost:4430" -darcVersion 1.1.0-beta.20230.1 -maestroBearerToken <BAR TOKEN> -githubPAT <GH PAT> -azdoPAT <AzDO PAT>```

**Comment by ChadNedzlek** [comment]
Sounds like yet another IcM for Azure Dev Ops.  That documentation is very clear 5.0 is released, but the service is also very clear that it is is not.

**Comment by riarenas** [comment]
My bet is not all APIs made it out of preview, so if we need to make the port, we'll need to find what they actually are in 5.0 release, or move them to 5.1 preview.

**Comment by lukas-lansky** [comment]
There are definitely parts of the API that working smoothly with `5.0`. Let me check.

**Comment by lukas-lansky** [comment]
Sorry, nothing much to add here. Moving to 5.1 preview makes sense, but I'm afraid to touch the codebase. Ricardo's description of what needs to be done to run scenario tests locally helps a lot here though, I didn't have that before.

**Comment by epananth** [comment]
@riarenas had to revert this change cos azdo-all-checks-successful test did not pass in staging. Investigating this change.

**Comment by epananth** [comment]
Found the API which still requires Azdo preview 5.0. 

PR -> https://github.com/dotnet/arcade-services/pull/1172
