### ISSUE TITLE
[darc/maestro++] BarViz coherency display produces false negatives

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4144]
The coherency metric on BarViz is overly conservative. It was basically correct for .NET Core 3 during the main release, because every repository in the graph built every possible package.  Now that we are in the servicing timeframe, repositories are not producing every package on every build.

This basically means that two versions of corefx, for instance, can be referenced in core-setup. If Microsoft.NETCore.Platforms is not being revved, then it might be pinned, or simply not update.

This is necessarily not a problem. It does not necessarily mean that core-setup is incoherent. From the Maestro standpoint, there can be no overlapping assets in the Version.Details.xml file. This does not mean it *couldn't* be incoherent.  Consider:
- core-setup depends on binaries A and B from corefx, and B from corefx depends on A from corefx.
- If A but not B is revised for an upcoming servicing release and is now coming from a different build, then technically there could be incoherency (since B still depends on old A), but whether there actually is a problem is heavily dependent on product behavior (will B simply pick up the new A, etc.)

This means we need to revise our incoherency check in BarViz so that incoherency is calculated based on conflicting input dependencies and not conflicting repo+shas. A build is incoherent if the graph contains multiple versions of the same input dependency. Thus:
- A repository **cannot** be directly incoherent. Taking assets from two diffferent builds of an input repository is not a problem. Since the Version.Details.xml file cannot mention the same asset twice, it is not possible for build to be directly incoherent.
- A repository **can** be indirectly incoherent if the graph underneath it contains multiple versions of a specific input dependency, regardless of what repo or sha they were built at.

**Comment by ChadNedzlek** [comment]
It was probably me, long ago.  It's just a recursive SQL query under the covers.

**Comment by mmitche** [comment]
I think this will require some changes in the Maestro push tasks, which currently only record the input builds.

**Comment by mmitche** [comment]
> @mmitche Do you see this as required to make sense of .NET 5, or more of an improvement?

I think it's required to make sense of any servicing release. So not needed for .NET 5 right now, but needed for 3.

**Comment by riarenas** [comment]
Makes sense. Keeping it in the current epic then
