### ISSUE TITLE
[darc/maestro++] Maestro/darc not updating System.Diagnostic.DiagnosticSource

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4155]
https://github.com/aspnet/AspNetCore-Tooling/pull/1256/files

Note that this does work in aspnet/extensions.

**Comment by riarenas** [comment]
From my debugging:

* Whichever asset that has a `Microsoft.NETCore.App.Runtime.win-x64` is listed first in the dependencies section will get an incorrect version pulled in. Just so happens that it's `System.Diagnostic.DiagnosticSource` which is getting the incorrect 4.6.0 version.
* When building the dependency graph for that first dependency, we will introduce a build of the release/3.0 branch of corefx, which brings in the incorrect version.
* For any subsequent assets, the dependency graph is populated with more builds, and the incorrect corefx build gets visited after the correct build.

I believe this is related to https://github.com/dotnet/arcade/issues/4067, and I'm working on modifying the CPD algorithm to get the right dependency versions.
In parallel I'm trying to find if any ordering of the dependencies makes the algorithm do the right thing today. This would allow aspnetcore-tooling to work around the bug without any tooling changes, as a fix to the algorithm will require a rollout.

**Comment by riarenas** [comment]
Haven't been able to find any permutation of the dependency order that makes this update work as expected, so we will definitely need tweaks in the CPD algorithm to fix this instance.

**Comment by mmitche** [comment]
It's that extensions had Microsoft.Bcl.AsyncInterfaces (a pinned dependency) listed first.

I've resolved it for now, and things look good.  We still need a resolution as part of https://github.com/dotnet/arcade/issues/4067, but it's not blocking at the moment.
