### ISSUE TITLE
Transient failure in Publish Assets

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4161]
While executing a test build a publishing job failed due to what looks like a transient failure (Retry of the job succeeded):

- [This is the build/job that failed](https://dnceng.visualstudio.com/internal/_build/results?buildId=395883&view=logs&j=4c4bf07a-940d-50a5-ff36-fba77abc096a&s=d1c62061-e9a9-50af-e8b0-2679778e4057&t=a1552aa5-1086-5087-6342-0f8cee9da72b&l=530)
- [This is the code region involved](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifest.cs#L780)

Seems that the NuGet push failed for some reason. Perhaps we should add some retries & more logging around that code to help in the future.

/cc @mmitche @riarenas

**Comment by riarenas** [comment]
Closing as this doesn't seem to happen a lot. We can revisit if it becomes a problem
