### ISSUE TITLE
Update documentation for local Helix debug best practices

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4165]
We need to better guidance on how to manage to secrets when locally debugging the Helix API. Specifically, there should be guidance on how to deal with secrets so that they are less likely to be inadvertently committed to the repo and pushed.

**Comment by riarenas** [comment]
Since this is helix service specific, do you want to keep this issue here, or does it overlap with https://github.com/dotnet/core-eng/issues/8126?

**Comment by mmitche** [comment]
Oh, that was the issue I was originally looking for.
