### ISSUE TITLE
Explore what it would take to start with a known state

### ISSUE THREAD

**Issue by andresff** [dotnet/arcade#4167]
To put in context.. this issue is triggered by the solution described in #4154. After some messages back and forth with @tmat, @dougbu and @markwilkie, they comes to the conclusion that there is a need to know what would be the state before run a **build**, to validate and comply with it, and to fail with a known error/good error message to take action on it.

Something to verify could be:
- Environment variables to delete (e.g. in my case **Platform**)
- Some right on some resources (e.g. write permission on X folder)
- Some Privilege user account

**Comment by tmat** [comment]
> Environment variables to delete (e.g. in my case Platform)

I think we should delete all env variables in build.ps1|sh. All parameters to the build should be passed via explicit `/p:X=Y` property or `-xyz` switch.

**Comment by dougbu** [comment]
> I think we should delete or explicitly set all env variables in build.ps1|sh before we invoke msbuild.

This will cause security issues unless we have an escape mechanism to allow all security tokens used in a build to remain available from the environment. Putting any token, password, or similar credential into a command line or response file is a **Bad Idea:tm:**

**Comment by tmat** [comment]
@dougbu I'm not sure I understand the issue. We already pass tokens like that:
https://github.com/dotnet/arcade/blob/9f3ff5b755c3a0ecd4627731aa1015aab4eac15b/eng/common-variables.yml#L33

**Comment by dougbu** [comment]
In that particular case, AzDO is smart enough to hide the token as seen in a recent Arcade build https://dev.azure.com/dnceng/internal/_build/results?buildId=396282&view=logs&j=fa59fe4e-195c-56fa-189b-58fd241f10dd&t=afa1ce5e-d2bc-56f3-ad78-7883f25a3e3a&l=11 But, that should not be relied upon.

**Comment by markwilkie** [comment]
On a seperate thread it was discussed having a set of "blessed" env variables and clearing all but those on every build.  This seems like a reasonable approach to me.

In addition, we're actively exploring using docker more widely.  This also would give a "clean slate" - but unfortunately is not applicable in all scenarios.

**Comment by markwilkie** [comment]
There are other discussions too about dealing with env vars in a better way (including better validation).  It seems however, that this issue has run its course.
