### ISSUE TITLE
Arcade allows build to pass as green even when target shows error and build output is corrupted

### ISSUE THREAD

**Issue by jmarolf** [dotnet/arcade#4183]
In [this](https://dev.azure.com/dnceng/internal/_build/results?buildId=398126) build I get the following error:

```
##[error].packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19521.4\tools\VisualStudio.InsertionManifests.targets(23,5): error : Property VisualStudioDropName must be specified in official build that produces Visual Studio insertion components.
```

Yet the build passes. This will cause the build output to be invalid and should fail the build

**Comment by markwilkie** [comment]
@riarenas - do you remember the deal here?

**Comment by riarenas** [comment]
Looks similar to some issues from a month back. I'll take a look.

**Comment by dagood** [comment]
I wonder if this is https://github.com/microsoft/msbuild/issues/3345?

That target "hangs off" the build using `AfterTargets` so errors in there may not fail the all-up build:

https://github.com/dotnet/arcade/blob/894bd005267af53f7d39ac988881e61193e67ae1/src/Microsoft.DotNet.Arcade.Sdk/tools/VisualStudio.InsertionManifests.targets#L12-L13

**Comment by riarenas** [comment]
Does look related. All our previous instances of something like this were in the powershell side, but that was not the case here. Thanks Davis.

**Comment by riarenas** [comment]
Yeah, definitely related. This is exactly the same issue described in #3418 
Doesn't look like we got resolution there.

**Comment by dagood** [comment]
I sympathize with MSBuild's interpretation of "Build Successful", but yeah, throws an ugly wrench in a *lot* of code.

**Comment by tmat** [comment]
I get the interpretation, but I think the current behavior is incorrect and inconsistent with a common sense rule "if a task runs and it fails the build should fail".
I'd be fine if msbuild chose not to run these AfterTargets at all. But running them and ignoring their failure is imo wrong.

Nevertheless, I have been fixing these cases. I guess there are some more left.

**Comment by riarenas** [comment]
The error is understood. Using `AfterTargets` here causes the errors in msbuild to be swallowed.

Going to pass this off to FR so someone can fix the target chaining here to something that will actually failed the build. (It looks like using `BeforeTargets` or `DependsOnTargets` doesn't get hit by the bug.

**Comment by MattGal** [comment]
@rainersigwald  any suggestions on how best to address this?

**Comment by rainersigwald** [comment]
Generally, hook `BeforeTargets` the rollup target, rather than `AfterTargets` it. That look perfectly cromulent for `Pack` in this case.

**Comment by MattGal** [comment]
@Tohron if this is merged, can it be closed?
