### ISSUE TITLE
[Validation] Enable VSTS YAML build definition testing

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/arcade#419]
@chcosta commented on [Thu Aug 02 2018](https://github.com/dotnet/core-eng/issues/3998)

In addition to having documentation for creating VSTS YAML official builds in the .NET Core 3 ecosystem, we should have tests that you can run against a build definition before using it to catch any issues product teams need to fix.

**Comment by markwilkie** [comment]
I haven't heard much about this still being a thing, so am closing.  (but feel free to reopen of course)
