### ISSUE TITLE
Rework arcade feeds and channels to enable a dotnet-tools feed

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4197]
There is a need for a generic channel for non core-version specific components. For example:
- vstest
- Sourcelink

the most obvious place for these today would be a .net tools channel, but we already have arcade pushing to dotnet-tools and a '.NET Tools channel".  We should change this around:

- Rename feed dotnet-tools -> dotnet-eng
- New feed dotnet-tools for .net core tooling
- New channels ‘.NET Tools Dev’ and '.NET Tools Release' for .net core tooling.
- Rename channel .NET 3 Tools -> .NET 3 Eng
- Rename channel .NET 3 Tools - Validation-> .NET 3 Eng- Validation
- Rename channel .NET Tools – Latest -> .NET Eng - Latest
- Rename channel .NET Tools – Validation -> .NET Eng - Validation

I think, for the most part, that the channel names can simply be changed.  There is only one place in arcade-validation that uses the channel by name:

- https://github.com/dotnet/arcade-validation/blob/master/eng/validation/update-channel.ps1#L5
- https://github.com/dotnet/arcade-validation/blob/release/3.x/eng/validation/update-channel.ps1#L5

In addition, the display names of the publishing templates should be updated

**Comment by tmat** [comment]
@markwilkie @mmitche What's the ETA for this change? I'd like to set up proper Source Link publishing, so that we can flow Source Link automatically to our repos and customers can get the latest from ADO, rather then MyGet.

**Comment by mmitche** [comment]
> @markwilkie @mmitche What's the ETA for this change? I'd like to set up proper Source Link publishing, so that we can flow Source Link automatically to our repos and customers can get the latest from ADO, rather then MyGet.

I'll come up with a plan by EOW and execute on it early next week. It's a bit of a risky change that has a possibility to be disruptive if not done right,.

**Comment by tmat** [comment]
Sounds good. Thanks!

**Comment by mmitche** [comment]
Plan to implement this, with the intention of it being a seamless transition.
1. Create dotnet-eng feeds
2. Push all packages from dotnet-tools into dotnet-eng.
3. Create a PR to arcade master that updates the tools channels templates to push to dotnet-eng instead of dotnet-tools. PR should also update the display names of publishing steps.  Changing the stage names is not recommended.
4. Merge PR from step 1
5. Trigger an arcade update and react in repos by replacing use of dotnet-tools with dotnet-eng
6. Port PR from master to release/3.x and repeat steps 2-5.
7. Prepare a PR to arcade-validation master that changes the channel name of the promoted build to new .NET Engineering - Latest channel.
8. Merge PR and rename channel
9. Do same in release/3.x branch of arcade-validation

**Comment by mmitche** [comment]
@tmat Initial bit of this change is in PR

**Comment by ViktorHofer** [comment]
@mmitche is the dotnet-tools feeds already good to use? Asking for VSTest and SourceLink (cc @tmat).

**Comment by mmitche** [comment]
We can manually push packages to it for now, but I am still working on enabling the channels that automatically publish to it.

**Comment by ViktorHofer** [comment]
Thanks for the update, we are good for now.

**Comment by mmitche** [comment]
The tools feed is now in place for the servicing branch in arcade, Next step is to flow to all the repos.

**Comment by tmat** [comment]
@mmitche Would Maestro update NuGet.config files in all repos to include dotnet-tools and dotnet-eng feeds?

**Comment by tmat** [comment]
Also, can we clean up dotnet-tools feed - move previously published packages to dotnet-tools?

**Comment by mmitche** [comment]
> @mmitche Would Maestro update NuGet.config files in all repos to include dotnet-tools and dotnet-eng feeds?

No, I don't want to flow additional non-specialized feeds. That said, it's been updated in everywhere in the main stack.

> Also, can we clean up dotnet-tools feed - move previously published packages to dotnet-eng?

No, we cannot. We will break old builds of repos if we do so, including builds we have actually shipped.

**Comment by tmat** [comment]
> No, we cannot. We will break old builds of repos if we do so, including builds we have actually shipped.

Hmm. That's unfortunate. The intention was to make this feed "customer facing". So now the customers will see bunch of old internal packages there. Is it possible to at least hide them (unlist like on NuGet.org), or is that not a supported feature?

**Comment by tmat** [comment]
> No, I don't want to flow additional non-specialized feeds. That said, it's been updated in everywhere in the main stack.

Roslyn doesn't have it. https://github.com/dotnet/roslyn/blob/master/NuGet.config

**Comment by mmitche** [comment]
> > No, we cannot. We will break old builds of repos if we do so, including builds we have actually shipped.
> 
> Hmm. That's unfortunate. The intention was to make this feed "customer facing". So now the customers will see bunch of old internal packages there. Is it possible to at least hide them (unlist like on NuGet.org), or is that not a supported feature?

Yeah I think we can hide them.

**Comment by mmitche** [comment]
> > No, I don't want to flow additional non-specialized feeds. That said, it's been updated in everywhere in the main stack.
> 
> Roslyn doesn't have it. https://github.com/dotnet/roslyn/blob/master/NuGet.config

Roslyn master has an ancient version of arcade, I think.

**Comment by mmitche** [comment]
> > > No, we cannot. We will break old builds of repos if we do so, including builds we have actually shipped.
> > 
> > 
> > Hmm. That's unfortunate. The intention was to make this feed "customer facing". So now the customers will see bunch of old internal packages there. Is it possible to at least hide them (unlist like on NuGet.org), or is that not a supported feature?
> 
> Yeah I think we can hide them.

Yeah you can unlist. Feel free to do so.
