### ISSUE TITLE
dotnet-maestro merged a dependency PR without running CI

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/arcade#4204]
https://github.com/dotnet/wpf/pull/2105 was merged automatically without CI running. What happened was:

- Another PR, https://github.com/dotnet/wpf/pull/2113, contained the same changes to the versions files, and was merged into release/3.1
- I merged release/3.1 into https://github.com/dotnet/wpf/pull/2105, making it a no-op PR
- The bot immediately merged it

This seems wrong. I've seen other no-op dependency PRs that weren't auto-merged - any idea what happened here? CC @mmitche @riarenas @JohnTortugo @dotnet/dnceng

**Comment by dagood** [comment]
IIRC this happens when the subscription is missing `ignoreChecks`, and a check turn green before AzDO even starts running. That means Maestro++ sees "all checks are green", and it merges the PR.

I'm not familiar with the `auto-merge.config.enforce` CI that's showing up on that PR... know what that is?

**Comment by mmitche** [comment]
Yeah, what it is is that automerge.enforce (whatever that is) is not in the ignored checks by default. It has no way to know the difference between auto-merge.config.enforce being an interesting CI check

**Comment by mmitche** [comment]
What I'm going to do is add the additional checks to the standard list of ignored checks.  If we see this happen again (this is the first time), I'll modify and add a new DB table so that we don't need a rollout to actually fix this in the future.
