### ISSUE TITLE
Add functionality to Helix JobSender SDK to support .tar

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#4206]
Because .tar preserves file metadata that is otherwise lost in .zip files, we would like to teach the Helix SDKs in Arcade how to make .tar (or possibly tar.gz).  Helix Clients already know how to unpack such archives, so the only challenge is making sure the files are properly generated (any mismatch in the manifest of an archive and the unpacked file can cause errors in the client) and included in job lists.

There don't seem to be existing C# libraries (* I did minimal searching) that would work on core for creating .tar files, but all of the places we build (Windows RS5+, OSX, Linux) have tar on the path, so we could simply use shell-exec on such things to do this.  I'd expect this would be most used on builds performed in Posix-based systems since on Windows these metadata elements aren't there.

@wli3 , @johnbeisner  FYI.  SDK team needs this functionality to support testing on Helix, but they are going to also investigate ways to work around this while the functionality is not built in.

**Comment by markwilkie** [comment]
@wli3 - is this still a requirement?

**Comment by wli3** [comment]
Not a requirement. But this logic should be in Helix jobsender. We have custom code in SDK is the wrong place
