### ISSUE TITLE
Where to set build architecture in Arcade?

### ISSUE THREAD

**Issue by omajid** [dotnet/arcade#4209]
Over at another issues (https://github.com/dotnet/core-sdk/pull/4102#discussion_r339253751) I was told that arcade handles all the build architecture stuff for .NET Core projects:

> The 'Architecture' logic is handled in Arcade; defaults, et al - I don't feel that this is the correct place for this, or if it should be included at all.

I tried looking for this code in arcade it, but couldn't find any obvious answer. Anyone know how I can find this code that sets up architecture related stuff for consuming projects in arcade?

Additionally, does that mean projects where they are setting up architecture need fixing? I am looking at code like:

https://github.com/dotnet/corefx/blob/cf28b7896a762f71c990a5896a160a4138d833c9/Directory.Build.props#L59-L62

**Comment by markwilkie** [comment]
Is this helpful by any chance?  https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md

If not, what are you trying to do specifically and we can certainly help.

**Comment by dagood** [comment]
I believe it isn't correct that Arcade handles build and target arch. This was a challenge in the Arcade onboarding process for core\*, and we decided not to try to standardize it (and I believe this means Arcade has continued not to have a default implementation). This is one of the road bumps that's come up in core\* repo consolidation, that everyone has handled it differently.

---

Another way to look at this is how Core-SDK targets e.g. win-x86. In CI, x86 shows up here in the build matrix:

https://github.com/dotnet/core-sdk/blob/4330dfdf747c0e8e57a43328a1ddcaaac453589e/.vsts-ci.yml#L37

which is passed to build.cmd as `-Architecture $(_BuildArchitecture)`

https://github.com/dotnet/core-sdk/blob/4330dfdf747c0e8e57a43328a1ddcaaac453589e/eng/build.yml#L64

which is directed to `run-build.ps1`, which translates it to `/p:Architecture=$Architecture`:

https://github.com/dotnet/core-sdk/blob/4330dfdf747c0e8e57a43328a1ddcaaac453589e/run-build.ps1#L17

which is used by the build infra (a line your PR touches!):

https://github.com/dotnet/core-sdk/blob/fe0f103694e2eade6a98476ae858de5518669bf8/src/redist/targets/GetRuntimeInformation.targets#L16

Arcade isn't involved at any point if I followed it right.

**Comment by omajid** [comment]
That makes sense to me. Should I close this issue and continue my efforts to add `Architecture` to arcade?

**Comment by dagood** [comment]
> That makes sense to me. Should I close this issue and continue my efforts to update `Architecture` in ~arcade~ core-sdk?

In my opinion, yep. @johnbeisner, do you have any feedback on this issue?

**Comment by omajid** [comment]
All my concerns have been resolved, so I am going to close this issue now. Please feel free to re-open if anyone has any outstanding questions.
