### ISSUE TITLE
Improve diagnostics of Service Fabric

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/arcade#421]
For context, during our triage meeting we talked about improving the diagnostics of Service Fabric so we can understand and debug it better.
We also decided to put it in the Flow epic so as part of the Maestro++ work we could identify, modify and set a pattern for the other Service Fabric we have.

@MattGal could you help here providing a list of the things we should consider?

**Comment by jcagme** [comment]
@Chrisboh, what's the expected output of this issue?

**Comment by Chrisboh** [comment]
@MattGal had some ideas around what we should do here to improve the debugging.  I will defer to him on what those things are.

**Comment by MattGal** [comment]
I actually already opened a really similar issue at Mark's behest a while back.  ANyways something like this:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-report-health, and then add health checks to the SF apps.  Something that allows the app to report excessive unhandled exceptions, the inability to load anything from Key Vault, etc as unhealthy.  This would provide us a more believable health status (

**Comment by markwilkie** [comment]
Closing in favor of https://github.com/dotnet/core-eng/issues/3594
