### ISSUE TITLE
VSTS: create Win7 and Win8 images

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/arcade#423]
@natemcmaster commented on [Tue Jul 31 2018](https://github.com/dotnet/core-eng/issues/3973)

We want to move the <https://github.com/aspnet/IISIntegration> repo to build completely on VSTS. Before we can do so, we would like to ensure we keep test coverage for Win7 and Win8. How can we go about creating agents for these OSes for https://dotnet.visualstudio.com? Ideally, we'd have them available for PR validation and official builds.

cc @jkotalik @pakrym

**Comment by natemcmaster** [comment]
I'm not sure why this issue got moved to Arcade. @markwilkie @chcosta can you help route this? While we're waiting for VSTS improvements, I'm okay if we use devdiv.visualstudio instead for win7/win8 testing.

**Comment by chcosta** [comment]
I'll leave this here for now so we can remember to address it when BYOC becomes available in dotnet.visualstudio.com.

**Comment by chcosta** [comment]
@ChadNedzlek can I close this?  Is this basically being addressed by https://github.com/dotnet/core-eng/issues/4106 and other OS Onboarding work?

**Comment by natemcmaster** [comment]
The guidance we have been given is to use Helix.

Closing as we'll do that eventually in aspnet. No work necessary from arcade.
