### ISSUE TITLE
Investigate NuGet.Common load errors in Microsoft.DotNet.Build.Tasks.Feed

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#4235]
As seen in the two most recent master builds here:
https://dev.azure.com/dnceng/internal/_build/results?buildId=407363

(Previous successful build: https://dnceng.visualstudio.com/internal/_build/results?buildId=406382)

Seems to be correlated with the migration from Arcade SDK 5.0.0-beta.19528.5 -> 5.0.0-beta.19529.9

Given the symptoms it would seem either we've already loaded a copy of Nuget.Common with a different fusion name (fairly common source of this type of problem) or the assembly itself was not restored and thus is not load-able. 

@rladuca  FYI.

**Comment by MattGal** [comment]
Skimming the logs, I think it was this commit: https://github.com/dotnet/arcade/commit/5a666a2e3e7eadfd61ca34a0003630103a0486b0 ... where something likely loaded the 4.9 version of this Nuget.Common already in the build process, making it  unable to load 5.3 of it.  (@ericstj  / @mmitche  FYI)

**Comment by rladuca** [comment]
FYI @vatsan-madhavan

**Comment by mmitche** [comment]
This also means that release/3.x is almost certainly broken for at least some repos

**Comment by ericstj** [comment]
So I took the dependency on the latest nuget knowing that it would cause these problems, but I also asserted that folks *must* be using 3.0 RTM or later in order to use Arcade.  It looks like some repos are on some early builds of 5.0 that have older copies of NuGet than 3.0 RTM: seems like something we ought to sort out @nguerrera @livarcocc.  If folks think that sorting is going to take a long time I'm OK with a temporary revert.  I could call this API through reflection if folks want to, but I'd just as soon use the break as a forcing function to get the product on 3.0 or latest bits...

**Comment by vatsan-madhavan** [comment]
@rladuca we should move to a newer version if we can. Certainly for 5.0, possibly for 3.1 also.

**Comment by MattGal** [comment]
Looks like servicing branches should be on 3.0.100 right now and prod should be on >= 5.0.100-alpha1-014915.  I'm sending a partners mail about this and will keep it open until affected branches are unblocked.

**Comment by vatsan-madhavan** [comment]
This affects 3.0 branches too, does it?

**Comment by MattGal** [comment]
Yes it may if you're below 3.0.100 on them; just update if so.

**Comment by vatsan-madhavan** [comment]
Even if we are below, I don’t understand the value of this churn in 3.0. I don’t want the ‘value’ here to be defined as a reactive fixup to a build-breaking change somewhere else, please. For 3.0, I think we should start with the assumption that everyone will not react to fixup - rather the build-breaking change ought to be reverted/redesigned etc. I just don’t like the idea of an unplanned change to servicing branches.

**Comment by mmitche** [comment]
@vatsan-madhavan For 3.0 branches, everyone should be on 3.0.100. This was part of the branding shift to 3.0 servicing.  This was planned and happend for I think basically all repos except coreclr and wpf (see current in flight wpf PR https://github.com/dotnet/wpf/pull/1955).  Wpf held off for VS reasons and missed the 3.0.1 window.  Once 3.0.1 finalizes we'll merge this.

There are nuget service side changes (package icon specifically) that need to be dealt with and sooner or later, your preview version will no longer work.

For 5.0, simply being on a recent alpha build that has the updated nuget is enough.

**Comment by MattGal** [comment]
Closing as I have not seen new instances of this.
