### ISSUE TITLE
PackageIcon errors after latest arcade updates

### ISSUE THREAD

**Issue by tlmii** [dotnet/arcade#4240]
The [auto PR](https://github.com/dotnet/HttpRepl/pull/274) to https://github.com/dotnet/httprepl last night is failing because of [this error](https://dev.azure.com/dnceng/public/_build/results?buildId=407280):

> ##[error].dotnet\sdk\3.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5118: File 'F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19529.9\tools\Assets\DotNetPackageIcon.png' is not added because the package already contains file 'PackageIcon.png'

It is true, we do already have PackageIcon.png for our nuget packages and reference it in our .csproj files like so:

https://github.com/dotnet/HttpRepl/blob/7feb45b8d997e16116284aa1029f5eed7ce8ffe4/src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj#L11

Are we supposed to change our code to not include that file and just let it happen automatically? Or should this process detect that we already have it and not try to add it again?

**Comment by tmat** [comment]
I don't see a simple way to detect that the icon is already in the package files, since there is no metadata on the item that adds the icon file that indicates it's indeed an icon file :(. 

To fix the build you can remove 
https://github.com/dotnet/HttpRepl/blob/7feb45b8d997e16116284aa1029f5eed7ce8ffe4/src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj#L41-L43

If your package uses the default .NET icon then you can also remove https://github.com/dotnet/HttpRepl/blob/7feb45b8d997e16116284aa1029f5eed7ce8ffe4/src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj#L11

If you need a different icon than the default then set `PackageIconFullPath` to the full path of that icon file.

**Comment by ericstj** [comment]
Looks like this is hit here too: https://github.com/aspnet/websdk/blob/62532af20afcf6a54100f3f7745af5002a2c15e0/eng/Package.props#L19.  @vijayrkn

**Comment by MattGal** [comment]
I'm marking this as FR / Critical as it's impacting multiple teams and comes from Arcade.  I'll update as I can.  I think we may need to teach SignTool to special-case such files (i.e. store them in separate paths but still check them)

**Comment by tmat** [comment]
@ericstj YEs, that should also be removed. I believe that was a known follow up.

**Comment by ericstj** [comment]
> I think we may need to teach SignTool to special-case such files 

One could see this is unintentional bonus validation.  We don't want to ship NuGet packages that have duplicate file paths in them (will they even install??).  Maybe teach SignTool to identify the duplicates and give a friendlier error message, or do some nuget package validation, but I wouldn't go out of our way to handle the duplicates.

**Comment by jcagme** [comment]
> I don't see a simple way to detect that the icon is already in the package files, since there is no metadata on the item that adds the icon file that indicates it's indeed an icon file :(.
> 
> To fix the build you can remove
> https://github.com/dotnet/HttpRepl/blob/7feb45b8d997e16116284aa1029f5eed7ce8ffe4/src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj#L41-L43
> 
> If your package uses the default .NET icon then you can also remove https://github.com/dotnet/HttpRepl/blob/7feb45b8d997e16116284aa1029f5eed7ce8ffe4/src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj#L11
> 
> If you need a different icon than the default then set `PackageIconFullPath` to the full path of that icon file.

So should we send an email to partners about they having to update projects to remove existing icon references?

**Comment by jcagme** [comment]
Email to dnceng Partners has been sent after online communication with @tmat
