### ISSUE TITLE
Automate creation of tags / GitHub releases

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/arcade#4252]
For each release of .NET Core (including previews and patches), we have to create tags and GitHub releases corresponding to that release in 15 different repos.

For each repo, this involves:

- Figuring out the correct hash for the release for that repo
- Create a tag with the right version number for the right commit hash
- Push the tag to the repo
- Create a GitHub release corresponding to the tag

This is a fair amount of work across all the repos and releases we do, and is error-prone.

I think we should have all the correct version and hash information based on the dependency flow for the release.  So we should be able to create automation that will create all the right tags and GitHub releases in the different repos on demand.

**Comment by dsplaisted** [comment]
Related: https://github.com/dotnet/arcade/issues/2420

**Comment by nguerrera** [comment]
I have witnessed multiple incidents where that’s were applied incorrectly. +100 from me on this

**Comment by mmitche** [comment]
What I'd like to see for this:
- The tagging script takes as input:
  - The release information (in darc's manifest file. Json if needed).
  - Mapping of repo and asset->target remote
- The script walks the release info looking for the repo uris that need tagging
- The script finds the indicated asset for that repo, creates a tag using its version and pushes it to the corresponding target remote.

Remember that the repo uri were the tag sha lives, and the github repo uri may not be the same

**Comment by chcosta** [comment]
ToDo's

- [ ] Convert manifest yaml file to json format (Powershell plays nicer with json)
- [ ] Determine which packages should be used for determining tag versions
- [ ] Wire in GH PAT
- [ ] Validate in release pipeline

**Comment by chcosta** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/6169?_a=overview

**Comment by chcosta** [comment]
This is validated for 3.0/3.1 and currently in a testing pipeline.  I'm working with the release team to try to get agreement that we can move this to the official release pipeline.

**Comment by chcosta** [comment]
This is now in the official release pipeline
