### ISSUE TITLE
Symbol Archiving checks failing for some builds

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4288]
Reported by @brettfo : 

> Recent insertions of my teams’ component in VS have been failing symbol check, but we haven’t taken any recent changes to how we build/archive.  Is there a known issue around this?
> 
> - [Build log showing symbol archiving](https://dev.azure.com/dnceng/internal/_build/results?buildId=415437&view=logs&jobId=e3072f97-b3f6-597b-f816-087a04d4fd77&taskId=a6d78b66-d6e0-5387-684e-63c5cb4cbf69&lineStart=852&lineEnd=862&colStart=1&colEnd=1), look at lines 852-861.  (Is there a way to get a detailed log of this?)
> 
> - [Relevant lines in build definition](https://github.com/dotnet/fsharp/blob/release/dev16.4/azure-pipelines.yml#L81-L84)
> 
> - [Insertion into VS.](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/212286?_a=overview)
> 
> - [One of the generated symbol check bugs.](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1013718) Note that re-running symbol check doesn’t work, so it doesn’t appear to be a timing issue.
> 

Roslyn seems to also be having the same problem:

- [Roslyn build log](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3212138&view=logs&jobId=20fcf628-b65c-5865-625a-1cef81cda63b&taskId=51b3af06-8563-5d12-20a7-fb3b58d92162&lineStart=519&lineEnd=529&colStart=1&colEnd=1), see lines 519-528
- [Roslyn build definition](https://github.com/dotnet/roslyn/blob/release/dev16.4-preview3-vs-deps/azure-pipelines-official.yml#L88-L90).
- [Roslyn VS insertion](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/212221?_a=overview).
- [One of the Roslyn symbol check bugs](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1013548).

@mikem8361  input on the issue:

> The symbol uploading logging at lines 852-861 doesn’t tell us much of anything except that there were no errors or warnings. It might be that the Windows PDBs didn’t get converted (arcade does that separately) which is what symchk.exe requires.  

Cc'ing some folks from the e-mail thread: @JoeRobich @markwilkie @RikkiGibson

**Comment by JohnTortugo** [comment]
Moving this issue to tracking while we wait for feedback/guidelines from Symbol publish experts.

**Comment by mikem8361** [comment]
@JohnTortugo are you waiting for me to do something?

**Comment by JohnTortugo** [comment]
@mikem8361 Nope. The failure reported in this issue was due to a delay for the symbol files to be available in the servers.

I actually want to be sure what delay we should expect before the symbols are available in the symbol servers. In the past I heard about 10 minutes were the common delay but in a recent e-mail thread I heard that 24 hours delay can be the norm in some cases.

/cc @markwilkie

**Comment by JohnTortugo** [comment]
Adding a comment that I got from Helen Huang about symbol availability:

> Right now we don’t have any SLAs around availability of symbols to be discovered internally via symweb as we’re not able to measure it holistically, so we don’t have a guaranteed time for symbols to appear unfortunately. 
> 
> For some background, there are many ways to publish symbols to have them discoverable via symweb. One of those ways is using the Azure DevOps publish symbols task. If this is what you’re using, they should be available via symweb in 10 minutes or less, so if you’re seeing issues with this, we should loop in the Azure Artifacts team to help support you with that. If you’re using another process, please let us know! 
>
