### ISSUE TITLE
Upload logs from Validation post-build stage

### ISSUE THREAD

**Issue by dougbu** [dotnet/arcade#4305]
We've found problems encountered in https://dnceng.visualstudio.com/internal/_build/results?buildId=411570&view=results difficult to debug. @joeloff can't reproduce the problem locally and no artifacts from the Validation stage are uploaded. Since it seems likely others hitting validation failures will be in a similar boat, @riarenas asked me to file this issue.

Basic idea is to create a Validation_Logs artifact (or some such) containing at least `artifacts\log\Debug\*.binlog`. The change should land in `eng\common\templates\post-build\post-build.yml` of everybody's repo once they update.

We would prefer this change was made available in the 'release/3.x' branch and therefore the '.NET 3 Tools' channel.

/cc @JohnTortugo

**Comment by dagood** [comment]
Related: https://github.com/dotnet/arcade/issues/3687. Yeah, this is a pain.

**Comment by JohnTortugo** [comment]
We need to also add the `signcheck.errors.log`  file.
