### ISSUE TITLE
Signing validation should upload the `signcheck.errors.log`

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4309]
See sample build here: https://dnceng.visualstudio.com/internal/_build/results?buildId=411570&view=results

When SignCheck finishes execution it creates a log file which is very useful when the validation fails. We should make that log easily available for inspection.

**Comment by JohnTortugo** [comment]
Closing in favor of this previous one: https://github.com/dotnet/arcade/issues/4305

**Comment by JunTaoLuo** [comment]
Doesn't look closed 😄
