### ISSUE TITLE
Enable evaluation of product build content

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#431]
Because the repo dependencies of what we are building are specified in the sha that is built, we can evaluate the whole tree of shas to determine what commits make up a repo build.  This will allow us to ensure that the build we are about to ship contains the right fixes.  When this epic is done:

- [ ] Given a build artifact, we should be able to determine the sha on which it was built
- [ ] Given a sha, determine the full set of sha+repos that are implicitly contained.
- [ ] Given two shas or builds from the same repository A and B, determine whether all commits in A are contained within B.

The last point is an on-demand evaluation.  Let's say A's sha is the 3.0.100 SDK, and B's sha is the 3.1.100 SDK.  Implicitly B's sha should contain all of A's sha's, or else we have regressed what we ship.  This is especially important when running multiple ship trains in parallel.

**Comment by jcagme** [comment]
@mmitche is this what you are currently working about diffs and how far behind is a commit compared to other?

**Comment by mmitche** [comment]
Yes.  The how far is only local to a single tree.

**Comment by jcagme** [comment]
I'll assign this to you and move it to Dev so it reflects its actual status
