### ISSUE TITLE
EmbedUntrackedSources is breaking WPF build

### ISSUE THREAD

**Issue by panopticoncentral** [dotnet/arcade#4319]
The https://github.com/dotnet/project-system-tools repo has been unable to integrate arcade updates since the beginning of October due to build failures. The problem appears to be that EmbedUntrackedSources is now being set to true in ProjectDefault.props. This causes the generated files of WPF Page objects to emit #line pragmas without relative paths, and the build breaks:

D:\project-system-tools\artifacts\obj\ProjectSystemTools\Debug\net472\BinaryLogEditor\LogViewControl.g.cs(41,18): error CS1504: Source file 'BinaryLogEditor\LogViewControl.xaml' could not be opened -- Could not find file. [D:\project-system-tools\src\ProjectSystemTools\ProjectSystemTools.csproj]

It looks like there's a workaround for WPF temp projects, but this is for the main project build. (You can see this by cloning the darc-master-0d0fb37d-635d-49f6-ad5c-f57950a7b9b2 branch and doing eng\common\cibuild.) It's possible there's something funky about the project since I introduced WPF to it by hand (it's a .NET Standard project) before there was official support, but it's not clear to me what I might be doing wrong or if it's a problem in Arcade.

**Comment by alexperovich** [comment]
The #line pragmas need to be correct. If they are not then that is a WPF bug. Setting EmbedUntrackedSources to false should unblock your build, but the underlying bug in the generated code needs to be fixed.

**Comment by tmat** [comment]
This is a bug in WPF: https://github.com/dotnet/wpf/issues/1718.

**Comment by tmat** [comment]
As a workaround, I wonder if we can write a task that post-processes the .g.cs file and fixes up the paths.

**Comment by markwilkie** [comment]
Closing given the external bug and existing work-around.
