### ISSUE TITLE
Support .NET Core internal only builds

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#432]
Build stacks should be able to be created that are internal only.  They clone from internal branches and build to private output storage.  Dependencies flow like in the public branches,, and PRs work as expected (except in internal VSTS).  The mechansim for this should be just another variation of a private stack build, just without publicly visible inputs and outputs.

This epic is complete when:

- [ ] Developers can easily create an internal build stack
- [ ] Inputs and output worflow on that build stack is no different from public builds, just different visibility

**Comment by markwilkie** [comment]
Closing in favor of #815
