### ISSUE TITLE
Fix Signing Validation

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4325]
Issue reported by @dougbu . Sample build here: https://dnceng.visualstudio.com/internal/_build/results?buildId=419640&view=results

@joeloff had done some preliminar investigation and said that he wasn't able to repro the problem locally with the latest version of SignCheck.

I think the problem here might be that Arcade.SDK isn't indeed using the latest version of SignCheck.

**Comment by JohnTortugo** [comment]
Steps I'm following here are:

- I'm creating a test SDK that I made sure use the latest SignCheck. ([Build is here](https://dnceng.visualstudio.com/internal/_build/results?buildId=422948&view=results))
- Once the new SDK is built I can plug it into a test build from Extensions and see if my fix works. 
- If it works I'll need to submit a PR to Arcade and once the PR is merged customers will have the fix from next Maestro++ update.

**Comment by JohnTortugo** [comment]
Testing Extensions with my custom SDK here: https://dev.azure.com/dnceng/internal/_build/results?buildId=423091&view=results

**Comment by JohnTortugo** [comment]
Signing validation passed: https://dev.azure.com/dnceng/internal/_build/results?buildId=423116&view=results . My change was just to update the SignCheck version in Arcade.SDK.

**Comment by dougbu** [comment]
#4329 is the PR for this. Right @JohnTortugo❔

**Comment by joeloff** [comment]
Just catching up since I was OOF yesterday. So we've confirmed this is a version issue of the tool being used?

**Comment by dougbu** [comment]
@joeloff yes, @JohnTortugo tested and confirmed that yesterday
