### ISSUE TITLE
Arcade.SDK SdkTasks dependency packages default version

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4331]
[`SdkTasks/Version.props` ](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/Versions.props) isn't respecting versions set in repos' `eng\Version.props`.

Furthermore, some questions about this file content:

- Do we really need the hardcoded list of feeds?
- Can't we change the code to use the $(ArcadeSdkVersion) version of the packages by default?
- The condition on line 6 can be removed.

/cc @tmat @mmitche @riarenas

**Comment by tmat** [comment]
> Do we really need the hardcoded list of feeds?

I don't think so. We can replace these with `NuGet.config` file that we put into the `SdkTasks` directory.

> Can't we change the code to use the `$(ArcadeSdkVersion)` version of the packages by default?

I think we should for components that are built from dotnet/arcade repo.

The symbol uploader isn't (`MicrosoftSymbolUploaderBuildTaskVersion`). But what we can do is to
1) publish symbol uploader to dotnet-tools or dotnet-eng feed if it isn't there yet 
2) flow it to Arcade like so: https://github.com/dotnet/arcade/pull/3468

Then we would be able to remove the hard-coded versions.

**Comment by markwilkie** [comment]
I would love to see these hard coded versions go away...

**Comment by JohnTortugo** [comment]
Thanks @tmat

> `SdkTasks/Version.props` isn't respecting versions set in repos' `eng\Version.props`.

Do you agree with this statement?

**Comment by tmat** [comment]
Correct. That's intentional. `SdkTasks` should be independent of the repo configuration.

**Comment by markwilkie** [comment]
What are the right next steps here?

**Comment by JohnTortugo** [comment]
Two packages still have their version hardcoded: Maestro.Tasks and the symbol uploader. The former I think it's easily fixable by just adding another dependency to arcade-services builds. However, there isn't much we can do right now about the symbol uploader since the repo that produces it doesn't publish to Maestro/BAR.

**Comment by JohnTortugo** [comment]
Maestro.Tasks now is updated automatically. Only remaining package is the symbol uploader.

**Comment by riarenas** [comment]
We've added all the packages that can be automatically updated.

**Comment by JohnTortugo** [comment]
The symbol uploader is still manually updated. Do you want to create a separate issue to track that?

**Comment by riarenas** [comment]
Basically, we'll live with it. We have no interest in adding the symbol uploader to dependency flow at this time.
