### ISSUE TITLE
Tasks.Feed.dll : Could not load file or assembly 'NuGet.Common, Version=5.3.0.4

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4332]
The following builds failed with the error mentioned in the title:

- https://dnceng.visualstudio.com/internal/_build/results?buildId=422416&view=results
- https://dnceng.visualstudio.com/internal/_build/results?buildId=422649&view=results

```
##[error].packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.19558.11\tools\Publish.proj(162,5): error MSB4062: The "PushToAzureDevOpsArtifacts" task could not be loaded from the assembly F:\workspace\_work\1\s\.packages\microsoft.dotnet.build.tasks.feed\5.0.0-beta.19529.3\build\../tools/netcoreapp2.1/Microsoft.DotNet.Build.Tasks.Feed.dll. Could not load file or assembly 'NuGet.Common, Version=5.3.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621) Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

I think we dealt with a similar (same) problems a few days ago... Perhaps all we need is to update the Tasks.Feed lib in the affected repo?

/cc @mmitche @riarenas @MattGal

**Comment by mmitche** [comment]
It's because the dotnet SDK in use in the repo is tool old. Updating will work.

**Comment by JohnTortugo** [comment]
Pinging repo owners for awareness: @dotnet/dotnet-winforms  @dougbu

**Comment by merriemcgaw** [comment]
@AdamYoblick and @RussKie can you guys take care of this ASAP?

**Comment by mmitche** [comment]
I already opened a PR.

**Comment by AdamYoblick** [comment]
At the dentist, anyone else on the winforms team should be able to merge in Matt’s PR :)

________________________________

**Comment by markwilkie** [comment]
@AdamYoblick - just tell the dentist to take a break from drilling for a moment and check stuff in.   :)

**Comment by mmitche** [comment]
There are some test failures that need dealing with https://github.com/dotnet/winforms/pull/2357

**Comment by Tanya-Solyanik** [comment]
@mmitche  - the CI build is failing for your PR, had you investigated it?

**Comment by mmitche** [comment]
I had not.

**Comment by JohnTortugo** [comment]
Update:

- Winforms now is failing due to another issue which is being tracked here: https://github.com/dotnet/arcade/issues/4337
- EntityFramework6/master was updated to a newer .Net SDK by @JunTaoLuo . I queued a test build here: https://dnceng.visualstudio.com/internal/_build/results?buildId=426213&view=results

If EF6 build passes I'll close this issue.

**Comment by JunTaoLuo** [comment]
Yes we updated the SDK in EF6 to fix this issue. It should be passing now.

**Comment by JohnTortugo** [comment]
EF6 build passed.
