### ISSUE TITLE
C++ file properties lose version information

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/arcade#4339]
Here is a side-by-side comparison of c++ and C# file properties to illustrate the difference: 

![image](https://user-images.githubusercontent.com/20246435/68717651-34409800-055c-11ea-9bb5-381683209821.png)

For C++, the version string comes out to look like `4,800,19,46238 @Commit: c6a86389475b7d71a073433e3b2746f10b448ecb`, whereas for C#, it comes out to be like `4.8.0-rc2.19462.14+3e99215204ccf7ae18e7c654ebdd77c91b7140e2`. 

https://github.com/dotnet/arcade/blob/ea85a3c52f75e198785848b93d5456c3c01b1c1a/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.targets#L80-L88

For C#, this is based on `Version` defined here:
https://github.com/dotnet/arcade/blob/ea85a3c52f75e198785848b93d5456c3c01b1c1a/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets#L119-L123

Can we change C++ to use the same format so that both are consistent, and the product version can be easily inferred from the binaries by just looking at the file properties? 

/cc @tmat

**Comment by markwilkie** [comment]
Any chance you could submit a PR @vatsan-madhavan ?

**Comment by vatsan-madhavan** [comment]
Happy to - though not right away. I'll do it over the next week or two - that seem ok ?

**Comment by vatsan-madhavan** [comment]
Still planning on this - just haven’t gotten to it yet.
