### ISSUE TITLE
Publishing a package from a nuspec is broken

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/arcade#4341]
Quoting @jmarolf:

> Arcade broke generating a nuget package from a nuspec in #2003.  We will need to submit a PR to arcade to do the correct thing in the presence of nuspec files.  The root of the issue is that is appends the `CommonMetadataElements` xml in to the `NuspecProperties` list. The pack command does not know how to extract key-value pairs from xml

Original comment: https://github.com/dotnet/roslyn-tools/pull/574#issuecomment-545749753
Related to: dotnet/roslyn-tools#577

I am interested in fixing this if I can, but I could use some pointers on stuff like how to use a local `Microsoft.DotNet.Arcade.Sdk` and how to do a dry run of a NuGet pack.

**Comment by tmat** [comment]
This is not a bug in Arcade SDK. Packaging works just fine, but the nuspec needs to be updated. See https://github.com/dotnet/sourcelink/blob/master/src/SourceLink.AzureDevOpsServer.Git/Microsoft.SourceLink.AzureDevOpsServer.Git.nuspec for an example.

**Comment by RikkiGibson** [comment]
Thank you, this makes total sense now!
