### ISSUE TITLE
Delete eng\common\SigningValidation.proj

### ISSUE THREAD

**Issue by tmat** [dotnet/arcade#4342]
The file is already in Arcade SDK package under `tools\SdkTasks`. The files differ but I assume the one in the package is the one that's used. If not then we should make it so.

Also delete this code:
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.proj#L105-L110

Edit: file is currently in use. This issue should be worked only after #4034 is done.

**Comment by JohnTortugo** [comment]
That file is currently being used by the RM release pipelines: https://dnceng.visualstudio.com/internal/_release?_a=releases&view=mine&definitionId=39

We'll be able to delete them once we don't need the release pipeline runner anymore: https://github.com/dotnet/arcade/issues/4034

**Comment by tmat** [comment]
So why is this closed? The fact that this issue has a dependency doesn't mean it should be closed.

**Comment by markwilkie** [comment]
@jcagme - this will likely become possible once the ring work is done?

**Comment by jcagme** [comment]
Yes. @Tohron FYI

**Comment by JohnTortugo** [comment]
This file was already deleted: https://github.com/dotnet/arcade/tree/master/eng/common
