### ISSUE TITLE
Associate arcade-validation builds with all channels

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4351]
Associate arcade-validation with all channels, so that we better test our publishing infrastructure.

**Comment by mmitche** [comment]
@mjanecke @sunandabalu This should help with validation of arcade.

**Comment by JohnTortugo** [comment]
Just mapped the default branch of arcade-validation to all .net 5 channels. Current list is:

```
(1064) https://github.com/dotnet/arcade-validation @ master -> .NET Eng - Latest
(129)  https://github.com/dotnet/arcade-validation @ master -> .NET Eng - Validation
(1060) https://github.com/dotnet/arcade-validation @ master -> .NET Core 5 Dev
(1069) https://github.com/dotnet/arcade-validation @ master -> General Testing
(1062) https://github.com/dotnet/arcade-validation @ master -> .NET Core Tooling Dev
(1063) https://github.com/dotnet/arcade-validation @ master -> .NET Core Tooling Release
(1068) https://github.com/dotnet/arcade-validation @ master -> .NET Internal Tooling
(1061) https://github.com/dotnet/arcade-validation @ master -> .NET Core Experimental
(1066) https://github.com/dotnet/arcade-validation @ master -> .NET Eng Services - Int
(1067) https://github.com/dotnet/arcade-validation @ master -> .NET Eng Services - Prod
(1057) https://github.com/dotnet/arcade-validation @ master -> .NET 5 Preview 1
(1058) https://github.com/dotnet/arcade-validation @ master -> .NET 5 Preview 2
(1059) https://github.com/dotnet/arcade-validation @ master -> .NET 5 Preview 3
```

Test build running here: https://dnceng.visualstudio.com/internal/_build/results?buildId=532468&view=results

/cc @riarenas

**Comment by JohnTortugo** [comment]
Builds after the change are succeeding:

- https://dnceng.visualstudio.com/internal/_build/results?buildId=532468&view=results
- https://dnceng.visualstudio.com/internal/_build/results?buildId=532491&view=results

**Comment by riarenas** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=534321&view=logs&j=51c75269-d108-5b35-500b-cc803a6d6b66&t=db467048-79f0-5bc7-fe0b-67cface4c44b looks related to this
