### ISSUE TITLE
[QCR][Release prep] Create script to do as much of the branding updates as possible

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4371]
Create a script or program that can be run that will open a PR in each repo that requires branding updates.  Requirements:

- [ ] Takes a set of branch + repository combos in a json file (maybe directly on the command line too?)
- [ ] A method that will do the update. This should be extensible in that
  - [ ] It should be able to be replaced eventually with a call to some kind of arcade functionality (upgrade this repo to X) where appropriate
  - [ ] Update methods can differ per update entry.
  - [ ] Update methods are parameterizable (e.g. we could have a "update to next version" entry and an "update to specific version")
- [ ] A PR is opened to the target branch with the update and appropriate users tagged.

**Comment by jcagme** [comment]
ref: https://github.com/dotnet/arcade/issues/2419

**Comment by jcagme** [comment]
Also https://github.com/dotnet/arcade/issues/2420

**Comment by adiaaida** [comment]
This was checked in. Closing (there is no rollout procedure for the release repo).
