### ISSUE TITLE
JobSender API is missing XML documentation comments

### ISSUE THREAD

**Issue by lukas-lansky** [dotnet/arcade#4384]
JobSender provides nice, fluent, strongly typed interface for Helix:

```
IJobDefinition WithSource(string source);
IJobDefinition WithProperty(string key, string value);
IJobDefinition WithCreator(string creator);
IJobDefinition WithContainerName(string targetContainerName);
```

What I'm missing here is a quick explanation of concepts we are setting in the standard XML doc format. I can see that there is a description for some of these at https://github.com/dotnet/core-eng/blob/master/Documentation/Tools/Sample-Job-Sender/Helix-SDK-Job-Sender.md#modifying-the-code , but discoverability of XML docs understood by IntelliSense is obviously better. Also, additions to the interface have better chance to stay in sync with docs when documentation is as collocated as possible.

```
/// <summary>
/// Obtains API client for unauthenticated access to external queues.
/// The client will access production Helix instance.
/// </summary>
/// <remarks>
/// Attempt to access internal queues by such client will cause
/// `ArgumentException` triggered by `SendAsync` call.
/// </remarks>
public static IHelixApi GetAnonymous()
```

**Comment by MattGal** [comment]
Moving to WIP since you've already self-assigned.

**Comment by MattGal** [comment]
Arcade and Helix service are rolled out, closing...  (please consider putting links to PRs in here)
