### ISSUE TITLE
GenerateVisualStudioInsertionManifests not executing during build

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/arcade#4391]
After this change (https://github.com/dotnet/arcade/pull/4307) merged in, Roslyn signed builds stopped generating manifests.

binlog before change
![image](https://user-images.githubusercontent.com/611219/69098386-554a3280-0a0d-11ea-80c8-ad116fb09ec7.png)

binlog after change:
![image](https://user-images.githubusercontent.com/611219/69098434-701ca700-0a0d-11ea-902b-16d8d1c6cd28.png)

**Comment by markwilkie** [comment]
cc/ @MattGal

**Comment by riarenas** [comment]
#4183 was the original issue for this.

@Tohron could you take a look? it looks like the change still broke target chaining.

**Comment by markwilkie** [comment]
Perhaps we should revert this?

cc/ @Chrisboh

**Comment by riarenas** [comment]
I think we should:

1. Revert #4307 
2. Use the same pattern used in https://github.com/dotnet/arcade/pull/4379 for a new fix after we re-validate that the fix works.

**Comment by ulisesh** [comment]
> 
> 
> I think we should:
> 
>     1. Revert #4307
> 
>     2. Use the same pattern used in #4379 for a new fix after we re-validate that the fix works.

Working on it

**Comment by Tohron** [comment]
> Use the same pattern used in #4379 for a new fix after we re-validate that the fix works.
It might be useful to have a breakdown of how the logic in #4379 works for replacing AfterTargets (along with how the logic for the fix I implemented broke down in this instance.)

**Comment by Tohron** [comment]
Taken over to look for a solution that doesn't have unexpected consequences for anyone.  For now, I'm trying to figure out the logic in https://github.com/dotnet/arcade/pull/4379/files

**Comment by tmat** [comment]
Please tag me for review on any future changes in the targets.

**Comment by Tohron** [comment]
Testing out breaking apart the Build and Pack targets in AfterSigning into stages on @tmat 's recommendation to avoid use of AfterTargets in https://github.com/dotnet/arcade/pull/4487

**Comment by Tohron** [comment]
I've confirmed that the changes Tomas recommended will lead to build failure if an error occurs in GenerateVisualStudioInsertionManifests.  What steps should I take to validate that they didn't have any unexpected effects elsewhere?

**Comment by tmat** [comment]
@Tohron I think we just need to make sure Roslyn builds still work as expected after this change is propagated to dotnet/roslyn repo. @JoeRobich should be able to help with that.

**Comment by Tohron** [comment]
Closing since there have been no issues since the merge.
