### ISSUE TITLE
Weird AssemblyAttributes file path

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#4395]
https://github.com/dotnet/arcade/blob/75da942953455e0e4e07a9c613bca74015902975/src/Microsoft.DotNet.Arcade.Sdk/tools/Workarounds.targets#L51 currently generates the following output:

`C:\git\runtime\artifacts\obj\ref\System.Drawing.Common\netcoreapp3.0-Debug\.NETCoreApp,Version = v3.0.AssemblyAttributes.cs`.

The file contains spaces and invalid characters. Is this expected?

cc @tmat

**Comment by tmat** [comment]
Yes, this is expected. Copied from .NET SDK. What invalid characters?

**Comment by ViktorHofer** [comment]
Why doesn't this use the short from of the TargetFrameworkMoniker instead? Having [., =] characters in a path is super weird. They aren't invalid but usually we try to avoid having ie spaces in a path.

**Comment by ViktorHofer** [comment]
OK thanks. Closing.
