### ISSUE TITLE
[QCR][Staging ring] Generate list of shipping packages for each servicing release, for the release doc to use

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#4397]
E.g. https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.7/2.2.7.md#packages-updated-in-this-release

The initial thought is to trivially add this to `gather-drop`.

I wonder if this might be the start to doc generation infra and maybe deserve more thought. For example, maybe these docs would be useful as something the Maestro++ site can show for build insight? Maybe it should (also?) be available as its own `darc` command?

**Comment by mmitche** [comment]
> I wonder if this might be the start to doc generation infra and maybe deserve more thought. For example, maybe these docs would be useful as something the Maestro++ site can show for build insight? Maybe it should (also?) be available as its own `darc` command?

That's an interesting idea. I like it.

**Comment by markwilkie** [comment]
cc/ @chcosta and @jcagme 

I'm adding this to the release epic because it's essentially a contract.  But I think @chcosta made progress here too because of signing.

**Comment by jcagme** [comment]
Is this different from "\\vsufile\patches\sign\NET\CORE_BUILDS\5.0.X\5.0.0\5.0.100-preview.2.20176.6\manifest.json"?

**Comment by dagood** [comment]
That looks like a source of the raw data, but the output would be the table format I linked to, filtered to shipped packages and sorted properly. This is a release doc artifact for @rbhanda @leecow. (See email thread "Ship-*.txt files missing for 3.0.1 release", @mmitche was on.)

**Comment by jcagme** [comment]
> That looks like a source of the raw data, but the output would be the table format I linked to, filtered to shipped packages and sorted properly. This is a release doc artifact for @rbhanda @leecow. (See email thread "Ship-*.txt files missing for 3.0.1 release", @mmitche was on.)

Sorry I wasn't explicit enough :). When I pointed to `manifest.json` I was referring to that been the source where we would get the information about shipping packages and apply the required formats, etc.

**Comment by adiaaida** [comment]
I've nearly got this done, but I wanted to check about the format of the version for the packages. Currently, for the preview versions, I'm grabbing the entire version, including the build number. So for example `5.0.0-preview.2.20160.9`. But looking at the release docs, it looks like we'd exclude the build number, suggesting for a 5.0.0 release, version would just be `5.0.0`, but what should it be for a preview? `5.0.0-preview.2`?

Thanks for your help!

**Comment by mmitche** [comment]
for previews it's always the full build with the build number.

**Comment by mmitche** [comment]
So I think you can actually just take the version as it exists in the manifest. The previews would include the full version, while for servicing releases that build number/pre-release tag is stripped away.

**Comment by adiaaida** [comment]
Perfect! That's what I was hoping to hear.

**Comment by adiaaida** [comment]
This functionality is now part of the release pipeline.
