### ISSUE TITLE
Get signing plan sorted

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#44]
I presume we'll want to use signtool, but there are some details that need to be worked out.  Once there's a plan, I'd like to see that funded soon so we can start using it for ESRP and nupkg signing.

**Comment by morganbr** [comment]
Are you planning to use signtool for test signing or production signing? Production probably requires something else.

**Comment by jaredpar** [comment]
@morganbr for test and production signing. It's already being used for both by a fairly large number of teams inside the organization. The tool itself doesn't actually do signing, it's just a wrapper for our signing process that adds extra validation, ability to validate signing consistency on developer machines, batching, and zip format support.
