### ISSUE TITLE
Update readme to include Service Fabric SDK as prereq

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#4406]
`Build.cmd` and `build.sh` will not work unless the Service Fabric SDK is installed on the machine. We should update the Readme to include instructions on how to install those as part of the build process.

**Comment by markwilkie** [comment]
If this is still relevant - especially given that we're moving more stuff to SF, please add the link.

**Comment by jonfortescue** [comment]
I'm not sure if the main README is the right place for this anymore. @garath do you have thoughts on this?

**Comment by garath** [comment]
I agree the Arcade readme or StartHere isn't quite right. This doesn't really help customers and those docs are already pretty busy.

What if we instead improved visibility in the [arcade-services readme](https://github.com/dotnet/arcade-services/blob/master/README.md)? It seems like this doc is the right place to describe the projects within arcade-services (and this repo has gotten complicated enough that some clarity would be helpful) and tie together any developer documentation. 

I'll put together a draft for evaluation.
