### ISSUE TITLE
Arcade should update the versions repo with published versions

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#441]
If I want to know what the current guidance for how to update the versions repo is, I'd expect to go to Arcade and Arcade official builds, but I don't think Arcade is updating the versions repo.  

If the guidance is to update BAR instead, it feels like there's a gap since that's not currently being used and teams still need to flow version dependencies via dotnet/versions.

**Comment by maririos** [comment]
> Arcade is updating the versions repo.

Correct.

>guidance for how to update the versions repo is

Why do you want to know how to update the versions repo? From my understanding, all repos are using the "old" flow where Maestro is in charge of updating its dependencies. Developers shouldn't worry about it, and the versions repo has documentation on how Maestro works.

Once Maestro++ is ready, we'll stop having a dependency on the versions repo (at least for .Net Core 3.0). I will expect to have documentation for repos on how to consume this new flow, but knowing that the infrastructure is not ready yet, well no documentation.

**Comment by chcosta** [comment]
> Why do you want to know how to update the versions repo?

CLI / Sdk did some refactoring and the new core-sdk repo doesn't have a clean way to update the versions repo - https://github.com/dotnet/core-eng/issues/3974.

**Comment by maririos** [comment]
I guess the confusing part here, is, should the guidance for Maestro (not Maestro++) and versions repo should be in Arcade, knowing that the code is not here, and is something we are not currently supporting in Arcade?

FYI @jcagme

**Comment by jcagme** [comment]
Maestro's code just got merged in the past couple of days and soon will be integrated with Darc to do versions flow. For this to work fine, repositories have to be Arcade repos and need to have the required version files. Is this the case for CLI?

**Comment by chcosta** [comment]
I'm not plugged into the Darc work, but my presumption is that no repos are currently using Darc and that they're all still using some ad-hoc thing to update the versions repo, then Maestro to flow dependency changes when dotnet/versions is updated.  

If the Darc / BAR / Maestro stuff is imminent, we can table this issue for Arcade, it just surprised me that Arcade wasn't updating dotnet/versions today.

Having a src folder named Maestro which is not identical to the Maestro people are using today and is not going to be compatible, is a bit confusing.

**Comment by jcagme** [comment]
What would you suggest to make this less confusing? At the end, Maestro++ will absorbe and replace Maestro but we are not there yet to shut down Maestro.

/:cc @alexperovich

**Comment by dagood** [comment]
I don't see the need to force the branding for Maestro++ to be Maestro. Why don't we consistently refer to it as Maestro++?
