### ISSUE TITLE
Create temporary-ish script to check mirror state

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4425]
Create a script (temporary?) to check the state of the mirrors.  Until we have a real long term solution for them, having the mirrors fail and then not really know about it is a major issue for servicing.

Script should:
- [ ] Check state of each mirrored branch listed in old maestro's subscriptions.json
- [ ] Check dediv and dnceng repos where needed
- [ ] Check that the normal mirror has all commits (HEAD matches)
- [ ] Check that internal merge mirror has all commits.

**Comment by markwilkie** [comment]
Closing given that the epic closed.
