### ISSUE TITLE
[darc/maestro++] Include subscription info in pull requests

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/arcade#4441]
It would be nice if a Maestro pull request that was created because of a subscription included information about the subscription that caused it to be created. Ideally a link, but I don't think there's a URL for subscriptions at the moment.

I wanted this today when I noticed a PR to a branch that I didn't expect to be receiving updates. I had to manually inspect my repo's subscriptions to find the one to disable.

**Comment by mmitche** [comment]
Thanks, will do.
