### ISSUE TITLE
Recent changes to SymStore.targets cause F# CI to fail; Pdb2Pdb package isn't restored

### ISSUE THREAD

**Issue by brettfo** [dotnet/arcade#4449]
Recent arcade updates to F# (dotnet/fsharp#7891) have been failing in ways similar to #4405, #4411, and #4424.  The issue is that the Pdb2Pdb package isn't restored in time so the attempt to convert symbols fails.

This can be locally reproduced from the dotnet/fsharp `darc-master-18beaa65-4326-493a-8f0f-f25fce2ef84c` branch with the following:

- Delete the directory `1.1.0-beta2-19521-03` from `%USERPROFILE%\.nuget\packages\microsoft.diasymreader.pdb2pdb`
- `build.cmd -bl -ci`

**Comment by tmat** [comment]
Thanks for the report. That finally explains what was going on. 
A couple of things:
1) I'll make a change in Arcade to move the PackageReference to the right place.
2) You don't need to run the PDB conversion when building bootstrap compiler, so pass `/p:PublishWindowsPdb=false` here: 
https://github.com/dotnet/fsharp/blob/37970b41db5c858411fc42876233e608844c9f58/eng/build-utils.ps1#L240

**Comment by tmat** [comment]
Doing [2] would fix it. No need to wait for new Arcade build.
