### ISSUE TITLE
[Signing] Make the sample repo adopt the sign tool

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#445]

**Comment by maririos** [comment]
Sample Repo: https://github.com/dotnet/arcade-minimalci-sample

**Comment by maririos** [comment]
@jonfortescue  will provide more guidance here on what the best approach to do this is

**Comment by JohnTortugo** [comment]
@jonfortescue what needs to be signed on the sample repo? I think ideally we would need a project marked as packable so can get a .nupkg from it, then the Arcade.SDK should be able to automatically find it.

**Comment by jonfortescue** [comment]
@JohnTortugo @maririos Based on talking with @chcosta, I think the current thinking is to have Arcade be the sample for "real signing" and simply to enable test-signing for the sample repo. FYI @markwilkie

**Comment by JohnTortugo** [comment]
AFAIU the setup for "test" and "real" signing is mostly the same. A boolean flag control which method will be used.

**Comment by chcosta** [comment]
We can transition to real signing this repo once an official build is created.  We should do that work as we begin to enable official builds out of dotnet.vs.com.

**Comment by JohnTortugo** [comment]
Will there be any packages to "test" sign for now?

**Comment by chcosta** [comment]
If that's a scenario you want to highlight, then that is part of the work.  Currently the repo only produces binaries.

**Comment by maririos** [comment]
To clarify, adding a package and the logic to use the SignTool will be on us?

**Comment by chcosta** [comment]
Yes, my view is that the samples repo is a shared repo to demonstrate best practices for using Arcade infrastructure.  It's owned by the Arcade / engineering working teams across the board.  You should feel empowered to demonstrate clear usage and scenarios in this repo.  Let me know if that is different than your understanding of the repo.

**Comment by JohnTortugo** [comment]
I created a PR on the sample repo but couldn't link you as reviewers. Could you PTAL? 

https://github.com/dotnet/arcade-minimalci-sample/pull/7

**Comment by chcosta** [comment]
@jonfortescue , is the sample repo not a part of the dotnet org?

**Comment by jonfortescue** [comment]
@chcosta Uhhh I assumed that's what happened when you create a repo in dotnet. I actually do not know. How would I check?

**Comment by chcosta** [comment]
I went to My profile -> Organizations -> .Net foundation, and searched there.  Looks like this repo is a part of the org.   I'm not sure why we wouldn't be able to be added as reviewers for @JohnTortugo , I appear to be able to add reviewers in arcade-minimalci-sample repo.

**Comment by JohnTortugo** [comment]
@jonfortescue added me as a Contributor and then I was able to use full functionality of the UI.
