### ISSUE TITLE
Setup SetupNugetSources.ps1 doesn't seem to be working properly

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4469]
https://dev.azure.com/dnceng/internal/_build/results?buildId=443999&view=logs&j=ec36e75a-6b88-5377-6d50-3ad14fd09c58&t=c70e0f28-8e93-5b47-f39b-88644244d135

This appears to be setting up the nuget sources properly (see 3.1 feeds being searched), but still seeing credential errors.

**Comment by riarenas** [comment]
Looking.

**Comment by riarenas** [comment]
Looks like there was an error in the example usage that the scripts provide. Made a few tweaks to the failing PR and was able to get past the errors by adding this commit: https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/commit/697335c3fca3cbdb6ae7cdebe4186278552b9842

and got a successful PR build: https://dev.azure.com/dnceng/internal/_build/results?buildId=444119&view=logs&j=775c2470-dc26-5fca-04e0-a0c513c348cf.

I'll make a PR to update the example usage yaml that the scripts provide, and to add a few fixes to support 3.1 feeds that @mmitche added to the script in this failing PR directly.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade/pull/4479

**Comment by riarenas** [comment]
We want this in 3.x which is the urgent case here, so created https://github.com/dotnet/arcade/pull/4481

**Comment by riarenas** [comment]
The script changes should now be available in the ".net tools 3" channel. I'll keep this open until we get some more news on whether there is more work to be done in these scripts.

**Comment by riarenas** [comment]
Closing as @mmitche reported the scripts working with the changes in the core-setup build. Closing.
