### ISSUE TITLE
Process and Tools Reliability Analysis

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4471]
This epic covers an analysis and set of recommendations for process and tools reliability.

I have some hypothesis that our current processes (engineering and associated tools, inter-repo cooperation, communication required to produce a product, etc.) are more complex than necessary, leading to increased effort required to produce a shipping product.  Basically, the hypothesis is that our process is both complex AND highly integrated. Failures are always possible, and when a failure happens (e.g. someone forgets to update branding), recovery requires more effort. These failures can come from many places.  Some are from automated systems (e.g. failing code mirrors) and some are human. In the past we have simply added more safety checks to our processes.  But those safety checks can also fail, and thus if they are part of the integrated process, they may make failure more likely.

After this epic is done, we will:
- [ ] Have a report on the sources of complexity within .NET Core's processes and associated recommendations for improvement,
- [ ] Have a metric (even rough) by which may measure process complexity so we can track improvements over time.

**Comment by markwilkie** [comment]
What are the next steps here?

**Comment by markwilkie** [comment]
Is this an epic we should put on our backlog?
