### ISSUE TITLE
Create MVP for CoreCLR CI build in VSTS

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#448]

**Comment by chcosta** [comment]
@jonfortescue can you add status here?

**Comment by jonfortescue** [comment]
Yep, that's my bad. Copy/paste from earlier status email:

_________________________________

I have a working build! It currently only does the work for x64 Windows and there is one more missing piece that I’ll be adding today.

Link to the most recent build: [here](https://dotnet.visualstudio.com/public/_build/results?buildId=15695&_a=summary&view=logs).

Link to the source code: [here](https://github.com/jonfortescue/coreclr/tree/jofortes-vsts).

Currently the build:

-   Installs the correct version of .NET on the build machine
-   Uses the native-tools bootstrapping feature of Arcade to install CMake on the build machine
-   Cleans up binaries from previous builds (this process is a little hacky and should probably be replaced with something that coreclr already does)
-   Runs coreclr’s build.cmd
-   Uses Arcade SDK to zip up the tests directory and send it to Helix with “runtests.cmd” as the command

-   In order to do this, we’re using a new GitHub bot for sending public CI jobs to Helix
-   The parameters (source, type, etc.) of the job should be changed from their temporary values

As part of that last bit of work, we found a bug in the Arcade SDK that was causing the jobs sent to Helix to fail because it was improperly packing the zip files. As soon as that bug gets fixed, I’ll be putting the logic in for these builds to wait on Helix test completion and the migration work will be complete.

**Comment by jonfortescue** [comment]
The bot that I created needs to be updated by folks in account management so that it can join the Microsoft GitHub org. In tracking until this update occurs.

**Comment by jonfortescue** [comment]
As far as I can see, all the blocking issues on this have been solved, so I will be proceeding with creating a PR after I complete the arcade-minimalci-sample.

Issues solved:
* Archive upload to Helix using the SDK
* Helix Job Waiter improved and added to the SDK
* Sending payloads to Helix has a temporary solution with a more complete longer-term solution on its way
