### ISSUE TITLE
Feed proxy 502 issues

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4480]
The feed proxy has trouble when a bunch of builds hit it at the same time. E.g.:

https://dnceng.visualstudio.com/internal/_build/results?buildId=444870&view=logs&j=b4919f40-b143-5761-630b-1f7e93bd50c9&t=a94ae068-d517-5353-7e47-b540ecc1aa89&l=749

It's not really clear whether this is something new, or a result of increased usage in these tests. Anyways, it probably should not fail in these cases.  There's no obvious fix in the portal, so it may be a matter of following up with Azure re: what the expected performance should be.

**Comment by MattGal** [comment]
502s frequently come with no useful logging from the server-side, but I'll put this on the backlog to investigate.

**Comment by rokonec** [comment]
There was enabled debug detail trace on dotnetfeedmsrc azure function proxy. This trace was filling disk space and become unpractical as there was 100K files in it and identify proper log in it turned to be very hard. Nevertheless there were not single log which would report 502 as return value so this has no use for fighting this particular issue.
I have disabled detailed trace and cleaned its history data. I have also enabled logging into application insights - not sure if it actually logs proxy calls.

I plan to let it this collect data for two days and then survey its logs.

**Comment by rokonec** [comment]
I assume retry is not possible here as its failing on standard msbuild target
```NuGet.targets(119,5): error :   Unable to find package```
@mmitche is my assumption correct?

**Comment by rokonec** [comment]
Everything looks OK since. We shall not invest into it anymore as it is used by 2.1 only builds.

**Comment by rokonec** [comment]
Please @MattGal review and close

**Comment by mmitche** [comment]
> I assume retry is not possible here as its failing on standard msbuild target
> `NuGet.targets(119,5): error : Unable to find package`
> @mmitche is my assumption correct?

Nuget already done a ton of retry, as do most of our download tasks that may use this.

**Comment by MattGal** [comment]
> Please @MattGal review and close

With gusto.
