### ISSUE TITLE
Support "ignore errors" type mode in native toolset installs

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#4482]
winforms and wpf repos have a dependency on current behavior of native toolset bootstrapping which unintentionally ignores some failure.

![failure](https://user-images.githubusercontent.com/10092143/70078489-9fa7e380-15b7-11ea-95b3-facd700cce66.png)

The result is that we have to omit pipeline telemetry output for this part of our code or else we will force this to fail during CI builds.  This creates a gap in our telemetry as we don't have insight into when native toolset bootstrapping is really causing problems in repos.

**Comment by jonfortescue** [comment]
Not sure if this still needs to be done -- kicking to triage for further discussion.

**Comment by RussKie** [comment]
In .NET 6+ dotnet/winforms moved the intellisense bundles from global.json; dotnet/wpf moved the intellisense bundle from global.json in .NET 7.
