### ISSUE TITLE
[PKPIs] Longest Build Path: Add Longest Build Path flow graph to BarViz

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#4499]
* [x] Add viz.js package to maestro-angular project
* [x] Add swagger api that we can use to generate the graph, and send the json to barviz like we do with the dependency build graph.
* [x] Once we have the json in barviz, walk the graph, and write the string that we will send to Viz to generate the svg
* [x] Update the channel sidebar so that when we click a channel id, we open a page in the main frame that displays the flow graph with longest build path highlighted
* [x] Refactor out the code that gets the build times so that it can be shared by the ChannelsController and the BuildTimeController.
* [x] Add links in the PowerBI report to the channel page for the selected channel for an easy way to access the longest build path graph.

**Comment by riarenas** [comment]
@adiaaida There's still a checkbox to mark here. Is there more work that needs to be done for that after today's rollout?

**Comment by adiaaida** [comment]
That's correct. I still need to make the power bi change.
