### ISSUE TITLE
Runtime installation steps do not fail build if the runtime fails to download

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4503]
The dotnet-install script will not exit with an exit code if the runtime fails to download.

**Comment by riarenas** [comment]
Looks like the windows script is missing exiting with an error code when it fails to install, it only logs telemetry. https://github.com/dotnet/arcade/blob/master/eng/common/tools.ps1#L218

**Comment by riarenas** [comment]
PRs are out:

Master: https://github.com/dotnet/arcade/pull/4505
Release/3.x: https://github.com/dotnet/arcade/pull/4506

**Comment by riarenas** [comment]
This has been flowed through the ".NET 3 tools" channel,  but we haven't been able to get a green build of arcade master to get this flowing to the ".NET tools - latest" channel.

**Comment by riarenas** [comment]
Was able to get a successful arcade build and it's flowing to Arcade-validation in https://github.com/dotnet/arcade-validation/pull/1115. Once Arcade-validation official build succeeds this will be considered rolled out.

**Comment by riarenas** [comment]
Changes were also now propagated through the ".net tools - latest" channel this morning.
