### ISSUE TITLE
[darc/maestro++] Improve internal dependency flow titles

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4504]
The internal dependency flow titles tend to get written always as

`[internal/release/3.0.1xx] Update dependencies from 1 repositories`

This is because of two things, I think:
- Longer branch names
- Source url is longer (e.g. https://dev.azure.com/dnceng/internal/_git/dotnet-core-setup)

This isn't too useful when looking at the set of PRs.  I would either:
- Compute a better shortened source url
- Increase the max length.

Goal is that when there is a non-batched sub for internal->internal flow, it shouldn't just show "from 1 repositories"

**Comment by riarenas** [comment]
Ooh yeah, definitely due to our maximum length.

**Comment by JohnTortugo** [comment]
Do we have a limit on the title length? Is that arbitrary or some downstream tool impose that?

**Comment by riarenas** [comment]
We're limited by whatever the maximum length is for Github/ Azdo pull request title lengths.

**Comment by mmitche** [comment]
For AzDO I think the limit is longer than what we have on github, but will take some experimentation.
