### ISSUE TITLE
Use of dynamic internal feeds fails validate steps

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4507]
When automatic internal feeds (darc-int) are part of the nuget.config file, the validation steps provided by arcade will fail because they do not automatically use the nuget feed credential steps.

Example:

https://dev.azure.com/dnceng/internal/_build/results?buildId=449737&view=logs&j=b11b921d-8982-5bb3-754b-b114d42fd804&t=2821fb27-4bed-51b5-9616-aecc2c09fe47

**Comment by riarenas** [comment]
Tagging as FR.

**Comment by mmitche** [comment]
I think I've got a fix already

**Comment by riarenas** [comment]
@mmitche can this be closed since #4508 was merged? or do you think there's more to be done for this?

**Comment by mmitche** [comment]
Nope, good to go here.
