### ISSUE TITLE
Option to not use xcopy-msbuild if VS is not found 

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/arcade#4534]
I'd like to introduce an option to fail the build if Visual Studio with required components is not found. 

The current behavior (search for VS with requested components; if it's not found then fall-back to xcopy-msbuild) works for most repos/users. For WPF, there is no real fallback besides VS, so I'd like to turn off the fallback. 

I have two possible implementation proposals. 

i. A global variable, something like `$global:DoNotUseXcopyMsBuild`. Interested parties can set it in `eng\configure-toolset.ps1`. 
ii. In `global.json`, use an invalid version as a sentinel value for `xcopy-msbuild`. For e.g., `none` (we'll have to document it). It will be interpreted as "do not fallback to `xcopy-msbuild`". 

I like option (ii) over (i). Thoughts ? 

I'd like to use this in https://github.com/dotnet/wpf/pull/2307. 

/cc @tmat, @chcosta 
/cc @rladuca

**Comment by tmat** [comment]
+1 for `"xcopy-msbuild" : "none"`
