### ISSUE TITLE
[PKPIs] Longest Build Path: Add build times to darc flow graph

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#4536]
* [x] Run generate-client.cmd to generate the models to be used by darc
* [x] Add api calls to remote and bar client
* [x] While constructing the flow graph, call api to get official build time for the given repo/branch and pr times for this repo.
* [x] Walk the flow graph to determine, at each node, the time that it takes to go from that node to the shipping node, for both the best case (only official build times) and worst case (official build times + pr times).
* [x] Determine which path through the graph is the absolute longest and mark the edges of that path so that when we generate the graph, we mark those edges with red
* [x] Modify the flow graph generation to include build times

**Comment by riarenas** [comment]
This has been rolled out.
