### ISSUE TITLE
Enable repro tool for AzDO tests (instead of Helix)

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#454]
Repro tool should work with both CI and official builds in VSTS.  This epic is considered complete when:

- [ ] The current repro functionality in Jenkins CI is available in VSTS CI

**Comment by eerhardt** [comment]
@markwilkie - has this been scheduled at all? Any idea when it will be available? ML.NET is using the Dev Ops hosted machines for Windows and Linux (and soon to be macOS), and having repro machins for failures that only occur in CI would be helpful.

/cc @TomFinley

**Comment by markwilkie** [comment]
Pretty [straight forward](https://github.com/dotnet/arcade/blob/master/Documentation/VSTS/SendingJobsToHelix.md) to get going and [getting even better](https://github.com/dotnet/arcade/issues/947) based on feedback.  (be sure and use zenhub to look at 947 to see the linked issues)

cc/ @jonfortescue

**Comment by eerhardt** [comment]
Using Helix for tests doesn't eliminate the need for this. There are plenty of cases where the build fails, like dependency issues, version on the machine is different issues, etc.

**Comment by markwilkie** [comment]
Closing in favor of #6113
