### ISSUE TITLE
Configure code coverage to be collected during build and test in Arcade Services

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#4551]
https://github.com/dotnet/core-eng/issues/8343 is adding code coverage to Arcade Services, however, it would be preferable if we collected code coverage at the same time we built and ran unit tests. This will require https://github.com/dotnet/arcade/issues/4539 to be completed so that vstest is our default test running and we should be able to pass along parameters to cibuild to pass to vstest to collect coverage. 

We also need to ensure that the code coverage reports are picked up by the steps in the test.yaml that convert the `.coverage` files to xml and then are later converted to a report and uploaded to AzDO.

**Comment by markwilkie** [comment]
Looks like this can be closed now based on the merged PR.
