### ISSUE TITLE
[PKPIs] AzureDevOpsTimeline should normalize the SourceBranch

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#4553]
BAR stores the branches as normalized (ie master vs. refs/heads/master), and so should AzureDevOpsTimeline (Kusto).

- [x] Normalize the branch name in the build object
- [x] Update longest build path code to not append refs/heads/ to the branch name
- [ ] Update power bi reports which currently work around the difference between BAR and Kusto

**Comment by ChadNedzlek** [comment]
Which direction are we going to "normalize" to? "refs/heads/master" or "master"?  I guess if it's "branch name" then "master" is correct. "refs/heads/master" is... something else. :-) I don't know the right git terminology.

**Comment by adiaaida** [comment]
We are going to normalize to branch name, ie master. That is what BAR recently switched to.

**Comment by adiaaida** [comment]
All but the Power BI changes have been done for this issue.

**Comment by adiaaida** [comment]
@chcosta once this change is rolled out, we will need to change whatever branch comparison we do in the power bi report to map branches between BAR and Kusto (they are now the same), assuming that in all of the changes you made, you didn't take away that map.

**Comment by chcosta** [comment]
I'd expect this to just work.  I think the only thing we do in PowerBI is strip off "refs/heads/" (if present) and do the comparison

**Comment by adiaaida** [comment]
I figured the same. Once we rollout, we'll need to make the change to the power bi report.
