### ISSUE TITLE
Maestro not identifying all versions correctly.

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4559]
Some of the symbol packages and VS redist packages don't end up with correct versions in BAR. I thought these come directly from the nupkg itself, so something else might be going on:

```
  Downloading asset assets/symbols/VS.Redist.Common.AspNetCore.SharedFramework.x86.3.1.3.1.1-servicing.19615.10.symbols.nupkg
    Failed to download asset, errors shown below:
      Blob uri 'https://dev.azure.com/dnceng/internal/_apis/build/builds/458370/artifacts for assets/symbols/VS.Redist.Common.AspNetCore.SharedFramework.x86.3.1.3.1.1-servicing.19615.10.symbols.nupkg is of an unknown type
      Failed to download https://pkgs.dev.azure.com/dnceng/_apis/packaging/feeds/dotnet3.1-internal-symbols/nuget/packages/VS.Redist.Common.AspNetCore.SharedFramework.x86/versions/3.1.3.1.1-servicing.19615.10/content: Response status code does not indicate success: 400 (Bad Request - The package's version isn't formatted correctly. (DevOps Activity ID: 9711303E-8C92-4733-881F-FC092871AE61)).
  Downloading asset assets/symbols/VS.Redist.Common.AspNetCore.SharedFramework.x64.3.1.3.1.1-servicing.19615.10.symbols.nupkg
    Failed to download asset, errors shown below:
      Blob uri 'https://dev.azure.com/dnceng/internal/_apis/build/builds/458370/artifacts for assets/symbols/VS.Redist.Common.AspNetCore.SharedFramework.x64.3.1.3.1.1-servicing.19615.10.symbols.nupkg is of an unknown type
      Failed to download https://pkgs.dev.azure.com/dnceng/_apis/packaging/feeds/dotnet3.1-internal-symbols/nuget/packages/VS.Redist.Common.AspNetCore.SharedFramework.x64/versions/3.1.3.1.1-servicing.19615.10/content: Response status code does not indicate success: 400 (Bad Request - The package's version isn't formatted correctly. (DevOps Activity ID: AD4567C4-1648-4FE9-835C-5C36BF72A4B9)).

```

3.1.3.1.1-servicing.19615.10 is not the version of that package.

**Comment by JohnTortugo** [comment]
The issue here is that the branch producing those assets is using a version of Arcade.SDK + Maestro.Tasks + VersionTools that doesn't have the change you proposed in this PR: https://github.com/dotnet/arcade-services/pull/749

Here is the analyze:


SDK used in aspnet  core release 3.0/3.1 branches:

        Microsoft.DotNet.Arcade.Sdk @ 1.0.0-beta.19607.3
        Repository:    https://github.com/dotnet/arcade
        Branch:        release/3.x
        Commit:        4d80b9cfa53e309c8f685abff3512f60c3d8a3d1
        Build Number:  20191207.3
        Date Produced: 12/7/2019 10:35 AM
        Build Link:    https://dev.azure.com/dnceng/internal/_build/results?buildId=450466
        BAR Build Id:  37141

That SDK uses this Maestro.Tasks:

        Repository:    https://github.com/dotnet/arcade-services
        Branch:        production
        Commit:        a449ef723256ae11c95a4869ef70e756daaa7f36
        Build Number:  20191030.2
        Date Produced: 10/30/2019 8:08 AM
        Build Link:    https://dev.azure.com/dnceng/internal/_build/results?buildId=407404
        BAR Build Id:  33291

That Maestro.Tasks uses a VersionTools package that does not have the change made in this PR: https://github.com/dotnet/arcade-services/pull/749

/cc @dougbu

**Comment by dougbu** [comment]
@JohnTortugo why **not** port dotnet/arcade-services#749 to the 'release/3.x' branch? These versioning differences are a constant source of annoyance and confusion.

**Comment by riarenas** [comment]
@dougbu I *think* this is just a matter of updating arcade for the branches that are seeing this.

Both the 3.x and master versions of arcade use the same version of the maestro tasks.

release/3.x: https://github.com/dotnet/arcade/blob/d4a1ce6278134f5dc25843e228d0498203031e61/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/Versions.props#L9

master: https://github.com/dotnet/arcade/blob/ade7c8cb46ba88f5e698c91da9e7605619e34b6c/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/Versions.props#L9

**Comment by JohnTortugo** [comment]
@dougbu - It's what @riarenas said, you just need to update to a newer version of Arcade SDK in the release branches.

**Comment by JohnTortugo** [comment]
@dougbu - please let me know if there is something I can help with here.

**Comment by JohnTortugo** [comment]
Ping.

**Comment by mmitche** [comment]
I think this is fixed in the current 3.x arcade update, which will go out on Tuesday when branches open.

**Comment by dougbu** [comment]
Agreed. Thanks for the confirmation 3.x was fixed too 😺
