### ISSUE TITLE
System.SR.vb(20,1): error BC30012 : '#If' block must end with a matching '#End If'

### ISSUE THREAD

**Issue by RussKie** [dotnet/arcade#4593]
-  Is this issue blocking: **yes**
-  Is this issue causing unreasonable pain: **yes**

The latest update from Arcade (https://github.com/dotnet/winforms/pull/2624) fails [Windows Forms builds](https://dev.azure.com/dnceng/public/_build/results?buildId=473029&view=logs&jobId=7c8326b9-0a5f-532a-e6de-db8515c72d9a&j=7c8326b9-0a5f-532a-e6de-db8515c72d9a&t=cab6e3f0-aa10-5bbb-514b-fc6a638553f8) with a peculiar error:
```
C:\Development\winforms\artifacts\obj\Microsoft.VisualBasic.Forms\Debug\netcoreapp5.0\System.SR.vb(21,9): 
error BC32035: Attribute specifier is not a complete statement. Use a line continuation to apply the attribute to the following statement. [C:\Development\winforms\src\Microsoft.VisualBasic.Forms\src\Microsoft.VisualBasic.Forms.vbproj]
C:\Development\winforms\artifacts\obj\Microsoft.VisualBasic.Forms\Debug\netcoreapp5.0\System.SR.vb(20,1): 
error BC30012: '#If' block must end with a matching '#End If'. [C:\Development\winforms\src\Microsoft.VisualBasic.Forms\src\Microsoft.VisualBasic.Forms.vbproj]
```

Here's the generated file: [System.SR.vb](https://github.com/dotnet/arcade/files/4028858/System.SR.vb.txt)
The offending snippet:
```vb
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
#If Not NET20 Then
        <Global.System.Runtime.CompilerServices.MethodImpl(Global.System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)>
#End If
        Friend Shared Function GetResourceString(ByVal resourceKey As String, Optional ByVal defaultValue As String = Nothing) As String
            Return ResourceManager.GetString(resourceKey, Culture)
        End Function
        ''' <summary>File not found.</summary>
        Friend Shared ReadOnly Property [ID53] As String
          Get
            Return GetResourceString("ID53")
          End Get
        End Property
```

Before the update there were no conditionals present, e.g.:
```vb
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo

        <Global.System.Runtime.CompilerServices.MethodImpl(Global.System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)>
        Friend Shared Function GetResourceString(ByVal resourceKey As String, Optional ByVal defaultValue As String = Nothing) As String
            Return ResourceManager.GetString(resourceKey, Culture)
        End Function
        ''' <summary>File not found.</summary>
        Friend Shared ReadOnly Property ID53 As String
          Get
            Return GetResourceString("ID53")
          End Get
        End Property
```

**Comment by riarenas** [comment]
I think this came from https://github.com/dotnet/arcade/pull/2208.

@tmat any suggestions here?

**Comment by tmat** [comment]
Oops. Fixing.

**Comment by tmat** [comment]
I did not realize VB does not support `#if def` on custom attributes :-|

**Comment by RussKie** [comment]
> I did not realize VB does not support `#if def` around custom attributes :-|

It is not that it doesn't support it, it is that the wrapping it different to what c# supports.

https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/directives/if-then-else-directives
![image](https://user-images.githubusercontent.com/4403806/71935970-422d3500-31fc-11ea-97f1-2bb151f35327.png)

**Comment by tmat** [comment]
Yeah, you need to repeat the whole signature. It doesn't really matter, we don't have any projects that build against NET20 in VB. So this is not really needed.
