### ISSUE TITLE
[darc/maestro++] gather-drop sometimes unable to download some assets

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4598]
gather-drop appears to not download some package assets correctly:

Sdk/3.1.101-servicing-014848/VS.Redist.Common.NetCore.Templates.x86.2.1.3.1.101-servicing-014848.nupkg

The attempt was made to download from: 

https://pkgs.dev.azure.com/dnceng/_apis/packaging/feeds/dotnet3.1-internal-transport/nuget/packages/3.1.101-servicing-014848/VS.Redist.Common.NetCore.Templates.x86.2.1/versions/3.1.101-servicing-014848/content

Which appears correct, but fails.

**Comment by mmitche** [comment]
This is because these are getting added to the manifest as blobs, but published as packages. I think this might be incorrect from the standpoint of the VS redist packages.

**Comment by mmitche** [comment]
Alright, so what's going on here is that these are classified as in the packages category by the file extension of the blob, and thus we try and push them to a feed.  The push works fine.

When we go to download the package, we don't know how to correctly extract the package name (since it contains blob path elements) , and thus we attempt to ask AzDO for the content from the wrong URL.

Two possibilities:
- Remove publishing of blobs to AzDO feeds. It's not entirely clear why blobs are getting published to nuget feeds in the first place.  This PR enabled it: https://github.com/dotnet/arcade/pull/3937 but it's not entirely clear why.  @riarenas Do you remember why?
- Alter the download logic to recognize that a package can't have path elements, strip them away, and this under a workaround flag.

/cc @JohnTortugo 

I think this is what is behind #4559

**Comment by riarenas** [comment]
> Remove publishing of blobs to AzDO feeds. It's not entirely clear why blobs are getting published to nuget feeds in the first place. This PR enabled it: #3937 but it's not entirely clear why. @riarenas Do you remember why?

I believe this was a conflict with ONE package produced from the core-sdk repo that broke their build when attempting to move to the new publishing infra. It might have been just a hasty fix to unblock the overall release and perhaps we can dig into the actual issue in the core-sdk publishing now.

**Comment by mmitche** [comment]
Okay. I think I'm inclined to unblock gather-drop with a workaround, then remove publishing of packages (including symbol packages) to AzDO feeds in master, make sure that doesn't break anything, then backport to 3.x and remove the workaround.

**Comment by mmitche** [comment]
After https://github.com/dotnet/arcade-services/pull/869 there are a still a few symbol packages that do not download properly due to incorrectly identified versions.  It looks like this will be fixed in the next build,. as the version identifier was upgraded in the new Maestro tasks version in the arcade release/3.x branch.
