### ISSUE TITLE
[darc/maestro++] Remove RPR - Point ChannelReleasePipeline to the empty release pipelines

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4602]
Point ChannelReleasePipeline definitions in BAR to the empty release pipelines. Essentially disabling the use of the current release pipelines.

**Comment by JohnTortugo** [comment]
@mmitche @riarenas - I plan to change all ChannelReleasePipelines entries to point to the [empty release pipeline](https://dnceng.visualstudio.com/internal/_release?view=all&_a=releases&definitionId=73) today. Please let me know if you have any objection to that.

**Comment by riarenas** [comment]
Let's wait until we're all in the office. Dealing with any potential fallout while we're all from home doesn't seem ideal.

**Comment by riarenas** [comment]
Unless this is blocking any other work.

**Comment by riarenas** [comment]
Just realized we definitely can't do this yet. Arcade still uses the release pipeline to publish from the validation to the latest channel. We will need to move Arcade-Validation to call the new pipeline as part of its build once it's ready.

**Comment by mmitche** [comment]
> Just realized we definitely can't do this yet. Arcade still uses the release pipeline to publish from the validation to the latest channel. We will need to move Arcade-Validation to call the new pipeline as part of its build once it's ready.

Is that true? I think validation and latest/3 eng publish to all the same feeds and thus you dont' actually need the RP for them.

**Comment by riarenas** [comment]
> Is that true? I think validation and latest/3 eng publish to all the same feeds and thus you dont' actually need the RP for them.

Yeah I'm just thinking about the sleet feeds. So it might be fine? is everyone getting arcade now from the azdo feeds?

**Comment by JohnTortugo** [comment]
I'm holding this until we get a build promotion pipeline that we can use in Arcade-validation to promote Arcade builds. No reason to hurry this current issue. I'm working on the other ones.

**Comment by JohnTortugo** [comment]
This is done now.
