### ISSUE TITLE
[darc/maestro++] Remove RPR - Channels should be assigned to the build only when the assets are published

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4603]
BuildChannel should be created only when the assets are published. BuildChannel creation should be decoupled from Build creation.

**Comment by riarenas** [comment]
Reopening and moving to rollout.

**Comment by riarenas** [comment]
This has been rolled out in a disabled state behind a feature flag.

@JohnTortugo could you create an issue to:
* Enable this feature when all the prerequisite work is completed
* Remove the feature flag

**Comment by JohnTortugo** [comment]
Sure thing. Thanks.

**Comment by riarenas** [comment]
Thanks! Closing.
