### ISSUE TITLE
[darc/maestro++] Remove RPR - Remove need of PublishUsingPipelines from Arcade SDK

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4604]
Remove need of PublishUsingPipelines from Arcade SDK. Essentially assume that the parameter is always set to true.

**Comment by JohnTortugo** [comment]
@mmitche @riarenas - We should still support copying files to the source build publishing directory, right?

/cc @dagood

**Comment by dagood** [comment]
> We should still support copying files to the source build publishing directory, right?

I don't follow, what's the connection to `PublishUsingPipelines`?

/cc @crummel @adaggarwal @dseefeld

**Comment by JohnTortugo** [comment]
We are changing Arcade SDK to assume that `PublishUsingPipelines` is always true. That means that Publish.proj won't publish any asset to feed or storage locations. My question here is whether the copying of the files to the source build publishing directory should be an exception to that or not.

I guess I can also put it differently: will Maestro++ also control publishing to source build directory? I don't think it will.. but I'm really nothing familiar with source build requirements.
