### ISSUE TITLE
Don't publish blobs as packages

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4608]
When publishing, we often push nupkg blobs to package feeds.  There are two major cases of these:
- **Symbol packages** - These are intentionally pushed to a package feed and can probably stay this way.
- **Other packages that are blobs** - We recognize any blob with a .nupkg extension as a package and then push it to a package feed. According to @riarenas this was because of a one-off issue in core-sdk.

The second case should be changed, and we should push .nupkgs to the normal storage locations.

**Comment by riarenas** [comment]
This hasn't caused any problems. If it does, we'll revisit.
