### ISSUE TITLE
Add a new step to build definition(s) that check signed packages are compliant

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#462]
We need a way to check that all packages that we publish are signed.

This is a follow up issue from @tmat comment here: https://github.com/dotnet/arcade/issues/295#issuecomment-410909839

**Comment by maririos** [comment]
More than packages being signed, we also need to validate that all assets are compliant, that they got published, etc. 
Maybe change the title to reflect that?

**Comment by JohnTortugo** [comment]
Updated the title. Can you please post here what exactly should we check to gurantee the asset is compliant?

**Comment by markwilkie** [comment]
For now, I'm putting this into the sign tool epic.  I recognize it may be a separate task, but it seems part of parcel.

Microbuild has an implementation of this and we should use it.

**Comment by JohnTortugo** [comment]
@natemcmaster commented that aspnetcore uses a validation tool written by @joeloff that is able to validate .dll, .exe, .msi, .nupkg, etc. We should consider using that alternative. 

On @natemcmaster words:

> He [@joeloff] wrote an awesome tool for validating code signing on .dll, .nupkg, .msi, etc. We’re using it on aspnetcore and it’s been really helpful. The source for this tool is currently private, but if we can make it open source, I think it would be a great addition to dotnet/arcade.
> 
> https://devdiv.visualstudio.com/DevDiv/_git/WebTools-InternalTools?path=%2FSignCheck&version=GBmaster

**Comment by sunandabalu** [comment]
@JohnTortugo Looks like this is handled here - https://github.com/dotnet/arcade/blob/master/eng/common/SigningValidation.proj. Is there anything more left here?

**Comment by JohnTortugo** [comment]
Nope. Thanks for checking.
