### ISSUE TITLE
Issue template is unclear: how am I expected to fill out the questions?

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#4629]
-  Is this issue blocking (yes/no): no
-  Is this issue causing unreasonable pain (yes/no): no

I have to type `: no` above, and that's just a guess.

Thoughts:
* Include the `: ` to make it clearer what format is expected and reduce typing?
* Include both options as separate lines and let the user delete the one that doesn't apply?
* Include brief instructions in an HTML comment?

Right now there's both unnecessary thought and typing involved--let me be lazy! 😄 

Without a clear standard it's also harder for tooling to read.

@markwilkie

**Comment by riarenas** [comment]
Maybe we should make them checkboxes? We also probably need a definition for what each question means. We've had:
* Issues marked as blocking, but with no explanation of what is actually blocked.
* Issues marked as blocking with known workarounds in the issue description. Is an issue that has a known workaround blocking?
* Issues marked as causing unreasonable pain, that don't actually seem all that painful (Pain is subjective after all)

**Comment by dagood** [comment]
I like that idea.

I have a minor concern that checkboxes would encourage people to post the issue *then* check the box, because it's easier than adding the `x` in the right spot in edit mode. Then, tooling could get confused because the initial post would be "no/no" but edited to "yes/yes". But maybe any theoretical tooling needs to handle this anyway--the answer may change over time as the issue becomes more understood.

**Comment by dagood** [comment]
Fixed by https://github.com/dotnet/arcade/pull/4917.
