### ISSUE TITLE
Warning when running build.sh from mac root: unrecognized option `--dereference-recursive

### ISSUE THREAD

**Issue by hughbe** [dotnet/arcade#4634]
-  Is this issue blocking: no
-  Is this issue causing unreasonable pain: no

```
hugh@Hughs-MacBook-Air arcade % ./build.sh 
grep: unrecognized option `--dereference-recursive'
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
```

I'm on a mac

**Comment by riarenas** [comment]
Looks like this is coming from https://github.com/dotnet/arcade/blob/6655dd01031c68712f56d6e5c7b2ccfff589645d/eng/configure-toolset.sh#L16

which was added in https://github.com/dotnet/arcade/pull/4272

@chcosta how would you like to handle this?

**Comment by riarenas** [comment]
It looks like `--dereference-recursive` is `-R` and that looks suppported in mac?
