### ISSUE TITLE
Consider TRX support for xunit-reporter

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#4655]
See discussion [here](https://github.com/dotnet/aspnetcore/pull/18274#issuecomment-575868757)

ASP would like to ingest their XUnit results to Kusto so as to be able to make complex queries across their tests and preserve results longer than AzDO does.  I suggested they use it without realizing it only supported XML.

Doing this fix would basically mean transcribing TRX to XML in xunit-reporter.py, I don't expect we want to teach the DataMigrationProcessor to do TRX as this is not the primary reporter used; that's a discussion for the Arcade triage folks.

**Comment by markwilkie** [comment]
kicking this out to triage.

**Comment by MattGal** [comment]
I think @ChadNedzlek's current epic may completely obviate all the reporters, but Xunit-Reporter is also pretty dead given we've chosen to not make it work in cross-arch docker scenarios as well.

**Comment by ChadNedzlek** [comment]
It will change the reporters, _something_ in arcade needs to produce a stable output that we can read.  So there needs to be some sort of TRX -> stable thing layer in arcade.  But I'm pretty sure xunit-reporter is already dead (we no longer read the events it sends, so it's just uploading a bunch of files that get ignored)

**Comment by MattGal** [comment]
Pretty sure it's still quite in use, and still works, or there wouldn't be entries like this:

```
WorkItems
| where Queued> ago(1d)
| where FailCount != 0 or PassCount != 0
```
shows ~87K work items doing this in the last day.  Also, I routinely try to gently say "hey turn this off and stop using it?" to the folks in Runtime and every time I do they point out they still depend on it for... something involving kusto queries and test reliability analysis or something.

**Comment by ChadNedzlek** [comment]
No, we now read the data directly out of AzDO, not the "xunit report". :-) They wouldn't stop using it, so we just stopped listening.

**Comment by MattGal** [comment]
oh wow cool.  Yeah then we can just make the property do nothing then.
