### ISSUE TITLE
Git checkout failed with darc insertion PRs

### ISSUE THREAD

**Issue by sfoslund** [dotnet/arcade#4659]
We are seeing failures with darc insertion PRs into dotnet/toolset with error message `Git checkout failed`. See examples: dotnet/toolset#4115, dotnet/toolset#4102, and dotnet/sdk#4193

**Comment by JohnTortugo** [comment]
@sfoslund - Is this blocking?

@MattGal - There is an ongoing inviestigation about this right?

**Comment by MattGal** [comment]
I'm unaware of an existing issue for this, we can take this into FR though.  @chcosta any idea?

**Comment by sfoslund** [comment]
@JohnTortugo No, not blocking at the moment.

**Comment by sfoslund** [comment]
This issue was resolved when new updates were pushed to the PRs, but we're also seeing similar failures in new PRs. For example, [this one](https://github.com/dotnet/toolset/pull/4120/checks?check_run_id=402972090) is failing with the message `Unhandled: Not found SourceFolder: /home/vsts/work/1/s/artifacts`

**Comment by riarenas** [comment]
@sfoslund that build failed because of an error in a previous job:

```
./build.sh --pack --publish --ci --test --configuration Release --docker rhel --architecture x64
(node:3554) Warning: Use Cipheriv for counter mode of aes-256-ctr
========================== Starting Command Output ===========================
(node:3554) Warning: Use Cipheriv for counter mode of aes-256-ctr
/bin/bash --noprofile --norc /home/vsts/work/_temp/b9f7d2c0-3629-4351-b515-6e0387489e92.sh
Using requested image: rhel
Building Docker Container using Dockerfile: scripts/docker/rhel
Sending build context to Docker daemon  3.072kB

Step 1/13 : FROM microsoft/dotnet-buildtools-prereqs:rhel-7-rpmpkg-e1b4a89-20175311035359
unexpected EOF
##[error]Bash exited with code '1
``` 

which I assume failed to build things into where you were expecting to find them during the log upload job.
Are the similar failures you are seeing all similar to that error? the ./build.sh script is managed by the repo, so there might be something worth looking at how that docker image is being pulled from within the script?

@MattGal I've seen some noise about git checkout issues so I'm adding this to FR to think about in case it comes back.

**Comment by MattGal** [comment]
Just sent partners mail about this, there's also https://github.com/dotnet/arcade/issues/4667 tracking it.  
I'll keep both issues active and assigned to me until the rollback occurs, or we can just close this one;  the AzDO folks definitely know about it and are actively working to fix it.

**Comment by MattGal** [comment]
As noted in #4667 this should be fixed , just keeping both issues in "Validate" until EOD.

**Comment by MattGal** [comment]
The rollback seems to be holding, I am closing this issue.
