### ISSUE TITLE
Git checkout failing on build jobs

### ISSUE THREAD

**Issue by jaredpar** [dotnet/arcade#4667]
Various builds are failing during checkout of a job with a message that the commit is missing. Typically in this form:

> ##[command]git checkout --progress --force 697271c1362741e8a6ccaaf2ffae0bd2a082a70d
fatal: reference is not a tree: 697271c1362741e8a6ccaaf2ffae0bd2a082a70d
##[warning]Git checkout failed on shallow repository, this might because of git fetch with depth '5' doesn't include the checkout commit '697271c1362741e8a6ccaaf2ffae0bd2a082a70d'. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=829603)
##[error]Git checkout failed with exit code: 128

This is a bug in the [AzDO feature](https://mseng.visualstudio.com/AzureDevOps/_workitems/edit/1529338) which causes all jobs in a build to use the same commit SHA. Effectively a job in a build will fail if either of the following happen between when the job is queued and when it begins executing:

- The developer pushes a new commit to their PR 
- A different PR is merged into the target branch

The underlying problem is best explained by examining the following PR and build failure combo:

- PR https://github.com/dotnet/roslyn/pull/40998/commits
- Build https://dev.azure.com/dnceng/public/_build/results?buildId=491794

@dibarbet pushes dotnet/roslyn@5fd5a858a639c8856aec50db1623836d5736d66a on 1/21. The build runs by merging the commit into current master HEAD which is dotnet/roslyn@485649c321aa705ed752bc737ae374cc391e28a8. This results in merge commit dotnet/roslyn@697271c1362741e8a6cc. The build job kicks off against the merge commit. All of the jobs except Mac complete on 1/21
 
@dibarbet pushes dotnet/roslyn@2f812ba2ab1d06663bc9b83730ed5dd5b579210d on 1/22. This creates a new merge commit in his pull request branch and hence orphans dotnet/roslyn@697271c1362741e8a6cc from the perspective of refs/pull/40998/merge. The MacOS test from 1/21 finally begins running, it does a simple fetch on refs/pull/40998/merge. This does not pull down dotnet/roslyn@697271c1362741e8a6cc because that commit isn't parented to any of the remotes that AzDO fetches. Hence the attempt to checkout dotnet/roslyn@697271c1362741e8a6cc fails.

This is happening on a number of builds as indicated below.

Failing Builds:
- https://dev.azure.com/dnceng/public/_build/results?buildId=491794&view=results
- https://dev.azure.com/dnceng/public/_build/results?buildId=491203&view=logs
- https://dnceng.visualstudio.com/public/_build/results?buildId=491182
- https://dev.azure.com/dnceng/public/_build/results?buildId=491790&view=results
- https://dev.azure.com/dnceng/public/_build/results?buildId=492803&view=logs&j=726c32c5-2761-5cc5-d548-4557dc0ed42f&t=58d1be2d-9208-5f18-eef9-a74c742e15f8
- https://dev.azure.com/dnceng/public/_build/results?buildId=492812&view=logs&j=c7d55675-1894-5242-0dc2-83f89261ea24&t=59764339-ec44-5423-f405-c67dd468463c

ICM Ticket https://icm.ad.msft.net/imp/v3/incidents/details/171862607/home

**Comment by MattGal** [comment]
This should be resolved via rollback but I'll keep it in validate until EOD while I monitor some of the affected builds.

**Comment by MattGal** [comment]
The rollback seems to be holding, I am closing this issue.
