### ISSUE TITLE
[darc/maestro++] darc add-channel should tell you the ID

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#4670]
-  Is this issue blocking: no
-  Is this issue causing unreasonable pain: yes

When adding a channel here is the flow:
1. darc add-channel --name "Pizza"
1. darc get-channels | grep "Pizza", find the id it reports
1. modify arcade/eng/common/post-build.yml, which requires the channel id

The second step seems... unnecessary. Since you _need_ the id to make progress, and you will, 100% of the time, need it, we should report it from the add-channel command.

**Comment by riarenas** [comment]
Reopening and moving to rollout (for my sanity when compiling the release notes)

**Comment by riarenas** [comment]
The fix for this has been rolled out.
