### ISSUE TITLE
Remove Release Pipeline Runner - Make Arcade-Validation use the new Build Promotion pipeline

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4677]
-  Is this issue blocking: no
-  Is this issue causing unreasonable pain: no

Soon we'll have a build pipeline that is able to promote builds after the fact to different Maestro++ channels. This issue is to [make arcade-validation](https://github.com/dotnet/arcade-validation/blob/master/eng/validation/update-channel.ps1) use that pipeline.

**Comment by jcagme** [comment]
Moving to the "Releases are quick and have high confidence" Epic since I'll close the "Releases are fast and have high confidence"
