### ISSUE TITLE
Add support for running binskim 

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#468]
Today, aspnet runs [binskim](https://github.com/Microsoft/binskim), a static analysis tool for security isseus. It would be good to add this to the Arcade SDK.

https://github.com/Microsoft/binskim
https://www.nuget.org/packages/Microsoft.CodeAnalysis.BinSkim/

**Comment by markwilkie** [comment]
@jonfortescue - what binskim part of the 1ES offerings Jon?

**Comment by jonfortescue** [comment]
Yes, it's part of the [Secure Development Tools](https://www.1eswiki.com/wiki/Secure_Development_Tools_VSTS_Extension) VSTS extension and it's also supported by Guardian. I think it's outside of the scope of what we want to do with Arcade.

**Comment by tmat** [comment]
>  I think it's outside of the scope of what we want to do with Arcade.

I agree. We should definitely run it in MicroBuild as a build step in YAML definition but not integrate it to Arcade.

**Comment by markwilkie** [comment]
Setup as a VSTS template

**Comment by jonfortescue** [comment]
As an update for this -- this will now be handled once [this](https://github.com/dotnet/core-eng/issues/6049) PR goes through. We're not planning to support doing this as part of builds, but rather as part of release definitions.
