### ISSUE TITLE
[darc/maestro++] gather-drop should produce nupkg release layout

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4683]
Gather drop should produce a layout that is usable by the RM pipeline to publish the final packages, rather than use @dagood's tool as an intermediary.

Example layout: \\vsufile\patches\sign\NET\NET_CORE\3.1.1\publish_files\nuget

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade-services/pull/955

**Comment by riarenas** [comment]
This is rolled out.
