### ISSUE TITLE
Remove Release Pipeline Runner - Patch Darc add-build-to-channel to call build promotion pipeline

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4686]
-  Is this issue blocking: no
-  Is this issue causing unreasonable pain: no

Patch Darc `add-build-to-channel` operation to call the new build promotion pipeline. We need to make the operation call the pipeline so that we make sure that the assets are published to the right location - this was being done by the release pipelines which we are now deleting.

**Comment by riarenas** [comment]
This is now rolled out.
