### ISSUE TITLE
Consider using .txt instead of .html for file attachment in AzDO test runs

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/arcade#4695]
-  Is this issue blocking: no
-  Is this issue causing unreasonable pain: no

Right now if you want to download the console.log of a Helix test run in dotnet/runtime you need to download the UploadFileResults.html, open it in your browser, click and download the console.log and finally open it.

I recently saw that AzDO renders a preview of .txt files so if we switch to that we'd save downloading the .html file. I tried it out by adding a sample .txt version via the API:

![image](https://user-images.githubusercontent.com/1376924/73202461-64e7a500-413b-11ea-820d-e82af965dcc8.png)

I can send a PR unless there's a reason to keep using .html 😄

**Comment by markwilkie** [comment]
Oh interesting!  @alexperovich - any reason not to switch to txt?  The preview is kinda nice for sure.

**Comment by alexperovich** [comment]
txt is fine. If they make the links in the txt file work then I'm all for it.
