### ISSUE TITLE
Add AssemblyResolver to Tasks libraries targeting .NET Framework

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#47]
See https://github.com/dotnet/buildtools/pull/1943. Without this resolver it will become very difficult to align our assembly dependencies across our tasks when running on .NET Framework.

**Comment by markwilkie** [comment]
@weshaggard - anything more actionable here?

**Comment by weshaggard** [comment]
Yes we need to port the AssemblyResolver we currently use in BuildTools to Arcade (https://github.com/dotnet/buildtools/blob/master/src/common/AssemblyResolver.cs) it is general purpose and we are going to need it for all the build tasks we use in arcade.

**Comment by adiaaida** [comment]
Closing because the parent Epic was closed. If you believe this issue should still be worked on, please re-open.
