### ISSUE TITLE
Make Helix Arcade Job Sender error / warn on non-url-usable characters for Work Item friendly names

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#4703]
-  Is this issue blocking (no)
-  Is this issue causing unreasonable pain (no)

As @HaoK notes in https://github.com/dotnet/aspnetcore/pull/18597 , if you put / in a Helix work item's friendly name we now can run the tests all the way through the system... but you can't ask about said work items to the Helix API:

Example: Go to any of the details links in this page:
https://helix.dot.net/api/2019-06-17/jobs/98f9dfa1-6b3a-4fe6-96d5-d6df2f6271c6/workitems

I believe we should either
- Force the Helix Job Sender SDK in Arcade to explicitly ban certain characters from submission to Helix (anything that has special meaning for a Uri)
or
- Automatically escape these characters before they're sent (so that reporting works)

Fixing the Helix API to tolerate these is quite non-trivial because folks naturally want to put / characters into their work items (as in this case), so it makes the most sense to have the supported entry point do this.  I favor forcibly coercing the Friendly name to a URI-friendly name and printing a warning when doing so (so as to get the attention of folks doing this).

**Comment by mjanecke** [comment]
- escape characters that are returned. 
- replace forward-slash with a dash or something, and a nice warning that what they sent was changed.

**Comment by MattGal** [comment]
> * escape characters that are returned.

Just to be clear, that means URI-escape the characters of work item friendly names logged to the terminal / msbuild

**Comment by MattGal** [comment]
This has been merged for some time, I'm going to close as Arcade has already flowed it out.
