### ISSUE TITLE
dotnet/runtime is failing to restore from internal azdo feeds

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4704]
-  Is this issue blocking: no
-  Is this issue causing unreasonable pain: yes

@safern reported that even after updating the version of .Net SDK to a recent one the dotnet/runtime builds are still failing to restore from internal azdo feeds. [Sample build is here.](https://dev.azure.com/dnceng/internal/_build/results?buildId=499590&view=logs&j=afcd0a2b-3642-5a54-8afa-6712076a5a9f&s=ff05ad62-bb9a-53b6-ce9f-72f329a63e7c&t=8eaede7c-1de5-55e5-544c-6c644c9243da&l=28)

Error message:

```
      (Restore target) -> 
         C:\Program Files\dotnet\sdk\3.0.100\NuGet.targets(123,5): error : Problem starting the plugin 'C:\Users\vsagent\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll'. Plugin 'CredentialProvider.Microsoft' failed within 5.272 seconds with exit code -1. [F:\workspace\_work\1\s\eng\common\internal\Tools.csproj]
         C:\Program Files\dotnet\sdk\3.0.100\NuGet.targets(123,5): error : Unable to load the service index for source https://devdiv.pkgs.visualstudio.com/_packaging/dotnet-core-internal-tooling/nuget/v3/index.json. [F:\workspace\_work\1\s\eng\common\internal\Tools.csproj]
       C:\Program Files\dotnet\sdk\3.0.100\NuGet.targets(123,5): error :   Response status code does not indicate success: 401 (Unauthorized). [F:\workspace\_work\1\s\eng\common\internal\Tools.csproj]
```

@markwilkie @riarenas @nkolev92

**Comment by nkolev92** [comment]
@JohnTortugo I can't see any failures in the logs you sent...are they hidden because of the retries or is there maybe a better link?

**Comment by JohnTortugo** [comment]
I updated the issue's description including the error message and also updated the link to point to the failed attempt - Attempt 1 of the build stage.

**Comment by nkolev92** [comment]
> C:\Program Files\dotnet\sdk\3.0.100\NuGet.targets

Is 3.0.100 being used on purpose?
Unfortunately it won't contain the fixes we did, as they were only added to 3.1.200

**Comment by riarenas** [comment]
Ooh, that's a good catch @nkolev92 

@safern, since these steps aren't going through Arcade, the sdk that is specified in the global.json is not being installed, so it looks like it's using whatever is on the agent?

**Comment by safern** [comment]
What is weird is that the command is calling the "repo" restored `.dotnet`.

```
[command]F:\workspace\_work\1\s\.dotnet\dotnet.exe restore F:\workspace\_work\1\s\eng\common\internal\Tools.csproj --packages F:\workspace\_work\1\s\.packages --configfile F:\workspace\_work\1\Nuget\tempNuGet_499590.config --verbosity normal
```

So I don't know why it is falling back to the machine wide dotnet.

**Comment by safern** [comment]
Could it be because of?

https://github.com/dotnet/runtime/blob/master/global.json#L3-L5

That’s the SDK we specify in global.json but we specify rollForward: true. So it should definitely pick the NuGet.targets for the 5.0.0 SDK.

**Comment by safern** [comment]
I'll increase the verbosity of the command in a follow up PR.

This is the pointed config file:
https://github.com/dotnet/runtime/blob/master/eng/internal/NuGet.config

**Comment by riarenas** [comment]
Did the changes help?

**Comment by safern** [comment]
> Did the changes help?

Yeah, the changes fixed the problem. 

I guess whenever 3.1.200 is available we could bump our global.json to that and we can then remove the workarounds.

**Comment by JohnTortugo** [comment]
I didn't look deep into this. Do you guys know why it solved the problem?

**Comment by riarenas** [comment]
Added a comment about the new sdk to try out in https://github.com/dotnet/arcade/issues/3932. @safern do you want to keep this open for some reason?

**Comment by safern** [comment]
> Do you guys know why it solved the problem?

It seems like the problem manifests when we try and hit an internal feed in a second restore in the same machine, that's when the plugin crashes. Since the repo restore doesn't hit internal feeds, I just moved the "Internal Tools Restore" which uses internal feeds, to happen before the repo restore and that fixes the problem.

It seems like the first time the plugin is loaded in  the computer everything works fine. 

> @safern do you want to keep this open for some reason?

Nope, closing. Thanks!

**Comment by markwilkie** [comment]
@riarenas - we need to do a RCA on this.  Perhaps open another issue?  This'll come back....  :(

**Comment by JohnTortugo** [comment]
I'll open another issue to look into it.

**Comment by riarenas** [comment]
My impression was that:

* The machine wide SDK doesn't have any of the nuget fixes / workarounds
* The machine SDK was being used for these initial steps, without going through Arcade, so there was no initial install of any other SDK.
* Turns out that doing two installs of the cred provider also causes problems with the current SDK in the build agents.
