### ISSUE TITLE
SkipOnMono attribute is not in Xunit namespace

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/arcade#4710]
-  Is this issue blocking: no
-  Is this issue causing unreasonable pain: no

The SkipOnMonoAttribute is in the `Microsoft.DotNet.XUnitExtensions.Attributes` namespace: https://github.com/dotnet/arcade/blob/0bee21c1e9d9ee354705e778d583f64c1390f7e2/src/Microsoft.DotNet.XUnitExtensions/src/Attributes/SkipOnMonoAttribute.cs#L5-L9

This means we need to add a using for that namespace compared to the SkipOnCoreClrAttribute which is in the default Xunit namespace.

@safern is there a reason for this special namespace?

**Comment by safern** [comment]
> @safern is there a reason for this special namespace?

I believe it was a mistake from the default of using VS to add the class to the project.

I'll put up a PR tomorrow to fix it.

**Comment by akoeplinger** [comment]
Thanks, I was already working on a PR so here you go: https://github.com/dotnet/arcade/pull/4711 :)
