### ISSUE TITLE
[PKPIs] Add unit tests for flow graph

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#4715]
When the framework for C# scenario tests for arcade-services is ready, we need to add scenario tests for the new flow graph and longest build path apis.

From @mmitche:

> I think it should be pretty simple to add some mocked up flow graphs with fake timing data, and verify that the longest path APIs come out with the right answer. Because of the complexity of our existing flow graphs, even just pulling the graphs from the various channels, serializing them in such a way as to reconstruct them in a test, etc...adding some fake timing data, would probably be enough.

**Comment by mmitche** [comment]
I'm thinking unit tests, not scenario tests for this.

**Comment by adiaaida** [comment]
Oh, where do we have unit tests for this sort of thing now?

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade-services/tree/master/src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests

**Comment by riarenas** [comment]
This test is now rolled out.
