### ISSUE TITLE
Add validation for cross org publishing / restore

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/arcade#4719]
-  Is this issue blocking - no
-  Is this issue causing unreasonable pain - yes

Arcade changes are consumed by Roslyn. At times Arcade change contains publishing changes taht break the signed build for Roslyn. When such breaks happen we're down for a the longest period of time. Recently we were down for nearly a week due to one Arcade integration. This outage cause delays in critical projects and wasted many hours of our infra team.

It would be helpful if Arcade team could add VS publishing tests to validate the signed build if there are any VS publishing changes.

**Comment by riarenas** [comment]
I'd be interested to understand more about how the arcade changes to publishing broke Roslyn. I don't believe we do anything special (or even know about) vs packages specifically. 

Could you provide some details about the scenario that broke?

**Comment by vatsalyaagrawal** [comment]
For more details of the scenario that broke please refer to https://github.com/dotnet/arcade/issues/4660

**Comment by riarenas** [comment]
Gotcha. I updated the title a bit. We do validate the publishing infrastructure, but there are specific challenges around publish and restore of packages across azure DevOps account boundaries that we can probably validate better.

One option is to add a reference to a devdiv feed in arcade-validation, which would make sure that the cross org authentication is working correctly.

**Comment by markwilkie** [comment]
@mjanecke - Any chance you could add this to the validation backlog for round II?

**Comment by vatsalyaagrawal** [comment]
@markwilkie we have another break due to Arcade changes (https://github.com/dotnet/arcade/issues/4748). Arcade breaks make life really difficult for Roslyn. Can we please take add this validation on priority.

**Comment by markwilkie** [comment]
ACK - I will raise the priority even more.  Multiple moving pieces, but we'll get it sorted.

**Comment by riarenas** [comment]
See this comment for what we think is a good way to think about getting some more meaningful validation for these scenarios

https://github.com/dotnet/arcade/issues/4748#issuecomment-582003555

> This was not a breaking change in AzDO.

> I chatted with @riarenas about this a bit, and @jaredpar expressed frustration that Arcade is breaking signed builds a lot of the time. We have the arcade-validation repo builds specifically for this purpose, but we're still missing things. This comes down to a few things:

> * dnceng is different than DevDiv
> * arcade-validation does not have enough coverage for the breadth of scenarios that show up in official builds of real repos.

> The second bullet should be one that we should be able to remedy in arcade-validation over time, but gaining that test coverage, given the complexity of official builds, will be time consuming and involve breaks in repos in the process.

> Here is what I think we should do:

> Change the arcade-validation official build to be a 'stub' build
The arcade-validation build launches a series of official builds that must pass before the build can be promoted. These builds will always include two base builds:
An arcade-validation build in dnceng
An arcade-validation build in DevDiv
In addition to those two base builds, there will be a series of identified repos, base branches, and build pipelines that must pass prior to promoting a build to the Eng - Latest channel. This set will vary over time based on where we think our test coverage is lacking. Let's say it initially includes dotnet/roslyn and dotnet/runtime.
When we encounter failures that show up in the target repos but not in the arcade-validation builds, we will investigate, determine whether the failure is our fault and determine a course of action. We will add test coverage to arcade-validation where needed. The course of action may be that the target repo needs to make changes if they were using arcade in an unsupported way/
Over time, as arcade-validation becomes a reliable measure of whether arcade will pass in all target repos, we can remove the extra validation builds to reduce flakiness and end to end validation time.
Mechanically, what it means is that arcade-validation will branch off the repos+branches we need to validate, update to the candidate version of arcade, and queue the build. The build must pass for arcade to move forward.

> One additional notes: It's important that this not be a license for repos to use arcade in non-standard ways and get support for it.

/cc @shawnro @markwilkie @Chrisboh @tkapin

**Comment by tmat** [comment]
Looking at https://github.com/dotnet/arcade/pull/4625 I must say that our YAML files are getting super complicated. The logic in YAML is impossible to test in isolation, which increases the chance of a mistake.

**Comment by vatsalyaagrawal** [comment]
@riarenas any updates on this?

**Comment by riarenas** [comment]
Not yet.

**Comment by vatsalyaagrawal** [comment]
@riarenas any updates on this?

**Comment by riarenas** [comment]
Yes: https://github.com/dotnet/arcade/issues/4932 tracks the overall effort to improve arcade reliability.

**Comment by riarenas** [comment]
@mjanecke I'm moving this issue to the new validation Epic.

**Comment by riarenas** [comment]
The overall plan now has this particular scenario as a gap now that Roslyn has moved off the current development branch of Arcade. What we should do to validate that the scenario of publishing across orgs doesn't break should be:

* Make a pipeline in devdviv that builds arcade-validation. This will make it so we both restore, and publish from feeds across org boundaries
* This will probably mean we need to refactor the current Arcade-validation build YAML such that we only validate against consumer repos once, and not from both pipelines.

**Comment by missymessa** [comment]
Closing this as projects in DevDiv are no longer taking in Arcade via the Latest channel. We can reopen this if that changes in the future.
