### ISSUE TITLE
[darc/maestro++] Consider making it possible for builds to trigger the build promotion pipeline at build creation time

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4726]
-  Is this issue blocking: no
-  Is this issue causing unreasonable pain: no

@mmitche commented that Roslyn demonstrated interest in using the new Build Promotion pipeline as a replacement for the build YAML-stages. In other words, instead of activating the channels' stages in the build creation ADO UI the build creating the assets would, at its end, actually trigger a new build of the Build Promotion pipeline to do the publishing job - quite similar to how it worked when we used Release-based publishing.

Possible benefits of this approach:

- Quicker to roll out channel / publishing updates. We wouldn't need to wait for changes in Arcade post-build files to be propagated to other repos, since the Build Promotion pipeline directly uses Arcade repo files.
- Prevent cross-org publishing issues since the Build Promotion pipeline and the feeds we use would live in the same ADO org.
- Clean up the ADO build interface.

Probably issues to overcome to accomplish this:

- How to validate the changes to the YAML stages before they are used by the Build Promotion pipeline.
- How to deal with repos that need to wait for the publishing to happen before doing something.
- How publishing errors and notifications will be handled.

/cc @mmitche  @riarenas @markwilkie

**Comment by riarenas** [comment]
Is having all the publishing information in a single pipeline still a goal? If so, this breaks that and will make it harder to debug for repos when publishing goes wrong. It was one of the main reasons why we moved to stages inside the build instead of replacing the release pipeline runner with a build pipeline runner 😁 

If that is not a goal anymore, this sounds like a good change for all the benefits you mention.

**Comment by riarenas** [comment]
Some things to take into account

* How to deal with repos that need to wait for the publishing to happen before doing something (Core-sdk's publish to latest always comes to mind) but I believe core-setup (and probably now runtime) also have such steps.

**Comment by JohnTortugo** [comment]
> If that is not a goal anymore, this sounds like a good change for all the benefits you mention.

I agree with what you're saying and _personally_ I'd like to keep the publishing stages in the same UI as the build creation. I should have make it more clear in the issue's description: the message here is 1) repos have the option to use the build promotion pipeline instead of the the post-build stages (as is today) if they want; 2) Let's discuss about the pros and cons of this idea.

AFAIU @mmitche said he is going to talk with @markwilkie about this.

**Comment by riarenas** [comment]
Yeah, I actually really like the idea:
* It makes the infrastructure and channel addition a lot easier to manage
* Repos can stop having those ugly stages that don't do anything
* Introducing a new channel is transparent to repos
* We have a lot more flexibility to make changes

So if that one goal I mentioned is not the correct way to think about it, then I'm 100% behind this.

**Comment by JohnTortugo** [comment]
IMO there are two problems with current approach: 

1) It bloats the UI big time. 
2) If we need to hot fix something in the publishing infra it will take some hopes to get to the failing repo.

**Comment by JohnTortugo** [comment]
Closing in favor of this issue https://github.com/dotnet/arcade/issues/5302 and the plan discussed here https://github.com/dotnet/arcade/issues/4283
