### ISSUE TITLE
Consider inserting empty Directory.Build.props and Directory.Build.targets as part of tool.[ps1|sh]

### ISSUE THREAD

**Issue by pranavkm** [dotnet/arcade#4727]
-  Is this issue blocking (yes/no) no
-  Is this issue causing unreasonable pain (yes/no) no

As part of this change - https://github.com/dotnet/arcade/commit/cc8fe69635c7c6e791c87540851aea75946945fa, running build.ps1 changes the temp directory for all scripts in the powershell session to use ~/artifacts/tmp directory. Projects generated in the temp folder (such as the temporary project created by `dotnet tool restore`) will now import any Directory.Build.[props | targets] file located in the root of the repo. 

The suggestion here is to generate a reset file in the temp directory that prevents the repo's Directory.Build files from being imported.

**Comment by riarenas** [comment]
@tmat?

**Comment by garath** [comment]
Triage: Not seeing much motion on this. Will close unless this is still needed.
