### ISSUE TITLE
[darc/maestro++] Darc client is failing due to bug in API result paging logic

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4728]
-  Is this issue blocking: no
-  Is this issue causing unreasonable pain: yes

GetPages methods in Darc.Client is failing because it tries to fetch one more page than the number of available pages in Maestro API result. This is one of the affected methods & culprit logic: https://github.com/dotnet/arcade-services/blob/40b0b62b2687223fce9ad78b9a002bcd14cf553b/src/Maestro/Client/src/Generated/Assets.cs#L105

Talked with @alexperovich and he said the right fix here is to patch the code generator to add a try-catch to catch 404 errors in that method and abort execution when that happens.

/cc @alexperovich @mmitche @riarenas

**Comment by JohnTortugo** [comment]
Fix merged in Arcade. I'll wait for a new version of the generator to be available and re-create the Maestro Client with it.

**Comment by mmitche** [comment]
Any idea why we didn't see this in the darc scenario tests?

**Comment by riarenas** [comment]
We actually have a test that would've caught this: https://github.com/dotnet/arcade-services/blob/master/src/Maestro/tests/Scenarios/builds.ps1 but it's not in all.ps1, so it's not running...

**Comment by mmitche** [comment]
err. dang.

**Comment by riarenas** [comment]
Reopening as this is yet to be rolled out.

**Comment by riarenas** [comment]
The latest darc versions are already fixed, but customers using the `darc-init` scripts will keep getting the bad version until we have another production rollout.

As a workaround, a version parameter can be passed to the script to install a fixed version of the tool.

`eng/common/darc-init.ps1 -darcVersion 1.1.0-beta.20081.2`

**Comment by riarenas** [comment]
This is rolled out and fixed
