### ISSUE TITLE
[darc/maestro++] Source-build-reference-packages subscriptions not triggering

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4738]
The source-build-reference-packages -> source build subscriptions appear not be properly firing: https://github.com/dotnet/source-build/pull/1430. The update works fine locally, but new builds are not appearing in the source-build repo.

**Comment by JohnTortugo** [comment]
Yeah. I was looking into that right now. I'll take the issue since I was already helping @adaggarwal to get source-build-reference-packages assets flowing.

**Comment by riarenas** [comment]
I see this in the logs `Unable to update Microsoft.Extensions.Logging to have coherency with parent Microsoft.AspNetCore.Mvc.Razor.Extensions. No matching asset found in tree. Either remove the coherency attribute or mark as pinned.`

**Comment by mmitche** [comment]
Oddly, I can update those branches locally.

**Comment by mmitche** [comment]
(release/3.0 and 3.1)

**Comment by riarenas** [comment]
Odd. I see the same error for both subscriptions:

`ffed26db-8d20-4537-d43e-08d76e1d3434`: release/3.1
`9bb4e621-18e3-4ecf-6305-08d6bc51899c`: release/3.0

**Comment by riarenas** [comment]
I wonder if we somehow swallow that particular error when updating locally through Darc?

**Comment by mmitche** [comment]
It seems unlikely. I've seen that exact error before.

**Comment by riarenas** [comment]
I also tried doing a local update-dependencies from the release/3.0 and release/3.1 branches of source-build and didn't see the coherency error.

**Comment by JohnTortugo** [comment]
I'm load balancing issues on my plate; assigning this one to @riarenas . Thanks Ricardo for taking this one.

**Comment by riarenas** [comment]
I'll try and get a repro of this tomorrow and see if I can find why it only fails when running in the service and not from darc.

**Comment by mmitche** [comment]
@riarenas Looks like another instance of this in aspnetcore-tooling->aspnetcore

https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0utSE4tKMnMzytWqFEoz0gtSlXIL0gtSgQJxXumKNjaKihFOKa5FhSkhhmWGtgqcQEAr10V3TIAAAA%253D/timespan/PT4H

**Comment by riarenas** [comment]
Does it also work through darc for that case? I'm just about to get started to look at this one today. Let me see what I can find.

**Comment by riarenas** [comment]
@mmitche I couldn't find any SQL exceptions near the triggering of the source-build-reference-packages -> source-build subscriptions. I just retriggered them again, and only see the Coherency exceptions. The sqlExceptions we saw might be a red herring.

I'll keep looking.

**Comment by riarenas** [comment]
I was able to repro this when restricting the source repo of the subscription to dotnet/extensions, which is where the asset that isn't being found for CPD is produced.
`darc update-dependencies --source-repo extensions --channel ".NET core 3 release"`

```
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to update dependencies to channel .NET core 3 release
Microsoft.DotNet.DarcLib.DarcException: Dependency Microsoft.Extensions.Logging has non-existent parent dependency Microsoft.AspNetCore.Mvc.Razor.Extensions
   at Microsoft.DotNet.DarcLib.Remote.GetRequiredCoherencyUpdatesAsync(IEnumerable`1 dependencies, IRemoteFactory remoteFactory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 481
   at Microsoft.DotNet.Darc.Operations.UpdateDependenciesOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs:line 183
```

which suggests that we're somehow incorrectly restricting the builds we visit when generating the dependency graph during the remote dependency updates. 

I'm working on modifying the `update-dependencies` command to take a source build as the root, which is pretty much what the service is doing, and see if I can find why the needed builds aren't getting picked up.

**Comment by adaggarwal** [comment]
Experiencing this again.

**Comment by riarenas** [comment]
Which subscription?

**Comment by adaggarwal** [comment]
> Which subscription?

Not getting new builds from `source-build-reference-packages` to `source-build`

**Comment by riarenas** [comment]
I see the following errors still:

`The use of the same asset 'Microsoft.NETCore.Runtime.CoreCLR', even with a different version, is currently not supported.` so it looks like the versions.details.xml files in source-build still need to be fixed.

**Comment by riarenas** [comment]
https://github.com/dotnet/source-build/issues/1470

**Comment by adaggarwal** [comment]
> I see the following errors still:
> 
> `The use of the same asset 'Microsoft.NETCore.Runtime.CoreCLR', even with a different version, is currently not supported.` so it looks like the versions.details.xml files in source-build still need to be fixed.

Ah. I see. Although, we'd just want reference-package updates. But I think coherency updates forces to peek other assets as well. Thanks for the response 👍
