### ISSUE TITLE
GetDotNetInstallScript has no retry behavior, fails on network flakiness

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#4740]
-  Is this issue blocking (no)
-  Is this issue causing unreasonable pain (no)

Reported by @333fred : https://dev.azure.com/dnceng/public/_build/results?buildId=503683&view=logs&jobId=1d3b3092-ebea-54d1-0a97-42044640f186&j=1d3b3092-ebea-54d1-0a97-42044640f186&t=229ccf78-8103-517e-b52d-eda4bea77a29

https://github.com/dotnet/arcade/blob/master/eng/common/tools.ps1#L191

We need to add basic retry logic to this function:
```
function GetDotNetInstallScript([string] $dotnetRoot) {
  $installScript = Join-Path $dotnetRoot 'dotnet-install.ps1'
  if (!(Test-Path $installScript)) {
    Create-Directory $dotnetRoot
    $ProgressPreference = 'SilentlyContinue' # Don't display the console progress UI - it's a huge perf hit
    Invoke-WebRequest "https://dot.net/$dotnetInstallScriptVersion/dotnet-install.ps1" -OutFile $installScript
  }
```

**Comment by MattGal** [comment]
@vzarytovskii - please consider Jared's feedback when adding this: (" Is there any way to have curl dump diagnostic data too?")

**Comment by vzarytovskii** [comment]
@MattGal It will be not that easy to have diagnostics with the version of cmdlet/Powershell we use. Unfortunately, in the earlier versions, Invoke-WebRequest doesn't expose much and doesn't give you much freedom.

If it is really required, I would create a separate issue for that, and migrate from Invoke-WebRequest to something more usable.

**Comment by MattGal** [comment]
> @MattGal It will be not that easy to have diagnostics with the version of cmdlet/Powershell we use. Unfortunately, in the earlier versions, Invoke-WebRequest doesn't expose much and doesn't give you much freedom.
> 
> I have added basic errors/exceptions logging on retries. If something more verbose/sophisticated is needed, I would create a separate issue for that, and migrate from Invoke-WebRequest to something more usable.

There is [an .sh version too](https://github.com/dotnet/arcade/blob/master/eng/common/tools.sh#L176)  that uses curl and does not retry.

**Comment by vzarytovskii** [comment]
@MattGal I see it uses curl’s built-in retry mechanism, is it not sufficient? IIRC, it should also retry on the connection errors.

**Comment by MattGal** [comment]
Fairly certain I have seen this fail on linux;  I believe the reason being curl's version of retry is not for all possible error scenarios.

**Comment by vzarytovskii** [comment]
@MattGal ok, makes sense, I will take a look at the shell version and include changes in the same PR
