### ISSUE TITLE
[Arcade-Services] Scenario Tests failing after moving to NetCoreInternal-Pool from Hosted VS2017 Pool

### ISSUE THREAD

**Issue by sunandabalu** [dotnet/arcade#4741]
-  Is this issue blocking (no)
-  Is this issue causing unreasonable pain (no)

https://dev.azure.com/dnceng/internal/_build/results?buildId=503821&view=logs&j=4d9f00d7-d155-5977-7b70-2e6b79720ff2&t=c5fa51d8-f4b1-5178-14fd-2c49e5155c0d

@alexperovich moved Scenario tests to use the NetCoreInternal-Pool instead of Hosted VS2017 Pool, which is breaking the powershell based scenario tests.

**Comment by riarenas** [comment]
An attempt was made to fix this with https://github.com/dotnet/arcade-services/pull/937 but that ended up breaking the tests in a different way: https://github.com/dotnet/core-eng/issues/8884. https://github.com/dotnet/arcade-services/pull/954 should resolve both issues.

**Comment by riarenas** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=514544&view=results succeeded after dotnet/arcade-services#954 was merged. Closing this.
