### ISSUE TITLE
Winforms-designer VS insertion PRs are frequently failing symbol checks

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4749]
-  Is this issue blocking: yes
-  Is this issue causing unreasonable pain: yes

@jmarolf pointed out that frequently Winforms-designer PR insertions in VS are consistently failing. Here are some insertions that fail:

- https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/221512
- https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/225457

Here are some insertions that pass:

- https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/220833
- https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/220839

This might be a timing issue, i.e., symbols take a while to be available on the symbol servers. Nevertheless, I think it deserves further investigation.

**Comment by AdamYoblick** [comment]
@JohnTortugo This kind of IS blocking us though, because we can't insert into VS without symbol checks passing. :(

**Comment by AdamYoblick** [comment]
/cc: @mmitche Merrie asked me to escalate this because we're not able to reliably insert into VS. winforms-designer builds show symbol publishing as passing, but insertion PR's into visual studio have failing symbol checks. Not sure how to troubleshoot this and could use some help. 😄

**Comment by jmarolf** [comment]
I updated to bug to say this is blocking. We are unable to insert automatically while this bug exists and someone must manually merge all insertions.

**Comment by AdamYoblick** [comment]
Even manually merging, does the Vs master build do symbol checks? Won’t it just fail further down the pipe?

________________________________

**Comment by jmarolf** [comment]
No, there is no further symbol checking in the build pipeline

**Comment by AdamYoblick** [comment]
Ah that’s good to know :)

________________________________
