### ISSUE TITLE
[darc/maestro++] Maestro++ should be able to trigger the official build for a repo

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#4754]
In order to do dependency flow without opening PRs in repos, maestro++ needs to be able to run the official build of a repository after merging the dependency updates against a fork of the target branch for the subscription.

For this to happen, Maestro++ needs to know:
* Which is the official repo for GitHub repo.
* Which build pipeline should be triggered.

In most cases we should be able to deduce this information during the dependency flow operation, but we can also add fields to the subscription creation/update form.

**Comment by mmitche** [comment]
I don't think Maestro strictly needs to be able to launch the build (though that is an option). We could also require that the branch triggers be altered to include the maestro update branch, and then Maestro would simply need to find those launched builds.

**Comment by riarenas** [comment]
Hmm, I was mostly thinking of Maestro knowing about it as we need to have a way to avoid the duplicate build when the change is merged to GitHub and back to the mirror. This definitely needs some more specifics. I'm working on a doc right now to see all the places where there are still some gaps about what Maestro actually needs to do for the new flow.

**Comment by mmitche** [comment]
The more we can correctly infer, the better. The more manual configuration is required, the more chances that those steps will be forgotten or whatnot.  Now, maybe it's as simple as the build pipeline info ends up being part of a subscription merge policy, and thus it's not possible to get wrong.

**Comment by riarenas** [comment]
I think it makes sense for Maestro++ to trigger the build. We need to monitor the build that gets triggered anyways, and being the triggerer lets us do this in an easier way instead of having a model where we have to poll the builds of the repo and search if there was a build from that branch.

We should be able to infer the build definition that we need to trigger by looking at what is in the BAR already, and in cases where this isn't straightforward (It's a new repo that has never published builds to the BAR, or a repo that switched pipelines recently), we can ask for this information when the subscription is created / updated to enable the new flow.

**Comment by riarenas** [comment]
Closing as we're closing the parent epic
