### ISSUE TITLE
[Publish] Ask BAR for a storage account and a key for where to publish build assets

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#476]
Currently build definitions have this information. It would be good if instead, the build asks BAR where the content should go.

FYI @mmitche

**Comment by maririos** [comment]
Updating issue with @mmitche comments:

" I think publishing needs to be configurable, but I’d like to move away from pre-determined storage accounts, containers etc.  It has some disadvantages:
- Security – need to pass around long lived SAS tokens or storage account keys
- Publicness/privateness of build ends up determined at build time.  I’d like to get to a point where sharing an msrc build doesn’t involve a lot of hoops.  Just a different post-build process.
- Different repos end up with vastly differently structures.
- Repos have to be careful about designing structures that don’t end up with overlapping folders (e.g. utilizing the version number in output folders)

Instead, I’d like our outputs to be pushed to locations that are determined by the build asset registry.  So for instance, you are creating a new build for the BAR, the BAR gives back a url to publish to, complete with a limited SAS token.  In general, these initial URLs are always for isolated per-build private storage.  Then, after the BAR push is finished and the build is finalized, we use that event to push out to other endpoints (myget, public storage feeds, vsts, etc.) based on the security restrictions and use of the build."

**Comment by maririos** [comment]
FYI @alexperovich @jcagme

**Comment by JohnTortugo** [comment]
As per the[ current publishing redesign plan](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/AsyncPublishing.md) I don't we'll need to implement this issue. Is that so @mmitche ?

**Comment by mmitche** [comment]
Correct
