### ISSUE TITLE
Support JUnit test results in Helix runs

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/arcade#4762]
-  Is this issue blocking (yes/no) sort of
-  Is this issue causing unreasonable pain (yes/no) I guess

We're trying to move all our tests to Helix which includes some Java and Npm tests that produce test results in Junit format. However Arcade+Helix is hardcoded to search for xunit test results. Can we add support for Junit?

**Comment by alexperovich** [comment]
The azure pipelines test reporter support works with junit files. See: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/tools/azure-pipelines/reporter/formats/junit.py#L17
The files just have to be named correctly.

The legacy test reporter that reports results to mission control only supports xunit and is being phased out, it should not be used.

**Comment by BrennanConroy** [comment]
Thanks! I thought I searched for JUnit in this repo and couldn't find anything...
