### ISSUE TITLE
BarViz shows a dotnet-windowsdesktop and dotnet/windowsdesktop for .NET 5 Dev channel

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4767]
The dotnet-windowsdesktop build is shown twice for some reason, once with the typical azdo repo shortname `dotnet-windowsdesktop` and once with the github short name `dotnet/windowsdesktop`.

Both nodes point to the same build.

**Comment by markwilkie** [comment]
Any insight @adiaaida ?  If this is no longer relevant, feel free to close.

**Comment by adiaaida** [comment]
Well, currently .Net 5 Dev is broken, so I do not know.

**Comment by adiaaida** [comment]
I am only seeing one node for windowsdesktop on barviz, so maybe this worked itself out?

**Comment by chcosta** [comment]
If you click ".NET 5 Dev" and look at the repos listed below, there's a dotnet-windowsdesktop and a dotnet/windowsdesktop

**Comment by adiaaida** [comment]
Oh it's in the list, not the graph, gotcha.

**Comment by adiaaida** [comment]
Looks like there were 4 builds that were published where the azure devops repository was set, but the Github repository was not, so ListRepositories sees the ones that are azure devops only as distinct from those that have both set.

```
select * From BuildChannels
join Builds on Builds.Id = BuildChannels.BuildId
where BuildChannels.ChannelId = 131
and Builds.AzureDevOpsRepository like '%windowsdesktop%'
and Builds.GitHubRepository is null
```

**Comment by mmitche** [comment]
Got it. So it's saying the right thing. This probably rolls into #4769 then, where we would simply have these fall off over tiem.

**Comment by chcosta** [comment]
I'm going to close this.  Feel free to re-open if you think we should change behavior here.
