### ISSUE TITLE
Introduce .NET Core 5 Release channels

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4768]
Introduce new channels for .NET Core 5 Release channels. A few channels should be initially introduced:
- .NET Core 5 Preview 1 Release
- .NET Core 5 Preview 2 Release

These will be deleted as they are no longer in use.  It's likely that two channels will be in use at some point.

**Comment by JohnTortugo** [comment]
@mmitche is this a dupe of https://github.com/dotnet/arcade/issues/4815 ?

**Comment by mmitche** [comment]
Yes
