### ISSUE TITLE
Delete old config system

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#4778]
-  Is this issue blocking: no
-  Is this issue causing unreasonable pain: no

@ericstj @Anipik should we delete the old configuration system SDK?

**Comment by Anipik** [comment]
>  should we delete the old configuration system SDK?

I think we can keep it for a reference untill the new system becomes stable. Most of the binplacing code is similar to old system. (we can always look in the history though)  
After the new configuration becomes stable and if nobody else is using it, then we can go ahead and delete it

do we need to set up something to automatically update the version number of the new sdk ?

**Comment by ViktorHofer** [comment]
> do we need to set up something to automatically update the version number of the new sdk ?

No, the package and assembly versions are handled by the Arcade SDK.

> I think we can keep it for a reference untill the new system becomes stable.

I don't want to keep stuff around just for reference. If someone wants to look at it, he/she can go back in history or look into the release branch.
