### ISSUE TITLE
Fragile native tool bundle format

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#4787]
The structure, format of native tool bundle is a bit fragile and has to be organized just-right, with the right naming conventions etc. 

The bootstrapper isn’t always named to match what the installation scripts expect, and yet-another custom installation script must be written

- a simple tool (commandline or GUI) that can take a folder as input + and a few basic parameters and build the tool-bundle automatically would be great.

**Comment by jonfortescue** [comment]
No longer installing native tools. Closing.
