### ISSUE TITLE
When a test run selects no tests, that should not be a failure

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#4789]
-  Is this issue blocking: not yet
-  Is this issue causing unreasonable pain: yes

Right now, if because of traits or whatever, a test run ends up selecting no tests, that turns into a Helix fireball failure.  This blocks some key scenarios, for example, ASP.NET core trying to run some [Quarantined] tests to determine the current status, and there isn't a super compelling reason to call this a failure and prevent this workflow.

**Comment by riarenas** [comment]
Moving this to FR. @MattGal let me know if you feel it's out of scope.

**Comment by MattGal** [comment]
@ChadNedzlek can you provide some example runs here?  I know runtime has assemblies where 0 facts actually run without this problem, so I'm having a rough time grokking this.

**Comment by ChadNedzlek** [comment]
This was brought up the the ASP.NET folks during our meeting on Friday.  I don't have a ton of details, but I'll see if I can get some.

**Comment by ChadNedzlek** [comment]
@Pilchie You brought this up during our Friday meeting.  Do you have an example where this fails?

**Comment by Pilchie** [comment]
Adding @HaoK  and @anurse - basically, we have a job that tries to run only our tests with a "Flaky" attribute, and sometimes that ends up not being anything.  We worked around it for now by running everything in those runs, but we'd like to stop that again.

**Comment by MattGal** [comment]
Can you show me the runs?  Logs / Correlation ids would be great.

**Comment by anurse** [comment]
@HaoK might be able to help here. I'm not totally sure if it was an issue in our script or in the Helix AzDO test reporter.

**Comment by HaoK** [comment]
Sure I can whip up a PR for fresh logs

**Comment by HaoK** [comment]
Here's the azdo https://dev.azure.com/dnceng/public/_build/results?buildId=515132&view=results

Doesn't look too bad actually, https://github.com/dotnet/aspnetcore/pull/18937

**Comment by ChadNedzlek** [comment]
Sounds like the problem is solved, I'm going to close this issue.
