### ISSUE TITLE
Native bootstrapping needs to support xcopy deployable tools with no installer 'exe' in the package

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#4790]
The native tool bootstrapper should not assume that the tool-bundle has an “installer” that needs to be ‘executed’. Native-tools come in all shapes and sizes – the current bootstrapper assumes much. For e.g., see Strawberry Perl – there is no exe inside; it’s just a zip that’s “installed” by “unzipping” it, that’s all. See https://github.com/dotnet/arcade/pull/2249. If there are changes being planned to the native-tools bootstrapper, the general architecture can be improved to remove such assumptions.

**Comment by jonfortescue** [comment]
No longer supporting native tools bootstrapping. Closing.
