### ISSUE TITLE
Native toolset bootstrapper should support private cache

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#4792]
The bootstrapper uses a cache under %userprofile%\.netcoreeng. This is analogous to NuGet cache; but just like “-ci” uses a private cache ($(RepoRoot)\.packages or something like that), the native tool bootstrapper should be able to use a private cache for CI builds as well (for e.g., $(RepoRoot)\.netcoreeng). 
-  NuGet provides a handy away to clear its cache (nuget locals all -clear), but there is no handy analog for clearing the native-bootstrapper cache

**Comment by jonfortescue** [comment]
wait do dollar signs cause weird markdown rendering? $test$

**Comment by jonfortescue** [comment]
Whoa that's wild. is this intended for like math or something?

Anyway, we're not installing native tools anymore so this can be closed.
