### ISSUE TITLE
Native toolset bootstrapping should have better support for shared tools

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#4793]
There should be a shared library of native-tools made available by Arcade and managed centrally. 

Currently, bundles are created ad-hoc by partners.  There should be better support / process around common tools used by multiple partners.

We can identify a bunch of common tools and make these available as standard packages. For e.g., Git, VCRedist, Python, Azure tools etc. should just be maintained by a central team and repos should be able to consume it. In turn, we can also advocate for the producers of some of these tools (VS team for e.g that produces VC Runtime), to NuGet-ify their products directly based on usage stats etc.

**Comment by jonfortescue** [comment]
Not installing native tools anymore. Closing.
