### ISSUE TITLE
[Discussion] Blockers for native toolset bootstrapping adoption in .NET Core repos

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#4795]
Arcade has a very simplistic [feature](https://github.com/dotnet/arcade/blob/master/Documentation/NativeToolBootstrapping.md) for bootstrapping a repos native toolset dependencies.  The intent of the feature is to make our repos more reliable / maintainable.  The current version of the tool works for some repos, but is far from robust or able to meet the needs of all .NET Core 5 product repos.
 
The current major blockers for repo adoption are:
 
•	[Overly simplistic configuration capability](https://github.com/dotnet/arcade/issues/2673) – can’t define tool installss per OS / RID
•	[Redundant installations](https://github.com/dotnet/arcade/issues/4780) – version checking can be fragile, and native toolset installation does none which means it may install tools that are already on the box
 
Known issues are tracked [here](https://github.com/dotnet/arcade/issues?q=is%3Aissue+is%3Aopen+native+label%3Anative-toolset-bootstrapping).  These are mostly improvement areas and not blockers to adoption.

- ASP.NET Core’s reasons for not using native tool bootstrappers are: 
  - They would prefer to use the global.json approach but are blocked by the [lack of per-OS support](https://github.com/dotnet/arcade/issues/2673)
  - They've tried to use a few bootstrappers with the Arcade installation scripts and normally find the bootstrapper [isn’t named to match](https://github.com/dotnet/arcade/issues/4787) what the installation scripts expect, then end up writing yet-another custom installation script in one of our repos

- dotnet/runtime is blocked on the two "major blockers" listed above

- bootstrapping is sufficient for wpf, but there is drastic room for improvement (see [query](https://github.com/dotnet/arcade/issues?q=is%3Aissue+is%3Aopen+native+label%3Anative-toolset-bootstrapping))

**Comment by vatsan-madhavan** [comment]
>  bootstrapping is sufficient for wpf

This following note is somewhat orthogonal to "native-tool" bootstrapping.. today WPF (and WinForms) use native-tool bootstrapping to incorporate intellisense xml's into our ref-assembly (transport) package. This is a static copy (i.e, a native-tool "bundle" containing the intellisense xml's a  a static snapshot). In theory this needs to be updated by hand periodically, but it is seldom updated. 

The general problem is that when a frequently-changing tool is consumed this way (i.e. through native-tool bootstrapping), it is very hard to maintain. This is a problem for native-tool mechanism to (somehow) solve over time. 

The specific problem (which is what is orthogonal to this issue) is that consuming and redistributing intellisense xml's (as part of ref-assemblies) is a common duty for all .NET Core repos, which is something one would expect Arcade to provide a shared turnkey infrastructure for.  We don't have a working plan for updating intellisense XML's for .NET 5... so please give us a solution in time for Preview 1 ;-)

/cc @AdamYoblick, @RussKie, @rladuca

**Comment by tmat** [comment]
@vatsan-madhavan I'm not sure I understand your scenario. Can you share details of your process of producing XML doc comment files? Are they not produced by the tool that generates the ref assembly?

**Comment by vatsan-madhavan** [comment]
No, they are not. In fact I don't believe that any of the intellisense xml's bundled with `Microsoft.WindowsDesktop.App.Ref`, `Microsoft.NetCore.App.Ref` etc. are produced alongside the ref-assemblies (or even in the respective repos).  These usually come from the docs repo. 

I tried documenting how I set it up for WPF/WinForms in 3.1 timeframe at https://github.com/dotnet/wpf/blob/release/3.1/Documentation/intellisense.md.

**Comment by ViktorHofer** [comment]
@markwilkie @chcosta we gathered these items ~two months ago and wanted to ask where we currently are in regards to improving the native toolset bootstrapping. I was just asked again if we have plans to reduce the costs for (first time) contributors and for the team.

**Comment by markwilkie** [comment]
Unfortunately, bootstrapping didn't make the cut for .NET 5....   :(

**Comment by ViktorHofer** [comment]
😢
