### ISSUE TITLE
[Versioning] Update Versioning documentation

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#480]
how repos will consume it? -> Arcade sdk .props files.

**Comment by tmat** [comment]
Consume what?

**Comment by maririos** [comment]
We want to update Arcade documentation and the versioning one to say explicitly that by consuming the Arcade SDK they consume the versioning schema defined in https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md
