### ISSUE TITLE
remove the requirement for the ApiCompat contract to be a binary

### ISSUE THREAD

**Issue by adamralph** [dotnet/arcade#4802]
-  Is this issue blocking (yes/no) - _yes_
-  Is this issue causing unreasonable pain (yes/no) - _no_

I do not want to commit the previous versions of my binaries, nor do I want to somehow bootstrap them locally for the comparison.

A common approach is for the contract to be a text file, containing the public API signatures of the previous version in C#.

**Comment by adamralph** [comment]
Any interest in this?

**Comment by markwilkie** [comment]
Any comments on this @ericstj ?

@adamralph  - could you elaborate a bit on what this is blocking please?  Maybe the scenario that has you stuck.

**Comment by adamralph** [comment]
@markwilkie basically as it says in the description:

> I do not want to commit the previous versions of my binaries, nor do I want to somehow bootstrap them locally for the comparison.
> 
> A common approach is for the contract to be a text file, containing the public API signatures of the previous version in C#.

Is there anything specific which is unclear?

**Comment by ericstj** [comment]
> I do not want to commit the previous versions of my binaries, nor do I want to somehow bootstrap them locally for the comparison.

Don't commit them.  Bootstrapping is required.  NuGet's `PacakgeDownload` feature is particularly useful at this.  API Compat's purpose is to perform comparisons of metadata to determine binary compatibility.   It's rather tightly coupled to this and changing that would really be a new tool entirely.  We don't plan on changing it to take other formats of input.

One thing to consider if you only care about exact match with text input is https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysispublicapianalyzers.  This analyzer might better suit your needs.

**Comment by adamralph** [comment]
>  API Compat's purpose is to perform comparisons of metadata to determine binary compatibility.  It's rather tightly coupled to this...

@ericstj thanks, I didn't know that. I'll take a look at Microsoft.CodeAnalysis.PublicApiAnalyzers. Thanks for your answers here.
