### ISSUE TITLE
Refactor common utilities functions into common/util.ps1

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#4822]
Some functions that currently exist in common/native/CommonLibraries.psm1 are useful outside of the context of installing native tools. For example, DownloadAndExtract, Extract-Zip, and Get-File all are useful when downloading tools outside of init-native-tools. We should consider refactoring those functions out of common/native and into a common utility powershell script

**Comment by garath** [comment]
@adiaaida Does your PR cover this?

**Comment by adiaaida** [comment]
I don't believe I ultimately did anything with this, tbh

**Comment by jonfortescue** [comment]
These still sound useful, potentially, but aren't really related to native tools work. Kicking to triage.

**Comment by adiaaida** [comment]
This hasn't come up again, but if someone is in there and doing refactoring, doing some of this could be good.
