### ISSUE TITLE
Send build information in property bag for Helix

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#4837]

**Comment by ManickaP** [comment]
Does this issue intends to propagate the build number into Jobs.Build column within `SendHelixJob` msbuild task?

**Comment by ChadNedzlek** [comment]
The Jobs.Build column is deprecated. It was used to drive mission control, which is also deprecated, and many jobs aren't correlated to a build.

This would populate the json formatted "Properties" column.  That column is designed for "stuff about this job that you won't usually query about, but you might want for diagnostic purposes (like to track down a particular failure, it's useful to know what build it came from).

**Comment by ManickaP** [comment]
I see. Well the properties should be good enough for diagnostics. Thanks for the answer.

**Comment by ChadNedzlek** [comment]
I'm curious about your scenario, what are you trying to do?  I want to make sure I inject enough information to help you.

**Comment by ManickaP** [comment]
I've been querying Kusto to hunt down some test crashes. I needed to see whether it happened in one particular test or across multiple ones from the same build. Then I needed to track down CI build to get the artifacts. I know there's job-list to get some of the artifacts, but that gets deleted after 10 days.

It would be great to be able to group jobs by the build run and to be able to easily find which pipeline started the job. I can see which PR triggered the run (`Source` column), but there's usually multiple runs per a PR and it's quite hard to pair these by the time. Also, I see in `Type` column something that should probably tell me which pipeline triggered it. But I've yet to figure out the pattern to match it, e.g. Type: `test/functional/cli/outerloop/` ==> pipeline: `runtime-libraries outerloop-windows`.

**Comment by ChadNedzlek** [comment]
My plan is to include this data in there:
* Build number
* Definition Name
* Definition ID
* URL to the build

Those things are all pretty easy to get via built-in azure pipeline variables.  Which job/stage of the pipeline (linux/windows) isn't so easily attainable, so I wasn't going to include it.

The "Type" doesn't really have a pattern.  It's just whatever the msproj file sending it chose.  "Source" should, with the most recent API, be formed by concatenating the Repository and Branch columns, so you might be able to query those directly.

**Comment by ManickaP** [comment]
It's a good set of data and that should help immensely. I'm looking forward to it. :+1:

**Comment by markwilkie** [comment]
Perhaps this is already done @ChadNedzlek ?

**Comment by ChadNedzlek** [comment]
It is not. :-)

**Comment by rokonec** [comment]
PR: https://github.com/dotnet/arcade/pull/5480
