### ISSUE TITLE
.NET Core inter-branch merge bot should be (very) smart

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4848]
.NET Core has a lot of inter-branch merges, and they generate a ton of noise. Most of the changes in the inter-branch merges are dependency files, which are hard to merge by hand. **Generally**, the right strategy for merging dependency files is that the target branch's files should be retained, whereas the rest of the files in the repo should just merge in normal fashion.

Basically, inter-branch merging needs to get optionally smarter. It needs to:
- Be context aware of version details files. Optionally choose to merge by taking the target branch's version.details.xml file completley
- Be context aware of other version files like Versions.props, global.json etc. Some changes to versions.props, global.json, etc. may be legitimate, as in they are changes that are not controlled by dependency flow. So it's not correct to just blanket take the target versions.props file.  But a merge with conflcit resolution that recognizes the content of an already merged version.details file would generate an appropriate merge

There are some other options, like separating out versions.props files for dependency flow, and those for use otherwise. You couold then make blanket rules about version.detials.xml and verisons.props as in "take my whole file". The problem is that while that reduces the cost for those two files, there still exist others that will have the same problem: global.json and the arcade files come to mind.

I think the right thing to do is generate a custom merge driver.

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

**Comment by wli3** [comment]
Any update? Timeline?

**Comment by mmitche** [comment]
No timeline. It's not scheduled at the moment. For me, right now build time is my highest priority.

**Comment by markwilkie** [comment]
Converting to an epic

**Comment by markwilkie** [comment]
@marcpopMSFT poked us about this....

**Comment by marcpopMSFT** [comment]
@markwilkie it's still a thing but we're managing with a vendor. An example you can see here: https://github.com/dotnet/sdk/pull/25403#discussion_r875245198.  I don't think any of the nuget.config changes should be merged across but it's not a big deal as darc will fix it later. We've trained our vendor to basically always take the target changes in the eng folder if there are merge conflicts and it's working ok for now.

**Comment by mmitche** [comment]
> @markwilkie it's still a thing but we're managing with a vendor. An example you can see here: [dotnet/sdk#25403 (comment)](https://github.com/dotnet/sdk/pull/25403#discussion_r875245198). I don't think any of the nuget.config changes should be merged across but it's not a big deal as darc will fix it later. We've trained our vendor to basically always take the target changes in the eng folder if there are merge conflicts and it's working ok for now.

The problem is that this is not necessarily the case 100% of the time. Added or removed dependencies, changed names, etc. etc. are not "take yours", and darc cannot fix them.

This is a case where product context is important, and the person or thing doing the inter-branch merge needs to understand that context.
