### ISSUE TITLE
Arcade 5.0.0-beta.20116.1 update broke mono/linker

### ISSUE THREAD

**Issue by marek-safar** [dotnet/arcade#4860]
https://github.com/mono/linker/pull/954 update broke build with the following error

```
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.5.0-beta3-20110-03\tasks\netcoreapp3.1\Microsoft.Managed.Core.targets(104,5): error MSB4062: The "Microsoft.CodeAnalysis.BuildTasks.MapSourceRoots" task could not be loaded from the assembly D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.5.0-beta3-20110-03\tasks\netcoreapp3.1\Microsoft.Build.Tasks.CodeAnalysis.dll. Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\a\1\s\external\cecil\Mono.Cecil.csproj]
2020-02-17T13:02:20.7290220Z ##[error].packages\microsoft.net.compilers.toolset\3.5.0-beta3-20110-03\tasks\netcoreapp3.1\Microsoft.Managed.Core.targets(104,5): error 

```

**Comment by marek-safar** [comment]
Any update on this Arcade breakage?

/cc @jaredpar

**Comment by riarenas** [comment]
Sorry I missed this before. 

@dotnet/dnceng Could FR take a look at this? We did receive a new version of microsoft.net.compilers.toolset in https://github.com/dotnet/arcade/pull/4856, but that's not the version reported in the error?

**Comment by MattGal** [comment]
Sounds good.  I'll take an initial stab and see if I can add details for whoever takes it.

**Comment by MattGal** [comment]
Based off the errors compared to master, I'm pretty sure it's this change flowing in: https://github.com/dotnet/arcade/commit/3d51396c1c07faaacc39903045ab4b4fb2b1f79c but there's so much different in Roslyn between those two commits I'm still puzzling over what it is.

**Comment by MattGal** [comment]
@jaredpar , @marek-safar FYI.

I took the mono linker repo and changed global.json to have this:
```
{
  "tools": {
    "dotnet": "3.1.101",
    "runtimes": {
      "dotnet": [
        "3.1.0"
      ]
    }
  },
```
and the build succeeded locally.

It seems that roslyn stuff built and published after [this commit](https://github.com/dotnet/roslyn/commit/4515321ba65f46b148157a82818050b774f631ca) 
doesn't work on lower .NET Core versions and ARcade / mono-linker are there.  I'm following up with the Arcade working group to know what the right guidance here is.

**Comment by MattGal** [comment]
Moving to tracking while that conversation continues via email

**Comment by jaredpar** [comment]
This is breaking local development in dotnet/runtime now. Previously it's broken aspnetcore. 

Can we move forward with adopting a 3.1 compatible runtime here? Or barring that we should pin Roslyn back before we took the dependency on `netcoreapp3.1`. Need to fix this centrally vs. fighting the fire in every repository.


@stephentoub

**Comment by markwilkie** [comment]
Echoing the email thread here:

@mmitche - should we just make the change and tell tactics at 10 today, or wait for tactics?

cc/ @riarenas to make the change if appropriate

**Comment by mmitche** [comment]
This isn't in servicing, so it doenst' really need to go through tactics.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade/pull/4914/files is up.

**Comment by riarenas** [comment]
PR has been merged and I'll nurse the build until it makes it to publishing and makes it to the channel.

**Comment by riarenas** [comment]
Tomorrow's update should include the SDK update. I'll leave this open until the dependency update PRs are opened.

**Comment by riarenas** [comment]
I triggered the mono subscription manually to validate that the SDK update fixes the original report.

**Comment by riarenas** [comment]
The SDK update wasn't enough to get the Linker update through. The repo now builds, but their integration tests are failing.

**Comment by riarenas** [comment]
https://github.com/mono/linker/pull/977 is in flight int he linker repo which should unblock the Arcade (and .NET sdk update) to go through.

**Comment by riarenas** [comment]
Arcade PR to Linker has been merged and its official build succeeded and is currently in the publishing phase: https://dev.azure.com/dnceng/internal/_build/results?buildId=543827&view=results

Closing.
