### ISSUE TITLE
Create 3.x+ style manifest for 2.x builds

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4862]
Create a 3.x style manifest out of the 2.x style builds so that the automatic tagging and future automatic VS insertion mechanisms can work without extra hoops to jump through.

Most of the BAR specific data can probably just be faked, like BAR build id's, etc.  The really important bits are the asset and version numbers.

**Comment by adiaaida** [comment]
Out of scope for #6418.

**Comment by mmitche** [comment]
Not necessary for 2.1 support at this point.
