### ISSUE TITLE
[darc/maestro++] Darc add build to channel should wait until the promotion build finishes

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4863]
-  Is this issue blocking: no
-  Is this issue causing unreasonable pain: no

Darc should wait until the promotion build created from `add-build-to-channel` operation finishes - perhaps this should be the default behavior and we have a flag to disable it. This way it can report back to the user whether or not the promotion worked. This is specially important for:

- Scripts that need to fail if the promotion fails.
- Humans so that they don't assume the promotion worked to later find out that it didn't.

/cc @riarenas @mmitche

**Comment by riarenas** [comment]
Part of this issue also involves making sure that Arcade-validation's script that moves arcade builds (https://github.com/dotnet/arcade-validation/blob/master/eng/validation/update-channel.ps1) still works after this is finished and deployed.
