### ISSUE TITLE
Old packages with wrong prerelease label still published on nuget feed

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/arcade#487]
It seems that the packages produced from this repo aren't pushed to the https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json nuget feed.

E.g. the latest version of Microsoft.DotNet.Helix.JobSender is 1.0.0-prerelease-63213-02 from 2018-08-13.

/cc @chcosta

**Comment by chcosta** [comment]
Looking

**Comment by chcosta** [comment]
The most recent version of Microsoft.DotNet.Helix.JobSender is 1.0.0-beta.18420.3.nupkg from 2018-08-20.

**Comment by chcosta** [comment]
The prerelease label appears to have been changed on 8/13 - https://github.com/dotnet/arcade/commit/d3a73e5629eced2995d0b805397953bdc6874b48

**Comment by akoeplinger** [comment]
Hm okay, that's a problem though since `1.0.0-prerelease-63213-02` is greater than `1.0.0-beta.18420.3` according to nuget version logic: http://nugettoolsdev.azurewebsites.net/4.2.0/version-comparison?versionA=1.0.0-prerelease-63213-02&versionB=1.0.0-beta.18420.3

**Comment by ViktorHofer** [comment]
I think we should just cleanup the ones with the prerelease label. We haven't taken a dependency on those in corefx yet.

**Comment by markwilkie** [comment]
@jcagme, please make sure the packages are either cleaned up, or bump the versions for the packages from Arcade.  (probably the later)

**Comment by akoeplinger** [comment]
Nope, 1.0.0-prerelease-63213-02 is still on the feed and considered the latest package.

**Comment by akoeplinger** [comment]
Ping. It's a bit annoying not being able to use the IDE to update my packages.

**Comment by chcosta** [comment]
@jcagme @markwilkie

**Comment by akoeplinger** [comment]
This was fixed with https://github.com/dotnet/arcade/commit/66ec4320194c4b65fb85d754fe01fb2e137cbc9f where the version of that package was bumped to 2.0.0.
