### ISSUE TITLE
Reduce time spent in publishing by removing output locations

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4874]
For the .NET 5 channels
- [ ] Remove blob feed publishing for packages - AzDO feeds have these packages (dotnet5 and dotnet5-transport)
- [ ] Remove azdo feed publishing for symbol packages - The storage locations get these symbol packages.

This should get rid of a significant chunk of time in the dotnet/runtime publishing.

- May require action from repos that do not have the dotnet5/dotnet5-transport feeds in their input nuget feeds.
- Should change master's SetupTargetFeeds.proj, but not port to 3.x (yet)

**Comment by adiaaida** [comment]
Will this fix issues like this this build, where it appears that we timed out due to sleet taking too long?

https://dev.azure.com/dnceng/internal/_build/results?buildId=524247&view=logs&j=0b850c37-f3ae-5bb9-a9fb-4f1e0fce2747&t=50d41e72-ce5e-50a3-efc7-c28c030be91c

**Comment by riarenas** [comment]
It should. It would help with both:

* Runtime keeping the feed locked for other repos publishing.
* Runtime timing out due to feed being locked by someone else.

**Comment by JohnTortugo** [comment]
@mmitche - Can/should we do this for all channels instantiated in Arcade@master YAML or just to the channels that publish to dotnet5 & dotnet5-transport feeds?

If we can remove it for all channels I can just remove the creation of some TargetFeedConfigs in SetupTargetFeeds.proj; otherwise, I'll need to add some small logic there.

**Comment by mmitche** [comment]
I think we can do it for all. FYI this will probably cause failures in various repos during dependency updates (there are probably still some places that use dotnet-core exclusively).

**Comment by riarenas** [comment]
Yeah, before merging this change we should definitely inform people that it's in flight so they can prepare. The list of feeds that they need to add to their nuget config is well known, so we can just let them know to add them days in advance of this change making it through.

**Comment by JohnTortugo** [comment]
@mmitche @riarenas - Thanks. First steps I'm planning is:

- Do a GH search to have an idea of which repos doesn't have the AzDO feeds.
- Send an e-mail to partners about the upcoming breaking change.

**Comment by JohnTortugo** [comment]
Moving to backlog while we wait for partners to update their NuGet.Config.

**Comment by JohnTortugo** [comment]
@mmitche I think you got this completed already, right?

**Comment by mmitche** [comment]
Yes.  it's still waiting for rollout.

**Comment by JohnTortugo** [comment]
Closing as the improvements made by @mmitche are already deployed.
