### ISSUE TITLE
Helix testing on public PR coming from fork fails

### ISSUE THREAD

**Issue by smitpatel** [dotnet/arcade#4886]
-  Is this issue blocking (yes/no) no
-  Is this issue causing unreasonable pain (yes/no) no

Error message 
```
  Starting Azure Pipelines Test Run Ubuntu.1804.Amd64.Open
/home/vsts/.nuget/packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20116.1/tools/azure-pipelines/AzurePipelines.MultiQueue.targets(16,5): error : Request to https://dev.azure.com/dnceng/public/_apis/test/runs?api-version=5.0-preview.2 returned failed status 401 Unauthorized [/home/vsts/work/1/s/eng/helix.proj]
/home/vsts/.nuget/packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20116.1/tools/azure-pipelines/AzurePipelines.MultiQueue.targets(16,5): error :  [/home/vsts/work/1/s/eng/helix.proj]
/home/vsts/.nuget/packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20116.1/tools/azure-pipelines/AzurePipelines.MultiQueue.targets(16,5): error :  [/home/vsts/work/1/s/eng/helix.proj]
```
Run: https://dev.azure.com/dnceng/public/_build/results?buildId=530301&view=logs&jobId=107b6447-6976-5e9d-0de1-92099cc60ad8&j=107b6447-6976-5e9d-0de1-92099cc60ad8&t=d41080c9-6b6f-523e-8424-6273a8737d4d

I am not sure what kind of authentication needs to be passed here.

**Comment by jonfortescue** [comment]
@smitpatel Yes, this is an authorization thing that everyone runs into -- you have to do on the build to make it accept forks (in AzDO). I don't remember what it is off the top of my head (been a while since I've seen it) but I'll track it down for you as soon as I can.

**Comment by jonfortescue** [comment]
Ah, I found it. Instructions here: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/6305

**Comment by jonfortescue** [comment]
Ensure that you don't check "make secrets available," however.

**Comment by smitpatel** [comment]
This is current settings which allows PR from forks still it has failed. Anymore checkbox I have to tick?

![image](https://user-images.githubusercontent.com/1528107/74995581-2b3a4f00-5406-11ea-99a8-dc707c57e89b.png)

**Comment by jonfortescue** [comment]
Talked to Smit offline and this should be resolved; I was mistaken on checking "make secrets available." @smitpatel please close this after you've confirmed it's working!

**Comment by smitpatel** [comment]
Verified working.
