### ISSUE TITLE
WindowsDesktop builds are being assigned to channel before publishing completes

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#4888]
-  Is this issue blocking (yes/no): no
-  Is this issue causing unreasonable pain (yes/no): **yes**

See https://github.com/dotnet/core-sdk/pull/6502#issuecomment-589476746.

Related: https://github.com/dotnet/arcade/issues/4603.

It looks like Core-SDK auto-update PRs will need to be manually retried due to this, since assets aren't available quite in time.

**Comment by dagood** [comment]
Remembered why this felt a little familiar. Core-Setup took a fix for this a while back in the pipeline yaml, https://github.com/dotnet/core-setup/pull/7807 (Aug 22, 2019): 

```diff
     - template: /eng/common/templates/job/publish-build-assets.yml
       parameters:
+        publishUsingPipelines: true
```

However, windowsdesktop forked from core-setup *after* that, so it already has that parameter set: https://github.com/dotnet/windowsdesktop/blob/4c03b747eebff93c47626fae333324c0a9b669f0/azure-pipelines.yml#L73-L75

Something new seems to be going on.

**Comment by riarenas** [comment]
When the dotnet 5 preview channels were introduced, they didn't get a release pipeline associated to them, which is still a requirement for the publishing to wait for the build to complete. I fixed up the new channels and this shouldn't be an issue anymore.

**Comment by dagood** [comment]
Feel free to close, I don't know how to check if it's fixed other than a spot check of comparing the timestamps again.

**Comment by riarenas** [comment]
I want to spot check a few builds and then I'll close this.

**Comment by mmitche** [comment]
Looks good to me now.

**Comment by riarenas** [comment]
Yep, nothing in the logs from this morning's round of updates. I think all the channels are now configured correctly for this.
