### ISSUE TITLE
Publish flag set for PR builds?

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4897]
-  Is this issue blocking: no
-  Is this issue causing unreasonable pain: no

We have the `-publish` flag set in [eng\common\cibuild.cmd](https://github.com/dotnet/arcade/blob/master/eng/common/CIBuild.cmd) & [cibuild.sh](https://github.com/dotnet/arcade/blob/master/eng/common/cibuild.sh) and the same file gets used for public & internal builds. Do we have a specific reason for that? 

/cc  @riarenas @mmitche @tmat @chcosta

**Comment by mmitche** [comment]
Consistency maybe? Maybe detects regressions in publish behavior for arcade updates? Unsure about that though.

**Comment by riarenas** [comment]
@JohnTortugo Is there anything else you want from this issue or is it good to close? I believe the answer was that we do a dry-run of the symbol publishing during PRs to make sure produced symbols are publishable.

**Comment by JohnTortugo** [comment]
I think we're good to close this.
