### ISSUE TITLE
Remove MSBuildPath from SignToolTask

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#490]
After comment here: https://github.com/dotnet/arcade/pull/488#discussion_r211422567

The new SignTool is a MSBuild task and is able to execute without a direct path to MSBuild:

https://github.com/dotnet/arcade/blob/569feb95ac491cf4ffc17f6cfa8223466e7aecac/src/Microsoft.DotNet.SignTool/src/RealSignTool.cs#L42

therefore we can remove that parameter.

**Comment by tmat** [comment]
We need the desktop msbuild path when we are running the build on Core CLR.
