### ISSUE TITLE
[darc/maestro++] Add option to update-dependencies based on a build id

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4905]
Add an option to update local dependencies based on a BAR build, vs. the "latest". This will allow for rolling to a specific version of a runtime, SDK, etc. much more easily

**Comment by wli3** [comment]
There should be an automated way to find out all the corresponding ASPNET, windows components IDs. So humans do not need to dig the manifests. Only do the triggering of IDs.

**Comment by mmitche** [comment]
What do you propose the input to this is? This is the problem.  How does it know that you mean "this specific build of aspnetcore vs. that other 3.1.2"...how does it know you don't mean websdk?

**Comment by mmitche** [comment]
What i'd suggest though is...it's trivial to write a script that knows that for your specific scenario, these N repos are what you want to update...load up the manifest.json and look up those repos and find the builds.  But I do not want to build specific knowledge of repos into the tooling, because that stuff shifts over time.

**Comment by wli3** [comment]
"specific scenario" it is a specific case, but I don't think it is an edge case. This is one of 3 ways of shipping runtime. We would need to do it pretty frequently.

**Comment by mmitche** [comment]
@wli3 But even what repos that means varies based on release...
We can write helper scripts and check them into eng/common or whatever, but it should not be built into the maestro tooling itself.

**Comment by wli3** [comment]
That's fine. As long as it is maintained

**Comment by mmitche** [comment]
I'd also suggest that the best place for these is the core-sdk repo....because not only do the source repositories change between 3.0 and 5, but so do the target repos.

**Comment by wli3** [comment]
That'd also fine. However, this script should be maintained by central engineering team. Since Darc is the source of truth on what versions should we ship. Considering before arcade, we would ask for individual component owner for which version should be in certain version of SDK

**Comment by mmitche** [comment]
I'm not convinced this is the job of the central engineering team. Darc isn't the source of truth for versions. The repo itself is. Darc is just reading that info and making transforms based on what the repo is telling us about new builds. The central engineering team will provide the tools necessary to enable these kinds of scenarios, and we can certainly help out in the construction of them, but I think these should be owned either by the individual runtime teams or the sdk team.

Having them owned by the runtime teams does makes sense in some respects, in that this would be a similar model to toolset teams owning their insertions. It's just likely to be more communication on your side to get the right runtimes inserted (since you'll need to deal with 2-3 teams)
