### ISSUE TITLE
[darc/maestro++] Add ability to trigger subscription update for a specific build ID

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4906]
Today trigger-subscriptions will just trigger based on the latest build in a channel. This is fine, but we also have cases where we need to update to a specific build, like when we want to update a branch to a specific build of the runtime. https://github.com/dotnet/arcade/issues/4905 covers this option for a local update-dependencies. We should add a REST api + darc commands to do the same inside of Maestro itself.

**Comment by MattGal** [comment]
Working on a more urgent issue, pushed my WIP to https://github.com/MattGal/arcade-services/tree/arcade-4906 and putting this issue into tracking/blocked until I complete https://github.com/dotnet/arcade/issues/6047

**Comment by MattGal** [comment]
Created https://github.com/dotnet/arcade-services/pull/1375

**Comment by MattGal** [comment]
PR merged, moving to rollout and will make a doc PR now.

**Comment by MattGal** [comment]
https://github.com/dotnet/arcade/pull/6081 adds --build to the existing arcade darc.md

**Comment by MattGal** [comment]
Rolled out, closing.
