### ISSUE TITLE
Categorize ErrorMessages in RepositoryHistoryTable

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#4918]
-  Is this issue blocking - No
-  Is this issue causing unreasonable pain - No

**What has to be done?**

RepositoryHistoryTable ErrorMessages has to be categorized. 
Github issue search api breaks when there are any special characters in the issue body, and that is blocking future work on this issue: https://github.com/dotnet/arcade/issues/1387

**What is the actual work?** 
There are 2 options 

1) Add a new column in the RepositoryHistoryTable  - Which is painful to do so according to @alexperovich 
2) Updating the way we are capturing the ErrorMessage. Add the category in brackets and then parse it to get the category in the UpdateDepenedencyErrorProcessor.

**Comment by epananth** [comment]
Types of error are defined here to start with -> https://github.com/dotnet/arcade/issues/1387#issuecomment-573916862

**Comment by riarenas** [comment]
Which option are we going to go with? I know we discussed a third one where we'd add some invisible markdown to the issue body without any special characters and search on that, so wondering which one you think we should go with?

(I also took the liberty of making this issue non-blocking and not causing additional pain, as this is not blocking any scenarios. It's a task for a feature that is still in flight)

**Comment by epananth** [comment]
Unfortunately the comment marker does not find the string in the body of the GitHub issue. So need to take a step back on this. 

There is an alternative approach that is being discussed.( Using Reliable Services to store the Repo-branch combo). We might not even need this, I am going to keep this open until we hit that point.

**Comment by epananth** [comment]
I think issue in no longer relevant. Going to close this.
