### ISSUE TITLE
Package Microsoft.DotNet.Build.Tasks.Feed corresponding to arcade version isn't found

### ISSUE THREAD

**Issue by brettfo** [dotnet/arcade#4931]
Recent F# (dotnet/fsharp#8612) and Roslyn (dotnet/roslyn#41860) arcade updates are failing because the package `Microsoft.DotNet.Build.Tasks.Feed` cannot be found.  That package version is set to be [identical to the arcade version](https://github.com/dotnet/arcade/blob/0d6357ac00b8c3edae1fe1f3d476c9598c2ddff4/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L84).

Without the expected package, the arcade updates cannot continue.

**Comment by JohnTortugo** [comment]
@brettfo - This is a known bug and we have a fix for it in PR here: https://github.com/dotnet/arcade/pull/4926

The issue was due to a change in Arcade SDK that made it stop (correctly) restoring Tasks.Feed for source builds.

**Comment by JohnTortugo** [comment]
Closing in favor of previous issue: https://github.com/dotnet/arcade/issues/4919
