### ISSUE TITLE
Backup Reliable Services

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#4933]
-  Is this issue blocking (no)
-  Is this issue causing unreasonable pain (no)

Reliable Services need to be backed up.

**Why?**
1) If the cluster goes down then all the data will be deleted.
2) We are using this pretty heavily and back up is a nice thing to have.

**Comment by garath** [comment]
Had an offline conversation with @epananth. She is looking into the risk on this and will update here.

**Comment by epananth** [comment]
Currently we are using reliable services heavily. Also the data in it is growing every day.We are not backing this up at all. So if we lose this data then bad things can happen. 

For example in dependency update error processor 
1)  For the same dependency update flow we will have multiple github issues
2)  No Github issue will be created, we might miss an error completely

Also for the q? What happens during deployment? 
Reliable services does not lose data during redeployment. If the services is deleted then we data will be lost.

**Comment by alexperovich** [comment]
thankfully service fabric has full support for backup and restore, we just have to write the code to request a backup and restore from backup when needed. The docs are here https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-backup-restore

**Comment by garath** [comment]
How often would a request-to-backup be needed for Maestro to stay consistent?

**Comment by alexperovich** [comment]
we can backup whenever, the question is how much time do we want to wait before data is persisted into a backup. We can do incremental backups every 10 minutes if we want to, with a full backup every day or something. Or one backup every week.

**Comment by garath** [comment]
Triage: Investigate and recommend @alexperovich

**Comment by alexperovich** [comment]
We should do this in the ServiceHost package so it can be shared among all services. We should backup to azure storage every hour, using incremental backups for all but the first every day.

**Comment by missymessa** [comment]
I don't think we've had issues with this in the last few years, so I'm going to close this out.
