### ISSUE TITLE
Make job-list-guid.json formatted

### ISSUE THREAD

**Issue by ManickaP** [dotnet/arcade#4937]
-  Is this issue blocking (no)
-  Is this issue causing unreasonable pain (no)

The generated job-list is a very long one-line file with unformatted json. Since it's read by humans, it needs to be formatted before one can make a use of it.
The solution should be as easy as adding `Formatting.Indented` on https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/JobSender/JobDefinition.cs#L171.

**Comment by garath** [comment]
@ManickaP PRs welcome!
