### ISSUE TITLE
[darc/maestro++] add-build-to-channel's source-branch parameter should cause lookup of latest arcade sha on that branch

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4940]
-  Is this issue blocking **no**
-  Is this issue causing unreasonable pain **no**

When specifying --source-branch 'master', I expected that we would look up the latest sha of arcade on that branch. Instead, it takes the sha that you have in the source-build's repo.

**Comment by JohnTortugo** [comment]
@mmitche - I'm not sure if I follow here. The current behavior is:

- you need to specify both branch name & SHA from the branch.
- the sources of the promotion pipeline will be that branch+SHA.

The branch name + SHA needs to be from Arcade repo.

**Comment by mmitche** [comment]
The branch name shouldn't really matter, since the sha describes the source completely.  So I'd expect branch name (take head of branch), or sha (branch doesn't matter)

**Comment by JohnTortugo** [comment]
So, you want to be able to specify branch OR SHA?

I implemented requiring both because the AzDO REST API requires SHA + branch if you specify a SHA (but only branch if you don't specify a SHA). I can implement something to lookup the branch name given the SHA.

**Comment by mmitche** [comment]
On queuing a build? That doesn't make much sense because a sha can appear in multiple branches. It does appear that when you do this in the UI, it then asks for a "branch context".

Alright, well it doesn't appear you can get this data from either the GitHub or AzDO APIs.  There is a github web page with the info, but that's not particularly useful: https://github.com/dotnet/arcade/branch_commits/e32ba79455a9b06a2bdd93e54552c5d8c5575085

Maybe the right thing to do is just to leave as-is.

**Comment by riarenas** [comment]
Maybe just outright fail and give a helpful message if either option is passed without the other?
