### ISSUE TITLE
[Release prep] Arcade verification mechanism

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#4947]
@mmitche brought up that it would be good to have a way to do Arcade verification. Will talk to him and add more details here on how this is currently done and at what stage so we can try to put that into a thing (script, pipeline, etc.) to make it automatic.

**Comment by Tohron** [comment]
This issue appears to already be covered by work to improve arcade reliability:
https://github.com/dotnet/core-eng/blob/master/Documentation/Project-Docs/improve-arcade-reliability.md

Closing...
