### ISSUE TITLE
Fast patching NuGet restore issue

### ISSUE THREAD

**Issue by jaredpar** [dotnet/arcade#4957]
The context is the following NuGet issue https://github.com/NuGet/Home/issues/9199.

A summary of the problem is there is a bit of a race during restore that leads to failures. This is impacting the dotnet/runtime repository to the tune of 6% build failures all up. The failure rate is consistent over the last two weeks and is effectively the largest source of reliability in the builds. It is impacting all of the build definitions we use there: official, CI, outerloop. 

The NuGet team proposed a work around for the issue but that did not work. In fact the PR which implemented their work around hit the issue hence. https://github.com/dotnet/runtime/pull/32979

The good news is the NuGet team has fixed the issue. I want to know how we can get this fix into the runtime repository as soon as possible. Is there a way we can separately consume this fix in our repository? Or if not can we push the SDK loop through sooner to get this fix?

Example data from the last 300 builds of the CI loop:

|Build|Kind|Timeline Record|
|---|---|---|
|[542690](https://dev.azure.com/dnceng/public/_build/results?buildId=542690)|PR https://github.com/dotnet/runtime/pull/32912|Restore|
|[542122](https://dev.azure.com/dnceng/public/_build/results?buildId=542122)|PR https://github.com/dotnet/runtime/pull/33025|Build product|
|[541784](https://dev.azure.com/dnceng/public/_build/results?buildId=541784)|Rolling|Restore|
|[540909](https://dev.azure.com/dnceng/public/_build/results?buildId=540909)|Rolling|Build product|
|[540894](https://dev.azure.com/dnceng/public/_build/results?buildId=540894)|PR https://github.com/dotnet/runtime/pull/32979|Build product|
|[540907](https://dev.azure.com/dnceng/public/_build/results?buildId=540907)|PR https://github.com/dotnet/runtime/pull/32912|Build product|
|[540608](https://dev.azure.com/dnceng/public/_build/results?buildId=540608)|PR https://github.com/dotnet/runtime/pull/465|Override CoreCLR from live drop|    |[540426](https://dev.azure.com/dnceng/public/_build/results?buildId=540426)|PR https://github.com/dotnet/runtime/pull/32803|Build product|
|[540066](https://dev.azure.com/dnceng/public/_build/results?buildId=540066)|PR https://github.com/dotnet/runtime/pull/32538|Restore|
|[539759](https://dev.azure.com/dnceng/public/_build/results?buildId=539759)|PR https://github.com/dotnet/runtime/pull/32948|Override CoreCLR from live drop|  |[539331](https://dev.azure.com/dnceng/public/_build/results?buildId=539331)|Rolling|Restore|
|[538676](https://dev.azure.com/dnceng/public/_build/results?buildId=538676)|Rolling|Restore|
|[538657](https://dev.azure.com/dnceng/public/_build/results?buildId=538657)|PR https://github.com/dotnet/runtime/pull/32858|Override Mono from live drop|     |[538533](https://dev.azure.com/dnceng/public/_build/results?buildId=538533)|PR https://github.com/dotnet/runtime/pull/32906|Send to Helix|
|[538533](https://dev.azure.com/dnceng/public/_build/results?buildId=538533)|PR https://github.com/dotnet/runtime/pull/32906|Build product|
|[538411](https://dev.azure.com/dnceng/public/_build/results?buildId=538411)|PR https://github.com/dotnet/runtime/pull/32759|Restore|
|[538114](https://dev.azure.com/dnceng/public/_build/results?buildId=538114)|PR https://github.com/dotnet/runtime/pull/32890|Override CoreCLR from live drop|  |[538335](https://dev.azure.com/dnceng/public/_build/results?buildId=538335)|PR https://github.com/dotnet/runtime/pull/31701|Restore|
|[538080](https://dev.azure.com/dnceng/public/_build/results?buildId=538080)|PR https://github.com/dotnet/runtime/pull/31701|Build product|
|[537359](https://dev.azure.com/dnceng/public/_build/results?buildId=537359)|PR https://github.com/dotnet/runtime/pull/32857|Build product|
|[537202](https://dev.azure.com/dnceng/public/_build/results?buildId=537202)|PR https://github.com/dotnet/runtime/pull/32811|Send to Helix|
|[536984](https://dev.azure.com/dnceng/public/_build/results?buildId=536984)|PR https://github.com/dotnet/runtime/pull/32705|Restore|

**Comment by riarenas** [comment]
Could runtime take an SDK update with the fix, and if it solves the issue we can update Arcade's version again so everyone else benefits?

CC @markwilkie

**Comment by ViktorHofer** [comment]
Sure, that's possible. First we need to get the SDK change in of course: https://github.com/NuGet/Home/issues/9199

**Comment by jaredpar** [comment]
The SDK PR is merged now. What is the next step here in getting this into dotnet/runtime?

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/runtime/pull/33113

**Comment by carlossanlop** [comment]
@jaredpar the 7th element on the table is linking the wrong PR (465).

**Comment by riarenas** [comment]
runtime is using an SDK with this fix already, and we're updating the minimum SDK version distributed by arcade in https://github.com/dotnet/arcade/pull/5357
