### ISSUE TITLE
[Signing] Cannot codesign files which don't have strong names such as native .dlls 

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#496]
I'm trying to use Microsoft.DotNet.SignTool 1.0.0-beta.18421.2 to code sign the following types of files:

* .jar (see https://github.com/dotnet/arcade/issues/412)
* A native .dll file (no public key)
* A managed .dll without a strong name.

I'm running into the following errors

1. If I don't specify FileSignInfo items, SignToolTask fails with

> error : SignInfo for Public Key Token  not found.

2. If I provide a FileSignInfo item without a public key, I get

> error : This PublicKeyToken metadata for FileSignInfo isn't valid:

**Comment by natemcmaster** [comment]
cc @jonfortescue @maririos

**Comment by maririos** [comment]
FYI @JohnTortugo

**Comment by JohnTortugo** [comment]
I'll ping you on skype. Maybe there is some issue on the format of the PKT.

**Comment by natemcmaster** [comment]
There is no PKT, that's the point. I tried `PublicKeyToken=""` and `PublicKeyToken="null"`.

**Comment by tmat** [comment]
@JohnTortugo FileSignInfo without PKT should be allowed.

**Comment by JohnTortugo** [comment]
Updating:

- The ".jar" file extension is currently not recognized.
- The tool currently should be able to identify native .dll (no need for PKT) and sign it with (cert=MicrosoftSHA2, sn=null). You don't need to specify anything, the file will be parsed and identified as native.

> A managed .dll without a strong name.

I want to be sure that I understand this. You have a managed .dll that doesn't have a PKT. In that case, to sign it you'll need to use the "override capability" of the tool to assign a Certificate name to be used for this specific file. However, currently the tool requires a PKT for that. 

@natemcmaster @tmat did I get this right? If yes, I'll create an issue+PR for that.

**Comment by tmat** [comment]
> did I get this right?

I think so.

**Comment by JohnTortugo** [comment]
Tracking the .jar work on issue #509
