### ISSUE TITLE
Enable Maestro updates when there is multiple Version.Details.xml entries with the same package name

### ISSUE THREAD

**Issue by crummel** [dotnet/arcade#4960]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Source-build uses multiple entries with the same package name in Version.Details.xml to build the same repo in multiple ways:
https://github.com/dotnet/source-build/blob/8ffc4e5a7d67f892c9032d8a9ef660ef895f5e43/eng/Version.Details.xml#L30-L39
Currently, this is used for building both the portable and non-portable versions of the runtime, but could be expanded to other uses.  We've had cases in the past where we do not receive Maestro updates to our Version.Details.xml because multiple elements with the same package name are not supported.

Alternative approaches we've considered:
- Using two different package names so we can have effectively duplicate entries: this seems error prone if some packages stop being produced or have different version numbers.
- Not using Version.Details.xml to facilitate this: this is possible, but we prefer to keep Version.Details.xml as the single source of truth.

This isn't blocking but would be nice to have so that we can have more confidence that the Maestro auto-updates are getting everything and not have to rely on manual double-checking as much.

cc @adaggarwal

**Comment by mmitche** [comment]
So what behavior would you expect when a new build comes in? This is entirely based on name today, so it would simply update both elements to the new version. Furthermore, it can then only map to a single version property in any other version file. That sounds basically the same as having a single node in version.details.xml.

**Comment by crummel** [comment]
Right, that would be the behavior I expect.  We have additional metadata on the node that tells us which MSBuild project to use for each entry:
```
    <Dependency Name="Microsoft.NETCore.Runtime.CoreCLR" Version="3.1.2-servicing.20066.2" CoherentParentDependency="Microsoft.Private.CoreFx.NETCoreApp">
      <Uri>https://github.com/dotnet/coreclr</Uri>
      <Sha>fd22fd600a2526a7c58536da0e80325eb710d7f1</Sha>
      <RepoName>coreclr</RepoName>
    </Dependency>
    <Dependency Name="Microsoft.NETCore.Runtime.CoreCLR" Version="3.1.2-servicing.20066.2" CoherentParentDependency="Microsoft.Private.CoreFx.NETCoreApp">
      <Uri>https://github.com/dotnet/coreclr</Uri>
      <Sha>fd22fd600a2526a7c58536da0e80325eb710d7f1</Sha>
      <RepoName>coreclr-portable</RepoName>
    </Dependency>
```

Like I said, we can move this out of Version.Details.xml but it's nice to have the single source of truth and I didn't think it would break anything.

**Comment by mmitche** [comment]
Why not just do this then?:

```
<Dependency Name="Microsoft.NETCore.Runtime.CoreCLR" Version="3.1.2-servicing.20066.2" CoherentParentDependency="Microsoft.Private.CoreFx.NETCoreApp">
      <Uri>https://github.com/dotnet/coreclr</Uri>
      <Sha>fd22fd600a2526a7c58536da0e80325eb710d7f1</Sha>
      <RepoNames>coreclr;coreclr-portable</RepoNames>
    </Dependency>
```

I'm mostly worried about where assumptions of this might be baked in. There are a ton of places which are using various hash sets when looking at dependencies.

**Comment by riarenas** [comment]
Do the versions always match? can't you have multiple reponame nodes, or have all the repos in the same reponame? 

```xml
    <Dependency Name="Microsoft.NETCore.Runtime.CoreCLR" Version="3.1.2-servicing.20066.2" CoherentParentDependency="Microsoft.Private.CoreFx.NETCoreApp">
      <Uri>https://github.com/dotnet/coreclr</Uri>
      <Sha>fd22fd600a2526a7c58536da0e80325eb710d7f1</Sha>
      <RepoName>coreclr</RepoName>
      <RepoName>coreclr-portable</RepoName>
    </Dependency>
```

**Comment by riarenas** [comment]
Oh Matt beat me to it :|

**Comment by crummel** [comment]
Hmm, sure, we should be able to do something like that.  Thanks!
