### ISSUE TITLE
Signing validation for Arcade validation is failing

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4963]
This build from Arcade validation is failing signing validation consistently: https://dnceng.visualstudio.com/internal/_build/results?buildId=543905&view=results

Previous build passed: https://dnceng.visualstudio.com/internal/_build/results?buildId=543556&view=results

Seems there was not change in SignTool in Arcade. I also don't see any change in Arcade validation files related to signing. 

The failure error is:

```
[File] Validation.1.0.0-prerelease.20152.5.nupkg, Signed: False
  [File] 8ccdda4c8ccc0950007bcad85d812703.dll, Signed: False, Full Name: lib/netcoreapp2.0/Validation.dll [Error] HRESULT: 800b0109 (A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider)
[File] Validation.Tests.1.0.0-prerelease.20152.5.nupkg, Signed: False
  [File] 9553bb952bf30e31a6ebfe78d1d305b1.dll, Signed: False, Full Name: lib/netcoreapp2.1/Validation.Tests.dll [Error] HRESULT: 800b0109 (A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider)
```

I downloaded the packages and they are signed but the Certificate seems bogus:

<img width="457" alt="signed" src="https://user-images.githubusercontent.com/2249648/75732407-40856800-5ca7-11ea-9fdc-5c69c6017dc8.png">

The SignTool logs indicate that the package/file was submitted correctly to the servers and signed properly.

/cc @MattGal

**Comment by JohnTortugo** [comment]
Subsequent builds seem to have signed correctly the files: 
https://dnceng.visualstudio.com/internal/_build/results?buildId=544059&view=results

<img width="719" alt="sign2" src="https://user-images.githubusercontent.com/2249648/75734770-b7bdfa80-5cad-11ea-8127-55a5c5b3a171.png">

**Comment by markwilkie** [comment]
Did this turn out to be only the machine we were building Arcade on?

**Comment by JohnTortugo** [comment]
- I removed the "Blocking", "Critical" labels as the build passed on retry.

@markwilkie - I don't know how the build agent would interfere here. IMHO it might have been a problem on the signing server, which is scary. I'll keep poking the signing folks about it.

**Comment by JohnTortugo** [comment]
@mmitche @riarenas - What happened here was that two build legs from Arcade-Validation published packages with same name. The Debug leg produce test signed binaries and the Release leg produce real signed binaries. The Debug leg finished last and published packages to AzureDevOps artifacts overriding the real signed packages produced by the Release leg.

I think any build-definition can hit this problem if they produce packages with same name from multiple build legs (I think they aren't supposed to do this, right?!).

My question is: does it make sense to patch Arcade.SDK to only publish from a Release configuration?

**Comment by riarenas** [comment]
Ooh, that's an interesting one and it makes sense. So basically arcade-validation has been really lucky that release configurations have been taking longer than debug builds for a long time?

I think in principle it makes sense, my concern would be breaking existing repos already publishing from debug configuration. I don't think there's anything stopping them from setting debug + real sign, right?

Maybe just disable the publishing in arcade-validation for now?

**Comment by mmitche** [comment]
Yeah, I think fixing in arcade-validaiton is the right place, though it might be interesting to see whether someone else is publishing from debug.

**Comment by JohnTortugo** [comment]
Yeah, real lucky. I confirmed by looking at the .dlls bits and they were indeed built from a Debug configuration.

I also think fixing only in Arcade-validation is better right now. AFAIU most repos have signing validation enabled and would catch this sort of thing (as it just did).
