### ISSUE TITLE
TargetOSTrait auto detection without passing in trait

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#4973]
- [ ] This issue is blocking
- [ ] This issue is causing unreasonable pain

@safern does it make sense to replace the manual passing in of the `TargetOSTrait` with an auto detection similar how we detect different runtime modes? Similar question for failing tests, should we just trim those out during discovery as well? That would solve the current VS Test Explorer issues until we have support for defining default traits in the .runsettings file.

**Comment by safern** [comment]
> @safern does it make sense to replace the manual passing in of the TargetOSTrait with an auto detection similar how we detect different runtime modes? Similar question for failing tests, should we just trim those out during discovery as well? 

Yes I think that makes sense, I think @akoeplinger just took advantage of that for the Mono skips, so it would definitely make sense to do it in runtime rather than on buildtime to decouple, building from running.

**Comment by ViktorHofer** [comment]
Closing as done.
