### ISSUE TITLE
[Signing] NullReferenceException error in SignToolTask when processing .nupkg files

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#498]
I'm trying to use  Microsoft.DotNet.SignTool 1.0.0-beta.18421.2 to codesign .nupkg files and getting the following NullReferenceException for all .nupkg's

```
     2>C:\src\aspnet\Blazor\build\sign.proj(42,5): error : Object reference not set to an instance of an object.
         New file to sign: File: C:\src\aspnet\Blazor\build\..\artifacts\Debug\packages\Microsoft.AspNetCore.Blazor.Build.0.6.0-preview1-t000.nupkg; SignInfo: Empty: False; ShouldSign: True; IsAlreadySigned: False; ShouldIgnore: False; StrongName: ; Certificate:
NuGet;
```

I've attached a binary log with more details
[msbuild.binlog.zip](https://github.com/dotnet/arcade/files/2307363/msbuild.binlog.zip)

**Comment by natemcmaster** [comment]
cc @JohnTortugo @maririos

**Comment by maririos** [comment]
Thanks Nate. We are looking into it

**Comment by JohnTortugo** [comment]
I think this is related to the fact that the tool currently requires the files to have PKT.

**Comment by JohnTortugo** [comment]
I'll close this issue as it was related to the empty PKT issue. If you see the error again, please ping me or kindly re-open the issue.
