### ISSUE TITLE
MSbuild error using multiple levels of Directory.Build.props

### ISSUE THREAD

**Issue by rynowak** [dotnet/arcade#4985]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

I'm getting the following error when I have multiple levels of `Directory.Build.props` in my tree:

```txt
C:\Users\rynowak.REDMOND\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20151.1\Sdk\Sdk.targets(24,46): error MSB4100: Expected "!$(_SuppressSdkImports)" to evaluate to a boolean instead of "!", in condition "!$(_SuppressSdkImports) and !$(_SuppressAllTargets)".
```

**Comment by garath** [comment]
@rynowak These properties are set normally by using the Arcade SDK. For your specific scenario, feel free to submit a PR.

**Comment by tmat** [comment]
@rynowak My guess is that you don't end up importing the Arcade SDK Sdk.props and Sdk.targets files correctly.

**Comment by rynowak** [comment]
I'm closing this because I don't have a repro anymore and it hasn't come up again 🤷 

I'm going to assume that it was user error on my part, but unfortunately I'm not sure which error.
