### ISSUE TITLE
[darc/maestro++] Darc add-build-to-channel should trigger the DevDiv promotion pipeline if target build is in DevDiv

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4986]
What the title says. We need to patch the code to trigger the DevDiv promotion pipeline for builds that originated in DevDiv, otherwise things will fail.

**Comment by riarenas** [comment]
I'll work on this today.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade-services/pull/1048
