### ISSUE TITLE
[Feed package] Turn off publishing of Feed package from BuildTools

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#5]
Once Feed package is publishing from Arcade, disable publishing from BuildTools.  Note, there is still work to be done (official builds, signing, etc...) before we're ready for that.

**Comment by maririos** [comment]
FYI @jcagme

**Comment by maririos** [comment]
@chcosta you mean each repo will need to start consuming the Feed package in Arcade instead of the Feed package in Buildtools?

**Comment by maririos** [comment]
For now, we should start by adding documentation in BuildTools to point people to the code over here.

Once repos that are using Buildtools start consuming the Arcade version, then we can disable the package publish there

**Comment by alexperovich** [comment]
why can we not disable package publish from buildtools now? Disabling the publish doesn't delete already published versions.

**Comment by maririos** [comment]
Until repos don't start consuming the version of Arcade, they might need to do fixes or modifications to the package in BuildTools so they get the change.
I prefer to wait until they don't depend actively on it.

**Comment by markwilkie** [comment]
I'm going to let @weshaggard make then call regarding buildtools
