### ISSUE TITLE
Report Arcade official build status to MC

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#50]
@chcosta commented on [Mon Mar 05 2018](https://github.com/dotnet/core-eng/issues/2820)

---

@Chrisboh commented on [Thu Mar 08 2018](https://github.com/dotnet/core-eng/issues/2820#issuecomment-371629968)

@chcosta could you please move it to the Arcade repo?

**Comment by alexperovich** [comment]
I am currently working on this. #125 is the first step.
