### ISSUE TITLE
[QCR] One-pager for release cli

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#5016]
Write up a one pager for the cli for automating releases.

1. We need to define the scope
    1. What operations will be included vs. what things we'll reuse from existing mechanisms
2. We need to define the purpose
    1. Like merely this will be used in the release pipeline and not in devs machines (not all devs)
3. Technical aspects
    1. Location
    2. Dependencies
    3. Permissions

**Comment by jcagme** [comment]
In case you want to call out some of the commands/operations we know it will have:
* [Branding](https://github.com/dotnet/arcade/issues/4371)
* [Create branches](https://github.com/dotnet/arcade/issues/4946)
* [Contract validation](https://github.com/dotnet/arcade/issues/5036)
* [Validate checksums](https://github.com/dotnet/arcade/issues/5037)
* [Validate assets availability ](https://github.com/dotnet/arcade/issues/5038)
* [Publish release notes](https://github.com/dotnet/arcade/issues/5039)
* [Publish release metadata ](https://github.com/dotnet/arcade/issues/5040)
