### ISSUE TITLE
Extract TempFile to arcade

### ISSUE THREAD

**Issue by hughbe** [dotnet/arcade#5017]
dotnet/runtime contains `TempFile`: https://github.com/dotnet/runtime/blob/master/src/libraries/Common/tests/System/IO/TempFile.cs

I need to use it in winforms in order to test loading of html files by the `WebBrowser` component (https://github.com/dotnet/winforms/pull/2962).

Should we extract this file from dotnet/runtime into dotnet/arcade for use by other .NET Core projects

/cc @RussKie

**Comment by tmat** [comment]
I don't think this belongs to Arcade. Arcade does not provide test utility libraries. I'd suggest making a copy.

**Comment by hughbe** [comment]
> Arcade does not provide test utility libraries 

I can think of
- Microsoft.DotNet.XUnitExtensions (https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.XUnitExtensions)
- Microsoft.DotNet.RemoteExecutor (https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.RemoteExecutor)

**Comment by markwilkie** [comment]
> Should we extract this file from dotnet/runtime into dotnet/arcade for use by other .NET Core projects

Are there other .net core repos who would want to use this?  In other words, is it shared?

**Comment by hughbe** [comment]
> Are there other .net core repos who would want to use this? In other words, is it shared?

Winforms in dotnet/winforms#2962 - can see similar usage possibilities for wpf

**Comment by tmat** [comment]
> Microsoft.DotNet.XUnitExtensions

These are meta-helpers extending XUnit attributes. 

> Microsoft.DotNet.RemoteExecutor

I'm not sure what this thing is. 

It'd make sense to share some complex hard to get right code.
But I don't think we should add trivial helpers like TempFile that can be easily copied. If we do that we would likely end up with a huge pile of random trivial helpers. 
The rule of thumb is - is it worth going thru public API review process for this, testing and maintaining behavior to avoid breaking changes?

**Comment by markwilkie** [comment]
> The rule of thumb is - is it worth going thru public API review process for this, testing and maintaining behavior to avoid breaking changes.

Yup, this is the right way to think about these things in my opinion
