### ISSUE TITLE
[QCR][Staging ring] Add release cli command for adding release notes

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#5030]
While automating the generation of release notes probably isn't possible, we should have a command that will put the release notes in all of the right places once they are ready.

**Comment by jcagme** [comment]
Talked to @leecow and he suggested that we generate the markdown fragment covering the change list for the release during this step.

@leecow can elaborate on details once we start working on this

**Comment by jcagme** [comment]
@adiaaida, looking at what we have in staging currently, do you know if the markdown @leecow refers above is covered by https://dnceng.visualstudio.com/internal/_git/dotnet-release?path=%2Feng%2Fpipeline%2Ftemplates%2Fsteps%2Fcreate-packages-md.yml?

**Comment by leecow** [comment]
There are many examples of what this might look like. Here's one that has a very clean structure - https://community.ui.com/releases/UniFi-Network-Controller-5-11-39/6ab8ef1a-376f-41e6-85b2-ceec098b8462. Other options include linking commits to the issues and providing a list of updated packages with new version numbers.

**Comment by adiaaida** [comment]
I was just looking at the markdown we created for the 5.0.0-preview8 release, and I think the creation of quite a bit of that can be generated in the staging ring, and once packages are published, I think that the rest of it can be automatically fixed up before publishing the md file (creating the PR).

Once the PR is created, a release QB can go in and make any additional fixes to the md file (for example, descriptions of any security fixes, links to blog posts and the like), but I think almost everything else can be automated.
