### ISSUE TITLE
[QCR][Signing ring] Linux signing

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#5033]
Speak with folks who are knowledgeable about signing on mac and linux. If this can be automated, we should do that, otherwise, add a command that will put the signed binaries in the right places for the release ring.

**Comment by jcagme** [comment]
Mac signing is considered to be notarization. For Linux, there is already a task in the existing RM which does Linux, signing, I'll port that to the new pipeline.

**Comment by adiaaida** [comment]
Should this be moved to the signing epic? I know that it is different from the actual work the signing epic folks are doing, but seems like it should go there.

**Comment by chcosta** [comment]
I don't know, I think it would get lost in the signing epic.  The notarization of Mac stuff has historically been a release only thing.

**Comment by adiaaida** [comment]
The Mac notarization is already done. Since the Linux stuff already exists and just needs to be ported, I'm cool with taking it on, I just don't want to get in your (the signing epic's) way.

**Comment by jcagme** [comment]
I wouldn't move it since the scope of the Signing Epic is just what happens in the builds today. Linux happens in the "publishing-pipeline" today so I'd just move it into the Signing ring

**Comment by adiaaida** [comment]
Looks like Alex Svyatenkiy is working on this. @leecow do you know what his github alias is?

**Comment by adiaaida** [comment]
Alex has checked this in, so closing.
