### ISSUE TITLE
[QCR] [Contracts] Define input and output contracts for staging ring

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#5035]
Add input and output contract jsons for staging ring and add support to generate the generated contract.

**Comment by markwilkie** [comment]
For whatever reason, I'm not seeing the contract itself.  Could someone point me to it?

**Comment by jcagme** [comment]
You looking for the PR? If so https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/8530
