### ISSUE TITLE
[QCR][Release ring] Publish release notes

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#5039]
On the final stage of the release, along with publishing all the assets to the public, we need to publish release noted into repos and other public facing endpoints. We need to add this functionality to the CLI so the notes can be easily read from a file (maybe merged into a repo) and publish them "officially".

Sample release notes: https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.16/2.1.16.md

**Comment by jcagme** [comment]
Talked to @leecow and he suggested that we generate the markdown fragment covering the change list for the release during this step.

@leecow can elaborate on details once we start working on this

**Comment by adiaaida** [comment]
out of scope for #6418

**Comment by jakubstilec** [comment]
[Async Triage]: @adiaaida will there be "Release Team can ship the product with confidence" phase 2, or do you have any other idea under which epic can this go?

**Comment by adiaaida** [comment]
Based on the priorities of the release team, my feel is that this is not one of their pain points, and may already be part of their release pipeline. I think I actually recommend just closing it.

**Comment by adiaaida** [comment]
I have confirmed this is already part of the existing RM pipeline that is being converted to yaml by Alex Svyatenkiy. Closing.
