### ISSUE TITLE
[QCR][TTR] Collect and track timing data for releases

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#5041]
One of the major focuses of the "Releases are quick and have high confidence" epic is to make releases *quick*. In order to define and track what a quick release is, we need to track how long it takes us to go from build candidate to released product so that we can drive that number down.

**Comment by jcagme** [comment]
All data that we need is in https://dataexplorer.azure.com/clusters/1es/databases/AzureDevOps. The following query returns all the runs for our release pipeline 

```
BuildTimelineRecord
| where ProjectId == "7ea9116e-9fac-403d-b258-b31fcf1bb293"
| sort by StartTime asc
```
Interesting columns are: RecordName and Type, and also StartTime and Result.

To get access to this cluster we need the following request to be approved: https://myaccess/identityiq/accessRequest/accessRequest.jsf#/accessRequest/review?role=1ES%20Data&autoSubmit=true

**Comment by adiaaida** [comment]
Should we individually request access or do we need to get a lab account access?

**Comment by jcagme** [comment]
@adiaaida I guess this can be closed?

**Comment by adiaaida** [comment]
I have published this report.
