### ISSUE TITLE
aka.ms link generation timed out

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5044]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In this build, the aka.ms link generation timed out on this particular call and caused a cancellation. There should be a retry here before we fail.
https://dev.azure.com/dnceng/internal/_build/results?buildId=556960&view=logs&j=0b850c37-f3ae-5bb9-a9fb-4f1e0fce2747&t=50d41e72-ce5e-50a3-efc7-c28c030be91c

**Comment by jaredpar** [comment]
So far there is only one instance of this across all internal builds. Keeping an eye on it.

**Comment by JohnTortugo** [comment]
Labeling this as a first responder issue so that I can help fixing it.

**Comment by BrennanConroy** [comment]
This aka.ms stuff is just flat out failing in Runtime 
`D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20160.4\tools\SdkTasks\PublishArtifactsInManifest.proj(79,5): error : Error creating/updating aka.ms links: {"":["The input was not valid."],"AkaLinks":["Aka links cannot be empty!"]}`
https://dev.azure.com/dnceng/internal/_build/results?buildId=557254

**Comment by jaredpar** [comment]
Two builds of runtime so far but failing all of them

|Build|Kind|Timeline Record|
|---|---|---|
|[557254](https://dev.azure.com/dnceng/internal/_build/results?buildId=557254)|Rolling|Publish Assets|
|[556993](https://dev.azure.com/dnceng/internal/_build/results?buildId=556993)|Rolling|Publish Assets|
