### ISSUE TITLE
Component Detection erroring for Linux musl builds

### ISSUE THREAD

**Issue by jaredpar** [dotnet/arcade#5046]
Take this build as an example 

https://dev.azure.com/dnceng/internal/_build/results?buildId=556246

This build passes and is listed as green. Yet if you look at the actual jobs you'll notice that there is an error in every Linux musl job in the "Component Detection" task. 

>       error General Unable to locate dotnetcore on build agent.

![image](https://user-images.githubusercontent.com/146967/76537853-9a222b00-643b-11ea-8209-8db39830290d.png)

This is happening on every official build in dotnet/runtime that I can see. Even though this is an error it's not blocking the build from completely successfully. Still though it's disconcerting to see errors in our official build pipelines.

I'm also unsure what this particular task is and how important it is or isn't that it's failing on every single build.

**Comment by markwilkie** [comment]
This was done "to" us by governance.  The good news is that @mmitche found a way to disable it.  Also, we're looking to see if we can disable it for all .net core repos.

**Comment by jaredpar** [comment]
Glad we can remove it but at the same time are we following up with the owner to relay the bug in the implementation? 

Given they forced it on us once it's reasonable to assume they can do so again in the future. What happens if they do that and the error actually causes the build to fail that time? That would take our builds down until we got a resolution.

**Comment by mmitche** [comment]
I don't know how to remove the component detection, though I can poke through the docs.  Also of note: The component detection runs on every leg (I think) and codesign validation runs on every windows job. So if you look at the overall time the injected tasks took, they added **6 mins** to the total e2e time, not including the validation and publishing stages.

That may not sound super significant, but it's a 'death by a thousand paper cuts' scenario. That's about 3% of the total build time prior to the validate stages. The times for those steps look reasonably consistent for various repos, so for websdk for instance, it adds accounts for 10-20% of the overall build time.

**Comment by jaredpar** [comment]
Do we have the ability to contact the teams responsible here? Seems like there are two important issues to hash out:

1. The task has a 100% failure rate on certain Linux distros
1. The task is consuming valuable resources: official build time. 

> codesign validation runs on every windows job. 

Also seems to be true based on my poking around. 

> The component detection runs on every leg (I think) 

Seems to be the case based on my poking around. The leg seems to average a time of ~30 seconds. Assuming we still have a longest path of six repos though that 3 minutes of build time or 2.5% of the time allotted for official builds.

**Comment by markwilkie** [comment]
Yes, I'm on point to reach out to the team responsible.

**Comment by jaredpar** [comment]
Any updates here about the error? If this is related to governess can we turn it off?

**Comment by markwilkie** [comment]
Yup, we can turn this off via build variable as their target is services right now.  See https://github.com/dotnet/arcade/pull/5049 for an example.

**Comment by mmitche** [comment]
I've turned it off for every job where we know that it shouldn't run that comes in through the templates.
