### ISSUE TITLE
aka.ms link generation batching is not working

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5054]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

When the batch size appears to be larger than 300...it appears that the link generation fails on later batches for some reason. The bug does not appear obvious.

**Comment by markwilkie** [comment]
What's this blocking?  Who should we get to work on it?

**Comment by mmitche** [comment]
Runtime. And I'm working on it.

**Comment by mmitche** [comment]
fix in testing here; https://dnceng.visualstudio.com/internal/_build/results?buildId=558942&view=results

**Comment by BrennanConroy** [comment]
What's the status with this?

**Comment by mmitche** [comment]
Fix is in testing in a real runtime build.

**Comment by mmitche** [comment]
Still working on it...I'm seeing some really odd behavior that only repros once the number of links is above the maximum batch size. I'm working on it locally and hopefully should have something in a little bit.
