### ISSUE TITLE
Run Codesign Validation is slow

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#5065]
- [ ] This issue is blocking
- [ ] This issue is causing unreasonable pain

The Codesign Validation step is slow as it first needs to bootstrap the SDK and restore. Instead this could be improved by converting that codesign validation application to self-contained which comes with everything bundled already.

A single "Run Codesign Validation" invocation doesn't take longer than 1:30min but multiple steps invoked in serial easily account for 5-10 minutes.

![image](https://user-images.githubusercontent.com/7412651/76684924-11101d00-6610-11ea-8cca-122b376040ba.png)

cc @mmitche

**Comment by markwilkie** [comment]
We checked w/ the compliance folks and we're ok turning off the codesign injection for the .net repos.  It's basically a variable in the build.  Check out this PR for more context.  https://github.com/dotnet/arcade/pull/5049

**Comment by ViktorHofer** [comment]
Awesome, thanks. Closing.
