### ISSUE TITLE
Validate that published packaged don't depend on non published ones

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#5073]
If you have 2 assemblies in a repository, Packed, and Secret, and then look like this
### Packed
```
<IsPackable>true</IsPackable>

<ProjectReference Include="../Secret.csproj"/>
```

### Secret
```
<IsPackable>false</IsPackable>
```

Then when we do the BAR publish, we publish Packed, but not Secret, which means that any reference to Packed will cause a failure at runtime when it can't find Secret.dll, which is a really bad thing.

We should be able to have some logic to detect this, and error at some point in the build, I would think.

This hit arcade-services today, and it's a really easy trap to fall into when refactoring code, because everything works locally, and the dependency update won't fail either, since everything builds fine.

**Comment by tmat** [comment]
This tool checks package dependencies and reports warnings: https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.NuGetRepack

It's currently only used when the repo opts-into building all flavors of packages (release/pre-release/per-build) during each build. This mode is alternative to the default Arcade package labeling mode controlled by `DotNetFinalVersionKind`.

**Comment by markwilkie** [comment]
@jcagme - is this something that could (should) go in the validation ring?

**Comment by jcagme** [comment]
This feels more of a thing to include during build. For one, I don't know (I will check) if this tool can run against already built and published packages. If that is the case, we would only be checking end-repo packages, which for example, not include arcade, arcade-services, etc.

**Comment by JohnTortugo** [comment]
@tmat - I think most people use the `DotNetFinalVersionKind` control, right? Would it make sense to have the tool/SDK patched to make it work with `DotNetFinalVersionKind`? IMO this looks like an interesting validation to have by default (in the SDK) and a flag to disable it if needed.

**Comment by garath** [comment]
@mmitche Thoughts?

**Comment by mmitche** [comment]
I think JC put this in the validation ring already.

**Comment by riarenas** [comment]
>I think JC put this in the validation ring already.

CC @jcagme to confirm. We can close if that's the case.

**Comment by riarenas** [comment]
@jcagme ping!

**Comment by jcagme** [comment]
Yes this already been checked in the validation ring

**Comment by ChadNedzlek** [comment]
Is this done as part of my build? The "validation ring" doesn't sound like at all what I wanted.  I want my build not to work if I've screwed up the package versions.

**Comment by mmitche** [comment]
This requires the closure of all packages about to be released to determine. It's basically looking to see whether all packages that will be published to nuget.org only depend on other packages that would be published to nuget.org, or are on nuget.org already.

Your build will work just fine if you produce packages that are depending on non-shipping packages, even within your own repo. It's about viewing the world from the customer's point of view, rather than from the build's.

**Comment by mmitche** [comment]
Oh oh I gotcha. Within arcade you may be able to check this? But since we don't control ProjectReference it may not be super easy. Honestly this sounds more like NuGet and the .NET SDK should be checking this kind of thing, rather than arcade. /cc @wli3

Also, there may be cases where it's totally valid to do this, like if `Packed` is set up to include all the content in Secret (in which case there would be no dependency).

**Comment by ChadNedzlek** [comment]
If Packed was set up to include all the content, why would there be a project reference?  I guess maybe it is a little weird that NuGet doesn't provide some sort of warning here... I'm not even sure what it's going to write down... like... what package ID doesn't the "Packed" nuget package reference? Since the Secret package isn't actually a package...  I wonder if there is an issue in their repository somewhere...

**Comment by nkolev92** [comment]
Making sure I understand the scenario here. 
Packed has ProjectReference to NotPacked, and Packed has a dependency to NotPacked in the nuspec when packed. 

It's not a scenario consider in pack right now as far as I know. 

Whether a package is included as a dependency is fully controlled by the project reference.

**Comment by ChadNedzlek** [comment]
Yup, which leads to a broken package.  "Packed" needs the stuff in NotPacked, and the project reference (and the resulting package) build fine, even though NotPacked isn't going to produce a package, so the reference it embeds won't be resolvable.

This feels like something that should be "warnable". Presumably the referenced package had to be loaded to read the package name out of... noting that it's not going to actually pack anything feels feasible?

**Comment by nkolev92** [comment]
Pack depends on restore & build, so it uses the name out of the assets file, it doesn't do it's own walk, but there is an ask for that https://github.com/NuGet/Home/issues/3891. 

We should be able to add a warning though, it just hasn't been something on our radar. 

I'd recommend you file an issue at NuGet/Home for this scenario :)

**Comment by ChadNedzlek** [comment]
Created https://github.com/NuGet/Home/issues/9797 hopefully to track this.  If it doesn't happen soon, I'll see what sort of target magic I can whip up... Publishing broken packages is pretty bad.
