### ISSUE TITLE
Microsoft.DotNet.ServiceFabric.ServiceHost package needs to build with the latest released Service Fabric Package(4.0.470)

### ISSUE THREAD

**Issue by sunandabalu** [dotnet/arcade#5079]
If you create a new Service Fabric application, the default version of Microsoft.ServiceFabric.Services ie 4.0.470 whereas Microsoft.DotNet.ServiceFabric.ServiceHost package in arcade-services uses an older version of the SF package (3.3.644) making it unusable with the latest SF packages. Microsoft.DotNet.ServiceFabric.ServiceHost should be built with the latest SF package.

**Comment by sunandabalu** [comment]
More context can be found on this PR - https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/6624?_a=overview

While including the package for Microsoft.DotNet.ServiceFabric.ServiceHost from arcade-services host, I ran into the following issues when I was doing it:

a) Microsoft.ServiceFabric.Services and Microsoft.ServiceFabric.Actors are currently on 4.0.470 while Microsoft.DotNet.ServiceFabric.ServiceHost is still using older version (3.3.664), so unable to add the package.

b) Lowering the Microsoft.ServiceFabric.Actors version to 3.3.664, gave an error while building the actor service
```
An assembly specified in the application dependencies manifest (FabActUtil.deps.json) was not found:
      package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '3.1.0'
      path: 'SOS_README.md'
```
https://dev.azure.com/dnceng/internal/_build/results?buildId=562603&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=7510ef29-db76-5a4c-4d87-8cd81d6b33b8

**Comment by ChadNedzlek** [comment]
That's a pretty big change.  Hopefully it won't break too much.

**Comment by ChadNedzlek** [comment]
Presumably it should also be possible to go the other way.  Lower the version of the application that is getting built.

**Comment by alexperovich** [comment]
I'm gona grab this one because its also causing problems with my changes.

**Comment by alexperovich** [comment]
This is published and working.
