### ISSUE TITLE
[Signing] Make SignTool accept and sign .jar files

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#509]

**Comment by JohnTortugo** [comment]
@anurse @natemcmaster @tmat Which certificate/strong-name should be used for signing .jar files?

**Comment by natemcmaster** [comment]
I don't see a friendly name listed in MicroBuild docs, but the ESRP keycode is CP-232612-Java.

**Comment by JohnTortugo** [comment]
Thanks for the info @natemcmaster . I'm using that as the certificate name. Is there a way we can double check if ESRP keycode == certificate name?

**Comment by natemcmaster** [comment]
@JohnTortugo I'm not sure. I'll send an email to the MicroBuild team to clarify.

**Comment by JohnTortugo** [comment]
I'll move this issue/PR to blocked beacause @natemcmaster is looking what is the right certificate to be used for the .jar files.

**Comment by JohnTortugo** [comment]
@natemcmaster comment here: https://github.com/dotnet/arcade/pull/517#discussion_r212161389
> Could this be generalized to more file types which do not need to zip/rezip? e.g.

Which certificate will these files use? Can we assume that all repos that use files with such extensions will use the same certificate?

**Comment by tmat** [comment]
> Can we assume that all repos that use files with such extensions will use the same certificate?

We can always have a default and means to override it if necessary.

**Comment by JohnTortugo** [comment]
That's what I was thinking (have defaults), but was wondering if overriding would be needed.

**Comment by natemcmaster** [comment]
I think it makes sense to have a file extension -> default cert mapping. We already have the beginning of one.

To cover aspnet scenarios:

Extension | Default cert name
----|-------
jar | (friendly name pending) CP-232612-Java.
vsix | Vsix (aka OPC)
nupkg | NuGet
exe, dll, js, ps1, psd1, psm1, psc1 | Microsoft 
dylib | Apple



See https://microsoft.sharepoint.com/teams/prss/esrp/info/ESRP%20Onboarding%20Wiki/Selecting%20CodeSign%20Certificates.aspx for a complete list of what's available.
