### ISSUE TITLE
[darc/maestro++] Interrupted gather-drop can cause file not found exceptions on rerun

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5093]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

If a gather-drop is interrupted (e.g. run out of disk space), then --skip-existing is used on the subsequent download, we can get file not found exceptions.  What is probably happening is that we copy from the source location->many target locations. I think we end up deciding that we should not skip if one of the target locations is present, but then we try to copy to the release layout from a  non-present target location, causing the error.

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade-services/pull/1060

**Comment by riarenas** [comment]
This has been rolled out.
