### ISSUE TITLE
Explore ability to flow nuget.exe without going through the .net sdk

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#5095]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

While it's not yet clear exactly how we could reasonably do this, and the risk of a meaningful torn state is significant, we should look more carefully at what it would mean to flow these kinds of high impact tools that the infrastructure also uses, for the express purpose of taking blocking bug fixes quickly.

cc/ @jaredpar @mmitche

**Comment by garath** [comment]
Triage: Close it.
