### ISSUE TITLE
Symbol files are not being published

### ISSUE THREAD

**Issue by jmarolf** [dotnet/arcade#5102]
- [x] This issue is blocking

Automated insertions into Visual Studio are completely blocked.

- [X] This issue is causing unreasonable pain

In [this](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/236801) PR we get a failed symbol check for the assemblies that are being inserted.

log of failure is [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1085970)

Note that this add hours on to insertion times for us as insertions can no longer be automatic (we need to manually override the checks when this fails). Combine this across multiple branches and I am quickly losing days of time :(

**Comment by tmat** [comment]
Seems that the build does not publish to any channel:
https://dev.azure.com/dnceng/internal/_build/results?buildId=567590&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76

We have the same problem in Roslyn. But it might be our fault that we did not specify default channel for a branch from which we are inserting.

**Comment by riarenas** [comment]
Correct, these are the only default channels for winforms-designer: 
```
(994)  https://dev.azure.com/dnceng/internal/_git/dotnet-winforms-designer @ pdb-publish-test -> General Testing
(757)  https://dev.azure.com/dnceng/internal/_git/dotnet-winforms-designer @ master -> .NET Internal Tooling
``

**Comment by riarenas** [comment]
Closing as this is not an arcade issue. Default channels should be created in order for branches to perform any sort of publishing.

Instructions on setting up a default channel can be found here: https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#add-default-channel

**Comment by tmat** [comment]
@riarenas Would it be possible to fail the build if there is no channel registered to publish to  - with an error message that points folks the right direction?

**Comment by jmarolf** [comment]
Why was this working for months and then stopped working then? What changed?

**Comment by riarenas** [comment]
We moved to the new model where publishing is detmrnined by default channels back in I want to say October last year?

What was the last build where you saw this working? @JohnTortugo made some changes recently to close some gaps where repos were publishing to the symbol servers during the build. Maybe related?

@tmat I think we can probably provide an *option* for repos to fail if publishing is not going to happen. There was a discussion about enforcing this and @mmitche had some sane arguments against it. https://github.com/dotnet/arcade/issues/3503 was the last time this was disussed.

**Comment by markwilkie** [comment]
My understanding is that this came about because of the new branch - which wasn't setup.  Is that correct @jmarolf ?    (publishing doesn't "just move" with the branch of course)

If so, discussions have been spawned (again) about what we could potentially do to provide additional visibility/help for publishing - which is a good conversation to have.

@jmarolf - can you confirm that this specific instance is taken care of now?  If so, we can continue the conversation about the desired state in #3503 - which I just reopened.

**Comment by ilyas1974** [comment]
It appears the wrong variable group was set up (per @MattGal). Closing issue.

**Comment by riarenas** [comment]
This was not the variable group. It was due to a lack of a default channel

**Comment by MattGal** [comment]
Yes my bad, I mixed up the two.
