### ISSUE TITLE
Stop using dn-bot-dnceng-artifact-feeds-rw secret for enabling x-org publishing 

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5103]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain
It makes it really hard to manage our secrets appropriately when a PAT does more than its name implies

The step to [enable authentication for package publishing across orgs](https://github.com/dotnet/arcade/blob/d1c752bbdb56989be87ec72934a9200d7fbf95fb/eng/common/templates/post-build/channels/generic-public-channel.yml#L131) uses the `dn-bot-dnceng-artifact-feeds-rw` secret. The naming convention implies that this token only has scope for dnceng, while in fact it has access to all accessible azdo accounts. We should consider changing this secret to another, more appropriately named one.

This change would need to happen in both the release/3.x, release/5.x and main branches of arcade

**Comment by riarenas** [comment]
I'm not sure where to triage this after it was punted out of the secret management epic. Maybe FR? or the publishing debt epic?

**Comment by alexperovich** [comment]
This feels very much like publishing debt to me.

**Comment by riarenas** [comment]
Sending it there for now.

**Comment by riarenas** [comment]
The secret-sweep and clean epic didn't exist at the time, but this seems like a good candidate for that and noticed this is still scary. I'll take care of this

**Comment by riarenas** [comment]
This looks to be working fine in the latest runs of the publishing pipeline in both organizations where we have build promotion.
