### ISSUE TITLE
[QCR][Errors] Identify infra vs product errors

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#5111]
It is super important that 1) We identify when things failed and 2) We can distinguish between a product error and a infra error. This should be straight forward for things in rel-tool but might be challenging for scripts/toll that we consume from external sources like arcade, hence the main goal would be to have everything in rel-tool. 

As part of this, we should also define what's the retry flow, if any. For example, if msdl is down, most likely we want to retry, but if there are incorrect symbols, we should fail. Also, who should be notified, etc.

**Comment by Tohron** [comment]
No apparent issues, so closing.
