### ISSUE TITLE
Investigate what's going on in symbol publishing for dotnet/extensions

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#5124]
- [x] This issue is blocking
- [x] This issue is causing unreasonable pain

Dotnet/extensions VS insertions are failing due to symbol check error. Investigation so far is pointing that something is wrong with the Windows PDB file for the .Net Standard tfm.

I'll update this issue with more information as I progress in the investigation.

/cc @NTaylorMullen @dougbu @leculver @tmat

**Comment by JohnTortugo** [comment]
@NTaylorMullen - Which was the Extensions latest successful VS insertion? I ask because it seems that this symbol check problem goes as far back as 2020/Jan.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen - Which was the Extensions latest successful VS insertion? I ask because it seems that this symbol check problem goes as far back as 2020/Jan.

The last time we successfully inserted we weren't using the Microsoft.Extensions libraries but that was back in Nov 2019. We made changes to run our Razor langauge server in-process (depends on the MS.Extensions libs) in VS which then resulted in us failing the symbol check verification 😄

**Comment by JohnTortugo** [comment]
Update with my findings so far:

- This issue goes as far as I could check: September/2019. I.e., symbol check for .Net Standard 2 isn't working.
- The issue seems to be specific for `Microsoft.Extensions.Configuration.Json` ; I checked other packages and the symbol validation passes.
- I inspected the differences between the dumps of netstandard2 PDB and netcoreapp5 PDB and former seems to be missing some modules, which right now is my best guess for the root of the problem. Here is the relevant part of the dump:

For .NetCoreApp5:

```
0001 "DAE45467" "Microsoft.Extensions.Configuration.JsonConfigurationExtensions"
0002 "A7F29791" "Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser"
0003 "BCD6E4D9" "Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider"
0004 "09ED1952" "Microsoft.Extensions.Configuration.Json.JsonConfigurationSource"
0005 "57A69647" "Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationProvider"
0006 "B832B374" "Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationSource"
0007 "E60FDB24" "Microsoft.Extensions.Configuration.Json.Resources"
0008 "D4EE145D" "Microsoft.Extensions.Configuration.JsonConfigurationExtensions.<>c__DisplayClass3_0"
0009 "02B7F740" "Microsoft.Extensions.Configuration.JsonConfigurationExtensions.<>c__DisplayClass5_0"
000A "7FBDA2D2" "<DanglingDocuments*223343bd-a859-41a3-90c0-9dfa101f1a95>"
```

For .Net Standard 2:

```
0001 "DAE45467" "Microsoft.Extensions.Configuration.JsonConfigurationExtensions"
0002 "BCD6E4D9" "Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider"
0003 "09ED1952" "Microsoft.Extensions.Configuration.Json.JsonConfigurationSource"
0004 "57A69647" "Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationProvider"
0005 "B832B374" "Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationSource"
0006 "7FBDA2D2" "<DanglingDocuments*223343bd-a859-41a3-90c0-9dfa101f1a95>"
```

@NTaylorMullen - I'm not very familiar with PDB format... but I think there is something going on with symbol generation for .Net Standard 2. What do you think? /cc @tmat

**Comment by NTaylorMullen** [comment]
> I'm not very familiar with PDB format... but I think there is something going on with symbol generation for .Net Standard 2. What do you think?

From the bits you posted it definitely seems like there's significant differences happening between netcoreapp5 and netstandard2. That being said I'm also not very familiar with the PDB format and therefore don't have the context to weigh in on if that's the core issue. @tmat are you the right SME in this matter or is there someone else?

**Comment by tmat** [comment]
The Windows PDB does not match the DLL (`sig70` != `guid`)

```
> pdbdump Microsoft.Extensions.Configuration.Json.pdb hdr
Header for 'Microsoft.Extensions.Configuration.Json.pdb' = {
        impv  =   20000404
        age   = 0x1 (1)
        sig   = 0xa4feb935
        sig70 = {17F4E96C-00A3-43CE-8AD0-7E893C0B8691}
        }
```

```
>mdv Microsoft.Extensions.Configuration.Json.dll /il- /md-
Debug Directory:
  CodeView stamp=0xB35B0FD4, version=(0x0100, 0x504D), size=148
    path='/_/artifacts/obj/Microsoft.Extensions.Configuration.Json/Release/netstandard2.0/Microsoft.Extensions.Configuration.Json.pdb', guid={5fdec507-eadc-4010-be7e-7459b6e6c5ec}, age=1
  PdbChecksum stamp=0x00000000, version=(0x0001, 0x0000), size=39
  Reproducible stamp=0x00000000, version=(0x0000, 0x0000), size=0
```

**Comment by dougbu** [comment]
Any suggestions what could mess up one of the GUIDs @tmat❔ I don't see anything TFM-specific in our MSBuild code.

**Comment by tmat** [comment]
I don't know, I'd need to see the binlog but it's not available. Just sent email.

**Comment by JohnTortugo** [comment]
@tmat helped a lot and set up a PR to fix this: https://github.com/dotnet/arcade/pull/5150

**Comment by dougbu** [comment]
Agree this is great. Why is #5150 unmerged?

**Comment by JohnTortugo** [comment]
I was expecting him to do it; but I went ahead and just merged it.

**Comment by tmat** [comment]
thanks. a lot of things to juggle...
