### ISSUE TITLE
List of tests for Dependency Update Error processor

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#5127]
- [x] This issue is blocking  -  Tests are a must have 
- [ ] This issue is causing unreasonable pain

This issue is to track the following: 

- [x] Setting up the test infrastructure 

List of unit tests to be created [WIP]
[Edit] 

- [x]  Create an issue 
- [x] Update an issue body 
- [x] Update a comment body 
- [x] Descriptions for various methods 
- [x] Marker tag and parsing it

**Comment by riarenas** [comment]
What types of tests are these going to be?

All but the first one sound like unit tests, but testing GitHub authentication sounds more like a functional test, and it would probably require a different setup than any other unit tests.

Additionally, what do you hope to catch in the GitHub test? It seems like it'd be really susceptible to GitHub going down.

**Comment by epananth** [comment]
Mostly I'm going to be writing unit tests. 

For Github authentication, some thoughts are 

1) Use a fake token and probably check if the request header is set or not. 
2) Check if arguments are not null. 

More unit testing. 

We cannot do functional testing right? As per our previous conversation, please correct me if I am wrong, we will be adding fake errors in the db then creating issues out of that. We might end up creating non relevant ones which is not the right thing to do. This will unnecessarily create a lot of issues in github.

**Comment by epananth** [comment]
After discussing we Ricardo, github authentication seems like an overkill. So removing that from the list.
