### ISSUE TITLE
[darc/maestro++] Darc add-build-to-channel, allow publishing to multiple or all default channels at once

### ISSUE THREAD

**Issue by nohwnd** [dotnet/arcade#5134]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Darc tools allows adding build to a single channel like this:
`darc add-build-to-channel --id 1 --channel "channel1"` 

There are multiple default channels that are associated with the build and it would be nice to be able to add the build to all of by adding `--all-default-channels`, or `--channel *`, or similar syntax. 

This would make manual build promotion easier to handle, and would probably start only single promoting pipeline.

**Comment by riarenas** [comment]
I like this idea. This means we only trigger one build promotion pipeline and don't need to trigger multiple builds just wasting machine time.

CC @mmitche @epananth @JohnTortugo

**Comment by JohnTortugo** [comment]
AFAIU the goal of the promotion pipeline is to promote a build to a single channel, at least in the vast majority of the cases. Adding a build to all default channels is something that is and should be done at build creation time.

**Comment by riarenas** [comment]
That contradicts the goal of faster build times, having to make multiple darc commands means we will trigger multiple builds, using unnecessary resources.

I would go as far as to consider this a requirement if we want to use the build promotion pipeline for the merge only dependency flow.

**Comment by mmitche** [comment]
@JohnTortugo I've seen a few cases now where promotiing builds to multiple channels happens. For instance, nuget.client wants to promote to to .NET 5 Preview 3 and .NET Core SDK 3.1.3xx.

Maybe we just allow the command to take a comma separated list? it just ends up being a shorthand.

**Comment by JohnTortugo** [comment]
Yeah, I can see how this will be interesting moving forward.
