### ISSUE TITLE
[darc/maestro++] get-latest-build repository parameter is inconsistent

### ISSUE THREAD

**Issue by nohwnd** [dotnet/arcade#5135]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

`darc get-latest-build` uses `--repo` parameter, unlike other commands that use `--source-repo` parameter, which is slightly annoying, and unnecessarily inconsistent. Please consider renaming it or adding an alias.

**Comment by riarenas** [comment]
Sad to see my very convincing arguments weren't enough to dissuade you.

**Comment by JohnTortugo** [comment]
From a quick search I see that we use **"source-repo"** in these places (_6 out of 7 also use target-repo_):
- add-subscription
- delete-subscription
- get-subscriptions
- subscription-status
- trigger-subscription
- get-default-channels
- update-dependencies

We use "repo" in these places (which doesn't involve ideas of source+target repository):

- clone
- add-default-channel
- add-dependency
- gather-drop
- get-dependency-graph
- get-health
- **get-latest-build**
- get-repository-merge-policies
- set-repository-merge-policies
- update-default-channel
- default-channel-status

the way I see it we don't need to make a change in the parameter name for `get-latest-build`.

**Comment by nohwnd** [comment]
Maybe I just used the tool too little. Thanks!
