### ISSUE TITLE
[QCR][Validation ring] Signing Validation

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#5138]
Arcade SDK currently has a `.proj` that does signing validation. We should evaluate how hard would it be to port https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/SigningValidation.proj to `rel-tool`. If the work is too much, which I don't think it would be, we should just use this `.proj` to add signing validation to the Validation ring.

**Comment by adiaaida** [comment]
This was checked in. Closing (there is no rollout procedure for the release repo).
