### ISSUE TITLE
[darc/maestro++] darc-add-build-to-channel command failing after the build promotion pipeline succeeds publishing assets

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5139]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain
users using this command to test things / add builds to channels after the fact are experiencing problems.

Got a few reports that darc fails the command after triggering and succeeding to run the build promotion pipeline that publishes the assets and attempts to add the build to the channel

```
 darc add-build-to-channel --id 46931 --source-branch master --source-sha c5358d4e1cc821f0b826a0eea75afd331aa2bbd0 --channel ".NET Core 3.1 Release"
Assigning the following build to channel '.NET Core 3.1 Release':
Repository: https://github.com/dotnet/test-templates
Branch: master
Commit: 2720fcade72d709a5d2fe80d0b80fbdac54213f6
Build Number: 20200326.1
Date Produced: 26/03/2020 17:49
Build Link: https://dev.azure.com/dnceng/internal/_build/results?buildId=574617
BAR Build Id: 46931
Released: False
Channels:
- .NET Core 5 Dev
Build 46931 will be assigned to channel '.NET Core 3.1 Release' once this build finishes publishing assets: https://dnceng.visualstudio.com/internal/_build/results?buildId=576519
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
The promotion build finished but the build isn't associated with the channel. This is an error scenario. Please contact @dnceng.
```

FYI @JohnTortugo

**Comment by riarenas** [comment]
Another example of a successful build promotion pipeline that then reports a darc error:

https://dnceng.visualstudio.com/internal/_build/results?buildId=576493&view=results

**Comment by JohnTortugo** [comment]
> Another example of a successful build promotion pipeline that then reports a darc error:
> 
> https://dnceng.visualstudio.com/internal/_build/results?buildId=576493&view=results

What was the command line for this one and the darc output?

**Comment by riarenas** [comment]
Added to the comment

**Comment by riarenas** [comment]
Also, the first one is that it's trying to publish to a channel that doesn't have a publishing implementation in the selected arcade branch. I'll open a new issue about failing early for those cases. The build pipeline probably should've failed early instead of finishing with just the warning.

**Comment by JohnTortugo** [comment]
> Also, the first one is that it's trying to publish to a channel that doesn't have a publishing implementation in the selected arcade branch. I'll open a new issue about failing early for those cases. The build pipeline probably should've failed early instead of finishing with just the warning.

IMO these warning messages in AzDO aren't as apparent as they should. Second day two person didn't notice them. In hindsight I agree that failing early is better than the warning.

**Comment by riarenas** [comment]
Opened https://github.com/dotnet/arcade/issues/5141 to fail early

**Comment by riarenas** [comment]
Have you had a chance to look at why the second instance failed? that one seemed to even publish everything, so it should've been in the channel?

**Comment by JohnTortugo** [comment]
It's possible that it was just a matter of timing? I'll start looking in a few.

**Comment by riarenas** [comment]
I checked just in case, the build is still not in the channel :(

**Comment by JohnTortugo** [comment]
Now it got weird!!

**Comment by JohnTortugo** [comment]
What is happening is:

- Bottom line of the error is that the build being promoted didn't succeed: https://dev.azure.com/dnceng/internal/_build/results?buildId=576412
- For some reason the release pipeline runner is waiting steps of 15 minutes for the build to succeed. 
  - I found several records of this line in App Insights: https://github.com/dotnet/arcade-services/blob/production/src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs#L157

I'm going to delete the `ChannelReleasePipelines` entries so we don't trigger the release pipeline runner anymore and thus this shouldn't happen again.

**Comment by JohnTortugo** [comment]
> I'm going to delete the `ChannelReleasePipelines` entries so we don't trigger the release pipeline runner anymore and thus this shouldn't happen again.

Talked with v-team and did the above.
