### ISSUE TITLE
Helix SDK: Switch to using "dotnet vstest" or "dotnet test" for test execution

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#5143]
We are currently using "xunit.runner.console", but that package is quite old.  It doesn't even list .NET 3.1 as a supported runtime.

We should switch to a more actively support test triggering mechanism.

As part of this, we should ensure that we set the logging options so that test discover/execution is logged to the console (sometimes the XML file doesn't make it out the other end, like in timeouts, so having the console logs available in invaluable in this situtations). For vstest, this is "--logger:console;verbosity=normal", for test it's just "--verbosity normal"

**Comment by ChadNedzlek** [comment]
Note: This is going to be very painful, because we leaked WAY too much of the implementation details out.  People are counting on the XUnitArguments behavior, so this is going to be a long, painful road.

And we should probably take care that the next abstraction not be so leaky.  It should only accept the DLL that is to be run, and everything else should be standardized and non-customizable.

**Comment by ChadNedzlek** [comment]
This change will have to be opt-out-able. It looks like Roslyn and the SDK projects have taken some pretty huge dependencies on the internal implementations here, so we're going to have to have a way to leave them on the old crusty stuff so we don't break their whole world.

**Comment by davidfowl** [comment]
I did some digging and we need to support this as an option even if it's not the default. The vstest runner has better extensibility that we can hook to get better test diagnostics.

**Comment by davidfowl** [comment]
> As part of this, we should ensure that we set the logging options so that test discover/execution is logged to the console (sometimes the XML file doesn't make it out the other end, like in timeouts, so having the console logs available in invaluable in this situtations). For vstest, this is "--logger:console;verbosity=normal", for test it's just "--verbosity normal"

I did more investigation here so adding notes:
- You can specify multiple loggers when using the vstest command (akin to reporters in the xunit console runner)
- There's an xml logger for the xunit test results format https://github.com/spekt/xunit.testlogger
- The vstest console logger does not print out test started, test completed messages. In fact it can't because there's no way to get called for started tests when writing a custom logger (I have a thread with the team on this)
- It's possible to write a data collector that gets notified of start/stop tests and logs them to the output (I have a prototype)

**Comment by ChadNedzlek** [comment]
Here' is output from my console, the logging worked fine for me...

```
D:\github\arcade-services\artifacts\bin\Microsoft.DotNet.Monitoring.Sdk.Tests\Debug\netcoreapp2.1 > dotnet vstest .\Microsoft.DotNet.Monitoring.Sdk.Tests.dll --Blame --ResultsDirectory:. "--logger:console;verbosity=normal"
Microsoft (R) Test Execution Command Line Tool Version 16.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.28516.03)
[xUnit.net 00:00:00.93]   Discovering: Microsoft.DotNet.Monitoring.Sdk.Tests
[xUnit.net 00:00:00.97]   Discovered:  Microsoft.DotNet.Monitoring.Sdk.Tests
[xUnit.net 00:00:00.98]   Starting:    Microsoft.DotNet.Monitoring.Sdk.Tests
[xUnit.net 00:00:01.15]   Finished:    Microsoft.DotNet.Monitoring.Sdk.Tests
  √ DotNet.Grafana.Tests.MakePackTests.ExtractDataSourceNamesTest [30ms]
  √ DotNet.Grafana.Tests.MakePackTests.SanitizeDataSourceTest [11ms]

Test Run Successful.
Total tests: 2
     Passed: 2
 Total time: 1.7832 Seconds
```

**Comment by ChadNedzlek** [comment]
Oh darn, that's just assembly again, yeah, that's no good.  it only does the check after the test finishes (which is no good figuring out which one hung)

**Comment by davidfowl** [comment]
Here's the DataCollector I wrote. This needs to go into an assembly that ends up *.Collector.dll. See https://github.com/Microsoft/vstest-docs/blob/master/docs/extensions/datacollector.md#extend-datacollector.

It'll log tests as they run and dump what started and what ended.

```C#
using System.Xml;
using Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection;

namespace UnitTestingDiagnostics
{
    [DataCollectorFriendlyName("execution")]
    [DataCollectorTypeUri("datacollector://Microsoft/TestPlatform/Extensions/execution/v1")]
    public class ExecutionCollector : DataCollector
    {
        public override void Initialize(XmlElement configurationElement, DataCollectionEvents events, DataCollectionSink dataSink, DataCollectionLogger logger, DataCollectionEnvironmentContext environmentContext)
        {
            events.TestCaseStart += (sender, e) => logger.LogWarning(environmentContext.SessionDataCollectionContext, e.TestCaseName + " [Start]");
            events.TestCaseEnd += (sender, e) => logger.LogWarning(environmentContext.SessionDataCollectionContext, e.TestCaseName + " [Ended]");
        }
    }
}
```

Here's my test case:

https://gist.github.com/davidfowl/5227871499007b53c60c1dbdfe95fd02

**Comment by davidfowl** [comment]
The output looks like this:

```
Microsoft (R) Test Execution Command Line Tool Version 16.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:06.61]     XUnitTestProject1.UnitTest1.Test2 [FAIL]
  X XUnitTestProject1.UnitTest1.Test2 [5s 16ms]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False
  Stack Trace:
     at XUnitTestProject1.UnitTest1.Test2() in C:\Users\davifowl\source\repos\XUnitTestProject1\XUnitTestProject1\UnitT
est1.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.InvalidOperationExcept
ion: Operation is not valid due to the current state of the object.
   at XUnitTestProject1.OtherComponent.<Execute>g__BuggyCode|0_1() in C:\Users\davifowl\source\repos\XUnitTestProject1\
XUnitTestProject1\UnitTest1.cs:line 22
   at XUnitTestProject1.OtherComponent.<>c__DisplayClass0_0.<Execute>b__0(Object _) in C:\Users\davifowl\source\repos\X
UnitTestProject1\XUnitTestProject1\UnitTest1.cs:line 16
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Data collector 'execution' message: XUnitTestProject1.UnitTest1.Test1 [Start].
Data collector 'execution' message: XUnitTestProject1.UnitTest1.Test1 [Ended].
Data collector 'execution' message: XUnitTestProject1.UnitTest1.Test2 [Start].
Data collector 'execution' message: XUnitTestProject1.UnitTest1.Test2 [Ended].
Data collector 'execution' message: XUnitTestProject1.UnitTest1.CrashTestRunner [Start].

Test Run Aborted.
Total tests: Unknown
     Passed: 1
     Failed: 1
 Total time: 8.6870 Seconds
```

**Comment by davidfowl** [comment]
Turns out the built in --blame collector does this already:

```
Test run for C:\Users\davifowl\source\repos\XUnitTestProject1\XUnitTestProject1\bin\Debug\netcoreapp3.1\XUnitTestProject1.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:07.08]     XUnitTestProject1.UnitTest1.Test2 [FAIL]
  X XUnitTestProject1.UnitTest1.Test2 [5s 5ms]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False
  Stack Trace:
     at XUnitTestProject1.UnitTest1.Test2() in C:\Users\davifowl\source\repos\XUnitTestProject1\XUnitTestProject1\UnitTest1.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.InvalidOperationException: Operation is not valid due t
o the current state of the object.
   at XUnitTestProject1.OtherComponent.<Execute>g__BuggyCode|0_1() in C:\Users\davifowl\source\repos\XUnitTestProject1\XUnitTestProject1\UnitTest1.cs:li
ne 22
   at XUnitTestProject1.OtherComponent.<>c__DisplayClass0_0.<Execute>b__0(Object _) in C:\Users\davifowl\source\repos\XUnitTestProject1\XUnitTestProject
1\UnitTest1.cs:line 16
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
XUnitTestProject1.UnitTest1.CrashTestRunner


Attachments:
  C:\Users\davifowl\source\repos\XUnitTestProject1\XUnitTestProject1\TestResults\1636e416-fd71-4781-9918-c58416063c73\Sequence_326e44fd6e7b4a29977053ea0
bdb4a28.xml
Test Run Aborted.
Total tests: Unknown
     Passed: 1
     Failed: 1
 Total time: 9.2878 Seconds
```

**Comment by ChadNedzlek** [comment]
I think I've got something basic worked up here.  A PR will be available soon.

**Comment by ChadNedzlek** [comment]
I tried this, and the RemoteExecutor is blowing up in strange ways... there only appear to be like 4 tests for the thousand plus lines of code, and the failure states don't really make any sense to me, so I'm a bit blocked.  I could check it in with these tests disabled, but I assume people care about the RemoteExector.

Here's a log from one of the failures: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-arcade-helix-dotnet-test-c281b10da5b54ead8e/DotNetTestRunner.Microsoft.DotNet.RemoteExecutor.Tests.dll/console.d463368e.log?sv=2019-02-02&se=2020-08-14T01%3A41%3A11Z&sr=c&sp=rl&sig=voNF4IjlOXepaX%2BvywCah8QWI1hpoJyxaY3RmxfjQE0%3D

If I don't set "DOTNET_ROLL_FORWARD", the tests don't execute at all because of a framework version mismatch.  Here's a log for that https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-arcade-helix-dotnet-test-9b5bfe7aa5ff4527ac/Microsoft.DotNet.RemoteExecutor.Tests.dll/console.7cbfca24.log?sv=2019-02-02&se=2020-08-13T22%3A36%3A01Z&sr=c&sp=rl&sig=FkqzAXIBuojTNTo1eGj%2BMBlSVKsnx8nJ7UON6U0gZ5s%3D

I assume the problem is that my DOTNET_ROLL_FORWARD command is poisoning the inner execution (since it doesn't clear that environment variable, and definitely tries to mess around with that setting).  Unfortunately, there doesn't appear to be a way to do the roll forward for "dotnet test" without the environment variable.  It doesn't have a "--roll-forward" command line argument.

**Comment by ChadNedzlek** [comment]
I'm going to close this for now. There doesn't seem to be any need/desire for this to happen right now, and there will be a bigger effort in the future to consolidate test execution, and this work is likely very different in that ecosystem.
