### ISSUE TITLE
Add "-verbose" the the call to xunit.console.runner

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#5146]
https://github.com/dotnet/arcade/issues/5143 is a pretty big one, in the meantime, we could get some cheap benefit here by just adding "-verbose" to the call to XUnit to make the console logs more useful.

**Comment by markwilkie** [comment]
As far as I know, we're in an ok place because of the dump effort late in 2020.  If I'm wrong, please reopen.
