### ISSUE TITLE
The arcade-minimal-sample should accurately reflect how we want people to use Helix

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#5180]
I've talked with several people on the team, and they all agree that the way https://github.com/dotnet/arcade-minimalci-sample/blob/master/azure-pipelines.yml uses Helix is bad and wrong, and no actual repository uses it that way.

Our sample shouldn't tell people a bad and wrong way to do the thing.

**Comment by riarenas** [comment]
How can we point people to the right direction if they don't do it wrong first!!

(We definitely need to update minimalci-sample)

**Comment by garath** [comment]
Triage: 

- Consider closing the repository in favor of "samples" via the validation project. cc/ @alexperovich 
- More, fundamental, doc issues around send-to-helix and dependency flow need separate investigation cc/ @ChadNedzlek

**Comment by missymessa** [comment]
We deleted the sample repo, and will create new samples in the future if there is a need.
