### ISSUE TITLE
Add better build lookup commands to darc

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5194]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Right now to get build info in darc, as well as perform many other commands, you need the BAR build ID. this is sometimes annoying to get and involves trolling through logs. Instead, build lookup should be available by:
- AzDO URI
- repo+sha

**Comment by MattGal** [comment]
@mmitche pretty much already this, other than the "AzDO URI" version above is no longer wanted and the repo/sha stuff didn't support substring match.  Both addressed via https://github.com/dotnet/arcade-services/pull/1337

**Comment by MattGal** [comment]
Rolled out yesterday, closing
