### ISSUE TITLE
Yet another odd CPD scenario that needs resolution

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5195]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Another odd CPD scenario where a dependency moved backwards from https://github.com/dotnet/aspnetcore-tooling/pull/1724. In this case, a dependency can move backwards unintentionally if it disappears from the dependency graph via an incremental servicing scenario. The CPD parent

From the conversation:

I figured it out. It's yet another reason why CPD is so complicated. So 4.7.1 disappeared from the graph. under core-setup because core-setup has no direct dependency on System.Runtime.CompilerServices.Unsafe.

So the previous release generated the 4.7.1 version of that assembly. It updated here properly because core-setup was referencing a version of corefx that produced that package. When we switched over for 3.1.4's build, we stopped producing a new S.R.CU as well as other out of band packages. That means that core-setup for 3.1.4 is not referencing **any** of the February build's corefx binaries any longer. Thus, the newest version in the graph was what it was before, which was 4.7.0.

You can either pin this here, or I can fix up core-setup to reference S.R.C.U at the shipping 4.7.1 version.

The other fix that we **could** make would be to change CPD so that it does not take into account builds. It only looks at direct dependencies. Currently you can do the following:

- A->CPD B
- B does not directly reference A, but references a dependency C from a build which also produced A.
- A resolves appropriately.

The advantage here is that aspnetcore-tooling for instance, doesn't need to reference every binary from extensions that aspnetcore may try to CPD. This means less bloated version details files in repos. Most of these dependencies that you would have to add are never actually used in this repo, just used downstream. This is also totally fine in cases where we do not do incremental servicing. The downside, of course, is that you can have this happen in incremental servicing cases.

I'm leaning towards **not** allowing build lookup in the CPD algorithm and fixing up all the repos. Of course, things like this make me also want to ban CPD altogether in 5.0 branches. It's insanely complicated.

**Comment by dougbu** [comment]
I'm :ok: with pinning the System.Runtime.CompilerServices.Unsafe dependency in aspnetcore-tooling and aspnetcore as long as that doesn't cause problems for any CPD relationships higher in the stack.

**Comment by mmitche** [comment]
It will not. In fact, it will proibably do good things.

**Comment by dagood** [comment]
Assuming I'm CC'd because of my recent question about CPD (me not knowing it was recursive). Interesting coincidence this came up. 😄

My interest in CPD is because of this source-build 5.0 feature/requirement: [Add forced coherency ability to "darc clone" rather than maintaining a dependency for every repo #1495](https://github.com/dotnet/source-build/issues/1495). I [currently think](https://github.com/dotnet/source-build/issues/1495#issuecomment-608047506) that we need to mark certain deps as "coherentizing", but I'm still actively working on prototyping:

> Right now I think marking specific dependencies with "ends up in the SDK product" is what we need. Then, during `darc clone`, the marked dependency's target repo overrides all dependencies on the same repo throughout the graph. If the same target repo is marked in two different dependencies in the graph as ending up in the SDK product, clone should fail.

I don't know if that's useful at all for Microsoft builds or dependency updates, but FYI.

**Comment by wtgodbe** [comment]
👀

**Comment by mmitche** [comment]
Alright, here's the proposal:

- We introduce a switch to darc update-dependencies called `strict-coherency`. This strict coherency will only find dependencies IN the dependency files. If the dependency is not found in any version details file under the CPD parent, the lookup will fail.
- In addition to only looking for things in dependency files, CPD behavior will be altered so that instead of choosing the newest **build**, it will choose the **highest semantic version** of a dependency. in 99.99% of cases, these should match.  Where they don't match today, the current behavior is probably not what we want.  Doing this will allow us to avoid a build lookup per dependency, which will make CPD much cheaper.

Then for rollout, we will go through the 3.1 and 5.0 branches and use this new switch to identify all places where we need to add **new** dependencies to various repos to account for the new beahvior. What this looks like is that if dotnet/extensions has a CPD on core-setup for some corefx dependencies, those corefx dependencies need to be referenced in core-setup in order to resolve.

Once we have resolved all these cases, we will turn on strict CPD as the default behavior in Maestro and remove the switch.
