### ISSUE TITLE
Arcade repo should be given meaningful name.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/arcade#52]
How about not using a silly project name and give this repo a meaningful name?   Let's continue to use meaningful names within the dotnet organization.  It really helps newbies understand things when we aren't using meaningless project names.

**Comment by jac009** [comment]
Are we too far down this road to shift repos to a better name?  I'm with @MichaelSimons  on this one :)

**Comment by markwilkie** [comment]
Just talked to @jac009, and given that we already have a repo building in the open, not to mention quite a bit of momentum with the current name, I'm unfortunately closing the issue again.

Having said that - no more code names......   It is tough to keep track and "map" for sure.
