### ISSUE TITLE
Microsoft.DotNet.XUnitExtensions auto update into corefx

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#520]
Not following on the various topics around Darc/Maestro++/BAR so please excuse naive questions but what needs to be done to auto update one of the packages built here into corefx? I'm talking about `Microsoft.DotNet.XUnitExtensions` which we consumed from buildtools which was auto updated before.

**Comment by dagood** [comment]
I was poking through some old issues, and saw this ties into https://github.com/dotnet/arcade/issues/441 "Arcade should update the versions repo with published versions".

Arcade apparently doesn't currently have a way to update dotnet/versions (which would enable this version flow now). It seems like Arcade packages won't be auto-updateable until CoreFX is onboarded to Darc/Maestro++/BAR.

@jcagme @maririos @markwilkie @weshaggard is this correct?

**Comment by dagood** [comment]
To clarify what I'm hoping to understand from the question: if it's true that Arcade doesn't update dotnet/versions (and it's not a quick fix), that puts a maintenance burden on repos like CoreFX that are trying to onboard to Arcade packages. In that case I think we should reopen https://github.com/dotnet/arcade/issues/441.

It should be a matter of copying a single MSBuild task from BuildTools with a dependency on VersionTools and using it in the Arcade build to get dotnet/versions updates working.

**Comment by markwilkie** [comment]
This should be taken care of as part of the dependency flow work that's part of 3.0.  Feel free to reopen is that turns out to be insufficient or the timing is off.
