### ISSUE TITLE
Investigate why longest build path is broken for .Net 5 Dev channel

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#5209]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Sometime 4/2/2020 or 4/3/2020, something changed so that longest build path stopped working for the .Net 5 Dev channel. Around this time the channel name changed from .Net Core 5 Dev to .Net 5 Dev, which should not have affected anything, as we use the channel ids to get the channel names, but it's possible that that broke something.

This is broken in both BarViz (Maestro.Web) and the over time code (DependencyUpdater), but probably has something to do with DependencyFlowGraph.IsInterestingNode or DependencyFlowGraph.IsInterestingEdge.

To debug: run barviz locally, using prod data. Insert breakpoints so that you can check the flow graph after we call BuildAsync (which should be fine), and after/while we prune the graph. Then go to your local barviz and click on the .Net 5 Dev.

When this is fixed, .Net 5 Dev should have a similar graph to https://maestro-prod.westus2.cloudapp.azure.com/739/graph (rather than the currently blank graph it currently displays: https://maestro-prod.westus2.cloudapp.azure.com/131/graph). Assuming what is broken is in shared code, you shouldn't have to touch more than one spot, but you may need to fix things in Darc (GetFlowGraphOperation), DependencyUpdater.cs, and GetFlowGraphAsync in the ChannelsController.

**Comment by adiaaida** [comment]
<img width="1074" alt="Screen Shot 2020-04-06 at 11 13 37 AM" src="https://user-images.githubusercontent.com/9666644/78591040-ab224a00-77f7-11ea-8312-c6627ad15aa3.png">

As shown in this graph tracking longest build path time over time, the first time we collected this data, at midnight on 4/2, it was successful, but starting on 4/3, building the graph was not successful.

**Comment by alexperovich** [comment]
I can't reproduce the locally when accessing prod data. I will investigate to see what changed.

**Comment by alexperovich** [comment]
And... this appears to have been fixed by the recent prod rollout. If this comes back I can look deeper, but it is fixed now.

**Comment by adiaaida** [comment]
I bet that's why you couldn't repro it either.
