### ISSUE TITLE
[QCR][Validation ring] Arcade validation for the logo in the package

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/arcade#5218]
While searching for a package in NuGet noticed that the logo for one of the packages (built by arcade) was missing the .NET Logo. It would be good to have some kind of validation check to ensure all packages have the logo set correctly. 

![image](https://user-images.githubusercontent.com/3981619/78694830-17fa1a80-78b2-11ea-83bc-a90e781bde05.png)

**Comment by jcagme** [comment]
Talked to @joelverhagen and this check is not included in the tool we have in builds so we'd need to add an special check for this. @joelverhagen recommended using NuGet.Packaging APIs to check for an icon.
