### ISSUE TITLE
[AV] Status page for state of Arcade (part I)

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5230]
Since Arcade is no longer automatically flowing into .NET Eng - Latest, we want to keep our consumers up-to-date with the current state of Arcade. 

First iteration of this would be putting this status on the root README.md of the Arcade repo. It should contain the following information: 

- The current Arcade version in .NET Eng - Latest, and links to the darc/channel documentation. 
- The current Arcade version in the Validation channel as of the time the page was updated, and instructions for how to look up the latest version in the Validation channel. 
- The state of validating the latest version of Arcade (e.g. if all bell-weather repos are passing with Arcade; if we're unable to validate Arcade against one or more of the bell-weather repos)

**Comment by riarenas** [comment]
Isn't this the same as looking at barviz for the latest arcade in the latest channel? can't we just have a link to barviz for each channel?

https://maestro-prod.westus2.cloudapp.azure.com/2/https:%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_git%2Fdotnet-arcade/latest/graph

and 

https://maestro-prod.westus2.cloudapp.azure.com/9/https:%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_git%2Fdotnet-arcade/latest/graph

**Comment by riarenas** [comment]
And the third bullet point could maybe be a link to the latest build of the arcade-validation pipeline?

**Comment by JohnTortugo** [comment]
> Since Arcade is no longer automatically flowing into .NET Eng - Latest, we want to keep our consumers up-to-date with the current state of Arcade.

Question: So we are doing the promotion manually, right? We plan to keep doing it manually in the long term? I'm not very familiar with the matter, so I'm wondering why can't Arcade builds be automatically promoted anymore?

**Comment by markwilkie** [comment]
@JohnTortugo - more context here:  https://github.com/dotnet/arcade/blob/master/Documentation/Validation/Overview.md

**Comment by missymessa** [comment]
Merged this. Closing
