### ISSUE TITLE
SDL configuration caching fails

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/arcade#5238]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Every time SDL verifications run, scripts fail to properly cache the `.gdn` configurations, resulting in an init every time. Looks like `push-gdn` fails to authenticate each time. 

```log
git add .
fatal: not a git repository (or any of the parent directories): .git
git -c user.email="dn-bot@microsoft.com" -c user.name="Dotnet Bot" commit -m "Initialize gdn folder for Diagnostics/test"
fatal: not a git repository (or any of the parent directories): .git
git push
fatal: not a git repository (or any of the parent directories): .git
```

Prior to this looks like cloning fails. Is the secret being used still valid and does it have enough scope? There's been no updates to any config since Aug 2019, even though there's customers than onboarded to SDL after that.

@jonfortescue

**Comment by markwilkie** [comment]
cc/ @sunandabalu

**Comment by sunandabalu** [comment]
This is how it has been for a while, it has not blocked the SDL runs. Something we should def investigate, @jonfortescue may have some ideas.

**Comment by jonfortescue** [comment]
I've definitely been noticing this. I'll investigate.

**Comment by jonfortescue** [comment]
This is non-blocking and the original intent is outmoded now that TSA is used for everything. I'm just going to remove this from the scripts.

**Comment by jcagme** [comment]
@jonfortescue you have any updates on this?

**Comment by jonfortescue** [comment]
This PR stalled out because removing this portion ended up causing side effects I didn't have bandwidth in April to investigate. However, it will be covered when we shift away from scripts in this epic: https://github.com/dotnet/core-eng/issues/10186

Closing since it will be covered by this work. cc / @sunandabalu

**Comment by sunandabalu** [comment]
> This PR stalled out because removing this portion ended up causing side effects I didn't have bandwidth in April to investigate. However, it will be covered when we shift away from scripts in this epic: [dotnet/core-eng#10186](https://github.com/dotnet/core-eng/issues/10186)
> 
> Closing since it will be covered by this work. cc / @sunandabalu

Yep I was literally typing the same thing :) Since this is not blocking the SDL runs, we can table this in favor of moving to Guardian AzDO tasks.

**Comment by adiaaida** [comment]
Reopening this issue since the reason we closed it is not viable, and we should remove this dead code.

**Comment by garath** [comment]
I believe @jakubstilec has this sorted and is just waiting until his next FR rotation to implement.

**Comment by jakubstilec** [comment]
@garath now it's safe to remove push to SDL configuration as it always reinitializes at the begin and this steps isn't used any more. I'll updated it next week.

**Comment by jakubstilec** [comment]
PR: https://github.com/dotnet/arcade/pull/6994/files

**Comment by jakubstilec** [comment]
The PR was merged.
