### ISSUE TITLE
error MSB4066: The attribute "Include" in element <_SolutionRestoreProps> is unrecognized.

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5243]
- [x] This issue is blocking 
This is blocking flow of Arcade.
- [ ] This issue is causing unreasonable pain

When https://github.com/dotnet/arcade/pull/5226 made it to arcade-validation, the build started failing. See https://dev.azure.com/dnceng/public/_build/results?buildId=598332&view=results for the latest build. https://github.com/dotnet/arcade-validation/pull/1409 is blocked due to this.

@safern @ViktorHofer

**Comment by safern** [comment]
Hmm, I don't know how we didn't catch this in the PR. The Item is defined in a `PropertyGroup` section: https://github.com/dotnet/arcade/pull/5226/files#diff-dd56d402696a527015ce4c6de1e9a53bR201

@ViktorHofer are you planning on fixing this?

**Comment by riarenas** [comment]
Fixed via #5249
