### ISSUE TITLE
Errors loading GenerateAzureDevOpsBuildManifest in linux

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5255]
- [x] This issue is blocking 
This is blocking Arcade from flowing to other repos
- [ ] This issue is causing unreasonable pain

Arcade -> Arcade-Validation Dependency flow PR https://github.com/dotnet/arcade-validation/pull/1409 is failing in linux legs with:

```
/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20213.5/tools/Publish.proj(250,5): error MSB4062: The "Microsoft.DotNet.AzureDevOps.Build.GenerateAzureDevOpsBuildManifest" task could not be loaded from the assembly /__w/1/s/.packages/Microsoft.DotNet.AzureDevOps.Build/5.0.0-beta.20213.5/tools/netcoreapp2.1/Microsoft.DotNet.AzureDevOps.Build.dll. Could not load file or assembly '/__w/1/s/.packages/Microsoft.DotNet.AzureDevOps.Build/5.0.0-beta.20213.5/tools/netcoreapp2.1/Microsoft.DotNet.AzureDevOps.Build.dll'. The system cannot find the file specified.
/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20213.5/tools/Publish.proj(250,5): error MSB4062:  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

This was introduced in https://github.com/dotnet/arcade/pull/5210

CC @chcosta

**Comment by chcosta** [comment]
ack, looking

**Comment by chcosta** [comment]
Unfortunately, this succeeds on my local repro attempts when building against the same merge branch and running in the same docker container.  I'm continuing to investigate.

**Comment by chcosta** [comment]
I'm stumped, can't get a repro, but this clearly repro's consistently in CI.  I'll continue to investigate tomorrow morning.

**Comment by chcosta** [comment]
I'll prepare a PR to change the manifest generation to opt-in while I investigate.
