### ISSUE TITLE
NPE with latest darc when adding build to channel

### ISSUE THREAD

**Issue by nkolev92** [dotnet/arcade#5280]
- [ ] This issue is blocking NuGet's insertion into .NET 5
- [ ] This issue is causing unreasonable pain

I’m trying to add a build to the channel .NET 5 Dev channel with the latest darc and I’m running into an NPE. 
darc add-build-to-channel --id 49099 --channel ".NET 5 Dev" --source-branch master
Assigning build '49099' to the following channel(s):
        .NET 5 Dev
 
Repository:    https://github.com/NuGet/NuGet.Client
Branch:        dev
Commit:        818ca73c9d788fa7afe05567d16b0e84dd88edca
Build Number:  5.7.0.6568
Date Produced: 15-Apr-20 2:46 PM
Build Link:    https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3645546
BAR Build Id:  49099
Released:      False
Channels:
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to assign build '49099' to channel '.NET 5 Dev'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.PromoteBuildAsync(Build build, List`1 targetChannels, IRemote remote) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs:line 0
   at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs:line 113

1.1.0-beta.20215.1 and 1.1.0-beta.20208.1 both failed

**Comment by riarenas** [comment]
I was able to run the command, and https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3649872&view=results is running, so I suspect some misconfiguration in darc, that we are not exposing correctly.

**Comment by riarenas** [comment]
@nkolev92 the build is now in the channel
```
darc get-build --id 49099
Repository:    https://github.com/NuGet/NuGet.Client
Branch:        dev
Commit:        818ca73c9d788fa7afe05567d16b0e84dd88edca
Build Number:  5.7.0.6568
Date Produced: 4/15/2020 2:46 PM
Build Link:    https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3645546
BAR Build Id:  49099
Released:      False
Channels:
- .NET 5 Dev
```

Could you try and run the authentication setup in https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#step-3-set-additional-pats-for-azure-devops-and-github-operations once again? this smells to me like a PAT issue (invalid, missing scopes) that we're not exposing correctly.

**Comment by riarenas** [comment]
I used the exact same command, on version `1.1.0-beta.20215.1`

@JohnTortugo you might be interested in this one.

**Comment by JohnTortugo** [comment]
@nkolev92 - Can you please try the following if you didn't change your setup yet:

- Running your add-build-to-channel again and try to assign the build to channel "general testing"
- If it fails, then create a new AzDO PAT with the Build read & execute scopes
- Run darc authenticate to set the new PAT in Darc
- Try adding the build to channel again

**Comment by nkolev92** [comment]
I have no changed my set-up:

> Running your add-build-to-channel again and try to assign the build to channel "general testing"

NPE again, same line. 

> If it fails, then create a new AzDO PAT with the Build read & execute scopes

I don't think I ever set-up an AzDO PAT. 
I only ever needed the Build Asset Registry password. 

It did work in the past though, so maybe it was more permissive.

**Comment by JohnTortugo** [comment]
Yeah, we did some changes recently and now to promote the build you need an AzDO PAT with certain permissions. If you don't need to publish the artifacts to feeds then you don't need the PAT.

Can you try after setting the AzDO PAT and please let me know?

**Comment by riarenas** [comment]
Removing the blocking checkbox. Please let us know if the PAT addition works, and we'll use this issue to track bubbling up the error in a more actionable way.

**Comment by nkolev92** [comment]
So after getting a azdo pat, it sort of completed succesfully: 

Build 49099 will be assigned to channel 'General Testing' once this build finishes publishing assets: https://devdiv.visualstudio.com/devdiv/_build/results?buildId=3650097
Waiting '60' seconds for promotion build to complete.
The promotion build finished but the build isn't associated with the channel. This is an error scenario. Please contact @dnceng.

@JohnTortugo is this what you'd expect?

Beyond that, a message instead of NPE would be nice, but I *think* I'm definitely unblocked for this build & I *think* I should be fine for future ones, is that correct?

**Comment by riarenas** [comment]
That still looks like an error scenario, both the command and the build failed. I think I'd expect that if you didn't use the `--source-branch master` parameter.

**Comment by JohnTortugo** [comment]
The pipeline used a pretty new version of Arcade branch. The problem seems to be that the DevDiv pipeline was missing the `PromoteToChannelIds` queue time variable.... I fixed it. 

@nkolev92 - can you please execute the command again?

**Comment by nkolev92** [comment]
I did use the `--source-branch master` parameter in both invocations.
Now it's saying: Build '49099' has already been assigned to 'General Testing'

**Comment by JohnTortugo** [comment]
This is fixed now. The problems were:

- The DevDiv build promotion pipeline didn't have a parameter introduced recently. I fixed that in the pipeline definition.
- The scope (existence) of the AzDO PAT wasn't sufficient to perform the command. I'll address that as part of: https://github.com/dotnet/arcade/issues/5285

**Comment by nkolev92** [comment]
Thanks for the quick turnaround @JohnTortugo, @riarenas
