### ISSUE TITLE
[darc/maestro++] We need a way to let Darc verify that the PATs in use meet requirements

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#5285]
Got some failure reports recently where users were using an AzDO PAT that didn't have all required scopes necessary to execute an Darc operation. 

It would be really good if we had an infra (in Darc) so that an operation could declare what PAT scopes are required and then a check that the PAT in use have all required scopes otherwise fail and let the user know the reason.

- A first step here would be to simply patch add-build-to-channel (which is the operation that's requiring new scopes) to check that the PAT have the scopes required.

/cc @mmitche @riarenas

**Comment by riarenas** [comment]
We have added some better error messages to add-build-to-channel which is where most of the PAT errors come from. In general we have resorted to documenting and informing about the required scopes. Writing PAT scope detection functionality to darc seems like a longer investment for minimal gains. Please reopen if you feel like there are places that still make this worthwhile.
