### ISSUE TITLE
Update Microsoft.NET.Test.Sdk to latest

### ISSUE THREAD

**Issue by RussKie** [dotnet/arcade#5291]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The current shipped version of Microsoft.NET.Test.Sdk is 16.1.1 which is almost a year old (5/30/2019).
Is there a reason not to update to a later version? The [current stable](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/) is 16.5.0, 16.6 is in beta.

I know I can request a specific version through `Versions.props` in our repo, just curious why is that we are still using an old package...

**Comment by garath** [comment]
@russkie I don't think it's set to this version for any particular reason, and will look at updating it. Is there a feature you need in the later versions?

**Comment by RussKie** [comment]
I should have linked the original issue that prompted this - https://github.com/dotnet/winforms/issues/2926
In a nutshell we needed a newer versions (16.4+) to be able to run x86 tests under VS.

**Comment by garath** [comment]
I've updated the default version as mentioned. 

I see that winforms has also specified a version, so hopefully you're unblocked. Let me know if anything looks amiss.

**Comment by garath** [comment]
Reopening as this change was rejected by a test in the validation build. We'll have to investigate what exactly broke and reevaluate updating this default. It may be noisier than we anticipated. 

See also dotnet/arcade#5673.

**Comment by nohwnd** [comment]
I tried to fine where it fails, but only found this message that would normally be a warning:

"The assembly 'content\testhost.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced."

If there are some other problems, feel free to mention me, or file an issue on vstest an I will have a look.

**Comment by riarenas** [comment]
My approach for this is going to be:

* Start with @garath's change to update the version in arcade-validation (should fail the same way it did before)
* Make the changes necessary to the test projects that fail until arcade-validation builds
* Use the arcade-validation mechanism to run builds of runtime / aspnetcore/ installer
* See what the issues that pop up are

Once we understand any other breaking changes that are revealed from this exercise, we can give some guidance on any steps that repos will need to perform once the version change makes it to them.

**Comment by riarenas** [comment]
The only problem is the warning. Supressing it fixes arcade-validation's build. 

I haven't found any other problems with updating the version. Will start running the change against other repos today:

This change has the potential to be disruptive, and will fail the build whenever the following conditions are met:

* The repo has WarnAsError turned on (our guidance is that this should be turned on)
* A test project has: `IsPackable` set to `true`
* `NU5100` isn't supressed 

The only workarounds are to either make the test project not produce a package, or to supress the NU5100 warning.

**Comment by riarenas** [comment]
This build should reveal whether there are any problems in the big repos. If there aren't I think we can just get away with making the change in Arcade and then letting repos know of the two workarounds for when this warning is shown.

**Comment by riarenas** [comment]
Some failures in the aspnetcore build. Looking into them.

**Comment by riarenas** [comment]
All the builds were able to build and package correctly after some retrying due to agent disconnections. I'm pretty comfortable that updating the version won't be a problem in these big repos, and that we can get away with just letting users know how to fix the issue if there are any failures.

**Comment by riarenas** [comment]
PRs are open: 

* Fix Arcade-validation so that it doesn't produce a warning once the new version comes in: https://github.com/dotnet/arcade-validation/pull/1629
* Re-introduce the version update in arcade: https://github.com/dotnet/arcade/pull/5756

**Comment by riarenas** [comment]
This has gone out with the latest arcade promotion.
