### ISSUE TITLE
Consolidate cross/build-rootfs.sh into 1 place

### ISSUE THREAD

**Issue by eerhardt** [dotnet/arcade#53]
In order to build arm binaries, we currently have roughly the same script copied into the following places:

https://github.com/dotnet/coreclr/blob/master/cross/build-rootfs.sh
https://github.com/dotnet/corefx/blob/master/cross/build-rootfs.sh
https://github.com/dotnet/core-setup/blob/master/cross/build-rootfs.sh

And they are all slightly out of date with each other because someone will update coreclr for a new platform or to fix a bug, and then forget to update the other duplicates.

Also, if/when ASP.NET and the SDK need to build for arm, they will need these scripts as well.

We should consolidate this infrastructure into a single place - this repo - where the things that are common across repos should live.

/cc @weshaggard @janvorli

**Comment by markwilkie** [comment]
create native build epic

**Comment by markwilkie** [comment]
It'd be good to be opportunistic here.  (not blocking though)

**Comment by deinok** [comment]
@eerhardt core-rt and source-build also use the cross folder. Just to no notice.

**Comment by deinok** [comment]
@janvorli About the cross folder.

I'm new to arcade, but I supose that what you need is a Task (https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.utilities.task?view=netframework-4.7.2) that implements all the things from the cross folder, I'm right?

**Comment by jcagme** [comment]
What repo should we use to get the file from?

**Comment by deinok** [comment]
I'm not sure but I think coreclr

**Comment by janvorli** [comment]
Yes, coreclr is the right source. But it is not just the `build-rootfs.sh`. We need to share the whole cross folder contents except of the tryrun.cmake which is repo specific.
