### ISSUE TITLE
[darc/maestro++] [post-build improv] Merge the channel YAML stages into a single stage with a packages/blobs publishing job and a job for symbol publishing.

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#5303]
Related to the plan discussed here: https://github.com/dotnet/arcade/issues/4283 

We won't have separated stages for each channel anymore.

**Comment by epananth** [comment]
https://github.com/dotnet/arcade-services/pull/1261 has been reverted need to make 'publishing-infra-version'  optional and run scenario test again.

**Comment by epananth** [comment]
I think I merged this couple of weeks ago https://github.com/dotnet/arcade-services/pull/1291
