### ISSUE TITLE
[darc/maestro++] [post-build improv] Patch arcade-validation to promote builds using Darc add-build-to-channel and move files from arcade/master to arcade/publishing branch.

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#5304]
Related to the plan discussed here: https://github.com/dotnet/arcade/issues/4283 

We'll use `darc add-build-to-channel --id xxx --source-branch master` to validate that changes merged in Arcade are good to be rolled out to arcade publishing branch.

**Comment by epananth** [comment]
closing this
