### ISSUE TITLE
[darc/maestro++] Built-in support for source-build intermediate nupkg dependencies

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#5320]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

As part of [arcade-powered source-build](https://github.com/dotnet/source-build/tree/release/3.1/Documentation/planning/arcade-powered-source-build), repos will need to download source-built outputs from upstream. The outputs are in nupkgs like `Microsoft.SourceBuild.dotnet-runtime.linux-x64`, produced by every official build.

Today, we have a few choices to get this done:
1. Add N new dependencies per repo to get this done--one per upstream repo. This not only bloats the file, but can cause mistakes if someone e.g. changes the coherency parents on the Microsoft build dependency and forgets to update the source-build dependency. That could result in a broken/different source-build product.
   * I went with this in my prototype for https://github.com/dotnet/source-build/issues/1543. Also give that thread a look for broader context.
2. Reuse an existing version prop to set up a source-build dependency. E.g. use the runtime pack version property as the version of the source-build intermediate nupkg. This requires per-repo tweaking, and obscures the dependency somewhat.
   * Might be viable. Somewhat more maintenance-heavy and potentially confusing, however given the dependency doesn't change much, I wouldn't expect high cost in the long run.
3. Run MSBuild tasks during `CollectPackageReferences` to parse `eng/Version.Details.xml` to look for a custom element marking specific dependencies. Generate `PackageReference` items based on the repo names and versions to acquire the intermediate nupkgs.
   * The end result is clean (less checked-in data than any other approach) and requires only Arcade SDK changes, not Darc changes. However, I think arcade-powered source-build should be as mainstream as possible so I want to explore options first.

And a new way that involves some Darc work:

4. Make this a first-class concept in Darc. When encountering a new element `<SourceBuildUpstream>true</SourceBuildUpstream>` under a dependency in Version.Details.xml, Darc should behave like there's another dependency on the same repo name, commit hash, and version, but with the name `Microsoft.SourceBuild.{org}-{reponame}.linux-x64`.
   * Ideally Darc would also maintain a `eng/Versions.props` itemgroup linking these to source-build infra. ([`SourceBuildCacheReference`](https://github.com/dotnet/installer/compare/616fa8a09ee5513f4c7e6d81dd8d8ec0101789e3...ee0610e005449b67683996681b7dac7d29b83ec0#diff-8b8f08ffbf7b863fb3700c1718eeb4cb) in prototype, but I think `SourceBuildIntermediatePackageReference` would be a better name.)

---

@mmitche what do you think? Is it worth it to build this into Darc, does one of the approaches stick out to you as the best?

@dseefeld @crummel I didn't think of all the approaches when we met, interested what you think too.

**Comment by dagood** [comment]
The more I think about it, the more I like (3). It doesn't help anyone to add more noise to `eng/Version.Details.xml` and `eng/Versions.props`, Darc support or not.

**Comment by mmitche** [comment]
I think 3 and 4 are both quite viable. We do have precedent for 'special' elements (e.g. the arcade sdk element ends up updating global.json)

I think the question is which of these involve less "hidden" behavior.

**Comment by dagood** [comment]
> I think the question is which of these involve less "hidden" behavior.

I think (3) is better there. The detection and new dependency happens in front of me, and can be found fairly easily in the binlog, vs. run on a server and checked into the repo.

**Comment by dagood** [comment]
Closing discussion: POR is (3).
