### ISSUE TITLE
Product validation pipeline should have the ability to do custom signing validation

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5331]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The DAC libraries have to be signed very in specific ways that have been broken frequently in the past. The dotnet/diagnostics repo has tools to do very specific sorts of verification on these files.  Since we are eventually moving signing out of the builds and into the prep stage, we need to have a place for these kinds of tools.

**Comment by jcagme** [comment]
Closing since this will be added to runtime's build. @hoyosjs @mikem8361 feel free to re-open if you think we should still have this around.

**Comment by hoyosjs** [comment]
This is orthogonal to what were talking about. It needs to be verified in the signed framework and runtime packs hopefully.

**Comment by jcagme** [comment]
We do signing validation already which should include the assets that will be signed during builds. Is there something else needed?

**Comment by hoyosjs** [comment]
The DAC's need to be signed with a windows trusted cert (usually `MicrosoftSHA2/200`, but it can be phone cert too) in order for non-full dumps to work on Windows.

**Comment by hoyosjs** [comment]
@jcagme Also noticed that there are some symbols.nupkg in the runtime. 

- The cross architecture debugging assets need to be signed in the symbol package. 
- The DAC needs to be signed 

This validation needs to happen at symbol server publishing time (otherwise things will end up unsigned and some Watson and VS scenarios will fail).

**Comment by jcagme** [comment]
By the time the staging pipeline runs all packages are symbols have been published to an internal/transit "location". This happens during build promotion to different channels. Before the staging process any sort of validation needed after publishing would need to be added to the build/promotion pipeline. If this is a release day thing (when things are published to the public) some sort of validation can be added to the publishing pipeline
