### ISSUE TITLE
Investigate Arcade failures for version 5.0.0-beta.20221.14

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5337]
Arcade Validation run: https://dnceng.visualstudio.com/internal/_build/results?buildId=612731&view=results

## Runtime

Runtime build with this version of Arcade: https://dev.azure.com/dnceng/internal/_build/results?buildId=612845&view=results 

LKG build used for this branch: https://dev.azure.com/dnceng/internal/_build/results?buildId=611275&view=results

### Issues

- ~~SourceLink Validation failure. Problem did not occur in LKG. A bunch of 404s from GitHub.~~ Based on discussion down-thread, it sounds like this is a completely normal error to see based on how we're handling the branching and running of this code (branch from GitHub, push to AzDO to run)

## ASPNETCore

ASPNETCore build with this version of Arcade: https://dev.azure.com/dnceng/internal/_build/results?buildId=612842&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc&t=39263dad-2be6-5f40-bde4-1bab0d7931b4&l=852

LKG build used for this branch: https://dev.azure.com/dnceng/internal/_build/results?buildId=612274&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc&t=39263dad-2be6-5f40-bde4-1bab0d7931b4

### Issues

- ~~Warnings are being treated as errors.~~ This was investigated and the mitigation around this is the following: By removing `treatWarningsAsErrors` from the override properties list, it’s now getting pulled in from Directory.Build.props. Avoid setting this property to true in Directory.Build.props for the impacted project, since it’s not actually able to restore without warnings.

**Comment by missymessa** [comment]
@alexperovich are the errors in Runtime's SourceLink Validation stage related to work you recently did?

**Comment by missymessa** [comment]
Currently attempting to narrow down when warnings started being treated as errors. 

Validating ASPNETCore with Arcade version 5.0.0-beta.20206.4: https://dev.azure.com/dnceng/internal/_build/results?buildId=613933&view=results

**Comment by missymessa** [comment]
SourceLink was failing on Runtime with at least version 5.0.0-beta.20216.3, maybe further back, but those builds were causing failures during the Build stage due to conflicts with Roslyn.

**Comment by safern** [comment]
It seems like the commit SourceLink is looking for doesn't even exist: https://github.com/dotnet/runtime/commits/06d808e15e7081cc2f2e6d1c9a1605f9359c9423

The commit only exists in internal validation branch: https://dev.azure.com/dnceng/internal/_git/dotnet-runtime/commit/06d808e15e7081cc2f2e6d1c9a1605f9359c9423

**Comment by missymessa** [comment]
@safern should we be concerned about this issue if we were to promote Arcade?

**Comment by safern** [comment]
The question here is why hadn't we hit this before on validations? Did we use to create a validation branch in the GH repo as well?

**Comment by missymessa** [comment]
@safern Since about the end of March, we started running Arcade validation using Runtime. The early validations builds we captured were failing at during the Build stage due to conflicts with Roslyn, so we weren't able to see the errors with SourceLink until recently. And yep, we branch in GitHub. 

@riarenas is having an epiphany that this may be completely normal.

**Comment by safern** [comment]
> And yep, we branch in GitHub.

But it seems like the commit is missing in GH. This doesn't seem like an issue with source link or source link validation. This is the default behavior I expect, you build from internal, source link takes the build commit, and maps it to github as that is the public repo. If you added this commit, on any branch in GH (matching sha) it will pass the SourceLink validation.

**Comment by riarenas** [comment]
We branch from Github, but we only push the branch to AzDO. You're right that this is normal.

**Comment by missymessa** [comment]
@safern @riarenas and I chatted about this and it sounds like this is expected based on how we're handling... okay, Ricardo commented while I was in the middle of writing this :)

**Comment by missymessa** [comment]
Warnings being treated as errors was investigated, too.  Added a comment to the issue description regarding this situation.

**Comment by missymessa** [comment]
Closing this issue. Investigations complete.
