### ISSUE TITLE
[AV] Test gaps: null check in Signing properties

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5349]
Related PR: https://github.com/dotnet/arcade/pull/5327

This would've been caught by Installer if it was hooked up to Arcade Validation, but it wasn't. It should be a part of Arcade Validation, though.

**Comment by missymessa** [comment]
Moving to Signing epic.

**Comment by mmitche** [comment]
I think this is covered now. GenerateBuildManifest appears no longer used at all, and the green path (generation of the manifest during publishing), is heavily covered for these cases (there are plenty of cases in the BuildManifestUtilTests that do not supply various signing info.

**Comment by mmitche** [comment]
GenerateBuildManifest formally removed in https://github.com/dotnet/arcade/pull/6729
