### ISSUE TITLE
NuGet.Client: help understanding CreateSatelliteAssemblies

### ISSUE THREAD

**Issue by zivkan** [dotnet/arcade#5354]
I'm investigating adding the Arcade SDK to [NuGet.Client](https://github.com/NuGet/NuGet.Client/). My branch name is [`dev-zivkan-use-arcade-sdk`](https://github.com/NuGet/NuGet.Client/tree/dev-zivkan-use-arcade-sdk). So far all I've done is followed the onboarding docs (adding the `eng\` files, `Directory.Build.[props|targets]`, etc.), and try to fix up our strong name key stuff.

When I build now, `NuGet.Common.Test` fails to build with the error: `ALINK : error AL1028: Key file 'c:\git\NuGet.Client\keys\35MSSharedLib1024.snk' is missing the private key needed for signing [C:\git\NuGet.Client\test\NuGet.Core.Tests\NuGet.Common.Test\NuGet.Common.Test.csproj]`.

Looking at the binlog, I see in my branch that the target `GenerateSatelliteAssemblies` is run, but when I compare to NuGet's `dev` branch, it does not. I haven't yet figured out why. Can someone help me investigate?

`NuGet.Client` build instructions, once you've cloned and switched branches to `dev-zivkan-use-arcade-sdk`:

```text
git clean -xdf
powershell .\configure.ps1
powershell .\build.ps1 -binlog
```

If you want to compare to NuGet's `dev` branch, I created a branch & PR to add the `-binlog` switch to our `build.ps1` script. If my PR hasn't been merged when you try, checkout `dev-zivkan-add-binlog-to-buildps1` instead of `dev`.

Since Arcade SDK redirects the `obj/` folder, it's necessary to `git clean` when switching from the `dev` branch to my Arcade branch.

In case it's not clear because of the large amount of text above, I'm trying to understand why `GenerateSatelliteAssemblies` is causing `NuGet.Common.Tests` to fail building when the Arcade SDK is used, but that target doesn't even run in NuGet's `dev` branch.

**Comment by markwilkie** [comment]
> In case it's not clear because of the large amount of text above, I'm trying to understand why GenerateSatelliteAssemblies is causing NuGet.Common.Tests to fail building when the Arcade SDK is used, but that target doesn't even run in NuGet's dev branch.

@alexperovich - any chance you could help out?

cc/ @tmat as an FYI

**Comment by zivkan** [comment]
I think I was chasing a red herring. Taking another look this morning, I see that the error was actually coming from the project `NuGet.PackageManagement.VisualStudio`, which appears to be a transitive project reference from `NuGet.Common.Tests` (probably though our test helper utilities project)

`NuGet.PackageManagement.VisualStudio` failed to compile, so I guess when the test projects were being compiled, MSBuild tried to run `GenerateSatelliteAssemblies` because it wasn't "up to date" due to failing.

Arcade SDK is causing `NuGet.PackageManagement.VisualStudio` to have a very, very different set of assemblies being passed to csc.exe, so several types used by the project cannot be found.

**Comment by alexperovich** [comment]
This appears to just be a normal build error. Unless there is something incorrect about what arcade is changing?

**Comment by zivkan** [comment]
Perhaps we should close this issue until I have more time to investigate (I'm working on it as a side issue, not a main deliverable).

While "can't find type" is a "normal" build error, it doesn't happen in NuGet's dev branch. If you compare my arcade branch to the dev branch, I didn't add or remove any PackageReferences, or change the versions we try to use, which means that by simply using the Arcade SDK, it has changed our dependency graph in ways that I personally did not expect.

I haven't yet had time to look into what versions have changed, what assembly the missing types normally come from, and why they're no longer in the dependency graph. Yesterday I was focusing on strong name issues, and I missed that one of the strong name errors comes from a project which failed to build.

**Comment by alexperovich** [comment]
To my knowledge arcade doesn't do any removing of references. It only adds references in some cases. If it is actually removing needed references then that is definitely a bug.

**Comment by zivkan** [comment]
Closing as I need to do more investigation.
