### ISSUE TITLE
Implement notifications for Validate-DotNet

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#5363]
- [x] Add functionality to BuildMonitor so that it can Validate-DotNet for repos and assign issues based on tags
- [x] Update Validate-DotNet pipeline tags to separate repo and channel, and possibly not add tags for internal builds
- [x] Enable dotnet-status-eng on product repos (starting with runtime, aspnetcore, installer, then moving on to others)
- [ ] Add repos to appsettings.json for BuildMonitor to monitor them

**Comment by adiaaida** [comment]
| Repo | Infrastructure Tags | Bot Enabled | Monitor added | Rolled out |
| ---- | ------------------- | ----------- | ------------- | ---------- |
| runtime | area-Infrastructure | | | |
| aspnetcore | area-Infrastructure | | | |
| windowsdesktop | | | | |
| sdk | Area-Infrastructure | | | |
| installer | Area-Infrastructure | | | |
| aspnetcore-tooling | open in aspnetcore | open in aspnetcore | | |
| winforms | area: infra | | | |
| wpf | area-infrastructure | | | |
| efcore | area-infrastructure | | | |
| ef6 | area-infrastructure | | | |
| reverse-proxy | Type: Infrastructure | | | |
| iot | area-infrastructure | | | |

**Comment by adiaaida** [comment]
This has been implemented for installer, sdk, runtime and aspnetcore. Closing.
