### ISSUE TITLE
[QCR] [Staging Ring] Create cli command for aggregating the staging ring manifests

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#5368]
Each staging ring job that creates something will generate a manifest. Once all of the jobs in the staging ring are done, we will collate their manifests into one uber manifest.

**Comment by markwilkie** [comment]
This makes sense.  I'm curious though, what are some examples of artifacts we'd want to move along the different rings?

**Comment by adiaaida** [comment]
For example, the Antares zip that we will be generating.
