### ISSUE TITLE
Make SDL Validation works on Promotion Pipeline

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#5372]
The SDL validation step inspect the source code of the running build. The current code uses AzDO checkout task to download the sources, that doesn't work when we execute the validation in the scope of the build promotion pipeline because the current build isn't what should be validated.

We need to patch the SDL scripts to be able to validate a repo given an specific SHA.

**Comment by markwilkie** [comment]
Pretty sure @jcagme got this working already?

**Comment by jcagme** [comment]
Yeah this works. I check out the source of `dotnet-release` repo which has a tool that knows how to clone a repo and checkout a commit using Okto. If you need something in the likes, let me know.

**Comment by JohnTortugo** [comment]
That's great. Thank you folks.

**Comment by JohnTortugo** [comment]
After internal talks it turned out that this isn't necessary in the Promotion Pipeline. Validations will be performed as part of the release process.
