### ISSUE TITLE
BARViz should show a couple extra things:

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5374]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

It would be incredibly helpful if BARViz showed:
- [x] The BAR id of the build you're currently looking at (this is particuarly useful for sending builds through the release pipeline. Copy button would be extra helfpul (no api changes needed)
- [ ] Whether a dependency update PR is open for the current repo + channel you're looking at, meaning at: Is there a subscription PR opened such that if merged and succesfully built, would result in a new build. (api changes needed)
- [x] Add a copy button for the sha. (no api changes needed)
- [ ] Show the top line commit message of the build commit. (api changes needed)

**Comment by mmitche** [comment]
Reordered for priority.

**Comment by lwintjen** [comment]
I've started working on this issue ([PR available](https://github.com/dotnet/arcade-services/pull/1397)).

I've implemented the copy button for the sha :
![image](https://user-images.githubusercontent.com/43049559/92243793-54ae5a00-eec2-11ea-84fb-95037bbd2cf3.png)

We won't enrich existing Build API but instead create a new API to get 
  1. commit message
  2. existing PR status

I'll focus on changes that don't require API changes (such as just copy button)

**Comment by lwintjen** [comment]
I'm closing this issue and splitting it into 2 different ones (one more complex that requests some changes in the API and one that doesn't).

1. [Require API changes](https://github.com/dotnet/arcade/issues/6138)
2. [Doesn't require API Changes](https://github.com/dotnet/arcade/issues/6137)
