### ISSUE TITLE
[AV] Auto create GitHub issue to track investigation of failures

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5378]
To better track our investigations and streamline the process, every time Arcade Validation fails (on master branch only), we should auto create a GitHub issue (in the Arcade repo) to track investigation findings. Should include the appropriate build links for the downstream product repos and the result of those builds and the version of Arcade being validated.

**Comment by markwilkie** [comment]
@ChadNedzlek to perhaps hook up the magic fire hose

**Comment by missymessa** [comment]
> @ChadNedzlek to perhaps hook up the magic fire hose

Yep, we've been discussing this :)

**Comment by missymessa** [comment]
Need to configure appsettings.json similarly: https://github.com/dotnet/arcade-services/pull/1136/files

**Comment by ChadNedzlek** [comment]
Of note, the thing currently opens them in core-eng.  At the moment, there is only one big config switch for which repository it sends items too. If it's important they go to arcade, we'll have to make it more flexible.

**Comment by missymessa** [comment]
RIP my inbox.

**Comment by missymessa** [comment]
Can't validate until this is rolled out. Putting in the rollout column and I'll verify once it's completed.

**Comment by missymessa** [comment]
Well, it works: https://github.com/dotnet/core-eng/issues/9765#event-3310929028

**Comment by markwilkie** [comment]
sweet
