### ISSUE TITLE
Wrong path to NuGet.targets

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/arcade#5379]
I noticed something weird in `microsoft.dotnet.arcade.sdk\1.0.0-beta.20215.5\tools\Build.proj`:

https://github.com/dotnet/arcade/blob/62fc25d3be470d58e4b88625520f0be39c0f124d/src/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj#L86-L87

NuGetRestoreTargets is set to:
```
      <_NuGetRestoreTargets>$(MSBuildToolsPath)\NuGet.targets</_NuGetRestoreTargets>
      <_NuGetRestoreTargets Condition="'$([MSBuild]::IsRunningFromVisualStudio())' == 'true'">$(MSBuildToolsPath32)\..\..\..\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets</_NuGetRestoreTargets>
```

As far as I can tell, the `MSBuildToolsPath` is always:
`MSBuildToolsPath = C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin`

In regular builds it is set like this in `Microsoft.Common.CurrentVersion.targets`:

```
    <NuGetRestoreTargets Condition="'$(NuGetRestoreTargets)'=='' and '$([MSBuild]::IsRunningFromVisualStudio())'=='true'">$(MSBuildToolsPath32)\..\..\..\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets</NuGetRestoreTargets>
    <NuGetRestoreTargets Condition="'$(NuGetRestoreTargets)'==''">$(MSBuildToolsPath)\NuGet.targets</NuGetRestoreTargets>
```

Basically NuGet.targets is never in the same directory as MSBuild.exe as far as I can tell, so Arcade sets it to the wrong location. I don't know why it's currently setting it to `$(MSBuildToolsPath)\NuGet.targets` but it should probably just remove this line and always set it to `$(MSBuildToolsPath32)\..\..\..\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets`?

My repro: I was building Roslyn.sln with a path set to custom MSBuild: 

1. git clone https://github.com/dotnet/roslyn
2. restore
3. In a regular command prompt (with fresh environment):
```
    set PATH=C:\roslyn\.dotnet;C:\msbuild\artifacts\bin\bootstrap\net472\MSBuild\Current\Bin;%PATH%
```

and it failed with:
import not found C:\msbuild\artifacts\bin\bootstrap\net472\MSBuild\Current\Bin\NuGet.targets

However I have to say that the failure is not deterministic so I was unable to reproduce since. Just wondering how it works though.

**Comment by KirillOsenkov** [comment]
Ah, the Sdk folder contains NuGet.targets, interesting. So depending on the order in which I set the environment variables, it will or will not work.

E.g. if I first set the path to MSBuild and then Dotnet, it won't work. But if I first set the path to Dotnet, then to MSBuild, then it works? Basically the order of PATH matters.

Roslyn happens to rely on both a custom SDK and I was building it with custom MSBuild. If both are custom, then you have to be careful about which order you set the environment variables in.

**Comment by KirillOsenkov** [comment]
`C:\roslyn\.dotnet\sdk\3.1.200\nuget.targets`
`C:\msbuild\artifacts\bin\bootstrap\net472\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets`

Should probably add a `Condition='Exists(...)'`

**Comment by garath** [comment]
Triage: This seems like something better fixed in the repo. But, if you disagree, reopen and we can discuss further.

**Comment by KirillOsenkov** [comment]
Apologies for reactivating but I'm pretty sure that we need to add conditions for file existence in the link I provided above:
https://github.com/dotnet/arcade/blob/62fc25d3be470d58e4b88625520f0be39c0f124d/src/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj#L86-L87

Need to add `Condition="Exists('<the file you're setting it to>')"`

It is really misleading to be setting a variable to point to a file that doesn't exist. Both lines 86 and 87 need an Exists check.

The point of Arcade is to take care of all these minutiae so that the repo authors don't have to worry about it.

Thanks~

**Comment by MattGal** [comment]
https://github.com/dotnet/arcade/pull/5753

**Comment by MattGal** [comment]
Commits merged to master and release/3.x, closing.
