### ISSUE TITLE
Remove eng\common\tools.ps1's dependence on myget.org

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#5385]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

See https://github.com/dotnet/arcade/blob/master/eng/common/tools.ps1#L356-L374 .  We want to remove all dependence on myget; I'd suggest for maximum compatibility we just put all versions of this package on either blob storage or our dotnet-eng / dotnet-tools AzDO package feeds.

For maximum correctness we should just make a zip of the latest stable .NET Core Msbuild, put it on netcorenativeassets, and simply download with lots of good retry code from there in this function.

@garath  if this is a dupe please accept my apologies and close it.

**Comment by tmat** [comment]
@jaredpar FYI

The packages should definitely not go to `dotnet-tools` feed as that's for official, shipping tools. `dotnet-eng` would work.

> For maximum correctness we should just make a zip of the latest stable .NET Core Msbuild

I'm not sure what you mean. I don't think we want to use .NET Core msbuild for this package. This is specifically used for building with .NET Framework msbuild tooling.

**Comment by MattGal** [comment]
> I'm not sure what you mean. I don't think we want to use .NET Core msbuild for this package. This is specifically used for building with .NET Framework msbuild tooling.

My mistake, I should have said "make a zip of the latest stable desktop msbuild" then.   Either way since it's in eng\common we should agree on some myget-departing solution; you're welcome to suggest the best way.

**Comment by tmat** [comment]
BTW, long term I'm trying to work with VS Extensibility team to port VSSDK build targets to .NET Core, so we can actually build completely with `dotnet build` and remove this dependency. It will take a while though.

**Comment by tmat** [comment]
@MattGal Adding the packages to `dotnet-eng` would be reasonable.

**Comment by MattGal** [comment]
Do you know which all we'd need ?  Would be pretty easy to push them there real quick.

**Comment by garath** [comment]
@dibarbet, in your work to clean-up the Roslyn MyGet feeds, did you also move publishing of [RoslynTools.MSBuild](https://dotnet.myget.org/feed/roslyn-tools/package/nuget/RoslynTools.MSBuild)? If so, where?

**Comment by dibarbet** [comment]
> @dibarbet, in your work to clean-up the Roslyn MyGet feeds, did you also move publishing of [RoslynTools.MSBuild](https://dotnet.myget.org/feed/roslyn-tools/package/nuget/RoslynTools.MSBuild)? If so, where?

No - for Roslyn restore, there are still a few packages that we need to move off of roslyn-tools, tracked here - https://github.com/dotnet/roslyn/issues/45573 .  However we don't use RoslynTools.MSBuild for Roslyn restore, so it's not tracked in that issue, focusing on getting Roslyn off first.  https://github.com/dotnet/roslyn-tools/issues/793 tracks the rest of the packages on roslyn-tools

It sounds like dotnet-eng is the right feed for this one.
@jaredpar is RoslynTools.MSBuild also manually published?  If so going forward would it be reasonable to publish to the dotnet-eng feed?

**Comment by jaredpar** [comment]
> is  RoslynTools.MSBuild also manually published? If so going forward would it be reasonable to publish to the dotnet-eng feed?

Yes it's manually published. Completely reasonable to use a different feed. Just need to know where to publish it.

**Comment by dougbu** [comment]
@jaredpar I think the votes above were all for https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json 😺

**Comment by jaredpar** [comment]
@dougbu 

How do I use that feed though? I can't find the place where there is a UI for me to upload a package.

**Comment by dougbu** [comment]
@jaredpar I dunno but hope @MattGal does

**Comment by garath** [comment]
The Azure UI for that feed is [here](https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=dotnet-eng). 

I can take care of pushing the versions that exist on MyGet, if that helps.

**Comment by MattGal** [comment]
Sounds like @garath  is on top of it, but happy to help if needed.
