### ISSUE TITLE
Report failure to create darc PR

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#5386]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

When Darc fails to create a dependency PR there is no error. And we can only tell by realize a branch is behind when we want to insert it. By this time it is too late. We need some way to report failure of automated PR.

**Comment by wli3** [comment]
@wtgodbe

**Comment by wtgodbe** [comment]
@mmitche I thought we had an issue tracking this already, but I can't seem to find it in my mentions, am I misremembering?

**Comment by JohnTortugo** [comment]
@epananth - Is this related to what you were working on the past weeks?

**Comment by epananth** [comment]
Yes but the feature is not turned on in Prod yet. It will be turned on next week.

**Comment by epananth** [comment]
This  feature was turned ON 2 weeks ago. So closing this issue.

**Comment by wtgodbe** [comment]
@epananth Do the issues get created in the repo where the PR should've been created? Who gets tagged?

**Comment by epananth** [comment]
It gets created in core-eng repo and I get tagged to the issues. So if it is an infrastructure error, we will take care of it else we will assign it to repo owners.
