### ISSUE TITLE
[QCR][Pipeline] Allow partial dev runs

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#5389]
After some talks it looks like having a single up-until-the-end single run for SDL, and maybe some other things that are still not included, might be risky and cause time to fix issues to be tight.

We need to allow product repos to run a portion of the release pipeline, mainly `prep`, `validation` and `source validation` stages, on a defined cadence (nightly, once a week, etc.) so repo owners know what's wrong before a release.

At the same time the "full" release pipeline should not change.

The easiest way to do this is introducing a new "type" input variable which will mandate whether the run is a "dev" or a "release" run. This flag will determine what stages run.

**Comment by wtgodbe** [comment]
👀

**Comment by Pilchie** [comment]
:eyes:

**Comment by JohnTortugo** [comment]
👀

**Comment by sunandabalu** [comment]
I like this plan of allowing product repos to have "dev" SDL runs. 👍
