### ISSUE TITLE
[darc/maestro++] [post-build improv] Handling of errors in promotion pipeline

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#5390]
How should the errors in the build promotion pipeline(s) be tracked & reported to the user?

My initial idea was to create a GitHub issue on the repository of origin of the promoting build whenever the promotion finished. For that we would probably need to patch the promotion pipeline to add a task that execute whenever an error happens and then call some service (or maybe the GH API) to create the issue.

Another option maybe to use the infra that @ChadNedzlek created recently to monitor build failures. Also, looks like the release pipeline folks have implemented something similar, so it's worth checking.

/cc @epananth @jcagme

**Comment by riarenas** [comment]
Any additional details you want to add here @JohnTortugo

**Comment by JohnTortugo** [comment]
@riarenas - I updated the issue description.

**Comment by missymessa** [comment]
@riarenas @epananth The associated epic for this issue was closed. Do you know if there's still need for this issue?

**Comment by epananth** [comment]
we have build monitor to track build errors in maestro promotion pipeline. I think we can close this
