### ISSUE TITLE
Cannot create build drop locally

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#5397]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

I try to create a drop for https://dnceng.visualstudio.com/internal/_build/results?buildId=629128&view=logs&j=d17d50ef-afac-5d4b-95a6-3014ce5cf7a4&t=95fe4740-169e-5ca1-2f88-330db40deac4

`darc gather-drop  --id '50791' --output-dir <output-dir> --non-shipping --full --skip-existing --continue-on-error`. I put  _--continue-on-error_ already

```
warn: Microsoft.DotNet.Darc.Operations.Operation[0]
      https://github.com/dotnet/corefx@7ee84596d92e178bce54c986df31ccc52479e772  does not have an eng/Version.Details.xml.
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Something failed while trying the fetch the dependencies of repo 'https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int' at sha '553cd6e92b14ca8a950b86aa7690c1d0d7ad106f'
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 80
 
```

**Comment by JohnTortugo** [comment]
Given the error messages, which clearly should be improved, I think this might just be a matter of an expired PAT?

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
```

I tried the command locally we Darc version `1.1.0-beta.20222.1+921959e3d838829de198ec5f5fe2e4771521fd4c` and it worked fine for me. 

Can you please try a new PAT?

**Comment by mmitche** [comment]
Right, you need, set via `darc authenticate`
- azdo pat
- github pat
- maestro pat

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#setting-up-your-darc-client

**Comment by JohnTortugo** [comment]
Talked offline, there was no bug. It was just an issue of setting the PAT>
