### ISSUE TITLE
Customise eng\common\build.ps1

### ISSUE THREAD

**Issue by RussKie** [dotnet/arcade#5398]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

In Windows Forms we are struggling with stability of our tests, and we added a screenshot-capturing service to our build (https://github.com/dotnet/winforms/pull/3056). 
However it appears build.ps1 file is overwritten by ingestion of new arcade builds (e.g. https://github.com/dotnet/winforms/pull/3134/files#diff-b76a3f23fd33241b618730c7f6b05b92).

Could you please provide guidance how to have our build modified in a way that coexist with the arcade.

**Comment by markwilkie** [comment]
@alexperovich and/or @MattGal can probably help with how to do custom logic in your build.  Basically, everything under eng/common is "owned" by arcade, but you can do what you need under /eng.  There's some docs here https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md if that helps too.

**Comment by tmat** [comment]
This: https://github.com/dotnet/arcade/pull/5469 would hopefully help to clarify the intent.

**Comment by RussKie** [comment]
I'll have a read thank you

**Comment by garath** [comment]
Looks like this is satisfied? If not, please reopen.

**Comment by RussKie** [comment]
If anyone is curious, I've implemented it in https://github.com/dotnet/winforms/pull/3544

**Comment by markwilkie** [comment]
Thanks @RussKie !
