### ISSUE TITLE
Make Tasks.Feed use the forked version of Sleetlib

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#540]
Recently @jcagme patched the latest version of Sleetlib to use Newtonsoft.Json 9.0.1. Now we need to make Tasks.Feed use it.

**Comment by jcagme** [comment]
Hmmm it already does. I don’t recall if this change was already merged to master or in my fork but this is done. 

What’s the context around this issue?

**Comment by JohnTortugo** [comment]
I was trying to validate some changes I did on the PushToBlob class and got an error on related to Sleetlib+Newtonsoft.JSON. Checking the .csproj for Tasks.Feed I see that we are still using the original version of it: 

https://github.com/dotnet/arcade/blob/e1172d9b1353cbbed890b80d42ed0d07980389ae/src/Microsoft.DotNet.Build.Tasks.Feed/Microsoft.DotNet.Build.Tasks.Feed.csproj#L16

Did you publish the package with your version of Sleetlib ?
