### ISSUE TITLE
Assembly dll is NOT signed properly && Container .nupkg does not have signature marker.

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/arcade#5418]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Hey Arcade
I got those error messages (in title) when I launch a build using CIBuild, after some investigation I find out it's because the `OfficialBuild` is set to true because of I set up `OfficialBuildId`, but I don't know what're those error msg means and how can I fix that. I use default sign configuration for my project right now.

Another question is how to config arcade to use my  own sign key to sign dll/nuget, right now it all defaults to MSShareLib1024.snk and I can't change it using Visual Studio, (After I replace snk file in VS and save and reopen, the snk file will switch back to default MSSharLib1024.snk).

I spend about 3 hours on this issue, I don't know if that can be `unreasonable` pain but that definitely no a happy journey. So please help me, Thanks!

**Comment by JohnTortugo** [comment]
@LittleLittleCloud can you point me to your build definition and a failing build?

**Comment by LittleLittleCloud** [comment]
a fail build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3701763&view=results

Build definition: https://github.com/LittleLittleCloud/machinelearning-auto-pipeline/blob/master/ci.yaml

**Comment by LittleLittleCloud** [comment]
Hello, any updates?

**Comment by riarenas** [comment]
I'd like to echo @JohnTortugo's question. Was this previously working and started failing recently?

If you're just onboarding to signing, I wonder if it's related to your build not installing the microbuild signing plugin?

The arcade templates do this automatically for you with the use of a single parameterhttps://github.com/dotnet/arcade/blob/9f3ff5b755c3a0ecd4627731aa1015aab4eac15b/Documentation/AzureDevOps/TemplateSchema.md and I'd recommend moving to them.

If using the templates is not an option, then you'll need to add the task, similar to how our templates do it https://github.com/dotnet/arcade/blob/eead20d5a6a17bdf591efb3f8117c7af4079c668/eng/common/templates/job/job.yml#L103-L108

**Comment by LittleLittleCloud** [comment]
> I'd like to echo @JohnTortugo's question. Was this previously working and started failing recently?
> 
> If you're just onboarding to signing, I wonder if it's related to your build not installing the microbuild signing plugin?
> 
> The arcade templates do this automatically for you with the use of a single parameterhttps://github.com/dotnet/arcade/blob/9f3ff5b755c3a0ecd4627731aa1015aab4eac15b/Documentation/AzureDevOps/TemplateSchema.md and I'd recommend moving to them.
> 
> If using the templates is not an option, then you'll need to add the task, similar to how our templates do it
> 
> https://github.com/dotnet/arcade/blob/eead20d5a6a17bdf591efb3f8117c7af4079c668/eng/common/templates/job/job.yml#L103-L108

Right, I didn't install microbuild signing plugin in my pipeline, the previous runs are success because it's not signed build. 

So do I need to install MicroBuild plugin to sign my build? What's MicroBuild do, and is that a internal tool or it's available for all developers.

**Comment by JohnTortugo** [comment]
@LittleLittleCloud - Looks like your build definition isn't even authorized to sign files. Here are some guidelines to how request the authorization: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/652/Build-Definition-Approval

**Comment by JohnTortugo** [comment]
> Right, I didn't install microbuild signing plugin in my pipeline, the previous runs are success because it's not signed build.

In the link that I just posted there are some documents about what's Microbuild, how to use it, etc.

**Comment by LittleLittleCloud** [comment]
@JohnTortugo 
Oh Just find out I create my pipeline under devdiv,, which is a mistake. It's a personal project so right now I can't and I also don't want to request authorization from devdiv. I just migrated building pipeline to another project other than devdiv.

Here's the latest run for that pipeline, which is not signed and success (the error log will be the same if I enable sign)
https://dev.azure.com/xiaoyuz0315/BigMiao/_build/results?buildId=5&view=logs&j=37bec900-c686-5858-5c69-ce96aeb4a5fe

So can I still use microbuild to sign my build even it's not under devdiv? And do I still need to request authorization after I move it out of devdiv?

**Comment by JohnTortugo** [comment]
> So can I still use microbuild to sign my build even it's not under devdiv? And do I still need to request authorization after I move it out of devdiv?

Yes, you need the Microbuild plugin even if you aren't on DevDiv. It's independent of the org. Same answer for the authorization request. The authorization is per build-definition, not org or project.

**Comment by garath** [comment]
@littlelittlecloud Looks like this is resolved. If not, please reopen.
