### ISSUE TITLE
DotNetFinalVersionKind=release does not remove prelease tag

### ISSUE THREAD

**Issue by imback82** [dotnet/arcade#5432]
- [ x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

I set DotNetFinalVersionKind=release, but the published artifacts still contain `prerelease` tags. This is the link to the build: https://dev.azure.com/dnceng/internal/_build/results?buildId=634475&view=results.

**Comment by riarenas** [comment]
@imback82 Could you point us where in your repo you are setting the property?

**Comment by imback82** [comment]
@riarenas I set the variable when I ran the pipeline.

**Comment by riarenas** [comment]
I'm not sure it's supposed to work as a queue time variable, but rather an msbuild property that you specify. Getting a binlog of your build would help to diagnose.

**Comment by imback82** [comment]
This was working fine as a queue time variable. But we recently moved `dotnet/arcade` to `release/3.x`. I guess something changed?

**Comment by riarenas** [comment]
If you can confirm that this happened after moving from a master version of arcade to a release/3.x version, it's quite possible that there's functionality around that area that we added to master but not to the servicing branch.

Uploading the binlog for your build would definitely be the best way to diagnose which properties are getting set where and when.

**Comment by imback82** [comment]
Is the binlog from a local run would also help or do you need the one from the pipeline run?

**Comment by riarenas** [comment]
The one from the pipeline will have all the properties that you're setting for the real build, which would make it more accurate.

It's a good idea overall to upload the binlogs as part of your pipeline. The Arcade templates provide functionality for enabling this, but if you're not using the build templates provided by arcade, you can use the PublishBuildArtifacts task and upload what is in your logs directory.

**Comment by imback82** [comment]
Thanks @riarenas  for the explanation. Here is the binlog from the pipeline: https://dev.azure.com/dnceng/internal/_build/results?buildId=635132&view=artifacts&type=publishedArtifacts (under Microsoft.Spark.Binaries/BuildArtifacts/artifacts/log/Release).

**Comment by imback82** [comment]
Let me rerun it with a queue variable in the pipeline. Please ignore the previous comment. Sorry about that.

**Comment by imback82** [comment]
@riarenas Here is the binlog from the pipeline: https://dev.azure.com/dnceng/internal/_build/results?buildId=635160&view=artifacts&type=publishedArtifacts (under Microsoft.Spark.Binaries/BuildArtifacts/artifacts/log/Release). I set `DotNetFinalVersionKind=release` as a queue variable.

**Comment by JohnTortugo** [comment]
I think the problem might be related to setting IsShipping/Package to 'true':

![shipping](https://user-images.githubusercontent.com/2249648/81330190-96361200-9054-11ea-8fc0-1b794e006a4b.png)

There was some changes in the more recent 3.x SDK. Can you update to the newest 3.x SDK and try again?

**Comment by riarenas** [comment]
@imback82 I think I validated that this is a bug in the version of Arcade you updated to. It's an old version from 9/9/19, and there have been fixes since then.

I created https://github.com/dotnet/spark/pull/512 for this since I had already done the changes in order to validate that this was the issue.

**Comment by imback82** [comment]
Thank you @riarenas!
