### ISSUE TITLE
[darc/maestro++] update-dependencies doesn't update the .net sdk properly

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5433]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

It appears the global.json's sdk node does not get updated by update-dependencies (works fine in normal subscription flow)

**Comment by riarenas** [comment]
Reopening, this wasn't rolled out and the current change is getting reverted https://github.com/dotnet/arcade-services/pull/1162

**Comment by markwilkie** [comment]
Curious what happened here?

**Comment by riarenas** [comment]
The PR introduced a test that was causing failures in a subsequent job because it seems the "install .net core task" in azdo scans every file called global.json from the repo.

https://github.com/dotnet/core-eng/issues/9776#issuecomment-625836167 has some more details.

**Comment by riarenas** [comment]
I'm working on the test changes needed to reintroduce this, as we really want this change to rolloutt his week.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade-services/pull/1164 re-introduces the change and fixes the test issue

**Comment by riarenas** [comment]
Build was successful after re-introducing the changes with the test fixes: https://dev.azure.com/dnceng/internal/_build/results?buildId=639967&view=results
