### ISSUE TITLE
Make azdo to github sourcelink translation optional

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/arcade#5446]
https://github.com/dotnet/arcade/blob/8078d8f3f77b7e8b7f6e289cf82cfdfa9c7a9355/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryInfo.targets#L46

Most repos want AzDO -> GitHub translations to ensure the mirrored repositories'official builds have PDBs pointing to the public location. However, we have some components that are internal in nature and the PDBs should still point to the internal implementation (for example, the symbol uploader). It should be possible to opt out of such scm URI translation. This is producing errors in validation and PDBs with incorrect information currently.

I can see two easy options:
- Condition the translation target on a property. This is probably the easiest to implement.
- Respect the original repository URL if set (sourcelink already does this)

cc: @mikem8361, @tmat

**Comment by garath** [comment]
Triage: @tmat your thoughts?

**Comment by hoyosjs** [comment]
I talked to @tmat about it. He agreed that PDBs should have the possibility of preserving the information for internal tools.

**Comment by MattGal** [comment]
Stood up a PR that does option 1.

**Comment by MattGal** [comment]
PR adding the property is merged, closing.
