### ISSUE TITLE
[darc/maestro++] Publish to BAR should fail on duplicated assets

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5450]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Publish to BAR should fail if there are multiple assets in input the manifests that have the same type (package vs. blob) and name.

**Comment by MattGal** [comment]
PR merged, moving to rollout.

**Comment by MattGal** [comment]
This was rolled out last Weds, closing
