### ISSUE TITLE
[Darc/Maestro++] Investigate whether PAT params to darc are being handled correctly

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5454]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Some darc commands don't seem to be respecting the `azdev-pat` and `github-pat` parameters if you have cached PATs from running `darc authenticate`, as it seems to use whatever is cached instead of whatever is passed to the command directly.

We should check the parameter handling in commands, and always use the PATs passed in directly if available.

**Comment by riarenas** [comment]
From #5463

>This causes a lot of chaos when running test cases locally, which may require PATs other than the ones set by the user (or if the user's are expired).

running the scenario tests locally is probably the most painful scenario where this pops up, and we haven't seen it a lot before because:

* Using darc in a build machine usually involves only using a PAT, no `darc authenticate` at all
* In normal developer scenarios, you'll only bother to `darc authenticate` and not need a PAT param.

**Comment by mattleibow** [comment]
I just got this now with the `add-subscription`. It works when i authenticate first, otherwise I get:

```
failWarning: Could not locate repository 'https://dev.azure.com/XXX/XXX/_git/XX'. Dependency updates may not happen as expected.
: Microsoft.DotNet.Darc.Operations.Operation[0]
      Non-continuable HTTP 401 error encountered while making request against URI '_apis/git/repositories/XXX'
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 100
```

**Comment by riarenas** [comment]
Ooh, that makes sense. You had a cached token for your dotnet org maestro darc usage, but now that you tried to use darc for the project reunion instance, you hit this corner case. 

I'm going to send this back to triage. I think you're the first person to hit this outside of core-eng development work, and it might make it fit the bar for getting solved through First responders since it could be pretty annoying for dotnet/maui devs that will have to live with both maestros.

**Comment by markwilkie** [comment]
We chatted about this in triage and sadly we need to close due to it's hard to justify given the business priority for our team.  HOWEVER, implementing multiple configs for darc seems like a pretty self-contained feature and we'd of course be more than happy to review PRs and/or help with direction.
