### ISSUE TITLE
Build not reporting failure on signing failure

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#546]
This build failed because of a lack of certs on a machine, but either the signtool did not report failure, or the build simply ignored it.

https://dotnet.visualstudio.com/internal/_build/results?buildId=15729&view=logs

**Comment by JohnTortugo** [comment]
For "Windows_NT Build_Release" I didn't see a Round 1 for signing, that sounds fishy and might be due the certificate issue. I'm checking if the SignToolTask reported an error.

**Comment by JohnTortugo** [comment]
Yeah, I see the cert not found error, but the SignToolTask failed to recognize it. I am fixing it. @tmat

**Comment by markwilkie** [comment]
Thanks @JohnTortugo.  @ilyas1974, any chance in fixing the machines?
