### ISSUE TITLE
[QCR] [Validation Ring] Add parallelism to symbols validation

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#5460]
Currently, symbols validation takes just over 5hrs, and is the longest pole on the release pipeline. We should work on strategies to parallelize this job so that we can reduce the time the release pipeline takes.

Questions that need to be answered:

* What is the best way to break up the run?
* How to we manage packages that have a larger number of symbols to validate vs smaller packages?
* How do we aggregate the results at the end and say symbols validation passed or failed.

**Comment by markwilkie** [comment]
wow - 5 hours is a lot and stuff.

**Comment by JohnTortugo** [comment]
@adiaaida - SourceLink validation is done in multi levels of parallelism. We perhaps can do a similar thing for symbol validation.

**Comment by adiaaida** [comment]
I'll look into that. I know that the pipeline errors get swallowed in that script (ie, they don't pop red, so they're hard to find), but maybe I can work something out for that.

**Comment by JohnTortugo** [comment]
@adiaaida - I wrote the script, let me know if I can answer any question.

**Comment by adiaaida** [comment]
After talking with Cesar, I'm going to try to add the parallelism via the powershell script, and add possibly look into caching results, if possible.
