### ISSUE TITLE
Darc doesn't use command line PAT if darc authentication file exists

### ISSUE THREAD

**Issue by meganaquinn** [dotnet/arcade#5463]
Darc doesn't respect PATS passed in as parameters if there is a darc authentication file present on the machine. This causes a lot of chaos when running test cases locally, which may require PATs other than the ones set by the user (or if the user's are expired).

**Comment by riarenas** [comment]
Closing as dupe of https://github.com/dotnet/arcade/issues/5454. I added your comment to that one.
