### ISSUE TITLE
aka.ms links should point to the CDN where possible

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5467]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The dotnetcli storage account is in a single datacenter in the US and thus download times can be painful elsewhere. The CDN helps with this, but the aka.ms links today point to the blob storage account. When generating links, we should point them to the CDN.

Basically:
- If the storage account we are publishing to is dotnetcli.blob.core,windows.net
  Replace the url prefix (up to the container) with https://dotnetcli.azureedge.net

This could be done in two ways:
- In the publisher code, if you see X when generating aka.ms links, point to Y
- Take additional inputs into the publisher code (e.g. SetupTargetFeeds.proj) that indicates that X should point to Y when generating aka.ms links.

**Comment by JohnTortugo** [comment]
I'll take care of this as part of the post-build improv: https://github.com/dotnet/arcade/issues/5301
