### ISSUE TITLE
darc update-dependencies should update .config/dotnet-tools.json

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#5481]
- [ ] This issue is blocking
- [ ] This issue is causing unreasonable pain

`darc update-dependencies` should update ".config/dotnet-tools.json".

`dotnet new tool-manifest` creates a nice way to manage tools for a respository, but has version numbers in it, similar to global.json.  `darc update-dependnecies` should update these versions so we have a good way to share tools between repositories in a standard way.

**Comment by garath** [comment]
Duplicate of dotnet/arcade#5315

**Comment by riarenas** [comment]
keeping #5315 to track this.
