### ISSUE TITLE
[QCR][Release ring] Release day stage of release pipeline should move blobs from internal to public storage

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5482]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

There are a number of build-only blobs that cannot be found in public places when we open source an internal build on release day. For example, the toolset repo generates a zip file. That toolset zip file lives in dotnetclimsrc rather than dotnetcli. On release day, when we push the dotnet/sdk (which depends on toolset) commit into the open, the public PR cannot download from dotnetclimsrc. This means that branding updates cannot go pass (though the official build would still pass).

Like making transport packages public, if blobs exist in the private storage accounts, they should be moved to the same location (same container and path) in public storage on release day.

Storage accounts mapping:
- dotnetfeedmsrc -> dotnetfeed
- dotnetclimsrc -> dotnetcli
- dotnetclichecksumsmsrc -> dotnetclichecksums

**Comment by jcagme** [comment]
This should happen in the process of publishing/releasing and not staging right?

**Comment by mmitche** [comment]
> This should happen in the process of publishing/releasing and not staging right?

Yep

**Comment by wtgodbe** [comment]
There are 4 sets of blobs that need to be moved - runtime, aspnetcore, toolset, and installer

**Comment by adiaaida** [comment]
@wtgodbe what about the WindowsDesktop blobs?

Also, do we need to be including every file, or just particular types (I'm seeing svgs, txt, etc in addition to zips, exes, msis, tar.gzs, pkgs, etc)

**Comment by wtgodbe** [comment]
> @wtgodbe what about the WindowsDesktop blobs?

Ah, those likely need to be moved as well for 5.0 - but they're not referenced directly by dotnet/installer in 3.1

**Comment by mmitche** [comment]
I think it can be pretty simple? Basically if you see the location as dotnetclimsrc, you can move the blob to dotnetcli, dotnetfeedmsrc to dotnetfeed, etc.

**Comment by adiaaida** [comment]
yeah, that's what I've got now.

Is there a blob storage equivalent to nuget.exe -push? Or do I need to do some fancy nonsense with PublishPackagesToBlobFeed?

**Comment by adiaaida** [comment]
@mmitche based on the conversations around the sleet feeds, is this still a thing? Are these feeds somewhere else? Am I misunderstanding the sleet issue.

**Comment by mmitche** [comment]
Yep, this is unrelated to the sleet feeds. There is a blob storage equivalent to nuget push (the azure storage SDK can copy blobs around).

**Comment by wtgodbe** [comment]
This is not actually done - today on release day, blobs like `x.y.z-servicing-blah` get copied from dotnetclimsrc into `x.y.z` in dotnetcli - they should also be copied into ``x.y.z-servicing-blah` in dotnetcli

**Comment by wtgodbe** [comment]
CC @Pilchie

**Comment by wtgodbe** [comment]
Another note - in 5.0 and up, dotnet/sdk also publishes to `https://dotnetcli{msrc}.blob.core.windows.net/dotnet/Sdk/` - that needs to get copied too (in place of dotnet/toolset, which doesn't exist in 5.0 and up)

**Comment by adiaaida** [comment]
This has been checked in, and is waiting for rollout

**Comment by adiaaida** [comment]
Moving this back to PR column because I missed the sdk requirement, which is now in PR: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/15282

**Comment by adiaaida** [comment]
Looks like there was a slight issue with multiple sdk scenarios for toolset. Need to make that fix.

**Comment by adiaaida** [comment]
The reason this didn't work for toolset is because we can only connect the release day pipeline to 1 single Servicing pipeline (where we get the manifest json). However, since we have the sdk versions, and therefore can construct the core-builds directory, I think we can just get the manifests from the core-builds directories directly.

**Comment by adiaaida** [comment]
I have checked in the *hopefully* final change for this work. After the next 3.1 release (ie, not the one currently in the pipeline as I believe it was started before I checked in my changes, but the one following), hopefully we can close this out.
