### ISSUE TITLE
Publish to BAR & Feeds in the same task

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#5489]
Currently a build can create several asset manifests before calling the Publish to BAR task, which will then merge all manifests and persist the assets into BAR. The Publish to BAR task however discards the merged asset manifest soon after the info is persisted to BAR.

In a later moment the build definition calls the Publish Assets in Manifest task (from Tasks.Feed) to publish the assets to some feed(s). At that moment we have to process again the several asset manifests.

We should consider:
 - Merging the two tasks into a single operation, I.e., publish to BAR to the feeds in a single task call. 
 - Persisting the merged manifest so that we don't have to parse and merge them again when publishing to feeds.

/cc @mmitche @riarenas

**Comment by riarenas** [comment]
Persisting the merged manifest is a side effect of the signing work. The planned v3 publishing will mitigate the rest of this issue, so I don't think we need to keep this around.
