### ISSUE TITLE
ArchivePayload needs the same mutexing that DirectoryPayload has

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#5493]
DirectoryPayload has mutexing here https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/JobSender/Payloads/DirectoryPayload.cs#L41 to handle parallel invocations cross-process.

ArchivePayload needs the same.

**Comment by BruceForstall** [comment]
@BruceForstall

**Comment by BruceForstall** [comment]
https://github.com/dotnet/runtime/pull/36486 depends on this to avoid a workaround

**Comment by BruceForstall** [comment]
@alexperovich Is there any chance this will be implemented soon?

It looks to me like the way the Helix sdk works is, I invoke MSBuild, generate a bunch of `<HelixWorkItem>` and related, then the SDK sends them off to Helix and waits for them to complete. Unfortunately, that means my system waits for test completion of the first "scenario" before it moves on to the next scenario, which will again invoke MSBuild, create a set of `<HelixWorkItem>`, etc. I need for all these Helix jobs to be created in parallel, to maximize parallelism (and avoid worrying about sequential job timeouts).

**Comment by alexperovich** [comment]
If there are multiple jobs in the same helix project (you specify multiple HelixTargetQueue items), the sdk will send all of them in sequence, then wait for all of them. If there are multiple projects then it each project does the waiting separately.

I think this should be an easy task for FR to do, let me check.

**Comment by BruceForstall** [comment]
@lukas-lansky How's this going? When do you think this will get fixed? I'm blocked on making a CI change to the dotnet/runtime coreclr testing until this is fixed.

**Comment by lukas-lansky** [comment]
This only waits for a deployment now. @missymessa, do you happen to know when we plan to rollout Arcade?

**Comment by markwilkie** [comment]
Arcade just got promoted Friday. (version 5.0.0-beta.20278.4)

To see the latest, along w/ the changelist, you can check out https://github.com/dotnet/arcade#status-of-latest-version-of-arcade-being-validated

**Comment by BruceForstall** [comment]
Leaving a reference here: This was fixed with https://github.com/dotnet/arcade/pull/5543

**Comment by BruceForstall** [comment]
Looks like dotnet/runtime picked it up Saturday with https://github.com/dotnet/runtime/pull/37200
