### ISSUE TITLE
[Feature request] Release day automation branding + internal branch merge

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#5494]
Problem:
Every servicing release require branding update. And some of them require internal branch merge. It requires at least all the following teams to update branding in a short time. It is an over all disruptive work considering a number of teams need to react quickly and drop existing work. It is especially expensive for SDK team (3 * 4  PRs need to be sent) . Several member of my team need to drop their work to keep up with the requirement.

All repos need to react:

- AspNetCore, AspNetCore-Tooling, EFCore, EF6, Extensions 
- CoreClr, CoreFx, Core-Setup
- WPF 
- CLI, Toolset, SDK, Installer
- Winforms 
- WebSdk, Templating

Ask:
However, this is relatively straight forward process. It should be able to be automated. And it does not need to be perfect. The easiest is to have a long shell script to run “git checkout; git merge…git push” all over the repos and branches to merge and update branding. Some one just need to run it locally, and teams just need to manually take the pushed branch and merge it.

Looks like we have `release-cli` with capability of update branding. We can combine it with the script below. And then generalize it to all repos.

Here is the script for my team to merge internal branch:
```powershell
"sdk", "cli", "toolset", "installer" | ForEach-Object -Process {
    cd "$_" 
    git checkout release/3.1.2xx
    git pull
    git checkout -b dev/merge-internal-05142020/release/3.1.2xx
    git remote add otherremote OTHERREMOTE
    git fetch --all
    git merge otherremote/release/3.1.2xx
    Get-Content .\NuGet.config | Where-Object {$_ -notmatch 'darc-int'} | Set-Content .\NuGet.config2
    rm .\NuGet.config
    mv .\NuGet.config2 .\NuGet.config
    git add --all
    git commit -m "Remove internal feed"
    git push --set-upstream origin dev/merge-internal-05142020/release/3.1.2xx
    git remote remove otherremote
    start "https://github.com/dotnet/$_/compare/release/3.1.2xx...dev/merge-internal-05142020/release/3.1.2xx?expand=1"
    cd ..
} 
```

**Comment by jcagme** [comment]
@Tohron @Chrisboh fyi

**Comment by markwilkie** [comment]
cc @mmitche

**Comment by jcagme** [comment]
We have the mechanics for branding is just deciding when in the release should we do it, staging vs publishing.

**Comment by adiaaida** [comment]
I have checked in the mechanics for opening PRs to merge the internal branch changes back to github. When we figure out what pipeline to add this work to, I will add the yaml.

**Comment by adiaaida** [comment]
@vseanreesermsft implemented the internal branch merge and it was run on the release last month. Closing.
