### ISSUE TITLE
Consolidate native code building scripts into 1 place

### ISSUE THREAD

**Issue by eerhardt** [dotnet/arcade#55]
We have a bunch of scripts that are duplicated across repos that build native code:

https://github.com/dotnet/coreclr/blob/master/src/pal/tools/gen-buildsys-win.bat
https://github.com/dotnet/corefx/blob/master/src/Native/Windows/gen-buildsys-win.bat
https://github.com/dotnet/core-setup/blob/master/src/corehost/Windows/gen-buildsys-win.bat

https://github.com/dotnet/coreclr/blob/master/src/pal/tools/probe-win.ps1
https://github.com/dotnet/corefx/blob/master/src/Native/Windows/probe-win.ps1
https://github.com/dotnet/core-setup/blob/master/src/corehost/Windows/probe-win.ps1

We should consolidate these scripts in a single place so bug fixes can be applied in one spot and all dependent places get the fixes.

This also applies to a bunch of common CMake functions like `strip symbols`:

https://github.com/dotnet/coreclr/blob/c1bbdae7964b19b7063074d36e6af960f0cdc3a0/functions.cmake#L125
https://github.com/dotnet/corefx/blob/a9f4a46f48baeaadd515d85ac9de1249b8023a5a/src/Native/Unix/CMakeLists.txt#L193
https://github.com/dotnet/core-setup/blob/b5dd381dd3a586640e4bfe4804d6563861eaab20/src/settings.cmake#L71

In general - we need better native code building infrastructure so we aren't copying these files all over any repo that needs to build native code.

/cc @weshaggard @dagood @markwilkie @janvorli

**Comment by dagood** [comment]
We need to make sure this change to symbol stripping gets in here: https://github.com/dotnet/core-setup/issues/1607. (Keeping unstripped binaries around even if symbol stripping is enabled, for certain scenarios where later tooling expects to do the stripping itself.)

**Comment by eerhardt** [comment]
> We could add something to eng/common/

The other drawback to that approach is that repos don't get to decide where in the folder hierarchy the file needs to live. So in order for the script to be found, the calling scripts need to know where the `$RepoRoot` is - so they can find `$RepoRoot/eng/common`. There also may be files (like CMake files) that depend on being in a specific location in the folder structure.

IMO - the system should be built in such a way that files can be placed anywhere in the repo, and still be kept in sync with the 'master' script.

**Comment by dagood** [comment]
Maybe consider if this fits in with https://github.com/dotnet/arcade/issues/774, dependency expression extensibility. That is, make the scripts a dependency repos can add if they need them, and express anywhere they want.

**Comment by weshaggard** [comment]
Yes I agree this should be extensible and repo's should be able to opt-in to particular folders and their locations. I was chatting with @mmitche about something similar for version updates but I think the same should hold true for file updates. Repo's can easily configure this in their Version.details.xml file.

**Comment by mmitche** [comment]
Yeah that's what I'm thinking.  I think we need more generic dependency expression, let me see what I can come up with.

**Comment by riarenas** [comment]
@mmitche what do you want to do with this one?

**Comment by mmitche** [comment]
I think we can close it. Most of the native code has been consolidated into runtime, so there is much less copying around now.
