### ISSUE TITLE
arcade-service arcade update is blocked because of broken build

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#5530]
https://github.com/dotnet/arcade-services/pull/1160

**Comment by ChadNedzlek** [comment]
I think the general consensus here was that we should switch to the release/3.1 channel for arcade, and not use master.  @markwilkie and @mmitche to confirm.

**Comment by markwilkie** [comment]
That's my understanding of what we decided.  @mmitche still to confirm I think...

**Comment by lukas-lansky** [comment]
OK, so this ticket is now about changing the subscription using darc, triggering the subscription and then verifying that the different PR got merged. Do I understand that correctly?

**Comment by mmitche** [comment]
Yes that is the right thing to do. 3.x arcade is a fine version to use.

**Comment by riarenas** [comment]
We will also need to add this change to 3.x: https://github.com/dotnet/arcade/pull/4671 so that arcade can handle the channels that arcade-services publishes to.

**Comment by lukas-lansky** [comment]
```
C:\Source> darc get-subscriptions --source-repo arcade --target-repo arcade-service
https://github.com/dotnet/arcade (.NET Core 3.1 Release) ==> 'https://github.com/dotnet/arcade-services' ('master')
  - Id: 471021e0-733a-4dd8-faf3-08d7f76e4602
  - Update Frequency: EveryDay
  - Enabled: True
  - Batchable: False
  - Merge Policies:
    AllChecksSuccessful
      ignoreChecks =
                       [
                         "WIP",
                         "license/cla"
                       ]
```

**Comment by riarenas** [comment]
* We can't start taking arcade from 3.x until we decide which channels Arcade-services will publish to: https://github.com/dotnet/arcade/pull/5585#issuecomment-638237314 
* We'll need to tweak the subscription again after the above is clear. The correct channel to move to is `.net 3 eng`, not `.NET Core 3.1 Release`

**Comment by ilyas1974** [comment]
@lukas-lansky, do you have an update on this issue?

**Comment by tkapin** [comment]
@ilyas1974 - @lukas-lansky had to go on parental leave earlier than expected and he wasn't able to pass this issue to anyone else.  Let me unassign him and move this issue to backlog.

**Comment by alexperovich** [comment]
@riarenas have we gotten clarity on what channels we should publish to?

**Comment by ChadNedzlek** [comment]
I think there is a whole epic about this problem.  Trying to figure out which pieces should be in which repo and go to which channels: core-eng#10210

**Comment by riarenas** [comment]
What we decided was that arcade-services won't take arcade updates until https://github.com/dotnet/arcade/issues/5789 is solved, and 3.x arcade uses the new publishing that doesn't inline all the publishing stages in the build, and all branches can publish to any channel.

https://github.com/dotnet/core-eng/issues/10217 pretty much tracks arcade-services picking up this change. I think we can just close this issue.
