### ISSUE TITLE
Release-DotNet prep stage should also push drop to blob storage

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5538]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

To enable some key VS4Mac scenarios, we need an HTTP endpoint that can be accessed during install. Today we push the drop to vsufile, which is great, as well as the build storage.

In addition, after notarization is done, we should push the entire drop to a blob storage location. @leecow will provide details on the base path. I recommend the subpaths match the vsufile path (e.g. 3.01\3.01-blahblah or 5.0.0\5.0.0-preview-blahblah)

**Comment by mmitche** [comment]
@jcagme

**Comment by leecow** [comment]
https://dotnetcli.blob.core.windows.net/dotnet-private/macsign/Runtime/
https://dotnetcli.blob.core.windows.net/dotnet-private/macsign/Sdk/

**Comment by leecow** [comment]
Just noticed this ...

> ... we should push the entire drop ...

@mmitche - I was only thinking of the Mac installers, can you clarify? For example, is this all of `core_builds/3.1.x/3.1.4/3.1.300-servicing-015161/` or `core_builds/3.1.x/3.1.4/3.1.300-servicing-015161/shipping/` or something else?

**Comment by jcagme** [comment]
Normally we only notarize between 2 and 4 PKGs depending on the release. If we could only push these then we'd save in time and space.

**Comment by mmitche** [comment]
I was thinking of everything, so we can have a more permanant archive of our builds (vsufile has space issues)

**Comment by jcagme** [comment]
Ok, so literally everything in the drop we've just created or just shipping/**?

**Comment by mmitche** [comment]
I'd say everything

**Comment by jcagme** [comment]
> I'd say everything

Then for example, for \\vsufile\patches\sign\NET\CORE_BUILDS\5.0.X\5.0.0\5.0.100-preview.5.20270.37, should I create a `5.0.0/5.0.100-preview.5.20270.37` container in https://dotnetcli.blob.core.windows.net/dotnet-private/ and drop all contents from share here?

**Comment by jcagme** [comment]
@markwilkie proposed using https://www.1eswiki.com/wiki/Azure_Artifacts_Drop which makes sense to me. Is there a reason we would want to stick to the Azure containers?

**Comment by mmitche** [comment]
That sounds good to me too.

**Comment by jcagme** [comment]
Details in https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=%2Fdocumentation%2Finternal-release.md&version=GBmain&_a=preview

**Comment by jcagme** [comment]
Things that will end up in the blob, I assume should be signed right? In this case we'll need to execute this step after we've pushed signed files to the drop. @leecow @mmitche can you please confirm?

**Comment by mmitche** [comment]
> Things that will end up in the blob, I assume should be signed right? In this case we'll need to execute this step after we've pushed signed files to the drop. @leecow @mmitche can you please confirm?

Yep.

**Comment by adiaaida** [comment]
Just to confirm: do we want this to happen as part of the staging ring (available early, potentially pre-validation) or as part of publishing (only available when we've decided this is a release we are releasing)?

**Comment by mmitche** [comment]
This would be part of staging. I think we need @leecow's input on final location. I think it should be private.

**Comment by leecow** [comment]
If we're talking blob storage then `https://dotnetcli.blob.core.windows.net/dotnet-private/5.0.X` would be good. I've been putting together what's needed for internal early access at this location.

@mmitche - I envision this perhaps becoming the non-file share stage location rather than a mirror of CORE_BUILDS. What's your thinking on copying everything?

**Comment by adiaaida** [comment]
Out of curiosity, would the new aka.ms link/dotnet-stage location work for this?

**Comment by adiaaida** [comment]
@mmitche @leecow Can we push the mac files to the same dotnetstage blob storage, like we do the others? Is dotnet-private necessary? Today we are still pushing unsigned mac/linux files there, but I've got a change that would instead push the signed files as well. Will that work for the VS4Mac scenario?

**Comment by mmitche** [comment]
> @mmitche @leecow Can we push the mac files to the same dotnetstage blob storage, like we do the others? Is dotnet-private necessary? Today we are still pushing unsigned mac/linux files there, but I've got a change that would instead push the signed files as well. Will that work for the VS4Mac scenario?

I don't see anything wrong with that approach.

**Comment by adiaaida** [comment]
PR for this: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/15567
