### ISSUE TITLE
arcade-validation should be more sample-like

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#5539]
The code in arcade-minimalci-sample has gotten out-of-date and is now wrong.
In #5180 we decided to phase out arcade-minimalci-sample in favor of using the arcade-validation repo to hold samples.

Samples are of no use if they don't work. If we put samples in the arcade-validation repo, they will run as part of standard validation test runs. This will reduce the chances of samples getting out-of-date because they are being ran as part of our normal workflow.

**Comment by missymessa** [comment]
Closing this issue for now. We determined that we'll create new samples if it's necessary in the future.
