### ISSUE TITLE
Validation stages should be able to be completely removed in official builds

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5545]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Many official builds have moved their SDL and other validation into the Release-DotNet pipeline. This means that any runs within official builds are not needed. Repos should be able to opt out from the stages (the stages should not even appear in the official build) by adding a parameter to their yaml file

**Comment by JohnTortugo** [comment]
@mmitche - won't this be addressed once they choose to switch to publishing using Darc/Promotion pipeline? When they opt into that only the one post-build stage will appear in the build and that stage will have only one job which is the one to trigger the promotion pipeline.

**Comment by mmitche** [comment]
@JohnTortugo Isn't that only for the publishing side, not the Validation stage?

**Comment by JohnTortugo** [comment]
The promotion pipeline also includes the validation stage. See here for an instance: https://dnceng.visualstudio.com/internal/_build/results?buildId=626196&view=results

**Comment by mmitche** [comment]
Because of the expense of running SDL, symbol validation, etc. we'll want to be able to skip it if the repo has opted in to running it in the prep stage.

**Comment by JohnTortugo** [comment]
Actually, SDL validation is disabled by default when publishing via Darc -> Promotion Pipeline. Overall, the repo can just use the `post-build.yml's` `enableXXXValidation` to control whether any validation will run or not in the promotion pipeline for that build.

**Comment by mmitche** [comment]
How does it affect the overall time there? Do we still lose time getting machines for any of the disabled validation or do they not get scheduled at all?

**Comment by JohnTortugo** [comment]
Unfortunately, that part is same as before.

**Comment by mmitche** [comment]
@JohnTortugo How can we avoid the scheduling cost?

**Comment by JohnTortugo** [comment]
We use template parameters to control whether any of the validations should be executed. The problem here is that AzDO template expressions cannot include template parameters - if it did we could use that to hide the job/stage. 

Recently, AzDO introduced `Runtime parameters`. Looks like that could be used instead of plain template parameters and it would solve our problem. I didn't play with that yet, though.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script#selectively-exclude-a-stage

**Comment by mmitche** [comment]
Sounds good. I just want to underline the overall goal so you can adjust as needed. Basically the interesting bits of the Validation stage will run after the build is done. The goal here is to remove the time spent doing those things. There are two parts to that time:
1. The time spent actually running tools and such
2. The time spent allocating machines, checking out code, etc.

The second part there is not insigificant, especially added over the full stack. So we want to do our best to completely eliminate that cost.

**Comment by riarenas** [comment]
@epananth this is cleanup that should happen as part of v3 publishing. Can you take a look at it?

**Comment by epananth** [comment]
this is done
