### ISSUE TITLE
Figure out what to do about Arcade Samples

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5547]
We have a couple open issues about how out-dated Arcade-minimal-CI is. We should determine if it's worthwhile keeping that and overhauling it, scrap it altogether and ensure the samples are provided elsewhere (in Arcade Validation, for example), or... ? 

Related issues: 
- https://github.com/dotnet/arcade/issues/5539
- https://github.com/dotnet/arcade/issues/5180

**Comment by missymessa** [comment]
@markwilkie @ChadNedzlek @riarenas The plan is to kill off the arcade-minimal-ci repo and create new samples in Arcade documentation if necessary?

**Comment by markwilkie** [comment]
That is my understanding.  In fact, I think I might have seen that arcade-minimal-ci already went away??  (don't remember)

**Comment by missymessa** [comment]
Emailed the team to give them a heads up about this repo being deleted.

**Comment by missymessa** [comment]
This repo has been deleted. Closing this issue.
