### ISSUE TITLE
Signing Validation tool false positives on azdo due to [Error] present in log outputs.

### ISSUE THREAD

**Issue by safern** [dotnet/arcade#5549]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When a file is not signed but it is present in the signing exclusion list, signing validation will log something similar to: 
[File] 548bd429e4fb6b1938555cdb15b03f30.exe, Signed: False, Excluded, Full Name: runtimes/win-arm/native/apphost.exe [Error] HRESULT: 800b0100 (No signature was present in the subject)

Saying it is Excluded -- `Signed: False, Excluded`. However, since `[Error]` is present in the log output, when running on Azure DevOps, it is parsed by Azure DevOps and displayed as red, when it is not a build error, making diagnostic of real errors on signing validation harder because of these false positives.

Maybe we could avoid printing `[Error]` as part of the output when the file is not signed and excluded?

cc: @chcosta @markwilkie @JohnTortugo

**Comment by markwilkie** [comment]
@joeloff - thoughts?

**Comment by joeloff** [comment]
Removing that output if the file is excluded would be the only option I think
