### ISSUE TITLE
fix warning: job.yml should use DownloadBuildArtifacts instead of DownloadPipelineArtifacts

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#5573]
- [ ] This issue is blocking
- [ ] This issue is causing unreasonable pain

When doing a build using arcade with "eng\common\templates\job\job.yml", the build always output this warning:
`##[warning]Please use Download Build Artifact task for downloading Build Artifact type artifact. https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops`

We should, presumably, do what it says.  It makes it hard to keep my builds clean when the infrastructure is outputting a bunch of warnings.

**Comment by garath** [comment]
Triage: @markwilkie to evaluate this class of issue

**Comment by garath** [comment]
@adiaaida @jcagme Did you work on something for this?

**Comment by garath** [comment]
Related #4628 ?

**Comment by adiaaida** [comment]
We recently made this change in dotnet-release, but not anywhere else. In summary, when making this change, make sure that anything that uses the artifact that you're downloading has its path updated. For example, if you have a an artifact `blob` that you are downloading to folder `foo`, the download path for DownloadPipelineArtifact will be `foo` but for DownloadBuildArtifact will be `foo/blob`. So product repos will be immediately affected.

**Comment by garath** [comment]
Triage: The differences between behavior is significant. Connect with AzDO to understand why the difference exists and what should be done.

**Comment by MattGal** [comment]
Created https://developercommunity.visualstudio.com/content/problem/1103816/need-clarification-on-warning-issued-regarding.html .  Will give it a few days before starting to ping folks directly.

**Comment by MattGal** [comment]
I got the answers I was looking for, putting back to no-epic backlog for triage discussion.

#### Upsides of changing:

- Warning goes away 
- The satisfaction of knowing we're doing things the way AzDO wants

#### Downsides of changing

- We will universally have to get the artifact name right when using constructing paths, and anything downstream that expects the contents 
- Finding out that the path(s) were constructed incorrectly takes the full length of every build pipeline used.
- Long knock-on effect tail

I don't know if this qualifies as FR as it's not directly impacting users other than the warning being irritating.

**Comment by garath** [comment]
Triage: @ChadNedzlek, follow-up with AzDO to eliminate warning.

**Comment by ChadNedzlek** [comment]
These warnings seemed to have vanished. CLosing.
