### ISSUE TITLE
Support x86 and arm64

### ISSUE THREAD

**Issue by RussKie** [dotnet/arcade#5583]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

## Current state

Due to dependency on certain Win32 idiosyncrasies Windows Forms needs to run tests in 32-bit and 64-bit mode. 

<details>
<summary>resolved in https://github.com/dotnet/winforms/pull/3396</summary>

However it doesn't appear that the CI pipeline is truly facilitating this, and 32-bit tests aren't run as 32-bit process:
![image](https://user-images.githubusercontent.com/4403806/83204493-55cb3f00-a18f-11ea-8c10-3d8b54c45536.png)

From my (limited) understanding, the reason for the above is absence of x86 .NET SDK, which is installed if `$installParameters.Architecture` is set to x86:
https://github.com/dotnet/arcade/blob/96c65ad967d2abbbd8e770ba752a6b64255ec669/eng/common/tools.ps1#L243
</details>

This can presumably be achieved by passing `-platform x86` to `build.ps1` script, but then this forces the code to be built in the specified arch not as "Any CPU", and [fails](https://dev.azure.com/dnceng/public/_build/results?buildId=663438&view=logs&j=1f132584-ab08-5fbf-e5d0-5685de454342&t=f9327361-8540-5485-614c-288fff439060). 
```
PS C:\Development\winforms> .\build.cmd -platform x86

Processing C:\Development\winforms\eng\..\global.json
cmake.exe already exists; replacing...
dotnet-api-docs_netcoreapp3.0 was not found in .
Native tools bootstrap failed
Processing C:\Development\winforms\global.json
cmake.exe already exists; replacing...
dotnet-api-docs_netcoreapp3.0 was not found in .
Native tools bootstrap failed
C:\Development\winforms\.dotnet\sdk\5.0.100-preview.5.20251.2\MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:C:\Development\winforms\artifacts\log\Debug\Build.binlog /clp:Summary /nr:True /p:ContinuousIntegrationBuild=False /p:TreatWarningsAsErrors=true /p:Platform=x86 /p:Configuration=Debug /p:RepoRoot=C:\Development\winforms /p:Restore=True /p:DeployDeps=False /p:Build=True /p:Rebuild=False /p:Deploy=False /p:Test=True /p:Pack=False /p:IntegrationTest=False /p:PerformanceTest=False /p:Sign=False /p:Publish=False /warnaserror C:\Users\igveliko\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\Build.proj
  Determining projects to restore...
  All projects are up-to-date for restore.

Processing C:\Development\winforms\eng\..\global.json
cmake.exe already exists; replacing...
dotnet-api-docs_netcoreapp3.0 was not found in .
Native tools bootstrap failed
GET https://dot.net/v1/dotnet-install.ps1
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-preview.6.20271.10/dotnet-runtime-5.0.0-preview.6.20271.10-win-x86.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-preview.6.20271.10/dotnet-runtime-5.0.0-preview.6.20271.10-win-x86.zip
dotnet-install: Adding to current process PATH: "C:\Development\winforms\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished

C:\Development\winforms\Winforms.sln.metaproj : error MSB4126: The specified solution configuration "Debug|x86" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\Development\winforms\Winforms.sln]

Build FAILED.

C:\Development\winforms\Winforms.sln.metaproj : error MSB4126: The specified solution configuration "Debug|x86" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\Development\winforms\Winforms.sln]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:17.53
Build failed.
```
Our code must be built as "Any CPU" as it gets packaged and passed over to dotnet/windowsdesktop, and upstream from that it gets cross-gen'ed to target platforms (x86, x64, or arm64) when it gets packaged.

<details>
<summary>resolved in https://github.com/dotnet/winforms/pull/3396</summary>

For the past week I've been observing builds randomly fail in x86 tests (e.g. https://github.com/dotnet/winforms/issues/3358), however it is impossible to tell whether these are red herrings, or genuine bugs in our code. The fact that x86 tests were passing before is also now under question, if those tests were run as 32-bit process.

Further to it, I have tried hardcoding [`$installParameters.Architecture = 'x86'`](https://github.com/dotnet/winforms/pull/3363) but the tests were still being run by the 64-bit dotnet.exe ([build](https://dev.azure.com/dnceng/public/_build/results?buildId=663449&view=results)):
![image](https://user-images.githubusercontent.com/4403806/83219842-c2a50000-a1b4-11ea-8184-e9c02edf22de.png)
![image](https://user-images.githubusercontent.com/4403806/83219927-fda73380-a1b4-11ea-8c0d-e2503ad2d284.png)

I suspect something is broken here, as it is not finding `x86\dotnet.exe`:
https://github.com/dotnet/arcade/blob/8547938aefa24475a04877285553f0b2663ae249/src/Microsoft.DotNet.Arcade.Sdk/tools/XUnit/XUnit.Runner.targets#L48-L49
</details>

## Target state

1. ~x86\dotnet.exe should be resolved and invoked for 32-bit tests~ resolved in https://github.com/dotnet/winforms/pull/3396
2. ability to install both 32-/64-bit SDKs in a way that co-exists with "Any CPU" solution configuration.

**Comment by RussKie** [comment]
@richlander @tommcdon @mmitche FYI - this will block us in arm64 story as well.

**Comment by garath** [comment]
Triage: The guidance is to use Helix for testing, which should resolve this. Would that work for you?

**Comment by RussKie** [comment]
We've discussed this possibility, and it is on our backlog (https://github.com/dotnet/winforms/issues/3140). But IIUC it's somewhat involved undertaking on our part.

And it doesn't allow us to to run tests locally.

/cc: @AdamYoblick

**Comment by markwilkie** [comment]
> somewhat involved undertaking on our part
I would love understand more what makes it hard.  Perhaps we could help.

> And it doesn't allow us to to run tests locally.
Helix is generally orthogonal to running locally.  The idea is to be able to run the tests locally by building/running your test projects.  Helix would be doing the same thing, but in the cloud...  

The main point here is not to change they way your tests are built/run, but to "split" them out from your main build.  Many many options open up once this happens...

**Comment by richlander** [comment]
Is there guidance on how to target multiple architectures, for both building and testing? It seems like there should be. Shouldn't the answer be there?

**Comment by RussKie** [comment]
> I would love understand more what makes it hard. Perhaps we could help.

@AdamYoblick can chime on this, he "suffered" the lot.



> Helix is generally orthogonal to running locally. The idea is to be able to run the tests locally by building/running your test projects. Helix would be doing the same thing, but in the cloud...
> 
> The main point here is not to change they way your tests are built/run, but to "split" them out from your main build. Many many options open up once this happens...

The big problem we're having issues with is inability to run x86 tests locally. On build agents [we run tests in x86 and x64](https://dev.azure.com/dnceng/public/_build/results?buildId=697717&view=artifacts&type=publishedArtifacts), I've looked at the ymls but I couldn't decipher what magic drives it:
![image](https://user-images.githubusercontent.com/4403806/85256789-1818b800-b4a8-11ea-8345-ebecc5e59b61.png)

We were totally blocked until recently, https://github.com/dotnet/winforms/pull/3396 got us a little further in  (thanks @hoyosjs) - now we can run platform specific tests in VS, but we're still unable to run tests from cli.

For me personally this is a massive productivity issue - I constantly switch branches, reloading VS every few minutes grinds my work to a halt. This also affects some of our contributors (like @hughbe) who use VS Code as their primary IDE, and who are forced to push changes in, further adding load on our infrastructure.

**Comment by RussKie** [comment]
I realise I reported 2 issues that are related, one dependent on the other.
The first issue - inability to run tests as true 32-bit processes is now resolved by  dotnet/winforms#3396. This also allowed us to run platforms-specific tests in VS. 
The second issue that prevents us running platform-specific tests from cli still remains (e.g. `build -test -platform x86`).

I have updated the original description to match the current state.

**Comment by markwilkie** [comment]
@alexperovich - could you help figure out the specifics of what the issues are here please?

@richlander - general guidance for small repos, running tests are part of the build is good and support via https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#testarchitectures-list-of-strings.  Specifically for winforms, I want to dig in more to find out what's going on.

cc/ @tmat

**Comment by hoyosjs** [comment]
`build -test` will run both in your case. You have this in your project:

`<TestArchitectures Condition="'$(Platform)' != 'x86'">x64;x86</TestArchitectures>`

As for ARM64, that wasn't accounted for; there's currently no really good way to do an architecture agnostic build and test directly unless from an arm64 host, which was announced recently by AzDO but I don't know if Windows ARM64 is available. 

Until very recently there was no native SDK, and normally none of our workflows build + test natively on ARM64. The other repos that I've worked with build the tests and create payloads manually to provide to the Helix SDK, completely circumventing the test support in Arcade for that scenario at least.

**Comment by markwilkie** [comment]
@RussKie - thoughts on next steps?

**Comment by mthalman** [comment]
We've been making use of the new agent support for Linux ARM64 hosts in our Docker builds. It's been working great. If you want support for Windows ARM64, I would suggest logging a similar issue to the one for Linux: https://github.com/microsoft/azure-pipelines-agent/issues/1911.

**Comment by alexperovich** [comment]
@markwilkie the issue of supporting x86 and arm64 in builds is..... an incredible amount of work that would have continual maintenance. Everything in arcade was written assuming x64. All of it would need to be fixed and we would need to create 2 additional builds for arcade to keep it working. The currently supported and maintained scenario for running tests on x86 and arm is Helix.

The support in arcade sdk for running tests (not building) on x86 does work from what I know. If that doesn't we should file a specific issue about it. I don't see us ever supporting arm64 for builds.

**Comment by markwilkie** [comment]
@RussKie - it looks like the current guidance of splitting your tests out separately is still the best way.  What's the best way we can help?

**Comment by RussKie** [comment]
Sorry for the silence, I'm stretched thin atm. 

I think the next step for me is to wrestle with the MSBuild and coerce it to run 32- and 64-bit tests locally, as this is what's degrades the developer experience. Nice find @hoyosjs, I think I've written that condition but I have completely forgotten about it.
@markwilkie - if I can get help here - it would be awesome.

With regards to the CI runs - I don't think there is an immediate action. 
I understand our current setup is a on hot path, and needs to be reworked with tests offloaded to the Helix. We may likely need some help with that too once we get on to it (/cc: @merriemcgaw @AdamYoblick). But this will be a done separately.

Thank you all for your help.

**Comment by markwilkie** [comment]
From what I can tell, it seems this specific issue is sorted as there's a work-around, and a path forward.

From a guidance point of view, separating out the tests from the build should give the needed flexibility in a clean fashion.  From earlier in this issue, it seems there have been challenges doing this, and we'd love to learn more and help/fix whatever.  I'm convinced this will be much better for everyone in the long term.

For this issue, I'm closing it.
