### ISSUE TITLE
[QCR] [Staging Ring] Antares prep output missing AspNetCore assets

### ISSUE THREAD

**Issue by leecow** [dotnet/arcade#5601]
@adiaaida 

A complete set of Antares assets will include AspNetCore runtime zips

* aspnetcore-runtime-internal-$(version)-win-x86.zip
* aspnetcore-runtime-internal-$(version)-win-x64.zip

These do not need to be generated, only staged from the drop location. The files can be found in drop/assets/manifest.json.

**Comment by adiaaida** [comment]
PR is here: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/8307
