### ISSUE TITLE
[QCR] [Staging Ring] Non-shipping files included in the aggregated checksum file

### ISSUE THREAD

**Issue by leecow** [dotnet/arcade#5602]
@adiaaida 

I think this would also mean that the staged file list also needs to be trimmed but I am not sure where I can see that list. 

See https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=%2Fsrc%2Finitialize-release%2Ffile_lists%2Ffile_list_5.0.txt for the correct list of installers and binary archives to be staged and eventually published.

Basic filtering is:

* no MSI
* no `*internal*` files
* no `*crossgen*` files
* no `*nethost*` files
* no `*engine*` files

Marking these as nonShipping = true in the manifest.json would take care of it?

**Comment by adiaaida** [comment]
PR is here, modulo that question: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/8290
