### ISSUE TITLE
[Darc] Group GitHub content updates into one commit

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#561]
Looks like the best option is to create a tree which contains each of the updated files. Need to further investigate but this seems feasible.

**Comment by dagood** [comment]
Yep, works for VersionTools on GitHub: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.VersionTools/Automation/GitHubVersionsRepoUpdater.cs

**Comment by jcagme** [comment]
Thanks for pointing this out!
