### ISSUE TITLE
SigningValidation doesn't validate files that are not in a package

### ISSUE THREAD

**Issue by bozturkMSFT** [dotnet/arcade#5612]
- [ ] This issue is blocking
- [ ] This issue is causing unreasonable pain

I have the dotnet-install.ps1 script file that I can get arcade to sign. It is not in a package, and my project produces not packages.

When it comes to validating, arcade only validates signatures of packages and their content. So my individual `dotnet-install.ps1` file will not be validated automatically.

I can get around this issue
- by putting my script in a package even though a package isn't needed, which isn't ideal
or
- directly running `SignCheck`, which wasn't easy for me to do.

I believe having built-in support for validating signatures of individual files in arcade could make things much simpler for such future cases.

**Comment by JohnTortugo** [comment]
Thanks for filling this @bozturkMSFT

**Comment by garath** [comment]
@joeloff your thoughts?

**Comment by JohnTortugo** [comment]
This isn't in the scope of the SignCheck tool. The limitation comes from our validation scripts: they only call signing validation on .nupkgs.

**Comment by joeloff** [comment]
What @JohnTortugo said. The tool itself will check any file you give it, it's just that Arcade only executes it on nupkg files.

**Comment by garath** [comment]
Triage: Arcade is intended to only support validation for nupkgs. More can be done, and PRs are welcome, but likely won't originate from dnceng.

**Comment by garath** [comment]
@bozturkMSFT Please reopen if you'd like to continue with the discussion.
