### ISSUE TITLE
[darc/maestro++] "NoRequestedChanges" Maestro++ merge policy not working

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5629]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

See this test PR: https://github.com/maestro-auth-test/maestro-test2/pull/10568 

I requested changes in the PR, and Maestro++ correctly detected that, but once I approved the PR, the service still believes there's a blocking review, and won't change the merge policy to green.

@epananth who noticed this first during local work.

**Comment by MattGal** [comment]
Rolled out yesterday.
