### ISSUE TITLE
Update Tasks.Feed package to use Azure Storage SDK

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#563]
The current implementation of the Feed package uses raw http requests to talk to azure storage. This should be changed to use the azure storage client libraries so we don't have to create custom retry logic. The libraries have proper retry and error handling built in.

**Comment by dagood** [comment]
Definitely. This has also been discussed in this BuildTools issue (now this task lives in both places): https://github.com/dotnet/buildtools/issues/1816.

**Comment by markwilkie** [comment]
Make sure that this builds using source build

**Comment by dagood** [comment]
To be a little more precise, it has to not block source-build. 😄 That most likely means not building the Feed package at all during source-build, because I'm very doubtful we can manage to build Azure Storage SDK (and its dependencies) from source.

**Comment by JohnTortugo** [comment]
@alexperovich - all, just to confirm, this is not blocking build preview. Right?

**Comment by chcosta** [comment]
> That most likely means not building the Feed package at all during source-build

@crummel @dagood , can you confirm that the current designs of source-build are such that this is still true and we can exclude the feed package from source-build?

**Comment by dagood** [comment]
😄 That just came up at https://github.com/dotnet/arcade/pull/2653#issuecomment-488324982, and AFAIK yes.

There's a proposal to have build infra do fancy stuff with build caches and per-repo builds, but it's ok for infra to use non-source-buildable stuff for that because distro maintainers won't use any of that for their end-to-end builds.

**Comment by crummel** [comment]
Yes, we don't need or build Microsoft.DotNet.Build.Tasks.Feed.  Currently it's patched out but we should upgrade to the `ExcludeFromSourceBuild` pattern now that we have it.

**Comment by chcosta** [comment]
Nice.  I didn't realize this was already being worked on (guess I should have followed all the links in this issue) in https://github.com/dotnet/arcade/pull/2653.  I guess I'll take a step back and take a look at what @JohnTortugo is doing.
