### ISSUE TITLE
[QCR][Validation ring] Add Nuget-Validation to Validation Ring

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#5631]
Looking at post-build validation items there is a task that we need to move to the validation stage so when repos turn off post-build they still have full coverage. Adding this to the validations stage should be easy since we just need to use https://github.com/dotnet/arcade/blob/master/eng/common/post-build/nuget-validation.ps1 as done in https://github.com/dotnet/arcade/blob/master/eng/common/templates/post-build/post-build.yml#L116.

Also, we need to make sure we add validation to determine that packages met a certain set of rules. For this we could use @Eilon's tool https://github.com/Eilon/NuGetPackageVerifier.

**Comment by garath** [comment]
The first half of this issue, the previous Arcade post-build step, is now in PR.

**Comment by adiaaida** [comment]
@garath What conclusions did you come to on the second half of this issue?
