### ISSUE TITLE
Symbols-validation.ps1 incorrectly counting number of failed 

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#5638]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Example: https://dev.azure.com/dnceng/internal/_build/results?buildId=679968&view=logs&j=b30a92fc-e51b-572d-9566-e3b9dae8a01d&t=e564009e-c055-53ef-34ee-0088bca9e3b6&l=2625

Fails saying that 81 packages are missing symbols, but a search of the log finds no "Missing symbols for xxx modules in the package yyy" statements, suggesting that no packages were missing symbols.

This suggests that something is wrong in the counting of missing symbols in the code that adds parallelism (https://github.com/dotnet/arcade/blob/master/eng/common/post-build/symbols-validation.ps1#L191) or in the return value of $CountMissingSymbols (ie for packages that are not missing, what is $CountMissingSymbols returning such that $jobResult does not equal 0). This appears to work for sourcelink validation (in the same ci run, the sourcelink leg fails with 76 packages with missing links and a cursory glance suggests that is correct. Likewise a different build passes with 0 missing links, which is correct).

A simple test to see if it's in the parallelism or in the return value would be, instead of returning $MissingSymbols (the count of the # of modules with missing symbols), to return 1 if symbols are missing and 0 if not, like sourcelink-validation does. I also suggest checking what the value of $jobResult is.  

To test:

* Download a few of the the symbols packages from the linked build (you don't need all of them, but it's good to download more than 1. Running on all of the packages could take up to an hour to test).
* Run 
```
eng/common/post-build/symbols-validation.ps1
                -InputPath <path to symbols>
                -ExtractPath <some other directory>
                -DotnetSymbolVersion 1.0.115903
                -ContinueOnError
                -Clean
```

**Comment by adiaaida** [comment]
@jcagme FYI

**Comment by missymessa** [comment]
Whoever works on this, please be sure to add tests either in Arcade or Arcade Validation to catch this issue in the event that it occurs again.
