### ISSUE TITLE
Delete `dn-bot-dnceng-unviersal-packages-rw` secret

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#5640]
This variable was added with a typo to the `AzureDevOps-Artifact-Feeds-Pats` variable group. We should delete it since current YAML files reference a variable with the correct name. However, there are some "outdated" repos that still have some YAML files that reference that variable:

- https://github.com/dotnet/platform-compat/pull/217 - is broken since July last year.
- https://github.com/dotnet/msbuild-language-service - doesn't seem to be receiving maestro updates.
- https://github.com/dotnet/source-build - outdated

We should investigate if we can update these repos and whether it's possible to delete the `dn-bot-dnceng-unviersal-packages-rw` thing - as it was clearly a typo and is [generating maintenance costs](https://github.com/dotnet/core-eng/issues/10045).

**Comment by MattGal** [comment]
it'll be painful but I'm going for it :)

**Comment by MattGal** [comment]
I cleaned up the relevant variable groups, checked out the repos that still have this string:


  dotnet/msbuild-language-service - May use this template but will just need an arcade update if used again (no commits in 11 months)
  dotnet/source-build - Not currently using the related templates
  dotnet/platform-compat - Not currently using the related templates

I'll keep this issue in Validate til the end of the week, at which point I'll delete the secret (if we need it back, just copy from the correctly spelled one) and close the issue.

**Comment by MattGal** [comment]
After one week of no screaming, closing :)
