### ISSUE TITLE
[Publishing] PublishArtifactsInManifest task logs an error when package is successfully pushed during the last retry attempt

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5649]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The way this loop is written: https://github.com/dotnet/arcade/blob/42a60d110cba56f543a987fdf519aac4d2b75be9/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifest.cs#L903-L943

When we successfully push the package during the very last retry attempt, we will still trigger the following check that incorrectly reports that the packages were not pushed due to the post-increment in the retry index.

We should rewrite this piece to handle the retries correctly.

An example build for this is: https://dev.azure.com/dnceng/internal/_build/results?buildId=687640&view=results

All the packages that reported failure were published to the feed.

```
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20309.1\tools\SdkTasks\PublishArtifactsInManifest.proj(79,5): error : Failed to publish package 'Microsoft.NETCore.App.Runtime.ios-arm64@5.0.0-preview.7.20315.2' after 3 attempts.
```
https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Microsoft.NETCore.App.Runtime.ios-arm64&protocolType=NuGet&version=5.0.0-preview.7.20315.2&view=overview
 
```
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20309.1\tools\SdkTasks\PublishArtifactsInManifest.proj(79,5): error : Failed to publish package 'Microsoft.NETCore.App.Runtime.ios-arm@5.0.0-preview.7.20315.2' after 3 attempts. 
```

https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Microsoft.NETCore.App.Runtime.ios-arm&protocolType=NuGet&version=5.0.0-preview.7.20315.2&view=overview
 
```
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20309.1\tools\SdkTasks\PublishArtifactsInManifest.proj(79,5): error : Failed to publish package 'Microsoft.NETCore.App.Runtime.ios-x64@5.0.0-preview.7.20315.2' after 3 attempts. 
```
https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Microsoft.NETCore.App.Runtime.ios-x64&protocolType=NuGet&version=5.0.0-preview.7.20315.2&view=overview

**Comment by riarenas** [comment]
Some suggestions from @mmitche:

> The while should either be:
> * while(true) with explicit exits from the method (returns) on max retries, package content check failure, and package push success.
> * Only check the attempts, with explicit returns from the method on failure modes within the loop, and no pre or post-increment

**Comment by missymessa** [comment]
Adding a reminder to include testing for this.

**Comment by MattGal** [comment]
Verified there are builds succeeding using the update, e.g. https://dnceng.visualstudio.com/internal/_build/results?buildId=750067&view=logs&j=c4b5a6e5-e43f-5a08-b65f-d603d0b5277f&t=bf288fe2-9135-5032-a01d-826cb0aca216 .  I will send a partners mail describing the issue shortly.  

The underlying problem causing us to randomly retry that hit the bug has been addressed, so it's hard to truly exercise the fix, but there are now 4 more tries, back off between tries, and the off-by-one error is fixed.
