### ISSUE TITLE
Create Tests for Validation Ring Operations

### ISSUE THREAD

**Issue by Tohron** [dotnet/arcade#5650]
Tests are needed for the functionality of the operations used in the validation ring:

- [ ] ValidateAssetsOperation
- [ ] ValidateChecksumsOperation
- [ ] ValidatePackageDependenciesOperation

**Comment by jcagme** [comment]
Actually we need tests for **all** operations in ReleaseCli not only those in the validation ring

**Comment by Tohron** [comment]
I'm just breaking up the issues so I don't have a single issue that stays in WIP forever, then has to take all the tests into PR at the same time.

**Comment by jcagme** [comment]
Ok cool. That's a great approach BTW!
