### ISSUE TITLE
"PackageDescription must be specified" errors in Runtime with Arcade version 5.0.0-beta.20319.1

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5678]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Runtime is one of the bellwether repos that we use to determine if Arcade can be promoted to `.NET Eng - Latest` channel. Building a branch of Runtime with the latest version of Arcade is how we validate. Unfortunately, this version of Arcade is causing "PackageDescription must be specified" in the build of the branch used for validation: 

AzDO Build Link: https://dev.azure.com/dnceng/internal/_build/results?buildId=696071&view=results

Diff of changes in Arcade between the last promotion (version 5.0.0-beta.20316.1) and this one: https://github.com/dotnet/arcade/compare/71b580038fb704df63e03c6b7ae7d2c6a4fdd71d...1f68f02347dcb21dc61e080613ab55a98658b9f3

This issue is to investigate what is causing this error to occur in Runtime with the latest Arcade.

**Comment by missymessa** [comment]
/cc @jaredpar (for visibility into this build of Arcade affecting Runtime)

Everyone else cc'd, changes you have made are present in this version of Arcade, so please help investigate this issue. 
/cc @garath @JohnTortugo @maryamariyan @DrewScoggins @ericstj @premun @jcagme @ooooolivia @gbalykov

**Comment by missymessa** [comment]
This error is still occurring in Runtime: https://dev.azure.com/dnceng/internal/_build/results?buildId=698171&view=results 

Arcade promotion will be blocked until this error is mitigated.

**Comment by ericstj** [comment]
I'll have a look.

**Comment by ericstj** [comment]
Caused by my change which set `IsPackable`.  This caused this target to be run: https://github.com/dotnet/arcade/blob/75da942953455e0e4e07a9c613bca74015902975/src/Microsoft.DotNet.Arcade.Sdk/tools/Workarounds.targets#L69

It sequences before GenerateNuSpec which we also have in PkgProj, but checks for properties like `PackageDescription` which have a different name in PkgProj.

**Comment by missymessa** [comment]
@ericstj thanks for looking into this, Eric! Is there any testing we could have done in Arcade Validation which would've caught this?

**Comment by ericstj** [comment]
Perhaps if we had a pkgproj that builds in a similar way to the way dotnet/runtime pkgprojs do.  But honestly I'd prefer we invest in eliminating pkgproj and instead adding targets to CSProj that support the scenarios that pkgproj supports.

**Comment by ericstj** [comment]
So it looks like this was fixed, the validation build made it past the point of failure, however it still seems to be failing due to timeout later in the pipeline: https://dev.azure.com/dnceng/internal/_build/results?buildId=701873&view=results

@missymessa does this look OK?
