### ISSUE TITLE
Test Run titles in Arcade Services are not configured properly

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5694]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Test Runs names in Arcade Services currently look like this, which is not very helpful: 

![image](https://user-images.githubusercontent.com/47990216/85442265-d9850b00-b544-11ea-84fb-063d8545c42d.png)

**Comment by ChadNedzlek** [comment]
This should be fixed by https://github.com/dotnet/arcade-services/pull/1260

**Comment by ChadNedzlek** [comment]
I'm watching the build now and will close this if the test run looks good. :-)
