### ISSUE TITLE
Backport version identifier code into 3.1

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#5695]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

We need the changes to the version identifier code backported to the release 3.1 branch. It's blocking this merge: https://github.com/dotnet/arcade-services/pull/1255

**Comment by ChadNedzlek** [comment]
I'm mostly just writing down what @mmitche told me here.  I'm not 100% sure which commits need to get backported, but it sounds like it should be pretty straightforward.

**Comment by MattGal** [comment]
This, and the bytecode change that makes Helix jobs sometimes fail on retry, are ported via https://github.com/dotnet/arcade/pull/5699

**Comment by MattGal** [comment]
Changes merged, as this will automatically flow , closing
