### ISSUE TITLE
Apply source-build patches

### ISSUE THREAD

**Issue by lpatalas** [dotnet/arcade#5719]
This issue tracks progress of applying source build patches to Arcade repository. This is related to https://github.com/dotnet/source-build/issues/1501.

- [x] [0001 - Update SystemNetHttpPackageVersion](https://github.com/dotnet/source-build/blob/4f0f472e458be20256b478cddcfefb0b6c64a0d5/patches/arcade/0001-Update-SystemNetHttpPackageVersion.patch)
- [x] [0002 - Remove reference to Microsoft CodeAnalysis in Packaging](https://github.com/dotnet/source-build/blob/4f0f472e458be20256b478cddcfefb0b6c64a0d5/patches/arcade/0002-Remove-reference-to-Microsoft-CodeAnalysis-in-Packag.patch)
- [x] [0003 - Update SystemTextJson version from Package flow](https://github.com/dotnet/source-build/blob/4f0f472e458be20256b478cddcfefb0b6c64a0d5/patches/arcade/0003-Update-SystemTextJson-version-from-Package-flow.patch)
- [x] [0004 - Update versions of some packages](https://github.com/dotnet/source-build/blob/4f0f472e458be20256b478cddcfefb0b6c64a0d5/patches/arcade/0004-Update-versions-of-some-packages.patch)
- [ ] [0005 - Don't attempt to update icon](https://github.com/dotnet/source-build/blob/4f0f472e458be20256b478cddcfefb0b6c64a0d5/patches/arcade/0005-Don-t-attempt-to-update-icon.patch) - probably not needed anymore. Won't be applied at this time
- [x] [0006 - Don't build for net472 when building from source](https://github.com/dotnet/source-build/blob/4f0f472e458be20256b478cddcfefb0b6c64a0d5/patches/arcade/0006-Don-t-build-for-net472-when-building-from-source.patch)
- [x] [0007 - Use SystemReflectionMetadata from package flow](https://github.com/dotnet/source-build/blob/4f0f472e458be20256b478cddcfefb0b6c64a0d5/patches/arcade/0007-Use-SystemReflectionMetadata-from-package-flow.patch)
- [x] [0008 - Exclude Helix tests from source-build](https://github.com/dotnet/source-build/blob/4f0f472e458be20256b478cddcfefb0b6c64a0d5/patches/arcade/0008-Exclude-Helix-tests-from-source-build.patch)
- [ ] [0009 - Add reference to PlatformAbstractions](https://github.com/dotnet/source-build/blob/4f0f472e458be20256b478cddcfefb0b6c64a0d5/patches/arcade/0009-Add-reference-to-PlatformAbstractions.patch) - it seems that Arcade works correctly even without this patch so I won't apply it
- [x] [0010 - Update newtonsoft json version for arcade](https://github.com/dotnet/source-build/blob/4f0f472e458be20256b478cddcfefb0b6c64a0d5/patches/arcade/0010-Update-newtonsoft-json-version-for-arcade.patch)
- [x] [0011 - Reassign MsbuildTaskMicrosoftCodeAnalysisCSharpVersion in offline build](https://github.com/dotnet/source-build/blob/4f0f472e458be20256b478cddcfefb0b6c64a0d5/patches/arcade/0011-Reassign-MsbuildTaskMicrosoftCodeAnalysisCSharpVersi.patch)

**Comment by garath** [comment]
@tkapin What epic should this go to?

**Comment by tkapin** [comment]
@garath I don't think it belongs in any epic, it's just a one-time work that needs to get done. Too big for FR, too small for a dedicated epic. I've classified that as extended FR, which I don't think it is, but it's as close as we can get.

@ilyas1974 - This is an ideal material for our operations discussions ;-).

As for the status, @lpatalas has this in PR (#5728) will merge it on the week of 20-July when he's back from vacation.

**Comment by lpatalas** [comment]
The PR was merged today. I'm moving it to validate state.

**Comment by tkapin** [comment]
@lpatalas - This is in Validate state for quite some time now, please close it if it's validated already. Thanks!

**Comment by lpatalas** [comment]
There has not been any problems related to the changed code since merging it so I think we can close it.
