### ISSUE TITLE
[Signing] Create Signing.props file (2/4)

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5724]
Process should be able to take signing metadata and convert it into the signing.props file.

**Comment by missymessa** [comment]
This issue shouldn't be more than taking the SigningInformation out of the MergedManifest.xml and creating a new file called Signing.props with that as it's content.

**Comment by markwilkie** [comment]
Does this is imply that perhaps just using mergedmanifest might be a better way to go?

**Comment by missymessa** [comment]
> Does this is imply that perhaps just using mergedmanifest might be a better way to go?

I believe that the signing functionality that we'll be using in Arcade expects there to be a signing.props file. So either way, we'd need to refactor the existing signing functionality to use a mergedmanifest.xml, or copy the data from the mergedmanifest.xml to a signing.props file. I think the latter is the easier option.

**Comment by markwilkie** [comment]
Sounds good - I defer to you.  Whatever the right thing is of course....well...right.    When thinking about that (now and in the future), sometimes what's most correct has to be carefully weighed again expediency.   Whenever possible, we should go with correctness of course.

**Comment by missymessa** [comment]
PR here: https://dnceng.visualstudio.com/internal/_git/dotnet-release/pullrequest/9202

**Comment by missymessa** [comment]
PR merged. Closing.
