### ISSUE TITLE
[QCR][Validation ring] Group signing validation errors and log them at the end

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#5730]
Today only a count summary is logged at the end and if there were errors I'd need to scroll up and find the errors among a bunch of other logs. Even when the error log is in red, it is a kind of tedious task.

Sample of this: https://dev.azure.com/dnceng/internal/_build/results?buildId=710855&view=logs&j=5b85417e-54cb-5f6d-80b3-4ff34773e92d&t=8a199eec-3af7-5249-efa2-c8f3a47fb99f

**Comment by joeloff** [comment]
If you're running with ```-f``` or ```--file-status```, remove it. The default is to only report unsigned files.
