### ISSUE TITLE
Build fails with mktemp usage message

### ISSUE THREAD

**Issue by ryandesign** [dotnet/arcade#5742]
Hi, msbuild fails to build on OS X 10.10 or older. The error is:

```
  usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
         mktemp [-d] [-q] [-u] -t prefix 
```

[Here is a full build log](https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/116475/steps/install-port/logs/stdio).

macOS uses BSD mktemp which doesn't support all of the permutations of options that GNU mktemp does, especially not on older versions of OS X.

**Comment by garath** [comment]
@ryandesign Unfortunately, .NET doesn't support OS X 10.10. See [Install .NET Core on macOS](https://docs.microsoft.com/en-us/dotnet/core/install/macos) for supported combinations.

**Comment by ryandesign** [comment]
It would not be difficult for you to rewrite your usage of mktemp to be compatible with all systems.
