### ISSUE TITLE
Maestro not triggering dependency updates

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5749]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

Maestro is not triggering all dependency updates in cases where a repo in the dependency graph doesn't have a version details file. This happens once in some .NET 5 repos.

**Comment by mmitche** [comment]
A bug was introduced in the latest rollout with a call to ToList() on a null value. Fix is here

https://github.com/dotnet/arcade-services/pull/1279

**Comment by sunandabalu** [comment]
Issue moved to [dotnet/core-eng #10213](https://github.com/dotnet/core-eng/issues/10213) via [**ZenHub**](https://www.zenhub.com/)
