### ISSUE TITLE
Recommended feed to get nightly nuget packages

### ISSUE THREAD

**Issue by zivkan** [dotnet/arcade#5752]
I'm not sure where the best place to ask this is, but here is my best guess.

In the past, customers who wanted to try nightly/per-build packages of packages built from dotnet/runtime would use `https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json`. They could then install the latest version of `System.Text.Json`, or whatever else they wanted to try out.

However, since this is a static feed, generated by Sleet, the search "service" is a static file more than 200MB now, so does not respect the HTTP GET parameters requesting to skip and limit results. This has caused customers using this feed in Visual Studio to [crash with out of memory exceptions](https://github.com/NuGet/Home/issues/8478). NuGet recently changed the way we deserialize the search results to avoid crashing, but we [no longer support pagination for static feeds](https://github.com/NuGet/Home/issues/9726).

I noticed many dotnet repos now use public feeds from `https://pkgs.dev.azure.com/dnceng/public`, although `dotnet/sdk` is still using the dotnet-core sleet feed.

Is there a Azure Artifacts feed that is equivalent to the dotnet-core sleet feed?  What feed do you recommend for customers who want to test nightly builds?

**Comment by riarenas** [comment]
The short answer is: for product packages, your best bet is probably the dotnet3 / dotnet5 feeds: https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=dotnet5

We also have these feeds for engineering and tooling packages:
* Engineering infrastructure packages: https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=dotnet-eng
* Tooling packages: https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=dotnet-tools

There is no mega feed like dotnet-core where we push every single package anymore.

**Comment by zivkan** [comment]
thank you 👍
