### ISSUE TITLE
Investigate failure in arcade-validation dependency update PR

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5778]
- [x] This issue is blocking 

This is blocking flowing the latest changes of arcade.
- [ ] This issue is causing unreasonable pain

Dependency update PR is stuck: https://github.com/dotnet/arcade-validation/pull/1628. I'll find which change introduced the problem and fix / revert so that arcade flow gets unblocked from that side.

**Comment by riarenas** [comment]
The helix validation is failing because the work items are failing: https://helix.dot.net/api/2019-06-17/jobs/14933479-ae14-418c-b769-bebc9692c98d/workitems/Validation.Tests.dll/console

It looks like the tests aren't actually running due to a misconstructed dotnet invocation:

```
 dotnet exec --roll-forward Major --runtimeconfig Validation.Tests.runtimeconfig.json --depsfile Validation.Tests.deps.json /home/helixbot/work/9FB7092E/p/xunit-runner/tools/netcoreapp2.0/xunit.console.dll Validation.Tests.dll -nocolor -xml testResults.xml
The application to execute does not exist: '--roll-forward'
```

And then the test results cannot be uploaded:
```
2020-07-08T01:02:48.300Z	INFO   	xunit-reporter.py	xunit-reporter(85)	main	Didn't find test results in working directory, trying upload folder
2020-07-08T01:02:48.301Z	ERROR  	xunit-reporter.py	xunit-reporter(90)	main	Unable to report xunit results: no test results xml file found.
```

Looks to have been introduced by this PR: https://github.com/dotnet/arcade/pull/5748

**Comment by riarenas** [comment]
This is due to the fact that arcade-validation is using a 2.1 SDK When sending the tests to helix, while roll-foward is a 3.x and newer feature. We shouldn't be breaking this retroactively, so we should add some conditions before adding the roll-forward parameter. Since this is blocking the flow of arcade for preview 8, I'm going to revert the original PR and sync up with @alexperovich on the proper fix.

**Comment by alexperovich** [comment]
Fix is here https://github.com/dotnet/arcade/pull/5779
