### ISSUE TITLE
Harden xunit-reporter.py against hangs in upload_blob

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#5783]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

As noted in this PR: https://github.com/dotnet/runtime/pull/39153
It seems that our storage client options are hitting https://github.com/Azure/azure-sdk-for-python/issues/11437 .  

- We might be able to work around this by upping the Helix azure-storage-blob version to 12.3.2 from 12.0.0 (that'd be a change in dotnet-helix-machines)
- Otherwise we should look into providing a timeout mechanism here for retries, as the file in question was actually quite small and if the upload_blob() call hadn't hung a retry would have been quite fast.

**Comment by MattGal** [comment]
@AlitzelMendez can this be closed?  If it's merged in Arcade for this long it's in use.

**Comment by AlitzelMendez** [comment]
yes, it is already merged. closing the issue
