### ISSUE TITLE
[Signing] Maintaining SignToolData file

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#58]
What is the strategy for maintaining the SignToolData.json (https://github.com/dotnet/arcade/blob/master/build/SignToolData.json) file? I'm not a fan of manually maintaining a list of files that we need to sign. People always forget to update it and we have build failures because some binary is unsigned. In the core repo's we have moved to a model of generating and dropping files next to the binaries (foo.dll.requires_signing) based on a property, as part of the build process and then gather the list of files to sign from those. It has worked pretty well over the last few years of doing it.

**Comment by weshaggard** [comment]
I'm fine if folks would like to manually maintain the file but I don't think it should be a requirement and I'm ok with the format I just want to enable an option to generate as part of the build instead of manually maintaining it.

**Comment by jaredpar** [comment]
I have another suggestion: please try this before you reject it. Literally the only people who want this option have not tried it. Why create deviations on the repositories based on a fear of a solution you haven't tried?

**Comment by weshaggard** [comment]
We have tried it for many years in the TFS world and I worked extremely hard to eliminate maintaining this file list as part of our move to the open. Sorry but this is something I feel strongly about not having.

**Comment by jaredpar** [comment]
Then the implementation is up to you. This is a case where CoreFx is going to deviate from the rest of the organization, without every trying the solution at all. Work and maintenance is on you. 

Got to say though this is very disappointing to see. The point of arcade is to unify our solution, not deviate. Kicking off the effort by deviating before trying is not a good start.

**Comment by weshaggard** [comment]
>Got to say though this is very disappointing to see. The point of arcade is to unify our solution, not deviate. Kicking off the effort by deviating before trying is not a good start.

Why is it that you guys don't want to try the approach that both core and aspnet are already using?

**Comment by jaredpar** [comment]
> Why is it that you guys don't want to try the approach that both core and aspnet are already using?

It doesn't meet the needs of our repositories:

- Declarative: need to understand the full set of artifacts that we sign. Having it be implicit has lead to numerous build authoring errors over the years. Making it declarative has eliminated those entirely.
- Local verification: developers need to be able to verify locally that signing is consistent. 
- Batch processing: a must for us to meet our throughput and reliability goals.

**Comment by markwilkie** [comment]
To update this thread, @jaredpar, @weshaggard, and I have agreed on the following requirements.  @maririos - please be sure and add these to the overall signtool requirement doc which is being created.

-	Signtool will (batch) sign from a manifest (list of files)
-	This manifest can be checked in  (explicit)
-	This manifest can be generated during the build  (implicit)

**Comment by weshaggard** [comment]
I like the idea of signing validation during both CI (currently don't do in corefx) and Official Builds (we do this) but I don't believe that requires a checked in file list it just requires the list of what we consider shipping bits, as you put it. That list is easily gathered from our builds today based on the project metadata. From there we can verify that all the files in our containers (msi's, vsix, nupkgs, etc) are in the list of shipping bits to be signed. 

We are planning to convert (or at least create a new) version of the signtool that is an msbuild task and ideally everyone would start using that version of the tool and the only pivot is how repo's decide they wish to pass in the list of files to it. That list can be a static json file as it is today (or perhaps a static file list in an msbuild props file), or it can generated as part of the build and passed to the tool. 

For the core repo's the plan will be for any shipping library we will produce a "<filename>.requires_signing" file next to the binary in the output which will contain it's strong name and cert ids. Then when we hit the signing phase we will gather all those require_signing files and produce the list of things we need to pass to the signing service.  For validation we will pass that list as well as a list of all our containers (mostly nupkgs) to the signtool task so it can validate that all assets we are going to ship are planned to be signed for CI, or are actually signed in the case of official builds.

**Comment by tmat** [comment]
Why are `.requires_signing` files needed? As I pointed out the set of files that need to be signed is given by the content of packages (NuGet, VSIX, etc.) that the repo produces. 

If each project that produces a shipping package outputs that package to an artifacts directory dedicated for shipping packages, while non-shipping packages are placed to a different directory, then the requirement is that all artifacts (the packages as well as the binaries contained in those packages) in the shipping directory must be signed.

The same logic can be applied to symbol publishing. All symbols contained in packages in the shipping directory must be published.

In addition, we would use the set of shipping packages found in the shipping directory for nuget repacking. NuGet repacking changes the per-build pre-release version of a NuGet package to a release version, which is readily available for publishing if we decide we need to publish the build. Roslyn (and other repos) use repacking since we don't know upfront which build is gonna be the final build. So we produce final packages for every build with extra information that tells us whether these packages can be published (i.e. whether they do not have pre-release dependencies).

**Comment by markwilkie** [comment]
@tmat - I like the fact that you had a good suggestion as to how further unification might be accomplished.  However, at the end of the day, I think this is an area where we can leave the decision up to the repo owner regarding if it's explicit or implicit.  The point of convergence is that the regardless the path - there's still a "manifest" of what should have got signed.

Is there something specific that you think blocks moving forward with the following?

- Signtool will (batch) sign from a manifest (list of files)
- This manifest can be checked in (explicit)
- This manifest can be generated during the build (implicit)

**Comment by tmat** [comment]
I don't think we disagree on the above bullet points. I'm just saying that if we structure the package output directory based on whether package is shipping or not we won't need the explicit manifest, nor we would need extra ".requires_signing" files. At that point I don't see why we wouldn't use implicit one in all repos.

I'm currently working on incorporating the package shipping/non-shipping classification into RepoToolset, since it's needed for NuGet and Symbol publishing. The publishing logic needs to know which packages are  shipping and which are not. The easiest way to do that, imo, is to separate them into directories during the build and let each project that produces a package decide to which directory to put the package (based on `<IsShipping>` property).

**Comment by markwilkie** [comment]
I see @tmat.  So you're saying that as part of the publishing work you're doing in repotoolset could potentially be used to determine what needs to be signed?

**Comment by tmat** [comment]
Exactly.

**Comment by weshaggard** [comment]
>I'm just saying that if we structure the package output directory based on whether package is shipping or not we won't need the explicit manifest, nor we would need extra ".requires_signing" files. At that point I don't see why we wouldn't use implicit one in all repos.

That is exactly what do today for our shipping packages and how we gather them to publish and validate. However one key missing piece of data is figuring out what strong name and certificate to use for a given binary. The certificate is generally the same but the strong name varies. If we can figure out a way to get all the necessary information (perhaps we could crack open the files and read the public key token to figure out the strong name) then I'm all for eliminating the requires_signing marker files as well. 

I think we still have to work out some of the details about unpacking/signing/repacking so I'm not sure if that approach will fully work but it is worth exploring. One thing we need to be careful with is that some binaries ship in multiple containers but today are only signed once if we move to a model of unpack/sign/repack then we may end up signing the same binary multiple times. That may not be that common and isn't the end of the world but something to keep in mind.

**Comment by tmat** [comment]
> perhaps we could crack open the files and read the public key token to figure out the strong name

I think that's a good idea. Let's try to read the strong name from the metadata.

>  One thing we need to be careful with is that some binaries ship in multiple containers but today are only signed once if we move to a model of unpack/sign/repack then we may end up signing the same binary multiple times. 

Absolutely. I believe the signtool has this built-in already. It calculates checksum of each artifacts to see if it matches the file that was listed in the .json.

**Comment by jaredpar** [comment]
@tmat 

> Absolutely. I believe the signtool has this built-in already. It calculates checksum of each artifacts to see if it matches the file that was listed in the .json.

Indeed this is the case. The tool itself primarily operates on checksums of artifacts for identity. The only time names are used is when printing out error messages to developers.

**Comment by JohnTortugo** [comment]
Closing this issue since the changes are now being tracked on this issue #396 and this PR #410 .
