### ISSUE TITLE
[Signing] Figure out how we want to use the sign prep tool in the validation pipeline

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5803]
As suggested by @jcagme, we should integrate the signing prep tool into the nightly validation pipeline. Based on a discussion with our joint-epic team, we should considering the following: 

- When the bits are signed, where do they go? 
  - Will we keep them to be reused when the release pipeline runs? Which then means we need to validate when things are already signed when the release pipeline runs to ensure we don't duplicate work already done. 
  - Do we want to toss them away? Or do we want to send them to a feed that we can clean up after the validation process is completed? 
- Will they be signed with the test certificate or the release certificate? 
  - If we sign them with the test certificate, then we cannot reuse these signed bits for the release process as noted in the bullet point above.

**Comment by missymessa** [comment]
In sign-prep, we're setting the dryRun parameter based on the validation parameter value, just not using it yet.

**Comment by chcosta** [comment]
Triage: no longer applicable
