### ISSUE TITLE
[darc/maestro++] Truncate PR description length to 4000 characters for azure devops repositories

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5811]
- [x] This issue is blocking 
This is blocking PRs from getting created in some azdo internal repos
- [ ] This issue is causing unreasonable pain

Maestro is having issues when trying to create PRs from the azdo mirrors in dotnet-runtime to dotnet-aspnetcore and dotnet-extensions because the PR length exceeds the hard limit of 4000 imposed by Azure DevOps.

We should truncate the PR description if it is longer than 4000 characters due to the large amount of dependencies that these repos have.

**Comment by mmitche** [comment]
I would not try and polish this too much (just truncate it).

**Comment by MattGal** [comment]
assigning to self and doing as this is blocking and I'm trying to get experience in the space.

**Comment by riarenas** [comment]
This was rolled out on 7/22
