### ISSUE TITLE
[QCR] Clean up helper code in release cli

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#5814]
Chad had some really good comments that we should look into and address on Aaron's PR to move the helper code into a library. We should try our best to refactor this code to make it better.

PR/Comments are here: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/9193

**Comment by jcagme** [comment]
Yeah totally!

**Comment by jcagme** [comment]
Assigning to me since I'll be working on both, the library and the CLI

**Comment by Tohron** [comment]
Link to PR:
https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/9535

**Comment by Tohron** [comment]
Merged
https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/953
