### ISSUE TITLE
[darc/maestro++] Pull Request actors got stuck after dns outage in 7/18

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5820]
- [ ] This issue is blocking 
Dependency updates not flowing when expected blocks consistent full product builds.
- [ ] This issue is causing unreasonable pain

Maestro is not opening all of the expected automated dependency update PRs. It looks like manually triggering them via darc opens the PRs.

We should understand why:

* these PRs are not opening.
* why nothing is getting reported by the error processor.

One simple example is the subscription from Arcade to arcade-validation that should trigger on every build that didn't fire since 7/18 until manually triggered this morning.

```
https://github.com/dotnet/arcade (.NET Eng - Validation) ==> 'https://github.com/dotnet/arcade-validation' ('master')
  - Id: d38dee0b-123f-41ce-84f5-08d65ee3ff76
  - Update Frequency: EveryBuild
  - Enabled: True
  - Batchable: False
  - Merge Policies:
    Standard
```

EDIT: This was found out to be caused by a dns outage in 7/18, which caused some in-progress dependency updates to get stuck. Once we rolled a new version of the service, the pending dependency updates got applied. We should find out why instead of reporting any errors, they just seemed to get stuck until something kicked them.

**Comment by markwilkie** [comment]
How often does this seem to be happening?

**Comment by riarenas** [comment]
All I know so far is that "some prs that should be there are missing" Once I make some progress understanding what is going on, I might be able to find past instances as well.

**Comment by riarenas** [comment]
I believe I have a local repro. I can't get this subscription to trigger by adding new builds to the general testing channel, but PRs get opened when I trigger it manually: 

```
https://github.com/dotnet/arcade (General Testing) ==> 'https://github.com/dotnet/arcade-validation' ('riarenas/try-repro-no-pr')
  - Id: ce2201f6-8284-4212-3dac-08d82e5d3fb0
  - Update Frequency: EveryBuild
  - Enabled: True
  - Batchable: False
  - Merge Policies: []
```

**Comment by riarenas** [comment]
As we finished today's deployment, https://github.com/dotnet/arcade-validation/pull/1647 was opened. It deals with the exact subscription I was investigating, and brought in some of the builds that were missing as of this morning.

**Comment by riarenas** [comment]
https://github.com/dotnet/core-eng/issues/10298 seems very similar to what happened here.

**Comment by riarenas** [comment]
Removed blocking tag as this was resolved after a rollout.

I haven't had luck getting this to repro locally, even after simulating a similar outage in my local environment. I don't see any of the PR actors showing the "No such host is known" exceptions that we saw in the production logs. 

I think this crashes only if the actors are in the middle of calculating dependency updates, and my local instance doesn't have enough data, so dependency updates are very quick. I'll introduce some delay to the updates and see if that makes any difference.

**Comment by riarenas** [comment]
I still haven't been able to repro this, moving to Tracking.

**Comment by riarenas** [comment]
It looks like expected PRs weren't opened this morning. Maybe Production is stuck again (again on a rollout day)

**Comment by riarenas** [comment]
I triggered the daily PRs, and trying to find why the automatic schedule didn't fire.

**Comment by riarenas** [comment]
The error triggering updates this morning is not related to this issue. I'll write another one shortly

**Comment by riarenas** [comment]
Closing for now. Too many things went wrong with Azure that weekend and I haven't been able to repro getting the actors stuck in this same state so I have nothing to keep the investigation going.
