### ISSUE TITLE
Detect when Arcade builds aren't being pushed to Arcade Validation in a timely manner

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5821]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Inspired by https://github.com/dotnet/arcade/issues/5820. Occasionally, new builds are not pushed to Arcade Validation, so the latest build won't be validated and instead, Arcade Validation will re-run the last build that it received. It's not immediately obvious that Arcade Validation isn't immediately updated with the latest Arcade until we're investigating promotion-worthy builds. 

We should have some kind of alerts that notify the .NET Eng Services team when a new build of Arcade is produced, put into the .NET Eng - Validation channel, but Arcade Validation hasn't been updated (let's say, in 30 minutes? an hour? something reasonable) so that we can investigate why it's "stuck". Think of this as a real-world scenario test for dependency flow.

**Comment by riarenas** [comment]
I don't think there's a real reason to single out these dependency updates. We have work underway to improve the issues that are opened in core-eng when a dependency update fails somewhere in the service.

**Comment by missymessa** [comment]
Because of how we're currently handling Arcade promotions, the goal would be to minimize the randomization of us (specifically you, Mitchell, and myself) when doing investigations as to why validation-for-promotion failed. If we know earlier in the stream of time that there's an issue with dependency flow, we can get that unblocked before MWF mornings when we're investigating the promotion-worthiness of the latest Arcade build. 

That said, if there's work already underway that will fulfill this request, then great! If not, I think it would be a worthwhile automated piece of functionality to have.

**Comment by riarenas** [comment]
I guess my question is:

Is there a reason to single this repo out from any other dependency flow issue? I'm leaning towards no.

**Comment by missymessa** [comment]
We COULD do alerts for all repos, however, I would imagine that the result would be a lot of noise when a problem happens and there are back-ups in several repos. My thought on only alerting on a single repo would be to reduce that kind of noise. But the primary reason is because Arcade Validation is Arcade's first stop along it's way to get out, and because of our current promotion process, identifying issues earlier in the validation process in a way that can be automated with reduce our randomization. 

My agenda for this request is more in regards to making validation for Arcade more efficient than only providing testing for dependency flow (however, it surely could be expanded to provide that support for more than just this repo). This isn't the first time we've seen dependencies get stuck going into Arcade Validation, so I'm trying to figure out a good solution for this problem aside from manually comparing the versions of Arcade that being validated on the runs of Arcade Validation to the ones that ran prior.

**Comment by garath** [comment]
Triage: A form of a solution for this is already happening in dotnet/core-eng#10076 (motivated by other work). Expect that will generally improve the situation, and may highlight additional areas for improvement. Will continue the conversation to address gaps as they are identified.
