### ISSUE TITLE
[maestro++] Implement code 'auto-merge info using the checks API' 

### ISSUE THREAD

**Issue by rokonec** [dotnet/arcade#5835]
- [x] based on work from #5764 implement related code changes
- [x] after all tests are implemented are passing, refactor code into final production quality

Related docs:
- https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/coding-style.md

**Comment by lwintjen** [comment]
The tests are passing, the refactoring has been done. The PR is waiting to be reviewed & merge.
