### ISSUE TITLE
[maestro++] Find and update documentation related to 'auto-merge info using the checks API' 

### ISSUE THREAD

**Issue by rokonec** [dotnet/arcade#5836]
Find and update related documentation describing new behavior of auto merge policy using checks API as oppose to timeline comments

**Comment by rokonec** [comment]
@mmitche Are there any documentation which need to be updated since we now using checks and not comments?

**Comment by mmitche** [comment]
There's nothing specifically about the comments that I can find. There are some places in Darc.md that mention merge policies but nothing about what effect they have on PRs.

The Maestro docs do need a bit of a rework. Darc.md should probably be renamed and made into DependencyFlow.md, with info about automation. Darc.md already has some.

**Comment by lwintjen** [comment]
I'm closing this issue since a [PR](https://github.com/dotnet/arcade-services/pull/1326) has been merged to solve this.
