### ISSUE TITLE
[maestro++] Plan and execute demo #1 of 'auto-merge info using the checks API'  for stake holders

### ISSUE THREAD

**Issue by rokonec** [dotnet/arcade#5837]
Prepare demo no. 1 for main stake-holders:
- Tomas Kapin
- Matt Mitchell

Goal of this demo is to get sign-off for user experience (look and feel) of new auto-merge behavior.

**Comment by sunandabalu** [comment]
I'm assuming you did not mean to tag issue #1 :)

**Comment by rokonec** [comment]
@tkapin Shall we still organize such demo? Or shall we simply ask Matt M to check how it works in production, so he can recommend some changes.

**Comment by tkapin** [comment]
I think the demo seems to be an overkill, just having a wiki page or two screenshots comparing the difference in the issue plus some informative text should be sufficient.

**Comment by tkapin** [comment]
I'm closing this one as the demo is not needed. What will be sufficient is some concise summary of what has been achieved during Loris' internship.
