### ISSUE TITLE
 [maestro++] Test and validate 'auto-merge info using the checks API'

### ISSUE THREAD

**Issue by rokonec** [dotnet/arcade#5838]
Manually test and validate final implementation. 

- [x] locally
- [x] on staging after PR is merged
- [x] on production after rollout

**Comment by tkapin** [comment]
@lwintjen What are the criteria for successfully passing this? Please elaborate on the test cases.

**Comment by lwintjen** [comment]
We would still need to test or approve (non exhaustive list of things that need to be tested or approved) : 
-  AllChecksSuccessful merge policy with other pending/failed check (such as build). The AllChecksSuccessful check should not be successful.
- The UI of the informations displayed for the merge policy checks.
- A PR with 1 or more pending/failed merge policy check(s).
