### ISSUE TITLE
Using Arcade to verify source-level compat instead of binary level in api versions

### ISSUE THREAD

**Issue by carlosscastro** [dotnet/arcade#5843]
Hello! This is more of a request for help than an issue. LEt me know if I should reach out through other avenue.

The Bot Framework SDK Team uses Arcade to verify binary level compatibility, and we want to currently change the kind of compat check. For that, let me define:

- Source level compatibility: users use 4.2.1 of my library and I can make changes as long as when they recompile, their code still builds and behaves in the same manner
- Binary level compatibility: Users use 4.2.1 of my library and when I release 4.2.2, they can jsut drop the dll and all will work just like before. 

# Binary compat break Example

```csharp
public interface IFoo {}
public class SomeFoo : IFoo {}

// somewhere else, this method exists in 4.2.1:
public class Bar
{
    public void Baz(SomeFoo foo) {}
}
```
If in 4.2.2, I were to change `Bar` to 

```csharp
public class Bar
{
    public void Baz(IFoo foo) {} //I Swapped SomeFoo -> IFoo
}
```

This change is, according to the definition above, a binary compatibility break, but not a source compatibility break.

# Source compat break example
I would be breaking source compatibility if I swapped for some other object, this would not compile when people upgrade.
public class Bar
{
    public void Baz(string foo) {} //I Swapped SomeFoo -> string
}

# Question

**We would like to use arcade only for source compatibility checks. We don't want to enforce binary level compatibility Is that possible to check with arcade?** 

Thanks!

**Comment by markwilkie** [comment]
This is compat for .NET?  Today source compat is done using testing does at each of the repos.  Could you explain a bit more what caused you wonder if Arcade could help?  That might help me in turn understand better...

**Comment by carlosscastro** [comment]
Thanks Mark!

Sure, let me explain in more detail. The .NET bot framework SDK, which is a set of .net libraries distributed through nuget, guaranteed binary compatibility, using the definition of binary level compat that I described above.

To catch issues, we used arcade in our build system, comparing each version to the previous version. Arcade detects these issues and fails the pull request, which is great!

Now, binary compatibility is too restrictive and we don't have that requirement anymore. So, we just plan to maintain source compatibility from now on. That is, new changes should not break consumer's code in terms of build and behavior. 

We use unit tests as one way of detecting source compatibility problems. However, we don't have 100% coverage and developers could change tests and twist things inadvertedly. With that in mind, we are looking to see if we can use arcade to enforce source level compat and be 100% certain that we are not breaking source backward compatibility -- this is our goal. We'll still lean on tests for the behavior aspect, but we are looking to use arcade to keep enforcing the non-breaking of the code public surface.

For example: If I have this code:

```csharp
public interface IFoo {}
public class SomeFoo : IFoo {}

// somewhere else, this method exists in 4.2.1:
public class Bar
{
    public void Baz(SomeFoo foo) {}
}
```
If I make this change in 4.2.2, I want no error because it is not a source level breaking change

```csharp
public interface IFoo {}
public class SomeFoo : IFoo {}

public class Bar
{
    public void Baz(IFoo foo) {} // changed to IFoo in 4.2.2
}
```
But I do wnat an error in this code change
```csharp
public interface IFoo {}
public class SomeFoo : IFoo {}

public class Bar
{
    public void Baz(string foo) {} // the code built on this method by users will be broken
}
```

I was wondering if there are any configs or changes I could do to arcade in order to check my code for backward compat at the level we are looking for. 

I know this is not the direct purpose of your development of arcade, but it has been amazingly helpful for us and I wish we could continue to use it. Happy to hop on a call over teams if that helps too. Thanks again for your response!

**Comment by markwilkie** [comment]
Based on what you're saying, it seems using arcade to build and the  .NET bot framework SDK to check for binary compat.  You'll need to find another way to check for source compat - arcade is mostly a build infra.  Usually, source compat is done by compiling and then testing....

**Comment by carlosscastro** [comment]
Thanks Mark, appreciate the insights.
