### ISSUE TITLE
[Signing] Signing.Extensions and sign-prep.yaml need to handle LightCommand scenarios (7/7)

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5852]
Another rough plan: 

1. Unzip the file
2. Find all (signable) the files
3. Create one <ItemsToSign> for each
4. Run your thing so things are signed
5. Run the light command to generate the MSI with signed stuffs
6. Publish/upload MSI

**Comment by missymessa** [comment]
Blocked on this until we can get a build that contains files that we can test this scenario against.

**Comment by markwilkie** [comment]
Who's working on getting the files?

**Comment by missymessa** [comment]
> Who's working on getting the files?

@jcagme and @jonfortescue are working on a solution for this.

**Comment by missymessa** [comment]
Going to break this down into smaller pieces.

**Comment by missymessa** [comment]
Okay, created the following issues to handle this: 
https://github.com/dotnet/core-eng/issues/10474
https://github.com/dotnet/core-eng/issues/10475
https://github.com/dotnet/core-eng/issues/10476
https://github.com/dotnet/core-eng/issues/10477
https://github.com/dotnet/core-eng/issues/10478
