### ISSUE TITLE
TargetFrameworks.Sdk doesn't stop on error when a P2P fails to build

### ISSUE THREAD

**Issue by safern** [dotnet/arcade#5867]
For example if we build `src\System.Runtime.csproj` which has a ProjectReference to `System.Private.CoreLib` and `System.Private.Uri` and `System.Private.Uri` also has a ProjectReference to `System.Private.CoreLib`. If `System.Private.CoreLib` fails to build with any error, then we will continue to build `System.Private.Uri` and since it references `System.Private.CoreLib` it will build it incrementally since it was already build, returning an empty output because it failed and the build will fail with a bunch of errors that System.Object, System.Int32, etc, types can't be found, hiding the real error which was a syntax error or something else in `System.Private.CoreLib`.

To Repro, just add a syntax error to `System.Private.CoreLib` and build `src\System.Runtime.csproj` in `dotnet/runtime`. 

Here is where we call MSBuild to build our P2Ps:
https://github.com/dotnet/arcade/blob/1a51bac5281a48e55d611e5cab7918f9e5a1a78f/src/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/src/build/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk.targets#L49-L58

We're passing `ContinueOnError=true`:
https://github.com/dotnet/arcade/blob/1a51bac5281a48e55d611e5cab7918f9e5a1a78f/src/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/src/build/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk.targets#L55

cc: @danmosemsft @ViktorHofer @ericstj @Anipik

**Comment by ericstj** [comment]
That just looks wrong.  We should never use `ContinueOnError`.
