### ISSUE TITLE
Document internal/public build flow

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5883]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Customers are often confused about the darc-int, darc-pub, etc. feeds. We should provide a relatively concise document on how we build and release from start to end, including info on internal releases, release day activities, etc.

**Comment by mmitche** [comment]
@wtgodbe Did we have any docs you wrote that may help out with this?

**Comment by jcagme** [comment]
Also, +@leecow

**Comment by wtgodbe** [comment]
I haven't written anything specifically on this topic, but I'm happy to help out after I'm done w/ RC1 feature work

**Comment by mmitche** [comment]
https://devblogs.microsoft.com/dotnet/a-deep-dive-into-how-net-builds-and-ships/
