### ISSUE TITLE
What desktop runtime do our tools require

### ISSUE THREAD

**Issue by jaredpar** [dotnet/arcade#59]
Looks like there will be a number of places where we need to specify a desktop target framework in our projects. This target framework essentially establishes the minimum desktop runtime necessary to use artifacts from the arcade repository. Rather than pick project per project think we should establish the minimum runtime we desire and use it consistently through our projects.

I believe we should use net461 for the following reasons:

1. Allows any utility libraries we write to target netstandard2.0. Choosing any lower desktop runtime means we have to use netstandard1.3.
1. It's present in over 97% of all window machines in existence. 
1. It's present in 99% of all windows machines which also install Visual Studio.

**Comment by weshaggard** [comment]
On a similar note we are going to have to move our task libraries up to target netstandard2.0 soon as with the 2.1 release the msbuild library packages will only support netstandard2.0 and net46.

**Comment by markwilkie** [comment]
tracking with #393
