### ISSUE TITLE
Create test project and add tests for Maestro.Task

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#5903]
There is no test project and hence no tests for Maestro.Tasks

- [x] Create a Test Design Document
- [x] Get Sign off from team on the Test Design Document
- [ ] Create a Test Project and write all the tests
- [ ] All Tests are run as part of PR's

Timeline (all dates by EoD):
Test Design Document written - 9/25
Test Design Document signed off - 9/28
Implement unit tests - ~10/26~ 12/1
Incorporate unit tests into PR pipeline - 10/15
Implement scenario tests - ~10/30~ 12/4

Test Plan Doc: https://github.com/dotnet/core-eng/blob/master/Documentation/Project-Docs/MaestoTask_TestPlan.md

High level test plan:

The logic is almost all in PushMetadataToBuildAssetRegistry, so that's where I'm going to focus. The only other file that does something worth testing is ManifestBuildData, the rest are either models, comparers, or launchers that contain 1-2 lines of code.

Refactor to use DI for testing:
Make any changes required to isolate the code in the class for unit testing (change methods to internal from private, add interfaces, etc where needed). I've only flagged a couple places, since I'm not familiar with the code I want to make sure I leave time for it in case I'm wrong. So far I think that I need to override GetEnv (which is used to get environnment strings for the class) & Local (which seems to be where a lot of the external stuff is called).

Unit Testing:
Add unit tests for each of the methods in PushMetadataToBuildAssetRegistry that do something more than return a string from environment variables. Most of these are small and just need some input checks, the bigger ones involve checking dependencies and will require some more extensive mocking.

Scenario Testing: Add a set of scenario tests for the public method (PushMetaDataAsync) with various configurations. I don't understand the code well enough to know exactly what those are, but I will by the time I get done with the unit tests.

Related PRs: 
- https://github.com/dotnet/arcade-services/pull/1333/

**Comment by adiaaida** [comment]
Moving to the signing epic, as it is related to the changes made to signing.

**Comment by missymessa** [comment]
@meganaquinn can you link your test doc/plan for this issue in the description of this issue? Thanks

**Comment by missymessa** [comment]
@meganaquinn and @Chrisboh: would it make sense to close this issue and create granular issues based on the items in the test plan doc Megan wrote? The dates JC noted in the original issue are probably not accurate anymore, and the test plan revealed that the amount of work needed for this is probably more than one issue should track.

**Comment by Chrisboh** [comment]
The dates in this issue are currently the same as my expectations of when this issue will be completed.  I don't have an opinion either way on how best your V-Team wants to track the work.

**Comment by missymessa** [comment]
This project was created and Megan broke down this issue into others to deal with the tests at a more granular level. Closing this issue.
