### ISSUE TITLE
Attempt to keep darc-int/darc-pub auto-inserted feeds from conflicting

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5909]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

When multiple dependency update PRs are opened against the same repo+branch and they all want to add darc-int/darc-pub feeds in about the same place in the nuget.config, meaning that when one merges, the other will conflict. Suggestion is perhaps that as we add new entries, we place comments around them, indicating the repo where they come from, and keep them in the same place over time.

**Comment by riarenas** [comment]
This is similar to what happens when entries in versions.props are around the same place for multiple dependency updates. batched subscriptions fixed that problem. Can the subscriptions that are seeing these merge conflicts be batched?

**Comment by mmitche** [comment]
Probably. @wtgodbe where do you usually see conflicts? 

We could also insert spacing, sorting, and comments to avoid conflicts. For instance:

```

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!-- Only specify feed for RepoToolset SDK (see https://github.com/Microsoft/msbuild/issues/2982) -->
  <packageSources>
    <clear />
    <!--Begin: Package sources managed by Dependency Flow automation. Do not edit the sources below.-->
    <!-- Package feeds from dotnet-core-setup -->
    <add key="darc-int-dotnet-core-setup-0c2e69c" value="https://pkgs.dev.azure.com/dnceng/_packaging/darc-int-dotnet-core-setup-0c2e69ca/nuget/v3/index.json" />

    <-- Package feeds from dotnet-corefx -->
    <add key="darc-int-dotnet-corefx-059a4a1" value="https://pkgs.dev.azure.com/dnceng/_packaging/darc-int-dotnet-corefx-059a4a19/nuget/v3/index.json" />
    <!--End: Package sources managed by Dependency Flow automation. Do not edit the sources above.-->

    <add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
    <add key="dotnet-tools" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" />
    <add key="dotnet3" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet3/nuget/v3/index.json" />
    <add key="dotnet3-transport" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet3-transport/nuget/v3/index.json" />
    <add key="dotnet3.1" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet3.1/nuget/v3/index.json" />
    <add key="dotnet3.1-transport" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet3.1-transport/nuget/v3/index.json" />
    <add key="nuget-build" value="https://dotnet.myget.org/F/nuget-build/api/v3/index.json" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="msbuild" value="https://dotnet.myget.org/F/msbuild/api/v3/index.json" />
  </packageSources>
</configuration>
```

So a little added spacing would help a little, but would still conflict sometimes. So you could also keep space for where feeds would be inserted. So if you no longer need the corefx feed, you remove it, but keep the comment and space after it for future insertions. The input repos stable in servicing, so after some time, you'd have a slot for each possible input repo.

**Comment by wtgodbe** [comment]
Aspnetcore & installer are the 2 most common places in 3.1. Namely, any repo that consumes 2 or more other repos which publish shipping packages

**Comment by mmitche** [comment]
Aspnetcore does batch their subs

**Comment by wtgodbe** [comment]
> Aspnetcore does batch their subs

Yes, but we still pretty frequently see separate PRs from EFCore & Aspnetcore-tooling
