### ISSUE TITLE
[Signing] Use DotNet Publishing pool for signing in dotnet-release

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5916]
Figure out what DotNet Publishing pool needs in order to support the signing scenario in dotnet-release. Work with the folks who are responsible for managing that pool to ensure we get the things we need. 

/cc @jcagme

**Comment by missymessa** [comment]
Emailed DDFun just now requesting help in adding support to the DotNet Publishing pool for certs required for Microbuild plugin. 

Moving this to tracking. Blocked on Signing progress until this is resolved.

**Comment by markwilkie** [comment]
If it's helpful, I'm pretty sure you can test sign w/o certs if you wanted to do a run through.

**Comment by missymessa** [comment]
Closing this as we are using a different pool. See #5944
