### ISSUE TITLE
[Signing] Add testing of signproxy.proj to Arcade Validation

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5918]
This. Needs. To. Be. Tested. 

https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/SignProxy.proj

**Comment by chcosta** [comment]
@missymessa can we close this?

**Comment by missymessa** [comment]
If we get rid of signproxy.proj in Arcade, yes. But if we're going to keep it, then this issue stands and it needs to be tested.

**Comment by chcosta** [comment]
Is anything else using it?  I thought that was just created for the post-build signing and that post-build signing isn't using it anymore

**Comment by chcosta** [comment]
oh, it's still in progress.  k

**Comment by missymessa** [comment]
No one else should be using it. But once we get the consolidated version of post build signing done, we can most likely remove it.

**Comment by missymessa** [comment]
We can close this once https://github.com/dotnet/arcade/pull/6285 is completed.

**Comment by missymessa** [comment]
Signproxy.proj is gone, so closing this issue.
