### ISSUE TITLE
Helix SDK DotNetCliRuntime does not support win-arm64

### ISSUE THREAD

**Issue by HaoK** [dotnet/arcade#5926]
When trying to use
```
    <IncludeDotNetCli>true</IncludeDotNetCli>
    <DotNetCliPackageType>sdk</DotNetCliPackageType>
```

We ran into issues with the correct version of the sdk not being installed on the windows arm64 queues.

See https://github.com/dotnet/arcade/pull/5734 for the workaround we are currently using.

**Comment by dougbu** [comment]
Since @pranavkm closed #5734, the current workaround is in dotnet/aspnetcore#24287. Would #5734 be the correct long-term fix❔

**Comment by premun** [comment]
@dougbu yeah, I would say that would do it if arm wasn't supported before like this

**Comment by dougbu** [comment]
@pranavkm suggest you reopen #5734 (I don't have permissions to do that.)
