### ISSUE TITLE
[Signing] Omit signed items from signing.props

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5927]
When the MergedManifest is built, it will identify items that are already signed (noted in the attribute of the element of the item in the MergedManifest). When Signing.Extensions comes across those items, they should be omitted when the signing.props file is built so we do not sign things that are already signed again. 

/cc @jonfortescue @jcagme

**Comment by chcosta** [comment]
https://github.com/dotnet/core-eng/issues/10167#issuecomment-696414508.  I *think* we can close this.  TBD based on feedback in the linked issue

**Comment by chcosta** [comment]
Triage: not applicable
