### ISSUE TITLE
[arcade 3.x] Newer versions of Arcade produced by the release/3.x branch are incompatible with newer .net sdks.

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5935]
- [X] This issue is blocking 
This is blocking any changes to the tasks in the release/3.x branch. So far it's blocking https://github.com/dotnet/arcade/issues/5487
- [ ] This issue is causing unreasonable pain

While working on https://github.com/dotnet/arcade/issues/5487 I had to produce a new version of Microsoft.DotNet.Build.Tasks.Feed and update arcade's 3.x branch to use that new version.

That new version of the task is causing publishing errors in repos subscribed to 3.x arcade, but using a newer version of the .net SDK.

**Success** Build using the minimum sdk that arcade 3.x enforces (3.0.101): https://dnceng.visualstudio.com/internal/_build/results?buildId=765409&view=results
**Failure** Build using latest released sdk (3.1.302): https://dnceng.visualstudio.com/internal/_build/results?buildId=765409&view=results
**Failure** Using a 3.1.4 preview (3.1.400-preview-015208): https://dnceng.visualstudio.com/internal/_build/results?buildId=759327&view=results

The error in the builds that fail to publish is:
```
\microsoft.dotnet.arcade.sdk\1.0.0-beta.20405.7\tools\SdkTasks\PublishArtifactsInManifest.proj(65,5): error : Method not found: 'System.Threading.Tasks.Task`1<Boolean> Sleet.PackageIndexFile.Exists(NuGet.Packaging.Core.PackageIdentity)'.
```

I'll revert the latest version upgrade, and sticking this in FR for investigation on how to unblock.

**Comment by riarenas** [comment]
Created a PR to revert the task version in use to the last known good: https://github.com/dotnet/arcade/pull/5936

**Comment by riarenas** [comment]
It looks like reverting the task version wasn't even enough. https://dev.azure.com/dnceng/internal/_build/results?buildId=766620&view=results failed with the same error after getting a new arcade with the reverted task version.

I'm getting a suspicion that this is not a problem with the task, but with Arcade itself. I'm promoting this to blocking, and adding the critical label, as it means newer versions of arcade produced by the 3.x branch and used by repos with a newer 3.1 dotnet SDK have broken publishing.

**Comment by ChadNedzlek** [comment]
Is this an assembly we own? If so, where does the code for it live?

**Comment by riarenas** [comment]
Sleet? I believe we use https://github.com/jcagme/Sleet but I'm not familiar with where it builds or where it ends up being published.

**Comment by ChadNedzlek** [comment]
@JohnTortugo Where does this build and where does it get published, and how I can we tell what versions go with which commits?

**Comment by ChadNedzlek** [comment]
@jcagme how does this think make it into the build system?  Where does it build? Where does it get published? How can I tell what version if being used and what source code that corresponds to?

**Comment by ChadNedzlek** [comment]
Apparently that assembly no longer exists? https://github.com/NuGet/NuGet.Client/commit/f7e4a189c85fc6cfcc2d3f6b3d94079125adfe91

**Comment by riarenas** [comment]
The change in arcade that precipitated this was https://github.com/dotnet/arcade/pull/5793. We are now building arcade using that SDK:

```
Stage 1: Build and create local packages
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.101/dotnet-sdk-3.0.101-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.101/dotnet-sdk-3.0.101-win-x64.zip
dotnet-install: Adding to current process PATH: "F:\workspace\_work\1\s\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.300

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
F:\workspace\_work\1\s\.dotnet\sdk\3.1.300\MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:F:\workspace\_work\1\s\artifacts\log\Release\ToolsetRestore.binlog /clp:Summary /clp:ErrorsOnly;NoSummary /nr:False /p:ContinuousIntegrationBuild=True /p:TreatWarningsAsErrors=true /p:__ToolsetLocationOutputFile=F:\workspace\_work\1\s\artifacts\toolset\1.0.0-beta.20221.2.txt /t:__WriteToolsetLocation /warnaserror F:\workspace\_work\1\s\artifacts\toolset\restore.proj

```

https://dnceng.visualstudio.com/internal/_build/results?buildId=765748&view=results

**Comment by ChadNedzlek** [comment]
Is that change important? It sounds like a pretty weak scenario... especially when the alternative is "fail to build everything everywhere"...

**Comment by ChadNedzlek** [comment]
K, we are going to hack like we've never hacked before to unblock this.  Opened https://github.com/dotnet/arcade/issues/6035 to track a more sustainable path.l

**Comment by ChadNedzlek** [comment]
Unblocking PR: https://github.com/dotnet/arcade/pull/6036

**Comment by ilyas1974** [comment]
Determined no forward path for sleet. See Issue #6035 for the work to remove sleet feeds from all affected repos.
