### ISSUE TITLE
Propagate CPD strict for remaining branches

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5940]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Propagate CPD strict for the remaining branches to prepare for enabling CPD strict by default.  To do so:

1. Go to branches below:
2. darc update-dependencies --strict-coherency --coherency-only
3. Follow instructions if it fails.

This should already be done for all .NET 5 branches

Will involve adding dependencies in some repos.
- [x] https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int @ master
- [ ] https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int @ release/3.1 (https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/10485)
- [ ] https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-test @ master (https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-test/pullrequest/10079)
- [ ] https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-test @ release/3.1 (https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-test/pullrequest/10080)
- [x] https://github.com/dotnet/aspnetcore @ release/3.1
- [x] https://github.com/dotnet/aspnetcore-tooling @ master
- [x] https://github.com/dotnet/aspnetcore-tooling @ release/3.1
- [x] https://github.com/dotnet/cli @ release/3.1.1xx
- [x] https://github.com/dotnet/cli @ release/3.1.4xx
- [x] https://github.com/dotnet/core-setup @ release/3.1
- [x] https://github.com/dotnet/ef6 @ release/6.4 (not really needed..no planned releases)
- [x] https://github.com/dotnet/efcore @ release/3.1
- [x] https://github.com/dotnet/extensions @ release/3.1
- [x] https://github.com/dotnet/installer @ master
- [x] https://github.com/dotnet/installer @ release/3.1.1xx
- [x] https://github.com/dotnet/installer @ release/3.1.4xx
- [x] https://github.com/dotnet/sdk @ master
- [ ] https://github.com/dotnet/source-build @ master
- [ ] https://github.com/dotnet/source-build @ release/3.1
- [x] https://github.com/dotnet/toolset @ release/3.1.1xx
- [x] https://github.com/dotnet/toolset @ release/3.1.4xx
- [x] https://github.com/dotnet/windowsdesktop @ master
- [ ] https://github.com/dotnet/winforms @ release/3.1 (https://github.com/dotnet/winforms/pull/3988)
- [x] https://github.com/dotnet/wpf @ master
- [x] https://github.com/dotnet/wpf @ release/3.1

**Comment by riarenas** [comment]
We should have an issue so that CPD strict is the default going forward.
