### ISSUE TITLE
[Signing] Cannot use DotNet Publishing for signing in dotnet-release

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5944]
The DotNet Publishing pool does not support the Microbuild plugin that is required for signing. Until there is a pool available for us to use for this project that has all the things on it that we need to support this scenario, we are going to do what we can to unblock ourselves. 

The current plan will be the following: 
- prep ring uploads shipping and nonshipping to a "to-sign" artifacts container
- signing stuff downloads these files and works on them
- when done:
  - does the file replacement in vsufile
  - uploads signed stuffs to the "drop" artifacts container

**Comment by jcagme** [comment]
I'll follow up with @ilyas1974 to know how hard would it be to have a pool with the same characteristics + Microbuild on dnceng

**Comment by missymessa** [comment]
Ilya and John got us a queue that will work for our purposes.

**Comment by missymessa** [comment]
The dotnetcore-windows pool works for our needs. Signing was able to get files from the share directory and perform signing: https://dnceng.visualstudio.com/internal/_build/results?buildId=769835&view=logs&s=58e52f8f-15ca-57a7-0b53-b259834939b5&j=f0eb847b-dc3a-5c41-fdf6-7b21e1229821

**Comment by missymessa** [comment]
PR here: https://dnceng.visualstudio.com/internal/_git/dotnet-release/pullrequest/9769

**Comment by missymessa** [comment]
PR closed. Closing this issue.
