### ISSUE TITLE
[darc/maestro+++] Add the changes in repos to the dependency updates PRs  

### ISSUE THREAD

**Issue by lwintjen** [dotnet/arcade#5961]
The dependency updates PRs do not currently have the changes in the different repos accessible (you have to get the sha of the old and new versions and then go to the link : https://www.github.com/dotnet/arcade/compare/{old_sha}..{new_sha}) which is annoying.

After some investigation, we decided to add these information within the body of the initial comment by maestro. It will look like this :
![image](https://user-images.githubusercontent.com/43049559/90254399-f4884300-de42-11ea-92be-128ecb73557b.png)

It should use link references (like [this][1]) to save overall length of PR body, as it gets, on azdo workflow mainly, close to its limits

[1]: http://get.me.there/

Also it has to support both AzDO and GitHub workflows.

**Comment by MattGal** [comment]
@lwintjen  if you're working on this issue, can you self-assign it?

**Comment by lwintjen** [comment]
The PR has been merged to the staging, waiting to be in the next rollout.
