### ISSUE TITLE
[Signing] SignProxy should be a no-op if there is nothing to sign

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5962]
To prevent the Stage-DotNet pipeline from breaking until repos have onboarded to the new process of post-build signing, we need to ensure that if there are no files to sign (because a mergemanifest wasn't generated, or signinginformation wasn't available) that the sign proxy step in sign-prep is a no-op.

**Comment by chcosta** [comment]
can we close this?

**Comment by missymessa** [comment]
Once we pull the usage of SignProxy out of the pipeline, we can close it. We haven't finished the work to consolidate it, yet.

**Comment by missymessa** [comment]
No longer using SignProxy for post build signing. Closing this issue.
