### ISSUE TITLE
Add signing to prep contract

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#5968]
Once signing is 100% running (including all the copying and stuff), add a call to create-step-subcontract.yml for signing, and update the prep contract with the expected output

**Comment by meganaquinn** [comment]
This can't be done until the new yaml is in, but when we get to that point I know what to do. :)
The info will be here once it's checked in (soon, relevant section is Step Outputs):
https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=%2Fdocumentation%2Frelease-contracts.md&version=GBmain&_a=preview

**Comment by missymessa** [comment]
@adiaaida says we need to handle the BuildLogs folder for signing as a part of this issue.

**Comment by missymessa** [comment]
Before we close down this epic, let's check with @adiaaida to see if we need to migrate this issue to another epic or can close it.

**Comment by adiaaida** [comment]
I'm ok with moving this to the Shipping with Confidence epic, as I am already implementing it as part of https://github.com/dotnet/core-eng/issues/11233
