### ISSUE TITLE
dotnetfeed.blob.core.windows.net ignores query parameter

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/arcade#5978]
I'm trying to fetch first 10 packages from dotnetfeed.blob.core.windows.net using the following url: https://dotnetfeed.blob.core.windows.net/dotnet-core/search/query?q=&skip=0&take=10&prerelease=true&semVerLevel=2.0.0
It seems that the server ignores query parameters and always return metadata of all available packages (225MB json):
<img width="801" alt="2020-08-18_17-29-28" src="https://user-images.githubusercontent.com/2259237/90525997-86ac8600-e178-11ea-9fd5-1914690a55ff.png">

In Visual Studio, it leads to a very strange paginator behavior that displays the first bunch of packages on each page:
![vs](https://user-images.githubusercontent.com/2259237/90526301-e571ff80-e178-11ea-8f9d-d91f5296e939.gif)

When I try to fetch the first 10 packages using the [NuGet.Client](https://github.com/NuGet/NuGet.Client) 5.5 API, it also allocates ~3GB of JSON objects in the managed heap.

**Comment by MattGal** [comment]
That's just plain Azure blob storage; its query parameters are not something we can change.

**Comment by garath** [comment]
Saying a bit more, this feed is hosted using [Sleet](https://github.com/emgarten/Sleet) in Azure blob storage. Unfortunately it does not support the query parameters and instead sends the entire index. (We've been opportunistically moving infrastructure feeds like this to the much smarter Azure Artifacts, but this one hasn't seen that migration yet.)

Closing this issue, but happy help you get whatever you're looking for from the feeds.

**Comment by MattGal** [comment]
> @MattGal @garath thanks for the answer. I have two more questions:
> 
> 1. Is there a "light" way to automatically detect such NuGet feeds that don't support query parameters (before the first call to the search API).

Sort of.  
- If it doesn't come from nuget.org,  myget.org, or azure devops, it's almost always going to be a sleet feed.  
- Any feed that starts with the string `dotnetfeed*.blob` (there are a few variants we use) will be Sleet, therefore just being a storage account only supporting the query parameters of Azure Blobs.

> 2. Should I report this problem somewhere else? The `https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json` NuGet feed is used in many open-source projects and it affects IDE experience, so it would be nice to fix it somehow.

Sleet can't be changed this way by definition of what it is. It is, however, not the state-of-the-art; we are working towards using Azure Devops feeds for most of our feeds other than what shows up on nuget.org.

**Comment by AndreyAkinshin** [comment]
@MattGal thanks for the information!
