### ISSUE TITLE
Arcade failing to publish to ".net eng - validation" channel

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5995]
- [X] This issue is blocking 
Arcade official build blocked
- [ ] This issue is causing unreasonable pain

Fallout from https://github.com/dotnet/arcade/commit/fe78432fbfa38368ca16d78e9b29c475c2050e44

Build promotion pipeline is failing when triggered via an arcade official build: https://dnceng.visualstudio.com/internal/_build/results?buildId=777232&view=results

Error:
```
 You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  Creating a task to publish assets from D:\a\1\a\AssetManifests\Windows_NT-AnyCPU.xml
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20417.6\tools\SdkTasks\PublishArtifactsInManifest.proj(97,5): error : The property TargetFeedConfig is required but doesn't have a value set.
##[error].packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20417.6\tools\SdkTasks\PublishArtifactsInManifest.proj(97,5): error : (NETCORE_ENGINEERING_TELEMETRY=Publish) The property TargetFeedConfig is required but doesn't have a value set.
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20417.6\tools\SdkTasks\PublishArtifactsInManifest.proj(97,5): error : Missing required properties. Aborting execution.
##[error].packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20417.6\tools\SdkTasks\PublishArtifactsInManifest.proj(97,5): error : (NETCORE_ENGINEERING_TELEMETRY=Publish) Missing required properties. Aborting execution.
```

**Comment by riarenas** [comment]
FYI @epananth

**Comment by dagood** [comment]
Asking just because some of my changes are blocked by this, I think, and I'm not familiar with how these issues are handled here--not to push on it particularly:
* Any idea how long this will take to fix?
* Can the break be reverted until the change is validated?
* Who is working on this?

**Comment by riarenas** [comment]
> Any idea how long this will take to fix?
@epananth should have an estimate once she takes a look
>Can the break be reverted until the change is validated?
My preference is on reverting the changes related to v3 too, unless it's an obvious thing that was missed. (There were already two merge errors with the PR, I wonder if this is just more of them)
> Who is working on this?
Should be @epananth.

**Comment by epananth** [comment]
Publishing.props is a mandatory file now for V3 publishing, and that is missing. That's the reason this is broken. I'm testing my changes now. Another hour I should have it merged.

**Comment by epananth** [comment]
Test build with the fix currently running here ->https://dnceng.visualstudio.com/internal/_build/results?buildId=778573&view=results

**Comment by epananth** [comment]
Merged my changes, this is the build -> https://dnceng.visualstudio.com/internal/_build/results?buildId=778994&view=results

**Comment by riarenas** [comment]
This was fixed.
