### ISSUE TITLE
[Darc] Create process for auto-updating common scripts/tools

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#60]
No matter what tools/infra we currently use there is always a need for some boiler-plate scripts, config files, etc that need to be maintained across many repos. Today that is mostly manual and is a very tedious process to ensure everything is in-sync and consistent. We need some process, perhaps maestro, that will monitor changes to common files and then submit auto-PRs to all repo's that subscribe to the engineering system.

We have issue https://github.com/dotnet/buildtools/issues/1709 tracking a similar feature but I think this is going to be key for getting people to arcade and keeping them updated so I've filed the issue here.

Some general requirements:
1. Any auto-updated files should be blindly updated by this tool and never have any customizations from the individual repos. If customizations are needed then it should be handled by an extension point where repo owners can plug into from a separate file. 
2. These files should be in well known locations in each repo so the updating is just a simple overwrite. 
3. We may need the flexibility in the system to move files if we decide we need to rename or move a file for some reason.

**Comment by jcagme** [comment]
Included in https://github.com/dotnet/arcade/issues/296
