### ISSUE TITLE
Update publishing docs 

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6004]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Our publishing docs should be updated to contain (or verified that they contain):
- [ ] Behavior of v1, v2, and v3 publishing
- [ ] How v3 (non-inline) publishing is verified and updated (updates of the publish branch)
- [ ] How v3 (non-inline) publishing can be tested

**Comment by riarenas** [comment]
@epananth one more duplicate publishing documentation issue, let's coalesce these into a single one.

**Comment by epananth** [comment]
closing this as its a duplicate of -> https://github.com/dotnet/core-eng/issues/10629
