### ISSUE TITLE
[Helix SDK] Support installing specific .NET SDKs **and** runtimes

### ISSUE THREAD

**Issue by dougbu** [dotnet/arcade#6005]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Many repos specify .NET runtimes in their global.json files to ensure they're building against the latest before new SDKs are available. The Arcade SDK handles this pretty well (at least given .NET SDK restrictions around extending a globally-installed SDK ☹️).

But, the Helix SDK has no similar feature. For the dotnet/aspnetcore repo, this means we can only use the Helix SDK to install the .NET SDK. We then have to call `dotnet-install` ourselves and, on Linux, hack things together using symbolic links. We would not be testing against the latest dotnet/runtime bits otherwise.

The problem is the Helix SDK's .NET installation features are either / or: Either we ask the Helix SDK to install a .NET SDK _or_ we request a .NET runtime. This issue is about adding an **and** option.

**Comment by garath** [comment]
Triage: @dougbu How soon would you need this feature?

**Comment by dougbu** [comment]
We have workarounds for the readonly SDK install location but it's a hack and @HaoK hasn't checked it in yet. See dotnet/aspnetcore#24287. This is about reducing the lifetime of that hack. So, sooner is better but not absolutely required.

**Comment by dougbu** [comment]
This may be more urgent given concerns about flooding CDNs with requests from dotnet/aspnetcore's Helix work items. /cc @Pilchie
