### ISSUE TITLE
How to configure helix work items based on test assembly name

### ISSUE THREAD

**Issue by smitpatel** [dotnet/arcade#6008]
In EF Core repo, we are running helix job through a proj file. We also utilize built-in xunit test runner functionality from helix SDK.
This is how we select test projects to run
```XML
  <ItemGroup>
    <XUnitProject Include="$(RepoRoot)/test/**/*.csproj"/>
    <XUnitProject Remove="$(RepoRoot)/test/EFCore.Specification.Tests/*.csproj"/>
    <XUnitProject Remove="$(RepoRoot)/test/EFCore.Relational.Specification.Tests/*.csproj"/>
  </ItemGroup>
```
This is how we configure the work items
```XML
  <PropertyGroup>
    <HelixPreCommands Condition = "'$(HelixTargetQueue.StartsWith(`Windows`))'">$(HelixPreCommands); SqlLocalDB start</HelixPreCommands>
    <XUnitPublishTargetFramework>netcoreapp5.0</XUnitPublishTargetFramework>
    <XUnitRuntimeTargetFramework>netcoreapp2.0</XUnitRuntimeTargetFramework>
    <XUnitRunnerVersion>2.4.1</XUnitRunnerVersion>
    <XUnitArguments></XUnitArguments>
    <XUnitWorkItemTimeout>00:30:00</XUnitWorkItemTimeout>
  </PropertyGroup>
```

We need to set certain pre commands and specific helix target queue for a specific test assembly. In order to write condition for that how do I get value of test assembly? 
e.g.  In order to start SqlLocalDB through pre command only when running SqlServer.FunctionalTests
```XML
<HelixPreCommands Condition = "'$(XUnitProject.Name.Contains(`SqlServer.FunctionalTests`))'">$(HelixPreCommands); SqlLocalDB start</HelixPreCommands>

**Comment by alexperovich** [comment]
There currently isn't any way to do this easily without writing a target. I will see if I can add this support.

**Comment by alexperovich** [comment]
https://github.com/dotnet/arcade/pull/6010
