### ISSUE TITLE
[darc/maestro++] Make the publish to BAR process independent from CI files

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#601]
Currently we push to the Build Asset Registry by adding extra phases to `base.yaml` and `.vsts-ci.yaml` along to other files which are required to perform the push.

We could change the current functionality of the `PushToBlobFeed` task and instead of creating a file which will be uploaded to the build artifacts (with a new phase in `base.yaml`), upload the file to something like Azure blob storage where the build_id+repo_name will be the container name. At this point we don't know if the build will succeed or not.

Once **all** the legs have succeeded we would call something like an Azure Function that will group the uploaded manifests and push the data to the registry.

**Comment by markwilkie** [comment]
Next steps:
- Work with VSTS to determine the right feature to enable a "finalize" step as a first class citizen
- For now, import a common yml which lives in 'eng' which does the publish to BAR
- Also, look further into making some of these tasks executable as command line tools

**Comment by jcagme** [comment]
This will be converted in an Azure DevOps tasks as described here https://github.com/dotnet/arcade/blob/master/Documentation/Projects/DevOps/Tasks/OnePager.md#task-candidates

**Comment by markwilkie** [comment]
The reality is that we're just not going to ever do this - especially given the move to GH actions.
