### ISSUE TITLE
Update XUnitRunnerVisualStudioVersion

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#6019]
Older version of xunit.runner.visualstudio cannot work on the latest dotnet core. https://github.com/dotnet/core/pull/5035/files

Could you update the XUnitRunnerVisualStudioVersion to 2.4.3

**Comment by wli3** [comment]
cc @nohwnd @dsplaisted

**Comment by dsplaisted** [comment]
@dotnet/dnceng

**Comment by lpatalas** [comment]
@wli3 Thanks for the report. We'll take care of this.

**Comment by lpatalas** [comment]
Looks like there's already a PR for it: https://github.com/dotnet/arcade/pull/5908. We'll try to merge it soon.

**Comment by lpatalas** [comment]
Th PR linked above was merged yesterday so I will close this issue.
