### ISSUE TITLE
Use (newish) 1ES data to help with reliability numbers (and maybe more)

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#6023]
Michael Simons did some good work that could serve as an example of how we might use the 1ES data.  Here is his email:

==============

Hi Mark,

Here is a recap of some work I’ve been doing to analyze the amount of compute being used by the .NET Docker builds.

Problem:
TLDR; We want to identify how much compute our builds are using as a way to measure the effectiveness of a feature we working on (https://github.com/dotnet/docker-tools/issues/186).

In the .NET Docker space it is critical that we share as many Docker layers as possible and limit the number of times an image gets rebuilt.  In preparation for the 5.0 release, we are working on a build caching mechanism so that we can share the runtime-deps images between 3.1 and 5.0.  The runtime-deps images contain the native dependencies required to run a .NET app on Linux.  As I thought about this feature, it made me think that we could benefit from this work in other ways.  Mainly it could be utilized to reduce the number of times we rebuild images in our nightly repositories.  The nightly Docker repositories get rebuilt “nightly” whenever there has been a new build of the product.  I speculate this is costing us a fair amount but have no data to back this up.

Solution:
A new Compute Usage page was added to the .NET Docker Metrics Power BI report.  This page shows the amount of compute used per month broken down by Docker repository, OS platform, and build type (Official build/PR Validation).

The following Kusto query is the source of the data for this page.
let dotnetBuilds = datatable(DefinitionId:long, ProductFamily:string, BuildType:string)
[
  359, "core-nightly", "Official Build",
  373, "core", "Official Build",
  376, "core-samples", "Official Build",
  372, "fx", "Official Build",
  374, "fx-samples", "Official Build",
  453, "core-nightly", "PR Validation",
  387, "core", "PR Validation",
  739, "core-samples", "PR Validation",
  454, "fx", "PR Validation",
];
alias database["AzDO"] = cluster("https://1es.kusto.windows.net").database("AzureDevOps");
database("AzDO").BuildTimelineRecord
    | join kind=inner (
        database("AzDO").Build 
        | join kind=inner dotnetBuilds on DefinitionId
        | where OrganizationName == "dnceng"
        | distinct *
        | project OrganizationName, BuildId, ProductFamily, BuildType, BuildStartTime=format_datetime(StartTime, 'yyyy-MM')
    ) on OrganizationName and BuildId
    | where State == 'completed' and Type == "Task"
    | extend Duration = FinishTime - StartTime
    | extend Platform = iff(WorkerName hasprefix "DDVSOLINUXAGE" or WorkerName hasprefix "ubuntu" or WorkerName hasprefix "ddvsotx" or WorkerName hasprefix "Azure Pipelines", "linux",
        iff(WorkerName hasprefix "DDVSOWINAGE" or WorkerName hasprefix "dotnetdoc" or WorkerName contains_cs "dock", "windows",
        "unknown"))
    | summarize TotalDuration = sum(Duration) by WorkerName, Platform

Learnings/Observations:

1.	The data model was fairly easy to work with.  It didn’t take me long to find the data I was looking for.
2.	I was concerned that my final query would timeout and therefore limit my ability to present the data in Power BI with filtering but it turns out to be fairly fast
3.	I didn’t realize at first but the Build table includes duplicates.  It took me a while to realize this.  This was skewing my data a lot.  Others should be aware of this.
4.	It was important that I could distinguish the amount of compute between linux/windows.  I feel like this could have been easy to figure out.  The BuildTimelineRecord table I was using contained a WorkerName column which appears to be the build Agent name.  There is a Pool and PoolAgent table but I couldn’t find any entries for the pools we use in dnceng.  In fact, I couldn’t find any entries for the dnceng organization.  I was hoping to use the build agent properties to retrieve the OS type.  To work around this I defined my own hard coded fuzzy mapping between the build agent names (e.g. WorkerName) and OS platform type.
5.	I decided to define static table containing the ids of the build defs I was interested in along with some additional metadata used to filter on.  This would not be feasible for a more holistic view of the data.

-Michael

**Comment by ChadNedzlek** [comment]
I'm not sure what the work is here. The database exists, is super useful... but what work is there?

**Comment by missymessa** [comment]
Might be able to be calculated when we track how much retries cost us.

**Comment by missymessa** [comment]
Closing this issue. We know this data exists in the even that we need it.
