### ISSUE TITLE
Push VS.Redist.* packages to VS feed

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6028]
During the prep stage of releases, after signing is complete, we need to push the VS.Redist packages to the VS feed.

The issue is that today, this is done in-build for a lot of repos. But because these are used to VS insertion, they need to have signed bits in them. So when we move signing out of the build, these steps will pushed unsigned unsigned packages, which of course can't be inserted into VS. So, the prep stage needs to sign the packages, then push anything VS.Redist.*.nupkg to the VS feed.

**Comment by jcagme** [comment]
Moving this to the signing Epic since this work is related to that

**Comment by jcagme** [comment]
So we need to remove https://github.com/dotnet/arcade/blob/master/eng/common/templates/post-build/post-build.yml#L547-#L575? Are VS.Redist.* packages going to the following feeds?

transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools-transport/nuget/v3/index.json'
shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json'
symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools-symbols/nuget/v3/index.json'

**Comment by mmitche** [comment]
Publishing can stay the same for the VS.Redist packages in the sense that they should be treated like any other package for publishing.  Today there are explicit publish steps within some builds, e.g. https://dev.azure.com/dnceng/internal/_build/results?buildId=806350&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc&t=e6eb9397-ba71-59b2-f76c-d069fa554d12, that push to the VS feed.

**Comment by jcagme** [comment]
Change has been made in the pipeline. We need to change repos so this step is constrained by the use of a `PostBuildSign` variable or something similar. We need make the change in the following repos:

- [x] WindowsDesktop - https://github.com/dotnet/windowsdesktop/pull/1094
- [ ] AspNetCore

**Comment by jcagme** [comment]
@mmitche I checked the other repos and looks like the above repos should be all. Do you know about any other?

**Comment by mmitche** [comment]
Not that I know of.
