### ISSUE TITLE
Consider removing the sleet feeds in 3.1.x servicing prior to doing the v1 -> v3 publishing conversion

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#6035]

**Comment by mmitche** [comment]
Repos that take 3.x, publish, and then downstream repos would no longer get packages (they don't pull from dotnet3.1 or 3.1-transport):

- [ ] https://github.com/dotnet/toolset @ release/3.1.3xx needs 3.1
- [ ] https://github.com/dotnet/toolset @ release/3.1.4xx needs 3.1
- [ ] https://github.com/dotnet/source-build @ release/3.1 needs 3.1
- [ ] https://github.com/dotnet/source-build @ release/3.1 needs 3.1-transport
- [ ] https://github.com/dotnet/toolset @ release/3.1.2xx needs 3.1
- [ ] https://github.com/dotnet/toolset @ release/3.1.1xx needs 3.1
- [ ] https://github.com/dotnet/sdk @ release/3.1.2xx needs 3.1
- [ ] https://github.com/dotnet/sdk @ release/3.1.2xx needs 3.1-transport
- [ ] https://github.com/dotnet/sdk @ release/3.1.1xx needs 3.1
- [ ] https://github.com/dotnet/sdk @ release/3.1.1xx needs 3.1-transport
- [ ] https://github.com/dotnet/winforms @ release/3.1 needs 3.1
- [ ] https://github.com/dotnet/winforms @ release/3.1 needs 3.1-transport

**Comment by ChadNedzlek** [comment]
Working on writing a script to automate this...

**Comment by ChadNedzlek** [comment]
All PR's in all the repos are created.

**Comment by ilyas1974** [comment]
@ChadNedzlek/ @mmitche can you update this thread with the ETA on when we can do this work.

**Comment by mmitche** [comment]
All the work is staged.  @wtgodbe will know when it can be checked in (when we are spinning october builds)

**Comment by epananth** [comment]
Most of the created PRs are merged. For the ones that are not, no need to manually merge the PRs created, it will get merged in the next servicing cycle. (Coherency QB will handle this)

**Comment by epananth** [comment]
Closing this one cos all the PRs created will be closed during servicing.
