### ISSUE TITLE
[Signing][LC] Refactor WixToolsDir usage to explicitly set the directory from upstream projects

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#6038]
We want to be able to explicitly define the location of WixToolsDir so that we know where the toolset will be installed to so that we know the directory to add to the path without having to programmatically search for it. 

Suggested: 

In: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk/targets/windows/wix.targets#L40

Change to: 
`<WixToolsDir Condition="'$(WixToolsDir)' == ''">$(IntermediateOutputRootPath)WixTools.$(WixVersion)/</WixToolsDir>`

Once this is made available, in the sign-prep.yml in dotnet-release repo, we can refactor the installwix.proj call to use the following: 
`dotnet msbuild eng/installwix.proj /bl:$(Build.SourcesDirectory)/artifacts/logs/installwix.binlog /p:WixToolsDir=$(Build.SourcesDirectory)/artifacts/toolsets/wix`

And then refactor the subsequent powershell tasks to use that explicit directory in the path instead of searching for the location of `light.exe`

**Comment by jkoritzinsky** [comment]
This should also be considered for the Microsoft.DotNet.Build.Tasks.Installers package with the opt-in targets from #5714

**Comment by chcosta** [comment]
This is no longer applicable, as the current implementation does not require searching for the wix installation location, it is populated during the project's build.
