### ISSUE TITLE
[QCR] Staging pipeline should update build name to include identifying info

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6042]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Right now it's really hard to identify which build is for which release in the staging pipeline. The build name is just the dotnet-release commit title. Instead, it would be useful to list....maybe the last few couple of the path that it's dropping to, along with the bar build ids?

**Comment by adiaaida** [comment]
Do you mean like this:
![Screen Shot 2020-08-26 at 10 18 46 AM](https://user-images.githubusercontent.com/9666644/91335645-89653780-e785-11ea-9290-ac4ea4a0a0b8.png)
?
