### ISSUE TITLE
GetLastCommitShaAsync should look for UnprocessableEntity in status messages

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6044]
When GetLastCommitShaAsync looks to see if there is a last commit for a branch, the github API returns an UnprocessableEntity status code when the branch does not exist, rather than NotFound, which is what GetLastCommitShaAsync assumes. 

We need to update the function to also look for UnprocessableEntity, as well as update ExecuteAsync to add UnprocessableEntity as a stopRetriesHttpStatusCode.

/cc @mmitche

**Comment by garath** [comment]
Important, and @adiaaida confirms she is working on it.
