### ISSUE TITLE
darc should stage templating packages in publish_files dir

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6048]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The templating packages are not currently getting pushed to nuget.org, but they should.

This is the block that needs to change: https://github.com/dotnet/arcade-services/blob/9684e0d9281b174e39c3e399f8e8ef623d8c19de/src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs#L336-L396

After that, the templating packages will appear here: \\vsufile\patches\sign\NET\CORE_BUILDS\5.0.X\5.0.0\5.0.100-preview.8.20417.9\publish_files\nuget

**Comment by wtgodbe** [comment]
👁️

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade-services/pull/1378

**Comment by riarenas** [comment]
This was rolled out.
