### ISSUE TITLE
[Infra] Show dotnet-install progress

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/arcade#6057]
On an average internet connection, running Restore.cmd will take a relatively large time to download the required version of the .NET SDK.

```
D:\dotnet\Roslyn>Restore.cmd
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.7.20366.6/dotnet-sdk-5.0.100-preview.7.20366.6-win-x64.zip
```

I think it's a better experience of a progress or something is shown.

- https://stackoverflow.com/questions/21422364/is-there-any-way-to-monitor-the-progress-of-a-download-using-a-webclient-object
- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-progress?view=powershell-7

These links might be relevant.

**Comment by garath** [comment]
@bozturkMSFT This sounds like your team. Where would you like this issue moved to?

**Comment by dagood** [comment]
The install scripts are over at https://github.com/dotnet/install-scripts now, probably the right place.

**Comment by bozturkMSFT** [comment]
https://github.com/dotnet/install-scripts is the correct place for install script related issues (I don't have the permission to move it myself). Thanks.

**Comment by riarenas** [comment]
Issue moved to [dotnet/install-scripts #77](https://github.com/dotnet/install-scripts/issues/77) via [**ZenHub**](https://www.zenhub.com/)

**Comment by riarenas** [comment]
I wasn't able to transfer it using Github's feature, but Zenhub's worked. dotnet/install-scripts#77
