### ISSUE TITLE
Support `-noPath` in `InstallDotNet` function

### ISSUE THREAD

**Issue by dougbu** [dotnet/arcade#6060]
- [x] This issue is blocking aspnetcore's merge from preview8: dotnet/aspnetcore#25280
- [ ] This issue is causing unreasonable pain

The dotnet/aspnetcore repo needs the latest runtime for some tests that run in Helix. We prefer to use the `InstallDotNet` function for this purpose because it supports private runtime feeds and we had too much custom infrastructure around the installation already.

Unfortunately, invoking dotnet-install.ps1 extends the `$env:Path` default system-wide unless `-noPath` is on the command line. The `InstallDotNet` function does not current support including that command-line argument. Please either add a `$noPath` parameter or (more generally) support the initial `$installParameters` value as a parameter.

**Comment by dougbu** [comment]
Not sure if this is appropriate as a FR issue but /cc @ilyas1974 just in case. Without this, we'll regress dotnet/aspnetcore#23575 and need dotnet/core-eng#10578 sooner. The other option is for us to leave that code behind in preview8, limp along w/ our custom infrastructure until we do a 5.0 MSRC.

/fyi @MattGal

**Comment by ilyas1974** [comment]
We will discuss this in stand up tomorrow.

**Comment by wtgodbe** [comment]
👀

**Comment by MattGal** [comment]
> 👀

I plan to work on this next week after I get the existing workarounds merged for this.

**Comment by MattGal** [comment]
I discussed this with @dougbu and ended up making the tweak only for the PS1 version of the scripts in the linked PR.

This is specifically for two reasons: 

  1. ASP.NET's actual scenario is needing to call these scripts repeatedly on Helix test machines, not a build scenario
  1. The scripts are only modifying the machine state permanently in the windows case (bash one just calls a typical `export PATH=...` if specified)
  1. The bash version of the dotnet-install script is both much trickier to add this to and as noted, has no need for the feature.

This change, along with some helix script changes which restore the registry every work item on Windows, buys us basically unlimited time to solve this problem the _right_ way, which is to make the changes described in https://github.com/dotnet/arcade/issues/6005
