### ISSUE TITLE
Strict CPD on dotnet/sourcelink via dotnet/arcade causes darc failure (due to empty <Sha/>?)

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#6064]
When I run `darc update-dependencies --coherency-only --strict-coherency` on this file:

https://github.com/dagood/installer/blob/96fb687168f26ce6c6bedc9cff25b5be593da770/eng/Version.Details.xml

(https://github.com/dagood/installer/tree/sb-cpd)

Most importantly (probably) is this dependency:

```xml
    <Dependency Name="Microsoft.SourceLink" Version="1.0.0" CoherentParentDependency="Microsoft.DotNet.Arcade.Sdk">
      <Uri>https://github.com/dotnet/sourcelink</Uri>
      <Sha>f175b06862f889474b689a57527e489101c774cc</Sha>
    </Dependency>
```

The update command fails:

```
...
info: Microsoft.DotNet.Darc.Operations.Operation[0]
      Reading 'NuGet.config' from repo 'C:/git/installer' and branch '' succeeded!
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to update dependencies.
Microsoft.DotNet.DarcLib.DarcException: Either the name, version, commit or repo uri of a dependency in repo 'C:/git/installer' and branch '' was empty.
   at Microsoft.DotNet.DarcLib.GitFileManager.UpdateDependencyFiles(IEnumerable`1 itemsToUpdate, String repoUri, String branch, IEnumerable`1 oldDependencies, SemanticVersion incomingDotNetSdkVersion) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 196
   at Microsoft.DotNet.DarcLib.Local.UpdateDependenciesAsync(List`1 dependencies, IRemoteFactory remoteFactory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs:line 79
   at Microsoft.DotNet.Darc.Operations.UpdateDependenciesOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs:line 238
```

Based on the error, it seems likely to be related to this missing commit hash:

https://github.com/dotnet/arcade/blob/f2b7fe854a0b1f78c04dfc065164d6d61040f5b8/eng/Version.Details.xml#L46-L50

My guess would be darc tries to create a dependency with no commit hash to match the coherent parent, but then it chokes immediately because normally dependencies with no commit hash are invalid. If that's what's going on, then the fix might just be to add a commit hash to dotnet/arcade.

@mmitche @riarenas 

(This is for the source-build coherency graph in dotnet/installer: https://github.com/dotnet/source-build/issues/1563)

**Comment by mmitche** [comment]
Hah. That's not even a correct asset name. It should be Microsoft.SourceLink.GitHub and Microsoft.SourceLink.AzureRepos.Git

**Comment by mmitche** [comment]
I'll fix it up.

**Comment by dagood** [comment]
Fixed in `master` with https://github.com/dotnet/arcade/pull/6065, https://github.com/dotnet/source-build/issues/1563 is now waiting on rollout to dotnet/installer.
