### ISSUE TITLE
[Signing] Calling the SignProxy task again overwrites logs from previous SignProxy task

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#6069]
The sdk-task.ps1 script in Arcade has it's own way of defining the name of the logs produced by the task, which is great, except when you want to run that same task again, and it overwrites the previous logs. 

In this case, we'll need to copy the log from the first run of SignProxy and rename them so that they aren't overwritten by the next call.

**Comment by chcosta** [comment]
Can we close this?

**Comment by missymessa** [comment]
Was this work done? Is yes, then close it.

**Comment by missymessa** [comment]
We're no longer using the SignProxy task in post build signing process. Closing this issue.
