### ISSUE TITLE
Maestro checks should reset to pending when appropriate

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6080]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Right now, if a dependency update is sent to a repo and the AllChecksSuccessful fails (a failed PR check), bot correctly marked the auto-merge into as failed. But when a new update is sent, the current PR checks will reset and all say pending again. Unfortunately, the Maestro check still indicates failed, even though none of the current checks are failed yet:

![image](https://user-images.githubusercontent.com/8725170/91776845-28819900-eba3-11ea-95fe-74300e209616.png)

**Comment by mmitche** [comment]
@lwintjen @rokonec

**Comment by lwintjen** [comment]
Interesting. I've been investigating this and I didn't know but when a status of a check has been set to completed (either failing or success), you cannot update it back to pending (but you can set it to failure/success/neutral/action_required or any other conclusion).  

I'm currently looking for a workaround @mmitche

**Comment by mmitche** [comment]
Wouldn't the check be specific to the current head ref for the PR? If a new commit is pushed, then shouldn't it reset back to pending automatically?

**Comment by mmitche** [comment]
ahh, this may only happen when things are rerun.

**Comment by lwintjen** [comment]
Yeah exactly, in the method where we evaluate the AllChecksSuccessful merge policy, if there aren't any ignored checks (non merge policies checks) then we return Fail with a message "Waiting for checks".
![image](https://user-images.githubusercontent.com/43049559/91909853-3e2fb500-ecae-11ea-9410-5791a0198aa7.png)

I think that in the scenario described above, the checks weren't created yet when maestro executed this method and they were created afterwards. The status of the check has been set to Fail (completed) and so even if we updated his status back to Pending, Github didn't do it.

**Comment by lwintjen** [comment]
The [PR](https://github.com/dotnet/arcade-services/pull/1387) has been merged, we can close this issue.
