### ISSUE TITLE
Make CPD strict the default CPD mode

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6093]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

After https://github.com/dotnet/arcade/issues/5940 is complete, CPD strict can be made the default CPD mode:

https://github.com/dotnet/arcade-services/blob/master/src/Maestro/SubscriptionActorService/PullRequestActor.cs#L1155-L1156

That can be changed to "Strict". It should then also be made the default in the update-dependencies operation.

We can also just remove all Legacy references and remove all the affected code paths, tests, etc.

**Comment by epananth** [comment]
This is ON by default.

**Comment by riarenas** [comment]
Also opened https://github.com/dotnet/arcade/issues/6782 in the pile of tech debt to remove the legacy algorithm eventually
