### ISSUE TITLE
[QCR] [Validation Ring] Assets validation should validate packages for all storage feeds

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6096]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Right now we only validate assets that are on the dotnetcli feed, but since the original implementation, we have started publishing to increasingly more feeds. We need to update both the yaml and the functionality to check more than just the single feed for assets. Ie, we need to check that all the packages that say they should exist on dotnetclichecksums exist there, dotnet5-transport, dotnet5, etc. We also probably need to be able to cover the 3.1 case.

Finally, we need to refactor the code that checks for existence to be able to handle the internal/msrc feeds, which you need the api key for.

**Comment by Tohron** [comment]
Merged:
https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/10517?path=%2Fsrc%2FMicrosoft.DotNet.Release%2FMicrosoft.DotNet.ReleaseLib.Tests%2FAssetHelpersTests.cs
