### ISSUE TITLE
Experiment with Workload Selection in the CoreCLR build

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#610]
Workload selection is the Cool New Feature:tm: from VSTS. Need to play around with it to figure out if it works, etc.

In tracking while I'm on FR.

**Comment by markwilkie** [comment]
@jonfortescue - Was anything learned here?

**Comment by jonfortescue** [comment]
Closed because this had ended up forgotten, but the work I did for this happened several weeks ago. Basically found out that workload suggestion is a thing that works and should be something that CoreCLR can apply in their PR builds when they get to that. Didn't do anything significant or permanent since it was out of scope for my main project which was producing a sample CI build for them.
