### ISSUE TITLE
v3 publishing attempts to create bad feed names

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6100]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Currently blocking the servicing exercise.

V3 publishing attempts to build stable feed names off of the Name attribute in the manifest. This is set to be the repo URI, but the feed creator is assuming it is the repo name (e.g. dotnet-installer). This is currently blocking the 5.0 servicing exercise, and will block an RTM builds on v3 publishing.

**Comment by epananth** [comment]
Pr -> https://dev.azure.com/dnceng/internal/_build/results?buildId=799026&view=results
