### ISSUE TITLE
New log upload steps don't work for builds publishing to multiple channels

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6103]
- [X] This issue is blocking 
Builds that publish to multiple channels try to overwrite the same pipeline artifact container, which is immutable, causing the build to fail.
- [ ] This issue is causing unreasonable pain

https://github.com/dotnet/arcade/pull/6067 broke the log publishing logic for the post-build publishing stages, as they are no longer publishing to a different container for each channel that the build publishes to:

Before:

![image](https://user-images.githubusercontent.com/23242101/92038470-4a585880-ed28-11ea-9914-52593bd8af4e.png)

After:

![image](https://user-images.githubusercontent.com/23242101/92038670-9dcaa680-ed28-11ea-9603-532e01c44606.png)

This only manifests in builds that publish to more than one channel from the same branch. See https://dev.azure.com/dnceng/internal/_build/results?buildId=799046&view=results for an example

CC @jcagme

**Comment by jcagme** [comment]
https://github.com/dotnet/arcade/pull/6104

**Comment by riarenas** [comment]
#6104 introduced yaml syntax bugs. Looking
