### ISSUE TITLE
Add "send tests to Helix" to the arcade minimal CI sample

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#611]
The work with CoreCLR has provided a great example of a common scenario, sending tests to Helix. We should add this work to the sample repo for other teams to take a look at.

**Comment by markwilkie** [comment]
@jonfortescue  to add links to the specifics issues which describe what this means.

**Comment by jonfortescue** [comment]
PR in for this! https://github.com/dotnet/arcade-minimalci-sample/pull/201
