### ISSUE TITLE
Merged Manifest should actually merge attributes

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6118]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Rather than merging the attributes from the input manifests (and erroring if there is a difference), the merged manifest takes some attributes from the environment again. This leads to possibilities that bugs in the original manifest (e.g. incorrect repo name) will end up duplicated.

In this specific case, the merge manifest has a different value for the repo name than the input manifests.

**Comment by epananth** [comment]
Matt M already fixed majority of this, still going to keep it and re access it in arcade 3.x epic
