### ISSUE TITLE
GitSync Mirroring Tasks

### ISSUE THREAD

**Issue by Anipik** [dotnet/arcade#612]
There are some bugs still left in the mirroring. They are not high priority but they still occur.

- [x] The commits gets missed in certain cases of merge conflicts. eg Commit A is retrieved from the azure table and contains merge conflicts. This leads to program being paused. If there is any commit that needs to be mirrored during this pause time, that commit will get missed. This occurs because we are not keeping a in memory list of the commits currently being applied. We retrive the commits while marking them as mirrored. This case can occur in multiple cases.
- [x] If there are  multiple commits by a person in a single PR. He will be tagged multiple time. It can be fixed by keeping a unique list of authors.
- [ ] The mirror branches are not getting cleaned. A small cleanup code can be written, which could be ran once a day to remove all the mirror branches. 

cc @danmosemsft @safern

**Comment by markwilkie** [comment]
@Anipik - can this be closed?

**Comment by Anipik** [comment]
Yeah I guess we can close, the third task is not going to be done
