### ISSUE TITLE
Should TargetFramework filtering also hook into the cross-targeting Clean target? 

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#6139]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://github.com/dotnet/msbuild/blob/c7790e1ed37c2e6cb4fc38e76c06ed1fb15d3148/src/Tasks/Microsoft.Common.CrossTargeting.targets#L136-L143 define the cross-targeting Clean target which relies on the same target to calculate inner build projects as the `DispatchToInnerBuilds` target which we hook into to filter the inner projects.

Should we also filter the inner build projects during when invoking the Clean outerbuild target?

cc @Anipik @ericstj

**Comment by ViktorHofer** [comment]
thoughts @Anipik or @ericstj?

**Comment by ericstj** [comment]
I think the filtering on clean is reasonable.  You want build and clean to be parallel.  For example, cleaning on debug doesn't clean the release paths.

**Comment by ViktorHofer** [comment]
Agreed. At the moment we don't do any filtering on clean but should.
