### ISSUE TITLE
[Signing] Support for appending digital signatures

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#614]
It appears the signtool skips submitting a file for authenticode signing if the file already has a signature.

https://github.com/dotnet/arcade/blob/7d8c2ec211f3067177d128889d5b6b65236ed040/src/Microsoft.DotNet.SignTool/src/Configuration.cs#L126-L129

We need the ability to specify that code signing should happen anyways. For example, when signing with Microsoft3rdPartyAppComponentDual, we need to preserve any original digital signatures added by the 3rd-party component authors. Under the hood, the code signing submission uses the `/as` flag to append signatures instead of replacing existing ones.

**Comment by JohnTortugo** [comment]
CC: @tmat @jaredpar @weshaggard

**Comment by JohnTortugo** [comment]
So, the decision whether to append or use a single certificate can be made based on the name of the certificate that would be used to sign the file?

**Comment by natemcmaster** [comment]
That's probably sufficient. Right now, I only know of one example: if certName == Microsoft3rdPartyAppComponentDual or Microsoft3rdPartyAppComponentSha2, then the signing should append, not override.

**Comment by JohnTortugo** [comment]
I'm not sure about this part:

> Under the hood, the code signing submission uses the /as flag to append signatures instead of replacing existing ones.

Do you mean that the certificate appending will be automatically handled or should I change something when calling the MicroBuild plugin?

**Comment by natemcmaster** [comment]
Appending signatures should be handled by MicroBuild. Arcade doesn't need to change the _way_ it invoke MicroBuild, but it needs to actually invoke Arcade instead of skipping. Skipping already signed files is an optimization we can make for certificates that we know will not be used to append signatures, such as NuGet, VSIX, Microsoft400, etc.

To clarify, there are several layers involved in code signing:
* Arcade code sign -> invokes MicroBuild
* MicroBuild -> invokes the ESRP client
* ESRP client -> (remotely) invokes `signtool.exe`

The `/as` flag is used on `signtool.exe` and configured in the options you pass to the ESRP client. Arcade sign tool doesn't need to worry about that, but does need to be aware of certificates for which signatures should be appended, not overwritten.

**Comment by JohnTortugo** [comment]
Thanks @natemcmaster . That makes it crystal clear.
