### ISSUE TITLE
Dependency update PRs in arcade should automerge

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#6143]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

For dependency update PRs like this -> https://github.com/dotnet/arcade/pull/6129,  I think this is safe to automerge this PR to master. So that we don't have to wait to manually merge this PR. 

cc @riarenas @MattGal

**Comment by riarenas** [comment]
We have auto merge enabled, but since we had accidents where people with push permissions were directly pushing to master, we made it so all PRs to that branch require an explicit PR approval. As soon as the PRs are approved they'll be auto merged.

**Comment by riarenas** [comment]
@mmitche do you know if the msftbot that does the auto merging via a label has some mechanism to auto approve certain types of PRs? Maybe that's a good solution here so we are still guarded from accidental pushes.

**Comment by mmitche** [comment]
> @mmitche do you know if the msftbot that does the auto merging via a label has some mechanism to auto approve certain types of PRs? Maybe that's a good solution here so we are still guarded from accidental pushes.

Yeah it does. You can have it auto-approve PRs from a certain user or bot.

**Comment by riarenas** [comment]
@mmitche where are those settings managed?

**Comment by mmitche** [comment]
https://fabric-cp.azurewebsites.net/bot/?repo=dotnet/arcade

**Comment by riarenas** [comment]
We no longer use fabric bot.
