### ISSUE TITLE
BARViz should link in-progress builds

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6150]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Today we link the most recent failed build as well as the most recent successful builds in BARViz. I find myself nagivating to the parent build pipeline just to find whether a build is currently in progress that will apply to the channel. It would be great if this was linked too.

![image](https://user-images.githubusercontent.com/8725170/92795174-076c3580-f365-11ea-87f3-334a9f8f9879.png)

This is probably fairly simple to add. BARViz is already finding builds that are failed, but would have applied to the current channel. So extending this out to current in progress builds would be great.

**Comment by mmitche** [comment]
@lwintjen @rokonec

**Comment by lwintjen** [comment]
The PR has been merged into the staging, waiting to be in the next rollout.

**Comment by tkapin** [comment]
Moving to the summer internship project epic as it's not related to telemetry improvements, but rather to Maestro++ improvements.

**Comment by riarenas** [comment]
This was rolled out.
