### ISSUE TITLE
[Build Resilience - Phase I] Enriching Kusto TestResults telemetry

### ISSUE THREAD

**Issue by rokonec** [dotnet/arcade#6158]
Kusto joins are very expensive and in the scale of data we store, 60e9 rows, some queries are hitting Kusto limits. By de-normalization of some related records properties, we can better leverage Kusto indexing and have answer for questions which would otherwise time-outed or hit other Kusto limitations.

### To be able to extract data with higher business value following enhancements to TestResults telemetry shall be done:

- [x] Add data so we can identify rollout tests run or particular PR branch test runs
- [x] Add data so we can identify tests which fails on same commit and thus are likely flaky
- [x] Denormalize Job (Project, Repository, Name, Type)
- [x] Denormalize Job Propertis (BuildNumber, BuildDefinition, OS, Architecture, Configuration, Reason)
- [x] Denormalize WorkItem (Queue, MachineName)
- [ ] Traits column shall contain json dictionary, as Kusto has optimized way to work with json strings as oppose to parse custom string format

### Example use cases

Some data enriching has strategic meaning so users can address most of their future tactical needs. 

With following enhancements we expect to have practical answer to following question:
- See overall aggregated tests metrics in time chart grouped by either of repository, build pipeline, OS, build reason, queue, job type, ...)
- Machine outliers - machines which tests fail rate or duration differs greatly from other machines on same queue. This might be useful to pinpoint problematic on premise machines.
- OS outliers - OS on which tests fail rate or duration differs greatly from other on same build definition - pipeline.
- Test Type outliers - Test types (class) in which tests behavior differs greatly from other test of same repository or build pipeline. 
- Tests both failing and passing on same commit are likely flaky. This can be used to mark those test as flaky in AzDO or build reports which particular partners can make decisions on (fix, quarantine, assign, ...).
- Compare docker tests performance and/or fail characteristics versus non docker tests.
- Windows vs Linux tests performance and/or fail characteristics.
- Group test metrics based on test type prefix of particular level (System.Net, System.Data, ...)
- ...

**Comment by rokonec** [comment]
**TestResults** table is currently taking vast majority of our storage data. About 1.4TB. A concern that new de-normalized data significantly increase this is valid.

To compute consumed data I have used following approach:

```KQL
.set-or-append _tr1000 <|
TestResults
| sample 1000

.set-or-append _tr1000new <|
TestResults
| extend Source = "pr/public/dotnet/runtime/refs/pull/42188/merge", TeamProject="public", Repository="dotnet/runtime", Branch="refs/pull/42188/merge", Architecture="x64", Configuration = "Debug", OperatingSystem = "windows.10.amd64.coreappcompat", JobType = "byoc/helixpoolprovider-dncengpublic-prod/"
| extend BuildId = "813716", BuildName = "20200913.1", DefinitionName = "runtime-coreclr crossgen2-composite gcstress", BuildReason = "Schedule", WorkItemStatus = "Pass", Queue = "windows.10.amd64.tof", Machine = "a005TWC"
| sample 1000
```

And then comparing size of both result tables by `.show table _tr1000new details` vs `.show table _tr1000 details`.

  | current | planned
-- | -- | --
raw | 287,258 | 583,574
compressed | 260,798 | 261,719

In raw form it consumes about twice as much data as current state, however, Kusto compress data at rest. Estimating size of compressed data is tricky, but since de-normalization will introduce big data redundancy, I believe efficiency of compressing algorithm will be high.

### Conclusion
I expect that final storage size will increase <10% which will result in < 40 USD/month.
To verify this hypothesis I recommend to monitor Kusto cluster after it goes live, and take corrective actions if unacceptable.

Possible actions are:
- change **TestResults** table retention policy. Currently it is 60 days, but since it is not used for anything, setting it to half would be acceptable
- optimize Kusto cluster size; current utilization of Kusto cluster seems to be low, and we would most probably be OK with half of compute power, which would results in savings overcoming additional storage cost

**Comment by markwilkie** [comment]
I like the analysis!

Confirming that mining test result data for a buildid and project is covered?  (https://github.com/dotnet/core-eng/issues/10346)

**Comment by rokonec** [comment]
PR: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/10440

**Comment by rokonec** [comment]
I am no longer working on this epic.
