### ISSUE TITLE
Help users not parse queue names by exposing Helix queue properties

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#6166]
People are parsing the helix queue names to do logic, it's failing in some cases, and is pretty fragile overall.

We should use the Queue info API in a task to populate the following build properties:
  * HelixQueueOperatingSystemGroup
  * HelixQueueArchitecture

We could populate these in a "FetchHelixQueueInfo" target, and users could then override the "CreateHelixCommand" target to build their commands and payloads using this information.  Then the task that actually sends to helix can depend on that target.

That way people don't have to parse the queue names, and we have a good pattern for depending on particular helix properties.

**Comment by safern** [comment]
What will be the story for docker images? Will we support parsing the helix queue and finding that it will run the workitem on a docker image and try and get the rid for that image?

**Comment by ChadNedzlek** [comment]
The architecture and os group shouldn't change because of docker... we run linux on linux, and the images all match their host architecture, I believe.

**Comment by safern** [comment]
It does, for example alpine is Linux but is MUSL based and that is important. It runs on docker image but the host machine is Linux.

**Comment by ChadNedzlek** [comment]
Hrm... Alpine does provide a... unique problem.  Helix doesn't know (or care) about the MUSL-ness of things, so it has no mechanism to use provide this information.  Maybe we need to add that to the QueueInfo?

**Comment by safern** [comment]
The thing is that there is no Alpine queue. We do it via the docker feature.

**Comment by ChadNedzlek** [comment]
Hrm... presumably when we added the alpine queue, we could have passed some sort of metadata along denoting it as special?

**Comment by adiaaida** [comment]
Closing because the parent Epic was closed. If you believe this issue should still be worked on, please re-open.
