### ISSUE TITLE
Extend #6039 to other non-.NET SDK projects (as needed)

### ISSUE THREAD

**Issue by dougbu** [dotnet/arcade#6167]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

@sfoslund corrected problems with newer .NET SDK versions and Tools.proj in #6039. However the problem may still be present in projects used in post-build validation steps. Suggest checking all `*.proj` project files in the repo.

**Comment by garath** [comment]
Triage: @dougbu, are there specific proj files you're having problems with? This was meant to be a work-around, and would like to avoid spreading it.

**Comment by riarenas** [comment]
Triage: It's been a week. Feel free to reopen if there's an actual proj file presenting an issue.
