### ISSUE TITLE
Run post-build validation steps using `dotnet msbuild`

### ISSUE THREAD

**Issue by dougbu** [dotnet/arcade#6168]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The Visual Studio / .NET SDK alignment has been problematic lately, especially because agents move to newer VS versions slower than the minimum required version of desktop `msbuild` changes in the SDK. Unfortunately, post-build validation steps run using desktop `msbuild` and do not currently use scouting queues. An example failure is https://dev.azure.com/dnceng/internal/_build/results?buildId=803092&view=logs&j=0a6c679f-72be-5867-422e-acb741a068a3&t=d8e44ddf-8ea2-5518-25e7-4300471a271a&l=21

The grief could be avoided now and in the future by using `dotnet msbuild` everywhere that's possible i.e. when C++ builds aren't needed.

**Comment by garath** [comment]
Triage: We've updated everywhere possible, unfortunately this is not possible with signcheck because it is a framework app.
