### ISSUE TITLE
Do not include packagereference of XliffTasks, Microsoft.SourceLink.GitHub, Microsoft.SourceLink.AzureRepos.Git for C++/CLI projects

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#6173]
C++/CLI does not support packagereference. This breaks the build of C++/CLI projects when arcade is used.

**Comment by garath** [comment]
Triage: @wil3, can you provide a bit more information? Is there a broken build we can look at?

**Comment by wli3** [comment]
@wtgodbe is working on this issue. What is the process? And @ryalanms is there a branch with the RestoreProjectStyle set?

**Comment by wtgodbe** [comment]
I was just helping @ryalanms diagnose his issues locally, but I believe he was planning on following up with folks from the Arcade team for a long-term fix

**Comment by ryalanms** [comment]
This branch has the first workaround applied (RestoreProjectStyle=Unknown) and will expose the missing Arcade task: 

https://github.com/dotnet/wpf/pull/3444

/cc @dotnet/wpf-developers

**Comment by mmitche** [comment]
@wli3 @wtgodbe @garath @ryalanms What changed here? The references to SourceLink and such have been there forever.

**Comment by riarenas** [comment]
I have prepared a test build version of arcade that conditions the inclusion of sourcelink + xliff packagereferences in this test build: https://dnceng.visualstudio.com/internal/_build/results?buildId=821771&view=results. If that ends up being needed by wpf I will make a PR so that it goes into official arcade.

**Comment by mmitche** [comment]
This has been worked around in the wpf repo
