### ISSUE TITLE
[QCR] [Tech debt] Make operations public

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6176]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Currently all of the operations in ReleaseCli are marked internal, which makes testing the verbs very challenging, as we have to have a public "TestLauncher" inside the CLI assembly that can be called by the tests, rather than just calling the operations directly. We should mark the operations as public, and then call them directly (moving the code from TestLauncher.cs to the actual tests).

/cc: @jcagme @garath @Tohron

**Comment by Tohron** [comment]
PR created:
https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/10621

**Comment by Tohron** [comment]
I'm taking the opportunity to fix the Asset Validation tests here, and I'm wondering whether
success = await (await curClient.GetBlobReferenceFromServerAsync(curSourceUri)).ExistsAsync();
is the right way to validate assets in feeds.

Currently, when validating https://dotnetcli.blob.core.windows.net/dotnet-testing/TestFiles/testinvalidasset.txt, it throws a StorageException saying "The specified blob does not exist.", although https://dotnetcli.blob.core.windows.net/dotnet-testing/TestFiles/ does exist, and only the file itself does not.  I get the impression that in this case, the function should be returning false, not throwing an exception, so perhaps I want another function?

**Comment by Tohron** [comment]
Created a new PR:
https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/10670

**Comment by Tohron** [comment]
Merged
