### ISSUE TITLE
Signing validation job doesn't work with RC1

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6186]
- [x] This issue is blocking arcade promotion
- [ ] This issue is causing unreasonable pain

With the update to the RC 1 SDK, MSBuild 16.8 is required. This breaks the signing validation job of the arcade official build (and presumably other places where this stage is run): https://dev.azure.com/dnceng/internal/_build/results?buildId=816756&view=logs&j=0a6c679f-72be-5867-422e-acb741a068a3&t=d8e44ddf-8ea2-5518-25e7-4300471a271a

**Comment by ViktorHofer** [comment]
@mmitche is this still happening?

**Comment by mmitche** [comment]
Fixed.
