### ISSUE TITLE
[QCR] [Testing] All tests in Microsoft.DotNet.ReleaseCLI should use FluentAssertions

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6213]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Right now we have a mix because the change to use FluentAssertions came in after the initial tests came in. Our policy is to use FluentAssertions everywhere, so we need to update those tests. In particular, the tests found in https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=%2Fsrc%2FMicrosoft.DotNet.Release%2FMicrosoft.DotNet.ReleaseCli%2Ftests%2FReleaseCliTests&version=GBmain&_a=contents need to be updated.

**Comment by garath** [comment]
Done and merged, PR 10432
