### ISSUE TITLE
Test project not running tests for command line build

### ISSUE THREAD

**Issue by smitpatel** [dotnet/arcade#6215]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In https://github.com/dotnet/efcore
We have EFCore.Analyzers.Test project. When invoking `build.cmd -test` (or cibuild.cmd in AzDo for ci build), the test project is not running tests. Same project runs test fine when running in Visual studio or dotnet test on the assembly directly.

The test project is compiled when running build.cmd just missing running tests. I am not able to figure out what is different from other test projects. Any help?

**Comment by alexperovich** [comment]
Your project isn't getting recognized as a test project by arcade sdk. It needs to end in `.Tests` for it to be picked up.

**Comment by smitpatel** [comment]
@alexperovich - Thank you. That did the trick!
