### ISSUE TITLE
BARViz build id should be the BAR build id, rather than the Azure DevOps build id

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6220]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

![image](https://user-images.githubusercontent.com/8725170/93903183-32cc1a00-fcad-11ea-8241-cfbea0b995ff.png)

This is currently displaying the ID of the azure devops build. This should be the BAR build id instead (which is what is typically copy/pasted into other places).

**Comment by lwintjen** [comment]
Fixed in https://github.com/dotnet/arcade-services/pull/1418
