### ISSUE TITLE
Staging Barviz showing "Unable to load content" due to 500 responses from the new commit API

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6221]
- [X] This issue is blocking 
I'm not sure we should deploy this change to production if this is going to manifest there

- [ ] This issue is causing unreasonable pain

See this link:

https://maestro-int.westus2.cloudapp.azure.com/9/https:%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_git%2Fdotnet-wpf-int/latest/graph

I added a build from wpf-int that is currently in the prod DB to the staging database as part of some testing I've been doing, and I saw this:

![image](https://user-images.githubusercontent.com/23242101/93903965-25fbf600-fcae-11ea-9296-00fcc18a9bf5.png)

This seems to be from getting a 500 response from the new commit API.

I don't think there's anything strange in the build object that should cause this to happen:

```json
{
  "id": 19617,
  "commit": "1045306aa2ccc7a08f14b71cbcaa49f40427913f",
  "azureDevOpsBuildId": 822963,
  "azureDevOpsBuildDefinitionId": 280,
  "azureDevOpsAccount": "dnceng",
  "azureDevOpsProject": "internal",
  "azureDevOpsBuildNumber": "20200920.1",
  "azureDevOpsRepository": "https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int",
  "azureDevOpsBranch": "refs/heads/release/5.0-rc2",
  "gitHubRepository": null,
  "gitHubBranch": null,
  "dateProduced": "2020-09-22T14:53:35Z",
  "channels": [
    {
      "id": 9,
      "name": ".Net Tools - Validation",
      "classification": "Test"
    }
  ],
  "assets": [],
  "dependencies": [],
  "incoherencies": null,
  "staleness": 0,
  "released": false,
  "stable": false
}
```

@lwintjen Do you see anything strange in this build that should result in a 500 from the API instead of returning the correct SHA?

**Comment by lwintjen** [comment]
Hmmm. I never had a 500 before. I tried on the staging by running a scenario test and leaving it open. It worked fine :
![image](https://user-images.githubusercontent.com/43049559/93904801-8153d580-fcfa-11ea-8571-d53c4ca47cf0.png)

Maybe it's due to the way we get the commit from AzDevOpsClient  (as I mainly tried with the test repos on github, there might be an issue in AzDev)?

![image](https://user-images.githubusercontent.com/43049559/93905635-79486580-fcfb-11ea-93c7-874d4682729b.png)

**Comment by riarenas** [comment]
Yeah, my fear is that this scenario might be broken for azure devops repos like wpf-int.

**Comment by lwintjen** [comment]
Fixed in https://github.com/dotnet/arcade-services/pull/1418
