### ISSUE TITLE
Move VS package publishing out of signing ring

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#6224]
It looks like VS.* package publishing is happening (with post build signing), in the signing ring, https://dnceng.visualstudio.com/internal/_git/dotnet-release?path=%2Feng%2Fpipeline%2Ftemplates%2Fsteps%2Fsigning.yml&version=GBmain&line=210&lineEnd=217&lineStartColumn=1&lineEndColumn=38&lineStyle=plain

This seems like an unexpected consequence of promoting something to the signing ring and we should consider where to move this to. For example, I see that there is a "vs-insertion" ring, but I don't have any experience in this area and it's not clear if that's the best place for it.

@jcagme @mmitche

**Comment by adiaaida** [comment]
VS insertion ring is meant for creating the VS insertion PRs, and runs post-signing validation/in parallel with other validation. If the VS.* package publishing should happen post signing validation, and is independent of the rest of the validation we do, then I think that would be a reasonable place to put it (perhaps renaming the Ring to something more general), but if it needs to happen pre-other validation, then that's not a good place for it.

**Comment by adiaaida** [comment]
Seems like we have a lot of requests for publishing various packages post-signing. We may want to add an early publishing ring for all of those tasks. For example, https://github.com/dotnet/arcade/issues/5538 (lots might be overstating it)

**Comment by adiaaida** [comment]
I think this is currently in PR. Is that correct @jcagme?

**Comment by jcagme** [comment]
Yes

**Comment by adiaaida** [comment]
Assigning to @garath, since he took over JC's PR.

**Comment by adiaaida** [comment]
@garath This is complete, correct?

**Comment by garath** [comment]
Yep, closing.
