### ISSUE TITLE
SourceLink validation step emits confusing error with automatically generated source-build intermediate nupkg symbol package

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#6225]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In dotnet/source-build-reference-packages, we started getting confusing errors like this--a pass that is a failure:
https://dev.azure.com/dnceng/internal/_build/results?buildId=824139

![image](https://user-images.githubusercontent.com/12819531/93910348-96af0c80-fcc6-11ea-87d4-d5b17add8672.png)

That shows up as a warning on the job icon and and the build succeeds, but it also shows up as two errors in the error list.

> ![image](https://user-images.githubusercontent.com/12819531/93910526-d2e26d00-fcc6-11ea-947e-7aa83dda1b97.png)
> ![image](https://user-images.githubusercontent.com/12819531/93910552-dd9d0200-fcc6-11ea-8518-504d620f37d4.png)

(More recent example: https://dev.azure.com/dnceng/internal/_build/results?buildId=824139)

When I try to run the `print-urls` command locally, I get:

```
#> sourcelink.exe print-urls C:\Users\dagood\Downloads\Microsoft.SourceBuild.Intermediate.source-build-reference-packages.6.0.0-alpha.1.20471.8.symbols.nupkg
Invalid COR20 header signature.
```

* **Can this be fixed?**
* **Why doesn't the job print any output?**
  * I actually have no idea whether it's hitting the same `Invalid COR20 header signature.` issue I see locally.
  * The sourcelink output is not very useful to begin with, though--just gives us a small step towards confirming local repro.

My concern is that this could start affecting repos as they begin to onboard onto arcade-powered source-build. The result is that the build is always in a warning state with spurious errors, never green.

---

I see some recent changes in Arcade about how this validation is run, but it sounds like that probably improved the reporting to the point where we're seeing an existing issue, and maybe on the Arcade side we just need further improvement to get rid of the self-contradiction. /cc @adiaaida 

@markwilkie @tmat

**Comment by adiaaida** [comment]
Looking at the code in sourcelink-validation.ps1, we don't even account for this kind of output:

```
if ($LASTEXITCODE -eq 0 -and -not ([string]::IsNullOrEmpty($SourceLinkInfos)))
```

which does not have an else case (and probably should). Also:

```
# We only care about Http addresses
$Matches = (Select-String '(http[s]?)(:\/\/)([^\s,]+)' -Input $SourceLinkInfos -AllMatches).Matches

if ($Matches.Count -ne 0) {
```

Also no else case. I'm wondering if, at least the first case should report failure.

**Comment by riarenas** [comment]
triage: @tmat any thoughts?

**Comment by adiaaida** [comment]
This turned out to be a different error, and should be fixed by https://github.com/dotnet/arcade/pull/6264.
