### ISSUE TITLE
Remove azdo  Send Helix Start/End Telemetry tasks from dnceng, and eng\common YAML templates (Release/3.x)

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#6228]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

See this build:
https://dev.azure.com/dnceng/public/_build/results?buildId=824043&view=logs&j=efda9e5f-cf98-536e-4181-9b6c13ac35b3&t=ec9e8c58-cea6-5839-9ee0-81311176b279

... I believe this task:
```
==============================================================================
Task         : Send Helix Start Telemetry
Description  : Send start job telemetry for .NET Core builds
Version      : 0.1.2
Author       : Microsoft
Help         : 
==============================================================================
```
... is actually installed somehow on our AzDO server, and is causing thousands of weird warnings.  

Additionally, per various folks we don't even use this telemetry any more and it should be removed both from here and the yaml templates in arcade eng\common.

@wtgodbe FYI; you can probably work around this in the short term by setting `enableTelemetry: false` on your pipelines.

**Comment by MattGal** [comment]
From chatting with @chcosta the source for this task lives in https://github.com/dotnet/arcade-extensions and we can likely delete this entire repo, after updating the server to not inject this task.

**Comment by MattGal** [comment]
First PR: https://github.com/dotnet/arcade/pull/6229/files

**Comment by riarenas** [comment]
>and we can likely delete this entire repo

isn't that where the test results extension also lives?

**Comment by MattGal** [comment]
Updated title.  It seems this may not meet the servicing bar for Arcade 3.x, especially given users can explicitly override the value for enableTelemetry.  We'll discuss Thursday at triage with @mmitche  / @markwilkie and make the decision then.

**Comment by riarenas** [comment]
Triage: We will create an epic for reducing technical debt in our yaml templates.

**Comment by ChadNedzlek** [comment]
It's not clear in this issue that it's not actually the warnings people are upset about, but rather the 15 minutes of pointless retries that's can't ever succeed.

**Comment by wtgodbe** [comment]
> It's not clear in this issue that it's not actually the warnings people are upset about, but rather the 15 minutes of pointless retries that's can't ever succeed.

@ChadNedzlek I was specifically concerned about the warnings - on builds that succeed, it's very annoying to have to scroll past 1000+ warnings to get to the build results

**Comment by garath** [comment]
@wtgodbe Will the `enableTelemetry` flag work for you for the 3.x builds?

**Comment by wtgodbe** [comment]
> Will the enableTelemetry flag work for you for the 3.x builds?

I don't know, what does the flag control? If it turns off the task that causes the warnings, then yes

**Comment by garath** [comment]
Sorry for the delay. I believe that flag does control what you want. @MattGal can help you leverage it. 

Matt sorted this in the main branch already. It isn't likely to meet the bar for servicing branches, especially with the flag to help.  Closing this issue.
