### ISSUE TITLE
Verify symbol indexing story with post-build signing

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6231]
Verify symbol indexing story with post-build signing. After removing signing from the build, the following needs to work:

- [x] Symbols still need to work for crash dump analysis prior to shipping. For example, if aspnetcore gets a new runtime and it crashes, symbols should work. This means that the symbols of the unsigned binaries must be indexed, as well as the unsigned binaries.
- [x] The DACs and cross OS dacs must be signed so that dumps can be analyzed.
- [ ] After shipping, symbols must be **re-indexed** using the signed binaries. If a user asks for symbols:

```
 dotnet symbol -d --modules --microsoft-symbol-server --symbols
```

Then they should get the signed binary.

**Comment by mmitche** [comment]
@hoyosjs

**Comment by hoyosjs** [comment]
@dotnet/dotnet-diag fyi

**Comment by mmitche** [comment]
@hoyosjs Verified that both MSDL and Symweb will transparently update the index if a new binary/pdb is indexed with the same client key.

So our current process should work.
