### ISSUE TITLE
Add net6.0 to the list of DefaultValidateFramework

### ISSUE THREAD

**Issue by Anipik** [dotnet/arcade#6247]
We need to add net6.0 to list of frameworks  for package validation.
The change should be made here https://github.com/dotnet/arcade/blob/b1754cc4a2d37d522946792f50887eb716220f6a/src/Microsoft.DotNet.Build.Tasks.Packaging/src/build/Packaging.targets#L906

cc @ericstj @ViktorHofer @safern

**Comment by ViktorHofer** [comment]
This should be a trivial change, why not just do it?

**Comment by ericstj** [comment]
Right, I wanted the issue to track removing it on dotnet/runtime side when Arcade was merged.
