### ISSUE TITLE
Do minimum validation of result of GetBuildManifest

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#6261]
BuildManifestOperations.GetBuildManifest(string) returns null if given a path to an extant but invalid file. This is default deserialization behavior. It is Good and Reasonable to at least check the top level for null after deserialization and throw an exception if so. 

FYI @missymessa

**Comment by adiaaida** [comment]
This seems like a dup of https://github.com/dotnet/core-eng/issues/10983

**Comment by adiaaida** [comment]
Checked, these are different issues. Converting to using System.Text.Json gets us the desired behavior (throwing a JsonException if the manifest file is empty)
