### ISSUE TITLE
Disable SigningValidation if PostBuildSign is true

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#6267]
A few repositories are still doing signing validation in their official builds.  When we run those repos with PostBuildSign=true and signing doesn't happen, this causes the build to fail.  We should disable signing validation if postbuildsign is true.  This would be a central update to the Arcade templates

Examples:
- Extensions: https://dnceng.visualstudio.com/internal/_build/results?buildId=834379&view=results
- Wpf-int: https://dnceng.visualstudio.com/internal/_build/results?buildId=834354&view=results

**Comment by chcosta** [comment]
ZenHub isn't working for me.   I'll try to put this in the post build signing epic when I can. :/

**Comment by mmitche** [comment]
I've completed this.
