### ISSUE TITLE
Package version safety checks should be able to be skipped if desired

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6276]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

**Blocking arcade updates for some repos that produce global tools.**

symstore uses release package versioning on every build. The package patch is based on the build number, so it always changes. This is functionality introduced here: https://github.com/dotnet/arcade/pull/2615.

See https://github.com/dotnet/symstore/blob/master/eng/Versions.props#L6-L7 for symstore's use.

This was fine up until a late August arcade change where we re-enabled safety checks so that stable packages could not be published to non-isolated feeds. This was re-enabled because runtime managed to publish some 5.0.0 packages during the servicing exercise. This broke some repos that onboarded to this global tool versioning in the interim.

We need an option to say "ignore the safety check, i know what I'm doing". I think this should be:
- Flag implemented as an attribute in the manifest (.e.g. UsesReleaseOnlyPackageVersion)
- Flag is read by the publishing task and changes the behavior of CheckForStableAssetsInNonIsolatedFeeds

I'm okay implementing this for v3 only.

**Comment by mmitche** [comment]
@epananth

**Comment by riarenas** [comment]
The Publishing task already has a property to skip this validation: https://github.com/dotnet/arcade/blob/f56c8fdc9fc149d135f121b21f7d93a384f26c6f/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs#L89

https://github.com/dotnet/arcade/blob/f56c8fdc9fc149d135f121b21f7d93a384f26c6f/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs#L267-L272

Fixing this should only require plumbing through that property into the task invocation.

**Comment by mmitche** [comment]
@riarenas That's a generic safety check option. It also checks some other things (like internal builds on public feeds, etc.). So maybe we'd need to split it out.

Also remember the promotion pipeline is involved here. So feeding it through that way would involve new parameters to darc, etc. IMO when dealing with this kind of versioning, we know that the versions we'll get will always be major.minor.patch. So I think it makes more sense to feed it through arcade:
1. Arcade knows it's generating release versioning, sets ReleaseVersioning property
2. Publish task sees that, adds attribute in manifest
3. This safety check is avoided.

**Comment by epananth** [comment]
Part 1 - arcade change -> https://github.com/dotnet/arcade/pull/6319
Part 2 - arcade-services change -> https://github.com/dotnet/arcade-services/pull/1434
Part 3 - arcade change -> Will update when I get the latest MaestroTask version

**Comment by epananth** [comment]
Thanks @riarenas for catching me close another issue instead of this one..

symstore test -> https://dnceng.visualstudio.com/internal/_build/results?buildId=858950&view=results
https://dev.azure.com/dnceng/internal/_build/results?buildId=859016&view=results

Symstore got the latest arcade update and it was merged https://github.com/dotnet/symstore/pull/228, closing this one,
