### ISSUE TITLE
Ability to ignore the helix work item download failure

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/arcade#6279]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

I have a use case where I spawn multiple helix work items to do gather some data, then put it inside `uploadResult` so I can download it on AzDo machine. Sometimes, the data gathering part might fail on one of the helix machine and in that case, I want to ignore that failure, but still gather data from other helix work items to do further processing. Currently, it is not possible to do. E.g. In https://dev.azure.com/dnceng/internal/_build/results?buildId=835712&view=logs&j=7cb0efdd-4e4f-50c9-6fc6-4cc567ebc460&t=bf59030a-e0a8-5aae-445b-e48c4d2d8570 , I partitioned the payload in 8 partitions, 5 of which succeed and I wanted to process its data, but the entire job failed and hence I couldn't do processing on the ones that succeed.

**Comment by garath** [comment]
After discussing in the triage meeting, this seems outside the expected use of helix and arcade. These sorts of failures are meant to be breaking as they indicate a real workitem problem. Closing, but please feel free to reopen if you want to continue the conversation.
