### ISSUE TITLE
[Maestro] Key Vault configuration needs to support retrieving new values from Key Vault without restarting the service

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#628]

**Comment by jcagme** [comment]
@alexperovich could you elaborate more on what is needed here?

**Comment by alexperovich** [comment]
The current configuration implementation in Maestro loads the values from key vault once, at the start of the process. We need to allow the values to be reloaded without requiring a restart.

**Comment by riarenas** [comment]
I believe this is fixed with the changes @ChadNedzlek made in https://github.com/dotnet/arcade-services/pull/517/files

Next deployment should include the fix.

**Comment by ChadNedzlek** [comment]
This only fixes things in "arcade-services".  If this "Maestro" is that "Maestro", then yeah, it's done. :-)

**Comment by riarenas** [comment]
Re-Opening and moving to rollout.
