### ISSUE TITLE
None of the ReleaseCLI tests validate the exit code, which is critical for operation in AzDO

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#6290]

**Comment by ChadNedzlek** [comment]
I was refactoring to do some DI, and realized that the "TestLauncher" stuff doesn't actuall return the exit code, which means the tests can't validate it.

My new DI returns it, but all the tests still ignore it (I don't have time to figure out the right answer for every test)

**Comment by adiaaida** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/11407
