### ISSUE TITLE
GetFailedWorkItemsAsync() makes all its Helix API calls simultaneously

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#6292]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

See this line;
https://github.com/dotnet/arcade/blob/dc949d8b3e4ac7ea50025fb39d8a161744089824/src/Microsoft.DotNet.Helix/Sdk/GetFailedWorkItems.cs#L60

As invoked by https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets#L60

GetFailedWorkItemsAsync() tries to hit the Helix Files API for every failed work item every time.  So, when users have total failure in an Azure DevOps run, this method tries to hit the API at least once per work item for every work item _simultaneously_ (limited of course by the number of connections that can be opened at once).

I'd suggest this be just done synchronously with a small delay between each call.  Yes, this is slower, but gives a much better chance of success.

**Comment by MattGal** [comment]
@ilyas1974 moved to top of the stack, but maybe critical, since people sending 400 failing work items on their pipeline could cause others in nearby machines to fail?

**Comment by rokonec** [comment]
Reworked by #6315

**Comment by MattGal** [comment]
The fix is in Helix SDK version 20502.7 and greater.  I'm leaving this in rollout until I can update it explicitly in runtime.

**Comment by MattGal** [comment]
This is rolled out all over, as well as fixed in another way, closing.
