### ISSUE TITLE
ReleaseCLI tests have required secrets to run, if they aren't set, the failure should say that

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#6293]
Right now if you don't have a bunch of user secrets/environment variable set, a bunch of random asserts just say "True, Expected: false" or the like, which is really hard to debug.

If a test needs a secret, and that value isn't set, it should throw a very clear message with the name of the secret and what it's value should be, so that people can get tests running.

**Comment by adiaaida** [comment]
@garath Do you mind if I take this one?
