### ISSUE TITLE
VSTest target hardcodes trx logger format for dotnet test

### ISSUE THREAD

**Issue by marek-safar** [dotnet/arcade#6300]
- [x] This issue is blocking

VSTest target hardcodes trx logger format for dotnet test at
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/VSTest.targets#L22 which causes the output to be incompatible with the default PublishTestResults publishing step https://github.com/dotnet/arcade/blob/master/eng/common/templates/job/job.yml#L209

This issue is blocking publishing any test results for .NET Core configurations in https://github.com/mono/linker repo.

Example of incompatible tests publishing log https://dev.azure.com/dnceng/public/_build/results?buildId=832580&view=logs&jobId=bb592630-4b9d-53ad-3960-d954a70a95cf&j=bb592630-4b9d-53ad-3960-d954a70a95cf&t=2f30a4de-6308-53a4-3de8-6f41c9742e3f

**Comment by ViktorHofer** [comment]
cc @alexperovich @MattGal

**Comment by alexperovich** [comment]
There isn't any "official" supported way to output xunit from vstest. We should just change the reporting to be okay with both.

**Comment by ViktorHofer** [comment]
Sounds great.

**Comment by garath** [comment]
Triage: This scenario isn't yet supported but is in the direction we want to go.

**Comment by ViktorHofer** [comment]
@garath this is currently blocking dotnet/linker to identify their test failures. They are basically blocked.

**Comment by marek-safar** [comment]
Could we enhance enablePublishTestResults to accept instead of `true` also `VSTest` or something like to avoid us recreating the pipeline?

**Comment by markwilkie** [comment]
Yes, to your point @marek-safar, perhaps it's worth the linker team adding the support?  We certainly do want to support vstest as a first class citizen, but it's not yet something we can actively address ourselves yet.

**Comment by markwilkie** [comment]
Also, this might help a little....  https://github.com/dotnet/arcade/pull/6253

**Comment by alexperovich** [comment]
PR: https://github.com/dotnet/arcade/pull/6325
