### ISSUE TITLE
Get dependency injection set up for ReleaseCLI

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#6302]

**Comment by ChadNedzlek** [comment]
PR https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/10609

**Comment by garath** [comment]
That's not the right PR link I think.

**Comment by ChadNedzlek** [comment]
I only did the logger, because it's usually a good place to start, even if it's not the most useful one (and was usually already sort of broken out).

After that is HttpClient and GitClient and such. Those are harder, because they are intertwined into the operations... they just create new ones, so it involves a lot more functional changes.
