### ISSUE TITLE
Workitems created with env/common/templates/steps/send-to-helix.yml always have the same name "WorkItem"

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/arcade#6304]
While building up some CI infrastructure I found myself with multiple jobs being sent to helix through this yml file which all used the same queue. The end result was that it is difficult to identify in the test tab of AzDo which tests failed as there are multiple jobs sent to the same queue, and without the ability to specify the workitem name they aren't distinguished. I've worked around the problem by changing the script run in helix to echo out a more descriptive name, so the issue is visible in the console log, but an ability to specify a custom workitem name would be better.

**Comment by alexperovich** [comment]
The send-to-helix template is designed for small repos with simple scenarios, and it isn't intended to be used more than once. If you have multiple kinds of work you need to send, you can create a project and construct the work items directly. Arcade uses this method here https://github.com/dotnet/arcade/blob/master/tests/UnitTests.proj

**Comment by garath** [comment]
Closing this issue. @davidwrighton feel free to reopen if you'd like to continue the conversation.
