### ISSUE TITLE
Make PkgProj permit no VersionSuffix being set

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#6305]
We should fix the dotnet/runtime packaging infra to not require VersionSuffix.  See https://github.com/dotnet/runtime/pull/42872/files#r497644103

We ought to permit an unset VersionSuffix and error any place where we would have needed one to be set (EG: a stable package referencing non-stable package).

**Comment by ericstj** [comment]
cc @ViktorHofer @Anipik

**Comment by AraHaan** [comment]
Are you refering to this part of the code in arcade?

https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets#L119-L141

If so, I want to change this to where it won't override what the user sets in their ``eng\Versions.props`` on their repository if they wanted to manually set the version suffix for some reason *after* importing the arcade sdk itself.

I was thinking of filing a new issue but then I found this one.

**Comment by ericstj** [comment]
No, this was for pkgproj.  I don't think we need this issue any more as we are moving off of pkgproj.
