### ISSUE TITLE
DotNetRoot isn't set when a globally installed SDK is used

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#6307]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

There are several customers (including dotnet/runtime) that expect `DotNetRoot` to be set. The current logic doesn't assign a value to the property when a globally installed SDK is used.

https://github.com/dotnet/arcade/blob/b6d0e8c2a27c94adc20bd97cf248d6522d20bf08/src/Microsoft.DotNet.Arcade.Sdk/tools/RepoLayout.props#L26-L37

Is that something that we can change to always point to the currently used SDK (except when building with desktop msbuild of course)?

**Comment by garath** [comment]
@ViktorHofer What is the use case? What would be a good default setting?

**Comment by ViktorHofer** [comment]
My use case was that I wanted to copy some of the currently used SDK's content into another location for CI submission.

> What would be a good default setting?

I don't really understand the question. If there isn't a way to find that information out when setting the `DotNetRoot` property we might want to consider making it private `_DotNetRoot` instead so that people don't depend on it.

**Comment by alexperovich** [comment]
Chatted with viktor. He doesn't need this property set anymore. There isn't any good way for us to set this property in all cases, so we should just document that it may be unset.

**Comment by alexperovich** [comment]
This is an undocumented feature of the acade sdk. We do not need to document the fact that this is undocumented. I would like to rename the property to reflect it being private, but that is a rather large change with little to no benefit.

**Comment by ViktorHofer** [comment]
How do Arcade SDK consumers now that this property is private given that it doesn't use a name that would indicate that. To avoid renaming it and then probably dealing with fallouts, I think adding a comment that the property isn't intended to be used would be best.

**Comment by alexperovich** [comment]
Its not in the documentation. If its not there it can't be depended upon at all. Reading the xml and using properties that you find isn't a sustainable path. If it isn't in the documentation, assume it will change every release. Documenting every property that we haven't documented as "private" is just extra words with no value. If its not in the docs, its private.

**Comment by ViktorHofer** [comment]
> If its not in the docs, its private.

How would you differentiate between something not being documented yet vs not documented because private? There are numerous properties in the Arcade SDK that we depend on in which aren't documented.

**Comment by alexperovich** [comment]
If something isn't documented it should be assumed private. If it is actually not-private then it needs to be documented.
