### ISSUE TITLE
BARViz should trim commit titles

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6309]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

BARViz appears to be taking maybe more than the first line of a commit for display? Or if it's not more than that, then it needs to be truncated anyway. In the bit below, I would expect to only see "Update dependencies from https://github.com/dotnet/wpf build 202010014 (#1137)" (at most)

![image](https://user-images.githubusercontent.com/8725170/94938620-f014f980-0485-11eb-8176-b1ffb278bf89.png)

**Comment by riarenas** [comment]
Yeah I opened https://github.com/dotnet/arcade/issues/6287 as soon as I saw this after Wednesday's deployment

**Comment by tkapin** [comment]
@rokonec Please move this to closed if there isn't anything left to verify, thanks.
