### ISSUE TITLE
Arcade-validation shouldn't depend on github

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#6313]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain
- [x] This issue is annoying

https://github.com/dotnet/arcade-validation/blame/master/eng/validation/test-publishing.ps1#L47

The internal Arcade-validation repo assumes that the change you're verifying is in the github (public) repo.  This is annoying, and not always correct.

https://dnceng.visualstudio.com/internal/_build/results?buildId=840062&view=logs&j=56ebfe15-69d8-5dd1-65e4-c65998c8d8a6&t=0a9483a6-3ac1-5fd2-c450-3586b050b65b&l=33

The magic that a thorough developer now needs to know is that, in order to validate their changes won't break Arcade or other repos, they need to push commits with their changes to BOTH the internal Arcade repository (so they can produce a build), and the public github repository.  

Also, if we're flowing dependencies internal, it is weird to have a requirement on the public repository (we tell all the product repos not to do this).

Also, it seems like there's a potential security issue here since the internal build has a dependency on the public repo.

**Comment by riarenas** [comment]
The new checkbox describes this perfectly. Spent a good amount of time trying to get this to work with a private arcade version yesterday with @jonfortescue without much luck.

I think this stage should only run when the build is not running from a private branch.

**Comment by chcosta** [comment]
This is resolved with Ricardo's changes

**Comment by riarenas** [comment]
Thanks. Forgot to close this.
