### ISSUE TITLE
Consider removal of Helix API usage in GetFailedWorkItems task

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#6318]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

As noted in https://github.com/dotnet/core-eng/issues/11037, we don't really need a text file with all the URLs of the files from a helix work item any more, since we have an Extension that presents this data in nicer,  HTML-formated formats.  

That said, the reason I am filing this issue to discuss in triage is that I am certain there are folks taking dependencies on the existence of the file this task is written to create, so it should be discussed.

**My preference:**  Nerf the Helix API usage in the task but have it create a file (at least for a few months) that redirects the user to look at the Azure Devops "Helix Workitem Results" tab that uses the new UI.

**Comment by akoeplinger** [comment]
I'm pretty sure @jaredpar's runfo tool is using the UploadFileResults.txt for some analytics.

**Comment by MattGal** [comment]
> I'm pretty sure @jaredpar's runfo tool is using the UploadFileResults.txt for some analytics.

Yup that's the " I am certain there are folks taking dependencies" part :)

**Comment by jaredpar** [comment]
Yeah I definitely depend on this file. If there is a better way to navigate from failed "Work Item" nodes ot Helix URIs I'd be happy to switch to that. For now though this is the only approach I know of.

**Comment by ChadNedzlek** [comment]
It doesn't sound like making changes here really helps.

**Comment by MattGal** [comment]
> It doesn't sound like making changes here really helps.

The problem seems to have almost entirely been the connection string not having a decorator that allowed more connections; fixing that basically ended this problem, so now that we did that and the function is serial, it has been well behaved.
