### ISSUE TITLE
[Helix] Display jobs URI for all Helix submissions

### ISSUE THREAD

**Issue by dougbu** [dotnet/arcade#6322]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When Helix work items fail, the Helix SDK displays useful messages such as
``` text
error : Failure log: https://helix.dot.net/api/2019-06-17/jobs/29687c8c-a7bf-42c4-b466-6436a873c787/workitems/ProjectTemplates.Tests--net5.0/console
```

Nothing similar is displayed when all work items _succeed_. This makes it annoying to check whether test infrastructure changes work as expected (versus disabling all tests for example 😺). Need to copy and paste the job GUID to craft the jobs URI and navigate from there to a work item console log. Would be more convenient if, at least optionally, the SDK displayed the overall jobs URI e.g. https://helix.dot.net/api/2019-06-17/jobs/779101d3-cecd-4b6d-befa-40d463ae65a4 and / or the work item list e.g. https://helix.dot.net/api/jobs/779101d3-cecd-4b6d-befa-40d463ae65a4/workitems?api-version=2019-06-17

**Comment by dougbu** [comment]
Happy to send a PR if I get guidance whether to add a new property controlling the message and which of the jobs and work item URI or both is preferred.

**Comment by dougbu** [comment]
Also is https://helix.dot.net/api/2019-06-17/jobs/779101d3-cecd-4b6d-befa-40d463ae65a4/workitems preferred over https://helix.dot.net/api/jobs/779101d3-cecd-4b6d-befa-40d463ae65a4/workitems?api-version=2019-06-17❔

**Comment by markwilkie** [comment]
Without thinking through this fully, this seems like reasonable thing for you to submit a PR for @dougbu.  Thoughts @ChadNedzlek, @AlexGhiondea, and @MattGal ?

Also, we're going to be investing in the telemetry side of test results in the very near future.  In other words, the hope is that you'll be able to super easily query your results without killing things due to the gigantic db size.  Don't know yet how for we can get, but that's (one of) the goals.

**Comment by alexperovich** [comment]
> Also is https://helix.dot.net/api/2019-06-17/jobs/779101d3-cecd-4b6d-befa-40d463ae65a4/workitems preferred over https://helix.dot.net/api/jobs/779101d3-cecd-4b6d-befa-40d463ae65a4/workitems?api-version=2019-06-17

The latter is preferred, but the former will work for the foreseeable future.

**Comment by dougbu** [comment]
Thanks @alexperovich and @markwilkie❕

Any thoughts on
> whether to add a new property controlling the message and which of the jobs or work item URI or both is preferred.

**Comment by ChadNedzlek** [comment]
I wouldn't make it customizable.  Just write the stuff to the logs.  If people don't want it, they can ignore it. :-)

**Comment by alexperovich** [comment]
Too much logging would be bad, but we can probably log at least the work item list uri always.

**Comment by ChadNedzlek** [comment]
Who looks at the logs for a successful run anyway?  If it's some weird property in the MSBuild, that's a pain to manage, document, support. Bleh.

Aren't the values already available in the "Helix Attachments" tab? Is the problem that it's hard to find one for a particular workitem?  I'm not 100% what the use case is here... Is the concern that a workitem "succeeded", but didn't actually run any tests?  Is there some other way we can reassure our users without dumping 100's of logs at them and making them read them all?

**Comment by alexperovich** [comment]
they should be available on failed tests, I believe they are also there for passed tests.

**Comment by ChadNedzlek** [comment]
It feels like we need some better way to handle people trying to change the test infrastructere... the "helix" part is so buried deep in the build that it's difficult to make these changes and get at the information people want without a crazy amount of digging.

But maybe these changes are rare enough that it's ok for it to be a bit messy?  Like if we only do this stuff once in a blue moon, we shouldn't impact the mainline scenarios/maintainability for it.

**Comment by dougbu** [comment]
My concern is double-checking changes made to Helix-related configuration in a repo e.g. dotnet/aspnetcore. In some cases, everything goes just fine but we _still_ need to confirm what we changed did what we expected e.g. expanded an archive and used it correctly.

The logs exist but are not currently a click away, especially when submitting Helix jobs from a local clone. dotnet/aspnetcore has a script just for this purpose -- [eng/scripts/RunHelix.ps1](https://github.com/dotnet/aspnetcore/blob/master/eng/scripts/RunHelix.ps1) 😺 and we often need to change things around as requirements change and as we on-board new classes of tests to run in Helix work items.

**Comment by dougbu** [comment]
BTW w/ JSON Viewer, JSON Formatter, or another browser extensions (I think Firefox provides something by default), the work items JSON is a great place to start.

**Comment by ChadNedzlek** [comment]
I'm just worried that bringing them "a click away" for a rare scenario negatively impacts mainline scenarios by filling them with noise.  Or making or code harder to maintain by adding a bunch of little switches that we need to support (and will probably get broken all the time since they are flipped rarely).

Something that is rarely done being a bit more complicated than the thing that is often done seems like a good thing...

**Comment by dougbu** [comment]
This doesn't have to mean an additional message @ChadNedzlek e.g.
``` diff
- Sent Helix Job 6e587b6e-b135-413a-881f-6e56d7984d2f
+ Sent Helix job; see work items at https://helix.dot.net/api/jobs/6e587b6e-b135-413a-881f-6e56d7984d2f/workitems?api-version=2019-06-17
```
or, perhaps (because it's another short message where the jobID isn't even displayed)
``` diff
- Stopping Azure Pipelines Test Run Ubuntu.1604.Amd64.Open
+ Stopping Azure Pipelines Test Run Ubuntu.1604.Amd64.Open; work items at https://helix.dot.net/api/jobs/6fe3fa24-9a2c-409a-be68-785b00f33a48/workitems?api-version=2019-06-17
```

BTW at least for dotnet/aspnetcore, the Helix submission, wait, and report messages come after ~700 lines of build logging and fit into ~90 lines even for our "full matrix" (13 queues). The Helix noise level is _very_ low.

**Comment by dougbu** [comment]
If you wish, I could make changes conditional on a successful run to avoid redundancy w/ the console log links for failed work items. Obviously that works only for my second option [above](https://github.com/dotnet/arcade/issues/6322#issuecomment-703944686)

**Comment by ChadNedzlek** [comment]
The single log sounds totally fine.  It's almost zero noise to just do all the time, so wouldn't impact anyone that wasn't looking for it.  Dumping _every_ log might be a bit much. :-)

**Comment by dougbu** [comment]
> adding a bunch of little switches

Thought avoiding new switches was the point of [your](https://github.com/dotnet/arcade/issues/6322#issuecomment-703933401) "I wouldn't make it customizable" comment.

> Dumping every log might be a bit much. :-)

Absolutely❕ That's why I suggested logging either the jobs URI or the (per job) work items URI or both but nothing at a finer granularity

**Comment by MattGal** [comment]
> The single log sounds totally fine. It's almost zero noise to just do all the time, so wouldn't impact anyone that wasn't looking for it. Dumping _every_ log might be a bit much. :-)

Could do this plus log everything else we can think of (that doesn't involve hitting the API a bunch of times) as diagnostic-level logging, so folks who turn on greater logging or are willing to crack open the binlog could have it handy.

**Comment by dougbu** [comment]
> Could do this plus log everything else we can think of (that doesn't involve hitting the API a bunch of times) as diagnostic-level logging

@MattGal the `SendHelixJob` task and so on have a bunch 'o logging at `MessageImportance.Low` but how would anyone turn the tasks' knob up to 11 without increasing the logging for everything that comes before it in that `msbuild` execution❔ In any case, I'd rather not deal with the Helix internals in almost all cases.

**Comment by dougbu** [comment]
Backing up,
> The single log sounds totally fine

What do people prefer between the following❔
1. `Sent Helix job; see work items at https://helix.dot.net/api/jobs/6e587b6e-b135-413a-881f-6e56d7984d2f/workitems?api-version=2019-06-17` i.e. a bit more logging near the start
2. `Stopping Azure Pipelines Test Run Ubuntu.1604.Amd64.Open; work items at https://helix.dot.net/api/jobs/6fe3fa24-9a2c-409a-be68-785b00f33a48/workitems?api-version=2019-06-17` i.e. a bit more logging near the end
3. A new line containing `See also https://helix.dot.net/api/jobs/6fe3fa24-9a2c-409a-be68-785b00f33a48/workitems?api-version=2019-06-17` i.e. a bit more logging that could be anywhere

And should the "bit more logging" happen **only** when the work items all succeed (if at or near the end)❔

**Comment by MattGal** [comment]
> What do people prefer between the following❔

I'd vote for the 2nd here.


> > Could do this plus log everything else we can think of (that doesn't involve hitting the API a bunch of times) as diagnostic-level logging
> 
> @MattGal the `SendHelixJob` task and so on have a bunch 'o logging at `MessageImportance.Low` but how would anyone turn the tasks' knob up to 11 without increasing the logging for everything that comes before it in that `msbuild` execution❔ In any case, I'd rather not deal with the Helix internals in almost all cases.

In some repos the Helix part is basically "fetch artifacts and send them off"... this would be what I was imagining so turning the whole thing verbose wouldn't be the worst.   There are hacky ways to only build a specific project with diag level but none I'd suggest, so let's not be concerned about that one (other than they're always in every binlog)

In either case such logs are more for the "figure out a problem" state since a majority of payload related problems end up being with how the payloads were created, and the average dev who isn't the person who set up Helix payloads doesn't want to see the logs of unzipping and copying.

**Comment by akoeplinger** [comment]
> What do people prefer between the following

Option 1 since I sometimes watch builds in real-time and getting the Helix URL at the start of the job rather than when every single work item finished is much better.

**Comment by dougbu** [comment]
I'm fine either way but work item lists appear empty these days e.g. https://helix.dot.net/api/jobs/5c5680b1-e39a-4e08-881a-df976726f0bc/workitems?api-version=2019-06-17 What gives❔

**Comment by dougbu** [comment]
That was an internal PR. https://helix.dot.net/api/jobs/4bccfce0-9570-44bd-a171-afd6973b6def/workitems?api-version=2019-06-17 was for a public PR and has listed work items. Oddly, the jobs URI works in both&hellip;

**Comment by ChadNedzlek** [comment]
You don't have access to the internal PR without authenticating, so you can't list it's workitems.

**Comment by dougbu** [comment]
I'm authenticated in AzDO and on https://helix.dot.net. The details URI e.g. https://helix.dot.net/api/jobs/5c5680b1-e39a-4e08-881a-df976726f0bc/details?api-version=2019-06-17 shows information but the work items list URI (matching my comment [above](https://github.com/dotnet/arcade/issues/6322#issuecomment-705285432)) remains empty.

In any case, how would I or any user get to a useful location from the work items URI❔ This feels less interesting if it doesn't work for internal PRs.

**Comment by MattGal** [comment]
> I'm authenticated in AzDO and on https://helix.dot.net. The details URI e.g. https://helix.dot.net/api/jobs/5c5680b1-e39a-4e08-881a-df976726f0bc/details?api-version=2019-06-17 shows information but the work items list URI (matching my comment [above](https://github.com/dotnet/arcade/issues/6322#issuecomment-705285432)) remains empty.
> 
> In any case, how would I or any user get to a useful location from the work items URI❔ This feels less interesting if it doesn't work for internal PRs.

Logging in just gives you the ability to get an access token; it does not cache this identity for all navigation to URIs.

As Chad points out, you would take this URI and append an access_token value like so:
`https://helix.dot.net/api/jobs/5c5680b1-e39a-4e08-881a-df976726f0bc/details?api-version=2019-06-17&access_token=<some token>` 

At which point you get the data with filled-in values.  Using the Arcade Helix SDK provides the simplest way to do this from code, but if you're just pasting URLs in the browser you just need to get familiar with providing your access token.

**Comment by dougbu** [comment]
Ah, then I'll work through how the C# and `msbuild` code calculates the correct URIs to avoid this with the console.log (error) links; those are displayed w/ the `access_token` query string when it's needed.

**Comment by MattGal** [comment]
Ideally, follow the links you get and only write those down; they're specific to the container they come from, whereas the token has other uses and thus if you can avoid logging it do (if you use binlogs, the cat's out of the bag, just don't log to console)

**Comment by dougbu** [comment]
Is that a bug in the existing error messages displayed when Helix jobs fail @MattGal❔ I was pretty sure they included the access token.

**Comment by MattGal** [comment]
possibly?   I'd have to see an example, but i've seen code that looks suspiciously like that.  As long as it's known to AzDO as a secret though, console logging will auto-mask it.

**Comment by dougbu** [comment]
@MattGal @ChadNedzlek my memory was wrong. The token isn't logged as I thought it was. See e.g. https://dev.azure.com/dnceng/internal/_build/results?buildId=846274&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=d5bf30bc-9e5a-596c-d1c8-39e2dfa42d49&l=726
``` text
...\s\.packages\microsoft.dotnet.helix.sdk\5.0.0-beta.20467.6\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(76,5): error : Failure log: https://helix.dot.net/api/2019-06-17/jobs/c63e5227-39dd-4f89-8454-5871800a85ee/workitems/ProjectTemplates.Tests--net5.0/console?access_token={Get this from helix.dot.net}
```

I may have been confused by some JSON files e.g. https://helix.dot.net/api/jobs/c63e5227-39dd-4f89-8454-5871800a85ee/workitems/Microsoft.AspNetCore.Cryptography.Internal.Tests--net5.0?api-version=2019-06-17&access_token=... containing URIs that authenticate automatically e.g. https://helixri107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-10023-merge-c63e522739dd4f8984/Microsoft.AspNetCore.Cryptography.Internal.Tests--net5.0/2390f94f-2b9d-4f94-b4cd-b562aff45de5.log?sv=...&se=...&sr=c&sp=rl&sig=...

**Comment by dougbu** [comment]
Done in 67035ca98fc8
