### ISSUE TITLE
Need tests for GenerateAzureDevOpsBuildManifest

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#6330]
This file was created for the Post-Build Signing project, so it should be tested in it's entirety in relation to that project. 

Related PRs: 
- https://github.com/dotnet/arcade/pull/5442
- https://github.com/dotnet/arcade/pull/5210

Code that needs unit testing: 
- https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/src/GenerateAzureDevOpsBuildManifest.cs

**Comment by mmitche** [comment]
@jonfortescue https://github.com/dotnet/core-eng/issues/9658 should be covered too. Folding that into this.

**Comment by mmitche** [comment]
@jonfortescue What is the status of this? Trying to figure out where I can help out on testing.

**Comment by mmitche** [comment]
@chcosta ETA for this is EOD next wednesday.

**Comment by mmitche** [comment]
I think this can be tested by completely removing it. We don't use the manifest generated by this: https://github.com/dotnet/arcade/pull/6528

We do need tests for the manifest generation in PushToAzureDevOpsArtifacts though https://github.com/dotnet/arcade/pull/6528/files#diff-2c204b59d01e73c04c5834f945685c3f74bbe862e33de4b58cd2ebc47f200cd1R150

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade/pull/6528

**Comment by jonfortescue** [comment]
@mmitche yeah, I had mentioned completely removing it as a possibility and I think that is probably the best path forward. I wasn't sure if I was missing something, but if we can delete code that we're just not using that would be A++

**Comment by mmitche** [comment]
Removed code. Will backport to release/5.0 after it makes a round through the normal master, https://github.com/dotnet/arcade/pull/6529
