### ISSUE TITLE
Exercise GenerateAzureDevOpsBuildManifest MSBuild task in Arcade Validation

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#6336]
The GenerateAzureDevOpsBuildManifest task was added to Publish.proj MSBuild project. We need to exercise this code path in Arcade Validation. 

Related PRs
- https://github.com/dotnet/arcade/pull/5442
- https://github.com/dotnet/arcade/pull/5517/
- https://github.com/dotnet/arcade/pull/5210/

Reference to code that needs testing
- https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Publish.proj
- https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/GenerateBuildManifest.proj
- https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.props

**Comment by mmitche** [comment]
I removed this task in master (also in 5.0, PR is currently open). It's unused.
