### ISSUE TITLE
[Maestro] Give subscriptions an off-switch

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#634]

**Comment by jcagme** [comment]
Does this mean disabling a subscription?

**Comment by jcagme** [comment]
I see that a `subscription` object has an `enabled` property. Is this what this issue was meant to track? @alexperovich @mmitche

**Comment by mmitche** [comment]
Yes, that is correct.

**Comment by jcagme** [comment]
Closing as this work is done
