### ISSUE TITLE
Exercise PushToAzureDevOpsArtifacts MSBuild Task in Arcade Validation

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#6341]
The PushToAzureDevOpsArtifacts was changed to support functionality for the Post Build Signing project. This code path needs to be exercised in Arcade Validation. 

Related PRs: 
- https://github.com/dotnet/arcade/pull/5517/

Code that needs testing coverage: 
- https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Publish.proj

**Comment by jonfortescue** [comment]
I think that this code path will also be covered in #6208.

**Comment by missymessa** [comment]
Unit tests were made for this task in #6344. #6208 should cover the E2E scenarios for Publish.proj.
