### ISSUE TITLE
Branch arcade for .NET 5

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6342]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Branch arcade for .NET 5.

**Comment by lukas-lansky** [comment]
We should merge https://github.com/dotnet/arcade/pull/6274 before proceeding. Also, @epananth, do you happen to know whether the channel creation docs as discussed in the e-mail are up-to-date? Thanks!

**Comment by epananth** [comment]
This is the channel creation doc-> https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#add-channel

@mmitche - should I add a link to this from Publishing.md? Or is there something else that I need to add here?

**Comment by lukas-lansky** [comment]
I will start now.

**Comment by mmitche** [comment]
> This is the channel creation doc-> https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#add-channel
> 
> @mmitche - should I add a link to this from Publishing.md? Or is there something else that I need to add here?

@epananth We should make sure we have details on how to add new channels into the publishing infrastructure too

**Comment by lukas-lansky** [comment]
@mmitche Should [this file](https://github.com/dotnet/arcade/blob/master/eng/common/templates/post-build/common-variables.yml) be updated with the new channel names (`.NET 5 Eng[...]`) and IDs given it already contains `.NET 3 Eng[...]`?

**Comment by mmitche** [comment]
@lukas-lansky Nope. That's for v2 publishing, which arcade doesn't need any longer. But we do need to add entries for publishing .NET 5 in PublishingConstants.cs, as seen for .NET Eng - Latest here:

https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/PublishingConstants.cs#L240-L260

I think you'll want:
- The Feed* parameters can be the same,
- PublishingInfraVersion.Next,
- akaMSChannelName: eng/net5 and eng/net5validation

**Comment by lukas-lansky** [comment]
@mmitche Thanks! (For documentation reasons:) Is it something that should be done before branching so both `master` and `release/5.0` contains the definition?

**Comment by mmitche** [comment]
Just master needs it (master is the branch publishing is run off of right now)

**Comment by lukas-lansky** [comment]
"Reset arcade Maestro++ subscriptions targeting .NET release branches to source from .NET Eng."

This is about sourcing from `.NET Eng 5` instead of `.NET Eng` for .NET 5 branches, right? @mmitche

**Comment by mmitche** [comment]
Yep!

**Comment by lukas-lansky** [comment]
So, I updated subscriptions targeting `release/5.0`/`release/5.0.1xx` to channel `.NET 5 Eng`. According to the list, this should be done. Please let me know @mmitche how to verify or whether you see something I should fix.

**Comment by lukas-lansky** [comment]
Everything seems fine to me. I obviously don't want to trigger the flow and rebuild all the .NET 5 release branches to verify completely. So still not completely sure.

@riarenas @ChadNedzlek Please let me know if you notice a problem that might be connected to this effort. Thanks!

**Comment by riarenas** [comment]
I took a look yesterday and thinks looked right. The default channels and subscriptions looked correct to me, but we'll know for sure the first time this needs to run.

Thanks @lukas-lansky

**Comment by riarenas** [comment]
Looks like we missed the subscription from arcade to arcade-validation for the new branch. I just created it
