### ISSUE TITLE
Need tests for BuildManifestUtil

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#6343]
BuildManifestUtil was modified during the Post Build Signing project. It needs to have unit tests to validate the changes that were made. 

Specifically, these methods need testing: 
- [x] CreateModelFromItems
- [x] CreateSigningInformationModelFromItems
- [x] CreateModel
- [x] ManifestBuildDataHasLocationInformation
- [x] All of SigningInformationModel
- [x] All of BuildModel (may be tested as a result of other functionality being tested, but listing it out here as changes were made to it and it's a small class)

Related PRs: 
- https://github.com/dotnet/arcade/pull/5517/

Code that needs unit tests: 
- https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed/src/BuildManifestUtil.cs
- https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/SigningInformationModel.cs
- https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/BuildModel.cs

**Comment by mmitche** [comment]
ETA EOD 11/18

**Comment by mmitche** [comment]
The build model itself already has a bunch of tests written by @jonfortescue, and I covered it a bunch more here https://github.com/dotnet/arcade/pull/6550.

This PR covers the rest of the items: https://github.com/dotnet/arcade/pull/6550
