### ISSUE TITLE
Need tests for PushToAzureDevOpsArtifacts

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#6344]
Changes were made to PushToAzureDevOpsArtifacts during the Post Build Signing project. We need to ensure the additional functionality is tested. 

Specifically, this method needs to be tested: 
- [ ] Execute

Related PR: 
- https://github.com/dotnet/arcade/pull/5517/

Code that needs to be unit tested: 
- https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToAzureDevOpsArtifacts.cs

**Comment by jonfortescue** [comment]
ETA EOD 11/11/2020

**Comment by missymessa** [comment]
Merged into master. Arcade Validation passed. https://dnceng.visualstudio.com/internal/_build/results?buildId=934612&view=results
