### ISSUE TITLE
[QCR] Testing pipeline should not open SDL Issues

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6362]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

The test pipeline uses older builds that may have SDL failures in them, but have been fixed in later builds. The testing pipeline would then open issues for those bugs, which causes the product teams to scramble, thinking that they have something they need to fix, only to not find the issue in question.

The sdl scripts have a -TsaPublish parameter that is set in the various repos' sdl-tsa-vars.config files, which we read in and then set as an environment variable. We read this file in as a list of strings, with each parameter on its own line. In the testing pipeline, we should look for -TsaPublish $True in the list of Tsa variables and then remove it so we do not publish the issues found. This way, we still get the coverage of running all of the steps in the test pipeline, without actually creating issues for the product teams.

**Comment by Tohron** [comment]
Merged: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/10796
Today I learned about YAML parameters :)

**Comment by adiaaida** [comment]
You and me both :)
