### ISSUE TITLE
Need tests for SignToolTask in SignTool

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#6365]
Changes were made to SignToolTask in SignTool during the Post Build Signing project. We need to ensure that the changes that were made have sufficient test coverage. 

- [ ] Validate bad path to WixToolset: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs#L204-L207
- [ ] ItemsToSign with OrderBy logic: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs#L226
- [ ] ItemsToSkipStrongNameCheck filtering logic: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs#L243
- [ ] ParseCertificateInfo: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs#L261-L266
- [ ] GetEnclosingDirectoryOfItemsToSign: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs#L268-L318
- [ ] ParseFileExtensionSignInfo: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs#L320-L360
- [ ] ParseStrongNameSignInfo: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs#L362-L416
- [ ] ParseFileSignInfo: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs#L418-L468

Related PRs: 
- https://github.com/dotnet/arcade/pull/6180
- https://github.com/dotnet/arcade/pull/6217

Code that needs to be unit tested: 
- https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs

**Comment by mmitche** [comment]
I think that we should probably have SignTool use the signing information model (construct from Items using BuildManifestUtil). That will then cover all of the signing info verification and it can be removed from SignTool.

**Comment by chcosta** [comment]
> I think that we should probably have SignTool use the signing information model 

I spent some time exploring this.  It's a fair sized refactor (involves pulling in 20+ source files from various projects), and I don't think we should tackle this given where we are in the dev cycle for this project.
