### ISSUE TITLE
Need tests for ZipData in SignTool

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#6366]
Changes were made to ZipData in SignTool during the Post Build Signing project. We need to ensure that the changes that were made have sufficient test coverage. 

- [ ] Validate bad path to WixToolset: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/ZipData.cs#L144-L148
- [ ] Validate non-zero exit code from BatchSignUtil.RunWixTool: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/ZipData.cs#L168-L172

Related PRs: 
- https://github.com/dotnet/arcade/pull/6180
- https://github.com/dotnet/arcade/pull/6216/

Code that needs to be unit tested: 
- https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/ZipData.cs

**Comment by mmitche** [comment]
@chcosta I'm taking this one. It may be covered somewhat already but will verify

**Comment by mmitche** [comment]
Covered by #6558
