### ISSUE TITLE
Certificate validation should take into account already signed items

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6388]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The nunit nupkgs are already signed with Nuget.org certs and should not be resigned. Because they are containers, they end up in the "filesToSign" set. When "None" is specified for the cert (don't replace the existing cert), we throw an error in `VerifyCertificates` becuase SignTool thinks all nupkgs should have a cert.

```
                else if (fileName.IsNupkg())
                {
                    if (fileName.SignInfo.Certificate == null)
                    {
                        log.LogError($"Nupkg {fileName} should have a certificate name.");
                    }

                    if (fileName.SignInfo.StrongName != null)
                    {
                        log.LogError($"Nupkg {fileName} cannot be strong name signed.");
                    }
                }
```

https://github.com/dotnet/arcade/pull/6314 may fix this issue, but we should be sure.

**Comment by mmitche** [comment]
@chcosta This is fixed, ya?

**Comment by chcosta** [comment]
Yep
