### ISSUE TITLE
Roslyn uses engineering dependency flow

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#640]
Documentation for dependency flow is currently being created / updated, here is some starter info

[Dependency flow](https://github.com/dotnet/arcade/blob/master/Documentation/DependenciesFlowPlan.md)

Add Version.Details.xml
- [ ] Create [Version.Details.xml](https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#engversiondetailsxml) file manually in repo

Channel mapping
- [ ] Create a [channel mapping](https://github.com/dotnet/arcade/blob/master/Documentation/Maestro/BuildAssetRegistry.md) between branch and channel name
  - manually (using REST API), documentation forthcoming

Create subscriptions
- [ ] Create [subscriptions](https://github.com/dotnet/arcade/blob/e20e8459bdae871bcafb731cf139210319d939d4/Documentation/Maestro/BuildAssetRegistry.md#subscription) 
  - manually (using REST API), documentation forthcoming

**Comment by alexperovich** [comment]
The casing of "Version.Details.xml" matters. It must match that casing exactly.

**Comment by jcagme** [comment]
Yes, I also found that wee not using the correct casing in https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#engversiondetailsxml. I'll create an issue on that

**Comment by jcagme** [comment]
Alex already did. https://github.com/dotnet/arcade/pull/747/files

**Comment by chcosta** [comment]
> We’ve been making steady progress here but I imagine we’re at least a month away. A lot of the changes we have to make have VS implications (net472 / netstandard2.0) and that slows us down considerably. Once we get over this hump though I think the finish line will be in sight.
\- Jared Parsons

**Comment by chcosta** [comment]
This is done
