### ISSUE TITLE
Publish using darc stage is not detecting failed promotion build

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#6403]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Publish using darc queues a build in Maestro promotion pipeline but it fails to detect if the promotion failed. 

Eg : https://dnceng.visualstudio.com/internal/_build/results?buildId=851119&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073

Failed promotion pipeline : https://dnceng.visualstudio.com/internal/_build/results?buildId=851947&view=results

[Edit]
 [Add a warning that Promotion pipeline may have failed till we fix this error]
1) Add-build-to-channel should detect if the promotion pipeline failed and fail the build

**Comment by epananth** [comment]
cc : @mmitche @riarenas @MattGal

**Comment by riarenas** [comment]
> Add work around to not to wait of the promotion pipeline build

This already exists right? there's a --no-wait parameter

**Comment by mmitche** [comment]
Yeah, the existing way builds are promoted is desirable. add-build-to-channel should not do the promotion itself unless --skip-assets-publishing is passed.

**Comment by epananth** [comment]
Yes the work around exists but we are not using it, so I was planning to add that for time being till I fix this the correct way ..

**Comment by riarenas** [comment]
Builds shouldn't pass --no-wait. It's correct behavior that they wait for the promotion build, it's just not correct that the step is saying it was successful.

**Comment by epananth** [comment]
If we are okay to show that build passed even when it failed for time being then we don't have to add the work around. I was thinking it will reduce the confusion if maestro promotion was successful or not cos then one will be forced to check the status of the build in the maestro pipeline and not rely on the msg in the logs.. 

I will edit the description.

**Comment by mmitche** [comment]
I think what we do today is wait for the promotion build to complete, then check that the build got assigned to the desired target channels. If it didn't, we say something went wrong and error out.

What we could do in the interim is detect the result of the promotion build. Then it would say: "the promotion build failed, but the build was still assigned to the target channels". Technically it might not be an error, so you could emit a warning. That would make this case more visible until we fix the root cause (that the symbol publishing isn't integrated into regular publishing)

**Comment by hoyosjs** [comment]
@epananth @mmitche do you know if there's any timeline for this?

It bit us pretty silently as we weren't publishing symbols:
- [Build](https://dev.azure.com/dnceng/internal/_build/results?buildId=871813&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073)
- [Failed Promotion](https://dnceng.visualstudio.com/internal/_build/results?buildId=872929&view=results)

cc: @mikem8361 @dotnet/dotnet-diag

**Comment by mmitche** [comment]
@epananth Is working on this right now and she'll have an ETA.

**Comment by epananth** [comment]
@hoyosis working on integrating symbol publishing with asset publishing, I am going to be testing my changes this week. So next week I should have this ready for you. I will keep you posted on my PR.

**Comment by hoyosjs** [comment]
Thanks @epananth

**Comment by epananth** [comment]
this got fixed
