### ISSUE TITLE
Maestro.Tasks Unit Tests - GetBuildDefaultChannelAsync

### ISSUE THREAD

**Issue by meganaquinn** [dotnet/arcade#6408]
Positive cases, validate that the correct subset of channels is returned
- [ ] Given all valid data (known good data set from a repo)
- [ ] Given GitHub source data
- [ ] Given AzDo source data
- [ ] Given both GitHub & AzDo source data
 
Negative cases, validate that the returned data is empty or a meaningful exception is thrown
- [ ] Given that both GitHub & AzDo are empty
- [ ] Given empty/null values in other properties that are logged/checked

**Comment by missymessa** [comment]
Parent epic closed. Closing.
