### ISSUE TITLE
Link to where the branch relationships are defined in automated merge PRs

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/arcade#6409]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

@dotnet-maestro-bot is sending nice PRs (like https://github.com/dotnet/msbuild/pull/5806). They have a great link to [the script that makes the PR](https://github.com/dotnet/arcade/blob/master/scripts/GitHubMergeBranches.ps1) (thanks!) but sometimes I'd like to know why a PR is happening. I remember that there's a repo somewhere with a bunch of data about the various repos and branches and relationships like "merge branch X into branch Y at cadence Z". But I don't usually remember exactly where that is.

Could it be linked in the PRs? Bonus points if the link goes directly to the line that cause the individual PR but just a static pointer to the file would be great.

**Comment by dagood** [comment]
You're looking for https://github.com/dotnet/versions/blob/master/Maestro/subscriptions.json, and yeah, should be easy enough to add the static URL.

Adding dynamic stuff gets more involved... would be a feature to add to https://github.com/dotnet/versions/tree/master/Maestro, working through it something like this:

1. Have the service figure out/store which lines of JSON defined the subscription.
2. Replace some token like `<subscriptions-json-lines>` with the value when it appears in a subscription.
   * `<trigger-repo>` works like this.
3. Handle the new arg in the `GitHubMergeBranches.ps1`.
4. Ask core-eng to deploy a new build of the Maestro service (not Maestro++).
5. Add the new `"SubscriptionsJsonLines": "<subscriptions-json-lines>"` arg mapping to each mirror subscription to link it all up.

**Comment by rainersigwald** [comment]
Yeah, the static URL should be fine. Doing it with detail sounds like more trouble than it's worth.
