### ISSUE TITLE
CoreClr uses engineering dependency flow

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#642]
Documentation for dependency flow is currently being created / updated, here is some starter info

[Dependency flow](https://github.com/dotnet/arcade/blob/master/Documentation/DependenciesFlowPlan.md)

Add Version.Details.xml
- [x] Create [Version.Details.xml](https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#engversiondetailsxml) file manually in repo

Channel mapping
- [x] Create a [channel mapping](https://github.com/dotnet/arcade/blob/master/Documentation/Maestro/BuildAssetRegistry.md) between branch and channel name
  - manually (using REST API), documentation forthcoming

Create subscriptions
- [x] Create [subscriptions](https://github.com/dotnet/arcade/blob/e20e8459bdae871bcafb731cf139210319d939d4/Documentation/Maestro/BuildAssetRegistry.md#subscription) 
  - manually (using REST API), documentation forthcoming

**Comment by hoyosjs** [comment]
The subscriptions are up and running for arcade and helix SDKs, will need to add more subscriptions as needed (CoreFX for tests, optimization, probably a dependency on self to consume ILAsm, etc.)

**Comment by hoyosjs** [comment]
Also, the build definitions are getting polished now. Will update thisissue as we start publishing assets to BAR

**Comment by RussKeldorph** [comment]
@sbomer FYI

**Comment by RussKeldorph** [comment]
@morganbr FYI

**Comment by chcosta** [comment]
This is done
