### ISSUE TITLE
[Darc/Maestro++] Remove powershell scenario tests now that there are c# tests with the same coverage

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6434]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The tests under https://github.com/dotnet/arcade-services/tree/master/src/Maestro/tests/Scenarios are not needed anymore. The remaining tests are adding 8 minutes to the post-deployment stage so we should remove all references to them.

**Comment by garath** [comment]
Spoke with @meganaquinn, she has agreed to take this
