### ISSUE TITLE
[QCR] Package dependency validation should only validate shipping packages

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6438]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Currently, we validate all packages that are in the packages directory in the drop. We should first check the manifest, and only validate those packages that are marked as shipping.

**Comment by MattGal** [comment]
Going to do this one and https://github.com/dotnet/arcade/issues/6439 at the same time.

**Comment by MattGal** [comment]
Created https://dnceng.visualstudio.com/internal/_git/dotnet-release/pullrequest/11331

**Comment by MattGal** [comment]
Changes merged and there does not seem to be a rollout process for this repo, closing.
