### ISSUE TITLE
[QCR] Package Icon Validation should only validate shipping packages

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6439]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Currently, we validate all packages that are in the packages directory in the drop. We should first check the manifest, and only validate those packages that are marked as shipping.

**Comment by MattGal** [comment]
Created https://dnceng.visualstudio.com/internal/_git/dotnet-release/pullrequest/11331

**Comment by MattGal** [comment]
Changes merged and there does not seem to be a rollout process for this repo, closing.
