### ISSUE TITLE
Publishing failure during aka.ms link creation

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#6444]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Publishing with darc job will yield the following error: 
```
The promotion build finished but the build isn't associated with at least one of the target channels. This is an error scenario. Please contact @dnceng. 
Problems using Darc to promote build 68632 to default channels. Stopping execution... 
```

Links to builds: 
- https://dev.azure.com/dnceng/internal/_build/results?buildId=863359&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073&l=34
- https://dev.azure.com/dnceng/internal/_build/results?buildId=863471&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073&l=38
- https://dev.azure.com/dnceng/internal/_build/results?buildId=863293&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073&l=34

According to the Maestro Build Promotion pipeline, the error is occurring during aka.ms link creation: 

Link to failure: https://dnceng.visualstudio.com/internal/_build/results?buildId=863536&view=results

```
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing. 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken) 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : at Microsoft.DotNet.Deployment.Tasks.Links.src.AkaMSLinkManager.<>c__DisplayClass16_0.<<CreateOrUpateLinkBatchAsync>b__0>d.MoveNext() in /_/src/Microsoft.DotNet.Deployment.Tasks.Links/src/AkaMSLinksManager.cs:line 258 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : --- End of stack trace from previous location --- 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : at Microsoft.DotNet.VersionTools.Util.ExponentialRetry.RunAsync(Func`2 actionSuccessfulAsync, CancellationToken cancellationToken) in /_/src/Common/ExponentialRetry.cs:line 48 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : at Microsoft.DotNet.Deployment.Tasks.Links.src.AkaMSLinkManager.CreateOrUpateLinkBatchAsync(IEnumerable`1 links, String linkOwners, String linkCreatedOrUpdatedBy, String linkGroupOwner, Boolean update, Boolean bucketed) in /_/src/Microsoft.DotNet.Deployment.Tasks.Links/src/AkaMSLinksManager.cs:line 248 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : at Microsoft.DotNet.Deployment.Tasks.Links.src.AkaMSLinkManager.<>c__DisplayClass14_0.<<CreateOrUpdateLinksAsync>b__0>d.MoveNext() in /_/src/Microsoft.DotNet.Deployment.Tasks.Links/src/AkaMSLinksManager.cs:line 152 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : --- End of stack trace from previous location --- 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : at Microsoft.DotNet.Deployment.Tasks.Links.src.AkaMSLinkManager.CreateOrUpdateLinksAsync(IEnumerable`1 links, String linkOwners, String linkCreatedOrUpdatedBy, String linkGroupOwner, Boolean overwrite) in /_/src/Microsoft.DotNet.Deployment.Tasks.Links/src/AkaMSLinksManager.cs:line 151 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : at Microsoft.DotNet.Build.Tasks.Feed.LatestLinksManager.CreateOrUpdateLatestLinksAsync(HashSet`1 blobsToPublish, TargetFeedConfig feedConfig, Int32 expectedSuffixLength) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/common/LatestLinksManager.cs:line 81 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestBase.PublishBlobsToAzureStorageNugetFeedAsync(HashSet`1 blobsToPublish, Dictionary`2 buildAssets, TargetFeedConfig feedConfig) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs:line 827 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestBase.HandleBlobPublishingAsync(Dictionary`2 buildAssets) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs:line 427 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestV3.ExecuteAsync() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs:line 156 
##[error].packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20514.1\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : (NETCORE_ENGINEERING_TELEMETRY=Publish) The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing. 
```

FR discussion link: https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1603470579274?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1603470579274&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1603470579274

We should: 
- [ ] Using Runfro (if possible) determine how often this error occurs. 
- [ ] Use the resulting data to determine a solution for hardening against this error in the future.

**Comment by missymessa** [comment]
Looks like in the last 100 runs on this pipeline there have been three instances of this failure, all yesterday between 6 to 10pm (PST). Maybe there was an outage with aka.ms during that time? 

https://dev.azure.com/dnceng/internal/_build/results?buildId=863536
https://dev.azure.com/dnceng/internal/_build/results?buildId=863462
https://dev.azure.com/dnceng/internal/_build/results?buildId=863384

**Comment by missymessa** [comment]
Next steps:
- [ ] Validate that the retry functionality in this code works as expected. (See code here: https://github.com/dotnet/arcade/blob/0c74bcb7cdaa8b224b8d5d37220b645a94c85ad4/src/Microsoft.DotNet.Deployment.Tasks.Links/src/AkaMSLinksManager.cs#L175)
- [ ] Determine if https://github.com/dotnet/arcade/blob/0c74bcb7cdaa8b224b8d5d37220b645a94c85ad4/src/Microsoft.DotNet.Deployment.Tasks.Links/src/AkaMSLinksManager.cs#L238 needs retry functionality, too. 
- [ ] Determine if there was an outage with aka.ms during that time.

**Comment by Tratcher** [comment]
Similar failures from Friday:
https://dev.azure.com/dnceng/internal/_build/results?buildId=864419&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073
https://dev.azure.com/dnceng/internal/_build/results?buildId=864547&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073

**Comment by missymessa** [comment]
> Similar failures from Friday:
> https://dev.azure.com/dnceng/internal/_build/results?buildId=864419&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073
> https://dev.azure.com/dnceng/internal/_build/results?buildId=864547&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073

These failures are due to 403 response from the Azure Blob Storage, not failures during aka.ms link creation, which is being tracked with this issue: https://github.com/dotnet/arcade/issues/6449

P.S. For future reference, the Publish to Darc step includes a link to the Maestro Build Promotion pipeline: 

![image](https://user-images.githubusercontent.com/47990216/97208036-ebd3b780-1777-11eb-8fd8-30b91cc0958b.png)

And then from there, you can see what the error is: https://dnceng.visualstudio.com/internal/_build/results?buildId=864495&view=logs&j=33961d73-1e6b-5306-1d3b-c6c083bff7de&t=577fb5b9-bfb7-5430-eb7a-5c5120b89b4d&l=245

**Comment by adiaaida** [comment]
When we get a timeout from HttpClient, it throws a TaskCancelledException. We only catch on HttpRequestException. To harden against this, we should also catch the TaskCancelledException, so that we can retry.

**Comment by adiaaida** [comment]
I have not been able to find evidence of an aka.ms outage, so I think this was just transient.
