### ISSUE TITLE
[QCR] [Signing] Push-to-drop does not publish signed files

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6451]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In the signing ring/step, we copy the newly signed files to {{ outputDir }}/signed/{{ path }}, but push-to-drop pushes files that are just in the {{ outputDir }}\shipping and {{ outputDir }}\nonshipping directories (ie, not the ones that have been copied to the signed directory). Either signing should copy files back to their original location, overwriting the originals, or push-to-drop should build the drop that we upload to azure build artifacts from the signed directory.

**Comment by chcosta** [comment]
I thought @jcagme was working on this or had an open issue tracking it

**Comment by adiaaida** [comment]
If there's already an issue for this, feel free to close this as dupe.

**Comment by chcosta** [comment]
I can't find a specific issue.  I'll work on this after I get the checksums PR up later today (hopefully)
