### ISSUE TITLE
Android XHarness tests failing in Arcade CI

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#6455]
- [ ] This issue is blocking
- [ ] This issue is causing unreasonable pain

### Context
- Both Windows test legs in the [arcade-ci pipeline](https://dev.azure.com/dnceng/public/_build?definitionId=208&_a=summary) that runs for PRs in Arcade have a step called **XHarness Android Helix Testing**.
- This step downloads a an Android apk application from our storage account and runs it using the Helix SDK.
- This flow tests executing XHarness payloads using the SDK.

We decided to mark this build step with `continueOnError` to not fail the build, because:
- Android was WIP,
- the apk was built a long time ago (around April) and can sometimes crash,
- the infrastructure for running Android emulators is evolving and fixes were done (increased RAM...), it was unstable in the beginning.

### Problem
The step fails quite often and causes noise and in case we would actually break the SDK, it would be possible to publish a broken version of Helix SDK because we might not notice this.

### To be done
We can update the apk with a newer one and see if this and the infrastructure updates that were done would make this build step stable enough to remove the `continueOnError` flag.
If not, we should think about disabling the step or adding a retry or so.. to reduce the noise.

**Comment by premun** [comment]
Also discussed here https://github.com/dotnet/arcade/pull/6032

**Comment by premun** [comment]
@MattGal feel free to close this ^^

I wasn't sure if you left the other opened to keep an eye out for few more builds or it was closed already too

**Comment by MattGal** [comment]
Sure, I was tracking via https://github.com/dotnet/core-eng/issues/11268 but it's been long enough to close that one too.
