### ISSUE TITLE
Maestro.Tasks Unit Tests - GetManifestAsAsset

### ISSUE THREAD

**Issue by meganaquinn** [dotnet/arcade#6473]
Positive cases, validate the contents of the AssetData and that it has been added to blobSet
- [x]  Given a list of AssetData with a location string and a manifest file that exists
- [x]  Given a list of AssetData with a location string and a manifest file that does not exist
- [x]  Given a golden path where the AssetVersion is set
- [x]  Given a golden path where the AssetVersion is not set, but there is a non-shipping asset with a version
- [x]  Given a golden path where the AssetVersion is not set and there is not a non-shipping asset with a version
- [x]  Given an empty list of AssetData (expect an empty list returned)
- [x]  Given a null location

Negative cases, expect a meaningful exception
- [x]  Given other null/empty arguments (if allowed by caller)
- [x]  Given blobSet that already has a key with the same name as an asset (if possible to get into that state)

**Comment by chcosta** [comment]
What's this issue for?

**Comment by missymessa** [comment]
@meganaquinn, can you update this issue to list the areas the tests will cover? Perhaps a bulleted list to track progress with it? Thanks!

**Comment by meganaquinn** [comment]
@missymessa @chcosta I updated this issue and added/updated issues for the rest of the methods in the test plan. This is the one I'm working on today.

**Comment by meganaquinn** [comment]
https://github.com/dotnet/arcade-services/pull/1480
