### ISSUE TITLE
All Types Marked as Missing

### ISSUE THREAD

**Issue by SirBuckinghamVI** [dotnet/arcade#6477]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

All types in my project are marked as missing from the implementation with a TypesMustExist error. I am using version 5.0.0-beta.20224.2. This is a new setup; I just set the ResolvedMatchingContract to a dll I built just before installing the package. This is a library targeting .NET Standard 2.0. The project does reference some nuget packages.

**Comment by garath** [comment]
@ericstj Can you help with this?

**Comment by ericstj** [comment]
@SirBuckinghamVI it sounds like you're trying to use APICompat.  Can you share more information about how you are using it?  If possible point to a repro project?

**Comment by ericstj** [comment]
Closing due to lack of response.  If you'd like help please reopen and provide more info about your scenario as requested.
