### ISSUE TITLE
Update handling of HttpClient timeout exceptions when we upgrade to .NET 5+

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6485]
In a lot of places where we retry on HttpClient timeouts, we catch TaskCanceledException as that is what HttpClient throws when it times out. See: https://github.com/dotnet/runtime/issues/21965.

As of .NET 5, this behavior has been modified to have the TaskCanceledException contain an inner exception of TimeoutException when the task was canceled due to a timeout: https://github.com/dotnet/runtime/pull/2281. When we upgrade our services to .NET 5+, we should also go back to the places where we catch TaskCanceledException for HttpClient and check the inner exception.

**Comment by garath** [comment]
Triage: This work would come out when Arcade properly implements cancellation.
