### ISSUE TITLE
BARViz should show the number of commits behind for a given dependency

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6486]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

If a build of an older commit successfully finishes **after** a newer commit is created and maybe built (or for instance, the newer commit was never built, or a retry caused the older build to appear to finish after), the older build will be "latest". This is intentional and correct, and really there's no other way to handle this case. However, we should highlight on the BARViz UI that while a repo has the latest build, it may be some commits behind on the dependency, which would lead to an investigation to determine whether that was the desired case.

This bit us in 5.0 GA.

**Comment by mmitche** [comment]
I'd suggest showing this as perhaps a suffix in the "Build Staleness" column. Maybe change that to "Staleness" and list each entry as: `N Builds, M commits`

Since it's always either "latest" or "behind" the behind text can probably be remvoed.

**Comment by adiaaida** [comment]
Closing because the parent Epic was closed. If you believe this issue should still be worked on, please re-open.
