### ISSUE TITLE
Merged Manifest path tests

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#6488]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Test merged manifest path for various cases. It will make it easier to iterate over the changes. 

cc: @meganaquinn @mmitche

**Comment by mmitche** [comment]
@meganaquinn This is the tests that I was mentioning in your arcade-services PR.

**Comment by missymessa** [comment]
Parent epic closed. Closing.
