### ISSUE TITLE
Investigate slow publishing

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6493]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

A long while back, publishing was changed to push packages and blobs in parallel. Looking at recent publishing, it seems pretty clear that this is no longer happening. I **think** it may still be happening for blobs, but it is almost certainly not happening for packages. It may have happened as part of the v3 publishing refactor.

It might just be the second await https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs#L576.

It could also be that this should be changed to parallel foreach
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs#L570, the client throttle should be removed (replaced with the parallel foreach's options)

**Comment by riarenas** [comment]
@mmitche do you think there's more to do here?

**Comment by mmitche** [comment]
Nope, this appears to be resolved.
