### ISSUE TITLE
Make "Publishing Using Darc" job's timeout configurable

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#6496]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://dev.azure.com/dnceng/internal/_build/results?buildId=871170&view=results failed because the publishing step took longer than 60 minutes. Looking at the post-build.yml I don't see an extensibility point yet to configure the publishing timeout: https://github.com/dotnet/arcade/blob/ba32978d76e590e1a5cde6b754eb4e9b8d212c73/eng/common/templates/post-build/post-build.yml#L254

cc @Chrisboh @safern @jkoritzinsky

**Comment by safern** [comment]
Wow it took 55 mins to publish. Did we get throttled? Are the package being published in parallel?

https://dnceng.visualstudio.com/internal/_build/results?buildId=871272&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a

cc: @mmitche

**Comment by mmitche** [comment]
I think somewhere recently the parallel package publishing got turned off...I filed an issue for this yesterday https://github.com/dotnet/arcade/issues/6493

**Comment by mmitche** [comment]
Note that stable publsihing will always be slower becuase the symbol packages have to be pushed to a nuget feed (because they have stable versions)

**Comment by mmitche** [comment]
No need for a timeout. Publishing should be that long. Fixed by https://github.com/dotnet/arcade/pull/6500

**Comment by mmitche** [comment]
Dupe of #6493
