### ISSUE TITLE
"Prepare artifacts and upload to build" step runs nearly two hours and times out

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#6499]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://dev.azure.com/dnceng/internal/_build/results?buildId=871307&view=logs&j=4d50a8bf-a143-51c7-5cc8-defff437e23b&t=d6d13245-d57d-5d5b-1534-614c370d18c6 shows that signing took about two hours and then timed out. I'm unsure how signing of 2690 files can take two hours.

cc @mmitche

**Comment by mmitche** [comment]
It can if ESRP has a slowdown or if it holds a file for scanning, The signing logs may have more info.

**Comment by ViktorHofer** [comment]
Your call whether we should follow-up on this.

**Comment by mmitche** [comment]
Not too much to follow up on here, and seems to have resolved itself.

**Comment by garath** [comment]
Nothing to follow-up on here, closing. 

We're tracking additional telemetry on how long packing and unpacking takes as part of the signing epic, so trends will be more clear.

**Comment by ViktorHofer** [comment]
Timed out again: https://dev.azure.com/dnceng/internal/_build/results?buildId=881690&view=logs&j=4d50a8bf-a143-51c7-5cc8-defff437e23b&t=d6d13245-d57d-5d5b-1534-614c370d18c6. Reopening.

**Comment by MattGal** [comment]
@ViktorHofer I've reached out to the folks involved to find out if there was an ESRP outage in this time frame, but I don't think there's anything that can be done for one-off timeouts like this further than increasing your timeout and being patient.  We don't control the service being talked-to here at all, as well as novel binaries often require manual intervention in the signing service, seeming like timeouts while this happens (anything which triggers anti-virus checks, for instance).   

Given this, I think the best you can do is increase your timeout for the pipeline.  Let's chat offline if you have concerns about this.

**Comment by MattGal** [comment]
@ViktorHofer the door's still open to chat at any time, but I'm going to close this issue.  I suggest you should increase the timeout on this pipeline as well as adjust expectations on the partner teams as they are constantly fighting to keep the service up, it just has slowness. 

Some notes:
- When you are seeing slowness in signing, you can check here for ongoing ESRP issues.  Yes, this query is quite noisy.
  https://portal.microsofticm.com/imp/v3/incidents/omnisearch?searchString=s:PRSS%20-%20Sign%20-%20ESRP

- Based on timing, there's a decent chance this was https://portal.microsofticm.com/imp/v3/incidents/details/213353140/home ... i.e. machines filled up their disks and throughput was affected.
