### ISSUE TITLE
Publishing v3 doesn't pass addintional parameters

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/arcade#6514]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

`symbolPublishingAdditionalParameters` are not getting passed to the the PS1 scripts so darc won't add the build appropriately. This caused a failure that got swallowed silently because of #6403

**Comment by riarenas** [comment]
Which parameters do you need to pass through that? Mostly wondering if we can generalize the case so you don't need to pass anything extra, or if this is definitely something where we need an exception. Special cases make it harder to write shared tooling,
