### ISSUE TITLE
Arcade-richnav pipeline shows error failing to upload index file

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6565]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

I merged a change in arcade and got an unexpected email about a pipeline partially succeeding:
https://dev.azure.com/dnceng/public/_build/results?buildId=887638&view=results

```
{
  "commitId": "7A2F81B46EC807FE5DF62F6DF9C26BD3DAEE4FCF",
  "oldState": "InProgress",
  "newState": "CompleteIndex"
}
##[error]Error: Failed to upload index file after 1 retry.
```

I'm not sure what the implications of this are, but it looks like the pipeline has been failing consistenly since this run on 9/13: https://dev.azure.com/dnceng/public/_build/results?buildId=885675&view=results

Is this something we need to fix?

**Comment by riarenas** [comment]
@alexperovich do you know anything about this? I seem to recall you were added to some richnav PRs?

**Comment by alexperovich** [comment]
I do not know how it works or how to fix it. One of the richnav people will need to look at it. This looks like just a failure in the task.

**Comment by riarenas** [comment]
This went away. Whatever was broken in the task has been fixed.
