### ISSUE TITLE
Maestro.Tasks Unit Tests - GetBuildDependenciesAsync

### ISSUE THREAD

**Issue by meganaquinn** [dotnet/arcade#6584]
GetBuildDependenciesAsync

Positive cases, validate that the correct subset of BuildRefs is returned
- [ ]  Given golden path (build is found and it has a set of dependencies that have all relevant values filled in)
- [ ]  Given build that has product dependencies
- [ ]  Given build that has tool dependencies
- [ ]  Given a build with both product & tool dependencies
- [ ]  Given a build with non-required fields empty (should have no impact on the returned list)
- [ ]  Given one dependency with no builds found (GetBuildId returns null & this method logs then continues, return an empty list )
- [ ]  Given a build with no dependencies (return an empty list)

Negative cases, expect a meaningful exception is thrown
- [ ]  Given an empty RepoRoot
- [ ]  Given that the RepoRoot is not defined in the input file
- [ ]  Given an incorrect (invalid) RepoRoot

**Comment by missymessa** [comment]
Parent epic closed. Closing.
