### ISSUE TITLE
Maestro.Tasks Unit Tests - GetBuildId

### ISSUE THREAD

**Issue by meganaquinn** [dotnet/arcade#6585]
GetBuild

Positive cases, validate that the correct buildId is returned and that the correct assets have been added to the assetCache
- [ ]  Golden path (given assets have a matching commit, buildId has a value, and build has assets in it aren’t in the given list)
- [ ]  Given assets are the only assets for build

Negative, expect a meaningful expection is thrown
- [ ]  Given assets don’t have a matching commit so no buildId is found (no exception, return null)
- [ ]  Given assets are missing field values that are expected/used in logic
- [ ]  Given null/empty arguments (if possible from caller)

**Comment by meganaquinn** [comment]
I pushed what I have to here: https://github.com/meganaquinn/arcade-services/tree/getBuildIdTests

**Comment by missymessa** [comment]
Parent epic closed. Closing.
