### ISSUE TITLE
Maestro.Tasks Unit Tests - GetBuildManifestsMetadata

### ISSUE THREAD

**Issue by meganaquinn** [dotnet/arcade#6586]
***GetBuildManifestsMetadata - was modified as part of the signing update

Positive cases, validate contents of returned values (buildsManifestMetadata, signingInfo, manifestBuildData)
- [ ]  Given a single manifest
- [ ]  Given multiple manifests
- [ ]  Given no manifests

Negative cases, expect a meaningful exception is thrown
- [ ]  Given a file that isn’t a manifest
- [ ]  Given badly formatted XML
- [ ]  Given an empty manifest file (valid XML formatting but with nothing in it)
- [ ]  Given a set of manifests missing various pieces of expected data (examples below, not a complete matrix)
- [ ]  Manifest without any assets listed
- [ ]  Manifest that has an asset that contains a package with no version set
- [ ]  Manifest that does not contain any Blobs
- [ ]  Manifest with a blob that does not have a version set
- [ ]  Manifest with a blob that does not have any assets
- [ ]  Given two manifests that have different attributes (expect exception thrown in method)

**Comment by missymessa** [comment]
Parent epic closed. Closing.
