### ISSUE TITLE
Maestro.Tasks Unit Tests -  LookingForMatchingGitHubRepository

### ISSUE THREAD

**Issue by meganaquinn** [dotnet/arcade#6587]
LookingForMatchingGitHubRepository

 Positive cases, validate that the BuildData is updated with the correct information
- [ ]  Given a BuildData that is based on GitHub (non-mirrored repo)
- [ ]  Given a BuildData that is based on AzDo (mirrored repo) where GitHub is the current mirror
- [ ]  Given a BuildData that is based on AzDo (mirrored repo) where AzDo is the current mirror

 Negative cases, expect a meaningful exception
- [ ]  Given a BuildData with an invalid url for the AzureDevOpsRepository value
- [ ]  Given null/empty arguments (if possible from caller)

**Comment by missymessa** [comment]
Parent epic closed. Closing.
