### ISSUE TITLE
Maestro.Tasks Unit Tests - CreateAndPushMergedManifest

### ISSUE THREAD

**Issue by meganaquinn** [dotnet/arcade#6588]
***CreateAndPushMergedManifest - was modified as part of signing changes

 Positive cases, validate content of manifest file
- [ ]  Given a list of compatible assets with SigningInformation & ManifestBuildData within expected values
- [ ]  Given assets that are blobSet
- [ ]  Given assets that are not in blobSet
- [ ]  Given assets where some are in blobSet and some are not
- [ ]  Given assets that are non-shipping
- [ ]  Given assets that are shipping
- [ ]  Given other empty/null arguments (as allowed by caller)
~- [ ]  Given a mergedManifestPath that does not exist~
~- [ ]  Given a mergedManifestPath that already contains a file with the same name~

 Negative cases, expect a meaningful exception
~- [ ]  Given null SigningInformation~
~- [ ]  Given SigningInfo that has some null/empty values~

**Comment by meganaquinn** [comment]
I refactored the method as the first step in creating the tests, it no longer does xml or file creation, so I crossed out related test cases.

**Comment by meganaquinn** [comment]
This is blocked on the arcade changes (which are blocked on review), however the newest version was pushed to the remote branch.

**Comment by missymessa** [comment]
Tests merged. Closing.
