### ISSUE TITLE
Maestro.Tasks Unit Tests - SigningInfoToXml

### ISSUE THREAD

**Issue by meganaquinn** [dotnet/arcade#6589]
***SigningInfoToXml (this is going to be a fine line between testing our logic and testing XDocument, so these test cases are very likely to evolve as they're written) - was modified as part of signing changes

 Positive cases, validate content of the returned XElement
- [ ]  Given a SigningInformation with a single one of each of the types parsed and all values filled in
- [ ]  Given a SigningInformation with multiple of the types parsed, all of which contain the expected values

 Negative cases, expect a meaningful exception
- [ ]  Given a SigningInformation missing various top level values that are assumed present (if allowed from caller)
- [ ]  Given a SigningInformation with nested values missing

**Comment by missymessa** [comment]
Parent epic closed. Closing.
