### ISSUE TITLE
5.0.0 dotnet/runtime official pipeline build is gone: "Build not found."

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#6615]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

I went to the dotnet/runtime 5.0.0 official build to try to trace something down, but it says "Build not found":
https://dev.azure.com/dnceng/internal/_build/results?buildId=858751

I assume this is because the build wasn't marked as "retained", and it got garbage collected by AzDO. 😅 

To try to get there, I looked at the released commit and clicked on the official build in the "linked builds" button:
https://dev.azure.com/dnceng/internal/_git/dotnet-runtime/commit/cf258a14b70ad9069470a108f13765e0e5988f51

> ![image](https://user-images.githubusercontent.com/12819531/100024066-b8527000-2dab-11eb-93c3-d3b73e5747ec.png)

then 

> ![image](https://user-images.githubusercontent.com/12819531/100024110-cbfdd680-2dab-11eb-9939-e8563d0597a3.png)

* Is there some infra that's meant to have retained this build, but failed?
* Is there no infra to retain builds?
* (Is something entirely different going on, and I'm not just finding the right build?)

I went looking for this for source-build, but retaining these can be useful to root-cause bugs outside of source-build too.

**Comment by riarenas** [comment]
Hi Davis, we took a look at the settings and such:

There's no infra outside of the azure devops built in retention options to retain builds. 

These are the current settings that we settled on in order to keep costs sustainable.

![image](https://user-images.githubusercontent.com/23242101/101093899-63afb180-3570-11eb-8474-90a32b2ba95a.png)

So it just looks like that build was old enough to no longer be retained.

**Comment by dagood** [comment]
> There's no infra outside of the azure devops built in retention options to retain builds.

I did a quick search and it looks like implementing this is tracked as part of https://github.com/dotnet/arcade/issues/5068 and https://github.com/dotnet/arcade/issues/5069. Good to know the current state though--unfortunate these builds are being lost. 😕
