### ISSUE TITLE
Support for performance optimization data collection and application

### ISSUE THREAD

**Issue by shawnro** [dotnet/arcade#6619]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The performance optimization process, being driven by the performance team, will be changing so that it is lower cost and more similar to the rest of the build/release process.  This includes creation of instrumented binaries and application of training data occurs as part of the repo builds.  Generation of data is currently planned to be done in a centralized manner, likely as part of the release pipeline.  Eng Services will need to provide necessary support for dependency flow and machine configuration for this end-to-end process.  More details to come.

**Comment by markwilkie** [comment]
Closing in favor of https://github.com/dotnet/arcade/issues/7243
