### ISSUE TITLE
Deb/Rpm targets don't construct a non-shipping version

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/arcade#6624]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The targets for producing Deb and Rpm packages in Microsoft.DotNet.Build.Tasks.Installers don't correctly produce a non-shipping version number for the package file name.

**Comment by ViktorHofer** [comment]
@jkoritzinsky will you be the one looking into this?

**Comment by jkoritzinsky** [comment]
I can take a look.
