### ISSUE TITLE
Allow less strict SDK version in local developer cmd

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/arcade#6636]
Currently `dotnet-install` invoked by `build.cmd` requires strict SDK version. It can be a pain if the developer has moved to a higher global installed version. Downloading with `dotnet-install` is very slow (~10KB/s) for certain network.

`build -restore` can follow the roll forward setting, but `build -vs` doesn't for now.

**The less-strict behavior can be explicit or implicit.** Local developer doesn't require determinism all the time.

**If possible, the install script should download from official download source.** Downloading from https://dotnet.microsoft.com/download is typically fast, because it has decent CDN.

**This should also apply to other repos in dotnet organization.**

**Comment by alexperovich** [comment]
This is a bit strange. We should have roll-forward enabled in the global.json, and build.cmd should not download a specific sdk for developer machine builds if you have a compatible sdk already installed. The builds on azure pipelines need to download the sdk so we don't get broken by surprise bugs, but developer machines should use whatever is installed if it is compatible.

**Comment by jkotas** [comment]
How do you determine what is compatible?

For dotnet/runtime, I believe that it has been a common situation that the build does not work with latest .NET SDK preview build and that there are fixes required to fix that.

**Comment by ViktorHofer** [comment]
As far as I can see today's it's a direct match and doesn't respect rollforward policies specified in the global.json file: https://github.com/dotnet/runtime/blob/0079d87d84e0e4067fc8d74a651450efbd3fafaa/eng/common/tools.ps1#L149.

**Comment by alexperovich** [comment]
We need to at least honor whatever roll-forward policy is present. If runtime needs a more strict policy then that's fine, but in general a developer in a repo shouldn't need to download a new version of the cli for their builds if they have a higher patch version installed.

**Comment by ViktorHofer** [comment]
> For dotnet/runtime, I believe that it has been a common situation that the build does not work with latest .NET SDK preview build and that there are fixes required to fix that.

That was true in some cases but we intentionally allow to [build with a newer SDK even across major versions](https://github.com/dotnet/runtime/blob/0079d87d84e0e4067fc8d74a651450efbd3fafaa/global.json#L4-L5). We are usually on the latest stable and if a preview SDK doesn't work already, we want to know that.

> We need to at least honor whatever roll-forward policy is present.

Right that's what I would like to see fixed in the tools.ps1/sh Arcade scripts and I believe this issue is about.

**Comment by missymessa** [comment]
Epic closed. Let's retriage.
