### ISSUE TITLE
[QCR] Allow pipeline to handle partial releases

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6640]
There are instances where the pipeline should allow for partial releases. In those cases, the runtime/aspnetcore/windowsdesktop components may have already been released and we can't assume that they exist. If that's true, we can't assume that the following components exist:

* ANCM versions
* Runtime, aspnetcore, windowsdesktop versions

However, all of these things are required, so the pipeline needs to be able to either take a hand crafted config, or take information supplied at queue time to use to build the config file.

**Comment by adiaaida** [comment]
More info from @mmitche:

> It’s not a partial release, but it’s an installer that contains a runtime and many other components that have already been released (see https://dev.azure.com/dnceng/internal/_build/results?buildId=939896&view=logs&j=40e1e683-ea82-5be9-b25e-899b65e1c0cb&t=94a692ec-20f2-55dd-1884-cf0cad1763a4&l=1557) so the gather drop stage skips downloading all those released builds. This then confuses the release pipeline.
>  
> The reason this is done is that if you do NOT skip released builds, incremental servicing over time will build up a huge variety of runtimes and other that are “in” the product. This is because the dependency tracking systems cannot determine how a dependency is used, only that it is. So if aspnetcore depends on 3 packages out of runtime, say Foo, Bar and Baz, and we ship only one of them on each servicing release, there will be 3 runtime builds referenced by the end of month 3. But, the problem is that two of those packages have already been shipped. You can’t ship them again. So the dependency system eliminates this problem by marking previously released builds and just skipping putting them in the drop.
>  
> @Michelle McDaniel is the primary reason that the partial releases thing doesn’t work is that we cannot build up the release config based on the manifest? How is it built up today?
>  
> What if we built up the release config based on dependency information (that we would encode into the manifest)? E.g. installer references X Y and Z dependencies, and Y is the one that corresponds to the ANCM version.

**Comment by MattGal** [comment]
https://github.com/dotnet/arcade-services/pull/1507/files does the arcade-services side of the change, I will put up the change(s) for dotnet-release separately after this merges (in case anything changes from this review)

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-release?version=GBarcade-6640 is a mock-up (it works, but is based off an unmerged PR).   Since this now won't possibly be usable until the next arcade-services rollout, I'm putting this in tracking and doing an FR issue

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-release/pullrequest/12427 should do the trick; it still should not be merged until the arcade-services rollout this Wednesday.

**Comment by MattGal** [comment]
I ... probably (?) broke this and am addressing it via https://github.com/dotnet/core-eng/issues/11960

**Comment by MattGal** [comment]
Based off discussion in the corresponding dotnet-release PR, I created https://github.com/dotnet/arcade-services/pull/1527 which allows us to optionally always download (and find in a special place in the manifest) arbitrary blobs that are part of gather-drop.

**Comment by MattGal** [comment]
keeping this WIP until the aka.ms link generation for internal builds is sorted.

**Comment by MattGal** [comment]
This rolled out yesterday
