### ISSUE TITLE
Generate aka.ms links in the release pipeline on release day

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6641]
To satisfy a whole host of new scenarios in dotnet-install, we need to generate aka.ms links on release day to point to newly released bits.

Doc defining scenarios: https://microsoft-my.sharepoint.com/:w:/r/personal/vshubina_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B481C0C24-D630-4E04-846E-874B7AE66EDE%7D&file=%5Bdotnet-install%5D%20aka.ms%20links%20suggested%20structure.docx&nav=eyJjIjo1OTQ3ODM5MzF9&action=default&mobileredirect=true

Specifically in this doc, see the aka.ms section. This issue is concerned with:
- Suggested aka.ms link structure for current channel/version(UC 2)
- Suggested aka.ms link structure for LTS channel/version(UC 1):
- Suggested aka.ms link structure for specific version with quality for 5.0+ (UC3 and UC4), **where "preview" is the quality level**
- Suggested aka.ms link structure for specific version without quality (UC3):

**Comment by adiaaida** [comment]
Closing this one in favor of the broken down issues #6849 and #6850.
