### ISSUE TITLE
Generate aka.ms links in the staging pipeline

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6642]
This covers generation of aka.ms links at different points in the staging pipeline, specifically when new builds that are post-build signed are finished signing, and when new builds are validated.

See https://microsoft-my.sharepoint.com/:w:/r/personal/vshubina_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B481C0C24-D630-4E04-846E-874B7AE66EDE%7D&file=%5Bdotnet-install%5D%20aka.ms%20links%20suggested%20structure.docx&nav=eyJjIjo1OTQ3ODM5MzF9&action=default&mobileredirect=true

This issue covers the aka.ms generation for the following section:
- Suggested aka.ms link structure for specific version with quality for 5.0+ (UC3 and UC4), **where the quality level is "signed" or "validated"**

**Comment by adiaaida** [comment]
How is this different from https://github.com/dotnet/arcade/issues/6641?

**Comment by mmitche** [comment]
These are about pre-release links, the other one is about release day links. I may have use the wrong language when talking about release pipeline vs. staging pipeline?

**Comment by adiaaida** [comment]
I *think* I understand. I just wanted to make sure this would be publishing aka.ms links possibly 3 times: once post-sign, once post-validation, and once in the final release process.

This isn't talking about doing it on the nightly runs for individual repos, correct? Only full builds we're running through Stage-DotNet.

**Comment by mmitche** [comment]
> This isn't talking about doing it on the nightly runs for individual repos, correct? Only full builds we're running through Stage-DotNet.

Correct

> I think I understand. I just wanted to make sure this would be publishing aka.ms links possibly 3 times: once post-sign, once post-validation, and once in the final release process.

Yep

**Comment by adiaaida** [comment]
I have broken down this issue into its component parts (signed, validated), so closing this in favor of those issues: #6920
