### ISSUE TITLE
Generate different aka.ms links in build publishing

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6643]
This is about applying the changes specified here:

https://microsoft-my.sharepoint.com/:w:/r/personal/vshubina_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B481C0C24-D630-4E04-846E-874B7AE66EDE%7D&file=%5Bdotnet-install%5D%20aka.ms%20links%20suggested%20structure.docx&nav=eyJjIjo1OTQ3ODM5MzF9&action=default&mobileredirect=true

Specifically, this is about altering aka.ms link generation in build publishing to be of the form specified in sections:
- Suggested aka.ms link structure for specific version with quality for 5.0+ (UC3 and UC4), **where quality is "daily"**.

This just means flatting the path to the files and also altering the base part of the links to <product band>/daily.

**Comment by adiaaida** [comment]
PR: https://github.com/dotnet/arcade/pull/6872
