### ISSUE TITLE
Define quarantine process for single tests

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#6661]
We need to document the process by which a test can be quarantined

**Comment by alexperovich** [comment]
I am in favor of using test category attributes on the tests to handle quarantining. Including or excluding tests based on categories is built-in to the test runners so we don't have to shoehorn in runner support for something else. Attributes also make it easy for a dev to tell if a test is quarantined or not because the "quarantine status" is in the code, right on the test method.

**Comment by ChadNedzlek** [comment]
Me too, mostly because that's essentially the supported way to do it.  Every test runner out there as support of this concept, so it will work for everyone, no matter what.

**Comment by ChadNedzlek** [comment]
It _does_ make automation difficult (and it can be difficult to answer the question of "what are all the tests that are quarantined right now"). So we'll need answers to questions like that if we go with categorization.

**Comment by alexperovich** [comment]
Its not too difficult to automate "add some attributes to these methods" though its not trivial.

**Comment by markwilkie** [comment]
> "what are all the tests that are quarantined right now"

Yes - this question really must be answerable reasonably.

**Comment by sunandabalu** [comment]
It also requires a PR to quarantine / unquarantine with the use of attributes / annotations, is there a way we can achieve this where a PR is not required? Even if there needs to be a PR, maybe like a easy configuration where you can turn off / on quarantining at varying level?

**Comment by markwilkie** [comment]
FWIW - I sorta like the notion of a PR as it gives an audit trail.  Not super important at least to me....

**Comment by sunandabalu** [comment]
> FWIW - I sorta like the notion of a PR as it gives an audit trail. Not super important at least to me....

It was one of the pain points mentioned in ASPNETCore's experience with quarantine pipeline. While we are exploring options especially keeping future automation in mind, its important to draw from lived experience of folks who have been doing the quarantining via annotations IMHO.

**Comment by markwilkie** [comment]
Ah - I see.  Yea, good point @sunandabalu

**Comment by ChadNedzlek** [comment]
At least one person on runtime has more or less said anything that wasn't a code solution was a non-starter, and I don't have a strong preference one way or the other.  If it's something that lives outside the code, then it definitely needs historical data, so we can ask data about the past.  It could also make reproduction weird... if I run this same build again, the behavior might be different (because tests haved moved into/out of quarantine) which could be confusing.

**Comment by ChadNedzlek** [comment]
If it's _not_ in source code, then the flaky test stuff in AzDO solves almost all of the problem (though auditing get's weird... I don't know what it records/doesn't, we'd have to explore it more)

**Comment by ChadNedzlek** [comment]
This is defined via the "ignoreRules" in https://github.com/dotnet/core-eng/pull/12078
