### ISSUE TITLE
Publishing to multiple channels is failing. 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#6669]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Eg : https://github.com/dotnet/arcade/issues/6616#issuecomment-738948260 

f-sharp build is failing during publishing step. I was able to do darc add-build-to-channel and get that published but we need to investigate if its cos of the multiple channels parsing or something else. 

Look for the target channels here -> https://dnceng.visualstudio.com/internal/_build/results?buildId=908496&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a&l=10

I added a work around till we fix this issue -> https://github.com/dotnet/arcade/issues/6616#issuecomment-741567891

**Comment by epananth** [comment]
We currently have only one testing channel so may be its a good idea to have multiple channels to test

**Comment by riarenas** [comment]
Are you sure the feed exists? https://pkgs.dev.azure.com/_packaging/general-testing-internal/nuget/v3/index.json is a 404.

**Comment by riarenas** [comment]
I think the right URI is https://pkgs.dev.azure.com/public/_packaging/general-testing-internal/nuget/v3/index.json
