### ISSUE TITLE
NuGet.config disabled package sources have incorrect comments

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6685]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When Maestro adds disabled package sources for internal feeds (so that shas build properly in OSS, it's suppose to surround each entry with `<!--  Begin: Package sources from <repo> -->` and `<!--  End: Package sources from dotnet-aspnetcore -->` and alphabetize the entries based on the comment name.

It only does this for the last entry:

```
 -  <disabledPackageSources />
-     <add key="darc-int-dotnet-runtime-728fdef" value="true" />
-     <add key="darc-int-dotnet-aspnetcore-75759a8" value="true" />
-     <add key="darc-int-dotnet-aspnetcore-489d2cc" value="true" />
 +    <add key="darc-int-dotnet-windowsdesktop-3fef65d" value="true" />
 +    <add key="darc-int-dotnet-runtime-0260401" value="true" />
 +    <!--  Begin: Package sources from dotnet-aspnetcore -->
 +    <add key="darc-int-dotnet-aspnetcore-6a87a2d" value="true" />
 +    <!--  End: Package sources from dotnet-aspnetcore -->
 +  </disabledPackageSources>
```

Repro: check out bdb0aba56cf3a99f878041f41103dc7fc6397bc1 in dotnet-sdk in dnceng, change a CPD'd entry in the version.details.xml file (to force an update) and do darc update-dependencies --coherency only.

**Comment by MattGal** [comment]
Weird, will check it out.

**Comment by MattGal** [comment]
Addressed via https://github.com/dotnet/arcade-services/pull/1492/files

**Comment by MattGal** [comment]
This is rolled out, @mmitche please let me know if you see weirdness again.
