### ISSUE TITLE
gather-drop should allow for writing of relative paths in the manifest

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6689]
When we create the manifest file during gather-drop, the absolute paths to the assets are written to the asset list. This means that if we want to consume the outputs of gather-drop/the manifest, we need access to the exact path that is listed in the manifest, or we need to do some path manipulation to get the new absolute path, assuming we've copied the drop elsewhere (for example, in the release pipeline). Gather drop should be extended to take a command line option that tells it to write the relative paths to the artifacts (ie, relative to the output directory option), so that future path manipulation doesn't have to happen. Additionally, the manifest may want to also record the original output directory as another property of a build/drop.

**Comment by MattGal** [comment]
Created https://github.com/dotnet/arcade-services/pull/1498

**Comment by MattGal** [comment]
PR merged, move to rollout (not sure this repo actually has rollouts?  Will check with @adiaaida )

**Comment by MattGal** [comment]
Rolled out yesterday, closing.
