### ISSUE TITLE
Allow an alternate .NET SDK path to be used for xunit tests

### ISSUE THREAD

**Issue by mikem8361** [dotnet/arcade#6711]
The diagnostics repo needs a way to separate the SDK we use to build (i.e. stable 5.0.x) from the one used to test (6.0.x).  For SOS testing we currently install the SDK and various versions of the runtime (2.1.x, 3.1.x, 5.0.x and .6.0.x) into \<reporoot\>/.dotnet-test. Our SOS test runner uses that to launch the debuggees.

We also have regular xunit tests that also need to run on those runtimes so they also get installed in the global.json but if we could get an arcade change, it would save having to install all of these runtimes at both build time and at test time.  All of the architectures we want to test on need to be in specified in global.json. x64 and x86 currently, but arm32 and arm64 need added when we test (currently done manually) on those. When arm32 and/or arm64 are add to global.json, the build failures during install on other architectures.

**Comment by garath** [comment]
@alexperovich Alex, what do you think?

**Comment by alexperovich** [comment]
@mikem8361 how are you running tests currently? If you are using helix you can just set DotNetCliVersion to whatever version you want to use for that test run. It defaults to the currently running version, but you can set it to anything.

**Comment by mikem8361** [comment]
We don't use helix to run our tests yet. They are xunit tests that run on build leg for some OS's and in a test-only leg in a docker container for the various Linux distros supported. For the SOS test "debuggees", the diagnostics repo infrastructure installs (in the ".dotnet-test" subdir) a 6.0.x SDK and various versions of the runtime (2.1.x, 3.1.x, 5.0.x and 6.0.x). The SOS test runner uses that SDK/runtimes to launch the debuggees.

Example of our official build run: https://dev.azure.com/dnceng/internal/_build/results?buildId=942361&view=results

We also have just "plain" xunit tests for the other global tools, etc and those are the ones we want to run on that same SDK install instead of what is installed by global.json:

```
{
  "tools": {
    "dotnet": "5.0.100",
    "runtimes": {
      "dotnet/x64": [
        "$(MicrosoftNETCoreApp31Version)",
        "$(VSRedistCommonNetCoreSharedFrameworkx6460Version)"
      ],
      "dotnet/x86": [
        "$(MicrosoftNETCoreApp31Version)",
        "$(MicrosoftNETCoreApp50Version)",
        "$(VSRedistCommonNetCoreSharedFrameworkx6460Version)"
      ]
    }
  },
  "msbuild-sdks": {
    "Microsoft.Build.NoTargets": "2.0.1",
    "Microsoft.DotNet.Arcade.Sdk": "6.0.0-beta.20630.2"
  }
}
```

For the current Linux arm64 manual testing I do I also need to add:

```
    "dotnet/arm64": [
        "$(MicrosoftNETCoreApp31Version)",
        "$(MicrosoftNETCoreApp50Version)",
        "$(VSRedistCommonNetCoreSharedFrameworkx6460Version)"
      ]
```

Just to build and it seems to break building on other architectures and OSs if checked in.

We are trying to separate the SDK used to build (5.0.100) from the SDK/runtimes used to test (latest 6.0.x updated by DARC).

**Comment by alexperovich** [comment]
I don't believe the support built in to arcade sdk has support for running on different versions like that. It runs inside msbuild using the same dotnet that is running the build. It just runs either xunit.console or `dotnet test` based on your configuration.

To run the same test on multiple different runtimes/architectures you will need to either use helix, or run the tests in a separate step in your build manually.

**Comment by markwilkie** [comment]
We're happy to take a PR though of course.  Also, adding @tmat as this comes up every once in a while.

**Comment by garath** [comment]
@mikem8361 What are your thoughts?

**Comment by mikem8361** [comment]
I don't currently have time to do this myself.  It still would be nice if the diagnostics repo could specify a different SDK/runtime with some kind of msbuild property, but I could just run \<path-to-test-sdk\>/dotnet test \<xuinit-tests\>.sln explicitly to execute our tests. 

One of the things that makes this complicated is doing the build and test in one command something like `eng\common\build.ps1 -build -test` which does run in the same msbuild instance.

**Comment by hoyosjs** [comment]
@mikem8361 arcade's support uses msbuild execs to run it. It's several processes. The build part and test part is just msbuild invocations of the targets. I feel like this should definitely be in arcade though. If we deployed to helix, the external reference is necessary - sure. But also it should work similarly for the dev box scenario. I think the property that you state here is the cleanest possible solution.

**Comment by missymessa** [comment]
Epic closed. Let's retriage.
