### ISSUE TITLE
Roslyn analyzer could detect unused strings

### ISSUE THREAD

**Issue by danmoseley** [dotnet/arcade#6731]
From time to time we find unused strings in the resx's eg after code is refactored. It would be nice to have an easy way to detect these. If we assume that all resources are pulled from the SR class, we could use a Roslyn analyzer to flag any unreferenced members of the SR class. 

It would need to consume a baseline violation file, since (a) some places in the code (certainly in dotnet/runtime) dynamically generate resource ID's unfortunately (b) some places we may not want to fix eg because a resx file is largely the same between build configurations and it's not worth breaking it up.

cc @Marusyk in case they are interested.

**Comment by riarenas** [comment]
@jonfortescue was this removed because it was out of scope? If https://github.com/dotnet/core-eng/issues/11917 is not something we care about, where are we going to track issues related to these areas?

**Comment by markwilkie** [comment]
The question is if this actually needs to be done - which is why it's in triage.

**Comment by jakubstilec** [comment]
[Async Triage]: How much work is it? Does it require creation of a new tool or do we need to configure some existing tool?

**Comment by MattGal** [comment]
[Async Triage]: Seems like more trouble than its worth, and once actually localized a "dead" string has minimal ongoing cost and (speaking historically) occasionally becomes useful when a component needs to log something related to the "dead" string near the end of a release.

**Comment by danmoseley** [comment]
> once actually localized a "dead" string has minimal ongoing cost and (speaking historically) occasionally becomes useful when a component needs to log something related to the "dead" string near the end of a release.

It's correct it has minimal cost - mostly it's on-disk bloat.- and possibly the linker removes unused resources (@eerhardt )?

I disagree with the second part -- "it might be useful later" is never a reason we use to retain dead code. We just delete it.

I am neutral about whether it is worth investing in this analyzer though. I do know that dead strings are surprisingly common, even though we have made a pass. If the linker eg can tell us about them, then a Roslyn analyzer is low value.

**Comment by eerhardt** [comment]
> possibly the linker removes unused resources 

It doesn't today. It is pretty hard to safely do this. Take this code for example:

https://github.com/dotnet/runtime/blob/5f15498d937653986821d636c04cd03c58d4bb4c/src/libraries/System.ComponentModel.Primitives/src/System/ComponentModel/CategoryAttribute.cs#L168-L192

https://github.com/dotnet/runtime/blob/5f15498d937653986821d636c04cd03c58d4bb4c/src/libraries/System.ComponentModel.Primitives/src/System/ComponentModel/CategoryAttribute.cs#L199-L202

https://github.com/dotnet/runtime/blob/5f15498d937653986821d636c04cd03c58d4bb4c/src/libraries/System.ComponentModel.Primitives/src/Resources/Strings.resx#L63-L124

Here's a public `string _categoryValue ` that anyone can set in the ctor of this attribute `[Category("DragDrop")]`. Reading the `attribute.Category` property will look up a resource using the value from the ctor, but appending on the `PropertyCategory` prefix. And in this case look up the string `Drag Drop`.

In general, anyone can do any string manipulation to build up a resource key and try to find a resource. The linker isn't able to dynamically figure out which resources can be trimmed.

**Comment by jakubstilec** [comment]
[Async Triage]: +1 for more trouble than its worth, given that we can possibly remove keys which are still in use.

**Comment by danmoseley** [comment]
Agreed, given that point. It's unfortunate even we build resource strings dynamically.
