### ISSUE TITLE
Helix JobEnqueueFailure needs to be understood by Arcade Helix SDK and cause fast failure

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#6733]
- [ ] This issue is blocking
- [ ] This issue is causing unreasonable pain

Noted while investigating https://github.com/dotnet/runtime/issues/46484, out of which fell https://github.com/dotnet/core-eng/issues/11791.

When we have a job enqueue failure, we've done all the retries we're going to;  it's entirely possible that the job even had some batches of work sent off.  Unfortunately, the code in the Helix Arcade SDK doesn't know about the errors in the job, so it ends up waiting forever.

I believe we need the following functionality:

- [ ] Fail fast in the case where a JobEnqueue error is returned from the Helix Job Details API while waiting for a job to end.
- [ ] (nice to have) Cancel any job in this state, since it cannot be completed.

@ilyas1974 FYI

**Comment by MattGal** [comment]
https://github.com/dotnet/arcade/pull/6753

**Comment by hoyosjs** [comment]
I think I just saw this in https://dev.azure.com/dnceng/public/_build/results?buildId=939932&view=logs&j=f5bbf73d-4d5d-5c21-6748-018818b1d8ec&t=49b7db0f-7ab2-56d3-55e4-df171e8b3dbb for job 2ef40fdb-4c47-4b30-a1ca-7dd9c2e6e4ce

**Comment by MattGal** [comment]
> I think I just saw this in https://dev.azure.com/dnceng/public/_build/results?buildId=939932&view=logs&j=f5bbf73d-4d5d-5c21-6748-018818b1d8ec&t=49b7db0f-7ab2-56d3-55e4-df171e8b3dbb for job 2ef40fdb-4c47-4b30-a1ca-7dd9c2e6e4ce

Will take a look. The change I made just prevents unnecessary waiting; we're still unclear what caused the ObjectDisposedException that underlies it.  Checking that out.

**Comment by MattGal** [comment]
@hoyosjs [checking the API](https://helix.dot.net/api/jobs/2ef40fdb-4c47-4b30-a1ca-7dd9c2e6e4ce/details?api-version=2019-06-17) you're right, I'll open a new issue about the exception now as the first time we saw it, it was assumed to be very rare.

**Comment by MattGal** [comment]
Thanks so much for bringing this to my attention @hoyosjs.  This has happened way more than twice though it seemingly started on 12/3 which gives us something at least to analyze because that's the day after a rollout at least.

There's a known problem wiht this symptom Service Bus clean team has been chasing down so upgrading won't likely help; I filed https://github.com/dotnet/core-eng/issues/11824 ; we need to harden against it until they resolve it.

**Comment by MattGal** [comment]
Closing, this has been rolled out both in arcade and Helix services, so we'll be able to catch it if it keeps occurring.
