### ISSUE TITLE
Publish build assets job fails if there is reference to a private feed hosted in a different azdo org

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6743]
- [X] This issue is blocking 
We know of at least one repository, [roslyn-debug](https://dev.azure.com/dnceng/internal/_build?definitionId=926&_a=summary) where we fail to publish to the BAR because of this.

- [ ] This issue is causing unreasonable pain

The [publish build assets job](https://github.com/dotnet/arcade/blob/master/eng/common/templates/job/publish-build-assets.yml) is failing for scenarios where a repo requires authenticating to a private feed outside the azdo organization where the build runs due to missing the steps required for cross-org authentication.

In order to authenticate against all private feeds between dnceng and devdiv, we us steps such as this one:https://github.com/dotnet/arcade/blob/7d638bb082f374f7c8ddbada79f757662df4a246/eng/publishing/v3/publish-assets.yml#L51-L55

**Comment by riarenas** [comment]
I believe #6744 should unblock this

**Comment by tmat** [comment]
Should the publish step use the same NuGet.config as the repo?

**Comment by riarenas** [comment]
It most likely doesn't need to, but since we have to authenticate against the azure artifact feeds anyways to be able to restore the arcade sdk from the dotnet-eng, it seemed harmless to go with the cross-org authentication route.
