### ISSUE TITLE
Upgrade Arcade to current version of .NET

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#6745]
Many projects in Arcade are currently targeting .NET Core 2.1, which then required a downgrade of libraries per https://github.com/dotnet/arcade/pull/6738#discussion_r552186191. We should upgrade all projects to at the minimum use .NET Core 3.1 (upgrading to 5.0 would be ideal). 

- [ ] Upgrade Arcade projects to support .NET Core 3.1 at a minimum. .NET 5 would be ideal. 
- [ ] Upgrade the Dependency Injection (and related) libraries back to at least 3.1.9. (Abstractions, Logging)

**Comment by garath** [comment]
Triage: Moving to 3.1 can be considered as part of Extended FR. If scheduling does not allow this, move this to an epic scheduled later.

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/arcade/pull/6891
