### ISSUE TITLE
Arcade -> arcade-validation PR flow stuck due to logger changes in linux

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6763]
- [X] This issue is blocking 
This is blocking the arcade promotion flow.
- [ ] This issue is causing unreasonable pain

https://github.com/dotnet/arcade-validation/pull/2040 is still stuck because the linux legs can't load the new logger. An attempt to fix was submitted in https://github.com/dotnet/arcade/pull/6759, but it didn't stick.

```
MSBUILD : error MSB1020: The logger was not found. Check the following: 1.) The logger name specified is the same as the name of the logger class. 2.) The logger class is "public" and implements the Microsoft.Build.Framework.ILogger interface. 3.) The path to the logger assembly is correct, or the logger can be loaded using only the assembly name provided.
```

Arcade flow has been stuck for over a week now, and there are a few changes that repos require to be unblocked.

**Comment by riarenas** [comment]
I will make a quick attempt at fixing, or will revert the logger changes while we find a good path forward.

**Comment by markwilkie** [comment]
I support reverting per our policy...

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade/pull/6764 should fix this. I have validated an arcade-validation public build with the changes.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade-validation/pull/2040 has been merged. Waiting for its official build to succeed to confirm that the flow is unblocked.

**Comment by riarenas** [comment]
Official build was successful. I can sleep tonight.
