### ISSUE TITLE
[QCR] Fix Publish Signed Assets stage

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6783]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When we ran the pipeline with this turned on, we saw a failure in the Publish Signed Assets leg of the pipeline:  https://dev.azure.com/dnceng/internal/_build/results?buildId=940901&view=logs&j=7b3eece1-45a6-5c0c-c652-1d9905ffc78c&t=37854f68-528d-551a-2b96-c8319ee76c7f

Nuget complains that vs_packages is not a file, because it is a directory. In the yaml for this step, we need to specify a wildcard path to the nupkgs, rather than the path to the directory. See the specification for NugetCommand@2 here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops

**Comment by Tohron** [comment]
Merged: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/12060
