### ISSUE TITLE
Publishing V3 doesn't respect if a repo has SymbolPublishingExclusionsFile.txt 

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/arcade#6804]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The property gets piped, but :
- It never gets passed to the `PublishOperation`.
- It never gets uploaded to the assets nor downloaded from a raw github url (and this would only support public repos anyway).

We are facing an issue with an unindexable dll and I can't figure out where in the native build system the build options for this are - it would be nice if symbol files could be excluded just like the signing exclusion files (be it due to restrictions about shipping symbols or as a mechanism to disable publishing a problematic dll like now).

**Comment by epananth** [comment]
@hoyosjs can you please attach a build where it failed?

**Comment by hoyosjs** [comment]
It doesn't fail. It's never piped through. I was going to use it as a workaround.
