### ISSUE TITLE
Release day pipeline should create PRs for internal->public merge

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6819]
In the release pipeline, the tagging process tags the commits used to build the release, then pushes those commits to the public side. At that point, we can automatically create PRs for the internal->open merge where needed. This should be done in the following way:

1. Obtain the public repo name 
2. Calculate the public branch name
3. Check whether the public git repo already contains the tagged commit with ```git branch --contains <tag> | grep <public branch-name>```
4. If it does not, create and check out a merge branch from the public repo branch
5. ```git merge <tag>```
6. Push to public github repo
7. Create PR

**Comment by mmitche** [comment]
@adiaaida @wtgodbe @rahku @Anipik @leecow

**Comment by adiaaida** [comment]
@vseanreesermsft implemented the internal branch merge and it was run on the release last month. Closing.

**Comment by mmitche** [comment]
Woo!
