### ISSUE TITLE
CoreFx uses engineering dependency flow

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#683]
Documentation for dependency flow is currently being created / updated, here is some starter info

[Dependency flow](https://github.com/dotnet/arcade/blob/master/Documentation/DependenciesFlowPlan.md)

Add Version.Details.xml
- [x] Create [Version.Details.xml](https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#engversiondetailsxml) file manually in repo

Channel mapping
- [x] Create a [channel mapping](https://github.com/dotnet/arcade/blob/master/Documentation/Maestro/BuildAssetRegistry.md) between branch and channel name
  - manually (using REST API), documentation forthcoming

Create subscriptions
- [x] Create [subscriptions](https://github.com/dotnet/arcade/blob/e20e8459bdae871bcafb731cf139210319d939d4/Documentation/Maestro/BuildAssetRegistry.md#subscription) 
  - manually (using REST API), documentation forthcoming

**Comment by danmosemsft** [comment]
@chcosta are we missing a checkbox here for publishing from corefx?

cc @weshaggard

**Comment by weshaggard** [comment]
All the consumption steps are finished but we still need to do publishing.

**Comment by safern** [comment]
We are already publishing. The only subscriptions that corefx has is to arcade repo. So I will leave this open as I need to revisit this, compare what is still being updated from the old maestro and add those subscriptions for corefx.
