### ISSUE TITLE
CoreFx builds using shared toolset (Arcade SDK)

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#684]
Use Arcade SDK - here are some "getting started" steps, experience / usage may vary.

- [x] Add a [global.json](https://github.com/dotnet/arcade-minimalci-sample/blob/master/global.json)
- [x] Add (or copy) [Directory.Build.props](https://github.com/dotnet/arcade-minimalci-sample/blob/master/Directory.Build.props) && [Directory.build.targets](https://github.com/dotnet/arcade-minimalci-sample/blob/master/Directory.Build.targets)
- [x] Copy `eng\common` from [Arcade](https://github.com/dotnet/arcade/tree/master/eng/common) into repo
- [x] Add dotnet-core feed to [NuGet.config](https://github.com/dotnet/arcade-minimalci-sample/blob/master/NuGet.Config)

**Comment by chcosta** [comment]
https://github.com/dotnet/corefx/pull/31436

**Comment by weshaggard** [comment]
>Must have an sln file for the repo to build

We don't need a sln file we have configured it to use our root build.proj file instead. See https://github.com/dotnet/corefx/pull/31436/files#diff-991506ab3bfb2ea4767ed342c4f95726R4.

corefx already is setup to get auto dependencies from arcade and the PR dotnet/corefx#31436 will start restoring Arcade and enable us to use it but we will still not be using it fully yet we will still need work to transition away from BuildTools to arcade targets.

**Comment by weshaggard** [comment]
This work has been completed. CoreFx now consumes arcade sdk.
