### ISSUE TITLE
Flatten aka.ms links

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6862]
Today, aka.ms links use the full path to the files. So for example, if the file is `Sdk\biz\bop\boop\file.zip`, the aka.ms link will be `aka.ms/dotnet/version/Sdk/biz/bop/boop/file.zip`. Instead, we want to fully flatten this link, so the aka.ms link will be `aka.ms/dotnet/version/file.zip`. As our file names are distinct, this should be safe.

**Comment by adiaaida** [comment]
Looks like this will require some coordination with product repos for anyone relying on the full path.  In addition, we will need to rename some files to include the repo name in the file name so that there aren't conflicts.

**Comment by adiaaida** [comment]
installer, runtime, and aspnetcore have all been updated to also produce a <reponame>-productVersion.txt.

These changes need to be ported to the release branches in those repos as well, starting with release/5.0[.#xx] and release/6.0-preview branches.

**Comment by hoyosjs** [comment]
@adiaaida looks like the fix you added to avoid flattening on non-in-box channels didn't work. dotnet-monitor's publishing still ended up with a flattened URL. Oddly, we expected a link of the form aka.ms/dotnet/daily/diagnostics/monitor5.0/dotnet-monitor.nupkg.version, given this is a channel where we don't expect flattening to happen. However we end up seeing https://aka.ms/dotnet/dotnet-monitor.nupkg.version, so flattened and with no build quality in the link. 

For an example, see https://dev.azure.com/dnceng/internal/_build/results?buildId=1014320

We changed this for now: https://github.com/dotnet/dotnet-docker/pull/2628/files, but probably not as tenable on the long run. 

Do you know if we're missing a setting? We are publishing to ".NET Core Tooling Dev/Release"

**Comment by adiaaida** [comment]
I will take a look.

**Comment by adiaaida** [comment]
PR to fix: https://github.com/dotnet/arcade/pull/7036
