### ISSUE TITLE
Roslyn compiler updates are not flowing into Arcade and consuming repositories

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#6863]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The compiler package version hasn't been updated in Arcade for more than 2 months now: https://github.com/dotnet/arcade/blob/afd54cd0cb49f8c919411394231b1c7447513a51/eng/Versions.props#L38

Is that intentional or is a dependency not set-up correctly?

cc @mmitche @jaredpar

**Comment by jaredpar** [comment]
I'm not aware of any issues on our side, my expectation is that this should be flowing. 

@JoeRobich, @RikkiGibson FYI

**Comment by ViktorHofer** [comment]
My assumption is that the wrong channel is associated with arcade (VS 16.8 vs something else):

```
PS C:\git\runtime3> darc get-subscriptions --target-repo arcade --source-repo roslyn
https://github.com/dotnet/roslyn (VS 16.8) ==> 'https://github.com/dotnet/arcade' ('master')
  - Id: c4ba476b-52c5-4bcf-e67a-08d808024d62
  - Update Frequency: EveryWeek
  - Enabled: True
  - Batchable: True
  - Merge Policies:
    Standard
```

**Comment by ViktorHofer** [comment]
@jaredpar @JoeRobich @RikkiGibson any update? The fix should be straightforward but I don't think I'm the right person to update the subscription. Also can we please write this down somewhere / educate folks to prevent this from happening again when your branch/channel changes again?

**Comment by JoeRobich** [comment]
@jaredpar I wasn't aware we were updating the subscriptions for Arcade. Should this be part of the Tiger duties?

**Comment by RikkiGibson** [comment]
I think in a previous snap some of the necessary darc updates may have slipped under the radar. I can try to address it now.

**Comment by RikkiGibson** [comment]
I went ahead and updated the subscription to use 16.9 channel and triggered the subscription. This automated PR was just updated to reflect that: #6894

However, I found that all the darc-related steps we have documented appear to have been followed properly. Looking at the scenario a bit, though, it feels like the consuming repo should be the ones to decide when they are ready to start consuming dependencies from a new channel, and to make the config change to do so. Does that seem right to you?

**Comment by ViktorHofer** [comment]
> it feels like the consuming repo should be the ones to decide when they are ready to start consuming dependencies from a new channel, and to make the config change to do so. Does that seem right to you?

I disagree. How would Arcade know that roslyn changed their default channel? The goal of the subscription from Arcade to roslyn is to have a centralized up-to-date version of the compiler package. Handing that duty off to Arcade would mean that they would need to check every day or so if the subscription still points to the latest channel.

**Comment by RikkiGibson** [comment]
If the goal is to have Arcade always receive the most up-to-date possible compiler version, it might make sense to maintain a perpetual subscription to the "VS Master" channel.

Otherwise: The channels we use are tightly bound to VS releases. We only introduce a new default channel when we snap the first preview for a new VS release. That's the only time you should need to check.

For an example, here are some of the Roslyn subscriptions used by the SDK repo. I don't have evidence that Roslyn team manages these subscriptions, but I could be wrong. Tagging @JoeRobich @Cosifne to check my knowledge here.
```
https://github.com/dotnet/roslyn (VS 16.8) ==> 'https://github.com/dotnet/sdk' ('release/5.0.1xx')
  - Id: fe6e5bc9-bc04-4376-6b6a-08d85e7136ee
  - Update Frequency: EveryBuild
  - Enabled: True
  - Batchable: False
  - Merge Policies:
    Standard
  - Last Build: 20201204.10 (9ed4b774d20940880de8df1ca8b07508aa01c8cd)
https://github.com/dotnet/roslyn (VS 16.9) ==> 'https://github.com/dotnet/sdk' ('release/5.0.2xx')
  - Id: 549f64c9-69c5-4918-bc89-08d87076189d
  - Update Frequency: EveryBuild
  - Enabled: True
  - Batchable: False
  - Merge Policies:
    Standard
  - Last Build: 20210130.10 (3f54551d64817ec41c571b60cd512bd4e5902431)
https://github.com/dotnet/roslyn (VS Master) ==> 'https://github.com/dotnet/sdk' ('release/6.0.1xx-preview1')
  - Id: 15ea2541-5b90-4526-02d6-08d8b80548e4
  - Update Frequency: EveryBuild
  - Enabled: True
  - Batchable: False
  - Merge Policies:
    Standard
  - Last Build: 20210202.4 (c99c6fb04e72e0acc9d516533b17c5e1f72026f0)
```

[This OneNote doc](https://microsoft.sharepoint.com/teams/managedlanguages/_layouts/OneNote.aspx?id=%2Fteams%2Fmanagedlanguages%2Ffiles%2FTeam%20Notebook%2FRoslyn%20Team%20Notebook%20-%20New&wd=target%28Infrastructure.one%7C0E3C75FE-0827-41BF-9696-F5CD7105BC9A%2FUpdate%20Arcade%20channels%7C315761AC-43E1-475A-AAB6-1D46CF71BA0E%2F%29) includes the only darc-related steps we expect the Roslyn infra team to perform when snapping a new minor VS version (e.g. dev16.8-preview1, or dev16.9-preview1).

**Comment by jaredpar** [comment]
> If the goal is to have Arcade always receive the most up-to-date possible compiler version, it might make sense to maintain a perpetual subscription to the "VS Master" channel.

This matches my mental model. The compiler we are shipping to the logical "VS master" is the one that we are pushing into Arcade.

**Comment by ViktorHofer** [comment]
@RikkiGibson, based on Jared's response, should we change the subscription to always target the latest from roslyn?

**Comment by RikkiGibson** [comment]
I don't see why not :) if it builds and only arcade itself is impacted by the decision, then I have no objection.

**Comment by garath** [comment]
@mmitche As I recall, the guidance is to use the latest publicly released compiler (including previews). Is that what you rememeber?

**Comment by mmitche** [comment]
Yeah that's the general guidance for tooling.

**Comment by ViktorHofer** [comment]
@RikkiGibson did we actually update the subscription to use the always latest?

**Comment by ViktorHofer** [comment]
Reopening as the last compiler update happened more than a month ago. We need to depend on a newer version in dotnet/runtime than the stale one offered by Arcade.

Presumably having repositories with different roslyn toolset versions breaks source build.

@RikkiGibson @jaredpar can we please make sure bits are flowing asap again?

**Comment by ViktorHofer** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
related: https://github.com/dotnet/runtime/issues/57583

**Comment by am11** [comment]
SDK repo is kept up-to-date with latest version of compiler by @dotnet-maestro (e.g. latest one https://github.com/dotnet/sdk/commit/96756710ad5f78402ffc66151aa62cf9931c4b0d), perhaps arcade could use the same automation process? Current main branch of arcade repo itself is building fine with latest version of Roslyn at the moment.

**Comment by JoeRobich** [comment]
Arcades Roslyn subscription was set to the VS 16.10 channel. I've updated it to track VS 17.0. It would be nice if there was a maestro channel for "Latest Build" that we could publish to, since our latest build channel changes so often.

```
> darc get-subscriptions --source-repo roslyn --target-repo arcade
https://github.com/dotnet/roslyn (VS 17.0) ==> 'https://github.com/dotnet/arcade' ('main')
  - Id: 46ce138d-8732-4e0b-d9f7-08d961c27f17
  - Update Frequency: EveryWeek
  - Enabled: True
  - Batchable: False
  - Merge Policies: []
```

**Comment by am11** [comment]
Thanks, meastro bot has opened PR #7760. 💪🤖👍

**Comment by ViktorHofer** [comment]
Thanks Joe.

> It would be nice if there was a maestro channel for "Latest Build" that we could publish to, since the channel our latest build corresponds to changes so often.

Can you introduce such a channel for the roslyn repo that points to the master branch?

**Comment by riarenas** [comment]
@mmitche do you think it makes sense to create a channel for "VS tools - latest" or something to that regard that we could point roslyn's main branch to? right now I see it's going to general testing.

**Comment by mmitche** [comment]
> @mmitche do you think it makes sense to create a channel for "VS tools - latest" or something to that regard that we could point roslyn's main branch to? right now I see it's going to general testing.

We could use `.NET Tools - Dev` for this. I question whether this is actually what we want though or whether it will have unintended side-effects. Will the `main` branch of roslyn always be compatible with the SDK in main arcade for .NET and the corresponding .NET repos? IIRC those schedules aren't always aligned. Furthermore, if this had been subscribing to VS 17.0, it would have basically been exactly the same state as a 'latest' for the last months.

**Comment by ChadNedzlek** [comment]
Has there been any resolution on this @jaredpar, @mmitche?

**Comment by ViktorHofer** [comment]
Are compiler updates stale again? The last update in Arcade happened 16 days ago: https://github.com/dotnet/arcade/commit/7d3fcd449762518a19ac4ba34cb4d325f792c3b6.

**Comment by mmitche** [comment]
@ViktorHofer I believe the intention is that roslyn comes in through the SDK, not through direct references in arcade?

/cc @stephentoub

**Comment by ViktorHofer** [comment]
We only update the SDK once every month and we often need to move faster than that. Sounds like we need our own subscription from dotnet/roslyn to dotnet/runtime. Should the subscription towards arcade be removed then?

**Comment by ViktorHofer** [comment]
Yes, that would be my preferred option. It worked well for some time in the past.

> Update it when new VS versions show up.

Can this be added to some documentation so that the subscription from arcade to roslyn gets updated in time / or automatically?

**Comment by riarenas** [comment]
I've updated the channel to source from 17.5.

If they get stale again and it becomes a problem, I think we should remove the dependency from arcade, and have repos that want more frequent updates to manage their own subscriptions as @mmitche suggested. There doesn't seem to be a lot of interest for flowing roslyn through arcade for dogfooding reasons, so the value of flowing it centrally from arcade is low.
