### ISSUE TITLE
daily vs official/shipping build version numbers

### ISSUE THREAD

**Issue by zivkan** [dotnet/arcade#6868]
If this is documented, I failed to find it.

With repos using the Arcade SDK, how does "daily" (or in reality, every merge to main branch) build versions, using an auto-incrementing pre-release SemVer2 number work, compared to generating NuGet packages with "stable" version numbers?

The way that the NuGet.Client repo (not using Arcade SDK) currently works is that every build generates two sets of nupkgs. One set has a pre-release label, like `5.9.0-rc.1234`, and we also create `5.9.0` packages. The `5.9.0` packages are unused until the product ships, then we trigger the appropriate release pipeline to push the `5.9.0` packages to nuget.org, which is the only time the `5.9.0` packages are used.

I've seen [this doc on versioning](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md), but I don't understand the end-to-end flow of a PR being merged, an official build with the `-rc.<build_number>` being generated and pushed to BAR, then when the product is ready to ship, the "no-version-suffix" package being created and pushed to nuget.org.

**Comment by garath** [comment]
@mmitche Can you shed some light here?

**Comment by zivkan** [comment]
ping.

While I don't have time to onboard NuGet to the Arcade SDK any time soon, I am thinking about issues that will make it difficult. All of our release/deployment scripts and procedures are dependent on how we do this split `-rc` and GA package versioning, so is one of the issues blocking us.

**Comment by mmitche** [comment]
There are basically two typical states for a build:
- Build using pre-release version numbers
- Build using final version numbers.

When in pre-release (typical day to day) mode, the suffix on a package is determined by the date. The switch is basically checked into the repo (DotNetFinalVersionKind=release). When that is present, the suffix is dropped and packages end up with 1.2.3 version.

This is not actually a required pattern, though it is what basically most repos do. Individual projects can set the version properties directly, so really any versioning scheme is possible.

**Comment by zivkan** [comment]
Probably someone else. The first post in this thread explains that this is how NuGet.Client works. Maybe I mentioned this to you in a chat once as well, but I certainly don't remember asking anyone to justify why other repos don't build both sets of assets at the same time.

Having separate builds makes sense. There could theoretically be a benefit in building both nupkgs from the same assemblies and pdbs, so only one set of symbols need to be published for support both packages. And half as many assemblies to sign. But NuGet doesn't do this and the complexity to implement probably isn't worthwhile.

I'm trying to come up with an incremental approach to onboarding onto the Arcade SDK, with steps as small as possible. But having to rewrite a bunch of release procedures and scripts makes it not small. Oh well, I'll keep trying to get us there somehow. Thanks for the info.
