### ISSUE TITLE
Standard uses engineering dependency flow

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#688]
Documentation for dependency flow is currently being created / updated, here is some starter info

[Dependency flow](https://github.com/dotnet/arcade/blob/master/Documentation/DependenciesFlowPlan.md)

Add Version.Details.xml
- [x] Create [Version.Details.xml](https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#engversiondetailsxml) file manually in repo

Channel mapping
- [x] Create a [channel mapping](https://github.com/dotnet/arcade/blob/master/Documentation/Maestro/BuildAssetRegistry.md) between branch and channel name
  - manually (using REST API), documentation forthcoming

Create subscriptions
- [x] Create [subscriptions](https://github.com/dotnet/arcade/blob/e20e8459bdae871bcafb731cf139210319d939d4/Documentation/Maestro/BuildAssetRegistry.md#subscription) 
  - manually (using REST API), documentation forthcoming

**Comment by weshaggard** [comment]
The incoming dependency flow has been setup but the publish/outgoing still needs to be done.

**Comment by wtgodbe** [comment]
Standard now has a channel mapping for .NET Core 3 Dev, as well as a subscription to Arcade.
