### ISSUE TITLE
Standard builds using shared toolset (Arcade SDK)

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#689]
Use Arcade SDK - here are some "getting started" steps, experience / usage may vary.

- [x] Add a [global.json](https://github.com/dotnet/arcade-minimalci-sample/blob/master/global.json)
- [x] Add (or copy) [Directory.Build.props](https://github.com/dotnet/arcade-minimalci-sample/blob/master/Directory.Build.props) && [Directory.build.targets](https://github.com/dotnet/arcade-minimalci-sample/blob/master/Directory.Build.targets)
- [x] Copy `eng\common` from [Arcade](https://github.com/dotnet/arcade/tree/master/eng/common) into repo
- [x] Add dotnet-core feed to [NuGet.config](https://github.com/dotnet/arcade-minimalci-sample/blob/master/NuGet.Config)

**Comment by wtgodbe** [comment]
This is done
