### ISSUE TITLE
Standard official builds from VSTS (dev.azure.com/dnceng/internal)

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#690]
Official builds on VSTS - https://github.com/dotnet/arcade/blob/master/Documentation/VSTS/MovingFromDevDivToDncEng.md
- [x] Official builds are building in VSTS (dnceng)
  - [x] Using YAML
  - [x] Referencing [base.yml](https://github.com/dotnet/arcade-minimalci-sample#base-your-builds-on-arcade-for-ease-of-use)

**Comment by wtgodbe** [comment]
This is complete as of https://github.com/dotnet/standard/pull/995

https://dnceng.visualstudio.com/internal/_build?definitionId=246&_a=summary

**Comment by chcosta** [comment]
@wtgodbe 

nit: the name of your root yml file is non-standard.  Across dotnet, teams are using the recommended filename `azure-pipelines.yml` which Azure DevOps explicitly looks for when creating build definitions.  Conforming to that standard may make creating builds in future servicing branches slightly easier.

**Comment by wtgodbe** [comment]
@chcosta oops, I didn't know. I'll put up a PR to change the file name.
