### ISSUE TITLE
PKG notarization 'Replace PKGs' drops output packages into main drop folder when post build signing is enabled

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6904]
When post build signing is enabled, it would make more sense to use the 'signed' dir for the output files.

https://dev.azure.com/dnceng/internal/_build/results?buildId=978633&view=logs&j=44399984-ec83-5b4a-ba3f-e5ffd96035e6

@adiaaida Is this something no longer an issue with the file share being removed?

**Comment by adiaaida** [comment]
This will no longer be an issue with file share being removed.

**Comment by adiaaida** [comment]
This was fixed in prod
