### ISSUE TITLE
Investigate whether push to drop is necessary in staging pipeline

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6905]
The push to drop step: https://dev.azure.com/dnceng/internal/_build/results?buildId=978633&view=logs&j=3d541542-b300-5f6d-2a0f-da664695629c&t=329bacae-8c00-5482-3ade-d8f26b716d8c is exceedingly expensive. Is this output location used at all?

/cc @leecow @adiaaida

**Comment by adiaaida** [comment]
For the initial question, yes, the push to drop output location is used by most of the validation checks, by vs insertion, and by the staging ring.

It is being removed as part of the work to get us off of vsufile (though at that point, ALL of the artifacts will be pushed to the drop, so you will still sort of see this, there will just be less movement of files post-vsufile removal).

**Comment by adiaaida** [comment]
push-to-drop was removed as part of the work to remove vsufile. Closing.
