### ISSUE TITLE
Move Standard CI to VSTS (dev.azure.com/dnceng/public)

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#691]
VSTS public CI builds
- [ ] public CI builds are building in VSTS (dnceng.visualstudio.com)
  - [ ] Using YAML
  - [ ] Imports [base.yml](https://github.com/dotnet/arcade-minimalci-sample#base-your-builds-on-arcade-for-ease-of-use)

**Comment by wtgodbe** [comment]
This is complete as of https://github.com/dotnet/standard/pull/995

https://dnceng.visualstudio.com/public/_build?definitionId=235&_a=summary
