### ISSUE TITLE
InitializeDotNetCli's sdk.txt file does not support updates to different paths on Windows

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/arcade#6915]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

While testing out building dotnet/runtime with Docker for Windows, I've discovered that the current support for writing out sdk.txt in `InitializeDotNetCli` in `eng/common/tools.ps1` doesn't handle the case when the file exists from a previous invocation but points to a different location.

As a result, this breaks the scenario of switching between building with the local machine and building with Docker within the same repository (we end up using this file from the `./dotnet.cmd` script in our repo root during our native CoreCLR build).

cc: @lukas-lansky

Connected to https://github.com/dotnet/arcade/issues/6560

**Comment by lukas-lansky** [comment]
It seems to me that [we are using](https://github.com/dotnet/arcade/blob/938b3e8b4edcd96ca0f0cbbae63c87b3f51f7afe/eng/common/tools.ps1#L172) `Rename-Item -Force` expecting it will force overwrite, but [it isn't](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/rename-item?view=powershell-7.1). The situation would be more complicated if we wanted to bypass discovery in the case of already existing `sdk.txt`, but that's not the case – we just fail to overwrite after all the expensive action happened.

Let me throw a quick PR to see whether @riarenas agrees.

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/arcade/pull/6918
