### ISSUE TITLE
Helix SDK's Azure Pipelines reporter needs to return non-0 exit code if results are not successfully uploaded to AzDO

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#6919]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Runtime team (and possibly others?) now return 0 from their scripts when tests fail, due to https://github.com/dotnet/runtime/pull/45164

However in doing that work, https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/tools/azure-pipelines/reporter/run.bat and https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/tools/azure-pipelines/reporter/run.sh didn't bake this assumption in so the exit code of run.bat or run.sh is always 0 if setting environment variables work (basically always), since the last thing these scripts do is set an env var.

**Comment by ChadNedzlek** [comment]
I'm taking this bug into the Dev WF epic, since we are going to do some major overhaul of it there. Unless this is something that needs immediate attention for the current version.

**Comment by MattGal** [comment]
> I'm taking this bug into the Dev WF epic, since we are going to do some major overhaul of it there. Unless this is something that needs immediate attention for the current version.

I think given the problem is rare enough that we haven't found an instance of it yet indicates it doesn't need immediate attention.   Should be fairly simple; if you aren't 100% certain you successfully reported the result, return anything but 0.

**Comment by MattGal** [comment]
@ChadNedzlek just wanted add, it should probably be optional, since only runtime AFAIK has this special "return 0 when you would normally return 1"

**Comment by ChadNedzlek** [comment]
Well, I'm going to be moving all of the reporting code into helix (since we need to know a LOT more context about the retry/upload mechanic to do any useful reporting), so it won't really be an issue anymore. The workitem will long have finishes before we start talking to AzDO.

**Comment by ChadNedzlek** [comment]
I've rewritten most of this code, so I'm closing this one, in lieu of that work.

**Comment by MattGal** [comment]
@ChadNedzlek can you clarify all this rewritten code solves the problem seen in this log (DNS broken, can't use reporter, no results reported, 0 exit code?) https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-51870-merge-2403df6cc48142d087/System.Xml.XmlSerializer.ReflectionOnly.Tests/console.fe5356b5.log?sv=2019-07-07&se=2021-05-16T16%3A41%3A19Z&sr=c&sp=rl&sig=spDdf4qHiGbZRQIzIVpMW2GxOOahMWSqRLbIYG6D5Fw%3D

**Comment by ChadNedzlek** [comment]
Well that problem appears to be pip nonsense. Since I'm going to be doing pip in the middle of python execution anymore (it will just use the same pip method the rest of our stuff uses) it won't be a potential place for it to fail.

**Comment by ChadNedzlek** [comment]
Yes, mostly I was just saying the new code doesn't have a pip dependency, so it's not possible for the failure you mentioned to be present in it. So it "solves" it by the code not being there in the first place.

**Comment by Chrisboh** [comment]
@MattGal I talked with Chad about this and we are in agreement we should do something quick now to mitigate the failure to report now as his feature is still about a month out.

**Comment by MattGal** [comment]
Awesome thanks Chris and Chad.  @alexperovich can I get you to do this through FR?  (I favor an unfamiliar exit code if the azdo reporter fails so we can query for how often it happens, where, and on which machine easily)

**Comment by alexperovich** [comment]
Yup, i'll get this done.

**Comment by ChadNedzlek** [comment]
It looks like there are 2 culprits.  "Batch" is the first... every line in the "run.bat" can silently fail... batch is terrible.  And then the background workers in run.py

**Comment by alexperovich** [comment]
There is also the "ignore all exit codes from PostCommands" part.

**Comment by ChadNedzlek** [comment]
... Wait, we explicitly enabled this behavior? For what scenario...?

**Comment by MattGal** [comment]
> ... Wait, we explicitly enabled this behavior? For what scenario...?

Scenario would be that the post command's exit code is something that's always 0 ( "echo %variable%", say) but wanting the exit code of the work item to match what came back from the command, not echo / copy / whatever thing that won't return non-0, allowing for running post commands that succeed on a failing work item.

Through shenanigans the exit code can always be coerced to 0 or non-0 for a sufficiently motivated user.

**Comment by ChadNedzlek** [comment]
Ugh. Post Commands are a weird, dangerous idea.  Good luck, I guess.  You need to both ignore their exit code but also respect them.
