### ISSUE TITLE
XHarness Helix SDK outputs errors when used in parallel (parallel dotnet tool install)

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#6921]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

See https://github.com/dotnet/runtime/issues/47984 for context.  Basically, Xharness sets up CLI payloads for execution and when two runs are submitted in parallel to do this, it can collide.

Some kind of file-based semaphore would be a simple solution, or perhaps even a means to do nothing if the target directory already exists (will need to be sure it matches, though)

@ilyas1974 this is small and directly affecting day-to-day runtime team stuff so I put it in FR, please remove if  you disagree.

**Comment by premun** [comment]
This issue needs a 2-step update of Arcade. First step is done, I will open a PR for the second step today.

**Comment by premun** [comment]
Waiting for Arcade promotion

**Comment by premun** [comment]
Technically it is about merging this PR - https://github.com/dotnet/arcade/pull/8072
