### ISSUE TITLE
[release/3.x] official build broken during SDL validation with missing functions

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6930]
- [X] This issue is blocking 
This is blocking the release/3.x branch of arcade
- [ ] This issue is causing unreasonable pain

Build started failing as of https://dev.azure.com/dnceng/internal/_build/results?buildId=971573&view=results, which seems to point towards this change: https://github.com/dotnet/arcade/commit/6e8b0da07468ed1653292b1aeb11c9d76da64dea

```
at <ScriptBlock>, D:\a\1\s\eng\common\sdl\init-sdl.ps1: line 41
at <ScriptBlock>, D:\a\1\s\eng\common\sdl\execute-all-sdl-tools.ps1: line 57
at <ScriptBlock>, D:\a\_temp\2f650cf7-27ef-461d-aa0e-cb9388fc6822.ps1: line 3
at <ScriptBlock>, <No file>: line 1
Write-PipelineTelemetryError : The term 'Write-PipelineTelemetryError' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again.
At D:\a\1\s\eng\common\sdl\init-sdl.ps1:45 char:3
+   Write-PipelineTelemetryError -Force -Category 'Sdl' -Message $_
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Write-PipelineTelemetryError:String) [], ParentContainsErrorRecordExcep 
   tion
    + FullyQualifiedErrorId : CommandNotFoundException

```

**Comment by riarenas** [comment]
CC @dotnet/dnceng added this to FR. @jakubstilec FYI

**Comment by jakubstilec** [comment]
@riarenas - it happened during merge of SDL fix from HEAD into release/3.x where Write-PipelineTelemetryError doesn't exist. I prepared fix https://github.com/dotnet/arcade/pull/6938.

**Comment by jakubstilec** [comment]
Build pipeline is fixed for [release/3.x](https://dev.azure.com/dnceng/internal/_build/results?buildId=988519&view=logs&j=3034d33c-f6e3-5dce-656e-25219163ec67&t=a4e9890b-bd80-53cf-aaf7-30d58d9b7b71).
