### ISSUE TITLE
Repos should no longer use V1 / V2 publishing

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#6933]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

All the repos using V1/V2 publishing are subscribed to .Net 3x channel.

**Comment by epananth** [comment]
start with making a list of repos and then target all the release 3.1.1.xx and 3.1.4.xx branches

**Comment by mmitche** [comment]
v2 is basically gone (as far as I know). v1 is still in use in a few places 3.1, but we will not be changing it as 3.1 is going out of support soon.
