### ISSUE TITLE
Onboard to V3 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#6946]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

|  Repo Name |  Branch 3.1.1.xx   | Branch 3.1.4.xx  | 
|---------------|--------------------|------------------|
| Installer        |                              |                          |
| Toolset         |                              |                          |
| Sdk               |                              |                          |
| WebSdk        |                              |                          |
| AspnetCore  |                              |                          |
| Aspnetcore-tooling|                              |                          |
| Core-setup   |                              |                          |
| Fsharp      |                          |
| msbuild    |                              |                          |
| roslyn       |                              |                          |
| templating |                              |                          |
| vstest   |                              |                          |
| nuget.client |                              |                          |
| linker |                              |                          |

**Comment by mmitche** [comment]
Not going to do this.
