### ISSUE TITLE
Merged manifest does not show one of the assets

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#6949]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://github.com/dotnet/installer/pull/9702

The asset appears on the asset manifest but does not show up in the merged manifest. 

cc: @mmitche

**Comment by MattGal** [comment]
@chcosta when you come online can you drive this?  For now I'm trying to get a hold of some dependency flow folks to discuss if we can figure out what happened.

**Comment by MattGal** [comment]
@mmitche points out tha tin a post-build-signing world, this yaml:

https://github.com/dotnet/aspnetcore/blob/main/.azure/pipelines/ci.yml#L822-L824
... doesn't currently wait on any linux legs at all, and would only succeed if very lucky and all linuxes finish before all Windowses.  

As that makes this an AspNetCore build authoring issue, closing the arcade FR issue.
