### ISSUE TITLE
Move Core-Sdk CI to VSTS (dev.azure.com/dnceng/public)

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#696]
VSTS public CI builds
- [ ] public CI builds are building in VSTS (dnceng.visualstudio.com)
  - [ ] Using YAML
  - [ ] Imports [base.yml](https://github.com/dotnet/arcade-minimalci-sample#base-your-builds-on-arcade-for-ease-of-use)

**Comment by livarcocc** [comment]
Issue moved to [dotnet/cli #10138](https://github.com/dotnet/cli/issues/10138) via [**ZenHub**](https://www.zenhub.com/)
