### ISSUE TITLE
sdk.txt encoding issues

### ISSUE THREAD

**Issue by lukas-lansky** [dotnet/arcade#6960]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

A part of the runtime issues discussed at length at https://github.com/dotnet/runtime/issues/42397 is the fact that the `sdk.txt` mechanism doesn't play well with non-ASCII characters. We should specify encoding and make sure the `.dotnet` path gets through in cases like this:

```
> mv runtime runťime
> cd runťime
> ./dotnet.cmd
C:\Source\runťime\.dotnet
The system cannot find the path specified.
```

**Comment by ilyas1974** [comment]
@tkapin is this something you can help get sorted? Should this go to the backlog or is there something that we can push forward and complete?

**Comment by tkapin** [comment]
The scripts should be certainly respecting the filesystem capabilities (spaces, non-ASCII characters, etc. in paths), but this is a year old issue and it seems this doesn't cause any problems, which indicates the ROI isn't met. Closing as won't do, feel free to reopen if you thing we should invest into this.
