### ISSUE TITLE
Rename ".Net 6 dev" channel to ".Net 6"

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6981]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We want to consolidate on fewer channels for .net 6, so we should rename the dev channel to reflect that it will be used for release as well.

**Comment by mmitche** [comment]
While this happens, can 1753 be renamed from '.NET 6.0.1xx SDK Preview 2' to '.NET 6 SDK 6.0.1xx Preview 2' to be consistent with the .NET 5 sdk channel names

**Comment by riarenas** [comment]
Sounds good

**Comment by riarenas** [comment]
Done:

```
darc get-channels
...
(1296) .NET 6
...
(1753) .NET 6 SDK 6.0.1xx Preview 2
...
```

**Comment by riarenas** [comment]
This broke the powerbi dashboard. Definitely wasn't even on my radar of things to check after the update 😞

**Comment by garath** [comment]
> This broke the powerbi dashboard. Definitely wasn't even on my radar of things to check after the update 😞

This is a small hiccup, and there's no real way to catch it. It only happened because ".NET 6 Dev" happened to be the default selected item in the PowerBI filter. Choosing any others, including ".NET 6", did the right thing. If it wasn't the default, it wouldn't have even shown on the filter list.
