### ISSUE TITLE
Arcade is not able to publish to the .net 6 preview 2 channel

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7004]
- [X] This issue is blocking 
Blocking publishing for preview 2 channel
- [ ] This issue is causing unreasonable pain

https://github.com/dotnet/arcade/commit/1fdfdf58690a09b9555abe257ab4caa15d5c5b45 added publishing capabilities to the preview 2 channel, but since arcade flow is currently blocked, a manual update in arcade is required for the promotion pipeline to be able to publish there.

**Comment by riarenas** [comment]
I'll take a quick stab at this, if there are any problems with the PR I'll send it out to @epananth or FR for investigation

**Comment by mmitche** [comment]
Fixed with https://github.com/dotnet/arcade/pull/7005

**Comment by riarenas** [comment]
#7005 brought along its own set of errors:

https://github.com/dotnet/arcade/pull/7005#issuecomment-784398005, still trying to get this unblocked

**Comment by riarenas** [comment]
Looks like the update to nuget versions in 6dca077daa0706548b88ecb9af62abdb5af37dc6 breaks arcade right now. I'm reverting that commit so that we can get an updated arcade that can unblock preview 2 publishing.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade/pull/7014 Should be the final PR to fix this. Once it is merged I'll retry a couple of builds that failed to publish to preview 2 to verify it was unblocked.

**Comment by riarenas** [comment]
This is now unblocked. I retried the following builds that had previously failed to publish to the preview 2 channel:

* https://dev.azure.com/dnceng/internal/_build/results?buildId=1007194&view=results
* https://dev.azure.com/dnceng/internal/_build/results?buildId=1007203&view=results
