### ISSUE TITLE
Source-build-managed leg of CI pipeline fails intermittently

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7013]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain
I've seen multiple PRs and official builds fail with this

This leg of the pipeline is intermittently failing with:

```
/__w/1/s/.dotnet/sdk/5.0.100/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(207,5): error : The process cannot access the file '/__w/1/s/artifacts/packages/Release/NonShipping/Microsoft.SourceBuild.Intermediate.arcade.6.0.0-ci.nupkg' because it is being used by another process. [/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/6.0.0-beta.21117.1/tools/SourceBuild/SourceBuildIntermediate.proj]
##[error].dotnet/sdk/5.0.100/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(207,5): error : (NETCORE_ENGINEERING_TELEMETRY=AfterSourceBuild) The process cannot access the file '/__w/1/s/artifacts/packages/Release/NonShipping/Microsoft.SourceBuild.Intermediate.arcade.6.0.0-ci.nupkg' because it is being used by another process.
  Successfully created package '/__w/1/s/artifacts/packages/Release/NonShipping/Microsoft.SourceBuild.Intermediate.arcade.6.0.0-ci.nupkg'.
```

It usually goes away after retrying.

See https://dev.azure.com/dnceng/public/_build/results?buildId=1008592&view=results (attempt 1) for an example.

**Comment by riarenas** [comment]
@dagood are you a good contact for this?

**Comment by dagood** [comment]
@dseefeld @crummel @MichaelSimons for ArPow infra. This is what's tracked by https://github.com/dotnet/source-build/issues/2066.

@mmitche pinged me about this yesterday--I assumed there was a discussion Arcade-side about it. Sorry about that. Maybe ArPow issues should go into dotnet/arcade for visibility. Need to be careful it doesn't make responsibilities unclear, though.

**Comment by riarenas** [comment]
We struggle with the same thing between issues in core-eng and arcade. In the end our policy ended up being: if the change needs to go in arcade, issue lives in arcade.

I also think it's not unreasonable to look in dotnet/source-build for source-build related issues. Since this is already tracked there I'm good with closing this.
