### ISSUE TITLE
sourceIndexPackageVersion is stale

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#7024]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

The SourceIndex package version is hard-coded in the yml and never updated which leads to source indexer not being able to parse newer msbuild binlog versions.

https://github.com/dotnet/arcade/blob/fecdaeca751e49cf64bdce8e18057a3768153de7/eng/common/templates/job/source-index-stage1.yml#L3

cc @alexperovich

**Comment by MattGal** [comment]
Per @alexperovich : "The work that needs to be done is make the source-indexer build update maestro++ with the versions of the packages, and change the build part in arcade to use versions that maestro flows. The current state is a hardcoded version that isn’t easy to update."

Seems > FR, removing from epic.

**Comment by riarenas** [comment]
Seems like a good candidate for https://github.com/dotnet/core-eng/issues/8790?

**Comment by missymessa** [comment]
Parent issue closed.

**Comment by ViktorHofer** [comment]
@missymessa this issue still applies. Please reopen.
