### ISSUE TITLE
Do not package vs template files as zip files during packaging

### ISSUE THREAD

**Issue by BertanAygun** [dotnet/arcade#7041]
Visual Studio 2017 and above supports reading vstemplate files deployed as flat files directly from their install location instead of zip files and in fact having flat files is better for new project dialog/new item dialog performance as VS doesn't have to extract vstemplate file.

 _GetVsixTemplateItems build target should be modified to include template files as individual files in the final VSIX.

ie ProjectTemplate\MyTemplate.zip should be deployed as ProjectTemplate\MyTemplate\MyTemplate.vstemplate and so on.

**Comment by garath** [comment]
@tmat Is this something you were planning on doing?

**Comment by genlu** [comment]
https://github.com/dotnet/arcade/pull/7056
