### ISSUE TITLE
Gather aka.ms usage telemetry collection

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#7043]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

**Comment by MattGal** [comment]
thing to investigate: 

- Is there a way to get the traffic data redirected to helix or ingested into Kusto ?
- What does programmatic access look like in general?

**Comment by MattGal** [comment]
Didn't spend as much time as I'd like to have on this today but will look at it more tomorrow.  Basically, from reading [their FAQ] the only explicitly mentioned ways are via the portal which gives you either 1) UI-based display of up to 5 links' telemetry or 2) an XLSX download. 

All is not lost, the remaining hope for usage telemetry is directly through the API.  I'll give this a shot tomorrow, but my sense is if there's any sort of throttling on this API that we wouldn't be able to gather it for all our links super often.

**Comment by MattGal** [comment]
The API works very well for this.  Description of how this would work:

1. Use the search API to get all FWLinks in our tenant, 50 at a time (there's > 17K, so this is 340 GETs).  The response contains a "total" field so writing the for-loop of this is straightforward.

```
GET https://redirectionapi.trafficmanager.net/api/aka/1/ncd/search?filter=&query=*&offset=0&count=25&sortby=lastModifiedDateTime:1%2Bid:1
```

2. extract the link Ids from the returned JSON:

Relevant bit looks like lots and lots of this:
```
	"links": [{
		"id": 11931667,
		"hostId": 1,
		"tenant": "ncd",
	
```

3. Getting hits metrics:

/aka/[host]/[tenant]/telemetry/linkhits?id=[id]&start=[starttime]&end=[endtime]&unit=[unit]

ex: https://redirectionapi.trafficmanager.net/api/aka/1/ncd/telemetry/linkhits?id=11931667&start=2020-11-11&end=2021-03-11&unit=Day
```
{
  "id": 11931667,
  "linkHits": [{
    "requestTime": "2021-03-10T00:00:00Z",
    "value": 2
  }, {
    "requestTime": "2021-03-09T00:00:00Z",
    "value": 2
  }, {
    "requestTime": "2021-03-08T00:00:00Z",
    "value": 1
  }, {
    "requestTime": "2021-03-07T00:00:00Z",
    "value": 2
  }, {
    "requestTime": "2021-03-06T00:00:00Z",
    "value": 2
  }, {
    "requestTime": "2021-03-05T00:00:00Z",
    "value": 3
  }, {
    "requestTime": "2021-03-04T00:00:00Z",
    "value": 7
  }, {
    "requestTime": "2021-03-03T00:00:00Z",
    "value": 98
  }]
}
```

4. Getting unique users (to diminish build automation)

/aka/[host]/[tenant]/telemetry/bulk/linkhits?start=[starttime]&end=[endtime]&unit=[unit]

ex: https://redirectionapi.trafficmanager.net/api/aka/1/ncd/telemetry/uniqueuser?id=11931667&start=2020-11-11&end=2021-03-11&unit=Day
```
{
  "id": 11931667,
  "uniqueUser": [{
    "requestTime": "2021-03-09T00:00:00Z",
    "value": 1
  }, {
    "requestTime": "2021-03-08T00:00:00Z",
    "value": 1
  }, {
    "requestTime": "2021-03-07T00:00:00Z",
    "value": 1
  }, {
    "requestTime": "2021-03-06T00:00:00Z",
    "value": 2
  }, {
    "requestTime": "2021-03-05T00:00:00Z",
    "value": 2
  }, {
    "requestTime": "2021-03-04T00:00:00Z",
    "value": 5
  }, {
    "requestTime": "2021-03-03T00:00:00Z",
    "value": 4
  }]
}
```
At this point we have all the data we need, and just need to stick it somewhere.  I envision this would go into the "MetricsObserver" class that runs in the dotnet-helix-service ServiceFabric cluster, but it could go anywhere.

**Comment by ChadNedzlek** [comment]
Phew, that's a lot of calls. :-) But yeah, the MetricsObserver seems like a reasonable place.  Just query it once a day/hour and dump it into Kusto or AI or something.

**Comment by adiaaida** [comment]
How do we correlate those ids back to the links they represent?

**Comment by MattGal** [comment]
> How do we correlate those ids back to the links they represent?

This is via their short URL.  I had stripped this down to demonstrate getting telemetry, here's a "full" example of what you get from the search API:

```
{
		"id": 12037776,
		"hostId": 1,
		"tenant": "ncd",
		"shortUrl": "dotnet/6.0/daily/dotnet-targeting-pack-win-x86.zip",
		"targetUrl": "https://dotnetcli.azureedge.net/dotnet/Runtime/6.0.0-preview.3.21165.3/dotnet-targeting-pack-6.0.0-preview.3.21165.3-win-x86.zip",
		"mobileUrl": null,
		"createdBy": "dn-bot",
		"createdTime": "2021-03-04T18:14:25Z",
		"lastModifiedBy": "dn-bot",
		"lastModifiedDateTime": "2021-03-15T14:55:14Z",
		"isVanity": true,
		"isAllowParam": true,
		"isTrackParam": false,
		"description": "",
		"groupOwner": "ddfwlink",
		"groupOwnerSid": "",
		"owners": "jamshedd;leecow;rbhanda;v-susles;v-paddan",
		"category": null,
		"isActive": true,
		"isReadOnly": false,
		"bypassCvsCheck": false,
		"bypassCvsCheckJustification": null
	}
```
In general, if you have the integer id of a given aka.ms link, or its short URL, you can easily get the other value, just the usage telemetry APIs only take the integer version.  Perhaps they did it this way because the same int can be updated to another url?   Either way, regularly gathering all this data is pretty straightforward.

Let's discuss today in the UBA standup what next steps are.

**Comment by adiaaida** [comment]
Very cool. That's awesome!

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/13813?_a=files

**Comment by MattGal** [comment]
PR is merged, waiting to roll out.

**Comment by MattGal** [comment]
Rolling out now in https://dnceng.visualstudio.com/internal/_build/results?buildId=1065964&view=results, but since it only runs at midnight I'll leave this in validate until it's been going a few days in prod to close.

**Comment by MattGal** [comment]
Spot checking the data seems good (though delayed a day longer than expected), so closing.
