### ISSUE TITLE
Respond to possible changes needed due to dotnet/roslyn moving from master -> main

### ISSUE THREAD

**Issue by allisonchou** [dotnet/arcade#7052]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Roslyn switched from master->main yesterday. I'm not sure if some arcade code will also need to be updated, such as here: https://github.com/dotnet/arcade-services/blob/737108990a317c591d6beb46197a1b094e5979a6/src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/DependencyFlowGraph/IncludeBuildTimes/output.json#L489-L490

**Comment by riarenas** [comment]
I don't think we need to change anything. I can't find any real references to roslyn master. Those tests in arcade-services use a static input/output file, we just happened to use roslyn master-vs-deps for the test inputs, so we expect it to stay the same in the test outputs. 

Closing this for now until some actual fallout comes out of the rename (It's been a couple of weeks, so if it does come up, it's going to be some weird edge case we couldn't find easily anyways)
