### ISSUE TITLE
Arcade 6 forces consumers to use Microsoft.NETFramework.ReferenceAssemblies 1.0.0

### ISSUE THREAD

**Issue by jmarolf** [dotnet/arcade#7053]
Even though the version of reference assemblies is set [here](https://github.com/dotnet/arcade/blob/4126a4421e99b1f31214c0f25e211251ed745559/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L87) it is not respected and all arcade repos on version 6 build with `<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0">`

Roslyn will need to work around this in custom targets. If it is intentional that customers build against version `1.0.0` then the property in `DefaultVersions.props` should be modified or deleted.

**Comment by jmarolf** [comment]
This is the result of interaction between the .NET 6 Preview 1 SDK and arcade 6. If the .NET 6 SDK is going to be recommended for arcade consumers this issue should be addressed.

**Comment by jaredpar** [comment]
Can you elaborate on what problem that causes for Roslyn when we can't move to a different version?

**Comment by garath** [comment]
Curious about the answer to Jared's question. If there's something more blocking, please reopen.
