### ISSUE TITLE
Include properties needed for servicing redirect in jobs created by SendHelixJob

### ISSUE THREAD

**Issue by lpatalas** [dotnet/arcade#7074]
- [ ] This issue is blocking
- [ ] This issue is causing unreasonable pain

We need to include `System.PullRequest.TargetBranch` pipeline variable in job properties to be able to redirect PR test jobs to servicing subscription. Currently Helix API has no way to tell if the PR was created for `main` or `release/*` branch.

This has to be done for all supported .NET versions. i.e.: 3.1, 5.0 and 6.0.

**Comment by lpatalas** [comment]
All three PRs were merged. Next step is to trigger the subscriptions for 3.x and 5.0 branches which I will do today.

**Comment by lpatalas** [comment]
The changes in `main` are ready. `3.x` and `5.0` are validated but didn't make it in current servicing cycle. They will wait until the next servicing cycle but the work is finished.

**Comment by lpatalas** [comment]
Helix.Sdk was updated in most of 3.x and 5.x servicing branches.

Below are the repos that don't have the updated version of Helix.Sdk (`2.0.0-beta.21161.1`). Most of these branches does not seem to have been modified recently. The only exception is `dotnet/coreclr` which probably should contain the updated Helix.Sdk if it's possible to add it there.

Repository | Branch | Helix.Sdk version
-|-|-
dotnet/coreclr | release/3.1-crossdac | 2.0.0-beta.21072.7
dotnet/coreclr | release/3.1 | 2.0.0-beta.21072.7
dotnet/sdk | release/3.1.3xx | 2.0.0-beta.20113.5
dotnet/sdk | release/3.1.2xx | 2.0.0-beta.20113.5
dotnet/wcf | release/3.1.0 | 2.0.0-beta.20113.5
dotnet/corefx | release/3.1-blazor | 2.0.0-beta.20113.5

**Comment by mmitche** [comment]
Removed the branches that I know do not need the update:

Repository | Branch | Helix.Sdk version
-- | -- | --
dotnet/coreclr | release/3.1-crossdac | 2.0.0-beta.21072.7
dotnet/coreclr | release/3.1 | 2.0.0-beta.21072.7
dotnet/wcf | release/3.1.0 | 2.0.0-beta.20113.5

**Comment by lpatalas** [comment]
The missed 3.1 branches will be updated during next servicing window. It's not clear at the moment what is the process for `release/3.1-crossdac`.
