### ISSUE TITLE
Arcade does not include xunit.runner.json file if being run with the VS Test runner

### ISSUE THREAD

**Issue by jmarolf** [dotnet/arcade#7080]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain

If a consumer of arcade sets `<UseVSTestRunner>true</UseVSTestRunner>` like we do [here](https://github.com/dotnet/roslyn/blob/7e8b9ee7491b4d51809f5cc0273883692807c279/eng/Versions.props#L290). 

This causes all xunit targets to be skipped:
https://github.com/dotnet/arcade/blob/6cc4c1e9e23d5e65e88a8a57216b3d91e9b3d8db/src/Microsoft.DotNet.Arcade.Sdk/tools/XUnit/XUnit.targets#L18-L19

as a result any configuration such as a custom `xunit.runner.json` are not respected. The following sections should be moved from `XUnit.Runner.targets` ot `XUnit.targets`

https://github.com/dotnet/arcade/blob/6cc4c1e9e23d5e65e88a8a57216b3d91e9b3d8db/src/Microsoft.DotNet.Arcade.Sdk/tools/XUnit/XUnit.Runner.targets#L2-L4

https://github.com/dotnet/arcade/blob/6cc4c1e9e23d5e65e88a8a57216b3d91e9b3d8db/src/Microsoft.DotNet.Arcade.Sdk/tools/XUnit/XUnit.Runner.targets#L10-L24

**Comment by garath** [comment]
This looks like work as part of the unification effort we want to get to, but this work is not priorities. If you want to submit a PR in the meantime, we'd be happy to look at it.

**Comment by JoeRobich** [comment]
Implemented Jon's suggestions in https://github.com/dotnet/arcade/pull/7170
