### ISSUE TITLE
Post-build SDL should not need to rely on SetupMaestroVars if downloadArtifacts is set to false.

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#7095]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

If repos do not have build artifacts, but still want to run post-build sdl validation, they should not have to rely on setupMaestroVars, since they aren't publishing/there is no barBuildID, etc. Currently, there is no way to bypass this, and it's failing for folks like SignalR-Client-Cpp. This doesn't mean that sdl won't run, but it's painful for them to have that failing leg that they don't need to run anyway.

**Comment by BrennanConroy** [comment]
I guess you could say it's blocking us from on-boarding to component governance. You need a successful build before it lets you assign a branch.

**Comment by MattGal** [comment]
@adiaaida is going to look into this

**Comment by BrennanConroy** [comment]
Alternatively, is there a way to produce empty assets that will pass all the jobs arcade adds?

**Comment by adiaaida** [comment]
I'm not totally sure on that. However, you could, rather than adding the full post-build.yml template, simply add a new stage in your repo/pipeline that only calls execute-sdl.yml (this is probably the fastest path for you).

I do have something for this that I am testing, but I want to make really sure that it's not going to break existing infra.

**Comment by adiaaida** [comment]
Hey @BrennanConroy. We talked about this in our stand up today, and we think that, because your scenario is outside of the normal path, the correct solution for you will actually to be for you to call execute-sdl.yml directly, rather than using post-build.yml. Post-build.yml is very much tied to having artifacts to publish, so we think this is the right thing for your repo, since you do not have build artifacts. So your azure-pipelines.yml would instead have this code:

```
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - stage: post_build
    displayName: Post Build Validation
    jobs:
      - template: /eng/common/templates/job/execute-sdl.yml
        parameters:
          enable: true
          additionalParameters: ' -SourceToolsList @("policheck","credscan")
            -TsaInstanceURL $(_TsaInstanceURL)
            -TsaProjectName $(_TsaProjectName)
            -TsaNotificationEmail $(_TsaNotificationEmail)
            -TsaCodebaseAdmin $(_TsaCodebaseAdmin)
            -TsaBugAreaPath $(_TsaBugAreaPath)
            -TsaIterationPath $(_TsaIterationPath)
            -TsaRepositoryName "AspNetCore"
            -TsaCodebaseName "AspNetCore"
            -TsaPublish $True
            -PoliCheckAdditionalRunConfigParams @("UserExclusionPath < $(Build.SourcesDirectory)/eng/PoliCheckExclusions.xml")'
          continueOnError: false
          downloadArtifacts: false
```

**Comment by BrennanConroy** [comment]
Makes sense! I'll try that out.

**Comment by adiaaida** [comment]
Please let me know what I can do to help out. I am going to close this issue.
