### ISSUE TITLE
We need arg parsing scripts for windows and linux

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#71]
In order to standardize our scripts across all the repos we are going to need a set of arg parsing scripts that will be able to handle consistent properties passed to both our windows (build.cmd) and our linux (build.sh) scripts.

The repo api doc at https://github.com/dotnet/source-build/blob/dev/release/2.1/Documentation/RepoApi.md outlines how we plan to pass in common arguments. Spec snippets copied here for convenience:

## build.cmd/sh

Each repo will have two files that implement the repo API:

* build.cmd
* build.sh

The `.cmd` file will be called when running on Windows, while the `.sh` file will be called on all other operating systems.

These scripts will contain the logic necessary in order to build, test, publish the repo's assets.

source-build will invoke these scripts on each repo passing in:

1. An action to perform
1. A set of parameters

Individual repos are free to implement more features in these build scripts than what is required by source-build. For example, a repo may want to provide a default action. These extra behaviors are not defined by source-build.

### Actions

There will be a number of actions source-build will need the repos to implement. As more scenarios are designed and implemented, more commands will specified. The first action necessary is the `Build` action:

1. `Build` - Assemble the product from the current source contained in the repo.

Actions will take the form of `ActionName` and are the first parameter passed to the build script. Action names are case insensitive.

Note that actions don't have a leading dash `-`. Also note that individual repos can support a default action if one isn't specified. However, source-build will always specify an action explicitly.

### Parameters

Each action above will take a set of parameters used to pass information into the action and control its behavior.

Parameters will take the form of `-ParameterName ParameterValue`. This form avoids any confusion with file paths on Unix machines by not using `/` to start the argument and works well in both powershell and shell script parsing. Every parameter passed by source-build will have a value, even if that value is just `true`.

### Other questions/considerations:

1. Should we define a complete set of known properties/verbs? Or should we have the parsing scripts parse into a generic list of key/value pairs for the properties? Or perhaps a mix of both where we have set of common ones and allow for extras to be generically parsed and passed through (perhaps mapped to msbuild style properties). 
2. These scripts should be separate files so they can be reused by other scripts beyond build. There will definitely be a need for arg parsing at the script level for the native asset builds.
3. We want the arg style to work for the common shells (i.e. cmd/powershell on windows and bash on linux). This is how we arrived at the spec above, see the conversation at https://github.com/dotnet/source-build/issues/194. 
4. While build.cmd will be the entry point on windows it is fully expected that most of the heavy logic for the windows scripts will be in powershell scripts so the arg parser can be in powershell for windows.

**Comment by alexperovich** [comment]
Can we explore converging on powershell for build scripts now that powershell is cross-plat? Maintaining 2 versions of each script is akward and powershell does argument parsing and help output for free.

**Comment by weshaggard** [comment]
No we cannot converge on powershell that requires .NET Core to run which means we have nothing to use for building the native components to bootstrap a new platform. I think the best strategy is to minimize what we put into these scripts and jump into our build engines (cmake/msbuild) as quickly as possible.

**Comment by markwilkie** [comment]
@weshaggard - I believe you have this covered now?

**Comment by weshaggard** [comment]
I have part of this covered and I will try to write up the strategy as part of closing this issue. We probably still need to decide if we want to unify the parameter parsing between the ps1 and sh scripts however. Currently they are different then what is outlined in the proposal above.

**Comment by jcagme** [comment]
Pinging this issue to know is there is an update also to know if we should fit this in preview (before 12/14) or after. 

/cc: @weshaggard

**Comment by jcagme** [comment]
Not needed anymore.
