### ISSUE TITLE
Update Installer's repo name from "master" to "main" once that change has been made

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#7106]
As Installer is one of our "bellwether" repos for Arcade validation, we should ensure we're looking at the correct branch for their main/master. Once they have renamed their master branch to main, we should change that value in two places related to Arcade validation: 

- https://github.com/dotnet/arcade-validation/blob/master/azure-pipelines-bellwether-repos.yml#L38
- https://github.com/dotnet/arcade-validation/blob/master/eng/validation/update-channel.ps1#L72

/cc @dsplaisted and @marcpopMSFT

**Comment by marcpopMSFT** [comment]
@missymessa , I plan on updating to main on Thursday afternoon if you want to coordinate then.

**Comment by missymessa** [comment]
Thanks @marcpopMSFT! Just ping me whenever it's good to go and I'll get a PR up with the changes :)

**Comment by missymessa** [comment]
Looks like dotnet/installer is now on "main", so merging these PRs.

**Comment by missymessa** [comment]
Looks like Jakub beat me to the punch on this last Friday. Pipeline's been running fine, so closing.
