### ISSUE TITLE
Move aspnet/Scaffolding CI to VSTS (dev.azure.com/dnceng/public)

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#711]
VSTS public CI builds
- [x] public CI builds are building in VSTS (dnceng.visualstudio.com)
  - [x] Using YAML
  - [ ] Imports [base.yml](https://github.com/dotnet/arcade-minimalci-sample#base-your-builds-on-arcade-for-ease-of-use)

**Comment by chcosta** [comment]
aspnet/scaffolding.  I was told this was a "tier 1" repo.

**Comment by natemcmaster** [comment]
Ok. We can close this then (along with the related issues). Scaffolding is part of aspnet/Universe, so this will be addressed with https://github.com/dotnet/arcade/issues/677
