### ISSUE TITLE
Turn off Arcade Validation for Promotion scheduled runs

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#7110]
Arcade is now being promoted after successful runs of the Arcade Validation Official pipeline, and per our new policy/process, we are no longer validating Arcade against the bellwether repos in order to promote. Some clean-up we need to do now: 

- [x] Turn off the scheduled runs for the Arcade Validation for Promotion pipeline: https://dnceng.visualstudio.com/internal/_build?definitionId=838 (the schedule should be set in the UI). 
- [x] Remove the entry in the Build Monitor configuration for issues to be generated and sent to Missy. The pipeline will still be used, but on an as needed basis for contributors, and I don't need to know if they failed :)  https://github.com/dotnet/arcade-services/blob/master/src/DotNet.Status.Web/appsettings.json#L31-L34

**Comment by riarenas** [comment]
After talking to @missymessa, we're trying to move any promotion issues to be handled by FR. Should we move it to FR or expanded FR?

**Comment by MattGal** [comment]
**[Async Triage]** @ilyas1974 I think this is small enough to do as a regular FR issue, as long as you agree that promotion issues == FR which is OK by me.

**Comment by adiaaida** [comment]
PR for 2nd checkbox: https://github.com/dotnet/arcade-services/pull/1576
