### ISSUE TITLE
Feature Suggestion:  Add "Cancel Helix Job" Build task

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#7113]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

As noted here: https://developercommunity.visualstudio.com/t/ADO-pipeline-timeouts-dont-cancel-the-s/1371617?space=21&entry=myfeedback&viewtype=all, it seems that the automated cancellation feature I built doesn't run as often as we'd expect because it's far more common for a build to time out than be cancelled via push.  Perhaps ADO will fix this.

In the mean time, we could make it simpler to cancel jobs in this scenario by:

- Introduce a build task that, given a cancellation token (could use API Access token too but not necessary since all jobs produce unique cancellation tokens), calls the Helix API for job cancellation.
- Add ADO logging commands to emit all started jobs and their cancellation tokens for consumption by later steps

**Comment by akoeplinger** [comment]
This would be really helpful for the runtime-staging pipeline where we're battling with capacity issues on the Android devices Helix queue which means we run into timeouts quite often when a lot of work gets scheduled at the same time. This in turn exacerbates the issue because work items don't get canceled.

**Comment by alexperovich** [comment]
This functionality already exists in the WaitForHelixJobCompletion task, If the task gets canceled the job is canceled.

**Comment by MattGal** [comment]
> This functionality already exists in the WaitForHelixJobCompletion task, If the task gets canceled the job is canceled.

I know, I wrote it; this is for later one when they just want to explicitly cancel without cancelling the task.  Long story, happy to regale you with it any time after 3 PM PST.

**Comment by akoeplinger** [comment]
Yeah the problem is when a build runs into the job timeout AzDO will just kill the process, so the cancellation code in WaitForHelixJobCompletion doesn't run.

Until AzDO fixes this we'd like to run a subsequent task that uses `condition: canceled()` to cancel the pending workitems even on job timeouts.

**Comment by markwilkie** [comment]
We are definitely seeing higher pressure on machine queues - and this would likely help.  Thoughts from others?  

How expensive do you think it would be to do @MattGal ?

**Comment by MattGal** [comment]
> We are definitely seeing higher pressure on machine queues - and this would likely help. Thoughts from others?
> 
> How expensive do you think it would be to do @MattGal ?

SWAG: 1-2 days.  All the pieces are already there in the SDK, this would just be stitching them together.

**Comment by MattGal** [comment]
**[Async Triage]** the last poster has a good point.

**Comment by riarenas** [comment]
If this is causing pain and it's not expensive as per Matt's point, this could probably be done as part of FR?

**Comment by MattGal** [comment]
> If this is causing pain

Yes, if used by the Helix Android runs to work around AzDO's limitation, it would drastically reduce pain in PRs that need Android testing because it would prevent hundreds of hours of usage of limited hardware.

**Comment by MattGal** [comment]
Grabbing this one as it should be pretty quick.

**Comment by MattGal** [comment]
https://github.com/dotnet/arcade/pull/7185

**Comment by MattGal** [comment]
As this is an Arcade change that's now in master, I am closing the issue; natural dependency flow should get it to the runtime team next week.
