### ISSUE TITLE
Unable to subscribe repo to Dependency flow

### ISSUE THREAD

**Issue by dmonroym** [dotnet/arcade#7150]
Moved the [dotnet/NuGet.BuildTasks](https://github.com/dotnet/NuGet.BuildTasks) repo to arcade but we haven't been getting dependency updates. I tried running `darc add-subscription` but get the following error:

```
fail: Microsoft.DotNet.Darc.Operations.Operation[0] Failed to create subscription: {"message":"The request is invalid","errors":["Target repository URL should be one of the following forms: https://github.com/:org/:repo or https://dev.azure.com/:account/:project/_git/:repo"]}
```
I'm assuming this is due to the . on our repo name

**Comment by riarenas** [comment]
Looks like there's a bug in the validation of the target repository. We can probably work around this, but I would like to understand how depedency flow is blocking the repository from building?

**Comment by dmonroym** [comment]
Discussed offline. This isn't the reason why I'm blocked so I'm editing to remove that.

**Comment by riarenas** [comment]
It looks like it's a silly regex bug here, where we simply don't allow `.` as a valid character in the repo name: https://github.com/dotnet/arcade-services/blob/737108990a317c591d6beb46197a1b094e5979a6/src/Maestro/Maestro.Web/RepositoryUrlAttribute.cs#L46

**Comment by riarenas** [comment]
I think this is FR worthy, as this is blocking some repos from onboarding into dependency flow.
