### ISSUE TITLE
Dev WF: Investigate on how to keep the build analysis check high in the list

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7194]
It's sometimes hard to find the build analysis check. Ideally it would be high up in the list. See if there is a way to do this. It might be something like this:

- When a PR is opened, immediately create the check (don't wait till AzDO is done)
- If an azdo check we are analyzing fails, change the build analysis to failed. Otherwise it will always fall below the failing checks.
- To keep it at the top, change it to "passed", then back to "failed". This may bump it.

**Comment by missymessa** [comment]
This should be in M2. We will keep an eye on discoverability, though. Closing.
