### ISSUE TITLE
Dev WF: Investigate UX improvements with mockups and users

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7195]
The layout and formatting of the GitHub checks is difficult to get "right". There are many options, and we need user feedback to determine what people like and can read best. We should do a small user study. Perhaps present a number of mockups with small tweaks, over time as the checks tab changes.

Here is a start. These are build only. We should try to be consistent between builds and tests where possible:

Based on this PR: https://github.com/dotnet/aspnetcore/pull/31506
1. get rid of "not failing in main" unless actually failing, rid of the log links, code block error line, and link it: https://gist.github.com/mmitche/084269b27bcd24f1afab6a0fad868ddb
2. get rid of "not failing in main" unless actually failing, keep the log links, but code block the error line: https://gist.github.com/mmitche/666ba9f51415b2d493df180133c6d41d
3. Same as 2 except it's failing in main. https://gist.github.com/mmitche/9899e418894c5bd46e6dab9ee8d5ab73.

**Comment by MCCshreyas** [comment]
So someone was looking at my PR. 😄😄😄

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade/issues/7285

**Comment by missymessa** [comment]
Mitchell needs to do a write up on his findings.

**Comment by missymessa** [comment]
Closing this. Mitchell created https://github.com/dotnet/arcade/issues/7475 based on feedback from folks using mock-up he created.
