### ISSUE TITLE
Dev WF: Job name listed twice in build results

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7196]
See: https://github.com/dotnet/aspnetcore/pull/31506/checks?check_run_id=2270519548

Build / Test: macOS 10.14 / **Test: macOS 10.14** / Run build.sh

**Comment by missymessa** [comment]
PR: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/15361

**Comment by missymessa** [comment]
Looks like this is fixed. Closing. 

![image](https://user-images.githubusercontent.com/47990216/122618893-0c70ba80-d044-11eb-9324-a53c72c7961b.png)
