### ISSUE TITLE
Staging pipeline should use add-build-to-channel to avoid needing arcade updates for new channels

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7200]
Example: https://dev.azure.com/dnceng/internal/_build/results?buildId=1072719&view=logs&j=06e47235-ea4e-5696-bf7a-60141ec0f646&t=7adbb44b-0920-5500-2f14-2ac5aa500441

The publishing pipeline is calling the publish tasks to push to staging. The problem is that if arcade has has not been updated in dotnet-release, then it's possible the target channels won't exist. This will lead to failure to publish to the staging location.

I think it should be possible to use the standard arcade publsihing script (https://github.com/dotnet/arcade/blob/main/eng/common/post-build/publish-using-darc.ps1) to call the promotion job, with additonal parameters for the feed overrides. This will avoid being dependent on an arcade update for channels.

**Comment by mmitche** [comment]
@adiaaida

**Comment by adiaaida** [comment]
So instead of calling publishing directly, we would create the various BlobArtifacts, PackageArtifacts, etc directories for each build in the manifest.json, publish those, and then call add-build-to-channel? I guess that could work.

**Comment by mmitche** [comment]
@adiaaida Hmm I had forgotten about that part. I think add-build-to-channel is going to try and download the original build artifacts. That makes this approach tougher...

**Comment by jakubstilec** [comment]
**[Async Triage]** Should this be part of some Arcade improvements?

**Comment by adiaaida** [comment]
Probably should be #6418.

**Comment by riarenas** [comment]
assigned to #6418

**Comment by adiaaida** [comment]
@mmitche I think I am going to close this issue as I don't actually think it's feasible to use add-build-to-channel in the way you've suggested. I am more in favor of simply updating the .net version dotnet-release uses so that it can get arcade updates automatically instead of on demand. Thoughts?

**Comment by mmitche** [comment]
Fine by me.
