### ISSUE TITLE
Stable publishing should update latest links

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7201]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The stable publishing feed config is skipping the aka.ms links. I think this is most likely a hold-over from old cases where we overwrote non-stable blob locations. This is no longer the case, and I think it can be changed to publish latest links.

/cc @epananth do you happen to remember anything about this?

**Comment by jakubstilec** [comment]
**[Async Triage]** @adiaaida could this be added to #5757?

**Comment by adiaaida** [comment]
Yes. But I think @mmitche  already checked in the change for this, so it might just be able to be closed.

**Comment by riarenas** [comment]
I haven't seen any changes to arcade that would fix this. Adding to Unified Build Access epic, and if it's done or not needed can be closed.

**Comment by adiaaida** [comment]
If I'm not mistaken, it's this: https://github.com/dotnet/arcade/pull/7203

**Comment by riarenas** [comment]
Yep I'm just blind, that looks like exactly this.

**Comment by adiaaida** [comment]
Cool. I *think* this can be closed then. Going to do that, and Matt can reopen if that was wrong.
