### ISSUE TITLE
Should Microsoft.DotNet.Build.Tasks.Feed be conditionally referenced

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/arcade#7205]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

As part of moving Roslyn to Arcade 6 (https://github.com/dotnet/roslyn/pull/52255), we had to add an additional package reference for Microsoft.DotNet.Build.Tasks.Feed. Normally this would be covered by the Build.proj restoring the Tools.proj. However, Roslyn performs a Restore separate from the Build and Publish steps.
https://github.com/dotnet/roslyn/blob/98530991561773ac1fbc2c511f40eab211a11790/eng/pipelines/build-windows-job.yml#L36-L46

Restoring Tools.proj requires Restore to be true
https://github.com/dotnet/arcade/blob/0b4d6253f298a5f9d6e2c4bd20e1de33a6763061/src/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj#L181-L187

and then within Tools.proj the PackageReference is conditioned on Publish being true as well.
https://github.com/dotnet/arcade/blob/0b4d6253f298a5f9d6e2c4bd20e1de33a6763061/src/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj#L32

Is it necessary to conditionally reference this package?

**Comment by jakubstilec** [comment]
**[Async Triage]** Is this a FR question? CC @ilyas1974.

**Comment by alexperovich** [comment]
We can remove the condition easily, but that would mean that every build that ever happens would restore this package, even if it wasn't going to do any publishing. I don't know how much extra time that would be given that we restore hundreds of packages already. It might be fine.

**Comment by MattGal** [comment]
[Async Triage]  Given the size of the other files in the nupkg graph for our builds, I think always restoring this just doesn't matter in the scale of how much network and disk capacity is going towards other stuff (like the jillionth download of NewtonSoft).

- While I think this is harmless to do though, I don't see it being FR; I would LGTM on a PR that removed the condition though, assuming we'd tested it appropriately
- IIRC, certain pieces of Tasks.Feed has some challenges on other OSes ; we need to be sure restoring it in linux and mac builds is OK.

**Comment by jakubstilec** [comment]
[Async Triage] I'm unable to find out under which epic this item belongs.

**Comment by jakubstilec** [comment]
[Async Triage]: @MattGal how much work is for this on our side?

**Comment by markwilkie** [comment]
@JoeRobich - any chance you want to submit a PR for this?

**Comment by MattGal** [comment]
> [Async Triage]: @MattGal how much work is for this on our side?

It's about 2 minutes of work then about a week of watching it flow through the system to see if there's some 'ah ha, we shouldn't have done that' moment or not.

**Comment by MattGal** [comment]
Discussed a bit more with @JoeRobich .  I'm just going to throw this in FR and create add a check for a new property named "AlwaysRestoreArcadeFeedTasks" in the proj to allow getting this to restore without having to universally do the restore (where it might not always work on some OSes) or turning on the Publish machinery.

**Comment by MattGal** [comment]
https://github.com/dotnet/arcade/pull/7356

**Comment by MattGal** [comment]
change merged, I'll leave in validate and check back periodically for fallout.  Once an official Arcade publishing job runs with it, I think we're clear.

**Comment by MattGal** [comment]
Seems to have not blown up the universe.
