### ISSUE TITLE
Move WebSDK CI to VSTS (dev.azure.com/dnceng/public)

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#721]
VSTS public CI builds
- [ ] public CI builds are building in VSTS (dnceng.visualstudio.com)
  - [ ] Using YAML
  - [ ] Imports [base.yml](https://github.com/dotnet/arcade-minimalci-sample#base-your-builds-on-arcade-for-ease-of-use)

**Comment by natemcmaster** [comment]
Adding @vijayrkn since the aspnet/websdk falls under his team.

In theory, this should be easy. IIUC aspnet/websdk already builds in vsts and is under the devdiv account. @vijayrkn is there someone on your team that could take on websdk + Arcade related work?

**Comment by chcosta** [comment]
this is done
