### ISSUE TITLE
Symbols publishing is not publishing symbols packages

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#7226]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

Symbols validation is failing for 455 packages in the most recent release run: https://dev.azure.com/dnceng/internal/_build/results?buildId=1072719&view=logs&j=b30a92fc-e51b-572d-9566-e3b9dae8a01d

With so many packages failing to validate symbols, it makes me wonder if there is an issue with symbols publishing.

/cc: @epananth @mmitche

**Comment by adiaaida** [comment]
I think this is the issue. dotnet-symbol (in symstore repo) uses:

```
--microsoft-symbol-server                         Add 'http://msdl.microsoft.com/download/symbols' symbol server path (default).
--internal-server                                 Add 'http://symweb.corp.microsoft.com' internal symbol server path.
```

Where as we publish to:

```
private const string SymwebServerPath = "https://microsoft.artifacts.visualstudio.com/DefaultCollection";
private const string MsdlServerPath = "https://microsoftpublicsymbols.artifacts.visualstudio.com/DefaultCollection";
```

**Comment by hoyosjs** [comment]
@adiaaida this is normal. https://microsoft.artifacts.visualstudio.com/DefaultCollection is symweb's publishing endpoint, the internal server. Whereas the other one is microsoft's public publishing endpoint.

**Comment by adiaaida** [comment]
The point was more that the two symweb links didn’t match and the two msdl links didn’t match, though I agree that after looking at code history that it is probably a red herring, and the real issue is something else

**Comment by adiaaida** [comment]
Renamed this, as the real issue is that symbols publishing is broken. Also adding to the publishing epic

**Comment by ViktorHofer** [comment]
Blocking Preview 4. cc @leecow @Chrisboh

**Comment by adiaaida** [comment]
Thanks for the clarification @hoyosjs. That's super helpful.

@epananth and I have looked into this and I believe we know what the issue is. I think Epsi should have a PR to fix it out today.

**Comment by epananth** [comment]
I am running a test, and validating the changes using https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-symbol.

**Comment by epananth** [comment]
https://github.com/dotnet/arcade/pull/7275
