### ISSUE TITLE
Remove dependency on AssetManifests folder

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#7235]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

May be we can remove this condition https://github.com/dotnet/arcade/blob/04e32d778d4dd32980c09017a43be5df25e02714/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/PublishArtifactsInManifest.proj#L95

https://github.com/dotnet/arcade/blob/04e32d778d4dd32980c09017a43be5df25e02714/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/PublishArtifactsInManifest.proj#L89

Since we are downloading the mergedManifest.xml, not sure if this will impact the release pipeline. 

cc: @adiaaida , @mmitche , @riarenas

**Comment by adiaaida** [comment]
I don't think this should affect the release pipeline, as we set BlobBasePath and ManifestsBasePath to the same thing. My only concern is getting the MergedManifest.xml files published like they were before, since that is breaking post-build signing (no MergedManifest = no signing)

**Comment by riarenas** [comment]
Added to unify and improve publishing across .NET

**Comment by epananth** [comment]
I removed the dependency on asset manifest folder, since we just need merged manifest. Now we only download the mergedmanifest. Closing this one
