### ISSUE TITLE
We need duplicate aka.ms links for GA sdk builds

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#7239]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Sdk builds for GA need to be accessible using aka.ms links with the A.B.Cxx format (currently available) and the A.B format (currently not implemented). We need to rearchitect how aka.ms links are generated in the RM pipeline code so that we can produce multiple aka.ms links for the same file.

**Comment by riarenas** [comment]
Adding to Release epic: #6418
