### ISSUE TITLE
GA aka.ms links need to have productVersion.txt files next to them for install scripts

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#7240]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Without having the productVersion.txt files, the install scripts can't verify the version that was downloaded. When we create the aka.ms links for GA, they point to download.visualstudio.com locations, and we don't publish the productVersion.txt files, which we may need to do.

/cc: @leecow @mmitche @bozturkMSFT

**Comment by riarenas** [comment]
Adding to Release epic: https://github.com/dotnet/arcade/issues/6418
