### ISSUE TITLE
MSBuild official builds from VSTS (dev.azure.com/dnceng/internal)

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#725]
Official builds on VSTS - https://github.com/dotnet/arcade/blob/master/Documentation/VSTS/MovingFromDevDivToDncEng.md
- [ ] Official builds are building in VSTS (dnceng)
  - [ ] Using YAML
  - [ ] Referencing [base.yml](https://github.com/dotnet/arcade-minimalci-sample#base-your-builds-on-arcade-for-ease-of-use)

**Comment by chcosta** [comment]
This is done

**Comment by rainersigwald** [comment]
Our official build still runs from devdiv, but it is in Azure DevOps and YAML driven. Do you need/want more?

**Comment by chcosta** [comment]
I saw [this](https://dev.azure.com/dnceng/internal/_build?definitionId=285) build definition, and thought the work was done (just noticed all the recent builds are failing there).  We'll still want your builds to move into dnceng so that we can provide better support (there are features / throughput / etc... things we can only provide support for in dnceng).
