### ISSUE TITLE
Change arcade-pool-provider's deployment to use yaml pipelines

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7250]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Currently the deployment process for the arcade-pool-provider involves running a build which kicks off an RM pipeline which does the actual deployment. 

The release pipelines are deprecated, hard to find, and to diagnose. We should move this repo to use the same process all our other repos use, where the yaml pipeline takes care of building and deploying.

**Comment by riarenas** [comment]
I'm adding this to the deployment improvements phase 2 epic. I don't think it makes sense as part of FR

**Comment by MattGal** [comment]
This is no longer a thing, so closing.
