### ISSUE TITLE
Remove separated build drop directories from gather-drop by default

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7251]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

By default, gather-drop creates a unified directory as well as separated directories per repo. This effectively ends up doubling the size of the download directory (though each file is only downloaded once). With the vsufile removal, the separated drops aren't actually even uploaded to the build artifacts.

We should remove the separated drop by default, and add a switch for --separated so that it can be created if necessary.

**Comment by adiaaida** [comment]
Marked this as blocking, as it prevents our ability to do a multiple sdk release, as the drop is too big (~115GB for the 5.0.104/5.0.201 release which is more than the buildpool machines can handle).

**Comment by riarenas** [comment]
If this is blocking, do you see this as an FR issue? or should it be taken care of as part of the next release epic? It seems somewhat big for an FR task.

**Comment by adiaaida** [comment]
I think we can put this in the release epic, and recognize that it needs to be done in order for us to continue working on https://github.com/dotnet/core-eng/issues/12336.
