### ISSUE TITLE
Roslyn failing with conflicting FileSignInfo entries

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/arcade#7260]
- [x] This issue is blocking us from moving to v3 publishing 
- [ ] This issue is causing unreasonable pain

I'm trying to setup Roslyn with v3 publishing and hit a snag. Here is the test build https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4661139&view=logs&j=29d4eac0-e772-56a4-ad0d-2d727d908ceb&t=4edcb01d-2da8-54c4-439e-584d3c1a5e90
 
The publishing pipeline fails claiming we have duplicate FileSignInfo entries for a few assemblies https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4661624&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a

> The following files have conflicting FileSignInfo entries: Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.dll, Microsoft.CodeAnalysis.ExpressionEvaluator.FunctionResolver.dll, Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.dll, Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.ResultProvider.dll

It is true there are multiple entries in the Signing.props for these, but each entry has a unique TargetFramework. https://github.com/dotnet/roslyn/blob/4b27a2d2e2db875e2c01615f1020dc767aa38770/eng/Signing.props#L14-L22
 
I found https://github.com/dotnet/arcade/issues/7064 which seems similar, but Roslyn is already building with the version of Arcade that resolved the issue for Symreader.

**Comment by epananth** [comment]
I took a look at the versions.props file, this is still referring to older version of Feeds Task 
https://github.com/dotnet/roslyn/blob/1e70c73bf107bfa640bab0ccf9fdea24d4168cea/eng/Versions.props#L95

Also I see you have not got the latest arcade update in quite some time.

**Comment by JoeRobich** [comment]
@epananth Thanks for looking into it. This package was added to work around https://github.com/dotnet/arcade/issues/7205. Indeed this package version has become separated from the Arcade SDK version we are using. Is there an easy way to have this package version updated when Arcade updates?

**Comment by epananth** [comment]
I am going to run a test now, by updating the microsoft.dotnet.build.tasks.feed version to the latest one that we have in arcade. I'm hoping that should fix that issue. 
 
After that we need to discuss about the way roslyn builds. To on-board to V3 publishing, building from Azdo mirror is a must. Let's discuss that after I run this test.

**Comment by epananth** [comment]
Easy way to update package version through arcade update would be using 
darc add-dependency to the package 

https://github.com/dotnet/arcade/blob/main/Documentation/Darc.md#adding-dependencies-to-a-repository

**Comment by JoeRobich** [comment]
> To on-board to V3 publishing, building from Azdo mirror is a must

I am working on moving us to dnceng this sprint.

**Comment by JoeRobich** [comment]
Same failure in dnceng build https://dev.azure.com/dnceng/internal/_build/results?buildId=1100637&view=results

**Comment by jakubstilec** [comment]
[Async Triage]: @epananth could you see to which epic should this go?

**Comment by MattGal** [comment]
[Async Triage]: I didn't realize that I already fixed this, I'll take this one myself as I already did the work.

**Comment by MattGal** [comment]
v3 publishing is working ([example build](https://dev.azure.com/dnceng/internal/_build/results?buildId=1119478&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073) ) with latest arcade, and the changes are already in all v3-publishing arcade branches, so closing this as done.
