### ISSUE TITLE
Investigate ways to reorder build queues in AzDO

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7268]
There are occasional times when we need a specific build done ASAP. When queues are heavy with builds, these builds can get stuck while existing work clears out.

It would be great to have a way to reorder the queue or just send specific builds to the front of the queue.

**Comment by Chrisboh** [comment]
There is no good consistent way to do this as we don't own all the ways in which builds happen.  For example, anything that happens in the hosted pools will always be at the mercy of what ever AzDo supports.  As for the queues we do support there are technically a few ways we could implement this but I would advise against it as I can't think of a way to stop anyone from just bumping their builds to the front of the stack.  

Honestly though I think the thing that is going to help the most is the work that should be finished by Ulises and Lukas by the end of this month which is to have the ability to redirect builds into their own subscription.  Doing this will pull all of the runtime builds into their own sub which should leave the queues in Helix Prod with significantly lower wait times.

**Comment by mmitche** [comment]
> There is no good consistent way to do this as we don't own all the ways in which builds happen. For example, anything that happens in the hosted pools will always be at the mercy of what ever AzDo supports. As for the queues we do support there are technically a few ways we could implement this but I would advise against it as I can't think of a way to stop anyone from just bumping their builds to the front of the stack.
> 
> Honestly though I think the thing that is going to help the most is the work that should be finished by Ulises and Lukas by the end of this month which is to have the ability to redirect builds into their own subscription. Doing this will pull all of the runtime builds into their own sub which should leave the queues in Helix Prod with significantly lower wait times.

Primarily I'm thinking mostly about AzDO builds, rather than test queues (in this case most of the time it's official builds, which aren't running tests). So this is more of a hopeful feature on the AzDO side.

**Comment by jakubstilec** [comment]
[Async Triage]: @mmitche, @Chrisboh should we convert this into an epic?

**Comment by markwilkie** [comment]
This keeps coming up, but I have yet to hear that it's worth the effort.  Maybe now it is with more releases?

**Comment by Chrisboh** [comment]
@mmitche have you by chance had time to look at the data on how much this is impacting builds?  I am with Mark in that I am struggling to see the ROI of doing the work.

**Comment by mmitche** [comment]
I think it's somewhat hypothetical? IMO low ROI vs. other improvements. I can only think of a small handful of times when I was wanting a build to jump the queue.

**Comment by Chrisboh** [comment]
Based on the fact that you think it has low ROI should we close this now and reopen when its more impactful or do you think it is worth keeping around?
