### ISSUE TITLE
Q: build.sh using system install dotnet

### ISSUE THREAD

**Issue by tmds** [dotnet/arcade#7278]
Is there a way to stop the `build.sh` script (that is used from arcade by several repositories) from downloading an SDK, and make it use what the system has?

cc @ViktorHofer

**Comment by hoyosjs** [comment]
It should use your install, provided that it is at least the version of tools.dotnet in global.json - like in https://github.com/dotnet/arcade/blob/90af68df86e2c126c1804f962284581f482becb9/global.json#L3 - and [this config](https://github.com/dotnet/diagnostics/blob/8232b6cbdfc7804c9fb4064434f51f9a897298ba/eng/configure-toolset.sh#L5)  isn't set.

**Comment by ViktorHofer** [comment]
It must be the exact same version as the dotnet entry in our global.json, currently Preview 2. Will be preview 3 on the first Monday of the month.

**Comment by tmds** [comment]
Thanks for the info. I was looking for some flag/envvar to control this. I can update the global.json version and use_installed_dotnet_cli instead.
