### ISSUE TITLE
Make V3 publishing default in main 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#7284]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Right now repos have an option to switch to V2/ V3 publishing. Going forward V3 is the only source of truth for all the repos using the latest arcade update ( main branch) . So defaulting publishing to V3. 

cc: @mmitche

**Comment by jakubstilec** [comment]
[Async Triage]: @epananth  why it was removed from #5789, do we another epic for this?

**Comment by epananth** [comment]
This has been done. Closing this issue
