### ISSUE TITLE
Aka.ms links are not available for "-Quality preview"

### ISSUE THREAD

**Issue by bekir-ozturk** [dotnet/arcade#7295]
- [x] This issue is blocking - install script update with aka.ms link support cannot be released.
- [ ] This issue is causing unreasonable pain

The aka.ms link for `-Channel 6.0 -Quality preview` doesn't point to a file: https://aka.ms/dotnet/6.0/preview/dotnet-sdk-win-x64.zip
Is this already implemented so that the links will be available with preview4 or do we still have some work to do to get preview channel to work?

cc @adiaaida

**Comment by markwilkie** [comment]
Moving into the unified build epic

**Comment by adiaaida** [comment]
The release team has not been running the aka.ms link generation or repo propagation stages as part of the preview releases, as far as I can tell. I will reach out to Rahul to check with him, and see if we can get those running for preview. But this is why -Quality preview doesn’t work

**Comment by adiaaida** [comment]
I apparently fixed this, but never closed the issue.
