### ISSUE TITLE
Unix: VersionSuffixDateStamp is not setting for libraries subset in official builds

### ISSUE THREAD

**Issue by am11** [dotnet/arcade#7326]
In the official builds on Linux x64, this condition seem to be failing (only) for libraries subset, because `VersionSuffixDateStamp` is empty:
https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.targets#L28-L34

as a result, the version information in native shared libraries produced by libraries subset is set to default placeholder value in the official builds, The value `42.42.42.42424` is meant only for local or unofficial builds. All the other native/ELF files (shared libraries and various executables) have the version properly set.

#### Repro
```sh
# bash on Ubuntu x64

# download latest nightly build in tmp
$ mkdir /tmp/.dotnet6
$ curl -sSL https://aka.ms/dotnet/6.0/daily/dotnet-sdk-linux-x64.tar.gz | tar xzf - -C /tmp/.dotnet6

# generate version report of all ELF files
$ printf "| binary filename | version info in binary |\n| --- | --- |\n" > ver-report.md
$ find /tmp/.dotnet6 -exec sh -c \
  'if file {} | grep -q ELF; then printf "| \`{}\` | \`%s\` |\n" "$(strings {} | grep "(#)")"; fi' \; >> ver-report.md
$ cat ver-report.md
```

| binary filename | version info in binary |
| --- | --- |
| `/tmp/.dotnet6/sdk/6.0.100-preview.5.21230.4/AppHostTemplate/apphost` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |
| `/tmp/.dotnet6/host/fxr/6.0.0-preview.5.21229.9/libhostfxr.so` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |
| `/tmp/.dotnet6/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.0-preview.5.21229.9/runtimes/linux-x64/native/apphost` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |
| `/tmp/.dotnet6/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.0-preview.5.21229.9/runtimes/linux-x64/native/singlefilehost` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |
| `/tmp/.dotnet6/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.0-preview.5.21229.9/runtimes/linux-x64/native/libnethost.so` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |
| `/tmp/.dotnet6/dotnet` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |
| `/tmp/.dotnet6/shared/Microsoft.NETCore.App/6.0.0-preview.5.21229.9/libdbgshim.so` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |
| `/tmp/.dotnet6/shared/Microsoft.NETCore.App/6.0.0-preview.5.21229.9/libSystem.Native.so` | `@(#)Version 42.42.42.42424` |
| `/tmp/.dotnet6/shared/Microsoft.NETCore.App/6.0.0-preview.5.21229.9/libclrjit.so` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |
| `/tmp/.dotnet6/shared/Microsoft.NETCore.App/6.0.0-preview.5.21229.9/libSystem.Security.Cryptography.Native.OpenSsl.so` | `@(#)Version 42.42.42.42424` |
| `/tmp/.dotnet6/shared/Microsoft.NETCore.App/6.0.0-preview.5.21229.9/libSystem.IO.Compression.Native.so` | `@(#)Version 42.42.42.42424` |
| `/tmp/.dotnet6/shared/Microsoft.NETCore.App/6.0.0-preview.5.21229.9/libhostpolicy.so` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |
| `/tmp/.dotnet6/shared/Microsoft.NETCore.App/6.0.0-preview.5.21229.9/libmscordaccore.so` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |
| `/tmp/.dotnet6/shared/Microsoft.NETCore.App/6.0.0-preview.5.21229.9/libcoreclr.so` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |
| `/tmp/.dotnet6/shared/Microsoft.NETCore.App/6.0.0-preview.5.21229.9/libSystem.Net.Security.Native.so` | `@(#)Version 42.42.42.42424` |
| `/tmp/.dotnet6/shared/Microsoft.NETCore.App/6.0.0-preview.5.21229.9/libSystem.Globalization.Native.so` | `@(#)Version 42.42.42.42424` |
| `/tmp/.dotnet6/shared/Microsoft.NETCore.App/6.0.0-preview.5.21229.9/createdump` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |
| `/tmp/.dotnet6/shared/Microsoft.NETCore.App/6.0.0-preview.5.21229.9/libmscordbi.so` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |
| `/tmp/.dotnet6/shared/Microsoft.NETCore.App/6.0.0-preview.5.21229.9/libcoreclrtraceptprovider.so` | `@(#)Version 6.0.21.22909 @Commit: 49aec59e52d2f0bc8e2acd297023aa8464aee00c` |

as we can see only the binaries produced by libraries subset have the wrong default version, rest have it properly set.

**Comment by am11** [comment]
cc @safern, I can't seem to fond the official build YAML, so need your help for this one. :)

Since VersionSuffixDateStamp [depends on](https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets) OfficialBuild property, could the rootcause be that for other (non-libraries) subsets, we are setting: `/p:OfficialBuild` and <code>/p:OfficialBuild<ins>Id</ins></code>
but for libraries we are only setting <code>/p:OfficialBuild<ins>Id</ins></code> (but not `/p:OfficialBuild=true`)?

**Comment by MattGal** [comment]
[Async Triage] :  @am11 , all the official runtime YAML is actually in the public github repo, just look for the conditions to find it, e.g. [some CoreCLR build jit job](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/eng/pipelines/coreclr/templates/build-jit-job.yml#L98) .  

I'm looking to see if this works when the property is set elsewhere (such as in Arcade's own builds) and if so I suggest we move this issue to dotnet/runtime.

**Comment by safern** [comment]
I thought that `OfficialBuild` was set by arcade to true if `OfficialBuildId != ''`. We've never set `OfficialBuild == true` in libraries and it has always worked as expected, so I think something else is going on here rather than being an issue with the yaml. Two properties shouldn't be required for this purpose in my opinion. It is better to have the flag be set if the id is not empty.

The yaml files for official build are the same as the ones for CI we just condition them based on the project name. Here is the official build entrypoint yaml though: https://github.com/dotnet/runtime/blob/main/eng/pipelines/runtime-official.yml

**Comment by MattGal** [comment]
@safern are you thinking this is a regression? if so, do you have a rough guess of when?

**Comment by am11** [comment]
Thanks.

The Linux results in table above are inline with Windows. On Windows, we are also getting the placeholder file and product version in native dlls built as part of libraries subset:

latest archive: https://aka.ms/dotnet/6.0/daily/dotnet-sdk-win-x64.zip

![image](https://user-images.githubusercontent.com/3840695/117399997-6db45280-af0a-11eb-906a-1569ee0e28c3.png)

(note that the `Product name` field also seem unexpected above..)

all the other managed libraries as well as native dlls in that archive have the proper file and product version:

![image](https://user-images.githubusercontent.com/3840695/117399882-30e85b80-af0a-11eb-9281-114c1365e883.png)

![image](https://user-images.githubusercontent.com/3840695/117399708-d6e79600-af09-11eb-953a-958e73a73228.png)

It looks like other arcade-powered repos are setting `DotNetUseShippingVersions=true` and satisfying this condition
https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets#L39
I am not sure where the coreclr and installer subsets are setting `OfficialBuild` or `DotNetUseShippingVersions`, but if they didn't they had also ended up using the default `42.42.42.42424` binary version. 😕

I think @safern's approach to fix this is cleaner:

```diff
- <PropertyGroup Condition="'$(OfficialBuild)' == 'true' or '$(DotNetUseShippingVersions)' == 'true'"> 
+ <PropertyGroup Condition="'$(OfficialBuild)' == 'true' or '$(OfficialBuildId)' != '' or '$(DotNetUseShippingVersions)' == 'true'"> 
```
i.e. without needing to additionally define DotNetUseShippingVersions=true in runtime repo.

**Comment by riarenas** [comment]
I think we would welcome a PR with this change, but seeing how it only manifests in a particular scenario in the runtime repo and there's a workaround for it, it won't get addressed soon. Maybe it should go in the Arcade SDK epic (https://github.com/dotnet/arcade/issues/2053) unless someone thinks this somehow meets the bar for FR?

**Comment by safern** [comment]
> I think @safern's approach to fix this is cleaner:

Rather than expanding that condition, what I meant is that `OfficialBuild` should be set to true when `OfficialBuildId != ''`. However it seems like that is the intent, but something in ordering is wrong here:

https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L12

**Comment by am11** [comment]
Looks like DefaultVersions.props is imported by Settings.props, which is then imported by (arcade) Sdk.props conditionally:
https://github.com/dotnet/arcade/blob/e8d0df4f35cfa23174fe7204ef958cf5d1b8e797/src/Microsoft.DotNet.Arcade.Sdk/sdk/Sdk.props#L11
it seems in the runtime repo, it should be true for all subsets' official builds, but somehow it is evaluating to false (only) for the `Libs` subset. That or something more interesting is happening. 🙂

**Comment by am11** [comment]
This was a regression from 3.1, fixed in runtime repo. Thanks!
