### ISSUE TITLE
Update channel ids in post-build.yml

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#7332]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

From Miha:

> We’re seeing the following error on the internal YARP pipeline (for builds on the main branch):
> “Channel 1299 is not present in the post-build YAML configuration! This is an error scenario. Please contact @dnceng.”
> [build results](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D1118427%26view%3Dlogs%26j%3Da13e9384-d6d3-5a14-7a96-79282fc11262%26t%3D62b78796-390e-5a19-0957-0b46593907e3%26l%3D13&data=04%7C01%7Cmichelm%40microsoft.com%7C573da929ff5f4394556508d90e4425b9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637556508152884604%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6LrfgQ9W7hJppiugRRdQR1C8CT28mOVmlGg881CHg6g%3D&reserved=0)
> This started last Thursday (29th).

eng/common/templates/post-build/post-build.yml needs to be updated with the latest supported channels for folks still on publishing v2.

**Comment by riarenas** [comment]
There’s a few things going on here:

* It looks like the main branch was previously publishing to the “.net 5 dev” channel, and that was changed to the “.net 5” channel. 
```
darc get-default-channels --source-repo reverse-proxy
(3499) https://github.com/microsoft/reverse-proxy @ main -> .NET 5
``` 
* The repository is using the deprecated version 2 publishing, which does not allow to publish to the .net 5 channel. If you wish for your main branch to publish to the “.NET 5” channel, you will need to update to the new version 3 publishing. These are the steps for this: https://github.com/dotnet/arcade/blob/main/Documentation/CorePackages/Publishing.md#how-to-upgrade-from-v2-to-v3

* The branch is using an arcade SDK from February. There might be failures when moving to version 3 unless the repo takes an up to date version of Arcade. 


FYI @MihaZupan 

Closing this as the issues appear to be repo specific and not related to infra. Feel free to reopen if there's something else we should take a look at.
