### ISSUE TITLE
Inform repos using v2 publishing that v3 exists

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7333]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We get a few questions a month for publishing related errors where the answer is "you're using v2 publishing, we're not fixing v2, please move to v3 to get your scenario unblocked". 

Perhaps it would be useful to add something to the builds still using v2 to let them know that they should really be considering moving to v3 as fixes for v2 are not going to happen, and the actual plan is to remove the v2 templates altogether?

**Comment by riarenas** [comment]
FYI @epananth  @mmitche

**Comment by mmitche** [comment]
Yeah....can we add a warning or message into the template?

**Comment by MattGal** [comment]
[Async Triage]:  Doesn't have a home, might be worth handling via FR if @ilyas1974 agrees since FR deals with a fair percentage of these questions.

**Comment by riarenas** [comment]
I agree with @MattGal on triage.

**Comment by markwilkie** [comment]
@ilyas1974 ?

**Comment by ilyas1974** [comment]
Yes, we can take a look at this in FR.

**Comment by MattGal** [comment]
Created https://github.com/dotnet/arcade/pull/7415/files.  Will test in the morning

**Comment by MattGal** [comment]
Distracted by a few things, but https://dnceng.visualstudio.com/internal/_build/results?buildId=1148964&view=results tests the change on a 3.x repo.

**Comment by MattGal** [comment]
This is merged and as it is only for dependency-flowed yaml publishing, I tested the approach in a manual 3.1 build.  Closing.
