### ISSUE TITLE
Tracking: Update to new .NET cert in repos

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7348]
Tracking the update to the new cert in the repos

| Repo | Status | Notes |
|---|---|---|
| dotnet/runtime | Complete | https://github.com/dotnet/runtime/pull/52336 |
| dotnet/aspnetcore | Complete | https://github.com/dotnet/aspnetcore/pull/32584 |
| dotnet/winforms | Complete | https://github.com/dotnet/winforms/pull/4889 |
| dotnet-wpf-int | Complete | https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/14782 |
| dotnet/wpf | Complete | https://github.com/dotnet/wpf/pull/4506 |
| dotnet/windowsdesktop | Complete | https://github.com/dotnet/windowsdesktop/pull/1617 |
| dotnet/roslyn-analyzers | Complete | https://github.com/dotnet/roslyn-analyzers/pull/5096 |
| dotnet/sdk | Complete | https://github.com/dotnet/sdk/pull/17577 |
| dotnet/installer | Complete | https://github.com/dotnet/installer/pull/10592 |
| dotnet/roslyn | Complete | https://github.com/dotnet/roslyn/pull/53360 |
| dotnet/fsharp | Complete | https://github.com/dotnet/fsharp/pull/11555 |
| dotnet/msbuild | Complete | https://github.com/dotnet/msbuild/pull/6448 https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4826873&view=results |
| dotnet/templating | Complete |  https://github.com/dotnet/templating/pull/3160 |
| dotnet/machinelearning | Complete | https://github.com/dotnet/machinelearning/pull/5794 |
| dotnet/symreader | Complete | https://github.com/dotnet/symreader/pull/242 |
| dotnet/symreader-portable | In Progress | https://github.com/dotnet/symreader-portable/pull/316 https://dev.azure.com/dnceng/internal/_build/results?buildId=1134997&view=results |

https://github.com/dotnet/arcade/pull/7347/files - support for UseDotNetCertificate

**Comment by MattGal** [comment]
[Async Triage] This seems to be something @mmitche is driving and already in flight, so adding to the "Tracking" epic to get off triage.

**Comment by markwilkie** [comment]
I'd rather have this work be part of a proper epic if at all possible.  @mmitche - hopefully the security work has enough "shape" to at least get an epic started?

**Comment by mmitche** [comment]
@markwilkie I don't think it's in that shape yet. There is a grab bag of security-ish related items at this point (e.g. using a different storage account for builds), but as of yet no real business goal except "we should have a secure engineering system". That box is essentially uncheckable (how do you know?), and is much larger than a single epic's scope anyway.

Lastly, changing the cert doesn't have to do with the security of the engineering system, it's more for product security and customer choices (see https://github.com/dotnet/announcements/issues/184). We **could** make this its own epic. What do you think?

**Comment by mmitche** [comment]
Donezo

**Comment by cocowalla** [comment]
Are details of this new certificate available? I can't find the thumbprint or subject name, or those of the issuing certificate, either here or over on https://github.com/dotnet/announcements/issues/184
