### ISSUE TITLE
Extract backport action from dotnet/runtime into arcade

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/arcade#7373]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In dotnet/runtime we're using a GitHub Action that allows you to comment `/backport to <branch>` on your PR and the action will open a new PR targetting the respective branch.

@wtgodbe asked me about having the same for aspnetcore and while we can just copy the GH Action files over I feel like this would be a better fit for some common arcade solution.

I can think of two approaches:
1) Extract the action code into a separate repository (this is how GH Actions are usually shared: https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-release-management-for-your-custom-actions)
2) Flow the code into repos via arcade's `eng/common`

The implementation in dotnet/runtime lives in these two files/folders:
- https://github.com/dotnet/runtime/tree/main/eng/actions/backport
- https://github.com/dotnet/runtime/blob/main/.github/workflows/backport.yml

**Comment by riarenas** [comment]
Removed the First responder label so this gets triaged, and it also doesn't seem appropriate to be handled in FR. 

Currently we are not supposed to be using GitHub Actions, so I don't think it'd be appropriate for Arcade to distribute it. Perhaps it's something that we could add to dotnet/versions?

@markwilkie @tkapin this is what @lukas-lansky brought up today during our sync.

**Comment by mmitche** [comment]
I'm fine by it. There have been some Action related security issues in the past. However, IIRC when I looked at them before, none would apply in that case. However, we should re-evaluate it before pulling it into arcade. See https://securitylab.github.com/research/github-actions-untrusted-input/

**Comment by akoeplinger** [comment]
> However, having the code live in the arcade repo (basically #1) probably seems fine I think.

Note that we can't put it in dotnet/arcade if we go that route but it needs to be a separate, standalone repo since GH Actions expects an action.yml in the root of the repo.

**Comment by markwilkie** [comment]
> it needs to be a separate, standalone repo since GH Actions expects an action.yml in the root of the repo.

Oh, I see yea.

**Comment by markwilkie** [comment]
What are the next steps here @akoeplinger ?

**Comment by MattGal** [comment]
**[Async Triage]** :  I lack context but am commenting as those are the rules.  Seems like a good thing to extract from runtime and not FR, to echo previous comments.

**Comment by jakubstilec** [comment]
[Async Triage]: Created [teams chat](https://teams.microsoft.com/l/message/19:f9bc826d88fe4e52a0c84c0a4bc8577f@thread.skype/1622106518790?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1622106518790&teamName=.NET%20Eng%20Services&channelName=Triage&createdTime=1622106518790)

**Comment by MattGal** [comment]
[Async Triage]: commented in chat.

**Comment by markwilkie** [comment]
Thoughts on next steps @akoeplinger ?  This issue is languishing a bit...

**Comment by markwilkie** [comment]
closing due to diminished interest.
