### ISSUE TITLE
Port additional runtime Helix SDK support to release/5.0

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#7378]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Should be a straightforward port, but there may be a follow up commit or two required.  

Relevant issue for context: https://github.com/dotnet/arcade/pull/7158

The meat of the change is just this:
https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/Sdk/tools/dotnet-cli/DotNetCli.targets#L26 
...  which should be a straight port, but I'm not just doing that because every time I say that I get surprised:

@ilyas1974 since this helps mitigate the azureedge.net SSL issue for ASP, I'm dumping it straight into FR.

**Comment by riarenas** [comment]
The change made it through arcade-validation and is now available in the ".net 5 eng" channel
