### ISSUE TITLE
Arcade-Services: TimelineBuilds stopped ingesting on 5/11 due to ArgumentNull exception

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#7389]
- [X] This issue is blocking : viewing timeline issues from Kusto DB and other services
- [ ] This issue is causing unreasonable pain

Last successful ingestion was 2021-05-11 21:09:44.0000000, i.e. 2 PM PST Tuesday:

```
TimelineBuilds
| top 10 by ingestion_time() desc
```

[Exceptions query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAz2NPQvCMBgGd3%252FFS5fqUJsERAi0UHBWkO4S00cMJE1IUr%252Fwx2sRvPHgODw0QjZ%252BTIs33a%252BIoGwcUlYuUEvZDypjNstSMMErtqk4J8Gk2ErB1%252BxHuaJ%252Frq2fhtPRW%252ByVAzUNFRd1jkbLuoeFQ47PLgRrtJq%252FdfeaIna4HULqvx9rRhQf4HecEpYAAAA%253D)

It's crashing here:
https://github.com/dotnet/arcade-services/blob/main/src/Telemetry/AzureDevOpsTimeline/AzureDevOpsTimeline.cs#L263

Given the only secret this app uses (dn-bot-dnceng-build-rw-code-rw-release-rw) is still valid and working, I think this was a change in ADO we need to adapt to.

**Comment by garath** [comment]
The build that caused this (at least locally) is [#1133591](https://dev.azure.com/dnceng/internal/_build/results?buildId=1133591&view=results). The failure comes from Build.Properties being null because it's an AzDO PR and not GitHub. 

Putting together a fix PR now.

**Comment by garath** [comment]
Data is once again flowing into the Timeline tables.
