### ISSUE TITLE
Add symbols to SymbolPublishingExclusionsFile.txt so that they do not get published 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#7420]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Some pdbs / symbols  files which we do not want to publish can be added to SymbolPublishingExclusionsFile.txt 

https://github.com/dotnet/arcade/blob/349d4a363ccb18d94f406f782c13ccf48df30805/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs#L388

We are already passing the param, we just need to pass that file to the API

**Comment by epananth** [comment]
Also this has to be documented in publishing.md

**Comment by epananth** [comment]
I made some initial changes in this branch https://dnceng.visualstudio.com/internal/_git/dotnet-arcade?version=GBexcludeSymbols

We have to make sure that the files in that SymbolPublishingExclusionsFile.txt does not get uploaded to Symbol server 

Eg: where runtime keeps the file 
    runtime/SymbolPublishingExclusionsFile.txt at main · dotnet/runtime (github.com)
dotnet/runtime.NET is a cross-platform runtime for cloud, mobile, desktop, and IoT apps. - dotnet/runtimegithub.com

I think we need to add more logging to debug this, also tweak the place where we are looking for SymbolPublishingExclusionsFile.txt in publish-asset.yml

**Comment by epananth** [comment]
cc: @garath

**Comment by epananth** [comment]
This test uses runtimes excludeSymbols file https://dnceng.visualstudio.com/internal/_build/results?buildId=1151136&view=results

**Comment by epananth** [comment]
PR : https://github.com/dotnet/arcade/pull/7433

**Comment by epananth** [comment]
@joeloff  we need a test build where we can test this changes against. This will help us verify the change. Can you please help with the test build? ( need the barid from the test build)

**Comment by joeloff** [comment]
We don't have a BARID. The issue is failing my PR build.

**Comment by epananth** [comment]
closing this cos its a duplicate https://github.com/dotnet/arcade/issues/7423
