### ISSUE TITLE
Location for symbolPublishingExclusionsFile

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#7423]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Should this file be added here -> https://github.com/dotnet/arcade/blob/349d4a363ccb18d94f406f782c13ccf48df30805/eng/publishing/v3/publish-assets.yml#L86 

or should it be uploaded to the container like we do for BlobArtifacts and PackageArtifacts and then download it during publishing? 

cc: @hoyosjs @mmitche

**Comment by mmitche** [comment]
I'm thinking the latter, unless we have precedent for pulling repo contents during publishing today.

**Comment by mmitche** [comment]
You could also integrate it into the manifest.

**Comment by hoyosjs** [comment]
How does the new workflow honor the check for [signing exclusions](https://github.com/dotnet/runtime/blob/main/eng/SignCheckExclusionsFile.txt)? The container or the manifest both sound good and were the original suggestions. I just didn't know how arcade v3 honors those type of files we used to have (or if they are even honored anymore.

**Comment by MattGal** [comment]
[Async Triage]: Looks like #6108

**Comment by MattGal** [comment]
[Async Triage]: No change, pinged the team to see if I should stop doing this.

**Comment by riarenas** [comment]
@epananth aren't you already looking at this as part of an FR issue? how is this different from the one you're looking at?

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade/issues/7420 is the issue I was referring to.

**Comment by epananth** [comment]
ah.. Idk why I created 2 issues. ;/ going to close the other one and use this

**Comment by tkapin** [comment]
[Async Triage]: @epananth - moving this to tech debt publishing #6108, feel free to throw it away from that if you feel it doesn't belong there.

**Comment by epananth** [comment]
Merged this changes. So closing this https://github.com/dotnet/arcade/commit/7e675d42ae78b36a02fbb2b9ef8cdf6f3917391b
