### ISSUE TITLE
Test Configuration name for docker based queues in helix is hard to read

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#7424]
Currently the test run we trigger the configuration against looks like this 
`net6.0-Linux-Debug-x64-CoreCLR_checked-(Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200602002622-e06dc59 `. That's WAY to long, and should really just be "Alpine.312.Amd64.Open", or perhaps "net6.0-Linux-Debug-x64-CoreCLR_checked/Alpine.312.Amd64.Open".  The other information isn't really pertinent at this level.

**Comment by ChadNedzlek** [comment]
@alexperovich, does this seem like a reasonable thought? I know you have a lot of context on this area of code.

**Comment by alexperovich** [comment]
The Alpine.312.Amd64.Open part is the "friendly name" for that docker format, so it makes sense to use it instead of the whole string. The "net6.0-Linux-Debug...." thing is just the Job Name IIRC, I don't know how much of that is valuable to the runtime team.

**Comment by ChadNedzlek** [comment]
It's a little helpful, so you can know if it's debug/release.  Though I think PR's only ever do one of the two of them, so maybe less so?

**Comment by ChadNedzlek** [comment]
I might try whipping up a fix to clean it up a bit (It's making the dev WF PR's look really ugly, because this enormous sting wastes so much screen space)

**Comment by MattGal** [comment]
[Async Triage]: Yes, if we can make this just display the Display name that'd be great.  Docker tags from that repo aren't getting shorter ever.

**Comment by MattGal** [comment]
[Async Triage]: No change, pinged the team to see if I should stop doing this.

**Comment by missymessa** [comment]
@ChadNedzlek and @alexperovich how easy would it be to get the "Friendly Name" during the building of the Build Result Analysis?
