### ISSUE TITLE
Channel '.NET Internal Tooling' publishes to internal feed but publishes public symbols

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/arcade#7430]
https://github.com/dotnet/arcade/blob/da05407f9a21c9a3092b19dc4068432dd1b2445d/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/PublishingConstants.cs#L577

Is this expected of this channel? Otherwise, is there a private channel to use for internal symbols and publishing for out of band tooling?

**Comment by epananth** [comment]
this should not publish to public and internal 

PR -> https://github.com/dotnet/arcade/pull/7432/files

**Comment by riarenas** [comment]
This has been fixed as far as I can tell.
