### ISSUE TITLE
Consider reverting to/multitargeting netcoreapp2.1 in RemoteExecutor

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/arcade#7435]
- [x] This issue is blocking -- adaption of #7426 in ImageSharp
- [ ] This issue is causing unreasonable pain

Although 2.1 will reach EOL soon, the (1) time has not come yet (2) OSS libraries may decide to keep deploying/testing 2.1 packages. RemoteExecutor is a standalone project, including it in #6891 was probably unnecessary.

Changing the `.csproj`, I can build against 2.1 locally, if it doesn't break the bigger CI infra, I don't see why not to keep it accessible to the wider ecosystem by targeting a lower version.

/cc @vitek-karas @ViktorHofer

**Comment by ViktorHofer** [comment]
I'm fine with targeting the lower version if sourcebuild does work with that, but as soon as 2.1 is out of support we are going to revert this change.

**Comment by ViktorHofer** [comment]
Feel free to submit a PR to downgrade the version and I'll approve it :)
