### ISSUE TITLE
Arcade support for XCopy-able MSBuild 

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#7444]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Arcade uses an [xcopy version](https://github.com/dotnet/arcade/blob/main/eng/common/tools.ps1#L286-L378) of MSBuild (package name is RoslynTools.MSBuild).  The current version available on dotnet-eng feed is 16.8.0-preview3.  We should consider what our support agreement for this package is and if / when we should add new packages to dotnet-eng (ie 16.9+).

Source: https://github.com/jaredpar/xcopy-msbuild

FYI @joeloff

**Comment by markwilkie** [comment]
This seems relevant to the harmonization effort

@tkapin @riarenas @lukas-lansky

**Comment by MattGal** [comment]
[Async Triage]: Would be great to automate this, lots of repos depend on it.

**Comment by tkapin** [comment]
Agreed, adding it to the epic.

**Comment by lukas-lansky** [comment]
@chcosta @riarenas Do you happen to know why we just don't use the public version https://www.nuget.org/packages/Microsoft.Build.Runtime/ ?

**Comment by chcosta** [comment]
That could be perfect!  It's quite possible that we're not using it simply because it didn't exist when the need was there (xcopy-msbuild is 4-ish years old).  I'm not sure what the delta is between the two, and there would have to be some script modification to support it, but it seems like a good path to investigate.

**Comment by tkapin** [comment]
Let's bring this to the next Harmonization meeting with the CLR folks - I'd be curious to learn if the version suggested by @lukas-lansky would be sufficient or if there are any other requirements.

**Comment by dougbu** [comment]
Suggested decision tree for this issue:

1. decide if the [NuGet Gallery | Microsoft.Build.Runtime 17.6.3](https://www.nuget.org/packages/Microsoft.Build.Runtime/#readme-body-tab) option would actually work in most of the repos that explicitly or implicitly use `xcopy-msbuild`
    1. if yes, do the cost / benefit analysis then (perhaps) migrate `eng/common/tools.*` to use that option
    2. if no, it's probably best (from a software supply chain perspective) to migrate the code from Jared's repo into dotnet/arcade
1. decide if we should stop there. for example, we may determine [RoslynTools.MSBuild (xcopy-msbuild) generation - Overview (azure.com)](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1074/RoslynTools.MSBuild-(xcopy-msbuild)-generation) is sufficient and (while complicated) we don't need anything better for a once / year process
    1. if yes, do more
    2. if no, 🛑

**Comment by dougbu** [comment]
> I like it @dougbu. What would happen if we did nothing?

@mmitche would continue to get paid overtime and I'd be disappointed 😀

It's mostly an ease-of-use thing and would help any repo using down-level runtimes even if we ignored the feature in dotnet/arcade's global.json.

Might be worth asking customers how interested they are❔

**Comment by garath** [comment]
Removing from triage consideration because this found a home in the Harmonization epic.

**Comment by missymessa** [comment]
Work has been covered by another issue.

**Comment by chcosta** [comment]
FYI, closing this issue, does not mean we're done with xcopy-msbuild.  it just means we've addressed this specific issue.  As mentioned previously, there's another issue (somewhere) targeting other potential investments.
