### ISSUE TITLE
SignTool should support cancellation

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7456]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We saw an issue where a specific file type was rejected by the ESRP signing service. The tool decided that was a transient error and retried the signing. This caused problems for ESRP. However, when I tried to cancel the build (https://dev.azure.com/dnceng/internal/_build/results?buildId=1160272&view=logs&j=9ff0e0af-24e7-5b0f-fa76-5e12fc9920ef&t=04e39753-8cfe-5fb5-2824-43b4c4b51e3b) it kept attempting to rerun. My hunch is this is because there was not a cancellation token plumbed through to the right place.

**Comment by MattGal** [comment]
[Async Triage]: We'd need to make sure you can derive from AppDomainIsolatedTask and implement ICancelableTask at the same time (trying this out in a project now)  but if it's that easy and it causes problems in daily signed builds, I think this should go into FR, @ilyas1974 do you agree?

**Comment by MattGal** [comment]
Aww.  Nothing stops you from making an AppDomainIsolatedTask implement ICancelable Task, but it doesn't cancel either:

```
d:\scratch\fun>msbuild fun.proj
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/3/2021 10:45:12 AM.
Project "d:\scratch\fun\fun.proj" on node 1 (default targets).
Build:
  Here we go...
  I am the execute() in this task class.  Imagine I'm doing real stuff.  I'm going to spin FOREVER unless I get cancelled
   Execute task is still running if you see this...
   Execute task is still running if you see this...
   Execute task is still running if you see this...
Attempting to cancel the build...
  Cancellation started at 10:45 AM. We'll see how long we get to try.
   Cancellation is running ...10:45 AM
   Execute task is still running if you see this...
   Cancellation is running ...10:45 AM
   Execute task is still running if you see this...
   Cancellation is running ...10:45 AM
   Execute task is still running if you see this...
   Cancellation is running ...10:45 AM
   Execute task is still running if you see this...
   Cancellation is running ...10:45 AM
```

**Comment by MattGal** [comment]
Ignore previous comment, yes this works as I'd expect in an local experiment for a task that is ` : AppDomainIsolatedTask, ICancelableTask`

**Comment by adiaaida** [comment]
Didn't manage to make much progress on this. Whoever works on this needs to reach out to @chcosta, who is the SignTool SME about how far the cancellation token should be plumbed through. The work, after that, should be relatively straightforward.

**Comment by chcosta** [comment]
This isn't quite straight-forward because signtool is just a wrapper around MicroBuild.  SignTool generates some MSBuild projects that include signing information, and MicroBuild target imports; but MicroBuild handles the actual signing.

**Comment by MattGal** [comment]
This is much more complex than we thought and does not have much ROI, closing.
