### ISSUE TITLE
Configure dotnet-install timeout for downloading .NET

### ISSUE THREAD

**Issue by kant2002** [dotnet/arcade#7458]
By some reasons my internet connection is relatively slow. So default timeout of 20 minutes in dotnet-install.ps1 for downloading .NET does not work for me.
It would be nice if that timeout can be configured.

Right now timeout in that script is hardcoded like that:
```
# Default timeout for HttpClient is 100s.  For a 50 MB download this assumes 500 KB/s average, any less will time out
# 20 minutes allows it to work over much slower connections.
$HttpClient.Timeout = New-TimeSpan -Minutes 20
```

And since that script is downloaded, each time I do `git clean -xdf` my timeout modifications reset to 20 minutes.

**Comment by MattGal** [comment]
[Async Triage]: Small work item, consistent customer pain, good candidate for FR so putting it there.

**Comment by adiaaida** [comment]
@MattGal I agree that this is a small work item, but we do not own the install scripts, @vlada-shubina's team (and I believe @bekir-ozturk in particular) owns them and their rollout schedule. This seems like an issue for https://github.com/dotnet/install-scripts?

**Comment by MattGal** [comment]
@adiaaida oh sorry you're right I was thinking somehow this was in https://github.com/dotnet/arcade/blob/main/eng/common/dotnet-install.ps1.  Let's move this issue there.

**Comment by MattGal** [comment]
Created https://github.com/dotnet/install-scripts/issues/195 and tagged @kant2002 .
