### ISSUE TITLE
Reconcile OS onboarding and Native tool bootstrapping

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#746]
Right now we use different systems and scripts to bring down tools for OS onboarding and via Arcade. We initially decided to keep them separate due to difficulties working with DTL artifacts, but it might be worth revisiting now that both projects are more fleshed out.

Aspects to consider:

1. OS Onboarding uses its own private storage account/container to store all the installers, Arcade SDK needs them to be publicly accessible.
   * We could split the artifact installers: the ones that require it point to the private storage (things that may need keys, or downloading configuration from Keyvault), and whatever isn't really private (things we can get from the internet anyways) could go in the public storage account. This would mean we'd split the installers and no longer have a single place where they are stored. 
   * We also need to converge on a clear structure for the containers and installer package names. The current guidance for Native bootstrapping is to use the installer package names just as they are available from the internet. In OS onboarding we've already done a fair share of renaming to fit a simpler scheme for the artifacts.

1. Sharing the installer scripts between Arcade and OS onboarding
**Potential solution:** For any tool that needs an artifact created, the actual installer sript for the tool lives in Arcade. If an OS onboarding artifact is necessary, the artifact will download the script from Github and routes all the required parameters from the artifactFile to the real installer.
The downsides with this approach are two:
   * The authoring and Debugging experience for artifacts worsens. You now need two PRs, one to Arcade and one to Helix Machines. Additionally, the code for a faulty artifact is now much harder to debug and fix, as every fix needs to go through a PR in Arcade first.
   * OS onboarding artifacts may need a post-install step that happens when the machine is created to deal with any steps that require a user account to be present, and any steps that require a reboot after configuration. There are no sysprep or deprovision steps during the native tool bootstrapping. The installers for these tools would need to be split in two sections. Arcade just runs them one after the other, but OS onboarding would need to use the current mechanism for running post-install steps.

1. DTL does not allow the concept of a "common library" that is shared among artifacts. OS onboarding works around this fact by force installing a specific artifact, and copying a util.ps1 script to a known location in the machine. Every other artifact assumes this script is present in the specific folder. Arcade does have a common library with basic functionalities that help with the native tool download and deployment.
   * We could merge the two libraries and follow the same process as in 2. The DTL helix-prep artifact would download the common library as one of its steps.

**Comment by riarenas** [comment]
I think there are three options for how we want to proceed:

1. Keep both systems separate as they are right now. This means we can potentially host the same installer twice.
2. Converge the storage accounts that we use for both systems. (Section 1 of the issue). This requires some changes in the OS onboarding artifacts, and we need to decide on a common container structure.
3. Converge the storage account locations and the installer scripts (Sections 1 through 3). This requires some potentially confusing documentation, and it would change the way we install artifacts in OS onboarding.  We could also consider using some sort of mirroring from Github to VSTS of the installers, but that seems even more complex and fragile.

Although I love the idea of being able to share the installer scripts, it seems like it could be really fragile. Not only for instances where the Arcade installer gets broken and now the artifacts fail to install silently, but it becomes a more confusing experience for whoever is authoring the installers. A good middle ground is option 2, where we at least don't double down potentially hosting the same installer over and over. 

@ChadNedzlek, @chcosta Any thoughts or concerns?

**Comment by ChadNedzlek** [comment]
@markwilkie I happen to think our current storage layout is pretty good (since we just created it a few weeks ago).  The only change is that we probably need 2 containers... a "public" one and a "private" one... onboarding can use the public one with no sas, and the private one for things that don't need to be bootstrapped (like things for build agents and app compat).  If that sounds good, it's just making a new container and copying the artifacts we want to be publicish over... 10 minutes?

**Comment by ChadNedzlek** [comment]
@chcosta I think they systems _are_ different. bootstrapping is just "I need cmake.exe" somewhere on my computer. OS Onboarding is "I need to make fundamental, global changes to a pattern that will modify the machine".

There shouldn't _be_ anything that's in both system either... since if it's bootstrappable, we don't need to pre-install it (since the builds will bootstrap it themselves). Only one of the two will ever really be "installing" a thing.

**Comment by chcosta** [comment]
> There shouldn't be anything that's in both system either... since if it's bootstrappable, we don't need to pre-install it

That's an ideal situation.  The reality is that teams will transition to using Arcade bootstrapping over time, so there will be some teams that will bootstrap tools and others that have it as a pre-req and we'll need to support both for quite a while.  Either that, or, we just don't bootstrap anything and then the "problem" goes away.

**Comment by markwilkie** [comment]
@weshaggard or @tmat - any input?

**Comment by riarenas** [comment]
> That's an ideal situation. The reality is that teams will transition to using Arcade bootstrapping over time, so there will be some teams that will bootstrap tools and others that have it as a pre-req and we'll need to support both for quite a while. Either that, or, we just don't bootstrap anything and then the "problem" goes away.

I think if our long term goal (and I agree that it's going to beterm) is to be able to clone and build in a completely clean machine, just relying on Onboarding is not an alternative, and it's a problem we still need to tackle.

I hear Chris's concern about maintenance cost for having two separate installation mechanisms, and that's why I came into this with the hope that we could "merge" both systems, and I'm still trying to look for alternatives.

As I keep reviewing the state of the OS onboarding artifacts, there are very few there that are simply "drop an exe/msi and then run it". Most of the artifacts have to deal with the difficulties that Chad alluded to.

The artifacts that do involve just calling an installer, or copying some binaries are usually simple enough that I don't think there's a lot of burden to go from one system to the other, and eventually deleted from the OS onboarding repo.

**Comment by markwilkie** [comment]
The North Star here is the usual one - namely, reuse where we can.   A good first step down this road is to share the location of the tool, so it seems to me this should be done regardless.

Regarding any reuse of the artifact/installer itself, I still haven't heard a plan we think works. (unless I missed it, which is entirely like me and possible)  If there's no actionable plan to reuse the installers themselves yet, then I'd like to see that step we can take, taken.

**Comment by riarenas** [comment]
> A good first step down this road is to share the location of the tool, so it seems to me this should be done regardless.

Agreed. I created #757 to track that work.

> Regarding any reuse of the artifact/installer itself, I still haven't heard a plan we think works.
I think it would "work" for the OS onboarding artifacts to download the installer from the Arcade repo and wrap them. It just makes the experience fragile in a lot of ways for those particular artifacts, and would require a rewrite of some of them.

I'm not really a fan of that solution because of the problems I outlined, but it does let us reuse the installers scripts.

**Comment by riarenas** [comment]
Another alternative:

Re-purpose the On-prem DTL bootstrapping scripts for this. We have some scripts that download and install artifacts. They were designed for on-prem machines, but we could probably repurpose them with some work so that they can work for this scenario.

This doesn't solve the issue of OS onboarding artifacts being a lot more complex than native tool bootstrapping needs, and the fact that it would take a non-trivial amount of work.

**Comment by riarenas** [comment]
The consensus is that none of the options, beyond converging in storage location for the tools, are any better than just keeping the two systems separate.
#757 tracks the convergence of storage locations.

**Comment by weshaggard** [comment]
FWIW I agree with this conclusion. I completely agree with @ChadNedzlek's point that the bootstrapping should be isolated and not installed globally and if the machine on-boarding is doing global installs then there will be little to nothing to share in the installer scripts.

We should simply keep an eye on this as we progress and if we find duplication that we have to keep manually updating then we should reconsider potential sharing options.
