### ISSUE TITLE
SourceLink URI translation broken for msbuild

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7463]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://dev.azure.com/dnceng/internal/_build/results?buildId=1166651&view=logs&j=28bdc2c7-156f-51fb-6444-d4b8da3693ac&t=db80a514-da0d-59b3-7d70-a8c1f2a0491a&l=1121

The URI should point to the public repo. I can't remember whether there is a way to explicitly specify the public URI to the SourceLink targets, but it could either be fixed that way if available, or we should implement translation.

**Comment by mmitche** [comment]
@rainersigwald @alexperovich @tmat

**Comment by MattGal** [comment]
[Async Triage]:  Maybe fits into https://github.com/dotnet/arcade/issues/6811 ?   We don't exactly own sourcelink but we expose and configure it via Arcade, so it does sound like something we should do even if it also results in generating and waiting on a feature request for another team.

**Comment by riarenas** [comment]
Feels like something that we track as part of #363. Even though arcade is involved in running sourcelink, we historically haven't owned it.

**Comment by mmitche** [comment]
I wasn't sure whether arcade implemented the translation (since the repo pattern is .NET specific), or whether it was in SL itself.

**Comment by riarenas** [comment]
Hmm, is it here? https://github.com/dotnet/arcade/blob/67737ae294375c867bea72de19a66149785881e5/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryInfo.targets#L62-L79

**Comment by mmitche** [comment]
Yep. I wonder whether that was because they weren't on a new enough version of arcade in p5. Main is now on mainline arcade.

**Comment by rainersigwald** [comment]
Our latest `main` build does show that running: 
![image](https://user-images.githubusercontent.com/3347530/120709063-02668d80-c482-11eb-8dcc-4e34e1e1c815.png)

**Comment by mmitche** [comment]
> Our latest `main` build does show that running:
> ![image](https://user-images.githubusercontent.com/3347530/120709063-02668d80-c482-11eb-8dcc-4e34e1e1c815.png)

Awesome. I will close this.
