### ISSUE TITLE
Build analysis checks should be ignored as part of the standard Maestro merge policy

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7466]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain
Maestro is unable to merge PRs where the build analysis check has not run. 

We should add this check to the list of automatically ignored checks in the standard merge policy: https://github.com/dotnet/arcade-services/blob/5c68775870d6587644972afe6f48d411996cd8e4/src/Maestro/Maestro.MergePolicies/StandardMergePolicy.cs#L25

**Comment by riarenas** [comment]
I think this is either FR, or should be part of the dev WF epic since that's where the check was added.

**Comment by riarenas** [comment]
@ChadNedzlek points out it might be better to just change Maestro's policy evaluation logic so that neutral checks are also considered successful.

**Comment by ChadNedzlek** [comment]
It seems a bit easier than having to hard code our particular check as ignored/special.  Unless there are other situations where "neutral" not blocking would cause trouble.  But GitHub doesn't consider it blocking (the "All Checks Successful" green checkmark is there with a neutral build), so matching that behavior should be ok, I think.

**Comment by MattGal** [comment]
[Async Triage]:  Can this go in the Dev WF epic?  I think that's where it belongs, otherwise I'd say let's just put it in FR, as either approach (ignoring this check or ignoring all neutral checks) are  cheap fixes to make.  

I strongly favor Maestro ignoring just this check as clearly when something is failing it can present as neutral; this issue exists because failures can present as such.

**Comment by ChadNedzlek** [comment]
When does a failure present as neutral?

**Comment by ChadNedzlek** [comment]
This is blocking people, so FR seems appropriate... otherwise it's going to keep blocking people until someone in that epic grabs this.

**Comment by MattGal** [comment]
> When does a failure present as neutral?

This morning, before your hotfix rolled out, build result analysis failed to do its thing, and presented a neutral check.   That's how I noticed this but lots of others did too.  

> This is blocking people, so FR seems appropriate... otherwise it's going to keep blocking people until someone in that epic grabs this.

It was blocking people but it wouldn't have been if we just rolled back the changes your epic rolled out yesterday, and the epic is still open.  I was under the impression that until an epic is closed the folks on that team own the fallout from the epic, but I'd check with @markwilkie  / @Chrisboh  for clarification.

**Comment by ChadNedzlek** [comment]
That's not a failure though.  It was very intentionally "not a failure". We choose the neutral status specifically so as not to block merges.

**Comment by ChadNedzlek** [comment]
It is true that it was cause by the epic, but the epic is likely to be open for the better part of a year, and one issue in the sea of issues in that epic is likely to get missed/take a while to resolve.

**Comment by MattGal** [comment]
Fair enough.  "The other players in the system shouldn't have configured themselves the way they were such that I could break them" is a recurring theme in all build and test infrastructure.  I'm fine with FR btw, just needs to happen soon since such a break could happen again.

**Comment by ChadNedzlek** [comment]
Yeah, I'm going to see if I can figure out how to fix it... but I'm SUPER unfamiliar with the maestro code, so it's going to take me a while.

**Comment by ChadNedzlek** [comment]
I believe https://github.com/dotnet/arcade-services/pull/1632 should address this situation?
