### ISSUE TITLE
Consider moving VerifyClosure task into the PackageTesting package

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#7474]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The `VerifyClosure` task is implemented in the `Microsoft.DotNet.Build.Tasks.Packaging` project which will be marked as deprecated or deleted later this year. Both dotnet/runtime's package testing system and the Shared Framework SDK depends on the task so it should be considered to be moved into `Microsoft.DotNet.PackageTesting`. Both consumers could then take a direct dependency on that package instead.

cc @Anipik @ericstj @jkoritzinsky

**Comment by MattGal** [comment]
[Async Triage]: Sounds like general work to be done whenever Tasks.Packaging is deprecated.  Seems like "Work tracking by/for other teams" epic as AFAIK Package Testing is entirely a runtime feature

**Comment by ViktorHofer** [comment]
@MattGal would it be possible to exclude issues that are specific to tools that core-eng doesn't own from the async triage? Of course the question stands how to filter them out.

**Comment by MattGal** [comment]
@ViktorHofer sorry I'm trying to follow some rules :) If you have zenhub, sticking them in that catch-all epic I mentioned would keep them off triage radar.  Failing that, I think someone has added the "I think this is triaged" label that might do the same, or finally if neither works, just saying that in the initial writeup will cause ME to do the first thing when I run into your issues.  

Apologies for the noise, we're just trying to be disciplined about making sure issues aren't ignored for long periods of time, something we've had challenges with in the past.

**Comment by ViktorHofer** [comment]
I'm super happy that your team prioritizes triaging incoming issues higher than before. Thanks a lot for doing that.

In this case it was me who opened the issue but in other cases it will be someone different who doesn't know much about how Arcade triages their issues. Would it help to add a codeowners file or an [area-owners file](https://github.com/dotnet/runtime/blob/main/docs/area-owners.md) similar to what we have in dotnet/runtime to list the owners of each component? That might help you reason about which tools are owned by which team.
