### ISSUE TITLE
Build Analysis UX tweaks

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7475]
BA UX Modifications proposal:

There is not broad consensus on what the UX should look like, and so I think we should take a measured approach with the expectation that we will have to make future tweaks based on user feedback or requirements changes. The feedback for the UX study (https://github.com/dotnet/arcade/issues/7285) has been somewhat mixed.

I think we should use option ['C'](https://github.com/dotnet/arcade/issues/7285#issuecomment-825163457) and ['D'](https://github.com/dotnet/arcade/issues/7285#issuecomment-825165601) in the UX study as the baseline for changes, with some tweaks. Overall, the following changes would take place:
- Each build failure goes under a non-bulleted heading that is: <pipeline name> / <stage> / <job>. Tests will be <pipeline> / Tests.
  - This is linked to the specific azdo job (but not the specific failure)
  - If there are no stages, then the stage element is removed
  - Top level test link should link to the azdo test tab
  - In cases where there are a LOT of failures, show a selection (top N?), and then the job/test heading should include a suffix e.g. 'arcade-ci / Tests (1000 failures not shown)'
- Specific failures in each job/test run will be sub-bullets under each of those, linking to the specific log line that has the issue.
  - Multi-line failures will not be expandable. Instead, just include the full block on the next line
  - Single line failures will be placed after the link (like in the sample)
  - Individual test failures should link as specific a link as is possible (this might depend on whether it's helix or not), with additional links for helix console logs and test history (where possible)
  - Tests should include two code blocks, one for the stack and one for the text output.
  - Care should be taken to try and get newlines correct in test/build failure output
  - For Helix tests, include a "Failing on" sub-element and list each failing queue.
- Fonts should be the same size for all elements
- Log text, stack and test failure text should be in code blocks (monospaced fonts)
- Emoji icons will be used, prefixing each issue:
  - Red X = Unique failure
  - Yellow circle = Failure in the target
  - Fire = Infra problem
- The analysis section (which is the summary info for a check) will:
  - Contain a brief summary of the failures that are present, with a key for the emojis that are seen.
  - Emojis that are not present in the details should not be present in the summary (to avoid someone searching for a problem that doesn't exist).
  - Will contain an "action required". This action required should detail:
    - What the user is expected to do prior to merging. E.g. 
      - Resolve unique (X) failures prior to merging
    - What the system might do if there are baseline or infra failures (may be automatically retried)
- Subheading at the bottom with a link to documentation

Open questions:
- Suggestion was to remove duplicate error messages/stacks/test failure text. I mulled this over and couldn't come up with a method that would reliably detect duplicates, nor provide a good way to indicate where a user should look for the non-removed duplicate if one was removed. For example, if you have two build failures with the same text, and you eliminate the second one's text...how does the user know to look at the first one? I suggest deferring this to later.
- The callstack is often not that useful for test failures a lot of the time. Maybe half of it is just the callstack for the assertion itself. Should that part be eliminated?

**Comment by missymessa** [comment]
Blocking this until we get feedback from the user study researcher and UX designer per work on https://github.com/dotnet/core-eng/issues/13413

**Comment by missymessa** [comment]
Doing https://github.com/dotnet/arcade/issues/9066 instead. Closing.
