### ISSUE TITLE
Stage-DotNet should be marked as "SucceededWithIssues" if overrides are approved

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#7484]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When running Stage-DotNet, if any stage has errors in it, even if those stages have overrides that are approved, the entire pipeline will be marked as failed. We want to see the errors, but we also want a fully completed pipeline (ie one that drops the final bits) to be marked as succeeded or succeeded with issues. We need to come up with a way to not mark everything as failed, but still have the overrides hit if there were issues in the triggering stages.

**Comment by adiaaida** [comment]
@jonfortescue Do you think this fits in the scope of the Staging environment work you are doing? It'll also be a nice win for the release team.

**Comment by jonfortescue** [comment]
@adiaaida I can pull this into my work!

**Comment by jonfortescue** [comment]
PR in [here](https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/15959).

**Comment by monstro805** [comment]
fix??
Sent from Yahoo Mail on Android 
 
  On Wed, Jun 16, 2021 at 2:46 PM, Jon ***@***.***> wrote:   


PR in here.

**Comment by adiaaida** [comment]
moving to rollout

**Comment by jonfortescue** [comment]
whoops right i'm in a repo that does rollouts now
