### ISSUE TITLE
Arcade flow into arcade-validation is failing PR validation

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7494]
- [X] This issue is blocking 
This blocks arcade promotion
- [ ] This issue is causing unreasonable pain

Dependency update PR https://github.com/dotnet/arcade-validation/pull/2360 is failing its helix validation leg with the following errors:

```
+ dotnet exec --roll-forward Major --runtimeconfig Validation.Tests.runtimeconfig.json --depsfile Validation.Tests.deps.json /home/helixbot/work/BE770A59/p/xunit-runner/tools/netcoreapp2.0/xunit.console.dll Validation.Tests.dll -nocolor -xml testResults.xml
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0-preview.4.21253.7' was not found.
  - The following frameworks were found:
      6.0.0-preview.3.21201.4 at [/home/helixbot/work/BE770A59/p/dotnet-cli/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0-preview.4.21253.7&arch=x64&rid=debian.9-x64
+ export _commandExitCode=150
```

This is more than likely caused by the upgrade to the preview 4 sdk: https://github.com/dotnet/arcade/commit/130a085011ed5d5ef0fd30e07fa16ce88c2df28a

**Comment by riarenas** [comment]
Adding to FR as critical, as this blocks Arcade changes from flowing to repos

**Comment by riarenas** [comment]
@ilyas1974 we'll want to look at this one soon as there's a big list of changes waiting to be promoted.

**Comment by ilyas1974** [comment]
@missymessa, can you please take a look at this?

**Comment by missymessa** [comment]
@ilyas1974, looks like @jakubstilec is looking into it?

**Comment by jakubstilec** [comment]
@missymessa I'm looking into it. I think it's because of reference to preview.3 and we need to update it manually to preview.4. I'm not sure why it wasn't done automatically.

**Comment by riarenas** [comment]
The failing PR is updating to preview 4: https://github.com/dotnet/arcade-validation/pull/2360/files#diff-8df3cd354bc584349d04ad5675b33c042d8b99b741b8b95af394c55e0f5001bfR3

**Comment by ilyas1974** [comment]
I asked @jakubstilec to take a look at this as you were working on https://github.com/dotnet/core-eng/issues/13301

**Comment by jakubstilec** [comment]
@riarenas - I tried to update it to 6.0.0-preview.4.21253.7 in https://github.com/dotnet/arcade-validation/pull/2362. However it can't install it:
```
dotnet-install: Downloading legacy link https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.0-preview.4.21253.7/dotnet-dev-win-x64.6.0.0-preview.4.21253.7.zip

dotnet-install: The resource at https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.0-preview.4.21253.7/dotnet-dev-win-x64.6.0.0-preview.4.21253.7.zip is not available.
```

**Comment by riarenas** [comment]
That seems to be the wrong version. The released preview 4 sdk is `6.0.100-preview.4`: https://dotnet.microsoft.com/download/dotnet/6.0. 

If I may, I would suggest you work directly on the dependency update PR as it has everything that Arcade updates automatically, and if you get that building and merged it should unblock the first part of validation. (I'm also expecting something else to break during official builds)

**Comment by jakubstilec** [comment]
There is a missing change of preview 4 in azure-pipelines.yml. I added it to https://github.com/dotnet/arcade-validation/pull/2360.

**Comment by jakubstilec** [comment]
PR build passed, it should be fixed now.

**Comment by riarenas** [comment]
Yup, now we need to wait for the official build: https://dnceng.visualstudio.com/internal/_build?definitionId=282. I expect things to break there as well in some other way 😶

**Comment by jakubstilec** [comment]
Lets be optimistic :).

**Comment by jakubstilec** [comment]
PR with fix https://github.com/dotnet/arcade-validation/pull/2365/files

**Comment by jakubstilec** [comment]
This issue is fixed, build is passing now https://dev.azure.com/dnceng/internal/_build/results?buildId=1183151&view=results.

**Comment by riarenas** [comment]
@jakubstilec I left a comment in the Arcade-validation PR, but the changes you made there need to be made in arcade instead as they were changes to the scripts in the eng/common folder. We left things in a pretty dangerous state as if the current arcade build makes it to consumers, they will be broken by the errors you fixed directly in arcade-validation. Reopening this. If no one sees this I can try and make the change in an hour or so.

**Comment by riarenas** [comment]
opened https://github.com/dotnet/arcade/pull/7513 to bring these changes to arcade

**Comment by jakubstilec** [comment]
@riarenas thank you a lot for catching this!
