### ISSUE TITLE
Darc CLI is functional to ship preview II

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#750]
We should provide an entry point for devs to interact with dependency flow mechanisms and functions from a command prompt.

It should have git-like operations and options as well as "confirmation" views as when one is about to merge or rebase and can modify things that are about to be done from a view (file, console, etc.)

There is already several operations defined in https://github.com/dotnet/arcade/blob/master/Documentation/BranchesChannelsAndSubscriptions.md. We can start with these and add more on top as we see fit.

We'll also need to add the actual functionality into `DarcLib` so the CLI is as "dumb" as possible and only understand how to call things in `DarcLib` but has no notion about what is really happening.

- [x] Darc bootstrap is in place

Commands:
- [x] authenticate
- [x] get
  - [x] channels
  - [x] default channels
  - [x] dependencies
  - [x] dependency graph
  - [x] subscriptions
- [x] add
  - [x] channel
  - [x] default channel
  - [x] local dependency
  - [x] subscription
- [x] delete
  - [x] channel
  - [x] default channel
  - [x] subscription
- [x] update
  - [x] dependencies
- [x] retry subscriptions  
- [x] verify

**Comment by dagood** [comment]
What we care about in source-build are the dependency operations in https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md. The ops in https://github.com/dotnet/arcade/blob/master/Documentation/BranchesChannelsAndSubscriptions.md all look like BAR ops, which aren't applicable.

Related in terms of how this is implemented: https://github.com/dotnet/arcade/issues/629 "Darc should be buildable from source".

**Comment by jcagme** [comment]
All issues are fixed!
