### ISSUE TITLE
[darc/maestro++] Maestro staging is currently broken

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7500]
- [x] This issue is blocking 
Maestro staging is totally broken.

- [ ] This issue is causing unreasonable pain

as of https://github.com/dotnet/arcade-services/commit/dec31bcfda19c5941d4a6edb7a1ba52d92812801 the staging website is returning a 500 error when trying to log in:

https://maestro-int.westus2.cloudapp.azure.com/

This manifested itself in breaking all scenario tests due to the maestro tokens being invalid: https://dev.azure.com/dnceng/internal/_build/results?buildId=1179984&view=results

Looking at app insights, it's filled with the following errors:

```
Keyword not supported: 'multiple active result sets'.
```

@alexperovich should we revert this change?

**Comment by riarenas** [comment]
I put this in FR just because it's a build break, but could also just go into the secret management epic as it looks like it was a change in that area that caused this.

**Comment by alexperovich** [comment]
Yea, I think this is caused by some secret changes... I have no idea why the sql stuff would be yelling about. Reverting the change wouldn't help though, the "break" is caused by changed secrets.

**Comment by alexperovich** [comment]
interestingly, the new connection string (created with SqlConnectionStringBuilder), has "Multiple Active Result Sets", the old functional secret has "MultipleActiveResultSets" with no spaces. Thats.... unfortunate that the connection string builder creates a connection string that doesn't work. I can fix it, but its not great.

**Comment by alexperovich** [comment]
ahah, its this issue https://github.com/dotnet/SqlClient/issues/811

**Comment by alexperovich** [comment]
Yep, I have to remove all the spaces from the connection string fields to make them work with the old sql client. :/

**Comment by alexperovich** [comment]
This is fixed
