### ISSUE TITLE
GenPartialFacadeSource task broken for WCF

### ISSUE THREAD

**Issue by mconnew** [dotnet/arcade#7504]
- [x] This issue is blocking 
We can't update to the latest versions, including automatically picking up the latest .net 6.0 builds to test for regressions.
- [x] This issue is causing unreasonable pain

A recent change in the Arcade tooling broke the GenPartialFacadeSource tool for the WCF repo. This is blocking us taking updates to the latest versions as the PR dotnet/wcf#4633 to do so is failing. The suggested workaround when reporting this issue internally was to start manually generating our partial facades and checking in the code when needed. This adds extra steps to the release process which adds unreasonable pain.

**Comment by ericstj** [comment]
Closing as I worked with @mconnew to resolve the break
