### ISSUE TITLE
sdk-task.ps1 script does not have PR validation

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7509]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain
This gap caused a major outage for the publishing infrastructure

The [sdk-task.ps1](https://github.com/dotnet/arcade/blob/main/eng/common/sdk-task.ps1) script is used in many places, including the publish to Build asset registry and the maestro publishing pipeline. A recent change inadvertently broke the execution of this script: https://github.com/dotnet/arcade/issues/7506 which broke the publishing pipeline for every repository. 

We didn't catch this during the PR because nothing calls this script until the official build runs. We should guard against these types of widespread failures by running the script somewhere in the PR validation pipeline.

**Comment by markwilkie** [comment]
@riarenas - do you feel this meets the bar to fix as part of FR or does it better belong in tech debt?  How often does this bite us?

**Comment by riarenas** [comment]
I don't think changes to this script have bitten us before. The script hasn't seen many changes.

I think I'd like to see this addressed in FR mostly due to how impactful a bug in this script can be. A change that didn't affect this script directly, but instead changed an assumption the script had in it caused us to bring down publishing, so every official build for every repo was failing.

**Comment by markwilkie** [comment]
Thoughts @ilyas1974 ?

**Comment by ilyas1974** [comment]
We can evaluate the work involved here in FR and make a determination. As we discovered in https://github.com/dotnet/arcade/issues/7339 the work involved to fix the issue "correctly" (add tests) took the issue beyond what could be accomplished in the FR time frame.

**Comment by missymessa** [comment]
@riarenas what are some examples of how this script is used so I can get a better idea of where in a PR pipeline this would be appropriate to run? Otherwise, I'm thinking it might not be a bad idea to make sure it gets exercised in the Arcade Validation like other parts of Arcade are validated.

**Comment by riarenas** [comment]
@missymessa It's used as the entrypoint to run any msbuild tasks. You can find some examples by searching for usage in the repo.

https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/eng/publishing/v3/signing-validation.yml#L47 and https://github.com/dotnet/arcade/blob/fce95f2bb1a748e65ec6f8f0606c76e0c0d62c27/eng/common/templates/post-build/channels/generic-public-channel.yml Are some examples.

This is already validated in arcade's and arcade-validation's official build, but since the publishing infrastructure picks up changes to the source code directly on merging, waiting for those layers of validation is not sufficient, hence the ask to validate this during PRs to Arcade.

**Comment by missymessa** [comment]
Ahh, okay, thanks for the explanation on that. So either we find a MSBuild task to call that is quick and doesn't affect anything, or create one we can use for testing. Do you have any in mind that might be good for calling during the PR build?

**Comment by riarenas** [comment]
>Do you have any in mind that might be good for calling during the PR build?

I do not.

**Comment by missymessa** [comment]
Okay, no worries. We'll figure something out :)

**Comment by missymessa** [comment]
Okay, after thinking about this, I think the correct thing here is to create a specific MSBuild project for testing this script, and then run that in the PR yaml. I'm hesitant to use an existing MSBuild project in case there's a bug in the project itself, or if the project gets removed or whatever. The test project doesn't need to do anything special, just needs to do something we can assert on to make sure the sdk-task.ps1 script does it's job. 

Hopefully this is enough information to determine if this FR-worthy or belongs in another epic.

**Comment by lukas-lansky** [comment]
After a discussion with Ricardo, I will try to use `DryRun` mode of `PublishToSymbolServers` project to do the test instead of artificial testing proj.

**Comment by jakubstilec** [comment]
Katya created a PR https://github.com/dotnet/arcade/pull/7708, but there are issues which have to be investigated. It's handed over to me.

**Comment by jakubstilec** [comment]
was deployed into production
