### ISSUE TITLE
BARViz showing username/password popup when accessing AzDO

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7527]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

As of the morning of 6/15, a username and password popup is shown when accessing BARViz. I believe this is happening when it's attempting to access AzDO build and/or code info.

**Comment by riarenas** [comment]
THis is most likely due to https://github.com/dotnet/core-eng/issues/13351

**Comment by markwilkie** [comment]
@ilyas1974 - has this been sorted already? (I seem to recall it has)

**Comment by ilyas1974** [comment]
I believe so - let me have someone in FR confirm.

**Comment by missymessa** [comment]
This issue isn't reproducing for me. So I'll close it. I'll direct the RCA to the other one that Michelle filled out.
