### ISSUE TITLE
Publishing to symbol server is failing in runtime 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#7532]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Publishing to symbol server we are experiencing some problem 

![image](https://user-images.githubusercontent.com/47157394/122141206-adbbfe80-ce01-11eb-8b46-cb4971e69973.png)

So I did a check if the symbol actually got uploaded 

https://microsoft.artifacts.visualstudio.com/defaultcollection/_apis/symbol/symsrv/mscordaccore.dll/60C90EE5870000/mscordaccore.dll 

Looks like it somewhere in the middle we encounter that the stream is disposed

**Comment by epananth** [comment]
Note: Most recent change was 
1) Changed the symUploader build task from 1.1.152002 to 1.1.230702
2) For out of memory issue we changed the number of maxclients from 20 to 16

**Comment by epananth** [comment]
I am going to do a test with the older version of symuploader task to see if that will fix this..

**Comment by epananth** [comment]
reverting the symbolUploaderVersion seemed to have worked 

https://dev.azure.com/dnceng/internal/_build/results?buildId=1189499&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=ba23343f-f710-5af9-782d-5bd26b102304

**Comment by epananth** [comment]
tried another failed runtime build https://dev.azure.com/dnceng/internal/_build/results?buildId=1189556&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=ba23343f-f710-5af9-782d-5bd26b102304, seems like something with the SymUploader version

**Comment by ViktorHofer** [comment]
cc @hoyosjs @mangod9 @safern as we discussed this in the team's channel

**Comment by ViktorHofer** [comment]
Note that this is blocking the snapped P6 bits from flowing. cc @Anipik @mmitche

**Comment by epananth** [comment]
I don't think so either.. The one we saw in runtime was the only publishing failure we have seen after the change.

**Comment by hoyosjs** [comment]
Sorry I didn't see this. Revert got handled in #7534 and we just discussed the fix.

**Comment by ViktorHofer** [comment]
In which issue are we tracking the fix for symuploader?

**Comment by hoyosjs** [comment]
All source in that case is internal. We don't have a public facing issue or PR right now.
