### ISSUE TITLE
Build failures due to PublishBuildArtifacts

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#7545]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Errors with the PublishBuildArtifacts were reported to the team twice in the last week. 

See this issue: https://github.com/dotnet/installer/pull/10920#issuecomment-864303995 

Actions: 
- [x] Determine how often this error is occurring so that we can get metrics on the frequency. 
- [ ] Open an IcM on Azure DevOps regarding the issues with this artifact. 
- [ ] Depending on the outcome of the IcM with Azure DevOps, work with LT/SMEs on the team to determine if we need to overhaul this functionality on our side (non-trivial work).

**Comment by ChadNedzlek** [comment]
I'm going to grab the data here. It should be pretty trivial to see how many "PublishBuildArtifacts" tasks failed in a time period, since this is recorded in the timeline data.

**Comment by ChadNedzlek** [comment]
Data!
![image.png](https://images.zenhubusercontent.com/58584e04b9dc3c622023c43a/92e4b6df-d656-4e6c-8cd6-ea9ca82e340b)

I'm not sure what we want to do with this, so I'm putting it back on the backlog. :-)

**Comment by ilyas1974** [comment]
@ChadNedzlek 

- can sure a link on where you pulled this data from so we can add that to our knowledge base. 
- The data you linked above shows Failures (I'm assuming). Do you have data on how those failures numbers compare to the overall? 

@missymessa 
- have you heard of any additional instances of this more recently than a month ago?

**Comment by missymessa** [comment]
I don't know of any other instances of this, but it's likely to occur again if no changes are made.

**Comment by ChadNedzlek** [comment]
It's the same place we pull all of our data from: Kusto.

**Comment by ChadNedzlek** [comment]
The number of builds is enormous.  This task ran 600,000 times. we failed 418 times. So 0.7%, I think.

**Comment by ChadNedzlek** [comment]
Percentage per day version:
![image](https://user-images.githubusercontent.com/11790765/126394470-bb41bdcc-d9df-4716-ae70-92add861b816.png)

**Comment by missymessa** [comment]
I know the last time this happened, DanM wanted an IcM ticket for this.

**Comment by ChadNedzlek** [comment]
1% is pretty high for failures.

**Comment by alexperovich** [comment]
If there are 100 attempts in a build, and each attempt fails 1% of the time, thats a 63% failure rate for that build.

**Comment by ChadNedzlek** [comment]
*nods* Indeed, failures are multiplicatively bad, and our builds are _huge_.  I'll try an tweak this to "number of builds that had a failure"

**Comment by ChadNedzlek** [comment]
![image](https://user-images.githubusercontent.com/11790765/126401309-89f93e0a-1f9d-44f9-ba74-92b4ecc2a6c2.png)

**Comment by ChadNedzlek** [comment]
Apparently if we categorize it by "Builds that had one of these failures" it spiked almost to 10%, which is really bad.

**Comment by riarenas** [comment]
Does this overlap with https://github.com/dotnet/core-eng/issues/13786 at all? If so there's a bunch of those that are entirely on us and not on azure devops.

**Comment by ChadNedzlek** [comment]
I don't think we have any code inside the PublishBuildArtifacts task. That's just a task in AzDO.  It's possible we are giving it bad inputs, it's hard to differentiate those with the data I have available unless someone can tell me how to differentiate them or what to look for. :-)

**Comment by riarenas** [comment]
There are two ways in which we upload to azure artifacts:

* using a logging command (like all the failures in the above issue, they are trying to upload the same artifact from multiple legs at the same time, which makes azdo just not know what's going on)
* using the publishBuildArtifacts@1 task

Mainly wondering if how we're looking at these includes both types, or only when we call the task directly from the YAML.

**Comment by ChadNedzlek** [comment]
The graphs I added ONLY take into account the "PublishBuildArtifact" task failures.  Not any of the logging commands.

**Comment by riarenas** [comment]
Awesome, that way we can tell them we're not conflating both things.

**Comment by ilyas1974** [comment]
Now that we have data, what are the next steps here?

**Comment by ChadNedzlek** [comment]
The data shows that it's fairly low now. And given the current problems with AzDO, opening an IcM saying it was a problem 2 weeks ago probably won't get a lot of traction.

This feels like a good place to use @AlitzelMendez new feature: if PublishBuildArtifacts fail, maybe trigger a retry?

**Comment by AlitzelMendez** [comment]
dotnet/installer is already using the Build Retry since Monday/Tuesday.

**Comment by ChadNedzlek** [comment]
Yup, but this would let us pave over it in other repos too.  It's unfortunate that you need to basically do the whole build part again because the very last leg failed, but it's better than failing the whole build

**Comment by ChadNedzlek** [comment]
Given that it looks like the incidence right now is really low, I'm going to close this.
