### ISSUE TITLE
Get build error "The property 'Prefer64bit' cannot be found on this object. Verify that the property exists." in the latest update

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/arcade#7574]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

- build ID: 20210624.3
- commit: a68ec1edf328e737b31a09cb49e1929c28e91d0c
- link to insertion PR: https://github.com/dotnet/machinelearning-tools/pull/1116

**Comment by riarenas** [comment]
Fixed by: https://github.com/dotnet/arcade/pull/7564

MachineLearningTools has a weekly update cadence, so I had to trigger the subscription manually. I suggest moving to a daily update cadence so you don't get stuck with bad updates for an entire week.

**Comment by RussKie** [comment]
This also blocks dotnet/winforms release/3.1 branch: https://github.com/dotnet/winforms/pull/5211/checks?check_run_id=3015332988

**Comment by riarenas** [comment]
@RussKie that's not the latest arcade build for the 3.x channel so its missing the latest fixes.

**Comment by RussKie** [comment]
So what are our options? Give it a bit more time?

**Comment by RussKie** [comment]
Here's another one: https://github.com/dotnet/wpf/pull/4813/checks?check_run_id=3011268415

/cc: @dreddy-work @ryalanms

**Comment by lukas-lansky** [comment]
@RussKie Looking into your subscription:

```
> darc get-subscriptions --source-repo arcade --target-repo winforms --target-branch release/3.1
https://github.com/dotnet/arcade (.NET 3 Eng) ==> 'https://github.com/dotnet/winforms' ('release/3.1')
  - Id: a2a5ea62-d9bf-419c-0c86-08d7315b512a
  - Update Frequency: None
  - Enabled: True
  - Batchable: False
  - PR Failure Notification tags:
  - Merge Policies:
    Standard
  - Last Build: 20210428.7 (99023a1f05a0bb03257f473e48b376c8fb78f845)
```

I can see you don't update Arcade automatically (`Update Frequency: None`). Therefore, I will trigger it manually like this:

```
> darc trigger-subscriptions --id a2a5ea62-d9bf-419c-0c86-08d7315b512a
Will trigger the following 1 subscriptions...
  https://github.com/dotnet/arcade (.NET 3 Eng) ==> 'https://github.com/dotnet/winforms' ('release/3.1')
Continue? (y/n) y
Triggering 1 subscriptions...done
```

This updated this already existing PR from two days ago: https://github.com/dotnet/winforms/pull/5211 . We just need to merge it now.

**Comment by lukas-lansky** [comment]
I did the same for WPF: https://github.com/dotnet/wpf/pull/4813

**Comment by lukas-lansky** [comment]
Interesting, the fix isn't present in Arcade's 3.x servicing branch. Let's fix it here: https://github.com/dotnet/arcade/pull/7604 . As soon as that's merged, I will trigger the subscriptions again.
