### ISSUE TITLE
Make SDL automation support broader: tar.gz/zip artifacts, extensible Guardian tool configurations

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#7592]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

I worked on SDL requirements for a new repo, and had to make some changes to the Arcade SDL automation to make it fit. Main changes:
* Support tar.gz and zip artifacts, not just NuGet. (My repo only produces archives.)
* Make Guardian tool configuration more directly settable by the caller.
  * The set of tools to run, what to run them on, and how to run them is not necessarily the same for all repos. Requirements can also change over time.
* Support pipeline artifacts, not only build artifacts. (Pipeline artifacts being preferable for new infra.)
* Let the caller pass in pipeline info, rather than requiring the build be published to BAR via a Maestro++ job.
  * This also lets the caller point the SDL job to a specific build to download, to make it faster to iterate on SDL changes in a dev branch without doing a full build each time.
* Improve configure -> run workflow.
  * Right now it configures some tools (for source code), runs them, then configures other tools (for artifacts), and runs those. The second run overwrites the results of the first, so they aren't accessible for `guardian break` (if enabled), and you can't get to the old results in the `.gdn` dir.
  * Instead, configure *all* tools up front and `run` once.
* Publish important `.gdn` files for more detailed diagnosis. Especially useful when trying to set up a new Guardian tool.

Do any of these changes seem questionable, at a high level?

I have some WIP here, if seeing concrete changes makes it easier to understand what I'm describing. 😄 https://github.com/dotnet/arcade/commit/c348b268450d4c3f203819fccdae0abb213aa92a. I want to change a few things before submitting a PR to dotnet/arcade. (I want to make the version of Guardian user-configurable without changing the hard-coded default, and make it clear when you would want to change `pool`.)

**Comment by markwilkie** [comment]
My initial reaction is that this indeed sounds very reasonable at a high level.   And...thanks Davis for helping out.

Including @adiaaida (who's on vacation right this minute) as she might have input.  Also, it'd probably be wise to reach out to the Guardian folks as perhaps they have something in their pipeline as well.

**Comment by adiaaida** [comment]
This all sounds pretty reasonable to me, but I'd want to run it in the test staging pipeline to make sure it works well with our existing functionality.
