### ISSUE TITLE
[Localization] Assistance with translation

### ISSUE THREAD

**Issue by crsuzukimsft** [dotnet/arcade#7593]
Could you please clarify the use of this string and the placeholder: "# API List of {0}"

Likewise, the string "# API Difference {0} vs {1}"  would need clarification about the placeholders and where it is used.

Is # translatable or does it represent some number or perhaps commenting?
Provide some examples.

**Comment by riarenas** [comment]
@ericstj these are about asmdiff https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.AsmDiff/xlf/Resources.es.xlf. Can you help @crsuzukimsft?

**Comment by cristianosuzuki77** [comment]
@ericstj Could you please assist?

**Comment by ericstj** [comment]
The `#` is a special character that should not be localized.  It's the markdown specifier for a heading.

The `{0}` and `{1)` are command line arguments which the directory or filename of a comparison.  They are specified here, with `{0}` being `--OldSetName` and `{1}` being `--NewSetName` https://github.com/dotnet/arcade/blob/d80b16b64fe001a99c699262ef65f712aa98d538/src/Microsoft.DotNet.AsmDiff/Program.cs#L19-L22

An example, suppose we were using this tool to produce an API diff of .NET 5.0 and .NET 6.0, we might pass in `-osn 5.0.0 -nsn 6.0.0`

This string would be
> # of API Difference 5.0.0 vs 6.0.0

See https://github.com/dotnet/core/blob/main/release-notes/6.0/api-diff/.Net/6.0.0.md

Another use might be for the developer to pass in some word to indicate the meaning of either side of the comparison
> # of API Difference old vs new
Or
> # of API Difference before refactoring vs after refactoring

cc @Herrmel who contributed this.  cc @safern @carlossanlop

**Comment by cristianosuzuki77** [comment]
Thanks.
Could you give an example for the first placeholder?
"# API List of {0}"

**Comment by Herrmel** [comment]
I think the first placeholder is used when only one Version is provided and the tool then returns a simple List of the api or something like that. I think it also uses any of the two parameters when provided to be able to clarify what the api-List is from. Could be an assemblyname for example.
I agree the # should not be localized and it would make sense to move it out of the resourcestrings, that was an oversight by me.
