### ISSUE TITLE
Consider running restore first & separately in eng/common build scripts when -restore flag set

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#7617]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

This comes as a suggestion from the Azure DevOPs team for dealing with when their public package feeds get overwhelmed.  We directly call Msbuild with all the flags today in build.sh / build.ps1, this would simply be to run a separate restore first when the -restore flag is set.

I don't think so, nor do I have data that this would make matters better (since I learned today Nuget is already retrying with 200 ms delay 3x, more restores feels like more storm).

**Comment by AlitzelMendez** [comment]
This is the PR in which I was trying to do this: https://github.com/dotnet/runtime/pull/55788/checks?check_run_id=3082091301

I will be OOF tomorrow so probably @ChadNedzlek can continue to look at this.

**Comment by MattGal** [comment]
@ChadNedzlek please keep this moving, but I think Ali's experiment shows what we wanted to see:

- An explicit extra build that (at least tries to be) purely a restore before the normal build does cause the behavior that Azure Devops claims could make package feed access more reliable (could probably skip the first one's binlog)
- "Build Mono LLVM AOT cross compiler" pipeline needs to be investigated as it may have found a case where this doesn't work
- For some stages like "Build CoreCLR Runtime", there are clearly some side effects like rerunning CMake validation, but most seem minor.

**Comment by AlitzelMendez** [comment]
I am currently working into: `"Build Mono LLVM AOT cross compiler" pipeline needs to be investigated as it may have found a case where this doesn't work`
I am running a new build with small changes.

**Comment by MattGal** [comment]
> I am currently working into: `"Build Mono LLVM AOT cross compiler" pipeline needs to be investigated as it may have found a case where this doesn't work`
> I am running a new build with small changes.

Given the FR backlog, I don't think this is worth too much more of your time; the fact that we hit weird problems trying to do this on the first repo tried, I think it's a strong indicator for "avoid doing this".

**Comment by AlitzelMendez** [comment]
As a result of this test we realize that doing this change it's not as straightforward as it should be as "Build Mono LLVM AOT cross compiler" failed what showed us that could be bad repercussions in doing this change that could impact more repos that rely on this.

Closing this issue.
