### ISSUE TITLE
Delete Darc_GitHubFlow_NonBatched_AllChecksSuccessful scenario test from arcade-services

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7632]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain
This test is flaky and causes several builds a week to fail. It currently has a 65% pass rate (over 30 days) in staging.

This particular test has caused a lot of CI builds to fail in staging, and it's also unnecessary. The `Darc_GitHubFlow_AutoMerge_GithubChecks_AllChecksSuccessful` test covers the exact same scenario, except it has additional checks to make sure that the PR gets merged at the end of the test instead of just checking that the PR exists. 

Removing this test will both help with making the scenario tests run faster overall, and will reduce noise.

**Comment by markwilkie** [comment]
I agree with removing the test.  Thanks Ricardo.
