### ISSUE TITLE
Running restore first & separately in eng/common build scripts 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#7647]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Per Azure DevOPs team suggestion a build was ran having a separate restore first in build.sh/build.ps1, right before another restore. This means having two restore (when the restore flag is set)

Sharing the pr in which this was tested: https://github.com/dotnet/runtime/pull/55788

Our findings were:

* An explicit extra build that (at least tries to be) purely a restore before the normal build does cause the behavior that Azure Devops claims could make package feed access more reliable (could probably skip the first one's binlog)
* The quick test that we did was not successful for the entire build and we should invest more effort to make it work. The error is on the stage: "Build Mono LLVM AOT cross compiler" 
* For some stages like "Build CoreCLR Runtime", there are clearly some side effects like rerunning CMake validation, but most seem minor.

**Comment by ilyas1974** [comment]
@AlitzelMendez, what is the action here for us?

**Comment by riarenas** [comment]
What's the difference between this one and https://github.com/dotnet/arcade/issues/7617?

**Comment by AlitzelMendez** [comment]
As a result of this test we realize that doing this change it's not as straightforward as it should be as "Build Mono LLVM AOT cross compiler" failed what showed us that could be bad repercussions in doing this change that could impact more repos that rely on this. 

Closing this issue.
