### ISSUE TITLE
Investigate Sleet push issue when prerelease contains uppercase letters

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/arcade#765]
@dagood commented on [Fri Aug 24 2018](https://github.com/dotnet/core-eng/issues/4103)

dotnetfeed itself has been cleaned up (see https://github.com/dotnet/core-eng/issues/4098) but this issue should be investigated:

Uploading `System.ServiceModel.Duplex` `4.5.3-UwpPreview2` caused this url to get set up:

[https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.servicemodel.duplex/4.5.3-**uwppreview2**/system.servicemodel.duplex.4.5.3-**uwppreview2**.nupkg](https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.servicemodel.duplex/4.5.3-uwppreview2/system.servicemodel.duplex.4.5.3-uwppreview2.nupkg)

However, `index.json` contains `4.5.3-UwpPreview2`, which causes the NuGet client to request this URL, which 404'd:

[https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.servicemodel.duplex/4.5.3-**UwpPreview2**/system.servicemodel.duplex.4.5.3-**UwpPreview2**.nupkg](https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.servicemodel.duplex/4.5.3-UwpPreview2/system.servicemodel.duplex.4.5.3-UwpPreview2.nupkg)

This causes a nuget restore error like this:

```
error : The feed 'dotnet-core [https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json]' lists package 'System.ServiceModel.Security.4.5.3-UwpPreview2' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. [E:\temp\restore-uwp\restore-uwp.csproj]
error :   Unable to find package 'System.ServiceModel.Security.4.5.3-UwpPreview2'. [E:\temp\restore-uwp\restore-uwp.csproj]
```

MyGet didn't have this issue because `index.json` contained `4.5.3-uwppreview2`.

**Comment by riarenas** [comment]
@johntortugo did you look into this? I believe the new publishing infra solves this, but just making sure

**Comment by JohnTortugo** [comment]
I think wen can close this, because:

- I never looked into this. It's been one year since the issue creation and I never saw another occurrence of this problem. 
- We are moving away from Sleet.
