### ISSUE TITLE
NugetAuth task should run on internal PRs by default (Port to release branches)

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/arcade#7663]
After #7580, an internal feed is automatically added but the [job template](https://github.com/dotnet/arcade/blob/c5d8214ed77ba3abc86337e870e8568deb14a93a/eng/common/templates/job/job.yml#L117) only does nuget auth if not in the public. This is not friendly with internal PRs - say for MSRC ones. NugetAuth should happen automatically if not running in the public project. 

cc: @mmitche

**Comment by mmitche** [comment]
@hoyosjs Do you have a link to a failing build? I've seen a bunch of places where it is working.

**Comment by hoyosjs** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-diagnostics-internal-components/pullrequest/16604

https://dev.azure.com/dnceng/internal/_git/dotnet-diagnostics-internal-components/pullrequest/16871

**Comment by riarenas** [comment]
It seems like a reasonable ask. @mmitche Is there somewhere you're tracking these kinds of issues for the work that you and Lukas do during releases?

**Comment by dougbu** [comment]
In a similar fashion, could we consider centralizing the `SetupNugetSources.*` invocations in the eng/common YAML❔ If there's already an issue for that, please point me that way 😸

**Comment by mmitche** [comment]
We could, but we need to be careful, since there are lots of repos that do not need this functionality and whose build pipelines do not (and should not) have access to the credentials required for SetupNugetSources.ps1. So we would need to conditionalize this based on available variables.

I see the benefit here of centralizing this as fairly minimal.

**Comment by MattGal** [comment]
Based off the push back I am not going to port this to release branches.  It's easy for people who need it to "do the right thing" in their own pipeline versus if you make it a default what you predict is likely to happen, so closing.
