### ISSUE TITLE
Darc gather-drop failing to download files larger than 2GB

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#7668]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

Installer now publishes files that are larger than 2GB. A fix was made in arcade to allow the publishing of these files, but this fix now needs to be applied to gather-drop for downloading the files as well. The error message looks like this:

```
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      There was an error executing method 'GET' against URI 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk//dotnet-sdk-source-6.0.100-rc.1.21375.5.tar.gz' after 3 attempts. Exception: System.Net.Http.HttpRequestException: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in System.Net.Http.dll:token 0x6000275+0x216
         at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 76
```

Full log: https://dev.azure.com/dnceng/internal/_build/results?buildId=1257973&view=logs&j=40e1e683-ea82-5be9-b25e-899b65e1c0cb&t=94a692ec-20f2-55dd-1884-cf0cad1763a4&l=423

/cc: @riarenas

**Comment by riarenas** [comment]
Yep makes sense. I'll find where we do the download and set the option there.

**Comment by riarenas** [comment]
Now I'm facing an issue where even if we don't allocate the response buffer, the connection ends up being closed before the file is fully downloaded. Probably due to all the parallel downloads.

**Comment by adiaaida** [comment]
:(

**Comment by riarenas** [comment]
I think it's just because the file is too large to be downloaded in the default timeout of 180 seconds. If I pass a longer timeout to the gather-drop invocation, I'm able to gather it. Once the buffer problem is fixed we will need to include a --download-timeout parameter to the gather-drop command in the release pipeline.

**Comment by riarenas** [comment]
Arcade-services piece of this is https://github.com/dotnet/arcade-services/pull/1685

**Comment by riarenas** [comment]
The fix is available in darc version `1.1.0-beta.21376.2`.

**Comment by riarenas** [comment]
This is now available in the default version of darc that the scripts obtain. @adiaaida have you been able to test whether the change fixes things?

**Comment by adiaaida** [comment]
I will run a test pipeline on the build that previously failed

**Comment by adiaaida** [comment]
Testing this here: https://dev.azure.com/dnceng/internal/_build/results?buildId=1266498&view=results

**Comment by adiaaida** [comment]
all seems well.

**Comment by riarenas** [comment]
Thanks for verifying! closing as fixed.
