### ISSUE TITLE
Staging - Publish Assets to Staging Location failing in release/5.0

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7683]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://dev.azure.com/dnceng/internal/_build/results?buildId=1262932&view=logs&j=06e47235-ea4e-5696-bf7a-60141ec0f646&t=47670f0e-00d8-5b02-83e7-3c31b24a0034

I think what is happening here is that the copy in the first loop is critical to the publishing process (otherwise files don't end up in the right directories), but the `break` here https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=%2Feng%2Fpipeline%2Ftools%2Fpublish-v3.ps1&version=GBrelease%2F5.0&line=88&lineEnd=89&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents short-circuits the copy. Sometimes this works because the merged manifest is before the first internal item in the build, but it still probably misses some artifacts.

**Comment by adiaaida** [comment]
This was definitely a bug that came in with a recent change. The fix has been checked in.
