### ISSUE TITLE
http client timeouts when uploading blobs to storage account during publishing

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7687]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain

We're seeing some failed publishing jobs where we fail to upload a blob because we hit the default 100 second HttpClient timeout. We should see if we can increase the timeout in the Azure libraries, and whether that helps or not. 

Some example failures:

* https://dev.azure.com/dnceng/internal/_build/results?buildId=1265525&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a
* https://dev.azure.com/dnceng/internal/_build/results?buildId=1264791&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a
* https://dev.azure.com/dnceng/internal/_build/results?buildId=1265145&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a

The operation that is failing is here: https://github.com/dotnet/arcade/blob/b038a54d9137901e22868692b3d1f5c050e968c8/src/Microsoft.DotNet.Build.Tasks.Feed/src/common/AzureStorageUtils.cs#L85

**Comment by AlitzelMendez** [comment]
This has been merged. The timeout has been increased to 300 seconds and the expectation is that this fix the issue but as Ricardo said this can't be the case, so feel free to reopen if needed.
