### ISSUE TITLE
Investigate tweaking algorithm to determine whether the staging feed should be public or internal

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7688]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In .NET 6 Preview 7, I had the default channels set up to assign the same dotnet-wpf-int branch to internal and public (they are the same branch, so this made some sense). When gather-drop ran, it downloaded packages from the wpf-int build from the internal feed first. That meant that the feed was created as internal because one asset was only available internally. This is correct according to the existing logic. But because those assets were also available on public feeds, one could argue they're public by default.

Tweaking the logic might be worth it (if low cost) to improve the public/internal feed decision:
- An asset is public if **any** of its source locations is public. If all source locations are internal, the asset is internal
- The output feed should be internal if **any** of the assets are internal.

Doing this would require recording all valid source locations for an asset, rather than just the one that gather-drop actually managed to use successfully, so I'm not sure it's worth it.

**Comment by adiaaida** [comment]
Do we have any easy translation between an internal feed and a public feed? For 6.0, it looks as simple as:

1. Remove -internal
2. Replace internal/ with public/.

I'm thinking maybe, if we find a feel link that we think is internal, convert it to what the public version would be, and if that is successful, we can say it exists on both feeds, and can be deemed public.

**Comment by mmitche** [comment]
There's not, since sometimes the internal feeds are project scoped and sometimes they are org scoped. I think the real way to do it would be to have gather-drop record all possible source locations that work. Basically attempt to download from all source locations by doing a HEAD request, use one of those to actually download, but record all of the source locations in the manifest.

Anyways, I think this may not be worth it. Instead:
* Avoiding mixing the two types of channels together in the same build seems relatively
* Adding some global override switch to the pipeline to treat a build as public or internal.

**Comment by riarenas** [comment]
I'm adding this to the current release epic. Let me know if you feel like that's not the right place for this.

**Comment by adiaaida** [comment]
@mmitche my other thought was also changing gather-drop, but I agree that that might not be worth it, and could be quite risky if we don't do it right. Your second suggestion (global override switch) is really straight forward an easy.

**Comment by adiaaida** [comment]
> I'm adding this to the current release epic. Let me know if you feel like that's not the right place for this.

That's good.

**Comment by adiaaida** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/17127
