### ISSUE TITLE
init-tools-native.sh does not currently work ("must use subscript when assigning associative array")

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#7689]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Seems to have been introduced in https://github.com/dotnet/arcade/pull/6726.  Not sure how this hasn't been noticed for 7 months; it may just be something the defaults tend to be 'good enough' in the build machines for.

When running linux-based arcade-ified builds, I consistently see this line:

``` 
/__w/1/s/eng/common/init-tools-native.sh: line 150: native_assets: "$line": must use subscript when assigning associative array
No native tools defined in global.json
```

Since I noticed this while adding native tools to a repo, it seems odd that the next line is "no native tools" but that could still be a red herring, since it's possible that expressed cmake dependency somehow knows not to try to work on Linux. (unlikely?)

**Comment by ChadNedzlek** [comment]
If this hasn't worked for 7 months, it sounds like no one is using it and we should probably delete it?

**Comment by MattGal** [comment]
[Triage]: @ilyas1974  I'm just putting this into FR.  Even if it's unneeded, we can clean it up so it doesn't cause confusion for other users.
