### ISSUE TITLE
Temporarily disabled iOS.Device queue

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#7696]
Temporarily disabled the iOS.Device queue in arcade because it's failing with the new helix reporting, and we were unable to fix it.

We need to reenable it once we figure out why it can't report to helix like other queues.

It seems to be some sort of permission issue writing a sdk cache file:
PermissionError: [Errno 13] Permission denied: '/Users/helix-runner/.azure-devops/python-sdk/cache/options.json'

**Comment by premun** [comment]
Can you link where you disabled those? I cannot find the commit

**Comment by ChadNedzlek** [comment]
It's this commit: https://github.com/dotnet/arcade/pull/7646/commits/2fd06326dbb94740897765b918242bd88d61809b

**Comment by ChadNedzlek** [comment]
Found the problem, didn't do this. Closing.
