### ISSUE TITLE
Remove hack in NuGet feed package

### ISSUE THREAD

**Issue by greenEkatherine** [dotnet/arcade#7699]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

There was hack added in Nuget feed package https://github.com/dotnet/arcade/commit/841c83d to unblock issue https://github.com/dotnet/arcade/issues/1965 It should be resolved now after MSBuild update https://github.com/dotnet/msbuild/issues/5073

We need to remove it and validate that sdk /runtime repos are not broken.

**Comment by adiaaida** [comment]
Just for clarity, does this mean just removing the code that Chris added and then testing it against the repos that were broken?

**Comment by chcosta** [comment]
I think the hack is fine, and the "fix" doesn't appear to be working, so closing this.
