### ISSUE TITLE
Investigate Component Governance warnings in Validate-DotNet

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#7710]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We don't always see these warnings, but we sometimes do, and they are annoying. Investigate why we get these warnings so product teams don't see them when BuildMonitor opens issues in their repos for pipeline failures.

**Comment by ViktorHofer** [comment]
cc @dougbu FYI this is about this warning: https://github.com/dotnet/runtime/issues/56516#issuecomment-892832588

**Comment by adiaaida** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/17225

**Comment by adiaaida** [comment]
The change to disable CG in the validate and staging pipelines has been checked in. Validate will get this immediately. Stage will have to wait for rollout.
