### ISSUE TITLE
[Darc] Dependency expression extensibility

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#774]
How are more dependency expression types added?

[DependencyDescriptionFormat.md](https://github.com/dotnet/arcade/blob/master/Documentation/DependencyDescriptionFormat.md) describes existing dependency expression capabilities. (A dependency expression is similar to a VersionTools auto-updater.)

Examples:
* Submodule updates
* Info insertion into Dockerfiles
  * Checksum/hash of .NET Core artifacts to verify during Dockerfile build.
  * Download endpoint (and/or partial info, like version) of .NET Core artifacts.
  * (These need to be checked in because Dockerfiles are expected to be buildable as-is. They can't be processed during a build to dynamically incorporate info from the `eng/` dir.)
* `BuildToolsVersion.txt` and similar
  * (If we try to apply Darc functionality to pre-Arcade .NET Core Runtime repos.)

It would be nice if new expression types could be added by individual repos. However, since Maestro++ uses DarcLib directly (in-process?) to modify files using the target Git host's web API, it might not be reasonable to load in new code. By that I mean it would make sense to me if new expression types could only be created by contributing to dotnet/arcade.

@alexperovich @mmitche 
/cc @dleeapho @MichaelSimons @weshaggard

**Comment by weshaggard** [comment]
I would like to add files as a whole we need to be able to update particular files from a repo with other repo's. This is similar to `eng/common` but more general.

**Comment by mmitche** [comment]
/cc @jcagme @dagood It should be extensible by submitting to dotnet/arcade, then a new maestro deployment will get new capabilities.

I don't think we should scatter out update capability into other repos.  That's what we have today and it ends up leading to inconsistencies in how repos are handling and updating their dependencies.

**Comment by markwilkie** [comment]
Closing for now as @mmitche has an answer and there does not seem to be anything actionable just yet.
