### ISSUE TITLE
SourceIndexStage1 is broken with the SDK upgrade

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#7747]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

**Official builds in at least dotnet/runtime are currently broken** because the [source index pipeline relies on the `UseDotNet@2` task](https://github.com/dotnet/runtime/blob/daeb85b4abb4008f5202185f4a4e958edd7a80b9/eng/common/templates/job/source-index-stage1.yml#L38-L41) which only respects released versions listed in https://github.com/dotnet/core/blob/main/release-notes/releases-index.json.

This doesn't repro in arcade as arcade doesn't specify an sdk version in its global.json file and hence that step is a no-op: https://dnceng.visualstudio.com/internal/_build/results?buildId=1290901&view=logs&j=316d5c15-0c50-544e-8051-e6b14a1ab674&t=59bb5a6d-1561-5af9-b304-6b168fc2f9c5&l=10

Meanwhile on dotnet/runtime where we specify an "sdk" version in our global.json, official builds are broken: https://dev.azure.com/dnceng/internal/_build/results?buildId=1291797&view=logs&j=316d5c15-0c50-544e-8051-e6b14a1ab674&t=59bb5a6d-1561-5af9-b304-6b168fc2f9c5&l=12

I will try to workaround this in dotnet/runtime just to unblock official builds but we should agree on what the right mitigation would looks like. I imagine one of these in order of preference:
- As building the repository already fetches an SDK, can't we use that avoid downloading yet another one?
- Get rid of the `UseDotNet@2` task and acquire the SDK the same way as we in our build (by using Arcade's install scripts which call into dotnet-install.ps1/sh).
- Hardcode versions in the `UseDotNet@2` task invocation and make sure those stay up-to-date.

cc @markwilkie @Chrisboh @danmoseley

**Comment by jakubstilec** [comment]
cc @alexperovich

**Comment by ViktorHofer** [comment]
One more thought on this. The SDK version used by the repo must either be the same or higher than the one used to compile the global tools used. As Arcade flows SDK version updates to their consuming repositories, that should be fine.

As that contract between matching SDK versions already exist, the mitigation that I applied in dotnet/runtime https://github.com/dotnet/runtime/commit/c842beb5a94642e7ddd06e262c50f67e297ce986 might be suitable as a real fix **if we are fine with restoring tools** later during the build and not up-front. Usually we tried to avoid that but tripple restoring SDKs doesn't make sense either.

**Comment by ViktorHofer** [comment]
Update: The fix that I applied in eng/common/ in dotnet/runtime was expectedly overwritten by the latest Arcade update. I again temporarily fixed this to unblock broken builds but we need to find a permanent solution asap: https://github.com/dotnet/runtime/commit/0a1ff5b63071909b18115aac151d415ff007b63c.

**Comment by riarenas** [comment]
@chcosta this is the issue that goes along with the email and the teams thread in case you haven't seen Viktor's workarounds yet.
