### ISSUE TITLE
[Maestro++] Support declarative subscriptions

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#775]
Docker repos have enough dependencies that manually creating and setting up subscriptions would be a significant maintenance burden. At the moment it's expected that we'll have one channel per Docker base image, like https://github.com/dotnet/versions/tree/master/build-info/docker. Each Docker base image gets built granularly, so each one needs a new channel.

To keep maintenance effort down, subscriptions for this scenario should be declarative based on the subscribing repo.

Here's an idea for how to do this. I imagine it could be made cleaner if directly supported, but the below seems doable with minimal new code. Whenever a commit is checked into the subscribing repo (e.g. during its rolling build):

1. Calculate which subscriptions make sense given the current state of the repo.
   * This may be complicated. To keep it cohesive, it would make sense for the logic to be in the repo.
1. Check which subscriptions exist in Maestro++.
1. Add subscriptions that don't exist yet.
1. Remove subscriptions that aren't needed that were originally created by this infra.
   * Sounds dangerous. I think this step could actually be skipped. Although the subscriptions would build up in the database, as long as they don't have any expression in the repo they should NOP.
   * This is what first-class support would be good at cleaning up.

This enables a workflow where a dev would submit a PR to a Docker repo that adds a dependency on a new base image, and after the PR is merged, the Docker repo would start getting auto-PRs for that new base image without any manual subscription work.

If Arcade doesn't support this, the steps could be done in a custom repo-specific project.

@alexperovich @mmitche 
/cc @dleeapho @MichaelSimons

**Comment by dagood** [comment]
> Each Docker base image gets built granularly, so each one needs a new channel.

For example, the Alpine base image gets built independently and at different times from the Ubuntu base image. (I mean the OS image itself: we don't control these builds. Even if we did, we would want to build them independently so we only need to rebuild things that have actually changed.) Putting them in the same channel seems like the same scenario as trying to put two branches' builds in the same channel.

**Comment by dagood** [comment]
This was kinda discussed in https://github.com/dotnet/arcade/pull/268#discussion_r196820948, where an alternative is to let them in the same channel but make the latest build/assets of each "type" addressable. ("Type" in this case would be the base image name.) I was really unclear about the scenario though, so maybe this changes things.

**Comment by mmitche** [comment]
If those are different assets, then they can go in the same channel.  For instance, core-setup and coreclr can both go to 'NET Core 3.0 latest', since there is no overlap in assets.

**Comment by mmitche** [comment]
That said, since these are inputs we're not building, it may make sense to have them go to different channels.

**Comment by mmitche** [comment]
Btw, for subscription purposes, both the input repo and channel are considered.

**Comment by dagood** [comment]
The BAR doc suggests that there's no way to get the latest version of an asset other than looking at the latest build of a specific repo in a specific channel:

> [Query](https://github.com/dotnet/arcade/blob/e847a3beca0e2a7c34f482270c9616d14fdad031/Documentation/Maestro/BuildAssetRegistry.md#query)
> 1. Get latest Build of a repository for a channel
>    * Used by Darc to determine if a dependency needs to be updated
> 1. Get repositories that subscribe to updates from a [Repository] intended for a Channel
>    * Used by Darc to flow dependencies when a Build is assigned to a Channel
> 1. Get a Specific Build
>    * Used by MC
> 1. Get dependencies of a Build
>    * Used by MC to show dependency tree for a Build

This makes me think each base image type must have its own (fake) repository to be addressable by the auto-update infra. My understanding is with one channel we need to do one of these to get auto-update hooked up:

1. Have one subscription per (fake) repository, all pointing to this one channel.
   * Even though they're on one channel, since we need many subscriptions, I think declarative subscriptions are still needed to be maintainable in this case.
1. Have a single subscription for the channel, which *doesn't* consider repo.
   * I don't think I've considered this possibility before. I agree a single subscription like this would probably be reasonable to manually maintain.
1. Add a "Get latest Asset of a certain name in a Channel [from any repo's build]" API.
   * Maybe this simply exists. To me, the APIs and models in the doc don't imply this would work.

Multiple channels is basically the same as (1) there, so yeah, I guess it isn't necessary to do that.

**Comment by dagood** [comment]
Does this issue make sense, is it being considered for Maestro++?

If not, should it be closed with the workaround recommended?

> If Arcade doesn't support this, the steps could be done in a custom repo-specific project.

**Comment by dagood** [comment]
Chatted with @mmitche then @MichaelSimons offline, and it turns out I didn't know the actual Docker scenarios. The base image dependencies in the Dockerfiles are actually floating, so the repo just needs to rebuild, not check in the new versions. So, I'm closing this.

But also, talking with @mmitche, we discussed a way to do upgrades with a single subscription without new features. Maestro++ doesn't remove dependencies when they don't exist anymore, so we don't need a "Get latest Asset of a certain name in a Channel [from any repo's build]" API to keep the repo up to date. Maestro++ matches up the assets that *were* built to dependencies and updates only those.

The weakness is that if a PR is closed, losing the update commit, Maestro++ won't bring the lost dependencies up to speed in a new PR. (Until that specific dependencies gets a new build.) For this scenario, that API would be added and Darc would have some way to iterate through each dependency and find the latest version of each one, regardless of build.

Either way, issue not needed.
