### ISSUE TITLE
[Darc] Support dependencies generated from repo state

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#777]
If a repo is organized in a way that its dependencies can be derived from the repo's current state, Darc can take advantage of this: the dependencies don't need to be duplicated and maintained in `eng/`. I have https://github.com/dotnet/dotnet-docker in mind.

This also allows devs in the repo to add/remove dependencies by making the changes they care about--they don't have to also understand and use Darc, which would be a maintenance burden in these cases.

A way to allow repos to do this if they choose, but avoid adding it to mainline Darc/Maestro++, is to do something like Maestro: a subscription trigger starts a completely custom process defined by the repo. (The process would hopefully use Darc as part of its flow.)

@mmitche @jcagme 
/cc @dleeapho @MichaelSimons

**Comment by mmitche** [comment]
@dagood How will you identify the source sha of the dependencies?

**Comment by dagood** [comment]
In dotnet-docker's case I don't think the dependencies will come from a known Git repo so I don't expect them to have any (meaningful) commit hash. That does point out the scope is extremely limited for this feature, though. (And I'll edit out "fully".)

**Comment by dagood** [comment]
Chatted with @mmitche offline, and the idea that came out of it is to have something in dotnet-docker tooling that checks if the Darc dependencies match what's in the Dockerfiles. This could run in PR or rolling CI and on dev machines, and ideally the tooling can automatically bring the Darc dependencies back in line.

I see this is already in an epic so I'm not going to go ahead and close it myself, but I don't think the workaround is terrible.

**Comment by jcagme** [comment]
@dagood any updates on this? Do we still need this around?

**Comment by dagood** [comment]
Up to you. I'm not sure what its presence in this epic means.

**Comment by markwilkie** [comment]
Closing given that there's a path forward.  If we see that this keeps coming up, then we should definitely revisit.
