### ISSUE TITLE
Azure Package feed telemetry markers are logged on non CI builds

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#7776]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

```
C:\git\runtime6> dotnet.cmd build x.csproj
Attempting to log this client's IP for Azure Package feed telemetry purposes
Socket IP: 213.47.0.130
Client IP: 213.47.0.130
```

Apparently https://github.com/dotnet/arcade/commit/cd4a811405114fab93ff2a1939195339113a1af6 causes the IP to be logged regardless of the `-ci` flag. This is observable in dotnet/runtime local builds (for every invocation) as our dotnet.cmd/sh script calls into the changed code paths.

cc @MattGal

**Comment by MattGal** [comment]
@ViktorHofer that was as requested by @Chrisboh, is that a problem?  It shouldn't be hard to make conditional

**Comment by ViktorHofer** [comment]
Yes, we should make it only run on CI as otherwise it will be logged locally as well an just creates noise.

**Comment by MattGal** [comment]
OK, since I already have a PR touching it may as well

**Comment by MattGal** [comment]
tacked on to https://github.com/dotnet/arcade/pull/7781

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/arcade/pull/7781
