### ISSUE TITLE
TryLogClientIpAddress fails during source-build

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/arcade#7778]
Source build has a requirement to build offline.  The TryLogClientIpAddress logic which was [recently added](https://github.com/dotnet/arcade/pull/7761) appears to be [causing the offline source-builds to fail](https://dev.azure.com/dnceng/public/_build/results?buildId=1310141&view=logs&jobId=d38d06a6-3157-59e6-1a2b-006f83a0b824&j=d38d06a6-3157-59e6-1a2b-006f83a0b824&t=69d8436a-48cf-5c59-0e4a-b09e43cdd841).  

This is currently a blocking issue for source-build.

**Comment by MichaelSimons** [comment]
cc @dseefeld, @crummel

**Comment by MattGal** [comment]
@ilyas1974 I'll take this as I caused it.

**Comment by MattGal** [comment]
Merged and unblocked, closing
