### ISSUE TITLE
SourceBuild/SourceIndex jobs using hosted pool, adding hours to all builds

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#7786]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain

This pool is extremely high contention (possibly because of this very issue). My most recent build was 600th in the queue waiting for a machine. This adds _hours_ to a build that should take a few minutes, basically crippling my ability to be productive.

I tried using "sourceBuildParameters" to move it to one of our pools, but that didn't work.

**Comment by dseefeld** [comment]
> I have observed this and it is painful. @dseefeld can you comment on the move-ability of these builds?

@MattGal I'm sorry, I'm not sure what builds you're talking about here.  Can you elaborate which builds and which pool?  Thanks!

/cc @crummel @MichaelSimons

**Comment by MichaelSimons** [comment]
I'm guessing this is what @MattGal is referring to:  https://github.com/dotnet/arcade/blob/main/eng/common/templates/job/source-build.yml#L36.  I have noticed this problem and had thought about using the Helix queues but after reading https://github.com/dotnet/arcade/blob/main/Documentation/AzureDevOps/AzureDevOpsOnboarding.md#agent-queues specifically the following:

>Whenever possible, you're always encouraged to use the hosted agent pools for your builds. These don't come from the same budget as other build agents, and have far more MacOS machines than the Engineering Services team has.

I thought we should stick to using the hosted pool.  If this isn't the case, I would be happy to switch.

**Comment by MattGal** [comment]
> I thought we should stick to using the hosted pool. If this isn't the case, I would be happy to switch.

You're not wrong, but I would point out that was just written at a time when we weren't routinely going 200+ builds past the 200 build parellism-limit, which cannot be changed.  We know some repos do more builds than others and it tends to eat up capacity; this is definitely something the teams doing this are aware of and will eventually be trying to curb.

If you don't need to do authenticode signing, @ulisesh should be able to help you try out the 1ES hosted pools today, and we could use more usage of these to shake out any capacity issues there as we'll be moving to them en masse on 9/30.

**Comment by ChadNedzlek** [comment]
We should DEFINITELY change that recommendation. The hosted pools are just insufficient for our current usage, so we shouldn't be encouraging people so strong (or at all) to use them.

**Comment by ChadNedzlek** [comment]
Now that the 1ES pools are available, could we/should we move this there?

**Comment by alexperovich** [comment]
yes, we should.

**Comment by alexperovich** [comment]
Really anyone can do this. Its just finding the pool specifications and switching it to the right one. I know where the source-index pool is defined in the yaml, I would have to dig a bit to find the source build stuff. This can easily be an FR item.

**Comment by jakubstilec** [comment]
@premun Lukas missed to mention this item to me during hand over. I'm re-assigning to you.

**Comment by jakubstilec** [comment]
PR is here https://github.com/dotnet/arcade/pull/8108/files

**Comment by premun** [comment]
Yeah, the PR also didn't respect even OS (swapped Ubuntu for Windows).

I fixed it but there's no 20.04 build machine available currently and I have no idea if that matters for source build (which is run in docker?)

These are the proposed changes:
![image](https://user-images.githubusercontent.com/7013027/139666508-bf96af0f-6139-45ab-81e2-bb2dcc551d57.png)

![image](https://user-images.githubusercontent.com/7013027/139666544-62fd9c0e-4a7f-4d2a-862e-7f4e72069adf.png)

**Comment by lpatalas** [comment]
We had to revert the changes because the pools were hardcoded to public ones and this caused the internal build to fail: https://github.com/dotnet/arcade/pull/8127. I will update the yamls to use proper pools.

**Comment by lpatalas** [comment]
This is completed
