### ISSUE TITLE
Deploy build machines for PR (Linux)

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/arcade#779]
Using OS On-Boarding we need to deploy a scale set using Ubuntu that has VSTS and Docker installed on it.

/cc @ChadNedzlek

**Comment by ChadNedzlek** [comment]
This one will probably be ready Tuesday. We need to get the Llinx VSTS artifact @HaoK / @natemcmaster are PRing working. I think it's just on the cusp, but I've been fighting with the Windows one right now.

**Comment by ChadNedzlek** [comment]
Waiting for merge from ASP.NET guys. If we don't get it today, I'll see if I can take it over to get the vsts agent stuff for linux merged.

**Comment by HaoK** [comment]
Do you want to take over the PR @ChadNedzlek I'm getting new errors after merging from master

**Comment by ChadNedzlek** [comment]
Sure. I'm going to take your branch and see if I can make it work.
