### ISSUE TITLE
Add a tag to the build scale sets so that the machine cleaner doesn't touch the build machines

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/arcade#780]
Right now we have a service that detects if a machine has gone into a bad state and then will delete it.  Since the build machines we are creating right now don't use Helix they will show up as bad machines unless we add a tag to them so they get ignored.

/cc @ChadNedzlek

**Comment by ChadNedzlek** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/140?_a=overview
