### ISSUE TITLE
Accept zip files as input for XHarnessApkToTest

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/arcade#7808]
This feature is needed for leveraging `XHarnessApkToTest` for runtime tests running on mobile targets. Because for current runtime test infrastructure, there could be more than just one apk file needed to be send to the helix machine, such as test dll's and other supporting assemblies and sometimes there are multiple apk files per work item.

cc @premun

**Comment by premun** [comment]
This was previously added as a feature for Apple workloads only - https://github.com/dotnet/arcade/pull/7740

**Comment by greenEkatherine** [comment]
@premun you assigned this task to me and didn't notify that you are working on it

**Comment by premun** [comment]
@greenEkatherine ah sorry, I thought you will ping me once you're ready and I can hand it over. I had some changes from Friday and FR was calm so I just finished them.
