### ISSUE TITLE
Branch dotnet/arcade for .NET 6 servicing

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7818]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Need to do the branching exercise for net6 servicing. This is our previous info on how to do this: https://github.com/dotnet/arcade/blob/fa7990b1fa5aded5d355b46d8da47c8d8ece7c8f/Documentation/Policy/ArcadeServicing.md#mechanics-of-branching-arcade-and-services but it may be somewhat out of date since we haven't done it since .NET 5.

**Comment by mmitche** [comment]
I think we can branch at any time now. There are no critical changes that are imminent for .NET 6 at this point, so porting changes into main will be sparse.

**Comment by markwilkie** [comment]
Agreed that we can branch anytime - @ilyas1974 is this something you see fitting into FR or should I find another way?

also including @adiaaida as we'll be branching the staging pipeline at the same time.

**Comment by ilyas1974** [comment]
What is the time frame for this work item? We can do this work, but it may be a few days before we can get to this.

**Comment by markwilkie** [comment]
I don't think it's urgent....

**Comment by adiaaida** [comment]
And ask on the staging pipeline came in from @joeloff. They want to be able to publish bits for vs insertions to vsdrop as part of the currently existing infra for insert-into-vs. He is going to be working on it, and we can probably just backport the change to the release/6.0 branch once it exists.

I know that product repos have already branched, so main is now .NET 7, and arcade may want to go soon. Since the release pipeline is only releasing 6.0 releases until after GA, we (dotnet-release) may want to wait a bit longer.

**Comment by markwilkie** [comment]
Thanks @adiaaida and makes sense - we just need to make sure it happens within a reasonable time period.

**Comment by joeloff** [comment]
yup, I hope to have it done during RC2 timeframe. Right now I can publish manually, but once we hit multiple SDK bands, it's going to get worse and increase the chance of making mistakes.

**Comment by ilyas1974** [comment]
I will make sure when this issue is assigned, the IC working on it coordinates with @adiaaida. @joeloff, i anticipate we should have this completed within the next few days.

**Comment by epananth** [comment]
created https://github.com/dotnet/arcade/tree/release/6.0

**Comment by joeloff** [comment]
LOL, I just asked Matt about this a few seconds ago when I noticed it :)

**Comment by joeloff** [comment]
What's the preferred way for making fixes in 6.0 at this point? Are there automatic merges back from 6 to main or do we just pick commits from 6.0 that we want into main?

**Comment by mmitche** [comment]
We haven;t been too successful with the inter-branch merges in this repo. I suggest backporting to 6, or forward porting to main.

**Comment by joeloff** [comment]
ok, I'll make the fix in 6.0 first since this is causing pain for runtime and maui and then pick it into main

**Comment by epananth** [comment]
Update version -> PR -> https://github.com/dotnet/arcade/pull/7829

create Channel -> 
![image](https://user-images.githubusercontent.com/47157394/131914999-1b343e54-3299-454b-8a81-199b622ffbf4.png)

create default channel ->(3861) https://github.com/dotnet/arcade @ release/6.0 -> .NET 6 Eng - Validation

create Subscription -> 
![image](https://user-images.githubusercontent.com/47157394/131915173-c5a4ff7d-41f8-45bc-a5b9-09d2e49fc25a.png)

Arcade validation pr => https://github.com/dotnet/arcade-validation/pull/2517

Arcade update channel PR -> https://github.com/dotnet/arcade/pull/7832
