### ISSUE TITLE
Intermittent gather-drop failures on very large files

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7827]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://dev.azure.com/dnceng/internal/_build/results?buildId=1336807&view=logs&j=40e1e683-ea82-5be9-b25e-899b65e1c0cb&t=6e491791-6ce2-572a-3132-c49a3995e637&l=2010

I think what is happening here is that the file in question is really large and we are hitting the http client timeout. But for some reason we aren't retrying in these cases. So we probably need to ensure we retry in these cases, and also may need to raise the timeout.

**Comment by MattGal** [comment]
[Async Triage]: @ilyas1974 probably FR? but from the logs it doesn't seem like a timeout rather a malformed SAS token being appended (the *** is a secret being shaved off)

`.tar.gz***: Response status code does not indicate success: 403`

**Comment by mmitche** [comment]
> [Async Triage]: @ilyas1974 probably FR? but from the logs it doesn't seem like a timeout rather a malformed SAS token being appended (the *** is a secret being shaved off)
> 
> `.tar.gz***: Response status code does not indicate success: 403`

That's a red herring, it's not a private blob. So it tries the anon (non SAS) form first, which times out on this line: https://dev.azure.com/dnceng/internal/_build/results?buildId=1336807&view=logs&j=40e1e683-ea82-5be9-b25e-899b65e1c0cb&t=6e491791-6ce2-572a-3132-c49a3995e637&l=2010, which then causes it to try the SAS forms, which fail because they are non SAS's for that storage account.

**Comment by ilyas1974** [comment]
I think this is something we should can address in FR. While I don't think it is directly affecting the customer currently, I would rather address it now before it because a problem for them.

**Comment by MattGal** [comment]
@mmitche thanks for the reminder, at some point I knew that.  Put into FR backlog.  I think we should both reexamine whatever retry logic exists there in gather-drop as well as consider increasing the default HTTP client timeout.

**Comment by adiaaida** [comment]
It is directly affecting the release process (which counts as a customer?). I'm fine with it being in FR, but I might take a look at it tomorrow anyway

**Comment by adiaaida** [comment]
We are definitely retrying. I think we just need to up the timeout

**Comment by MattGal** [comment]
> It is directly affecting the release process (which counts as a customer?). I'm fine with it being in FR, but I might take a look at it tomorrow anyway

FR should never block someone with area knowledge from making or guiding the quick fixes.  Thanks!

**Comment by mmitche** [comment]
It's not blocking at the moment. The particular file isn't needed for signing or anything, so it's just a failure that requires manual approval after the prep stage.

**Comment by MattGal** [comment]
@adiaaida rolled out ?

**Comment by adiaaida** [comment]
As part of today's rollout, yes.
