### ISSUE TITLE
DarcLib GItHubClient needs to understand Octokit.ForbiddenException 

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#7828]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Filed after looking at https://github.com/dotnet/core-eng/issues/14238.

We already try to understand and respect when GitHub is considering our API usage excessive, with a 60s backoff on top of the existing exponential backoff, as seen here:
https://github.com/dotnet/arcade-services/blob/dd1f7ff2d64251fcd67d973ac27872c50ae28b3e/src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs#L681-L689

We should also:
- Understand Octokit.ForbiddenException and do the same thing (just adding an or)
- Consider increasing the backoff / retry
- investigate if OctoKit API returns metadata (headers, etc) that would let us be more strategic than "sleep a minute"

@ilyas1974  FR?

**Comment by riarenas** [comment]
PR https://github.com/dotnet/arcade-services/pull/1752

**Comment by MattGal** [comment]
This has been in rollout for over a month, closing... reopen if I am mistaken pls!
