### ISSUE TITLE
Add understanding of  productVersion.txt  to Helix SDK .NET SDK feature

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#7836]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Helix SDK does not use dotnet-install.* scripts, which now understand a special "productVersion.txt" to allow a mismatch between the file names inside the container and out.  Adding support for this makes those "special" .NET Core SDKs usable by Helix work items.

**Comment by dougbu** [comment]
> This issue is blocking

This issue _will_ block dotnet/aspnetcore's Helix use once we stabilize for 6.0.0. Workarounds I'm doing in the 6.0.x servicing exercise cannot be carried forward.

**Comment by MattGal** [comment]
Created https://github.com/dotnet/arcade/pull/7837

**Comment by MattGal** [comment]
Merged, moving to validate.

**Comment by MattGal** [comment]
Ported to 6.0 at Doug's request here: https://github.com/dotnet/arcade/pull/7861

**Comment by MattGal** [comment]
Seems good, will merge https://github.com/dotnet/arcade/pull/7889 and then close.

**Comment by MattGal** [comment]
feature is now in main and release/6.0, and successfully published (https://dnceng.visualstudio.com/internal/_build/results?buildId=1359695&view=logs&j=7d9eef18-6720-5c1f-4d30-89d7b76728e9&t=f511b583-5060-5810-7549-865816347c8e&l=296), closing
