### ISSUE TITLE
Regression in SourceLink Url generation when metadata is missing

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#7850]
@adiaaida FYI if you want to handle it, otherwise I think Eric's suggestion will work (setting up a thing to test that)

https://github.com/dotnet/arcade/pull/7844 introduced the change, but it's evidently possible for https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryInfo.targets#L76 a missing ScmRepositoryUrl metadata item on SourceRoot.

**Comment by MattGal** [comment]
I set up a quick repro, and thanks to some quick help from the Rainer on the MSBuild team was able to get this PR created:
https://github.com/dotnet/arcade/pull/7852/files

**Comment by adiaaida** [comment]
MSBuild is so hard! Sorry about the mess up. Matt, can you also port this to release/6.0 once it goes into main?

**Comment by MattGal** [comment]
> MSBuild is so hard! Sorry about the mess up. Matt, can you also port this to release/6.0 once it goes into main?

Created https://github.com/dotnet/arcade/pull/7854

**Comment by ericstj** [comment]
> MSBuild is so hard! Sorry about the mess up

No worries, I've hit this exact same bug before.

**Comment by MattGal** [comment]
This fix worked locally in my "artificial" setup but not in practice.  back to WIP, will handle it as fast as I can.

**Comment by adiaaida** [comment]
:(

**Comment by MattGal** [comment]
> :(

Sorry I just only fixed on location, the new one fixes both and definitely works on the arcade-validation build.

**Comment by MattGal** [comment]
I have shepherded the complete fix through on both main and release/6.0  and things look good through publishing on main.  Release/6.0 doesn't seem to be set up to automatically trigger post-merge so I manually kicked it and mentioned that to @epananth
