### ISSUE TITLE
Events from Azure DevOps delivered using unrecognizable organization name in URL

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#7851]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

As discussed in the Dev WF v-team channel, events for when pipelines have started or a being re-ran are being received containing URLs that reference the name `x-pipes` instead of `dnceng` as the organization. This is causing functionality in the Build Result Analysis check to not work on PRs that are linked to builds that contain that organization in the URL. 

I've created an IcM for Azure DevOps to fix the issue: https://portal.microsofticm.com/imp/v3/incidents/details/260345554/home

**Comment by missymessa** [comment]
Looks like the IcM was bounced to the AzDO Pipelines team. No resolution yet.

**Comment by missymessa** [comment]
Taking this with me as I come off FR and go back to my epic, since this issue directly impacts the functionality of my epic.

**Comment by missymessa** [comment]
Dev assigned to IcM verifies that this is a bug and they'll be looking into it this week.

**Comment by missymessa** [comment]
Team claimed they would get this out in a hotfix last week, but the fix is still not in. Poked on the IcM this morning to see where we're at with this.

**Comment by AlitzelMendez** [comment]
This is happening again :) I will open a new IcM

**Comment by AlitzelMendez** [comment]
IcM: https://portal.microsofticm.com/imp/v3/incidents/details/393973177/home

**Comment by AlitzelMendez** [comment]
small update: the issue has been bouncing around teams

**Comment by AlitzelMendez** [comment]
the lates update was that they were fixing this in couple of weeks, I will wait one more wait and if this is not fixed I will ping them again :)

**Comment by AlitzelMendez** [comment]
This has been fixed 🥳
