### ISSUE TITLE
Update darc dependency flow troubleshooting directions

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/arcade#7868]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

This section seems quite stale; it doesn't look like `darc get-subscription-history` exists any more.

https://github.com/dotnet/arcade/blob/7cbe70f57e3ccf97a3604b528fde7ecd6eb79573/Documentation/DependencyFlowOnboarding.md#L179-L218

What's the latest best practice here?

**Comment by jakubstilec** [comment]
[Async Triage]: @riarenas please don't you know about get-subscription-history? It isn't in our code and I also can't find it in history, but it's mentioned in documentation.

**Comment by riarenas** [comment]
I'm not familiar with get-subscription-history. I can't find any code references to it, and I'm probably not using the right keywords to search commits where it was added/removed. @mmitche Do you know if it was something we never implemented? 

It's definitely a command that doesn't exist right now, so we should update this documentation. We have no current way for customers to look into the subscription history table.

**Comment by adiaaida** [comment]
It was deleted here: https://github.com/dotnet/arcade-services/commit/b8827fd0b8dd0b9c406777d08fa90cfaab037f72#diff-d7b596f72d2e2bd09844ed34cecb5eb87dfbf11325bbe1f9cdb24222f91a1b08

**Comment by markwilkie** [comment]
Next steps?

**Comment by epananth** [comment]
https://github.com/dotnet/arcade/blob/main/Documentation/CorePackages/Publishing.md#how-to-add-a-new-channel-to-use-v3-publishing 

Need to update this also with the latest params.
