### ISSUE TITLE
[release/6.0] update the MicrosoftNetSdkWorkloadManifestReaderVersion used 

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/arcade#7880]
Currently MicrosoftNetSdkWorkloadManifestReaderVersion `6.0.100-preview.5.21254.11` is used - https://github.com/dotnet/arcade/blob/release/6.0/eng/Versions.props#L86.  In Preview 7 there were some breaking changes made with - https://github.com/dotnet/sdk/commit/b8ade8ee1c3e2470db732fb934e9c6e1feeb9d1d.  Please update Arcade to build with a newer version and address the resulting build breaks:

```
  /repos/tarball1/src/arcade.474307e526160c813c9fd58060eb8356ccca6099/artifacts/source-build/self/src/src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateWorkloadMsis.cs(124,33): error CS1061: 'BaseWorkloadDefinition' does not contain a definition for 'Platforms' and no accessible extension method 'Platforms' accepting a first argument of type 'BaseWorkloadDefinition' could be found (are you missing a using directive or an assembly reference?) [/repos/tarball1/src/arcade.474307e526160c813c9fd58060eb8356ccca6099/artifacts/source-build/self/src/src/Microsoft.DotNet.Build.Tasks.Workloads/src/Microsoft.DotNet.Build.Tasks.Workloads.csproj]
  /repos/tarball1/src/arcade.474307e526160c813c9fd58060eb8356ccca6099/artifacts/source-build/self/src/src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateWorkloadMsis.cs(124,58): error CS1061: 'BaseWorkloadDefinition' does not contain a definition for 'Platforms' and no accessible extension method 'Platforms' accepting a first argument of type 'BaseWorkloadDefinition' could be found (are you missing a using directive or an assembly reference?) [/repos/tarball1/src/arcade.474307e526160c813c9fd58060eb8356ccca6099/artifacts/source-build/self/src/src/Microsoft.DotNet.Build.Tasks.Workloads/src/Microsoft.DotNet.Build.Tasks.Workloads.csproj]
```

This is currently impacting source-build as it requires building with the latest bits.

**Comment by riarenas** [comment]
This looks like it could be part of the new operational epic, but maybe until that's in place, and since it's impacting source-build, FR?

**Comment by markwilkie** [comment]
@ilyas1974 / @MattGal - thoughts?

**Comment by MattGal** [comment]
Both PRs are merged now, and will flow with the regular dependency flow.  Having moved forward to an RTM version of the package I'm optimistically closing this, @MichaelSimons  please reactivate if I've missed something.
