### ISSUE TITLE
Upgrade version of CredScan used by SDL tooling

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#7897]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We want to upgrade the version of CredScan used by our shared SDL tooling scripts. Tracking https://securitytools.visualstudio.com/SecurityIntegration/_workitems/edit/51126 to get instructions on how to do so.

**Comment by adiaaida** [comment]
I have pinged the guardian ticket asking for more information.

**Comment by adiaaida** [comment]
Pinged the guardian team again.

**Comment by ilyas1974** [comment]
It looks like the Guardian Team replied to the issue. @adiaaida is this something you can complete or shoudl we assign it to someone who is currently on FR?

**Comment by adiaaida** [comment]
From their response, I think what we want to do is modify the tools list https://github.com/dotnet/runtime/blob/main/eng/sdl-tsa-vars.config in runtime. I can definitely take a stab at this and try to get it updated.

**Comment by ilyas1974** [comment]
Let me know if there is anything FR can do to help.

**Comment by adiaaida** [comment]
what do you mean "turn the crank"?
