### ISSUE TITLE
Preference gather-drop to pull from dotnetbuilds after storage account rework

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7909]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

After the storage account rework is done, we should preference gather-drop to pull from dotnetbuilds over dotnetcli in the interim while we are publishing to both locations.

**Comment by mmitche** [comment]
@alexperovich @adiaaida

**Comment by mmitche** [comment]
Followup from https://github.com/dotnet/core-eng/issues/14375

**Comment by riarenas** [comment]
Should this go in the dotnetbuilds epic, or the release epic?

**Comment by adiaaida** [comment]
I think the dotnetbuilds epic

**Comment by adiaaida** [comment]
Adding to the dotnetbuilds epic

**Comment by mmitche** [comment]
This is not necessary. We're also only publishing to one location.
