### ISSUE TITLE
[DarcLib] version property files should handle line endings properly

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#791]
In repos where Darc/Maestro has updated versions, one will notice that the version files always appear edited.  This is probably because there is a mix of line endings.  My hypothesis is that:
- Darc is editing and using GitHub APIs to make file modifications using CRLF
- Because no git client is involved, there is no auto-replacement of CRLF with LF before commit.

**Comment by jcagme** [comment]
Ack
