### ISSUE TITLE
[Maestro++] Remove unimplemented "NoExtraCommits" merge policy

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7926]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain: This causes a lot of confusion. 

The merge policy is available in the documentation and you can set it in a subscription via darc. However, that policy is not implemented: https://github.com/dotnet/arcade-services/blob/722d732c4c202f7f92ed96355c7d5c59b719fbf3/src/Maestro/Maestro.MergePolicies/NoExtraCommitsMergePolicy.cs#L22 so if you set it, you will have an always failing check in your dependency update PRs. 

We should delete all this code and documentation until we actually implement the policy.

**Comment by premun** [comment]
[Async triage] If it breaks people's flows because of consufion I'd say **First Responder**, otherwise Arcade technical debt and test gaps (#6811)

**Comment by riarenas** [comment]
I think it's FR as well, and I'm going to put it there. This is small enough and can get branches in a pretty bad state if they start requiring this check.

**Comment by MattGal** [comment]
This has been chilling in rollout since September, closing. @alexperovich feel free to reopen if I am mistaken.
