### ISSUE TITLE
Reduce verbosity of signing console logging in the staging pipeline

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7945]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The signing console logs are enormous. It might actually effect performance (it certainly does in my browser). Anyways, the info presented is useful and should be maintained in file form, but it doesn't need to go to the console.

Ideally the verbosity goes down to maybe just high-level status updates, like "unpacking containers", "signing round N", "signing engines", etc.

**Comment by mmitche** [comment]
> [Async Triage]: Good candidate for #7282 ? If it's actually causing more pain than Matt scrolling a lot could handle in FR.

Yes. Today I usually download the log and search through it since the console log load takes a long time (e.g. a typical log might be 120MB)

**Comment by riarenas** [comment]
It does seem most relevant to the release epic. The lack of checkboxes on the issue makes me think it doesn't quite meet the bar for FR?

**Comment by riarenas** [comment]
@adiaaida FYI

**Comment by adiaaida** [comment]
This is more SignTool related I think? All of that verbosity is coming from SignTool itself.

**Comment by adiaaida** [comment]
The change didn't work (or at least, not that I can tell), so I'm moving this back to the backlog for now.

**Comment by andriipatsula** [comment]
> Fixed in https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/19372
> 
> It was too annoying to leave until we have time to work on the epic.

@mmitche , is there anything left for us to do in scope of this issue? Can we close it?

**Comment by mmitche** [comment]
Can be closed.
