### ISSUE TITLE
Ensure wix tooling is up to date in staging pipeline

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7946]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

After changes to the wix tooling to support some key scenarios, we are using a new version in RC2+. Because we relink after signing in the staging pipeline, we need to update the version of the tooling we use there too, if it hasn't already been done transparently (I can't remember how the version is specified)

Here is the tooling package to use: https://netcorenativeassets.blob.core.windows.net/resource-packages/external/windows/wix/Microsoft.Signed.Wix-1.0.0-v3.14.0.4118.zip

**Comment by MattGal** [comment]
[Async Triage]: Small change which is necessary in Arcade which Matt has already self assigned, tossing in FR for tracking.

**Comment by adiaaida** [comment]
@missymessa who may know how we specify/get the wix version

**Comment by adiaaida** [comment]
FYI, the release repo is currently blocked on getting the latest arcade version (assuming that is how we get the WiX tools). I will look into it, but I'm hesitant to allow the update to 7.0 arcade for 6.0 releases, since there may be changes that break the pipeline.

**Comment by adiaaida** [comment]
This target is how we get the WiX tools: https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Build.Tasks.Installers/build/wix/wix.targets

**Comment by MattGal** [comment]
This was merged via https://github.com/dotnet/arcade/pull/7947 (main) and https://github.com/dotnet/arcade/pull/7948 (release/6.0), so closing this issue unless we also need this somewhere else (the wix.targets patched wasn't present <= release/5.0)
