### ISSUE TITLE
Publishing v3 doesn't publish converted portable PDBs

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/arcade#7988]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Symuploader used to do PDB conversion, then it was handled by Symstore.targets + PDB2PDB in publishing v2. I don't think there's anything doing this conversion right now. 

This issue is blocking insertions. All Portable PDBs need to be converted to Windows PDBs and indexed.

This is also a gap in validation - it verifies a file is available, not that all appropriate assets are indexed. 

cc: @epananth and @mmitche as this is affecting timely insertions.

**Comment by epananth** [comment]
In the call to publishSymbolHelper we always default this to false 
https://github.com/dotnet/arcade/blob/c6825302a5621905726f2db53cfce992558e0618/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs#L490

We will need to make sure that value can be updated by repo owners...

**Comment by epananth** [comment]
One thing I noticed this feature was turned off even in V2 https://github.com/dotnet/arcade/blob/c6825302a5621905726f2db53cfce992558e0618/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/PublishToSymbolServers.proj#L101

**Comment by hoyosjs** [comment]
That's because in-repo the conversion was done not by the uploader, but in-build: https://github.com/dotnet/arcade/blob/c6825302a5621905726f2db53cfce992558e0618/src/Microsoft.DotNet.Arcade.Sdk/tools/SymStore.targets#L70

**Comment by hoyosjs** [comment]
That design had an issue in the mono world too (we can't really do it at build time) - as we now have components that build not on windows but get inserted into VS, so PDB2PDB never ran.  cc: @directhex

**Comment by hoyosjs** [comment]
So this is really 3 issues:

- SymStore.targets + Publishing v3 don't allow for publishing the Windows PDBs needed on Watson.
- There's no conversion mechanism for VS insertions that are build on non-Windows OSs.
- Symbol validation is brittle - only verifies one item and not all necessary assets.

**Comment by mmitche** [comment]
@epananth @hoyosjs Can we just flip that switch to always be true? Are there downsides? Publishing v3 always runs on Windows so we have a point at which we can convert all PDBs.

**Comment by hoyosjs** [comment]
More CPU + time. You'd need to retune the timeouts of publishing for something like runtime

**Comment by mmitche** [comment]
@epananth Can you run some tests on runtime with the proposed changes?

**Comment by epananth** [comment]
Yes will do!

**Comment by epananth** [comment]
I'm seeing this error in promotion build -> https://dev.azure.com/dnceng/internal/_build/results?buildId=1404592&view=results 

@alexperovich is helping fix this one..

**Comment by epananth** [comment]
was able to test it against runtime -> https://dev.azure.com/dnceng/internal/_build/results?buildId=1407043&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a

**Comment by epananth** [comment]
Will get this PR out first thing in the morning

**Comment by riarenas** [comment]
Reopening since the changes for this had to be reverted.

**Comment by riarenas** [comment]
Then I guess we need to make fixes to pdb2pdb so that it doesn't result in sourcelink errors in aspnetcore?

**Comment by epananth** [comment]
@hoyosjs any update on this?

**Comment by epananth** [comment]
This has been enabled in release pipeline. So going to close this.
