### ISSUE TITLE
[darc/maestro++] Enable disabling of auto-merge for a specific PR.

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#799]

**Comment by markwilkie** [comment]
@alexperovich - is this already completed?

**Comment by mmitche** [comment]
Not required for preview2

**Comment by jcagme** [comment]
Today, PR info is just stored in the DB. Would we need to call something like `Reminders.TryUnregisterReminderAsync(PullRequestCheck);` on a given subscription id?

**Comment by alexperovich** [comment]
This should just be a comment or something someone can put in the PR that causes Maestro to not auto-merge it.

**Comment by mmitche** [comment]
This is accomplished today by marking the PR as "changes reqested"
