### ISSUE TITLE
Settle on versioning plan of record

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#8]
Seems two things should be done at a minimum:
1) Settle on long term package versioning plan
2) Settle on versioning plan for Arcade itself (especially the scripts)

The versioning scheme needs to work for our servicing scenarios

**Comment by markwilkie** [comment]
Changing title and initial description of issue.

This is also related to #48.

**Comment by markwilkie** [comment]
PR is out:  https://github.com/dotnet/arcade/pull/120
