### ISSUE TITLE
Enable disabling of auto-updates to a specific PR.

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#800]

**Comment by jcagme** [comment]
@alexperovich probably not but I kinda remember seeing work on this. Is this the case?

**Comment by alexperovich** [comment]
I think @mmitche actually fixed this issue.

**Comment by jcagme** [comment]
@mmitche can you please confirm this is done and close this if this is the case?

**Comment by markwilkie** [comment]
Closing given no response
