### ISSUE TITLE
Investigate missing symbol publishing for all repos and branches using V3

### ISSUE THREAD

**Issue by ghost** [dotnet/arcade#8015]
- [X] This issue is blocking 

This is blocking msbuild insertion into VS. 
- [ ] This issue is causing unreasonable pain

There seems to have been a regression in symbol publishing that might be related to https://github.com/dotnet/arcade/commit/a661399307c8c72eeff4e0cf6e221a78ae1ea765

The logs for the latest maestro publishing build no longer shows any indication that symbols are actually being pushed to the symbol servers:

https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=5309117&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a.

**Comment by hoyosjs** [comment]
This is actually affecting all repos - runtime is also having this issue.

**Comment by ViktorHofer** [comment]
Official builds targeting both 5.0 and 6.0 are failing for dotnet/runtime presumably because of this. Ie https://dev.azure.com/dnceng/internal/_build/results?buildId=1412894&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a

**Comment by hoyosjs** [comment]
This one is different - and new...

**Comment by ViktorHofer** [comment]
Could this be the reason for the missing symbols here: https://github.com/dotnet/runtime/issues/57259#issuecomment-940649110?

**Comment by adiaaida** [comment]
@alexperovich Is it possible something about the new publishing work you're doing affected symbols publishing?

**Comment by alexperovich** [comment]
With my publishing changes we made a specific decision to publish symbols to azure storage instead of the nuget feeds they used to be in. I didn't touch any of the code that uploads to msdl or symweb, but potentially it got disconnected somewhere. I will check.

**Comment by riarenas** [comment]
This call seems to be returning empty: https://github.com/dotnet/arcade/blob/8d89c24d4b70c6af8b8cf1d749d748464276ded4/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestBase.cs#L670-L671 so there's probably some disconnect around the feedConfigsForSymbols

**Comment by riarenas** [comment]
Newer runs are attempting to publish symbols. There's a new problem I'm seeing during symbol publishing so I opened https://github.com/dotnet/arcade/issues/8033 for that.
