### ISSUE TITLE
Suspend updates to a Pull Request when PR validation is in progress

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#802]
All updates intended for a PR that has pending checks should be held in a queue until the checks are finished.

Passed checks -> merge existing PR and create a new PR with queued updates
Failed check -> update PR with queued updates

**Comment by jcagme** [comment]
@alexperovich is there any update here? I don't think this is a ship blocker for preview is it?

**Comment by alexperovich** [comment]
This is actually fixed with my batching changes.
