### ISSUE TITLE
gpu_init.cc Passthrough is not supported, GL is disabled

### ISSUE THREAD

**Issue by donnie-msft** [dotnet/arcade#8046]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

I haven't run `darc` in many months, but today I needed to, so pulled main (6d47939a55dde813), ran `.\eng\common\darc-init.ps1`, followed by `darc authenticate`.

For some reason, I got this error on my physical machine during the `authenticate`:

> [4184:1015/103136.034:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled

![image](https://user-images.githubusercontent.com/49205731/137530088-7875efe4-3c46-4e5c-9b23-06436ff3a837.png)

The editor opened, I entered my tokens, saved/closed, then the error appeared after 30 seconds or so.

On a VM I have, I performed the same steps, using the same tokens, and it worked immediately.

Has this issue been seen before? From a quick web search, it sounds like it often occurs due to some Chromium driver issue, but I don't understand how that would be related to darc.

**Comment by adiaaida** [comment]
I don't know of anything that would prevent us from using vscode as the editor, and this code hasn't changed in a long time.

Tagging @mmitche who might be able to provide more insight
