### ISSUE TITLE
Auto-locate Dev16 VS installs as well

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/arcade#806]
One of the parameters to determine VS location is the presence of `VS150COMNTOOLS` environment variable which needs to change to accommodate Dev16 builds as well. This helps if a developer has multiple VS instances installed and wants to be able to build and deploy bits against one specific instance.

**Comment by markwilkie** [comment]
It's probably best to let the dev manage their own environment.  For official builds or CI, I would expect the image management to take care of this.  However, feel free to reopen as appropriate.

**Comment by tmat** [comment]
The build script already has logic to locate VS 2017. We should update the logic and make it work for VS 2019 as well. See https://github.com/dotnet/arcade/blob/master/eng/common/init-tools.ps1#L69

**Comment by markwilkie** [comment]
Thanks @tmat
