### ISSUE TITLE
Upgrade version of Guardian

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#8075]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

On a periodic basis, we need to intentionally upgrade the version of guardian so that we are getting the latest versions of our sdl tools. Currently we are on 0.53.3. The latest version, as far as I can tell, is 0.100.0. You can run

```
nuget.exe list Microsoft.Guardian.Cli -Verbosity Detailed -ConfigFile eng\common\sdl\NuGet.config
```

From the arcade repo root to determine the latest version of Guardian available.

**Comment by adiaaida** [comment]
@MattGal This likely should end up as part of operations work, since it's something we'll need to rev on an occasional basis.

**Comment by MattGal** [comment]
I've updated all versions in arcade release branches to latest (0.100+) as part of incidental FR work and made all branches work.  I will get this made more generic and put it in the security management epic.
