### ISSUE TITLE
[Darc] Support multiple Azure DevOps PATs

### ISSUE THREAD

**Issue by lbussell** [dotnet/arcade#8106]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Some Azure DevOps accounts cannot create PATs that work across multiple orgs in DevOps. When running `darc update-dependencies` in a repo that has dependencies from multiple orgs, darc will throw a 401 unauthorized error because you can't authenticate for multiple orgs with one PAT.

cc @crummel

**Comment by ChadNedzlek** [comment]
Does darc _need_ to use a PAT? Why not have an interactive auth mode?  That seems easier than having to plumb multiple PAT's all over the place?

**Comment by riarenas** [comment]
All the backing operations in the darclib, which the service also uses currently works with PATs. It sounds like it'd still be significant work to make that work with integrated auth throughout?

**Comment by lbussell** [comment]
> Why not have an interactive auth mode?

From a purely end-user standpoint, this could work as long as I can authenticate the tool to be used on a non-domain-joined device. I do all of my work in Linux over SSH. So opening a web browser is out of the question too unless you could remotely authenticate it from a domain-joined device.

**Comment by ChadNedzlek** [comment]
It's... rather unlikely it would work interactively on Linux, that's unfortunate.

**Comment by lbussell** [comment]
It would be possible to pull the repo on a windows machine solely for running Darc commands, though that is kind of painful.
We use darc for source-build CI on Linux machines as well, but getting all-orgs PATs isn't an issue there.

**Comment by mmitche** [comment]
Unfortunately device code doesn't work, IIRC. I think it requires that you register an Application with the AAD instance, and that application have user impersonation privileges. This requires a whole additional level of approval on the MSFT side that we are unlikely to get.

**Comment by mmitche** [comment]
@lbussell can you try out https://github.com/dotnet/arcade-services/pull/1762? I haven't quite got it completely sorted yet but it does allow for multi-org generation.

**Comment by riarenas** [comment]
The PAT tool has been merged. I'm going to close this as that should be the preferred way to create PATs for multiple orgs, and it's just not feasible for us to plumb multiple per org PATs everywhere where it would be needed.
