### ISSUE TITLE
Add razor-tooling to package gathering for .NET releases

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#8150]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The repo changed names so we need to add razor-tooling to the repos gather-drop does nuget gathering on (https://github.com/dotnet/arcade-services/blob/main/src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs#L342). Best guess is to add it to the aspnet section

**Comment by BrennanConroy** [comment]
Just to double check, this will apply to all release trains (3.1, 5.0, etc.)?

**Comment by adiaaida** [comment]
Yes

**Comment by riarenas** [comment]
This was rolled out already.
