### ISSUE TITLE
Unblock ASP.NET Core build for Tasks.Feed desktop (4.7.2) msbuild support removal 

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#8157]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain
This change: https://github.com/dotnet/arcade/pull/8132

Causes desktop msbuild users to not be able to use Tasks.Feed: 
https://dev.azure.com/dnceng/internal/_build/results?buildId=1459928&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc&t=0ae2e125-c681-5f61-9a7a-794339ba0f15

In a worst-case scenario I could have different (older) versions when targeting 4.7.2 but this is not ideal.  I could also just nerf out all the changes for Tasks.Feed but I was trying to improve the code base by having the versions be in synch (to avoid annoying mixed-loaded-assembly version stuff.

**Comment by MattGal** [comment]
@joeloff  / @dougbu FYI.

**Comment by dougbu** [comment]
My ideal choice here would be to build our WiX projects w/ `dotnet msbuild`. Is that possible w/ current WiX bits @joeloff❔

If that's not possible, suggest

1. Change Build.proj in Arcade to ignore whether `@(_SolutionBuildTargets)` is empty when deciding whether to import AfterSigning.proj and (therefore) the dotnet/aspnetcore AfterSigning.targets file. This may require a new "hook here" target that always executes -- even when `$(Build)` is `false`. May make sense to load AfterSigning.proj based only on the `$(Sign)` property and to use a new `Sign`target in that project.
    - After this is done, could change our ci.yml to separate the `Publish` step again i.e. revert dotnet/aspnetcore#37557
2. Update our ci.yml to sign in the Installers step _but_ publish in a new build step after that i.e. revert dotnet/aspnetcore#37557 and then separate signing from publication to avoid the odd noop-edness we observed before dotnet/aspnetcore#37557.
 
Both fallbacks would be relatively inefficient because the overhead of just starting `msbuild` or `dotnet msbuild` is high. If we need a fallback, would appreciate better ideas❕

**Comment by MattGal** [comment]
@dougbu I'm trying my best to not have you do anything more than take a dependency update.  Since the functionality being used her isn't BAR publishing, it should be possible to just have the Tasks.Feed package turn those pieces off for .NET 4.7.2 usage.

I have a draft PR up that should do this and my goal for tomorrow is to try out the bits published by [this build](https://dnceng.visualstudio.com/internal/_build/results?buildId=1460341&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76) on the ASPnet official build ; If this works you shouldn't have to do anything beyond proactively updating the Arcade SDK.  After discussing with @mmitche  this seems like the simplest way forward since WiX isn't likely to support core any time soon.

**Comment by joeloff** [comment]
I tried, but there are some things like the tasks that are not resolving properly. I can run `msbuild test.wixproj /p:WixTargetsPath="\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\WiX\v3.x\wix.targets"` and it builds fine, but when I run with dotnet msbuild, I get errors like

`
The "GenerateCompileWithObjectPath" task could not be loaded from the assembly \WixTasks.dll. Could not load file or assembly 'C:\WixTasks.dll'.
`

The tasks DLL is resolved through a registry search, so I'm not sure why it fails to locate the DLL when using dotnet msbuild

**Comment by premun** [comment]
> Since the functionality being used her isn't BAR publishing, it should be possible to just have the Tasks.Feed package turn those pieces off for .NET 4.7.2 usage.

Similar issue is happening here for @jakubch1 where they are interested in publishing, I think:

> D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21555.2\tools\Publish.proj(151,5): error MSB4062: The "PushToAzureDevOpsArtifacts" task could not be loaded from the assembly D:\a\_work\1\s\.packages\microsoft.dotnet.build.tasks.feed\7.0.0-beta.21555.2\build\../tools/net472/Microsoft.DotNet.Build.Tasks.Feed.dll. Could not load file or assembly 'file:///D:\a\_work\1\s\.packages\microsoft.dotnet.build.tasks.feed\7.0.0-beta.21555.2\tools\net472\Microsoft.DotNet.Build.Tasks.Feed.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. 

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5420090&view=logs&j=7e6a3fb7-dbfe-5169-4db8-92b72295ba6c&t=a5f60245-6322-5899-1632-a5d91eac5a8e

It probably started happening after they consumed #8132

From the build, I see their pipeline is executing the VS MSBuild so I guess it then only uses net472 parts:

![image](https://user-images.githubusercontent.com/7013027/140919111-f568d936-094d-418e-bb0f-e8ab78251c22.png)

**Comment by MattGal** [comment]
@jakubch1 I verified my fix unblocks you [sample build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5427609&view=logs&j=7e6a3fb7-dbfe-5169-4db8-92b72295ba6c), so updating your Arcade subscription should be all that's needed to unblock you. 

I'll park this issue in validate til I'm sure no more fallout has occurred.

**Comment by MattGal** [comment]
ASP and vs-code-coverage pipelines are green with the update, so I am optimistically closing this.

**Comment by Haplois** [comment]
Can confirm this also fixes https://github.com/microsoft/vstest build.
