### ISSUE TITLE
Darc CLI

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#816]
We should provide an entry point for devs to interact with dependency flow mechanisms and functions from a command prompt.

It should have git-like operations and options as well as "confirmation" views as when one is about to merge or rebase and can modify things that are about to be done from a view (file, console, etc.)

There is already several operations defined in https://github.com/dotnet/arcade/blob/master/Documentation/BranchesChannelsAndSubscriptions.md. We can start with these and add more on top as we see fit.

We'll also need to add the actual functionality into DarcLib so the CLI is as "dumb" as possible and only understand how to call things in DarcLib but has no notion about what is really happening.

/cc: @mmitche @dagood

**Comment by dagood** [comment]
I'm assuming this was closed since it's a near-exact duplicate of https://github.com/dotnet/arcade/issues/750. (Noting to make sure I have a pointer to follow if I get lost in the future.)

**Comment by jcagme** [comment]
Yeah, I thought there was no way to convert an issue to an epic but then I found the way of doing it so I closed this and went with the original issue (now epic)
