### ISSUE TITLE
Channel cleanup for .NET 6 Previews/RCs

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#8166]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Clean up channels and subscriptions for .NET 6 previews and RCs. Should also include the publishing constants.

**Comment by riarenas** [comment]
@mmitche I think you already did this? I don't see the preview channels anymore and https://github.com/dotnet/arcade/pull/8192 removed them from publishingConstants

**Comment by mmitche** [comment]
Ahh yeah, gone now.
