### ISSUE TITLE
Introduce channel for .NET 6 Maui

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#8169]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Add a channel (and publishing) for .NET 6 Maui preview work. Can use the same feeds as normal dotnet6.

**Comment by tkapin** [comment]
[AsyncTriage] Adding to [#14577](https://github.com/dotnet/core-eng/issues/14577); @adiaaida please shout if it doesn't belong there.

**Comment by adiaaida** [comment]
That seems like a fine place to triage for now.

**Comment by adiaaida** [comment]
Matt did this.
