### ISSUE TITLE
Support internal/alternate location runtime downloads in Helix correlation payload setup

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#8172]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Right now the helix correlation payload setup at https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/Sdk/tools/dotnet-cli/DotNetCli.targets#L38-L40 has no knowledge of additional default runtime locations (dotnetbuilds) and also can't pull in the intenral runtime download credentials+location that are passed for internal builds.

Also https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/Sdk/FindDotNetCliPackage.cs

This needs to apply to release/6.0 and main

**Comment by mmitche** [comment]
@alexperovich I think this may need to change for your work
@dougbu This is why the Helix tests are failing for internal release/6.0 builds
/cc @MattGal

**Comment by mmitche** [comment]
PR build in question: https://dev.azure.com/dnceng/internal/_build/results?buildId=1464169&view=results

**Comment by MattGal** [comment]
no objection here, I think we just need to plumb through support for secret(s) that allow accessing internal builds and make sure this only works in the Helix authenticated scenario to prevent leaking via public API.

**Comment by alexperovich** [comment]
dotnetbuilds support went in with this PR https://github.com/dotnet/arcade/pull/8162 that I am working to get into release branches. It doesn't have private feed support though.

**Comment by mmitche** [comment]
@MattGal I think we ended up implementing this at some point. Is that correct?

**Comment by MattGal** [comment]
> @MattGal I think we ended up implementing this at some point. Is that correct?

Yes, I think https://github.com/dotnet/arcade/pull/8667 does this.  I'm not sure I've had to help anyone use it though, so I'm unsure how well it works.

**Comment by dougbu** [comment]
> I'm not sure I've had to help anyone use it though, so I'm unsure how well it works.

I'm pretty sure it **Just Works:tm:** 😀

**Comment by mmitche** [comment]
BAM! Winners all around. Closing.
