### ISSUE TITLE
masemarket.net

### ISSUE THREAD

**Issue by mbfaust19** [dotnet/arcade#8178]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

**Comment by mbfaust19** [comment]
can someone help me get access to my two owned domains:

(1) masemarket.net
         &
(2) masemarket.dev

**Comment by riarenas** [comment]
@mbfaust19 this doesn't seem like an issue relevant to this repository. Feel free to add more details on why you think this belongs here.

**Comment by Chrisboh** [comment]
Updated title and comment to remove suspicious links.
