### ISSUE TITLE
Dotnet SDK / runtime acquisition doesn't handle file versioning for dotnet shared host

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#8198]
- [x] This issue is blocking
- [x] This issue is causing unreasonable pain

I'm not 100% sure if this is blocking entirely, there may be a workaround.

A repo may specify more than one runtime as well as an SDK in its global.json.  When these are installed by arcade they are mostly side-by-side, however there is one important file that is not: dotnet(.exe).

As a result, the behavior ends up being "last in wins".  The SDK is installed first, then later on runtimes are installed, overwriting (an in use dotnet).  The order in which runtimes are installed appears to be document order.
https://github.com/dotnet/arcade/blob/463f440136d4fd91b0b2e7c2dffa42edf089a685/src/Microsoft.DotNet.Arcade.Sdk/src/InstallDotNetCore.cs#L66

I think a workaround here is to always state the "latest" runtime last and add one that matches the latest SDK (if all listed runtimes are lower).  This is not ideal.  If possible, the install script should try to follow versioning rules for overlapping files, including cross-platform.

**Comment by MattGal** [comment]
Since the install script we use is the publicly visible one (https://github.com/dotnet/arcade/blob/main/eng/common/tools.sh#L271, https://github.com/dotnet/arcade/blob/main/eng/common/tools.sh#L232), we can certainly explore workarounds and drive the fix but there should probably be an issue in https://github.com/dotnet/install-scripts (@bozturk FYI)

**Comment by MattGal** [comment]
(@ericstj apologies you're likely right about the code you linked, but the code we're talking about in the related conversation is in the bash scripts / their PS1 equivalents)

**Comment by ericstj** [comment]
That task appears to do the job of ordering and then into this script: 
https://github.com/dotnet/arcade/blob/ade4f45b1fdcc2c64ab7d784b64b926475b700cb/eng/common/dotnet-install.sh#L78

Which then does call into the public script, as you mention:
https://github.com/dotnet/arcade/blob/463f440136d4fd91b0b2e7c2dffa42edf089a685/eng/common/tools.sh#L184-L266

So yes, if we can fix the public install script it would fix this problem, and we probably should since it means this problem is more wide-spread than just the arcade scenario.

I'd be fine with moving this issue to the install-scripts repo, if we think it's feasible to fix there.

**Comment by ericstj** [comment]
I noticed the script does have:
https://github.com/dotnet/install-scripts/blob/0aa4951a546b42c6a4ff5ed553065ddf0a494098/src/dotnet-install.sh#L1505-L1506
> --skip-non-versioned-files         Skips non-versioned files if they already exist, such as the dotnet executable.

That might be helpful here.

**Comment by alexperovich** [comment]
https://github.com/dotnet/arcade/pull/8208 should fix this.

**Comment by ericstj** [comment]
This might actually be specific to how the SDK was using the install script.  It might not be going through this path (which does appear to default to skip: https://github.com/dotnet/arcade/blob/977c4612a668c06232bee5acf3e9162dda31fe24/eng/common/dotnet-install.sh#L78)

Here's where the SDK calls the script without specifying skip:
https://github.com/dotnet/sdk/blob/aac033b9324f687eda51d9d7291537bb46cf3a55/eng/restore-toolset.ps1#L67

**Comment by alexperovich** [comment]
That line in sdk doesn't even use the install script in arcade, it is using the standard one. That can just pass the flag as normal.

**Comment by ericstj** [comment]
Agreed.  I opened this issue originally as a result of a problem reported in SDK issue.

**Comment by alexperovich** [comment]
This is now fixed in arcade. Every usage of the standard install scripts through arcade sets the --skip-non-versioned-files flag.
