### ISSUE TITLE
Add support to allow Helix WorkItem DownloadFilesFromResults behavior to ignore 404

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#8200]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

As originally added in https://github.com/dotnet/arcade/pull/2103, the DownloadFilesFromResults Metadata Item causes error logging in the 404 (file not found) case.  The specific custom usage done by the SuperPMI pipeline ends up getting error messages when files they want to copy to Azure DevOps artifacts are not present.

This will, unfortunately, not likely be able to differentiate _which_ files are OK to 404 and instead be for the whole work item, but this can be addressed later via msbuild or other means.

**Comment by MattGal** [comment]
@BruceForstall FYI.

**Comment by BruceForstall** [comment]
A little more context, if it helps:

Our [runtime-coreclr superpmi-asmdiffs](https://dev.azure.com/dnceng/public/_build?definitionId=1064&_a=summary) AzDO pipeline needs to upload some generated files from Helix to the AzDO artifacts for users to then download. Some of these files are only generated in some scenarios, not all the time.

The set of files to download is found [here](https://github.com/dotnet/runtime/blob/8ae135aa738b6b3c3605c8e6f26cfa99c9fedc30/src/coreclr/scripts/superpmi-asmdiffs.proj#L70) using `DownloadFilesFromResults`. One of the files listed in that `<HelixWorkItem>` is `Asmdiffs_%(HelixWorkItem.Platform)_%(HelixWorkItem.Architecture).zip`, and is only sometimes generated. Currently, we see error messages if it can't be found, which appears to cause the work item to fail the AzDO job. Example log for that is [here](https://dev.azure.com/dnceng/public/_build/results?buildId=1476754&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=486c0909-f67d-5748-80b3-bb1d531e7b43).

**Comment by BruceForstall** [comment]
cc @kunalspathak

**Comment by tkapin** [comment]
One thought on the proposed implementation. Although ignoring non-existent files would be opt-in, the ambiguity with real 404s worries me. Another solution might be creating list(s) of the files (a.k.a. manifests) in scope of the task as they get created, upload them to results and then use them to determine which files to download. Helix SDK could be then extended by something like <DownloadFilesFromResultsByManifest>manifest_%(HelixWorkItem.Platform)_%(HelixWorkItem.Architecture).txt</DownloadFilesFromResultsByManifest> to get the exact list of files.

**Comment by markwilkie** [comment]
Is there a recommend for next steps?

**Comment by alexperovich** [comment]
As this is a warning, we should add warning codes to our warnings. With codes added customers can add /NoWarn:<code> in the msbuild cmd line to ignore this specific warning if they wish.

**Comment by BruceForstall** [comment]
We've worked around this issue (in https://github.com/dotnet/runtime/pull/62368) by simply always creating all files, even if the files are actually empty, so I'm not going to address this in Helix (which is a complex and foreign (to me) dev experience).
