### ISSUE TITLE
Remove CI build IP logging behavior 

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#8205]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Tracks removing changes from https://github.com/dotnet/core-eng/issues/13691 - this was  done when we were hunting down problems with Azure Devops NuGet Package feeds, and while it did help us figure out the issues seen with the Azure Front Door service, it has not been useful and the URL in question is not guaranteed to last.  As such, I am opening this to remove the logging.

**Comment by MattGal** [comment]
https://github.com/dotnet/arcade/pull/8207

**Comment by MichaelSimons** [comment]
Will this get backported to 6.0?

**Comment by MattGal** [comment]
> Will this get backported to 6.0?

Sure, it's a slow week :)

**Comment by MattGal** [comment]
This is merged everywhere it existed, closing.
