### ISSUE TITLE
Gather-drop broken for dotnetbuilds asset locations

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#8225]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

AssetLocations using dotnetbuilds no longer end with index.json. However, gather-drop's code relies on locations ending with index.json to decide that they are blob storage locations. Otherwise, it determines that the locations are "unknown" and refuses to download the files.

We should either use the AssetLocation's type, or remove the code from IsBlobFeedUrl that expects it to end with index.json.

This is currently blocking all Validate-DotNet runs and will soon block all Stage-DotNet runs.

/cc: @alexperovich @mmitche

**Comment by adiaaida** [comment]
I haven't put this in an epic yet, as I think it could either go in Alex's epic or in FR.

**Comment by riarenas** [comment]
This was rolled out.
