### ISSUE TITLE
Latest aks.ms link generation for blob files not happening

### ISSUE THREAD

**Issue by jander-msft** [dotnet/arcade#8235]
- [x] This issue is blocking
- [ ] This issue is causing unreasonable pain

In the latest successful dotnet-monitor build, the latest aka.ms links were not generated for the files published to blob storage during the Maestro promotion: https://dev.azure.com/dnceng/internal/_build/results?buildId=1493217&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a

The prior successful build did correctly generate the latest aka.ms links: https://dev.azure.com/dnceng/internal/_build/results?buildId=1472950&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a

Example links that should be created/updated:
```
    aka.ms/dotnet/diagnostics/monitor7.0/daily/dotnet-monitor.nupkg.version -> https://dotnetcli.azureedge.net/dotnet/diagnostics/monitor7.0/daily/dotnet-monitor.7.0.0-alpha.1.21566.1.nupkg.version
    aka.ms/dotnet/diagnostics/monitor7.0/daily/dotnet-monitor.nupkg.buildversion -> https://dotnetcli.azureedge.net/dotnet/diagnostics/monitor7.0/daily/dotnet-monitor.7.0.0-alpha.1.21566.1.nupkg.buildversion
```

Without the link generation/update, we are unable to flow the dotnet-monitor version to the dotnet-docker repo for nightly ingestion.

**Comment by riarenas** [comment]
@adiaaida Could this be related to https://github.com/dotnet/arcade/commit/97463777ee9a8445d4a4c5911ede0f0cd71fa8aa?

**Comment by adiaaida** [comment]
Looking. It looks like the short url prefix disappeared, which is probably related

**Comment by adiaaida** [comment]
PR to fix: https://github.com/dotnet/arcade/pull/8236

**Comment by adiaaida** [comment]
PR has been merged.

**Comment by adiaaida** [comment]
I believe this has been fixed based on this build of dotnet-diagnostics: https://dev.azure.com/dnceng/internal/_build/results?buildId=1496668&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a&l=434

Closing. Please let me know if you see any links not being generated in dotnet-monitor
