### ISSUE TITLE
Add Visual Studio 2022 support for loading bundleproj and sfxproj project files.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/arcade#8256]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Currently there is no Visual Studio extension for loading the ``*.bundleproj`` and the ``*.sfxproj`` files directly from dotnet/runtime. While on command line it will build, people like me would like to be able to load them like we can with Rider inside of Visual Studio to make changes to settings on them as needed much easier.

As such I feel like something like this is needed so that way those who use arcade can load the projects needed that will use arcade to build their installers.

Note: Not only does just dotnet/runtime use arcade to build installers, but other projects in the foundation *might* use it as well for installers (Windows Desktop Runtime for example), or even 3rd parties will use it just so they can save time with the complexity of making an msbuild sdk that will generate installers exactly the way arcade does and so they use arcade instead.

No matter what their reason for using arcade, users really do need to be able to load their installer projects inside of Visual Studio that are built entirely with the arcade like how the command line builds can load them.

**Comment by markwilkie** [comment]
@marcpopMSFT - is this something best routed to VS or do we have context?

**Comment by marcpopMSFT** [comment]
I'm not quite sure what work is required to enable this. @tmeschter , do you know if there is project system work required to enable this or something else?

**Comment by AraHaan** [comment]
I think there is work that needs to be done for this yes, in this case I think it can be done with a project type extension if I remember right that basically allows to set the icon Visual Studio will display for the project type as well as possibly the capabilities that can be done in Visual Studio (I think that is how it works).

**Comment by tmeschter** [comment]
Yes, there would need to be some project system work. At a minimum we need to set up the mappings from the .bundleproj and .sfxproj extensions to the correct project system in VS; I believe this is handled by registry keys.

There is likely work beyond that, though. I would need to know more about what .bundleproj and .sfxproj represent and how they differ from .csproj. It may not be as simple as opening them with the .NET Project System.

**Comment by AraHaan** [comment]
sfxproj is for making msi installers on windows, or macos pkg installer packages (intermediate ones) which then gets referenced in bundleproj projects to produce the final (shipping) installers.

**Comment by markwilkie** [comment]
Thoughts on next steps @tmeschter ?

**Comment by tmeschter** [comment]
Those sound fundamentally different than C# or VB projects, so trying to support them with the .NET Project System is not the right approach. Really what we're talking about is creating a completely new project system (maybe two?) that understands the specifics of those projects and how to represent them in VS.

There is some documentation about how to create a new project system built on top of CPS (the Common Project System) at https://github.com/microsoft/VSProjectSystem -- the documentation is old but fundamentally sound. But I would recommend engaging the CPS team directly.

**Comment by markwilkie** [comment]
I'm closing this for now @AraHaan - but am more than happy to re-open if you think we should.

also....thanks a ton for your involvement - we really appreciate it.
