### ISSUE TITLE
[Maestro++/Darc] Maestro service not refreshing certain secrets automatically from key vault

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#8272]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain

After cycling of the github application secrets, The maestro service didn't refresh the values it had cached, and a service restart was required to pick up the new values. These secrets are supposed to be refreshed by the service host every 5 minutes:https://github.com/dotnet/arcade-services/blob/722d732c4c202f7f92ed96355c7d5c59b719fbf3/src/Microsoft.DncEng.Configuration.Extensions/ServiceConfigurationExtensions.cs#L53

We should try and find out why this automatic refresh didn't work in this case.

**Comment by riarenas** [comment]
Maybe 5th time's the charm. Going to try and take a look at this.

**Comment by riarenas** [comment]
Haven't been able to look at this due to incoming issues. Sending back to backlog for now.

**Comment by ChadNedzlek** [comment]
Any insight @alexperovich ?

**Comment by alexperovich** [comment]
This is the issue that just won't die. Every thing I have looked at suggests that the refresh should happen correctly. We even did a test locally by triggering the rotation and the values loaded correctly in that case.

**Comment by ChadNedzlek** [comment]
@riarenas do you know an example of a secret that didn't rotate? So we can see if there is some difference for that one that's causing a problem?

**Comment by riarenas** [comment]
Yes. The latest time it happened was when I rotated the github application secrets: https://github.com/dotnet/arcade-services/blob/d40ac7f8c1509290da13b98134701cf498510504/.vault-config/shared/maestro-secrets.yaml#L1-L6

**Comment by ChadNedzlek** [comment]
Apparently that secret is... 5 secrets?  Do you know which specific one in which service didn't refresh?

**Comment by ChadNedzlek** [comment]
I guess and what the symptoms were. It's a bit hard to track down without a bit more information.

**Comment by riarenas** [comment]
https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAxXLMQ6DQAwEwJ5XrCh5QjraFEkR5QFgr5ITkX3yGUGRxwPtSMNdWLO4NfyxfRnEAHHLqZzUv417pSQVjPBADRe2VuyDSa53w4j76%252FnAxhnpC%252B3s609hnpgJpbhS%252B%252B4Allh9fmoAAAA%253D/timespan/2021-12-16T21%3A41%3A05.000Z%2F2021-12-21T21%3A41%3A05.000Z

This is the error we were getting after the secrets were rotated in dec 17th. Nothing in maestro was working until we rebooted all the nodes.

**Comment by ChadNedzlek** [comment]
Thanks. Looks like it's the same 'ol IOptions problem (IOptionsMonitor is needed for anything that might change)

**Comment by ChadNedzlek** [comment]
Arcade part of the problem: https://github.com/dotnet/arcade-services/pull/1807

Helix incoming...

**Comment by ChadNedzlek** [comment]
The helix part of this is a lot more intense.  Helix put a lot of bad objects directly into the service providers (like a pre-authed HttpClient or something).  Ripping those out into updatable objects is messy, and I'm hoping I don't break something.  We'll have to keep a eye on helix when we roll this out.

**Comment by MattGal** [comment]
@ChadNedzlek any update on this issue?  has been in the rollout column 7 months now.

**Comment by MattGal** [comment]
@ChadNedzlek any update on this issue?  has been in the rollout column 7 months now.

**Comment by ChadNedzlek** [comment]
Just gonna assume it's done then. :-)
