### ISSUE TITLE
Allow to manually override VersionSuffix in eng\Versions.props.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/arcade#8282]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

I noticed when looking in the arcade sdk code in where it sets the VersionSuffix, there is no way to force it to use a specific suffix instead of what it calculates.

As such I feel like a new property ``OverrideVersionSuffix`` for Versions.props is needed to where one can "override" it if they wanted to.

**Comment by markwilkie** [comment]
Part of the value of Arcade is that things like versions are consistent.  (see https://github.com/dotnet/arcade/blob/main/Documentation/Policy/DefaultsGuidance.md for a bit more context)

Is there a scenario you're thinking of?

**Comment by AraHaan** [comment]
For example one might want this sort of setup as well (me on my CI's) ``preview.$(GITHUB_RUN_NUMBER).$(BUILD_RERUN_COUNT)`` where on github actions I manually set ``BUILD_RERUN_COUNT`` from the ``github`` object that holds the rerun count.

Other people might want to do similar things as well using the CI run numbers as part of the version suffix.

**Comment by markwilkie** [comment]
Hi @AraHaan - my sense is that value here does not quite outweigh the increased inconsistency and possible "states" we'd need to keep track of.  I'm closing for now, but I'm happy to revisit.
