### ISSUE TITLE
Gather drop incorrectly populates the sympkgs-all.txt

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#8286]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In this staging build, the symbol nupkg file was generated improperly by gather-drop. It appears to be missing a number of files (most symbol nupkgs, see \\vsufile\patches\sign\NET\NET_CORE\6.0.1\publish_files\nuget\nupkgs\runtime\packages) https://dev.azure.com/dnceng/internal/_build/results?buildId=1483150&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by adiaaida** [comment]
@mmitche can this be closed now?
