### ISSUE TITLE
Investigate issues with publishing pipeline

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#8318]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

There are a few ongoing issues occurring during publishing:

* Checksums are sometimes going to the wrong storage account container:
https://dev.azure.com/dnceng/internal/_build/results?buildId=1538636&view=results published its checksums to the `public` container, but https://dev.azure.com/dnceng/internal/_build/results?buildId=1538476&view=results and https://dev.azure.com/dnceng/internal/_build/results?buildId=1538636&view=results published them to public-checksums. The correct location is `public-checksums`

* There are multiple failures in the publishing pipeline https://dev.azure.com/dnceng/internal/_build?definitionId=750&_a=summary&statusFilter=failed that are not getting reported to the originating builds that trigger the publishing.

**Comment by alexperovich** [comment]
I'll take this.
