### ISSUE TITLE
Explore moving some of the installer script logic into the common library

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#833]
Xcopy-able dependency installers will usually be the same:
* Point me to the file I need to download
* Download and extract in the requested location

We might be able to provide a CreateInstaller function in the common library that does this just given the tool name and version.

For tools that need a more complex installation. They will need to be written separately.

**Comment by markwilkie** [comment]
@jonfortescue - perhaps you made some forward progress here because of python?

**Comment by jonfortescue** [comment]
I didn't stick it in the common library, but just created a generic `install-tool.ps1` that does this. So, yes?

**Comment by markwilkie** [comment]
Cool - @riarenas, thoughts on putting this into the common library?

**Comment by riarenas** [comment]
I want to see if I can come up with something to unify linux and windows. The current approach for windows is an improvement in terms of usability, but it's worse for tool discoverability and is much less flexible. I'll move this into breakdown to come up with a plan.

**Comment by jcagme** [comment]
Are there any updates @riarenas ?

**Comment by riarenas** [comment]
I believe the wok to be done here is:

* Windows:
  * Move the current install-tool.ps1 to the common library.
  * Create wrapper scripts for install-python and install-cmake that pass the download location to install-tool

* Linux:
  * Write a linux-y version of install-tool in the common library that helps with things such as getting args.
  * Change the current install-cmake.sh to use the new common file.

* Update docs.

**Comment by jcagme** [comment]
Thanks @riarenas. Is this something that should still be in your plate?

**Comment by riarenas** [comment]
Yeah, the changes aren't too big, I can take fixing this up.

**Comment by riarenas** [comment]
Clearly @riarenas didn't add this to his plate.

**Comment by jonfortescue** [comment]
Given that we're no longer investing in native tools bootstrapping, I'm closing this.
