### ISSUE TITLE
Helix SDK AdditionalDotNetPackage should allow download of packages from specified locations

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#8336]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Mainly for internal build scenarios where an sdk or runtime that isn't yet publicly available needs to be downloaded. This should allow passing additional storage accounts and authentication via a SAS for download.

**Comment by BrennanConroy** [comment]
Ideally this would be fixed in the 6.0 branch

**Comment by dougbu** [comment]
I suspect src\Microsoft.DotNet.Arcade.Sdk\src\InstallDotNetCore.cs should lend some of its expertise to src\Microsoft.DotNet.Helix\Sdk\FindDotNetCliPackage.cs but am not positive.

In the meantime, I hard-coded the runtime version we test against in Helix jobs for now.

May look more and duplicating parts of src\Microsoft.DotNet.Helix\Sdk\tools\dotnet-cli\DotNetCli.* to enable the other (`@(HelixCorrelationPayload)`) workaround. I didn't get the pattern right in my initial attempts.

**Comment by ilyas1974** [comment]
Unfortunately, because of a number of high priority issues, moving this back to the back log.

**Comment by dougbu** [comment]
/fyi @Pilchie this means a workaround we have in place that's (at best) iffy will remain for the foreseeable future. ☹️ See eng/helix/helix.proj in dotnet/aspnetcore#40073

**Comment by Pilchie** [comment]
This will presumably be an issue for Winforms/WPF/Windows Desktop if they start using Helix as well right?  Because they will also want to install runtime packages?

**Comment by markwilkie** [comment]
@ilyas1974 - thoughts on how long you anticipate this being on the backlog?  Meaning, once the current "storm" of FR issues subsides, do you anticipate putting this back on?

**Comment by dougbu** [comment]
> Because they will also want to install runtime packages?

Depends on how those repos choose to get the runtimes. If they use something like our old (worse) hacks and install on each Helix agent i.e. ignore the Helix SDK feature, they'll be 🆗 They'll also be 🆗 if they use the Helix SDK to install only a .NET SDK (that's not an MSRC SDK).

**Comment by ilyas1974** [comment]
I have asked @ulisesh to look at this.

**Comment by ulisesh** [comment]
I'm leaving FR tomorrow, @jonfortescue can you take this issue?

**Comment by jonfortescue** [comment]
@ulisesh yep, absolutely.

**Comment by chcosta** [comment]
Status update: still writing the tests for this.  Nothing blocking at the moment apart from finding cycles to focus on this.  I expect to have the tests written in the next few days and then I can focus on the particular change this issue is focused on.

**Comment by dougbu** [comment]
I suspect we were all slow to respond @chcosta because we have no concerns. Just making it clear that's my perspective 😺

**Comment by chcosta** [comment]
@mmitche , it occurs to me that the above implementation would open this up to providing arbitrary package sources. Do you see that as a concern? Ie, should I be more restrictive /explicit about the package sources?

**Comment by mmitche** [comment]
Since this is only .NET runtimes and SDKs, I don't see this as a concern at this point. I don't expect repository owners to go finding random .NET packages on the internet. Also, potential inputs will eventually be enforced on a network level, which will reduce the risk.

**Comment by chcosta** [comment]
Merged the fix for this (#8667) into main.  Does this need to be ported to some other branch as well?

**Comment by dougbu** [comment]
> Does this need to be ported to some other branch as well?

Pretty please take this back to release/6.0. That's where we actually workaround the root problem.
