### ISSUE TITLE
dotnetcli.blob.core.windows.net not reachable from IPv6 only network

### ISSUE THREAD

**Issue by erwinwolff** [dotnet/arcade#8341]
Hi Team,

More a infrastructure issue than a technical one, but dotnetcli.blob.core.windows.net not reachable from an IPv6 only network.

**Comment by alexperovich** [comment]
This is because azure blob storage doesn't support IPv6 as far as I can tell. If you use the CDN dotnetcli.azureedge.net that does have an IPv6 address from what I can tell.

**Comment by adiaaida** [comment]
Since this is an issue with blob storage, not arcade scripts, we are closing this.
