### ISSUE TITLE
Make it easier to override default exe bundle installer background image by splitting it's value into a settable msbuild property.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/arcade#8352]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Currently this https://github.com/dotnet/arcade/blob/7097001cd87357ebc6fb82f3c7a801efeed70e3f/src/Microsoft.DotNet.Build.Tasks.Installers/build/wix/wix.targets#L188 sets the candle variable directly which if a 3rd party is using it to create installers (which sets the Company and Authors value on the installer information to something other than Microsoft / .NET Foundation) wants to change the background image, one must then somehow override it (with another wix file). The issue is, what if they want to override it without technically including the default one in the bundle as well or even have to manually specify all the items that are in the wix source file that lives in the Installers package not to mention what if the values in the file in the package just ends up overwriting the ones they try to manually provide. As such I think the best aproach to this is to extract this value to an msbuild property that defaults it to the current value if the sdk sees it not being set by the project themselves. This would mean no breaking change to Microsoft or even .NET Foundation projects at all and helps out 3rd party people who use arcade to make 3rd party installers as well out as well making the experience a win for everyone.

For this I think an msbuild property of ``WixInstallerBackgroundFile`` (or some other name if it conflicts with something in wix like that) as an msbuild property name would be a best thing to define for holding the value to pass to the candle variable.

**Comment by riarenas** [comment]
@NikolaMilosavljevic FYI

**Comment by NikolaMilosavljevic** [comment]
@AraHaan, the change in your PR is straightforward. Have you tried building dotnet/runtime installers to confirm that there are no regressions?

I've added myself as PR reviewer.

**Comment by AraHaan** [comment]
> @AraHaan, the change in your PR is straightforward. Have you tried building dotnet/runtime installers to confirm that there are no regressions?
> 
> I've added myself as PR reviewer.


I have not yet found out how to use it against dotnet/runtime locally with the local package build of this.

**Comment by NikolaMilosavljevic** [comment]
> > @AraHaan, the change in your PR is straightforward. Have you tried building dotnet/runtime installers to confirm that there are no regressions?
> > I've added myself as PR reviewer.
> 
> I have not yet found out how to use it against dotnet/runtime locally with the local package build of this.

It would be the same way you tested your installers.

If your local Arcade repo is in `d:\git\arcade` you can use the following command to tell the build to use local changes instead of the downloaded package:

`set MicrosoftDotNetBuildTasksInstallersMSBuildDir=d:\git\arcade\src\Microsoft.DotNet.Build.Tasks.Installers\build\`

**Comment by AraHaan** [comment]
Ah, thanks

**Comment by AraHaan** [comment]
Building with it now. It *should* work however because I did test it without it being set manually on my codebase, and then after that with it set.

**Comment by AraHaan** [comment]
Yep, I have verified that dotnet/runtime still works with the changes.
