### ISSUE TITLE
arcade-validation broken due to templates change

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#8368]
- [X] This issue is blocking 
This blocks validation and promotion of arcade
- [ ] This issue is causing unreasonable pain

https://github.com/dotnet/arcade/pull/8344 changed the setup-maestro-vars template from job template to a steps template. This breaks arcade-validation's publishing validation job when it tries to use the template during a stage: https://github.com/dotnet/arcade-validation/blob/b06c3ea7c155e01d8db898edb1a188b0c4d02799/azure-pipelines.yml#L259

**Comment by riarenas** [comment]
FYI @mmitche I'll see if I can just change arcade-validation's yaml to use the new steps template here.

**Comment by mmitche** [comment]
I did some searching and found a couple places (pool provider) that use the template explicitly, but this should be about it

**Comment by riarenas** [comment]
PR with the fix: https://github.com/dotnet/arcade-validation/pull/2858

**Comment by riarenas** [comment]
Finally managed to unblock this: https://dev.azure.com/dnceng/internal/_build/results?buildId=1564021&view=results
