### ISSUE TITLE
Allow explicitly including symbol files in non-symbol packages

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/arcade#8374]
Both the `NuGetPack` task and `sharedfx.targets` always filter out symbol files from non-symbol packages, so if a project explicitly includes a symbol file as a `File`/`FileToPackage`, it is still excluded from the implementation package
https://github.com/dotnet/arcade/blob/8cd73087e3a24ab17b6b2ae000aef98b9aec3e2f/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs#L22-L23
https://github.com/dotnet/arcade/blob/8cd73087e3a24ab17b6b2ae000aef98b9aec3e2f/src/Microsoft.DotNet.SharedFramework.Sdk/targets/sharedfx.targets#L136-L138
https://github.com/dotnet/arcade/blob/8cd73087e3a24ab17b6b2ae000aef98b9aec3e2f/src/Microsoft.DotNet.SharedFramework.Sdk/targets/sharedfx.targets#L542

In some cases - for example, static native libraries on Windows - implementation packages may want to include symbol files. There should be a mechanism to override these default exclusions for a specific item, such that a symbol file can be explicitly included.

Required for https://github.com/dotnet/runtime/issues/63602

**Comment by markwilkie** [comment]
Is the end result of this that we're missing symbols?  (trying to understand better the end customer impact)

**Comment by elinor-fung** [comment]
The end result for the customer is:
- Linker warnings
  - [LNK4099](https://docs.microsoft.com/cpp/error-messages/tool-errors/linker-tools-warning-lnk4099) for every object file in the static library whenever they try to build. They would have to configure their link command to suppress this via `/ignore:4099`. For the static lib mentioned in https://github.com/dotnet/runtime/issues/63602, the warnings would be something like:
  ```
  libnethost.lib(nethost.cpp.obj) : warning LNK4099: PDB 'libnethost.pdb' was not found with 'libnethost.lib(nethost.cpp.obj)' or at 'C:\repos\Cpp\x64\Debug\libnethost.pdb'; linking object as if no debug info
  libnethost.lib(utils.cpp.obj) : warning LNK4099: PDB 'libnethost.pdb' was not found with 'libnethost.lib(utils.cpp.obj)' or at 'C:\repos\Cpp\x64\Debug\libnethost.pdb'; linking object as if no debug info
  libnethost.lib(fxr_resolver.cpp.obj) : warning LNK4099: PDB 'libnethost.pdb' was not found with 'libnethost.lib(fxr_resolver.cpp.obj)' or at 'C:\repos\Cpp\x64\Debug\libnethost.pdb'; linking object as if no debug info
  libnethost.lib(trace.cpp.obj) : warning LNK4099: PDB 'libnethost.pdb' was not found with 'libnethost.lib(trace.cpp.obj)' or at 'C:\repos\Cpp\x64\Debug\libnethost.pdb'; linking object as if no debug info
  libnethost.lib(pal.windows.cpp.obj) : warning LNK4099: PDB 'libnethost.pdb' was not found with 'libnethost.lib(pal.windows.cpp.obj)' or at 'C:\repos\Cpp\x64\Debug\libnethost.pdb'; linking object as if no debug info
  libnethost.lib(fx_ver.cpp.obj) : warning LNK4099: PDB 'libnethost.pdb' was not found with 'libnethost.lib(fx_ver.cpp.obj)' or at 'C:\repos\Cpp\x64\Debug\libnethost.pdb'; linking object as if no debug info
  libnethost.lib(longfile.windows.cpp.obj) : warning LNK4099: PDB 'libnethost.pdb' was not found with 'libnethost.lib(longfile.windows.cpp.obj)' or at 'C:\repos\Cpp\x64\Debug\libnethost.pdb'; linking object as if no debug info
  ```
- Missing symbols
  - The customer's binary will be missing debug information in their PDB for the static library being consumed

**Comment by adiaaida** [comment]
@mikem8361 Can you weigh in on this?

**Comment by mikem8361** [comment]
I don't know how creating a PDB for a .lib works.  Most of this issue looks like generating the PDB so the symbol uploader can upload it? Or so the devs that are using libs like libnethost.lib can create a PDB?

**Comment by elinor-fung** [comment]
This is for devs consuming static libs like `libnethost.lib`. The linker pulls in the static lib and looks for a corresponding PDB next to that lib, so having the symbols uploaded to a symbol server does not help in this case. They will get a PDB (for their binary that is consumbing the static lib), but that PDB will not have debug information for libnethost. They will also hit the warning [LNK4099](https://docs.microsoft.com/cpp/error-messages/tool-errors/linker-tools-warning-lnk4099) that I mentioned above and have to suppress it vie `/ignore:4099`.

We already generate the PDB for the static lib (libnethost.lib), but we currently don't have it shipped because it gets excluded from the non-symbol packages.

**Comment by markwilkie** [comment]
This seems like it's perhaps a build thing then?  Sorry, not 100% sure how best to help here @elinor-fung

**Comment by elinor-fung** [comment]
The request is that the tasks and targets in arcade (the `NuGetPack` task, the [`CreatePackage` target using that task](https://github.com/dotnet/arcade/blob/ca8ebd397fffb437282c32f4be79c74ac21c2724/src/Microsoft.DotNet.Build.Tasks.Packaging/src/build/Packaging.targets#L1257), and the items in `sharedfx.targets` mentioned in the description) provide some mechanism for consumers to indicate that a PDB should be included in the normal/implementation package - not just the symbols package.

Right now, even if we explicitly specify that a `.pdb` file should be included in a package (like the runtime repo does for its  [`Microsoft.NETCore.DotNetAppHost` package](https://github.com/dotnet/runtime/blob/a847ddfea5265218afab95adb7fd5eb3730091dc/src/installer/pkg/projects/Microsoft.NETCore.DotNetAppHost/Microsoft.NETCore.DotNetAppHost.pkgproj#L25)), that `.pdb` file is automatically filtered out by the task/targets in arcade and not included in the implementation package. Because we don't have a mechanism to indicate that the `.pdb` really should be included and not filtered out, that results in the experience mentioned in https://github.com/dotnet/arcade/issues/8374#issuecomment-1035249340 for developers trying to consume one of the static libraries in the implementation package.

**Comment by adiaaida** [comment]
@ericstj Do you know the best way to update the NuGetPack task for Elinor?

**Comment by ericstj** [comment]
I believe that task has 
https://github.com/dotnet/arcade/blob/8cd73087e3a24ab17b6b2ae000aef98b9aec3e2f/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs#L76-L81

Which is controlled by this property:
https://github.com/dotnet/arcade/blob/ca8ebd397fffb437282c32f4be79c74ac21c2724/src/Microsoft.DotNet.Build.Tasks.Packaging/src/build/Packaging.targets#L1262

For most of our packages we don't want to do this - we instead want customers to get symbols from the symbol server.  It sounds like @elinor-fung has a scenario to include this -- packaging native static libraries.   We haven't really designed the packaging tasks to support this scenario (nor does the built in NuGet pack task) but it may work.

**Comment by elinor-fung** [comment]
Thanks @ericstj - I had tried `IncludeSymbolsInPackage=true` before, but that included all symbols in the regular package (rather than some specific one). I saw there is `AdditionalLibExcludes`, but it looks like that is ignored if `IncludeSymbolsInPackage=true`. Maybe the thing here is that `AdditionalLibExcludes` (only - not the default `_libPackageExcludes`) should still be used in this case? 

> For most of our packages we don't want to do this - we instead want customers to get symbols from the symbol server.

For sure. I'd be on board with: here is a way to do it - may not be 'nice', but serves the purpose for the hosting / static lib use case. But I couldn't figure out how to do it in the current infrastructure. I'm also happy to make whatever change might be needed in the task if what I said about using `AdditionalLibExcludes` is reasonable, or if someone can point me at what would be reasonable.

**Comment by elinor-fung** [comment]
I also want to clarify that the `NuGetPack`/`Packaging.targets` is separate from `sharedfx.targets` and we're looking for a mechanism to include a symbol file - specific one(s), not all symbols - in both cases.

**Comment by ericstj** [comment]
We're trying to move off of the PKGPROJ infrastructure completely so we should really avoid much investment here.  I'm not too familiar with what `sharedfx.targets` uses -- is that using the pack task from this repo or is it using the official nuget pack task?  cc @jkoritzinsky @NikolaMilosavljevic
