### ISSUE TITLE
Add publishing for .NET 6.0.3xx SDK channels

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#8390]
- [X] This issue is blocking 

Installer repo is trying to publish to this channel
- [ ] This issue is causing unreasonable pain

Add publishing configuration for the .NET 6.0.3xx SDK and internal channels.

**Comment by TanayParikh** [comment]
> Once arcade self-updates through dependency flow it will be possible to publish to the 6.0.3xx SDK channels

@riarenas when would that be / is there a way I can check if it has happened? Just [tried](https://github.com/dotnet/razor-compiler/pull/55) triggering an arcade update to `dotnet/razor-compiler` without much luck.

**Comment by riarenas** [comment]
I will update this issue when we have received the correct update.

**Comment by riarenas** [comment]
I can probably trigger an update manually in the next few minutes as it looks like we have a good window to promote arcade right now.

**Comment by riarenas** [comment]
Once https://github.com/dotnet/arcade/pull/8398 is merged and mirrored to the internal repo this should be unblocked

**Comment by riarenas** [comment]
This should be working now, already verified with the installer build that first saw the issue: https://dev.azure.com/dnceng/internal/_build/results?buildId=1566018&view=results. @TanayParikh you should be able to retry any builds that saw the issue now. You don't need to wait for any arcade updates as the publishing pipeline only depends on the arcade repo itself.
