### ISSUE TITLE
Auto-PR requests

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#841]
I've onboarded corefx to get auto-updates and it has been working but there are a few feature requests that I'd like to add.

1) Can we have the PR message either list no dependencies or only the applicable dependencies in the description? I'd like to eliminate noise.
2) Can we have some way to tag a team or set of github users in the PR description so folks can keep an eye on these PRs?
3) For the Auto-Merge Status can you please list the failed CI legs with a link to the CI logs?
4) Branch used for the PR does the branch need to be made in the main repo? Is there any easy way to make the branch in a fork? 
5) For the commit messages can we add a little better description then "Update version files"? I fear a time when we have hundreds of these comments and no easy way to find a particular one without opening each commit manually.

**Comment by jcagme** [comment]
Actually we could use 2 when we have notifications in place

**Comment by markwilkie** [comment]
@alexperovich - wondering if you ended up fixing this already.

**Comment by alexperovich** [comment]
1 should be done with my change.
2 I haven't done but it is trivial, though we would need some way to know what users to tag
3 Is already done IIRC. The merge status should list out the failed legs.
4 Making the branch in a fork is not-trivial. I haven't explored anything in this directory
5 I have updated the commit messages to be good as part of my changes. This is an example PR: https://github.com/maestro-auth-test/maestro-test/pull/44 

Unfortunately the PR title can't be much better with batching. The PR description has all the changes in it.

**Comment by weshaggard** [comment]
For 4) I'm noticing that we are starting to build up a number of these branches in the main repo and they aren't getting cleaned up. If you don't plan to do this in a fork what is the plan for ensuring the branches get properly cleaned up?

**Comment by alexperovich** [comment]
The branches get deleted when the associated PR gets merged. If the PR is manually closed/merged by a human then they need to delete the branch at the same time or it will get lost.

**Comment by weshaggard** [comment]
Another reason for a fork in my opinion as that is how all our repos keep the root repo clean of left over branches.

**Comment by alexperovich** [comment]
I did some investigation and there isn't anything actually blocking us using a fork. I thought that "GitHub Applications" couldn't have forks, but it looks like that is possible. Creating and managing the forks will be non-trivial though.

**Comment by jcagme** [comment]
IIRC only 2 and 4 are missing here. For 2, we have https://github.com/dotnet/arcade/issues/1387 which is for notifications when there are errors but we could use the same list as reviewers. https://github.com/dotnet/arcade/issues/1211 tracks the work for 4.

Since we have these two issues tracking remaining work, will close this one, but feel free to open it in case one of the listed items is still needed.
