### ISSUE TITLE
Microsoft.DotNet.ApiCompat latest version in missing some older features

### ISSUE THREAD

**Issue by RojaEnnam** [dotnet/arcade#8410]
Microsoft.DotNet.ApiCompat version 5.0.0-beta.19626.1 detects when a public method is changed to internal but the latest version(7.0.0-beta.22078.2) doesn't.

**Comment by riarenas** [comment]
@ericstj @safern wuold you be able to help here? Maybe a change that was made only in the release/5.0 branch?

**Comment by riarenas** [comment]
@dougbu mentions this was added in https://github.com/dotnet/arcade/pull/4585, and this is still in main https://github.com/dotnet/arcade/blob/9b22f498e6c8c225251f5a39c35cd9af54dff69e/src/Microsoft.DotNet.ApiCompat/src/ApiCompatRunner.cs#L80-L81

**Comment by RojaEnnam** [comment]
@dougbu respectInternals is still in main but a different feature that detects when a public member is changed to internal seems to be removed.

**Comment by dougbu** [comment]
My changes mostly focused on filters i.e. when to exclude what from the comparisons. I _think_ @safern did some follow-up work in ApiCompat that got deeper into the comparisons themselves.

I could also see how `--respect-internals` could mess w/ `public` ➡️ `internal` transitions. Both are "visible" when `--respect-internals` is in force. Not sure where the "same visibility" check might be missing these days.

**Comment by ericstj** [comment]
This was no-repro for me.  Have a look at https://github.com/ericstj/sample-code/tree/apiCompat8410

If you build that you'll see
```
 Restored C:\src\ericstj\sample-code\apiCompat8410\lib\lib.csproj (in 96 ms).
  Restored C:\src\ericstj\sample-code\apiCompat8410\lib2\lib.csproj (in 127 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  lib -> C:\src\ericstj\sample-code\apiCompat8410\lib\bin\Debug\net6.0\lib.dll
C:\Users\erics\.nuget\packages\microsoft.dotnet.apicompat\7.0.0-beta.22081.3\build\Microsoft.DotNet.ApiCompat.targets(82,5): error : MembersMustExist : Member 'public void lib.Class1.Method()' does not exist in the implementation but it does exist in the contract. [C:\src\ericstj\sample-code\apiCompat8410\lib2\lib.csproj]
C:\Users\erics\.nuget\packages\microsoft.dotnet.apicompat\7.0.0-beta.22081.3\build\Microsoft.DotNet.ApiCompat.targets(96,5): error : ApiCompat failed for 'C:\src\ericstj\sample-code\apiCompat8410\lib2\bin\Debug\net6.0\lib.dll' [C:\src\ericstj\sample-code\apiCompat8410\lib2\lib.csproj]
```

If you're able to repro the bug, please share a repro similar to that shown here.  It makes it much easier for us to see what you're seeing (or spot some other problem causing the symptom).

Some pointers:
1. Replicate the syntax of your change that you'd expect it to catch in the sample I've shared.  If it catches it, then try to find what's different in your case.
2. Is API Compat even running in your scenario?  I've seen folks break the targets before and that causes the tool to no longer run, which would present the same symptoms.

**Comment by ericstj** [comment]
Chatted offline with @RojaEnnam who mentioned that they were using `--respect-internals` on the assembly impacted.  I updated the repro to do this and it does reproduce the issue: https://github.com/ericstj/sample-code/commit/387a600de0d9999f7677bfc17cba6030f961615a

To repro, clone that and `dotnet build lib2\lib.csproj -t:Rebuild /p:Repro=true`

**Comment by ericstj** [comment]
We're no longer maintaining this version of APICompat.  Instead we recommend that folks move to the functionality built into the .NET SDK.  I believe this should correctly catch the case that this issue mentions.

@RojaEnnam I see you might be using this here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/  Can you see if the new API Compat suits your needs better?  cc @brentschmaltz @ViktorHofer 

https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/overview
