### ISSUE TITLE
Runtime-only signed builds go to a strange feed

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/arcade#8433]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

See this staging build:
https://dev.azure.com/dnceng/internal/_build/results?buildId=1589078&view=logs&j=270c1d66-4ffe-5c01-4596-5cf1c5d07eaa&t=75548d85-99ba-5770-43d4-c6bdf6d160fb

it ended up pushing the bits to this feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/-shipping-2/nuget/v3/index.json

I think it was trying to put the SDK version number into that feed but since there wasn't an SDK included in this pipeline, it just created a pretty odd feed. It should probably fall back to use the runtime version if the SDK is missing.

**Comment by riarenas** [comment]
FYI @adiaaida

**Comment by adiaaida** [comment]
That is indeed weird.

**Comment by adiaaida** [comment]
I have created a PR to fix this: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/21038

**Comment by adiaaida** [comment]
This is fixed in main. Rollout will happen next week
