### ISSUE TITLE
File execute permissions are not getting transferred when we run darc update-dependencies 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#8456]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

I created a new bash file link to the branch ->(sbom-task)  https://dev.azure.com/dnceng/internal/_git/dotnet-arcade?version=GBsbom-task
Filename -> eng/common/generate-sbom-prep.sh

File permissions -> 
git ls-files -s eng/common/generate-sbom-prep.sh
**100755** d7d132c8d8fd8dfc081c9ea144baf11a621ac0c7 0       eng/common/generate-sbom-prep.sh

Link to the arcade build -> https://dev.azure.com/dnceng/internal/_build/results?buildId=1605698&view=results

In order to test my changes in aspnetcore , I did update dependencies on my local branch 
log from my console 

```
darc update-dependencies --id 126420
Looking up build with BAR id 126420
Updating 'Microsoft.DotNet.Build.Tasks.Templating': '7.0.0-beta.22103.1' => '7.0.0-beta.22110.5' (from build '20220210.5' of 'https://dev.azure.com/dnceng/internal/_git/dotnet-arcade')
Updating 'Microsoft.DotNet.Build.Tasks.Installers': '7.0.0-beta.22103.1' => '7.0.0-beta.22110.5' (from build '20220210.5' of 'https://dev.azure.com/dnceng/internal/_git/dotnet-arcade')
Updating 'Microsoft.DotNet.Arcade.Sdk': '7.0.0-beta.22103.1' => '7.0.0-beta.22110.5' (from build '20220210.5' of 'https://dev.azure.com/dnceng/internal/_git/dotnet-arcade')
Updating 'Microsoft.DotNet.Helix.Sdk': '7.0.0-beta.22103.1' => '7.0.0-beta.22110.5' (from build '20220210.5' of 'https://dev.azure.com/dnceng/internal/_git/dotnet-arcade')
Checking for coherency updates...
Using 'Strict' coherency mode. If this fails, a second attempt utilizing 'Legacy' Coherency mode will be made.
Local dependencies updated based on build with BAR id 126420 (20220210.5 from https://dev.azure.com/dnceng/internal/_git/dotnet-arcade@refs/heads/sbom-task)

```

Link to the branch in aspnetcore -> https://dev.azure.com/dnceng/internal/_git/dotnet-aspnetcore?version=GBtest-sbom-latest
console log to check file permissions

git ls-files -s eng/common/generate-sbom-prep.sh
**100644** d7d132c8d8fd8dfc081c9ea144baf11a621ac0c7 0       eng/common/generate-sbom-prep.sh

execute permissions are not getting transferred to generate-sbom-prep.sh file when we run darc update-dependencies

**Comment by riarenas** [comment]
Local darc update-dependencies does not commit the files for you, it only stages them for commit. Execute permissions don't exist until the file is committed. I don't think this is actionable unless you start seeing it with dependency updates done by maestro itself.

**Comment by riarenas** [comment]
When we were looking at this earlier I thought the command still committed the files, but we changed that behavior a while ago. This was partly my fault for misleading you

**Comment by epananth** [comment]
So while we do update-dependencies we should commit with correct permissions ! 

Closing this after discussion with @riarenas
