### ISSUE TITLE
Execute bit not set for generate-sbom-prep.sh

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#8461]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

We're seeing issues with the execute bit not being propagated to repos, causing failures for the generation steps: https://github.com/dotnet/core-eng/issues/15551

It's set correctly in arcade;
```
git ls-files -s eng/common/generate-sbom-prep.sh
100755 f6c77453142a28129a04e059532de3a3d6b7f6eb 0       eng/common/generate-sbom-prep.sh
```

But it didn't get propagated through maestro.

**Comment by missymessa** [comment]
Should we mark this issue as blocking, as Arcade isn't going to pass Arcade Validation until it's fixed?

**Comment by riarenas** [comment]
This isn't blocking arcade-validation. The build is already out in the wild and repos will see this. 

The steps are purposely marked to continueOnError as to avoid build breaks.

**Comment by missymessa** [comment]
I see. Okay, then it's just causing unreasonable pain because I'll keep getting spammed with Arcade Validation failure notifications :)

**Comment by riarenas** [comment]
Looks like at some point, possibly during our move from using libgit2sharp to git executable commands during dependency updates, we stopped flowing the execute bit for files from Arcade. I prepared a workaround to unblock linux sbom generation in #8463 and will get some testing going for the proper fix in Maestro.

**Comment by riarenas** [comment]
We have a workaround in the templates themselves. Once we're done with the critical SBOM work I'll fix the root cause (bug in maestro)

**Comment by mmitche** [comment]
Generally: https://github.com/dotnet/arcade/issues/5346, closing this one
