### ISSUE TITLE
Make HttpClient static in Arcade SDK's DownloadFile

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#849]
ToF has seen issues with downloading logs from Azure using buildtools and they suspect that it was due to using a bad HttpClient pattern that [we also use in the Arcade SDK](https://github.com/dotnet/arcade/blob/55b8f8a3a8c20d382518770a8bdde23a8a7bc5d6/src/Microsoft.DotNet.Arcade.Sdk/src/DownloadFile.cs#L70).

Instead of

```C#
using (var httpClient = new HttpClient())
```

We should instead declare a static HttpClient and use that everywhere.

**Comment by chcosta** [comment]
Not sure if this is really a "move to Azure DevOps" issue, maybe it is... kicking out for triage.

**Comment by markwilkie** [comment]
Closing in favor of https://github.com/dotnet/arcade/issues/863
