### ISSUE TITLE
.NET 7.1 preview package is missed 

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/arcade#8493]
Hi @dotnet/dnceng 

[The issue](https://github.com/dotnet/core/issues/7213) was created in a different repository, but I suppose it can be related to aka.ms links. Please use this link to the missed package as an example [https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.100-preview.1.22110.4/dotnet-sdk-7.0.100-preview.1.22110.4-linux-x64.tar.gz](https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.100-preview.1.22110.4/dotnet-sdk-7.0.100-preview.1.22110.4-linux-x64.tar.gz).

**Comment by adiaaida** [comment]
Taking a look

**Comment by adiaaida** [comment]
Actually, I don't think it's a sas token issue, as Runtime and aspnetcore files are on the storage account.
