### ISSUE TITLE
Duplicate named maestro tokens cause server error

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#851]
If you you create a new maestro token with the same name as another token the server errors.  This is probably the correct behavior, the error message should just be handled.

**Comment by jcagme** [comment]
Yeah, just tried this and got a 500.

FYI: @alexperovich

**Comment by jcagme** [comment]
Still needed

**Comment by riarenas** [comment]
![image](https://user-images.githubusercontent.com/23242101/72497177-b2c9e800-37e0-11ea-9527-d21f9431955c.png)

Is now a thing. Closing
