### ISSUE TITLE
Migrate issues out of core-eng

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#8526]
We need a tool (or to just use the github cli) to migrate all issues newer than a year/2 years old to arcade, so long as they are not part of any excluded epics.

**Comment by adiaaida** [comment]
@mmitche @riarenas @garath @jonfortescue @MattGal @epananth @alexperovich: As listed above, as part of this, I have identified all of the security/EO related epics, whose issues we will not be migrating to arcade. The hope is that we will wait until all skipped epics are complete before archiving core-eng. After that, issues will need to be opened as AzDO work items, with a linked issue in arcade that has no details (just "Do AzDO work item #12345" with a link to the azdo work item)

@chcosta I didn't include your epic on the list of epics to skip, but I'm wondering if that also should be kept internal since it's full framework related, and not open source to my knowledge. Let me know.

**Comment by riarenas** [comment]
What is the date for the shutting down of core-eng? New requirements for EO keep coming up, so it's possible we might not be able to skip all of those epics from migration. If the epics cannot be completed, will the issues be moved to azdo along with the tracking arcade issues as part of this work?

**Comment by adiaaida** [comment]
Yes. That would be my plan. We don't have a date yet for archiving core-eng (I need to talk to Chris about it), but we're hoping that at the very least, the first phase of EO can be completed before archiving, and everything new that comes up can be handled in the "open issue in azdo with linking arcade issue" way, rather than opening issues in core-eng. I, of course, can't stop you from opening core-eng issues.

**Comment by riarenas** [comment]
More specifically, https://github.com/dotnet/core-eng/issues/15136 and https://github.com/dotnet/core-eng/issues/13551 might be lingering longer than we expected.

**Comment by adiaaida** [comment]
The JIT stuff should definitely be moved almost completely to AzDO, I'd say starting now. But having specifics makes it a lot easier to focus in on solutions, thanks.

**Comment by riarenas** [comment]
Do we have guidance on which fields need to be filled out when opening the azdo issues? Mainly thinking about how to track an issue back to an epic, or which area path so they don't show up in other people's query tracking, etc...

**Comment by adiaaida** [comment]
That is a really good idea, and shouldn't be too hard to do. Could you open an issue for me for it?

**Comment by riarenas** [comment]
In azdo?? (I kid, I'll open one and link back)

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade/issues/8567

**Comment by adiaaida** [comment]
Thank you! Added to my epic!

**Comment by adiaaida** [comment]
Realized there were a few more things I needed to implement: 
* Copying all of the project fields so they match
* Updating arcade issues if their backing epic has been been moved out of core-eng

**Comment by adiaaida** [comment]
All except a handful were "automatically" migrated over. A few will need to be manually migrated, which I will do tomorrow.

The tool failed on updating the arcade issues, which I will also deal with tomorrow. I would say this is about 95% done.

**Comment by adiaaida** [comment]
This is done!
