### ISSUE TITLE
3.1 and 5.0 staging builds should have correct permissions for staging feeds

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#8527]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The 3.1 and 5.0 staging pipelines create feeds for testing. These feeds are getting permissions that only allow contributors to see the contents. I think the issue is that this should be backported to 3.1 and 5.0:

https://github.com/dotnet/arcade/pull/8082

**Comment by adiaaida** [comment]
This might be more complicated than we think it is because the 3.1 and 5.0 staging pipelines version of arcade will need to be updated, and likely require changes in a bunch of publishing code. 3.1 might be easy. 5.0 definitely will not be.

**Comment by adiaaida** [comment]
5.0 merge main into release/5.0 branch. Will get us this and alllllll the goodness we've put into production (sbom, retention, various publishing changes, and this change).

servcing I am still working on and to upgrade arcade, I had to do some other shenanigans, but it was stuff that wasn't be used anyway, so I think it's ok to disable.

**Comment by adiaaida** [comment]
changes for 5.0 have been checked in. Changes for 3.1 don't seem to be working at all. @mmitche how important is it that 3.1 has this?

**Comment by mmitche** [comment]
> changes for 5.0 have been checked in. Changes for 3.1 don't seem to be working at all. @mmitche how important is it that 3.1 has this?

Not that important. It's more annoying than anything else.

**Comment by adiaaida** [comment]
Based on that, I am going to close this issue and skip the 3.1 changes, unfortunately.
