### ISSUE TITLE
Consider cycling secrets prior to services rollouts

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#8533]
Related: https://github.com/dotnet/core-eng/issues/15618

Cycling secrets prior to rolling out our services may reduce problems that were related to the above issue.

**Comment by adiaaida** [comment]
What we should do for this is move dotnet-helix-machines key vault usage to HelixProdService. And then remove the secrets from HelixProdKV.

**Comment by missymessa** [comment]
Parent epic closed. Closing.
