### ISSUE TITLE
Investigate potential bug in secret manager when updating manually updated secret

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#8534]
Related: https://github.com/dotnet/core-eng/issues/15508

This issue was resolved manually, but we're unsure if it was a bug in the Secret Manager CLI or not. To prevent it from happening again, we should validate if this is a bug in Secret Manager and fix it if it is.

**Comment by adiaaida** [comment]
Steps to take: 

* Create a fake secret that is manually updated.
* Update the manual secret to have a different value
* Make sure it is updated correctly in the key vault.

**Comment by alexperovich** [comment]
This is not an issue with secret manager, I just checked it. When rotating a github app secret type it will prompt for a new webhook secret, and if the wrong value is passed by the user, the wrong value will be saved.
