### ISSUE TITLE
Rollout Scorer Not Working?

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#8535]
Haven't gotten a rollout scorecard since the 2/17 rollouts, what's wrong with Rollout Scorer?

**Comment by jonfortescue** [comment]
Scorer is working fine according to logs. Seems likely that the issue is with dotnet-eng-status.

**Comment by missymessa** [comment]
@jonfortescue do we need to do any manual intervention to get the scorecards for the rollouts from last week?

**Comment by jonfortescue** [comment]
@jonfortescue I'm...not entirely sure that we _can_ get them without the logs in status to tell us what the rollouts are. I can look into it tho

**Comment by jonfortescue** [comment]
Took care of this and got the missing scorecard up.

**Comment by missymessa** [comment]
> Took care of this and got the missing scorecard up.

Did this happen to go into core-eng or arcade?

**Comment by missymessa** [comment]
> Is the scorer still down or did we just get the missing scorecard uploaded?

@jonfortescue

**Comment by jonfortescue** [comment]
It's up but it's posting to core-eng still: https://github.com/dotnet/core-eng/pull/15754

**Comment by adiaaida** [comment]
Hm. That's.... odd. I definitely changed the code.

**Comment by adiaaida** [comment]
https://github.com/dotnet/arcade-services/commit/bdf379e0a28c347a599c35c0a6ad9db71bc271e1

Did I miss anything?

**Comment by missymessa** [comment]
In person discussion: The previous score card was based on the previously released code that still pointed at core-eng. We'll keep an eye on the next scorecards and make sure they go into Arcade, then we can close this.

**Comment by adiaaida** [comment]
Scorecard prs for the last two that were missed: https://github.com/dotnet/arcade/pull/8594
