### ISSUE TITLE
Investigate and fix crashing scenarios in Helix SF

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#8539]
Extension of https://github.com/dotnet/core-eng/issues/15691

Helix SF cluster is stable on our staging environment, however, our services are continually crashing, and it needs to be fixed.

**Comment by ChadNedzlek** [comment]
I _think_ a step along the way is: https://github.com/dotnet/arcade-services/pull/1839

But that just gets the process to log/exit normally. It doesn't fix the underlying problem.

**Comment by missymessa** [comment]
I believe this issue is resolved now. Closing.
