### ISSUE TITLE
Fix or disable ValidateHelix execution for on-prem OSX validation

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#8541]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We spend 30+ minutes every main-branch build and lots of azure storage costs to setup a macOS test machine, but only test it in PRs.  We can either nerf this entire testing leg in main (my vote, actually) or fix it (just provide a fake queue name with a custom name, so the temporary machine can validate things)

Instead of running tests, we're just doing this:
```
2022-03-02 11:50:17Z osx.1015.amd64: Not sending test job; OSX queues are tested previously via the 'OSX_OnPrem' pipeline which also validates their artifacts.
Finishing: Run ValidateHelix
```
Example build: https://dnceng.visualstudio.com/internal/_build/results?buildId=1640316&view=logs&j=12dd99f1-dd1e-53c8-4e42-345b564b0209&t=4f4eac42-ee9a-5e2d-30f4-53c46d07d2b3)

**Comment by premun** [comment]
Did this change at some point?

Afaik we've been hooking the AzDO machine to staging 10.15 queue and sending a job from it after the bootstrap (and then processing it there too) so that we've had E2E Helix job test there.

I agree that this stage could only run on-demand (maybe via some `FORCE_` commit message).

**Comment by premun** [comment]
Yeah, it's not 30+ minutes as Matt claims, it's actually below 10 often, sometimes 15. Furthermore, the step was put side by side with `Build Images` which frequently takes 2 hours but many times it finishes immediately and then we get an extra cost.

1. Seeing the logs, we actually add the machine into `osx.1015.amd64`:
    ```
    /usr/local/opt/python@3.9/bin/python3.9 /Users/runner/work/1/s/./driver/driver.py -b helixosautostaging -c helixosconfigstaging -i *** -q osx.1015.amd64 -s *** -v helixstagingkv -e staging -l -p
    ```
    Maybe we could remove this `if` and let it run in `main`? Maybe we could let it run in `main` only?

2. The kind of problems we open ourselves to is that our bootstrap scripts might break and we won't notice and when DDFUN needs to re-image a machine, or stand up a new queue, they block time in their schedule (which can take time) and then find out that the scripts break and they have to go back to us, we have to fix it, roll it out and wait for them to find time again.

Maybe running this in `main` only + having `FORCE` would be enough?

**Comment by lpatalas** [comment]
> Maybe we could remove this if and let it run in main? Maybe we could let it run in main only?

But if we send the job to `osx.1015.amd64` are we sure that it will end up on our test VM? Wouldn't there be any real on-prem machines connected to the same queue?

**Comment by premun** [comment]
I know that at least 2 years back this queue was dedicated for this purpose when someone added this stage. I know that I couldn't use that queue when developing first prototype of XHarness.

However, it's a silent contract but we are keeping it (I think) still

**Comment by lpatalas** [comment]
I will move it into the backlog because I won't be able to start on this before the end of my FR week.

**Comment by ulisesh** [comment]
> However, it's a silent contract but we are keeping it (I think) still
This is correct and should be documented. The idea is to use open queues for rolling build validations and use close queues for queue that have physical devices attached. 

I'll make this is documented somewhere

**Comment by ulisesh** [comment]
Talked to Matt about this and explained how we use on-prem queues in staging
