### ISSUE TITLE
dotnet-sdk-linux-musl-x64.tar.gz package is missed

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/arcade#8542]
Hi @dotnet/dnceng,

We have an issue in install-scripts repository that is related to a missed package for Apline env : [-Channel 6.0.1xx -Quality daily fails](https://github.com/dotnet/install-scripts/issues/258).
I have tried to run the command without` -Quality `option but it still returns the message `The aka.ms link 'https://aka.ms/dotnet/6.0.1xx/dotnet-sdk-linux-musl-x64.tar.gz' is not valid: failed to get redirect location.`.
I run the initial command for PowerShell script and it was executed successfully. The generated link looks like this: `Using alternate version 6.0.103 found in https://dotnetbuilds.azureedge.net/public/Sdk/6.0.103-servicing.22151.11/sdk-productVersion.txt`.

I have found the mentioned build and artifact for Alpine was successfully generated [Build 22151.11](https://dev.azure.com/dnceng/internal/_build/results?buildId=1639909&view=artifacts&pathAsName=false&type=publishedArtifacts).
Could you please make sure that aka.ms links are valid for Alpine?

**Comment by dkurepa** [comment]
Hi Yuliia, we are looking into this issue

**Comment by adiaaida** [comment]
Closing in favor of https://github.com/dotnet/core-eng/issues/15740
