### ISSUE TITLE
SBOM list of repos left for signoff

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#8549]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

**Repos we need signoff for SBOM generation**

| Repository |  Owner | Status | Does this need sbom? | Notes |
|-------------|---------|---------|------|--------|
| dotnet-project-system |  MiYanni | | | Spl case, inserts to VS |
| SignalR-SignalR | BrennanConroy | ✔️ | |  working on arcade update | 
| dotnet-insertions-client |  bekir-ozturk| | || 
| dotnet-deployment-tools | NikolaMilosavljevic  | ✔️ | | I think I saw a PR in that repo| 
| dotnet-diagnostics-internal-components |   hoyosjs| | | |  
| dotnet-machinelearning-assets | ericstj | ✔️ | |  they were working on getting the arcade update | 
| dotnet-maui | antonfirsov  | | |arcade update is flowing? Not sure | 
| dotnet-microsoft.maui.graphics | mjbond-msft  | || arcade update is flowing? | 
| dotnet-optimization | DrewScoggins | | |  | 
| dotnet-try-convert | jmarolf  |✔️ | |last update was in oct 21st| 
| dotnet-winforms-datavisualization |  | | |last update was in dec 31st| 
| dotnet-wpf-int | singhashish-wpf | | |I see release/6.0 generating SBOM but not in main. Is that expected? |
| Microsoft-clrmd |  | | |Needs arcade update | 
| microsoft-vstest | Evangelink  | |  ||
| vs-code-coverage |  | |  || 
| dotnet-symuploader | hoyosjs  | | |Not sure | 
| dotnet-spark | suhsteve  | | |Needs arcade update | 
| Nuget.BuildTasks |  MiYanni  |  |  | Spl case, gets arcade update and inserts only to VS | 
| ASP.Net Classic nuget packages  |  StephenMolloy  |  |  | New case, has not been updated in a few years (added 3/8 to this list) | 

**created PR but not updated the issue** 
| Repository |  Owner | Status | Does this need sbom? | Notes |
|-------------|---------|---------|------|--------|
| dotnet-roslyn-tools |  JoeRobich |✔️ | | |
| dotnet-roslyn |  JoeRobich |✔️ | |Still needs update to reference SBOM from VS Component manifests. | 
| dotnet-roslyn-sdk |  JoeRobich |✔️ | | | 

**SBOM tool failure** 
| Repository |  Owner | Status | Does this need sbom? | Notes |
|-------------|---------|---------|------|--------|
| dotnet-aspnetcore and dotnet-runtime | dougbu | | Alpine legs fail  | https://github.com/microsoft/dropvalidator/issues/397 | 
| dotnet-llvm-project | akoeplinger  | |Problem with symlinks |(https://github.com/microsoft/dropvalidator/issues/368)  |

**Comment by BrennanConroy** [comment]
aspnet-SignalR-Client-Cpp needs more info https://github.com/dotnet/arcade/issues/8477#issuecomment-1043324121
SignalR-SignalR is [almost working](https://github.com/SignalR/SignalR/pull/4620), has a PR to fix some conditions

**Comment by epananth** [comment]
@BrennanConroy which is fully C++ and ships as code - we don't need to create SBOM for this. Sorry I missed this converstation

**Comment by Haplois** [comment]
For dotnet-test-templates, we updated arcade, and sbom is generated as part of our pipeline.

**Comment by premun** [comment]
@epananth `dotnet-xharness` should be handled by our team

**Comment by BrennanConroy** [comment]
SignalR/SignalR done

**Comment by epananth** [comment]
> For dotnet-test-templates, we updated arcade, and sbom is generated as part of our pipeline.

thank you !

**Comment by epananth** [comment]
> @epananth `dotnet-xharness` should be handled by our team

okay, will change owner. It is validated..

**Comment by MiYanni** [comment]
@epananth The `dotnet-project-system` has now been verified to have SBOM. The insertion PR hasn't merged yet, but the SBOM check has passed.
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/385416

**Comment by epananth** [comment]
calling this done and closing this issue
