### ISSUE TITLE
Networking Issues with AzDO

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#8553]
Reported to FR by @dougbu 

https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1646335401653?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1646335401653&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1646335401653

Need to get some telemetry on this issue, and possibly open an IcM on AzDO to fix it.

**Comment by MattGal** [comment]
Can you please point out where is the IcM with AzDO for this? Wanted to follow along.

**Comment by ilyas1974** [comment]
@missymessa is there an update on this? Is this the same issue as https://github.com/dotnet/arcade/issues/8593?

**Comment by missymessa** [comment]
I think that this can be consolidated with #8593.

**Comment by ilyas1974** [comment]
Thanks. Closing this issue in favor of #8593
