### ISSUE TITLE
Improve performance of "purge" operation in Helix.Admin.CommandLine tool

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#8568]
The tool described [here](https://github.com/dotnet/core-eng/wiki/%5BFR-Operations%5D---Purging-a-Helix-Queue) (Helix Admin command line)  is kind of slow, and as such when purging Helix queues that have been overly backed up, people do incorrect things not wanting to wait.

We should make the tool use batching to increase its throughput, so that people don't use alternate methods that cause trouble to purge Helix queues.

**Comment by premun** [comment]
It happened again today but I found out we just need to set the prefetch property of the client to increase the throughput of the purging: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/21741

**Comment by MattGal** [comment]
> It happened again today 
Can you share some more details here?   There can be lots of interesting reasons a queue gets buried, and _occasionally_ it's not just sending tons of work.  I hope we're at least quickly investigating such things?

**Comment by premun** [comment]
More details here https://github.com/dotnet/core-eng/issues/15755
