### ISSUE TITLE
[Maestro++] Investigate validaton failed errors

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#8579]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We've been getting some errors during dependency updates where the only error we see is "validation failed". We should understand which validation it's talking about, and see if we can improve the error message so they are more actionable.

Some examples:
https://github.com/dotnet/core-eng/issues/15706
https://github.com/dotnet/core-eng/issues/15705
https://github.com/dotnet/core-eng/issues/15703
https://github.com/dotnet/core-eng/issues/15702
https://github.com/dotnet/core-eng/issues/15650
https://github.com/dotnet/core-eng/issues/15505

**Comment by epananth** [comment]
I was looking at app insights for the validation logs

https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0utSE4tKMnMzytW4KpRKM9ILUpVyC8tSS3yTS0uTkxPVVBIzs8rScwEyiuFJeZkpiSCFCu4JWbmpKYoAQDcZ7wQPgAAAA%253D%253D/timespan/2022-02-25T19%3A39%3A41.000Z%2F2022-02-27T19%3A39%3A41.000Z

Something related to the way we are updating the PR is causing this error. Need to investigate it further.. @garath Let me know if this makes sense.
