### ISSUE TITLE
donet/roslyn-debug is not able to publish to darc

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#8580]
### Build

Pipelines - Run 20220308.1 logs (azure.com)

### Build leg reported

Publish using darc 

### Error message

The engineering services team will fill in the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
   "ErrorMessage" : ""
}
```
D:\a\1\s\.dotnet\sdk\6.0.100-rc.1.21430.12\NuGet.targets(130,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/internal/_packaging/roslyn-debug/nuget/v3/index.json. [C:\Users\VssAdministrator\AppData\Local\Temp\152bc0x1.cho\restore.csproj]
D:\a\1\s\.dotnet\sdk\6.0.100-rc.1.21430.12\NuGet.targets(130,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\VssAdministrator\AppData\Local\Temp\152bc0x1.cho\restore.csproj]
The tool package could not be restored.
Tool 'microsoft.dotnet.darc' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
The term 'D:\a\1\s\artifacts\tmp\Debug\darc\a02ea5b4-1333-47e0-8cc2-aef9a4ac1ab2\darc.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
##[error](NETCORE_ENGINEERING_TELEMETRY=PromoteBuild) There was an error while trying to publish build '128970' to default channels.
##[error]PowerShell exited with code '1'.

### Additional information about the issue reported
https://dev.azure.com/dnceng/internal/_build/results?buildId=1652629&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073&l=42
_No response_

**Comment by epananth** [comment]
cc: @tmat

**Comment by riarenas** [comment]
This.... looks like a transient nuget feed failure. Did you try a retry? I queued it again.

**Comment by riarenas** [comment]
Actually, this looks like a repo error. https://pkgs.dev.azure.com/_packaging/roslyn-debug/nuget/v3/index.json doesn't seem to ve a valid feed. Why is it trying to access that?

**Comment by riarenas** [comment]
Ah, the feed is [https://pkgs.dev.azure.com/dnceng/internal/_packaging/roslyn-debug/nuget/v3/index.json](https://pkgs.dev.azure.com/dnceng/internal/_packaging/roslyn-debug/nuget/v3/index.json.). Still unsure why it's being accessed at all.

**Comment by riarenas** [comment]
(also, I don't think this is how these issues are supposed to be used) @AlitzelMendez @ulisesh ?

**Comment by riarenas** [comment]
I didn't see you had assigned yourself to this @epananth. I'll let you investigate. I think it's related to the fact that this repo is only using a single private feed in their nuget.config: https://dev.azure.com/dnceng/internal/_git/dotnet-roslyn-debug?version=GBmain&path=/NuGet.Config which is not being authenticated against during the publishing, but darc doesn't need that feed at all.

**Comment by AlitzelMendez** [comment]
this is not the way they should be used, and this is the documentation on how they should be used: [KnownIssues](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md)

Also, this template is new and it's a great moment to review the information available like title and description because it seems that it was misleading :)

**Comment by epananth** [comment]
@riarenas okay will do :) 

@AlitzelMendez sorry just picked the first one..

**Comment by epananth** [comment]
Spoke to @tmat 

1) Need to remove the invalid feed and use the correct ones.
2) All the packages mentioned are really old, need to update the package version.

So he is working on fixing the repo. Closing this issue for now..
