### ISSUE TITLE
Helix Admin: Add command to enable/disable specific machines in a queue

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#8584]
On FR, we need to enable/disable specific machines in on-prem queues. Having this as a command in the [Helix Admin](https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service?path=/src/helix-admin-cli) tool should make it a lot easier to do. 

This command should do the following: 
- [ ] Authenticate the user
- [ ] Use the /api/machines/{queueId}/{machineName}/state endpoint to disable/enable the machine.

**Comment by premun** [comment]
FYI the `OsobCli` in `dotnet-helix-machines` already does that:

E.g.
```
dotnet run change-machine-state --queue windows.10.amd64.android.open -r "Android device disconnected" --production -e -m DNCENGWIN-123
```

**Comment by adiaaida** [comment]
We should probably make the documentation for this tool more robust, but I think that most of the alerts for machines needing to be taken offline have this tool's run command in the instructions (and if it's not, we should probably update the alerts that could use it, but that's a different issue -- as in literally, we're discussing that elsewhere). Given that, I am going to close this.

**Comment by ChadNedzlek** [comment]
It's unfortune we have two tools, but I guess it's better than zero tools.
