### ISSUE TITLE
Arcade repo needs to stop PR validation on 'Documentation' folder

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#8596]
Arcade's code validation stages run a lot of build and helix testing stages, but our team is now putting process docs and such into this repo.  This means even tiny typo corrections continuously cost machine time and test resources every time a commit gets pushed.  We should filter out, at least, the "Documentation" folder, from all PR validation stages since we do not have anything validating our docs anyways.

@ilyas1974 - FR candidate? 
@adiaaida FYI

**Comment by riarenas** [comment]
We used to have this policy in place, but the result was that only admins of arcade could merge any documentation PRs. Until we have a proper way forward for this I don't think this should be treated as an FR issue.

**Comment by adiaaida** [comment]
What Ricardo laid out is what I remember also. I think we would have to change the permissions on arcade to allow this to go through.

**Comment by ilyas1974** [comment]
Unfortunately, we are not able to do this.
