### ISSUE TITLE
Increase token-authenticated Helix API maximum throttling value

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#8612]
We do a lot more testing these days internally, which requires an access token.  Many dnceng/internal builds use the common "HelixApiAccessToken" from variable groups, which gets them all put into the same bucket.   I'm going to increase this limit to 500 / 1 min to relieve pain; if we see significantly more pain we can look at having more bot accounts.

**Comment by MattGal** [comment]
created https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/21760

**Comment by MattGal** [comment]
@BruceForstall the runs you saw throttling in should now have effectively unlimited API quota to poll for status; let us know if you see 429s in that scenario again.

The quota is now increased for .open queues but it's still definitely going to be possible to throttle.

**Comment by BruceForstall** [comment]
Thanks!
