### ISSUE TITLE
Update `BinLogToSln` to enable roll forward

### ISSUE THREAD

**Issue by dougbu** [dotnet/arcade#8643]
Per discussion in <https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1647284476328?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1647284476328&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1647284476328>, this tool requires a `netcoreapp3.1` runtime and will not automatically roll forward. @alexperovich commented in that Teams thread that the tool could be updated to do so and @dsplaisted provided details in https://github.com/dotnet/aspnetcore/pull/40701#issuecomment-1068383129. Without this, dotnet/aspnetcore needs to install a runtime that's not used anywhere but for source indexing.

The `BinLogToSln` tool lives in https://dev.azure.com/dnceng/internal/_git/dotnet-source-indexer?path=/src/SourceBrowser/src/BinLogToSln

**Comment by akoeplinger** [comment]
Setting `<RollForward>LatestMajor</RollForward>` in the .csproj should fix it.

**Comment by missymessa** [comment]
I think this was related to Source.Dot.Net, which has been moved to a new owner. Closing.

**Comment by dougbu** [comment]
this was related to Arcade's source-indexing features. https://dev.azure.com/dnceng/internal/_git/dotnet-source-indexer?path=/src/SourceBrowser/src/BinLogToSln/BinLogToSln.csproj now enables roll forward (matching @akoeplinger's suggestion). Closing was the right thing to do.
