### ISSUE TITLE
Parallelizing the upload of large files to Azure

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#865]
From Tomas Rylek:

> Today, parallelization works nice when there are tons of small files to upload, however it fails to kick in when there are just a few large files (this is the case of our correlation payloads – four zip files that sum up to about ¾ GB). At the implementation level, such large uploads are internally broken down to 4 MB chunks that are uploaded separately, followed by a special command to stitch them together at the Azure side to form the final file. Is seems to me we should be able to parallelize the upload of these individual chunks in the same manner we’re parallelizing small file uploads yet the current split of the upload logic between UploadToAzure and UploadClient makes this more advanced parallelization logic quite hard to implement.

@alexperovich has suggested using the Azure Storage APIs to do this.

cc / @MattGal

**Comment by Chrisboh** [comment]
Kicking back to triage.  I dont think this is something we will need for dev 16 GA.

**Comment by ChadNedzlek** [comment]
We are using the built in Azure SDK's here.  If this is something that is valuable, an issue can be opened in the blod SDK repository.
