### ISSUE TITLE
Assist aspnet with setting up their pipelines for aspnet-AspNetKatana

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#8659]
@Tratcher is requesting help setting up a pipeline for 

https://dev.azure.com/dnceng/internal/_git/aspnet-AspNetKatana
https://dev.azure.com/dnceng/internal/_build?definitionId=1113&_a=summary

**Comment by garath** [comment]
Working with Chris over email

**Comment by Tratcher** [comment]
Seems to be working, thanks.
