### ISSUE TITLE
Queue Monitor query uses fixed (small) step size, causing rampant Kusto resource usage

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#8668]
This query: https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/queues/queue-monitor?orgId=1&editPanel=84

It is hard coded to 5 minutes, which is FAR to granular, especially at multiple month time scales, so it causes a lot of resource usage on Kusto, and frequent failures.

The interval should be "$__interval", or some other interval relative to the total range.

**Comment by garath** [comment]
What's the Kusto query that you used to discover this?

**Comment by ChadNedzlek** [comment]
`.show queries | where State == "Failed"`, and I was just perusing through there to see if anything was weird.

(One of our Power BI dashboards was failing, so I was looking for it, and saw a bunch of other interesting ones)

**Comment by ulisesh** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/22146

**Comment by ulisesh** [comment]
Didn't get any traction on my PR so closing

**Comment by ulisesh** [comment]
Chad mentioned offline that he missed AzDo notifications for the questions in the PR and that caused the lack of traction. 

Chad already merged a change to use a cluster function to calculate a better interval for date ranges, thanks @ChadNedzlek!
