### ISSUE TITLE
Draft and publish AAT (Accessibility) document for public-facing UI (helix.dot.net)

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#8678]
[Task 2592](https://dev.azure.com/dnceng/internal/_workitems/edit/2592)

**Comment by garath** [comment]
@mattgal does this need to happen only after we've fixed the accessibility issues, or should this just be done as soon as we can?

**Comment by ilyas1974** [comment]
@garath / @MattGal is there a current status for this?

**Comment by garath** [comment]
I lost track of this. I'll wrap it up ASAP.

**Comment by garath** [comment]
I've completed the survey.
