### ISSUE TITLE
Maintenance of Maestro-bot?

### ISSUE THREAD

**Issue by deeprobin** [dotnet/arcade#8680]
> If there is interest (and Maestro has not yet been replaced by anything else) I can create a small Maestro rewrite.

Maestro is still being used fairly heavily, but I'm not sure if there's interest in updating it (let alone a rewrite). However, I would recommend asking at https://github.com/dotnet/arcade/issues for a definitive answer from the team that maintains it now.

_Originally posted by @dagood in https://github.com/dotnet/versions/issues/83#issuecomment-1079522857_

**Comment by dagood** [comment]
Note: this is about the Maestro service, not Maestro++ or the dotnet-maestro-bot app.

**Comment by riarenas** [comment]
As mentioned in https://github.com/dotnet/versions/issues/83#issuecomment-1079522857 there is little interest in a rewrite at this point.
