### ISSUE TITLE
Move windows.11.amd64.clientpre.open to an azure gallery image/create new queue

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#8684]
### Important rollout notes:  
Rollout notes should mention 

1. We intend to deprecate queues windows.11.amd64.clientpre / windows.11.amd64.clientpre.open mid-June 2022.
2. Images as of next rollout will include the newer, publicly-available official 21H2 Windows 11 Enterprise client image, not a preview.

- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

See https://github.com/dotnet/arcade/issues/8674. We are on a preview client version for this helix queue, which the autoscaler sometimes has issues in deleting when a VM is no longer needed, which leads to confusing and troublesome alerts. We should either create a new queue that uses the azure gallery image and/or replace the image that this queue uses.

```
Get-AzureRmVMImage -Location WestUS2 -PublisherName MicrosoftWindowsDesktop -Offer windows-11 -Skus Win11-21h2-ent

Version          FilterExpression Skus           Offer      PublisherName           Location Id
-------          ---------------- ----           -----      -------------           -------- --
22000.493.220201                  Win11-21h2-ent windows-11 MicrosoftWindowsDesktop westus2  /Subscriptions/11c6037b-227b-4d63-bee1-18c7b68c3a40/Providers/Microsoft.Compute/Locations/westus2/Publishers/MicrosoftWindowsDesktop/ArtifactTypes/VMImage/Offers/windows-11/Skus/Win11-21h2-ent/Versio...
22000.556.220303                  Win11-21h2-ent windows-11 MicrosoftWindowsDesktop westus2  /Subscriptions/11c6037b-227b-4d63-bee1-18c7b68c3a40/Providers/Microsoft.Compute/Locations/westus2/Publishers/MicrosoftWindowsDesktop/ArtifactTypes/VMImage/Offers/windows-11/Skus/Win11-21h2-ent/Versio...
```

**Comment by MattGal** [comment]
Change is merged in https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/commit/ca999adc14734aed5e5cdd7b8430382f99cadaf7, moving to rollout

**Comment by MattGal** [comment]
@lpatalas FYI, we need to get people to stop using ClientPre-named stuff when possible
