### ISSUE TITLE
Investigate removing dependency on Azure DevOps for Build Analysis 

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#8692]
Throughout the development of this feature, we have has significant challenges with Azure DevOps that are still affecting us today, and more importantly, are affecting our customers. Some examples as follows: 

- [Azure DevOps outages affect the Build Analysis check](https://github.com/dotnet/core-eng/issues/14002). A significant portion of our process relies on receiving event messages (e.g. pipeline started, restarted, completed) from Azure DevOps. When outages occur, this prevents the Build Analysis process from working as intended and eventually affects ours customers due to the check run not presenting the correct information to the user. 

- An ongoing issue can be seen [here](https://github.com/dotnet/core-eng/issues/15712), in which the Build Analysis process is unable to reset the status of the check run because we are not being notified from Azure DevOps that a build is restarting. The IcM has been open with Azure DevOps for almost a month now and no resolution has been found. This issue has been affecting customers (was originally reported by a customer) and makes it challenging for them to use the Build Analysis feature due to not knowing the accurate state of the check. 

- We've also experienced functionality changing on us randomly that end up affecting the feature. In [this case](https://github.com/dotnet/core-eng/issues/15572), the URL that we use to determine information about an event became inconsistent with the value we were expecting. This caused a part of our functionality to stop working, and the IcM resulted in a suggestion for a workaround and that they were not planning to fix this issue anytime soon. 

Overall, the unreliability and inconsistency of the Azure DevOps functionality we have a dependency on for Build Analysis is causing our functionality to not operate reliably, and is causing pain to our customers. We should investigate the effort to remove dependencies on Azure DevOps as much as possible in an effort to improve our own functionality.

**Comment by ChadNedzlek** [comment]
Here's another instance: https://github.com/dotnet/core-eng/issues/15503

**Comment by missymessa** [comment]
The issue that Chad referenced above is likely the reason we're seeing the ["Unable to find workitem/job"](https://github.com/dotnet/core-eng/issues/15542) warnings in our service. The problem is that AzDO is not supplying us with attempt information, which their API documentation says should be supplied. The IcM was resolved without any fixes, and the AzDO team acknowledged that they didn't have the resources to look into it. 

The work around that Chad discovered would require the repos to make changes to their tests so that would allow us to discover which attempt belongs with which test while AzDO is not providing us attempt information. I'm doubtful that the product teams would be willing to make those changes, however.

**Comment by missymessa** [comment]
These issues were escalated to AzDO, and they are now actively engaged with us on fixing these issues. Moving this issue to tracking for now. Each issues referenced in the original comment have links back to their associated IcM where engagement is being tracked.

**Comment by missymessa** [comment]
AzDO issues to track: 
- https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1918428

**Comment by missymessa** [comment]
Going to close this issue. There's another issue (https://github.com/dotnet/arcade/issues/8953) tracking this work: https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1918428, which sounds like it should be rolling out in the near future. 

The other one is feature work for AzDO, and not directly related to DevWF.
