### ISSUE TITLE
Helix website marks 1es pools as unknown OS

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#8699]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://helix.dot.net/#1esPools shows the 1es versions of the hosted pools as having an unknown OS

![image](https://user-images.githubusercontent.com/23242101/160899969-9fd982da-5b16-43b7-a715-78b29c1167c9.png)

the names make them self-explanatory, but would be nice if we could add them to the correct os grouping on the site

**Comment by garath** [comment]
@MattGal has agreed to handle this!

**Comment by MattGal** [comment]
PR is here: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22113?_a=files

**Comment by MattGal** [comment]
From https://helix.int-dot.net:

![image](https://user-images.githubusercontent.com/7862010/161645607-5dce3b90-1324-4786-a802-0ee0970da7e6.png)
