### ISSUE TITLE
Settle on name (again)

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#87]
There's still discussion on the name.  I still prefer "Arcade.net", but other names like the following have also been proposed:

-  Arcade.Net.Sdk
-  DotNet.Toolset.Sdk
-  DotNet.Sdk
-  Dot.Net.Sdk 
-  Microsoft.NET.Sdk

**Comment by natemcmaster** [comment]
"Microsoft.NET.Sdk" is taken already by github.com/dotnet/sdk. 

+1 for DotNet.Toolset.Sdk

**Comment by jaredpar** [comment]
Are we talking about the base namespace / assembly name? If so DotNet.Toolset.Sdk.

**Comment by natemcmaster** [comment]
I think we're talking about package name. `<Project Sdk="DotNet.Toolset.Sdk" >`

**Comment by weshaggard** [comment]
I actually like RepoTools so it is a little more clear that this isn't a general toolset for our customers. So Perhaps "DotNet.RepoTools.Sdk"?

**Comment by jcagme** [comment]
I guess we are settled on Arcade.Sdk?
