### ISSUE TITLE
Helix azure-pipelines reporter still produces a Logs.txt file that no longer has valid URLs

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#8702]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

### The problem: 
- [This code](https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/Sdk/tools/azure-pipelines/reporter/test_results_reader/__init__.py#L76) assumes the URL that Helix logs will be uploaded to
- Recent Dev Workflow work has start baking the "attempt #" into the log URIs, which in this case is not known by the script in question.  Thus, the URL will be wrong and missing a /1, /2, etc.

### Possible workarounds:
- Teach this code to directly make the attachments for the console log instead of a txt file with a URL of the console log
- Add the Azure DevOps extension that dnceng has to be able to view the Helix view of the file attachments for a work item
- Just slap a /1 in the guess-generated URL when creating this file (yuck)

Tagging @alexperovich (wrote the original reporter) and @ChadNedzlek  (SME on the modifications that broke this URL) so we can have a discussion.

**Comment by garath** [comment]
From triage, I shared the DNCEng extension with the Microsoft org.

**Comment by ilyas1974** [comment]
FR, could you please follow up with the Microsoft org to make sure this has been resolved.

**Comment by alexperovich** [comment]
who is "the Microsoft org"?

**Comment by ilyas1974** [comment]
This is the Azure DevOps org that is called Microsoft

**Comment by alexperovich** [comment]
I get that, but who needs this extension installed? Who can approve this? I can't just email "the Microsoft org".

**Comment by ilyas1974** [comment]
Sorry - I thought were more "plugged in" on this issue. 

The URL for this issue is https://dev.azure.com/microsoft and the "owner" can be found at https://dev.azure.com/microsoft/_settings/organizationOverview. I would recommend starting with him.

**Comment by alexperovich** [comment]
The Logs.txt file has been removed, and the WinUI team knows what they need to do for the extension.
