### ISSUE TITLE
Azure DevOps workitem processor 403s when trying to get the project board

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#8766]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain
This causes issue spam

The workitem processor is failing to add issues it creates to a projects board, causing the configured 10 retries to kick in and resulting in 10 github issues for each workitem processed.

This is a two fold issue:
1) We probably shouldn't retry if the issue was created and/or we should check to see if an issue has already been created for an azdo work item (this would probably be a bunch a string compares, but shrug. It's probably the best we've got). Or maybe just not fail-fail when the board updates fail. Or just keep the retries at 1 forever, which is also probably the right answer.
2) We need to figure out why the auth isn't working for the processor when it works just fine for HelixApi's WebHookController

**Comment by riarenas** [comment]
We are disabling the offending code and reducing the retries to 1 to mitigate the effects while a fix is found: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/22148

**Comment by adiaaida** [comment]
@AlitzelMendez figured it out. PR in https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/22210

**Comment by adiaaida** [comment]
I have confirmed the fix has worked, and issues are opened, added to the board, and epic issue added based on what is supplied when creating the azdo task work item!
