### ISSUE TITLE
Remove unused on-prem queues

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#8771]
@dkurepa brought to my attention that we have a couple of on-prem queues that do not have systems assigned to them. After doing some research, the systems have been retired but we never removed the queues. 

Please remove the following queues 

windows.10.amd64.nperf (used by the PERFRATxx systems that have been retired)
windows.10.amd64.clientrs1.perf (used by the PERFSNAKExxx systems that have been retired)

**Comment by alexperovich** [comment]
Should the Windows.10.Amd64.ServerRS1.Perf.Open queue also be retired?

**Comment by alexperovich** [comment]
It depends on the clientrs1.perf queue definition.

**Comment by alexperovich** [comment]
This has been finished.
