### ISSUE TITLE
CG work for dotnet-helix-machines

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#8773]
To drive our CG alert to Zero, please address the following items.

https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-helix-machines?_a=alerts&typeId=6377838&alerts-view-option=active

We need to address anything with a medium (or higher) priority

**Comment by ulisesh** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22239

**Comment by ulisesh** [comment]
Good progress on this, hopefully I can merge my PR tomorrow

**Comment by ulisesh** [comment]
PR for Azure SDK merged 🤞

**Comment by ulisesh** [comment]
PR for azure functions sdk https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22358

**Comment by ulisesh** [comment]
More Azure function changes https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22516

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/22865  should address this.

**Comment by MattGal** [comment]
I believe that fixed it, closing this issue (optimistically...)
