### ISSUE TITLE
CG work for dotnet-helix-services 

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#8774]
To drive our CG alert to Zero, please address the following items.

https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-helix-service?_a=alerts&typeId=6439726&alerts-view-option=active

We need to address anything with a medium (or higher) priority

**Comment by MattGal** [comment]
Note: Most of this work will come in an arcade-services update when https://github.com/dotnet/arcade/issues/8775 is complete

**Comment by ChadNedzlek** [comment]
This is also done.
