### ISSUE TITLE
CG work for dotnet-arcade-services

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#8775]
To drive our CG alert to Zero, please address the following items.

https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-arcade-services?_a=alerts&typeId=6567134&alerts-view-option=active

NOTE: there are separate work items for the following branches and we need to address anything with a medium (or higher) priority

- main
- production

**Comment by ChadNedzlek** [comment]
I should hopefully be able to whip this out. I'll take these.

**Comment by ilyas1974** [comment]
@alexperovich is this something you are still working on?

**Comment by ChadNedzlek** [comment]
I believe we have resolved all of these, unless a new one has cropped up.

**Comment by ChadNedzlek** [comment]
Indeed, it's green. Closing.
