### ISSUE TITLE
Support publishing to VS Drop

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#878]
Whether or not to publish to VS Drop should be re-evaluated and probably implemented.  This is especially true when we have a "blessed build".

**Comment by JohnTortugo** [comment]
@markwilkie is this blocking build preview?

Cc'ed @ericstj @tmat @natemcmaster

**Comment by JohnTortugo** [comment]
Let @johnbeisner knows when this gets done.

**Comment by riarenas** [comment]
@markwilkie should we be looking into this one for servicing 3, or should we look into this for the next release?

**Comment by riarenas** [comment]
This one keeps popping up from time to time. Moving to current epic.

**Comment by riarenas** [comment]
I think we can just close this as a dupe of https://github.com/dotnet/arcade/issues/5538, which has a lot more details on how this is being throught out.
