### ISSUE TITLE
PowerBI report with build errors uses template to open new issues

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#8794]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

**Comment by missymessa** [comment]
Need to find out who owns the PowerBI report and how we can update it. 

cc @ilyas1974

**Comment by garath** [comment]
What report does this refer to?

**Comment by ulisesh** [comment]
The one used in CI council, I think it shows build breaks with many hits

**Comment by AlitzelMendez** [comment]
I talked with @ulisesh and took a look to the dashboards and it seems that this is not necessary.

closing the issue. Please feel free to reopen this issue :)

**Comment by AlitzelMendez** [comment]
for dashboard: https://msit.powerbi.com/groups/de8c4cb8-b06d-4af8-8609-3182bb4bdc7c/reports/f0702582-7c04-47ca-a145-6ac37fd25813/ReportSectioncb62e8e5baebca8883e1?experience=power-bi

**Comment by AlitzelMendez** [comment]
@ilyas1974 this has been done! 
closing!
