### ISSUE TITLE
Converge "KoreBuild" and Arcade

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#88]
The way arcade builds, tests, packages, signs, and publishes must be directly usable by all repos in the stack.   Among other things, it provides the following value:
-  Consistency across repos for devs
-  Implements the "repo API", making adoption more straight forward
-  Allows for reasonable updates and improvements across the entire stack
-  More efficient, in that there's only one implementation for shared eng 

This epic is considered complete when:
-  [ ] Arcade has the changes necessary for KoreBuild repos
-  [ ] All KoreBuild driven changes are useful across the stack

**Comment by natemcmaster** [comment]
cc @Eilon @muratg

**Comment by markwilkie** [comment]
@natemcmaster wrote a great list to get started.  https://gist.github.com/natemcmaster/0ef23512c011b7ec09f25ad13a1d65e2  We should probably create an issue for each item noted and attach it to zenhub.

**Comment by natemcmaster** [comment]
I've opened some issues on aspnet/BuildTools for things we can do to start moving the needle on this.

* https://github.com/aspnet/BuildTools/issues/727 - change repo layout to match Arcade conventions
* https://github.com/aspnet/BuildTools/issues/399 - Use netfx ref assemblies as a package
* https://github.com/aspnet/BuildTools/issues/728 - use resx string generation from Arcade
* https://github.com/aspnet/BuildTools/issues/729 - checkin the global.json file instead of generating it

**Comment by markwilkie** [comment]
Thanks @natemcmaster

**Comment by natemcmaster** [comment]
We've started converting some repos to Arcade. As expected, we've run into lots of little issues. We're not done yet, but I'm going to start filing issues for the ones we think are important.

First up, https://github.com/dotnet/arcade/issues/1441

**Comment by natemcmaster** [comment]
https://github.com/dotnet/arcade/issues/1444

**Comment by markwilkie** [comment]
@natemcmaster - is this tracking issue (epic) providing any value for you guys?  If not, I'll close it....

**Comment by natemcmaster** [comment]
By the way, here is a list of existing issues that I would say are related to this.

- https://github.com/dotnet/arcade/issues/1646
- https://github.com/dotnet/arcade/issues/1526
- https://github.com/dotnet/arcade/issues/1525
- https://github.com/dotnet/arcade/issues/1444
- https://github.com/dotnet/arcade/issues/1441
- https://github.com/dotnet/arcade/issues/1485
- https://github.com/dotnet/arcade/issues/1558
- https://github.com/dotnet/arcade/issues/1912
- https://github.com/dotnet/arcade/issues/1910

**Comment by markwilkie** [comment]
Thanks @natemcmaster !

**Comment by natemcmaster** [comment]
I've also opened https://github.com/aspnet/AspNetCore/issues/7280 on our end to track and assign this work. I'm doing more costing exercises today for other infrastructure efforts, and I think converting to Arcade will be a prerequisite to enabling source-build for aspnetcore.

**Comment by natemcmaster** [comment]
It's been a long journey, but almost there. This will be resolved with https://github.com/aspnet/AspNetCore/pull/11122
