### ISSUE TITLE
Signing task doesn't surface enough information

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#886]
The signing task gets to 

```
 Signing Round 0: 38 files to sign.
```

and then will move on to round 1 if signing is successful, but if there is a failure, you have no way of knowing there is a failure until the task times out.  The task hides relevant information like "certificate not found", "build definition not approved", etc...  The task should surface that information and also do a better job of telling you where logs (on the machine exist, they are both in `s\artifacts\tmp\release\signing` and `a\MicroBuild\Plugins\InstallESRP` or something close to that).  Additionally, if the overall build times out or is cancelled, the binary log is not closed and is not useful.

**Comment by tmat** [comment]
We should make the task cancellable.
Having the binary log not closed cleanly seems like a bug in msbuild.

**Comment by JohnTortugo** [comment]
I think increasing the verbosity of the signing task will definitely help and it's pretty easy. However, from what I've observed, having the the binary log available when the build times out would help much more. Being able to cancel the task should also definitely help, but are you able to even see log messages from MicroBuild execution on the screen?

What I propose of improvements:

- Increase verbosity of SignToolTask
- Make SignToolTask cancellable
- Be able to inspect MicroBuild logs when the task or build is cancelled/times out.

As for this last point I'm not sure if MSBuild provide a way circumvent that (can you please comment on this @rainersigwald ?). I was thinking that maybe providing a custom logger or dumping the logs to the screen would help to alleviate that.

Do you think this sounds reasonable & will help?

**Comment by chcosta** [comment]
I agree.  I don't think we need gobs of information, but I think we need a better balance than what we have today.  Bin logs are great for post-build deep investigations, but if a build is failing after 10 minutes, andyou have to wait 40 minutes to do an investigation, it really slows down an engaged dev.

**Comment by JohnTortugo** [comment]
> Additionally, if the overall build times out or is cancelled, the binary log is not closed and is not useful.

I'm doing some investigation on this. Can you please point me to one such build?

**Comment by chcosta** [comment]
I think you can repro this just by scheduling a build, cancelling it, and then trying to open the build binlog (should have the same behavior as the signing binlog)

**Comment by JohnTortugo** [comment]
Thanks @chcosta . Does any of you know if the signing plugin is cancellable or who can I ask that or where is the source code?

**Comment by chcosta** [comment]
@JohnTortugo, Sent you the email alias for the plugin via Skype.  I'm not sure what a "cancellable" signing plugin really gets you, it's not going to roll back state or anything.  

I assume that on cancellation, the VSTS agent just kills all the running processes and that's why the binlog doesn't get closed (unless the step is set to "always" or something).

**Comment by tmat** [comment]
@KirillOsenkov What happens with binlog when msbuild process is killed in the middle of execution? Can the binlog reader open unfinished binlog?

**Comment by tmat** [comment]
@chcosta Seems to me that VSTS should not just kill the process. That could leave machines in bad state. Perhaps it should be possible to specify a build step that is triggered when cancallation is requested. Such build step could attempt to cancel the build gracefully.

**Comment by JohnTortugo** [comment]
As per talk with @rainersigwald there seems to be a bug in msbuild.exe or at least margin for some improvement. He suggested to open an issue in msbuild. I'll do that soon.

**Comment by KirillOsenkov** [comment]
Also please share the corrupt .binlog with me, I can try and see if I can make it openable in the viewer.

**Comment by JohnTortugo** [comment]
Here is the msbuild issue: https://github.com/Microsoft/msbuild/issues/3815

> Also please share the corrupt .binlog with me, I can try and see if I can make it openable in the viewer.

Sadly, the files are always empty on that scenario :-/

**Comment by JohnTortugo** [comment]
> I don't think all of the errors are hidden behind the MicroBuild plugin. Things like "definition is not approved" are captured in the binlog, so it seems plausible that it's easily determined.

They are captured on the MicroBuild binlog, right? Anyway, that's one of the validation that I'd like to see if we can "re-"implement.

> I don't know what we really get by adding a console logger (or file logger) for these cases.

The hope is that you'd at least be able to see some error message before the build times out or maybe get some error messages in case the .binlog is empty. I've "repro-ed" the "definition not approved" error and it come from MicroBuild plugin validation and it actually "re-tried" to sign the files about 5 times before it finally failed and reported error.

**Question:** shouldn't calling the MicroBuild plugin for signing in "test" mode do these validations?

**Comment by chcosta** [comment]
> They are captured on the MicroBuild binlog, right? 

MicroBuild doesn't create a binlog, just a file log.  When I say binlog, I'm referring to the signing tool and Arcade things that use binlogs.

**Comment by JohnTortugo** [comment]
Update:

- Talked with @chcosta and explained that these logs are actually produced by the MicroBuild plugin and not exposed to the SignToolTask until the plugin finishes execution.
- I'm talking with the Microbuild team to see if we can get a fast-fail option so we don't have to wait long to get the error messages for trivial checks.
