### ISSUE TITLE
SignTool does not fail when a nupkg/vsix contains an unaccounted for file

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#887]
RoslynSignTool would issue an error when a file in a container was not accounted for in the sign or exclusions. Example:
```
signtool : error : Zip Container 'packages\Mono.WebAssembly.Interop.0.7.0-preview1-t000.nupkg' has part 'lib/netstandard2.0/Mono.WebAssembly.Interop.dll' which is not listed in the sign or external list
```

The Arcade tool, on the other hand, will silently skips files that are not accounted for in the PKT/info => cert mappings. For example, the logging output on a run of SignToolTask that would have signed the .nupkg, but not the .dlls inside, would pass and produce logging output as:
```
  Build artifacts signed and validated.
```

I'd like a stricter mode with the RoslynSignTool behavior. I would like to be able to assert that everything in a container is accounted for -- either it is signed or it was explicitly excluded -- and have the dry run of the tool validate this.

**Comment by jcagme** [comment]
Probably related to what is mentioned in https://github.com/dotnet/arcade/issues/886 about verbosity

**Comment by JohnTortugo** [comment]
That's odd. At least for such files I'd expect a warning like so: 

`Couldn't determine signing information for this file: {fullPath}`

I'll call you on Skype to get a repro of this.

**Comment by natemcmaster** [comment]
@JohnTortugo: I'm not at my work computer anymore, but I believe you can reproduce this easily if you pass in any .nupkg's for signing and it contains files are signable but do not match the PKT or file extension conditions.

> Any reason not to use Arcade SignTool?

@tmat: Yes. I want the behavior of RoslynSignTool. We've been burned by things signed with the wrong certs or missing signing altogether. I want a stricter mode.

**Comment by JohnTortugo** [comment]
@natemcmaster I think having the tool create a manifest with the status that it left each file that it found would make it easier to inspect and diagnose any problems. What do you think?

Something like the below on a manifest file:

```
/file/path/name.dll - Going to be signed with: CertName
/file/path/name.pkg - Going to be signed with: CertName
/file/path/name.pkg->file1.dll - Going to be signed with: AnotherCert
/file/path/name.dll - Is already signed and will be skipped
/file/path/name.dll - Is already signed but will have a certificate appended
/file/path/name.dll - will be ignored from signing because xyz
```

**Comment by natemcmaster** [comment]
A diagnostic file like this would be great, but I would still like it to fail when new files appear in packages or vsix's and which are not accounted for. The list of files in our packages and containers continually shifts, and I want to make sure we don't end up with un-signed files in our build output.

**Comment by JohnTortugo** [comment]
We can make the tool fail if a file doesn't have a mapping information on `FileExtensionSignInfo`. That will actually makes things quite "strict", since all files will either have a default certificate or will explicitly be asked to be ignored (due it's extension). 

The "downside" is that we'll need to populate that `FileExtensionSignInfo` with a bunch of extensions that we aren't interested in signing. What do you guys think?

**Comment by natemcmaster** [comment]
Does the tool already know which [file extensions are considered "signable"](https://microsoft.sharepoint.com/teams/codesigninfo/Wiki/Signable%20Files.aspx)? Adding `FileExtensionSignInfo` for every possible extension is less than ideal, and may be unnecessary if the tool already knows that it can skip extensions such as .txt and .yml.

**Comment by JohnTortugo** [comment]
That is done implicitly on the configuration, and seems to be the root of your problems here. Currently, it **[ignores](url)** all files that doesn't have the extension listed on `FileExtensionSignInfo`, which is cool because we ignore such files as .txt and .yml, but can lead to accidentally ignoring files that we would want to sign - as seems to be your case.

**Comment by JohnTortugo** [comment]
Another option, it seems, is to just get all the extensions that are "signable" and add them on `FileExtensionSignInfo`. That also will make sure that all "signable" files have a default certificate. If the tool find a file that isn't on that list it will just ignore it - as is today - but on that scenario I think it would not be a problem, right?

**Comment by markwilkie** [comment]
Another option would be to implement a "strict" flag.

**Comment by natemcmaster** [comment]
I would prefer a solution that bakes in strictness to the sign tool. The problem with the `FileExtensionSignInfo` items is that those are configuration data. There is a set of these defined by the arcade SDK targets and passed into the signtool task, but ASP.NET is not using SDK targets (at least not yet) and will have a different set of `FileExtensionSignInfo` items to pass in.

**Comment by natemcmaster** [comment]
> The certificates used to sign each file are listed in binlog

Good to know. I'll take a closer look. A file is still nice, but binlog may be good enough.

> Can you be more specific in what was missed, or in what cases a certificate was wrong?

Missing code signing: oh gosh, too many times to count, and embarrassing amount of times actually.
Wrong cert: I'll email you internally about what happened here.

> BTW, this should catch any unsigned files: #335

Yes, and it's good we have it. The reason I still think this is worth doing is that #335 requires you to run real signing. I like that Roslyn signtool dry run can tell you when things are missing without having to wait for a real CI build. It's extremely helpful for the inner dev loop and fast feedback. It also helps surface signtool misconfiguration in PRs.

**Comment by tmat** [comment]
Ok, so the proposal now is to remove `FileExtensionSignInfo` and require all repos to specify all files using `FileSignInfo`. 

The sign tool will output to a file in logs directory the expected list if it encounters some unsigned files that are not listed in `FileSignInfo` (during dry run as well as real signed run). The list should be in msbuild xml format, so that it can be directly copy-pasted to `Signing.props`. In fact, this would be the way to transition to this new version of sign tool.

**Comment by natemcmaster** [comment]
Use caution with globs. System.*.dll would pick up a 3rd party binary: System.Interactive.Async.dll (from Ix-Async).

**Comment by tmat** [comment]
That's why it's just a suggestion. You'll need to review the suggested certificates.

**Comment by JohnTortugo** [comment]
- The files to be signed are still going to be automatically discovered after the seed files informed in ItemsToSign.
- `FileSignInfo` will be populated with all files the user expect to be signed.
- We aren't going to look for signing info in `FileExtensionSignInfo` anymore.
- If an **unsigned** file is found that doesn't have it's **name** on `FileSignInfo` 
the file name will be logged on a new manifest file.

Questions:
- **Every repo** will have to adopt this new process. Is that it? No way to opt out?
- **Should the existence of such files make the task fail?**

**Comment by tmat** [comment]
> The files to be signed are still going to be automatically discovered after the seed files informed in ItemsToSign.

Correct. The files discovery is not changing. It's still based on `ItemsToSign`.

> FileSignInfo will be populated with all files the user expect to be signed.

If you mean that the repo will need to list all file names and their certificates in `FileSignInfo` then yes.

> If an unsigned file is found that doesn't have it's name on FileSignInfo
the file name will be logged on a new manifest file.

Yes. I wouldn't call it a "manifest file". More like "Suggested certificates file". The tool should report an error "Discovered unsigned files that do not have assigned certificates. To fix this issue add missing entries to Signing.props. The list of files and suggested certificates are listed in {path to SigningSuggestions.props}"

> Every repo will have to adopt this new process. Is that it? No way to opt out?

Correct.

> Should the existence of such files make the task fail?

The task should log an error (see above) and at that point generate the file that the user can open and copy the entries from. The file should contain comment that the certificates listed there were determined heuristically and must be reviewed.

**Comment by JohnTortugo** [comment]
Thanks for clarifying. Crystal clear now. But, I've another question related to this:

> If an unsigned file is found that doesn't have it's name on FileSignInfo the file name will be logged on a new manifest file.

Of course this is only relevant for "signable" files but the tool doesn't understand the concept of signable file. Should we incorporate a list of signable file types? In other words, if we find a "foo.bar" file that isn't signable it doesn't have to be on the `FileSignInfo` list. Maybe we can use the `SuggestedSignInfo` list to help with that?

**Comment by tmat** [comment]
Yes, let's use `SuggestedSignInfo` to determine what files are signable.

**Comment by JohnTortugo** [comment]
Aborting the work on this.
