### ISSUE TITLE
Various minor common script issues

### ISSUE THREAD

**Issue by mikem8361** [dotnet/arcade#889]
I found the following issues with the common arcade build scripts while working on the diagnostics repo:

eng\common\build.ps1 - needed to pass the architecture to the dotnet cli `dotnet-install.ps1` script. Added a new option called -architecture.

eng\common\build.sh - same as build.ps1 above and there were two places where `if [[ $ci ]]; then` needs to be changed to `if [[ $ci == true ]]; then`. The first one causes the NUGET_PACKAGES to be always set to `$repo_root/.packages` even when building locally.

eng\common\templates\phases\base.yml: My build defs need to set the "dependOn:" for a phase. Added a dependOn parameter.

**Comment by markwilkie** [comment]
FYI @weshaggard @tmat @jcagme

**Comment by weshaggard** [comment]
>eng\common\build.sh - same as build.ps1 above and there were two places where if [[ $ci ]]; then needs to be changed to if [[ $ci == true ]]; then. The first one causes the NUGET_PACKAGES to be always set to $repo_root/.packages even when building locally.

I believe I'ved fixed that while editing other stuff in the script in PR https://github.com/dotnet/arcade/pull/845

**Comment by mikem8361** [comment]
Yes you did.

**Comment by markwilkie** [comment]
@mikem8361 - anything more to do here do you think?

**Comment by mikem8361** [comment]
The "architecture" option hasn't been added yet and the "dependsOn" in the base.yml hasn't been added either.

**Comment by jcagme** [comment]
@mikem8361 when you say "added" in the description of this issue, is that something you added locally? If so, would you mind creating a PR with those changes so these are official?

**Comment by mikem8361** [comment]
Yes, I added the "architecture" command line option locally to eng\common\build.ps1 and eng\common\build.sh.  I offered to create a PR to the arcade repo, but @tmat recommended at the time to  just file the issue because @weshaggard was in the middle of some big changes.

**Comment by jcagme** [comment]
At the time, there might be an overlap on `build.*` scripts but not in `base.yaml`. Also, I think @weshaggard  is done since #845 has been merged. If you still have the changes around please create  PR when you have a cycle. In case other folks are working on something similar I'm pretty sure comments will arise in the PR
