### ISSUE TITLE
[Maestro] Provide help/possible values in the REST API for certain subscription fields

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#892]
Because subscriptions have two open ended fields that are extensibly implemented in Maestro, we should provide a way to query for possible values and formats.  This is for the update frequency and merge policies.

**Comment by jcagme** [comment]
When creating a subscription through darc, recommended values for update frequency and merge policies are given. These are hard coded strings in the tool. Is this issue tracking the work to expose an API to get possible values for these fields or the fact that darc already provides these is good for closing?

**Comment by riarenas** [comment]
We provide all the merge policies and update frequencies when creating and editing a subscription
