### ISSUE TITLE
Issues with docker containers on Windows Server 2022

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#8981]
Per https://github.com/dotnet/runtime/issues/67728, we need to verify the configuration of the systems being used. 

On Windows Server, process isolation is used by default. With process isolation, the host and container must be the same version. With Hyper-V isolation, the container can be the same version or a lower version than the host. This is described at https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility with some helpful tables.

We need to see how our systems are configured.

**Comment by danmoseley** [comment]
@MattGal @alexperovich do we have a clear next action here, and who owns it 😃

**Comment by MattGal** [comment]
> @MattGal @alexperovich do we have a clear next action here, and who owns it 😃

We do, I apologize for your inconvenience.

Alex has merged a fix here, and we can test it in staging to be 100% sure that this addresses your issue pretty easily (just need to get the right docker tag from this issue and send it to staging with a little "hello world" work item, I'll do that shortly)

We tried to roll out Weds. but I found an issue that reset that.  Then, a whole comedy of other errors prevented having a clean staging environment, so we've reset to rolling out next week.  Let me know if this is more painful than I'm understanding; ideally we can just keep some broken tests disabled until 4/27 if that works for you.

**Comment by danmoseley** [comment]
No need to apologize, no doubt I would inadvertently break you periodically if that was technically possible 😺 

We're renewing focus on reducing https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+label%3Ablocking-clean-ci 

From the [issue](https://github.com/dotnet/runtime/issues/67105), it's not clear to me how to query how impactful it is.

**Comment by MattGal** [comment]
Rolled out today, closing.
