### ISSUE TITLE
[Validation] Create test projects which validate packages

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#9]
Validate use as packagereference
Validate use as sdk
Validate closure (probably grab this from buildtools)

**Comment by markwilkie** [comment]
@chcosta - is this done already?

**Comment by chcosta** [comment]
No, there's one package which has unit tests, but we don't have any validation that the set of packages we produce meet any of the above criteria.

**Comment by markwilkie** [comment]
closing as it's super old and I *think* is covered sufficiently elsewhere.  Feel free to reopen if that's not the case.
