### ISSUE TITLE
Add ItemGroup to SignToolTask to receive info about Certificates

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#900]
Add a new ItemGrop to the SignToolTask that will enable it to receive information about the certificates that are going to be signed.

Proposal

```
<ItemGroup>
  <CertificateSignInfo Include="{certificate name}" DualSigningAllowed="true" ThirdPartyAllowed="true" />
</ItemGroup>
```

If `DualSigningAllowed` is true (default is false) the certificate can be used to sign already signed files that specify such certificate. 

If `ThirdPartyAllowed` is true (default is false)  then the certificate can be used to sign unsigned artifacts not produced by Microsoft, otherwise an attempt to sign such artifact with the certificate will fail.

What's considered a Microsoft artifact:
- PE file: copyright string must be `© Microsoft Corporation.  All rights reserved.`
- other file types: TBD, for now we only apply this policy to PE files.

Originally mentioned here: @weshaggard https://github.com/dotnet/arcade/pull/882#discussion_r221108946

Cc @tmat

**Comment by JohnTortugo** [comment]
AFAIU from the meeting yesterday we don't need to incorporate the `ThirdPartyAllowed` option anymore for we aren't going to include signing validation on the SignTool at this momment. Right?

**Comment by tmat** [comment]
Correct.
