### ISSUE TITLE
DDARM64-132 failing all work items

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#9016]
A customer reported DDARM64-132 has been failing all jobs without any failure details (https://github.com/dotnet/runtime/issues/67821). Kusto shows that the machine has been failing all work items for since 2022.04.09. Taking the machine offline and creating an ICM

**Comment by dkurepa** [comment]
Icm link: https://portal.microsofticm.com/imp/v3/incidents/details/301282899/home

**Comment by MattGal** [comment]
also https://github.com/dotnet/arcade/issues/9024 (046)

**Comment by dkurepa** [comment]
The machine has been reimaged and brought back online
