### ISSUE TITLE
Upgrade VS2022 preview to 17.2.0 Preview 2.1

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#9017]
Vs2022 preview so be updated to 17.2.0 Preview 2.1 so that it maches VS2022 scouting preview

**Comment by dkurepa** [comment]
PR link: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22256

**Comment by dkurepa** [comment]
Queue update PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22258

**Comment by dkurepa** [comment]
The PRs have been merged

**Comment by MattGal** [comment]
Rolled out today, closing.
