### ISSUE TITLE
Consider adding a link to the opened GitHub issue in work item processor

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#9021]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When an issue is opened in GitHub to track an internal azure devops work item, adding a link to the generated GitHub issue as a field or comment in the task would be a useful way to keep both issues linked.

**Comment by adiaaida** [comment]
Sounds good. Makes sense. I'll look into it

**Comment by adiaaida** [comment]
Trying to do this, but getting tripped up by the tests (having a hard time figuring out how to mock out the VssConnectionProvider). Will likely talk to someone on the build analysis v-team to see if they have prior art that I just can't find.

**Comment by adiaaida** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/22573

**Comment by adiaaida** [comment]
Pretty sure this rolled out
