### ISSUE TITLE
Customer user documentation for Build Analysis

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9022]
The placeholder wiki page here: https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki%20(old)/911/Simplifying-build-failure-investigation needs to be fleshed out with documentation geared towards users (customers) of Build Analysis, so they can better understand how to use this feature.

**Comment by riarenas** [comment]
If it's for customers, should this be in the arcade wiki instead of the azdo wiki?

**Comment by missymessa** [comment]
> If it's for customers, should this be in the arcade wiki instead of the azdo wiki?

I'm fine with either, just wherever the team has decided this information should live. @ilyas1974 has been heading up an effort to get documentation sorted, and he created the placeholder above.

**Comment by missymessa** [comment]
Okay, looks like the "old" AzDO wiki has been deleted, so I'm going to add this documentation to our Arcade documentation (not wiki) per usual for customer documentation. If where this documentation should be stored is changed, I'll move it then :)

**Comment by missymessa** [comment]
Looks like we already have some pre-existing documentation: https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/Introduction.md

I'll update this, since more of our features have been completed since it was originally written.

**Comment by missymessa** [comment]
PR was merged. https://github.com/dotnet/arcade/pull/9354
