### ISSUE TITLE
Make redirection of xunit stdout/stderr to .log files optional

### ISSUE THREAD

**Issue by nguerrera** [dotnet/arcade#903]
I personally miss how xunit runs would dump test failure info to my console before we moved to repo toolset/arcade. I lose time every day copying and pasting the .log file path to open it in a text editor.

Even worse, we sometimes end up in situations where the .log file is not available in CI artifacts. (At the moment, we are blocked on a VSTS public CI missing feature and the log files are not available though this is supposed to be fixed in the coming weeks.)

cc @livarcocc

**Comment by markwilkie** [comment]
@jonfortescue - thoughts on this?  (cc @jcagme)

**Comment by jonfortescue** [comment]
This will require us to rewrite some of the job waiter logic in the Helix SDK, but it's completely manageable work. I will add this issue to my epic's backlog.

**Comment by alexperovich** [comment]
This actually has nothing to do with helix. The tests @nguerrera is talking about are xunit tests run as part of the build. This is a change in the arcade sdk.

**Comment by jonfortescue** [comment]
@alexperovich ah, gotcha. removing from my epic then. I have a feeling that Mission Control should be the way to go for Helix xunit results anyway, yeah?

**Comment by markwilkie** [comment]
Also - folks running their tests in Helix will likely want the same functionality.  @jonfortescue - this seemed like something that might be a good "intro" to the Arcade SDK.  I'll let @jcagme weigh in of course...

**Comment by jonfortescue** [comment]
@markwilkie Gotcha. I will file a parallel issue under my epic then.

**Comment by markwilkie** [comment]
@alexperovich  - once there's an issue tracking the work to provide visibility to all logs, link to it here and close the issue please.

@nguerrera - please touch bases with @alexperovich to make sure your scenario is taken care of.  We're pretty sure it is....

**Comment by markwilkie** [comment]
Found it!  (grin)  #907 is tracking the actual work.
