### ISSUE TITLE
Add documentation for matrix of truth output files

### ISSUE THREAD

**Issue by lpatalas** [dotnet/arcade#9031]
Matrix of truth CLI generated several JSON and CSV output files that are then imported to Excel, PowerBI, etc. We should add some kind of readme that will live alongside the output files and will describe what each file contains. One idea to do it is to attach some description to each "OutputWriter" class we have in code, programmatically generate readme.md file from it and upload it to the storage together with the rest of the files.

**Comment by dkurepa** [comment]
Pr link: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22587

**Comment by dkurepa** [comment]
The previous PR was abandoned. The PR that added the changes was https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22600. We added a README.md to the MatrixOfTruthCli project that gives a list of all available outputs and describes them in a few sentances
