### ISSUE TITLE
Tracking issue for AzDO IcM: "AzureDevOps: Tests results search for a build are non deterministic"

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9035]
https://portal.microsofticm.com/imp/v3/incidents/details/301407309/home

This issue is that when searching test results in a build, the search results returns partial results... and more results each time you search (search and get one, search a minute later, and now there are seven).

It causes customers not to be able to tell what tests are actually running, which makes bring up new platforms/features difficult, since it's possible to miss coverage in the complex matrix.

This was reported by a customer in an email thread when we were discussing their usage patterns. (They are relying on _other_ services they are maintaining to solve this basic bug in AzDO)

**Comment by ilyas1974** [comment]
Feature request - https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1943353 has been submit. We are currently waiting for AzDo to complete this work.

**Comment by ilyas1974** [comment]
Per comments in ICM - work has been prioritized for the next sprint.

**Comment by missymessa** [comment]
AzDO team made some changes to the UI, so I followed up with customers who had reported the issue to us originally. Even though the results load in chunks, upon filtering/searching, the issue still remains where it does not return all the results expected. Followed up with the AzDO team regarding this functionality still not working. (Conversation in private Team channel)

**Comment by missymessa** [comment]
Following up: AzDO had a conversation with one of our product team customers and came to an agreement of how to further improve the searching, especially when there are millions of test results.

**Comment by missymessa** [comment]
Checked in on the state of the feature on AzDO's side and they said they resolved it in August. Closing this.
