### ISSUE TITLE
Sentiment tracker Links to AzDO issues don't go to the issue

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9036]
Issues that are created with links back to issues in AzDO are not properly linked. For example: https://github.com/dotnet/arcade/issues/9029, the link in here will return a JSON object instead of taking the user to the linked issue. This makes it difficult to look at the issue without digging around in the JSON for link to the actual issue.

**Comment by adiaaida** [comment]
Putting this in my epic. Thanks for the report!

**Comment by adiaaida** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/22542

**Comment by adiaaida** [comment]
PR is checked in,. Moving to rollout

**Comment by adiaaida** [comment]
This rolled out
