### ISSUE TITLE
dnceng/internal TFS work item 2648

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9043]
[dnceng/internal work item](https://dev.azure.com/dnceng/internal/_workitems/edit/2648)

**Comment by dkurepa** [comment]
I kicked off image patching as a part of https://github.com/dotnet/arcade/issues/9052. Once our images are patched we can create a VM to see if the patches were applied

**Comment by ChadNedzlek** [comment]
It sounds like the current stat is just... wait for the deployment and a rescan then?

**Comment by ilyas1974** [comment]
@garath , can you please follow up on this? It appears that the scans associated with this work item have not run since 4/12.

**Comment by garath** [comment]
I'll take a look. Responses will go in the other issue.

**Comment by garath** [comment]
@ilyas1974 

> It appears that the scans associated with this work item have not run since 4/12.

Where do you see that?
