### ISSUE TITLE
Monthly Windows patching

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#9052]
We should do the monthly patching of our windows images

**Comment by dkurepa** [comment]
I've kicked off image patching with ImageFactoryCLI

**Comment by dkurepa** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22346

**Comment by lpatalas** [comment]
There is one missing update for `Helix-Client-Ent-21H2-ES-ES-VS2019-Pre-Ent_*` base image. I will regenerate the image and then merge the PR.

**Comment by MattGal** [comment]
Rolled out today, closing.
