### ISSUE TITLE
Adopt new AzDO public upstream feature

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9059]
Azure DevOps has completed work to allow upstreaming from one public Azure DevOps feed to another.  This allows for improvements to how we construct 

[Upstreams for public feeds spec](https://microsoft.sharepoint.com/:w:/r/teams/AzureArtifacts/_layouts/15/doc2.aspx?sourcedoc=%7BE6A1324F-FB20-45BC-ADF5-ED7D4E381EB7%7D&file=Upstreams%20for%20Public%20Feeds%20Spec.docx&action=default&mobileredirect=true&share=IQFPMqHmIPu8Ra317X1OOB63AVreKXRtUx1jBci_hb45Bds&CID=4C8E150A-3568-4078-A4AA-7C9301C260F0&wdLOR=c2BCD4598-B2E1-4FB0-A4FC-865883CDF8A8)

It may not be entirely possible to converge to a single feed in every .NET Core repo, but this should allow for significant simplification of this.

This is likely an epic-scope task, so I'm labelling it to discuss at triage. @mmitche FYI.

**Comment by riarenas** [comment]
converging into a single feed should be possible for our normal transport and product feeds, such as dotnet-eng, dotnet-tools, dotnet7-transport etc... and it should be minimally disruptive.

I think we will still need to have multiple feeds in our nuget.configs because of stable versions though.

**Comment by garath** [comment]
This conversation is happening in email right now. Let this issue idle while that resolves.

**Comment by garath** [comment]
The email convo indicates this won't be adopted. But it's a tool for use. Closing.
