### ISSUE TITLE
CG alerts for dotnet-arcade

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#9076]
Per the newest scan, we have some additional CG alerts to address in the dotnet-arcade repo

https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-arcade?_a=alerts&typeId=6283540&alerts-view-option=active

Please note, there are issues in the main, release-3.x, release-5.x and release-6.x branches.

**Comment by ilyas1974** [comment]
Main is complete. Currently working on backporting to release branches.

**Comment by AlitzelMendez** [comment]
I will be updating this comment with open prs.

release-6.x: 
- https://github.com/dotnet/arcade/pull/9241
- https://github.com/dotnet/arcade/pull/9097

**Comment by garath** [comment]
Reminder to not forget the release/3.x branch.
