### ISSUE TITLE
Arcade Onboarding documentation updates

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#908]
A couple of issues have come up in our onboarding docs.

1. ADO has updated their [pipeline construction](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts) process that we link to, which means that [these](https://github.com/dotnet/arcade/blob/master/Documentation/VSTS/VSTSOnboarding.md#vsts-pull-request-and-ci-builds) instructions are now out of date and need to be updated accordingly. Also, this new process is a pain if you're working on a dev branch and not master, so we need to file an issue with ADO to have them improve this.
2. We need to change VSTS to ADO I guess lol
3. The [minimal CI sample](https://github.com/dotnet/arcade-minimalci-sample) needs to be updated in terms of new recommended practices and pool information. I'll likely be doing this as a part of my work on getting Helix tests to run.

cc / @chcosta unsure which epic this fits into

**Comment by markwilkie** [comment]
@chcosta - is there still more to do here?

**Comment by chcosta** [comment]
This is largely addressed by (2) https://github.com/dotnet/arcade/pull/924,  (3) https://github.com/dotnet/arcade/pull/971, and (3) https://github.com/dotnet/arcade-minimalci-sample/commit/72a13b7f6436129f8a48f774b657a58407aee57e.

(1) still needs to be addressed.  I'll try to get to it this week.

**Comment by jonfortescue** [comment]
Thanks @chcosta!

**Comment by chcosta** [comment]
Filed https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_workitems/edit/97 to address pipeline creation experience for a dev branch
