### ISSUE TITLE
Create runtime queues for missing queues

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#9081]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The following queues need a "runtime" queue for test jobs redirection to work

- windows.11.amd64.clientpre.open
- windows.10.amd64.android.open
- ubuntu.2004.s390x.experimental.open
- ubuntu.1804.amd64
- windows.10.amd64.server20h2.open
- windows.10.amd64.server2022.es.open
- windows.10.amd64.client21h1.open
- windows.amd64.server2022.open
- windows.10.amd64.serverrs5
- windows.10.amd64
- windows.11.amd64.clientpre
- windows.10.amd64.server2022.es
- windows.10.amd64.client21h1
- windows.10.amd64.server19h1.es
- windows.10.amd64.server20h2
- windows.amd64.server2022
- sles.15.amd64
- sles.12.amd64

**Comment by MattGal** [comment]
I'll do this but leave out ubuntu.2004.s390x.experimental.open; this is an on-prem queue that runtime maintains and we do not ever connect to or have access to.

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/22529

**Comment by MattGal** [comment]
Rolled out today, closing.
