### ISSUE TITLE
enable Tls 1.2 on Windows 7

### ISSUE THREAD

**Issue by wfurt** [dotnet/arcade#9094]
This is follow-up on https://github.com/dotnet/core-eng/issues/15558 and related to https://github.com/dotnet/runtime/pull/67935
There was change in Helix to enable all protocols via registry since were able to get approval for that.
However Tls .12 is still not working on Windows 7 and we are failing to connect to external sites. 
Unlike other Windows versions, Windows 7 needs additional setting to make it work.

https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392
We will also need to add `DisabledByDefault=0` for both Client and Server. 
AFAIK it is ok to add that for all Windows if that is easier than just adding it for Windows 7.

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/22625

**Comment by MattGal** [comment]
PR is merged and I verified ([sample helix log](https://helixre8s23ayy6tv7v8isja.blob.core.windows.net/results-3f56c4bfc4f24225a8/testing-tls-2/1/console.ca087efa.log?helixlogtype=result)) that I can access corefx-net-http11.azurewebsites.net from a Windows.7 Helix machine now.  This should roll out next Weds (@wfurt FYI)

**Comment by wfurt** [comment]
Thanks @MattGal

**Comment by MattGal** [comment]
This rolled out today, closing.
