### ISSUE TITLE
Chi-Squared data is no longer updating

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#9096]
The query is getting killed by Kusto with:

 Query execution has exceeded the allowed limits (80DA0003): Query result set has exceeded the internal data size limit 67108864 (E_QUERY_RESULT_SET_TOO_LARGE; see https://aka.ms/kustoquerylimits).

So it's stuck, and won't ever "get passed" the day it's stuck on.

We need to do something about this poor query.

**Comment by markwilkie** [comment]
The right long term fix is probably "streaming" mode:  A sample: https://github.com/zivcaspi/kusto-samples-query-v2/blob/master/Program.cs

However, a stopgap could be: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/22469?_a=files

(info courtesy of @ChadNedzlek )

**Comment by missymessa** [comment]
PR into Arcade Services that adds the new "streamable" method has been merged. Will update Helix Services with the new version of Arcade Services when it's ready.

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/23628
