### ISSUE TITLE
Commonize Debian package tooling

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#912]
We have almost identical code in several repos to produce debian files. The most up to date version of this tool lives in https://github.com/dotnet/core-setup/tree/master/tools-local/setuptools/dotnet-deb-tool. Variations of this tool are used by aspnet and dotnet/cli to produce Debian packages.

It would be good to move the source for that tool into this repo and unify aspnet and dotnet to use it.

**Comment by markwilkie** [comment]
@dleeapho - is this something your team is looking into?

**Comment by dleeapho** [comment]
I'm not immediately looking at this but it is my intent that we do so at some point. Thoughts @rakeshsinghranchi ?

**Comment by markwilkie** [comment]
@dleeapho - should this issue stay in Arcade or move to another repo?

**Comment by rakeshsinghranchi** [comment]
Issue is in core-setup : https://github.com/dotnet/core-setup/issues/3718  . This can be moved and prioritized.

**Comment by markwilkie** [comment]
closed per @rakeshsinghranchi
