### ISSUE TITLE
Update VS2022 base images

### ISSUE THREAD

**Issue by lpatalas** [dotnet/arcade#9123]
Based on [schedule](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/899/VS2022-Upgrade-Schedule):
- For regular and scouting release we should update to `17.1.5` which contains some security patches.
- For preview there's new `17.2 Preview 4` which should go to preview scouting

**Comment by lpatalas** [comment]
PR for base image update: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22499

**Comment by lpatalas** [comment]
PR for yaml definitions: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22535

**Comment by MattGal** [comment]
Rolled out today, closing.
