### ISSUE TITLE
Broken links on One Pager template

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9129]
(Would just make this fix, but I'm in the middle of another thing and don't want to context switch, so documenting it here so it gets done eventually). 

Links are broken on this page: https://github.com/dotnet/arcade/blob/main/Documentation/Project-Docs/one-pager-template.md, specifically in the Housekeeping subheading where things still point back to core-eng repo or deleted wiki pages in AzDO.

**Comment by adiaaida** [comment]
PR: https://github.com/dotnet/arcade/pull/9155

**Comment by adiaaida** [comment]
Fixed!
