### ISSUE TITLE
Fix VM cleaner after updating Azure Table support libraries

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9131]
Found during today's rollout and I over-zealously rolled back because the cleaner is more important in prod than staging.  

@ulisesh is already working on a fix;  if this is healthy in staging by EOD we should do the rollout again tomorrow as no other issues have been noted.

**Comment by ulisesh** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22516

**Comment by MattGal** [comment]
Rolled out today, closing.
