### ISSUE TITLE
Fix console logger in ImageFactoryCli

### ISSUE THREAD

**Issue by lpatalas** [dotnet/arcade#9139]
We have downgraded the versions of some packages in #8773 and that broke console logging in ImageFactoryCli because console logger was no longer registered by default.

- For example: https://dev.azure.com/dnceng/internal/_build/results?buildId=1730634&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=45862c6e-83c5-515f-73e2-e7009eff9f9b&l=12.
- Correct output: https://dev.azure.com/dnceng/internal/_build/results?buildId=1724192&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=45862c6e-83c5-515f-73e2-e7009eff9f9b&l=12

**Comment by lpatalas** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22534

**Comment by ulisesh** [comment]
Thanks for fixing this @lpatalas

**Comment by premun** [comment]
@lpatalas this can be closed?
