### ISSUE TITLE
Investigate/workaround ImageFactory logging limits

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9148]
I needed an issue to make a PR to test image generation;  per @ChulHul when ImageFactory sees 50,001 lines of text or greater logged from an image's packer scripts, it hangs and times out image generation.

**Comment by ChulHul** [comment]
if you remove Set-PSDebug -Trace 1 from this file, https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=%2Fartifacts%2Fwindows-prep%2Futil.ps1, it'll fix it.

**Comment by MattGal** [comment]
I already did yes

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/22540

**Comment by MattGal** [comment]
Rolled out today, closing.
