### ISSUE TITLE
Look for known issues in Helix logs

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#9152]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

**Comment by markwilkie** [comment]
Perhaps can be done via https://github.com/dotnet/arcade/issues/9057

**Comment by Pilchie** [comment]
:eyes:

**Comment by ulisesh** [comment]
The proposed process is:
- Create a new label for known test issues - "Known Test Error"
- Build Analysis fetches the error message from all issues with the new label and looks for them in the logs of failed tests in the PR
- Developers see known test error matches in the build analysis check

cc @AlitzelMendez @markwilkie @missymessa

**Comment by markwilkie** [comment]
@AlitzelMendez / @ulisesh - I think this is a dupe?

**Comment by AlitzelMendez** [comment]
@markwilkie I think it is.
I will close it because this was already rolled out but if it was something else, please feel free to reopen it.
