### ISSUE TITLE
Make life on slow connections easier

### ISSUE THREAD

**Issue by kant2002** [dotnet/arcade#9156]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

As requested in #7910 will try to show my pain here to facilitate discussion.

Consider scenario where external contributor of dotnet runtime, for example, have bad internet connection where downloading NET takes more then 20 minutes. You run, wait 20 min, fail. Try again because it’s not very obvious what happens, maybe it’s network glitch. That can repeat couple times until you give up. Either you abandon idea of contribution this time, or start troubleshooting. I would speculate that most people do now know how Arcade do it’s magic. Finding location where dotnet downloads was not very obvious for me first time. So in hope that having explicit download timeout in the Arcade code can helps with finding such value, because Timeout is nice searchable term.

Reason why I do not want increase value following — 20 minutes is already a lot of time, and if some network issues arise it’s really depends on the environment. And larger value can make troubleshooting bad networking in CI a pain.

Indirect pain for me was that I did not know where to configure timeouts. I also independently hit issue with Wix downloading on older version, so I incorrectly understand problem and add https://github.com/dotnet/msbuild/pull/7541, only to realize that it's fixed by @MichalStrehovsky in  #8385. Experience troubleshooting Wix download was fine since I clearly saw `proj` file which has issue, and it was a matter of applying timeout. My incorrect assumption about `DownloadTask` source was my mistake. If I hit error in https://github.com/dotnet/arcade/blob/fd571576503ab207ecb12ee6ec0611fed1d1e987/src/Microsoft.DotNet.Build.Tasks.Installers/build/acquisition/acquire-nuget-exe/acquire-nuget-exe.proj#L12-L15 then probably I would figure out that I should manually set Timeout because it is task from Arcade https://github.com/dotnet/arcade/blob/fd571576503ab207ecb12ee6ec0611fed1d1e987/src/Microsoft.DotNet.Build.Tasks.Installers/build/acquisition/acquire-nuget-exe/acquire-nuget-exe.proj#L3

**Comment by kant2002** [comment]
@riarenas do I explain my problem in this issue? Or I need to provide additional information? From what I see in PR comments, it's somewhat painful problem for some people.

**Comment by adiaaida** [comment]
@YuliiaKovalova can the install scripts team take on improving the logging in the install scripts when download fails due to timeout so that we can consume that in a more useful way in arcade?

**Comment by YuliiaKovalova** [comment]
Hi @adiaaida ,

I am discussing this topic with management.
Once I have the response I will return to you.

**Comment by adiaaida** [comment]
Thanks!

**Comment by kant2002** [comment]
@ChadNedzlek no. This is not resolved. Progress does not help when you are on slow but reliable connection. You need to control timeout and that’s why I did create #7910 . What’s the point seeing progress, see that it fails and now what?

**Comment by ChadNedzlek** [comment]
Gotcha. I'll reopen. :-)

**Comment by kant2002** [comment]
I still constantly experience this issue when I nuke dotnet/runtime repo from time to time.

**Comment by garath** [comment]
This issue and the linked PR have become stale, so closing. If more progress is made on a solution we can reopen.
