### ISSUE TITLE
imagefactory-cli should wait until image creation is finished before cleaning resources

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#9157]
The scenario test run by the Image Factory CLI submits to Image Factory a request for a new image, then immediately checks for and deletes the VHD that is created. This deletion happens while the image is still being copied from IF, causing exceptions and bad behavior within the service. @ChulHul reached out to ask that the test instead wait at least until after this operation is finished before cleaning up resources. 

The scenario test method is [[here](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/test/ImageFactoryCli.ScenarioTests/ProcessTemplatesTests.cs&version=GBmain&line=66&lineEnd=67&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)]. Deletion happens in disposal [[here](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/test/ImageFactoryCli.ScenarioTests/ProcessTemplatesTests.cs&version=GBmain&line=153&lineEnd=166&lineStartColumn=8&lineEndColumn=10&lineStyle=plain&_a=contents)]. Note that waiting until the VHD is complete will also probably require the test to clean-up the compute image that gets created for it.

**Comment by premun** [comment]
The scenario tests were deleted this week because they had little value and a high maintenance cost.

More details: https://github.com/dotnet/arcade/issues/9177
