### ISSUE TITLE
Update expired Win10 21h1 marketplace image

### ISSUE THREAD

**Issue by lpatalas** [dotnet/arcade#9158]
Marketplace image for `windows.10.amd64.client21h1.open` expired as seen here [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=1732444&view=logs&j=9f602f64-2450-51a0-e2eb-2e7e093ff59e&t=60c6cf17-2b11-597e-4355-2adb9530f56e&l=251).

PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22547

**Comment by lpatalas** [comment]
Merged. Just have to double check if it fixes [main build](https://dev.azure.com/dnceng/internal/_build/results?buildId=1732818).

**Comment by MattGal** [comment]
Rolled out today, closing
