### ISSUE TITLE
Investigate if zip files are being correctly signed

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#916]
@mikem8361 reported that the signing of zip files seems to not be working properly. Here is a [sample build](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2FDevDiv%2FDevDiv%2520Team%2F_build%2Fresults%3FbuildId%3D2082206%26view%3Dlogs&data=02%7C01%7CDivino.Cesar%40microsoft.com%7C50224798db514571850b08d628b99d81%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636741175378584599&sdata=7zo0Hb7J40raInbaE5CTfAFaAooJFGqvxEvNeg2iCs4%3D&reserved=0). 

> I just checked my latest build and it is the same thing: all the nupkg binaries are signed, but none of the zip files are.  The build.binlog does show the right ItemsToSign, but it doesn’t show the zip files being repackaged like it does for the nupkgs.  I think some of my changes got lost in the transient or there are some assumptions that break the zip files.

**Comment by mikem8361** [comment]
Maybe I’m mistaken but I think zip files can’t be signed like nupkg’s can (even though nupkgs are zip files).

What cert would I use for zips?

mikem

**Comment by JohnTortugo** [comment]
You're right. I don't think there is a certificate for zip files. 

I took a look at you changes when you added the support for the .zip files. The idea was to extract the zip, sign only the content and then repack the zip, right? It seems that when we added the support for .extension mapping we accidentally 'disabled' that.

I'm looking what we can do to fix that.

**Comment by mikem8361** [comment]
@JohnTortugo can you let me know what the version of the new signtool package is or what version of the arcade SDK the new signtool will be in.  Thanks.

**Comment by JohnTortugo** [comment]
> @JohnTortugo can you let me know what the version of the new signtool package is or what version of the arcade SDK the new signtool will be in. Thanks.

Yeap, I'll send it to you.

**Comment by mikem8361** [comment]
@JohnTortugo what version of the Arcade SDK or the signtool did this change go into?

**Comment by JohnTortugo** [comment]
Hey @mikem8361, I believe it was around `1.0.0-beta.18511.3`, but can you try the latest version - `1.0.0-beta.18516.5`?

**Comment by markwilkie** [comment]
This discussion indicates a need for a change log.  @JohnTortugo, would you mind filing an issue please to make sure we do this?
