### ISSUE TITLE
Remove Git installation from images with VS on them

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9166]
([Related issue](https://github.com/dotnet/arcade/issues/9165)) We keep our Visual Studio 2017, 2019, and 2022 images up to date with the latest public versions of the respective image.  As a result, sometimes the Git client that comes with these is actually slightly newer than what we're trying to install, resulting in image timeouts (due to the related issue).  

Since we know VS comes with Git and this is unlikely to ever change, we should remove this artifact whenever the image is known to have VS on it; this would prevent even the chance of this modal dialog from popping and would get free automatic updating from the VS public channels.

**Comment by premun** [comment]
We could also make the artifact check if a newer git is available and finish with a warning?

But if we go down the road of removal, we should add unit tests testing presence of either `windows-vs` or `windows-git` so that we don't end up without git entirely

**Comment by MattGal** [comment]
I don't super care how we address it but this problem has been repeatedly happening (VS updates keep updating Git) so as long as the underlying problem is addressed that works too.

**Comment by premun** [comment]
@MattGal @ilyas1974 can we give this to @andriipatsula as something to start with slowly?

**Comment by MattGal** [comment]
@premun sounds good to me

**Comment by tkapin** [comment]
Thanks @ilyas1974, @MattGal

**Comment by andriipatsula** [comment]
Hello @MattGal . I plan to add UT to check that for windows images there should be always either windows-git, or windows-vs artifact; to be sure that all windows images have git installed. Could I consider that this is a valid test case and we'll never have windows images without git?

**Comment by andriipatsula** [comment]
List of windows images with `windows-git` artifact and without `windows-vs`

- windows.10.amd64.serverrs5
- windows.10.amd64.serverrs5.open
- windows.10.amd64.server20h2.open
- windows.10.amd64.server20h2
- windows.10.amd64.19h1.tiger.perf
- windows.10.amd64.19h1.tiger.perf.open
- windows.10.amd64.19h1.snake.perf.open
- windows.10.amd64.20h2.owl.perf
- windows.10.amd64.android.open
- windows.10.amd64.pixel.perf
- windows.10.amd64.galaxy.perf
- build.windows.10.amd64.open
- windows.10.amd64.serverrs5.rt
- windows.10.amd64.serverrs5.open.rt
- windows.10.amd64.server20h2.rt
- windows.10.amd64.server20h2.open.rt
- windows.amd64.server2022.rt
- windows.amd64.server2022.open.rt
- windows.10.amd64.server20h2.svc
- windows.10.amd64.server20h2.open.svc
- windows.10.amd64.serverrs5.open.svc
- windows.10.amd64.serverrs5.svc

**Comment by premun** [comment]
And a list without either?

**Comment by andriipatsula** [comment]
the list of queues without windows-git and without windows-vs
- windows.7.amd64
- windows.7.amd64.open
- windows.10.amd64
- windows.10.amd64.open
- windows.10.amd64.x86
- windows.81.amd64
- windows.81.amd64.open
- windows.10.amd64.appcompat
- windows.10.amd64.appcompatpr
- windows.10.amd64.core
- windows.10.amd64.clientrs5.open
- windows.10.amd64.clientrs5
- windows.10.amd64.clientrs5.open.xaml
- windows.10.amd64.clientrs5.xaml
- windows.10.amd64.clientrs5.open.reunion
- windows.10.amd64.clientrs5.reunion
- windows.10.amd64.server2022.es.open
- windows.10.amd64.server2022.es
- windows.10.amd64.client20h2.xaml
- windows.10.amd64.client20h2.reunion
- windows.10.amd64.client20h2.open.reunion
- windows.10.amd64.client21h1.open
- windows.10.amd64.client21h1
- windows.10.amd64.client21h1.xaml
- windows.10.amd64.client21h1.open.xaml
- windows.10.amd64.client21h1.reunion
- windows.10.amd64.client21h1.open.reunion
- windows.amd64.server2022.open
- windows.amd64.server2022
- windows.10.arm64
- windows.10.arm64.appcompat
- windows.10.arm64.tof
- windows.10.arm64.open
- windows.10.arm64v8.open
- windows.10.arm32
- windows.10.arm32.open
- windows.10.arm32.iot
- windows.10.arm32.iot.open
- windows.10.arm64.perf
- windows.10.arm64.perf.surf
- windows.server.arm64.perf
- windows.11.arm64
- windows.11.arm64.open
- windows.11.amd64.cet
- windows.11.amd64.cet.open
- windows.10.amd64.arcade
- windows.10.amd64.open.arcade
- windows.11.amd64.client.open
- windows.11.amd64.client
- windows.11.amd64.client.xaml
- windows.11.amd64.client.open.xaml
- windows.11.amd64.client.reunion
- windows.11.amd64.client.open.reunion
- windows.11.amd64.clientpre
- windows.11.amd64.clientpre.open
- windows.7.amd64.rt
- windows.7.amd64.open.rt
- windows.81.amd64.rt
- windows.81.amd64.open.rt
- windows.10.amd64.rt
- windows.10.amd64.open.rt
- windows.10.amd64.x86.rt
- windows.10.amd64.core.rt
- windows.10.amd64.clientrs5.open.rt
- windows.11.amd64.client.rt
- windows.11.amd64.client.open.rt
- windows.10.amd64.client21h1.rt
- windows.10.amd64.client21h1.open.rt
- windows.10.amd64.server2022.es.rt
- windows.10.amd64.server2022.es.open.rt
- windows.10.amd64.svc
- windows.10.amd64.client21h1.open.svc
- windows.10.amd64.client21h1.svc
- windows.10.amd64.clientrs5.open.svc
- windows.10.amd64.clientrs5.svc
- windows.10.amd64.core.svc
- windows.10.amd64.open.svc
- windows.10.amd64.server2022.es.svc
- windows.10.amd64.server2022.es.open.svc
- windows.amd64.server2022.open.svc
- windows.amd64.server2022.svc
- windows.7.amd64.svc
- windows.7.amd64.open.svc
- windows.81.amd64.svc
- windows.81.amd64.open.svc
- windows.11.amd64.clientpre.open.svc
- windows.11.amd64.clientpre.svc
- windows.11.amd64.client.open.svc
- windows.11.amd64.client.svc

**Comment by andriipatsula** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22954

**Comment by MattGal** [comment]
> https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22954

Generally we keep these open until they roll out, which may not be until next week.

**Comment by andriipatsula** [comment]
reopening till Roll Out

**Comment by MattGal** [comment]
Rolled out today, closing.
