### ISSUE TITLE
Investigate assigning devices to queues in OsobInventory table

### ISSUE THREAD

**Issue by lpatalas** [dotnet/arcade#9188]
We have mobile devices listed in `OsobInventory` table but the column that usually stores queue name just have `Tethered Android Device` or `Tethered Apple Device` value instead. If we could fill device rows with proper queue names that would enable us to automatically consume this data in matrix of truth tooling to present number and types of devices available on each queue.

**Comment by lpatalas** [comment]
We discussed it with @ilyas1974 and apparently there is a consistent mapping between device names and machine names to which the device is connected, for example Android device `DNCENGDRD-XXX` is always connected to `DNCENGWIN-XXX`. We could use this fact to get list of devices available in given Helix queue directly from `OsobInventory` without the need to specify it in yaml.

There are two issues:
1. I don't know what's the mapping for Apple devices though. I see those types:
    - `DNCENGOSX-XXX`
    - `DNCENGTVOS-XXX`
    - `PERFIOS-XXX`
2. `MachineType` needs to be more specific. Currently we see just `iphone` there but we would like to know which iPhone model it is.

**Comment by ilyas1974** [comment]
I have uploaded the device to host machine mapping to a new Azure table called OsobDeviceMapping within the helixscripts 2 storage account in the Helix Subscription. 

The MachineType request is being addressed in https://github.com/dotnet/arcade/issues/9107
