### ISSUE TITLE
Update ARM64 Galaxybook machines to newer builds

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9193]
I have offlined Helix machine DDARM64-136 and @hoyosjs is investigating updating OS builds on it that work better for CoreCLR testing.

This issue is just tracking for now; if he finds a build that reliably works and unblocks CoreCLR tests, we may have a follow up issue to reimage these machines.

**Comment by MattGal** [comment]
Created https://portal.microsofticm.com/imp/v3/incidents/details/304521978/home , @Chrisboh FYI

**Comment by ilyas1974** [comment]
90 of 132 systems have bene updated and are back online. DDFUN is waiting on MLS on the remaining system

**Comment by ilyas1974** [comment]
Galaxy books have been updated. While we do have some systems still offline, that work is not related to these updates. Closing this issue as complete.

**Comment by premun** [comment]
I disabled `DDARM64-159`

**Comment by ilyas1974** [comment]
This issue has been resolved - the issue being reported has to do with reporting and not the actual machines. I have created https://github.com/dotnet/arcade/issues/9788 to address the reporting issue.
