### ISSUE TITLE
Apple & Android devices are in horizontal position

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#9195]
Some of the devices are in horizontal position which means apps need to rotate after they are started.

This potentially skews the startup time of the app which we are measuring (it then differs between machines).

We need to ask DDFUN to enable a rotation lock while in portrait mode.

**Comment by premun** [comment]
IcM for iPhones - https://portal.microsofticm.com/imp/v3/incidents/details/304438748/home

**Comment by premun** [comment]
Android phones can be done through ADB:
> adb shell settings put system accelerometer_rotation 0

You can also force a specific rotation:
> adb shell settings put system user_rotation 3 #270° clockwise

**Comment by premun** [comment]
All 122 Android devices in the main queue were locked for rotation by job `a73174e6-a0c9-4d37-998b-8df7be800678`

**Comment by ilyas1974** [comment]
This has been resolved on existing systems and added to the documentation for additional deployments.
