### ISSUE TITLE
The agent did not connect within the alloted time of 45 minute(s).

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#9207]
### Build

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1741176

### Build leg reported

Windows_NT debug_configuration

### Pull Request

https://github.com/dotnet/arcade-services/pull/1876

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "The agent did not connect within the alloted time"
 }
 ```

### Report
|Build|Definition|Step Name|Console log|
|---|---|---|---|
|[1866644](https://dev.azure.com/dnceng/public/_build/results?buildId=1866644)|dotnet/arcade|SourceIndexStage1|
|[1866654](https://dev.azure.com/dnceng/public/_build/results?buildId=1866654)|dotnet/arcade|SourceIndexStage1|
|[1868790](https://dev.azure.com/dnceng/public/_build/results?buildId=1868790)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1869052](https://dev.azure.com/dnceng/public/_build/results?buildId=1869052)|dotnet/arcade-services|Windows_NT release_configuration|
|[1867952](https://dev.azure.com/dnceng/public/_build/results?buildId=1867952)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1869203](https://dev.azure.com/dnceng/public/_build/results?buildId=1869203)|dotnet/arcade|SourceIndexStage1|
|[1869152](https://dev.azure.com/dnceng/public/_build/results?buildId=1869152)|dotnet/arcade|SourceIndexStage1|
|[1869153](https://dev.azure.com/dnceng/public/_build/results?buildId=1869153)|dotnet/arcade|Windows_NT|
|[1869070](https://dev.azure.com/dnceng/public/_build/results?buildId=1869070)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1869002](https://dev.azure.com/dnceng/public/_build/results?buildId=1869002)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1868933](https://dev.azure.com/dnceng/public/_build/results?buildId=1868933)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1867689](https://dev.azure.com/dnceng/public/_build/results?buildId=1867689)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1865569](https://dev.azure.com/dnceng/public/_build/results?buildId=1865569)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1865299](https://dev.azure.com/dnceng/public/_build/results?buildId=1865299)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1865655](https://dev.azure.com/dnceng/public/_build/results?buildId=1865655)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1863888](https://dev.azure.com/dnceng/public/_build/results?buildId=1863888)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1866927](https://dev.azure.com/dnceng/public/_build/results?buildId=1866927)|dotnet/aspnetcore|Tests: Helix x64|
|[1866717](https://dev.azure.com/dnceng/public/_build/results?buildId=1866717)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1866657](https://dev.azure.com/dnceng/public/_build/results?buildId=1866657)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1866608](https://dev.azure.com/dnceng/public/_build/results?buildId=1866608)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1866457](https://dev.azure.com/dnceng/public/_build/results?buildId=1866457)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1866595](https://dev.azure.com/dnceng/public/_build/results?buildId=1866595)|dotnet/arcade|SourceIndexStage1|
|[1861223](https://dev.azure.com/dnceng/public/_build/results?buildId=1861223)|dotnet/sdk|Windows_NT_TestAsTools Build_Debug|
|[1864836](https://dev.azure.com/dnceng/public/_build/results?buildId=1864836)|dotnet/installer|Windows_NT Build_Release_arm64|
|[1863359](https://dev.azure.com/dnceng/public/_build/results?buildId=1863359)|dotnet/runtime|CoreCLR  Pri1 Runtime Tests Run  windows x64 checked|
|[1862606](https://dev.azure.com/dnceng/public/_build/results?buildId=1862606)|dotnet/roslyn|Build_Windows_Release|
|[1861549](https://dev.azure.com/dnceng/public/_build/results?buildId=1861549)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1861514](https://dev.azure.com/dnceng/public/_build/results?buildId=1861514)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1860378](https://dev.azure.com/dnceng/public/_build/results?buildId=1860378)|dotnet/installer|Windows_NT Build_Release_x64|
|[1861210](https://dev.azure.com/dnceng/public/_build/results?buildId=1861210)|dotnet/aspnetcore|Build: Windows x64/x86/arm64|
|[1861408](https://dev.azure.com/dnceng/public/_build/results?buildId=1861408)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1861577](https://dev.azure.com/dnceng/public/_build/results?buildId=1861577)|dotnet/aspnetcore|Tests: Helix x64|
|[1861579](https://dev.azure.com/dnceng/public/_build/results?buildId=1861579)|dotnet/aspnetcore|Tests: Windows x64|
|[1861581](https://dev.azure.com/dnceng/public/_build/results?buildId=1861581)|dotnet/runtime|Mono  Product Build Linux arm64 release|
|[1861420](https://dev.azure.com/dnceng/public/_build/results?buildId=1861420)|dotnet/runtime|Libraries Test Run release coreclr windows arm64 Release|
|[1861676](https://dev.azure.com/dnceng/public/_build/results?buildId=1861676)|dotnet/aspnetcore|Test: Templates - Windows Server 2016 x64|
|[1861604](https://dev.azure.com/dnceng/public/_build/results?buildId=1861604)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1865463](https://dev.azure.com/dnceng/public/_build/results?buildId=1865463)|dotnet/runtime|Libraries Build Windows_NT net48 x86 Release|
|[1866530](https://dev.azure.com/dnceng/public/_build/results?buildId=1866530)|dotnet/aspnetcore|Tests: Windows x64|
|[1866565](https://dev.azure.com/dnceng/public/_build/results?buildId=1866565)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1866800](https://dev.azure.com/dnceng/public/_build/results?buildId=1866800)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1866809](https://dev.azure.com/dnceng/public/_build/results?buildId=1866809)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1866863](https://dev.azure.com/dnceng/public/_build/results?buildId=1866863)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1866977](https://dev.azure.com/dnceng/public/_build/results?buildId=1866977)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1866929](https://dev.azure.com/dnceng/public/_build/results?buildId=1866929)|dotnet/aspnetcore|Tests: Windows x64|
|[1867064](https://dev.azure.com/dnceng/public/_build/results?buildId=1867064)|dotnet/installer|Windows_NT Build_Release_arm|
|[1866816](https://dev.azure.com/dnceng/public/_build/results?buildId=1866816)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1867121](https://dev.azure.com/dnceng/public/_build/results?buildId=1867121)|dotnet/installer|PGO_Windows_NT Build_Release_arm64|
|[1867195](https://dev.azure.com/dnceng/public/_build/results?buildId=1867195)|dotnet/aspnetcore|Tests: Windows x64|
|[1867193](https://dev.azure.com/dnceng/public/_build/results?buildId=1867193)|dotnet/aspnetcore|Tests: Helix x64|
|[1866976](https://dev.azure.com/dnceng/public/_build/results?buildId=1866976)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1866979](https://dev.azure.com/dnceng/public/_build/results?buildId=1866979)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1867380](https://dev.azure.com/dnceng/public/_build/results?buildId=1867380)|dotnet/installer|Windows_NT Build_Release_x64|
|[1868676](https://dev.azure.com/dnceng/public/_build/results?buildId=1868676)|dotnet/aspnetcore|Tests: Windows x64|
|[1868674](https://dev.azure.com/dnceng/public/_build/results?buildId=1868674)|dotnet/aspnetcore|Tests: Helix x64|
|[1868603](https://dev.azure.com/dnceng/public/_build/results?buildId=1868603)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1868782](https://dev.azure.com/dnceng/public/_build/results?buildId=1868782)|dotnet/aspnetcore|Tests: Windows x64|
|[1868787](https://dev.azure.com/dnceng/public/_build/results?buildId=1868787)|dotnet/aspnetcore|Tests: Helix x64|
|[1868841](https://dev.azure.com/dnceng/public/_build/results?buildId=1868841)|dotnet/installer|PGO_Windows_NT Build_Release_arm64|
|[1868851](https://dev.azure.com/dnceng/public/_build/results?buildId=1868851)|dotnet/installer|PGO_Windows_NT Build_Release_arm64|
|[1868932](https://dev.azure.com/dnceng/public/_build/results?buildId=1868932)|dotnet/sdk|Windows_NT_FullFramework Build_Debug|
|[1868789](https://dev.azure.com/dnceng/public/_build/results?buildId=1868789)|dotnet/aspnetcore|Tests: Windows x64|
|[1868670](https://dev.azure.com/dnceng/public/_build/results?buildId=1868670)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1868937](https://dev.azure.com/dnceng/public/_build/results?buildId=1868937)|dotnet/arcade|Windows_NT|
|[1868936](https://dev.azure.com/dnceng/public/_build/results?buildId=1868936)|dotnet/arcade|SourceIndexStage1|
|[1868843](https://dev.azure.com/dnceng/public/_build/results?buildId=1868843)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1868967](https://dev.azure.com/dnceng/public/_build/results?buildId=1868967)|dotnet/aspnetcore|Tests: Windows x64|
|[1868941](https://dev.azure.com/dnceng/public/_build/results?buildId=1868941)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1869064](https://dev.azure.com/dnceng/public/_build/results?buildId=1869064)|dotnet/aspnetcore|Tests: Windows x64|
|[1869062](https://dev.azure.com/dnceng/public/_build/results?buildId=1869062)|dotnet/aspnetcore|Tests: Helix x64|
|[1868976](https://dev.azure.com/dnceng/public/_build/results?buildId=1868976)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1869078](https://dev.azure.com/dnceng/public/_build/results?buildId=1869078)|dotnet/installer|PGO_Windows_NT Build_Release_arm64|
|[1869171](https://dev.azure.com/dnceng/public/_build/results?buildId=1869171)|dotnet/sdk|Windows_NT_FullFramework Build_Debug|
|[1869149](https://dev.azure.com/dnceng/public/_build/results?buildId=1869149)|dotnet/installer|PGO_Windows_NT Build_Release_arm64|
|[1869225](https://dev.azure.com/dnceng/public/_build/results?buildId=1869225)|dotnet/aspnetcore|Tests: Helix x64|
|[1869227](https://dev.azure.com/dnceng/public/_build/results?buildId=1869227)|dotnet/aspnetcore|Tests: Windows x64|
|[1869172](https://dev.azure.com/dnceng/public/_build/results?buildId=1869172)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1884041](https://dev.azure.com/dnceng/public/_build/results?buildId=1884041)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1884119](https://dev.azure.com/dnceng/public/_build/results?buildId=1884119)|dotnet/sdk|Windows_NT_FullFramework Build_Debug|
|[1884121](https://dev.azure.com/dnceng/public/_build/results?buildId=1884121)|dotnet/arcade|SourceIndexStage1|
|[1884112](https://dev.azure.com/dnceng/public/_build/results?buildId=1884112)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1881963](https://dev.azure.com/dnceng/public/_build/results?buildId=1881963)|dotnet/sdk|Windows_NT_FullFramework Build_Debug|
|[1881538](https://dev.azure.com/dnceng/public/_build/results?buildId=1881538)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1881612](https://dev.azure.com/dnceng/public/_build/results?buildId=1881612)|dotnet/aspnetcore|Tests: Helix x64|
|[1881614](https://dev.azure.com/dnceng/public/_build/results?buildId=1881614)|dotnet/aspnetcore|Tests: Windows x64|
|[1881245](https://dev.azure.com/dnceng/public/_build/results?buildId=1881245)|dotnet/runtime|Libraries Test Run release coreclr windows arm64 Release|
|[1881428](https://dev.azure.com/dnceng/public/_build/results?buildId=1881428)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1881582](https://dev.azure.com/dnceng/public/_build/results?buildId=1881582)|dotnet/sdk|Windows_NT_FullFramework Build_Debug|
|[1881398](https://dev.azure.com/dnceng/public/_build/results?buildId=1881398)|dotnet/aspnetcore|Build: Windows x64/x86/arm64|
|[1881597](https://dev.azure.com/dnceng/public/_build/results?buildId=1881597)|dotnet/arcade-services|Windows_NT release_configuration|
|[1881461](https://dev.azure.com/dnceng/public/_build/results?buildId=1881461)|dotnet/sdk|Windows_NT_FullFramework Build_Debug|
|[1881320](https://dev.azure.com/dnceng/public/_build/results?buildId=1881320)|dotnet/installer|PGO_Windows_NT Build_Release_x86|
|[1881189](https://dev.azure.com/dnceng/public/_build/results?buildId=1881189)|dotnet/runtime|Installer Build and Test coreclr  Linux_arm Debug|
|[1881401](https://dev.azure.com/dnceng/public/_build/results?buildId=1881401)|dotnet/aspnetcore|Build: Windows x64/x86/arm64|
|[1879367](https://dev.azure.com/dnceng/public/_build/results?buildId=1879367)|dotnet/aspnetcore|Tests: Helix x64|
|[1879227](https://dev.azure.com/dnceng/public/_build/results?buildId=1879227)|dotnet/roslyn|Test_Windows_CoreClr_Debug_Single_Machine|
|[1879084](https://dev.azure.com/dnceng/public/_build/results?buildId=1879084)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1879266](https://dev.azure.com/dnceng/public/_build/results?buildId=1879266)|dotnet/installer|PGO_Windows_NT Build_Release_arm64|
|[1879041](https://dev.azure.com/dnceng/public/_build/results?buildId=1879041)|dotnet/sdk|Ubuntu_20_04 Build_Release|
|[1879305](https://dev.azure.com/dnceng/public/_build/results?buildId=1879305)|dotnet/sdk|Windows_NT_FullFramework Build_Debug|
Displaying 100 of 347 results
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|347|

**Comment by MattGal** [comment]
The builds are hitting the fact that we're averaging > 820 builds in parallel at once.  I'm investigating to see if we can say who.,

**Comment by garath** [comment]
I'm interested to know how you do the investigation. It seems like this should be added to Grafana.

**Comment by garath** [comment]
Is it worth sending out a message to partners (probably via the FR channel) when these wait times get close to build-timeout range?

**Comment by MattGal** [comment]
@garath I don't think so since there's literally nothing they can do in this case besides retry and they're already doing plenty of that.

**Comment by ChadNedzlek** [comment]
It would be nice if we could auto-retry for them for this sort of thing (since they don't really have any choice but to do that anyway).

**Comment by ChadNedzlek** [comment]
I just lost four legs to this today.  It's making my Mondays completely unproductive, as I have to wait hours and hours, only for my build to get half finished (which tends to REALLY mess up deployments, since they don't expect to half finish) and then rejected... then I have to get back in line all over again, hoping it's not just another wasted 3 hours.

**Comment by premun** [comment]
Seems like a huge spike yesterday, yeah:

![image](https://user-images.githubusercontent.com/7013027/167573542-cbd143ba-6136-4bc5-9391-d85518ad6822.png)

```sql
TimelineIssues
| where Type == "error" and Message contains "The agent did not connect within the alloted time"
| join kind=inner TimelineBuilds on BuildId
| where StartTime > now() - 14d
| order by StartTime desc
| summarize count() by bin(StartTime, 4h)
| order by StartTime
| render areachart
```

**Comment by ulisesh** [comment]
Because of https://github.com/dotnet/arcade/issues/9338 we won't get known issues "matches" until deploy the fix in Build Analysis

**Comment by MattGal** [comment]
I set the Acquistion Timeout to 90 days via AzDO API calls last week and it seems to have worked; The last instance of this logged was in 20220718.18.  Given the agreement of 0 day 24 hour / 7 day hit count, I am optimistically closing this issue.
