### ISSUE TITLE
Rewrite documentation for Helix Job Sender and AzDO Onboarding to reflect new process

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#921]
The documentation is badly out of date and needs to be improved to reflect the new process.

**Comment by jonfortescue** [comment]
@chcosta -- I think you did something like this already, is that correct?

**Comment by chcosta** [comment]
Yes for AzDev.  I haven't gotten to the Helix stuff yet.  I need to get to that today.

**Comment by jonfortescue** [comment]
Awesome. Just assigning this to you for transparency then.
