### ISSUE TITLE
Strong name attributes getting dropped in windowsdesktop signed assets

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#9219]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

DirectWriteForwarder.dll and some other binaries within the WD shared framework do not have valid strong names. This is the case for both 5.0 and 6.0, though 6.0 appears delay-signed, while 5.0 just doesn't have a strong name at all.

The issue here appears to be the re-packaging of DirectWriteForwarder.dll (and others, it's not special). When viewed in context of WPF (post-build signed or not), the binary is given a signature and strong name. Then the binary is repackaged in WindowsDesktop.

In the post-build signing (6.0) case, when the binary is repackaged in WindowsDesktop, it's altered (probably crossgen?). This means that post-build signing will not know that the binary originally came from WPF, and therefore should have signing metadata from WPF. I **think** in this case the signing metadata is wrong for WD, not specifying that a SN should be present. But it does appear that the binary is initially delay signed, coming out of windows desktop.

In the non-post-build signing (5.0) case, it's less clear why there is no strong name signature. The binary is repackaged and probably cross-genned, but it doesn't get delay signed.

**Comment by garath** [comment]
Strong Name signing is not currently supported, but of course we will revisit if it becomes a requirement.
