### ISSUE TITLE
Move Build Analysis out of .NET Helix GitHub app into its own App

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#9221]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

As part of https://github.com/dotnet/arcade/issues/8708 and described in https://github.com/dotnet/arcade/issues/8554#issuecomment-1072688229, we should move the build analysis portion of .NET Helix into its own github app so that we can lock down the access a bit more in the .NET Helix app

**Comment by adiaaida** [comment]
FYI @ChadNedzlek @missymessa @AlitzelMendez @ulisesh

**Comment by missymessa** [comment]
See https://github.com/dotnet/arcade/issues/8625 for historical discussion.

**Comment by AlitzelMendez** [comment]
Pull Request: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/23861

This is a different approach, and I am abandoning the first pr

**Comment by missymessa** [comment]
@AlitzelMendez can you make sure we get the permissions for the app documented for our engineering purposes and why we need those permissions, so that future devs understand the reasons those permissions are there? Thanks!
