### ISSUE TITLE
Prepare VS 2022 images for rollout 2022-05-04

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#9224]
Looks like we need 2 bumps, I updated the schedule:
https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/899/VS2022-Upgrade-Schedule

**Comment by dkurepa** [comment]
The base-image was updated in this pr: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22599

**Comment by dkurepa** [comment]
Pr link: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22612

**Comment by MattGal** [comment]
This rolled out today, closing.
