### ISSUE TITLE
Rotate HelixApiAccessToken 

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#9235]
https://dev.azure.com/dnceng/internal/_build/results?buildId=1736216&view=logs&j=df0a3355-897e-53ae-288d-2f16ccab2822&t=07261306-a000-50cf-efd2-5d677d89250f&l=136

**Comment by MattGal** [comment]
I think this is solved by reading [the readme](https://github.com/dotnet/arcade-services/tree/main/src/Microsoft.DncEng.SecretManager#readme) then running `dotnet secret-manager synchronize --force-secret=HelixApiAccessToken .\.vault-config\helixprodkv.yaml`, rerunning weekly build to check.

**Comment by MattGal** [comment]
verified fixed in attempt 2 of https://dev.azure.com/dnceng/internal/_build/results?buildId=1736216&view=logs&j=adcf571c-cc13-5e72-b2ad-561cfc37a926&t=adcf571c-cc13-5e72-b2ad-561cfc37a926
