### ISSUE TITLE
Create a PowerShell script that does the end-to-end Microbuild cert signing installation for 1es-windows-**** images

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#9240]
Currently, our 1ES hosted provisioning script relies on the presence of helix-prep scripts, which aren't installed on the 1es-windows-**** images. This makes them unable to sign, so we should create a new ps1 that can be executed as part of the provisioning scripts that will do the cert installation so people can sign on these images.

**Comment by Jonnyboy1992** [comment]
#9207

**Comment by MattGal** [comment]
> #9207

This linked issue is unrelated and simply correlates to when the system is so loaded that jobs cannot start within 45 minutes of enqueuing.  That problem is endemic to all 1ES Hosted Pool providers.

**Comment by MattGal** [comment]
Prototype is tested and[ a pr is merged](https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/23616).  Putting this into validate until I can run a real build against the staging environment using the 1es-windows-* image

**Comment by MattGal** [comment]
This rolled out today and works well with the exception of the special "No MSI" pools I made, which have a prototype hotfix.  Am working on this edge case in https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/23712

**Comment by MattGal** [comment]
PR is merged, putting into "Waiting for Rollout" so I can validate things are still functional (no user should be impacted at this point thanks to Wednesday's hotfix), and I will send partners email today recommending the 1es-windows-* pools for this purpose.

**Comment by MattGal** [comment]
This is rolled out and working for typical users, I am going to send a partners mail encouraging its use and close the issue.

**Comment by MattGal** [comment]
woohoo, this is done and working reliably.
