### ISSUE TITLE
iPhone perf queue needs updates (device+host)

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#9248]
### Context

We found out DDFUN haven't originally disabled auto-updates on the phones. This led to the phones downloading the iOS 15.4 update and prompting to install it. We disabled auto-updates but the update is already downloaded and keeps prompting. The prompt causes our tests to hang.

![image](https://user-images.githubusercontent.com/7013027/166429426-a936eaf6-417a-4fb7-8d84-99e9d0b7f8f5.png)

This means:
- We need to install the update
- This means we need to install new Xcode
- That means we need to install MacOS 12
- That means we need to create a new queue and move the devices there, then kill the old queue

### Steps to do

**Before we do the actual update, wait for Premek to test iOS 15.4 device runs first.**

1. Create a new queue `osx.1200.amd64.iphone.perf` with Xcode 13.3 and MacOS 12.00 (this step can be done already)
2. Ask DDFUN to update the MacOS on the existing machines and to update the iPhones (ask them to confirm auto-updates are still off and phones are vertical with rotation lock on)
    Machines are `DNCENGMAC044` and `DNCENGMAC045`
5. [Install Xcode 13.3](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/870/Install-new-version-of-Xcode-on-Helix-machines) on these machines
3. Move the machines into the new queue
4. Remove the old queue

Please keep @LoopedBard3 and @akoeplinger know (through this issue for instance) about any steps as their tests rely on this.

**Comment by premun** [comment]
Putting to blocked while I try out iOS 15.4 on my test device

**Comment by premun** [comment]
We are first trying a factory reset to see whether this will remove the downloaded update

**Comment by premun** [comment]
![image](https://user-images.githubusercontent.com/7013027/166932040-12280003-a500-4f89-bdb3-4f769be220ff.png)

There's a new dialog after the factory reset

**Comment by premun** [comment]
@akoeplinger the dialog should be cleared. DDFUN followed the steps from the blog post to "finish the setting up later".

Let me know how it goes, we can re-open this again if you see hangs still.

**Comment by lpatalas** [comment]
@akoeplinger reported on the [Teams channel](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1652262727828?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1652262727828&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1652262727828) that the issue still exists so I reactivated IcM: https://portal.microsofticm.com/imp/v3/incidents/details/304436149/home

**Comment by premun** [comment]
I am closing this as we will add functionality to mlaunch that will allow us to heal from this automatically. We won't be tracking this here though as no more work is required from us.
