### ISSUE TITLE
Http error 500 when looking at the Helix Artifacts tab in Tests

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#9263]
A customer [reported](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1651756401293?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1651756401293&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1651756401293) getting an http error 500 when trying to look at the test artifacts https://dev.azure.com/dnceng/internal/_build/results?buildId=1753680&view=ms.vss-test-web.build-test-results-tab&runId=47288382&resultId=100015&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab. I'm also getting the same error.

**Comment by epananth** [comment]
Looks like this is a secret issue like the one we have for runtime build

**Comment by epananth** [comment]
Secret was fixed and retrying this build -> https://dev.azure.com/dnceng/internal/_build/results?buildId=1753680&view=results

**Comment by epananth** [comment]
Seeing a lot of 401s 

https://ms.portal.azure.com/#blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0utSE4tKMnMzyvmqlFQKM9ILUpVUEjOyS9NiQ%252FKz0n1S8xNVbC1VVBKS0wqyky20vdIzcmsgJCOAZ5KAHM9P2Q%252FAAAA/timespan/PT4H

May be another secret expired

**Comment by ilyas1974** [comment]
@AlitzelMendez , when you get a chance, can you please take a look at this issue? Thank you

**Comment by AlitzelMendez** [comment]
it was a secret issue; it was rotated, and this is working again

**Comment by adiaaida** [comment]
@AlitzelMendez @epananth Do you remember what secret this was? A customer is reporting that it is failing again.

**Comment by akoeplinger** [comment]
Was the secret rotated? it is still happening

**Comment by alexperovich** [comment]
This was not a broken secret. Some code ql changes broke this workflow. I have a fix for this in staging.
________________________________
