### ISSUE TITLE
Add link to kusto query docs on the build analysis page

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#9267]
@danmoseley wondered if it might help to add a link on the query docs on the build analysis page.  While the queries are for a different audience, he pointed out that the build analysis tab is often the jumping off point.

**Comment by missymessa** [comment]
We were talking about a place to point the "View more details link" and currently it points to our docs, but it might be better to have a landing page that points to our docs and FAQ and Kusto queries, et cetera. 

I'm hesitant to use up more of our valuable character quota with a link to our Kusto queries when we have that link at the bottom of the check.

**Comment by danmoseley** [comment]
That makes sense to me -- I can go through your landing page.
