### ISSUE TITLE
People have to escape the error message to report a known issue 

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#9268]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

You have to escape special characters if the error message has them when you are reporting a known issue

**Comment by davidwrighton** [comment]
This is particularly annoying for error messages from compilers, as compiler errors are fairly likely to have parentheses and quotes in them.

**Comment by ChadNedzlek** [comment]
I wouldn't expect that you'd have to escape parenthesis.  I'd expect only quotation marks and backslashes (though these will show up for windows file names).

**Comment by missymessa** [comment]
Time boxing to a day of investigation of how we would want to change the input.

**Comment by davidwrighton** [comment]
One thought would be to have a link to a website that will do the escaping for you. I don't necessarily think this needs to be a different format.

**Comment by missymessa** [comment]
Recommend for this epic is to add documentation and/or link to a tool to escape the string.

**Comment by ulisesh** [comment]
Online I found [freeformatter](https://www.freeformatter.com/json-escape.html) which should help people escape their error messages. I added a reference to it in #12390
