### ISSUE TITLE
[Known Issues] Re-run button for build analysis check is misleading

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#9269]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The button makes you think that you can regenerate build analysis report if you press it

**Comment by missymessa** [comment]
This is another piece of mandatory functionality from GitHub we have no control over if it's there or not. This button will make a call to this API: https://docs.github.com/en/rest/checks/suites#rerequest-a-check-suite

Is there something you're thinking this button should do?

**Comment by ulisesh** [comment]
Thanks for the doc link, I'll take a look. Ideally, I would like the button to regenerate the report

**Comment by missymessa** [comment]
When we initially created Build Analysis, the only triggering functionality that would affect the content of the check was when a pipeline was completed or re-ran, and those events are automatically detected through the Build Analysis system of services (thus, clicking re-run would yield the same results that are currently reflected on the check). I'm assuming that "regenerating the report" is moreso for Known Issues than Build Analysis?

**Comment by ulisesh** [comment]
That's correct. Now, there is value in regenerating the report because we might have new data

This is just tracking issue for the feedback we got, we might not need it once we retroactively analyze known issues

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/24630
