### ISSUE TITLE
[Known issues] Add 'project' to KnownIssues table

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#9270]
It would be a great addition having a link to the build on the report of known issues 
<img width="931" alt="image" src="https://user-images.githubusercontent.com/6895254/167046727-be720499-50b6-407d-9051-cbba8315a8b5.png">

in order to achieve that we need the 'project' information on the records inserted on the known issues table.

**Comment by ulisesh** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/22829

**Comment by ulisesh** [comment]
Deployed and validated in https://github.com/dotnet/arcade/issues/9026
