### ISSUE TITLE
Validation scripts on sles.12 are owned by root, causing validation to fail

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#9272]
Validation scripts on sles.12 are owned by root, causing the validation to fail as seen [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=1750604&view=logs&j=212ae36d-62af-591b-b368-2ff0720fcf23&t=e800c3aa-32c1-5370-1ecc-8ac9ed7dd05c&l=224).
Running ls -al in the validate folder confirms this.

To unblock the main pipeline we either need to call validation scripts as sudo, or fix the ownership of them

I'm very curious why this is happening only on this queue

**Comment by MattGal** [comment]
I think this is just a random race condition on SLES, and SUSE/SLES are the only place this locks file can be defined.  Older images simply don't have this file; I prepped a PR to remove it if it's present at the end of add-packages.

**Comment by MattGal** [comment]
This is merged and verified fixed, closing since it doesn't need to "roll out".
