### ISSUE TITLE
DataMigration might be running with reduced capacity

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#9273]
A customer reported that some data he expected to see in Kusto was missing ([link](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1651733568657?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1651733568657&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1651733568657))
After a bit of investigation a big drop I saw a big drop in the number of daily Jobs that we have in Kusto with
`
Jobs
| where Queued >= ago(30d)
| summarize count() by bin(Finished, 1d)
`
We usually average around 4000-5000 jobs or more a day, but on the 2nd and 4th May, we had less than 1000 Jobs.
Could there be something wrong with the DataMigration application?

**Comment by MattGal** [comment]
Has anyone pointed to a missing job?  Fewer jobs isn't necessarily an indication of a problem.

**Comment by ChadNedzlek** [comment]
This as resolved in the thread this issue was opened from.  A secret had expired. Ali rotated it yesterday and the problem resolved itself (though that doesnt' cause the jobs to recreate themselves).
