### ISSUE TITLE
Regularly reset iOS/tvOS Simulators

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#9274]
### Context

The Simulators are slowing down as they are being used. The folder with their data grows substantially. I did an analysis and found sizes up to 12 GB, most frequently ranging from 2 to 7 GB. This is a potential cause of the slowdown.

### To be done

XHarness has a command that wipes the Simulator data and resets the Simulator. We should do this repeatedly on our OSX queues to keep them healthy.

A good fit might be the [weekly OSOB pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=959)?

### Notes

Simulators can be reset via following Helix job:
```bash
sudo rm -rf /Users/helix-runner/.dotnet # some machines have global .NET installed and there are permission problems
curl -sL aka.ms/get-xharness | bash -
export DOTNET_ROOT=./.dotnet

# Reset iOS
sid=`./xharness apple device ios-simulator-64`
du -sh ~/Library/Developer/CoreSimulator/Devices/$sid
./xharness apple simulators reset-simulator -o . -t ios-simulator-64
du -sh ~/Library/Developer/CoreSimulator/Devices/$sid

# Reset tvOS
sid=`./xharness apple device tvos-simulator`
du -sh ~/Library/Developer/CoreSimulator/Devices/$sid
./xharness apple simulators reset-simulator -o . -t tvos-simulator
du -sh ~/Library/Developer/CoreSimulator/Devices/$sid"
```

|Build|Kind|Start Time|
|---|---|---|
[1863024](https://dev.azure.com/dnceng/public/_build/results?buildId=1863024)|Rolling|2022-06-07|
[1865333](https://dev.azure.com/dnceng/public/_build/results?buildId=1865333)|Rolling|2022-07-07|
[1867636](https://dev.azure.com/dnceng/public/_build/results?buildId=1867636)|Rolling|2022-08-07|

**Comment by karelz** [comment]
Impact:
- 1x [1840029](https://dev.azure.com/dnceng/public/_build/results?buildId=1840029) (6/22 PM) - "Test run timed out after 45 minute(s)" failure
- 1x [1837529](https://runfo.azurewebsites.net/view/build/?number=1837529) (6/21 PM) - "Test run timed out after 45 minute(s)" failure
- 1x [1835035](https://runfo.azurewebsites.net/view/build/?number=1835035) (6/20 PM) - "Test run timed out after 45 minute(s)" failure
- 1x [1830538](https://runfo.azurewebsites.net/view/build/?number=1830538) (6/17 AM) - "Test run timed out after 30 minute(s)" failure
- 1x [1828326](https://runfo.azurewebsites.net/view/build/?number=1828326) (6/16 AM) - "Test run timed out after 30 minute(s)" failure
- 2x [1823354](https://runfo.azurewebsites.net/view/build/?number=1823354) (6/14 AM) - "Test run timed out after 30 minute(s)" failure
- 1x  - "fail: Cancelling the run after 180 seconds as application failed to launch in time" failure
- 1x  - "fail: Cancelling the run after 180 seconds as application failed to launch in time" failure
- 1x  - "fail: Cancelling the run after 180 seconds as application failed to launch in time" failure
- 1x  - "fail: Cancelling the run after 180 seconds as application failed to launch in time" failure
- 1x  - "fail: Cancelling the run after 180 seconds as application failed to launch in time" failure

**Comment by premun** [comment]
@greenEkatherine this is just too many jobs hitting the queue. Nothing to be done from our side.

Maybe too many runs of extra-platforms?

**Comment by carlossanlop** [comment]
Saw this problem today in a tvOS job for runtime-extra-platforms: https://dev.azure.com/dnceng-public/public/_build/results?buildId=38971&view=logs&j=f4520fb1-1559-5885-1d9c-3cb3f6a85e23&t=6c7a8cfe-f92e-569a-eef9-b2ad3e13056d

```
[14:58:16] dbug: [TCP tunnel] Xamarin.Hosting: Failed to connect to port 60652 (60652) on device (error: 61)
[14:58:16] dbug: [TCP tunnel] Xamarin.Hosting: Attempting USB tunnel between the port 60652 on the device and the port 60652 (60652) on the mac: 61
```

The changes in the PR are unrelated: https://github.com/dotnet/runtime/pull/76565

**Comment by premun** [comment]
@carlossanlop I don't think this is related as this issue is about simulators but your job is from a real device

**Comment by carlossanlop** [comment]
@premun Thanks for the confirmation. Should I open a new issue in this repo, or do you know if there's an existing one for real devices?

**Comment by premun** [comment]
@steveisok is there a tracking issue on your side for the TCP issues?

**Comment by premun** [comment]
The original reset we talked about and are not going to do but the unrelated issue discussed below has been resolved by https://github.com/dotnet/arcade/issues/11700
