### ISSUE TITLE
Sent EventHub events get dropped every Thursday/Friday 

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9275]
As seen [in this app insights query,](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAz2PT0sDQQzF736K0Eu3INbibaGeVCxoRT14lOxM3A3OnyWTabvihzdW7Ckhebz3eyroqJx9w34gIVCOVBTjCNeAfW6uLv3i9HQhV%252F%252F%252BkgNtMRKs1zD%252FwE7Ytct7CnxY3qDiI%252FeCyjnNAZOHQjsS1unBZjDT1fFqIQV7AosSLXvWAWZ3yIE8aIZRsjGVf1ULr1NRihebtMPA%252Fmmkv4Tbg6Pxd2lhm%252BEty%252BfGZM%252BVqvlYXtKZsZcaIwp%252FGX%252BuSZsFdBN0nJpT13NYHVsKJU9islBjcoOh%252FQAinJ04HgEAAA%253D%253D) every week around Thursday or Friday we have a reliable C# client library "send" of an event that is never seen or heard from.  This results in Helix work items that never finish and is observed by the customers as timeouts, even if the work items themselves finished on time, since without the WorkItemQueued event (sent while queuing the work item) we refuse to process them.  This should not change, we simply need EventHub to be reliable during this time.

From historic experience, the interesting thing that happens on this date is that EventHub / Service Bus has their weekly rollouts.  This is very likely the problem but we'll need to coordinate with both the Azure SDK team writing the client library and the Azure EventHub team itself to confirm that this is expected or bug behavior, and find out what sort of workarounds we might try here.

**Comment by ChadNedzlek** [comment]
Some events are not making it into the SQL processor.  When these events are things like "WorkItemFinished", that means the workitem never completes, and builds time out.  Other events have different, though often equally disasterous, outcomes.

It looks like the SDK we are using for reading the events is to blame (it seems to just drop batches occasionally when restarting).: Microsoft.Azure.EventHubs.Processor.

I suspect it's bad dispsable management internal to that library, or some incompatibility with AMQP and net6.0.

Unfortunately, that package is deprecated, and hasn't received an update in years, and we are on the latest version.

There is no current package that supports both batching, and checkpointing (to ensure that we don't reprocess old events when rebooting).

My suggestion would be to use Azure.Messaging.EventHubs, use the "PartitionReceiver" to keep the batched receiving we want, and implement checkpointing by just writing the offset to an AzureTable. But this involves a non-trivial amount of code rewriting to adopt this new model

**Comment by ChadNedzlek** [comment]
Since this causes customers to lose work, I'm not sure why it's not in FR. @ilyas1974 can you say why you removed the FR label before?

**Comment by garath** [comment]
It looks like this is the path we want: [Processing Events in Batches](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample07_BatchProcessing.md). This sample shows overriding `PluggableCheckpointStore` to get both checkpointing and batching. I don't _think_ it needs much modification if any beyond what's shown. Just drop this in as the queue processor client, and add the processing logic.

**Comment by alexperovich** [comment]
I really like these new types the sdk team has created. I think we should also do this https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample08_CustomEventProcessor.md#static-partition-assignment to remove the overhead of different processors fighting over partitions. We can make one partition in service fabric for each partition in the event hub, then service fabric can handle keeping each processor running.

**Comment by ChadNedzlek** [comment]
I'm not sure there is really a need to make service partitions. That makes things messy later, because then the SF and event hub partitions need to be matched 1-to-1, which means we can't ever change either of them without the other one exploding.  Unless we dynamically allocated the partitions at runtime to match the number of partitions in the event hub, but that would require a bunch of work, because SF is a pain in the butt when it comes to these things.

**Comment by ChadNedzlek** [comment]
Or I guess we could do a weird thing where we did a round robin assignment using SF partition ID and the list from EventHub (we did it in helix, so we already have the algorithm).  That's not... too bad? Then it lets the partitions get decoupled by just deterministically choosing which event hub partitions each service instance listens too.  That would let us scale out the SQL processor too, which could be really handy.

**Comment by ChadNedzlek** [comment]
Here's the fancy thing in the build analysis thing that deterministically partitions partitions: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service?path=/src/ServiceFabric/Helix/Helix.Internal.Reporting.Statistics/Providers/TestAggregatorProvider.cs&version=GBmain&line=113&lineEnd=114&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

**Comment by alexperovich** [comment]
> I'm not sure there is really a need to make service partitions. That makes things messy later, because then the SF and event hub partitions need to be matched 1-to-1, which means we can't ever change either of them without the other one exploding. Unless we dynamically allocated the partitions at runtime to match the number of partitions in the event hub, but that would require a bunch of work, because SF is a pain in the butt when it comes to these things.

technically we can't change the event hub partitions at all, without deleting and recreating the event hub. unless that has changed since the last time I looked.

**Comment by missymessa** [comment]
@ChadNedzlek would it be better for me to leave this issue for either you or @alexperovich to handle in your next FR stint so you can do the optimal solution?

**Comment by missymessa** [comment]
After a conversation with @garath, the solution will require recreating interfaces from the old SDK in our project. On top of additional refactors and regular FR work, I don't think I will be able to complete this refactor by the end of the week when my FR stint is up. Putting this back into the backlog for @alexperovich or @ChadNedzlek to handle when they are on FR next.

**Comment by MattGal** [comment]
@alexperovich FYI looks like https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/23699 has broken the staging environment.

**Comment by alexperovich** [comment]
Things have been fixed and things are working.
