### ISSUE TITLE
DDARM64-147 failing all jobs

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/arcade#9284]
Similarly to [dotnet/runtime#67821](https://github.com/dotnet/runtime/issues/67821) and #9088, we are now seeing all helix jobs failing on DDARM64-147. The consoles are all empty.

```scala
WorkItems
| where MachineName == "DDARM64-147"
| order by Started desc 
| project MachineName, Started, Status, ConsoleUri
| limit 200
```
All runs since 2022-05-06 17:03 UTC have `BadExit` status.

**Comment by lpatalas** [comment]
I have offlined the machine.

**Comment by lpatalas** [comment]
KVM gives me just a black screen. I've created IcM to reimage the machine: https://portal.microsofticm.com/imp/v3/incidents/details/306672802/home

**Comment by lpatalas** [comment]
Machine was reimaged and I already see successful jobs in Kusto. Closing.
