### ISSUE TITLE
Move helix machines out of westus2

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#9294]

**Comment by alexperovich** [comment]
The last ICM that was blocking has been fixed, and the rollout next week will finish the move to westus.

________________________________

**Comment by ilyas1974** [comment]
Thanks for the update. Will that include restoring the queues that have been set to be unmonitored?

**Comment by alexperovich** [comment]
Yes, they already have been switched back.

**Comment by adiaaida** [comment]
We did it! I'm closing :D
