### ISSUE TITLE
Update windows.vs2017.amd64.es.open to > Windows 20H2

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9298]
I am [kicking the can for my current PR](https://dev.azure.com/dnceng/internal/_build/results?buildId=1761232&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=386f29c8-4681-50e7-ecbc-1b877753e479) to 6/10/2022  but we need to update the image to a still-supported Windows version of `windows.vs2017.amd64.es.open`

**Comment by lpatalas** [comment]
I think the wrong date was bumped by mistake so I changed it and updated your PR.

**Comment by MattGal** [comment]
Merged new JSON file with 21H2 image and am waiting on [this build](https://dnceng.visualstudio.com/internal/_build/results?buildId=1763739&view=results) for an image.

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/22863
