### ISSUE TITLE
Build Arcade from source

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#93]
Migrated from this suggestion about BuildTools (https://github.com/dotnet/core-eng/issues/186):

> [Matt Ellis] One other comment (basically a jumping off point for discussion).  Since BuildTools uses BuildTools to build itself, there’s an obvious bootstrapping problem (we solve this today via the LKG).
> 
> For a pure source build, it’s ideal to minimize the number of dependencies we have to carry along and then rebuild.  It may be nice if we could get to the place where we could build build-tools without having to take a dependency on build-tools itself.  Does this seem like something that is worthwhile?  I understand that we lose the value of getting to dogfood buildtools, but I think there are obvious plus sides to being able to build it just using a stock MSBuild toolchain (with the default targets).
> 
> I’ll be the first to admit I don’t know how much buildtools logic we actually use in buildtools and if the pain of doing things “by hand” would be terrible.

We have https://github.com/dotnet/arcade/issues/72 "Build Arcade with Arcade", but this is more like "Build Arcade with only CLI".

This isn't necessarily a requirement for Build from Source, because we can use a "bootstrap flow". (Might be a different definition of bootstrap than you're used to.) We can build Arcade based on an existing downloaded version of Arcade, then rebuild Arcade using the version of Arcade we just built. That is meant to ensure that Arcade only depends on things that can be built from the commit itself. A concern with this flow is that binaries can "leak" from the downloaded version of Arcade through the builds, so it isn't perfect.

**Comment by markwilkie** [comment]
@dagood - do you think there's specific work to be done here?  The requirement is clear, but if it's not directly actionable right now, I'd like to close the specific issue.  Thoughts?

**Comment by dagood** [comment]
The title for this issue isn't great, it goes a lot deeper than building from source:

> this is more like "Build Arcade with only CLI".

To expand on that, it would mean building and packaging the Arcade SDK NuGet packages without access to any Arcade SDK features. This isn't necessary to build from source, it would just mean we wouldn't have to bootstrap this repo (by providing some prebuilt or N-1 packages).

Closing.
