### ISSUE TITLE
Include on-prem machine specification in matrix of truth output

### ISSUE THREAD

**Issue by lpatalas** [dotnet/arcade#9301]
In #9107 we have added new file describing on-prem machine specifications. We need to include this data in the outputs produced by MatrixOfTruthCli.

**Comment by lpatalas** [comment]
Additional points based on discussion with @tkapin and @dkurepa:
- Rename `Cores` to `PhysicalCores`, include logical cores as well
- Add processor architecture
- Number of cores for other physical machines where it's missing
- Why do we have VM in physical hardware list

**Comment by lpatalas** [comment]
Hey @ilyas1974. I noticed that in `OnPrem-Hardware-Specs.json` there is no definition for `Mac Mini (Intel)` and `Mac Pro (Intel)`. Some rows in `OsobInventory` use those values for `MachineType`. Could you add it to the JSON or just write them here and we can fill it as part of the other PR.

**Comment by ilyas1974** [comment]
Thank you for pointing this out. I have fixed the machines that were in this state.

**Comment by dkurepa** [comment]
pr link: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/23075
