### ISSUE TITLE
arcade-services secret synchronization build failing

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#9304]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://dev.azure.com/dnceng/internal/_build/results?buildId=1759661&view=results

**Comment by riarenas** [comment]
this is only affecting the staging status website, so I don't think it's blocking the rollout anymore.

**Comment by MattGal** [comment]
Secret synchronization fixed by manually updating grafana staging token using dotnet-gh-app-bot, verified it works.

Given the other side of the build has been red for a month, I'll spend a little time poking at it.

**Comment by MattGal** [comment]
I made this PR to remove the other build side. https://github.com/dotnet/arcade-services/pull/1887

**Comment by MattGal** [comment]
Secrets fixed, PR merged, once this mirrors into dnceng/internal I'll run it once more then close.

**Comment by MattGal** [comment]
Verified that the unneeded build stage is gone [here](https://dnceng.visualstudio.com/internal/_build/results?buildId=1765652&view=results), closing.
