### ISSUE TITLE
DevWF services are getting "you are not authorized to access https://dev.azure.com" errors

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9306]
- Build Analysis doesn't seem to be getting updated after pipelines have completed (either successfully or not successfully), so we need to figure out what is going on there. 
- AzureDevOpsTestAggregation service started throwing errors yesterday afternoon "VS30063: You are not authorized to access https://dev.azure.com."

**Comment by missymessa** [comment]
The BuildResultAnalysisProcessor is throwing the same error: "
022-05-10 09:35:12 | Failed to process message: Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access https://dev.azure.com.

**Comment by riarenas** [comment]
Is this in staging or in production?

**Comment by missymessa** [comment]
Both

**Comment by missymessa** [comment]
Also, where is our alerting? The error in the Build Analysis processor is a warning, so we don't report on that, however, the errors in the test reporting services should've triggered our alerts as it was an exception.

**Comment by missymessa** [comment]
Looks like two of our secrets that we've been using for DevWF functionality have expired and weren't properly configured for Secret Manager. @AlitzelMendez is taking care of this. 

Still need to figure out why our alerting missed this.

**Comment by missymessa** [comment]
PR here: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/22817

**Comment by missymessa** [comment]
PR merged and rolled out. Closing this.
