### ISSUE TITLE
Create staging tests for our docker queues

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9328]
Action item from retrospective: 

We currently don't have tests in staging to run work items through docker queues (both Windows and a flavor of Linux) that may have helped us track down some issues prior to rollout with those queues. Let's add some!

**Comment by MattGal** [comment]
A basic docker-ized version of the usual test script should run on matching linux / windows queues with the docker artifacts, starting with [this main run.](https://dnceng.visualstudio.com/internal/_build/results?buildId=1822230&view=logs&j=aca11814-7bc2-5885-ef95-90a009f7c437&t=a2d9fe37-57ce-5c9c-6b90-ed18ba493c1e)  Leaving in "validate" until I have confirmed this.

**Comment by MattGal** [comment]
Nope, it's not running the tests.  https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/23534 should get it.

**Comment by MattGal** [comment]
This is merged and now runs on any PR that updates an ubuntu.1804 or Windows server 2022 queue with a respective docker artifact.
