### ISSUE TITLE
Refactor how we look at rollout times

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9329]
Based on discussion started in our retrospective. 

- Determine if it's possible to divide the timing calculation of our rollouts between things we have control over (e.g. preparation stages, test stages, et cetera) versus things we don't have control over (e.g. waiting for a machine to be available). A reason for having this delineation for the timing of things is to determine if our rollouts are being negatively impacted by resources/dependencies outside of our control that we would need to escalate an issue to leadership. 
- Determine an acceptable upper threshold for rollouts (per repo, or same for all?). 
- Change the scoring for going over the upper threshold to a single large value (such as 20) instead of "nickle and diming" ourselves with small values per 15-minute increments. The idea here is that we have an acceptable threshold that we're okay with, but when we go over that time, there is likely something going wrong and we need to investigate it.

**Comment by garath** [comment]
@jonfortescue If I understand the work here correctly, you'll also end up resolving #9206, yes?

**Comment by jonfortescue** [comment]
Yeah, I can probably do that.
