### ISSUE TITLE
Add further xunit abstraction to Helix Job Sender SDK

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#933]
There is a lot of manual work required to get xunit to run on Helix. The table below lists these steps (per @jaredpar) and my prognoses for solving them.

| Step |  Prognosis |
|---------------------------------------------------------------------------------------------------|------------|
| Finding the xunit binaries and including them in the Helix payload. | I could envision the SDK having a "XUnit Project Payload" which is intelligent enough to read a .proj file and determine where the XUnit binaries live and then include them in a workitem payload. I could imagine that this would also be a great jumping off point for tackling issue #934. |
| Constructing the command to execute xunit relative to the layout on the Helix machine | This is more difficult since there's a wide variety of ways to execute xunit projects. At the very least, we could consider having some sort of pre-command script which sets the locations of xunit dlls in a variable for easy access by the workitem command? |
| Uploading the results file to MC | Already solved by the `EnableXUnitReporter` flag |
| Uploading crash dumps, diagnotsics to MC when xunit hits an error | Could likely be added to the xunit-reporter.py script |
| Invoking the helix pipeline from the client / build machine and properly interpreting the results | The solution to this *is* the JobSender SDK, I believe |

**Comment by alexperovich** [comment]
For 1 and 2 it should work something like this.

-  `XUnitProjectReference` item in `helix.proj` referencing `Pizza.Tests.csproj`
-  As part of item evaluation the `XUnitProjectReference` items are transformed into standard `ProjectReference` items that direct the `ResolveProjectReferences` target to run `Publish` on the project and return the published location and possibly some metadata.
    -  This may require using one of the custom properties msbuild supports to inject a new target into the referenced project.
-  A target that runs After `ResolveProjectReferences` takes the outputs and produces `HelixWorkItem` items that represent each test project and its payload.

**Comment by markwilkie** [comment]
I'm hoping (assuming) that we'll be able to create one Helix job per .dll to get some level of parallelization.

**Comment by alexperovich** [comment]
Why one job per dll? That doesn't gain us any parallelism.

**Comment by markwilkie** [comment]
@jonfortescue - What's next here to get this out of the "breakdown" lane?

**Comment by jonfortescue** [comment]
Sorry, this is broken down now! Closing.

**Comment by jonfortescue** [comment]
Specifically, this was broken out into #932, #934, and #907.
