### ISSUE TITLE
Clarity regarding new epic process

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9330]
Action item from retrospective

- Determine if it is still necessary to update the list of issues in the epic description if the epic URL is in the custom field value. 
- Should we have a process for cleaning up defunct boards from our project? (That scroll bar is getting kind of big). 
- Add the answers to the team process docs.

**Comment by adiaaida** [comment]
I think to the first point, no, it is not necessary to update the list of issues, unless you want to work that way

**Comment by adiaaida** [comment]
Missy clarified that point 2 was about the board views in the .NET Engineering Services project, not about projects in the dotnet org. On that point, my thought is that when an epic is shut down, part of that should be removing any board views that were created to support that epic.

**Comment by adiaaida** [comment]
Created a PR to update the wiki page "Guidelines for Epics" https://dev.azure.com/dnceng/internal/_git/dotnet-eng-wiki/pullrequest/23314
