### ISSUE TITLE
WorkItemProcessor adds link to the github API instead of the github UI

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#9336]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When the workItemProcessor adds a link to the github issue that it creates, it adds links such as https://api.github.com/repos/dotnet/arcade/issues/9318. It should instead create the link to the human readable version: https://github.com/dotnet/arcade/issues/9318

**Comment by riarenas** [comment]
FYI @adiaaida

**Comment by adiaaida** [comment]
:(
