### ISSUE TITLE
Automatic XUnit workitem creation (helix YAML template)

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#934]
First three bullets per @alexperovich:

- [x] `XUnitProjectReference` item in `helix.proj` referencing `Pizza.Tests.csproj`
- [x]  As part of item evaluation the `XUnitProjectReference` items are transformed into standard `ProjectReference` items that direct the `ResolveProjectReferences` target to run `Publish` on the project and return the published location and possibly some metadata.
    -  This may require using one of the custom properties msbuild supports to inject a new target into the referenced project.
- [x] A target that runs After `ResolveProjectReferences` takes the outputs and produces `HelixWorkItem` items that represent each test project and its payload.
- [ ] Add the ability to use a helix project IF no properties are set as part of the helix entry in the YAML

@jaredpar has stated that he has some stuff that can help with XUnit scaling and is willing to contribute that to this effort.

_______________

Originally proposed by @jaredpar:

> Today consumers of Helix end up defining their own scaling parameters. Essentially you’re only as scalable as the number of payloads that you send to Helix. I.E. if you send 10 payloads to Helix then at best you can utilize only 10 machines to run the tests. Allocating more than 10 is wasteful as they won’t do anything. 
> 
> This seems like it’s putting the burden in the wrong place. I want to be in a world where we can scale up or down simply by adding more machines. Not by adding more machines then asking every repository to further partition their payloads.
> 
> Xunit tests can be partitioned out in a repository independents manner. That is it’s quite simple to take one xunit DLL and run it across N different processors / machines. Roslyn implemented this logic some time ago in our tests and it’s reaped huge benefits for us. This logic could be added to helix-xunit and then we could easily manipulate PR throughput times by adding more / less machines to a given repository.

I think putting this in Helix itself is the wrong place. However, I think this is likely possible if we bake in more XUnit support to the job sender SDK.

**Comment by jaredpar** [comment]
> I think putting this in Helix itself is the wrong place

Why? Helix is the only part of the system which understands the resources available to execute the payload. Hence it's the only place that can make optimal scheduling decisions.

**Comment by jaredpar** [comment]
> The job sender can look at xunit tests being sent and decide how to best partition them into work items 

The best partitioning scheme relies on knowing how many VMs are available to execute the work. Any other strategy is sub-optimal and won't properly benefit from scaling. 

> Helix is designed to be as absolutely agnostic as possible when it comes to payload execution

We should consider changing that then. It seems reasonable to have the idea of partitionable payloads. Helix can determine how many resources are available and then ask the partitioning strategy to partition accordingly.

**Comment by jonfortescue** [comment]
> The best partitioning scheme relies on knowing how many VMs are available to execute the work. Any other strategy is sub-optimal and won't properly benefit from scaling.

Without knowing how long it takes for work items to execute in advance, any partitioning scheme will be suboptimal &ndash; thus, all automated partitioning schemes will be suboptimal compared to manual partitioning. Helix is based on scale-sets, so while there is a maximum number of VMs we can scale up to, the number of VMs available at work item queue time is essentially irrelevant.

What we can definitely do is have the job sender SDK look at the xunit proj files you have and partition out work items on a dll-basis. Test execution will still benefit greatly from the parallelism without requiring Helix to have knowledge of what is inside the payload you send.

**Comment by markwilkie** [comment]
After this happens - we should evaluate again and see what could be done.  @jaredpar - perhaps use Roslyn itself for hints/directives? 

Regardless, this next step will be a big win and we should circle back around with the learnings to see where we go from there.

**Comment by alexperovich** [comment]
> Helix can determine how many resources are available and then ask the partitioning strategy to partition accordingly.

Helix intentionally doesn't know this at all. It knows a queue exists, and that some number of machines are accepting work from it.

Once work item execution time gets down to < 15 seconds more parallelism will most likely not result in any increase in visible throughput as per-work-item and per-job overhead starts to take over.

**Comment by jaredpar** [comment]
@jonfortescue 

> Without knowing how long it takes for work items to execute in advance, any partitioning scheme will be suboptimal 

Sure. At the same time it's reasonable to assume most methods will execute in about the same amount of time. Hence Helix can make reasonable decisions about partioning based on this. 

> thus, all automated partitioning schemes will be suboptimal compared to manual partitioning. 

Manual partitioning is just that ... manual. It means that we have to 

1. constantly maintain it 
1. can't just throw more VMs at a repository and make it faster. We have to both throw more VMs and manually partition again.

Want to clarify one point. The ideat that we can automatically, and agnostically, partition up xunit DLLs based on available execution units is not a proposal. It's something we actively do in Roslyn today and it's been extremely successful.

**Comment by markwilkie** [comment]
@safern had a good idea to look for a helix project IF no properties are set as part of the Helix YAML entry.

**Comment by safern** [comment]
It could be if no properties are set or also if a specific parameter is set in the YAML template, then that is passed to the msbuild project which has an import conditioned to that property and if the file exists. That would give repos extensibility.
