### ISSUE TITLE
Update VS2022 for 2022-05-25

### ISSUE THREAD

**Issue by lpatalas** [dotnet/arcade#9343]
https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/899/VS2022-Upgrade-Schedule

Update:
- VS2022 scouting release to `17.2.0`
- VS2022 regular preview to `17.2.0 Preview 4`
- VS2022 scouting preview to `17.3.0 Preview 1`

**Comment by lpatalas** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22874

**Comment by MattGal** [comment]
This is rolled out, closing
