### ISSUE TITLE
[Maestro] Mutli-instance Azure DevOps support

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#936]
ML.NET needs to flow dependencies to repo in another Azure DevOps instance.  Ensure that this is possible.  Also work through whatever issues exist in the Auzre DevOps PR support today.  Some notable issues that we know about:
- Need to be able to get appropriate PATs based on the instance that we are targeting.

/cc @alexperovich

**Comment by jcagme** [comment]
@mmitche is there an update on this issue? Is this on track (or required) for 12/14?

**Comment by mmitche** [comment]
It's on track for 12/14.  I got about halfway through this and then had to reset my changes back to 0 due to crayz merge conflcits.
