### ISSUE TITLE
Fail gracefully when cannot upload test results in Helix SDK

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#9369]
### Context

There seem to have been a large amount of 503s from Azure DevOps when trying to upload test results from Helix SDK to the build results:
https://dev.azure.com/dnceng/public/_build/results?buildId=1772527&view=logs&j=53cf86c0-f7f7-528c-7b36-2a04d9bd9a41&t=b86d509d-fe0c-589d-b423-5d49ee4c2f68

I can see there was a high amount of these errors over the weekend, and they seem to have disappeared again:
![image](https://user-images.githubusercontent.com/7013027/168550406-dee89904-4917-4bd5-9d91-ac0e86513b93.png)

### Problem

The problem are not the 503s but rather how we handle the retries. We are retrying the code here:
https://github.com/dotnet/arcade/blob/243972462df0409928cdac13fea9820ed263e7a7/src/Microsoft.DotNet.Helix/Sdk/CreateFailedTestsForFailedWorkItems.cs#L35

and then we use the response data here:
https://github.com/dotnet/arcade/blob/243972462df0409928cdac13fea9820ed263e7a7/src/Microsoft.DotNet.Helix/Sdk/CreateFailedTestsForFailedWorkItems.cs#L75

Problems:
1. We don't check whether the retry succeeded and use `testResultData` right away which causes an NRE. A more graceful message here would improve dev experience / investigations.
2. Possible problem: When we fail attempts inside of the retry, we log using `Log.LogError`. I think this will fail the build even if we happen to succeed on a further attempt. I think this should be warning.

### Other occurences
|Build|Definition|Step Name|Console log|
|---|---|---|---|
|1772527|dotnet/runtime|Send tests to Helix (Windows)|https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1772527/logs/275
|1772373|dotnet/runtime|Send to Helix|https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1772373/logs/326
|1772393|dotnet/runtime|Send tests to Helix (Windows)|https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1772393/logs/1464
|1772390|dotnet/runtime|Send to Helix|https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1772390/logs/64
|1772426|dotnet/runtime|Send tests to Helix (Unix)|https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1772426/logs/1308
|1772404|dotnet/runtime|Send tests to Helix (Unix)|https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1772404/logs/537
|1772528|dotnet/runtime|Send tests to Helix (Unix)|https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1772528/logs/386

### Reported in
https://github.com/dotnet/runtime/issues/69374

**Comment by ChadNedzlek** [comment]
It's odd the retry can "not succeed" but still return. I would have expected that to throw. In general, in C#, you shouldn't generally have to check that thing succeed, that's what exceptions are for.

**Comment by MattGal** [comment]
Looking at this with @ChadNedzlek it's clear the stuff derived from AzureDevOpsTask is not cancellable, and looking at binlogs the retries definitely did occur (til they ran out of tries) for these logs.  

As a result, we probably just want to add null checking for anything that takes a return value from retryAsync, and promote logging level from low to normal for the retry message.
