### ISSUE TITLE
PERFTIGER196 offline for investigation

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#9379]
PERFTIGER196 in queue ubuntu.1804.amd64.tiger.perf taken offline at request of @DrewScoggins.

Reenable when done.

**Comment by ilyas1974** [comment]
I have created https://portal.microsofticm.com/imp/v3/incidents/details/315983130/home to re-image this resource and have it put back into helix.

**Comment by ilyas1974** [comment]
Per IM from @DrewScoggins, it appears that this machine has faulty RAM. Working with DDFUN to get replacement RAM
https://portal.microsofticm.com/imp/v3/incidents/details/319848964/home

**Comment by ilyas1974** [comment]
RAM has been replaced and system has been added to the staging environment.
