### ISSUE TITLE
[Darc CLI] It is not obvious that authenticate must be run before running get-channels

### ISSUE THREAD

**Issue by shawnro** [dotnet/arcade#938]
We should do a check and if not authenticated, provide that as guidance rather than a somewhat cryptic Exception.

**Comment by shawnro** [comment]
@mmitche assigning to you for now.  Please reassign as necessary.

**Comment by mmitche** [comment]
@jcagme Was working on this.

**Comment by jcagme** [comment]
This should be fixed by https://github.com/dotnet/arcade/pull/1369
