### ISSUE TITLE
Review, improve docs on frequent alerts

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#9387]
Timebox improvements to the documentation associated with Grafana alerts. Prioritize based on frequency alert is seen.

**Comment by garath** [comment]
**FACTS:**

Execute in [[Web](https://dataexplorer.azure.com/clusters/1es/databases/GitHub?query=H4sIAAAAAAAAA1VQwUrDQBC9+xVz2w1moeLJQ4TWgxSKgnizHqbZSVxoZsLsBE3x401qbfEyMPPevPd465wHuvqGzw9SggclNIpLg3vAVvztIhZn8Flb5HRAS8IbaRNDVYGLYkzmzqwX6iUnEx2fsCOYWN6h1hjJleBqUQrErbvIbnBH+wy1sGHiDO5RsUFGWO5Jj8L0ZcTxd19HqOaDYm3ebflEDsvBpJuzhyMtrGPwb4twh6F5vy62PJnflLCSOJZgY0/S+GyauC0uSVJmMep6G/3Ja8by0HWo6TC1IwNbVc/TF7Ab/xKV8JpsP7coGkn/IccfiJTrH7NcIjpqAQAA)] [[Desktop](https://1es.kusto.windows.net/GitHub?query=H4sIAAAAAAAAA1VQwUrDQBC9+xVz2w1moeLJQ4TWgxSKgnizHqbZSVxoZsLsBE3x401qbfEyMPPevPd465wHuvqGzw9SggclNIpLg3vAVvztIhZn8Flb5HRAS8IbaRNDVYGLYkzmzqwX6iUnEx2fsCOYWN6h1hjJleBqUQrErbvIbnBH+wy1sGHiDO5RsUFGWO5Jj8L0ZcTxd19HqOaDYm3ebflEDsvBpJuzhyMtrGPwb4twh6F5vy62PJnflLCSOJZgY0/S+GyauC0uSVJmMep6G/3Ja8by0HWo6TC1IwNbVc/TF7Ab/xKV8JpsP7coGkn/IccfiJTrH7NcIjpqAQAA&web=0)] [[cluster('1es.kusto.windows.net').database('GitHub')](https://dataexplorer.azure.com/clusters/1es/databases/GitHub)]

```
Issue
| where CreatedAt > ago(30d)
| where OrganizationLogin == 'dotnet'
| where RepositoryName in ('arcade', 'core-eng')
| where Labels contains 'Grafana Alert'
| extend AlertId = extract('\nGrafana-Automated-Alert-Id-([0-9a-f]+)\n', 1, Body, typeof(string))
| where isnotempty(AlertId)
| summarize Count=count() by AlertId, Title
| order by AlertId, Count desc
```

AlertId | Title | Count
-- | -- | --
fd20a5c2ffca4e89940bc33e00e7aada | Staging - [Alerting] Maestro / BarViz alert | 1
fb8faaf7600740f98a1c2db076cd1712 | Staging - [Alerting] source.dot.net Availability | 2
d67c04dd4b26487db22334164bb03b63 | Staging - [Alerting] MessageAbandoned alert | 2
d2356d84cf3e43ea952d81de941eaa76 | Production - [Alerting] On-Prem Machines Heartbeating By Queue alert | 6
d2356d84cf3e43ea952d81de941eaa76 | Staging - [Alerting] On-Prem Machines Heartbeating By Queue alert | 1
6fe0b7b34a004f0bad0064a42f9b9135 | Production - [Alerting] Exceptions and Errors alert | 1
54aa0d7e647e46ff9e880bf6ae532b99 | Production - [Alerting] Autoscale: Minutes to scale-up from zero machine alert | 6
54aa0d7e647e46ff9e880bf6ae532b99 | Staging - [Alerting] Autoscale: Minutes to scale-up from zero machine alert | 4
49 | Staging - [No Data] Build Monitor Service Hook Deliveries alert | 1
44aff3c937c042caa09f821ae923c26c | Staging - [Alerting] Azure quota usage for west us 2 | 5
36d07fceeaf0472b804d8358b2198eac | Production - [Alerting] Apple simulator failure rate alert | 2
35f560112f7a4bfabf9fd69bc1bd76fa | Production - [Alerting] Android devices disconnected | 4
24cae10d9eca44079e7cf3d47f148497 | Staging - [Alerting] Helix API Average Response Time | 1
116ed29b46934330b0aa31e843807b32 | Staging - [Alerting] On-Prem Machines Heartbeating alert | 1

</div>

**Comment by premun** [comment]
I guess this is related to https://github.com/dotnet/arcade/pull/9402?

**Comment by garath** [comment]
@ilyas1974 I think the newer work (like what we just got off the phone discussing) is superseding this issue. Shall we close this?

**Comment by Chrisboh** [comment]
@garath I am going to assume that since no one objected we can just close this?
