### ISSUE TITLE
Azure DevOps test result publishing failures

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9389]
We're seeing failures, sometimes with errors as below, sometimes not, where the test runs created don't seem to exist.  We have tweaked some settings with respect to the system access token recently; this may be related, but I'll likely open an IcM to track this on the AzDO side shortly if this can't be attributed to that.

Representative instance of the problem:  https://github.com/dotnet/roslyn/pull/61351
From [a representative log:](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-roslyn-refs-pull-61351-merge-c8f5ae474c46418ca2/Microsoft.CodeAnalysis.Workspaces.UnitTests.dll.3.Attempt.2/465edbc5-a741-4215-ac2c-b07e28bbf5e5.log?helixlogtype=result)

```
2022-05-17T00:35:20.336Z	ERROR  	azure_devops_result_publisher(134)	log_error	got error: Traceback (most recent call last):
  File "C:\h\scripts\helix-scripts\helix\test_reporting\azure_devops_result_publisher.py", line 139, in upload
    self._process(batch)
  File "C:\h\scripts\helix-scripts\helix\test_reporting\azure_devops_result_publisher.py", line 151, in _process
    hot_path_tests += self._publish_results(converted)
  File "C:\h\scripts\helix-scripts\helix\test_reporting\azure_devops_result_publisher.py", line 287, in _publish_results
    published_results = self._send(lambda: test_client.add_test_results_to_test_run(
  File "C:\h\scripts\helix-scripts\helix\test_reporting\azure_devops_result_publisher.py", line 265, in _send
    raise ex
  File "C:\h\scripts\helix-scripts\helix\test_reporting\azure_devops_result_publisher.py", line 241, in _send
    return execute()
  File "C:\h\scripts\helix-scripts\helix\test_reporting\azure_devops_result_publisher.py", line 287, in <lambda>
    published_results = self._send(lambda: test_client.add_test_results_to_test_run(
  File "C:\h\scripts\helix-scripts\azure\devops\v5_1\test\test_client.py", line 675, in add_test_results_to_test_run
    response = self._send(http_method='POST',
  File "C:\h\scripts\helix-scripts\azure\devops\client.py", line 104, in _send
    response = self._send_request(request=request, headers=headers, content=content, media_type=media_type)
  File "C:\h\scripts\helix-scripts\azure\devops\client.py", line 68, in _send_request
    self._handle_error(request, response)
  File "C:\h\scripts\helix-scripts\azure\devops\client.py", line 247, in _handle_error
    raise AzureDevOpsServiceError(wrapped_exception)
azure.devops.exceptions.AzureDevOpsServiceError: Test result 0 of test run 47634538 cannot be found.
Traceback (most recent call last):
  File "C:\h\scripts\helix-scripts\helix\test_reporting\azure_devops_result_publisher.py", line 139, in upload
    self._process(batch)
  File "C:\h\scripts\helix-scripts\helix\test_reporting\azure_devops_result_publisher.py", line 151, in _process
    hot_path_tests += self._publish_results(converted)
  File "C:\h\scripts\helix-scripts\helix\test_reporting\azure_devops_result_publisher.py", line 287, in _publish_results
    published_results = self._send(lambda: test_client.add_test_results_to_test_run(
  File "C:\h\scripts\helix-scripts\helix\test_reporting\azure_devops_result_publisher.py", line 265, in _send
    raise ex
  File "C:\h\scripts\helix-scripts\helix\test_reporting\azure_devops_result_publisher.py", line 241, in _send
    return execute()
  File "C:\h\scripts\helix-scripts\helix\test_reporting\azure_devops_result_publisher.py", line 287, in <lambda>
    published_results = self._send(lambda: test_client.add_test_results_to_test_run(
  File "C:\h\scripts\helix-scripts\azure\devops\v5_1\test\test_client.py", line 675, in add_test_results_to_test_run
    response = self._send(http_method='POST',
  File "C:\h\scripts\helix-scripts\azure\devops\client.py", line 104, in _send
    response = self._send_request(request=request, headers=headers, content=content, media_type=media_type)
  File "C:\h\scripts\helix-scripts\azure\devops\client.py", line 68, in _send_request
    self._handle_error(request, response)
  File "C:\h\scripts\helix-scripts\azure\devops\client.py", line 247, in _handle_error
    raise AzureDevOpsServiceError(wrapped_exception)
azure.devops.exceptions.AzureDevOpsServiceError: Test result 0 of test run 47634538 cannot be found.
```

 ```json
 {
    "ErrorMessage" : "has one or more failing tests based on run statistics, but I couldn't find the failures."
 }
 ```

### Report
|Build|Definition|Step Name|Console log|
|---|---|---|---|
|1777488|dotnet/runtime|Send to Helix|https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1777488/logs/1232
|1777179|dotnet/runtime|Send to Helix|https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1777179/logs/1261
#### Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|2|2|

**Comment by ulisesh** [comment]
I'll update the issue to make it a known issue for build breaks matches

**Comment by MattGal** [comment]
IcM ticket: https://portal.microsofticm.com/imp/v3/incidents/details/308470519/home

**Comment by Neme12** [comment]
@MattGal I think it has to do with the full name of the test being too long - the `name` property in the results file, which includes the namespace, class name, method name and all parameters:
```xml
<test name="Microsoft.CodeAnalysis.UnitTests.WorkspaceServiceTests.DirectMemoryAccessStreamReaderTests.ReadToArray(bufferLength: 10, index: 3, count: 7, expected: &quot;\0\0\0bcdefgh&quot;, expectedResult: 7, expectedPeek: -1)" type="Microsoft.CodeAnalysis.UnitTests.WorkspaceServiceTests.DirectMemoryAccessStreamReaderTests" method="ReadToArray" time="0.0010000" result="Pass">
  <traits>
    <trait name="Feature" value="Workspace" />
  </traits>
</test>
```
I tried doing various thing in a new PR (https://github.com/dotnet/roslyn/pull/61363) to get the problematic tests to succeed - if I removed all the tests I added, it succeeded, I added more and more tests and it still succeeded, until I added the one that has a lot of parameters - then it failed. After that, I tried shortening the namespace and class name and now it succeeded. Then I restored the namespace and class name to the longer version and it failed. This points to the fully qualified test name being too long.

**Comment by MattGal** [comment]
@Neme12 that may be the case for your scenario, but it led to finding lots and lots of missing test results across many runs, so we'll see where it goes.  Thanks for pointing that out!

**Comment by MattGal** [comment]
The tests pane on almost every runtime run going quite far back is missing many of the (passing) run results.  AzDO has acknowledged the issue and is working on a fix.  It's great you've figured this out, but I'm still going to keep this issue around until that's resolved.

**Comment by Neme12** [comment]
> I'm still going to keep this issue around until that's resolved.

Of course.

> The tests pane on almost every runtime run going quite far back is missing many of the (passing) run results. 

So it showed a similar error that I encountered and was being ignored, or in these other cases the results were missing but no error was showing, meaning it wasn't detected?

**Comment by MattGal** [comment]
The latter; results are (partially) missing, but no error.

**Comment by Neme12** [comment]
@MattGal What do you mean by weird names? Will the issue of longer names work now?

**Comment by MattGal** [comment]
> @MattGal What do you mean by weird names? Will the issue of longer names work now?

A fix was merged that meant only the first 20,000 tests could show, which in our systems meant a tiny percentage.  This I have verified to be fixed.

For your issue, it would seem sufficiently long test names will break any system (or get truncated and risk duplication).   There's no new or ongoing issue with test result publishing, but you will need to avoid too-long test names.  If you have concerns with this, the only recourse I'm aware of is the developer community page.

**Comment by Neme12** [comment]
Also, this issue was created because of that particular failure that I encountered in that PR, so why close this if that isn't addressed?

**Comment by MattGal** [comment]
@Neme12 I hear you and I'll reopen this til we get more of a conclusive answer for you. I had closed it because AzDO hotfixed an issue at 1 PM today that would be obfuscating problems past the 19,999th test result in any given run which most .NET Core teams blow past very quickly.  This seems like it fixes the errors linked in this issue.

I've reached out to the team involved to ask for details (I doubt it's documented), and will share back what I find.  What I can confirm is that we submit whatever test name we are given from Helix, and if it gets abandoned upstream without throwing an error it's hard for us to react to that.

Would you be so kind as to revert your workaround in a draft PR so we can make sure it's still occurring post hotfix?

**Comment by MattGal** [comment]
> Maybe it was related not to the length of that particular test but rather the length of all tests combined that started to exceed a certain threshold?

If so that would match my problem.  What I discovered was the API was unable to page past the 20,000th test, and odd behavior fell out all over from the API having this.  For the first report (from runtime), just making all the tests pass seemed to make the problem go away too (but you still couldn't query back the passed results)

**Comment by Neme12** [comment]
One of the jobs got suddenly cancelled here: https://github.com/dotnet/roslyn/pull/61351
Do you know anything about that?

**Comment by MattGal** [comment]
That's a new one, the pool provider quietly failed:
``` 
##[error]An error occurred while provisioning resources (Error Type: Failure).
,##[error]The remote provider was unable to process the request.
```
You unfortunately can't retry til the other legs finish but it should not repro on retry.

**Comment by Neme12** [comment]
@MattGal The issue is gone and I can't reproduce it anymore. Thanks!

**Comment by MattGal** [comment]
Great to hear.  They've updated the severity of https://portal.microsofticm.com/imp/v3/incidents/details/308470519/home for its RCA so it sounds like this was just a knock-on effect of the same bug.   I'll close this now, but feel free to bring new issues any time.
