### ISSUE TITLE
Create "how to contribute" guide

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#94]
The guide should not only have the "standard" general guidance for our Core repos, but also describe the following:
-  How to determine whether or not to build and publish a package via Arcade
-  What the bar is for Arcade packages
-  What the review process and feedback looks like
-  Where to learn about packaging guidelines
-  Guidance regarding where source code for a package should live

**Comment by markwilkie** [comment]
For now I'm ok.  I think we'll need to revisit this in the future, but we can do that...well...in the future.

**Comment by maririos** [comment]
ok. Closing until we arrive to the future
