### ISSUE TITLE
Should we support nested .zip packages?

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#941]
The current SignTool task doesn't support signing content of nested .zip packages. I.e,

```
package1.zip
    -> package2.zip
         -> library1.dll
``` 

the library won't be signed because the .zip extension is ignored for nested content. 

CC: @natemcmaster @weshaggard @tmat @jaredpar @mikem8361

**Comment by JohnTortugo** [comment]
Actually, I even wonder if we should generalize this and support other kinds of compressed formats that aren't signed themselves but their content probably will be. I'm thinking .tar, .tar.gz, etc.

**Comment by natemcmaster** [comment]
I don't need this feature, so I'm fine if we don't.

**Comment by weshaggard** [comment]
If we don't actually support it we should at least warn/error about it to avoid issues if this case comes up.

**Comment by mikem8361** [comment]
Yes, .tar/.tar.gz should eventually be supported.  I'm currently using zip files for Linux/MacOS, but the standard is .tar.gz.

**Comment by mikem8361** [comment]
Opps. Reopened.

**Comment by mikem8361** [comment]
I currently don't need nested zip support.

**Comment by jaredpar** [comment]
Signing currently supports nesting: VSIX in VSIX and VSIX in NuPkg. Generalizing this should not require a lot of effort.

**Comment by JohnTortugo** [comment]
The only difference right now is that some aren't "signable", like .zip, .tar.gz (in the future). I think we can handle all these the same way we did for .zip .. eventually.

**Comment by JohnTortugo** [comment]
Closing this as we now support nested .zip files. Also, postponing the work for other containers to when the need show up - should be straight forward to implement it in the way that we did for .zip.
