### ISSUE TITLE
Helix dump functionality does not work as expected on CBL Mariner skus

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9410]
Filed so https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/23024 can be merged and we can have bare-metal Mariner support, as this has taken way too long.  For unknown reasons (likely related to the "always root" behavior?) Mariner just can't make core dumps with our current setup.  Investigations seemed to indicate that it's either permissions to the folder in question or the core pattern getting 'lost'.

My best guess for mariner would be, and this may be a non-trivial change, is it wants to run everything as root all the time.

**Comment by MattGal** [comment]
I may have worked around this, will reopen and use if not.  (Image Factory is down so I am stuck waiting on it)

**Comment by ilyas1974** [comment]
There has not been a need currently from our customers for this functionality. We can revisit this should we need to.
