### ISSUE TITLE
Stop using deprecated WindowsAzure.Storage

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#9420]
This package is TWO cycles of deprecation (WindowsAzure -> Microsoft.Azure -> Azure) and hasn't received any udpates in 3 years.  We need to move off of it to "Azure.Storage.*".

**Comment by MattGal** [comment]
I assume this means in the codebase of dotnet-helix-services correct?

**Comment by ChadNedzlek** [comment]
Yup, it's the only place that does it, I think, but we should check others, just in case.

**Comment by ulisesh** [comment]
New PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/23680

**Comment by ulisesh** [comment]
After merging the PR we got a new exception "The resource doesn't support specified Http Verb." I'll take a look tomorrow

**Comment by ulisesh** [comment]
Rolled out. Dealing with a regression in https://github.com/dotnet/arcade/issues/9847
