### ISSUE TITLE
AzDo Work Item

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#9461]
Please address the following work items 

https://nextgenpriv.visualstudio.com/NGP2/_workitems/edit/34116?src=WorkItemMention&src-action=artifact_link
https://nextgenpriv.visualstudio.com/NGP2/_workitems/edit/34115?src=WorkItemMention&src-action=artifact_link

@garath is this something you can take a look at?

**Comment by garath** [comment]
It looks like this has passed, closing.
