### ISSUE TITLE
Build Analysis: Step Name, show StepHierarchy Name

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#9469]
@missymessa and I observed something while investigating https://github.com/dotnet/core-eng/issues/15846.

We noticed that in some cases was very hard do differentiate that the errors belonged to different steps because they had the same name, for example:
<img width="855" alt="image" src="https://user-images.githubusercontent.com/6895254/170374507-742cd30f-2848-4e79-9c29-3b564687122a.png">

showing the step name with the hierarchy is going to help to have a lot more context and to know that are different steps 
<img width="872" alt="image" src="https://user-images.githubusercontent.com/6895254/170374169-842c5d9e-107c-42e2-bff0-f25cd5e461d8.png">

**Comment by missymessa** [comment]
I think we filtered that out because that's where the `_default` step name was occurring on pipelines that only had one stage. Let's make sure that keeps getting filtered out, but leave in anything else.

**Comment by AlitzelMendez** [comment]
@missymessa do you remember an example of how it was? so I can create a test for that scenario?
was something like _default/_defaul/StepName?
or just like _default/StepName?
or only StepName?
