### ISSUE TITLE
Helix is functional to build preview

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#947]
- [x] Simple case supports minimal setup and it "just works"
- [ ] Documentation updated

**Comment by jcagme** [comment]
FYI @jonfortescue. This epic will track the work that came out from the big "Mass on boarding to Helix" email and that should help make the tools better so when new teams start consuming it, it should just work (given that it will work for Roslyn, in theory it should work for **most** of the other teams)

**Comment by jonfortescue** [comment]
Everything in this epic is now complete, so I'm closing. Work on the followup epic (https://github.com/dotnet/arcade/issues/1227) will begin after I'm off FR.

**Comment by jcagme** [comment]
Great!!!
