### ISSUE TITLE
Add clang zlib-devel krb5-libs krb5-devel libraries on centos.7.amd64* Helix queues

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/arcade#9485]
cc: @MattGal 
Not having this and doing the network install during the run is causing intermittent issues in dotnet performance runs. Specifically, we are hitting the problem outlined here: https://github.com/dotnet/performance/issues/2449. With the packages installed by default, we will be able to remove the installation of them here: https://github.com/dotnet/performance/blob/main/eng/performance/benchmark_jobs.yml#L64-L66.

**Comment by MattGal** [comment]
Whoever takes this, it's a good opportunity to fix & enable "update = true" on linux package manager for Centos at the same time.

**Comment by adiaaida** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/23352

**Comment by MattGal** [comment]
Rolled out, closing.
