### ISSUE TITLE
dotnet-tools feed started to require authentication

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/arcade#9490]
### Build

Looks like this is affecting roslyn-ci builds for the past hour or so. I used the "Report infrastructure issue" button in Helix Build Analysis to fill this out. It was very handy!

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1792333

cc @333fred whose build is affected

### Build leg reported

Restore

### Pull Request

https://github.com/dotnet/roslyn/pull/61551

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "Failed to retrieve information about 'Microsoft.NETCore.App.Ref' from remote source"
 }
 ```

### Report
|Build|Definition|Step Name|Console log|
|---|---|---|---|
|[1790340](https://dev.azure.com/dnceng/public/_build/results?buildId=1790340)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1790340/logs/2911)
|[1792779](https://dev.azure.com/dnceng/public/_build/results?buildId=1792779)|dotnet/roslyn|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792779/logs/83)
|[1792778](https://dev.azure.com/dnceng/public/_build/results?buildId=1792778)|dotnet/aspnetcore|Build x64 native assets|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792778/logs/11)
|[1792771](https://dev.azure.com/dnceng/public/_build/results?buildId=1792771)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792771/logs/222)
|[1792780](https://dev.azure.com/dnceng/public/_build/results?buildId=1792780)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792780/logs/11)
|[1792758](https://dev.azure.com/dnceng/public/_build/results?buildId=1792758)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792758/logs/421)
|[1792781](https://dev.azure.com/dnceng/public/_build/results?buildId=1792781)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792781/logs/7)
|[1792775](https://dev.azure.com/dnceng/public/_build/results?buildId=1792775)|dotnet/aspnetcore|Run build.sh|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792775/logs/200)
|[1792765](https://dev.azure.com/dnceng/public/_build/results?buildId=1792765)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792765/logs/7)
|[1792764](https://dev.azure.com/dnceng/public/_build/results?buildId=1792764)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792764/logs/19)
|[1792746](https://dev.azure.com/dnceng/public/_build/results?buildId=1792746)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792746/logs/590)
|[1792763](https://dev.azure.com/dnceng/public/_build/results?buildId=1792763)|dotnet/roslyn|Restore|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792763/logs/75)
|[1792769](https://dev.azure.com/dnceng/public/_build/results?buildId=1792769)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792769/logs/187)
|[1792770](https://dev.azure.com/dnceng/public/_build/results?buildId=1792770)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792770/logs/84)
|[1792749](https://dev.azure.com/dnceng/public/_build/results?buildId=1792749)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792749/logs/67)
|[1792735](https://dev.azure.com/dnceng/public/_build/results?buildId=1792735)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792735/logs/878)
|[1792726](https://dev.azure.com/dnceng/public/_build/results?buildId=1792726)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792726/logs/91)
|[1792727](https://dev.azure.com/dnceng/public/_build/results?buildId=1792727)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792727/logs/35)
|[1792714](https://dev.azure.com/dnceng/public/_build/results?buildId=1792714)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792714/logs/169)
|[1792700](https://dev.azure.com/dnceng/public/_build/results?buildId=1792700)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792700/logs/562)
|[1792722](https://dev.azure.com/dnceng/public/_build/results?buildId=1792722)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792722/logs/13)
|[1792719](https://dev.azure.com/dnceng/public/_build/results?buildId=1792719)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792719/logs/7)
|[1792717](https://dev.azure.com/dnceng/public/_build/results?buildId=1792717)|dotnet/roslyn|Build - Validate determinism|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792717/logs/54)
|[1792695](https://dev.azure.com/dnceng/public/_build/results?buildId=1792695)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792695/logs/645)
|[1792701](https://dev.azure.com/dnceng/public/_build/results?buildId=1792701)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792701/logs/95)
|[1792698](https://dev.azure.com/dnceng/public/_build/results?buildId=1792698)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792698/logs/120)
|[1792715](https://dev.azure.com/dnceng/public/_build/results?buildId=1792715)|dotnet/aspnetcore|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792715/logs/52)
|[1792703](https://dev.azure.com/dnceng/public/_build/results?buildId=1792703)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792703/logs/56)
|[1792702](https://dev.azure.com/dnceng/public/_build/results?buildId=1792702)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792702/logs/41)
|[1792718](https://dev.azure.com/dnceng/public/_build/results?buildId=1792718)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792718/logs/13)
|[1792697](https://dev.azure.com/dnceng/public/_build/results?buildId=1792697)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792697/logs/34)
|[1792696](https://dev.azure.com/dnceng/public/_build/results?buildId=1792696)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792696/logs/83)
|[1792659](https://dev.azure.com/dnceng/public/_build/results?buildId=1792659)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792659/logs/917)
|[1792684](https://dev.azure.com/dnceng/public/_build/results?buildId=1792684)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792684/logs/55)
|[1791693](https://dev.azure.com/dnceng/public/_build/results?buildId=1791693)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1791693/logs/839)
|[1792620](https://dev.azure.com/dnceng/public/_build/results?buildId=1792620)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792620/logs/493)
|[1792641](https://dev.azure.com/dnceng/public/_build/results?buildId=1792641)|dotnet/aspnetcore|Build shared fx|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792641/logs/10)
|[1792634](https://dev.azure.com/dnceng/public/_build/results?buildId=1792634)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792634/logs/18)
|[1792439](https://dev.azure.com/dnceng/public/_build/results?buildId=1792439)|dotnet/roslyn|Build - Validate determinism|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792439/logs/129)
|[1792611](https://dev.azure.com/dnceng/public/_build/results?buildId=1792611)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792611/logs/94)
|[1792612](https://dev.azure.com/dnceng/public/_build/results?buildId=1792612)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792612/logs/40)
|[1792528](https://dev.azure.com/dnceng/public/_build/results?buildId=1792528)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792528/logs/1344)
|[1792613](https://dev.azure.com/dnceng/public/_build/results?buildId=1792613)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792613/logs/67)
|[1792582](https://dev.azure.com/dnceng/public/_build/results?buildId=1792582)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792582/logs/67)
|[1792093](https://dev.azure.com/dnceng/public/_build/results?buildId=1792093)|dotnet/aspnetcore|Run build.cmd|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792093/logs/878)
|[1792529](https://dev.azure.com/dnceng/public/_build/results?buildId=1792529)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792529/logs/191)
|[1792530](https://dev.azure.com/dnceng/public/_build/results?buildId=1792530)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792530/logs/84)
|[1792516](https://dev.azure.com/dnceng/public/_build/results?buildId=1792516)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792516/logs/393)
|[1792520](https://dev.azure.com/dnceng/public/_build/results?buildId=1792520)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792520/logs/67)
|[1792524](https://dev.azure.com/dnceng/public/_build/results?buildId=1792524)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792524/logs/84)
|[1792525](https://dev.azure.com/dnceng/public/_build/results?buildId=1792525)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792525/logs/35)
|[1792207](https://dev.azure.com/dnceng/public/_build/results?buildId=1792207)|dotnet/installer|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792207/logs/557)
|[1792466](https://dev.azure.com/dnceng/public/_build/results?buildId=1792466)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792466/logs/508)
|[1792294](https://dev.azure.com/dnceng/public/_build/results?buildId=1792294)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792294/logs/367)
|[1792449](https://dev.azure.com/dnceng/public/_build/results?buildId=1792449)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792449/logs/449)
|[1792450](https://dev.azure.com/dnceng/public/_build/results?buildId=1792450)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792450/logs/940)
|[1792438](https://dev.azure.com/dnceng/public/_build/results?buildId=1792438)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792438/logs/386)
|[1792454](https://dev.azure.com/dnceng/public/_build/results?buildId=1792454)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792454/logs/482)
|[1792458](https://dev.azure.com/dnceng/public/_build/results?buildId=1792458)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792458/logs/614)
|[1792445](https://dev.azure.com/dnceng/public/_build/results?buildId=1792445)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792445/logs/35)
|[1792452](https://dev.azure.com/dnceng/public/_build/results?buildId=1792452)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792452/logs/41)
|[1792444](https://dev.azure.com/dnceng/public/_build/results?buildId=1792444)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792444/logs/94)
|[1792416](https://dev.azure.com/dnceng/public/_build/results?buildId=1792416)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792416/logs/89)
|[1792198](https://dev.azure.com/dnceng/public/_build/results?buildId=1792198)|dotnet/roslyn|Build - Validate determinism|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792198/logs/147)
|[1792411](https://dev.azure.com/dnceng/public/_build/results?buildId=1792411)|dotnet/roslyn|Build - Validate determinism|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792411/logs/47)
|[1792372](https://dev.azure.com/dnceng/public/_build/results?buildId=1792372)|dotnet/runtime|Build coreclr/libs components needed by test build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792372/logs/869)
|[1792412](https://dev.azure.com/dnceng/public/_build/results?buildId=1792412)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792412/logs/19)
|[1791684](https://dev.azure.com/dnceng/public/_build/results?buildId=1791684)|dotnet/aspnetcore|Build shared fx|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1791684/logs/258)
|[1792417](https://dev.azure.com/dnceng/public/_build/results?buildId=1792417)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792417/logs/40)
|[1792247](https://dev.azure.com/dnceng/public/_build/results?buildId=1792247)|dotnet/installer|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792247/logs/378)
|[1792405](https://dev.azure.com/dnceng/public/_build/results?buildId=1792405)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792405/logs/8)
|[1792408](https://dev.azure.com/dnceng/public/_build/results?buildId=1792408)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792408/logs/7)
|[1792368](https://dev.azure.com/dnceng/public/_build/results?buildId=1792368)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792368/logs/569)
|[1792407](https://dev.azure.com/dnceng/public/_build/results?buildId=1792407)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792407/logs/19)
|[1792406](https://dev.azure.com/dnceng/public/_build/results?buildId=1792406)|dotnet/roslyn|Restore|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792406/logs/64)
|[1791831](https://dev.azure.com/dnceng/public/_build/results?buildId=1791831)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1791831/logs/2402)
|[1792393](https://dev.azure.com/dnceng/public/_build/results?buildId=1792393)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792393/logs/19)
|[1792389](https://dev.azure.com/dnceng/public/_build/results?buildId=1792389)|dotnet/aspnetcore|Build shared fx|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792389/logs/38)
|[1791901](https://dev.azure.com/dnceng/public/_build/results?buildId=1791901)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1791901/logs/1399)
|[1792095](https://dev.azure.com/dnceng/public/_build/results?buildId=1792095)|dotnet/aspnetcore|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792095/logs/78)
|[1792295](https://dev.azure.com/dnceng/public/_build/results?buildId=1792295)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792295/logs/40)
|[1792394](https://dev.azure.com/dnceng/public/_build/results?buildId=1792394)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792394/logs/7)
|[1792400](https://dev.azure.com/dnceng/public/_build/results?buildId=1792400)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792400/logs/7)
|[1792367](https://dev.azure.com/dnceng/public/_build/results?buildId=1792367)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792367/logs/19)
|[1792369](https://dev.azure.com/dnceng/public/_build/results?buildId=1792369)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792369/logs/76)
|[1792370](https://dev.azure.com/dnceng/public/_build/results?buildId=1792370)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792370/logs/40)
|[1792360](https://dev.azure.com/dnceng/public/_build/results?buildId=1792360)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792360/logs/21)
|[1792359](https://dev.azure.com/dnceng/public/_build/results?buildId=1792359)|dotnet/roslyn|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792359/logs/8)
|[1791834](https://dev.azure.com/dnceng/public/_build/results?buildId=1791834)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1791834/logs/124)
|[1792357](https://dev.azure.com/dnceng/public/_build/results?buildId=1792357)|dotnet/roslyn|Build - Validate determinism|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792357/logs/62)
|[1792373](https://dev.azure.com/dnceng/public/_build/results?buildId=1792373)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792373/logs/95)
|[1792365](https://dev.azure.com/dnceng/public/_build/results?buildId=1792365)|dotnet/roslyn|Restore|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792365/logs/126)
|[1792361](https://dev.azure.com/dnceng/public/_build/results?buildId=1792361)|dotnet/aspnetcore|Run build.cmd|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792361/logs/223)
|[1792374](https://dev.azure.com/dnceng/public/_build/results?buildId=1792374)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792374/logs/40)
|[1792366](https://dev.azure.com/dnceng/public/_build/results?buildId=1792366)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792366/logs/43)
|[1792371](https://dev.azure.com/dnceng/public/_build/results?buildId=1792371)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792371/logs/60)
|[1792392](https://dev.azure.com/dnceng/public/_build/results?buildId=1792392)|dotnet/roslyn|Build - Validate determinism|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792392/logs/62)
|[1791884](https://dev.azure.com/dnceng/public/_build/results?buildId=1791884)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1791884/logs/1559)
|[1792375](https://dev.azure.com/dnceng/public/_build/results?buildId=1792375)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792375/logs/88)
|[1792399](https://dev.azure.com/dnceng/public/_build/results?buildId=1792399)|dotnet/roslyn|Build and Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792399/logs/19)
Displaying 100 of 195 results
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|195|

**Comment by premun** [comment]
We are also [seeing this](https://dev.azure.com/dnceng/public/_build/results?buildId=1792716&view=logs&j=a83666f7-a1cf-595f-f6cb-b187860111f1&t=a409c99c-b5a7-5554-fa88-a95fbe06c0d2):

>   Response status code does not indicate success: 401 (Unauthorized - TF400813: Resource not available for anonymous access. Client authentication required. (DevOps Activity ID: 048F8AC2-A394-440B-8571-AC3502879468)).

Seems like it's a similar issue

**Comment by premun** [comment]
Original IcM was closed as it was routed badly. I opened a new one for Azure DevOps: https://portal.microsofticm.com/imp/v3/incidents/details/310579759/home

All builds are still failing, waiting for M1 approval to upgrade to Sev 2

**Comment by premun** [comment]
The feature flag that caused this was reverted and we're back on track.

@mmitche you might be interested in this - the feature flag was for allowing public feeds to have upstreams - so something we're probably waiting for for some time already. Seems like we're going to have to wait some more :)

**Comment by ilyas1974** [comment]
Now that we have impact data, closing issue.
