### ISSUE TITLE
ARM Systems need Updating

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#9496]
@kunalspathak has requested that we update some of our ARM systems to run Ubuntu 20.04. Using this issue to track that work.

**Comment by ilyas1974** [comment]
ICM to track the specific work - https://portal.microsofticm.com/imp/v3/incidents/details/310650812/home

**Comment by ilyas1974** [comment]
Systems within this queue have been updated to 20.04

**Comment by kunalspathak** [comment]
Thanks a lot @ilyas1974
