### ISSUE TITLE
Build Analysis: show failure rate as part of history link 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#9497]
This is part of the feedback provided by @danmoseley in https://gist.github.com/danmoseley/f56e2cdb7e2e9579b7b78e69c3af2a95

This change is about moving the pass rate section next to the title as a part of the history link.
This is how it looks right now

<img width="561" alt="image" src="https://user-images.githubusercontent.com/6895254/170773125-5ed3001a-a38f-411e-bc4f-560358d4231a.png">

and how this is going to look after the changes
<img width="556" alt="image" src="https://user-images.githubusercontent.com/6895254/170772556-ba930035-7e3e-4de2-bed8-173127d5bd48.png">

which would give more visibility to this section and also will reduce the use of characters, on this example it went from 6607 to 6106.

any  thoughts about this change @missymessa / @ulisesh ?

**Comment by ulisesh** [comment]
I'm not sure if "past" is the right word 🤔 I think "failure rate" is enough

**Comment by missymessa** [comment]
Agreed with Ulises on removing the "past" part. I like this change, though.

**Comment by AlitzelMendez** [comment]
ok great, I will open a PR for this with the feedback!

**Comment by danmoseley** [comment]
Re "past" - this refers to the pass rate of runs previous to this one, right? If I don't see "past" I could think it was referring to the pass rate on the PR I'm looking at - which likely ran the test many times over all its pipelines.
