### ISSUE TITLE
UnauthorizedAccessException: Access to the path '/datadisks' is denied on Linux

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/arcade#9502]
### Build

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1776441

Some Roslyn tests which discover editorconfig files are intermittently failing on Linux. The failing Helix work item logs contains:

```log
   System.UnauthorizedAccessException : Access to the path '/datadisks' is denied.
```

I'm wondering if there's some nondeterministic config/setup issue which is resulting in unexpected permissions for this folder in some runs.

cc @dotnet/roslyn-infrastructure 

### Build leg reported

Test

### Pull Request

https://github.com/dotnet/roslyn/pull/60977

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "error : Work item Microsoft.Build.Tasks.CodeAnalysis.UnitTests.dll in job"
 }
 ```

### Report
|Build|Definition|Step Name|Console log|
|---|---|---|---|
|[1793804](https://dev.azure.com/dnceng/public/_build/results?buildId=1793804)|dotnet/roslyn|Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1793804/logs/184)
|[1794961](https://dev.azure.com/dnceng/public/_build/results?buildId=1794961)|dotnet/roslyn|Test|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1794961/logs/137)
#### Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|2|2|

**Comment by RikkiGibson** [comment]
https://github.com/dotnet/roslyn/issues/61017

**Comment by dibarbet** [comment]
> I'm wondering if there's some nondeterministic config/setup issue which is resulting in unexpected permissions for this folder in some runs.

Want to add some context from when I had to disable these originally in https://github.com/dotnet/roslyn/issues/61017

I was told by the dotnet eng folks that everything outside of the work item directory is not safe to access because it is not reset / cleaned between runs.  So some other CI run (could be any run using this pool) could have modified that folder.

The suggestion from the arcade folks was to not peek outside the work item directory, but that may not work for .editorconfig tests.  We may want to container-ize these tests so we can ensure a clean state, but that might have some overhead just for a couple tests.
