### ISSUE TITLE
V3 publishing fails when there are duplicate default channels

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#9508]
A customer reported a build failing due to a darc error. It looks like it's an issue on our end.
https://dev.azure.com/dnceng/internal/_build/results?buildId=1795967&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=c7a8693b-2f9c-5ea8-c909-cde9405ac2e1&l=315

Original conversation [link](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1653879950419?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1653879950419&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1653879950419)

**Comment by riarenas** [comment]
I spent some time figuring this one out.

I saw there were duplicate tags in the linked build:
![image](https://user-images.githubusercontent.com/23242101/171029092-423e984b-a424-457c-9684-4c4253e5addf.png)

which made me take a look at the default channels for the repo: 
```
darc get-default-channels --source-repo https://dev.azure.com/dnceng/internal/_git/dotnet-winforms-designer --channel ".NET 
Core Tooling Release"
```

The result showed that there were both a regex match for any release branch, and a direct default channel for the 17.3p2 branch which ended up being expanded identically:
```
(4263) https://dev.azure.com/dnceng/internal/_git/dotnet-winforms-designer @ release/17.3p2 -> .NET Core Tooling Release
(4219) https://dev.azure.com/dnceng/internal/_git/dotnet-winforms-designer @ -regex:release/* -> .NET Core Tooling Release
```

After removing the regex entry, a retry of the build was able to publish.

The error stack for the publishing build shows there's a bug in our Equals implementation for TargetFeedConfig that we should fix so that we don't fail builds that may have duplicate channel entries. 

```
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22276.1\tools\SdkTasks\PublishArtifactsInManifest.proj(144,5): error : Object reference not set to an instance of an object.
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22276.1\tools\SdkTasks\PublishArtifactsInManifest.proj(144,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.Model.TargetFeedConfig.Equals(Object obj) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/TargetFeedConfig.cs:line 94
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22276.1\tools\SdkTasks\PublishArtifactsInManifest.proj(144,5): error :    at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22276.1\tools\SdkTasks\PublishArtifactsInManifest.proj(144,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestV3.ExecuteAsync() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs:line 170
##[error].packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22276.1\tools\SdkTasks\PublishArtifactsInManifest.proj(144,5): error : Object reference not set to an instance of an object.
   at Microsoft.DotNet.Build.Tasks.Feed.Model.TargetFeedConfig.Equals(Object obj) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/TargetFeedConfig.cs:line 94
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestV3.ExecuteAsync() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs:line 170
```

**Comment by MattGal** [comment]
yay, the regex feature still works :)

**Comment by adiaaida** [comment]
I feel like there are two issues here to address:

1) Darc, when there are multiple default channels for a branch and they are the same channel, tries to publish to the same channel twice (should there be a Distinct() here: https://github.com/dotnet/arcade-services/blob/fc238be0112abfd0f8b895b476ce7410aba743c8/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs#L113-L116)
2) Publishing, when presented with the same channel twice gets.... confused. This can only happen in the case in # 1 (I think? I honestly am pretty confused by the error message/failure case and how to test it out to repro). So if we solve the former, we get the later for free. Of course, if this comes up just by virtue of the fact that a branch has the same default channel twice as a default channel, then that's something that definitely needs to be addressed.

**Comment by adiaaida** [comment]
Oh, and we should probably distinct targetChannelsIds here: https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs#L97

**Comment by adiaaida** [comment]
Still.... not sure why there was a nullref in the Equals method? That's super weird

**Comment by alexperovich** [comment]
That Equals method is rather large, and there are a lot of unguarded dereferences. Probably one of the strings is null and we end up with `null.Equals(<stuff>)`

**Comment by adiaaida** [comment]
add null refs TO EVERYTHING

**Comment by MattGal** [comment]
@adiaaida this has been in rollout some time, can it be closed?

**Comment by adiaaida** [comment]
oh yeah. definitely. well. I think. @riarenas did we end up having to roll back one of the changes I made to darc for this?
