### ISSUE TITLE
Artifacts window 404s when not logged in

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#9527]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://dev.azure.com/dnceng/public/_build/results?buildId=1793017&view=ms.vss-test-web.build-test-results-tab&runId=47908434&resultId=191620&paneView=debug
Not logged in mode
When selecting the "Artifacts" tab it says "404 Unable to process request."

**Comment by jakobbotsch** [comment]
Probably stating the obvious here, but the 404 has to do with whether or not you are signed in to AzDO. Incognito is just the easy way to make sure you aren't signed in.
I get this error whenever I try to check the artifacts from unmanaged devices since I cannot be signed in to my Microsoft account from those. Similarly this problem makes it impossible for contributors to look at artifacts of their test runs, if I am not mistaken.

**Comment by jakobbotsch** [comment]
I confirmed with contributors that this makes looking into test failures very tedious for them.

**Comment by missymessa** [comment]
I feel like this is something that we're constantly trying to fix. @garath, do you have any insight on what the outcome has been for trying to fix this in the past?

**Comment by garath** [comment]
Unfortunately, no, I don't really recall this happening before. 

The error page that is served is from https://helix.dot.net, and Helix does check for a login cookie at that endpoint (logged in to Helix). I don't recall anything changing in the code recently. Has this worked in the past?

For internal FR folks, here's a [sample request trace](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAxWNMQ6DMBAEe15xHU2a5IIdFzyAV6DDXhQKsHM2gkh5fEw7o9EoPjtyyc2P9m2JGxUVj3wjnB6pVHKp4w0FxQSVC41DoL6nlhlwZg6vTpyfYcE8GWvEuGd3f7Btaxo1QGn6UlnWOpI1kWT%252FB5yz6Qd3AAAA/timespan/P1D):

**Comment by missymessa** [comment]
> Unfortunately, no, I don't really recall this happening before. 

Hmm, I could've sworn that the issue with us needing to be logged in to view the content on the artifacts tab in AzDO has been an issue in the past that we've tried to fix. I'll do some digging into previous issues and see if I can find more information.

**Comment by missymessa** [comment]
This looks related: https://github.com/dotnet/core-eng/issues/12689

**Comment by garath** [comment]
Ah, yep. That was an issue with not being logged into AzDO, but that does also imply that anonymous to Helix worked.

**Comment by missymessa** [comment]
Here's a screenshot of what a non-signed in user sees when going to the Artifacts tab: 

![image](https://user-images.githubusercontent.com/47990216/172686898-8baa3b39-7cdd-402e-a88d-2f08b17e3136.png)

**Comment by alexperovich** [comment]
Yep, that change broke this flow. We set ValidateIssuer and ValidateAudience to "true" but didn't set any "valid" issuers or audiences, so this flow will never accept any token.

**Comment by garath** [comment]
Well, there ya go. Sorry about missing that!

**Comment by missymessa** [comment]
Well, this is a bummer. So I wonder if it's possible to make this work again for folks who aren't authenticated. If not, we should probably remove the anonymous version of the Artifacts tab so folks aren't confused.

**Comment by alexperovich** [comment]
I can't tell you what the "valid" issuers or audiences are either, we would have to get one of these tokens and test it. Or just turn off this validation.

**Comment by garath** [comment]
> Or just turn off this validation.

I strongly prefer to not do this.

**Comment by alexperovich** [comment]
> I strongly prefer to not do this.

Then we will somehow have to figure out what the issuer and audience are that the VSS.getAppToken() method returns. We use it here https://github.com/dotnet/arcade-extensions/blob/main/src/helix/index.html#L78

**Comment by alexperovich** [comment]
The vsts documentation about this explicitly turn both of them off https://docs.microsoft.com/en-us/azure/devops/extend/develop/auth?view=azure-devops#parse-and-validate-the-token

**Comment by missymessa** [comment]
Yeah, they were previously both set to false, but were changed due to CodeQL warnings.

**Comment by garath** [comment]
I'd suggest looking at the extension controller in Helix API to see if the auth requirement is being incorrectly applied to situations where anonymous access is okay.

**Comment by alexperovich** [comment]
Do you have an example of a page that 404s for anonymous access that shouldn't?

**Comment by missymessa** [comment]
> Do you have an example of a page that 404s for anonymous access that shouldn't?

The Artifacts tab in the link in the OP of the issue (if you're not logged in)

**Comment by alexperovich** [comment]
I just looked at this build https://dev.azure.com/dnceng/public/_build/results?buildId=1814246&view=ms.vss-test-web.build-test-results-tab&runId=48206262&resultId=100000&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab, and the error isn't caused by helix. Our extension is broken.

The tab url it produced is `https://helix.dot.net/AzDevExtension/WorkItemResultData?jobName=undefined&workItemId=undefined`, those "undefined" values don't work.

**Comment by garath** [comment]
Ah, good catch. That code has indeed been recently changed: https://github.com/dotnet/arcade-extensions/tree/main/src/helix-anon

**Comment by alexperovich** [comment]
I don't see what in it could be wrong though, I'll try to give it a debug

**Comment by alexperovich** [comment]
O yea, its just a name bug. The code constructs an object:
```javascript
return {
    'IsHelixWorkItem': true,
    'JobId': jobId,
    'WorkItemName': workItemName
};
```

Then tries to access it:
```javascript
var jobId = helixWorkItem.HelixJobId;
var workItemName = helixWorkItem.HelixWorkItemName;
```

Those names have an extra "Helix" at the beginning.

**Comment by missymessa** [comment]
Updated and verified it works when not logged into AzDO.
