### ISSUE TITLE
Build Analysis: Remove 'Test is not failing in <target branch>' for every test

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#9538]
This change was suggested by @danmoseley on [build analysis proposal](https://gist.github.com/danmoseley/f56e2cdb7e2e9579b7b78e69c3af2a95)

For reference right now we are showing the message "Test is not failing in <target branch>" on every test 
<img width="572" alt="image" src="https://user-images.githubusercontent.com/6895254/171512211-0bbe819e-8bdd-48fb-93bb-f36142b7fea7.png">

All this information seems a little bit redundant because on this section we only show test that are not failing in target branch, the ones failing on target branch have a different title:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/6895254/171512483-235dd7f8-1f6d-43b2-9132-8e1d5f7f3b59.png">

The proposal for Dan is to remove this little message and have a title that gives a better message that this issue is not happening on the target branch. After the changes this should look on the following way:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/6895254/171513070-a387012b-b0ae-40c2-b6dc-61c530d895e6.png">

(notice that on Dan proposal there is a link on the title of the section, unfortunately as we show information for multiple builds we have multiple links)

I think that with this change we could remove a line that at this point is not giving new information, I am not sure if the title reflects what we want or if we have further suggestions about this change.

@ulisesh / @missymessa which are your thoughts on this change?

**Comment by missymessa** [comment]
I'm fine with these changes, especially as we have this messaging done in the headers. 

LGTM ![shipit](https://cultofthepartyparrot.com/parrots/shipitparrot.gif)
