### ISSUE TITLE
Update VS2022 and VS2022 Preview versions

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#9541]
17.3.0 Preview 1 has been in scouting for two weeks, we should update the regular preview version to match it.
17.3.0 Preview 1.1 has been release, we should update the scouting preview to it.
17.2.3 Release recently got released, we should update our scouting release queues to it.

**Comment by dkurepa** [comment]
pr link: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/23305

**Comment by andriipatsula** [comment]
PR for updating queues: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/23421

**Comment by andriipatsula** [comment]
build finished
