### ISSUE TITLE
Add missing OSes to os-definitions.json

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#9542]
We noticed that there was a difference between all supported OSes (from this [page](https://docs.microsoft.com/en-us/dotnet/core/install/)) and the ones we have in the os-definitions.json. 
The oses that need to be added are: 
- Alpine 3.15, 3.16
-  Mariner 1
- CentOS 9
- Windows nano server 1809
- Raspbian 10 
- Fedora 36
- Ubuntu 22.04
- Windows Server Core 20H2

**Comment by dkurepa** [comment]
- Alpine 3.16 isn't listed on the [official page](https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine) as supported yet. As such, I don't know if we should include it in the list yet. There is a [PR](https://github.com/dotnet/core/issues/7401) for it that hasn't been close yet.
 - There is no official documentation on Mariner 1
 - Centos 9 isn't listed on  the [official page](https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos) as supported yet. As such, I don't know if we should include it in the list yet.
 - Fedora 36 isn't listed on the [official page](https://docs.microsoft.com/en-us/dotnet/core/install/linux-fedora) as supported yet.

**Comment by dkurepa** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/23423
I haven't included the OSes listed above

**Comment by tkapin** [comment]
Linking <https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md> for reference.

**Comment by dkurepa** [comment]
The PR has been updated with the information from the official dotnet github repositories
