### ISSUE TITLE
Helix / BuildAnalysis post-deploy tests failing after removing WindowsAzure.Storage

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#9546]
One post deployment test [started failing](https://dev.azure.com/dnceng/internal/_build/results?buildId=1798429&view=results) after merging [23154](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/23154). 

@AlitzelMendez tracked the problem back to the Data Migration service not migrating data. Azure Storage Queues are an important part of this, which is exactly what my PR changed. So... I'm investigating.

**Comment by ulisesh** [comment]
PRs:
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/23714
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/23680

**Comment by ulisesh** [comment]
One more attempt to fix this in https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/23881?_a=files
