### ISSUE TITLE
Please create new Helix queue ubuntu.2004.ppc64le.experimental.open

### ISSUE THREAD

**Issue by directhex** [dotnet/arcade#9567]
As part of IBM's engagement with us, we'd like to add some IBM-provided PPC64 little endian VMs they've provided to a Helix queue so they can get early & easy visibility on failures - this mirrors their engagement on s390x, and the corresponding ubuntu.2004.s390x.experimental.open queue.

Right now the only authorized SSH key on the provided VMs is my own, I can add anyone else's if there's a pubkey documented somewhere I should add.

**Comment by tkapin** [comment]
Assigning to @oleksandr-didyk, @premun - please give Alex the context here. Thanks!

**Comment by directhex** [comment]
IBM have given us some PPC VMS, to do along with their current work on a PPC port. All the same details as our existing s390x engagement, with a different team & a different architecture. IBM has lots of architectures

**Comment by premun** [comment]
@directhex just to make sure - do I understand it correctly that there is one specific VM somewhere (in Azure?) and we will want to install the Helix agent there and connect it to the new queue?

**Comment by oleksandr-didyk** [comment]
@directhex and will you install the agent on the VMs or should we provide a pubkey and install it ourselves?

**Comment by directhex** [comment]
I'm happy to do it myself, but I'll need access to the keyvault secrets demanded by the helix setup script. If y'all would prefer to do it, I'm happy to do that too.

**Comment by oleksandr-didyk** [comment]
PR -> https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/23425

**Comment by oleksandr-didyk** [comment]
As for your question @directhex, I think @premun has more context to make the best decision here

**Comment by directhex** [comment]
I don't have direct access to the VM management (I didn't request it), but I can file a ticket for that if needed

**Comment by premun** [comment]
@oleksandr-didyk looks like we have 4 attempts for now then 😅 should be doable

**Comment by oleksandr-didyk** [comment]
@directhex we successfully installed the agent on one of the VMs. Could you please submit some proper job to the queue so we can test it E2E properly before we procced with installing it to the other VMs. Thanks

**Comment by directhex** [comment]
Hm. What did the queue name end up as? I don't see it on helix.dot.net, and none of the variations I've tried work.

```
##[error].packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22310.1/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Helix API does not contain an entry for Ubuntu.2004.PPC64EL.Experimental.Open
```

(Above value from the dotnet-helix-machines.git PR)

**Comment by directhex** [comment]
I'm not going to change `HelixBaseUrl` in the PR in case I mess it up and submit everything there, but I've submitted that one job leg locally from my dev machine. Just waiting for a job to start running. Thanks for renaming the queue.

**Comment by premun** [comment]
@directhex it is possible that @oleksandr-didyk hasn't moved the VM he bootstrapped yesterday into the renamed queue yet

**Comment by directhex** [comment]
Looking good e.g. https://helixre107v0xd6tv7v8isja.blob.core.windows.net/dotnet-runtime-ppc64le-fullbuild-019947f6a77e4a08ae/Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests/1/console.150749a7.log?helixlogtype=result

**Comment by oleksandr-didyk** [comment]
Yeah, the queue is up and the agent seems to be processing the messages without any issues. I apologize for the delay and will continue with adding the agents to the other VMs. Once they are ready, I'll let you know

**Comment by directhex** [comment]
Thanks @oleksandr-didyk 

What's the process going to be for getting this into the prod instance? The initial smoke test submitted from my dev machine looks promising, jobs are running and tests are passing https://helix.int-dot.net/api/jobs/019947f6-a77e-4a08-ae41-e2c395e82d0d/workitems?api-version=2019-06-17

**Comment by oleksandr-didyk** [comment]
I just installed the agent on the rest of the VMs, everything seems to be A-OK. As @premun mentioned, once the PROD queue is up after next rollout, I'll switch the configuration files and will notify here

**Comment by premun** [comment]
The new queue is up and we should move the machines into PROD. @oleksandr-didyk is this something you could do in between the bootcamp? I believe it's only you who has access to these VMs?

**Comment by oleksandr-didyk** [comment]
@directhex the VMs were updated to listen to the PROD queue and seem to be working / hearbeating just fine. Could you please verify on your end that its A-OK so that the ticket can be `Done`? Thanks

**Comment by directhex** [comment]
Yep, queue in prod is working
