### ISSUE TITLE
Issues with Opensuse 42.3 docker image

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#9569]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Signature verification failure in the opensuse 42.3 leg of the toolset repo for 3.1.4xx even on a simple change

[Pipelines - Run 20220603.2 logs (azure.com)](https://dev.azure.com/dnceng/public/_build/results?buildId=1805966&view=logs&j=3a97e988-d2df-5c2f-7401-294791511699&t=53be1759-2de3-5734-e40e-e351e200c91a&l=52)
 
It appears to be running zypper when this fails: 

~~~https://github.com/dotnet/toolset/blob/5c242fa78550346b87ac0f236b91b042b219cee6/scripts/docker/opensuse.42.3/Dockerfile#L11

Retrieving repository 'OSS Update' metadata [.....Signature verification failed for file 'repomd.xml' from repository 'OSS Update'.

**Comment by marcpopMSFT** [comment]
The docker file is this one: mcr.microsoft.com/dotnet-buildtools/prereqs:opensuse-42.3-d46ee12-20180327014902
The failing zypper command is this one: https://github.com/dotnet/toolset/blob/5c242fa78550346b87ac0f236b91b042b219cee6/scripts/docker/opensuse.42.3/Dockerfile#L11

It'd be good to get this fixed before the July servicing window opens so we have some time to track it down.

**Comment by marcpopMSFT** [comment]
@epananth any update here? The branding updates for 3.1 are now blocked by this so I think I'll have to start merging on red soon.

**Comment by ulisesh** [comment]
I'll investigate

**Comment by ulisesh** [comment]
Opensuse 42.3 has reached its end of life, so I recommend moving the leg to opensuse 15.2

**Comment by ulisesh** [comment]
@marcpopMSFT did you have a chance to give opensuse 15.2 a try?

**Comment by ulisesh** [comment]
Didn't get any traction, closing
