### ISSUE TITLE
Incorporate signing verification for other signable extensions

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#958]
We should improve the [signing verification routine](https://github.com/dotnet/arcade/blob/77156837ab4b92c62aa23f69bab30a336de29f41/src/Microsoft.DotNet.SignTool/src/BatchSignUtil.cs#L253) in SignTool so that we can check that other "signable files" were indeed signed. 

This will prevent misconfiguration cases where the tool find a signable file but there isn't an explicit configuration (sign/ignore) for the extension of the file - and therefore the file would be just plainly ignored.

**Comment by markwilkie** [comment]
We should look into perhaps just using  https://devdiv.visualstudio.com/DevDiv/_git/WebTools-InternalTools?path=%2FSignCheck&version=GBmaster

In discussions now w/ @joeloff about the possibility of open sourcing this.

**Comment by JohnTortugo** [comment]
Agree. I think that once we add a validation step to the build and merge [this change](https://github.com/dotnet/arcade/pull/993) we might not need to work on this issue.

@tmat

**Comment by joeloff** [comment]
Running SignCheck separately might be a better option. SignCheck can tease apart nested content, so it's simpler to run it on say an MSI as it will find nested files like DLLs inside nupkgs inside MSIs, etc.

Having it as a separate tool would also simplify things for devs if they wanted to run it over an arbitrary set of files I think.

**Comment by tmat** [comment]
There is a difference between validating that a file is _correctly_ signed vs. checking that it's signed.

The SIgnTool only needs the latter. E.g. in case of a PE file it's literally check for one integer in the PE header to be non-zero.

@JohnTortugo Yes, we should add the checks for other file types - at least for the most common ones like nuget, VSIX, ps1. These checks should be trivial. E.g. check for nuget is just that it contains entry `.signature.p7s`. 

@joeloff The sign tool already unpacks containers like zip, VSIX and nuget. It does not currently support msi, that will need to be handled differently. 

I agree that we need another, separate tool that validates correctness of all signed files. I don't think Arcade should own such tool though. Such tool already exists and is part of the set of internal compliance validation tools.

**Comment by JohnTortugo** [comment]
@tmat Yeah, that is what I thought as well.

**Comment by JohnTortugo** [comment]
Planning on adding verification for the following extensions. Please advise if this plan sounds reasonable to you.

- Nuget : Check if the file .signature.p7s is present at the root level
- VSIX : check the existence of the `\package\services\digital-signature\` folder.
- PS1 / PSD1 / PSM1 : Check for a signature block starting with `# SIG # Begin Signature Block"
- PE files (.exe / .dll): Verification is already implemented.
