### ISSUE TITLE
Test out upstreams

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#9587]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Test out upstreams for .NET repos. Right now this requires:
- A lock file
- A public feed with upstreams.

The lock file is hard to update via Maestro, so we should choose repos that do not use dependency flow in some way.

**Comment by garath** [comment]
@mmitche What needs to be done for this? We discussed dogfooding to "see what the experience is like." Is that something you're doing?

**Comment by mmitche** [comment]
We did end up testing out the upstreams with NPM and it works great. Calling this done.
