### ISSUE TITLE
Test out MSAL azure client libs

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#9588]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We have new dogfood versions of the azdo client libs with MSAL support. We use this in the PAT generator and have been asked to test the switch from ADAL to MSAL:

```
The Interactive Client and Extended Client now have major version 17, to reflect the breaking changes in their APIs:

https://mseng.visualstudio.com/AzureDevOps/_artifacts/feed/Codex-Deps/NuGet/Microsoft.VisualStudio.Services.InteractiveClient/versions/
https://mseng.visualstudio.com/AzureDevOps/_artifacts/feed/Codex-Deps/NuGet/Microsoft.TeamFoundationServer.ExtendedClient/versions/



The remaining packages continue using major version 16, e.g.: [Codex-Deps - Azure Artifacts (visualstudio.com)](https://mseng.visualstudio.com/AzureDevOps/_artifacts/feed/Codex-Deps/NuGet/Microsoft.VisualStudio.Services.MemberEntitlementManagement.WebApi/versions/16.206.3-preview)
```

**Comment by melotic** [comment]
I think we can close this. We've given the teams feedback on our usage of the new libraries, and they've made the appropriate changes.

The preview packages are still only available in the codex-deps NuGet feed, which isn't ideal for arcade-services as contributors can't build it. However when they're released, it should be trivial to update the PAT Generator with my PR.
