### ISSUE TITLE
Improve test-configuration documentation 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#9597]
The following feedback was shared with us by @dougbu 

`
Hi all, before I report an issue or open a PR, I'd like to check whether you generally agree the documentation of test-configuration.json lacks concrete information about multiple inner rules. (I also think the distinction between "retryOnRules" et cetera and the rules in them is poorly phrased but that's not major.) Now, obviously, if I have multiple inner "testName" inner rules, they're combined using OR.  But, are any of the inner rules ever combined using AND❔ If not, is there a way to request retries only if e.g. a single test fails with a particular message❔
`

We need to improve the documentation, some of the suggestions are:
1. Add examples on what happens when I have many entries with many rules
2.  better description of the existing examples in [src/Microsoft.DotNet.Helix/Sdk/Readme.md](https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.Helix/Sdk#readme) and [Documentation/DevWorkflow/Design/Dev-Design-Test-Configuration-Json.md](https://github.com/dotnet/arcade/blob/main/Documentation/DevWorkflow/Design/Dev-Design-Test-Configuration-Json.md)

one of the confusing things was 
` I realize I offered to put up a PR but actually can't unless you confirm the inner rules are always ORd together. Oh, just realized I'm also not sure about the "raw string" inner rules. Are they really exact matches i.e. {​​​​​​"failureMessage": "network disconnected" }​​​​​​ will not match "Network disconnected when reaching out to Yada Yada"❔ If that's the case, our test-configuration has been busted forever
`

**Comment by dougbu** [comment]
Suggest also

1. tackling how the word "rule" is used to make it more clear when the word applies to `"retryOnRules"` and similar versus the "inner rules" (my name)
2. documenting the wonderful `{"testName":"Pizza", "failureMessage":"Message"}` option (which means "`AND` these two exact matches")

**Comment by missymessa** [comment]
Verify with @ChadNedzlek when we update this documentation.

**Comment by AlitzelMendez** [comment]
PR: https://github.com/dotnet/arcade/pull/12387

**Comment by AlitzelMendez** [comment]
merged
