### ISSUE TITLE
New Helix Queues needed to support macOS 13 (Ventura)

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#9608]
Apple announced during their developer conference yesterday the beta releases of their next generation software. To make sure .NET functions on these new operating systems, we need to create new helix queues. 

For macOS 13 (Ventura)
osx.1300.arm64.open
osx.1300.amd64.open

For iOS 16
osx.1300.arm64.iphone.open

Once the queues are created, I will work with DDFUN to populate them with hardware.

**Comment by dkurepa** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/23489

**Comment by MattGal** [comment]
This is rolled out
