### ISSUE TITLE
Fix Microsoft.DotNet.Internal.Tools.SynchronizePackageProps so that it knows about Directory.Packages.props

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#9615]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

As part of getting https://github.com/dotnet/arcade/issues/9591 done, we removed the run of Microsoft.DotNet.Internal.Tools.SynchronizePackageProps because Packages.props was removed. We need to make it understand Directory.Packages.props instead and reenable it.

**Comment by adiaaida** [comment]
@alexperovich is this package being used by anyone else? I'm trying to figure out if I need to keep the old behavior (packages.props) in tact while adding the new behavior (Directory.Packages.props).

**Comment by alexperovich** [comment]
Its only used by us, so its fine to remove the old behavior. If we need that behavior old versions exist.

**Comment by adiaaida** [comment]
Ok, checked the changes for this in, need to wait for rollout before adding it back to helix-service. Putting in tracking.

**Comment by adiaaida** [comment]
PR to add it back https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/23580
