### ISSUE TITLE
Add additional workloads to BuildPool images

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#9627]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

@sebastienros has requested the following workloads to the windows images:

"Microsoft.Net.Component.4.7.2.SDK",
"Microsoft.VisualStudio.Component.VC.Tools.ARM64",
"Microsoft.VisualStudio.Workload.NativeDesktop",
"Microsoft.VisualStudio.Workload.NetWeb",
"Microsoft.VisualStudio.Workload.VisualStudioExtension"
"Microsoft.VisualStudio.Component.Windows10SDK.18362"

Additionally, he'd like images with VS 17.3

**Comment by adiaaida** [comment]
Note: we have images for 17.3 preview rolling out next week. Image is Build.Windows.Amd64.VS2022.Pre.Open

**Comment by dougbu** [comment]
> This issue is blocking

I suggest this be checked because we don't seem able to ingest a new SDK without a VS2022 installation containing these components.

> Additionally, he'd like images with VS 17.3

I haven't read the Teams conversation yet @sebastienros. Why do we need to move to 17.3 in the CI❔

**Comment by MattGal** [comment]
This is rolled out
