### ISSUE TITLE
alpine.amd64.tiger.perf running on Alpine 3.12

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#9645]
According to https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md and https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1-supported-os.md, alpine 3.12 is no longer supported. We should update this queue to a supported Alpine version (13+)

**Comment by MattGal** [comment]
They're running 3.15, as noted in the artifacts... I just neglected to update the OSID / Description when I updated the machines.

**Comment by MattGal** [comment]
Added to PR https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/23534

**Comment by MattGal** [comment]
PR merged, no need to wait for rollout (this is just metadata)
