### ISSUE TITLE
Tab Twice to insert the snippet in Visual Studio 2022

### ISSUE THREAD

**Issue by CoderLittleChen** [dotnet/arcade#9653]
Can I change the setting to tab one?
![image](https://user-images.githubusercontent.com/32502670/173178663-9992b1e1-267b-48ce-9fb4-fdc351d958eb.png)

**Comment by garath** [comment]
@CoderLittleChen Unfortunately this repository is not associated with VIsual Studio. I think the best place for you to check is the [Code Snippets](https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets?view=vs-2022), or in the [Developer Community](https://developercommunity.visualstudio.com/home).
