### ISSUE TITLE
Machine `DNCENGMAC091` has never processed a job successfully

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#9659]
### Context
This queue is not really used by anyone, only `dotnet/xharness` automation that uncovered this.

### Problem

This machine has the AppleTV device on it but the device seems fine. We can install/uninstall apps fine, we just fail when trying to do things like opening TCP tunnels and other. I think the Xcode or the MacOS might be compromised?

### Details
```sql
WorkItems
| where MachineName == "DNCENGMAC091.local"
| order by Finished desc
| limit 100
```

No other machine has this low success rate:
```sql
WorkItems
| where QueueName == "osx.1100.amd64.appletv.open"
| summarize SuccessRate=countif(ExitCode == 0)*100/count() by MachineName
| order by SuccessRate desc
```

We should reboot the machine and if it doesn't help, we should re-image the machine

**Comment by premun** [comment]
I power-cycled the machine so let's see

**Comment by ilyas1974** [comment]
This device is still working on having never completed a work item successfully. I have opened https://portal.microsofticm.com/imp/v3/incidents/details/316147646/home to have the system and attached device reimaged.

**Comment by ilyas1974** [comment]
Waiting on https://github.com/dotnet/arcade/issues/10052 to be completed. Will then attach this system to the new scouting queue as the OS on the device has been updated to the latest version of tvOS.

**Comment by ilyas1974** [comment]
https://portal.microsofticm.com/imp/v3/incidents/details/327409924/home to have this system deployed into the scouting queue.

**Comment by ilyas1974** [comment]
System has been moved to the scouting queue.
