### ISSUE TITLE
Make standalone long path artifacts

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#9684]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

I was doing some test for sbom generation in roslyn 

Got this warning 

```
LongPath is not enabled, you may experience build errors. You can avoid these by enabling LongPath with "reg ADD HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1
```

Link to the build https://dev.azure.com/dnceng/internal/_build/results?buildId=1823758&view=logs&j=20fcf628-b65c-5865-625a-1cef81cda63b&t=57a3a016-8c4d-5bd4-ed27-11d4fc0386e2&l=646

That caused some build errors and it did not log that it failed due to long path error.

**Comment by epananth** [comment]
This is blocking sbom generation for roslyn repo

**Comment by adiaaida** [comment]
Apparently the validation failed on windows.amd64.vs2022.pre*. Whoever is on FR needs to go make a vm based on the image that was created by https://dnceng.visualstudio.com/internal/_build/results?buildId=1835019&view=results and figure out why long paths aren't enabled correctly.

**Comment by ulisesh** [comment]
I don't think we need long path support for test machines, so I'll make a PR to limit it to build machines

**Comment by ulisesh** [comment]
You're right, I assumed the name for all build images were Build.*

**Comment by epananth** [comment]
@JoeRobich

**Comment by JoeRobich** [comment]
Looking at a recent run of our official build and I no longer see a warning about LongPaths not being enabled.

[Previously](https://dev.azure.com/dnceng/internal/_build/results?buildId=1823758&view=logs&j=20fcf628-b65c-5865-625a-1cef81cda63b&t=57a3a016-8c4d-5bd4-ed27-11d4fc0386e2&l=13):
<img width="457" alt="image" src="https://user-images.githubusercontent.com/611219/176529893-5f645bd0-853d-40ec-bf73-2ae011c8c89e.png">

[Currently](https://dev.azure.com/dnceng/internal/_build/results?buildId=1852597&view=logs&j=20fcf628-b65c-5865-625a-1cef81cda63b&t=57a3a016-8c4d-5bd4-ed27-11d4fc0386e2):
<img width="457" alt="image" src="https://user-images.githubusercontent.com/611219/176529801-a929cdc1-25a4-469e-afd0-8eb93b577476.png">

**Comment by alexperovich** [comment]
This has been fixed.
