### ISSUE TITLE
dotnet/runtime Helix jobs are timing out

### ISSUE THREAD

**Issue by jkotas** [dotnet/arcade#9692]
### Build

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1825606

3 other jobs in my PR timed out in the same way

### Build leg reported

Libraries Test Run checked coreclr Linux_musl arm Release

### Pull Request

https://github.com/dotnet/runtime/pull/70765

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : ""
 }
 ```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by MattGal** [comment]
There are 17 sources, all runtime PRs or official CI runs, just absolutely burying this queue.  We probably need to purge it so tests can start to pass.  Some Kusto evidence from the time range of @jkotas 's timed out run:

```
// There were 29 days, 7 hours of work done in this time:
WorkItems
| where Started >= datetime(2022-06-15 06:23:38.0460000) and Started <= datetime(2022-06-15 09:03:33.6950000)
| where QueueName == "ubuntu.1804.armarch.open" and Name != JobName
| extend runtime = Finished - Started
| summarize sum(runtime)


// 107 jobs, 14K work items, 100% runtime jobs
let jobIds = 
WorkItems
| where Started >= datetime(2022-06-15 06:23:38.0460000) and Started <= datetime(2022-06-15 09:03:33.6950000)
| where QueueName == "ubuntu.1804.armarch.open" and Name != JobName
| project JobId;
Jobs | where JobId  in (jobIds)
| summarize count() by Type, Source
```

Type | Source | count_
-- | -- | --
test/functional/cli/ | ci/public/dotnet/runtime/refs/heads/main | 31
test/functional/cli/innerloop/ | ci/public/dotnet/runtime/refs/heads/main | 16
test/functional/cli/ | ci/public/dotnet/runtime/refs/heads/release/6.0 | 15
test/functional/cli/innerloop/ | pr/public/dotnet/runtime/refs/pull/70461/merge | 9
test/functional/cli/innerloop/ | pr/public/dotnet/runtime/refs/pull/70063/merge | 5
test/functional/r2r/cli/ | ci/public/dotnet/runtime/refs/heads/release/6.0 | 4
test/functional/cli/innerloop/ | pr/public/dotnet/runtime/refs/pull/70764/merge | 4
test/functional/cli/innerloop/ | pr/public/dotnet/runtime/refs/pull/70759/merge | 4
test/functional/cli/innerloop/ | pr/public/dotnet/runtime/refs/pull/70765/merge | 4
test/functional/cli/innerloop/ | pr/public/dotnet/runtime/refs/pull/70726/merge | 3
test/functional/cli/ | pr/public/dotnet/runtime/refs/pull/70461/merge | 2
test/functional/cli/ | pr/public/dotnet/runtime/refs/pull/70063/merge | 2
test/functional/cli/ | pr/public/dotnet/runtime/refs/pull/70764/merge | 2
test/functional/cli/ | pr/public/dotnet/runtime/refs/pull/70759/merge | 2
test/crossgen-comparison/ | ci/public/dotnet/runtime/refs/heads/main | 2
test/functional/cli/innerloop/ | pr/public/dotnet/runtime/refs/pull/70763/merge | 1
test/functional/cli/ | pr/public/dotnet/runtime/refs/pull/70201/merge | 1

... you're just sending way, way too many jobs to finish in the time you're allowing for, and mixing huge numbers of main/release runs in the same queue with PR runs.   @dkurepa let me know if you need any assistance purging the queue down; timeouts will continue for some time unless we do.

**Comment by jkotas** [comment]
How can we find what is sending these jobs in the first 3 lines? Unless the system that creates these jobs is fixed, we are going to see the same problem immediately again.

**Comment by MattGal** [comment]
@jkotas to answer your previous question (I only did it for the first 2 lines; generalization is pretty easy). you can just get the build ids back from Kusto.  Example:

```
let jobIds = 
WorkItems
| where Started >= datetime(2022-06-15 06:23:38.0460000) and Started <= datetime(2022-06-15 09:03:33.6950000)
| where QueueName == "ubuntu.1804.armarch.open" and Name != JobName
| project JobId;
Jobs | where JobId  in (jobIds)
| where Source == "ci/public/dotnet/runtime/refs/heads/main"
| where Type startswith "test/functional/cli"
| extend props = parse_json(Properties)
| summarize by tostring(props["BuildId"])
```
which leads me to these 8 main runs:


https://dnceng.visualstudio.com/public/_build/results?buildId=1825546
https://dnceng.visualstudio.com/public/_build/results?buildId=1825417
https://dnceng.visualstudio.com/public/_build/results?buildId=1825437
https://dnceng.visualstudio.com/public/_build/results?buildId=1825354
https://dnceng.visualstudio.com/public/_build/results?buildId=1825352
https://dnceng.visualstudio.com/public/_build/results?buildId=1825357
https://dnceng.visualstudio.com/public/_build/results?buildId=1825350
https://dnceng.visualstudio.com/public/_build/results?buildId=1825347

Skimming these, it would seem the majority are manually run runs from @agocke and @BruceForstall

**Comment by BruceForstall** [comment]
I manually kicked off some outerloop CI runs yesterday and noticed a bunch of arm32/arm64 timeouts. It's bad if we don't have capacity to do this.

**Comment by MattGal** [comment]
The fix for https://github.com/dotnet/arcade/issues/9694 is merged and rolled out.  As there's nothing more we can do presently if too much work gets sent, I am closing this issue.  Feel free to reach out if you feel this is in error.
