### ISSUE TITLE
Use System.Json instead of Newtonsoft Json

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#9704]
Currently, we are using Newtonsoft Json in the Matrix of Truth project, we want to change that and switch to System.Json

**Comment by dkurepa** [comment]
It looks like there is a feature that's currently missing in System.Text.Json (https://github.com/dotnet/runtime/issues/63686) that we use in Newtonsoft: Custom ContractResolvers

**Comment by alexperovich** [comment]
is there any actual reason to switch, other than "its not Json.NET"?

**Comment by dkurepa** [comment]
No, not really, it's mostly that
