### ISSUE TITLE
`DNCENGWIN-079` fails to run powershell

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#9717]
The machine seems borked and should be probably re-imaged. It fails to start threads, run powershell or throws out of memory exceptions.

Examples:

- [System.Reflection.Context.Tests](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelixre107v0xdeko0k025g8.blob.core.windows.net%2Fdotnet-runtime-refs-heads-main-44fe1039b93749e288%2FSystem.Reflection.Context.Tests%2F1%2Fconsole.faed82f0.log%3F%253Fhelixlogtype%253Dresult&data=05%7C01%7CPremek.Vysoky%40microsoft.com%7C13425028f2f74eaf171108da505d756f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637910659607848146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CFZ%2FunQibGOqEP0E5XqAxsfua4IIIfvFznKu%2B4BaDDI%3D&reserved=0)
    - Thread failed to start.
- [System.IO.FileSystem.DriveInfo.Tests](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelixre107v0xdeko0k025g8.blob.core.windows.net%2Fdotnet-runtime-refs-heads-main-44fe1039b93749e288%2FSystem.IO.FileSystem.DriveInfo.Tests%2F1%2Fconsole.965a0f6c.log%3F%253Fhelixlogtype%253Dresult&data=05%7C01%7CPremek.Vysoky%40microsoft.com%7C13425028f2f74eaf171108da505d756f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637910659607848146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Fn%2FFasQvXmtsZUt57IO%2BjJVRP4S3dvPF6xt7XuAqbcI%3D&reserved=0)
    - Thread failed to start.
- [System.Private.Uri.Unit.Tests](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelixre107v0xdeko0k025g8.blob.core.windows.net%2Fdotnet-runtime-refs-heads-main-44fe1039b93749e288%2FSystem.Private.Uri.Unit.Tests%2F1%2Fconsole.a2eb6fa9.log%3F%253Fhelixlogtype%253Dresult&data=05%7C01%7CPremek.Vysoky%40microsoft.com%7C13425028f2f74eaf171108da505d756f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637910659607848146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zTU2zYrF%2B7y9Mt8XzSMIXSoTYm39kIVfS8unpnc%2BnUc%3D&reserved=0)
    - Wait-Process : The 'Wait-Process' command was found in the module 'Microsoft.PowerShell.Management', but the module could not be loaded.
- [System.Private.Uri.Functional.Tests](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelixre107v0xdeko0k025g8.blob.core.windows.net%2Fdotnet-runtime-refs-heads-main-44fe1039b93749e288%2FSystem.Private.Uri.Functional.Tests%2F1%2Fconsole.838eb65b.log%3F%253Fhelixlogtype%253Dresult&data=05%7C01%7CPremek.Vysoky%40microsoft.com%7C13425028f2f74eaf171108da505d756f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637910659607848146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bH2fTrcoRwvLN2Lbheb6wfcR66RytimT4h%2FVb99Pk1Y%3D&reserved=0)
    - Wait-Process : Exception of type 'System.OutOfMemoryException' was thrown.
- [System.Resources.Reader.Tests](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelixre107v0xdeko0k025g8.blob.core.windows.net%2Fdotnet-runtime-refs-heads-main-44fe1039b93749e288%2FSystem.Resources.Reader.Tests%2F1%2Fconsole.5691a862.log%3F%253Fhelixlogtype%253Dresult&data=05%7C01%7CPremek.Vysoky%40microsoft.com%7C13425028f2f74eaf171108da505d756f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637910659607848146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fziJpveNse3pCTKy151YZUNHXE2utRQrxvnpBRFdUIM%3D&reserved=0)
    - Thread failed to start.
- [System.Threading.Tasks.Dataflow.Tests](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelixre107v0xdeko0k025g8.blob.core.windows.net%2Fdotnet-runtime-refs-heads-main-44fe1039b93749e288%2FSystem.Threading.Tasks.Dataflow.Tests%2F1%2Fconsole.d8f61e27.log%3F%253Fhelixlogtype%253Dresult&data=05%7C01%7CPremek.Vysoky%40microsoft.com%7C13425028f2f74eaf171108da505d756f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637910659607848146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Hk9VVqCue3BrS%2BAKYj7phy1BGgJJVLlsEIvKQQ01Kg4%3D&reserved=0)

I offlined the machine

**Comment by dkurepa** [comment]
I kvmed onto the machine, it *looked* fine, I had no trouble with powershell. It had 10GB of free space on it's C drive, maybe that was the issue? Also there was 100+GB of free on the D drive

**Comment by premun** [comment]
Can you check its history in Kusto?

**Comment by dkurepa** [comment]
Maybe this was just bad luck, the machine looks good to me

**Comment by premun** [comment]
It was about 100 failed jobs on June 14th but maybe a reboot healed this. We can put it back to rotation and see how it's doing?
