### ISSUE TITLE
Please add queue for Ubuntu 22.04 to use as container host

### ISSUE THREAD

**Issue by danmoseley** [dotnet/arcade#9755]
In dotnet/runtime we run tests in various Linux containers based on Ubuntu 18.04. Despite being containers, the kernel versions are of course relevant to tests so it would be nice to mix in one or more newer kernel versions

See https://github.com/dotnet/runtime/issues/13757#issuecomment-1156696786

>  you could instead be using ubuntu.2004.amd64.* but aren't currently (no special .rt version of it, yet, since you don't use the other one), and we have not added 22.04 yet. If you want either thing (22.04 queue / a special 20.04 .rt queue) just file an issue in dotnet/arcade asking for it.

I would like to be able to run on 22.04 to mix things up. Can you please set up such a thing? I do not know what 'rt' means. I think that success would look like -- I can replace something like "(Debian.10.Amd64.Open)[Ubuntu.1804.Amd64.Open@mcr.microsoft.com](mailto:Ubuntu.1804.Amd64.Open@mcr.microsoft.com)/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673" with Debian 10 on Ubuntu 22.04.

cc @agocke @ViktorHofer

**Comment by danmoseley** [comment]
At this point I'm interested in x64, I see we also use eg `Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440` `Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-arm64v8-20210304164340-5a7c380` etc. If those are cheap to offer 22.04 versions of, maybe those would be useful too.

**Comment by MattGal** [comment]
@danmoseley since the ARM64 side of this question is all on-premises physical machines, I can create the entry but it'll be some (non-trivial) amount of time before there would be any hardware to use it.

**Comment by MattGal** [comment]
Created https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/23818?_a=files.  I have learned that we don't have hardware that's capable of running ARM64 22.04 currently and will have to buy a bunch before that happens, so I skipped this as that's not going to happen for some time.

**Comment by danmoseley** [comment]
That's fine, x64 is good for now.

**Comment by MattGal** [comment]
@danmoseley this is ready for usage, please let us know if you have any issues.
