### ISSUE TITLE
Add ability to be "strict" to SignToolTask

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#977]
There should be a way to produce an error when there is a signable file which is not accounted for by the configuration

**Comment by JohnTortugo** [comment]
My plan to approach this is:

0. Add new `toggle` parameter to set the strict mode: `StrictSigningInfo`
1. Make the SignTool know what is a "signable file" without depending on configuration. I'll basically create a static list with the known [signable file extensions](https://microsoft.sharepoint.com/teams/codesigninfo/Wiki/Signable%20Files.aspx).
2. If SignTool encounters a file that is signable (as per definition above) but doesn't have an explicit certificate configuration, on `FileSignInfo`, the task will produce an error and abort execution.

Points about *already signed files*:

1. If the file should just be left as is: mark the file in `FileSignInfo` as ignored (i.e., CertificateName = None)
2. If the file should be signed again: mark the file in `FileSignInfo` with a dual certificate.

**Comment by tmat** [comment]
> Add new toggle parameter to set the strict mode: StrictSigningInfo
This is not needed. The tool already reports error if a signable file is not signed.

**Comment by markwilkie** [comment]
@natemcmaster - is your scenario addressed?  (I suspect not)

**Comment by JohnTortugo** [comment]
> This is not needed. The tool already reports error if a signable file is not signed.

You mean the check on VerifyAfterSign? Right now, that is only for .PE files and I think it might take some work until we get all files covered.

**Comment by markwilkie** [comment]
To clarify - my understanding is that if a file is explicitly listed, but somehow does not end up getting signed, the tool will throw an error.  Correct? 

Assuming this is the case, @natemcmaster - is this sufficient?

**Comment by JohnTortugo** [comment]
> To clarify - my understanding is that if a file is explicitly listed, but somehow does not end up getting signed, the tool will throw an error. Correct?

I was double checking this here. That will happen **only if** 1) the file is a PE file or 2) has its extension configured in the `FileExtensionSignInfo`. 

If I try to sign something like `foo.py` (**for instance**) currently the tool will just log that it didn't find signing information for the file. However, we can work around that by:

1. configuring the .py extension on `FileExtensionSignInfo` or
2. enabling .py signing information to be set using `FileSignInfo` (currently that is consumed only for PE files..)

@tmat please correct me if I am forgetting something..

**Comment by tmat** [comment]
@JohnTortugo Let's just focus on PE files for now. We know we need to handle other files. Let's do that separately.

**Comment by tmat** [comment]
@markwilkie Yes. More precisely, we take the set of all files that are in `ItemsToSign`. All these files and every file these files contain (if they are zip/nuget/vsix files) are expected to be signed. If any of these files are not signed at the end we report an error (unless their certificate is explicitly set to `None` [1]) . 

Therefore, if repo clears `FileExtensionSignInfo` then the list in `FileSignInfo` is need to match the files listed in `ItemsToSign`. If there is a file in `ItemsToSign` that isn't in `FileSignInfo` this file won't be signed and thus an error will be reported [2]. This means that `FileSignInfo` needs to list all files, which is the requirement of ASP.NET repos AFAICT.

[1] I think this check is missing from the current impl, but should be added.
[2] The reverse is not currently checked. I.e. there can be a file listed in `FileSignInfo` that does not appear anywhere in `ItemsToSign` and thus is "unused". We can report warning for these.

**Comment by markwilkie** [comment]
@tmat - that sounds right I think.  @natemcmaster - can you confirm please?

**Comment by JohnTortugo** [comment]
> @JohnTortugo Let's just focus on PE files for now. We know we need to handle other files. Let's do that separately.

Will the be sufficient for initial onboarding @natemcmaster ?

**Comment by tmat** [comment]
@JohnTortugo 
Just realized - once we have the static list of signable extensions we can add a simple check (always, no toggle) [here](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/Configuration.cs#L203) and report an error if certificate is not assigned to a file whose extension is signable. We should also remove the warning for non-signable files. It adds no value since we know exactly what files need to be signed.

This simple check will allows us to enforce all signable files to be accounted for without the need to fully validate they we signed. We should definitely expand the validation beyond PE files, but we don't need to implement it for all signable extensions to get explicit list validation.

**Comment by natemcmaster** [comment]
My scenario does not appear to be covered by version 1.0.0-beta.18507.1 of the tool. If I give sign tool task a .nupkg which contains a .dll, but there isn't any certificate info found for that .dll, I would like an error.

Repro:
If I pass in just the .nupkg, I would expect an error in "strict mode" because this package contains "lib/netstandard2.0/Microsoft.Extensions.ObjectPool.dll".
```xml
    <ItemGroup>
      <_FileSignInfo Include="Microsoft.Extensions.ObjectPool.2.2.0-preview3-t000.nupkg" CertificateName="NuGet" />
      <_ItemsToSign Include="C:\src\aspnet\Common\artifacts\build\Microsoft.Extensions.ObjectPool.2.2.0-preview3-t000.nupkg" />
    </ItemGroup>

    <Microsoft.DotNet.SignTool.SignToolTask
      DryRun="True"
      TestSign="False"
      ItemsToSign="@(_ItemsToSign)"
      FileSignInfo="@(_FileSignInfo)"
      StrongNameSignInfo=""
      FileExtensionSignInfo=".dll;.exe;.cab;.msi;.nupkg;.vsix;.jar;.ps1;.psd1;.psc1;.psm1"
      TempDir="$(IntermediateDir)"
      LogDir="$(LogOutputDir)"
      MSBuildPath="$(MSBuildx86Path)"
      MicroBuildCorePath="$(NuGetPackageRoot)microbuild.core\$(MicroBuildCorePackageVersion)" />
```

![image](https://user-images.githubusercontent.com/2696087/46748875-7288cb00-cc69-11e8-875c-0198a58cfe16.png)

**Comment by tmat** [comment]
Remove .dll from FileExtensionSignInfo

**Comment by natemcmaster** [comment]
Removing FileExtensionSignInfo doesn't help. I get a warning, but no error or warning about the .dll inside. This might be conflated with https://github.com/dotnet/arcade/issues/986

![image](https://user-images.githubusercontent.com/2696087/46752645-a0264200-cc72-11e8-88c0-be45ce932ad8.png)

**Comment by tmat** [comment]
Yes, we currently only report a warning. The [proposal](https://github.com/dotnet/arcade/issues/977#issuecomment-428613220) is to report an error instead for all signable files.
You can run with `/warnaserror` for now.

**Comment by tmat** [comment]
Oh, I see it's not warning for the dll. Hmm...

**Comment by tmat** [comment]
I can't see from [the source code](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/Configuration.cs#L143) why this doesn't work.

**Comment by natemcmaster** [comment]
We can't use `/warnaserror` because we haven't addressed all MSBuild warnings in our build system yet, and this warning doesn't have an error code on it (so we can't scope to `/warnaserror:CODE`.

**Comment by tmat** [comment]
This should be easy to fix in the sign tool. @JohnTortugo are you working on it now?

**Comment by JohnTortugo** [comment]
> This should be easy to fix in the sign tool. @JohnTortugo are you working on it now?

Yeap, I'm on it.

**Comment by JohnTortugo** [comment]
> @JohnTortugo
> Just realized - once we have the static list of signable extensions we can add a simple check (always, no toggle) [here](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/Configuration.cs#L203) and report an error if certificate is not assigned to a file whose extension is signable. We should also remove the warning for non-signable files. It adds no value since we know exactly what files need to be signed.
> 
> This simple check will allows us to enforce all signable files to be accounted for without the need to fully validate they we signed. We should definitely expand the validation beyond PE files, but we don't need to implement it for all signable extensions in order to get explicit list validation.

I'm working on this now.

**Comment by natemcmaster** [comment]
I don't think this is resolved. If anything, the behavior seems to have regressed. I just tried with 1.0.0-beta.18511.3

If I specify,

* `<FileExtensionSignInfo Include=".dll" />`
* `<FileSignInfo Include="Internal.AspNetCore.Analyzers.2.2.0-preview3-t000.nupkg" CertificateName="NuGet" />`

there is no error for .dll files which have no cert.

![image](https://user-images.githubusercontent.com/2696087/46835857-35553380-cd64-11e8-9a63-a75eb6604aef.png)
![image](https://user-images.githubusercontent.com/2696087/46835804-19519200-cd64-11e8-92df-79d4712cb75f.png)

If I remove `<FileExtensionSignInfo Include=".dll" />` and only include `FileSignInfo`, then .dll files are skipped, even if they are in `FileSignInfo`.

![image](https://user-images.githubusercontent.com/2696087/46836201-64b87000-cd65-11e8-9543-f58f36918152.png)

**Comment by JohnTortugo** [comment]
@natemcmaster this should include a `CertificateName` attribute:

`<FileExtensionSignInfo Include=".dll" />`

The tool misses a validation for the certificate name in that case..

**Comment by natemcmaster** [comment]
@JohnTortugo but wouldn't that mean every "*.dll" file is signed? If so, that's not an okay solution.

To clarify my scenario, I am expecting an error in the following scenario:

File inputs:
```
MyNupkg.nupkg
   lib/netstandard2.0/MyLib.dll
```

Sign tool inputs: 
```
Files to sign:
	MyNupkg.nupkg with 'NuGet' cert
Signable file extensions:
    .dll
Exclude files from signing:
    banana.txt
```

With these inputs, it should be an error because there is no certificate configured for `MyLib.dll`.

I believe the relationship between `FileSignInfo`, `ItemsToSign`, `StrongNameSignInfo`, and `FileSignExtensionInfo` is unclear, so if you can tell me how to define this behavior, I'll be happy. But as far as I can tell, this behavior cannot be defined.

**Comment by JohnTortugo** [comment]
@natemcmaster I got your point. I think I missed one change in my latest PR. 

> If I remove <FileExtensionSignInfo Include=".dll" /> and only include FileSignInfo, then .dll files are skipped, even if they are in FileSignInfo.

The error relates to this. The tool [still checks the signable extension](https://github.com/dotnet/arcade/blob/0f209fc718e920446ac1c85ab8b8d9fab68258d6/src/Microsoft.DotNet.SignTool/src/Configuration.cs#L336) on `FileExtensionsSignInfo` which is wrong.. it should be checking accordingly with MicroBuild supports.

After I fix this, if you only specify the signing for the NuGet package the result will be as you describe.

I'll write the fix and sync with you so I can test the new version of the tool in your branch.
