### ISSUE TITLE
`Windows.11.Amd64.CET(.Open)` queues need insider beta channel of Windows, registry change

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#9771]
From a request made by @janvorli and @eduardo-vp we need to update our On-Prem queues `Windows.11.Amd64.CET` and `Windows.11.Amd64.CET.Open` with CET-enabled Windows.

We need to:
- Join the Windows insiders beta channel to be on an insider build
- Have the following registry setting set:
    ```
    reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\corerun.exe" /v MitigationOptions /t REG_BINARY /d "0000000000000000000000000000001000" /f 
    ```

Connected email thread subject: "CET pipeline"

**Comment by janvorli** [comment]
The current queue should be updated. I believe that it was originally created for our purposes and noone else should be using it.

**Comment by ilyas1974** [comment]
@janvorli a few questions. 

- how often do you expect to the systems to be updated to a new insider build? 
- Will your team be requesting updating or is the expectation that the systems will be updated regularly for you? 
- Is there a good time frame for your team as to when we can perform these updates to reduce impact on your team? 
- Do you know if the registry setting listed above is persistent across insider preview updates (i.e. is this something that will need to be applied each time the system is updated or is it a "one and done" operation)?

**Comment by janvorli** [comment]
@ilyas1974 it should be ok to stay on the current insider build unless we discover any issues. And it is expected that Windows will have the necessary API in a stable release soon, so then we could just move to that. I am monitoring it, so I will ask you to move to non-insider Windows version once that happens.
The update can be done anytime. We don't use the queue yet.
I don't know if the registry setting is persistent across updates. I hope it is, but let me ask the right folks to figure out if that's really the case.

**Comment by ilyas1974** [comment]
I have created https://portal.microsofticm.com/imp/v3/incidents/details/316152269/home for our partner team to perform the requested updates.

**Comment by ilyas1974** [comment]
Systems have all been updated to the latest publicly available Insider Preview version of Windows.
