### ISSUE TITLE
Troubleshoot resources in osx.1015.amd64.open queue

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#9780]
There are several systems that require advance troubleshooting after the push in issue #8954. This issue is to track the systems that are still being worked on within the osx.1015.amd64.open queue.

**Comment by ilyas1974** [comment]
https://portal.microsofticm.com/imp/v3/incidents/details/314771415/home

**Comment by premun** [comment]
@ilyas1974 what kind of problems have we had? I started seeing an increased amount of iOS simulator failures in the OSX 10.15 queue in the last (2?) weeks.

Also are these older machines potentially slower than the MacMini's that were in the queue already?

**Comment by ilyas1974** [comment]
Systems are back online.
