### ISSUE TITLE
Rollout Scorer Broken

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9816]
We have not received any scorecard PRs since the rollout on 5/19.

**Comment by AlitzelMendez** [comment]
fixed in prod

**Comment by missymessa** [comment]
Rollout scorer still hasn't produced any score cards since 5/19. Reopening.

**Comment by AlitzelMendez** [comment]
we found what was going on I talked with @jonfortescue and he fixed it! :) I will let this open until tomorrow to see if this runs as normal on the scheduled time.

**Comment by garath** [comment]
@AlitzelMendez What was it?

**Comment by AlitzelMendez** [comment]
the rollout scorer was under the impression that:
Most recent rollout (arcade-services) is still in progress.

it wasn't producing the scores waiting for the rollout to conclude.

**Comment by garath** [comment]
@AlitzelMendez What did you do to resolve it? Cancel some broken build?

**Comment by AlitzelMendez** [comment]
no, @jonfortescue fixed it. I think he added a date on the table that holds that information, I don't remember the name of the table.  for Jon knows :D

**Comment by AlitzelMendez** [comment]
no, @jonfortescue fixed it. I think he added a date on the table that holds that information, I don't remember the name of the table.  for Jon knows :D

**Comment by AlitzelMendez** [comment]
closing as seems to be fixed: https://github.com/dotnet/arcade/pull/10252
