### ISSUE TITLE
[Workloads] Add support for side by side workload vsman files in VS

### ISSUE THREAD

**Issue by pjcollins** [dotnet/arcade#9820]
When .NET 7 ships, we would like for projects using optional workloads to be able to use both `net6.0-$(Platform)` and `net7.0-$(Platform)` target frameworks. 
The Android workload currently supports this by including [SDK packs for both .NET 6 and .NET 7](https://github.com/xamarin/xamarin-android/blob/df6c716e4168d14fe4d02cf955de5b6b081b9416/src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json#L21-L44) in the WorkloadManifest.json file, and the targets then import the correct SDK based on TargetFramework.  However, we do not rebuild the .NET 6 SDK pack on every .NET 7 workload build. We instead point to a stable version already published to NuGet.org.

To support this "out of the box" when using Visual Studio, I think we'll need to be able to insert multiple versions of optional workloads side by side into VS to some extent.

The [Android WorkloadManifest.json](https://github.com/xamarin/xamarin-android/blob/df6c716e4168d14fe4d02cf955de5b6b081b9416/src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json#L3-L31) currently declares one `android` workload. The arcade tooling will generate a VS component for this workload (full vsman can be found [here](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/.corext/Configs/dotnet-workloads-components.json&version=GBmain&line=10&lineEnd=11&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)):

    "id": "android",
    "version": "32.0.415.0",
    "type": "Component",

I believe that this component ID needs to be unique across VS? If we want to be able to support inserting multiple versions of these workloads into VS, we may need to update the tooling to add some version information to the VS component ID itself (e.g. `android.net7.0`).

Perhaps this is not needed if there is another solution in mind that would allow us to include partial .vsman files side by side, where only one manifest would declare the workload VS component?

----

Another potential solution I had considered for this would be to use workload pack groups. In this case we still only include one .vsman file in VS (which would describe our latest .NET 7 workload content). However, when we we went to package the workload pack group MSI we would also download the previously published .NET 6 SDK packs and put them in the .NET 7 workload pack group MSI. I have not done any testing with this and am sure how viable this solution would be however.

**Comment by joeloff** [comment]
the components intentionally match the workload ids becasue IPA relies on this to trigger when the design time build detects workloads that are not installed. The component IDs are also published publicly for extension developers to pull in as prerequisites for VSIX installations. Changing component IDs is considered a breaking change for VS and will break upgrades. We should talk about this in our Monday meeting

**Comment by pjcollins** [comment]
We may not need to change the component IDs (or have side by side manifests at all) if we find a way to "merge" relevant 6.0 manifest information into a 7.0 vsman, though I'm not sure of the best way to accomplish that while generating the 7.0 vsman.

**Comment by pjcollins** [comment]
@joeloff Do you have any more thoughts on what the right approach here may look like? @lewing I think this will also present an issue for you in your efforts to support net6.0 and net7.0 multitargeting in VS?

**Comment by joeloff** [comment]
It should be simple enough to change the tools to generate SxS, but there is a lot of code that expects the IDs to be predictable. For example, when `dotnet workload list` tries to determine if workloads were installed by VS, but also the design time stuff I previously mentioned. Also, we already shipped components with those IDs so they are now published in the VS catalog for 3rd party developers to depend on.

7.0 would be the place to introduce a breaking change to support this. I don't think this is something we can break in the middle of a servicing release. We're meeting on Wednesday so I can start the discussion on this.

It would likely impact other workloads, e.g. Maui that depends on mono pieces. If we support fully customizable IDs, and Maui takes a dependency and runtime changes how they name the workloads it won't be caught easily since we have two different builds.

**Comment by pjcollins** [comment]
We've found a way to resolve this by building swix projects in multiple batches, one for packs that will be used by multiple SDK bands, and one for everything else. I'm going to close this, though we still need to find a way to support multitargeting with workload pack groups without hitting NuGet size limitations.
