### ISSUE TITLE
Add pipeline ID to the pipeline output CSV

### ISSUE THREAD

**Issue by melotic** [dotnet/arcade#9824]
- [x] This issue is blocking. PR from filtering queue insights by pipelines
- [ ] This issue is causing unreasonable pain

Queue Insights needs to check pipelines, but comparing pipelines by names isn't always safe because the names of pipelines can change. Instead it would be better if we could compare by the Pipeline IDs.

**Comment by dkurepa** [comment]
The PR has been merged
