### ISSUE TITLE
[Release/6.0] Port xharness timeout changes 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#9828]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Port the following changes to release/6.0 
https://github.com/dotnet/arcade/commit/8e2ccde11b70936d8254669a4a74653c580a1340 and https://github.com/dotnet/arcade/commit/18adc5b47acce8bb03948baf578fca442d1029d4

**Comment by premun** [comment]
Hey Epsi,

Can you share a specific example of what's failing? There might be more we need to port around mobile devices to make it work more reliable.

I did actually ported the XHarness part of Helix SDK earlier already

**Comment by premun** [comment]
Ok, this just loooks like a backed up queue and a re-run should do the trick. The timeouts are not going to help in this case. For the failure in the first attempt, we could improve that by updating XHarness + porting over Helix SDK. I can have a look at that.

But seems like we will have to remove the Debian 9 queue from the unit tests as it will go away.

**Comment by premun** [comment]
PR here - #9841

**Comment by premun** [comment]
This was ported
