### ISSUE TITLE
Be able to determine which pipeline outputs are from the internal project

### ISSUE THREAD

**Issue by melotic** [dotnet/arcade#9829]
- [x] This issue is blocking. Queue Insights PR to filter by pipelines is blocked by this.
- [ ] This issue is causing unreasonable pain

Currently, we have no way to filter the records in pipeline outputs on which dnceng project it comes from, public or internal. Perhaps a column called 'project' containing public or internal could remedy this.

**Comment by garath** [comment]
Is this for the Matrix of Truth epic?

**Comment by melotic** [comment]
Yes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dkurepa** [comment]
pr: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/23805

**Comment by dkurepa** [comment]
The PR has been merged. We introduced a field called Project which describes what AzDo project the pipeline is a part of

**Comment by dkurepa** [comment]
The PR has been merged. We introduced a field called Project which describes what AzDo project the pipeline is a part of
