### ISSUE TITLE
AzureDevOpsTestAggregation_v2 has too much App Insights traces (will cause us to hit the data cap every day)

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9856]
As seen in [this AppInsights query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAyspSkxOLeaqUSjPSC1KVSjJzE0tLknMLVCwU0hMz9cwNsvQBEoWl%252BbmJhZlVqWCWBrxTpk5OakpwUC%252BpkJSpUJSZp4GXKOOgmmupo5Cck5%252BaUp8UH5Oql9ibirQiKLUvJTUIrAFyRmJRSUA7oRQjnkAAAA%253D), with yesterday's rollout the "AzureDevOpsTestAggregation_v2 " service is causing us to hit our 400 GB data cap in the dnceng app insights, entirely through traces(!):

![image](https://user-images.githubusercontent.com/7862010/176732106-04bdf11b-e2dd-4ed0-8c74-e8fb9a615fa0.png)

With 321 GB in the last 24 hours despite the rollout being < 24 hours ago, fabric:/Helix/AzureDevOpsTestAggregation_v2 is absolutely crushing all other outputs and will starve off our ability to see App Insights query if not addressed. 

@ChadNedzlek  / @missymessa  FYI; might be hotfix worthy?

**Comment by missymessa** [comment]
Acking, will consult with the v-team to see how we want to handle this.

**Comment by missymessa** [comment]
Update on hotfix plan: @AlitzelMendez is making a change to set our logging level on that service to be warnings and above (33 warnings and above in the last 24 hours, versus over 30k for everything). We'll get that hotfix rolled out and if it doesn't alleviate the load, we'll kill the service and reassess a longer term solution.

**Comment by missymessa** [comment]
PR for this: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/23830

**Comment by missymessa** [comment]
Hotfix deployed. Looks like we're not capturing any more HTTP response/request logs, and other logs are coming in for other services after the daily reset. Closing!

**Comment by missymessa** [comment]
The spike in teal does not look like AzureDevOpsTestAggregation_v2, which appears to be some kind of... grey?

**Comment by MattGal** [comment]
+1, I'd also point out that spike barely touches 30 MB on the Y axis unless you're dividing sum_BilledSize, so it's not interesting cost-wise or quota-wise.
