### ISSUE TITLE
XCode is not installed in the same location on every osx.1015.amd64.open machine (Xharness expects this)

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9859]
Seen trying to merge some PRs, likely related to recent reimaging of older machines to this queue?

[Sample log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-arcade-refs-pull-9849-merge-85472a70750a4f2ea6/System.Numerics.Vectors.Tests/1/console.34fda0b9.log): 

```
+ dotnet exec /tmp/helix/working/9E3208BC/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20505.1/tools/netcoreapp3.1/any/Microsoft.DotNet.XHarness.CLI.dll ios test --app=/tmp/helix/working/9E3208BC/w/A976096E/e/System.Numerics.Vectors.Tests.app --output-directory=/tmp/helix/working/9E3208BC/w/A976096E/uploads --targets=ios-simulator-64_13.5 --timeout=1800 --launch-timeout=1200 --xcode=/Applications/Xcode115.app -v
XHarness command issued: ios test --app=/tmp/helix/working/9E3208BC/w/A976096E/e/System.Numerics.Vectors.Tests.app --output-directory=/tmp/helix/working/9E3208BC/w/A976096E/uploads --targets=ios-simulator-64_13.5 --timeout=1800 --launch-timeout=1200 --xcode=/Applications/Xcode115.app -v
[15:09:20] fail: Failed to find Xcode root at /Applications/Xcode115.app
```
![image](https://user-images.githubusercontent.com/7862010/176761756-77de5c1a-3af0-469a-8854-f4811c62951c.png)

@premun may be able to comment where the --xcode arg comes from, as I couldn't immediately find the code that resolves this path.

Whichever is "correct', we should be consistent across all the machines in the pool.

**Comment by premun** [comment]
There was a change there, yeah, the installation script came from Xamarin and they had some second thoughts about this so I followed the suit. There were the 10.13/14 machines added in this queue so that's where this come from.

You can always use `xcode-select -p` to get the location of the currently active (default) Xcode. To my best knowledge, no one actually sets this manually but I can see in the code that if they do, this would cause problems.

@MattGal where is this coming from? Some release branch? If yes, then my other PR you have just approved should resolve this.

**Comment by premun** [comment]
Fix for **[main]** - https://github.com/dotnet/arcade/pull/9861

**Comment by premun** [comment]
I have re-installed the 10.15 queue so that Xcode's are in the new path `Xcode_11.5.app`. I have also removed 11.4 from the queue.

```PowerShell
osob_cli exec -c premun -P -q osx.1015.amd64.open `
	--work-item-count 120 `
	--timeout 01:00:00 `
	--payload D:\azdo\dotnet-helix-machines\artifacts\macos-xcode\macos-xcode.sh `
	--% "sudo rm -rf /Applications/Xcode11* && chmod +x ./macos-xcode.sh && ./macos-xcode.sh --version 11.5"
```

**Comment by premun** [comment]
Port to **[release/6.0]** - https://github.com/dotnet/arcade/pull/9862

**Comment by premun** [comment]
@MattGal I am OOF for the next two weeks. Can I ask you to merge the 2 PRs and close this please?

**Comment by premun** [comment]
Seems like this one is still needed: https://github.com/dotnet/arcade/pull/10051

**Comment by premun** [comment]
Backport to .NET 5.0 here:
https://github.com/dotnet/arcade/pull/10089
