### ISSUE TITLE
SignTool doesn't find certificate info for .nupkg files

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#986]
Sign tool does not appear to find certificate info for .nupkg files.

## Repro

Using Microsoft,DotNet,SignTool 1.0.0-beta.18507.1, pass in parameters like this:
```xml
    <ItemGroup>
      <_FileSignInfo Include="Microsoft.Extensions.ObjectPool.2.2.0-preview3-t000.nupkg" CertificateName="NuGet" />
      <_FileSignInfo Include="Microsoft.Extensions.ObjectPool.dll" CertificateName="Microsoft400" />
      <_ItemsToSign Include="C:\src\aspnet\Common\artifacts\build\Microsoft.Extensions.ObjectPool.2.2.0-preview3-t000.nupkg" />
    </ItemGroup>

    <Microsoft.DotNet.SignTool.SignToolTask
      DryRun="True"
      TestSign="False"
      ItemsToSign="@(_ItemsToSign)"
      FileSignInfo="@(_FileSignInfo)"
      StrongNameSignInfo=""
      FileExtensionSignInfo=".dll;.exe;.cab;.msi;.nupkg;.vsix;.jar;.ps1;.psd1;.psc1;.psm1"
      TempDir="$(IntermediateDir)"
      LogDir="$(LogOutputDir)"
      MSBuildPath="$(MSBuildx86Path)"
      MicroBuildCorePath="$(NuGetPackageRoot)microbuild.core\$(MicroBuildCorePackageVersion)" />
```

## Expected

Microsoft.Extensions.ObjectPool.2.2.0-preview3-t000.nupkg should be signed with the "NuGet" certificate

## Actual

The logs show that the .nupkg won't be signed. The task reports success without issuing a warning or error.
```
  Signing Round 0: 1 files to sign.
  Signing Round 1: 1 files to sign.
  Build artifacts signed and validated.
```

The binary log shows no certificate info was found for the .nupkg file.

![image](https://user-images.githubusercontent.com/2696087/46749594-f0010b00-cc6a-11e8-8598-71c1466a9fd3.png)

**Comment by tmat** [comment]
Try setting `FileExtensionSignInfo` to "".  As it is specified it means all the listed extensions have no certificate. There is still a bug in the tool - this should have been overridden by `FileSignInfo` entry.

**Comment by tmat** [comment]
@JohnTortugo Turns out we do not look up `FileSignInfo` for non-PE files currently :-|.
This should be done for non-PE files as well: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.SignTool/src/Configuration.cs#L175

**Comment by natemcmaster** [comment]
Removing `FileExtensionSignInfo` produces a warning, but it doesn't appear signing happens:

>  warning : Couldn't determine signing information for this file: C:\src\aspnet\Common\artifacts\build\Microsoft.Extensions.ObjectPool.2.2.0-preview3-t000.nupkg

![image](https://user-images.githubusercontent.com/2696087/46752843-10cd5e80-cc73-11e8-88da-c15eb0c73b98.png)
