### ISSUE TITLE
Missing / mangled log files under Azure DevOps 'Attachment' section

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#9865]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Reported by @hoyosjs 

Log files used to be available in attachment section (like [Pipelines - Run 20220621.9 (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=1838351&view=ms.vss-test-web.build-test-results-tab&runId=48568740&resultId=100361&paneView=attachments) but you can't see them after
[Pipelines - Run 20220621.7 (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=1837488&view=ms.vss-test-web.build-test-results-tab&runId=48557112&resultId=100349&paneView=attachments))

**Comment by ChadNedzlek** [comment]
Given that the build that is referenced is pointing to a commit messing with the STDOUT of tests, and we haven't changed anything in this area in a long time (certainly not in the time frame of this issue), it's because the repository stopped writing output.

I'm going to see if I can find a test in a different repository that has output to verify.

**Comment by ChadNedzlek** [comment]
It does look like arcade is missing it on "Trx.Fail1"... so we definitely broke something here... a month ago. Taking a look.

**Comment by ChadNedzlek** [comment]
This looks to be a problem with AzDO? The site _says_ it's a 9K file. But when I download it, it's empty. Also, I don't see any of our code mangling the name to "TestResult_{GUID}" anywhere. I'm going to open an IcM

**Comment by ChadNedzlek** [comment]
I also don't see any changes near this time frame in either piece of our code that could account for this...

**Comment by ChadNedzlek** [comment]
Yup, this is definitely a Azure DevOps change.  I made a raw test attachment upload, and it's not returning the contents. It's both messing with the name (prepending the TestResult_{GUID}_ to the name), and failing to save the contents, though the "size" reported is correct.  I'm opening an IcM

**Comment by missymessa** [comment]
@ChadNedzlek is this going to affect the test reporting functionality, too?

**Comment by ChadNedzlek** [comment]
I don't think so. It seems to only affect _test_ attachments.  The run attachments are presumably fine (otherwise we'd be getting "zero" passed tests, which we don't appear to be).  It's been broken since 6/21, so we'd have noticed by now if that were the case.

**Comment by ChadNedzlek** [comment]
Current estimate for when this change will be live is approximately 2 weeks.

**Comment by ilyas1974** [comment]
@ChadNedzlek is there an update on this issue?

**Comment by ilyas1974** [comment]
@ChadNedzlek Just wanted to follow up and see if Azure DevOps was able to resolve this issue for us as promised?

**Comment by hoyosjs** [comment]
We still don't see any attachments (now we see garbage instead of a blank attachment).

**Comment by ChadNedzlek** [comment]
It's base64 encoded of the original data.  So sounds like we need another IcM.

**Comment by ChadNedzlek** [comment]
I moved this out of tracking and unassigned myself, since we're going to need another IcM to fix the new broken behavior.

**Comment by ChadNedzlek** [comment]
Or we can reactivate the old one? The name is still messed up, after all.

**Comment by MattGal** [comment]
I am opening a fresh IcM.

**Comment by MattGal** [comment]
First IcM: https://portal.microsofticm.com/imp/v3/incidents/details/318952542/home
New IcM: https://portal.microsofticm.com/imp/v3/incidents/details/323269195/home

**Comment by MattGal** [comment]
TFS Item from first IcM: https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1967818

**Comment by MattGal** [comment]
Update: A new fix is supposedly deployed and should roll out by end of week.

**Comment by garath** [comment]
Reopening. This fix was rolled-back over the weekend due to dotnet/arcade#10358. 

[ICM 318952542](https://portal.microsofticm.com/imp/v3/incidents/details/318952542/home) has been reactivated.

**Comment by garath** [comment]
ICM Update: Fix expected in M209, which, if I read the patterns correctly, will start rolling out next week.

**Comment by garath** [comment]
Fix is rolled out. Test team will complete a retrospective.
