### ISSUE TITLE
AzureDevOpsTestAggregation_v2 Noise

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9872]
Errors are happening fairly often in the AzureDevOpsTestAggregation_v2 service (shown on our grafana dashboard https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/buildAnalysis/build-analysis?orgId=1&from=now-12h&to=now)

```
System.Net.Sockets.SocketException at Helix.Internal.Reporting.Statistics.Providers.TestAggregatorProvider+<GetPassingTestInstances>d__12.MoveNext
```
and 
```
System.Net.Sockets.SocketException at Helix.Internal.Reporting.Statistics.Providers.TestAggregatorProvider+<GetPassingTestListsForPartition>d__11.MoveNext
```

Error: `An error occurred while sending the request.`

Currently, we're having the service run every 5 minutes in order to retry the failures, but this is still causing noise in our logs and monitoring issues, so we should come up with a better solution to handle these.

**Comment by missymessa** [comment]
Latest noise: 

```
Azure.RequestFailedException at Azure.Storage.Queues.QueueRestClient+MessageId.DeleteAsync_CreateResponse
```

Outer message: 
```
The specified message does not exist. RequestId:b7b08470-3003-0081-2629-9503c3000000 Time:2022-07-11T13:24:11.3983553Z Status: 404 (The specified message does not exist.) ErrorCode: MessageNotFound Headers: Server: Windows-Azure-Queue/1.0,Microsoft-HTTPAPI/2.0 x-ms-request-id: b7b08470-3003-0081-2629-9503c3000000 x-ms-version: 2018-11-09 x-ms-error-code: MessageNotFound Date: Mon, 11 Jul 2022 13:24:11 GMT Content-Length: 221 Content-Type: application/xml
```

**Comment by markwilkie** [comment]
Has this indeed been fixed?

**Comment by riarenas** [comment]
According to the [app Insights logs](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAzWOSwrCQBBE956iyQH6Di4EsxExXmAyKSaNmQ%252FdjSbg4c3CrKp41IPCGtFcarHTlz4zFNS0jgtyP9EcjLphM0fmG5yHGl9w%252B%252BflUCk4XbHIyn1xaAkLP9CqupTEgwcXc4nGd61vmaDGT5ifU1Kk4FUP3u0Xqu6Fxo1c8j4KudEEiz9T9UJApwAAAA%253D%253D/timespan/PT4H), this is still happening

**Comment by AlitzelMendez** [comment]
this is still happening, and I created this issue: https://github.com/dotnet/arcade/issues/10807

**Comment by AlitzelMendez** [comment]
https://github.com/dotnet/arcade/issues/10807 wasn't related to this. 

This error is still happening.

**Comment by ChadNedzlek** [comment]
We can create a retry-based HttpHandler for these. It's not too hard to use IHttpClientFactory and write a quick DelegatingHandler that does retries on disconnects.

**Comment by missymessa** [comment]
Looks like the noise has been eliminated. Closing
