### ISSUE TITLE
Figure what to do with FabricBot for eng services repos

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#9884]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Fabric-bot is moving to a config-as-code mode and in the process opened the following PRs in our repos:

* arcade-services: https://github.com/dotnet/arcade-services/pull/1935
* arcade: https://github.com/dotnet/arcade/pull/9830

Looking at the existing configuration, it looks like all we really use fabric bot is for the auto-merge functionality when adding the auto-merge label, but that functionality is now part of GitHub so it seems like a good opportunity to examine our usage of fabric bot to see if we just want to disable it instead of checking in the configuration files

**Comment by ChadNedzlek** [comment]
I'm down with the "turn it off" option too. Yet another file that might let people run actions against our repository doesn't seem worth having enabled... just because.  config-as-code introduces a pile of... interesting... security considerations that I'd rather just avoid by not having this file.

**Comment by garath** [comment]
FabricBot has been disabled, so closing this issue.
