### ISSUE TITLE
[DDFUN] Reimage 7 OSX 10.15 machines with low disk space

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9890]
The following machines all have < 30 GB free space while every other agent has 300+ GB free.  This leads to low disk space issues.  The machines should be either reimaged to use the 1 TB onboard disk or, if unavailable, decommissioned.

dci-mac-build-003
dci-mac-build-004
dci-mac-build-012
dci-mac-build-045
dci-mac-build-057
dci-mac-build-058
dci-mac-build-140

Tracking IcM: https://portal.microsofticm.com/imp/v3/incidents/details/318888972/home

**Comment by kasperk81** [comment]
is the underlying issue that "cleanup" routine unable to calculate the disk size correctly? or is there no cleanup routine employed on those machine?

**Comment by MattGal** [comment]
@kasperk81 ... what he said. As long as a helix work item stays within its temp directory and work directory, we will automatically clean up excess logs, dumps, and payloads indefinitely; just need to have enough buffer space to handle big and crashy work items.

**Comment by ilyas1974** [comment]
Systems have been reconfigured.
