### ISSUE TITLE
New Helix Queue for Perf Team

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#9894]
The performance team would like the following helix queue created. 

Windows11.Arm64.Ampere.VM.Perf

Please use the windows.11.arm64 queue as the base for this request. The systems that will be added to this queue are physical systems and DDFUN will take care of making sure they are added properly.

**Comment by jonfortescue** [comment]
PR in [here](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/23914).
