### ISSUE TITLE
[publishing] Improve error messaging when a channel is not set up for publishing

### ISSUE THREAD

**Issue by ghost** [dotnet/arcade#9908]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain
This causes customer questions.

Right now, when someone attempts to publish a build to a channel that doesn't have any publishing infrastructure set up, their publishing build will show an error like this:

```
error : Value cannot be null. (Parameter 'first')
error :    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
error :    at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
error :    at Microsoft.DotNet.Build.Tasks.Feed.Model.TargetChannelConfig.Equals(Object other) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/TargetChannelConfig.cs:line 85
 error :    at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestV3.ExecuteAsync() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs:line 107
error : Value cannot be null. (Parameter 'first')
```

This makes the problems hard to diagnose for users, and we should try to make the error mention that the channel is missing from those that are configured for publishing, which would at least save us some investigation time whenever customers ask what's going on with their builds.

**Comment by garath** [comment]
Triage moved this to FR, Discussion was around finding the code right before this and adding a `ArgumentNullException.ThrowIfNull()`.
