### ISSUE TITLE
Add Support Data for .NET 7

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#9911]
As the PM team has started to post support data for .NET 7 (https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md), we should also incorporate this information in to the Matrix of Truth. This would also be a good opportunity to document the process for how we want to data added/formatted.

**Comment by dkurepa** [comment]
PR that adds .NET 7 and 8 fields to the outputs: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/24174
When this PR is merged, all we'll have to do is update os_definitions.json with the .NET 7 support

**Comment by dkurepa** [comment]
The PR has been merged. Now all that's left is to add .NET 7 support to the os_definitions.json

**Comment by dkurepa** [comment]
Part of this issue is also to add docs on how to add support for an existing .NET version and how to onboard a new .NET version to the Matrix of Truth

**Comment by dkurepa** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/24346

**Comment by ilyas1974** [comment]
Information has been added to the source data and incorporated into the reports.
