### ISSUE TITLE
[Known Issues] Support blocking-clean-ci label for known issues

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#9914]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

There is automation that uses **blocking-clean-ci** label to create tracking issues. We want to include **blocking-clean-ci** as a supported label for known issues

**Comment by hoyosjs** [comment]
cc: @agocke

**Comment by riarenas** [comment]
Why this specific label? isn't this a dotnet/runtime specific label? are we going to adopt that across the entire org?

**Comment by riarenas** [comment]
aaah I wasn't aware this was integrated with runfo. I think that makes sense then

**Comment by agocke** [comment]
> It is specific to runfo, it is the label is uses to create issues. As far as I know many repos/teams use runfo

I don't think it is, actually, it's just been the standard in `runtime` for a while and we have a specific pattern we use for inner/outer loop division where we have `blocking-clean-ci` for failing in PR/rolling builds, and we have `blocking-outerloop` and other `blocking-` labels for other queues. We could switch to the alternative label, but then it wouldn't be similar to our other labels.

**Comment by AlitzelMendez** [comment]
This has been shipped. Now we can use **blocking-clean-ci** label for the known issues feature. 
if you have any question @hoyosjs / @agocke let me know!
