### ISSUE TITLE
Matrix of Truth Report Updates 

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#9917]
After sharing the reports with the CI Council, I received some feedback. 

- ~~Add ability to search by Queue Name in pipeline to queue report~~ Complete
- ~~Add branch to table view in pipeline to queue report~~ Complete
- ~~Change the default sort in the pipeline to queue report to order by Repository~~
- ~~Create a new tab that details the docker image being used by the reports - not just if an image is being used~~

**Comment by dougbu** [comment]
I made another suggestion about aligning the column order w/ the control order in the .NET Environment Data tab.

> Create a new tab that details the docker &hellip;

A drilldown from the existing table or a sub table would work as well. Main point was about making the image information available.

**Comment by ilyas1974** [comment]
I have completed the requested changes from CI Council as well as the drill throughs. There are a few pending issues that are in progress for one of the reports (https://msit.powerbi.com/groups/de8c4cb8-b06d-4af8-8609-3182bb4bdc7c/reports/8b49a89c-7aea-4fdb-95d5-547a9fe5d734/ReportSectiona9f522f637357d3b547e)

**Comment by ilyas1974** [comment]
Issues waiting on to be addressed before I can proceed
arcade #9911
arcade #10107
arcade #10110

**Comment by ilyas1974** [comment]
Requested changes have been made and the reports have been updated.
