### ISSUE TITLE
Change helix-machines github issue validation to a separate check rather than breaking the PR build.

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#9937]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain

One of the thousand little cuts that make this repo uncomfortable to work on.

When a PR to helix-machines is missing a github issue in its description, the PR validation build breaks.

We should change this to a separate check that blocks the PR, while still letting devs make progress in PR validation.

**Comment by riarenas** [comment]
A very cheap fix would be to make this step run as an agentless job so that the frustration of the build immediately failing due to a missing issue link after waiting for 40 minutes for a build machine is lessened.

**Comment by adiaaida** [comment]
100% agree here

**Comment by MattGal** [comment]
Grabbing this one for ops.

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/24266

**Comment by MattGal** [comment]
PR is merged, nothing to roll out, closing.
