### ISSUE TITLE
Tracking Merge-on-red reasons

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9954]
Product teams want a way to track reasons for why a PR was merged on red. 

Initial thoughts regarding the mechanics behind this: 
- Needs to be consistent across all product repos that wish to adopt this functionality
- Should be easy to "mark" a PR with this information

A couple options here: 
- a formatted comment to look for in the PR. This would be easy to do, however, also easy for folks to mess up the formatting, which may make the comment unsearchable. 
- a label, preferably a prefix on a label, that can be used to denote "reason for merge-on-red" that we can search for across all repos. 

**Missy's Proposal** :)

Product repos implement labels that begin with `merged-on-red-` and they can fill in their own blank after that. For reporting purposes, we can look for PRs that contain labels that begin with that prefix (or without, even, if PRs are still be merged-on-red without the label for auditing purposes).

**Comment by jkotas** [comment]
Yes, I think it should be labels. The set of labels to use for this has to be more opinionated. We should only need two labels for what we are trying to measure currently:

- merge-on-red where all failures have been identified as known issues. This label should be set automatically by the build analysis automation. No human intervention required. These merge-on-red are "expected".

- merge-on-red where some of the failures are not known issues. Somebody (the test monitor?) should be responsible for understanding these and working together with the eng team to turning them into known issues. Ideally, the number of these will be zero.

**Comment by jkotas** [comment]
I think that the merge-on-red labels need to be assigned automatically by the build analysis, so there is no manual work required to maintain them and it is done consistently. It means that they cannot be just any labels.

If a repo owners want to manually tag a bunch of issues with a label (it can be any label - not just merge-on-red) using some criteria and track how many issues with this label they have, they can do that today.

**Comment by AlitzelMendez** [comment]
do we need a label, or can we have just report?  power BI? 
we could have a report of the status of a build when it was merged without the need of a label, and on the report specify the two scenarios mentioned above: 
- merge-on-red where all failures have been identified as known issues.
- merge-on-red where some of the failures are not known issues

**Comment by jkotas** [comment]
The label allows anybody to use the regular github issue queries, narrow the search by additional conditions, etc. The label can be manually corrected when the automation gets it wrong.

Power BI report is less flexible and you have to remember where to find it.

**Comment by missymessa** [comment]
Migrating to the "Improve Dev WF by improving PR blocking with Known Issues" epic

**Comment by missymessa** [comment]
I think this was covered in the "Merge on Green" effort in collaboration with the runtime team.
