### ISSUE TITLE
AzDo Issue #2968

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#9965]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

[Azure Boards WorkItem](https://dev.azure.com/dnceng/internal/_workitems/edit/2968)

**Comment by adiaaida** [comment]
(Created manually because the issue wasn't put in the correct area path on creation)

**Comment by ilyas1974** [comment]
Duplicate of what is already in scope for the epic this issue refers to.
