### ISSUE TITLE
Helix machines needs to move to net6.0 and Central Package Version Management

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#9966]
We had a big kerfuffle trying just to use CPVM, and I think part of that is because we ended up with a mismash of netcore3.1 assemblies and net6.0 assemblies (via dependency upgrades).

We need to make the migration and do both of these bad boys at once so that we have a slightly more management dependency management option.

**Comment by MattGal** [comment]
First prod rollout with these changes completed today. Aside from the tail of https://github.com/dotnet/arcade/issues/12264 I think this is ready to close.

**Comment by Chrisboh** [comment]
This succeeded so I am closing.  Please reopen if anything else needs to happen.
