### ISSUE TITLE
Test Reporting: Split Passing Aggregates Based on BuildReason

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9999]
Per discussion in the v-team channel with @dougbu, folks would find it useful to be able to limit passing aggregates based on BuildReason (e.g. BatchedCI, PullRequest, et cetera).

**Comment by ChadNedzlek** [comment]
Should be super easy.  Just need to add "BuildReason" to the "RunSignature" class and then write that down in "KustoReportDataStore.ReportTestAnalysisAsync".

**Comment by missymessa** [comment]
We need to fix our data issues before we can tackle this. (As well as our Kusto queries that are using up a lot of resources).

**Comment by ChadNedzlek** [comment]
True... if we are already using too many resources, doubling our usage would probably be... bad. :-)

**Comment by missymessa** [comment]
Closing due to budget issues.
